azerothcore/azerothcore-wotlk

data/sql/updates/pending_db_world/rev_1651846511304338500.sql
src/server/scripts/Northrend/zone_icecrown.cpp

-  Fix: Raidus 3yards
-  Fix: event capture gryphon
-  Fix: Gravity and Hover 
-  Fix: added condition and also animation
- was performed windows 7 64bits. Not a single error was found and it is Functional
1. quest add 12814
2. tele icecrown
3. go to the zone indicated by the map and test …

fix(Scripts/Quest): improved You'll Need a Gryphon

---

data/sql/updates/pending_db_world/rev_1651498473518668825.sql

-  Set all target types correctly (they had 0)
-  Fixed timers on Gurubashi berserker following several classic youtube videos and comments as timers from Trinitycore/Vmangos were all incorrect.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3455
- Closes https://github.com/chromiecraft/chromiecraft/issues/3453
- Closes https://github.com/chromiecraft/chromiecraft/issues/3452
- Closes https://github.com/chromiecraft/chromiecraft/issues/3451
https://tbc.wowhead.com/npc=11352/gurubashi-berserker#comments;mode:n
https://www.youtube.com/watch?v=8uXBvAi40hY&t=8192s
-  Tested
1. Go to the four creatures in the linked post and see if they are using their abilities.
[x] none …

Fix(DB/SAI): Zul'Gurub trash monsters should cast their abilities

---

src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.h

Fixes #5980
Fixes #9314
- Closes #5980
- Closes #9314
- Closes https://github.com/chromiecraft/chromiecraft/issues/677
- Closes https://github.com/chromiecraft/chromiecraft/issues/2381
Enter Scarlet Monastery Cathedral
Progress until the closed door
Have any mob near the door and have it feared (warlock's or warrior's spells, or low hp)
Repeat from 3 until a mob's random fear movement makes it walk through the door
Join WSG battleground
Fear an enemy next to the line-of-sight object in the middle of the battleground (more info: [here](https://github.com/chromiecraft/chromiecraft/issues/677)) …

fix(Core/Movement: Rewritten fleeing movement generator. Source: TrinityCore.

---

src/server/game/Movement/MotionMaster.cpp
src/server/game/Movement/MotionMaster.h
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11653
- 
- 
1.
2.
3. …

Fix(scripts/spells) charge Auto attack

---

src/server/game/Spells/Spell.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix (core): Build Fix

---

src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp

Fixing it again. Something regressed.
-  fix client crash with dk starter zone quest https://www.wowhead.com/quest=12641/death-comes-from-on-high
-  sniif used for rescripting: https://github.com/MDic-s-Preservation-Archives/Sniff-Collective/blob/main/9.%20SL/DK%20Starter%20zone/Human%20DK/dump_9.1.5.41079_2021-11-19_10-10-00.7z
- Reworked to work with azerothcore.
Cherry Picked from:
https://github.com/TrinityCore/TrinityCore/commit/eccb0ed3dac67a7463cc5c1ff5cf2cd3919e7a25
Co-Authored-By: vincent-micheal  [trinity.michael_vincent@gmx.eu](mailto:trinity.michael_vincent@gmx.eu)
https://github.com/TrinityCore/TrinityCore/commit/60763fc5e2d7bb32150d8e03bfd0fb3e7cb890f3
Co-Authored-By: Ovahlord  [18347559+Ovahlord@users.noreply.github.com](mailto:18347559+Ovahlord@users.noreply.github.com)
- …

fix (core\crash): fix client crash dk starter

---

src/server/game/Handlers/MovementHandler.cpp

Anticheat Helper for knock back
-  add additional helper spot in knock back for anticheat support
- Closes 
- 
- 
1.
2.
3. …

add (core): Additional Helper

---

src/server/scripts/World/npc_stave_of_ancients.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/World): fix nullptr crash

---

data/sql/updates/pending_db_world/rev_1652543986104470300.sql
src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #11728
- Closes #11728
`.quest a 13010`
`.go c id 30105`
talk King Jokkum …

fix(DB/Quest): Fixed quest "Krolmir, Hammer of Storms".

---

data/sql/updates/pending_db_world/rev_1652734139275905167.sql
src/server/scripts/EasternKingdoms/zone_eversong_woods.cpp

-  Script Eversong Partygoers
Sniff
- Compiles.
1. .go c 59444
2. observe

Fix(Script/SAI/Misc) Eversong Partygoers

---

data/sql/updates/pending_db_world/rev_1652603039648242300.sql

The other Sound columns are empty for that creature by default
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6740
- Tested in-game (with sound)
1. Turn sound on
2. .cast 21688
3. Notice there is no more "Die, mortals" voice line while the mine is arming …

fix(DB/Creature): Goblin Land Mine playing Hakkar voiceline 

---

data/sql/updates/pending_db_world/rev_1652480165040490600.sql

-  Cast "Call Alliance Deserter" on accept and Valiance Keep Officer set immunity flags
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2952
https://www.youtube.com/watch?v=mSvXowqzhMw Quest is unchanged from wrath to current expansion
- Test in-game
You'll need to complete the previous quest 
1. .go c 125384
2. .q a 11709 (quest to unlock current one)
3. Turn in 11709 (Nork Bloodfrenzy's Charge
4. Accept 11711 from Warden Nork Bloodfrenzy 
5. Alliance Deserter should spawn
6. Go to the requested position, with the prisoner
7. After using the Flare Gun to start the RP, Valiance Keep Office should be unattackable. …

fix(DB/Quest): Coward Delivery... Under 30 Minutes or it's Free

---

data/sql/updates/pending_db_world/rev_1652175741735714800.sql
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp

If anyone has any video source that SAY_SPECIAL_1 and SAY_SPECIAL_3 were ever used, let me know.
- [SQL] Removed duplicates from creature_text & added the missing (but unused) text
- [SQL] Added trigger creature flag to Thorim Trap Bunny 33054 (guid 136059) & 33725 (guid 136816) (they were visible before)
- Remove hardcoded voice lines
- Removed all SAY_SPECIAL except "Do not hold back! Destroy them!" (Look source for more info)
- Fixed Chest orientation
- Encounter now starts when ALL adds are killed (previously started on 5 out of 6) 
- Added player filter on KilledUnit
- Closes none
*Source for SAY_SPECIAL "Do not hold Back! Destroy them!" on Runic Colossus kill - https://youtu.be/ifSof148-4Y?t=102https://youtu.be/TwVPCU5c00Q?t=192 (Note, after looking over 30 Thorim videos, this line …

fix(Script/Ulduar): Thorim - misc fixes & hardcode removal

---

data/sql/updates/pending_db_world/rev_1652348913017613700.sql
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp

Prat of https://github.com/azerothcore/azerothcore-wotlk/projects/15
All of Mimiron's text and computer are already in the DB.
-  [SQL] Change model of Computer to fix empty broadcast text - 
- [SQL] Converted Plasma Blast emote into creature_text and assigned it's proper sound ID
-  Remove hardcoded text
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4155
Source for computer model ID: https://www.wowhead.com/npc=34143/computer
Plasma Blast sound - https://youtu.be/X3ZkgnmftJQ?t=53 
[(additionally linked here)](https://db.rising-gods.de/?sound=15800)
- Tested in-game (with sound)
1. .go c 137630
2. Pull (with sound enabled) both normal and hardmode
3. Can see Computer's yell text in chat. (previously was blank) …

fix(Script/Ulduar): Mimiron - remove hardcode text and fix Computer broadcast.

---

data/sql/updates/pending_db_world/rev_1652715563226780200.sql

Unsure which table to trust, if its either "!" or "." at the end of the sentence, trusting broadcast_text (which is supposed to be all sniffed?) for now.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8628
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9820
1. .go c id 11680
2. Pull/spawn a hostile creature, let the scout(s) attack | Or go .gm on and spam aggro to trigger the voice line
3. when they attack and the message shows (15% chance) they should say the correct message and not show an error in the console …

fix(DB/Creature): Horde Scout - console SmartScript::ProcessAction errors

---

src/server/scripts/Northrend/zone_dragonblight.cpp

All of the creature_text is already in the db
-  Added the 20s period to jump and it's text
-  Added the fail text
- Added quest fail (it doesn't actually fail, just shows it in the chat if you jump too early)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5669
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4167 
[(There is still hardcoded text in zone_dragonblight, entirety of the hourglass quest event is hardcoded)](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/zone_dragonblight.cpp#L301-L469)
https://www.youtube.com/watch?v=Ef-tK5JifJg https://youtu.be/jZBF9FExel8?t=91
https://wowpedia.fandom.com/wiki/Conversing_With_the_Depths#Notes
https://www.wowhead.com/quest=12032/conversing-with-the-depths#comments
- …

fix(Script/Quest): Conversing With the Depths adjustments & zone_dragonblight move to db from hardcode

---

src/server/scripts/Northrend/zone_dalaran.cpp

Quest is a bit buggy, there was an open issue somewhere.
Gossip menu and it's options are properly linked in DB and to the creature.
-  
-  
- Completes zone_dalaran having hardcoded texts
- 
1. .go c id 36856
2. .q add 20438 -- alliance
3. .q add 24556 -- horde
4. Check the gossip  …

fix(Script/Quest): A Suitable Disguise - Move zone_dalaran to DB from hardcode

---

src/tools/vmap4_extractor/vmapexport.cpp
src/tools/vmap4_extractor/wmo.cpp
src/tools/vmap4_extractor/wmo.h

-  Add attribute `[[maybe_unused]]` for function `WMOGroup::ConvertToVMAPGroupWmo`

fix(Tools/Vmap): correct build

---

data/sql/updates/pending_db_world/rev_1653127299704263300.sql

Fixes #11809
- Closes #11809
`.quest a 12536`
talk `Zepik the Gorloc Hunter`
Crocodile moves to its final destination. …

fix(DB/Quest): Fixed Captive Crocolisk not moving to final destination.

---

data/sql/updates/pending_db_world/rev_1652526320425217900.sql

-  Fix animation
-  Remove all auras before mounting
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5926
1. get quest 12255(horde get quest 12259)
2. .go c 110538
3. cast a Mount
4. talk with Flamebringer
5. Being mounted should no longer prevent you from mounting the creature …

fix(DB/Creature): Flamebringer spawning indefinitely 

---

data/sql/updates/pending_db_world/rev_1652563880706540800.sql

Unsure if this is the proper way to do this, but it works.
Additionally, **I don't know how to stop giving EXP through SAI,** without messing with the spell's properties.
-  Set dynamicflag 128 on spell hit and despawn corpse after 2s
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6129
https://www.youtube.com/watch?v=DaMBxAdcslw - Corpse stays for 1-2 seconds
1. .go c 5126 - and look for the NPC in the rooms around (multiple spawns) /tar Commander
2. Bring him to low HP: 1-120 Hp. / .damage 1050 
3. Let him finish his cast
4. Notice he is unlootable and corpse despawns
5. Kill him without letting the the cast to go off, he is lootable  …

fix(DB/Creature): Commander Felstrom Infinite Loot Farm

---

data/sql/updates/pending_db_world/rev_1651751512749712800.sql

-  Added the english and french text for the item Rune-Inscribed Parchment.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11583
- Closes https://github.com/chromiecraft/chromiecraft/issues/3440
https://classic.wowhead.com/item=9568/rune-inscribed-parchment for the english text
https://fr.classic.wowhead.com/item=9568/parchemin-runique for the french text
- Create lvl 1 shaman
- .levelup 1
- go to gornek, in the cave
- Pick the mission cutting teeth.
- .complete quest 788
- get the rune-inscribed-parchment  quest
- open the letter and check the content
1. Create lvl 1 shaman
2. levelup 1
3. go to gornek, in the cave
4.   Pick the mission cutting teeth.
5. .complete quest 788
6. get the rune-inscribed-parchment  quest
7. open the letter and check the content
- I dont have …

fix(DB/SAI): updated text for Rune-Inscribed Parchment

---

src/cmake/googletest-download.cmake

-  fix temporarily the issue of googletest using my branch
- we'll change back the repository to the official googletest when this PR https://github.com/google/googletest/pull/3859 will be merged
- all the builds are failing for googletest

fix: temporary workaround for the googletest issue

---

data/sql/updates/pending_db_world/rev_1653731455835127800.sql

Fixes #11842
- Closes #11842
- Not tested.

fix(DB): Crashfix.

---

data/sql/updates/pending_db_world/rev_1653830830812451556.sql

- Redo existing quest turn in script.
- Existing script was horrible with just a spell cast and text.
- This script is 100% blizzlike.
Sniff
- Inserts properly
1. .go c 56398
2. .add quest 8891
3. turn in quest

fix(Quest/SAI/Equip) Quest 8891 "Abandoned Investigations"

---

src/server/game/Entities/Unit/Unit.cpp

Fixes #11880
- Closes #11880
- Closes https://github.com/chromiecraft/chromiecraft/issues/3549
- Not tested.
1. Enter Blackwing Lair.
2. Engage Razorgore the Untamed.
3. Try to use Orb of Domination …

fix(Core/Units): Clear any movement on charm - vol. 2.

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp

Fixes #11760
- Closes #11760
- Not tested.
Engage Hakkar and look if he cast the spell …

fix(Scripts/ZulGurub): Re-implemented Hakkar's Insanity.

---

src/server/scripts/Northrend/zone_howling_fjord.cpp
src/server/scripts/Northrend/zone_sholazar_basin.cpp
src/server/scripts/Northrend/zone_wintergrasp.cpp

Everything is in DB and it's properly linked
-  Same minor changes to Your Inner Turmoil to be more blizzlike
-  Added missing text to A Hero's Burden
- Still At It barrel is lootable only once, before it never despawned and you could loot it 100 times
- https://github.com/azerothcore/azerothcore-wotlk/issues/4165
- zone_wintergrasp -> to DB
- zone_howling_fjord -> to DB
https://youtu.be/irJrrqQpd_Y?t=98 - A Hero's Burden
https://youtu.be/RW_U8aAA8wI?t=114 - Your Inner Turmoil
- Tested all in-game 
**Preferably with non English client**
>.q a 11322 -- Alliance
.q a 11317 -- Horde
.go xyz 3027 -5088 723 571
---
>.bf timer 1 50 (If WG battle isn't within 15m)
speak with any npc that can queue you for WG
---
>.q add 12634
.npc add 28604
---
>.q add 12645
.go c id 28568
---
>.q add 12621
.go …

fix(Script/Core): Move hardcoded text to DB

---

data/sql/updates/pending_db_world/rev_1653602942462997500.sql

Forgot to add it in https://github.com/azerothcore/azerothcore-wotlk/pull/11725
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Leviathan Mk II's Plasma Blast BroadcastTextId

---

src/server/game/Entities/Player/PlayerMisc.cpp
src/server/game/Groups/Group.cpp
src/server/game/Groups/Group.h
src/server/game/Instances/InstanceSaveMgr.cpp
src/server/game/Instances/InstanceSaveMgr.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

 Update CHAR_DELETE_INSTANCE_SAVED_DATA

---

data/sql/updates/pending_db_world/rev_1653959480980961369.sql

-  Add missing gossip option conditions
- Closes #11913
TC
- Requires testing
1. .go c 35194
2. complete quest 5535 & 5536

fix (Conditions): Loh'atu gossip

---

src/server/scripts/Spells/spell_paladin.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/11931
- 
- 
1.
2.
3. …

Fix(scripts/paladin) infusion of light proc

---

data/sql/updates/pending_db_world/rev_1653724704946000500.sql

Fixed #11799
- Closes #11799
Be on any mount
`.quest a 13010`
`.go xyz 7345.899902 -2812.949951 798.488281 571`
talk King Jokkum(creature id 30105) …

fix(DB/SAI): Do not summon King Jokkum vehicle if player is mounted.

---

data/sql/updates/pending_db_world/abyssallordloot.sql

-  Grouped the 3 items per boss so that it's limited.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11712
- Closes https://github.com/chromiecraft/chromiecraft/issues/3485
Vmangos
- Tested
1. `.additem 20451` `.additem 20422` `.additem 20408` `.additem 20406` `.additem 20407`
2. equip them all
3. summon a Abyssal Lord from a Greater Windstone
4. loot and respawn until you see an epic and a rare, or 2 rares drop at the same time …

Fix(Creature/Loot): Abyssal Lord should only drop 1 rare/epic

---

data/sql/updates/pending_db_world/rev_1653600539752129200.sql
src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp

https://wotlkdb.com/?sounds&filter=na=_Radio;ty=10 - 
-  Move hardcoded text to DB
- Populate creature_text for Bronzebeard Radio
- Commented out text when a player repairs their vehicle
- Bronzebeard Radio remove equipment (floating pickaxe)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11858
https://youtu.be/NiWi5uJAD1s?t=194 - That there is no text when a player repairs their vehicle (commented out)
1. .tele uld
2.  check towers/fl …

fix(Script/Instance): Ulduar - Flame Leviathan Hardcore to DB

---

src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp

Finally learned how to do gossips (At least I like to think that....)
- Added the missing text that explains what each keeper does 
- Added the 2nd part of the gossip, where you confirm you want the keeper's assistance
- Removed the hardcode
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11702
In the issue
- Tested in-game (and tested with yogg, to make sure I didn't screw the keeper activation, all good)
.gm on
.go c 1975234
Speak with him or any other keeper
Notice the proper npc_text & 2nd gossip page
Make sure the keepers actually activate when spoken to (have to clear to yogg) …

fix(Script/Instance): Ulduar - Fix Keeper's missing gossips and remove hardcode

---

conf/dist/config.sh

Authored by: Nefertumm <nefertum.dev@protonmail.com>
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11978
- tested
1. compile with acore.
2. see that modules compile …

Fix(Conf): Modules should compile

---

data/sql/updates/pending_db_world/rev_1654360244950518900.sql
src/server/scripts/World/go_scripts.cpp

Based on @offl work.
Fixes #11610
-  Port of https://github.com/TrinityCore/TrinityCore/commit/9c1c34a79420b2513ee0009fcd84726c3ff95bfe
- Closes #11610
`.go xyz -11905 -1911 66 309`
`.learn 11611`
`.setskill 171 300`
interact with the Tablet of Madness
interact with the other tablets around the area …

fix(Scripts/ZulGurub): Fixed Edge of Madness tablets.

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerUpdates.cpp
src/server/game/Handlers/MiscHandler.cpp

Fixes #12004
- Closes #12004
- Closes https://github.com/chromiecraft/chromiecraft/issues/3595
- Not tested.
More info [here](#12004) …

fix(Core/Misc): Fixed radius of areatriggers in battlegrounds.

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  Proper submerge animations
-  Eye tentacles no longer overlap beams
- Small tentacles no longer submerge
- Timer adjustments and missing spells from retail research
- 
- Closes 
- Not tested, but last time I tested (6 y ago) it looked like this:
https://www.youtube.com/watch?v=0xk6T1GuYA0&ab_channel=SarahAlexander
1.
2.
3. …

fix(Scripts\TempleOfAhnQiraj): Rewrite C'thun tentacles

---

data/sql/updates/pending_db_world/huntress.sql

and fixed smart script errors
-  Removed invalid arguments in the link entries, which resulted in errors and them bugging out
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10728
- Closes https://github.com/chromiecraft/chromiecraft/issues/2992
- tested
Go to ghostlands, Shalandis Isle
Search for Darnassian Huntress
Move in and out of range to see if mob correctly attacks you.
check if they flee correctly …

fix(DB/Smartscripts): Darnassian hunter should melee when closed range

---

data/sql/updates/pending_db_world/derrington.sql

-  Alliance quest had horde mail and vice versa
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11308
- Closes https://github.com/chromiecraft/chromiecraft/issues/3260
- Tested
1. Complete 5236
2. Take next quest from derrington
3.wait 1 day for mail to arrive.
4. check if its horde mail …

fix(DB/QuestTemplate): Mission Accomplished! sent correct mail to player

---

data/sql/updates/pending_db_world/rev_1655079819870509800.sql

Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)
-  Update unit_flags
-  Update flags_extra
- Closes #12041
- Closes https://github.com/chromiecraft/chromiecraft/issues/3612
Any Ragnaros video encounter
- Tested in-game: No auto-attack or visual nameplate from the NPC
1. Go into MC
2. Kill all bosses and complete Majordomo's encounter as usual
3. Go into Ragnaros, stand still for some minutes, you won't notice "Flame of Ragnaros" NPCs …

fix(DB/creature_template): Hide 'Flame of Ragnaros'

---

data/sql/updates/pending_db_world/rev_1654964970863464300.sql

Fixes #11886
- Closes #11886
More info [here](#11886)

fix(DB/SAI): Removed one invalid action for Scarlet Warder.

---

data/sql/updates/pending_db_world/threshwackonator.sql

-  Set npc flag and add correct gossip menu
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12015
- Closes https://github.com/chromiecraft/chromiecraft/issues/3598
- Tested
- 
1. See linked issue …

Fix:(DB/Creature): Threshwackonator missing gossip

---

data/sql/updates/pending_db_world/siabispremiumtobacco.sql

-  Set drop late very low to make the chance so it pretty much never drops from the chest.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4448
- Tested
1. Go stratholme main gate
2. .q add 5214
3. loot box
4. fight npc
5. loot npc for quest item …

Fix(DB/Loot): Tobacco should not be in chest

---

data/sql/updates/pending_db_world/rev_1655221651010939500.sql

-  Remove loot, skinning loot, and XP from Domesticated Felboar
- Closes #11817 
- Killed creature, no loot, no XP, not skinnable
1. .go cr 77832
2. Kill creature, check for loot, XP, and skinnable …

fix(DB/creature_template): Fix Domesticated Felboar

---

data/sql/updates/pending_db_world/mcelementalsshouldbleed.sql

- remove bleed flag
- Closes https://github.com/chromiecraft/chromiecraft/issues/3225
- Closes https://github.com/chromiecraft/chromiecraft/issues/3226
- Tested
1. go to elementals in the sql and see if they bleeeeeed …

fix:(DB/Creature): Molten Core elementals should bleed.

---

data/sql/updates/pending_db_world/curseoftides.sql

-  Added smartAI
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12059
- Closes https://github.com/chromiecraft/chromiecraft/issues/3605
Youtube videos listed in the issues, as well as trinitycore (https://github.com/TrinityCore/TrinityCore/issues/20275)
- tested
Follow the SV Alliance storyline up to [The Curse of Tides](https://wowgaming.altervista.org/aowow/?quest=611)
Summon Gazban at the altar
Observe the lack of dialogue
none …

fix(DB/Smartscripts): Gazban smartAI

---

data/sql/updates/pending_db_world/rev_1655437816582367100.sql

Adds a lot of previously missed chests in Mulgore.
Pools them on sniffed spawns so they are not always the same.
-  Removes existing chests in Mulgore, for organizational purposes
-  Insert all Mulgore chests, then pools them where appropriate.
- Makes them correct and makes them complete.
Sniff variables and hard work looting them on blizz servers long enough to understand them.
- After installing, to test, I set the respawn time to 30 seconds.    UPDATE `gameobject` set spawntimesecs='30' WHERE id=106318;
- That makes it easy to check.  Since I found all these it was easy for me, but I also created a map.  The numbers on this map will match the GUID offset I've written
1.  See above
- Make sure GM is off when testing this or it will not work. …

fix(DB/gameobject): Overhaul of Gameobject 106318 in Mulgore

---

src/server/game/Battlegrounds/ArenaTeam.h

-  Update the current value of the MAX_ARENA_SLOT const
- https://github.com/azerothcore/mod-1v1-arena/issues/38
- Build without error
- in-game testing with the module
1. Install the azerothcore with this module (and the fixed code).
2. Open 2 clients and test arena module 1v1 queue.
3. Finish the arena.
- https://github.com/azerothcore/mod-1v1-arena/pull/41 …

Update MAX_ARENA_SLOT (Fix Arena 1v1 Module)

---

deps/g3dlite/source/CollisionDetection.cpp

-  remove excess line breaks
- Closes 
- Builds and compiles
- Nothing to test.
1. Nothing to test. …

chore (cleanup): Excessive line breaks removal.

---

apps/installer/includes/functions.sh

similar to https://github.com/azerothcore/azerothcore-wotlk/pull/11535
related of https://github.com/azerothcore/azerothcore-wotlk/pull/12111

chore(Dashboard/functions.sh): update data version

---

data/sql/updates/pending_db_world/rev_1655649959631988500.sql

Fixes #11781
- Closes #11781
- Closes https://github.com/chromiecraft/chromiecraft/issues/3609
`.learn 20252` `.learn 2458`
`.aura 19263` a target
Switch to Berserker Stance and cast Intercept …

fix(DB/Spells): Intercept should not bypass Deterrence.

---

data/sql/updates/pending_db_world/sonofhakkarimprovements.sql

-  Set the patrolling  son of hakkar respawn time to 60 seconds (source cmangos/vmangos)
-  Fixes duration of poison cloud effect, previously it would disappear if only 1 person got hit, now it will continue for the total duration
https://youtu.be/McmJ59Wo5p4?t=1479
- Tested
1. Go to son of hakkar
2. stand in poison shit when they die
3. see that the cloud stays for 10 seconds  …

fix(DB/Creature): Son of Hakkar Improvements

---

data/sql/updates/pending_db_world/rev_1654369041234881900.sql
src/server/scripts/Commands/cs_deserter.cpp

- Add an optional variable for the `.deserter remove bg all` and `.deserter remove instance all` commands
- Not specified defaults to 15min for bg and 30min for instance
- Set to -1 will remove any deserter debuff length
- Closes 
- Added bg deserter < 15min and removed all with and without  a set time
- Added bg deserter >= 15min and removed all with and without  a set time
- Added bg deserter and removed all with time set to -1
1. Use `.deserter bg add 300`
2. Use `.deserter bg remove all` and observe the outcome
3. Use `.deserter bg add 900`
4. Use `.deserter bg remove all` and observe the outcome
5. Use `.deserter bg add 3600`
6. Use `.deserter bg remove all 30m` and observe the outcome
7. Use `.deserter bg remove all 2h` and observe the outcome
8. Use `.deserter bg add 3600`
9. Use …

feat(Core/Command): Deserter rm all time parameter

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp

-  Store the present classes and remove them from the pool once one is picked, so the same call is not made in sequence
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3664
- not tested
- 
1. pull nefarian with 3 characters
2. notice the calls circle between the different classes
3. …

fix(Scripts/BlackwingLair): Nefarian class calls should not repeat

---

data/sql/updates/pending_db_world/rev_1656088067256222400.sql

-  Fix the gender in quest reward text
- Closes https://github.com/chromiecraft/chromiecraft/issues/3672
- ![1](https://user-images.githubusercontent.com/98835050/175603849-e54d3d4e-558d-4c85-b519-670c4cfd72f8.PNG)
1. Must be a priest with Eye of Divinity to see NPC
2. .quest add 7622
3. .quest complete 7622
4. Check reward text
5. .mod gender male/female
6. Check reward text …

fix(DB/quest_offer_reward): Balance of Light and Shadow Reward Text

---

data/sql/updates/pending_db_world/rev_1656181701026138200.sql
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp

-  Implement an overload to UpdateEntry() to allow updating the AI when the entry changes
-  Bone constructs won't cast draconid abilities anymore & will cast their proper ability
- Closes 
- 
1. go to nefarian, progress to phase 2
2. damage him until he brings the minions back to life
3. turn your back to minions, see that they cast backstab at you (expose weakness) …

fix(Scripts/BlackwingLair): Correct Bone Constructs abilities

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp

-  Fixes Arlokk reset behaviour and her panthers.
-  Some code improvements.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12098
- Closes https://github.com/chromiecraft/chromiecraft/issues/3628
1. .go xyz -11562 -1628 41.3 309 -2.9
2. Activate the gong.
3. Reset.
4. Her panthers should be gone and she should be despawned after she came back home.

fix(Core/ZulGurub): Arlokk reset behaviour

---

data/sql/updates/pending_db_world/rev_1655953968509118619.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp

Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)
-  Enable root state
- Closes #11869
- Closes https://github.com/chromiecraft/chromiecraft/issues/3539
Any Ragnaros encounter's video
- Tested -> the change fixes the issue and does not break any encounter's mechanic
1. Go Molten Core
2. Kill every boss and douse all runes
3. Engage into Ragnaros' encounter
4. Stay within 0-3 yards at all time, you'll notice no movement backwards from Ragnaros …

fix(scripts/MoltenCore): Disable Ragnaros movement

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp

Fixes #12162
- Closes #12162
`.go xyz -11562 -1628 41.3 309 -2.9`
Activate the gong
Wait adds spawn
Move in the room and look the panther behavior …

fix(Scripts/ZulGurub): Arlokk's Panthers should attack players.

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_grilek.cpp

Fixes #12088
- Closes #12088
- Not tested.
`.go xyz -11905 -1911 66 309`
`.npc add temp 15082` …

fix(Scripts/ZulGurub): Gri'lek should pursuit random targets.

---

data/sql/updates/pending_db_world/ancient_hero.sql

-  
-  
- Closes  #https://github.com/azerothcore/azerothcore-wotlk/issues/12153
- 
- 
.q a 13133
.go c id 30718
talk it
when he becomes iskalder, then use The Bone Witch's Amulet for iskalder
bring 'iskalder' back to 'The Bone Witch'
**For …

fix(DB/Creature): The Ancient Hero SmartAI fix

---

data/sql/updates/pending_db_world/dawnblade-hawkrider.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6064
- 
- 
1.
2.
3. …

fix(DB/Creature): Dawnblade Hawkrider SmartAI fix

---

data/sql/updates/pending_db_world/rev_1656442792617565900.sql

-  Add missing spawn and pathing for rare mob The Behemoth
-  All values are from Vmangos
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12177
- Closes https://github.com/chromiecraft/chromiecraft/issues/3682
Vmangos
- Tested in-game, NPC spawns and paths correctly
1. .go cr 300758 …

fix(DB/creature): Add missing rare The Behemoth

---

data/sql/updates/pending_db_world/rev_1656606538908234900.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp

-  Basically do what I originally suggested in [my PR](https://github.com/azerothcore/azerothcore-wotlk/pull/12022) before other people suggested using "creature_template_movement" instead of a change in the core.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3708
This was originally how I suggested fixing Ragnaros' movement without altering anything else. See [commit](https://github.com/azerothcore/azerothcore-wotlk/pull/12022/commits/fcd8be6b93b1caa113887d312545d7500a92ec84)
Current state, melee will not get aggro until it reaches 0-1yrds of Ragnaros Hitbox, if in max combat range aggro will reset.
With this PR: I get aggro since the beginning of the fight. (I'm behind/below the hammer)
1. Ragnaros encounter …

fix(scripts/Ragnaros): Move root handling from DB to Core

---

src/server/scripts/World/go_scripts.cpp

-  Fix Midsummer Music to only play for players in visibility of invisible music doodad
- Closes https://github.com/chromiecraft/chromiecraft/issues/3678
- Tested in game, music players near object, flied far away on same map and the music correctly stopped and changed to zone music
1. .go gameobject 50555
2. Listen to music
3. Run far way
4. Music should stop …

fix(Scripts): Midsummer Music Range

---

data/sql/updates/pending_db_world/rev_1656502396301969700.sql
src/server/game/Entities/Creature/Creature.h
src/server/scripts/EasternKingdoms/ZulGurub/boss_thekal.cpp
src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp

-  Fix equipment in cat form
-  adds actually die instead of sleeping
- boss no longer dies from dots during transition
- Closes 
- 
1.
2.
3. …

fix(Scripts/ZulGurub): Thekal improvements

---

data/sql/updates/pending_db_world/rev_1656776031584499100.sql

Fixes #12210
- Closes #12210
1 `.q a 12820`
2. `.go xyz 6370.488281 -1225.186157 426.779846 571`
3. use Improved Land Mines …

fix(DB/Quest): Fixed getting kill credit for quest "A Delicate Touch"

---

data/sql/updates/pending_db_world/juggling_torch_fix.sql
src/server/scripts/Events/midsummer.cpp

-  This Fix adressed to Achievement "Juggle 40 torches in 15 seconds in Dalaran." 
https://www.wowhead.com/achievement=272/torch-juggler
1. .additem 34599 40
2. .q a 11657 .q c 11657 .q rew 11657
3. .tele dalaran
4. cast item on self

Script/Spell: fix Midsummer's Juggling Torch

---

src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #12225
- Closes #12225
`.q a 11876`
`.go c id 25850`
use quest item D.E.H.T.A. Trap Smasher …

fix(Core/Spells): Smash Mammoth Trap should open Mammoth Calf's trap.

---

data/sql/updates/pending_db_world/rev_1656831380141778300.sql

Fixes #12213
- Closes #12213
1 `.q a 10231`
2. `.go c id 19720`
3. Dialogue he starts fighting and defeats him …

fix(DB/SAI): Fixed completing quest "What Book? I Don't See Any Book"

---

data/sql/updates/pending_db_world/rev_1656757421461118700.sql
src/server/game/Entities/Unit/Unit.cpp

Fixes #12209
- Closes #12209
`.q a 12662`
`.go xyz 5924.003418 -3803.821777 363.599518 571`
Right click on Heb'Jin's Drum …

fix(DB/SAI): Heb'Jin should not evade on attack. Source: TrinityCore.

---

data/sql/updates/pending_db_world/silithid_swarm_gold.sql

-  Removes money drop from creature 4196
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12261
- Closes https://github.com/chromiecraft/chromiecraft/issues/3695
- 
1. `.npc add temp 5451`
2. kill the summoned Silithid Swarm
3. try to loot …

fix(DB/Creature): Silithid Swarm remove gold drop

---

data/sql/updates/pending_db_world/rev_1657040899617221100.sql

- Use correct creature type (was incorrectly 12 - non-combat pets, should be 8 - critter) for Critters Killed achievement criteria
- This fix is dedicated to @tkn963 who has followed this issue closely. Haha. ^_^
Didn't work, now it works
1. Kill critters
2. Check that statistic page updates …

fix(DB/Achievements): Critters Killed statistic

---

src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Creature/GossipDef.h
src/server/game/Handlers/MiscHandler.cpp
src/server/game/Handlers/QuestHandler.cpp

Fixes #12215
- Closes #12215
`.go xyz 504.003845 2008.118896 113.079597 530`
`.q a 10382`
talk Gryphoneer Leafbeard fly to Shatter Point
talk Gryphoneer Windbellow Fly back
talk Field Marshal Brock
Also check #9962 if there is no regression on this. …

fix(Core/Gossips): Properly send packet with questgiver query handler.

---

src/server/game/Achievements/AchievementMgr.cpp

-  Fix Achievement packets to have correct times
-  Fixes display of many achievements such as Average Gold Per Day
- Closes https://github.com/chromiecraft/chromiecraft/issues/3712
Cmangos https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Achievements/AchievementMgr.cpp
- ![1](https://user-images.githubusercontent.com/98835050/176943519-cad0af93-8936-4d61-bd92-de61069b66e1.PNG)
1. View Statistics tab
- One more value in the packet should be 1 if it is a failed timed criteria, but I don't think this is ever used and would need some new functions so I didn't fix it. I left a TODO in case we are want to properly fix it later. …

fix(Core): Fix Achievement Packets

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Groups/Group.cpp
src/server/game/Handlers/LootHandler.cpp
src/server/game/Loot/LootMgr.cpp
src/server/game/Loot/LootMgr.h
src/server/game/Scripting/ScriptDefines/GlobalScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Keep reference of the worldobject (creature or object) source of the loot throughout the loot management process
-  Add custom hooks to allow managing item/loot availability
- Closes 
- 
- 
1. loot stuff and check if it still works/masterloot/grouploot etc.
2.
3. …

feat(Core/Scripting): Implement OnAllowedForPlayerLootCheck() hook

---

data/sql/updates/pending_db_world/rev_1657358307029243000.sql
src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp

Fixes #12273
- Closes #12273
- Not tested.
`.go c id 14834`
pull the boss and move down the stairs or fly away to reset him …

fix(Scripts/ZulGurub): Added missing yell on Hakkar's evade.

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Grids/Notifiers/GridNotifiers.h

- Closes #12332
- Closes https://github.com/chromiecraft/chromiecraft/issues/3749
More info [here](#12332) …

fix(Core/Spells): Fixed LoS problems with hunter traps.

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_thekal.cpp

-  Fix minions not respawning if they both die at the same time
- Fix minion no aggro after ress
-  Fix boss not dying in phase 2
- Closes 
- 
1. 
2.
3. …

fix(Scripts/ZulGurub): fix Thekal not dying in phase 2 

---

src/server/game/World/World.cpp

-  clean up SendGMText
-  Easier to read
- Closes 
- 
- 
1.
2.
3.

update (core): Clean Up SendGMText

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Scripting/ScriptDefines/UnitScript.cpp
src/server/game/Scripting/ScriptMgr.h

- Adds an `OnDisplayIdChange` hook for the `Unit` class
N/A
- Compiled and tested on Windows 10 x64, Visual Studio 2022
1. Make a custom script that uses the new hook
2. Do `.morph target 12345`
3. Verify that your hook fired
**For …

feat(Core): add OnDisplayId hook

---

src/server/game/AI/CreatureAI.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Scripting/ScriptDefines/UnitScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Needed for modules. Adds OnUnitEnterCombat/JustDied/Evade.
-  It's used to extend the current creature scripts without changing the source files
- Closes 
- 
- 
1.
2.
3. …

feat(Core/Scripting): Add several UnitHooks

---

data/sql/updates/pending_db_world/rev_1657988086857948400.sql
src/common/Dynamic/ObjectRegistry.h
src/common/Utilities/Timer.h
src/server/game/AI/CoreAI/CombatAI.cpp
src/server/game/AI/CoreAI/PetAI.cpp
src/server/game/AI/CreatureAISelector.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/World/World.cpp

-  Follow up for https://github.com/azerothcore/azerothcore-wotlk/pull/11779
-  https://github.com/TrinityCore/TrinityCore/commit/d56a28afee19741c582ed8e16dbf8e30311f68ea
-  https://github.com/TrinityCore/TrinityCore/commit/9c24ec5c966da1a78ddd3df6023c6cab43111ebc
-  https://github.com/TrinityCore/TrinityCore/commit/d02f481d9ac8e1d1a7716368f609d53a5add0960
-  https://github.com/TrinityCore/TrinityCore/commit/877749cf3ffd479a87f7b3a7ac1b3703389c6cb3
- Closes -
- Compiled, played a little bit in-game.
Check some creatures with smart script, gobs, etc. Try mind-controlling moving creatures as well.

fix(Core/AI): more AI factories checks

---

data/sql/updates/pending_db_world/rev_1657669676037619800.sql

Implements snake pack by entrance
-  Creates a pool for the first (and only) snake 3-4 pack in ZG  this will be the most complicated pack in the instance ironically. 
- Snake packs will spawn 1-3 of each type, never 4 of the same type, and about half the time will spawn only as 3
Blizzard servers
- Tried several repetitions
- Goto ZG
- Reboot server, goto ZG in new instance
- You should not need to reboot the server to have changes occur, this has nothing to do with data being put in this PR but rather with the way pooling is handled in instances somehow. …

fix(db/creature): ZG entrance creature improvement 2

---

data/sql/updates/pending_db_world/rocklance.sql

-  Adds a formation to GUIDs 20720, 14007, 20588
-  Adds missing waypoint data to leader Rocklance (GUID: 20720)
-  Updates respawn timers to be the same as Vmangos
-  Added a SmartAI script to force respawn the formation members 14007 and 20588 when the leader Rocklance spawns. I don't know if that's the usual method, but it would fix some of the problems of having either the leader alone or the members idle. I'll remove it if unneeded. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6974
- Closes https://github.com/chromiecraft/chromiecraft/issues/1220
VMangos
- Tested ingame, saw no issues.
- 
1. `.go c 20720`
2. Follow him in his patrol,
3. Kill the group, then .respawn Rocklance
You …

fix(DB/creature): Rocklance waypoints and formation.

---

data/sql/updates/pending_db_world/cauldronlordrazarch.sql

-  added smartscript
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12179
- closes https://github.com/chromiecraft/chromiecraft/issues/3671
trinitycore
- tested
- 
1. .npc add temp 11076
2. see that he casts shadowbolt
3. see that he casts summon skeleton
4. text line on aggro
5. drain life below 50% hp. …

fix(SmartScript/Creature): Cauldron Lord Razarch smartscripts

---

data/sql/updates/pending_db_world/rev_1658048928200692800.sql

Fixes #10313
- Closes #10313
`.q a 11627`
`.go c id 25416`
kill it
`.go c id 25418`
kill it …

fix(DB/Quest): Boiling Point.

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp

-  Follow up https://github.com/azerothcore/azerothcore-wotlk/commit/9aeb23636803c681efa8d25451639e2f7b7a2f0c  
https://www.youtube.com/watch?v=h9cYBbR0uHA
https://www.youtube.com/watch?v=x2-AEL4InTU
https://www.youtube.com/watch?v=UZEN8IbQQR0&t=276s
https://www.youtube.com/watch?v=QL1G_zQ38Gs&t=5s
https://www.youtube.com/watch?v=olTirBegGoQ&t=159s …

fix(Scripts/ZulGurub): Adjust Arlokk timers

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_fankriss.cpp

-  Correct Fankriss spell ID
-  Clean up crappy old code
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): Correct Fankriss Mortal Wound spell ID

---

data/sql/updates/pending_db_world/aq20trash.sql

-  Fixes trash scripts
- Closes https://github.com/chromiecraft/chromiecraft/issues/3819
- partially closes https://github.com/chromiecraft/chromiecraft/issues/3820
- closes https://github.com/chromiecraft/chromiecraft/issues/3821
- partially closes https://github.com/chromiecraft/chromiecraft/issues/3822
- closes https://github.com/chromiecraft/chromiecraft/issues/3823
- closes https://github.com/chromiecraft/chromiecraft/issues/3824
- closes https://github.com/chromiecraft/chromiecraft/issues/3826
- closes https://github.com/chromiecraft/chromiecraft/issues/3827
- closes https://github.com/chromiecraft/chromiecraft/issues/3828
- closes https://github.com/chromiecraft/chromiecraft/issues/3757
- closes https://github.com/azerothcore/azerothcore-wotlk/issues/12413
cmangos
- tested
1. go to …

fix(SmartScript/Creature): AQ20 Trash scripts

---

data/sql/updates/pending_db_world/crests.sql

-  Reverts revert https://github.com/azerothcore/azerothcore-wotlk/pull/9951
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12422
- Closes https://github.com/chromiecraft/chromiecraft/issues/3791
- Query runs, checked Keira
1. `.additem set 492`
2. `.go gameob id 180529`
3. equip item set, spawn the Abyssal Templar, see that it always drops the Abyssal Crest item …

fix(DB/Loot): Abyssal Crest (20513)

---

data/sql/updates/pending_db_world/moontouched_owlbeast.sql

-  Corrects spell_template
-  Adds SmartAI
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12342
- Closes https://github.com/chromiecraft/chromiecraft/issues/3741
Vmangos
1. `.go c id 7453`
2. engage, see if it casts Rejuvenation on pull and Moonfire occasionally. …

fix(DB/Creature): Moontouched Owlbeast (7453)

---

src/server/game/AI/SmartScripts/SmartAI.cpp
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScript.h
src/server/game/AI/SmartScripts/SmartScriptMgr.h

Co-authored-by: Meji <meji46@users.noreply.github.com>
Co-authored-by: Ariel Silva <ariel-@users.noreply.github.com>
Co-authored-by: Shauren <shauren.trinity@gmail.com>
-  https://github.com/TrinityCore/TrinityCore/commit/866074b6899d87df6c835b936524d9f76ba78949
-  https://github.com/TrinityCore/TrinityCore/commit/198d18bef5d3480cb30c80e4a4946327f401a6d4
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12485
- Built, not tested.
1. Check SAI

fix(Core/AI): validate stored targets

---

data/sql/updates/pending_db_world/rev_1658464932896975300.sql

-  Sets all item drops to equal-chance
-  Fixes skewed drop rates, and makes them in line with Vmangos' DB.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11645
- Closes https://github.com/chromiecraft/chromiecraft/issues/3465
- Query runs. Checked Keira. Tested ingame.
1. `.go c id 10997`
2. `.damage 999999`
3. respawn, loot, repeat
4. all drops should be equal chance
Note: use this macro:
```
/tar cannon master
.respawn
/tar cannon master
.damage 200000
``` …

fix(DB/Loot): Cannon Master Willey (10997)

---

data/sql/updates/pending_db_world/rev_1657756491696232200.sql

-  SmartAI from Warmaul Chef Bufferlo
-  All values from TrinityCore (https://github.com/TrinityCore/TrinityCore/commit/b54d389cf1ec812293e385e7b8a2f1b53aab7a9c)
- Co-authored by ZenoX92
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/b54d389cf1ec812293e385e7b8a2f1b53aab7a9c
1. Fight NPC, ensure texts and spells seem correct …

fix(DB): Script Warmaul Chef Bufferlo

---

data/sql/updates/pending_db_world/rev_1658689583030214000.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.h

-  Move its script to the new system and modernize the code.
-  Script sand traps to activate after 5s (sniffed).
-  Modify Ossirian yell on Kurinnaxx death.
-  Sand traps should not be casted on tanks.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12172
Go to Ruins of Ahn Qiraj and engage Kurinnaxx with 2 people or more.

fix(Core/RuinsOfAhnQiraj): Kurinnaxx

---

data/sql/updates/pending_db_world/rev_1658645642391085500.sql
src/server/game/AI/SmartScripts/SmartScript.cpp

- Closes #12461
- Not tested.
More info [here](#12461)

fix(DB/SAI): Fixed completing quest "Into The Realm of Shadows"

---

data/sql/updates/pending_db_world/rev_1658788379158805300.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp

-  Implement script for Anubisath Guardians
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/RuinsOfAhnQiraj): Script Anubisath Guardians

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp

-  Move to new system + improve code consistency + style.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12471
- Built.

refactor(Core/RuinsOfAhnQiraj): Ossirian

---

data/sql/updates/pending_db_world/rev_1658801275458302100.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_moam.cpp

- Stone phase now ends once all adds are killed OR Moam reaches full mana OR the phase duration expires
- Moam will no longer drain mana during stone phase
- Missing emotes & blizzlike spells implemented 
-  move to new register model
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/RuinsOfAhnQiraj): Rewrite Moam

---

src/server/game/Groups/Group.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Add OnGroupRollRewardItem hook for when a player receives an item from winning a GREED or NEED roll.
- Closes 
- Tested with my [module](https://github.com/AnchyDev/StatBooster) on a local server.
1. Add hook to a Player Script
2. Create group ingame with group loot
3. Loot uncommon+ item and roll on it.
or
1. Compile the core with my [module](https://github.com/AnchyDev/StatBooster)
2. Import the SQL located in `sql/world/base/development.sql`
3. Enable the module in the statbooster.conf.dist
4. Summon vancleef .npc add 639 - (This creature drops items in the itemlevel range for my module.)
5. Create a party.
6. Kill vancleef and loot corpse, roll GREED or NEED.
7. If the item got enchanted, then the hook was successfully called.
- I'm not really sure on how to handle DISENCHANT …

feat(Core): Add OnGroupRollRewardItem hook.

---

data/sql/updates/db_world/2022_07_26_04.sql

fix(DB/Update): Fix update 2022_07_26_04.sql

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/RuinsOfAhnQiraj): Despawn Ayamiss summons on death/reset

---

data/sql/updates/pending_db_world/rev_1657755590733012200.sql

-  Fix Chief Hawkwind - he should not have a gossip menu, and instead should be a quest_greeting, with correct emotes. Text was also wrong.
-  Values from TrinityCore https://github.com/TrinityCore/TrinityCore/commit/cdaf6c0d7a7b0b195cfef5620697c0ec9bc73dc7
- Co-authored by ZenoX92
https://github.com/TrinityCore/TrinityCore/commit/cdaf6c0d7a7b0b195cfef5620697c0ec9bc73dc7
- 
1. Talk to Chief Hawkwind, ensure no gossip menu.
2. If having multiple quest options, should see greeting, otherwise direct to quest
**REMEMBER**: …

fix(DB/quest_greeting): Fix Chief Hawkwind quest_greeting

---

data/sql/updates/pending_db_world/rev_1658502499846467300.sql

-  Script To Serve Kum'isha end event
-  Co-authored by ZenoX92
- From https://github.com/TrinityCore/TrinityCore/commit/515f47eec7263bfb593a2697c0be8afa40ed0324
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/515f47eec7263bfb593a2697c0be8afa40ed0324
1. Complete quest 2521
2. View end event …

fix(DB): Script To Serve Kum'isha End Event

---

data/sql/updates/pending_db_world/rev_1658886173744516000.sql

-  Closes #12554
-  Closes https://github.com/chromiecraft/chromiecraft/issues/3849
- reacting …

fix(DB/creature): update pos z for guid 34977

---

data/sql/updates/pending_db_world/rev_1657898491936446500.sql

-  Move Ghost Mushroom to be within underground cave, as close to existing position as possible
-  Co-ordinates are not sniffed but at least look more correct than existing values - before was incorrectly above ground which should not happen with Ghost Mushrooms
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12152
- Closes https://github.com/chromiecraft/chromiecraft/issues/3660
- In-game:
1. .go gameobject 16425
2. See if position looks correct (may need several attempts because it is pooled) …

fix(DB/gameobject): Ghost Mushroom Position

---

data/sql/updates/pending_db_world/rev_1658514767872316300.sql

-  Change gossip menu option to correct text
-  Co-authored by ZenoX92
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/ff7f085403f1bb1673a6f72d1350a0bad199ff60
- Checked in-game
1. View that text is now correct …

fix(DB/gossip_menu_option): Correct Marin Noggenfogger text

---

data/sql/updates/pending_db_world/rev_1658515102793478000.sql

-  Add missing outro event to quest Sprinkle's Secret Ingredient
-  Co-authored by ZenoX92
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/947b4792e1920d47b000ffcfa5ab85cd4c6c2f1a
1. Complete quest 2641, view event …

fix(DB): Sprinkle's Secret Ingredient Outro Event

---

data/sql/updates/pending_db_world/rev_1658519096000543100.sql

-  Add a missing gossip option for Wooden Outhouse to respawn gameobject "Goodsteel Ledger" in case the player didn't loot it when quest "Ledger from Tanaris" was taken
-  Co-authored by ZenoX92
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/dc145323a9b35b5e18059bcf39574f3f1dff4c37
- Checked in-game
1. Accept quest 4450
2. Get the ledger
3. Destroy the ledger
4. Confirm can get another ledger …

fix(DB): Restore Goodsteel Ledger

---

data/sql/updates/pending_db_world/rev_1658532736609953400.sql

-  first ZG Croc pack pooled, can now spawn 4 or 5 crocolisks
-  creature_formations added to create assist behavior
Retail Classic/Sniffs
- Tested in ZG, reset the server to make sure the pools reset.  You can now get either 4 or 5 and they will pull together. 
1.  Enter ZG
2.  Test as described above.
- There will be similar PRs for other packs in the area …

fix(DB/creature, pools, formations): Continued ZG Before Bats work

---

data/sql/updates/pending_db_world/rev_1658622609596209300.sql

-  Adds wander_distance to those previously idle creatures.
-  Improves the Caverns of Time entrance
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12009
30 mins sniffs from TBCC for each creature.
- 
1. `.go xyz -8200 -4612 8.87 1`
2. See if the 3 drakes (Tick, Chronalis, Occulus) now wander in a radius. …

fix(DB/Creature): Set wander_distance for creatures 21773, 21774, 21775

---

data/sql/updates/pending_db_world/rev_1658700301267875700.sql

Fixes Bat Pack agro and adds pooling possibilities
Adds formations to fix Troll/Snake pack agro behavior
- Bat pack at the top of hill will have Rider positions shift each time pool is chosen (server reboot currently)
- Pack at bottom of hill will reliably link together
Classic/Sniff
- Tested several itterations in game
- Tested by pulling each pack as well
1. Go to area on map and test as described above, rebooting server to see different versions of the packs. 
- This should conclude this area of ZG's spawns pooling and agro behavior.... and the bat area is all patrols which are already done by temper and look awesome so next area will be outside the snake boss area …

fix(DB/creature, pools, formations): Before Bat Area Creature Work Final

---

data/sql/updates/pending_db_world/hakkariwitchdoctor.sql

-  adds hakakri witchdoctor smartscript
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12527
Cmangos
- tested …

fix(SmartScript/Creature): Hakkari Witchdoctor smartscript

---

data/sql/updates/pending_db_world/rev_1659291517838965500.sql

-  Trigger Drop Weapon on hit Tail Lash hit.
-  Modify the timer, it was too spammy (sniffed)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12591
1. .go c id 15336
2. Engage and pay attention to your debuffs/character weapon.

fix(DB/Spells): Hive'Zara Tail Lasher's Tail Lash

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp

-  add a check for null victim
- Closes -
Crashlogs.
-  Built.
This maybe utterly wrong, ayamiss should use a waypoint or something like that.

fix(Core/Scripts): Ayamiss crashfix

---

src/common/Utilities/EventEmitter.h

Adds an `EventEmitter` class that allows you to store multiple callbacks that you can execute later, with the ability to pass arguments to the functions.
**Example**:
* Add an `EventEmitter` to one of your classes:
```cpp
class Calculator
{
public:
EventEmitter<void(int, int, int)> OnThingComputed;
int ComputeThing(int a, int b)
{
int result = a * b;
OnThingComputed(a, b, result);
return result;
}
};
```
* Then subscribe to the event with the `+=` operator:
```cpp
Calculator calc;
calc.OnThingComputed += [](int a, int b, int result)
{
std::cout << "The result of ComputeThing(" << a << ", " << b << ") is " << result << std::endl;
};
calc.ComputeThing(3, 4);
calc.ComputeThing(2, -10);
```
This prints:
```
The result of ComputeThing(3, 4) is 12
The result of ComputeThing(2, -10) is -20
```
I …

feat(Core/Utilities): add event emitter class

---

src/server/game/AI/CoreAI/PassiveAI.cpp

-  
-  
- Closes #12604
- Closes #12498
- 
- 
1.
2.
3.

fix(Core/AI): correct Permit level for trigger flagged creatures

---

data/sql/updates/pending_db_world/rev_1659574137813657500.sql
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp

-  Add missing checks in unused params for each event/action/target.
-  Improved logs.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12619
- Tested.
1. Set Logger.sql.sql to 3, with Appender.DBErrors to 2,5
2. There shouldn't be SAI warnings.

fix(Core/SAI): Unused parameters warnings

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_moam.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_rajaxx.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_fankriss.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h

-  Move all of them for good, for some cases move timers from uint32 to Milliseconds
- Closes -
- Built
1. Engage with the bosses and wait until they cast at least 1 ability. (then we know it's working as before) …

refactor(Core/Scripts): Move AQ scripts to new scripting system

---

data/sql/updates/pending_db_world/rev_1659261841085305300.sql

Fixes #11629
- Closes #11629
Create a hunter level 60
`.additem set 530`
Equip 4 pieces
Summon pet
Wait 15 sec
Notice the aura is applied …

fix(DB/Spells): Fixed Hunter T3 4P bonus.

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

Fixed #11630
- Closes #11630
Make a druid, level 60
`.additem set 521`
Equip all items
`.list auras` to see that the aura is being applied
cast Healing Touch until a crit and see mana being restored …

fix(Core/Spells): Fixed Druid T3 8P bonus.

---

.github/workflows/macos_build.yml

-  removing macos-10.15 as its deprecated
- Closes 

chore(CI): remove macos-10.15

---

data/sql/updates/pending_db_world/rev_1659805188255061100.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp

Fixes #12469
- Closes #12469
`.go xyz -9397 1947 87 509 2.5`
`.gobject add temp 180619`
Use it. …

fix(Scripts/AhnQiraj): Fixed activation animation.

---

data/sql/updates/pending_db_world/rev_1659650326495942600.sql

-  Updates timers for Hive'Zara Tail Lasher and Hive'Zara Collectors.
-  Initial timers were kept, Repeat timers were sniffed from retail, in 15min packets.
- Closes unopened issue.
- 
1. `.go c id 15336` `.go c id 15319`
2. See if Tail Lash, Deafening Screech and Web Spray are still being cast. …

fix(DB/SAI) Update spell timers for AQ20 Trash 15336 and 15319

---

data/sql/updates/pending_db_world/rev_1659661586230960300.sql

- Removes aura 25462 from creature_addon as it was not blizzlike
- Changes SAI to buff nearby creatures with Enlarge
- Kept initial timer but added repeat from retail sniffs
1. `.go c id 15385`
2. see if he has an aura already applied to him
3. engage Zerran, see if he buffs nearby creatures with Enlarge …

fix(DB/SAI) Colonel Zerran (15385) Enlarge spell mechanics

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp

Fixes #12174
- Closes #12174
- Not tested.
Try differents distance for natural aggro the boss …

fix(Scripts/AhnQiraj): Increased aggro range for Kurinnaxx.

---

src/server/game/AI/SmartScripts/SmartScript.cpp

Fixes #10413
Fixes #10610
- Closes #10413
- Closes #10610
More info [here](#10413) and [here](#10610) …

fix(Core/SmartScripts): Fixed `SMART_TARGET_OWNER_OR_SUMMONER` target.

---

data/sql/updates/pending_db_world/rev_1658221960996682200.sql

-  Add missing translations in the gossip.
-  The translations already exist, it is simply a matter of linking them.
- Closes 
- Windows 10
- In-Game
1. `.go c 189` (Alliance)
2. `.go c 3382` (Horde)
3. Talk to the game keepers before and after applying the change. At first, you will notice that the gossip does not detect the game client, and after restarting the server, it should be displayed in several languages (at least in Spanish it works). …

Add (Gossip/Locale) City guards

---

data/sql/updates/db_world/2022_08_07_05.sql
data/sql/updates/pending_db_world/rev_1659895072162193400.sql

-  Fix a startup error introduced on a previous PR because I'm too blind to review properly x.x

fix(DB): remove scriptname wrongly assigned

---

data/sql/updates/pending_db_world/rev_1659629437144429900.sql

-  Also removes loot from all of those but 10596
-  Two of them are summons, one is a fish that dropped gold and the other is a spider. None should be skinnable.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3874
- Closes https://github.com/chromiecraft/chromiecraft/issues/3873
- Closes https://github.com/chromiecraft/chromiecraft/issues/3864
- Closes https://github.com/chromiecraft/chromiecraft/issues/3863
1. `.learn 50305`
2. `.setskill 393 450`
3. `.additem 7005`
4. `.go c id 11374`
5. `.go c id 10596`
6. `.go xyz -11565 -1628 41.30 309 3`
7. ring gong, wait for adds to spawn, kill them and see if they are lootable/skinnable
8. `.go c id 14509`
9. kill everyone within 10s to initiate phase 2, wait until tiger adds are spawned (Zulian Guardian), try to …

fix(DB/Creature): remove skinning loot from creatures 11374, 10596, 15101 and 15068

---

src/server/scripts/Commands/cs_achievement.cpp

-  It now accepts a char name as parameter, allowing it to be executed on console.
- Closes -
- Tested all possible ways to execute the command.
1. Run the command through console and all the alternative ways possible.

fix(Core/Commands): Achievement checkall

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

-  Anticheat Helper
- Closes
- builds
- performs
1.
2.
3.

update (core): Additional anticheat helper

---

data/sql/updates/pending_db_world/rev_1659849272980985000.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_fankriss.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h

-  Use spells for entangle and worm summon.
-  Moved from ScriptedAI to BossAI (this needs to be done with almost every boss in the instance).
-  Added formation with Vekniss Drones around the boss.
-  Fixed SAI for Fankriss spawns, now they cast berserk after 10-20s iic.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3812
Positions and timers from CMangos, mechanics from classic videos/guides.
1. .go c id 15510
2. Engage Fankriss

fix(Core/TempleOfAhnQiraj): Rewrite Fankriss

---

data/sql/updates/pending_db_world/rev_1660216435302974300.sql

-  Fix AllowableClasses
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3910
- 
- 
1.
2.
3. …

fix(DB/Quest): fix Silithus Armament of War class condition

---

.github/workflows/windows_build.yml

-  pin boost version in windows-ci
- Closes 

fix(CI): pin boost version

---

data/sql/updates/pending_db_world/rev_1660401908463646700.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/mob_anubisath_sentinel.cpp

Fixes #12630
- Closes #12630
- Not tested.
`.go xyz -8180 2082 129.1 531 1.55`
engage the Anubisath Sentinels.
`.damage 65000` one of them, see if Enrage is cast
kill one see if it casts Transfer Power (2400) and Heal Brethren (26565) on the others …

fix(Scripts/AhnQiraj): Anubisath Sentinel - added missing spells.

---

data/sql/updates/pending_db_world/rev_1660378795386850300.sql

Fixes #12588
- Closes #12588
- Not tested.
`.go c id 15323`
see if it casts Ambush after burrowing …

fix(DB/SAI): Hive'Zara Sandstalker.

---

data/sql/updates/pending_db_world/rev_1660377276378786800.sql

Fixes #12586
- Closes #12586
- Not tested.
`.go c id 15324`
kill one of the pair, see if the other casts Vengeance.
`.combatstop` and pull again, see if it can cast Vengeance again. …

fix(DB/SAI): Qiraji Gladiator. Base on TC work.

---

data/sql/updates/pending_db_world/rev_1659884404778685600.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/kalimdor_script_loader.cpp

Fixes #12532
- Closes #12532
- Not tested.
Go to PTR.
Go to AQ20.
Engage Hive'Zara Stinger.
See result. …

fix(Scripts/AhnQiraj): Hive'Zara Stinger.

---

data/sql/updates/pending_db_world/rev_1659994158000361600.sql

-  Remove duplicate and wrong gossip (there a second gossip with the good conditions).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12658
- Tested
1. Speak with Anachronos ( .go c id 15192 and need to be neutral at least -> .modify reputation 910 3000)
2. He should not show the gossip "I'm ready.... the Scepter of Shifting Sands".
3. .q add 8742 ->Always not show the gossip
4. .q complete 8742 and .q reward 8742 -> Should show the gossip
5. If you click on it, you will recive the scepter …

fix(DB/Gossip): Fix gossip for anachronos

---

data/sql/updates/pending_db_world/rev_1660317462420871561.sql

Jero'me is missing his weapons.
-  Set Bytes2 to `1 = STATE_MELEE (prepared melee weapon in hands)`
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12010
- Closes https://github.com/chromiecraft/chromiecraft/issues/3596
```
.go c 71028
```
Check for weapons  …

fix(DB/EversongWoods): Add Jero'me weapons

---

src/server/game/AI/CoreAI/UnitAI.cpp
src/server/game/AI/CoreAI/UnitAI.h
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/TemporarySummon.cpp
src/server/game/Entities/Creature/TemporarySummon.h
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Item/Container/Bag.cpp
src/server/game/Entities/Item/Container/Bag.h
src/server/game/Entities/Item/Item.cpp
src/server/game/Entities/Item/Item.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Object/Position.cpp
src/server/game/Entities/Object/Position.h
src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Pet/Pet.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Transport/Transport.cpp
src/server/game/Entities/Transport/Transport.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Maps/Map.cpp
src/server/game/Maps/Map.h
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Auras/SpellAuras.h
src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h

Co-authored-by: jackpoz <giacomopoz@gmail.com>
-  Implement GetDebugInfo function
- Improve debug informations in ASSERTs
-  It's the TC base but functions can be modified to add or remove informations usefull/useless for us.
- Help https://github.com/azerothcore/azerothcore-wotlk/pull/12076
https://github.com/TrinityCore/TrinityCore/commit/9a924fb9d557434c5a2e4020c80db6e6bfe466ad
- None …

feat(Core/Debug): GetDebugInfo implementation

---

data/sql/updates/pending_db_world/rev_1660675431410515100.sql

-   Correct Tactical/Logistical assignment loots
-  
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/12748
- Updates https://github.com/chromiecraft/chromiecraft/issues/3930
- tested ig
- 
1.
2.
3. …

fix(DB/Loot): Correct Tactical/Logistical assignment loots

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp

- Closes #12778
- Closes https://github.com/chromiecraft/chromiecraft/issues/3933 …

fix(scripts/RuinsOfAhnQiraj): Apply movement on Ayamiss' death

---

apps/docker/docker-build-dev.sh
apps/docker/docker-cmd.ts

-  remove the duplicate db import for docker
- Closes 

fix(DOCKER): remove docker db import using bash

---

data/sql/updates/pending_db_world/shriekercharge.sql

-  set initial min/max based on sniffed values from @Gultask 
- set random target based on video in liked issue
- Closes https://github.com/chromiecraft/chromiecraft/issues/3932
- not tested
1. Engage shrieker scarab with multiple players in aq20
2. see that they wont charge at the same time and go to a random target …

fix(DB/Smartscript): [AQ20] Shrieker/Spitting Scarab smartscript improvement

---

data/sql/updates/pending_db_world/rev_1660963650747679400.sql

-  Update position y from `-2747.85` to `-3747.85`, since it was sending Fingat to Blasted Lands
- Closes https://github.com/chromiecraft/chromiecraft/issues/3957
1. ``` UPDATE `pool_template` SET `max_limit`=7 WHERE  `entry`=1027; ``` to force spawn all 7 spawn points
2. `.go c 134237`
3. see if Fingat doesn't phase through a wall near its 2nd or 3rd waypoint …

fix(DB/waypoint): Correct typo in Fingat (Guid 134237) waypoints

---

data/sql/updates/pending_db_world/rev_1660751422190118800.sql

- Closes #12615
- Closes https://github.com/chromiecraft/chromiecraft/issues/3872 …

fix(DB/gameobject): Update Z pos for gob guid 45150

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp

Fixes #12762
- Closes #12762
- Not tested.
`.go xyz -9397 1947 87 509 2.5`
Engage Ossirian.
Count the crystals that spawned. Ignore the crystal that was already present there.
See if using one respawns another somewhere else so that the number of crystal up simultaneously is always constant. …

fix(Scripts/AhnQiraj): Spawn 3 crystals at start.

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp

fix(scripts/ZulGurub): Set timer for Ohgan's Thrash

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp

fix(scripts/ZulGurub): Mandokir engage combat after Speaker's death

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h

-  Move some bosses from scriptedai to bossai
-  Sort datas for the header, this allows us to use set boss state properly to handle doors, etc.
- Closes -
-  Tested some bosses.
-  Tested ouro spawner respawn on fail.
1. Go to Temple of Ahn Qiraj and see the boss states for each boss.

refactor(Core/TempleOfAhnQiraj): Temple of Ahn Qiraj header

---

data/sql/updates/pending_db_world/rev_1660400285204352500.sql
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/kalimdor_script_loader.cpp

Fixes #12449
- Closes #12449
- Not tested.
Go to PTR.
Enter AQ40.
Go to the tonnels before Twin Emperors boss encounter.
Engage Anubisath Defenders one by one.
Check their abilities. …

fix(Scripts/AhnQiraj): Anubisath Defender.

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp

-  Title
-  
- Closes 
- Not tested
- 
1. See if it lands fully at p2
2.
3.

fix(Scripts/RuinsOfAhnQiraj): Enable Ayamiss gravity when landing

---

data/sql/updates/pending_db_world/rev_1661155287989922600.sql
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.h

-  Make sure Explosion spell used by buru eggs always hit and ignore vmaps.
-  Change the way eggs respawn is implemented, the boss shouldn't handle respawn timers.
- Closes 
- Not tested.
1. All should be working as before. Eggs should respawn every 2 minutes, despawn quickly after their death. All of them should be respawned on wipe, they should not spawn while buru is phased.
2.
3.

refactor(Scripts/RuinsOfAhnQiraj): Buru eggs

---

data/sql/updates/pending_db_world/rev_1661217788397138700.sql

-  Sets mingold & maxgold to 0 in entries 15344 & 15555
-  
- Closes unopened issue.
Retail
- 
1. `.go c id 15344`
2. engage Ayamiss, wait for Larva to spawn …

fix(DB/creature_template): Remove gold drops from Swarmguard Needler and Hive'Zara Larva.

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp

Fixes #12714
- Closes #12714
- Not tested.
`.go xyz -8295.55 2102.6 118.2 531 3.6`
engage the boss, enter melee range
select your character's portrait to cancel auto-attacks, see if boss casts Earth Shock
initiate auto-attacks on the boss, see if he stops casting Earth Shock
cast a spell such as Frostbolt (113), see if the boss resumes casting Earth Shock
`.damage 117000`
see if the same behaviour is applied to the images …

fix(Scripts/Temple of AhnQiraj): Fixed Skeram's Earth Shock.

---

data/sql/base/db_characters/log_money.sql

-  makes correction to the squash for mariadb users
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12825
- User Reported in Discord:
1. Update if using MariaDB
2. Run
3. …

fix (sql): Squash fix for mariadb

---

data/sql/updates/pending_db_world/rev_1661385481329687500.sql

Co-Authored-By: Gultask <100873791+Gultask@users.noreply.github.com>
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Fix AQ20 respawn timers

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix: Buru crash

---

data/sql/updates/pending_db_world/rev_1658802255073427200.sql

-  Removes mob that doesn't belong.
-  Adds id to several packs with no pooling.
- Creates a formation to link agro on one pack.
Sniff/Classic
1.  Enter ZG, note mob types of impacted npcs
2.  Reboot server and see if they change.
3. Test snakes agro linking
- This is only the unpooled changes of the following research note segment: 
```
--After second bridge up and around 
200616 does not exist
Hut Mob can be Axe Thrower or a Priest
PATROL Serpents OR Adder OR both
Left 2 Adders, Right 2 Serpents OR seemingly anything except all of the same type
--Serpent Boss Area 
3x Serpent / 3x Adder (this pack is always the same but mobs are in different locations each time)
Snakes in the speaker pack seem to be completely random, an honestly unusual trait for when 4+ are present.  
Additionally, …
```

fix(DB/creature, formation): ZG Snake Area Unpooled Fixes

---

data/sql/updates/pending_db_world/rev_1661870331362772300.sql

-  Add pathing to Maw
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12782
- 
https://user-images.githubusercontent.com/47818697/187466766-f4093326-5dac-43cc-bc26-4b0420c288df.mp4
1.
2.
3.
**For …

fix(DB/SAI): Script Maw's pathing

---

data/sql/updates/pending_db_world/rev_1661639722871846800.sql

-  And modifies Vekniss Hive Crawler formation distance based on sniffs.
1.
2.
3. …

fix(DB/creature_formation): Link AQ40 trash packs near Princess Huhuran.

---

src/server/game/Entities/Player/PlayerQuest.cpp

-  This hook is exist but was never called. Added the missing call in the appropriate place.
1. Call the hook from a PlayerScript, it now will work …

fix(Core): Fix Missing OnBeforeQuestComplete Hook

---

data/sql/updates/pending_db_world/rev_1662053082554812900.sql

-  Adds aura Spirit Burst (24051) to Voodoo Spirit's creature_addon
-  Modifies Hakkari Witch Doctor SAI to spawn Voodoo Spirit on death
- Adds SAI to despawn Voodoo Spirit after 10s (sniffed value)
TBCC PTR
1. `.go c id 11831`
2. kill them, see if a Voodoo Spirit spawns
3. see if it casts Spirit Burst and despawns in 10s …

fix(DB/SmartAI): Improve ZG Voodoo Spirit (15009)

---

data/sql/updates/pending_db_world/rev_1662045791088233400.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(DB/Commands): Add missing command to the database

---

data/sql/updates/pending_db_world/rev_1662127445191277200.sql

-  Removes QuestRequired
-  Update Chance to be the same as Vmangos
- Closes unopened issue.
Vmangos
1.
2.
3. …

fix(DB/creature_loot_template): Update AQ Scarab item drops

---

data/sql/updates/pending_db_world/rev_1662084538205393900.sql
src/server/scripts/Spells/spell_generic.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12928
- 
1.
2.
3. …

fix(Scripts/Spells): Fix Itch (26078) not applying Vekniss Catalyst

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

Fixes #12867
- Closes #12867
- Not tested.
`.go c id 15339`
`.learn all gm`
`.aura 25177` on boss
cast QA Debug Fire Spell - 1000 Damage, see below damage being dealt …

fix(Core/Spells): Resistance auras should affect creatures.

---

data/sql/updates/pending_db_world/ironbar.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4038
- Not tested
- 
1. `.additem 3575 60`
2. `.go c id 15431` …

fix(DB/Quests): Repeatable flag for The Alliance Needs More Iron Bars!

---

data/sql/updates/pending_db_world/fix_blackkngihtorder.sql

-  fix #11843
-  
- Closes #11843
- Tested, works, quest can complete
- 
1.
2.
3. …

fix(DB/Quest):BlackKnight‘Order npc required credit count 

---

src/server/game/Maps/Map.cpp

Fixes #11885
- Closes #11885
- Closes https://github.com/chromiecraft/chromiecraft/issues/3557
Create druid with aquatic form
`.go xyz -8431 1281 -49 0`
Cast aquatic form
Swim near the depth and see if aquatic form is removed. …

fix(Core/Maps): Fixed getting liquid data near depths.

---

src/server/game/Misc/GameGraveyard.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Add a new hook that can be called to modify the graveyard where a player will spawn when release spirit
- None
- Tested with the following script, works as intended:
```
void OnBeforeChooseGraveyard(Player* player, TeamId /*teamId*/, bool /*nearCorpse*/, uint32& graveyardOverride) override
{
if (player->GetMapId() == MAP_NAXX && player->GetMap()->GetSpawnMode() == RAID_DIFFICULTY_10MAN_HEROIC)
{
graveyardOverride = NAXX40_GRAVEYARD;
}
}
```
- Also tested regular dying and graveyard, still works properly
1. Test in a PlayerScript to modify the graveyard value
2. Test when not modified that original graveyard selection still works …

feat(Core): OnBeforeChooseGraveyard Hook

---

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_moam.cpp
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp

Fixes #12901
- Closes #12901
Engage these bosses from >30y range. …

fix(Scripts/AqhQiraj): Increased aggro range for Moam.

---

data/sql/updates/pending_db_world/rev_1661900434005893500.sql

- Links AQ20 trash to their bosses
- Flesh Hunters are not linked
- Closes 
Retail runs
- ~~Not tested yet~~ Tested.
1.
2.
3. …

fix(DB/linked_respawn): Link AQ20 trash spawn

---

data/sql/updates/pending_db_world/rev_1661557402555305100.sql

-  Imports values from Vmangos
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8667
Vmangos
1. `.list c 14222`
2. `.go c` to each spawn point, see if there's only one spawn
3. use the query below and try again, see if they all are wandering correctly
```
DELETE FROM `pool_template` WHERE `entry`=1108 AND `description`='Araga Rare Spawn';
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES (1108, 3, 'Araga Rare Spawn');
``` …

fix(DB/creature): Araga (14222) add spawn points and pooling

---

data/sql/updates/pending_db_world/rev_1662086293864172250.sql

RP event where mobs that attack Ranger Sareyn are missing.
This is a copy (with adjustments to INSERT) of made in TrinityCore https://github.com/TrinityCore/TrinityCore/issues/23538 to fix https://github.com/TrinityCore/TrinityCore/issues/21327 
Related PR https://github.com/azerothcore/azerothcore-wotlk/pull/12724 
Related issue but does not close https://github.com/azerothcore/azerothcore-wotlk/issues/11853
-  Add Fairbreeze Village attack on ranger Sareyn
1. `.go xyz 8678 -6790 94`
2. Observe attack …

 fix(DB/EversongWoods): Ranger Sareyn RP

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp

Fixes #12899
- Closes #12899
- Closes https://github.com/chromiecraft/chromiecraft/issues/3809
Enter AQ40.
Try to engage TBattleguard Sartura at difference distances …

fix(Scripts/Temple of AhnQiraj): Increased aggro range of Sartura.

---

src/server/game/Battlegrounds/BattlegroundQueue.cpp

-  
- ..
- https://github.com/azerothcore/mod-cfbg/pull/113
- cherrypick https://github.com/WarheadCore/WarheadBand/commit/1a3cd2942a88ef64152afeba4d9594237aa962d1
- Locally
1. Just try start bg without debug …

fix(Core/BGQueue): correct start match logic

---

data/sql/updates/pending_db_world/rev_1662835816011805500.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13018
- Closes https://github.com/chromiecraft/chromiecraft/issues/4057
- 
- 
1.
2.
3. …

fix(DB/Quests): One Commendation of Undercity quest (war effort)

---

data/sql/updates/pending_db_world/pathing_for_razorspine.sql

-  Add missing path to razorspine.
- Closes #12989
sniff. thank you @TheDdraig for sniff.
- Tested in game.
1. .go c 39309

fix(DB/Pathing): Add missing path to Razorspine

---

data/sql/updates/pending_db_world/rev_1658948121144924800.sql
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp
src/server/game/Spells/SpellMgr.cpp
src/server/game/Spells/SpellMgr.h
src/server/game/World/World.cpp
src/server/scripts/Commands/cs_reload.cpp
src/server/scripts/Spells/spell_druid.cpp
src/server/scripts/Spells/spell_shaman.cpp
src/server/scripts/Spells/spell_warrior.cpp

-  Implement loading SP Bonus Coefficients from DBC
-  Values that exist in the DB will override the DBC values. I have included SQL file to remove existing DB values that seem that have valid looking DBC values as those should be the most correct.
- Ported from TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/1826437c094966ae339a154844df8587b2122888
- Co-authored by: ariel-
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12510
- Compiles
- Still needs testing
1. Use affected spells (see SQL file) and confirm that damage seems appropriate  …

feat(Core): Implement SP Bonus Coefficients from DBC

---

data/sql/updates/pending_db_world/rev_1662835816011805500.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp

- Update stuff to taskscheduler
- Fix Claw tentacles not submerging
- Implement exit area trigger & center knockback areatrigger
- Use proper carapace spell
- Dont spawn tentacles during weakened phase
- Dont teleport players out of stomach auto once killing flesh tentacles + script the jump thing
- Cthun no longer moves
- Tentacles and other stuff despawn on wipe/death
- Phase transition animation (kind of)

fix(Scripts/TempleOfAhnQiraj): C'thun rewrite

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Corrects fishing skill to have to chance to level even when fishing junk (correct post 3.1 behavior)
-  Also adds a hook that can be used by servers want to re-create the current pre 3.1 behavior.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12116
- Closes https://github.com/chromiecraft/chromiecraft/issues/3619
3.1 Patch Notes
- Still needs testing
1. Fish in high level zone with low level skill
2. See skill up when catching junk
3. Assure skill still can increase when catching fish as well!
To restore old behavior, a PlayerScript can be used. (I like the pre 3.1 behavior better, but that is an opinion ^_^):
```
bool OnUpdateFishingSkill(Player* player, int32 /*skill*/, int32 /*zone_skill*/, int32 chance, int32 roll) override
{
if (chance < roll)
return false; …
```

fix(Core): Correct Post 3.1 Fishing Skill Leveling

---

src/server/game/Mails/Mail.cpp

- Debloat the following by process of elimination since `receiver` won't suddently change and avoid duplicate checks "are we missing `receiver`?".
- Don't do `ObjectAccessor::FindPlayerByLowGUID()` if we don't need it.
- ~~Don't calculate the value of `index` since it is always the same value for each `stmt->SetData(...)`.~~ (cancelled)
- Use directly the value of `mailItemIter->second` instead of putting it into an `Item*`. Same with `CharacterDatabaseTransaction(nullptr)`.
- Closes Nothing.
- Got mails from player.
- Got mails from player with items
- Got mails from GM.
- Got mails from GM with items.
- Got mails from AH.
- Returned mails.
- Deleted mails.
- Checked the returned mails.
Do mail stuff.
You …

chore(Core): Debloat Mail.cpp

---

data/sql/updates/pending_db_world/rev_1662770477382867700.sql

-  Updates Vanilla quest_greetings with new sniff data
-  All values from Vmangos, checked to see if still accurate for WotLK.
- Co-authored by ratkosrb
Vmangos: https://github.com/vmangos/core/commit/0f57a09a64b2df141da4c7af496e50af3c270672
1. .go to any affected creature or gameobject
2. Have multiple quests to ensure greetings text appears
3. Test that it looks correct …

fix(DB): quest_greetings corrections

---

data/sql/updates/pending_db_world/rev_1663289182740404500.sql

-  
-  
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/9571
- Closes https://github.com/chromiecraft/chromiecraft/issues/2500
1. `.go c 14514`
2. attack one, see that others are pulled as well
**For …

fix(DB/creature_formations): Update Fozruk GroupAI to pull together

---

data/sql/updates/pending_db_world/rev_1662891573836958300.sql

Fixes #11894
**Test it with #13006**
- Closes #11894
- Closes #11877
- Closes https://github.com/chromiecraft/chromiecraft/issues/3553
- Closes https://github.com/chromiecraft/chromiecraft/issues/3541
AoE Spells
Go to any cluster of enemies such as .go xyz 2113.280762 -4671.816895 44.418713 1
`.aura 12983` (Shatter talent gives targets hit by FoF +50% chance to be critically hit)
`.aura 44544` (FoF, 2 charges)
Cast any AoE spell such as Blizzard (10), Arcane Explosion (1449) or Flamestrike (2120) at more than one enemy.
See that both charges are aconsumed by Blizzard, Arcane Explosion and Flamestrike.
Immunity/Miss
Immunity:
`.aura 44544` on yourself
`.aura 40733` on target
cast Frostbolt/Frostfire Bolt
Miss:
`.aura 44544` on yourself
attack a higher level target until a …

fix(DB/Spells): Frost of Fingers vs AoE spells.

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core): SMART_EVENT_RANGE

---

src/server/scripts/Spells/spell_hunter.cpp

-  Prevent crash in some edge case of hunter use Readiness
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12980
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12971
- None
1. See if still crash in original situation …

fix(Core): Hunter Readiness crash fix

---

data/sql/updates/pending_db_world/rev_1663648375302333300.sql

-  Update to the correct groupAI for the group formation.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13055
- Tested.
1. Go to Sartura and engage with a hunter.
2. All the group should chase you.

fix(DB/TempleOfAhnQiraj): Sartura formation groupAI

---

data/sql/updates/pending_db_world/rev_1654095984571268900.sql

-  Adjust the gold drop values for many vanilla creatures based on sniffs
- Because the SQL will check that existing gold drop values match before the changing, this will not affect creatures that were changed from Elite to Normal or this type of thing. It will only change creatures that have the same incorrect Vanilla gold values as Vmangos is fix.
Vmangos: https://github.com/vmangos/core/commit/37b12caeb9becf4473096b319e1d69a105e2233f
- N/A
1. Gold drop values are changed …

fix(DB/creature_template): Vanilla gold drop values (credit Vmangos)

---

data/sql/updates/pending_db_world/Shadowpine.sql

-  Add multi id spawns to spawn points
Sniff
- Inserts
1. go to one of the guids ie: .go c guidnumber
2. kill guid and respawn

fix(DB/Spawning) Shadowpine NPCs Ghostlands

---

data/sql/updates/db_world/2022_09_14_03.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB): typo in DB file

---

src/server/scripts/Spells/spell_rogue.cpp

-  Add a check for proc actor
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13103
- 
- 
1. No clue how to reproduce the crash
2.
3. …

fix(Core): Crash

---

data/sql/updates/pending_db_world/rev_1664040930977215800.sql

-  Set the battered brewer's gossip, so it is not empty
-  
- Closes 
https://wowpedia.fandom.com/wiki/Battered_Brewer
1.
2.
3. …

fix(DB/Creature): Set Battered Brewer's gossip

---

data/sql/updates/pending_db_world/rev_1664007070636219300.sql

Fixes #13082
- Closes #13082
- Closes https://github.com/chromiecraft/chromiecraft/issues/4107
- Not tested.
`.go c 88857`
talk to him
select gossip options …

fix(DB/Conditions): Added conditions to Neill Ramstein & Ram Master Ray gossip options. Source: TrinityCore.

---

data/sql/updates/pending_db_world/rev_1663774492767692300.sql
src/server/game/Entities/Item/ItemTemplate.h
src/server/game/Globals/ObjectMgr.cpp

-  Many items in WoW history have negative element resistance, such as https://www.wowhead.com/wotlk/item=9509/petrolspill-leggings, but the current implementation uses unsigned int so negative values aren't support.
-  Changes to support negative values.
- Tested in game, item tooltip successfully shows negative resistance value and resistance drops when item is equipped
1. Add negative resist value to any item
2. Test in game …

feat(Core): Allow negative resistance values

---

src/server/scripts/Events/brewfest.cpp

Fixes #13077
- Closes #13077
- Closes https://github.com/chromiecraft/chromiecraft/issues/4102
- Not tested.
More info [here](#13077) …

fix(Scripts/Brewfest): Fixed race for tokens dailies.

---

data/sql/updates/pending_db_world/rev_1664088625449478500.sql

-  Remove trigger flag from his cleave cast.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4120
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13105
- Closes https://github.com/chromiecraft/chromiecraft/issues/4043
- Not tested.
1. .go c id 5320
2. CC the creature
3. It shouldn't cast cleave anymore while cc or not in range.

fix(DB/SAI): Jademir Boughguard

---

data/sql/updates/pending_db_world/rev_1662088856020689300.sql

- Most values imported from Cmangos
- Others were taken from 15-min sniffs
- Closes unopened issues.
Retail/Cmangos
1.
2.
3. …

fix(DB/SmartAI): Update AQ40 Trash SmartAI.

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp

-  Codestyle.
-  Change the way to get each boss object
-  Don't let bosses dying auto attack.
-  Remove player damage req whenever they heal.
-  Do their final spell after actually dying and not before.
-  Trying to fix an odd case of they dying with all of them dropping loot and not doing their final spell.
-  Fix timers according to sniffs
-  Refactor their death mechanic to be more blizzlike.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4087
- Not tested.
1. Engage bug trio, only one of them should drop loot, the dying creature should not auto attack.

fix(Core/TempleOfAhnQiraj): Bug trio

---

data/sql/updates/pending_db_world/rev_1664637513183204100.sql

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/13147
-  remove wrong items
- Closes 
- 
- 
1. . go c id 24495 and check vendor
2.
3. …

fix(DB/Creature): Blix Fixwidget

---

src/server/scripts/Spells/spell_item.cpp

-  no changes
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Spells): Remove some magic numbers

---

src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp

-  check build
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Anubarak): Convert spellscripts to new system

---

src/common/Collision/Models/GameObjectModel.cpp
src/common/Configuration/Config.cpp
src/server/apps/worldserver/Main.cpp
src/server/game/Achievements/AchievementMgr.cpp
src/server/game/Cache/CharacterCache.cpp
src/server/game/Conditions/DisableMgr.cpp
src/server/game/DataStores/DBCStores.cpp
src/server/game/DataStores/M2Stores.cpp
src/server/game/DungeonFinding/LFGMgr.cpp
src/server/game/Entities/Creature/CreatureGroups.cpp
src/server/game/Entities/Item/ItemEnchantmentMgr.cpp
src/server/game/Events/GameEventMgr.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Groups/GroupMgr.cpp
src/server/game/Guilds/GuildMgr.cpp
src/server/game/Instances/InstanceSaveMgr.cpp
src/server/game/Loot/LootMgr.cpp
src/server/game/Maps/TransportMgr.cpp
src/server/game/Misc/GameGraveyard.cpp
src/server/game/Pools/PoolMgr.cpp
src/server/game/Scripting/ScriptSystem.cpp
src/server/game/Spells/SpellMgr.cpp
src/server/game/Texts/CreatureTextMgr.cpp
src/server/game/Tools/PlayerDump.cpp
src/server/game/Weather/WeatherMgr.cpp
src/server/game/World/World.cpp

-  Updates in the insane inconsistentity on the log of the world server when starting up.
- Closes Incorherent Screech Noises I Make.
- build
- tested
1. Build and load up world server
2. observe
3. or look at dry run …

update (core): Startup console capitalizations

---

data/sql/updates/pending_db_world/rev_1664667583199432200.sql

-  Correct its completion text.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13139
- Closes https://github.com/chromiecraft/chromiecraft/issues/4020

fix(DB/Quest): The Alliance Needs Silk Bandages completion text

---

src/server/game/Spells/Spell.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13228
1.
2.
3. …

fix: Crash

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/SpellEffects.cpp

-  Part of https://github.com/TrinityCore/TrinityCore/commit/d3a71a83387f757f87c7d27e1054498c8cc49c8f
-  https://github.com/TrinityCore/TrinityCore/commit/2e457b3be418ce75b0e0ca901e84ebcdaf02ad18
-  https://github.com/TrinityCore/TrinityCore/commit/5db308b686993653d2bd2861254e10cc1cd5e645
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13217
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13261
1.
2.
3. …

fix(Core/QAston): fixed shields oneshotting

---

src/server/game/Entities/Vehicle/Vehicle.cpp

-  added nullcheck
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13178

fix(Core/Vehicle): Crash

---

data/sql/updates/pending_db_world/rev_1665108660264438400.sql

-  Allows Qiraji Scarabs to also spawn as Qiraji Scorpions and the inverse
- Closes 
Noticed in Retail runs
1. Restart worldserver until you see that a GUID can spawn either …

fix(DB/creature): Add id2 to Qiraji Scarabs/Scorpions

---

data/sql/updates/pending_db_world/rev_1664717737363595400.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13205
- Closes https://github.com/chromiecraft/chromiecraft/issues/4151
- 
- 
1.
2.
3. …

fix(DB/Quest): Morganth

---

data/sql/updates/pending_db_world/rev_1665274040139039300.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  Lower Dark Glare's cone radius to 5 yards
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4478
- 
1. Pull cthun and check if his red beam hits you when you are far off its radius
2.
3.
**For …

fix(Scripts/TempleOfAhnQiraj): Correct Dark Glare's radius

---

.gitignore

- Add ignore all build folder for `Clion`

chore(Gitignore): add ignore all folders `cmake-build-*` for Clion

---

data/sql/updates/pending_db_world/rev_1665344142978704300.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  title
-  
- Closes 
- 
1. Go to p2
2. Get into cthun stomach
3. Notice it stacks with each tick …

fix(Scripts/TempleOfAnhQiraj): Fix Digestive Acid not stacking

---

data/sql/updates/pending_db_world/rev_1665354750522312300.sql

-  Sets bytes2=1 in entries 15275, 15276
- Closes 
Retail, Classic
1. .go c id 15275
2. stand near entrance to start RP, see if their weapons are present …

fix(DB/creature): Set STATE_MELEE to Twin Emperors

---

data/sql/updates/pending_db_world/rev_1665240765400094500.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3697
- Not tested yet.
- 
1. `.go c 33621`
2. `.go c 34520`
3. See if only one spawned. If neither did, restart worldserver and try again. …

fix(DB/pool): Pool Spawn of Hakkar to avoid double spawns

---

data/sql/updates/pending_db_world/springpawpelt.sql

Co-authored by @neifion-00000000 
-  reduces droprate to 45%
- Closes no opened issue
A lot of kills by @neifion-00000000  on retail....
1.
2.
3. …

fix(db/creature): Springpaw pelt should drop less

---

src/server/game/Spells/SpellInfoCorrections.cpp

-  Change spawn from Guardian to none, it caused damage issues.
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): Change spawn mode for Spawn of Fankriss

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp

-  Modified Viscidus combat range to 60yds and Huhuran to 90yds
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): Huhuran and Viscidus combat range

---

data/sql/updates/pending_db_world/rev_1664763129717947000.sql
src/server/scripts/World/npcs_special.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12284
https://www.youtube.com/watch?v=xi2Rvi4VfCs
1.
2.
3. …

fix(Scripts/NPC): Arcanite Dragonling

---

src/common/Banner.cpp
src/common/Banner.h

-  Header consistency with two files
- Closes 

fix (core): Header consistency

---

data/sql/updates/pending_db_world/rev_1665250992619716400.sql

-  And removes loot from Rookery Whelp
- Also removes money drops from Razorgore adds
- Closes https://github.com/chromiecraft/chromiecraft/issues/4074
Vmangos
https://youtu.be/4zRLY2B4UA8 no gold drops
- Not tested yet
- 
1. `.learn 50305` `.setskill 393 450` `.additem 7005`
2. Spawn or teleport to one of the creatures modified by the PR. Try skin them
(12017, 12422, 12435, 13020, 14022, 14023, 14024, 14025, 14988) No skins
(12416, 12420) no gold
(10161, 12422) neither skins or gold …

fix(DB/loot): Remove skinning loot from creatures that shouldn't be skinnable

---

data/sql/updates/pending_db_world/rev_1665269180018074500.sql

- Changes from 300s to 180s
- Closes https://github.com/chromiecraft/chromiecraft/issues/3019
WotLK Classic PTR
- Query runs, checked Keira
1. `.go c id 10919`
2. Kill them and use `.npc info` to check respawn timer …

fix(DB/creature): Adjust Shatterspear respawn timer

---

data/sql/updates/pending_db_world/rev_1665784753998414100.sql
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  fixes tentacle animations
-  cthun spitting out while dead (area trigger)
- jump pad logic
- double spawns in p2
- combat reach of eye and tentacles
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): Fix double spawns during Cthun phase 2 and several other fixes

---

data/sql/updates/pending_db_world/rev_1665799472044108200.sql

-  😤 
-  
- Closes 
- Query runs. Checked Keira
- 
1.
2.
3.

fix(DB/creature_template): Remove gold from Giant Eye Tentacle

---

data/sql/updates/pending_db_world/durotarinsanity.sql

co-authored by @neifion-00000000 
- Adds Food and Water Crates from sniff
- Pools them together in a logical manner to estimate behavior seen
Sniffed/Researched
Tested locally by Neifion, works as expected
.go ga 44477, 44479, 44481, etc noting spawns and pools, no overlaps should be visible and aproximately 2/3rds should be food crates …

 fix(DB/gameobject): Dutotar Food and Water Gameobject Overhaul

---

src/server/game/Entities/Unit/StatSystem.cpp
src/server/scripts/Spells/spell_rogue.cpp
src/server/scripts/Spells/spell_warrior.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13402
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13373
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13369
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13368
- 
- 
1.
2.
3. …

fix(Core/Spells): Overflow damage

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core): Build

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  Set combat range to 90 yds.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13421
- Closes https://github.com/chromiecraft/chromiecraft/issues/4222
- Not tested.
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): C'Thun pull range

---

data/sql/updates/pending_db_world/veknissimpale.sql

co-authored by: @Gultask 
-  remove impale smartscript
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13418
- closes https://github.com/chromiecraft/chromiecraft/issues/4217
- tested …

fix(db/smartscripts): vekniss warrior should not use impale

---

.devcontainer/devcontainer.json
.github/workflows/core_build.yml
.github/workflows/core_matrix_build.yml
src/common/Utilities/StartProcess.cpp
src/common/Utilities/StartProcess.h
src/server/database/Updater/DBUpdater.cpp

- allow to pass MySQL password via env. This will stop the mysql password warning issue 
- fixed devContainer override file issue
- added authserver dry-run in our CI
- Closes 
This:
Instead of this:
1.
2.
3. …

fix(CORE/dbupdate)): allow to pass MySQL password via env

---

src/cmake/googletest-download.cmake

-  Try to fix the compilation test with gcc and googletests
-  Set a static version for the googletest repository
- Closes 
- 
- 
1.
2.
3. …

fix(CORE): gcc compilation errors with gtest

---

.github/workflows/docker_build.yml
.vscode/launch.json
apps/docker/docker-cmd.ts
conf/dist/env.docker

-  Switch from `docker-compose` to `docker compose` that is integrated with docker now
- Implemented a check to make sure that the docker compose version is high enough
- Closes 
- 
- 
1.
2.
3. …

feat(CORE/docker): switch to `docker compose` and check the version

---

src/server/database/Updater/DBUpdater.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix: codestyle CI

---

src/server/game/Entities/Player/Player.cpp

-  Fixed my oversight with the Bindpoint Packet issue i created with the orientation inclusion with homebinding
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13446
- Closes https://github.com/chromiecraft/chromiecraft/issues/4241
- Builds
- Runs
1. Rebind your hearth at any innkeeper
2. Observe hearthstone tool kit showing propper location in the named descriptiong …

Fix (core): SMSG_BINDPOINTUPDATE packet fix

---

data/sql/updates/pending_db_world/bluesackofgems.sql

-  set flags according to the other bags of gems of similar level
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13177
- closes https://github.com/chromiecraft/chromiecraft/issues/3965
- tested …

fix(DB/item_template): Blue sack of gems should not multidrop

---

data/sql/updates/pending_db_world/rev_1666161625586797500.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/SAI): Script Colossus of Zora, Ashi and Regal (AQ War Event npcs)

---

src/server/game/Spells/SpellEffects.cpp

-  Effect Transmit Anticheat Helper
- Closes 

Add (core): Effect Transmit Anticheat Helper

---

data/sql/updates/pending_db_world/rev_1666431872120651800.sql
src/server/scripts/Events/hallows_end.cpp

Fixes #13440
Fixes #13441
- Closes #13440
- Closes #13441
- Closes https://github.com/chromiecraft/chromiecraft/issues/4243
- Closes https://github.com/chromiecraft/chromiecraft/issues/4244
.event start 12
Pick a matron: .go c 20424, 11006, 86848 (Alliance Matrons) 20425, 19346, 17338 (HordeMatrons)
1.Notice only one quest is available
2. Accept the quest "let the fires come" from the matron to attempt to begin the event …

fix(Scripts/HallowsEnd): Fixed starting "Let the fires come" event.

---

data/sql/updates/pending_db_world/rev_1666455090199987000.sql

Fixes #13423
- Closes #13423
be alliance
`.go c 202771`
`.gm off` and run …

fix(DB/Creatures): Timothy Cunningham should be civilian.

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  Adds triggered argument
-  
- Closes 
Warcraft Logs
- 
1. Engage Vek'nilash with 2 characters (15275)
2. Keep both in melee range, see if Uppercut causes an extra melee attack from Vek'nilash …

fix(Scripts/TempleOfAhnQiraj): Prevent Uppercut from triggering Double Attack

---

src/server/game/Globals/ObjectAccessor.cpp
src/server/game/Globals/ObjectAccessor.h
src/server/scripts/Commands/cs_character.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/ObjectAcessor): Fix crash caused by forced character renames

---

data/sql/updates/pending_db_world/rev_1666552438715725700.sql
src/server/game/Entities/Player/Player.h
src/server/game/Miscellaneous/Language.h
src/server/scripts/Commands/cs_character.cpp

-  Allows moving characters from one account to another
-  
- Closes 
- 
1.
2.
3. …

feat(Scripts/Commands): Implement character changeaccount command

---

data/sql/updates/pending_db_world/rev_1666547226677678700.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/Movement): Root the Eye of C'thun

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/TempleOfAhnQiraj): Fix Veklor hitbox

---

src/server/game/Entities/Creature/Creature.cpp

Fixes #13472
- Closes #13472
- Closes https://github.com/chromiecraft/chromiecraft/issues/4270
Have it be Hallow's End / start event 12
.go c 12154
.go c 10998
.go c 85654
.go c 84402
.go c 86858
.go c 128462
.go c 129441
.go c 86846 …

fix(Core/Creatures): Fixed loading transform auras from DB.

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp

fix(scripts/Ouro): Sand Blast threat-wipe mechanic

---

data/sql/updates/pending_db_world/rev_1666968820839009500.sql

-  Add taunt immunity to Ouro and Twins Emperors
- Closes #13565
- Closes #13558 …

fix(DB/creature_template): AQ40 taunt immunity

---

data/sql/updates/pending_db_world/rev_1666399404567254100.sql

-  Adds flag 33554432 to creature 15276
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13553
- Closes https://github.com/chromiecraft/chromiecraft/issues/4308
- 
1.
2.
3. …

fix(DB/creature_template): Add interrupt immunity to Emperor Vek'lor

---

src/server/game/Entities/Object/Object.cpp
src/server/game/Movement/Spline/MoveSpline.cpp
src/server/game/Movement/Spline/MoveSpline.h
src/server/game/Movement/Spline/MoveSplineInit.cpp
src/server/game/Movement/Spline/MovementPacketBuilder.cpp
src/server/game/Movement/Spline/Spline.cpp
src/server/game/Movement/Spline/Spline.h

Closes #2623
- Closes #2623
- Nothing to be tested.

fix(Core/Movement): Removed some leftover after c8f43d85849.

---

src/server/game/Spells/Spell.cpp

Fixes #13179
- Closes #13179
- Closes https://github.com/chromiecraft/chromiecraft/issues/4145
`.learn 403`
learn talents up to Maelstrom weapon 5/5
get 1-4 stacks
auto-melee target
cast lightning bolt …

fix(Core/Spells): Maelstrom Weapon should not reset attack timers.

---

data/sql/updates/pending_db_world/rev_1666516880898803000.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/molten_core.cpp

Fixes #13107
- Closes #13107
- Not tested.
`.go c id 11668`
wait for a Lava Spawn to spawn, once it does, kill the Firelord to prevent more spawns.
observe the Lava Spawn, see if it casts Fireball, and Splits into 2 new Lava Spawns, emotes and despawns afterwards
see what happens if they reach a high number of Lava Spawns …

fix(Scripts/MoltenCore: Lava Spawn.

---

data/sql/updates/pending_db_world/rev_1667137824014916600.sql

-  Set from 55 to 100
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13606
- Closes https://github.com/chromiecraft/chromiecraft/issues/4343
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13608
- Query runs
- 
1.
2.
3. …

fix(DB/creature_loot_template): Fix Burning Legion Missive drop chance

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/TempleOfAhnQiraj): Fix Sartura not enraging if stunned

---

src/server/scripts/Commands/cs_group.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13612
- 
- 
1.
2.
3. …

fix(Scripts/Commands): Fix group list command output

---

src/server/game/Maps/MapUpdater.cpp

This will Log sync db queries in World::Update() loop for the mapupdater when building in debug. Originally part of TC Commit https://github.com/TrinityCore/TrinityCore/pull/25174 Apparently azerothcore never cherrypicked it entirely for whatever reason and is needed when running a debugger in debug build for me to find and address some recent crash issues that been posted on the issues to fully verify the issue.
Co-Authored-By: Giacomo Pozzoni <giacomopoz@gmail.com>
-  Adds in the rest of a apparrenty cherrypick that is needed to debug recent issues.
- Closes 
TC Commit https://github.com/TrinityCore/TrinityCore/pull/25174
- Builds locally
- Tested in debugger when build in debug.
1. Build in debugger
2. Attach Debugger
3. Observe map updater giving warnings of ```Sync query at:``` in …

Add (core\logging): Log sync db queries in mapupdater

---

data/sql/updates/pending_db_world/rev_1667095244859716200.sql

-  Same as the others
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/gameobject): Improve Isle of Quel'Danas gathering nodes and pooling

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Scripting/ScriptDefines/UnitScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

feat(Core/Scripting): Implement OnAuraApply() hook for unitscripts

---

data/sql/updates/pending_db_world/rev_1667341167147160100.sql

-  Sets to 0 (doesn't despawn)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13591
- Closes https://github.com/chromiecraft/chromiecraft/issues/4332
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13609
- Closes https://github.com/chromiecraft/chromiecraft/issues/4346
- 
1. `.quest add 10367` `.quest add 10916`
2. `.go xyz -706 4797 49 530` `.go xyz -698 2749 94 530` …

fix(DB/gameobject): Adjust respawn timers for Hellfire Peninsula quest objects 184466 and 185302

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/TempleOfAhnQiraj): Improve Veklor pathing

---

apps/compiler/includes/functions.sh
env/docker/etc/dbimport.conf.dockerdist
env/docker/etc/worldserver.conf.dockerdist

This PR is needed to allow the [acore-docker ](https://github.com/azerothcore/acore-docker) devserver (and possibly the azerothcore-wotlk devserver) to run without permission errors after the compilation
-  fix  file permissions for the devcontaine

fix(CORE): file permissions for the devcontainer

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp

-  
-  
- Closes 
https://youtu.be/kwlCOViQimA?t=101
https://youtu.be/JHOGWVd7OjQ
https://youtu.be/LZ6c7SCJNm4?t=66
https://youtu.be/xeFmNwU6Lkw?t=52
https://youtu.be/JHCn4qvQ8p4?t=55
- 
1. Engage Sartura with at least 2 characters (`.go c id 15516`)
2. See if she periodically changes targets while Whirlwinding.
3. See if she can be taunted to switch targets. …

fix(Scripts/TempleOfAhnQiraj): Replace Sartura's Gaze mechanic with a threat wipe

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/TempleOfAhnQiraj): Fix Ouro not using abilities if there's only one player and he's out of his melee range

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/TempleOfAhnQiraj): Don't store object references in scripts

---

data/sql/updates/pending_db_world/rev_1667582937946491700.sql

-  Modifies quests Imperial Qiraji Regalia and Imperial Qiraji Armaments
- Closes https://github.com/chromiecraft/chromiecraft/issues/4394
- 
1. .go xyz -8651.15 2025.81 108.66 531
2. Take quests: Imperial Qiraji Regalia, Imperial Qiraji Armaments
3. .quest complete 8789
4. .quest complete 8790
5. Turn in both quests
6. .quest complete 8789
7. .quest complete 8790 …

fix(DB/quest_template_addon): Add repeatable flag to Imperial Qiraji quests

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp

- Closes #13650
- Closes #13649
- Closes https://github.com/chromiecraft/chromiecraft/issues/4304
- Closes https://github.com/chromiecraft/chromiecraft/issues/4300 …

fix(scripts/TempleOfAhnQiraj): Huhuran/BugTrio - EnterCombat

---

data/sql/updates/pending_db_world/repandspawn.sql

-  Shelly gives 5 bloodsail rep and -25 Booty bay (+spillover) Rep
-  Set respawn time to 8 hours
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13200
- Closes https://github.com/chromiecraft/chromiecraft/issues/4149
- Partially fixes https://github.com/azerothcore/azerothcore-wotlk/issues/13201
- killed NPC on local
- 
.go c 1975960
at war with booty bay
/tar high
.damage 4000 …

fix(DB/creature): High Admiral "Shelly" Jorrik Rep and spawn

---

src/server/game/Entities/Player/PlayerStorage.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Includes master looted items
- New hook to keep backwards compatibility with old scripts
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13685
- 
- 
1.
2.
3. …

feat(Core/Scripting): Create OnStoreNewItem() hook

---

src/server/game/Guilds/Guild.cpp
src/server/game/Guilds/Guild.h
src/server/game/Handlers/GuildHandler.cpp

- Fix a bug with almost empty guild bank when there are item changes between the time player login or reload and the first time he opens guild bank (see related issue for screenshots)
- This fix also slightly improve networking performance as we don't send guild bank update packets on guild members who haven't opened it in current session.
- Closes #10026
- Several tests with friends on my server, see next section in order to have more details on tested scenarios.
1. Have at least two players on the same guild with a guild bank having at least one tab
2. Open guild bank on player A and move some items
3. Open guild bank on player B: he should see all items, not only items changed
4. Do a /reload on player B
5. Open guild bank on player B: he should see all items
6. Do a /reload on player …

fix(Core): Fix guild bank update broadcasts

---

data/sql/updates/pending_db_world/casttovictim.sql

-  Changes kidney shot to target victim rather than self
-  Removes Hamstring Ability
- Closes https://github.com/chromiecraft/chromiecraft/issues/4420
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13738
- Closes https://github.com/chromiecraft/chromiecraft/issues/4421
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13740
- checked on local
- 
1. .go creature 202631 …

fix(DB/SAI): Bonechewer Ravener

---

data/sql/updates/pending_db_world/questrepreqs.sql

-  sets required cenarion reputation rep of Watcher Leesa'oh and What's Wrong at Cenarion Thicket? to friendly
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13619
- Closes https://github.com/chromiecraft/chromiecraft/issues/4352
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13620
- Closes https://github.com/chromiecraft/chromiecraft/issues/4353
- tested via gm commands on local
- 
1. .go cr 63513
2. .modify rep 942 1 (neutral)
3. .modify rep 942 3001 (friendly) …

fix(DB/Quest): Zangarmarsh quest rep requirements

---

data/sql/updates/pending_db_world/rev_1667605127641040300.sql

-  Vikki Lonsav should be a General Goods vendor instead of an Innkeeper
https://www.wowhead.com/wotlk/fr/npc=2808/vikki-lonsav#english-comments
- See next section
1. Might need to delete cache
2. `.go c 11807`
N/A …

fix(DB/creature_template_locale): Fix Vikki Lonsav title

---

data/sql/updates/pending_db_world/rev_1667488663408666500.sql

Some quests had missing creatures name, rewards, creatures texts and they were shown in english
wowhead.com/wotlk/es/quest=12919 for example (There is more quests inside)
Valdifer
-  Update/Add some missing esES/esMX locales
- Closes 
Wowhead
- Does it build without errors? Yes
- Did you test in-game? Yes
- What did you test? WG quests, Dalaran quests, Headless Horseman quest, Violet Hold key Item, WG Announcers
1. Execute updates
2. Open the game
3. .additem 42482
4. .event start 12
5. .quest add 11404
6. .quest add 11405
7. .quest add 13222
8. .quest add 13223
9. .quest add 13177
10. .quest add 13179
11. .quest add 13181
12. .quest add 13183
13. .quest add 13158
14. .quest add 13159
15. .quest add 24585
16. .quest add 13178
17. .quest add 13180
18. .quest add 13159
- [Complete the rest …

fix(db/SAI): Missing esES/esMX locales

---

data/sql/updates/pending_db_world/rev_1667951025140607900.sql

- Adds to them flags_extra 33554432
- Closes https://github.com/chromiecraft/chromiecraft/issues/4419
- 
1. .go c id 17455
2. wait 20s for the hounds to spawn
3. See that the hounds do not pull additional packs
**For …

fix(DB/creature_template): Disable Shattered Hand Warhound assistance function

---

data/sql/updates/pending_db_world/Voicelines.sql

-  Swap Jammal'an voice lines to 1 (join us) on cast hex and 0 (The Soulflayer comes!) on aggro
-  Swap Dreamscythe lines 0 (You know not what you do, we must destroy you for your own good!) & 1 (Turn back! Do not wake the Dreamer!) around
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11344
Jammal'an;
https://youtu.be/cdTVc0d4XBw?t=5068
Dreamscythe;
https://youtu.be/f389dEoWdGE?t=10557
- run through dungeon on local
1. .go c 5713 (kill 6 in circle)
2. .go c 5710 (aggro, and wait for hex) 
3. walk back to dreamscythe room and aggro …

fix(DB/SmartAI): Dreamscythe and Jammal'an the Prophet

---

data/sql/updates/pending_db_world/removegossip.sql

-  Removes gossip line "My wind riders are trained to fly quickly through the hot barrens air." from Roetten Stonehammer
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13766
- Closes https://github.com/chromiecraft/chromiecraft/issues/4447
line belongs to Devrak (3615) https://wowpedia.fandom.com/wiki/Devrak
- teleported to on local
- 
1. .go c id 5637 …

fix(DB/Creature): Remove incorrect gossip from Roetten Stonehammer

---

data/sql/updates/pending_db_world/bleed.sql

-  Remove bleed immunity from Twilight Elementalist
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11553
- Closes https://github.com/chromiecraft/chromiecraft/issues/3425
[Asmongold Classic Stream using Rend and not being immune on Twilight Elementalists.](https://youtu.be/snSTzDUNO-s?t=2962)
https://youtu.be/-887Zu5hqJo?t=4646
- tp to mob on local
- 
1. .learn 768
2. .learn 1822
3. .go c 4814 …

fix(DB/creature) Remove bleed immunity from Twilight Elementalist

---

data/sql/updates/pending_db_world/rumblertweaks.sql

-  Removes Rock Shell ability
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11486
https://user-images.githubusercontent.com/11332559/200976702-7e7f8cbd-bf88-4520-86cd-a354e7209a88.mp4
- tested on local 
- 
1. .go c id 4661
2. enter combat and see if they cast rock shell
3. .go c id 4651
4.  kill Gelkis Rumbler
5.  die ( target self and .damage 1000000 ) …

fix(DB/SmartAI): Gelkis Rumbler & Gelkis Earthcaller

---

src/server/game/Entities/Unit/Unit.cpp

-  Superceedes #13505 
`.go c id 22441`
`.die`
`.respawn`
See the mob is flying in the air (instead of falling) …

fix(Core/Creature): Prevent flying creatures from falling on respawn.

---

data/sql/updates/pending_db_world/Closegossip.sql

-  Closes gossip menu on clicking "Absolutely" option at end of rp
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13388
- Closes https://github.com/chromiecraft/chromiecraft/issues/4044
https://youtu.be/xKEshNDHf9Q?t=32
- Checked on local 
1. .go c 137919
2. click through gossip options …

fix(DB/SmartAI): Awbee RP close gossip

---

.github/README.md

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Docs): ReadMe

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_renataki.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix: Renataki crash

---

data/sql/updates/pending_db_world/rev_1667732623534207400.sql

Quest id: 11360, 11439, 11440 were showing the objectiveText in english
https://github.com/azerothcore/azerothcore-wotlk/issues/13676
Valdifer
-  Add esES locales to FireBrigade quests
-  Add esMX locales to FireBrigade quests
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13676
https://www.wowhead.com/wotlk/es/quest=11360/prácticas-para-bomberos
- Executed in SQL (No errors loading SQL file)
- Not tested in game
1. Execute sql
2. .quest start (11360, 11439, 11440)
3. .Look at the objective
4. .quest complete (11360, 11439, 11440)
5. Talk to NPC and read the offer reward
- [Check all stational event quests and complete them if they miss a locale] …

fix(DB/SAI): Missing Fire Brigade Locale esES/esMX

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  From 5 - 12 to 10 - 24
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13647
- Closes https://github.com/chromiecraft/chromiecraft/issues/4312
Retail but not taking failed casts into consideration.
1.
2.
3. …

fix(Scripts/TempleOfAhnQiraj): Increase Vek'lor Blizzard timer

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  Adjust first tp to 30sec
- Closes #13648
- Closes https://github.com/chromiecraft/chromiecraft/issues/4291 …

fix(scripts/TempleOfAhnQiraj): Twins Emperors - First Teleport

---

data/sql/updates/pending_db_world/rev_1668357308398840000.sql

-  Add missing locales in Howling Fjord esES/esMX
- Closes 
wowhead.com
- Build without errors
- Tested quests from SQL
1. .quest start (11262, 12118, 12182, 12297, 12298, 12918, 12952, 13087, 13089, 13206, 13268, 13269)
2. Talk to NPC before complete
3. .quest complete (11262, 12118, 12182, 12297, 12298, 12918, 12952, 13087, 13089, 13206, 13268, 13269)
4. Talk to NPC after complete
- [Complete the rest of zones] …

Fix(DB/Locale) Missing howling fjord locale

---

data/sql/updates/pending_db_world/rev_1667343829848633100.sql
data/sql/updates/pending_db_world/rev_1667346234307893000.sql

-  Remove the duplicate GUID ( 85566 ) of the NPC on the bottom floor and Allows only 86925
- Add Warped Peon missing animations
- https://github.com/azerothcore/azerothcore-wotlk/issues/13634
- https://github.com/chromiecraft/chromiecraft/issues/4362
- https://github.com/azerothcore/azerothcore-wotlk/issues/13633
- https://github.com/chromiecraft/chromiecraft/issues/4361
- 
- 
1. Apply the change in the database and then go to the bottom of the structure
2. For the second case, just use the command .go cr 66764 and look at the npc
**REMEMBER**: …

fix(DB) Pathaleon the Calculator's Image duplicate spawn/ Warped Peon (Missing animation)

---

data/sql/updates/pending_db_world/rev_1667138451660733600.sql

Authored by: https://github.com/ZenoX92
- Adds comments, replaces some SAI
- Replaces some unnecessary casts with creature_template_addon auras
- Some minor adjustments
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13602
- Closes https://github.com/chromiecraft/chromiecraft/issues/4340
- 
- 
1.
2.
3. …

fix(DB/SmartAI): Improve Hellfire SmartAI part 1

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

Reverts azerothcore/azerothcore-wotlk#13796

Revert "fix(Scripts/Temple of AhnQiraj): Cthun's Eye should always focus on b…"

---

data/sql/updates/pending_db_world/rev_1669948633896561800.sql

-  Mob cast ability. Yes.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13984
- 
- 
1.
2.
3. …

fix(DB/SAI): Underbog Lord should cast Knock Away

---

data/sql/updates/pending_db_world/rev_1669943957803991000.sql

-  fix ctm flag so it doesnt move 
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14017
- closes https://github.com/chromiecraft/chromiecraft/issues/4521
- 
- 
1.
2.
3. …

fix(DB/CTM): Fix Vanquished Tentacle of  C'thun moving

---

src/server/game/Achievements/AchievementMgr.cpp
src/server/game/Achievements/AchievementMgr.h

refactor(Core/Achievement): Remove Hungarian notation

---

data/sql/updates/pending_db_world/rev_1669580350948326200.sql

-  Add reset and Nether Leech to SAI
-  Remove mana regen.
-  Set mana to 0 on respawn.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13927
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13923
1. .go c id 20196
2. Check nether leech cast
3. On evade, it should set mana to 0
4. Before combat, it should have 0 mana as well.

fix(DB/SAI): Bloodthirsty Marshfang

---

data/sql/updates/pending_db_world/rev_1670204648623403800.sql

-  
-  
- Closes 
Mangos
- 
1.
2.
3.

fix(DB/gameobject): Add 3 more Box of Surveying Equipment spawns

---

data/sql/updates/pending_db_world/rev_1670154585863356700.sql

Fixes #10256
- Closes #10256
`.go cr 94505` as non-mage char …

fix(DB/Gossips): Show the correct gossip for Ysuria.

---

data/sql/updates/pending_db_world/rev_1670179232683688400.sql

- Corrects typo from '$c' to:
- Closes 
- 
1. .quest add 10990
2.
3. …

fix(DB/SAI): Correct target type for Guardian of the Eagle SAI

---

data/sql/updates/pending_db_world/rev_1670201379035894100.sql

-  Adds unit_flags immune to PC and NPC
-  
- Closes 
- 
1. .quest add 9824
2. .go c id 18161
3. …

fix(DB/creature_template): Prevent Underground Well Credit Marker from attacking the player

---

data/sql/updates/pending_db_world/rev_1670203739787100600.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/creature_template): TBC Gas Clouds shouldn't be selectable

---

src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp

-  Mark optional boss as completed when it dies
-  Cherry-picked from TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/08d2b6743a7b5c7be1ab0da8d4da704fd477f38e
- Co-authored by Shauren
https://github.com/TrinityCore/TrinityCore/commit/08d2b6743a7b5c7be1ab0da8d4da704fd477f38e
- Not yet tested
1. Defeat optional boss
2. Restart server, load instance data
3. Ensure boss is still defeated …

fix(Scripts/Karazhan): Mark optional boss as completed when it dies

---

data/sql/updates/pending_db_world/rev_1670025626681890300.sql

Should be spawned by summoner instead (Feralfen Hunter)
-  Removes unnecessary Tamed Sporebat spawns
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13622
- 
1.
2.
3. …

fix(DB/creature): Remove redundant Tamed Sporebat (18201) spawns

---

data/sql/updates/pending_db_world/rev_1670022799341664800.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13916
- 
clear cache
.quest add 10172
.quest comp 10172
.quest add 10212
.go quest ender 10212
see if only Hero of the Mag'har rewards items
**For …

fix(DB/quest_template): Remove rewards from quest There Is No Hope (10172)

---

data/sql/updates/pending_db_world/rev_1670020658434932300.sql

-  Adds quest Forge Camp: Annihilated (10011) to Exclusive group -9868 (previously 0)
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13886
- 
.go cr 63870
.quest add 9868
.quest add 9934
.quest comp 9868
.quest comp 9934
Check if the quest "A Visit With the Greatmother" is available
.quest rem 9868
.quest rem 9934
.quest add 10011
.quest comp 10011
.go quest ender 10011
.go cr 63870
Check if the quest "A Visit With the Greatmother" is available
Complete all the quests above. See if quest "A Visit With the Greatmother" is now available. …

fix(DB/quest_template_addon): A Visit With the Greatmother shouldn't be available without completing all prerequisites

---

data/sql/updates/pending_db_world/rev_1668934585006062000.sql

Fixes #13790
- Closes #13790
- Not tested.
`.tele mt`
`.go cr 83305`

fix(DB/SAI): Crypto Raider should cast Enrage at <20% hp.

---

data/sql/updates/pending_db_world/rev_1669577451671502900.sql

-  Add Net to their SAI.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13928
1. .go c id 18113
2. Engage and wait until it casts Net.

fix(DB/SAI): Feralfen Hunter should cast Net

---

data/sql/updates/pending_db_world/rev_1668949092326733600.sql

Fixes #13818
- Closes #13818
- Not tested.
`.go creature 138152`
kill surrounding enemies
drop combat
engage npc from a distance
observe behaviour …

fix(DB/SAI): Hellfire Imp SAI. Source: TrinityCore.

---

data/sql/updates/pending_db_world/baristolth-badge.sql

-  Adds a gossip option and SAI to restore the [Agent of Nozdormu](https://www.wowhead.com/wotlk/item=20402) badge for a player that has deleted it but completed [the quest](https://www.wowhead.com/wotlk/quest=8301) for it.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4075
- Might do the same for https://github.com/chromiecraft/chromiecraft/issues/4448.
Wrath Classic.
- Tested locally.
1. `.tele cenarionhold`
2. `.quest add 8301`
3. `.quest complete 8301`
4. `.quest reward 8301`
5. Delete the [badge](https://www.wowhead.com/wotlk/item=20402).
6. Talk to [Baristolth](https://www.wowhead.com/wotlk/npc=15180) throughout all of these steps.
7. Observe the now available (and working) gossip option on doing step 5. …

fix(DB/SAI): Baristolth of the Shifting Sands Agent of Nozdormu restoration.

---

data/sql/updates/pending_db_world/smartaitoaura.sql

-  Instead of casting on respawn of similar, stealth detection 18950 is added via aura to creatures and their spawn addon
-  some Smartai shuffled around so that ID's are still sequential
- No issue, ive just been advised this is the better way to do it
https://github.com/azerothcore/azerothcore-wotlk/pull/13826#issuecomment-1313938911
- teleported to mobs on local
- 
1. go c 
(  3502, 4624, 9460, 11190, 12160, 14378, 15184, 16504, 16580, 16590, 16591, 16599, 17493, 17558, 17727, 17958, 18103, 19048, 19355, 19425, 19426, 19432, 19562, 19836, 22134, 24043, 25507, 27162, 30737 )
3. .list aura
4. SELECT \`entryorguid\` FROM \`smart_scripts\` WHERE \`action_param1\`=18950 …

fix(DB/SmartAI): Convert smartai stealth detection buff to Aura

---

src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp

Fixes #13825
- Closes #13825
- Closes https://github.com/chromiecraft/chromiecraft/issues/4498
`.go xyz 455.738464 48.713467 9.616814 542 1.231426`
start the gauntlet & complete it
observe broggok using poison cloud
**For …

fix(Scripts/BloodFurnace): Fixed Broggok not casting Poison Cloud.

---

src/server/game/Entities/Unit/Unit.cpp

Fixes #12849
- Closes #12849
Talk to Airae Starseeker and get At The Enemy's Gates quest
Equip Argent Lance
Use mount skills to kill mobs …

fix(Core/Players): Fixed awarding kill credit while being on vehicles.

---

data/sql/updates/pending_db_world/addquestreward.sql

-  Add Plans: Copper Chain Vest as quest reward  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4500
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13932
- completed quest on local
- 
.quest start 1578
.quest complete 1578
.go c id 6030 …

fix(DB/Quest): Supplying the Front quest reward

---

data/sql/updates/pending_db_world/rev_1669742453928322100.sql

- Large Coffer Pools increased based on Retail Sniffs
- Closes 
Retail, Cmangos
- Query runs
- 
1.
2.
3. …

fix(DB/loot): Adjust AQ40 Idols and coffers

---

src/server/game/Entities/Unit/Unit.h
src/server/game/Movement/MotionMaster.cpp
src/server/game/Movement/MotionMaster.h
src/server/game/Movement/MovementGenerator.h
src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.h
src/server/game/Movement/MovementGenerators/EscortMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/EscortMovementGenerator.h
src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/HomeMovementGenerator.h
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.h
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/RandomMovementGenerator.h
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp

Reverts azerothcore/azerothcore-wotlk#13989
Causes issues with propagation of movement updates. Needs to be breaken down by parts so the issue can be identified

Revert "refactor(Core/Movement): Naming convention"

---

data/sql/updates/pending_db_world/remove-black-pearl-ring-in-red-sack.sql

-  Remove [Black Pearl Ring](https://wotlkdb.com/?item=6332) from [Red Sack of Gems](https://wotlkdb.com/?item=17969).
- Closes none, I didn't bother opening an issue.
[Wowpedia](https://wowpedia.fandom.com/wiki/Black_Pearl_Ring) only says it drops from [Lady Vespira](https://wowpedia.fandom.com/wiki/Lady_Vespira).
Wotlk Wowhead loot tables also shows the same ([Black Pearl Ring](https://www.wowhead.com/wotlk/item=6332/black-pearl-ring)/[Red Sack of Gems](https://www.wowhead.com/wotlk/item=17969/red-sack-of-gems)).
- `.additem 17969 10`
- Opened them. I got none. They used to have a 100% drop chance.
1. `.additem 17969` …

fix(DB/loot): `Black Pearl Ring` wrongly drops

---

.github/workflows/build_dbimport.yml

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(build): build-db

---

data/sql/updates/pending_db_world/rev_1669583140592514600.sql
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp
src/server/scripts/Spells/spell_generic.cpp

Co-authored-by: Eridium <killyana@users.noreply.github.com>
Co-authored-by: Lucas Nascimento <keader.android@gmail.com>
-  https://github.com/TrinityCore/TrinityCore/commit/3432edf3dc1b6bda671c18b8baa40b9bdf0d824b
-  https://github.com/TrinityCore/TrinityCore/commit/990ad000f8e869e55353e6531d9e38f23104bcd6
-  Add mechanic immune mask to Rajis Fyashe.
-  Fix Bloodscale Enchantress SAI
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13931
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13930
1. .go cr 63990
2. Engage and see if it casts Freezing Circle.
3. Go to Pit of Saron, clean up to the second boss, wait until Tyrannus spawns a Wrathbone Coldwraith, engage it and see if it casts freezing circle and if it works properly/do the correct …

fix(Core/Scripts): Bloodscale Enchantress/Rajis Fyashe freezing circle

---

data/sql/updates/pending_db_world/nighthaven-mailbox.sql

- Adds mailbox in Nighthaven, Moonglade based on sniffed values.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4473.
Wrath Classic live sniffs.
- Untested.
2. `.go xyz 8005.35 -2671.04 512.1 1`
3. Observe the mailbox where it should be according to the related issue. …

fix(DB/gameobject): Add Mailbox in Nighthaven.

---

data/sql/updates/pending_db_world/rev_1670828923247478600.sql

-  A couple more adjustments in Tirisfal Glades, most of this zone did not need it, and is noted in the SQL.
retail for sanity checking + wowhead
- Rare mobs aren't included here …

fix(DB/loot): Improve Tirisfal Glade unique drops

---

data/sql/updates/pending_db_world/ruru-quest.sql

- Adds ruRU localization for CompletedText to quests 945, 1011, 1022, 1025, 1034, 1035, 1134, and 9517 and ObjectiveText to quest 9544.
- Closes #14145
- Closes #14146
- Closes #14159
- Makes progress towards #14147
- Makes progress towards #14148
- Makes progress towards #14174
- Makes progress towards #14183
- Makes progress towards #14184
- Makes progress towards #14185
Wrath Classic live sniffs.
- Untested.
2. Start the game with ruRU localization.
3. `.quest add` the related quests.
4. Observe Russian objective texts. …

fix(DB/quest_template_locale): Add some ruRU localization to multiple quests.

---

src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/SAI): Align SAI headers with TrinityCore

---

data/sql/updates/pending_db_world/rev_1671323007498257700.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14256
- Closes https://github.com/chromiecraft/chromiecraft/issues/4581
- 
- 
1.
2.
3. …

fix(DB/loot): Remove Fel Spirit (22454) loot

---

data/sql/updates/pending_db_world/terrorclaw.sql

-  reduce spawn time from 21 minutes to 7 minutes 30 seconds
-  
- Closes no adressed issue
WOTLK Classic PTR …

fix(DB/creature): Corrected Spawn Time Terrorclaw

---

data/sql/updates/pending_db_world/rev_1671397695840437500.sql

fix(DB/SAI): Workaround bad model for Void Spawner L

---

data/sql/updates/pending_db_world/rev_1670828439307255000.sql

-  A few tiny changes to a couple Mulgore rates as listed in the code
Classic/Wowhead comparison, it might be even lower than this but this is an improvement.
- This is PR looks at all the Mulgore unique loot not off rare mobs/vendor/etc, though it does not change them all as some looked fine as is. …

fix(DB/loot): Improve Mulgore zone unique items

---

data/sql/updates/pending_db_world/rev_1671056695826995700.sql

-  Sets state to 1 from 0
- Closes https://github.com/chromiecraft/chromiecraft/issues/4555
- Tested ingame before and after
1.
2.
3. …

fix(DB/gameobject): Correct state for 5 herbalism nodes

---

data/sql/updates/pending_db_world/rev_1671138587360304900.sql

-  Some improvement on some Hellfire quest drop rates (specifically https://www.wowhead.com/wotlk/item=23269/felblood-sample and https://www.wowhead.com/wotlk/item=30425/bleeding-hollow-blood)
- Further research is warranted but it should end up being higher than this not lower if it's wrong.   …

fix(db/loot): Hellfire quest loot improvements

---

data/sql/updates/pending_db_world/rev_1671210972250683700.sql

-  Morph Honor Hold Scout Archery Target into id 16925 on respawn
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4557
- Tested ingame with 3 worldserver restarts
- 
1. `.tele shatterpoint`
2.
3. …

fix(DB/SAI) Morph Honor Hold Scout Archery Target into correct modelid on respawn

---

data/sql/updates/pending_db_world/rev_1671217721798848700.sql

- Changes from NONE to closest player
- Replace comments
- Closes https://github.com/chromiecraft/chromiecraft/issues/4564
- 
1. change timers in the last row to something low
2. .go c id 19283 …

fix(DB/SAI): Correct Vagrant 19283 target_type

---

data/sql/updates/pending_db_world/rev_1671221785210348000.sql

- Corrects onkill rep for both normal and heroic versions based on WotLK and Retail data
- Closes https://github.com/chromiecraft/chromiecraft/issues/4559
- 
1. `.npc add temp 17540`
2. kill, see 1 rep
3. modify rep to 8999
4. repeat step 1, see no rep
5. `.npc add temp 18056`
6. see rep gain of 2 at no limit …

fix(DB/creature_onkill_reputation): Fiendish Hound

---

data/sql/updates/pending_db_world/rev_1671392360824482200.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4603
- 
- 
1.
2.
3. …

fix(DB/creature): Fix Dreadfang Widow bad Z coord

---

data/sql/updates/pending_db_world/rev_1671392697767302400.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4594
- 
- 
1.
2.
3. …

fix(DB/creature_template): Add trigger flag to Credit Marker: Water

---

src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #14241
- Closes #14241
- Closes https://github.com/chromiecraft/chromiecraft/issues/4567
`.quest add 10538`
`.add 30425 10`
`.go xyz -974.5 2165 15.91 530 1`
Use Cursed Cauldron …

fix(Core/Spells): Cursed Cauldron gobs despawn after 5 seconds.

---

data/sql/updates/pending_db_world/rev_1671751333190578800.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14334
- Closes https://github.com/chromiecraft/chromiecraft/issues/4605
Cmangos
- 
1. .npc add temp 17000
2.
3. …

fix(DB/SAI): Aggonis In Combat spells

---

data/sql/updates/pending_db_world/rev_1671666534424139900.sql

-  Correct skinning loot
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14318
- Closes 
Mainly https://www.wowhead.com/npc=21723/blackwind-sabercat
- 
1. .learn 50305
2. .setskill 393 450
3. .additem 7005
4. .go cr 75894 …

fix(DB/loot): Blackwind Sabercat

---

apps/installer/includes/os_configs/osx.sh

-  workaround for the current issue with brew python upgrade in github runners https://github.com/actions/runner-images/issues/6817
- Closes 
- CI …

fix(MACOS/CI): configure os

---

data/sql/updates/pending_db_world/rev_1665237212810221500.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9514
1.
2.
3. …

fix(DB/Scripts): Npc Tonk Control Console

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Handlers/CharacterHandler.cpp

- Remove the character from cache at the end of `Player::DeleteFromDB()`
- This ensures that the cache is always cleared when deleting a character. For example the `.character erase` command didn't clear the cache after deletion.
Compiled and tested on Windows 11 …

feat(Core/Player): delete character cache in Player::DeleteFromDB()

---

data/sql/updates/pending_db_world/bearwalker.sql

-  Removes the right claw occupying [Mathrengyl Bearwalker](https://www.wowhead.com/wotlk/npc=4217)'s left hand.
[World of Warcraft: Classic](https://youtu.be/4tMZjrxnTb0?t=297).
- Ran on local AC, observed in-game.
2. `.go c id 4217`
3. Observe. …

fix(DB/creature_equip_template): Remove Mathrengyl Bearwalker's Left Right Claw.

---

data/sql/updates/pending_db_world/dartols-rod.sql

- Adds new gossip menu, updates actionmenuID for gossip, removes vestigial smartscript stuff, and corrects a condition for [Raene Wolfrunner](https://www.wowhead.com/wotlk/npc=3691)
- Closes https://github.com/chromiecraft/chromiecraft/issues/4532
Wrath Classic live/PTR.
2. `.tele astranaar`
3. `.quest add 1029`
4. `.quest reward 1029`
5. If you have the [rod](https://www.wowhead.com/wotlk/item=5462), delete it now.
6. Interact with Raene and observe the added gossip menu. …

fix(DB/Gossip): Add gossip text, sub-menu, and correct condition for Raene Wolfrunner.

---

data/sql/updates/pending_db_world/rev_1671211355184764600.sql

-  Add Civilian flag to named Expedition Point NPCs
-  Adds SAI to Corporal Ironridge
- Closes https://github.com/chromiecraft/chromiecraft/issues/4568
Testing in Retail, I've tried several times to see if Corporal Ironridge's gender could change on respawn but I'm pretty certain that's not the case. This needs to be investigated further to see if we could be missing a field.
- 
1. `.tele expeditionpoint`
2.
3. …

fix(DB/SAI): Corporal Ironridge

---

data/sql/updates/pending_db_world/rev_1671752272097509400.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14330
- Closes https://github.com/chromiecraft/chromiecraft/issues/4623
Retail
- 
1. `.go c 65943`
2.
3. …

fix(DB/creature): Change bad id1 from Veil Skith

---

data/sql/updates/pending_db_world/MissingDiplomat

-  Decreased each value in event_flags by 512
- Closes https://github.com/chromiecraft/chromiecraft/issues/599
- [missingDiplomat.webm](https://user-images.githubusercontent.com/82369562/209441845-0442177a-e1a8-4a74-9f0f-46169e35b298.webm)
1. `.go c 9432` Mikhail
2. `.quest add 1248` Missing diplomat
3. go outside and kill Tapoke "Slim" Jahn (entry= 4962)
4. go back to Mikhail, small talk, and complete the quest easily …

fix(DB/smart_scripts): Fix Tapoke "Slim" Jahn's event_flags

---

data/sql/updates/pending_db_world/remove-mold-key.sql

-  Remove [Primed Key Mold](https://wotlkdb.com/?item=31245) from [Coilfang Emissary](https://wotlkdb.com/?npc=18681)'s loot table.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14364
- Closes https://github.com/chromiecraft/chromiecraft/issues/4576
That item is normally provided for quests [Grand Master Dumphry](https://wotlkdb.com/?quest=10762) (Ally) or [Grand Master Rohok](https://wotlkdb.com/?quest=10756) (Hordies).
- No longer drop, killed 5-7 times.
```SQL
SELECT *
FROM creature_loot_template
WHERE Item = 31245
``` …

fix(DB/Loot): Remove `Primed Mold Key` from `Coilfang Emissary`

---

src/server/game/Achievements/AchievementMgr.h
src/server/game/Entities/Player/Player.h

- Move `GetAchievementMgr()` and `GetCriteriaProgress()` to public
Required by https://github.com/azerothcore/mod-eluna/pull/78
N/A
- Compiled on Windows 11, used `GetCriteriaProgress()` from Eluna without issues.
N/A
N/A …

feat(Core): move achievement manager and criteria progress getters to public

---

data/sql/updates/pending_db_world/blinkeythefaydrake.sql

Co-authored by @Gultask 
-  set correct flags and target
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14080
- tested …

fix(DB/SmartScript): Fey Drake should blink behind target

---

data/sql/updates/pending_db_world/hewillwalktheearth.sql

-  Add quest rewards
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14381
- Closes https://github.com/chromiecraft/chromiecraft/issues/4676
not tested 
.quest add 9866
.quest complete
.go c id 18067 …

fix(DB/Quest): 'He Will Walk The Earth' Should have quest rewards

---

data/sql/updates/pending_db_world/tamedravagerbegone.sql

-  Remove extra tamed ravager spawns, as they are only summoned.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14301
- Closes https://github.com/chromiecraft/chromiecraft/issues/4583
- tested …

fix(DB/Creature): Remove Tamed ravager spawns

---

data/sql/updates/pending_db_world/fenstrider.sql

-  set correct quest required
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14400
- Closes https://github.com/chromiecraft/chromiecraft/issues/4683
- not tested
- 
https://www.wowhead.com/tbc/quest=9801/gathering-the-reagents#comments
https://www.wowhead.com/tbc/item=24427/fen-strider-tentacle#comments
.go cr 64813
Kill Fen Striders without the quest until it drops (it shouldn't)
test again with quest to see if it drops. …

fix(DB/Loot): Fen Strider Tentacle should only drop when on quest

---

data/sql/updates/pending_db_world/rev_1672338781776631800.sql

-  Improves Kil'sorrow coin using values gathered by Sam and I
- Closes 
Retail classic sniff and general research
- 
- 
1.
2.
3. …

fix(db/creature_template): Improve Kil'sorrow Coin

---

data/sql/updates/pending_db_world/neophyteguardianbegone.sql

- Remove spawn of Neophyte guardian as its not there on Wotlk Classic
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14292 …

fix(DB/Creature): Remove Neophyte Guardian spawn

---

src/server/game/OutdoorPvP/OutdoorPvP.h
src/server/scripts/OutdoorPvP/OutdoorPvPNA.h

-  expose Halaa slider value and owner setter for https://github.com/azerothcore/mod-eluna/pull/79
Co-authored by @r-o-b-o-t-o 
- Closes //
- Took Halaa with each faction from Neutral to both and from Ally to Horde and Horde to Ally
- Used setter and getter
1.
2.
3. …

feat(Core/scripts): expose Halaa slider value and owner setter

---

data/sql/updates/pending_db_world/bonelasher-oob.sql

- Removes two [Bonelashers](https://www.wowhead.com/wotlk/npc=18470) from the walls of Auchindoun.
It's simply illogical!
- Untested.
2. `.go xyz -3381.7 4616.8 -22.4 4.3`
3. Turn on nameplates.
4. Observe a lack of Bonelashers inside walls. …

fix(DB/creature): Remove Bonelashers inside of a wall.

---

data/sql/updates/pending_db_world/nagaclaws.sql

-  change dropchance of nagaclaws to 100%
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14399
- Closes https://github.com/chromiecraft/chromiecraft/issues/4686
.quest add 9728
.tele bloodscale
Kill nagas 
**For …

fix(DB/Loot): Naga claws should drop 100%

---

data/sql/updates/pending_db_world/rev_1671665943141414400.sql

Authored by: @Saben65
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14005
- Closes https://github.com/chromiecraft/chromiecraft/issues/4508
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5641
https://github.com/TrinityCore/TrinityCore/issues/16214
- 
1.
2.
3. …

fix(DB/Gossip): Remove empty data from Archmage Leryda gossip

---

data/sql/updates/pending_db_world/prospectada.sql

-  Set data according to Mangos WOTLK data.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14441
- Closes https://github.com/chromiecraft/chromiecraft/issues/4691
WOTLK Mangos
- Tested …

fix(DB/Loot): Prospecting Adamantite adjustment

---

data/sql/updates/pending_db_world/rev_1672587681948762700.sql

Fixes #13990
- Closes #13990
`.go cr 138500`

fix(DB/SAI): Swamplord Musel'ek prefers ranged attacks than melee.

---

data/sql/updates/pending_db_world/nagrandgoldfix.sql

-  Fixes gold drop rates of following mobs in nagrand:
Boulderfist Crusher
Boulderfist Mystic
Windyreed Scavenger
Windyreed Wretch 
Warmaul Brute
Warmaul Warlock
Warmaul Reaver
Warmaul Shaman
Murkblood Putrifier
Murkblood brute
Murkblood Scavenger
Murkblood Raider
Ortor of Murkblood (limited dataset)
Agitated Orc Spirit
Vir'aani Arcanist
Vir'aani Raider
Voidspawn
Terrorguard
Subjugator Vaz'shir (limited dataset)
Kil'sorrow Ritualist
- Closes no open issue
WOTLK PTR, based on minimum on average  15 kills per mob type. 
**REMEMBER**: when testing …

fix(DB/loot): Nagrand gold drop fixes

---

data/sql/updates/pending_db_world/auchenaideathspeakerdoomsayer.sql

-  Set mingold and maxgold 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14312
- Closes https://github.com/chromiecraft/chromiecraft/issues/4634
Based on manually killing mobs on WOTLK PTR
```
doomsayer
16,11
15,37
15,15
14,44
13,84
13,32
12,71
12,46
12,44
12,13
11,99
11,58
11,58
10,28
9.78
9,49
9,40
7,37
6,86
3,96
2,72
2,70
death speaker
15,47
14,74
13,67
13,16
12.59
11,45
11,38
10,07
9,82
9,02
8,78
7,89
6.54
6,02
5,85
5.84
5,13
4,63
3,67
3,65
3,38
3,03
2,59
```
- Tested …

fix(DB/Loot): Auchenai Death-Speaker/Doomsayer money drop

---

data/sql/updates/pending_db_world/rev_1672587966569522600.sql

Fixes #13981
- Closes #13981
- Not tested.
need 2+ characters
`.go cr 138465` …

fix(DB/SAI): Fen Ray should cast Psychic Horror on random target.

---

data/sql/updates/pending_db_world/update-crypt-guard.sql

-  Change target_type
-  Add SAI description
- Crypt Guard was not applying Acid Spit in the victim
- Tested …

fix(DB/smart_scripts): Fix Crypt Guard's Acid Spit

---

src/server/game/Grids/Notifiers/GridNotifiers.h

Fixes #13514
- Closes #13514
- Closes https://github.com/chromiecraft/chromiecraft/issues/4275
`.tele bloodfurnace`
`.go c id 17414`
Run over mines. Some will blow up, some won't. …

fix(Core/Gameobjects): Fixed LoS for traps summoned by creatures.

---

data/sql/updates/pending_db_world/felcannon.sql

-  Add proper smart script ported from Vmangos
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14420
- Closes https://github.com/chromiecraft/chromiecraft/issues/4699
Some kind of mango
- Tested …

fix(DB/Creature): Fel Cannon should be stationary and shoot

---

src/server/game/Loot/LootMgr.cpp

- Should fix https://github.com/chromiecraft/chromiecraft/issues/4542

fix(Core/Loot) Fix master looter invisible quest items

---

data/sql/updates/pending_db_world/rev_1672481631730954800.sql

Fixes #14395
- Closes #14395
`.q a 14107`
`.go xyz 7856.000488 2170.591797 370.094208 571`
`.additem 47035`
Use Light-Blessed Relic for Fallen Hero's Spirit …

fix(DB/SAI): Fixed Fallen Hero's Spirits not giving kill credit.

---

data/sql/updates/pending_db_world/rev_1672780892044441400.sql

-  Sniffs, adds and pools gatherables for Auchenai Crypts, Sethekk Halls and Shadow Labyrinth
- Closes 
Retail Sniffs, 10 runs each
1. .tele auchenai
2. .tele sethekk
3. .tele shadowlab …

fix(DB/gameobject): Rebuild gameobjects for the remaining Auchindoun instances

---

data/sql/updates/pending_db_world/rev_1672333160913910400.sql

-  https://youtu.be/0HJc7BlHjVg
- Implements one missing story.
- Randomizes the event each time it plays (can repeat)
- properly times it
- Fixes emoteState
- Fixes positions
- Closes 
- 
1. `.go c id 20344`
2.
3.
**For …

fix(DB/SmartAI): Implement Hal McAllister and Nat Pagle event in Old Southshore

---

data/sql/updates/pending_db_world/rev_1672205660081542200.sql

-  Implements the event entirely from Retail sniffs
-  Fixes the Blizzlike bug where Kel'thuzad and Helcular won't face each other
-  The event has a 2% chance of occurring at each waypoint. Calculated from a sniff where 12 events and 600+ waypoints were seen. I can confirm that the event can play at multiple waypoints.
- Closes 
Retail
- 
1. Use this query to change the chance of the event:
```
UPDATE `smart_scripts` SET `event_chance`=50 WHERE  `entryorguid`=20350 AND `source_type`=0 AND `id`=1;
```
2. `.go c id 20350` …

fix(DB/SAI): Implement Kel'Thuzad and Helcular RP event in Old Hillsbrad Foothills

---

data/sql/updates/pending_db_world/rev_1672240491963126000.sql

- Sniffs and implements the scene accordingly
- repeats every 3mins
- Adds equipment
- Corrects spawn positions
- Attempts to fix some blizzlike bugs
- Closes 
Retail sniffs
- Tested ingame. See: https://youtu.be/9fr6RxLm6MY
- 
1. `.go c id 20351`
2. wait and observe …

fix(DB/SAI): Implement Captain Sanders and Edward Hanes RP event in Old Hillsbrad Foothills

---

data/sql/updates/pending_db_world/helgrim-esesmx.sql

- Adds esES/esMX quest greeting to [Apothecary Helgrim](https://www.wowhead.com/wotlk/npc=3390).
- Closes #14480
- Closes https://github.com/chromiecraft/chromiecraft/issues/4407
Wrath Classic PTR, both [esES](https://user-images.githubusercontent.com/38561765/210300489-fade2db1-ee80-47e9-9a8c-e6e9cfdd5ce1.png) and [esMX](https://user-images.githubusercontent.com/38561765/210300433-a3e22b2c-a09b-46ed-ac05-6ee636861b66.png) locales.
- Untested.
1. Log in with an esES/esMX client.
2. `.tele crossroads`
3. Interact with Helbrim. …

fix(DB/quest_greeting_locale): Add esES/esMX quest greeting to Apothecary Helbrim.

---

data/sql/updates/db_world/2023_01_05_02.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(SQL): Rerunnable stuff

---

src/server/game/Entities/Pet/Pet.cpp

-  Increase the model size if scale is > 1.f
Does not change scale for pets that have a scale < 1
Bigger for those with > 1.f
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/14488
- 
1. Tame a beast
2.
3. …

fix(Core/Pets): Correct Pet size for bigger pets

---

apps/installer/includes/functions.sh

-  Update the defined client data files version to v16
- Closes 
- 
- 
1.
2.
3. …

fix(Apps): Update client data version

---

data/sql/updates/pending_db_world/rev_1672970916826961100.sql
src/server/scripts/Outland/zone_terokkar_forest.cpp

Co-authored-by: Andrew Letson <velinath@users.noreply.github.com>
-  Move script to SAI
-  SAI From TrinityCore Partial CP of https://github.com/TrinityCore/TrinityCore/commit/4d338b1d4d6ddf449e52c38f6cb9cdeb9cbf32fe
- Closes https://github.com/chromiecraft/chromiecraft/issues/4743
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14490
- 
- 
1.
2.
3. …

fix(DB/Creature): Infested Root-Walker

---

data/sql/updates/pending_db_world/rev_1673095047755497100.sql
src/server/scripts/Outland/CoilfangReservoir/underbog/underbog.cpp
src/server/scripts/Outland/outland_script_loader.cpp

Fixes #13977
- Closes #13977
`.go cr 138337`
`.tele underbog`
`.go xyz 280.749817 -169.079193 36.874214` …

fix(Scripts/Underbog): Fixed Fungal Decay spells.

---

data/sql/updates/pending_db_world/rev_1670753866467974200.sql
src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp

Fixes #8744
- Closes #8744
- Not tested.
`.go c 86195`
combat with Halazzi

fix(DB/Texts): Added texts to Halazzi.

---

data/sql/updates/pending_db_world/changes.sql

-  Adds immunity to multiple types of CC
-  Decreases spawn timer to 60 seconds
-  Allows mortal strike ability to be cast multiple times
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13881
- Checked on local
1. .go c id 18423
2. .damage 20000
3. check that he casts mortal strike more than once
4. kill and check spawn time …

fix(DB/Creature): Cho'war the Pillager

---

src/server/game/Entities/Pet/Pet.cpp

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/14525
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Creature): Check model increase only for Exotic creatures

---

data/sql/updates/pending_db_world/rev_1672970116654820600.sql
src/server/scripts/Spells/spell_item.cpp

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/13067
-  Pets should probably have the same restrictions as their owner. But before that is investigated this is a temporary fix
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Script/Item): Elixir of Shadows for pets

---

data/sql/updates/pending_db_world/rev_1673358485783743300.sql

-  Ports from Mangos
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4793
Cmangos-Wotlk
- 
1.
```
UPDATE `item_template` SET `lockid` = 0 WHERE (`entry` = 29569);
```
2. add 4 Foror's Crate
3. .add 29569 150
4. Make a macro /use Strong Junkbox
5. Set auto-loot in the Controls section of the options menu
6. spam …

fix(DB/Loot): Strong Junkbox

---

src/server/game/Globals/ObjectMgr.cpp

* fixed in https://github.com/azerothcore/azerothcore-wotlk/commit/e322c017ea62906af7bfc2839da1e6b0a23b5863
-  
-  
- Closes 
- 
- 
1.
2.
3. …

chore(Core/Docs): Remvoe old comment

---

src/cmake/macros/ConfigureApplications.cmake

-  
-  
- Closes  #12100
- WH
- 

fix(Cmake/Build): correct build single app

---

src/server/game/Handlers/ArenaTeamHandler.cpp
src/server/game/Handlers/MiscHandler.cpp

-  
-  
- Closes 
https://github.com/TrinityCore/TrinityCore/commit/abb97bac18d4d38feacad37a3f60e79dd3b9606c
- 
- 
1.
2.
3. …

Fix(core/packets) reduce sending unnecessary packets

---

src/server/game/Handlers/CharacterHandler.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11990
- closes https://github.com/chromiecraft/chromiecraft/issues/3566
- tested works
- 
1. Delete a character
2. Check realm selection
3. …

fix(Core/Characters): Correctly update char count on realm selection

---

src/server/game/Maps/MapMgr.h

-  getter function for the used Instance IDs
-  
- Closes 
- 
- 
1.
2.
3.

feat: getter for the used instance IDs

---

data/sql/updates/pending_db_world/rev_1673776593039171300.sql

Fixes #14638
Author: @offl
- Closes #14638
- Closes https://github.com/chromiecraft/chromiecraft/issues/4724
`.go c 70741`
`.damage 6000`
Wait for fleeing to end …

fix(DB/SAI): Sunfury Geologist.

---

data/sql/updates/pending_db_world/rev_1673697283424429000.sql

Fixes #14642
- Closes #14642
- Closes https://github.com/chromiecraft/chromiecraft/issues/4734
`.gm on`
` .go c 202645`
Clean a little to test properly
Attack from range the Archers and look at their behaviour
**For …

fix(DB/SAI): Bleeding Hollow Archers should only use ranged abilities.

---

data/sql/updates/pending_db_world/rev_1673490008927079900.sql

- Prevent the Grimclaw event for How Big a Threat (part 2) from taking several minutes longer than intended
-  Delete useless Grimclaw spawn
-  Rebuild Waypoints, use correct entry numbering (entry*100)
- Update SAI to conform to new waypoints and remove unused rows
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11374
- Closes https://github.com/chromiecraft/chromiecraft/issues/3188
- Closes https://github.com/chromiecraft/chromiecraft/issues/3313
- Closes https://github.com/chromiecraft/chromiecraft/issues/3216
- Closes https://github.com/chromiecraft/chromiecraft/issues/3296
- 
1. .quest add 985
2. .quest complete 985
3. .go quest ender 985 …

fix(DB/SAI): Grimclaw

---

data/sql/updates/pending_db_world/rev_1673093922693808500.sql

Fixes #13978
- Closes #13978
- Not tested.
`.go cr 138337`
`.tele underbog`
`.go xyz 280.749817 -169.079193 36.874214` …

DB/SAI: Bog Giant and Underbog Lord uses Growth only in Heroic mode.

---

data/sql/updates/pending_db_world/6387-6391-example.sql

This is an example for a pull request for AzerothCore and intended for review.
- Replaced post-Cataclysm text entry for 6387.
- Added missing female gender equivalent to 6391.
- Part of tasks of unconfirmed issue from CC Github: https://github.com/chromiecraft/chromiecraft/issues/4745
- 6391: https://www.wowhead.com/wotlk/de/quest=6391/flug-nach-eisenschmiede
- 6387: https://www.wowhead.com/wotlk/de/quest=6387/ehrenstudenten
- Not tested in-game.
1. Use a deDE client and play a female character.
3. Check quest progress text of 6391 and of 6387. …

fix(DB/Locale): deDE locales fixed for quests 6381 and 6391

---

apps/ci/ci-gen-server-conf-files.sh
src/common/Configuration/Config.cpp

Removal of .dist file loading and checking. The .dist file has little to no value other than as a blueprint when the .conf file is what should be edited in all cases. The conf file should be the master, the core should be the fallback.
The core already has preset default values for any config option, and these hard coded default values is what should load in the case of an outdated .conf file, or if any options are missing.
If, for any reason, the config file is missing any values, the core will output the default config option and which config file is missing said values. The user is then instructed what to add to the config file. The core will not halt in these circumstances, and will fall back to the default values.
- Compiled, ran and tested with missing config options. The core …

Removal of unnecessary .dist file loading

---

data/sql/updates/pending_db_world/rev_1674318614246381300.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14689
- fixed
- 
1.
2.
3. …

fix(DB/Creature): Bloodaxe Veteran equipment

---

data/sql/updates/pending_db_world/fixrespawntimes.sql

-  set respawn time of Lieutenant Commander Thalvos and  Arch Mage Xintor to 1 minute
- Closes https://github.com/chromiecraft/chromiecraft/issues/4834
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14709
both are exactly one minute from being looted
https://user-images.githubusercontent.com/11332559/213287265-981206be-a1ca-4bd8-84db-64b2390d49d9.mp4
https://user-images.githubusercontent.com/11332559/213287503-2df78c25-8b88-4ff1-abaf-135f96f6e359.mp4
- ran quesry on local 
- killed on local
1. .go c id 16978 & .go c id 16977
2. kill npc's and wait to respawn (no quest needed) …

fix(DB/Creature): Looking to the Leadership quest mob respawn times

---

data/sql/updates/pending_db_world/rev_1673978919934644100.sql

-  Forgot to remove them earlier
- Closes 
- 
- 
1.
2.
3.

fix(DB/Creature): Remove extra spawns of Sally Whitemane and Renault Mograine in Old Southshore

---

data/sql/updates/pending_db_world/rev_1674332540072656400.sql

-  Add missing creature emotes
-  Fix onkill rep for Avian Ripper and Sethekk Initiate
- Delete extra Saga of Terokk, fix respawn timer
- Add 'Summon Arakkoa Spirit' spell to Sethekk Prophet and fix their template
- Closes 
- 
1.
2.
3. …

fix(DB/SethekkHalls): Minor fixes for Sethekk Halls

---

data/sql/updates/pending_db_world/rev_1674343786491025500.sql

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/13851
Co-Authored-By: Grindelwald <137000133@qq.com>
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Locale): Chinese

---

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
src/server/game/AI/ScriptedAI/ScriptedCreature.h
src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  Move taskscheduler to the BossAI class
-  No longer requires importing the TaskScheduler header everywhere or instantiating it, simple use *scheduler*
- Closes 
- 
- 
1. check if ayamiss/cthun still cast their abilities and such
2.
3. …

feat(Core/AI): Move TaskScheduler to BossAI class

---

data/sql/updates/pending_db_world/rev_1674795014172966200.sql

-  Adds 10 reputation points with the kurenai/Mag'har when killing the creature
- https://github.com/azerothcore/azerothcore-wotlk/issues/14576
- https://github.com/chromiecraft/chromiecraft/issues/4783
- 
- 
1. Execute the statement in your database world
2. .go c id 18413 and kill the creature …

fix(DB) Zorbo the Advisor gives no rep

---

data/sql/updates/pending_db_world/rev_1674524357697119400.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4839
- 
- 
1.
2.
3. …

fix(DB/Creature): Add some immunities to C'thun adds

---

data/sql/updates/pending_db_world/talin-keeneye-esesmx.sql

- Adds esES/esMX Text0_0 (Greeting text) to [Talin Keeneye](https://www.wowhead.com/wotlk/npc=714).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13675.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4359.
Wrath Classic sniffs.
- Untested.
2. Launch with esES/esMX localization.
3. `.tele coldridgevalley`
4. Interact with Talin Keeneye.
5. Observe localization. …

fix(DB/npc_text_locale): Add esES/esMX text to Talin Keeneye.

---

data/sql/updates/pending_db_world/rev_1669573700722721000.sql
src/server/scripts/Northrend/VioletHold/violet_hold.cpp

-  Violet Hold door wasn't opening when you were pressing the lever, so i moved The Violet Hold door to Smart_script
- Closes 
- Build without errors
- https://www.youtube.com/watch?v=jOSdSKqGntM
1. .tele dalaran
2. go to violet hold
3. .additem 42482 and open the door
4. press the lever …

fix(DB/Script): Violet Hold Door not opening

---

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp

fix(Scripts/GruulsLair): Fixed assigning loot mode to High King Maulgar.

---

data/sql/updates/pending_db_world/rev_1674955488978183200.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4888
- 
- 
1.
2.
3. …

fix(DB/Reputation): Remove reputation from Fiendish Imp

---

data/sql/updates/pending_db_world/rev_1674932391387360100.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4875
- 
- 
1.
2.
3. …

fix(DB/Reputation): Fix reputation awarded for Murkblood Healers

---

data/sql/updates/pending_db_world/rev_1675041522992054000.sql

-  I was checking if the quest, had any condition that made it not to be taken, after being abandoned and I had no problems. Then, I noticed that the QuestType was set to 0, and I tried setting it to 2, which resulted in being able to take it and leave it as many times as necessary.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14791
- Windows 10
- In-game
1. `.go c id 28179`
2. `.quest add 13070` or complete the missions until you reach that
3. Abandon it and you will not be able to retake it.
4. Then apply the SQL and try again. …

fix(db/Quest Template) Change QuestType in quest 13070

---

src/server/game/Globals/ObjectAccessor.cpp
src/server/game/Globals/ObjectAccessor.h

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11539
- 
- 
1.
2.
3. …

feat(Core/ObjectAccessor): Helper to access creature/object by DB GUID

---

data/sql/updates/pending_db_world/rev_1675179113512972600.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14822
- Closes https://github.com/chromiecraft/chromiecraft/issues/4902
- 
- 
1.
2.
3. …

fix(DB/SAI): Port Coilskar Siren AI from Cmangos

---

data/sql/updates/pending_db_world/rev_1675174318109298400.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14814
- Closes https://github.com/chromiecraft/chromiecraft/issues/4905
- 
- 
1.
2.
3. …

fix(DB/SAI): Nether Ray (18880)

---

data/sql/updates/pending_db_world/rev_1671290232250846500.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4566
- 
- 
1.
2.
3. …

fix(DB/Quest): Rework support for 'Someone Else's Hard Work Pays Off'

---

src/server/scripts/EasternKingdoms/Karazhan/boss_maiden_of_virtue.cpp
src/server/scripts/EasternKingdoms/Karazhan/karazhan.h

-  Several aesthetic/codestyle changes
-  Added repetenance speech
- Closes 
- 
1. do the boss
2.
3. …

refactor(Scripts/Karazhan): Maiden of Virtue script update

---

data/sql/updates/pending_db_world/rev_1675544589170359700.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4859
- 
- 
1.
2.
3. …

fix(DB/SAI): Fix Spectral Chargers not casting fear

---

data/sql/updates/pending_db_world/elder_gossip_fix.sql
data/sql/updates/pending_db_world/elder_gossip_fix_2.sql

-  Fixes the non-working gossip menus for npc 15572 and 15579
-  
- Closes 
https://wotlkdb.com/?npc=15572
https://wotlkdb.com/?npc=15579
-  attempted to use gossip menus on both npcs which were unresponsive and now work as intended
- 
1. `.go creature id 15572` and/or `.go creature id 15579`
2. before applying the update the gossip menus do not work
3. after applying the update the gossip menus work …

fix(DB/Creature): Fix Elder Runetotem & Elder Darkhorn gossip

---

data/sql/updates/pending_db_world/rev_1675134563871963700.sql

- Add Baron Charr, The Windreaver, Princess Tempestria and Avalanchion to the Elemental Invasions event.
- Removed a Razormane Stalker from the creature list of the event. I don't know why it was there but it shouldn't be.
This only adds them to the event to make sure they are only around when the event is active. It doesn't address any other issues people are having with the creatures in question.
- Closes 
https://wowpedia.fandom.com/wiki/Elemental_Invasions_(Classic)
- Went to the location of the creatures and made sure they are not there
- Started the event and checked all the creatures again to make sure they were there
1. Check to make sure none of the creatures mentioned above are spawned
2. Use `.event start 13`
3. Check the creatures again. Make sure they are spawned
When a PR is …

fix(DB/Event): Elemental Invasions

---

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp

-  Change cast time to 7s
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4813
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14720
-  closes https://github.com/azerothcore/azerothcore-wotlk/issues/14718
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/14719
- 
- 
1.
2.
3. …

fix(Scripts/Gruuls Lair): Improvements to High King Maulgar

---

src/server/game/Instances/InstanceSaveMgr.cpp
src/server/game/Scripting/ScriptDefines/GlobalScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Added new hook for https://github.com/azerothcore/mod-zone-difficulty/pull/18
- Not tested.
Nothing to test. …

feat(Core/Scripting): Added new hook: OnInstanceIdRemoved.

---

src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/Chat/Chat.cpp
src/server/game/Conditions/ConditionMgr.cpp
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Transport/Transport.cpp
src/server/game/Events/GameEventMgr.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h
src/server/game/Grids/ObjectGridLoader.cpp
src/server/game/OutdoorPvP/OutdoorPvP.cpp
src/server/game/Pools/PoolMgr.cpp
src/server/scripts/Commands/cs_go.cpp
src/server/scripts/Commands/cs_gobject.cpp

-  Reduce differences between projects
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Object): Rename GetGOData() to GetGameObjectData()

---

src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h
src/server/game/World/World.cpp
src/server/scripts/Commands/cs_reload.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Core/ObjectMgr): Load Creatures.CustomIDs into stores

---

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp
src/server/scripts/Outland/GruulsLair/gruuls_lair.h

* Register with factory
* std::chrono
- Use std::chrono for events
- Register creaturescript with factory
- Closes 
- 
- 
1.
2.
3. …

refactor(Scripts/Gruuls Lair): Modernize High King Maulgar script

---

data/sql/updates/pending_db_world/rev_1675628318572061500.sql

-  Remove hacked scale for 18555 and add CTM
-  Add CANNOT_TURN for Time Rifts
-  Add aura for 21862
-  Otherwise add NOT_SELECTABLE flags to other dummies and change from NON_ATTACKABLE to IMMUNE_TO_PC
- Closes 
- 
1.
2.
3. …

fix(DB/Creature): Fix some unit flags for Black Morass

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_flamegor.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix: Crash on Flamegor

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_flamegor.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/BlackwingLair): Fix Flamegor frenzy timer

---

data/sql/updates/pending_db_world/rev_1675980081777637000.sql

-  Script Sawemba
-  Script is from TC but I cannot find the original author.
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Script Sawemba

---

data/sql/updates/pending_db_world/rev_1675982982263104100.sql

-  Just misc update of target type for talk, and walk pos
-  Originally from TC, author unknown
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Misc SAI updates

---

data/sql/updates/pending_db_world/rev_1675980251209377200.sql

-  Script Magister Savarin
-  Script from TC but cannot find the author.
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Script Magister Savarin

---

data/sql/updates/pending_db_world/rev_1675983759485500400.sql

-  
-  From TC, author unknown
- Closes 
- 
- 
1.
2.
3.

fix(DB/Creature): Spawn Floating Skull

---

data/sql/updates/pending_db_world/rev_1675983591397096200.sql

-  From TC, unknown author
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/Creature): Spawn Warsong Hold Mount

---

src/server/scripts/Outland/zone_netherstorm.cpp

-  Add an additional check for the spell target.
-  
- Closes 
- None.
- 
1.
2.
3. …

fix: Crash in Netherstorm

---

data/sql/updates/pending_db_world/rev_1675980334913373700.sql

-  Script Wyrmcaller Vile
-  Originally from TC but cannot find the author :(
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Script Wyrmcaller Vile

---

data/sql/updates/pending_db_world/rev_1675208727018608900.sql

-  Casts Arcane Shield out of combat
- https://github.com/azerothcore/azerothcore-wotlk/issues/14817
- https://github.com/chromiecraft/chromiecraft/issues/4907
https://youtu.be/HX8haCDIVT0?t=195
- 
2. .go c 67469 …

fix(DB/SAI) Warp Aberration should keep up Arcane Shield out of combat

---

src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp
src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp

Fixes #14782
- Closes #14782
`.tele kara`
Kill Moroes
begin Opera. if it is Wizard of Oz.
Bosses can be killed …

fix(Scripts/Karazhan): Fixed Wizard of Oz encounter.

---

src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp
src/server/game/AI/ScriptedAI/ScriptedFollowerAI.cpp
src/server/game/AI/SmartScripts/SmartAI.cpp

Fixes #14883
- Closes #14883
`.go c id 15608`

fix(Core/AI): Fixed mobs attacking in defensive state.

---

src/server/game/AI/CreatureAI.cpp
src/server/game/AI/CreatureAI.h
src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_captain_skarloc.cpp

-  Implement a delay option to the talk function, allowing us to create simple dialogues without the need of using the EventScheduler or other more sophisticated event scheduling
-  Example:
- 
boss_skarloc.cpp
- Closes 
- 
- 
1.
2.
3.
**For …

feat(Core/AI): Implement delay option to the Talk() function

---

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp

-  So we no longer need to replicate UpdateAI() when using the taskscheduler
-  
- Closes 
- 
- 
1.
2.
3. …

feat(Core/AI): Update the BossAI scheduler in the parent class

---

src/server/scripts/Outland/TempestKeep/botanica/boss_warp_splinter.cpp
src/server/scripts/Outland/TempestKeep/botanica/the_botanica.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/TheBotanica): Modernize the Warp Splinter script

---

data/sql/updates/db_world/2023_02_11_09.sql
src/server/game/Globals/ObjectMgr.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(DB/SQL): Correct file to comply with standards

---

src/server/scripts/Outland/TempestKeep/botanica/boss_high_botanist_freywinn.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/TheBotanica): Modernize High Botanist Freywinn script

---

data/sql/updates/pending_db_world/rev_1676174163801356100.sql

-  Corrected bad timers, now summons arcane minion, minion scripted
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14880
- 
1.
2.
3. …

fix(DB/SAI): Script Sunseeker Netherbinder

---

data/sql/updates/pending_db_world/rev_1676193535182619400.sql

Fixes #14847
- Closes #14847
- Closes https://github.com/chromiecraft/chromiecraft/issues/4923
Cannot say if these are the exact cause, but
Did the escort until the last event/boss
Stood next to Xiraxis and attack the moment he became hostile
Kill Xiraxis …

fix(DB/SAI): "Someone Else's Hard Work Pays Off" - fixed ending scene.

---

data/sql/updates/pending_db_world/rev_1676199530062182300.sql

Fixes #14873
- Closes #14873
Enter The Shattered Halls
Walk through them / attack them …

fix(DB/SAI): Shattered Hand Assassin.

---

data/sql/updates/pending_db_world/rev_1675540548592980100.sql

Fixes #12718
- Closes #12718
- Closes https://github.com/chromiecraft/chromiecraft/issues/3442
`.quest add 1266`
`.go xyz -2897.153809 -3349.867432 31.299358 1 6.278478` don't move any further.
Complete quest 1266, take the next quest
Proceed with the quest, see if it plays normally …

fix(DB/SAI): Fixed Private Hendel SAI script.

---

data/sql/updates/pending_db_world/rev_1676054259396904200.sql

-  title
-  
- Closes 
- 
- 
1.
2.
3.

chore(DB): Add default values to columns in creature_formations table

---

src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.h
src/server/scripts/Outland/TempestKeep/arcatraz/boss_dalliah_the_doomsayer.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/instance_arcatraz.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Arcatraz): Modernize Dalliah the Doomsayer script

---

data/sql/updates/pending_db_world/rev_1675035967923856800.sql

-  Adds missing animations and texts at the end of quest
- https://github.com/azerothcore/azerothcore-wotlk/issues/13661
- https://github.com/chromiecraft/chromiecraft/issues/4374
https://youtu.be/as4Pt0LZA6U?t=5540
- 
- 
-
2. .go cr 65790
3. .quest add 10201
4. .quest comp 10201 …

fix(DB/SmartScript) NPC - Rakoria RP event

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

-  Implement a new SMART_TARGET_INSTANCE_STORAGE, used to target creatures/objects inside the instance smart storage
- For example:
We could access Dalliah if we used her storage index as param (1)
So target type 205, param1 = 1 would get her as target
- Closes 
- 
- 
1.
2.
3. …

feat(Core/SAI): Implement SMART_TARGET_INSTANCE_STORAGE

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/TempleOfAhnQiraj): Clean up unused variables

---

src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp

-  Remove bad movement function, improve stuff
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13985
- 
- 
1.
2.
3. …

fix(Scripts/Ulduar): Fix Stormcaller Brundir flying under texture

---

data/sql/updates/pending_db_world/rev_1675168500421561700.sql

-  Upon accepting the quest, player should salute the questgiver, then a few seconds later questgiver salutes back and says their line. Previously only the line is said, and talking emote plays. 
- salute spell id from vmangos
- Closes 
https://youtu.be/h8Kv5RNNnJs?t=1445 (24:05)
- 
1. create a human
2. .quest add 21
3. .quest complete 21
4. Take Report to Goldshire from McBride in Northshire. Might have min level req.
5. Above described interaction should play. …

fix(DB/SAI): Quest - Report to Goldshire incomplete RP.

---

src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h
src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp
src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_kelidan_the_breaker.cpp
src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp

-  Move to BossAI, implement instance handling of BossStates, fix entrance door
-  
- Closes 
- 
- 
1.
2.
3. …

refactor(Scripts/BloodFurnace): Modernize Broggok script

---

src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15043
- 
- 
1.
2.
3. …

fix(Scripts/Naxxramas): Remove Sapphiron encounter boss requirements

---

data/sql/updates/pending_db_world/rev_1676415242315358700.sql

-  Adds no repeat flag
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4988
- Tested with 2 characters
- Boss can still be spawned
- Instance can reset with player outside with no issues
1.
2.
3.
**For …

fix(DB/SAI): Fix Escape from Durnholde Barrel exploit

---

data/sql/updates/pending_db_world/rev_1676502726004152400.sql

-  Adds emotes to stationary spawns
-  Adds patrols and pathing
- Ports auras to addon instead of SAI
- clears trashed addon entries
- Closes 
- 
1.
2.
3. …

fix(DB/Creature): Cleric of Karabor

---

data/sql/updates/pending_db_world/rev_1676321187026326300.sql

- Oh man it was bad
- Sniffs and rebuilds the area
- Implements SAI for Dormant Infernal
- Improves the Summoning Circle
- Adds waypoints, patrols and formations
- Fixes auras
- Adds emotes to Deathforge Smith
- Remove wrongly-spawned mine
- Remove wrongly-spawned non-combat pet
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15031
- Closes https://github.com/chromiecraft/chromiecraft/issues/5029
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15032
- Closes https://github.com/chromiecraft/chromiecraft/issues/5030
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15029
- Closes https://github.com/chromiecraft/chromiecraft/issues/5028
Retail sniffs
- 
1.
2.
3. …

fix(DB/Creature): Re-Construct The Deathforge spawns

---

data/sql/updates/db_world/2023_02_16_03.sql

sorry :(
-  Is now able to run twice
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB): Fix 2023_02_16_03.sql

---

data/sql/updates/pending_db_world/rev_1676600155710875500.sql

-  Ports WPs and AI
- Closes 
Mangos
- 
1.
2.
3.

fix(DB/Creature): Port Voidhunter Yar from Mangos

---

data/sql/updates/pending_db_world/rev_1676596950750457600.sql

Authored-By: Dr-J [1444120+dr-j@users.noreply.github.com](mailto:1444120+dr-j@users.noreply.github.com)
-  Ports the above quest events from TC
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6773
- Closes https://github.com/chromiecraft/chromiecraft/issues/1104
TC
- 
1.
2.
3. …

fix(DB/Quest): Kill'em With Sleep Deprivation/Look At the Size of It 

---

data/sql/updates/pending_db_world/rev_1676596180388597300.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/Creature): Delete extra Chess Square, OUTSIDE BLACK (DND) found in Nagrand

---

data/sql/updates/pending_db_world/rev_1676590661919341700.sql

-  Updates AI from TC
-  Ports spawns, WP from Mangos
- Closes 
- 
1.
2.
3. …

fix(DB/Creature): Port Dr. Whitherlimb spawns from Mangos

---

data/sql/updates/pending_db_world/rev_1676590176130007200.sql

-  Adds 2 more spawns and pools them
-  
- Closes 
Mangos
- 
1.
2.
3. …

fix(DB/Creature): Port Eldinarcus spawns from Mangos

---

data/sql/updates/pending_db_world/rev_1676515696524488800.sql

spaghetti sql
Please don't ask me to improve the readability 😩
-  Corrects spawn positions
-  Corrects many SAI inconsistencies causing the event to not progress
-  Replaces hard-coded spawns with the proper spell
-  Removes invisibility aura (not in sniffs) causing Karsius to be invisible
- Add a missing line for when the event fails
- Modifies Chains of Shadows to only spam on aggro
- In short makes it possible to start and finish the event
- Closes https://github.com/chromiecraft/chromiecraft/issues/5047
- Closes https://github.com/chromiecraft/chromiecraft/issues/4990
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15011
Retail Sniffs
- Tested in 2 different computers, one with a clean DB
- 
.q a 10634
.q c 10634
.q a 10635
.q c 10635
.q a 10636
.q c 10636
.go q ender …

fix(DB/SAI): Fix Teron Gorefiend, I am... being uncompletable

---

data/sql/updates/pending_db_world/rev_1676735655098024400.sql

Author: @offl
Fixes #14737
- Closes #14737
`.go c id 18472` in GM mode
Interact with Lakka, see the gossip
Kill Darkweaver Syth
See if yell message from Lakka is played
Interact with Lakka, see if gossip has changed.
See if gossip option is present.
If it is, then `.add quest 10097`
See if it gives credit.
See if Lakka says line, the cage opens, Lakka starts waypoints and despawns near the doorway. …

fix(DB/SAI): Lakka escort event.

---

data/sql/updates/pending_db_world/rev_1676624876337239900.sql

- Dragonmaw Bonewarders to respawn Skeleton on Reset (After Combat, On Respawn or Spawn) rather than only on respawn.
"At all times (unless killed during combat) a skeleton should be summoned by them"
- Dragonmaw Bonewarder's pet (Skeleton) to force despawn after being dead for 1s. (if the body is not despawned OR there is an active pet. when Bonewarder resets, he will **NOT** summon a new one).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6639
Dragonmaw Bonewarder & Skeleton
.go c id 1057
Observe that they have minions and that they're not despawning OOC, kill their skeletons and then reset the Warder (after waiting the 1s for the skeleton's corpse to despawn) to see if they spawn a new one. …

fix(DB/Creature): Wetlands Dragonmaw Bonewarder missing Skeleton Minion

---

data/sql/updates/pending_db_world/rev_1676663068384320000.sql

-  Remove previous quest requirement for All Is Well That Ends Well & Heroic:All Is Well That Ends Well
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8535
Reply-Code Alpha (All Is Well That Ends Well & Heroic:All Is Well That Ends Well)
.additem 46052 - Normal
.additem 46053 - Heroic
Attempt to start the quest from either of the items, verify that you can. …

fix(DB/Item): Remove Reply-Code Alpha previous quest requirements (10 & 25)

---

data/sql/updates/pending_db_world/rev_1676739457090257600.sql
src/server/game/AI/CoreAI/UnitAI.cpp
src/server/game/AI/CoreAI/UnitAI.h
src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp
src/server/scripts/Outland/Auchindoun/SethekkHalls/instance_sethekk_halls.cpp
src/server/scripts/Outland/Auchindoun/SethekkHalls/sethekk_halls.h

-  Clean instance files, update script, fix blink teleport
-  Add DoCastMaxThreat() helper
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15023
- Closes https://github.com/chromiecraft/chromiecraft/issues/4970
- 
- 
1.
2.
3. …

fix(Scripts/SethekkHalls): Update Talon King Ikiss script

---

data/sql/updates/pending_db_world/rev_1676764417910573100.sql

-  Removes 2 Shadowmoon Retainers causing issues with What Illidan Wants, Illidan Gets...
-  
- Progress Towards https://github.com/azerothcore/azerothcore-wotlk/issues/15088
- 
1.
2.
3. …

fix(DB/Creature): Remove custom-placed Shadowmoon Retainers in Eclipse Point

---

data/sql/updates/pending_db_world/rev_1676750377001449200.sql

Fixes #11578
- Closes #11578
- Closes https://github.com/chromiecraft/chromiecraft/issues/3438
.go c id 4274
Pull him outside of his room, to the end of the stairs and then kill him.
See that the event starts.
**For …

fix(DB/SAI): Increase range of Set Data for Fenrus the Devourer.

---

src/server/game/Server/WorldSession.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15122
- 
- 
1.
2.
3. …

fix(Core/PacketIO): Remove wrong QueuePacket()

---

src/server/game/Conditions/DisableMgr.cpp
src/server/game/Conditions/DisableMgr.h
src/server/game/Loot/LootMgr.cpp

-  Implement new DISABLE_TYPE_LOOT
-  sourcetype 10, entry = item entry, flags 0, param1 =0, param2 = 0
- Closes 
- 
1.
2.
3. …

feat(Core/Disables): Implement DISABLE_TYPE_LOOT

---

data/sql/updates/pending_db_world/rev_1676847290281165300.sql

-  https://github.com/azerothcore/azerothcore-wotlk/pull/15097#issuecomment-1436114988
-  
- Closes 
- 
1.
2.
3. …

fix(DB/Conditions): Increase range check for Lakka gossip

---

src/server/apps/authserver/resource.h
src/server/apps/worldserver/resource.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Misc): For Azeroth!

---

src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Scripts/Ulduar): fix typo/misc when loading instance data

---

data/sql/updates/pending_db_world/rev_1675023968959068200.sql

…before offering repairs
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4860
- 
- 
1.
2.
3. …

fix(DB/Conditions): Koren requires at least honored with Violet Eye

---

data/sql/updates/pending_db_world/rev_1675037344657947800.sql

-  Removes copper and ragveil drop from Tamed Sporebats
-  Removes the possibility of skinning Giant Plains Creeper
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14596
- Closes https://github.com/chromiecraft/chromiecraft/issues/4777
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14580
- Closes https://github.com/chromiecraft/chromiecraft/issues/4714
- 
- 
2. .go c id 2565 for Giant Plains Creeper
3. .tele feralfenvillage for Tamed Sporebats …

fix(DB) Tamed Sporebats have drops and Giant Plains Creeper spider should not be skinnable

---

data/sql/updates/pending_db_world/rev_1675054031508722800.sql

-  Update Unit Flag to make it non-attackable
- https://github.com/azerothcore/azerothcore-wotlk/issues/14295
- 
1. Insert the update in your World database
2. Be alliance
3. .go c 84372
4. Attack him …

fix(DB) Scout Jyoba should be dead

---

src/server/game/Chat/Channels/Channel.h

- Add `Channel::GetChannelDBId()`
- Needed for https://github.com/azerothcore/mod-eluna/pull/101
N/A
- Built and tested on Windows 11 …

feat(Core/Channel): add GetChannelDBId()

---

data/sql/updates/pending_db_world/rev_1677460150899347600.sql

- Did you know that by default the ReactState is set to passive?
- I didn't until a week ago
- Somehow I never really had any major problems until recently
- So I fix
- Closes https://github.com/chromiecraft/chromiecraft/issues/5087
- 
1.
2.
3. …

fix(DB/SAI): Fix WP_START parameter mistakes

---

src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/IcecrownCitadel): fix Lord Marrowgar bone spikes

---

data/sql/updates/pending_db_world/rev_1677121723939096800.sql

-  Continuation of: https://github.com/azerothcore/azerothcore-wotlk/pull/15065
-  
- Closes 
- 
1.
2.
3. …

refactor(DB/SAI): Re-organize Teron Gorefiend, I am... script and add time limit properly

---

data/sql/updates/pending_db_world/rev_1677368120858755900.sql

- Use sniffed data as much as possible
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15190
- Closes https://github.com/chromiecraft/chromiecraft/issues/5095
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/13903
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13904
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13907
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13908
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15176
- Closes https://github.com/chromiecraft/chromiecraft/issues/4952
- Tested Ingame
- 
1. `.go c id 18471`
2.
3. …

fix(DB/SAI): Rewrite Ring of Blood

---

src/server/game/Warden/Warden.cpp

-  fix fmt style warden logging issue junk like this
- Closes 
- 
- 
1.
2.
3. …

fix (logging): Warden FMT

---

src/server/game/Entities/Unit/Unit.cpp

-  Add check, the charmer may be null when the creature performs that action.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15252
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15250
- 
- 
1.
2.
3.
**For …

fix: Crash on unit charm

---

src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_hydromancer_thespia.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_warlord_kalithresh.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/steam_vault.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Steamvault): Modernize boss/instance scripts

---

data/sql/updates/pending_db_world/rev_1677959284674069900.sql
src/server/scripts/Outland/TempestKeep/botanica/boss_commander_sarannis.cpp

partial cherry-pick of https://github.com/TrinityCore/TrinityCore/commit/41da43d9f240ecd9976a440824507d73891eeeec
- Modernize script
-  Use proper spells
- adds no longer despawn on death
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/TheBotanica): Rework Commander Sarannis

---

data/sql/updates/pending_db_world/rev_1677807108312300000.sql

-  Port from Mangos
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15237
- Closes https://github.com/chromiecraft/chromiecraft/issues/5038
Mangos
- 
1.
2.
3. …

fix(DB/Loot): Fix Talon King Ikiss Normal Mode loot table

---

data/sql/updates/pending_db_world/rev_1677805290069827400.sql

-  Bosses from Sethekk Halls and Shadow Labyrinth drop 2 Spirit Shards
-  Bosses from Auchenai Crypts and Mana-Tombs drop 1 Spirit Shard
- Closes 
https://www.wowhead.com/wotlk/item=28558/spirit-shard#comments:id=67632
https://www.wowhead.com/wotlk/item=28558/spirit-shard#comments:id=25324
https://wowpedia.fandom.com/wiki/Spirit_Shard
- Query Runs, DB looks OK
- 
1.
2.
3. …

fix(DB/Loot): Spirit Shards

---

data/sql/updates/pending_db_world/rev_1677870148388497400.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13160
- Closes https://github.com/chromiecraft/chromiecraft/issues/3964
in the issue
- tested
.go c id 8888
.gm on
Confirm that last gossip menu text is correct. 
"You will find Fineous Darkvire beyond the Ring of Law, in the Hall of Crafting..." …

fix(DB/Gossips): Wrong gossip text for Franclorn Forgewright.

---

data/sql/updates/pending_db_world/rev_1677761748533314800.sql
src/server/scripts/World/npcs_special.cpp

-  Fix Sayge's menu_option.
-  Removed the wrong keys from Locksmith npcs and added the missing keys (Left a todo for Focusing Iris key).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11982
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4144
- tested
-- Sayge
.npc add temp 14822
Test the gossips https://www.wowhead.com/classic/npc=14822/sayge#comments:id=3035
To reset cooldown, delete character guid from acore_characters-> character_spell_cooldown OR copy line 1576 to above line 1572
-- Wormhole
.npc add temp 35646 
Test the gossips
-- Locksmith
.go c id 29665
Quest list for horde (for alliance look at code)
5511, 10704, 10758, 3201, 3802, 10982, 9837, 13159, 11011
.q a X
.q c X
.q reward X
Delete the key that you just received and speak with the npc, …

fix(Script/Core): npcs_special hardcode removal and fixes.

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Unit/Unit.cpp

Fixes #14699
- Closes #14699
- Closes https://github.com/chromiecraft/chromiecraft/issues/4785
`.learn 1515`
Tame a wolf-type beast (e.g. `.go c 79631`)
Attack with your pet and observe its speed …

fix(Core/Pet): Fixed set hunter pet's speed on load.

---

src/server/game/Entities/Player/Player.cpp

Fixes #14997
- Closes #14997
- Closes https://github.com/chromiecraft/chromiecraft/issues/5025
`.learn 871`
`.learn 20230`
`.learn 1719`
use any and log out
attempt to use any of the other two …

fix(Core/Spells): Fixed sending category cooldowns.

---

data/sql/updates/pending_db_world/rev_1677174924847719800.sql

- Remove OOC attack closest player
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13028
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13538
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8642
- Closes https://github.com/chromiecraft/chromiecraft/issues/4080
- Closes https://github.com/chromiecraft/chromiecraft/issues/4290
- Closes https://github.com/chromiecraft/chromiecraft/issues/2155
https://youtu.be/AAwpEJWR_fc?t=61
- tested
1.
.learn 1784
.tele tyrshand
/cast stealth
approach nearest scarlet enchanter AND cleric without getting too close to break stealth
Notice neither will attack or aggro.
2.
.go xyz 1759.7 -5445.5 81
Run around the building.
See that you don't aggro anything from inside the building …

fix(DB/SAI): Scarlet Enchanter & Scarlet Cleric - OOC attack

---

data/sql/updates/pending_db_world/rev_1677008695688965000.sql
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.h

Lots and lots of duplicated texts 
- Removed hardcode
- Cleaned duplicated creature_texts in DB and re-linked _locale
- Fixed Sindragosa air walking
- Added doxygen todo for initial roleplay
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4161
- tested
Clear cache
.tele pitofs
Run as H/A …

fix(Script/Instance): Pit of Saron - Remove hardcode and duplicated texts in DB

---

data/sql/updates/pending_db_world/rev_1676968393827350700.sql

- Added Disable Movement & Pacified & Not Selectable flags and missing text.
- SAI refractor
- Closes https://github.com/chromiecraft/chromiecraft/issues/3632
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12106
https://www.youtube.com/watch?v=6a_J7E_6VL8 You do need to click the trap to activate it.
.q a 1960
.additem  7308
.additem 7247
.go c id 6492 …

fix(DB/SAI): Rift Spawn no emote/flags

---

data/sql/updates/db_world/2023_03_04_01.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore: fix cherry-pick (MariaDB)

---

data/sql/updates/pending_db_world/rev_1677984661498248100.sql
src/server/scripts/Outland/TempestKeep/botanica/boss_thorngrin_the_tender.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/TheBotanica): Modernize Thorngrin the Tender's script

---

src/common/Utilities/Containers.h
src/server/game/Entities/Creature/Creature.h
src/server/scripts/Outland/TempestKeep/botanica/boss_laj.cpp

-  Update script
-  Fix activation delay after teleport
- Implement SelectRandomContainerElementIf, to allow selecting container elements with predicates
- Implement ResumeChasingVictim() helper
- Closes unreported gully issue
- 
- 
1.
2.
3. …

fix(Scripts/TheBotanica): Rework Laj

---

.github/workflows/cpp-check.yml
src/common/Collision/BoundingIntervalHierarchy.cpp
src/common/Collision/BoundingIntervalHierarchy.h
src/common/Platform/ServiceWin32.cpp
src/server/database/Database/Transaction.cpp
src/server/game/Autobroadcast/AutobroadcastMgr.cpp
src/server/game/Autobroadcast/AutobroadcastMgr.h
src/server/game/Battlegrounds/BattlegroundQueue.cpp
src/server/game/Entities/Player/PlayerQuest.cpp
src/server/game/Loot/LootMgr.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp
src/server/scripts/EasternKingdoms/zone_hinterlands.cpp
src/server/scripts/EasternKingdoms/zone_undercity.cpp
src/server/scripts/Kalimdor/zone_silithus.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
src/server/scripts/Outland/zone_shadowmoon_valley.cpp
src/server/shared/DataStores/DBCDatabaseLoader.cpp
src/tools/map_extractor/System.cpp
src/tools/map_extractor/dbcfile.h
src/tools/map_extractor/loadlib/loadlib.h
src/tools/map_extractor/mpq_libmpq04.h
src/tools/mmaps_generator/MapBuilder.cpp

This PR is ready.
I do not know if `Seconds x{};` and `Seconds x = 0s` are the same, I think so
- add cpp-check to the pipeline
- fixing cpp-check warnings
- only running cpp-check and checking the build in the pipeline
- ~~I have to add the cpp check to all sources~~ DONE ✅ 
a succesful pipeline should be enough …

feat: add cppcheck into the pipeline

---

data/sql/updates/pending_db_world/rev_1678037942434622700.sql
src/server/game/Spells/Auras/SpellAuraEffects.cpp

chore(Core/Spells): Un-hack Spellcloth trigger spell

---

data/sql/updates/pending_db_world/rev_1678028975514038300.sql

- After Combat, On Respawn or Spawn ->  Set Invincibility hp at 1% + set byte 7 (FlagStandstate Dead)
- At 1% -> Talk -> Set Home Pos -> Set faction 35 (friendly)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13379
- Closes https://github.com/chromiecraft/chromiecraft/issues/4170
- Closes https://github.com/chromiecraft/chromiecraft/issues/3720
https://wowpedia.fandom.com/wiki/Deathstalker_Vincent (without the bug mentioned there)
- tested, works with cross-faction (can turn in Horde quest as well)
be alliance
.go c id 4444
Attack without killing him, run a away and then try to kill him.
Confirm that he drops on the ground (with his text) and becomes friendly. …

fix(DB/SAI): Deathstalker Vincent being killable.

---

data/sql/updates/pending_db_world/rev_1676933500733249000.sql

Timers for Breath & Cleave are from TC.
- Added Breath, Cleave and Frenzy (from source)
- Added the missing emote.
- Closes #12120
https://www.youtube.com/watch?v=gEHSg7GbIZY&
- tested
.quest add 4743
.go creature 31041
Check if he does Cleave And Flame Breath
Check if he becomes frenzied 15-18s in combat, and again after 2~ minutes. (from Source)
Bring Emberstrife to 10% HP or less, see if the text shows. …

fix(DB/SAI): Add Emberstrife's missing SAI.

---

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_aeonus.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_chrono_lord_deja.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_temporus.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Blackmorass): Rewrite Blackmorass

---

src/server/database/Database/DatabaseWorkerPool.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Database): Improve error wording

---

data/sql/updates/pending_db_world/rev_1678044696832996700.sql

-  Set chance to 100
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15273
- Closes https://github.com/chromiecraft/chromiecraft/issues/5071
- Query runs
- 
1.
2.
3. …

fix(DB/Loot): Correct Gorefiend Truncheon drop rate

---

src/server/game/AI/ScriptedAI/ScriptedCreature.h

-  Allows using DoForAllSummons with functions to do stuff with all summons
-  
- Closes 
- 
- 
1.
2.
3. …

feat(Core/AI): Implement DoForAllSummons() function to summon lists

---

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Blackmorass): Clean unnecessary repetitions

---

data/sql/updates/pending_db_world/rev_1676986377096927800.sql

- On spawn add random movement
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/12500
- Progresses https://github.com/chromiecraft/chromiecraft/issues/3834#issue-1310056500
- tested
.q a 962
.go gameobject id 13891
Click and look for the snek …

fix(DB/SAI): Serpentbloom Snakes no movement.

---

data/sql/updates/pending_db_world/rev_1676673725150035900.sql

- (AND) Add condition to not spawn NPC if there is already an NPC within 10 yards.
- (AND) Add QUEST_STATE (Rewarded and Complete) condition that allows to spawn NPC after completing 3821
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10827
- Closes https://github.com/chromiecraft/chromiecraft/issues/3106
- tested
.q a 3821
.go gameobject id 160445
Spam click it while having the quest in your log AND after turning it in.
Notice that there will always be 1 NPC, and no more. …

fix(DB/Conditions): Sha'ni Proudtusk infinite spawning. 

---

data/sql/updates/pending_db_world/rev_1677929630251654400.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13133
- Closes https://github.com/chromiecraft/chromiecraft/issues/4053
- tested
.go c id 5760
Should always have weapon, in or outside of combat. …

fix(DB/Creature): Lord Azrethoc pathing without a melee weapon.

---

data/sql/updates/pending_db_world/rev_1678171987448093500.sql

- remove gossip flags from the few spawns that had it
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13973
- tested
run before applying the sql changes
```sql
SELECT guid,npcflag FROM creature WHERE id1=32820 AND npcflag <> ''
```
run again after applying the changes
.go c guid …

fix(DB/Creature): Wild turkey spawns having gossip flags.

---

data/sql/updates/pending_db_world/rev_1678044264637638600.sql

- Change to update IC (with castflag 64), timers are from video sources.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13536
- Closes https://github.com/chromiecraft/chromiecraft/issues/4283
https://www.youtube.com/watch?v=GDK0IKE-Ne0&t=46s
https://www.youtube.com/watch?v=eg8ASX730gA
- tested
.go c id 12800 
Confirm that it doesn't cast while stunned & on aggro, but in combat, every 12 to 15s. …

fix(DB/SAI): Chimaerok casting on aggro.

---

data/sql/updates/db_world/2023_03_04_06.sql

-  Also removes a made-up text and adds BroadcastIDs
-  
- Closes 
- 
- 
1.
2.
3. …

chore(DB): Rerrunnable SQLs

---

data/sql/updates/pending_db_world/rev_1678050182254364700.sql

-  Pools them with a limit of 2 (seems to be the accepted range where they can be found
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/13877
Strictly Wowhead. Didn't go much farther than that.
- 
1.
2.
3. …

fix(DB/Creature): Pool Ethereum Jailor

---

data/sql/updates/pending_db_world/rev_1678456197533430300.sql
src/server/scripts/Outland/zone_zangarmarsh.cpp

- Removes custom cpp script, replaces with a closer to blizzlike SAI script instead.
- Contained entirely in DB, without needing cpp
- Makes Progress towards https://github.com/azerothcore/azerothcore-wotlk/issues/8559
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14259
- Closes https://github.com/chromiecraft/chromiecraft/issues/4573
Retail
- 
1. `.go c id 17893`
2. `.q a 9738`
3. Start event by talking with Bite …

fix(DB/SAI): Rework Naturalist Bite in SAI

---

data/sql/updates/pending_db_world/rev_1678297474580870500.sql

-  add sneak (also fixes them having no nameplates???)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14313
- Closes https://github.com/chromiecraft/chromiecraft/issues/4638
https://www.youtube.com/watch?v=1ZgUFUfePdw&t=79s
- tested
.go c id 18116
Check if it's always in stealth when outside of combat. …

fix(DB/SAI): Daggerfen Assassin missing stealth.

---

data/sql/updates/pending_db_world/rev_1678025316144101700.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(DB/Text): Fix missing apostrophes in Coilfang Slavemaster and Slavehandler texts and add Broadcast IDs

---

data/sql/updates/pending_db_world/rev_1678331213655095700.sql

- Hidden rewards...
- Closes 
TC
- 
1. `.q a 10870`
2. `.q c 10870`
3. `.go q ender 10870` …

fix(DB/Quest): Add missing rewards to Ally of the Netherwing

---

data/sql/updates/pending_db_world/rev_1678027027215535800.sql

-  Leather and Cloth were switched around.
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5114
- 
1.
2.
3. …

fix(DB/Conditions) Correct Class conditions for Satchel of Helpful Goods (65-70)

---

data/sql/updates/pending_db_world/rev_1678432036156760800.sql

-  remove obsolete SAI (move to _addon) and fix aggro radius
(was Starving Helboar - Between 20-80% Health - Cast \'33908\')
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14438
- Closes https://github.com/chromiecraft/chromiecraft/issues/4701
mangos for aggro radius (20->30)
- tested
.go c id 16879
.list auras (33908)
check aggro radius
Hit it to see if it deals damage back …

fix(DB/Creature): Starving Helboar aggro radius.

---

src/server/scripts/Spells/spell_generic.cpp

Fixes #15236
Fixes #10493
Fixes #13737
- Closes #15236
- Closes #10493
- Closes #13737
Create a rogue, give him the talents for the murder branch
Find a training dummy
Use 2 mutilate and Envenom …

fix(Scripts/Spells): Fixed Rogue T10 4P bonus.

---

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_aeonus.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_chrono_lord_deja.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_temporus.cpp
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp

Fixes #14848
- Closes #14848
`.go c id 15608`
Observe the Elite and Boss spawns, see if they yell their lines, and bosses can be heard. …

fix(Scripts/BlackMorass): Fixed rift mobs texts on summon.

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h

-  Implement a helper to send system messages (yellow chat messages)
-  
- Closes 
- 
- 
1.
2.
3. …

feat(Core/Player): Implement helper to send system messages to players

---

src/common/Utilities/EventProcessor.cpp
src/common/Utilities/EventProcessor.h
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

feat(Core/BasicEvents): Add the possibility to group BasicEvents

---

src/server/scripts/World/npc_professions.cpp

Fixes #10866
- Closes #10866
- Closes https://github.com/chromiecraft/chromiecraft/issues/2999
Talk to one of the blacksmithing specialization NPCs. …

fix(Scripts/Creatures): Fixed some profession trainers.

---

src/server/game/Warden/Warden.cpp

-  
-  
- Closes 
- Not tested.
1. Run some cheat detected by warden and see if you could properly see the logs. …

fix(Core/Logs): Fix warden fmt logs

---

.gitignore

-  Add `/data/sql/custom/*` to gitignore
- Local additions to /data/sql/custom may get committed in
- Custom or local changes shouldn't make it into git

 chore: Add `/data/sql/custom` to gitignore

---

data/sql/updates/pending_db_world/rev_1678617293053295700.sql

Fixes #10660
- Closes #10660
- Closes https://github.com/chromiecraft/chromiecraft/issues/3018
`.event start 8`
.quest add 24636
throw the chocolate from the daily onto player …

fix(DB/Spells): Treat Chocolate Sample as a positive spell.

---

data/sql/updates/pending_db_world/rev_1678626418501365600.sql

Fixes #11397
- Closes #11397
- Closes https://github.com/chromiecraft/chromiecraft/issues/3191
`.go gameobject 11646` …

fix(DB/Gameobjects): Fixed one spawn position of Stranglekelp.

---

data/sql/updates/pending_db_world/qri01.sql

-  This fixes a few wrong entries in the quest_request_items.sql table.
- Closes an unreported issue.
- No tests performed.
1. Accept respective quest.
2. Talk to the quest giver NPC for the request items text. …

fix(DB/Quest): Improvements for request texts

---

data/sql/updates/pending_db_world/rev_1678704026507325400.sql

Check TODO please, need a second opinion.
- Fix stealth for both creatures
- Added poison to Stalker
- Added web and toxic spit to Horror
- Progress https://github.com/chromiecraft/chromiecraft/issues/4987
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/15012
- Closes https://github.com/chromiecraft/chromiecraft/issues/4820
mangos/sniffs
- tested
.go c id 20714
Check if its stealthed
Applies poison (744) when in melee, does not apply if aura is already active on victim.
.go c id 20998
Check if its stealthed
see if it casts web (root) and toxic spit
<details>
creature_ai_scripts
---
| id | creature_id | event_type | event_inverse_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | event_param6 | …

fix(DB/Creature): Port Ridgespine mobs from Mangos.

---

data/sql/updates/pending_db_world/rev_1678816322284905000.sql

- Fix creature_text and use areatrigger invoker to initiate text.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5171
https://github.com/TrinityCore/TrinityCore/issues/24738
Co-authored-by: offl <offl@users.noreply.github.com>
- tested
.go trigger 4495
Confirm he talks to the invoker (when the text with $n gets picked) …

fix(DB/SAI): Karaaz incorrect text target.

---

data/sql/updates/pending_db_world/rev_1678817080047611900.sql

- Use areatrigger invoker to initiate text
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14688
https://github.com/TrinityCore/TrinityCore/issues/24738
Co-authored-by: offl <offl@users.noreply.github.com>
- tested
be alliance
.go trigger 1125
See if he greets you (except DKs) …

fix(DB/SAI): Brother Sarno not greeting players.

---

data/sql/updates/pending_db_world/rev_1678855110111127300.sql

Continuation of: https://github.com/azerothcore/azerothcore-wotlk/pull/15137
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15367
- Closes https://github.com/chromiecraft/chromiecraft/issues/5148
- 
1.
2.
3. …

fix(DB/Quest): Fix Earthmender Wilda not properly resetting

---

data/sql/updates/pending_db_world/rev_1678835550178060800.sql

-  Temporary fix until https://github.com/azerothcore/azerothcore-wotlk/issues/15288 is fixed
-  
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Pools): Temporary fix for Arakkoa Eggs until Core is fixed

---

data/sql/updates/pending_db_world/rev_1678822685335162700.sql

-  Despawns Stasis Chamber Alpha after summoning the NPC
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15383
- Closes https://github.com/chromiecraft/chromiecraft/issues/5138
- 
1.
2.
3.
**For …

fix(DB/Quest): Fix Stasis Chamber Alpha not respawning

---

data/sql/updates/pending_db_world/rev_1678820124142570600.sql

- Use areatrigger invoker to initiate text
none
https://github.com/TrinityCore/TrinityCore/issues/24738
Co-authored-by: offl <offl@users.noreply.github.com>
- tested
.go trigger 4389
See that he greets you.
(can set his (19227) SAI cooldown to few seconds to test all quotes. …

fix(DB/SAI): Griftah not greeting players.

---

data/sql/updates/pending_db_world/rev_1678842792599909200.sql

-  And wrong waypoints being assigned to Technicians
-  And wrong flags for Control Consoles
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15303
- 
1.
2.
3. …

fix(DB/Quest): Fix Manaforge Questline not being completable while in party

---

data/sql/updates/pending_db_world/rev_1678797639960580300.sql

- Changed to be considered as a flask.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4930
in the issue, also https://www.wowhead.com/wotlk/spell=33053/mr-pinchys-blessing#comments
- tested 
.aura 33053 -- pinchy blessing
.aura 67017 -- stoneblood flask
Should overwrite each other. …

fix(DB/spell_group): Mr Pinchy's Blessing stacking with similar effects.

---

data/sql/updates/db_world/2023_03_11_06.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB): fix query

---

src/server/game/Entities/Player/Player.cpp

Fixes #10726
- Closes #10726
- Closes https://github.com/chromiecraft/chromiecraft/issues/3060
`.event start 8`
`.additem 49856`
`.additem 49857`
`.additem 49858`
`.additem 49859`
`.additem 49860`
`.additem 49861`
use all of them
respec …

fix(Core/Spells): Do not remove item casted auras on respec.

---

data/sql/updates/pending_db_world/rev_1679003943676070400.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/Spells) Fix Summon Morcrush Shardling Serverside Spells

---

src/server/game/Server/WorldSocket.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/de4340af37d9af403b42fff7129bb39693a021b6)
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/PacketIO): Require valid WorldSession for CMSG_KEEP_ALIVE

---

src/server/game/Achievements/AchievementMgr.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/af5bd270c3b6628b126e0fde8aa2069a552484bd)
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Achievements): Add log for missing achievement

---

src/server/game/Battlegrounds/ArenaTeam.cpp
src/server/game/Battlegrounds/ArenaTeam.h
src/server/game/Battlegrounds/ArenaTeamMgr.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/3f3dee804904042486741320519553a49c3149bb)
-  Do not process weekly distribution for teams that have 0 games played. To prevent possible lag
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Arena): Fix lag caused by arena distribution

---

data/sql/updates/pending_db_world/rev_1679194930369616000.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15462
- Closes https://github.com/chromiecraft/chromiecraft/issues/5198
- 
- 
1.
2.
3. …

fix(DB/Creature): Update Charming Totem movement

---

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp

fix(Scripts): Crashfix.

---

src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h
src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp

-  Fixes flickering animation, correct spawns/move points with sniffs

fix(Scripts/IcecrownCitadel): Rewrite the Spire Frostwyrms

---

src/common/Utilities/Util.h
src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/mechanar.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Mechanar): Modernize Mechano Lord Capacitus script

---

src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_gyrokill.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_ironhand.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/mechanar.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Mechanar): Modernize Gatewatchers script

---

data/sql/updates/pending_db_world/rev_1679267535485784600.sql
src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15377
- 
- 
1.
2.
3. …

fix(Scripts/Mechanar): Fix Mechano-Lord Capacitus's Nether Charges

---

src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_gyrokill.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_ironhand.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/mechanar.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Mechanar): Modernize Serpethrea script

---

src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

refactor(Scripts/Mechanar): Modernize Pathaleon's script

---

data/sql/updates/pending_db_world/rev_1679277561975731600.sql
src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Mechanar): Few updates to Sepethrea

---

data/sql/updates/pending_db_world/rev_1679102126965546700.sql

-  
-  
- Closes 
TrinityCore
- 
- 
1.
2.
3.

fix(DB/Arcatraz): Fix Arcatraz Sentinels and Corpses

---

src/server/game/Grids/ObjectGridLoader.cpp

Fixes #14645
Fixes all other problems with creatures not attacking each other without moving or any action.
- Closes #14645
- Closes https://github.com/chromiecraft/chromiecraft/issues/4806
`.go c 70186` …

fix(Core/Grids): Creatures should attack when loaded into grid.

---

data/sql/updates/pending_db_world/rev_1679322279120913800.sql

- 
- Closes 
TrinityCore and/or Mangos
- 
- 
1.
2.
3.

fix(DB/Mechanar): Update The Mechanar SAI scripts for trash mobs

---

data/sql/updates/pending_db_world/rev_1679303594025981500.sql
src/server/scripts/Outland/zone_zangarmarsh.cpp

- Move from hardcoded script to SAI.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4840 (orientation is correct)
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/4147
- Progress https://github.com/chromiecraft/chromiecraft/issues/4697
https://github.com/TrinityCore/TrinityCore/issues/24635
Co-authored-by: offl <offl@users.noreply.github.com>
- tested
.q a 9785
,go c id 17900
,go c id 17901
.modify rep 942 friendly/honored/revered/exalted
See if you get the correct buffs
```c++
// Ashyen
SPELL_BLESS_ASH_EXA         = 31815,
SPELL_BLESS_ASH_REV         = 31811,
SPELL_BLESS_ASH_HON         = 31810,
SPELL_BLESS_ASH_FRI         = 31808,
// Keleth
SPELL_BLESS_KEL_EXA         = 31814,
SPELL_BLESS_KEL_REV         = 31813,
SPELL_BLESS_KEL_HON         = 31812, …
```

fix(DB/SAI): Move Ashyen & Keleth to SAI.

---

src/server/game/Entities/Unit/Unit.cpp

-  adds dismount helper for module support
-  
- Closes 
- 
- 
1.
2.
3.

add (core): Dismount Helper

---

data/sql/updates/pending_db_world/rev_1679351113405999500.sql

In preparation of the Pathaleon event I've added actions 223 (DO_ACTION) to the creatures below
```
UPDATE `smart_scripts` SET `action_type` = X, `action_param1` = Y, `action_param2` = Z WHERE `id`=1003 AND `entryorguid` IN (-138820, -138869, -138893, -138879);
```
To my knowledge, I cannot figure out *exactly* how this event is scripted. But there are a couple of things I know for sure:
1. There are **no** trigger NPCs
2. There are **no** AreaTriggers
3. On Aggro, they use SpellID 34427
I've speculated that they have, on spawn, SpellID 34426 (Greater Invisibility (Passive)), which then allows them to trigger the event once a player gets within LoS
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15373
Retail Sniffs
- 
- 
1. `.go xyz 291.8 -27.8 25.4 554 3`
4. Move …

fix(DB/SAI): Implement Gauntlet/Bridge Event in The Mechanar

---

data/sql/updates/pending_db_world/rev_1679368320710232700.sql
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Misc): Fix bosses not reseting after the despawn update

---

data/sql/updates/pending_db_world/rev_1677089599224449400.sql

-  Add Flying Carpet to the tailoring trainers that were missing it
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15157
https://www.wowhead.com/wotlk/spell=60969/flying-carpet#taught-by-npc
- Checked the listed creatures to make sure they have the spell available in their list
1. Check the creatures listed in the SQL and make sure they have the spell available to train …

fix(DB/Trainer) Add Flying Carpet to Tailoring trainers

---

src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Mechanar): Raging Flames may target tanks

---

data/sql/updates/pending_db_world/rev_1679478116786061100.sql
src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp
src/server/scripts/Outland/TempestKeep/Mechanar/mechanar.h

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Mechanar): Implement Pathaleon's spawn

---

data/sql/updates/pending_db_world/rev_1679427813010713900.sql

-  Fixes some deprecated scripts
-  Does not touch on Slavehandlers and Drudges, those will be handled later
- Closes 
ACID and TC
- 
- 
1.
2.
3. …

fix(DB/SAI): Update Steamvault combat SAI

---

src/server/game/Entities/Player/Player.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Players): Fix typo

---

data/sql/updates/pending_db_world/rev_1677249657204460100.sql

- Remove ranged_movement from SAI
- Remove cast flag 1 (interrupt) from Hex of Ravenclaw
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11362
- Closes https://github.com/chromiecraft/chromiecraft/issues/3422
In the issue
- tested
.go c id 1947
Confirm that he follows you and melee attacks you between casts
Confirm that he doesn't interrupt his own spells …

fix(DB/SAI): Thule Ravenclaw - remove ranged movement

---

data/sql/updates/pending_db_world/rev_1678972128182408900.sql

- Correct Disarm timer
- Closes https://github.com/chromiecraft/chromiecraft/issues/4893
No threat change or target change when disarm is applied. (TBC Classic)
https://youtu.be/18B98I52r8w?t=4827
https://youtu.be/D8OZU8bg6lk?t=9759
Mangos (for the actual timing)
- tested
.go c id 16544 
Check disarm timer …

fix(DB/SAI): Ethereal Thief disarm timer.

---

src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Arcatraz): Fix Soccothrates fel flame charge

---

data/sql/updates/pending_db_world/time_lost.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5278
- 
- 
1.
2.
3. …

fix(DB/Creature): Correct faction of Time-Lost Skettis NPCs

---

data/sql/updates/pending_db_world/rev_1679697224834675700.sql

-  
-  
- Closes 
TC
- 
- 
1.
2.
3.

fix(DB/SAI): Correct timers for Arcane Servant's Arcane Volley

---

data/sql/updates/pending_db_world/rev_1679620675628266300.sql

- According to sniffed data. No gobs were recycled
- Closes 
Build 47871
- 
1.
2.
3. …

fix(DB/Gameobject): Rebuild The Steamvault ores and herbs

---

data/sql/updates/pending_db_world/rev_1679777836259359200.sql

Fixes #15535
- Closes #15535
- Closes https://github.com/chromiecraft/chromiecraft/issues/5162
`.go c 76729`
.GM off …

fix(DB/Creature): Added trigger flag to Gnome Cannor Shooter.

---

src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/steam_vault.h

Fixes #15547
- Closes #15547
`.go c id 17797`
`.die`
Use Access Panel
`.go c id 17796`
`.die`
Use Access Panel …

fix(Scripts/Steamvault): Improved Door Controller event.

---

data/sql/updates/pending_db_world/rev_1679676055115473900.sql

- Ports from ACID/TC
- Closes 
ACID/TC
- 
- 
1.
2.
3.

fix(DB/SAI): Update Shadow Labyrinth combat SAI

---

src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Arcatraz): Millhouse uses Iceblock under 50 percent hp

---

src/server/scripts/Outland/TempestKeep/arcatraz/boss_dalliah_the_doomsayer.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Arcatraz): Adjust Soccrothar charge timer and implement emote

---

src/server/game/Server/WorldSession.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix (core) : Violating Flag correction

---

data/sql/updates/pending_db_world/rev_1680115354717005600.sql

-  Changes to Set In Combat With Zone
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5261
- 
1.
2.
3. …

fix(DB/SAI): Correct combat mechanics in Mechanar's Gauntlet Event

---

data/sql/updates/pending_db_world/rev_1680109188044403400.sql

-  
-  
- Progresses https://github.com/chromiecraft/chromiecraft/issues/5284 
- 
- 
1.
2.
3. …

fix(DB/Creature): Remove rep rewards for killing Skyriss Images

---

data/sql/updates/pending_db_world/rev_1680113416988440900.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/SAI): Rewrite Nether Charge SAI

---

data/sql/updates/pending_db_world/rev_1679860646913027800.sql

- Snap to ground
- Closes https://github.com/chromiecraft/chromiecraft/issues/5235
- tested
.go gameobject 25285 …

fix(DB/Gameobject): Snap Floating Ivory Bell to ground.

---

data/sql/updates/pending_db_world/rev_1680141080010135400.sql

-  
-  
- Closes 
TC
- 
- 
1.
2.
3.

fix(DB/Spell): Correct Effect of all Summon dbc spells

---

src/server/scripts/Outland/TempestKeep/arcatraz/boss_dalliah_the_doomsayer.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Arcatraz): Update timers after research

---

data/sql/updates/pending_db_world/rev_1680250223811678100.sql

-  Rewrite guid and entry SAI for Death Watcher
- **Tested** - Closes [#5294](https://github.com/chromiecraft/chromiecraft/issues/5294) …

fix(DB/SAI): Corrections to Death Watcher

---

data/sql/updates/pending_db_world/rev_1680287940145588800.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15740
- 
- 
1.
2.
3. …

fix(DB/SAI): Crashfix

---

data/sql/updates/pending_db_world/rev_1680309231242305300.sql

-  Event cannot repeat anymore (No Repeat flag)
-  
- Closes 
> As of 3.02 patch, if you die killing the guardian, you have to start all over.... ([source](https://www.wowhead.com/wotlk/item=24514/first-key-fragment#comments:id=419804))
- 
1. `.q a 9831`
2. `.q a 9832`
3. `.go ga id 182196` `.go ga id 182197` `.go ga id 182198` …

chore(DB/SAI): Move Arcane Container script to SAI

---

data/sql/updates/pending_db_world/rev_1680298149569301100.sql

- Fixes Harbringer Skyriss loot matching image below 
-  I propose gultask not try to replace me you got enough on your plate :P 
-  kidding <3 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15727
- Closes https://github.com/chromiecraft/chromiecraft/issues/5292
https://www.youtube.com/watch?v=qS7CXZzk8Qs
https://www.youtube.com/watch?v=sm7VdGKY2EA
https://www.youtube.com/watch?v=JXiFiz9Ga5w
https://www.youtube.com/watch?v=HuDJJLQd9rQ
https://www.youtube.com/watch?v=-4qHcScnR3k
https://www.youtube.com/watch?v=iyo7nt_NmXw
https://www.youtube.com/watch?v=4S67iYnePoM
https://www.youtube.com/watch?v=fLUK1Ax2zPs
https://youtu.be/6ygGxca781A
I think those are the exact sources used to solve this, plus or minus a video or two as I did have to sort out some pserver videos, I …

fix(db/loot): Harbinger Skyriss Normal Loot

---

src/server/game/Entities/Pet/Pet.cpp

- Fixes `Pet::resetTalentsForAllPetsOf` for stabled pets
cf #9712 
- Fixes https://github.com/azerothcore/azerothcore-wotlk/issues/12363
- Fixes https://github.com/azerothcore/mod-eluna/issues/107 …

fix(Core/Pet): fix Pet::resetTalentsForAllPetsOf for stabled pets

---

data/sql/updates/pending_db_world/infinite.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(DB/Quest): Prevent infinite spawning of [DND]Spirit 1

---

data/sql/updates/pending_db_world/sentinel2.sql

-  Changes from ON_AGGRO to ON_RESET
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15758
- Closes https://github.com/chromiecraft/chromiecraft/issues/5311
- 
1.
2.
3. …

fix(DB/SAI): Fix Arcatraz Sentinels spawning at 1 health

---

.github/ISSUE_TEMPLATE/bug_report.yml

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/15734
-  
-  
- Closes 
- 
- 
1.
2.
3. …

chore(Github): clarify OS in issue themplates

---

src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp

should now only complete on heroic mode
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15728
- Closes https://github.com/chromiecraft/chromiecraft/issues/5293
the quests are all heroic only :)
- simple test by myself done following the little guide below. it doesn't complete on final boss kill on normal, but it does on heroic! so it is working as intended!
- other people need to test as well :)
1. .quest add 10886
2. go to arca normal
3. do event with last boss and millhouse
4. see (hopefully) that quest doesn't complete
5. go out and set difficulty to heroic
6. do the same event
7. see that event completes now …

fix(Scripts/Arcatraz): fix Trial of the Naaru: Tenacity complete condition

---

data/sql/updates/pending_db_world/rev_1680272944718299700.sql

fix(DB/SAI): Change castflags for Death Watcher's Death Count

---

data/sql/updates/pending_db_world/rev_1680343869738404700.sql

- Adds missing pattern drop at 3.25% (wowhead values slightly rounded and corrected total)
- Fixes the loot tables in the manner shown below
- Closes 
https://www.youtube.com/watch?v=CcLPt5Bg5L8
https://www.youtube.com/watch?v=WX06P63yqFQ
https://www.youtube.com/watch?v=SiWj17m7ACs
https://www.youtube.com/watch?v=gpUpd1LTY0Q
https://www.youtube.com/watch?v=G_Aoygd48Hs
https://www.youtube.com/watch?v=_GOa7l1IyRE
https://www.youtube.com/watch?v=oRcIjh1l7CE
https://www.youtube.com/watch?v=lhqEbp3Lr0I
https://www.youtube.com/watch?v=33vQJsua9R8
it also matched tbcmangos when checked against theirs in functionality
- 
- 
1.
2.
3. …

fix(db/loot): Fix Warlord Kalithresh Normal Loot

---

src/server/game/AI/SmartScripts/SmartScript.cpp

Fixes #15515
- Closes #15515
`.go c id 12476`
Damage the pack to below 40%
Notice no rejuvenation is casted by the Oracle to anyone …

fix(Core/SmartScripts): Fixed `SMART_EVENT_FRIENDLY_HEALTH_PCT` event.

---

src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_baron_geddon.cpp

-  Fix Bardon Geddon Inferno Damage
-  Source: Vmangos (https://github.com/vmangos/core/pull/1853)
Vmangos (https://github.com/vmangos/core/pull/1853)
See linked page for additional sources and info
- Compiles, not yet tested in game
1. Engage Baron Geddon, confirm damage is correct for each tick …

fix(Scripts/Molten Core): Correct Baron Geddon Inferno damage values

---

src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

feat(Scripts/IcecrownCitadel): Allow game masters to skip boss checks

---

data/sql/updates/pending_db_world/rev_1680487892209055100.sql

-  Uses timer variance shown below to slow the spam from Darkshire City Hall NPCs
- Closes nothing I could find, but I know I've heard complaints about this specific area
Screenshot above
- Ran SQL made sure it worked right
- 
1.
2.
3.
**For …

fix(db/SAI): Slow down Darkshire City Hall broadcasts

---

data/sql/updates/pending_db_world/rev_1680504193702080400.sql

- Correct most spell timers and cast flags.
- Add missing flee at 15%
- Move Officer's Thrash to _addon
- Closes https://github.com/chromiecraft/chromiecraft/issues/2517
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9602
Mangos for timers
- tested
All creatures should flee at 15%, except Prospector Khazgorm.
.go c id 3375
They should move to melee and cast torch toss less frequent. …

fix(DB/SAI): Correct Bael'dun creatures not fleeing.

---

data/sql/updates/pending_db_world/rev_1680516450079841800.sql

TrinityCore/TrinityCore/issues/18569
- add missing RP
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12259
- Closes https://github.com/chromiecraft/chromiecraft/issues/3703
- tested
.q a 4129
.go quest ender 4129
Turn it in, confirm RP happens …

fix(DB/SAI): Port The Knife Revealed RP from Trinity.
