azerothcore/azerothcore-wotlk

data/sql/updates/pending_db_world/rev_1677239119416820500.sql

- Add the missing no repeat flag, was already in the SAI's comment.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11461
- Closes https://github.com/chromiecraft/chromiecraft/issues/3338
- tested
.go gameobject id 17155 
Click it without looting, notice 1x mob spawns and shoots you
Click it again, without looting, notice nothing happens …

fix(DB/Gameobject): Defias Gunpowder - add no repeat flag.

---

src/server/game/Entities/Unit/Unit.cpp

Allow all unit deaths to call the OnUnitDeath(victim, killer) hook.
-
- Tested OnUnitDeath for player death and it works.
1. Test any module with this hook.
- You should have nullptr validation inside of this hook for your modules because there is none prior.
- Some modules using this hook may need to be updated if they assume it is still only relevant for creatures. …

fix(Core/Hook): Call OnUnitDeath for all unit types.

---

data/sql/updates/pending_db_world/rev_1676626501770430659.sql

Closes #15079
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15079
1. Enter The Shattered Halls
2. Attack Sharpshooter Guard …

fix(DB/ShatteredHalls) Sharpshooter Guard use Viper Sting in Normal mode

---

data/sql/updates/pending_db_world/rev_1677266850243629600.sql

The same menuID contains the npc_text for both active and inactive status.
- Require Pirates' Day (event 50) to be active in order to show the appropriate text.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11327
- Closes https://github.com/chromiecraft/chromiecraft/issues/3307
- tested
.go c id 2496
Check gossip
If not Pirates' Day = "... I hope your stay in my town ..."
.event start 50
If Pirates' Day = "... Don't mind DeMeza ..." …

fix(DB/Conditions): Baron Revilgaz - correct gossip for Pirates' Day

---

data/sql/updates/pending_db_world/fix-enraged-soul-triggers.sql

-  Give enraged soul triggers the trigger flag in `flags_extra`
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15174
- Closes https://github.com/chromiecraft/chromiecraft/issues/5075
- .go c 73995
- Observe that when killed you do not see the triggers appear while GM mode is OFF.
- Same process for each enrage soul type
- .go c 73995
- Observe that when killed you do not see the triggers appear while GM mode is OFF.
- Same process for each enrage soul type …

fix(DB/Trigger): Give Enraged Soul triggers the trigger flag

---

data/sql/updates/pending_db_world/rev_1677339915510744100.sql
src/server/game/Entities/GameObject/GameObject.cpp

Authored-By: Shauren <shauren.trinity@gmail.com>
Cherry pick from: https://github.com/TrinityCore/TrinityCore/commit/a26304478d9505713dfadb9b04a3bda4cef57545
-  Makes chests that have no loot but are quest-related (Rotten Arakkoa Eggs, Draenei Vessel, etc) lootable
-  Removes my old hack fix
- Closes 
TC
- 
1. `.q a 10028`
2. `.tele Tuurem`
3. See that both trapped and lootable Draenei Vessels are available
4. `.go zonexy 44.28 55.78 3932`
5. `.quest add 10547`
6. See that both trapped and lootable Rotten Arakkoa Eggs are available …

fix(Core/Gameobject): Fix lootable chests related to quests but not having quest loot

---

data/sql/updates/pending_db_world/rev_1677450429923552400.sql

-  Add show gossip menu condition upon quests Zapped Giants (7003) and Fuel for the Zapping (7721) have been rewarded.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12263
- Closes https://github.com/chromiecraft/chromiecraft/issues/3699
- tested
.go c id 14637
check gossip, see if it says "Maybe it wasn't the best place for a shop after all..."
.quest a 7721
.quest c 7721
.quest a 7003
.quest c 7003
turn in both quests and check gossip, should be "Well hello again..." …

fix(DB/Conditions): Show correct Zorbin Fandazzle gossip on quests rewarded.

---

data/sql/updates/pending_db_world/rev_1671948396193749028.sql
src/server/scripts/Northrend/zone_dragonblight.cpp

Co-authored-by: @r4d1sh
-  
-  
- Closes 
https://github.com/TrinityCore/TrinityCore/pull/28372
- Tested
- 
1. .aura 47447
2. .add 36770
3. …

fix(Core/Scripts): Zort's Protective Elixir

---

data/sql/updates/pending_db_world/rev_1677805981976626800.sql

-  These flags are sniffed, that's why I'm not using bitmask operations
-  
- Closes 
Detected build: V3_4_0_46368
- 
1.
2.
3. …

fix(DB/Creature): Correct Flags for Raging Souls

---

data/sql/updates/pending_db_world/rev_1677797244323339200.sql

-  Too many friendly NPCs can cause issues with quest credit
-  
- Closes 
- 
1.
2.
3. …

fix(DB/Creature): Add NO_PLAYER_DAMAGE_REQ flag to Socrethar

---

data/sql/updates/pending_db_world/rev_1677639790735595900.sql

-  Remove 1.X-era mobs from Mirror Lake Orchid
- Closes 
They exist in 1.12 classic, but not wotlk classic.  The rare mob is still there when it's up.
- Tested locally.
1. Goto Mirror Lake Orchid (north west of Goldshire) …

fix(DB/creature): Remove 1.X-era mobs from Mirror Lake Orchid

---

data/sql/updates/pending_db_world/rev_1677410180671468300.sql

Fixes #14524
- Closes #14524
- Closes https://github.com/chromiecraft/chromiecraft/issues/4510
Test melee and ranged hits on a mage with the blazing speed talent and an active damage absorb shield. …

fix(DB/Spells): Blazing Speed should proc off from absorbed damage.

---

data/sql/updates/pending_db_world/rev_1677597663131840800.sql

In the issues, warrior class is mentioned, but It didn't have any issues.
- Add rogue's revered quest and remove race restrictions. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12668
- Closes https://github.com/chromiecraft/chromiecraft/issues/3896
In wotlk these quests are restricted by class, not race.
- tested
Make a NON Night Elf, Undead or Troll rogue
.level 79
.go c id 14905
.modify rep 270 exalted
Confirm that you can get every neck, starting from friendly, all the way to exalted.
Friendly 19614-> Honored 19615-> Revered19616-> Exalted 19617
Make a NON Blood Elf or Human paladin
.level 79
.go c id 14902
.modify rep 270 exalted
Confirm that you can complete the last quest and receive the exalted neck. …

fix(DB/Quest): Zandalari Tribe missing rogue quest and race restrictions.

---

src/server/game/Spells/SpellEffects.cpp

Fixes #14664
- Closes #14664
- Closes https://github.com/chromiecraft/chromiecraft/issues/4738
`.setskill 202 235`
`.additem 10588`
Fight a NPC using the Helmet …

fix(Core/Spells): Goblin Rocket Helmet should not cause auto-attack.

---

data/sql/updates/pending_db_world/rev_1677495939101704800.sql
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/boss_falric.cpp
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/boss_marwyn.cpp
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.h
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp

I'm sorry.
- Fixed every creature_text (all were duplicates with empty broadcasts_text, from initial sniffs I guess?)
- Added Wave mobs death text (rare, 1 in 10, from various sources)
- Added Marwyn speech between wave 6 and 9 (starting after a wipe) (also fixed Felrick talking while dead)
- Fixed the entire Alliance side RP
- Fixed few lines of hardcode (starting gossip and quel'delar spawn)
- Delayed Battered Hilt RP slightly (was overlapping)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/773
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8989
https://www.wowhead.com/wotlk/npc=38113/marwyn#comments:id=1013045
https://wowpedia.fandom.com/wiki/Marwyn_(tactics)
https://wowpedia.fandom.com/wiki/Falric_(tactics) …

fix(Scripts/Instances): Halls of Reflection - Fix Alliance side, text broadcasts and hardcodes.

---

data/sql/updates/pending_db_world/rev_1678042235460663800.sql
src/server/scripts/World/item_scripts.cpp

-  Changes from script to serverside spell
-  Attempts to fix exploit around it as well
- Closes 
- 
1. `.quest add 10832`
2. use item in `.tele Netherstorm` …

chore(Core/Scripts): Use serverside spell instead of SummonCreature for Nether-wraith Beacon

---

data/sql/updates/pending_db_world/rev_1678173710393604400.sql

- Added aggro on spawn and missing text (said only once, on spawn)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13917
https://youtu.be/U3wXnt4YS2w?t=204
- tested
.additem 30850
.go xyz 4716.976074 3336.434326 191.614655 530
Use the item, mob will aggro on spawn and say the line.
Leave combat without killing the npc, aggro again, will not say the line again. …

fix(DB/Creature): Avatar of Sathal missing text.

---

data/sql/updates/pending_db_world/rev_1677781820338823400.sql

- Fixes Against the Legion and related quests to appear correctly when requirements are met
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15129
- Closes https://github.com/chromiecraft/chromiecraft/issues/5039
- Tested in game, works
See original issue reports. …

fix(DB): Against the Legion requirements

---

data/sql/updates/pending_db_world/rev_1678062827982837200.sql

-  Removes creature 138
-  Just look at this thing, what's it doing?  be gone.
https://wowgaming.altervista.org/aowow/?npc=138
This doesn't exist anywhere, nor should it.  If you can prove me wrong I'd be very interested to see it.
**For …

fix(db/creature_template): Remove creature 138

---

data/sql/updates/pending_db_world/rev_1678084806976383500.sql

Didn't even notice they were empty . . . (Was updating empty rows)
https://github.com/azerothcore/azerothcore-wotlk/pull/15160/files#diff-932bbc99b527b7ea8aa199559d97615d26286f877a2e0b4a20f3ef9c170768bdR135
https://github.com/azerothcore/azerothcore-wotlk/pull/15087/files#diff-b4a6ffc3678affd0f162d0c946212920a31b9da6f455cca754d7519aad465a10R8 …

fix(DB/Movement): Unpopulated rows from previous PRs.

---

data/sql/updates/pending_db_world/rev_1678529764517694100.sql

Aeonus should drop two pieces of gear as set
-  Splits Aeonus loot into two categories and creates an entry so 1 of each category drops  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5153
Linked in issue, also I found more videos to establish this as the correct separation in the table 
- Tested locally, works great
1. Kill Aeonus (17881):  .npc add 17881  .damage 237482323 or something
2. Loot
3. .respawn and repeat if desired  …

fix(db/loot): Fix Aeonus Normal Loot Drops

---

src/server/scripts/Outland/zone_hellfire_peninsula.cpp

- Fix MoveFollow distance and angle
- (On the same check as search for boars) - Despawn if owner doesn't have the quest.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14294
- Closes https://github.com/chromiecraft/chromiecraft/issues/4595
- tested
.go c 58690
.quest add 10629
Use item
Notice the hound following you like a pet.
Kill some boars, abandon quest or finish it, hound should despawn within 5s. …

fix(Scripts/Creature): Fel Guard Hound not despawning.

---

data/sql/updates/pending_db_world/rev_1678542211338425200.sql

-  Set Temporus Level 72 down from 73  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5151
voice in my head, but also wowhead and looks like an issue was already up
- 
- 
1.
2.
3. …

fix(db/creature_template): Set Temporus Level 72

---

src/server/scripts/Spells/spell_warlock.cpp

-  Remove extra 0.9f added to health cost
-  Adjusted fizzle calculation to be the same as health cost
- Use SpellBaseDamageBonusDone() to get the casters shadow spellpower
- Closes 
- Used various ranks of life tap at hp cost and hp cost +1 to test the fizzle
- Used various ranks of life tap with different amounts of (shadow)spellpower to see that restores the correct amount of mana
.learn 27222
.mod hp 1124
cast Life Tap -> Fizzle
.mod hp 1125
cast Life Tap -> Works …

fix (Core/Spells) Correct Life Tap mana gain and cleanup

---

src/server/scripts/Outland/zone_shattrath_city.cpp

-  Add a 5 second timer for Raliq the Drunk to animate drinking.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14916
- Checked time on retail, consistently 5 seconds.
- Observed 5 second time between drink animations.
1. .tele Shattrath
2. Go to Worlds End Tavern
3. Observe Raliq the Drunk and use /timer to time his drinks …

fix(Scripts/Creature): Add 5 second timer for Raliq the Drunk to animate drinking

---

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5156
- 
- 
1.
2.
3. …

fix(Scripts/BlackMorass): Don't pick the same rift spot in succession

---

src/server/game/Grids/Notifiers/GridNotifiers.h

Fixes #12355
- Closes #12355
`.go xyz -11810.099609 -1882.400024 46.074501 309`
kill the nearby hostile ZG mobs.
interact with the object at the coordinates (character must be level 65 or below)
see if the mind controlled character attacks the nearby critters.
if needed, spawn more critters using `.npc add temp 2914` …

fix(Core/Players): Charmed players should not attack critters.

---

data/sql/updates/pending_db_world/rev_1677339050428804700.sql

Fixes #14727
- Closes #14727
- Closes https://github.com/chromiecraft/chromiecraft/issues/3875
`.go c 52416`
`.mod rep 909 4999`
Look at quest, still available as it should be
`.mod rep 909 5001`
Look at quests - the old (the rep) ones are replaced by the new (the non-rep) ones …

fix(DB/Quest): Fixed rep requirements for some Darkmoon quests.

---

data/sql/updates/pending_db_world/rev_1678614761475144800.sql

-  Solves/corrects Warp Splinter loot in similar manner to Aeonus
- 2 items drop every time now instead of 1-2 items
- Closes 
both YT videos/and logical sorting of wowhead drops agree with this sorting
- spawned and killed it locally since I changed the SQL a bit from last time to take up less lines (though its basically the same, I wanted to be sure)
1.  .npc add 17977 .damage 43284324 
2.  loot it
3.  .respawn as much as desired …

fix(db/loot): Fix Warp splinter Normal Loot Drops

---

src/server/game/Battlefield/Zones/BattlefieldWG.h
src/server/game/Spells/SpellMgr.cpp

-  When you were capturing a workshop, when the bar was at gray (neutral), the workshops weren't updating to neutral team and the team who was owning the workshop still had more vehicles while it was neutral
-  Change workshop/GY to neutral
- Closes 
- Build without error
- 
1. .tele wintergrasp
2. start wintergrasp
3. go to some graveyard/workshop and cap it …

fix(Core/BattlefieldWG): Workshops/Graveyard not changing to neutral

---

data/sql/updates/pending_db_world/rev_1677428934650582700.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12130
- tested
be horde
.tele orgri
.learn 16609
find it in your spell book and click it
Confirm that it doesn't pvp flag you …

fix(DB/spell_custom_attr): Warchief's Blessing - add NO_PVP_FLAG.

---

data/sql/updates/pending_db_world/rev_1679005184533517400.sql

- Also removes Attack Nearest Player. They weren't attacking because they were level 6.
- Added aura to Heroic version as well
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Creature): Correct level for Sethekk Spirit for Heroic

---

src/common/Debugging/WheatyExceptionReport.cpp

* clarify that this is not the crash error, but an error with the crash report itself
* improve formatting and message boundaries
* warn the reader that this means the call stack symbols may be inaccurate
* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/6e37438e5dadd30dc2ce36e468045e0be4d26c83)
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Debugging): Improve SymInitialize fail message

---

src/server/game/Battlefield/Battlefield.cpp
src/server/game/Battlefield/Battlefield.h
src/server/game/Battlefield/Zones/BattlefieldWG.cpp

At the setup|Battlestart|Battleend of wintergrasp all WS were owned to attacker team, now only SW and SE are owned by Attacker, the rest are for Defender team
https://github.com/azerothcore/azerothcore-wotlk/issues/603
Valdifer
-  Set WS/GY from SW/SE to Attacker and the rest to Defender
-  Relocate alliance players when attacking WG to not appear in the air
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/603
- Build without error
- Capturing wintergrasp and wait until next battle to capture again with the contrary faction
- Restartint the server to see the owner of WG
1. Join WG war
2. Check workshops capturepoints sliders are correct
3. Win wintergrasp (Alliance or Horde)
4. Wait until the next war (You can change the timer in worldconfig.dist or editing the values in …

fix(Core/Battlefield): Wintergrasp Workshops SW/SE to Attacker

---

src/server/scripts/World/npc_taxi.cpp

All gossip was already in db and properly linked.
-  Removed unused action 23 and 24, used by Bat Handler Camille 23816 (Smart AI)
-  Removed hardcoded texts and improve readability 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4142
- 
1.
2.
3. …

fix(Script/Core): Remove hardcoded gossips in npc_taxi

---

data/sql/updates/pending_db_world/rev_1679268639264716700.sql
src/server/scripts/Spells/spell_generic.cpp

Authored-By: offl <11556157+offl@users.noreply.github.com>
ImmuneToAll is provably and demonstrably false. Removal might cause issues down the line but **These are fixed by sniffed unit_flags that are not changed by these auras**
ReactStates can be modified by script. Agressive ReactStates are able to aggro, it seems
-  
-  
- Closes 
Cherry-Pick from: https://github.com/TrinityCore/TrinityCore/commit/43f63d76315ec251cc04d70ec6ee811aef9d1176
- 
- 
1.
2.
3. …

fix(Core/Spells): Improve Feign Death scripts

---

src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_captain_skarloc.cpp

Quick fix, also timers are way off.
- Fix wrong spell for the event (cleanse duplicate) 
- tested
.go xyz 2055 235 64 560
.npc add temp 17862 …

fix(Scripts/Instances): Old Hillsbrad Foothills - Captain Skarloc casting wrong spell

---

src/server/scripts/Spells/spell_warrior.cpp

Fixes #15464
- Closes #15464
- Closes https://github.com/chromiecraft/chromiecraft/issues/5196
`.learn 46924`
`.learn 12328`
`.go xyz 2113.94 -4670.22 44.58 1`
Cast Sweeping Strikes and then Bladestorm …

fix(Scripts/Spells): Bladestorm vs Sweeping Strikes.

---

data/sql/updates/pending_db_world/rev_1679336075957797300.sql

Negatron Screamer's X Energy (visual buff) was for some reason stunning them and preventing movement. So I've removed it for now but kept it commented
-  Most creatures are just ports from Mangos/TC
-  Negatron Screamer is original
- Closes 
- 
- 
1.
2.
3. …

fix(DB/SAI): Update Arcatraz Trash SAI

---

data/sql/updates/pending_db_world/rev_1679427968797026500.sql
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

- Remove duplicated SMART_ACTION_SET_GO_STATE  (202) AC Only smart action, convert all smartscripts who've previously used it to SMART_ACTION_GO_SET_GO_STATE (118) (Which aligns that action ID with trinity)
- Uncomment SMART_ACTION_PLAY_CINEMATIC, it has been added in https://github.com/azerothcore/azerothcore-wotlk/pull/10231/files but never got uncommented
- Add missing comments to sound and sound random and summon go
- Comment out SET_CAN_FLY
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15529
- tested
<details>
<summary> SMART_ACTION_PLAY_CINEMATIC </summary>
https://user-images.githubusercontent.com/46330494/226733074-3824d605-ae9e-4bb2-a489-6500f38220a9.mp4
</details>
.go c id 26814
See if the blob next to him shrivels after killing him.
Source for SET_CAN_FLY …

fix(Core/SmartScripts): Remove duplicated GO_STATE

---

src/server/game/Entities/Player/Player.cpp

Fixes #12170
- Closes #12170
- Closes https://github.com/chromiecraft/chromiecraft/issues/3597
`.go xyz -7512.347656 -1087.560303 170.121368 0 5.523251`
Take a lava bath
see the delay between damage ticks …

fix(Core/Players): Set environmental lava damage timer to 2.02 sec.

---

data/sql/updates/pending_db_world/rev_1679382605948942700.sql
src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_keleseth.cpp

- Remove MoveInLineOfSight overrride (Source below)
- Add previously missing SAY_KILL creature_text and sound
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15514
https://youtu.be/Kuw6AqYrbGM?t=219
https://www.wowhead.com/npc=23953/prince-keleseth#comments:id=1097379
https://www.wowhead.com/wotlk/sound=13223/a-kelesethkill
- tested
.go c id 23953
Should aggro from proximity …

fix(Scripts/Instance): Utgarde Keep - Prince Keleseth not aggroing

---

src/server/game/Handlers/MailHandler.cpp

- Currently, the `CanSendMail()` player hook is not called when returning a mail to sender, this PR adds the hook call.
- Compiled and ran on Windows 11, tested the hook with Eluna …

feat(Core/Mail): call CanSendMail() when returning to sender

---

src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #15458
- Closes #15458
- Closes https://github.com/chromiecraft/chromiecraft/issues/5141
Go in example botanica with warlock
Find pack with spell reflect (a lot of them have it)
Seed a mob in proximity to spell reflect mob
Watch as the explosion damage is reflected …

fix(Core/Spells): Seed of Corruption cannot be reflected.

---

data/sql/updates/pending_db_world/rev_1679241095722302100.sql

- Remove DMF (Mulgore) Building event (71) gameobjects from Brewfest (24)
- Closes https://github.com/chromiecraft/chromiecraft/issues/4153
- tested
.go xyz -1572 162 -8 1
.event start 24 (Brewfest)
There should be nothing spawning.
**For …

fix(DB/Event): (Mulgore) DMF Building event GOs in Brewfest.

---

data/sql/updates/pending_db_world/rev_1679584531586420800.sql

-  And in turn remove bad comment
- Closes 
- 
- 
1.
2.
3.

chore(DB/Creature): Use addon instead of SAI for Eyeless Watcher and Unseen Servant

---

src/server/game/Handlers/ChatHandler.cpp

- Ignore `ChatLevelReq.Whisper` when whispering yourself
- This allows using addons like AIO when below the level requirement for whispers
- Compiled and ran on Windows 11 …

feat(Core/ChatHandler): ignore chat level requirement when whispering self

---

src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp

Players now not stucking anymore in the strangulating vehicle and getting teleported
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/IcecrownCitadel): Lichking "Harvest Soul" Fix

---

data/sql/updates/pending_db_world/rev_1679709753237572800.sql
src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp

-  Lower Timer according to Retail sniffs
-  Fix some spell_dbc pollution
- Closes https://github.com/chromiecraft/chromiecraft/issues/5264
Retail
- 
1.
2.
3. …

fix(Scripts/Mechanar): Fix Mechano-Lord Nether Charges not spawning

---

data/sql/updates/pending_db_world/rev_1679692788793844600.sql

-  64 is from TC
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5257
TC for flag 64
- 
- 
1.
2.
3. …

fix(DB/Creature): Add Knockback immunity to Raging Flames

---

data/sql/updates/pending_db_world/rev_1679690789861656800.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5256
TC
- 
- 
1.
2.
3. …

fix(DB/Gameobject): Nethermancer Sepethrea door should not be useable by players

---

data/sql/updates/pending_db_world/thespia.sql
src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_hydromancer_thespia.cpp

-  Add line 'Enjoy the storm warm bloods!' when casting Lightning Cloud
-  Correct the timers using sniffs
-  Remove incorrect double-cast mechanic
- Closes 
- 
- 
1.
2.
3. …

fix(Scripts/Steamvault): Correct Timers for Thespia and add missing line

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp

Fixes #14299
- Closes #14299
- Closes https://github.com/chromiecraft/chromiecraft/issues/4590
`.go c 9382`
`.learn 32379`
Cast spell on the critter. …

fix(Core/Spells): Shadow Word: Death vs critters.

---

src/server/game/Entities/Unit/Unit.cpp

Fixes #15499
- Closes #15499
While speced into Lightning Overload, Spam Lightning bolt or chain lightning on a target dummy or mobs until it happens. It shouldn't take long. Not only is a double proc 1 in 9, a triple proc is currently 1 in 27 (and continue multiplying by 3 for quad, quint, etc) …

fix(Core/Spells): Lightning Overload  should not proc off from itself.

---

src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp

Talon King Ikiss should cast his combo at 80%, 50% and 25%. After finishing the explosion, Talon King Ikiss should reset aggro. Talon King Ikiss cast sheep randomly also in normal mode. Fixes #15466
- Closes #15466
- Closes https://github.com/chromiecraft/chromiecraft/issues/5207
- Not tested.
`.go c 138719` …

fix(Scripts/SethekkHalls): Talon King Ikiss

---

src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp

now they fight after landing and no more immun to npc/pc
-  
-  
- Closes 
- 
- 
1.
2.
3. …

Fixxing last issue on Nerubs in ICC

---

data/sql/updates/pending_db_world/rev_1680124416269252400.sql
src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp

- Use correct spell for Frenzy
- Move Disgruntled Anger to its own event (sniffed)
- Check if boss is Enraged before doing summons
- Add missing spell cast to kill adds
- Changes equipment on Frenzy
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15378
- Closes https://github.com/chromiecraft/chromiecraft/issues/5262
- 
- 
1.
2.
3. …

fix(Scripts/TheMechanar): Add missing Enrage event for Pathaleon the Calculator

---

data/sql/updates/pending_db_world/rev_1680197775441354500.sql

-  Shaleskin Flayer casts Shaleskin spell out of combat
- Closes #15010 
- Closes https://github.com/chromiecraft/chromiecraft/issues/5000
https://youtu.be/dwi2HSu5A4A?t=19
- Tested in game. They cast the spell while out of combat.
1. .go c 71848
2. check if they have cast the spell …

fix(DB/SAI): Shaleskin Flayer should cast Shaleskin out of combat

---

data/sql/updates/pending_db_world/remove-bop-quest-loot.sql

removes two quest items (Gold-Trimmed Cuffs and Bloodforged Guard) from a reference loot table used by a few mobs in Hellfire Peninsula.
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15586
If you check the old database before these two deletes you will see reference 6002 from e.g. Fel Reaver loot points to Entry 4110 in reference_loot_template. The last two entries for 4110 are Gold-Trimmed Cuffs and Bloodforged Guard, which don't belong here.
- runs using HeidiSQL
- no syntax error
- rows are removed
1. run sql queries
2. see results …

fix(DB/Loot): Remove Bloodforged Guard and Gold-Trimmed Cuffs from reference loot

---

data/sql/updates/pending_db_world/rev_1680277738222003722.sql

-  Stone Keepers now use Self Destruct
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7357
https://www.wowhead.com/wotlk/npc=4857/stone-keeper#abilities;mode:normal
- Tested
1. .teleport Uldaman then enter dungeon
2. .go xyz 95.9 263 -26.5 …

fix(DB/SAI) Stone Keepers now use Self Destruct

---

data/sql/updates/pending_db_world/rev_1680292857775237100.sql

-  Remove Death Count aura from creatures in range 50 instead of from invoker's party
-  
- Closes 
- 
Have a pet
.go c 138927
.damage 30000
Wait for Death Count debuff to be applied
.damage 30000 …

fix (DB/SAI) Also remove Death Count from non-players (pets)

---

data/sql/updates/pending_db_world/rev_1679851493822859000.sql

- Correct Mote of Shadow dropping from wrong mobs for 3.3.5
- Add the 4 missing entries, from TrinityCore
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14760
- Closes https://github.com/chromiecraft/chromiecraft/issues/4732
https://www.wowhead.com/wotlk/item=22577/mote-of-shadow#dropped-by
https://wowpedia.fandom.com/wiki/Mote_of_Shadow
TrinityCore dropchance for the missing 4
- sql runs
run sql
```sql
SELECT * FROM `creature_loot_template` WHERE `Entry` IN (16974,16975,17014,17981,18341,18683,18869,18870,19299,19307,19354,19527,19554,20554,20870,20873,20875,22295,22301) and `Item` = 22577;
``` …

fix(DB/Loot): Mote of Shadow dropping from wrong creatures.

---

data/sql/updates/pending_db_world/rev_1680294116991836000.sql

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5306
- Closes https://github.com/chromiecraft/chromiecraft/issues/5307
- Closes https://github.com/chromiecraft/chromiecraft/issues/5305
- Closes https://github.com/chromiecraft/chromiecraft/issues/5303
- Progress https://github.com/chromiecraft/chromiecraft/issues/5302
Mangos
- 
- 
1.
2.
3. …

fix(DB/Creature): Some immunities in Arcatraz

---

src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #14696
- Closes #14696
- Closes https://github.com/chromiecraft/chromiecraft/issues/4235
.additem set 506
Equip the full 3-piece set of Battlegear of Eternal Justice.
Cast judgments …

fix(Core/Spells): Fixed Battlegear of Eternal Justice set bonus.

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Maps/Map.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/c6cd272505cdca5d21935ba346df82b8c767fb13)
-  This will fix the very rare bug of characters committing indecent exposure. Which is very illegal should you know.
( Rare bug where some players appear naked for individual players)
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Player): Send player's own auras before all visible objects

---

data/sql/updates/pending_db_world/rev_1678331336012484400.sql

-  Event Phases reset after Evade. This is safer, if a bit more worrisome
-  Starts a timed despawn as soon as Karsius spawns. About 1minute after everyone despawns naturally
- Closes 
- 
1.
2.
3. …

fix(DB/SAI): Yet another fix for Teron Gorefiend not resetting

---

data/sql/updates/pending_db_world/rev_1677192762421105200.sql

I'm not sure that the option to reclaim either of them if they were deleted should exist, but it acts as a fail safe (and we like those, no?), as neither of them can be disenchanted, sold or interacted in any shape or form outside of just acting as weapons.
- Create both items at once when using the Ancient Rune Etched Stave
- Fix incorrect gossip (for 3.3.5)
- Changed Vartus the Ancient's SAI to reflect the changes in this PR.
- condition gossip_menu_options (30201) to now require:
1. both quests 7636(Stave of the Ancients) & 7635(A Proper String) to be rewarded
2. to not have either Sinew or Rune
3. to not have either Bow or Stave. 
(This will also show the option to characters that have done the quest before this PR, allowing them to obtain the alternative item.)
- Closes …

fix(DB/Conditions): Lok'delar & Rhok'delar should not be mutually exclusive.

---

data/sql/updates/pending_db_world/rev_1675140644244916700.sql

- Removes the Deadmines Cleaver drop from entry 24076 of `reference_loot_template` and creates a new independent loot for the Defias Henchman.
- https://github.com/chromiecraft/chromiecraft/issues/2220
- https://github.com/azerothcore/azerothcore-wotlk/issues/8844
https://www.wowhead.com/wotlk/item=1927/deadmines-cleaver
https://www.wowhead.com/wotlk/npc=594/defias-henchman
- 
1. Insert the new statment in your world database and execute the statement SELECT * FROM `creature_loot_template` WHERE `Entry` = 594 AND `Item` = 1927;
**REMEMBER**: …

fix(DB) Deadmines Cleaver should only drop from Defias Henchman

---

data/sql/updates/db_world/2023_04_02_09.sql
data/sql/updates/pending_db_world/rev_1680463160388009300.sql

- Remove deprecated bytes2 flags.
- Remove couple of wrong creature spawns/addons.
(for the deleted creatures)
https://www.wowhead.com/wotlk/npc=21723/blackwind-sabercat
https://www.wowhead.com/wotlk/npc=15652/elder-springpaw
https://www.wowhead.com/wotlk/npc=22100/scorpid-bonecrawler
- tested
before running sql:
1) go to the 3 GUIDs that are being deleted, confirm they are out of place.
2) Go to random GUIDs and see their SheatheState (bytes2)
```sql
SELECT * FROM `creature_addon` where `bytes2` = XXXXXXXX;
```
Apply SQL
Go to the GUIDs to confirm their SheatheState (bytes2) is correct. …

fix(DB/creature_addon): Remove deprecated bytes2 flags.

---

data/sql/updates/pending_db_world/rev_1680371174965612100.sql

- Remove Blood of the Mountain from all creatures, except Molten Destroyer and change to 13%
- Closes https://github.com/chromiecraft/chromiecraft/issues/2090
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8530
https://www.wowhead.com/wotlk/item=11382/blood-of-the-mountain#dropped-by
- sql
```sql
SELECT * FROM creature_loot_template WHERE item=11382
``` …

fix(DB/Loot): Blood of the Mountain dropping from wrong mobs.

---

data/sql/updates/pending_db_world/rev_1680608649769062300.sql

-  Seems to be caused by the Keeper of the Cistern's script playing while Earthmender is dead
- Also prevents Water Elementals from flying
- Closes https://github.com/chromiecraft/chromiecraft/issues/5148
- 
- 
1.
2.
3. …

fix(DB/Quest): Prevent Earthmender Wilda to fail quest abruptly

---

data/sql/updates/pending_db_world/rev_1680525460717061700.sql

-  Add missing condition to require tailoring for the [battlecast hood recipe](https://wowgaming.altervista.org/aowow/?item=24313) from Warlord Kalithresh
-  
- Closes 
Common knowledge that the bop recipes in TBC require the profession
Comments: https://www.wowhead.com/wotlk/item=24313/pattern-battlecast-hood#comments
- Did test as described below
- 
```UPDATE `creature_loot_template` SET `Chance`=100 WHERE `Item`=24313;```
Killed Warlord Kalithresh with and without tailoring …

fix (DB/Loot) Add Tailoring condition for the Battlecast Hood Recipe

---

data/sql/updates/pending_db_world/rev_1680678566401144700.sql

-  Removes mind control abilities from a non-existent, non-mind controllable NPC
- Closes 
This could not have been sniffed, as this NPC does not exist in the game.  I also checked the dbc files for an entry as well using WDBX.Editor to view the CreatureSpellData.dbc file as well, just incase that was where it came from, but it is not.
- 
- 
1.
2.
3. …

fix:(db/creature_template_spell): Removes strange creature 290 data

---

data/sql/updates/pending_db_world/rev_1679482307407253900.sql

-  Removes a bunch of junk loot from water barrels
- Closes 
I am the self appointed king of water barrels.
Also classic wotlk, I'm sure I've looted enough water barrels to disprove this by now, wowhead agrees also although it has other pollution that wasn't in ours.
For reference, I have yet to find a normal food/water crate that has anything other than food/water in it so anyone who desires to hunt down every table that has this type of pollution will have my backing, I ran into this while checking another issue so it was just coincidental and I couldn't just ignore it.
- 
- 
1. Check the table, the following will help:
SELECT * FROM gameobject_template WHERE entry=3658;
SELECT * FROM gameobject_loot_template WHERE entry=2502;
3.
4. …

fix(DB/Loot): Junk Loot from Water Barrels removed

---

src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp
src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_warlord_kalithresh.cpp

-  Adds spells Head Crack to Kalithresh and Enrage to Steamrigger
-  Corrects timers
- Closes 
Retail Sniffs
- 
1.
2.
3. …

fix(Scripts/Steamvault): Correct timers and add missing events

---

src/server/game/AI/SmartScripts/SmartScript.cpp

-  Before, MOVE_TO_POS would use the sum of ObjectSize + ContactDistance to calculate position, creating large distances between the source and its target
-  This change causes distances to shrink by about 1-2y, which can be significant in a few cases, but not enough to cause major issues in already existing scripts
- Closes 
- Tested on creatures and gameobjects as targets
- 
1.
2.
3. …

fix(Core/SmartAI): Prevent MOVE_TO_POS from creating large distances between target

---

data/sql/updates/pending_db_world/rev_1681510679512783100.sql

-  Update Murmur Loot Count to always drop 2 items
- Closes 
https://www.youtube.com/watch?v=kXLuDZnJLc0
https://www.youtube.com/watch?v=ht9781OYx6M
https://www.youtube.com/watch?v=axb9b6NkXdM
https://www.youtube.com/watch?v=q1Ms3jSTVsQ
https://www.youtube.com/watch?v=AXsjN_yiu3A
https://www.youtube.com/watch?v=0y8ewSHQ3VE
https://www.youtube.com/watch?v=aKniMhI8HrQ
https://www.youtube.com/watch?v=4VDeFdhTSSQ
https://www.youtube.com/watch?v=DC7LSTgKXng
https://www.youtube.com/watch?v=d7rzDpVEgRM
These videos also show via logical processing why I cannot draw two tables like I normally can
- 
- 
1.
2.
3.
- Issue:  Due to the way the loot system works, I can not prevent it from dropping 2 of the same item unless I make up a table division
- Table division does seem to exist/is blizzlike to …

fix(DB/loot): Murmur loot count correction

---

src/server/game/Handlers/AuctionHouseHandler.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Adds a new hook that can prevent players from bidding on certain auctions
-  Designed for use with Individual Progression, but could be useful in other situations and modules
- Code compiles
- Auctions still work
1. Ensure auction bidding behavior by default is unchanged …

feat: Add CanPlaceAuctionBid hook

---

src/server/game/Entities/Unit/Unit.cpp

-  The OnAuraRemove hook should be called for owned auras.
- OnAuraRemove hook was not being called, you could not detect removed owned auras that were fired by `AURA_REMOVE_BY_EXPIRE` for example.
- Subscribed to OnAuraRemove hook and tested spell `67721` to see if it fired.
1. Attach debugger to worldserver
2. Set breakpoint at `L98` of `UnitScript.cpp`
3. Add weakness aura to self: `.aura 67721`
4. Observe the breakpoint being hit when the aura expires.
- ~~I'm not sure how to get the AuraApplication instance, so I've just passed a nullptr. Any tips here are appreciated.~~ …

fix(Core/Hook): Fix OnAuraRemove not being called for owned auras.

---

data/sql/updates/pending_db_world/rev_1681146335796877700.sql

-  Removes skinning loot from several Buzzard type mobs that should not be skinnable
No history of skinning on WoWhead for any of these creatures, and no other birds are skinnable.
- SQL runs, no longer skinnable
1. Ensure creatures no longer skinnable …

fix(DB): Several creatures incorrectly skinnable

---

data/sql/updates/pending_db_world/rev_1680858441993201000.sql

- Make members aggro with leader (everyone assist everyone)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14004
- Closes https://github.com/chromiecraft/chromiecraft/issues/4511
- tested
.go c id 2172
Pull Clutchmother , see if the adds aggro. …

fix(DB/creature_formations): Aggro Strider Clutchmother adds 

---

data/sql/updates/pending_db_world/rev_1681829644195320500.sql

They already have Shadowform (37816) as a template_addon.
- Remove https://www.wowhead.com/wotlk/spell=36471/rapid-pummel from SAI.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5250
https://www.wowhead.com/wotlk/npc=20668 / Mangos & Trinity
- tested
.go c id 20668
They should not cast any spells. …

fix(DB/SAI): Remove wrong spell from Fiendling Flesh Beast.

---

data/sql/updates/pending_db_world/rev_1681209847729403600.sql

-  Remove Roughshod Pikes from creature loot
- Closes 
They are from an object, not a drop.  Even more definitely not from a quest NPC in Redridge.
- 
- 
1.
2.
3. …

fix(DB/loot): Remove Roughshod Pikes from creature loot

---

data/sql/updates/pending_db_world/rev_1681812895352552200.sql

- Correct SAI for 22199 (Slaag), 20600 (Maggoc) and 20216 (Grulloc) 
- Add creature_texts (from wowhead) for Grulloc
- Closes https://github.com/chromiecraft/chromiecraft/issues/5285
- Closes https://github.com/chromiecraft/chromiecraft/issues/5286
- Closes https://github.com/chromiecraft/chromiecraft/issues/5287
Mangos
https://www.wowhead.com/wotlk/npc=20216 quotes
- tested
.go c id 22199
Should periodically cast Enrage (with emote) and Dust Field
.go c id 20600
Should stack mortal wound
Should cast Rock Rumble and Boulder on random players that are outside of melee range (Need 2+ characters to test OR root him)
.go c id 20216
Should periodically cast Burning Rage (with emote)
Should cast Grievous Wound to random melee player periodically. …

fix(DB/SAI): Correct Slaag, Maggoc and Grulloc.

---

data/sql/updates/pending_db_world/rev_1681039053601489100.sql
data/sql/updates/pending_db_world/rev_1681039353004394600.sql

-  Sets respawn timer to 2m
-  Based on NPC Time estimates after observed de-spawning 
- Closes 
Classic WotLK PTR
- 
- 
1.
2.
3. …

Fix:(DB/creature): respawn timer for Corporal  Keeshan corrected

---

data/sql/updates/pending_db_world/rev_1681730931684054700.sql

- Correct spawn position
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15033
- Closes https://github.com/chromiecraft/chromiecraft/issues/5031
Mangos
- tested
.go xyz -3349.74 2145.51 -7.24 530
.add 30672
Use item
**For …

fix(DB/event_scripts): Infernal Oversoul spawn position.

---

data/sql/updates/pending_db_world/rev_1681758967243313800.sql

You should be able to interact with the Pad after completing 10270, since you've "repaired" it. (the entire point of the quest)
- Remove the previous mess of conditions and add COMPLETE and REWARDED condition for quest 10270. 
- Reduce range check for Image of Wind Trader Marid to 10y, from 200.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5074
https://wowpedia.fandom.com/wiki/Ethereal_Teleport_Pad + Possibility of being locked out of the quest chain.
- tested 
.go gameobject id 184073
.q a 10270 
Interact with the pad, no gossip.
.q c 10270
Interact with the pad, gossip should be there.
Turn in the quest without accepting the follow up.
Wait for Image of Wind Trader to despawn and interact with the pad again, gossip should be present. …

fix(DB/Conditions): Allow gossip with Ethereal Teleport Pad after quest 10270.

---

data/sql/updates/pending_db_world/rev_1681729297995153300.sql

- Add CD to the spells.  
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/15035
- Progress https://github.com/chromiecraft/chromiecraft/issues/5033
In the issue(s)
- tested
.go zonexy 40.74 21.65 3943
.quest add 10612
Take control of a Fel Reaver Sentinel with one of the consoles in front of you
Use the spells, see if they have cooldown. …

fix(DB/spell_cooldown_overrides):  Fel Reaver Sentinel spells not having CD.

---

data/sql/updates/pending_db_world/rev_1681793209169080500.sql

- Closes #15996
https://youtu.be/8OEHi3WldNg?t=1686
- ### Before
- ### After …

fix(DB/ShadowLabyrinth): Apply 'Incite Chaos' as debuff

---

data/sql/updates/pending_db_world/rev_1681888475108592400.sql

-  Head of Ortor of Murkblood will no longer drop from pickpocketing Ortor
- https://github.com/chromiecraft/chromiecraft/issues/5239
Debunked wowhead comment, as seen in the issue, and tested via classic wotlk PTR
- 
- 
1.
2.
3.
**For …

fix(DB/loot): Remove pickpocket loot error item 24543

---

data/sql/updates/pending_db_world/rev_1681824132109329700.sql

Shouldn't the trapped and non trapped object be pooled?
- Add knockback and emote SAI for Bogblossom Bunny.
- Add despawn SAI for Bogblossom (Goober, that spawns the actual trap).
- Closes https://github.com/chromiecraft/chromiecraft/issues/5163
https://github.com/TrinityCore/TrinityCore/commit/6fc2c62883b18be58201608848dadf348d1d91fe
- tested
Be a druid
.q a 10961
.go gameobject 20375
See if it knocksback and despawn after. …

fix(DB/SAI): Bogblossom trap - knockback and despawn.

---

data/sql/updates/pending_db_world/rev_1681332432499578800.sql

Scraps drop during the next quest (10748) as well, unknown if they stop dropping after those 2 quests or not (10722 and 10748)
-  Require quest 10722 (Meeting at the Blackwing Coven) to be complete, in progress or have been rewarded in order to see Costume Scraps.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4993
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15004
https://www.wowhead.com/wotlk/item=31121/costume-scraps#comments
Scraps drop during the next quest as well, unknown if they stop dropping after those 2 quests or not (10722 and 10748)
https://www.wowhead.com/wotlk/quest=10748/maxnar-must-die#comments:id=200654
> By Nevoron (271 – 3) on 2007/12/13 (Patch 2.3.0)		
Those costume scraps from the previous quest still drop, i'm collecting them right …

fix(DB/Conditions): Costume Scraps not having quest status requirements.

---

data/sql/updates/pending_db_world/rev_1681835987102434300.sql

- Add missing gossip text and condition it to show if quest 9152 has been rewarded.
- Update comment for previously existing condition.
https://wowpedia.fandom.com/wiki/Rathis_Tomber
- tested
.go c id 16224
Check gossip, should be `Ah, hello there, <race>`
accept the quest
.q c 9152
turn in the quest
check gossip again, should be `Such a delight to see you again, <class>` …

fix(DB/Conditions):  Add missing gossip text for Rathis Tomber.

---

data/sql/updates/pending_db_world/rev_1682017480991526700.sql
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
src/server/game/Entities/Unit/Unit.cpp

- Instead of ignoring all assistance, the flag will now only not call the initial assistance call sent on aggro and not subsequent ones
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15460
- Closes https://github.com/chromiecraft/chromiecraft/issues/5203
- 
1. `.go xyz 118 283 -5.5 553 0`
2. See if you can pull each trio separately
3. Fly overhead and herd the aggroed trio to another group, see if assistance is called …

fix(Core/Creature): Adjust IGNORE ASSISTANCE CALL flag to prevent assistance on initial aggro only

---

src/server/game/Spells/SpellEffects.cpp
src/server/game/Spells/SpellInfoCorrections.cpp

-  SPELL_ATTR3_SUPRESS_TARGET_PROCS is already in DBC
-  We should not clear unitstate moving.
- Closes 
- 
- 
1.
2.
3. …

chore(Spell/Effects): Small improvement to EffectDistract

---

src/server/game/Entities/Player/Player.cpp

-  Move modifications of health regen due to SPELL_AURA_MOD_HEALTH_REGEN_PERCENT out of the not in combat check so that it applies to in combat regen such as the troll racial
https://www.twitch.tv/videos/1789023535
Regenerates 19 health per tick out of combat
Counted 1s and 2s of in combat health regen ticks and they averaged out to 1.88
Would average out to ~1.72 if the extra [troll health regen](https://wowgaming.altervista.org/aowow/?spell=20555) did not apply in combat
- 
be a troll or .learn 20555
Optional: equip a lot of spirit gear and be a warrior to easily discern the difference
get in combat and look at the health ticks …

fix (Core/Player) Apply SPELL_AURA_MOD_HEALTH_REGEN_PERCENT to in combat health regen

---

data/sql/updates/pending_db_world/rev_1677147108487825000.sql
src/server/scripts/Kalimdor/zone_desolace.cpp

- Closes #12893
- Closes https://github.com/chromiecraft/chromiecraft/issues/3984
https://www.youtube.com/watch?v=NS-oEeZhm9o
- tested
.tele desolace
.go xyz -1467 1743 61
.quest add 5561
Use Kodo Kombobulator on nearby kodos.
Try to interact (speak) with them, see that you can't, unless you get them close to Smeed. …

fix(DB/Creature): Tamed Kodo - Remove gosisp flag.

---

data/sql/updates/pending_db_world/rev_1680024512309807300.sql

-  In addition to being able to fished, Darkwood Fishing Pole should be a rare drop from some worg mobs
- Cherrypicked from Vmangos: https://github.com/vmangos/core/commit/620def0c321e4acf11f8544db126b0d2a30cdfee
Vmangos: https://github.com/vmangos/core/commit/620def0c321e4acf11f8544db126b0d2a30cdfee
- SQL runs without error
1. Ensure item drops (it is a rare drop - feel free to increase drop rate to test) …

fix(DB/creature_loot_template): Darkwood Fishing Pole

---

data/sql/updates/pending_db_world/rev_1680531018840455000.sql

-  Fix rep value for Nexus Terror on Heroic
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15799
- Closes https://github.com/chromiecraft/chromiecraft/issues/5328
- SQL runs successfully
1. Kill Nexus Terror in Heroic difficulty, confirm correct rep
- We may want to double-check retail values to confirm this is correct rep value. …

fix(DB/Creature): Correct Rep for Heroic Nexus Terror

---

data/sql/updates/pending_db_world/rev_1681296870508704800.sql

-  Removes https://wowgaming.altervista.org/aowow/?item=1219 from the current creatures it drops from
-  Places it on creature [Redridge Poacher](https://www.wowhead.com/wotlk/npc=424/redridge-poacher)
- Closes 
https://www.wowhead.com/wotlk/item=1219/redridge-machete
- 
- 
1.
2.
3. …

fix:(DB/loot): Put Item 1219 onto the correct loot table

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

Should Areatriggers support troggeredFlags? I know GOs don't, judging from code.
There are no Areatriggers with param3
```sql
SELECT * FROM smart_scripts WHERE source_type=2 AND action_type=11 AND action_param3 <> ''
```
- Add Triggered Flags for CAST & INVOKER_CAST
- Add LOG_DEBUG(s)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16029
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/AI/SmartScripts/SmartScript.cpp#L555-L622
- tested
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 61;
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 61);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, …
```

fix(Core/SmartScripts): Add Triggered Flags for CAST & INVOKER_CAST

---

src/server/game/Instances/InstanceScript.cpp

This has just sloppy looking at it. Moved to Case switch with log error and else debug logging
-  Move to Case Switch
-  Add logging
- Closes None reported. Strictly Code Style
- Nothing to test. This is strictly a code style change.
1. Nothing to test. This is strictly a code style change. …

chore (core): Move to switch case

---

data/sql/updates/pending_db_world/rev_1682708323762157900.sql

-  Changes timer until Warhounds are spawned
-  Corrects the spawn positions
- Adds waypoints (creatures should not enter combat immediately)
- Closes 
- 
1.
2.
3. …

fix(DB/SAI): Correct Bonechewer Beastmaster in Hellfire Ramparts

---

data/sql/updates/pending_db_world/rev_1682809085520081000.sql

* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/2d5afb36c7b3908e47bc3ea3ed27a85ed5cebb07)
> Essence of Wintergrasp is a buff that is available for every player in Northrend, as long as the faction controls Wintergrasp. Players under the effect of the buff receive 5% more experience and are able to collect [Stone Keeper's Shards](https://www.wowhead.com/item=43228) from dungeon bosses in Northrend.
Howling Fjord area and Azjol-Nerub (Dungeon) area are missing.
Instances should be removed from spell_area (Naxxramas, The Obsidian Sanctum, Vault of Archavon and Ulduar) because only in dungeons should gain the buff.
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Spell): Correct Essence of Wintergrasp zones

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/World/World.cpp

-  Check if the victim exists, if not, there is no point in processing the delayed dmg. This will prevent the server from crashing, as the victim must not be null.
-  Also added a check before dereferencing attacker, since it could be null.
- Closes #16160 
- Closes #16142
- None
- 
1.
2.
3. …

fix: Crash on ProcessDelayedDamages

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Globals/ObjectAccessor.cpp
src/server/game/Globals/ObjectAccessor.h
src/server/game/World/IWorld.cpp
src/server/game/World/IWorld.h
src/server/game/World/World.cpp
src/server/game/World/World.h

-  Move pointers to ObjectGuid
-  Add a secondary function to ObjectAccessor to allow it to return units with a map as parameter.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16179
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16141
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16137
- None.
1. Try to crash it and make sure everything is working as before.

Fix(Core/Spells): Delayed Damage system

---

data/sql/updates/pending_db_world/rev_1683046565991365200.sql

- Re-aligns ExclusiveGroups to correct the questline
Exclusive Group was:
The Seat of the Naaru + Time to Visit the Caverns
Now it is:
Time to Visit the Caverns + Call of the Farseer
To get Back to the Orphanage
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16162
- Closes https://github.com/chromiecraft/chromiecraft/issues/5539
- 
1.
2.
3. …

fix(DB/Quest): Correct quest progression in Children's Week Alliance Side

---

data/sql/updates/pending_db_world/rev_1683303351155130800.sql

- Creature 621 is a (bad) duplicate of 620, which is a valid brute forced creature type
- It's also not in the game anywhere, presumably its initial entry was a mistake  
- Closes 
- 
- 
1.
2.
3. …

fix(DB/creature_template): Remove Creature 621

---

data/sql/updates/pending_db_world/fixmechimmunemaskspectperf.sql

adds mechanic immunities to spectral performer that should make it immune to CC
-  change mech mask
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15972
- tests by me. seems to work
- 
1. `.tele gmisland`
2. add a bunch of CC spells to your character (.learn (20989, 37369, 39176))
3. `.npc add 16473` …

fix(DB/Karazhan): Update mech_immune_mask to make Spectral Performers immune to CC

---

src/server/game/Spells/SpellInfo.cpp

- add 35328 to AURA_STATE_FAERIE_FIRE
- Closes https://github.com/chromiecraft/chromiecraft/issues/5231
- tested
.aura 35328
Try to cast a stealth spell, notice you cannot. …

fix(Core/Spells): Apply AURA_STATE_FAERIE_FIRE to Lambent Blood.

---

src/server/game/Entities/Player/Player.cpp

Enforces a -1 duration value to auras applied from equip effects. 
Current reliance on the DurationEntry of the auras causes at least one aura to incorrectly expire.
-  Enforces a -1 duration value to auras applied from equip effects, rather than using the value from spellinfo->DurationEntry
- Closes AzerothCore issue #5649
- Closes https://github.com/chromiecraft/chromiecraft/issues/531
- May close other open or unreported issues
To my knowledge, there exists no concise documentation that proves this behavior was previously Blizzlike, or that the proposed behavior is Blizzlike. Please read my writeup in the comments for the supporting argument for this change.
- Tested item "The Green Tower" is now correctly applying an aura with -1 duration, and not expiring before unequip.
- Regression …

fix(CORE/Player): Apply equip effect auras with -1 duration

---

src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp

- Closes #16112 
- Closes https://github.com/chromiecraft/chromiecraft/issues/5488
- Tested …

fix(script/boss_mechano_lord_capacitus): Avoid Nether Charge despawn

---

data/sql/updates/pending_db_world/DM_FactoryDoor_Fix.sql
src/server/scripts/EasternKingdoms/Deadmines/instance_deadmines.cpp

-  The boss (Rhahk'Zor) activates the door in his room instead of only changing gameobject state
-  The lever behind the door then won't be able to close the door again when players click on it
- Change Instance script
- Closes [10340](https://github.com/azerothcore/azerothcore-wotlk/issues/10340)
In this WoW Classic video you see the door open as soon as the boss is killed:
https://youtu.be/71UPdm30VrI?t=448
Shortly after, the player clicks the door lever and nothing happens:
https://youtu.be/71UPdm30VrI?t=471
This is also the only logic way a group cannot be softlocked in the instance. If the lever would close _and_ open the door, the following could happen:
1) All players go through the door, a player closes the door behind the group.
2) The group progresses through the instance and …

fix(Instance/Script): Fix Factory Door in Deadmines being closable

---

src/server/game/Spells/SpellInfoCorrections.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14988
Necrosis ([Wowhead](https://www.wowhead.com/wotlk/spell=51460/necrosis)) should have the SPELL_ATTR3_IGNORE_CASTER_MODIFIERS flag and works as expected
- Tested as described below
.learn 20375
.learn 31884
Unequip your weapon for low variance in the damage
Use Seal of Command, attack a dummy
Use Avenging Wrath and attack more
With avenging wrath deals ~20% damage more than without …

fix(Core/Spells): Seal of Command, Seal of Vengeance and Seal of Corruption do not benefit from percentage damage increases

---

data/sql/updates/pending_db_world/rev_1683957297429455600.sql

-  Revert https://github.com/azerothcore/azerothcore-wotlk/pull/12792
Player gets a key drop that he cannot loot because he already has one
https://youtu.be/U2OEhkvjZaE?t=163
Numerous comments like that on [wowhead](https://www.wowhead.com/wotlk/item=18250/gordok-shackle-key#comments)
```UPDATE `creature_loot_template` SET `Chance` = 100 WHERE `Entry` = 14321 AND `Item` = 18250;```
.add 18250
.go c id 14321
.damage 1000000
Loot
To revert this test drop chance:
```UPDATE `creature_loot_template` SET `Chance` = 13 WHERE `Entry` = 14321 AND `Item` = 18250;```
https://github.com/azerothcore/azerothcore-wotlk/issues/12786
Being able to roll on already owned unique items possibly is a general bug with group loot
When a PR is ready to be tested, it will be marked as **[WAITING TO …

Revert(conditions): Gordok Shackle Key should not be seen if you already have one.

---

data/sql/updates/pending_db_world/18218.sql

-  NPC Harold Lane is not performing his 'sick/ill' emotes
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5477
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16204
https://wowpedia.fandom.com/wiki/Harold_Lane?so=search
https://github.com/TrinityCore/TrinityCore/issues/24987
- Local
- 
.go cr 65459 …

add(DB\NPC) NPC Harold Lane is not performing his 'sick/ill' emotes

---

apps/startup-scripts/run-engine
apps/startup-scripts/starter

-  Use a different file for each execution to avoid keeping all the crashes in one file.
- None for now.
1. Have a linux server.
2. Use the acore.sh dashboard.
3. Use the advanced restarter from [AC wiki](https://www.azerothcore.org/wiki/how-to-restart-and-debug)
4. On execution, check if the gdb is created inside the folder with the current datetime. Also, if you restart the server it should create a gdb file.

feat(apps/scripts): set a logging file for gdb using starter app

---

data/sql/updates/pending_db_world/rev_1684036819129474700.sql
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

- Adds a new smart action to set creatures invisible and immune to all, effectively disabling them to be re-enabled by scripts later. This allows for a hack of pre-spawns which is a feature that I've argued exists. This just allows us to bypass needless Actionlists and to be able to disable or re-enable several creatures at once with only one row.
- By itself it doesn't do much, as more sophisticated targeting methods would be preferable (targeting all formation members, for example)
- Using this method of pre-spawns is useful due to the large control we have over guid-scripting, especially with the newly added flags_extra. It allows the creation, in DB, of a large amount of creatures that'd otherwise require their spawn positions being handled in a cpp script, such as the Mechanar Bridge …

feat(Core/SAI): Implement SMART_ACTION_DISABLE 

---

data/sql/updates/pending_db_world/rev_1684589406305000945.sql

-  add missing stealth detection to mobs
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16221
- Closes https://github.com/chromiecraft/chromiecraft/issues/5645
- Closes https://github.com/chromiecraft/chromiecraft/issues/5580
- Tested
While stealthed (.aura 1784)
1. .go cr 71514  
1. .tele kara 
2. Walk next to the sentries/valets.
3. Observe they do see you. …

fix(DB/creature) add missing stealth detection to mobs

---

src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Pet/PetDefines.h
src/server/scripts/Pet/pet_hunter.cpp

-  Remove random multipliers for pets that doesn't have a petlevelstats entry.
-  Add a formula to calculate the damage (it's not perfect but for now it works.)
-  Refactor some code.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15910
https://github.com/azerothcore/azerothcore-wotlk/issues/15910#issuecomment-1553915910
With the data provided, I generated a linear regression model for each formula.
Models for Venomous Snake: 
Min damage:
Max damage:
As we can see the models are significant BUT we need to check the residuals to see if they are normal...
As we can see the data for the maximum damage is not quite normal, but we can leave it as it is for now (this would explain some behaviour later)
Model plots (blue line is the model for the min damage, red line is the …

fix(Core/Spells): Hunter snake trap damage

---

data/sql/updates/pending_db_world/fix_run_speed_dabyrie.sql

- change `speed_run` to 1.14286 which is the value of the laborers around her
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16337
- Closes https://github.com/chromiecraft/chromiecraft/issues/5649
- compare speed of laborers in [this](https://www.youtube.com/watch?v=JT5RfaxHaeY&ab_channel=BloodyFoxGaming) video to speed of Kenata 
- tested
- 
1.
2.
3. …

fix(DB/ArathiHighlands): set Kenata Dabyrie's run speed to a more realistic value

---

src/server/game/AI/SmartScripts/SmartScript.cpp

-  If the event_type is 61 (LINK) it previously would not be able to use event_chance. Workarounds are possible but I don't see a reason to not allow this in the core anyways
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/714
- Tested with single Links and Link chains
1.
2.
3. …

fix(Core/SAI): Allow LINK events to use event_chance

---

data/sql/updates/pending_db_world/rev_1685289370798076700.sql
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Creature/enuminfo_CreatureData.cpp

-  Shattered Hand Zealots might be the only case I've seen of this. Where they do not respond at all to any assistance calls whatsoever. Throughout the entire dungeon you can see cases where a workaround was made in order to make creatures not respond to assistance (creature when spawned will run a waypoint instead of aggroing immediately), same for Hellfire Ramparts
- Also changes flags around to be more organized
- With this PR there are no more explicitly unused extra flags, but some are still unimplemented OR need to be removed
- Closes 
- 
1.
2.
3. …

fix(Core/Creature): Re-Add IGNORE_ASSISTANCE_CALL flag

---

src/server/scripts/Commands/cs_send.cpp

-  makes item count optional again
- defaults the count of items sent to 1, as indicated by the help text
- None I could find
- personal experience and testing
- Sent items with and without a count attached to the itemId
1. `.send items CharacterName "Test1" "Test1" 11284`
2. `.send items CharacterName "Test2" "Test2" 11284:5`
3. `.send items CharacterName "Test3" "Test3" 11284:5 23768`
None …

fix (scripts/cs) Fix '.send items' command to no longer require an itemId count

---

data/sql/updates/pending_db_world/fix-kaliri-resist.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16368
- Closes https://github.com/chromiecraft/chromiecraft/issues/5639
The video shows that this resistance that it is rn (see AC issue) just cannot be right. The arcane shot we see [here](https://www.youtube.com/watch?v=8LrraqpLa1M&t=150s) would likely be totally resisted.
checking thanks to @heyitsbench 
- not tested in game
- 
1.
2.
3. …

fix(DB/HellfirePeninsula): remove very strange resistance from Kaliri Swooper, Matriarch and the Hatchlings

---

src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp

-  Exclude tanks and make the cast smarter by checking if any player is immune to the spell.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5129
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16243
- Tested in-game with a druid and a non-immune target as tank.
1. Go to Sethekk Halls and engage King Ikiss
2. Check if it still casts polymorph on tank/polymorph immune targets.

fix(Core/Scripts): Ikiss polymorph target

---

data/sql/updates/pending_db_world/rev_1685492458809465300.sql

-  Add immunity mask for every Rift Lord/Keeper.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16242
- Closes https://github.com/chromiecraft/chromiecraft/issues/5159
Mangos -> tweaked some weird ones.
1. Check every one of them are immunity to interrupts, stuns, etc.

fix(DB/Creature): Immunity mask for Rift Lord/Keeper

---

data/sql/updates/pending_db_world/rev_1685488203205825700.sql
src/server/scripts/Outland/Auchindoun/ManaTombs/boss_pandemonius.cpp

-  Code cleanup. Use BossAI instead of ScriptedAI.
-  Add interrupt immune mask, as it should be immune to interrupts.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5106
1. Go to Mana Tombs and engage Pandemonius.
2. Try to interrupt Void Blast.

fix(Core/Scripts): Rework Pandemonius

---

data/sql/updates/pending_db_world/update-peon-unit-flag.sql
src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp

-  intro now starts on lockpick
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5692
See issue
- tested the immunity part
- the lockpick part has to be thoroughly tested
1.
2.
3. …

fix(Scripts/ShatteredHalls): hack fix to prevent pets from pulling the non-attackable peons in Nethekurse room

---

data/sql/updates/pending_db_world/rev_1685233623001496914.sql

Updates two creatures to have more Blizz-like behaviors
- Lupine Delusion (5097, Shadowfang Keep)
- Illusionary Phantasm (6493, Scarlet Monastery Graveyard)
These creatures have been assigned as AI of "SmartAI" and have SAI actions to despawn immediately when hit.   
Creatures previously would be killed like normal enemies, with the entire health bar needing to be DPS'd through. This change fixes that incorrect behavior.
Personal testing on WotLK Classic live. Both creatures act identically - any damage (AoE or single-target) of any amount will cause them to immediately despawn without a death animation and without rewarding XP.
Worked with @Gultask to refine the SAI and ensure both small damage (taking a % of health away) and massive damage (killed in one hit) properly result in the same …

fix (DB/SAI): Lupine Delusion (5097) and Illusionary Phantasm (6493) properly despawn when hit

---

data/sql/updates/pending_db_world/rev_1685502020986918600.sql
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

-  Modify the SAI_ACTION to accept a timer as param1, this allows us to execute the action after x ms.
-  Modify Mechanar Tinkerer SAI to fix their Nether Explosion cast.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5270
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16237
1. Go to The Mechanar and lower the hp of one Mechanar Tinkerer
2. It should charge and immediately start casting Nether Explosion.
3. After the cast, you should take damage and the creature should die immediately.

fix(Core/SmartScripts): Allow SAI_ACTION_DIE to accept params

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_pyroguard_emberseer.cpp

- Remove EVENT_PLAYER_CHECK which was causing triggering the fight to work only sporadically and does not exist in the WotLK Classic version
- Break out pre-enter-combat phase to better match actual timing
- Pre-enter-combat sequence starts 2s after the adds are engaged (instead of 32s) to better match actual timing
- timing now matches DBM and multiple videos
- disable fire shield hack during pre-enter-combat to keep the fight from resetting
- remove faster add despawn which doesn't appear to be in the WotLK Classic version
- remove adds doing EVENT_ENCAGE every 10-20s, which was unnecessary and caused them to glitch move around the player
- None
Used these two videos as reference:
- https://youtu.be/roNyUYbM0JE?t=507 (Season of Mastery, good to watch timing of emotes and boss actions)
- …

fix(Scripts/UBRS): Update UBRS/Pyroguard Emberseer script to fix issues and increase accuracy

---

data/sql/updates/pending_db_world/rev_1685547548027950300.sql
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Spells/spell_dk.cpp
src/server/scripts/Spells/spell_druid.cpp

-  Convert some spells to SpellScripts
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16403
Druid
1. .learn 33763
2. .add 27886
3. .add 40711
4. Test Lifebloom with the Idols
DK
1. Learn Impurity talent in Unholy
2. Use ability, see the damge increases with more impurity learned …

fix(Scripts/Spells): Convert some Druid spells to SpellScript

---

data/sql/updates/pending_db_world/rev_1685737282291536800.sql

-  make Gargantuan Abyssal unaffected by knockbacks
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5709
https://www.icy-veins.com/tbc-classic/the-arcatraz-dungeon-guide
https://wowwiki-archive.fandom.com/wiki/Gargantuan_Abyssal
https://www.wowhead.com/wotlk/npc=20898/gargantuan-abyssal#comments
there are lenghty discussions how to counter the need to stack and spread for both abilities, which wouldnt be present if the meteor could simply the interrupted / stunned
- 
- 
1. Cast Blastwave/Typhoon near one
2.
3. …

fix (DB/Dungeon) make Gargantuan Abyssal unaffected by knockbacks

---

data/sql/updates/pending_db_world/rev_1686107255114155700.sql

- Modify spawn mask of the Hillsbrad Foothills heroic portal
- Closes https://github.com/chromiecraft/chromiecraft/issues/5720
- 
1.
2.
3. …

fix(DB/Gameobject): Instance portal in Escape from Durnholde Keep not showing

---

src/server/game/Spells/SpellInfoCorrections.cpp

-  Make the spell just hit one target instead of all.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5101
issue
1. Go to The Underbog
2. Engage Ghaz'an with more than 2 players.
3. It shouldn't hit anyone now.

fix(Core/Scripts): Ghaz'an acid spit should hit just one target

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

-  **Fix Spell:** [Net-o-Matic](https://wowgaming.altervista.org/aowow/?spell=13120) related to the Item: [Gnomish Net-o-Matic Projector](https://wowgaming.altervista.org/aowow/?item=10720) in SpellAuraEffects.cpp which caused an immobilizing Double "Aura", which persisted at each login, leaving the Player motionless until it expired.
- **Spell Removed:** [Net-o-Matic 1 (Duplicate)](https://wowgaming.altervista.org/aowow/?spell=13138)
- **Spell:** [Net-o-Matic 2 (The Right one)](https://wowgaming.altervista.org/aowow/?spell=16566)
- Closes:  https://github.com/chromiecraft/chromiecraft/issues/2889
- Closes:  https://github.com/azerothcore/azerothcore-wotlk/issues/16481
- **Video Test:** [Net-o-Matic](https://youtu.be/7LifmioZR3o)
1. …

Fix(Core/Spell): Net-o-Matic

---

src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp

- change timers according to evidence gathered from archive footage
- despawn corpses immediately as well, as well as despawning at evade (because they do persist atm)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16283
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16304
- Closes https://github.com/chromiecraft/chromiecraft/issues/5621
- Closes https://github.com/chromiecraft/chromiecraft/issues/5620
Used the following videos for the timers:
- links to come
- tested by myself. seems to work
- 
1.
2.
3. …

fix(Scripts/Karazhan): Opera Wizard of Oz fight correct start timers for combat as well fixing restart of the event

---

data/sql/updates/pending_db_world/rev_1686176056653005100.sql

-  Flag was missing from Heroic ver
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5731
- 
- 
1.
2.
3. …

fix(DB/Creature): Reanimated Bones pulling too much

---

src/server/scripts/Outland/CoilfangReservoir/underbog/underbog.cpp

-  and modify timer to follow sniffed retail timer range
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5733
Retail sniffs and the spell data
- 
1. With 2 characters, .tele underbog
2. Aggro the first Underbat
3. With both characters stand at opposite sides, one in front of the bat, one behind
4. Stand at different ranges, see if it only hits characters in melee range …

fix(Scripts/Underbog): Lower range check for Tentacle Lash

---

data/sql/updates/pending_db_world/rev_1686083132284151700.sql

-  Lower DamageModifier from 90 to 35.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5708
TC db
- None.

fix(DB/Worldboss): Lower Doom Lord Kazzak's damage

---

src/server/game/Loot/LootMgr.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

- The idea is to add a hook, which is used in a module, to be able to change the condition of the item and to allow all the members of the party to obtain the same item from the quest.
- In other words, if you do a quest, which consists of getting 12 items from an npc, if there are 5 people in the party, they should kill at least 60 npc, as long as the drop is at 100%. Because if the drop is lower, you should kill many more.
- Thanks to this, it is achieved that people do not abandon missions, which involve having to get a lot of items from an npc.
- Closes 
- Windows 10
- In-game
1. This change by itself does not work. It has to be accompanied by a module, which I will create once this code is working. Unless, of course, I have to make changes to it. I have tested it, without the module …

chore(Core/ScriptMgr):Add Hook OnBeforeFillQuestLootItem

---

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp

-  change events updateAI to scheduler
-  
- Closes 
none needed
- basic single player tests by me
- needs testing in group setting to confirm interrupt still works
1. go to magtheridon's lair
2. ???
3. profit …

chore(Scripts/MagtheridonsLair): rework Magtheridon boss script

---

src/server/game/Handlers/MiscHandler.cpp
src/server/game/Server/WorldSession.h

-  In order to translate many of the emulator modules, it is necessary, in this case, to enable the SendAreaTriggerMessage method to accept an integer value as an argument, so that it can be sent from acore_string
- Closes
- Windows 10
- In-game
1. Actually this PR, is related to another one that I have in the mod-individual-xp, where previously, the messages were set inside the same module, but now they are read from the DB. The question is that in order to publish this PR, first I need this to be approved. https://github.com/azerothcore/mod-individual-xp/pull/35 …

chore(Core/MiscHandler): SendAreaTriggerMessage with integer parameter

---

data/sql/updates/pending_db_world/rev_1686519678664565811.sql

-  Fel Embers now can't be shared with horde
- Turning the Tide can only be shared to Alliance
- The Will of the Warchief can only be shared to Horde
- Closes https://github.com/chromiecraft/chromiecraft/issues/5683
- Closes https://github.com/chromiecraft/chromiecraft/issues/5697
https://www.wowhead.com/wotlk/quest=9494/fel-embers
https://www.wowhead.com/tbc/quest=9495/the-will-of-the-warchief
https://www.wowhead.com/tbc/quest=9492/turning-the-tide
- Tested
1. .quest add 9494
2. .quest add 9492
3. Try sharing to Horde character (67 level +)
1. .quest add 9492
2. Try sharing to Alliance character (67 level +) …

fix(DB/Quest) Fix shareable quests

---

data/sql/updates/pending_db_world/rev_1686872651542486500.sql

-  The mission lacks credits upon arrival at the site, so it cannot be completed.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16210
- Closes https://github.com/chromiecraft/chromiecraft/issues/5771
- Closes https://github.com/chromiecraft/chromiecraft/issues/5472
- Closes https://github.com/chromiecraft/chromiecraft/issues/5650
I cannot provide any source. Because there is no sniff.
- Windows 10
- In-game
1. `.quest add 437`
2. `.go c 17611`
3. When you enter the area, it should give you the exploration credits and then, when you kill the npc, the mission is completed. …

fix(DB/Smart Scripts) Quest 437: The Dead Fields

---

data/sql/updates/pending_db_world/rev_1684908860029011348.sql

-  adds a SAI entry to cause Antu'sul (8127) to despawn his own summoned adds (8156) when reset
- summoned creatures created by Antu'sul's SAI during a first attempt are not despawned for subsequent attempts
- personal experience
- Engaged boss and reset to observe one or more adds being despawned
1. `.list creature 8127`
2. `.go creature <entry from above>`
3. target self and `.die`
4. observe that Antu'sul despawns the add he created upon returning to his spawn point …

fix(DB/SAI) Zul'Farrak: make Antu'sul (8127) despawn his summoned adds (8156) when reset

---

data/sql/updates/pending_db_world/rev_1686948961677753100.sql
data/sql/updates/pending_db_world/rev_1686949481728636000.sql

-  increase level from 67 to 71
-  
- Closes 
Only level 71 mages here
https://youtu.be/2XP5SsApWeU
range from 67 (normal) to 71 (heroic)
https://www.wowhead.com/wotlk/npc=18934/durnholde-mage
All other mobs are 71
- 
Do OHF until you free thrall …

fix (DB/Creature) set level of Durnholde Mage in OHF heroic appropriate for heroic

---

data/sql/updates/pending_db_world/rev_1687016239956745200.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/5634
Linked issue …

fix(DB/creature_template): Make "Ambient Minion of Terokk" not selectable

---

src/server/game/Entities/Player/PlayerUpdates.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Add hooks that allow for modification of skill gain when gathering and crafting based on player, skill level, color etc.
- None
- Linux x64
- In-game
1. By itself, this change should not affect gameplay. To test the change, create a module with a PlayerScript, changing the values of `gain` variables.
2. Without the module, the behavior is unchanged. Crafting any item gives the amount of points as configured.
3. With the module, the skill gain can be adjusted to add any amount of points, based on level. …

chore(Core/ScriptMgr): Add Hooks for profession skill gains

---

data/sql/updates/pending_db_world/rev_1687388954869141000.sql
src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp

-  Remove not-working AuraScript.
- Partially closes https://github.com/chromiecraft/chromiecraft/issues/5797
1. Go to Shadow Labyrinth and engage Murmur.
2. Wait for it to cast Murmur's Touch, stay close to the target of it.
3. It should knockback and silence the player and all the players within 20yds (also dmg)

fix(Core/ShadowLabyrinth): Murmur's Touch

---

data/sql/updates/pending_db_world/dustbelchernpcfix
data/sql/updates/pending_db_world/dustbelchernpcfix.sql

- Modified the MovementType values for three Dustbelcher NPCs to resolve WaypointMovementGenerator::LoadPath: creature doesn't have waypoint path id error.
- Specifically, the errors generated in the worldserver console were:  `WaypointMovementGenerator::LoadPath: creature Dustbelcher Mauler (GUID Full: 0xf130000a9d0016b4 Type: Creature Entry: 2717  Low: 5812) doesn't have waypoint path id: 0 WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c0016b7 Type: Creature Entry: 2716  Low: 5815) doesn't have waypoint path id: 0 WaypointMovementGenerator::LoadPath: creature Dustbelcher Shaman (GUID Full: 0xf130000a9e0016b8 Type: Creature Entry: 2718  Low: 5816) doesn't have waypoint path id: 0 WaypointMovementGenerator::LoadPath: creature Dustbelcher …

fix(DB/Creature): Dustbelcher NPC MovementType

---

data/sql/updates/pending_db_world/rev_1686957483376943500.sql

- TBC Epic goggles obtained from trainers were all over the place, some only having one trainer, WoWhead lists them all as part of a reference containing 14 trainers, all of which use reference 201013
- Closes 
WoWhead Wotlk Classic
```
SELECT * FROM `npc_trainer` WHERE `SpellID` IN (-201013)
```
- Also tested ingame
1.
2.
3. …

fix(DB/Trainer): Add TBC Goggles and Frost Grenades to proper reference

---

src/server/game/Scripting/ScriptDefines/PlayerScript.cpp

-  Update parameter order to match naming in docs
- No issue created, noticed while using
The function is specified as follows:
```c++
OnUpdateGatheringSkill(Player* /*player*/, uint32 /*skill_id*/, uint32 /*current*/, uint32 /*gray*/, uint32 /*green*/, uint32 /*yellow*/, uint32& /*gain*/)
```
However the use site used:
```c++
script->OnUpdateGatheringSkill(player, skillId, gray, green, yellow, currentLevel, gain);
```
Instead of:
```c++
script->OnUpdateGatheringSkill(player, skillId, currentLevel, gray, green, yellow, gain);
```
Created a module as following:
```c++
class CraftingGainScript : public PlayerScript {
public:
CraftingGainScript() : PlayerScript("CraftingGainScript_PlayerScript") {
}
void
OnUpdateGatheringSkill(Player *player, uint32 skill, uint32 skill_level, uint32 gray, …
```

fix: correct the parameter order

---

data/sql/updates/pending_db_world/rev_1686618584904041200.sql

-  Previously ungrouped
-  Changes the SAI to only despawn when out-of-combat. Also takes timers and Phase In spell from Mangos
- Closes https://github.com/chromiecraft/chromiecraft/issues/5779
- 
- 
1.
2.
3. …

fix(DB/Creature): Rework Avatar of the Martyred

---

src/server/game/Entities/Player/KillRewarder.cpp
src/server/game/Entities/Player/KillRewarder.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h

-  Remove reputation rate modifier for being partied
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16646
- Closes https://github.com/chromiecraft/chromiecraft/issues/5848
https://youtu.be/RjlygZkYcS8?t=81
Gets the full 20 reputation per kill
- 
get 2 characters
party up
.go c id 2206 …

fix (Core/Reputation) remove reputation splitting for being partied

---

data/sql/updates/pending_db_world/gnarlpine-mystic-wrath.sql

-  change spell from 5177 to 9739
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16678
- Closes https://github.com/chromiecraft/chromiecraft/issues/5682
Classic sniffs (see AC issue)
- Tested in-game. Damage seems accurate
- 
1. Find Gnarlpine mystics.
2. See correct damage and hopefully other things mentioned in original issue
3.
None I know off (maybe timers?) …

fix(DB/Teldrassil): Gnarlpine Mystic uses the right 'Wrath'

---

data/sql/updates/pending_db_world/rev_1688085865524921702.sql

-  Change event type to VICTIM_CASTING
- Closes https://github.com/chromiecraft/chromiecraft/issues/5513
-  Works
1. .npc add 18639
2. spam abilities …

fix(DB/SAI) Cabal Spellbinder adjustment to Spell Shock

---

data/sql/updates/pending_db_world/rev_1688730531283365116.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16685
https://www.wowhead.com/wotlk/quest=9145/help-ranger-valanna + grammar
-  Tested, works
1. Horde char
2. .npc add 9145
3. .go xyz 7932.62 -7573.54 145.5 530
**For …

chore(DB/Quest): Fix typo in quest reward offer text for ID 9145

---

src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h

Not used in the core.
To be used by modules.

feat(Core/Object): Add helper to allow removing allowed looters

---

src/server/scripts/Outland/zone_hellfire_peninsula.cpp

-  Make NPC passive while in the cage and aggressive when escorted
- Fix cage (open/close) state
- Closes https://github.com/chromiecraft/chromiecraft/issues/5727
- Closes #16543 …

fix(scripts/zone_hellfire_peninsula): Improve Wounded Blood Elf Pilgrim

---

data/sql/updates/pending_db_world/rev_1689021460555110200.sql

-  Remove Root, Stun and Sapped MIM
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16119
- Closes https://github.com/chromiecraft/chromiecraft/issues/5349
- Not tested.
1. Engage channelers and wait until they summon a Burning Abyssal.
2. Try to root/stun/banish it.

fix(DB/Creature): Burning Abyssal immune mask

---

data/sql/updates/pending_db_world/rev_1689020767712933600.sql
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/magtheridons_lair.h

-  Move scripts to newer system.
-  Remove spell_linked_spell for 30658 and add its own script. Based on CMangos work.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16120
1. Go to Magtheridon's Lair and do a .cast 30657, you usually will get knockback randomly.

fix(Core/Magtheridon): fix Magtheridon's Quake spell

---

data/sql/updates/pending_db_world/rev_1689094675369155000.sql

-  Change Blast Wave from 33061 (used by Krosh Firehand) to 17145.
-  Change comments on SAI (that's why I didn't use an UPDATE statement)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16736
- Closes https://github.com/chromiecraft/chromiecraft/issues/5911
https://www.wowhead.com/wotlk/spell=17145/blast-wave
- Not tested.
1. Do the quest and engage the mob.
2. Wait until it casts Blast Wave, it shouldn't hit for 7k anymore.

fix(DB/SAI): Fingrom Blast Wave

---

data/sql/updates/pending_db_world/fumper.sql

-  checks ooc time instead
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16458
- closes https://github.com/chromiecraft/chromiecraft/issues/5514
- tested
1. see linked issues …

fix(DB/SmartScript): Fix Sand Sifter and Hai'shulud despawning after 1 minute

---

data/sql/updates/pending_db_world/bladeofwizardry.sql

-  add icd
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16747
- not tested
.add 31336
Cast spells …

fix(DB/spell_proc_event): Add Blade of Wizardry ICD

---

src/server/game/Entities/Player/Player.cpp

-  don't dismiss warlock pets on logout
- Closes 
comment states that whoever added that was unsure
there are models in the character screen for all warlock pets
- 
1. summon pet
2. logout
3. …

fix (Core/Player) don't dismiss warlock pets on logout

---

data/sql/updates/pending_db_world/deathfrost.sql

-  add deathfrost icd
- partially adresses https://github.com/azerothcore/azerothcore-wotlk/issues/16233 
- tested …

fix(DB/Spell_proc_event): Add Deathfrost ICD

---

src/server/game/Spells/SpellEffects.cpp

- Reduce the amount of code by merging together some checks or removing duplicate code while keeping the very same logic.
- Closes none. Just made less code.
None.
- Made a warrior, `.learn 100`, used it.
- This creature still charges. `.go c 60102`
1. Fun...? …

Chore(Scripts/spells): Reduce the amount of player checks

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

- make them attack people
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16782
- Closes https://github.com/chromiecraft/chromiecraft/issues/4251
See issue
- tested with 1 char
- needs group testing to see if mind flay still works as intended
1. `.list creature <cthuneyeid>`
2. `.go creature <guid>`
3. engage
None I know of rn …

fix(Scripts/TempleOfAhnQiraj): let small Eye Tentacles attack the raid

---

data/sql/updates/pending_db_world/rev_1689638798154554100.sql

-  Remove skinning loot from several mobs in Tauren starting area
- Originally reported by Grimfeather: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/146
Starting zone mobs should not be skinnable, existing skinning loot template was obviously incorrect (blue whelp scales, etc.), and WoWhead entries for these creatures do not indicate any possible skinning loot.
- SQL runs, creatures no longer skinnable
1. .go cr id 2966
2. Confirm no longer skinnable …

fix(Creature): Incorrect Skinning Loot in Red Mesa

---

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp

-  uses the angle it faces when casting the last eye beam now instead of random player
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4442
Videos in linked issue
- tested, should work
- not extenstively tested with multiple characters. but it does seem to work with the little testing I did
1. go to c'thun
2. wait for dark glare
3. preferably with multiple characters …

fix(Scripts/TempleOfAhnQiraj): make C'thun Dark Glare face location of last eyebeam before cast, instead of random target

---

data/sql/updates/pending_db_world/command_typo_fix.sql

`s/$slected_waypoint/$selected_waypoint`
-  Fix a typo in a command description/example.
- N/A
- It builds.
- It changes a string.
1. Run the .wp show command, and observe that the help text no longer contains a typo. …

Fix typo in `wp show` command description.

---

data/sql/updates/pending_db_world/trinkets.sql

Memento of Tyrande - Set ICD from 60s to 50s
Memento of Tyrande - Make it only proc on spellcast
Fathom-Brooch of the Tidewalker - Set ICD from 45s to 40s
Hourglass of the Unraveller - Set ICD from 45s to 50s
Hand of Justice - Set ICD from 0s to 2s
Eye of Gruul - removed wrong cooldown from template
WOTLK Wowhead + comments
- tested …

fix(DB/Spell) Fix trinkets procs TBC and Vanilla

---

data/sql/updates/pending_db_world/talismanofascendance.sql

-   added flag
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11881
- closes https://github.com/chromiecraft/chromiecraft/issues/3545
- tested …

fix(DB/Spell): Talisman of Ascendance should only proc on spell casts

---

data/sql/updates/pending_db_world/darkmoonbluedragon.sql

-  only proc on spellcast
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11026
- Closes https://github.com/chromiecraft/chromiecraft/issues/3004
Neifion testing (see issue attached)
- tested but I would like someone else to check too
1. equip blue dragon
2. cast spells and see if no difference between aoe heal and st heal (like holy nova)
3. …

fix(DB/Spell): Darkmoon Card: Blue Dragon should only trigger on spellcast

---

src/server/game/Server/WorldSession.cpp

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5951
- 
1. Summon Voidwalker/Succubus/Felhunter
2. Logout
3. …

fix(Core/Session) don't refund soul shards when logging out with warlock pets

---

data/sql/updates/pending_db_world/rampartshcbadge.sql

-  adds badge of justice to hc ramparts chest
- Closes https://github.com/chromiecraft/chromiecraft/issues/5558
- tested both normal and hc (normal has different chest id)
1. see linked issue …

fix(DB/Loot): HC ramparts chest should drop a badge of justice

---

data/sql/updates/pending_db_world/wotlktrinkets.sql

Charred Twilight Scale - Removed unused PPM rate and set ICD of 50s.
Soul Preserver - Removed incorrect and unused cooldown
Dislodged Foreign Object - Removed unused PPM rate
Deathbringer's Will - Set correct proc chance
Tiny Abomination in a Jar - Set proc rate to 45%, down from 50%
Dislodged Foreign Object (normal) - Removed unused PPM rate, set correct ICD of 45s
Purified Lunar Dust - Set ICD to 50s, up from 45s
Reign of the Dead (Heroic) - removed incorrect cooldown from item template
Reign of the Dead (Normal) - removed incorrect cooldown from item template
Show of Faith - Set ICD to 50s, up from 45s
The General's Heart - removed incorrect cooldowns and unused  from item template, set correct ICD of 50s
Blood of the Old God - removed incorrect and unused  cooldowns from the item …

fix(DB/Spell) Fix WOTLK trinket procs

---

data/sql/updates/pending_db_world/heroism.sql

-  set flag
- Closes no issues
https://wowwiki-archive.fandom.com/wiki/Darkmoon_Card:_Heroism
- tested …

fix(DB/Spell): Darkmoon Card: Heroism should only trigger on melee autoattacks

---

data/sql/updates/pending_db_world/shatteredchampion.sql

-  Removes threat drop from shattered hand champion
- Closes https://github.com/chromiecraft/chromiecraft/issues/5962
https://youtu.be/C4uGJ6QWNpk?t=3728
- tested …

fix(DB/Smartscript): Shattered Hand Champion should not threat drop

---

data/sql/updates/pending_db_world/add_teleport_to_brs_are_trigger.sql

-  Area trigger entry 2068 is missing from  areatrigger_teleport
-  Jumping in the crater in BRS should teleport to Blackrock Mountain
- Current behavior:
https://github.com/azerothcore/azerothcore-wotlk/assets/19265585/6374cf93-62da-490f-b2ea-cfbe33081fd0
- Closes 
Mangos
- 
- 
1. go trigger 2068
2.
3. …

fix(DB/BlackrockSpire): Add teleport trigger for crater

---

data/sql/updates/pending_db_world/rev_1690478105252488100.sql

-  Remove movement from High Executor Darthalia
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16705
- NPC no longer moves
1. .go xyz -36.3284 -927.111572 54.467083
- I did not confirm with Classic that this is correct behavior for the NPC, but the linked video seems correct. Someone could check if they would like to be more confident this is correct behavior. …

fix(Creature): High Executor Darthalia movement

---

data/sql/updates/pending_db_world/shattered-rumbler-timers.sql

Thanks alot to [Bench](https://github.com/heyitsbench) for the sniffs that helped me fix this
-  change timers to be similar to those on retail
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16816
https://github.com/elthehablo/GeneralACResearch/blob/main/shattered-rumbler-research.md
- not tested
- 
Fight the mobs at the southern parts of Nagrand and see that they don't immediately start casting their signature ability anymore
None …

fix(DB/Nagrand): improve timers from Shattered Rumblers using sniffs

---

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp

Co-authored-by: Balleny <balleny@users.noreply.github.com>
-  Move the boolean flag out the last schedule.
-  Credits to balleny, practically solved it on the issue.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5975
- Not tested.
1. Go to Magtheridon, kil 4 channelers and leave 1 alive, then wait until Mag free himself.
2. Kill the last channeler.
3. Shouldn't be double scheduled abilities anymore.

fix(Core/Magtheridon): Fix double schedule

---

data/sql/updates/pending_db_world/rev_1690624654192328000.sql
src/server/scripts/Spells/spell_generic.cpp

- Script the spell  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16692
- Closes https://github.com/chromiecraft/chromiecraft/issues/5889
- tested
.aura 38048
Drop below 50% hp -> Buff should be removed on the next tick. …

fix(Core/Spells): Curse of Pain

---

src/server/scripts/Kalimdor/boss_azuregos.cpp

-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5860
- 
- 
1.
2.
3. …

fix(Scripts/Azuregos): Arcane Vacuum should also reset pet threat

---

src/server/scripts/World/npcs_special.cpp

- Fixes the script to use the xp toggle cost config option properly.
- Previously this config variable did not work, as the cost defined in the db would override this config option.
- It builds, logic should be fine. Feel free to test ingame.
- Set the config option to something else than 10g, it should now reflect properly ingame. …

Fix XP disable NPC script

---

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp

-  Kiggler no longer chases after target
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15865
- Closes https://github.com/chromiecraft/chromiecraft/issues/5343
- Works, same as Krosh and Olm
1. .tele gruul
2. kill all but kiggler …

fix(Scripts/Gruuls) Kiggler no longer chases after target

---

src/server/game/Entities/Pet/Pet.cpp

Original script was only applying the config option `CONFIG_ALLOWS_RANK_MOD_FOR_PET_HEALTH` (Pet.RankMod.Health)
to pets who did *not* have a DB entry. It was part of the else statement.
This PR creates a new if statement above the else statement where the scaling value will be applied appropriately if this bool is true.
-  Apply this change to core core to allow all pets to be scaled appropriately to config options if they have a DB entry and also without a DB entry.
- Further improves https://github.com/azerothcore/azerothcore-wotlk/issues/11480
- After testing noticed that pets without a DB entry would not scale regardless of the config option `Pet.RankMod.Health` being set to true or false.
- Rebuilt without errors. 
- Tested locally on entity 8996 (Voidwalker Minion)
- Tested locally …

fix(Core/Pets) Pet scaling only being applied to pets with DB Entry

---

src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/instance_old_hillsbrad.cpp

Fix escort event possibly getting stuck by preventing DATA_ESCORT_PROGRESS from being decreased
When all players leave the instance (e.g. corpse walk after wipe) and the first player re-entered the old hillsbrad, CleanupInstance() is called
CleanupInstance() schedules EVENT_FINAL_BARRELS_FLAME which unconditionally sets DATA_ESCORT_PROGRESS, possibly rolling back the instance progress and removing the gossip option from Thrall
Trivia: The way it was previously handled, you could unstuck the instance by leaving _twice_ and re-entering. After the second CleanupInstance() Lieutenant Drake would respawn and could be killed again (exploit alert!).
This would set the escort progress to the correct value again and Thrall's gossip option would reappear. This explains the second comment on the …

fix(Scripts/EscapeFromDurnholde): Fix escort mission getting stuck

---

src/server/game/Entities/Pet/Pet.cpp

##Changes Proposed:
-  Check if the scale of the display information is greater than 1 and the pet is marked as exotic
-  Exotic pets have a fixed scale of 1
- Otherwise multiply the calculated scaling with the scaling from the display information
- Return the calculated scaling
- Fallback value if conditions are not met or pet is not valid
- Closes #16441 
- Closes #15900 
- https://www.wowhead.com/wotlk/npc=6498/devilsaur
- https://www.wowhead.com/wotlk/npc=38453/arcturis
- https://www.wowhead.com/wotlk/npc=32517/loquenahak
- 
- 
1. `.learn 1515` `.learn 883` `.learn 2641` `.learn 53270` (Beast Mastery) 
2. `.learn 62757` `.modify money 1000g` (Add some Gold for buy stable slot)
3. `.character level 80`
4. `.cheat god` `.go creature id  32517` (Loque'nahak)
5. Tame the Beast & see the …

fix(Core/Pets): Corret Pet size for normal and exotics & bigger pets

---

data/sql/updates/pending_db_world/etherealdarkcaster.sql

-  add pickpocket loot from normal mob to heroic mob
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5959
wowhead... using same loot table as normal mob
-  tested …

fix(DB/Creature): Ethereal Darkcaster (H) should be pickpocketable

---

apps/ci/ci-pending.sh

- This fixes an issue in the `ci-pending.sh` script, which performs a few checks on incoming SQL changes.
- If there was a "--" that was supposed to be in a string, the `sed` command would see it as a comment.
- This PR updates the `sed` command used to remove strings (which may contain "--") and replace them with an empty string
- Addresses issue experienced in review of PR https://github.com/azerothcore/azerothcore-wotlk/pull/16850
- Tested on the file that was having issues in the PR
- Download file that was throwing errors 
- `cd data/sql/updates/pending_db_world`
- `curl -O curl -O https://raw.githubusercontent.com/azerothcore/azerothcore-wotlk/f258a496a47fbe5d778fe1457b1ffcabe6444889/data/sql/updates/pending_db_world/reaching.sql`
- `cd - # get back to where you started`
- Test the …

chore(CI): fix `ci-pending.sh` script for linting SQL

---

data/sql/updates/pending_db_world/hellfirechanneler.sql

-  add silence and freeze immune mask
- Closes https://github.com/chromiecraft/chromiecraft/issues/5994
- cmangos, wowhead …

fix(DB/Creature): Hellfire Channeler should be immune to silence

---

data/sql/updates/pending_db_world/karadragon.sql

-  adds mechanic immune flag for interrupt
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16918
Nobody interrupts them on any video. …

fix(DB/Creature): Netherspite, Nightbane should be immune to interrupt

---

data/sql/updates/pending_db_world/arcaneanomaly.sql

-  removes arcane immunity flag (it got high arcane resistance)
-  now it will cast his own mana shield
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16917
cmangos wotlk
- tested …

fix(DB/Creature): Arcane Anomaly should not be immune to arcane

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

-  castFlag 128 for SMART_ACTION_CAST will make it so the spell is only cast if there's more than one item in the threatlist.
-  Examples in retail include the mind control spells of Skeram and Hakkar
- Closes 
- Tested Ingame
- 
1.
2.
3. …

feat(Core/SmartAI): Implement castFlag THREATLIST_NOT_SINGLE

---

data/sql/updates/pending_db_world/hellfirewarder.sql

-  only cast if target has no aura from spell flag
- Closes https://github.com/chromiecraft/chromiecraft/issues/6012
- tested …

fix(DB/SAI): Hellfire Warder should not overlap rain of fire

---

data/sql/updates/pending_db_world/the-crone-interrupt.sql

-  add MECH_DISARM and MECH_INTERRUPT to immune mask
-  
CMaNGOS
- not tested
- 
1. go to opera as gm, start Oz event
2.
3.
probably, but too much to mention here …

fix(DB/Creature): make sure The Crone can no longer be disarmed or interrupted

---

src/server/game/Entities/Pet/Pet.cpp

* Fix pet scaling to properly take DBC data
* Restore old removed base scale for guardians
* Edge case for Devilsaur where the DBC data is whack, therefore we use Spirit Beast data instead. Yes I know, hackfix, but I cant for the life of me find any other scaling in dbc that would fix this issue
* updated scale calculation based on client function (https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/f09564b9d01ff372506f76f2345b99e3485738d5)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6017
- 
1. Check scaling for pets
2. Check scaling for devilsaur …

fix(Core/Pets): Hunter pet scaling

---

data/sql/updates/pending_db_world/kolkarresistance.sql

-  removes resistances
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16971
- closes https://github.com/chromiecraft/chromiecraft/issues/6023
- @heyitsbench 
-  …

fix(DB/Creature): Desolace Kolkar have no resistances.

---

data/sql/updates/pending_db_world/infectedwildkinfix.sql

Creature uses Infected Wound.
Infected Wildkin uses Infected Wound on target.
[Video](https://www.youtube.com/watch?v=nAx98HkQUqw&feature=youtu.be&ab_channel=Roddan)
Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16897
Retail & Youtube & Sniff.
Teleport to Bloodmyst Isle and attack it.
1. Teleport to Bloodmyst Isle or Spawn the NPC.
None so far.

fix(DB/Creature): Infected Wildkin uses Infected Wound

---

data/sql/updates/pending_db_world/change-pyroguard-rep-onkill.sql

-  change rep from 50 to 20
-  
Most Credible source 2023 (Bench):
- not tested
- 
1. kill pyroguard
2.
3.
none afaik …

fix(DB/UBRS): change rep on kill for Pyroguard Emberseer from 50 to 20

---

apps/docker/Dockerfile

-  adduser and addgroup commands in Dockerfile have `acore` hardcoded
- No issue found, but this was discussed in discord 
- I haven't performed any tests
1. Run command that should fail in previous setup
```bash
$ docker compose --profile app build --build-arg DOCKER_USER=foobar
```
- I need to test this change. I can't because I'm working right now.  …

Fix adduser/addgroup commands in dockerfile

---

src/common/Configuration/Config.cpp
src/common/Configuration/Config.h
src/server/apps/authserver/Main.cpp
src/server/apps/worldserver/Main.cpp
src/test/common/Configuration/Config.cpp

Implement overriding of configuration from the .conf file with environment variables. Environment variables keys are autogenerated based on the keys defined in .conf file.
Usage example:
```
$ export AC_DATA_DIR=/usr
$ AC_WORLD_SERVER_PORT=8080 ./worldserver
```
On windows:
```
> $env:AC_REALM_ID = '2'; .\worldserver
```
- Closes 
- Run the server with an overridden config.  …

feat(Core/Config): Implement config override with env vars

---

src/tools/dbimport/Main.cpp

- Fixes DBImport to allow it to pull configuration from the environment
- https://github.com/azerothcore/azerothcore-wotlk/pull/16817 was merged but it only added env var support for the authserver and worldserver
- This PR extends this functionality to the dbimport tool
- primarily, this is useful for docker
- env var configs (partially) nullify https://github.com/azerothcore/azerothcore-wotlk/pull/16806, which I opened up in order to simplify the few config changes that docker needs
- No issues exist for this.
- Setting up docker with env vars is (slightly) pointless at the moment, …

fix(Tools/dbimport): Add Env var support to DBimport tool

---

data/sql/updates/pending_db_world/rev_1689813586760998100.sql
src/server/scripts/Spells/spell_quest.cpp

-  added the book and used only in Varedis
-  added remove metamorphosis
https://www.youtube.com/watch?v=D0GecU9-gUE (58:25 minutos de vídeo)
1.  .quest add 10651 (Altar of Sha'tar)
2.  .quest add 10692 (Sanctum of the Stars)
**For …

fix(Scripts/Quest): Improved Varedis Must Be Stopped

---

data/sql/updates/pending_db_world/rev_1688557801143854400.sql

-  add spell 57403 (flight) to Njorndar Proto-Drake vehicle
-  adjust Njorndar Proto-Drake display status on the ground
-  fix Quest "Vile Like Fire" vehicle unable to fly
Vile Like Fire! https://www.wowhead.com/wotlk/quest=13071/vile-like-fire
spell 57403 https://www.wowhead.com/wotlk/spell=57403/flight
- It builds without errors
- Server:
AzerothCore rev. 893a9beeacc4+
Debian 11 x64
MySQL 8.0.33
- Client:
3.3.5a.12340 enUS
Windows 10 x64 LTSC
- .go xyz 7872.494 3695.697 653.3371 571
- observe the Njorndar Proto-Drake on the ground
- .q a 13071
- right click the Proto-Drake
- press space try flying
- fly to the "Vrykul buildings" press 4 use "Strafe Jotunheim Building"

fix(DB/Creature): Njorndar Proto-Drake vehicle unable to fly in “Vile Like Fire”

---

src/server/scripts/Northrend/zone_dragonblight.cpp

So, the crash occurs within this function:
https://github.com/azerothcore/azerothcore-wotlk/blob/57e0b496bdc13441870f36963020271b6ae3f4fa/src/server/game/Entities/Unit/Unit.cpp#L20014-L20039
The reason for this issue is that the `m_vehicle` object gets deleted after the line mentioned below:
https://github.com/azerothcore/azerothcore-wotlk/blob/57e0b496bdc13441870f36963020271b6ae3f4fa/src/server/game/Entities/Unit/Unit.cpp#L20019
This deletion occurs in the subsequent chain of calls:
[m_vehicle->RemovePassenger(this);](https://github.com/azerothcore/azerothcore-wotlk/blob/57e0b496bdc13441870f36963020271b6ae3f4fa …

fix(Crash): Fix crash on ExitVehicle from Wintergarde Gryphon.

---

src/server/scripts/Kalimdor/zone_orgrimmar.cpp

-  Replace hardcoded gossips for db references.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4179
- Gone through gossip with 6566 quest as male and female character.
- Checked if gossips are not available without 6566 quest.
1. `.go xyz 1920 -4125 43`
2. `.quest add 6566`
3. go through gossips
Gossips looks like: (adashiel comment)
https://www.wowhead.com/wotlk/quest=6566/what-the-wind-carries …

fix(CORE/Creature): replace hardcoded gossips in zone_orgrimmar

---

src/common/Collision/Maps/MapTree.cpp
src/server/game/Spells/Spell.cpp

- Using Blink while falling at a high height will no longer warp the player by 1y upward.
- Added a logic that prevents the player from moving backward by using `Blink`.
- Closes nothing, I've discovered it while failing to correct something else in Blink.
- 
- 
Learn Blink: `.learn 1953`
Use Blink without having to wait for the mana or the cooldowns.
`.cheat cooldown`
`.mod mana 239432432`
Make a `.gps` macro so you may see your Z coordinate while testing the falling from a high altitude.
- …

fix(core/spell): Stop `Blink` from the falling player to move upward by 1y and stop moving backward when facing a wall

---

apps/compiler/includes/functions.sh

-  [x] `acore.sh` script
This pr restores the functionality during the `./acore.sh docker build` that ensures the appropriate `.conf` files exist. 
- https://github.com/azerothcore/azerothcore-wotlk/issues/17063
- ad-hoc support in Discord
- I'm pretty sure this fixes CI failure in https://github.com/azerothcore/acore-docker/pull/27
1. Remove current conf files (or rename them, whatever works), `rm env/dist/etc/*.conf`
3. Run a build, `./acore.sh docker build`
4. Start the containers, everything should come up fine, `./acore.sh docker start:app`
- it might make sense to remove the volume mount to `etc`, and push people to just use env vars for config; it's easier to debug config issues if there's less places to look, and env vars in the …

fix(docker): ensure conf files always exist

---

src/server/game/Spells/SpellInfoCorrections.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17002 …

fix(Spell) set torment of the worgen to have 3% proc chance

---

data/sql/updates/pending_db_world/rev_1692366711663255300.sql

I set the condition that the Sub-Quests:
- [Flexing for Nougat](https://www.wowhead.com/quest=8356/flexing-for-nougat#comments:id=2774071)
- [Incoming Gumdrop](https://www.wowhead.com/quest=8355/incoming-gumdrop)
- [Chicken Clucking for a Mint](https://www.wowhead.com/quest=8353/chicken-clucking-for-a-mint)
- [Dancing for Marzipan](https://www.wowhead.com/quest=8357/dancing-for-marzipan)
They must disappear as soon as Quest **(Main)** - [Hallow's End Treats for Jesper!](https://www.wowhead.com/quest=8311/hallows-end-treats-for-jesper) is completed.
- Closes …

Fix(DB): Quest-ID: 8353-8355-8356-8357-8311-Conditions

---

src/server/game/Entities/Player/PlayerStorage.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17084
- closes https://github.com/chromiecraft/chromiecraft/issues/6070
1.
2.
3. …

fix(Core/Player): Allow to swap bags when they are filled

---

data/sql/updates/pending_db_world/rev_1693858384423226200.sql

Co-Authored-By: neifion-00000000 <91289495+neifion-00000000@users.noreply.github.com>
Object spawns in sniffs appear as either CreateObject1 or CreateObject2.
CreateObject1 appears based on visibility. For example, a pathing creature in the middle of its patrol will spawn as CreateObject1.
On the other hand, a creature that died and **respawns** appears as CreateObject2, revealing its **real** spawn point. Similarly, summons and event spawns as well as "pre-spawns" appear as CO2
This column is similar to VerifiedBuild. The reason we need it for the creature table is because they are more nuanced and VerifiedBuild is less powerful then.
A creature with no VerifiedBuild will be either unknown source or custom
A creature with VerifiedBuild and CreateObject1 will be good but imperfect
A …

feat(DB/Creature): Add CreateObject column in the creature table

---

data/sql/updates/pending_db_world/verify-your-builds.sql

- Closes the issue mentioned [here](https://github.com/azerothcore/azerothcore-wotlk/issues/17176#issuecomment-1704349834). No one else was gonna do it.
This PR: …

chore(DB/Creature): Correct VerifiedBuild for unverified chess piece spells.

---

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16973
not needed -> logical
untested so far …

fix(Scripts/Karazhan): remove redundant spellcasting check on Netherspite to ensure he moves back to phase 1

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp

-  add boolean check in OnGossipHello script to see whether the player gossiping has a current active pet
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5986
see issue above
- tested on a warlock with a felhunter, should work for hunter and DK too
- 
see steps in issue
none I know of …

fix(Scripts/BWL): Orb of Domination can no longer be used when you are controlling a pet

---

data/sql/updates/pending_db_world/remove-aura-from-kerlonian.sql
src/server/scripts/Kalimdor/zone_darkshore.cpp

removes permanent aura because this is a spell and not an aura. it has to be cast on reset. as it is already using a script for the quest following, I put it in the reset there
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13593
- Closes https://github.com/chromiecraft/chromiecraft/issues/4329
[this](https://www.youtube.com/watch?v=V_sXobA90f0&ab_channel=Bue) shows that the …

fix(Scripts/Darkshore): ensure Kerlonian Evershade is always in bear form

---

data/sql/updates/pending_db_world/rev_1694861198470600600.sql
src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp

Stop evocation on enrage
Remove Mana Regen
Make Hateful Bolt target the 2nd highest in threat
- Closes 
https://youtu.be/1e_PSVv6a30?t=366
https://www.wowhead.com/tbc/guide/curator-karazhan-strategy-burning-crusade-classic
> which is perfect because the main tank and the off tank should be first and second on threat anyway. The reason being, The Curator will target the second person on threat with Hateful Bolt, which should be the off tank at all times.
1. .go c id 15691
2. Observe mana regen not happening
3. Wait for evocation and bring below 15% hp …

fix (Scripts/Karazhan) Curator fixes

---

src/server/game/Globals/ObjectMgr.cpp

-  Code block is bypassed if enforceDBCAttributes is false reducing unnecessary logging and checks
- 
- DBC.EnforceItemAttributes = 1 produces logging errors verifying enforcement
- DBC.EnforceItemAttributes = 0 produces no errors therefore db overrides is successful
1. Change item types in db and modify  DBC.EnforceItemAttribute
2.
3. …

enforceDBCAttributes set to false bypass code block

---

data/sql/updates/pending_db_world/rev_1688549401806530816.sql

-  Remove NPC 245648 (is duplicated and standing on the bonfire)
-  Remove NPC 245645 (is duplicated and standing on the bonfire)
-  Remove NPC 245649 (is duplicated and standing on the bonfire)
- Closes : [Midsummer double spawning NPCs (reverted) #16617](https://github.com/azerothcore/azerothcore-wotlk/issues/16617)
- It builds without errors.
- Tested on Windows 11.
1. Follow the section called "Steps to Reproduce Problem" in https://github.com/azerothcore/azerothcore-wotlk/issues/16617 after updating the DB.
- None
**REMEMBER**: when testing …

fix(DB/GameEventCreature): Removed duplicated fire festival Flame Wardens

---

src/server/game/Entities/Object/Position.h

-  Normalize angle returned by both Position.GetRelativeAngle functions.
-  Currently GetRelativeAngle can return angles values which will later cause issues in ChaseMovementGenerator.PositionOkay. For example if it returns a relative angle -4.9 it is then passed onto ChaseAngle.IsAngleOkay function. For desired RelativeAngle value of 3.2 we will get a diff value of 8.1 which is larger than 2pi and will make the 2nd argument to std::min negative, returning said argument. Given that Tolerance for most sane applications should be positive this will cause the function to sometimes return incorrect result.
https://github.com/azerothcore/azerothcore-wotlk/assets/54774532/7e15fe71-a06c-4084-8d11-b25f627a19b2
From PetAI.cpp, PetAI::DoAttack:
```cpp
float angle = combatRange == 0.f && …
```

fix(Core/Position): Normalize Position.GetRelativeAngle

---

src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp

the relay spell being used made a visual of infernal comets going to every place. with only the normal one, only one falls down. This goes against some of the sniffs a bit so we might have to look at this better in the future.
none needed
1. go to malchy
2. engage
3. wait for infernals
4. observe only 1 falling
none afaik …

fix(Scripts/Karazhan): fix visual of infernals on Malchezaar

---

src/server/game/Entities/Unit/Unit.cpp

- AoE spells/abilities done by non-flagged players now has no effect on pvp flagged players.
- None.
"_it is not possible to become flagged through use of AOE attacks around players or NPCs, the attack will simply have no effect and will not flag you._" written 21 October 2008, https://wowpedia.fandom.com/wiki/Bluewall?oldid=1639893
"_Consecration and other similar spells can no longer be used by non-PvP flagged players to damage PvP flagged enemies._", Patch 1.7.0, 13 September 2005, https://wowpedia.fandom.com/wiki/Patch_1.7.0
"_In WoW aoe effects does not hit pvp flagged players unless you're pvp flagged as well._" written 27 December 2010, https://forums-archive.anarchy-online.com/showthread.php?585603-Turn-PVP-on-off&s=1c6663365aa80dc8fb5d4b159fc2e78f&p=5916665&viewfull=1#post5916665 …

fix(Core/Unit): Added bluewall AoE check

---

src/common/Configuration/Config.cpp
src/server/apps/authserver/Main.cpp
src/server/apps/worldserver/Main.cpp

- Change the `GetValueDefault` function in `Config.cpp` to always choose environment variable over which value is in a config file
- This is typically how environment var configs work in many programs; the environment var always take precedence over the config file
- The removes the need to execute an `OverrideWithEnvVariablesIfAny()` step
- This fixes env vars for modules since previously, modules would be loaded after the `OverrideWithEnvVariablesIfAny()` function
- I also changed some of the output messages related to loading configurations from env vars. They kind of made it seem like a config using an …

refactor(Core): Source config more aggressively from env, rephrase a few of the messages

---

src/server/game/Achievements/AchievementMgr.cpp
src/server/game/Instances/InstanceSaveMgr.cpp

- Progress #1418
This PR implements the 3 statistics shown in Statistics->Dungeons & Raids:
Total 5-player dungeons entered
Total 10-player raids entered
Total 25-player raids entered
The statistics actually counts the ENTERED dungeons / raids, although the criteria is named COMPLETED, see:
https://github.com/azerothcore/azerothcore-wotlk/issues/1418#issuecomment-1723318667 …

fix(Core): Implement ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_RAID

---

src/server/game/Entities/Unit/Unit.cpp

This PR fixes a side effect of #13705 for warriors charging underwater. The fix was based on the `Unit::CanSwim` method which is incorrectly returning false for the player.
- Closes #17268 …

fix(Core/Unit): Fix CanSwim method not accurate for players

---

data/sql/updates/pending_db_world/make_malchezaar_door_not_interactable.sql

- change the door to be not selectable
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16272
- Closes https://github.com/chromiecraft/chromiecraft/issues/5611
see sources linked in issues
- tested ingame -> works
- 
1. go to kara
2. fly up to the top 
3. go near the door and see it is unclickable …

fix(DB/GameObject): fix Malchezaar door being selectable

---

data/sql/updates/pending_db_world/uint32_quest_template.sql
src/server/game/Quests/QuestDef.cpp

closes https://github.com/azerothcore/azerothcore-wotlk/issues/16912
1. Set the AllowableRaces column in quest_template to a higher value than uint16
2. Check if you have any erros on starting the server according to this PR
3. Confirm that its working
- U need custom races to test this PR …

fix(Core/Quest): AllowableRaces to uint32 for custom Racemasks

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Scripting/ScriptDefines/AllCreatureScript.cpp
src/server/game/Scripting/ScriptMgr.h

Adds the `OnBeforeCreatureSelectLevel()` hook into the `Creature::SelectLevel` function. This hook allows a module to examine and potentially change the level of a creature just before it has its level set and stats generated.
This hook allows me to avoid the "Level Up" animation that happens when entering an instance with AutoBalance or summoning a new creature that is scaled, since the level decision is made before the creature exists in the world.
This PR is in support of new features coming Very Soon™ to the [AutoBalance module](https://github.com/azerothcore/mod-autobalance).
The changes have been …

feat(Core/Scripting): Implement `OnBeforeCreatureSelectLevel()` hook

---

data/sql/updates/pending_db_world/rev_1695820418952974700.sql
src/server/scripts/Events/midsummer.cpp

- Progress #12145
.event start 1
.tele orgrimmar
.go xyz 1937 -4326 22
click on ribbon pole
observe randomized beam color (blue/red/pink)
walk away from ribbon pole until beam disappears
repeat …

fix(Scripts/Midsummer): Randomize ribbon pole beam color

---

data/sql/updates/pending_db_world/rev_1696540155725328200.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9646
Make 2 warriors
.additem 12798
.additem 13286
Attacking with the same weapon (on 2+ characters) stacks the debuff.
(Digmaster 5000, and Vibroblade use different spell (that does not stack), but still shouldn't be stacking with 5%) …

fix(DB/spell_custom_attr): Allow Armor Shatter/Puncture armor to stack

---

src/server/game/Loot/LootMgr.cpp
src/server/game/Scripting/ScriptDefines/GlobalScript.cpp
src/server/game/Scripting/ScriptMgr.h

Adds a hook `OnAfterCalculateLootGroupAmount` to the loot manager directly after the config option `Rate.Drop.Item.GroupAmount` is read. This hook allows modules to dynamically modify the drop amount of grouped loot items. 
A similar hook already exists for reference loot (`OnAfterRefCount`).
I'm not to sure about the name `OnAfterCalculateLootGroupAmount`. If somebody has a better name I'm open to it.
1. Create a simple module that implements the hook
2. Modify the parameter "groupAmount" passed to a higher value
3. Observe higher drop amounts of …

feat(Core/Scripting): Implement hook `OnAfterCalculateLootGroupAmount()`

---

data/sql/updates/pending_db_world/rev_1696799173938352600.sql
src/server/scripts/World/go_scripts.cpp

Upon reset they return to their initial spawn positions, not next to the chest.
To fully close the issues, it would allegedly require sniffing every single Inconspicuous Landmark's spawns, since the NPCs are based on waypoints as seen on the Trinity issue sniff.
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/8407
- Progress https://github.com/chromiecraft/chromiecraft/issues/1998
https://www.youtube.com/watch?v=h2a9XKZpktM
https://github.com/TrinityCore/TrinityCore/issues/24962 - sniff, confirming that …

fix(DB/SAI):  Cuergo's Gold improvements

---

data/sql/updates/pending_db_world/rev_1696761835374043300.sql
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Spells/spell_item.cpp
src/server/scripts/World/npcs_special.cpp

PR also corrects the ability to use other people's hatchling to do your quest/projectile to them.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8409
- Closes https://github.com/chromiecraft/chromiecraft/issues/2473
- Closes https://github.com/chromiecraft/chromiecraft/issues/2488
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8107
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9296
- Closes https://github.com/chromiecraft/chromiecraft/issues/2376
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9548
- Closes …

fix(Core/Scripts): Venomhide Hatchling improvements

---

src/server/game/Spells/SpellEffects.cpp

Adds an extra condition to the position randomization function for summoned guardian. This condition ensures that if the target for the summon is from the DB (`spell_target_position`) that it will appear exactly at that position every time.
- Needed for #17398
- Related to #12257
- Related to https://github.com/chromiecraft/chromiecraft/issues/3709
Before applying the PR:
1. `.go xyz 4032.49 -3357.65 115.06 329 1.52`
2. Engage Baron Rivendare (10440)
3. Observe that the first wave of skeletons appear exactly at the spell effect on each bone pile
4. …

Fix (core/SpellEffects): Don't randomize summoned guardian position if target is in the DB

---

src/server/scripts/Spells/spell_paladin.cpp

I can see how this PR can spark some debate, and perhaps it should. I do invite people to read the sources, as well as the original bug report. As a lot of planning went into this from the reporter's side.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16537
- Closes https://github.com/chromiecraft/chromiecraft/issues/5673
https://wowpedia.fandom.com/wiki/Patch_3.2.0
Judgments are attacks, patch 3.2:
"Judgments: All paladin judgements are now properly considered as melee attacks that cannot be dodged, blocked or parried."
Again patch 3.2, about …

fix(Scripts/Paladin): ensure Judgements of the Just procs Seal of Vengeance/Corruption

---

src/server/game/Entities/Player/Player.cpp

A small durability loss on e.g. death still occurs even when all the "DurabilityLoss" options in worldserver.conf are set to 0.
This happens because the calculation for the actual durability points lost always "rounds up" to 1 point at the minimum.
- Closes 
No source, because this is a non-blizzlike server configuration.
1. Set all "DurabilityLoss" options in worldserver.conf …

fix(Core/Player) Stop small durability loss from still occuring when DurabilityLoss options in worldserver.conf are set to 0

---

src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp

This PR addresses two issues:
The `boss_valithria_dreamwalker` script does not correctly account for any change in Valithria's max health, notably from any module or process outside of the value set in the database. While this specifically impacts AutoBalance's changing in the creature's max health, it would also impact any other method of altering the creature's max health.
Additionally, I noticed that the Risen Archmages are not channeling as they should be, and my combat log is filled messages indicating that they are attempting to (incorrectly) cast Corruption over and over again. Changing the spell cast in …

fix (Scripts/ICC): Make Valithria starting health dynamic, fix broken channeling spell

---

src/common/Cryptography/OpenSSLCrypto.cpp
src/common/Threading/ProcessPriority.cpp
src/server/game/Movement/Waypoints/WaypointMgr.h

Because despite having a bazillion CI checks, not a single does check for actual important stuff
closes #17610

fixed nopch build

---

data/sql/updates/pending_db_world/rev_1698228038574727200.sql

Should proc on critical/normal/partial block
- Closes https://github.com/chromiecraft/chromiecraft/issues/6164
"struck" = damage taken
"hit by" = can be without taking damage (regarding https://github.com/azerothcore/azerothcore-wotlk/pull/17574)
>Just to expand a little, skullflame can actually push out decent numbers - it's the block value / rating that is the key decider.
If you full block it won't proc, so u need to switch around your gear (block value) to utilize it on strat where it's easy to get enough block value to full block. Once you get t4+ gear your lowering …

fix(DB/Procs):  Skullflame Shield & Demon Forged Breastplate

---

data/sql/updates/pending_db_world/2023_10_29_00.sql

**Current Behaviour**
Mining node is stuck midway up a vertical surface making it impossible to mine.
Co ordinates: 68.41, 67.97
Go to Ironband's Excavation Site, coordinates: 68.41, 67.97
**Before datafix:**
**After datafix:**

fix(DB/Loch Modan): adjusting x, y and z axes for nodes

---

src/server/game/Handlers/ArenaTeamHandler.cpp
src/server/game/Handlers/AuctionHouseHandler.cpp
src/server/game/Handlers/BankHandler.cpp
src/server/game/Handlers/CharacterHandler.cpp
src/server/game/Handlers/DuelHandler.cpp
src/server/game/Handlers/GroupHandler.cpp
src/server/game/Handlers/ItemHandler.cpp
src/server/game/Handlers/MiscHandler.cpp
src/server/game/Handlers/NPCHandler.cpp
src/server/game/Handlers/QueryHandler.cpp
src/server/game/Handlers/QuestHandler.cpp
src/server/game/Handlers/Socialhandler.cpp
src/server/game/Handlers/TaxiHandler.cpp
src/server/game/Server/WorldSession.cpp

Remove redundant logging calls from some message handlers and handle logging through the WorldSession::Update method.
Reduces redundant network logging code
1.
2.
3. …

chore: remove redundant logging calls from some message handlers

---

data/sql/updates/pending_db_world/rev_1699388718386814200.sql
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Events/midsummer.cpp

- using "Unlit Torches" no longer shows an AOE circle
- Throwing the first torch now correctly requires nearby Midsummer Bonfire
- Closes #12392
- Closes chromiecraft/chromiecraft#3667
Thanks to @heyitsbench, the sniffs gave the hint for the correct spell id
.event start 1
.quest add 11923
.go c 245602
use "Unlit torches" - should fail - "Requires Midsummer Bonfire"
walk close to bonfire
use "Unlit torches" to throw torch
observe no AOE circle, torch gets thrown and can be catched to rethrow …

fix(Events/Midsummer): fix AOE circle bug on Midsummer Torch Catching

---

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp

Revert from my refactor because I thought summoner was the boss for some dumb reason. The actual summoner is the affected player. Renamed variables to make that more clear. Also removed despawn condition (this happened when a different player casts a spell on the demon, which made it despawn immediately). I guess this could have been a failsafe to make sure that other players can't kill the demons with spells, but I don't think this is the right behaviour. Would be nice if someone checked if I'm wrong on this though.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17510
- Closes …

fix(Scripts/SSC): make sure Insidious Whispers demons don't instantly despawn

---

src/common/Metric/Metric.cpp
src/server/apps/worldserver/worldserver.conf.dist

- Change the default metric interval to 1 second instead of 10 seconds.
- Added some further explanation to the description.
- Not being able to gather any data in Grafana due to batch of data being too large to be sent.
I no longer get an error in worldserver.exe console, and I get data in Grafana as expected.
1) Follow this guide on how to set up monitoring: https://www.azerothcore.org/wiki/monitoring-azerothcore-with-grafana
2) See that you get data as expected. …

Correct default metric interval

---

src/server/scripts/EasternKingdoms/ZulGurub/boss_jeklik.cpp

Corrects an issue with #17573 where events happened twice as fast as intended. This was due to an oversight where the scheduler was being updated twice per `UpdateAI`, once in `boss_jeklik::UpdateAI()` as an explicit call and once in `BossAI::Update()`.
I have altered the script so that the scheduler is not needed outside of combat, and that the reset is aided by `DespawnOnEvade()`, which works great. Thanks to @Nyeriah for pointing me towards a function I didn't know about.
None yet.
Jeklik Test:
1.`.go xyz -12261.517578 -1411.231934 130.803345`
2. …

Fix (Scripts/AI) ZG/Jeklik (Bat Boss) - fix double-run scheduler

---

src/common/Utilities/StringFormat.cpp
src/common/Utilities/StringFormat.h

The Mac build fails with the following 2 error messages:
`src/common/Utilities/StringFormat.h:75:53: error: no type named 'locale' in namespace 'std'`
`src/common/Utilities/StringFormat.h:75:72: error: no member named 'locale' in namespace 'std'`
- Built on macOS Sonoma 14.1.1 (23B81)

fix a Mac build issue introduced by commit #17643

---

src/server/game/Handlers/MiscHandler.cpp
src/server/game/Miscellaneous/Language.h

The proposed changes rename the 
lengthy (and a little ambiguous) ACoreStrings::LANG_YOU_NOT_HAVE_PERMISSION to ACoreStrings::LANG_PERMISSION_DENIED.
In an ideal world I think the LANG prefix should probably switched for STRID given its usage context.

chore: rename LANG_YOU_NOT_HAVE_PERMISSION to LANG_PERMISSION_DENIED

---

data/sql/updates/pending_db_world/rev_1700202454906474700.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/5382
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/15386
.aura 40303
cast a hot, should get hit only when you cast, but not when the hot ticks …

fix(DB/Procs): Spell Bomb should proc only on cast

---

src/server/game/DungeonFinding/LFGMgr.cpp

- Closes https://github.com/chromiecraft/chromiecraft/issues/5966
[Players may teleport in and out of the dungeon at any time if they are not in combat
The automatic teleport does not work while on a moving boat or zeppelin, operating a vehicle, or while dead. Players will have to leave the boat or vehicle, or resurrect and then teleport in.
](https://wowpedia.fandom.com/wiki/Dungeon_Finder)
.debug lfg
try to tp in/out while in combat/falling/dead etc. …

fix(Core/LFG): Correct checks for teleport in/out

---

src/server/scripts/Commands/cs_guild.cpp

Ensures compatibility with the original syntax of the commands.
The new changes added in the PR made it so that quotes on guild creation, deletion, rename, etc. got broken. Looks like functionality was added to just paste in the guild names without the quotes, but it seems to also break on spaces. So I added some functionality to extract quotes from the strings again, and now the command works the same as it used to on the front-end for AC users.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17789
- Fixes some things added in https://github.com/azerothcore/azerothcore-wotlk/pull/17515
The …

fix(Scripts/Commands): guild commands revert back to using guild names in quotes

---

data/sql/updates/pending_db_world/rev_1700285808976576988.sql
src/server/scripts/Commands/cs_go.cpp

Rewrites the command handler function for `.go xyz` to handle flexible inputs. The new implementation will use regex to extract float and integer values from the provided arguments and will discard any other characters.
Since the parsing doesn't care about any of the surrounding text, many different versions of coordinates are supported by this implementation. The only requirement is that the numbers are in the right order (`x y [z [mapId [orientation]]]`) and have at least one delimiter character (not a number) between each number.
The following all work as expected:
`.go xyz 4073.1 -3536.1 123.5 329 2.8` - …

feat (core/cs): Make `.go xyz` ignore non-numeric data to improve copy-paste usability

---

data/sql/updates/pending_db_world/rev_1700315570944394100.sql

Added behavior after completing a mission for Warlock quest NPCs
https://clipchamp.com/watch/bMvNGFhxr6f Videos from Blizzard servers
- Closes 
1. Create Warlock
2. .level40+
3. .go xyz -782.5499 -3711.31 41.36 1
4. .quest add 4976 
5. Complete the quest
6. Wait for the emote to finish
7. Accept the assignment of "Tecompel de Obbendal 'Olahir" or "Tecompel de Obbenno 'Olahir".
8. She is supposed to use spells to craft jewelry. …

fix (DB\Creatures): Added an event for Warlock NPCs to craft gems when a quest is completed

---

src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp

Sindragosa skips her Airphase if she reaches 35%, Airphase istn forced after 50s.
https://youtu.be/U3dn89QhTy8?t=502
We did this on Retail with 1 Tank 8DDs 1 Heal in 10HC to force the boss to stay on ground. 
- Closes 
Debian 11 
Fight Sindra and do damage to 35% in under 50s
1.
2.
3. …

fix(Scripts/ICC/Sindragosa) Airphase should not be forced after 50s if already in p2 (under 35%)

---

data/sql/updates/pending_db_world/enchanted-elemental-walk.sql
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp

Wanted to originally use on waypoint reached, but that failed for some reason. They cast the spell way too early. Doing a 2 waypoint path seemed to work, but it would mess up the pathing the elementals did. And as they start in a cone, it doesn't make sense to have 2 points away from the center
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17791
- Closes https://github.com/chromiecraft/chromiecraft/issues/6250
1. engage vashj
2. get her to p2
3. see now that the elementals walk slowly …

fix(DB/SSC): make sure Enchanted Elementals always walk and not run towards Lady Vashj

---

data/sql/updates/pending_db_world/add-spells-zevrax.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16931
1.
2.
3. …

fix(DB/BloodmystIsle): add SAI to Zevrax

---

src/server/game/AI/CoreAI/GameObjectAI.h
src/server/game/AI/CreatureAI.cpp
src/server/game/AI/CreatureAI.h
src/server/game/AI/SmartScripts/SmartAI.cpp
src/server/game/AI/SmartScripts/SmartAI.h
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

Adds SMART_EVENT_SUMMONED_UNIT_EVADE for both creatures and GOs.
Used for cases (mostly c++) where something needs to happen when a summon is evading.
https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/a2eebaac-1984-4068-b466-dd1eef395ca2
```sql
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 40;
DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 40);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, …
```

feat(Core/SmartScripts): SMART_EVENT_SUMMONED_UNIT_EVADE

---

src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp

The current code only prevents Whitemane from dying before casting sleep, but the player(s) can inflict enough DPS on her before that, that she can die before resurrecting Mograine. When this happens, the dungeon is broken and cannot progress.
- Closes 
1. Enter Scarlet Monastery, the cathedral part (the door on the left)
2. Kill Mograine
3. Use as many DPS spells on Whitemane as possible
4. When her health reaches 50%, she puts the players to sleep.
5. Without this change, she could die now and the dungeon remains broken. With this change, she …

fix(Scripts/ScarletMonastery): Prevent Whitemane from dying before resurrecting Mograine

---

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_hydross_the_unstable.cpp

- Closes https://github.com/chromiecraft/chromiecraft/issues/6451
https://www.icy-veins.com/tbc-classic/hydross-the-unstable-guide-strategy-abilities-loot
https://youtu.be/FEYAX7l5H6A?t=646
*Sound warning* https://youtu.be/J1Vph9r5ZnY&t=47
1. Go to SSC's Hydross the Unstable
2. Move him across the flags
3. Check that there are 15s before he applies either Mark of Hydross or Mark of Corruption …

fix(Scripts/SSC): Update Hydross Mark Timers

---

src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.h
src/server/game/Scripting/ScriptMgr.h
src/server/game/Server/WorldSession.cpp

Adding a new hook "OnBeforePlayerLogout" which fires _before_ the logout logic is executed for a player inside WorldSession::LogoutPlayer.  This is to support a mod I made which allows a character to change their class, which you can find [here](https://github.com/NathanHandley/mod-multi-class).
There is logic to perform before the logout save event, which made utilizing the existing OnPlayerLogout non-viable (visual item changes on class switch were not being pushed and registered on the client).  Since the save hook does not have the "logout" bool available, I was left with a choice to add this new hook or update/overload that hook.  It seems that a OnBeforeLogout could be useful for more hypothetical use cases, so I elected with this approach.  Also, this allows it to work in the …

feat(Core/Hook): New hook OnBeforePlayerLogout

---

data/sql/updates/pending_db_world/rev_1705791671858497500.sql
src/server/scripts/Commands/cs_server.cpp

".server set motd something something" currently crashes server because it understands first word as realm id …

fix(scripts/commands) prevent crash on set motd

---

data/sql/updates/pending_db_world/striking-back-init.sql
src/server/scripts/Events/midsummer.cpp

- Closes #12151
This PR is being tested as changes are made.
1. `.quest add 11917/11947/11948/11952/11953/11954`
2. Go to the respective Ice Stone object.
3. Summon the lieutenant of Ahune.
4. Observe their speech and combat AI. …

fix(Scripts/Midsummer): Correct behavior for Striking Back quests.

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Globals/ObjectMgr.cpp
src/server/scripts/Commands/cs_npc.cpp
src/server/scripts/Commands/cs_wp.cpp
src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp

follow-up to #18153
functionality removed as suggested by @Nyeriah 
If spawns are stuck in the ground imo these should be fixed in DB and not rely on this automated manipulation.
I've assembled a list of creature spawns that used to trigger this function as of 4cfad0ffa:
https://gist.github.com/sudlud/b57f3ee6617e2cf10fe2edc554c13245
I've randomly checked some of these spawns - at least for creatures with movement it doesn't seem to matter, they still wander around.
Also there's at least one (sniffed) spawn that could never spawn correctly while this functionality is implemented as it's beeing spawned in a room …

fix(Core/Creature): Remove automated z spawn correction

---

src/server/database/Database/DatabaseWorkerPool.cpp
src/server/database/Database/DatabaseWorkerPool.h
src/server/database/Database/MySQLConnection.cpp
src/server/database/Database/MySQLConnection.h

Change the way the MySQL/MariaDB's version is checked to account for the `5.5.5` prefix that mariadb `10.x` uses
- Related to issue https://github.com/azerothcore/azerothcore-wotlk/issues/18113 
error appears when setting the database container to `mariadb:10.6`
```
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
Database "acore_auth" does not exist
Do you want to create it? [yes (default) / no]:
AzerothCore does not support MySQL versions below 5.7 or MariaDB versions below 10.5.
Found server version: 50505. Server compiled …
```

Fix(core): Support MariaDB 10.x when using mysql client libraries

---

data/sql/updates/pending_db_world/mana-warp-fix.sql

https://github.com/azerothcore/azerothcore-wotlk/pull/18026 did the following:
if the mana warps fail in casting their main growing ability (which happens only once) they fail to grow and also fail to execute the rest of the linked events (no explosion, no event setting and because of the latter no death as they are set to be invincible (stay at 1 hp). This PR simply removes the linking to fix this (all events should now fire individually)
credits to [kissingers](https://github.com/kissingers) for figuring this out
- Closes https://github.com/chromiecraft/chromiecraft/issues/6554
The changes have been validated …

fix(DB/Karazhan): remove smart_script linking so Mana Warps properly die even when stunned

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.h
src/server/game/Scripting/ScriptMgr.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/Spells/spell_item.cpp
src/server/scripts/Spells/spell_paladin.cpp
src/server/scripts/Spells/spell_shaman.cpp

Added a new hook "OnPlayerHasActivePowerType" inside a new interception helper function "Player::HasActivePowerType" (which has a virtual base Unit::HasActivePowerType) and replaced many comparison uses of Unit::getPowerType() == power.  This hook allows active power type overrides granting the ability to use any class power you choose on any other class, such as rage on a Mage or mana on a Warrior.
none
n/a
To test the change impact to core/stock: use rage/energy/mana/runic on the respective classes.  
To test this change as a hooked script, implement the PlayerScript hook OnPlayerHasActivePowerType.  An example of this implementation can be found in this mod branch I'm working on here: …

feat(Core/Unit): New helper HasActivePowerType and script hook OnPlayerHasActivePowerType

---

src/server/database/Database/MySQLConnection.cpp

- In the latest versions of MySQL, a method was changed, which gave errors in macOS. At first, the verification was going to be on that operating system, but in the end, it was done on the MySQL version, to try to continue supporting previous versions. However, it omitted the fact that MariaDB also continues to use this constant for the version and that was proving errors in some operating systems, such as Debian 12.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18307
1. Download the changes and compile.
2. The only thing that does the pull request is this and previous, and check the version of MySQL to know what method you should use. …

feat(fix/build) ignore mariadb in the conditional

---

src/server/game/Scripting/ScriptDefines/GameObjectScript.cpp

This PR essentially repeats this - #17596
But for GameObjects
Removed another unnecessary ClearGossipMenuFor call which randomly broke gossip menus.
For example, if you are talking with some NPC, and at that moment you receive/lose some item or gold, your client will send CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY. If at the same time there are some GameObjects near you that can be questgiver, then a chain of method calls will lead to ClearGossipMenuFor and your gossip menu with NPC will suddenly breaks. You won't even understand why this could happen.

fix(Core/GameObject): Remove unneeded ClearGossipMenuFor call

---

src/server/game/Handlers/ItemHandler.cpp

- remaining duration is not beeing stored in character_gifts
- gift wrapping of items with duration preserved them infinitely
- discovered while researching chromiecraft/chromiecraft#6669
take a non-stackable item with limited duration, e.g. "Book of Romantic Poems":
.additem 22298
take gift wrapping paper, e.g. "Empty Wrapper"
.additem 21830
try to wrap the item
before PR:
- item gets wrapped successfully
- item can be stored infinitely
- after unwrapping, duration gets reset to max. duration from item_template
after PR:
- item can't be  wrapped
1.
2. …

fix(Core): Prevent gift wrapping of limited duration items

---

CMakeLists.txt

Fix cmake warning
```
CMake Warning (dev) at src/cmake/macros/FindMySQL.cmake:113 (exec_program):
Policy CMP0153 is not set: The exec_program command should not be called.
Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Use execute_process() instead.
Call Stack (most recent call first):
CMakeLists.txt:103 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at src/cmake/macros/FindMySQL.cmake:122 (exec_program):
Policy CMP0153 is not set: The exec_program command should not be called.
Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Use execute_process() instead.
Call Stack (most …
```

feat(Cmake): add support old policy 0153

---

src/common/Debugging/Errors.cpp

- Example abort msg:
```
/home/winfidonarleyan/Git/azerothcore-wotlk/cmake-build-relwithdebinfo/src/server/apps/authserver
#----------------------------------------------------------------------#
>> ABORTED
#----------------------------------------------------------------------#
```
- Example assert msg
```
#----------------------------------------------------------------------#
>> ASSERTION FAILED
#----------------------------------------------------------------------#
```

chore(Common/Debugging): change report codestyle

---

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_morogrim_tidewalker.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18449
- Closes https://github.com/chromiecraft/chromiecraft/issues/6739
https://wowpedia.fandom.com/wiki/Morogrim_Tidewalker?so=search
1. bring two toons to Morogrim
2. take note that target toon doesn't get watery grave …

fix(Scripts/SerpentshrineCavern) Filter Watery Grave Target

---

src/server/game/Spells/SpellInfoCorrections.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17425
- Closes https://github.com/chromiecraft/chromiecraft/issues/6145
1. After applying the changes, it should prevent you from using the spells, if there is some type of barrier between the players. Like for example, a wall. …

fix (SpellInfoCorrections) Add them to the spells list

---

data/sql/updates/pending_db_world/rev_1708782048020249700.sql
src/server/game/Entities/Player/Player.h
src/server/game/Miscellaneous/Language.h
src/server/scripts/Commands/cs_reset.cpp

Adding a new command in the .reset command set allowing targeting item reset (deletes).
> Syntax : .reset items equipped|bags|bank|keyring|currency|vendor_buyback|all|allbags #playername 
Delete items in the player inventory (equiped, bank, bags etc...) depending on the chosen option. 
#playername : Optionnal target player name (if player is online only). If not provided the command will execute on the selected target player.
_Not applicable_
_Not applicable_
1. **Do not forget to apply the .sql file :** _data/sql/updates/pending_db_world/rev_1708782048020249700.sql_
2. Add any items in your inventory to fill it up
3. Add items in your bank and in …

feature(Core/DB): Implement ".reset items" command

---

src/server/game/AI/SmartScripts/SmartScript.cpp

To reproduce bug try to `.go cre id 16164 `and figh with him , or try to `.add creature  16420 ` in some place with big count of mobs and u will see many creatures witht id 16164 that spawn as spam . 
> What was broken ?
We call the action every time in the loop, the number of players is not taken into account, but all objects nearby are counted
In the loop we count the number of players and then call the action if the number is greater than indicated in the event
You can look in case above what work as expected: 
```
case SMART_EVENT_NEAR_PLAYERS_NEGATION:
{
uint32 playerCount = 0;
ObjectVector targets; …
```

fix (Core/Scripting): SMART_EVENT_NEAR_PLAYERS 

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/SpellEffects.cpp

The first commit related to `SPELL_EFFECT_INEBRIATE` (100) effect. The problem is that there are not only inebriation but also sobering spells (with basepoint < 0). The current implementation uses an unsigned type, ignoring sobering spells. This leads to a uint8 underflow, resulting in the spell's behavior being completely unexpected: it can both inebriate and sober you up.
Example:
1. `.gobject add temp 185914`
2. Use it!
3. If you were completely sober before, you will now get maximum inebriation. Although coffee was supposed to sober you up by 20%. This happened because of uint8 underflow.
There is another problem: there are spells with an inebriate effect with basepoint values so large or small that it inevitably leads to uint8 overflow/underflow. For example, `29690` or `46874`. As …

fix(Core/Spells): Fixed work of sobering spells and other improvements for drunk system

---

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
src/server/game/AI/ScriptedAI/ScriptedCreature.h
src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp

Some bosses make sure all nearby friendly creatures assist the boss when engaged. The problem here can be that this is only called on being engaged, which means that if a hunter uses FD right after pull, the boss will move to other targets (due to SetInCombatWithZone) but all the aggroed creatures will reset. This PR makes sure this call for help is called every 2 seconds during combat.
Problems may arise when we implement this on bosses that can move around a lot, as they would start calling every creature in the vicinity as they move around, which wouldn't be intentional. For the current 2 bosses I added this to in the PR, however, this is not an issue, as they have a boundary. And even at the max range of that boundary the range for call to help does not reach creatures it shouldn't. …

fix(Scripts/BossAI): add optional variable to BossAI class to make sure the boss calls for help

---

src/server/game/Server/WorldSocket.cpp

We have a network thread that makes approximately 1k invocations per second of this function for every socket:
https://github.com/azerothcore/azerothcore-wotlk/blob/73340b94e3dbcc67da8e52ea5ddea06298c2c6d4/src/server/game/Server/WorldSocket.cpp#L161-L166
Most of the time, `_bufferQueue` remains empty, and we should do nothing inside this function. 
However, for each call, we allocate a 4KB buffer even when it is unnecessary. 
As a result, a significant portion of CPU time is dedicated to the allocation and deallocation of this buffer.
Below, you can observe the reduction in CPU consumption (with one player online) after implementing this change.
Before:
After:
-  [ ] Scripts (bosses, spell scripts, …

feat(Core/Optimization): Reduce CPU consumption by allocating sendBuffer only when it is needed.

---

src/server/scripts/Outland/BlackTemple/illidari_council.cpp

- Closes 
- The error appeared when updating one of the modules.
1. If you compile on any Linux distribution with clang, possibly Ubuntu, you should get that error before applying this change. …

fix(Script/illidari_council.cpp). Add override in EnterEvadeMode

---

src/server/apps/worldserver/worldserver.conf.dist
src/server/game/Server/WorldSocket.cpp

While looking at #18628 and trying to understand, how the buffer works, I first noticed that the comment in the current code is wrong.
The buffer is not statically set to 4kB but instead initialized with 4kB and later resized to 64kB. This makes the impact on the CPU time to allocate that buffer (previously on every update even without queued packets) even more pronounced.
So the first commit is a definite fix of the documentation.
The following two commits are a proposal and up for discussion. When players are alone in the wilds, allocating a 64kB buffer every time seems wasted. On the other hand, in raids or cities, having a small buffer also doesn't seem that efficient.
Therefore, we could start with a 4kB sized buffer (as previously implied with the comment) and then increase its size …

feat(Core/Optimization): Correctly document sendBuffer size and optimize it.

---

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp

```
[ 60%] Building CXX object src/server/game/CMakeFiles/game.dir/Scripting/ScriptDefines/UnitScript.cpp.o
/Users/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp:164:46: fatal error: comparison of integers of different signs: 'uint32' (aka 'unsigned int') and 'int32' (aka 'int') [-Wsign-compare]
if (target->GetPower(POWER_MANA) < aurEff->GetBaseAmount())
[ 60%] Building CXX object src/server/game/CMakeFiles/game.dir/Scripting/ScriptDefines/VehicleScript.cpp.o
~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
``` …

fix. fatal error: comparison of integers of different signs

---

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp

Changes to initial timers are ok / predictable because of previous events.
repeated casts cannot be set appropriately because of the delayall in https://github.com/azerothcore/azerothcore-wotlk/blob/e4136639e3b1ce4e4fc73204872d988588d60aee/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L480 with 90 seconds repeat cycle and the delayall in https://github.com/azerothcore/azerothcore-wotlk/blob/e4136639e3b1ce4e4fc73204872d988588d60aee/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L754 with 50 sec cycle. Both will cross-over with phoenix cycle resulting in atleast 1 summon happening without the delay at some point.
Options would be to rework the script, using DBM timers as minimum or using DBM timers as a frequency to achieve most of the time (which is this …

fix(Scripts/TheEye): Update Kaelthas Phoenix timers

---

src/server/game/AI/SmartScripts/SmartAI.cpp

- Closes
```
/home/runner/work/mod-npc-all-mounts/mod-npc-all-mounts/src/server/game/AI/SmartScripts/SmartAI.cpp:1156:37: fatal error: unused parameter 'pathId' [-Wunused-parameter]
void SmartAI::PathEndReached(uint32 pathId)
^
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:300: src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartAI.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1131: src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
``` …

fix(Core/SmartAI) fatal error: unused parameter pathId

---

src/server/game/Maps/Map.cpp

- this just broke the whole purpose of setActive(true) if the gameobjects is still not really beeing set active afterwards
- GetGridActivationRange() returns 0.0f for gameobjects anyways
- so CalculateCellArea() will result in the minimal cell area around the gameobject's position
- if the cell around the gameobject should not be updated, the gameobject should not have been set active in the first place
- Closes 
fun fact:
Battlefield::SpawnGameObject() sets all objects active after spawning them
1.
2.
3. …

fix(Core/Map): remove hackfix that blocked update of GOs beeing set active

---

data/sql/updates/pending_db_world/rev_1714650326089446105.sql
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18818
original TBC reference https://youtu.be/YA_B7t2ojkU?si=UUr2nbMo3PON3wui&t=293
Changes to test with 1,2,3 characters
```
}).Schedule(3s, [this](TaskContext context) // FOR TESTING
{
DoCastSelf(SPELL_BLAST_NOVA);
```
```
if (GetTarget()->GetAuraCount(SPELL_SHADOW_GRASP_VISUAL) == 3) // FOR TESTING
```
Requires 5 characters to click cubes simultaneously to trigger banish effect
pull once and clear trash
1. `.go c 91254`
2. kill orcs to start p2
3. click cubes …

fix(Scripts/Magtheridon): Clicking cubes should Banish Magtheridon

---

src/server/apps/authserver/Server/AuthSocketMgr.h
src/server/apps/authserver/authserver.conf.dist
src/server/apps/worldserver/worldserver.conf.dist
src/server/game/Server/WorldSocketMgr.cpp
src/server/shared/Network/NetworkThread.h
src/server/shared/Network/Socket.h
src/server/shared/Network/SocketMgr.h

In some cases, you may want to place the authserver or worldserver behind a proxy or load balancer. However, if you do this, you would lose the client's address (IP). To address this issue, most proxies and load balancers support Proxy Protocol (v1 & v2). To utilize it, we also need Proxy Protocol support on both the authserver and worldserver.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18100
I used HAProxy to test this change.
1. I changed authserver and worldserver configs by changing ports (3777 & 8026) and by enabling Proxy …

feat(Core/Network): Add Proxy Protocol v2 support.

---

data/sql/updates/pending_db_world/za-timed-loot.sql

- Closes issue mentioned in notes of #18868. …

fix(DB/Loot): Correct Zul'Aman prisoner loot.

---

data/sql/updates/pending_db_world/rev_1715099644936912576.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17122
```
Keys
.add 21762 20
.add 21761 20
Spawn chests
.gobject add 180690
.gobject add 180691
```
1. open chest without key: "locked", not possible
2. open chest with key: possible, consumes key, can loot items
3. open chest again: possible, without using key
care with using GM-mode to tele to chests in AQ20/40 …

fix(AQ40/SmartGameObjectAI): remove locked status from scarab coffer upon opening

---

data/sql/updates/pending_db_world/rev_1713998045630729445.sql
src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp
src/server/scripts/Spells/spell_generic.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18801 
Approach is based on https://github.com/TrinityCore/TrinityCore/commit/5eac5ee2dbee289acbde48506b04ef35a0b1d5b2
See below for notes 
1. Go to  Netherspite (requires 2 characters) or  Blaumeux Naxx10/25 (requires 1 character),
2. Stand in Void Zone
3. Observe damage with and without a damage reduction spell
```
TP Blaumeux
.go c 130962
TP Netherspite
.go c 135476
learn pain suppresion or any %damage reduction spell: 
.learn 69910
```
EffectValues are hardcoded from the spell DBC.
``` …
```

fix(Scripts/Spell): Fix Void Zone damage calcs for Netherspite, Blaumeux

---

src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp

- fixes side effect of https://github.com/azerothcore/azerothcore-wotlk/pull/15048 that fixes a bug introduced with https://github.com/azerothcore/azerothcore-wotlk/pull/12696
portal hub areatrigger always returns true making the portal always enabled. Portal should be disabled until all 4 wings are cleared. Orbs are there to bypass this requirement
1. go stand on the portal
2. kill four wings and stand on the portal, should tp to sapphiron
3. …

fix(Scripts/Naxxramas): Re enable Portal Hub teleport requirement 

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/PlayerStorage.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
src/server/game/Scripting/ScriptDefines/PlayerScript.h
src/server/game/Scripting/ScriptMgr.h

Add two hooks for applying item mods (one from proto stats and one from enchantment slots).
1.
2.
3. …

feat(core): add hooks for applying item mods

---

apps/docker/entrypoint.sh

This makes it so the startup script (known as the entrypoint) for the docker containers will ensure that it owns the config and filelog directories on startup. 
This is important since there's the `dist` config files that get created during build, and these need to be transferred to the runtime config directory at runtime if they don't exist already.
Technically speaking, we could remove the bind mount (actually comment it out in the `docker-compose.yaml` file) so that the reader can see there's an option to do so. The reasoning for this is to nudge the user in the direction of using environment variables for config rather than files. On the other hand, this breaks compatibility for other users and we don't really need to do that for something so small.
- …

fix(Docker): Check write access for config dir

---

data/sql/updates/pending_db_world/rev_1716230497379077638.sql
src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h
src/server/scripts/Spells/spell_generic.cpp

Adds better interactions between Boss Keepers, Gossip Keepers, Keepers and Sara
Changes to Keeper AI, Keeper Auras/Buffs, Sanity Well summons, Boss Keeper outro,...
Core generic spellscript to handle Keeper Aura conditions
before fight: Gossip appear after "tp" trigger from Boss
on fight: Gossip Keepers despawn
on wipe: Gossip respawn
on fight end: Gossip do not respawn
before fight: talked to Keepers are spawned, they do not give buffs
on fight: Keepers give buffs only to players and themselves. should grow in size
on wipe: Keepers despawn, buffs go away
on reset: Keepers spawn, no buffs
on fight end: Keepers …

fix(Scripts/Ulduar): update Boss Keepers, Gossip Keepers, Yogg Keepers, Yogg-Saron

---

data/sql/updates/pending_db_world/rev_1716655119634919952.sql
src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h

Upon killing 4 keepers, after 45 seconds, unlock the gate and play emote "gate is unlocked"
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16088
World Trigger speaks `creature_text` from sniff
measured 45 seconds between boss and emote on Wrath Classic VOD
measured 45 seconds between boss and emote on Retail VOD
grabbed trigger position (next to gate) from TC 335
1. Kill 4 keepers
2. Go to gate
3. wait 45s
a. gate unlocks (does not open)
b. emote plays
```
Freya boss
.go c id 32906
Thorim boss
.go c id 32865
Mimiron boss
.go c id 33350 …
```

fix(Scripts/Ulduar): Add emote for opening of the Ancient Gate of the Keepers

---

src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp

Makes Mimi fall down and get up, become selectable, friendly, do his dialog
removes combat status on ejection
also fixes `pInstance->SetData(TYPE_MIMIRON, DONE);` to be done when loot spawns instead of on despawn
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/c3009ba4-3033-4b2d-a895-8a0dd31b29ef
note stuck in combat until despawn
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/d5862b9f-4524-48b0-939b-d61298546ac7
- Closes 
Summary from sniff:
```
20:27:35.819 
targettable
yeeted
sleep
20:27:41.849 
stand up, friendly
20:27:45.491
talk …
```

fix(Scripts/Ulduar): adjust Mimiron outro RP sleep visuals

---

data/sql/updates/pending_db_world/rev_1715708681053405822.sql
src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h

drawing of tram structure, ids - guids
I used timings to get the visual effects to sync up however the `StaticTransport` events for arrival should be used, but I can't get them to emit? I tried the following
```
-- 1: event_scripts to activate the "doors" circles upon arrival
DELETE FROM `event_scripts` WHERE `id` IN (21393,21394);
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `dataint`, `x`, `y`, `z`, `o`)
VALUES
(21393, 0, 11, 42867, 0, 0, 0.0, 0.0, 0.0, 0.0),
(21394, 0, 11, 56125, 0, 0, 0.0, 0.0, 0.0, 0.0);
-- 2: smartAI on the tram to activate the "doors" circles upon …
```

fix(Ulduar/Tram): add rocket booster, turnaround visuals, button logic

---

src/server/game/Handlers/PetHandler.cpp

Upon dismissing a charmed creature owned by another unit, stop the charm instead of despawning
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4198
https://github.com/TrinityCore/TrinityCore/blob/14501c0d7af9ae06e3febcb7567407191249d821/src/server/game/Handlers/PetHandler.cpp#L238
Go Thrall in Hyjal, charm demons that spawn in later waves. On dismiss they should not despawn
```
.go c 139637
```
Razuvious
```
.go c 128312
.go c id 16061
```
MC understudy, right click dismiss
1.
2.
3. …

fix(Core/PetHandler): when dismissing a charmed unit owned by another unit; stop the charm instead of despawning

---

src/server/game/Entities/Player/PlayerQuest.cpp

Timed quest 853 always has questState "QUEST_STATUS_COMPLETE" so it would never be able to fail within `FailQuest()`
- Closes #6991
- Closes https://github.com/chromiecraft/chromiecraft/issues/1217
```sql
-- reduce quest timeout to 60 seconds
UPDATE `quest_template` SET `TimeAllowed` = 60 WHERE (`ID` = 853);
```
.quest add 853
logout for at least 1 minute
login
before PR
observe quest not failed and no timer showing
after PR
observe quest beeing failed correctly
You can …

fix(Core/PlayerQuest): make timed quests failable

---

src/server/database/Database/Implementation/CharacterDatabase.cpp
src/server/scripts/Commands/cs_misc.cpp

-  [x] Command
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3177
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/18855
1. Use the `.unstuck` command with the name of the character you want to unlock. If it is offline, it will be sent to where the player has the hearthstone established.
2. ex. `.unstuck barbz`
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/9dd54db0-8d78-42ac-9d68-82509224bc63
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/1dc1f206-5d36-4014-863d-c7ea880b6099 …

chore(Command/unstuck) use command with offline players

---

src/server/game/Entities/Pet/Pet.cpp
src/server/game/Handlers/PetHandler.cpp

Consider the following scenario: 
1. warlock summons pet, mounts up and then logs out
2. warlock logs in
checks for conditions such as mounted and others
https://github.com/azerothcore/azerothcore-wotlk/blob/da8d42c72cf819f8baeda5cd0450023e7f1d066a/src/server/game/Entities/Pet/Pet.cpp#L257
pet can't be summoned as the player is mounted, so the pet is set as "summon later"
`IsPetNeedBeTemporaryUnsummoned` https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.h#L2395
3. when dismounting
When player tries to resummon this pet, it checks if we are able to summon. For …

fix(Core/Pet): Warlock pet handling

---

data/sql/updates/pending_db_world/rev_1718486949488763477.sql
src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp

1. refactors lava_strike spellscript
2. add Flame Tsunami knockback
knockback spell (id: 60241) uses SPELL_EFFECT_LEAP_BACK (id: 138), however in [acore this is limited to only do forward/backwards movement of the caster](https://github.com/azerothcore/azerothcore-wotlk/blob/5dae761a947956775ceea5a87dc39bf420b947e6/src/server/game/Spells/SpellEffects.cpp#L5026). There are only 21 spells that use it effect
pic1: caster can move only forwards or backwards
pic2: Tsunami knockback, player should be knocked back following orientation of caster
There are only 21 spells that use this effect and only I know of 2 that …

fix(Scripts/ObsidianSanctum): add Flame Tsunami knockback

---

src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp

Add missing SAY_DEAD, SAY_LOW_HP (20%) to Akama entry:23191
from TC: https://github.com/TrinityCore/TrinityCore/blob/858477148727b79be51d8c785a12af78c465dbb8/src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp#L405
- Closes 
1. go to Black Temple, clear trash around shade. GM mode kill creature generators
2. Wait for shade to damage akama to 20% for SAY_LOW_HP
3. Wait 0% for SAY_DEATH  …

fix(Scripts/BlackTemple): Akama shade missing says

---

src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerQuest.cpp

The quest XP displayed on the gossip window was not modified for auras that increase quest XP gain (e.g. spell ID 57353). This commit corrects the quest XP display when accepting/returning quests, using the same code as when rewarding the quest XP.
1. Go to a quest giver and note down the XP reward displayed in the gossip menu.
2. Equip at least one heirloom item with the "Experience gained from killing monsters and completing quests increased by 10%." effect (https://www.wowhead.com/wotlk/spell=57353)
3. Close and reopen the quest giver dialog and note the displayed XP reward again. It should …

fix(Core): Correct Quest XP Display when modified by SPELL_AURA_MOD_XP_QUEST_PCT

---

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp

1. fix pet spinning on caster mobs
I discovered what is going wrong when comparing a smartAI caster mob (fallen ranger: 16314) and a non-caster mob (lynx: 16348).
This is because: 
1. smartAI casts with `SMARTCAST_COMBAT_MOVE` and `SPELL_CAST_OK` removes chase movement in
https://github.com/azerothcore/azerothcore-wotlk/blob/90de4bb230c1e0a4900a084439a70d69409696ca/src/server/game/AI/SmartScripts/SmartScript.cpp#L682
this causes the `MutualChase` to be `false` in
https://github.com/azerothcore/azerothcore-wotlk/blob/90de4bb230c1e0a4900a084439a70d69409696ca/src/server/game/Movement/MovementGenerators/TargetedMove …

fix(Core/SmartAI): add prevent almost infinite spinning of mutual target to pets

---

data/sql/updates/pending_db_world/rev_1717787014792496771.sql

- Closes 
https://wowpedia.fandom.com/wiki/Patch_2.1.0  
wowhead https://www.wowhead.com/tbc/guide/raid-consumables-flasks-elixirs-potions-wow-burning-crusade-classic
can no longer apply to Alliance
https://wowpedia.fandom.com/wiki/Warchief%27s_Blessing
Go to Thrall
```
.quest remove  4974
.quest add 4974
.quest  complete  4974
```
Crossroads
```
.tele crossroads
```
- must be 63 or lower
- Horde only …

fix(DB/Kalimdor): limit Warchief's Blessing to level 63 and below and Horde only

---

data/sql/updates/pending_db_world/rev_1717779996280157826.sql

Limits Spirit of Zandalar to players level 63 and below
Adds Text and AI to Zandalarian Emissary in Booty Bay to cast Spirit of Zandalar after 50 seconds upon Heart of Hakkar turn in on Yojamba Island
- Closes 
https://wowpedia.fandom.com/wiki/Patch_2.1.0  
Booty Bay emissary yell 0:18 https://youtu.be/agOCLnzevDs?si=ouFqKBZ73nr9XzCi&t=15 
Yojamba
```
.add 19802
.go c id 14875
```
Booty Bay
```
.go c 436
```
recommended to test with 2 characters or more
1 character to turn in on Yojamba
1 character in Booty Bay
1 or more characters that do not fit level …

fix(DB/StranglethornVale): Spirit of Zandalar limit to 63 and below, apply to Booty Bay

---

data/sql/updates/pending_db_world/tbc-boss-parry-hasting.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/7147
This PR: …

fix(DB/Creature): Add parry hasting exception for a few TBC raid bosses.

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp

- Closes https://github.com/chromiecraft/chromiecraft/issues/7129
swing timer resets on bladestorm cast
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/cb26d34b-6913-4ce0-a2e0-50ee52a96ed7
melee spells such as cleave/heroic strike fail and stops attack
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/c517411d-46dd-4943-98ae-275fea1f3216
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/ba0d0284-ae2e-4721-8d7b-26f358701251
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/a9bfb61e-434d-4ea2-b7 …

fix(Core/Spell): Bladestorm remove reset swing and allow meleeSwingSpell during

---

src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_anubarak.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp

Anub'Arak (id: 34564) was using the RemoveAllAuras method when submerging.
Added correct spell and replace method with spellcast of spell ClearAllDebuffs (id: 34098)
Closes AzerothCore issue #19136
**Testing instructions :**
1. go into Trial of the Crusaders instance
2. get to Anub'Arak boss
3. let him submerge
4. observe for a debuff clear spellcast

fix(CORE/RAID): added correct spell to boss Anub'Arak to clear his debuffs on submerge

---

data/sql/updates/pending_db_world/rev_1719389897107886822.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_baron_geddon.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_magmadar.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_majordomo_executus.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_shazzrah.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/molten_core.cpp

refactor(Scripts/BlackrockMountain): Spell Scripts registry macros

---

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp

-  [X] Scripts (boss scripts).
This PR:
1. Engage Netherspite.
2. Kill him during portal phase and banish phase and during transitions between them.
3. Observe the portal behavior after the dargon dies. …

fix(Scripts/Karazhan): Destroy Netherspite portals on death.

---

src/server/scripts/World/boss_emerald_dragons.cpp

Events happen at 75, 50 or 25 percent health and should not include a 0% event.
Video showing Dot event does not happen at 0% as an example:
https://youtu.be/Wos1qtt280g?si=U6Kif8SeUgVI51lR

Emerald Dragons no longer have 0% health events

---

src/common/Utilities/Util.cpp

Currently, in the Cyrillic version of the server and client, there is an issue with the declension of a name when creating a new character. You can watch the video to see what the problem is:
https://github.com/azerothcore/azerothcore-wotlk/assets/33424304/7117aee2-830c-4fff-9338-1588e8417aad
This PR solves the problem.
I didn't find a similar issue.
I applied them on my server and everything worked fine. The DB table `character_declinedname` was populated with correct declined names.
1. Configure the server locale to be Russian.
2. Run ruRU client.
3. Create a character with a declinable name.
4. Apply declension after the character is being …

fix(core/character-creation): get main part of cyrillic name

---

data/sql/updates/pending_db_world/rev_1718974840446011698.sql
src/server/game/Spells/Spell.cpp

CREATURE_FLAG_EXTRA_OBEYS_TAUNT_DIMINISHING_RETURNS flag (extra_flags) is not set on any creature
When set, DR handling is incorrect. Most taunts have an EFFECT_APPLY_AURA  with SPELL_AURA_MOD_TAUNT as an effect AND a SPELL_EFFECT_ATTACK_ME. Currently, the former is handled by DR but SPELL_EFFECT_ATTACK_ME is still handled. Resulting in no taunt DR when the flag is set.
Some special cases have a 3rd effect:
- death grip: grip mechanic
- mocking blow: damage
sidenote: hand of reckoning only has 2 effects, damage is handled as a special case in taunteffect
changes:
- add …

fix(Core/Spell): implement taunt DR CREATURE_FLAG_EXTRA_OBEYS_TAUNT_DIMINISHING_RETURNS 

---

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp

Doomfire movement behavior was ported from CMaNGOS.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7167
1. Pull Archimonde.
2. Observe Doomfire behavior.
3. Observe Fear timing. …

fix(Scripts/HyjalSummit): Couple Archimonde adjustments.

---

data/sql/updates/pending_db_world/rev_1714139994033487600.sql

When the player has some diseases, the Healer in the Eastern Plaguelands will have a dialog box that can heal the player
I only tried the 3 debuffs in the game and the options show up and there may be more
https://github.com/azerothcore/azerothcore-wotlk/assets/49193927/ee13141e-3593-454f-b72c-759f0424da0a
- Closes 
1. .go c 53897 ro .go c 53898
2. .aura12541 or .aura 3427 or  .aura 16449 …

fix(db/sai) Added healing options for the Silver Dawn Healer in the Eastern Plaguelands

---

data/sql/updates/pending_db_world/rev_1719691851180437100.sql
src/server/scripts/Outland/zone_shattrath_city.cpp

We update once Quest gives AI updates and then once (every 60s) on when 1 or more players are within 30y.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15322
- Closes https://github.com/chromiecraft/chromiecraft/issues/5144
<details>
</details>
.go c id 24854
Compare daily HC/N quest to the 2 images
Edit pool_quest_save in characters DB
```sql 
SELECT * FROM `pool_quest_save` WHERE `pool_id` IN (356,357);
```
Edit them with questIDs from the script (356H, 357N)
Should update displayID (when more than 1 player is within 30y, 60s cd) …

fix(Scripts/Shattrath): Daily Dungeon quests holograms

---

src/server/game/Entities/Pet/Pet.cpp

Pets should scale based on level and scaling range as by their DBC value. I found that this also needs to be scaled with their DisplayID, this part was missing.
This factor was added in PR
- https://github.com/azerothcore/azerothcore-wotlk/pull/14511  but later removed?
Adding it back seemed correct besides that the scaling was not capped to MaxScaling. So pets past the MaxScaleLevel were still scaled larger than they should
-  https://github.com/azerothcore/azerothcore-wotlk/pull/14511#issuecomment-1648169456
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18412
The changes have been validated …

fix(Core/Pets): Correct Pet size for bigger pets 2

---

data/sql/updates/pending_db_world/rev_1720533126868678600.sql

Creatures already had KillCredit for 23450
Also correct [Gordunni Soulreaper's](https://wowgaming.altervista.org/aowow/?npc=23022) "smart" script
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18406
- Closes https://github.com/chromiecraft/chromiecraft/issues/6611
https://youtu.be/P2-OXOH-OIQ?t=83 (even source for that drainlife has castflag 1(was already there))
.quest add 11096
.go c id 22143
kill …

fix(DB/SAI): 'Threat from Above' giving double credit on kill

---

src/server/game/Entities/Pet/Pet.cpp

scaling strategy based on CreatureDisplayInfoEntry->Scale was wrong, oops
- https://github.com/azerothcore/azerothcore-wotlk/pull/18867
I went through tameable mobs from wow-petopia and assessed correctness
https://www.wow-petopia.com/classic_lk/gallery.php?id=available
I found that overriding maxScale to 1.0f in some cases did the job to achieve correctness:
```
pet, assessment, maxScaling
Chimaera, too small, ~0.6
Core Hound, too small, ~0.3
Crab, too big, ~1.3 
Wasp, too small, ~0.5
Nether ray, too small, ~0.5
Wind Serpent, too small, ~0.7
Spider, too small, ~0.6
Warp Stalker, too small, ~0.6
Rhino, too …
```

fix(Core/Pets): Correct Pet size for pets 3

---

data/sql/updates/pending_db_world/rev_1720633619992216684.sql
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Spells/spell_warlock.cpp

* moves Demonic Pact (DP) handling from Unit
* remove spell info correction as flag is already set
* apply DP effect to EFFECT_1 which allows healing power to scale with warlock's SP 
* remove DP effect from DP calculation, this fixes the "stacking with itself"
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3783
2 spells: 53646, 54909
Pets proc 53646, unknown 54909
~~Is 54909 the aura that's supposed to proc Demonic Pact during metamorphosis? (not implemented)~~
~~`Stances: FORM_METAMORPHOSIS`~~
~~pre-3.3 demonic pact does not proc for crits during …

fix(Scripts/Spells): warlock demonic pact

---

data/sql/updates/pending_db_world/rev_1719929004534756216.sql
src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp

air phase increased by 5s to match DBM "time until land"
https://github.com/DeadlyBossMods/DBM-BurningCrusade/blob/main/DBM-Raids-BC/Karazhan/Nightbane.lua
smoke blast:
previous: cast smoke blast trigger to random targets
now: uses the 2 smoke blast spells
1. instant cast smoking blast to random
2. smoking blast cast to highest threat
update fear spellId:
use sniffed fear spell 36922
increases cast time from 1.5s to 2.5s
adjusted fear timing based on DBM
adjust other timings based on WCL, not sure on rescheduling/repeat timers
`Target Charred Earth`  should trigger ground effect, however it is cast directly, …

fix(Scripts/Karazhan): Nightbane Combat Abilities

---

data/sql/updates/pending_db_world/rev_1719253714347835736.sql
src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp
src/server/scripts/Spells/spell_warlock.cpp

there are 2 kinds of seed of corruption spells:
1. player seed of corruption (r1,r2,r3)
2. generic seed of corruption cast by NPCs
differences:
1. player seed procs on creature death
1. player seed detonation threshold scales with spellpower
changes:
1. move seed proc handling from `unit.cpp` to warlock spellscript in `spell_warlock.cpp`
2. npc seed aoe: add LoS target selection
3. player seed: add damage threshold scaling with spellpower
4. player seed: proc damage on death
5. npc seed: deals damage using customspell with bp read from DBC, replaces need for custom spellscript
data detonation threshold with …

fix(Scripts/Spells): warlock seed of corruption

---

data/sql/base/db_world/creature_template_model.sql

fix(DB): Correct collation for c_t_model

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Handlers/CombatHandler.cpp

I've been informed in the Discord server that `uint8` is a `char` masquerading as an unsigned integer and that `uint32` is an actual unsigned integer and that I should have used that instead, as the client handler expects an unsigned integer and not a `char`.
- Closes no open issues.
This PR:
- https://github.com/azerothcore/azerothcore-wotlk/issues/19429 …

fix(Core): Further adjust packet structure for attack stop opcode.

---

src/common/Configuration/Config.cpp
src/common/Configuration/Config.h
src/server/game/Chat/ChatCommands/ChatCommand.h
src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/World/IWorld.h
src/server/game/World/World.cpp
src/server/game/World/World.h
src/server/scripts/Commands/cs_account.cpp
src/server/scripts/Commands/cs_ban.cpp
src/server/scripts/Commands/cs_learn.cpp
src/server/scripts/Commands/cs_wp.cpp
src/test/mocks/WorldMock.h

* Config - Deprecated for 3 years
* ChatCommand - Deprecated for 2 years
* getLevel() - Deprecated for 2 years
* SendGlobalText - Deprecated for 8 years +
- Closes 
1.
2.
3. …

chore(Core/Misc): Remove deprecated code

---

src/server/game/Loot/LootMgr.cpp

Items that start quest currently drop in cases when they should not. This commit improves the checks and conditions that determine whether an item that starts a quest should drop. Specifically items that start quests incorrectly drop when:
- The player already has the item in their inventory and the item is unique
- The player has not finished a prerequisite quest
The changes in this commit capture these conditions to prevent unnecessary or inappropriate item drops.
I tested this using:
https://www.wowhead.com/wotlk/item=13920 …

fix(Core/LootMgr): Improved drop checks for items that start quests

---

src/server/game/Entities/Unit/Unit.cpp

SPELL_ATTR2_IGNORE_LINE_OF_SIGHT is only used for the cast of the spell, not the effect itself.
| ID | Name | 
| ---: | --- | 
| 6940 | Hand of Sacrifice | 
| 9930 | Empathy of Stone | 
| 13903 | Seal of Sacrifice | 
| 25228 | Soul Link | 
| 34788 | Shared Bonds | 
| 36141 | Soulbind | 
| 41247 | Shared Suffering | 
| 41363 | Shared Bonds | 
| 60078 | Vehicle-Turret Shared Health | 
| 60085 | Vehicle-Turret Shared Health | 
| 64205 | Divine Sacrifice | 
- Closes https://github.com/chromiecraft/chromiecraft/issues/6103
https://youtu.be/zUpBrGJEP_s?t=581 …

fix(Core/Unit): Split Damage auras should ignore LOS

---

data/sql/updates/pending_db_world/l70etc-dmf.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16530
This PR: …

fix(DB/Event): Adjustments to BlizzCon L70ETC concert event.

---

src/server/game/Entities/GameObject/GameObject.cpp

- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/16101 …

fix(Core/Entities): Only add use to spell caster objects if cast succeeds.

---

apps/installer/includes/functions.sh

Installer output is wrong for BSD*.
"acore.sh install-deps" says "This platform is not supported" should be "BSD is not supported yet"
- Closes 
Tested on FreeBSD 14.1
1. On FreeBSD 14.1 install "pkg install bash"
2. execute "bash"
3. execute "acore.sh install-deps" …

chore(APPS/installer): Detection of BSD* OS

---

src/server/game/Spells/SpellEffects.cpp

Reverts azerothcore/azerothcore-wotlk#19599.
Closes #19658
Closes https://github.com/chromiecraft/chromiecraft/issues/7284
Opens #19514
Opens https://github.com/azerothcore/azerothcore-wotlk/issues/19514
Unfortunately, there are a *lot* of pet-related checks for whether the owner is a player or not. When the pet is not supposed to be owned by a player (sniffs lead me to strongly believe elementals should be owned by their totems), this causes quite a few problems, as seen in #19658. For now, best course of action in my opinion is to revert the commit until a better solution comes around.

fix(Core/Spells): Revert ownership and follow logic adjustment for guardian summons.

---

src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Spells/Spell.cpp

The check that starts in GridNotifiers.h is used by by all kinds of aoe aura spells that target enemies (persistent ground (consecration), npc aura(totem of wrath)
ground targeted aoe (blizzard) also passes it but the check is not used???
the one in Spell.cpp then is used by spells such as blizzard
- Progress #14367
1.
2.
3.
This only deals with the spells where players easily see a mismatch and get annoyed. Every type of spell should be checked if they should or should not include caster/target object size
Ground targeted aoe goes through two checks …

fix (Core/Spells) remove object size for hit calculation of aoe aura spells that target enemies

---

src/server/game/Entities/Pet/Pet.cpp
src/server/game/Handlers/PetHandler.cpp

When a pet ability was cast, PetHandler reset all CharmInfo flags before calling PetAI methods, setting the attack flag to true every time. This commands the pet to go and chase the target which is not correct when the state is COMMAND_STAY.
PetAI already handles the scenario since #9635, it just wasn't getting the actual pet attack state.
- Closes #14481
- Closes https://github.com/chromiecraft/chromiecraft/issues/4470
1.
2.
3. …

fix(Core/PetHandler): Allow PetAI to handle flags

---

data/sql/updates/pending_db_world/ele-class.sql

fix(DB/Creature): Correct Greater Fire Elemental template values.

---

src/server/game/Spells/Spell.cpp

If a spell is both channeled and has SPELL_ATTR0_COOLDOWN_ON_EVENT attribute (only rituals) is channeled for its full duration, it goes on an infinite cooldown. The client needs to be notified when the ritual ends without being completed.
- Closes #5603 
1.
2.
3. …

fix(Core/Spell) Reset cd on some channeled spells

---

src/server/game/Pools/PoolMgr.cpp

We are currently experiencing an issue with the pool system where a pool may fail to spawn an object when it should. This causes the pool to become inactive until the server is restarted. On servers with long uptimes, this could result in maps without active pools, leading to missing mining and herbalism nodes.
This problem arises in the following scenario:
Consider a pool group with the following objects and spawn chances:
* ObjectA: 75% chance
* ObjectB: 15% chance
* ObjectC: 10% chance
If the last spawned object was ObjectC and the roll results in ObjectC again, the logic here https://github.com/azerothcore/azerothcore-wotlk/blob/83f8871c31fd2b9f374587f921c11b2e00cbf733/src/server/game/Pools/PoolMgr.cpp#L327-L338 results in an empty rolledObjects list. As a consequence, no new objects …

fix(Core/Pool): Fix degradation of pools over time

---

data/sql/updates/pending_db_world/2024_08_25_00.sql

- Closes chromiecraft/chromiecraft#5654 …

fix(DB/Creature): Quest Escape through Force - party completion issue

---

data/sql/updates/pending_db_world/bloodboil-taunt.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/7321
This PR: …

fix(DB/Creature): Add taunt immunity to Gurtogg Bloodboil.

---

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp

* Force AttackStop for all members of the threatlist before the transition event during the last
* Fix some unit flag logics
* Fix the reset logic
* Cleanup a little the script and remove unused enums
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19548 and https://github.com/azerothcore/azerothcore-wotlk/issues/18486 . Partial fix for https://github.com/azerothcore/azerothcore-wotlk/issues/18488
* another test would be welcome. I found it difficult to reproduce the initial outcome. Even if the logic would dictate that it's fixed know. …

fix(Scripts/TempestKeep): revamp Kael'Thas

---

src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp

- Closes unreported issue. Depending on how the fight is reset, the council creature can break and no longer balance health between the council members.
The changes:
1. Engage the Illidari council.
2. Wipe.
3. Reset the fight.
4. Observe the council. …

fix(Scripts/BlackTemple): Ensure Illidari council health is balanced across wipes.

---

src/server/game/Movement/Spline/MoveSplineInit.cpp
src/server/game/Spells/SpellEffects.cpp

Changing only the orientation of a unit also flags it as if it were moving, which causes spells to be interrupted.
Checking if the unit is commanded to be moved to the same coordinates is an easy way to tell if it was an orientation only change. It is a workaround for the movement system but this way it won't require bigger changes.
- Closes #15913
- Closes https://github.com/chromiecraft/chromiecraft/issues/5385
1.
2.
3. …

fix(Core/Movement) Don't move for change in orientation only

---

src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/19809#issuecomment-2323729656
The changes:
- Upon studying of a sniff, it definitely appears a council member with effectively no health remaining should still be relaying full damage through the Shared Rule spell. This fix definitely seems more Blizzlike than current behavior. …

fix(Scripts/BlackTemple): Adjust order of damage calculations for Shared Rule.

---

src/server/game/Handlers/GroupHandler.cpp

fix(Core/Handlers): Don't allow data to be sent while not grouped.

---

src/server/game/Handlers/MovementHandler.cpp

fix(Core/Handlers): Only remove emote if player is moving.

---

src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
src/server/game/Battlegrounds/Zones/BattlegroundAV.h

1. Log into game and .debug bg.
2. Check spawns on the Towers and Archers AI. …

fix(Scripts/Battlegrounds/AlteracValley): Adding missing Tower Archers

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/PlayerStorage.cpp

1. When a character wields a MH and OH and has full bags, equipping a staff or polearm will no longer force equip said 2Her and send the offhand in the mail
2. Titan's Grip no longer allows held in off-hand items to be equipped with 2H staff or polearm. This now results in a `Cannot equip that with a two-handed weapon.` error
3. Titan's Grip no longer allows Fishing Pole MH + non-staff or non-polearm 2H as OH
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3779
Test regressions, dual spec, dual wield, titan's grip 
dual-wielding with a …

fix(Core/PlayerStorage): Equip OH, 2H, Titan's Grip weapon swapping 

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Spell.cpp

Reverts #19819, closes #19960. I've tried a few things to fix this issue, but none of them seem to have stuck yet. Since this is a relatively small issue, I figure it's better to revert it and find a solution later then keep it around for people to crash with it.
For those curious, the crash (as I understand it) seems to be caused with spells such as mage's Ignite and warrior's Deep Wounds due at least in part to how the munching mechanic is implemented. The issue is `aurEff` is being dereferenced after being supplied in the munching `CastCustomSpell` but [it turns out to be null by the time it gets dereferenced](https://www.youtube.com/watch?v=bLHL75H_VEM).
P.S. I have a feeling this is the issue UltraNix caused with https://github.com/azerothcore/azerothcore-wotlk/commit/96fa9c5c7b7274ba …

fix(Core/Spells): Revert triggered spell logic change.

---

src/server/game/Groups/Group.cpp

PR https://github.com/azerothcore/azerothcore-wotlk/pull/19272 broke  some loot. 
As example , if you heave item "Sliver of Pure Ice" from norlam ICC (https://www.wowhead.com/wotlk/item=50339/) you cant loot "Sliver of Pure Ice" from heroic ICC https://www.wowhead.com/wotlk/item=50346 . So this PR fix that. We no need to check `player->CanEquipUniqueItem(proto) != EQUIP_ERR_OK`.
PR https://github.com/azerothcore/azerothcore-wotlk/pull/19272 was Cherry-Pick from TC , but in last code in TC we see that `player->CanEquipUniqueItem(proto) != EQUIP_ERR_OK` not used 
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Groups/Group.cpp
- …

fix(Core/Loot)  fix bug with loot

---

data/sql/updates/pending_db_world/2024_09_11_00.sql
data/sql/updates/pending_db_world/2024_09_13_00.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19876
- Closes https://github.com/chromiecraft/chromiecraft/issues/7334
Actually, the bug is a bit different from how it was described in this ticket. The first spawned Assassin only casts Paralyzing Poison and Vanish abilities (and doesn't cast Riposte). The other 3 spawns don't cast anything, they only perform melee attacks.
So in the bugfix, I didn't modify the existing spells, but I added new row for Riposte. As for the timers, I checked the logs here: [link](https://classic.warcraftlogs.com/zone/reports?zone=1011). It seems that the first …

Fix(db/creature) black temple   illidari assassin riposte ability missing

---

src/server/game/Entities/Object/Object.cpp

There's a bug with [Traveler's Tundra Mammoth](https://wowgaming.altervista.org/aowow/?spell=61447) that occurs when mounting on a transport, the vendors are not interactable.
This bug does not occur if mounting before and then moving onto a transport.
Mounting and boarding a transport does not add the vehicle's passengers to the transport. So when summoning on the transport, there shouldn't be a need to add them to the transport.
after mounting on a transport this check fails on when interacting:
https://github.com/azerothcore/azerothcore-wotlk/blob/632d7f5f9ec1b44c3288168952a68533a6791686/src/server/game/Handl …

fix(Core/Object): do not add Object to Transport when summoned by a Vehicle

---

data/sql/updates/pending_db_world/debug-cooldown.sql
src/server/scripts/Commands/cs_debug.cpp

-  [X] Core (Commands).
-  [X] Database (Commands). …

feat(Core/Commands): Add debug command for applying a spell cooldown.

---

data/sql/updates/pending_db_world/rev_1719113163679056400.sql

Fixes quest turn-in dialogue not respecting character gender and always using Lady instead of Lady/Lord which reflects an oversight in the original dialogue that does not exist on live servers
Tested in-game on Windows and verified to build without errors. Dialogue was viewed as both a male and a female to verify functionality and quest was completed without issue with correct dialogue as shown below in images. No other issues caused by this change.
1. .additem 21221
2. Clear AQ40 and proceed to Caelestrasz
3. Verify that on turning in the quest your …

fix(DB/quest_offer_reward): C'Thun's Legacy turnin dialogue

---

data/sql/updates/pending_db_world/starstearlament.sql

- set Star's lament to 5 buycount
- set Star's tear to 20 buycount
- Progress https://github.com/chromiecraft/chromiecraft/issues/5978
NOTE: This is practically just a copy paste of https://github.com/azerothcore/azerothcore-wotlk/pull/16862.
It remains an issue for casters on Chromiecraft as they "need" this item for arena participation.
WoWhead entry https://www.wowhead.com/wotlk/item=32453/stars-tears#sold-by as described in the original issue.
- Tested (Trivial change) …

fix(DB/Item): Buycount adjustment for Star's Lament and Star's Tear

---

data/sql/updates/pending_db_world/rev_1726786940038269786.sql
src/server/game/Movement/MotionMaster.cpp
src/server/game/Movement/MotionMaster.h
src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp

1. refactor, handle script_effect of final Kael'thas explode ( 36092 - Kael Explodes) with script that [adds sounds (cp from cmangos)](https://github.com/cmangos/mangos-wotlk/blame/fe732710aed998e5a6a53f8edc3573d8d4a3f706/src/game/AI/ScriptDevAI/scripts/outland/tempest_keep/the_eye/boss_kaelthas.cpp#L1456C11-L1456C11), stunned unused
2. Kael no longer becomes unselectable after reaching 50% hp threshold. At 50% he stops attacking and once he reaches home, he becomes unselectable and removes attackers
3. Add `skipAnimation` arg to MoveTakeoff. This prevented setting a drowned state after the spline movement …

fix(Scripts/TheEye): Kael'thas p5 transition, flight, MotionMaster:MoveTakeoff

---

data/sql/updates/pending_db_world/rev_1726975868981293914.sql
src/server/game/AI/CoreAI/UnitAI.cpp
src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/CreatureData.h
src/server/game/Entities/Creature/enuminfo_CreatureData.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerUpdates.cpp
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Spell.cpp

dual wield:
current dual wield logic relies on `Unit::haveOffhandWeapon()` which requires  `m_canDualWield` to be set. New dual wield logic for creatures is based on cmangos' implementation. player DW remains unchanged. I did not remove `Unit::haveOffhandWeapon()` as it is still used on some scripts
creatures can now dual wield if: has non-disarmed weapon in offhand OR `m_canDualWield` is set. `m_canDualWield` is set by `SetCanDualWield` through script or `SPELL_EFFECT_DUAL_WIELD`, `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK`
https://github.com/azerothcore/azerothcore-wotlk/blob/bb0d292e1c2bb5619fbc3105e7cd919b45268 …

fix(Core/Unit): fix Dual Wield for more creatures, CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK, creature disarm damage

---

src/server/game/Battlegrounds/Battleground.h
src/server/game/Battlegrounds/BattlegroundQueue.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Handlers/BattleGroundHandler.cpp
src/server/game/Server/WorldSession.cpp

… into new-BattlegroundDesertionTypes
original author @laasker
Add more desertion type values to distinguish them Battleground desertion vs Arena desertion
No issues
Laasker did some tests using 3v3soloQ module
A successful build should be enough.
The web app "[BG queue abuser viewer](https://github.com/Helias/BG-Queue-Abuser-Viewer)" could be moved under azerothcore organization and it should be updated with these new types, but it's not blocking for this PR  …

new BattlegroundDesertionTypes for hook OnBattlegroundDesertion

---

data/sql/updates/pending_db_world/rev_1727429234467651703.sql

fixup of
- https://github.com/azerothcore/azerothcore-wotlk/pull/20015
removes CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK from the following creatures with - reason:
Boahn - uses 2h
Porfus the Gem Gorger - basilisk
Illidari Slayer - uses 2h
Dragonmaw Wrangler - shield OH
Lava Reaver - elemental
Torloth the Magnificent - uses 2h
Leoroxx - uses 2h
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/20051 
Karsius The Ancient Watcher - uses 2her as a 1her
https://www.youtube.com/watch?v=ZbDKfjHlerg
test query to spawn all creatures somewhere …

(DB/Creatures): fixup Dual Wield for creatures, remove some CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK

---

src/server/game/Battlegrounds/Battleground.cpp

no longer remove shapeshift auras like warrior stances, shadow form and druid shifts when leaving a battleground or arena
only remove spirit of redemption is removed
for details, see my explanation https://github.com/azerothcore/azerothcore-wotlk/issues/20024#issuecomment-2380430923
no changes are made to leaving/completing RDF as I can't reproduce it
- Closes? https://github.com/azerothcore/azerothcore-wotlk/issues/20024
example wrath classic not removing shadowform on bg exit
https://www.youtube.com/live/uILuK4__p_s?si=b3DGMVqxia9ArcDS&t=1948
1. arena …

fix(Core/Battlefield): shapeshift aura removal from players on leaving arena or battleground

---

src/server/game/Entities/Unit/Unit.cpp

There is a critical exploit at the moment. When you are dead and have previously equipped an item with [this](https://www.wowhead.com/wotlk/spell=62158/rune-of-the-stoneskin-gargoyle) enchantment (and possibly some others), if you attempt to replace it with another item while dead (it will throw an error, but this can be ignored), upon resurrection, you will have multiple enchantment auras - equal to the number of times you tried to equip the item. As a result, you can turn your character into a raid boss.
Here is the video that demonstrates that - https://youtu.be/1FtL7aiU7Mc.
Honestly, I'm not very familiar with the spell system and don't know exactly how everything works, but with every attempt to equip a new item, we are adding an aura to m_ownedAuras, which is eventually added to …

fix(Core/Items): Fix exploit where multiple auras could be applied from a single enchantment.

---

data/sql/updates/pending_db_world/shattrath-flasks.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19786
- Likely closes https://github.com/azerothcore/azerothcore-wotlk/issues/16360
- Closes https://github.com/chromiecraft/chromiecraft/issues/7381
- Closes https://github.com/chromiecraft/chromiecraft/issues/6482 …

fix(DB/Spell): Link triggered Shattrath flask effects to flask aura and proper area.

---

src/server/game/Combat/ThreatMgr.cpp
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

hopefully this fixes side-effects and crashes due to poor setting of unit's death state
see title+source
- Closes CC https://github.com/chromiecraft/chromiecraft/issues/7389
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19468
note the comment left in https://github.com/TrinityCore/TrinityCore/commit/91ebea4a77e1db10cea85ff8e891a2ea3f3587ab
comment is present in acore but deathstate it still set at the end 
https://github.com/azerothcore/azerothcore-wotlk/blob/67c746be7d166924011a98b5e74d666ba931b7e1/src/server/game/Entities/Unit/Unit.cpp#L14511
This PR …

fix(Core/Unit): update death state before handling RemoveAllAurasOnDeath()

---

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20129
- Closes https://github.com/chromiecraft/chromiecraft/issues/7396#issue-2565901451
1..tele bt
2. .go creature id 22917
3. going to fase 2 (under 65% hp)
4. place the flames of azzinoth on the warglaives launched by illidan. obviously you need 2 characters to do this. …

fix(Scripts/BlackTemple): exclude off tank of the Azzinoth Flame's charge

---

src/server/game/Entities/Unit/CharmInfo.cpp

- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/20149 …

fix(Core/CharmInfo): Add exception for Kil'jaeden dragon charm spells.

---

src/server/game/Spells/Spell.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20050 …

fix(Core/Spell): Include damaging spells for starting combat.

---

src/server/game/Entities/Unit/Unit.cpp

1. add rage gain limit to rage gain formula. see blizz post and line `addRage = std::min(addRage, rageFromDamageDealt * 2.0f);`
2. add rage gain when an attack is fully blocked, dodged or parried
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8867
- Closes https://github.com/chromiecraft/chromiecraft/issues/7098
Formulae [sic] from wiki which cites blizz post https://wowwiki-archive.fandom.com/wiki/Rage#Formulae
cited source from wiki linked in issue 
https://web.archive.org/web/20090604123729/http://forums.worldofwarcraft.com/thread.html?topicId=1736776 …

fix(Core/Unit):  add rage gain when attack is fully blocked, dodged or parried

---

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp

fix(Scripts/BlackTemple): Adjust caster of Blaze spell.

---

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp

fix(Scripts/BlackTemple): Add resets for enrage events with death.

---

data/sql/updates/pending_db_world/najentus-spine-removal.sql
src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20168
- Closes https://github.com/chromiecraft/chromiecraft/issues/7407 …

fix(Scripts/BlackTemple): Remove Naj'entus Spines from players on engage.

---

src/server/game/Spells/SpellInfoCorrections.cpp

Siphon Life's heal is done by a triggered custom cast with full mask (`true`) which should include the disallow proc events flag and no procs should happen. Yet the cast is proccing `0x4000` events. I'm not sure if there's a better way to fix this in the core, but setting the attr `SPELL_ATTR3_SUPRESS_CASTER_PROCS` fixes the issue 
https://github.com/azerothcore/azerothcore-wotlk/blob/eebb5596bf9ae8486e5cab51e4d28048a076d858/src/server/scripts/Spells/spell_warlock.cpp#L886
https://github.com/azerothcore/azerothcore-wotlk/blob/2a48a14908e590ad3a6730f14c80573c9571685d/src/server/game/Spells/SpellDefines.h#L145
- …

fix(Core/Spells):  supress caster procs for Siphon Life heal

---

apps/ci/ci-pending-sql.sh

-  [x] CI
Today, we ran into an issue where a pending SQL file had a space in the name. This was an issue because the previous script didn't wrap all process substitutions (`$(...)`) and variable references in double quotes, meaning.
This PR fixes this through making the script shorter and by adhering to safe shell scripting practices, using [shellcheck](https://github.com/koalaman/shellcheck) as a guide. Additionally, this PR adds comments to it's a bit more clear as to what is going on in the shell script
- no specific issue
1. Make a new pending sql …

fix(CI): simplify ci-pending-sql.sh and make it safer

---

src/server/game/Entities/Unit/Unit.cpp

Reverts azerothcore/azerothcore-wotlk#20032
Causes issues with warrior instances. Cant think of a solution to this atm.

Revert "fix(Core/Spells): SPELL_ATTR1_IMMUNITY_PURGES_EFFECT should not remov…"

---

src/server/game/AI/SmartScripts/SmartScript.cpp

The quest SteamTank Surprise has a SmartAI entry in the db that causes the tank to cast the kill credit spell on the player when they successfully destroy a plague wagon. Currently, this spell cast is being blocked by the rooted check handler for SMART_ACTION_CAST. The change proposes that this rooted check should not apply to vehicles.
Closes AzerothCore issue #20237
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20237
1. .quest add 12326
2. Jump in steamtank near NPC Duke August Foehammer
3. Ride to a plague wagon
4. Deploy the gnome …

fix(Core/SAI): rooted check blocks vehicles from casting quest credit

---

src/server/game/Entities/Player/Player.cpp

- Closes none.- Idk how or why this is not causing some other issues tbh.
Myself. I was creating a module I had in mind and noticed the hook OnBattlegroundRemovePlayerAtLeave was executed twice when a player left a bg. I put a breakpoint on the code and these are the two call stacks:
1. The wrong one. 
2. The good one.
Basically this method shouldn't be called by Player::LeaveBattleground and should be called by BattlegroundMap.
1. Use some module that uses BGScript::OnBattlegroundRemovePlayerAtLeave hook and log something, you should see it twice.
2. Make sure it doesn't break anything else.

fix(Core/BG): Fix double method call on removing a player

---

data/sql/updates/pending_db_world/rev_1730310110375137038.sql
src/server/scripts/Events/hallows_end.cpp

fixes horsemen falling out of the sky during his intro by setting his movement flags manually
- Closes 
https://github.com/user-attachments/assets/340e4944-6d0f-47f2-801d-f67ecd690519
https://github.com/user-attachments/assets/dca143bd-1cbd-4b3e-beb3-f17f64eec144
observe location 
```
.go xyz 1807.7548 1354.82 19.33 189 3.2035
```
1. .go ga id 186267
2. observe flight …

fix(Scripts/Events): Hallow's End Headless Horsemen fly intro

---

src/server/scripts/Kalimdor/zone_tanaris.cpp

Cast the reward quest spell on each group members if within group reward range
I opted to use the reward quest spell on each group member over `GroupEventHappens` because a reward spell exists. 
`void Spell::EffectQuestComplete(SpellEffIndex effIndex)`
`void Player::GroupEventHappens(uint32 questId, WorldObject const* pEventObject)`
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/19591
- Closes https://github.com/chromiecraft/chromiecraft/issues/6225
diff to "complete" escort after 10 seconds instead of 9 minutes
```
diff --git …
```

fix(Scripts/Kalimdor): Cavern of Time custodian escort quest group completion

---

data/sql/updates/pending_db_world/gameobject_142122_add_quest_starters.sql

I added the records so that these quests can be initiated from both wanted posters.
GameObject
https://www.wowhead.com/wotlk/object=142122/wanted-poster
Quests:
https://www.wowhead.com/wotlk/quest=2781/wanted-caliph-scorpidsting https://www.wowhead.com/wotlk/quest=2875/wanted-andre-firebeard

fix(DB/gameobject_queststarter): Added queststarter records for GameObject 142122

---

src/server/game/Entities/Unit/Unit.cpp

- Closes https://github.com/chromiecraft/chromiecraft/issues/7444
The changes: …

fix(Core/Unit): Only allow Judgement of Light/Wisdom to proc for targets friendly to caster.

---

data/sql/updates/pending_db_world/shattered-sun-transform-serversides.sql

- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/10795
The changes: …

fix(DB/Spell): Add spell effect data for Shattered Sun transform auras.

---

src/server/scripts/Northrend/zone_borean_tundra.cpp

- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/19591
tested with diff to not wait for the entire escort
```
diff --git a/src/server/scripts/Northrend/zone_borean_tundra.cpp b/src/server/scripts/Northrend/zone_borean_tundra.cpp
index dcc760e74e..ae004939c2 100644
--- a/src/server/scripts/Northrend/zone_borean_tundra.cpp
+++ b/src/server/scripts/Northrend/zone_borean_tundra.cpp
@@ -403,3 +403,3 @@ public:
{
-                        case 1:
+                        case 6:
if (Player* player = GetPlayerForEscort())
@@ -431,3 +431,3 @@ …
```

fix(Scripts/BoreanTundra): make Escape from the Winterfin Caverns group completable

---

src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp

Haven't done so before to prevent obfuscation
- Closes 
1.
2.
3. …

chore(Scripts/ZulAman): Update Akilzon to new register method

---

src/server/game/Chat/ChatCommands/ChatCommand.cpp
src/server/game/Scripting/ScriptDefines/AllCommandScript.cpp
src/server/game/Scripting/ScriptDefines/AllCommandScript.h
src/server/game/Scripting/ScriptMgr.h

feat(Core): Add hook during command security evaluation.

---

src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerQuest.cpp
src/server/game/Spells/SpellEffects.cpp

cherry-pick https://github.com/TrinityCore/TrinityCore/commit/6d62f852acf3e1a3ee57cde2442832280aee814
> Prevents people from ending up with strange quests in their quest logs.
- Closes 
deprecated quest shows up in quest log
```
.quest add 11523
.add 34338 4
.go ga id 187080
```
1. use quest item on crystal
2. relog
3. observe deprecated quest is no longer added …

fix(Core/Spell): EffectQuestComplete, set quest to rewarded instead of complete

---

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20571
- Closes https://github.com/chromiecraft/chromiecraft/issues/6755
1.
2.
3. …

fix(Scripts/TheEye): Fix Al'ar berserk timer

---

src/server/game/Spells/SpellInfo.cpp

make it so spells like Avenger's Sield, felguard Cleave, Hammer of the Righteous, Shield of the Righteous can target pets
list of spells with `SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS` https://gist.github.com/sogladev/884ff3f54319212beadbca118d20974c
`CanFreeMove()` checks `GetOwnerGUID` which causes pets to show as invalid targets even if they are not CC'd https://github.com/azerothcore/azerothcore-wotlk/blob/f6de601ddd5218290268268ee695c56d88847225/src/server/game/Entities/Unit/Unit.h#L941
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17015
The changes have been validated …

fix(Core/Spells): implicit target selection for chain spells that should ignore crowd controlled targets

---

data/sql/updates/pending_db_world/rev_1731773696314015000.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/7506
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20594
- `.go xyz -3215.17 -3649.05 52.9613 1 4.08407` for 18622
and
- `.go xyz -2572.63 -3742.22 31.0639 1 2.47837` for 7887

fix(DB/Creature) - Darkfang Venomspitter under the map

---

data/sql/updates/pending_db_world/rev_1731668322577028300.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20577 
- Closes https://github.com/chromiecraft/chromiecraft/issues/7503
- Make an alliance character
- `.level 30`
- `.go creature id 4794`
- Talk to `Morgan Stern`, now you're able to start the Quest `Mudrock Soup and Bugs` without the previous quest.

fix(DB/Quest): Morgan Stern [1260] not required for 1204

---

data/sql/updates/pending_db_world/silt_crawler_zspawn.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/7510
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20601
1.
2.
3. …

Fix(DB/Spawn) Silt Crawlers under the landscape.

---

src/server/game/Entities/Creature/Creature.cpp

`Creature::Respawn()` calls `AI->Reset()` before resetting `m_respawnedTime`. 
- https://github.com/azerothcore/azerothcore-wotlk/blob/b96acc57fb1f83e4fa44020ab62d21dee7ee53aa/src/server/game/Entities/Creature/Creature.cpp#L2117
In the case of Archimonde respawning: `AI->Reset(), SetVisible(), CreatureUnitRelocationWorker(), CanCreatureAttack()`  
The pet is valid to attack in this check and Archimonde attacks the pet 
- https://github.com/azerothcore/azerothcore-wotlk/blob/b96acc57fb1f83e4fa44020ab62d21dee7ee53aa/src/server/game/Entities/Creature/Creature.cpp#L2646
TC335 for reference: …

fix(Core/Creature): Set RespawnTime before AI Reset

---

src/server/game/Combat/ThreatMgr.cpp
src/server/game/Misc/GameGraveyard.cpp
src/server/game/Movement/Spline/MoveSplineInitArgs.h
src/server/game/Server/WorldSocket.cpp

Details :
1. HostileReference contains two methods creating "event" but one of tree variable of ThreatRefStatusChangeEvent is not initialize
2. Fix GraveYard ID initilization and micro-optimization by moving data instead copy them.
3. In WorldSocket::ReadDataHandlerResult WorldSocket::ReadDataHandler(), we move packet into a new variable "packetToQueue" but it's recall one time later. Fix the logic by calling packetToQueue instead.
- Closes 
1.
4.
5. …

refactor(Core): fix few static analysis

---

src/server/game/Entities/Player/Player.cpp

Fix level up while dead via check if player is dead while level up and update health/mana/rage/energy/foucus... only if player is not dead.
- add check for updating health/mana/rage/energy/focus/... stats that are supposed to be changed on level up
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16516
I use fedora system for running AzerothCore with enGB wotlk client. My character was killed by 12 lvl mob. Then I used level up gm command and my character was still dead, but gained everything else - talents, hitpoints, intelect, etc.
1. create 2 characters on same faction
2. …

fix(Core/Players): don't set full heath/mana/rage while Dead

---

src/tools/map_extractor/System.cpp

The client can support up to 10 patch files (such as patch-enUS.MPQ through patch-enUS-9.MPQ).  This change is needed if MapExtractor is to recognize all 10.
-  [X] Extractor (MapExtractor) 
Fixes an issue where the mapextractor will not read/extract from any patch files beyond patch-4.  This change will allow it to extract from all (which goes up to *-9.mpq). 
I ran into issues locally when extracting map data inside "patch-enUS-5.MPQ" (it stopped at patch-4, with the needed map data being in patch-5).
This has been tested by the change author.  Maps were successfully exported with the mapextractor.exe following this change.
Create (or rename existing to) a /Data/[localization]/patch-[localization]-5.MPQ file, then run mapextractor
No known issues.  It's an extremely simple change.

fix(Tools/MapExtractor) Update MPQ patch iterator to also load patch files 4 through 9

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

CC Auras which use their amount to drop are using 10% of the target's hp as a threshold. Propose to use an amount that scales with caster's level instead based on cmangos' implementation
new values for these levels:
lvl80 2650
lvl70 1890
I left the 10% line in case caster is null?
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/18787
per wiki 
> Fear effects have a damage limit, which appears to be based on level. Once the target takes a certain amount of damage, the fear effect will be broken, regardless of any remaining duration. …

fix(Core/SpellAuraEffects): use caster's level to scale amount to break crowd control auras

---

data/sql/updates/pending_db_world/rev_1725926206241976759.sql
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp

Currently, a players can mount a vehicle in TOC5 without having the Argent Lance equipped. The creature AI will remove the player after mounting if no Argent Lance is equipped. 
changes:
refactor `npc_toc5_player_vehicle`, use vehicleAI, it checks conditions in updateAI
add a comment to vehicle conditions in DB
check aura and send custom spell error when trying to mount without lance equipped like generic spell to mount argent tournament mounts
https://github.com/azerothcore/azerothcore-wotlk/blob/cbd74ae66365923ecaf5b493c8f9011912a5a46c/src/server/scripts/Spells/spell_generic.cpp#L3295
vehicle ids: 35644, …

fix(Scripts/TrialOfChampion): fail and send custom spell error when trying to mount without lance equipped

---

src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerStorage.cpp

- Closes #20193
[Sound](https://www.wowhead.com/sound=847/igquestfailed)
1. Fill up your inventory with items
2. .quest add 1060
3. Hear the sound of failure …

feat(Core/Player)Add quest failure sound when inventory is full or quest failed

---

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp

change timer p2 (weapons) to p3 (resurect): from 3min to 105s (1:45)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20877
TBC DBM https://github.com/DeadlyBossMods/DBM-BurningCrusade/blob/36d51585a8d5764150d355a29c29673cbaf1eaca/DBM-Raids-BC/TheEye/KaelThas.lua#L242
pre-nerf, post-nerf comparison
https://www.youtube.com/watch?v=CLCHgDFIQUg
```
prenerf
3:58 p2 text
5:33 (+95s) p3 text
5:43 (+105s) advisors
postnerf
2:28 p2 text
4:03 (+95s) p3 text
4:13 (+105s) advisors
```
1. `.go c id 19622`
2. kill advisors 1 by 1 or cheat with …

fix(Scripts/TheEye): Kaelthas reduce time until all advisors phase

---

src/server/game/Entities/Player/PlayerUpdates.cpp

should be category
- issue described in https://github.com/azerothcore/azerothcore-wotlk/pull/20797#issuecomment-2542545182
1.
2.
3. …

fix(Core/Player): SpellQueue fix typo StartRecoveryCategory

---

data/sql/updates/pending_db_world/Scarlet_Land_Cannons.sql

This PR proposes to change Flight and Rooted values and gives the possibility to the Scarlet Lands Cannons to cast Cannonball when they are in combat.
Flight and Rooted values has been sniffed from Cata Classic Live.
- Closes No report. I discovered this bug by chance and I decided to fix it.
1. Load the fix
2. Go to the Scarlet Land Cannons (DK Starting Area - Phase 1)
3. …

fix(DB/Creature) Scarlet Land Cannons

---

src/tools/vmap4_extractor/wmo.cpp

Add detection of vertices attached to triangles that map to collision-only material IDs (0xff).
-  [x] Tools (vmap4_extractor)
Since the extractor doesn't use MOBR to determine collision-eligible faces, it can miss faces inside WMO groups that contain collision only without render batches.  
- _Note 1: This is not the case for any blizzard provided WMOs (through WOTLK) so this has **no impact** to blizz content, only custom content.  Verification below_
This 0xff material ID association has been identified ([wowdev.wiki MOPY detail](https://wowdev.wiki/WMO#MOPY_chunk)).
This PR has been tested as follows:
- To verify no regression impact: You can run the extractor and compare the outputs.  If you use WinMerge, the report should look like above.
- To verify …

feat(tools/vmap4_extractor) Add detection of collision-only material IDs

---

apps/codestyle/codestyle.py
src/server/game/Battlegrounds/BattlegroundQueue.cpp
src/server/game/Handlers/MovementHandler.cpp
src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp

feat(CI/Codestyle): check for curly brackets before/after if/else statements

---

apps/codestyle/codestyle.py
src/cmake/macros/FindMySQL.cmake

feat(CI/Codestyle): Check for tabs

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp
src/server/scripts/Kalimdor/zone_desolace.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp
src/server/scripts/Northrend/Nexus/Oculus/boss_eregos.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
src/server/scripts/Northrend/zone_dalaran.cpp
src/server/scripts/Northrend/zone_icecrown.cpp
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
src/server/scripts/Spells/spell_dk.cpp
src/server/scripts/Spells/spell_paladin.cpp
src/server/scripts/World/achievement_scripts.cpp
src/server/scripts/World/boss_emerald_dragons.cpp
src/server/scripts/World/npc_stave_of_ancients.cpp

- Closes 
```cpp
static bool HandleDebugDummyCommand(ChatHandler* handler)
{
Player* player = handler->getSelectedPlayerOrSelf();
if (player->HasAuras(false, 70879, 70877, 70867))
handler->PSendSysMessage("Matched any spell for player {}", player->GetName());
if (player->HasAuras(true, 70879, 70877, 70867))
handler->PSendSysMessage("Matched all auras in the list for player {}", player->GetName());
return true;
}
```
1.
2.
3. …

feat(Unit/Misc): HasAnyAuras() HasAllAuras() HasAuras()

---

src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp
src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp

All chess pieces now properly return to their default positions after a reset. Before this fix, the pieces you started a dialog with would lose their default positions and use their current positions instead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16077
1. .tele kara
2. Go to chess and start event
3. Control the king and cancel
4. Go to any horde piece that is not in its default position and start a dialog
5. Reset the event …

fix(Scripts/Karazhan): Chess pieces reset to correct positions

---

data/sql/updates/pending_db_world/rev_1735425042597130000.sql
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15824
- [ X] Tested in-game by the author.
1. go Pit of Saron
2. go to Scourgelord Tyrannus start combat and die …

fix(DB/Scripts): Reset Scourgelord Tyrannus encounter state

---

src/server/game/Spells/SpellInfoCorrections.cpp

Remove level scaling for Booming Voice (40080). The ingame tooltip will still show 238% for a lvl 71 mob, but the actual speed is only increased by 25%
DBC data of ID - 40080 Booming Voice shows Level scaling. 
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 25 + Level * 3.00
Targets (22, 30) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ALLY)
Aura Id 193 (SPELL_AURA_MELEE_SLOW), value = 25, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 9) 20.00
```
- Closes https://github.com/chromiecraft/chromiecraft/issues/7619
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21005
The changes have …

fix(Core/Spells): Remove level scaling from Booming Voice

---

data/sql/updates/pending_db_world/rev_1736079931234163195.sql

Amani'shi Warbringer HEALTH_PCT  with `event_param1 = event_param2`. If the mob is not exactly 30% at the time of check, it skips the dismount. Also the bear doesn't despawn on evade.
This fixes both issues
- Closes 
`.go c id 23580`
```
.damage 1000
.damage 60000
```
1. damage slowly and instantly below 30% threshold
2. should trigger bear summon + frenzy
3. bear summon should despawn after combat …

fix(DB/SmartAI): more consistent bear summon, despawn bear on reset

---

data/sql/updates/pending_db_world/rev_1735381972383875988.sql

The Teleporter Runes are used to reach/leave Haleh in Winterspring
You should be able to reach Haleh in these ways to complete 3 quests (6501, 6502, 5160):
- 2 times Drakefire amulet (Onyxia Chain) quest: Dragon's Eye and subsequent Drakefire amulet quest
- Awbee's Scale
conditions:
1. Item check: This blocks Drakefire Amulet check. flavor text of Awbee's Scale mentions a requirement, but no mention for Drakefire Amulet.
2. Player check: faction (35) handles player check. Pets aren't teleported
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17855
This …

fix(DB/Conditions): remove conditions for Rune of Mazthoril

---

src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp

Halion's reset now works correctly under all tested conditions.
Prevents encounter exploits from players using Feign Death to bypass the reset.
-  [x ] Scripts (bosses, spell scripts, creature scripts).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3359
- [x ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x ] Tested in-game by the author.
This update fixes an issue with Halion's behavior during the encounter reset logic. The issue occurred when players used the Feign …

fix(Scripts/Halion): Halion freeze against "Feign Death" hunters

---

src/common/Threading/PCQueue.h
src/server/game/Maps/MapUpdater.cpp
src/server/game/Maps/MapUpdater.h

Modernize/Improve thread safety, performance, and maintainability of the MapUpdater class
**1. Atomic Operations for Thread Safety**
The refactored MapUpdater class now uses atomic operations (fetch_add and fetch_sub) for managing the pending_requests counter. This improves thread safety without the need for locking in certain cases, reducing contention and improving performance.
Improvement: This change ensures that the modification of pending_requests can be done in a lock-free manner, which enhances concurrency and reduces the risk of race conditions.
**2. Use of std::memory_order_acquire / memory_order_release in Atomic Operations**
In the refactored code, atomic operations are performed with the std::memory_order_acquire / memory_order_release flag, which ensures proper …

fix(Core/Threading): Modernize/Improve thread safety, performance, and maintainability of the MapUpdater class

---

src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp

The number of targets increases linearly, adding 1 target every 10 ticks.
There is always at least 1 target, regardless of the number of ticks.
-  [x ] Scripts (bosses, spell scripts, creature scripts).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21082
- [x ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x ] Tested in-game by the author.
The calculation is continuous and smooth, ensuring a progressive growth in the number of targets.
- [x ] This pull request can be …

fix(Scripts/SunwellPlateau): Muru - Changed the amount of Tick Negative Energy Periodic

---

src/server/game/Entities/Player/PlayerUpdates.cpp

if there's an invalid spell in the queue, clear the queue and return
- Closes 
1.
2.
3. …

fix(Player/SpellQueue): bandaid crashfix

---

src/server/game/Instances/InstanceScript.h
src/server/game/Maps/Map.cpp
src/server/game/Scripting/ScriptDefines/AllMapScript.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp
src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/instance_forge_of_souls.cpp
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/instance_pit_of_saron.cpp
src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
src/server/scripts/Northrend/Nexus/Nexus/instance_nexus.cpp
src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp

- Closes #21116
- Closes #15872
- Closes #10672
[mod-cfpve](https://github.com/pangolp/mod-cfpve) not needed anymore
1. Join two separate factions in ICC, Instance should get group leader faction instead of first to enter faction
2. Both characters will be able to interact with current instance faction
3. Leave instance, disband group, characters will return to original faction and they can attack eachother
- [Code Refactor self assigned by @Nyeriah]
- [Changing leader and switching raid difficulty will change instance faction based on the new leader …

fix(Core/Group) CF Faction Assign & Leader Instance Faction

---

data/sql/updates/pending_db_world/rev_1736879270259477703.sql
src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
src/server/scripts/Spells/spell_generic.cpp

Apply the same handling as [Sindragosa's Unchained Magic](https://wowgaming.altervista.org/aowow/?spell=69762) to [Zul'Jins Energy Storm](https://wowgaming.altervista.org/aowow/?spell=43983) 
example of things that:
proc
- mana cost casts from healers/casters
- hunters mark
- paladin apply seals
- shaman shocks/summon totem
- mind blast with inner focus buff
no procs
- priest summon shadowfiend
- hunter arcane shot/explosive shot/multishot/steady shot
- warrior abilities
- paladin judgement/cs/ds
- shaman thunderstorm/storm strike
These were problematic and should no longer proc:
- cast inner focus (.cast …

fix(Scripts/ZulAman): Zul'Jin reduce procs of Energy Storm Aura

---

data/sql/updates/pending_db_world/rev_1736947882353306449.sql
src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
src/server/scripts/EasternKingdoms/ZulAman/zulaman.h

typo fix of ~~Aminishi~~ Amanishi
Set Guardians and Savages to have NPC/PC immunity on spawn. This prevents pulling through the door with pets or social-pulling by Eyes of the Beast of other trash like Amani Bears.
Found that AreaTrigger 4768, a large areatrigger that can only trigger after the gate is opened, exists but doesn't prevent any exploit. Purpose is unknown, maybe an anti-cheat warning system when players go through the door without the event, or used as a trigger to set Sacrifice Timer when re-entering the instance.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21161
The changes …

fix(Scripts/ZulAman): prevent early engaging of door guardians to skip timed event

---

data/sql/updates/pending_db_auth/rev_1736966800561154000.sql
data/sql/updates/pending_db_world/rev_1736963775000223100.sql
src/server/game/Accounts/AccountMgr.h

> [!WARNING]  
> ~If any existing username have more than 17 characters after this PR or testing I don't know how SQL database reacts to that (when i had it active and tried lowering it didnt allow me until i changed or removed the username with more than 17 characters.~
Client limitation on creating username is of 17 characters. (AC has it set to 20).
Tested on 2 clean clients.
3.3.5 (12340) enGB
3.3.5 (12340) enUS
Updated acore_world.`acore_string` `55` and `1005` (`LANG_PASSWORD_TOO_LONG` and `LANG_ACCOUNT_TOO_LONG`)
- Adds French and Russian Locale to `55`.
- Adds French, Spain Spanish, Mexican Spanish and Russian Locale to `1005`
- German grammer was corrected for `1005`.
- Corrected all previous `20` character max in `1005` to `17`.
~Updated the acore_auth.`account` `username` field …

fix(Core/DB) - Correct the max length of a username

---

src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp

Add 5s between NPC_PURE_ENERGY
- Closes #21237
- Closes #21236
1. .go c id 24744
2. .damage 21600 (in Normal mode) or .damage 29300 (in Heroic Mode) on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744)
3. Use .damage again on [Vexallus](https://wowgaming.altervista.org/aowow/?npc=24744) after 1 second from him summoning [Pure Energy](https://wowgaming.altervista.org/aowow/?npc=24745). …

fix(Scripts/MagistersTerrace) Add 5s Vexallus Pure Energy

---

src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp

- Closes #21204
1. Use bots or other players so no reset during  bewildering strikes
2. .go c id 22948
3. Wait for fel rage and observe no acid wound
4. After fel rage acid wound should be used again …

fix(Scripts/BT) Fix Gurtogg will not use acidic wound in phase 2

---

data/sql/updates/pending_db_world/rev_1735350584050913500.sql

Removes `NOT_REPEATABLE` and `WHILE_CHARMED` `event_flag`, allowing to always drop the flag no matter if it's CC'd or not from `Warlord Krom'zar`
and
Adds `Strike` to the `Warlord Krom'zar` sniffed from: `4.4.1.58158` and `1.15.5.57979`
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21007
- Closes https://github.com/chromiecraft/chromiecraft/issues/7404
1.
2.
3. …

fix(DB/SAI) - Fixes quest Counterattack! sometimes not being completed and adds 1 ability to the creature.

---

data/sql/updates/pending_db_world/rev_1738086749699040789.sql

Previously, quest completion was targetted to player only with a call explored action as wp completes.
Instead, we set questId on WP start instead
mEscortQuestID needs to be set for the following to work
- https://github.com/azerothcore/azerothcore-wotlk/blob/dfd09a3541f3be672c3e2ff3a0a431547a229d3b/src/server/game/AI/SmartScripts/SmartAI.cpp#L302
- Closes https://github.com/chromiecraft/chromiecraft/issues/7724
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/19591
Requires 2 characters in the same group
```
.go c id 11016
.add …
```

fix(DB/SAI): Escape from Jaedanar group completion

---

data/sql/updates/pending_db_world/rev_1729891925644004000.sql
src/server/game/Spells/SpellInfoCorrections.cpp

The target type for the quest credit spell 43458 in the SAI quest for 11343 (The Echo of Ymiron) is wrong and should be set to SMART_TARGET_SELF. The NPC actually casts it on himself and if the player is in the appropriate radius when the spell is cast, it will give them credit. The other quest referenced here 11344 (The Anguish of Nifflevar) is actually working as intended, even though there was a bug logged against it. Because the radius for the quest completion spell (43468 - Secrets of Nifflevar) is only 30 yards, it was likely that the person who logged the bug was not standing close enough to the NPC to receive credit and assumed it was bugged. I have manually tested that quest and confirmed you do get credit if you are standing within 30 yards of the NPC. 
So to sum things up, this …

fix(DB/SAI): Add target type correction for spell 43458 (Secrets of Wyrmskull)

---

data/sql/updates/pending_db_world/rev_1738931456199932650.sql

Could not find reliable information about the usage of these. According to [wowhead](https://www.wowhead.com/wotlk/npc=27064/abandoned-fuel-tank#abilities) these have abilities so opted not to remove the `SmartAi` flag.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21315
1.
2.
3. …

fix(DB/Creature): Remove aggro from Abandoned Fuel Tank

---

src/server/game/Entities/Transport/Transport.cpp

Fix issue when vehicle passengers where dropped in the middle of nowhere on Transport teleport
TWO players required!
0. Create 2 characters, level up to 80. (.level 79)
1. `.go xyz -4263 -11331 5.4 530`
2. Obtain vehicle with additional seats on it ( `.additem 44083` )
3. Invite another player to party
4. Second player should sit on your vehicle
5. Enter any transport (like boat or zeppelin) 
6. Wait until it teleports to another location
As a result you party member will be teleported along with you, unlike before the fix when he was left in previous …

fix(Core/Transport): Fix for passengers dropped in the middle of nowhere 

---

src/server/database/Database/Field.cpp

This PR addresses the next error from address sanitizer:
```
==2062960==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c00001a748 at pc 0x5641942efa26 bp 0x7fff533ee730 sp 0x7fff533edef8
READ of size 5 at 0x61c00001a748 thread T0
#0 0x5641942efa25 in __interceptor_strlen (/root/azerothcore/ac-server-2025-02-03/bin/worldserver+0x8d6a25) (BuildId: 0906f0a07ca8f8de5fd6f3a26384802c973d05ac)
#1 0x5641973969c7 in std::char_traits<char>::length(char const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/char_traits.h:399:9
#2 0x5641973969c7 in std::basic_string_view<char, std::char_traits<char> >::basic_string_view(char const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/string_view:132:16
#3 0x5641973969c7 in unsigned int …
```

fix(Core/SQLField): Fix heap-buffer-overflow issue when interacting with mysql field value.

---

src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Pet/Pet.h
src/server/game/Handlers/PetHandler.cpp

Fixes `heap-use-after-free` error:
```
==230820==ERROR: AddressSanitizer: heap-use-after-free on address 0x626052dd0668 at pc 0x555557a3c630 bp 0x7fffc925b650 sp 0x7fffc925b648
READ of size 1 at 0x626052dd0668 thread T15
#0 0x555557a3c62f in Unit::IsAlive() const /opt/wotlk_prod/src/server/game/Entities/Unit/Unit.h:1707:50
#1 0x555557a3c62f in Pet::Update(unsigned int) /opt/wotlk_prod/src/server/game/Entities/Pet/Pet.cpp:734:61
#2 0x5555580d9057 in void Acore::ObjectUpdater::Visit<Creature>(GridRefMgr<Creature>&) /opt/wotlk_prod/src/server/game/Grids/Notifiers/GridNotifiers.cpp:366:18
#3 0x5555583c207d in void VisitorHelper<Acore::ObjectUpdater, Creature>(Acore::ObjectUpdater&, ContainerMapList<Creature>&) /opt/wotlk_prod/src/common/Dynamic/TypeContainerVisitor.h:43:7
#4 0x5555583c207d in …
```

fix(Core/Pet): Fix possible crash when using dangling pointer as pets spell target and fix possible memory leak.

---

src/server/game/Entities/Player/PlayerUpdates.cpp

Fixes this `stack-use-after-scope` error:
```
==338453==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fffce405900 at pc 0x555555e3fd9d bp 0x7fffde6d1e90 sp 0x7fffde6d1618
READ of size 5 at 0x7fffce405900 thread T8
#0 0x555555e3fd9c in printf_common(void*, char const*, __va_list_tag*) asan_interceptors.cpp.o
#1 0x555555e416c0 in __interceptor_snprintf (/opt/azeroth-server/bin/worldserver+0x8ed6c0) (BuildId: 8846f982bb719a408f7a40508eea6c898c665148)
#2 0x555557c6b7f2 in Player::UpdateLocalChannels(unsigned int) /opt/wotlk_prod/src/server/game/Entities/Player/PlayerUpdates.cpp:560:21
#3 0x555557c68419 in Player::UpdateZone(unsigned int, unsigned int) /opt/wotlk_prod/src/server/game/Entities/Player/PlayerUpdates.cpp:1345:5
#4 0x555557c638db in Player::Update(unsigned int) …
```

fix(Core/Channels): Don't use deleted pointer in channel name creation.

---

src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp

Crashlog:
```
Thread 11 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffda535640 (LWP 338487)]
0x00005555579c2c9d in Object::GetGuidValue (this=0x0, index=<optimized out>) at /opt/wotlk_prod/src/server/game/Entities/Object/Object.cpp:339
339    ASSERT(index + 1 < m_valuesCount || PrintIndexError(index, false));
#0  0x00005555579c2c9d in Object::GetGuidValue (this=0x0, index=<optimized out>) at /opt/wotlk_prod/src/server/game/Entities/Object/Object.cpp:339
#1  0x0000555557cd2963 in Unit::GetCharmerGUID (this=0x0) at /opt/wotlk_prod/src/server/game/Entities/Unit/Unit.h:690
#2  Unit::GetCharmerOrOwnerGUID (this=0x0) at /opt/wotlk_prod/src/server/game/Entities/Unit/Unit.h:1229
#3  Unit::GetCharmerOrOwnerPlayerOrPlayerItself (this=0x0) at …
```

fix(Scripts/ICC): Fix crash in npc_darnavan when killer is nil.

---

src/server/game/Handlers/PetHandler.cpp

Fixes this `heap-use-after-free` error:
```
==338453==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f0007e1f20 at pc 0x55555828544f bp 0x7fffda534070 sp 0x7fffda534068
WRITE of size 4 at 0x60f0007e1f20 thread T10
#0 0x55555828544e in CharmInfo::SetForcedSpell(unsigned int) /opt/wotlk_prod/src/server/game/Entities/Unit/CharmInfo.h:176:53
#1 0x55555828544e in WorldSession::HandlePetActionHelper(Unit*, ObjectGuid, unsigned int, unsigned short, ObjectGuid) /opt/wotlk_prod/src/server/game/Handlers/PetHandler.cpp:435:32
#2 0x5555582804ec in WorldSession::HandlePetAction(WorldPacket&) /opt/wotlk_prod/src/server/game/Handlers/PetHandler.cpp:104:9
#3 0x555558650f65 in WorldSession::Update(unsigned int, PacketFilter&) /opt/wotlk_prod/src/server/game/Server/WorldSession.cpp:360:35
#4 …
```

fix(Core/Pet): Fix possible heap-use-after-free of charmInfo when handling pet action.

---

src/server/game/Spells/SpellEffects.cpp

Fix this `heap-use-after-free` error:
```
==338453==ERROR: AddressSanitizer: heap-use-after-free on address 0x619010687dc4 at pc 0x55555893f291 bp 0x7fffda534560 sp 0x7fffda534558
READ of size 4 at 0x619010687dc4 thread T10
#0 0x55555893f290 in Object::GetTypeId() const /opt/wotlk_prod/src/server/game/Entities/Object/Object.h:124:53
#1 0x55555893f290 in Object::IsCreature() const /opt/wotlk_prod/src/server/game/Entities/Object/Object.h:201:59
#2 0x55555893f290 in Object::ToUnit() /opt/wotlk_prod/src/server/game/Entities/Object/Object.h:206:26
#3 0x55555893f290 in SpellCastTargets::GetUnitTarget() const /opt/wotlk_prod/src/server/game/Spells/Spell.cpp:235:32
#4 0x55555893f290 in Spell::_cast(bool) /opt/wotlk_prod/src/server/game/Spells/Spell.cpp:4112:34
#5 0x555558949f98 in …
```

fix(Core/Spell): Reset insignia spell target when it is deleted.

---

src/server/game/Chat/Chat.cpp

Fixed the system that prevents the use of certain GM commands on targets whose access level (GMLevel) is higher than yours.
For example, the .summon command. Before the fix, you could use it on characters with a higher access level than yours. After the fix, you will receive a notification that your access level is too low.
**The pull request is provided 'as is' in the interest of the entire community, in the spirit of open-source. If the AzerothCore maintainers refuse to accept it due to incorrect formatting (templates etc) or some other nonsense, you can add it to your server manually.**

fix(Core/Chat): Fix lower security check for GM commands.

---

src/server/game/Entities/Player/PlayerUpdates.cpp

ASan:
```
==393329==ERROR: AddressSanitizer: attempting double-free on 0x602004a77310 in thread T8:
#0 0x555555edc5bd in operator delete(void*) (/opt/azeroth-server/bin/worldserver+0x9885bd) (BuildId: 94b1b8a4438fe7573a83b5df74cccb8c99e9094a)
#1 0x555557c67a1c in __gnu_cxx::new_allocator<unsigned char>::deallocate(unsigned char*, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:145:2
#2 0x555557c67a1c in std::allocator<unsigned char>::deallocate(unsigned char*, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/allocator.h:199:25
#3 0x555557c67a1c in std::allocator_traits<std::allocator<unsigned char> >::deallocate(std::allocator<unsigned char>&, unsigned char*, unsigned long) …
```

fix(Core/SpellQueue): Fix undefined behavior when processing SpellQueue.

---

src/server/game/Spells/SpellInfoCorrections.cpp

Hand of Protection no longer removes the debuff as it no longer counts as school 1 (SPELL_SCHOOL_MASK_NORMAL).
The spell 42389 is correct as it shows up in a sniff, but we change server-side school of 42389 Mangle to Nature. This matches the source from linked issue and the rest of the boss' spells
No idea how to include server-side spell 44955 here as the server already uses the modifier from the client 42389. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20652
- Closes https://github.com/chromiecraft/chromiecraft/issues/7528
target …

fix(Core/Spells): Hand of Protection no longer removes Nalorak's Mangle

---

src/common/Utilities/Containers.h
src/server/game/Entities/Object/Position.h
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp
src/server/scripts/Outland/TempestKeep/botanica/boss_laj.cpp

previous: SelectRandomContainerElementIf returns a reference to a temporary container element which is destroyed after calling, resulting in a heap-use-after-free error
changes:
- return an iterator to match std::find, std::find_if, this avoids making copies, similar to the random containers
- fixes undefined behavior if the result of predicate is empty, returns std::end instead. The caller will need to check if the return is valid
- pass by reference over pass by value
asan log L128 https://gist.github.com/walkline/3a86a2e35fdb20f0763eb9676e0cff82
- Closes 
This PR has …

fix(Core/Common): Container fixes use after free 

---

src/server/game/Spells/Spell.cpp

Subj.
Closes #21351
**The pull request is provided 'as is' in the interest of the entire community, in the spirit of open-source. If the AzerothCore maintainers refuse to accept it due to incorrect formatting (templates etc) or some other nonsense, you can add it to your server manually.**

fix(Core/Spells): Chain heal shoudln't jump to other players who are at full hp.

---

data/sql/updates/pending_db_world/rev_1737738749227497700.sql
src/server/scripts/Northrend/zone_zuldrak.cpp

Quest: https://www.wowhead.com/wotlk/quest=12652/feedin-da-goolz
Same ghoul can be feed more than once. So quest completion can be achieved by just spamming quest item near same ghoul.
This PR:
- Replaces core script with SmartAI
- ensures that same ghoul can not be feed again and again
0) Make character and level him to 80 (.level 79)
1) .additem 38699 // choker
2) .go xyz 4968 -1660 241 571
3) use Choker
4) .quest add 12652
Go and do the quest - use quest item https://www.wowhead.com/wotlk/item=38701/bowels-and-brains-bowl near ghouls. Same ghoul …

fix(DB/SAI) Quest Feedin' Da Goolz (12652)

---

data/sql/updates/pending_db_world/Northrend_Multiple_SmartAI.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/7814
- Closes https://github.com/chromiecraft/chromiecraft/issues/7815
- Closes https://github.com/chromiecraft/chromiecraft/issues/7816
- Closes https://github.com/chromiecraft/chromiecraft/issues/7817
- Closes https://github.com/chromiecraft/chromiecraft/issues/7818
- Closes https://github.com/chromiecraft/chromiecraft/issues/7819
- Closes https://github.com/chromiecraft/chromiecraft/issues/7820
- Closes https://github.com/chromiecraft/chromiecraft/issues/7821
- Closes https://github.com/chromiecraft/chromiecraft/issues/7822
- Closes …

fix(DB/Creatures) Various Northrend NPCs now have a SmartAI.

---

src/server/scripts/Spells/spell_warrior.cpp

The AoE effects of Intimidation Shout select targets independently.
If there are more than 5 targets, each effect may drop different units, causing some units to be feared, others to have increased speed, and more than 5 to have the fear visual. 
EFFECT_1 and EFFECT_2 filter the same initial list from searcher. So instead of reducing randomly later, resize in spellscript.
https://github.com/azerothcore/azerothcore-wotlk/blob/a23b13defea47fa806b85074d108eaf19561ee50/src/server/game/Spells/Spell.cpp#L1319
https://github.com/azerothcore/azerothcore-wotlk/blob/a23b13defea47fa806b85074d108eaf19561ee50/src/server/game …

fix(Scripts/Spells): Warrior IntimidationShout

---

src/server/game/Server/WorldSession.cpp

Disables out of world packet requeuing as it would appear some faulty addons (maybe just one in particular? TSM for example which is a retail back port, not designed for 3.3.5) will request a CMSG_SOCIAL_LIST opcode before player is in world causing session update to repeatedly attempt to process the packet until eventually the in world conditions are satisfied sometimes up to 800+ times a second. There is never really any reasonable case where we should be adding a packet back to the main queue loop.
While it would appear I originally removed this functionality back in 2016 without any adverse effects I would still suggest some testing to verify. At worst if needed we can rework this loop to block until packet processing becomes available rather than requeuing and processing the same …

fix(Core/Server): Disable out of world packet requeuing

---

src/server/game/Entities/Unit/Unit.cpp

Remove proc "propagating" of lightning overload
The triggered spells 45297 and 45284 don't every proc lightning overload, handled before already (tested with a few hundred chain lightnings and lightning bolts)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15499
.learn 30679
.learn 49271
Spam that spell …

fix (Core/Spells) remove custom loop so that one lightning damage instance can only proc one lightning overload

---

src/server/game/Battlefield/Battlefield.cpp

UI is not updated when player left WG queue.
.go creature id 32169 //alliance
.go creature id 32170 //horde
Wait for the queue to be opened (30 min before start)
Enter the queue for WG
On newly appeared icon near minimap click "leave"
Observe how icon disappeared …

fix (Core/Wintergrasp) Icon now disappears when player leaves queue

---

src/server/game/Battlefield/Battlefield.cpp

When player left WG by clicking "exit WG", he is teleported to homebind position. Before this change - hearthstone was showing a cooldown. But it is just a visual bug.
.tele Dalaran
go to any tavern and make it your home
.tele wintergrasp
right click on the icon near minimap, and select exit.
You will be teleported home, and you harthstone will not be on CD. …

fix (Core/Wintergrasp) hearthstone was visibly on cooldown when player left WG

---

data/sql/updates/pending_db_world/chamber-of-secrets-spawns.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16833 …

fix(DB): Add spawns for Tenris Mirkblood room in Karazhan.

---

data/sql/updates/pending_db_world/rev_1741106880644889078.sql
src/server/scripts/Spells/spell_warrior.cpp

Add bonus damage to Heroic Strike (Ranks 10,11,12,13) if the target is afflicted by a Daze
"Daze" is ambiguous. https://wowpedia.fandom.com/wiki/Daze
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21644
Target Dummy
```
.tele darnassus
```
With dummy targetted apply a Daze
```
.cast self 15571 triggered
```
cast Heroic Strike with/without Daze
observe damage …

fix(Scripts/Spells): add warrior heroic strike daze bonus damage

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellInfoCorrections.cpp
src/server/scripts/Spells/spell_dk.cpp
src/server/shared/SharedDefines.h
src/server/shared/enuminfo_SharedDefines.cpp

Pet avoidance spells do not apply avoidance to some boss' spells. This is due to them being cast from players to their allies and counting as creature spells. There's only a limited amount of spells with this flag: e.g., Mutated Plague from Professor Putricide (ICC). These spells have `SPELL_ATTR7_TREAT_AS_NPC_AOE` so pet avoidance spells can apply to these spells
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21782
[PATCH] Core/Spells: Named and implemented most of SpellAttr7
https://github.com/TrinityCore/TrinityCore/commit/4e87bd7942d932225436940f62e2 …

fix(Core/Spells): implement `SPELL_ATTR7_TREAT_AS_NPC_AOE`

---

src/server/game/Warden/WardenWin.cpp

This PR addresses a timing attack vulnerability in the Windows version of the Warden anti-cheat system by implementing constant-time comparison for hash verification. The current implementation uses memcmp() which leaks timing information based on where differences occur in the compared data, potentially allowing attackers to extract secret values byte-by-byte.
The fix replaces vulnerable memcmp() calls with a constant-time comparison function ~~that's functionally equivalent to OpenSSL's~~ CRYPTO_memcmp() - a well-established cryptographic standard for preventing timing side-channel attacks.
Ref https://github.com/openssl/openssl/blob/50316c18a0468bb0191904d7615955c9b47f061f/crypto/cpuid.c#L199
The vulnerability exists because memcmp() returns as soon as it finds a difference between …

fix(Warden) Warden Anti-Cheat Timing Attack Protection WINDOWS

---

data/sql/updates/pending_db_world/fix-Spirit-Calling-q10853.sql

Requires Spirit Calling Aura to loot Lesser Nether Drake Spirit (QuestID: 10853)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20052
- Closes https://github.com/chromiecraft/chromiecraft/issues/5929
[![Watch the video](https://img.youtube.com/vi/uXRTrUYeM6w/0.jpg)](https://youtu.be/uXRTrUYeM6w)
🔗 [Click here to watch on YouTube](https://youtu.be/uXRTrUYeM6w)
1. .q a 10853
2. Kill Lesser Nether Drake and check loot with out totem aura.
3. Kill Lesser Nether Drake and check loot with totem aura.
tip: Quest item drop has 80%
- If recharges are finished quest giver should also [refill your stock](https://www.wowhead.com/wotlk/npc=22312/spiritcaller-dohgar#comments:id=380042), currently it doesn't. …

fix(DB/Conditions) Requires Spirit Calling Aura to loot Lesser Nether Drake Spirit (QuestID: 10853)

---

data/sql/updates/pending_db_world/rev_1743613994250754577.sql
src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp

Adds Moorba's Teleport gossip options which allow players to teleport ahead once specific encounters have been completed.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7987
gossip menu after killing Eredar Twins: https://www.youtube.com/watch?t=7358&v=ZrMRUxTtMYk
cherry-pick teleporter handling from SWP: Complete overhaul and implementation of missing and existing scripts
https://github.com/cmangos/mangos-wotlk/commit/a6964c0d476e4a0231239e9f1ad6e3c82921c160
tested with `.instance setbossstate 0 3`
Only 0 or 1 gossip option may be visible …

fix(Scripts/SunwellPlateau): Add Moorba's teleporter gossip

---

data/sql/updates/pending_db_world/rev_1744203507462519600.sql

`Recipe: Elixir of Empowerment` (35294)  and `Recipe: Haste Potion` (35295) from `Kael'thas Sunstrider` (24664) Heroic's Loot (35008) had their skill/proffession required to drop changed to match their required skill to use.
Currently the both recipes only drops for Blacksmithing players which is not the intended behaviour
- Closes https://github.com/chromiecraft/chromiecraft/issues/7998
1.
2.
3. …

fix (db/Conditions) -  Kael'thas Sunstrider's Heroic loot ref will drop the correct recipes to their respective proffesion.

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerUpdates.cpp

Currently:
When a player resurrects, calls to enter/leave zone handlers are skipped as the zone remains unchanged. These handlers apply zone wide buffs such as K'iru's Song of Victory, [Trollbane's Command](https://wowgaming.altervista.org/aowow/?spell=39911) and [Echoes of Lordaeron](https://wowgaming.altervista.org/aowow/?spell=1386)
This forces calls to enter/leave zone handlers on player resurrect
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21885
Trollbane's command
```
.add 32385
.go c 57876
.tele ramp
.die
.revive
```
Echoes …

fix(Core/Player): Force UpdateZone on resurrect to apply Zone auras

---

src/server/apps/worldserver/worldserver.conf.dist
src/server/game/Battlefield/Battlefield.h
src/server/game/World/World.cpp

WG minor edit: more Blizz-like for 3.3.5a.
Changed default values for
```
Wintergrasp.PlayerMax = 100
Wintergrasp.PlayerMinLvl = 77
```
to
```
Wintergrasp.PlayerMax = 240
Wintergrasp.PlayerMinLvl = 75
```
Default settings were not Blizz-like.
As of 3.2.0 and into 3.3.5a, this was the minimum queue level and maximum number of players in WG. [Patch notes.](https://wowpedia.fandom.com/wiki/Wintergrasp#Patch_changes)
> - Level 75 is required to queue
> - The queue will accept up to 120 players from each faction, resulting in a maximum battle of 240 players at a time.
The non-Blizz-like 77/100 settings were [copied from TrinityCore](https://github.com/TrinityCore/TrinityCore/blob/master/src/server/worldserver/worldserver.conf.dist). There they had not been changed ever since they were first …

fix(Battlefield/WG): set default maxplayer 120, minlevel 75

---

src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp

This PR implements raycasting functionality to prevent Singularity from throwing players through walls in the Entropius encounter. The method checks for obstacles by incrementally testing line-of-sight along a vector, returning the distance to the first collision.
~~While initially implemented for the black hole effect, this functionality could benefit many other game mechanics (knockbacks, teleports, placement checks). Exposing it as an API would allow future developers to avoid wall clipping issues without duplicating code.
The challenge is determining appropriate placement - Unit.cpp maybe since it leverages IsWithinLOS, but it's pretty bloated already~~
-  [x] Scripts (bosses, spell scripts, creature …

fix(Script/Sunwell): Implement raycast to prevent Singularity throwing players through walls

---

src/server/game/Entities/Object/Updates/UpdateFields.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/StatSystem.cpp

While the client display truncates the Expertise gained from Expertise Rating to int, there should be no truncating on the server.
- Closes 
ElitistJerks test from 3.1 comparing 209 and 213 expertise. Both are displayed as 25 Expertise on the client. This display was then fixed on classic wow
https://github.com/ClassicWoWCommunity/cata-classic-bugs/issues/556
106/82 = 12.9268292683 Expertise
Before
truncated to 12 expertise = 3% dodge reduction -> 3.5% dodge left
Result: 3433/100132 = 3.428% dodges
After
not truncated = 3.232...% dodge reduction -> …

fix(Core/Player) internally handle expertise as float

---

src/server/apps/worldserver/worldserver.conf.dist

Just a small edit to help users understand how this setting works, and there will be a different AH cut if it is used. 
Changes
```
```
to
```
```

fix(Core/worldserver.conf) Clarification for AllowTwoSide.Interaction.Auction

---

src/server/game/Entities/Player/Player.cpp

This reverts commit 9f37794f5c1f8c2b95906ab8e4c84a593be4703e.
The `hasteModifier`'s added in [#20321](https://github.com/azerothcore/azerothcore-wotlk/pull/20321) are already added [by a code block below (`SPELL_AURA_MOD_POWER_REGEN_PERCENT`)](https://github.com/azerothcore/azerothcore-wotlk/blob/8797e8ad280aabc8314bc175c3a6284aa2b6deaf/src/server/game/Entities/Player/Player.cpp#L1946), resulting in them being added twice.
Also see the discussion in the PR
- https://github.com/azerothcore/azerothcore-wotlk/pull/20321
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22003
- Closes …

Revert "Fix(Core/Player): Energy regen rate bonuses (#20321)"

---

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp

In similar veins as with https://github.com/azerothcore/azerothcore-wotlk/pull/22014
It feels more natural that Fatal Attraction teleporting less than 3 targets is somewhat unintentional on blizzards side, rather them deciding on some values to teleport less (or even 1 target, which makes the whole spell a non-issue for the raid)
This means the chances in a regular raid environment with 3 tanks are: 
3 targets: (22/25) x (21/24) x (20/23) = ~67%
2 targets: 3x (22/25) x (21/24) x (3/23) = ~30%
1 target: 3x (22/25) x (3/24) x (2/23) = ~2.7%
0 targets: (3/25) x (2/24) x (1/23) = ~0.04%
assemble …

refactor(Scripts/BlackTemple) remove tanks from Fatal Attraction after setting the target amount

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp

demonstrated by a Rogue specced with talents Combat Vitality and Adrenaline Rush. Use sinister strike to dump energy to 0, then use Adrenaline Rush.
The "after" clip should better match the Energy regen in [source video from wrath classic](https://www.youtube.com/watch?v=lSFNsQOwOhs) in the linked isuee
https://github.com/user-attachments/assets/91e8c208-8c00-49d8-afde-80329dba9457
https://github.com/user-attachments/assets/0989d603-1e16-4074-9d65-e03e93d8332e
<details>
<summary>
full
</summary>
https://github.com/user-attachments/assets/c705ed71-cdd3-4848-988a-a6bdf0fd3f99
</details>
- Closes …

fix(Core/Player): smooth energy regeneration with `SPELL_AURA_MOD_POWER_REGEN_PERCENT` mods

---

src/server/game/Spells/Spell.cpp

Seduce is a charm mechanic, you can't cast spells while MC-ed regardless.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21975
Make a priest
.additem 45760
.learn 33206
target self
.aura 6358
cast PS
- Add a proper function to bypass stuns …

fix(Core/Spells): Allow glyphed PS to be casted while Seduced

---

data/sql/updates/pending_db_world/rev_1745955461043147883.sql
src/server/game/Entities/Unit/Unit.cpp

Remove the cooldown of 4 seconds as both auras already function on 15 PPM.
Tested with a 2.0 speed weapon, 186 attacks -> 90 procs
2 x 15 / 60 = 50%
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4209
Cast judgement of wisdom/light on enemy.
Use consecration -> no procs
Use seal of corruption and stack the dot up -> see no procs
Use a fast weapon -> eventually see back to back procs …

fix(Spells/Paladin) remove custom cooldown and procFlags from Judgement of Wisdom/Light

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/SpellInfoCorrections.cpp

Reimplement SPELL_ATTR3_CAN_PROC_FROM_PROCS (and also remove the general ability of procs to proc procs)
Generalized fix for https://github.com/azerothcore/azerothcore-wotlk/pull/21961
The code was commented out in the first commit of azerothcore
Fixes todo in https://github.com/azerothcore/azerothcore-wotlk/pull/22018
Paladin with all Seals: they do not proc Judgement (the debuff) or Trinkets anymore
Shaman with Earthliving Weapon and Crystal Spire of Karabor: Karabor does not proc Earthliving anymore
Insert `LOG_INFO("server.worldserver", "{} did not …

fix(Core/Spells) reimplement SPELL_ATTR3_CAN_PROC_FROM_PROCS

---

data/sql/updates/pending_db_world/rev_1747255986267456043.sql
src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp

The core does not handle spell stealing refreshing stacks. I can't think of other spells where stacks should be refreshed upon Spell Stealing. 
Removes dot from spell proc
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21925
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21926
1.
2.
3. …

fix(Scripts/SunwellPlateau): Spell Fury spellsteal resets stacks and is no longer consumes on dot ticks

---

src/server/game/Entities/Player/Player.cpp

This reverts some previous changes to `ApplyItemEquipSpell` and proposes logic cherry-picked from cmangos to fix "Use" items.
This logic caused a regression to "Electromagnetic Gigaflux Reactivator
" and "Book of the Dead" , but removing lines 98cf237b61b7 fixed this.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19823#issuecomment-2895098252
The modified function has been modified a few times, causing regressions. 
book of the dead
> Allows player to unequip Book of the Dead and have the summoned skeleton remain for its duration
.add …

fix(Core/Player): aura removal logic to equipped "Use" items

---

src/server/game/Spells/SpellInfoCorrections.cpp

There exist a few spells that summon Traps with a startDelay as [Wild, without an owner.](https://github.com/azerothcore/azerothcore-wotlk/blob/8591e9f825d9c9eb0b38fcf7e82aed387a24525e/src/server/game/Spells/SpellEffects.cpp#L3778) The core[ requires an owner set](https://github.com/azerothcore/azerothcore-wotlk/blob/8591e9f825d9c9eb0b38fcf7e82aed387a24525e/src/server/game/Entities/GameObject/GameObject.cpp#L502), so let's hack these spells to use `Spell::EffectSummonObject` [where their owner is set](https://github.com/azerothcore/azerothcore-wotlk/blob/3f527c54e35d48aa962c3ef3054687c754be1050/src/server/game/S …

fix(Scripts/Spells): re-add startDelay for some traps

---

src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp

The changes:
1. Engage Kil'jaeden.
2. Get him down to final phase (~25% health).
3. Allow him to begin casting Darkness of a Thousand Souls.
4. Kill him.
5. Observe you did not taste vengeance. …

fix(Scripts/SunwellPlateau): Don't inflict Darkness damage if Darkness aura is removed by death,

---

src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_amanitar.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22182
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22181
1.
2.
3. …

fix(Scripts/AhnKahet): Modernize Amanitar script

---

data/sql/updates/pending_db_world/rev_1748972350605073197.sql
src/server/game/DungeonFinding/LFGMgr.cpp
src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
src/server/scripts/Kalimdor/zone_orgrimmar.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22267
Create a Deathknight
See the dungeon finder locked
.gm on (so that you can leave the area)
Alliance:
.quest add 13188
.go c id 29611
Hand in the quest
Horde:
.quest add 13189
.go c id 4949
Hand in the quest
Queue dungeonfinder
**REMEMBER**: …

fix(Core/Script/Deathknight) Lock Deathknights from the dungeonfinder until they complete their starting zone

---

data/sql/updates/pending_db_world/rev_1748707579733807961.sql
src/server/scripts/Outland/Auchindoun/ManaTombs/boss_nexusprince_shaffar.cpp

Nexus-Prince Shaffar in Mana Tombs spawns his three Ethereal Beacons via a script. Together with the pre-spawned ones, the fight incorrectly starts with six Beacons instead.
Remove the pre-spawned ones to fix this.
TrinityCore fixed this issue a while ago:
https://github.com/TrinityCore/TrinityCore/issues/24325
Relates to AzerothCore issue #18895, but doesn't fix it completely (the damage numbers still seem way off).
- Alleviates https://github.com/azerothcore/azerothcore-wotlk/issues/18895, but does not fix it completely.
1. Enter Mana Tombs,
2. …

fix(DB/Creature): Remove extra Shaffar adds

---

src/server/game/Spells/SpellEffects.cpp
src/server/game/Spells/SpellInfoCorrections.cpp

reverts https://github.com/azerothcore/azerothcore-wotlk/commit/a234314d359591f02ea1810b49895da67d947185
reverts https://github.com/azerothcore/azerothcore-wotlk/commit/a5d334db8ba5bda37eeafdc034d47ad17e001815
https://github.com/azerothcore/azerothcore-wotlk/pull/22232 introduces a proper fix for SPELL_EFFECT_WEAPON_PERCENT_DAMAGE
.cast 20375
Attack a bit
.cast 31884
Attack and only see a 20% damage increase on the seal …

fix(Core/Spell) Revert paladin seal hackfixes

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/SpellEffects.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22220
**Methodology**
List of SpellIds to use while testing this
49143 - Frost Strike (Magic damage based on both Weapon % damage and flat damage)
45902 - Blood Strike (Physical damage based on both Weapon % damage and flat damage)
45477 - Icy Touch (Magic damage dealing spell)
53209 - Chimera Shot (Magic damage based on Weapon % damage only)
48266 - Blood presence for damage buff
To test, get an average damage of a spell without the aura (for spells that have damage ranges). Write it down …

fix(Core/Spells): weapon damage based magic abilities gain too much effect from spell aura % damage increase

---

data/sql/updates/pending_db_world/rev_1747574437797050200.sql

Sets SpecialFlags from 0 to 1, allowing Fine Gold Thread to be repeatable.
- Closes https://github.com/chromiecraft/chromiecraft/issues/8047
Source: https://www.wowhead.com/wotlk/quest=4785/fine-gold-thread ( thanks @amed80 )
- Make a warlock
- `.level 32`
- `quest add 4783` // Components for the Enchanted Gold Bloodrobe (4/5)
- `quest complete 4783` // Components for the Enchanted Gold Bloodrobe (4/5)
- `quest reward 4783` // Components for the Enchanted Gold Bloodrobe (4/5)
- `quest add 4785` // Fine Gold Thread
- `quest complete 4785` // Fine Gold …

fix(DB/Quest) - "Fine Gold Thread" is now repeatable

---

src/server/game/Spells/Spell.cpp

Player movement handlers update a player's orientation (mouse drag or keyboard turn), but channel update overwrites it as if it were facing the creature
This causes issues with Yogg-Saron, where Drain Soul will face the boss on the server side when the player is turned away.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15795
1. Cast Drain Soul on a target dummy
2. Change orientation  (mouse drag or keyboard turn)
3. Log position
1. 
4.
5.
You can help …

fix(Core/Spells): channels no longer update player server-side orientation

---

data/sql/updates/pending_db_world/1748186943.sql

- Closes [19931](https://github.com/azerothcore/azerothcore-wotlk/issues/19931)
1. https://www.youtube.com/watch?v=BlmOZ07UlG0
1. https://www.youtube.com/watch?v=g6YGyNQBE3Y
1. https://www.youtube.com/watch?v=b0Ytr2192M0
1. `.quest add 12197`
2. `.go creature id 26409`
3. kill and loot
/ …

fix(DB/creature_loot) - Durar's and Kathorn's Power Cell corrected drop rate to 100%

---

src/server/game/Scripting/ScriptDefines/UnitScript.cpp

fix(Core/Scripting): `UnitScript::DealDamage` always returns the original damage value

---

data/sql/updates/pending_db_world/rev_1748021905087919900.sql

Blackrock Moutain `areatrigger_teleport` had their instances (in and out) updated to match the sniffed values.
Sniff data (related to each cords) can bee seen [here](https://gist.github.com/TheSCREWEDSoftware/5da1e8dcdc3dcbf69727528d6b410bb9) was sniffed on retail (`11.1.5.60822`) and the cords updates for cata+ instances can be ignored. Ignore the `Facing` value of the queries as TrinityCore handles orientation differently. look for this as an example:
```
Map: 409 (Molten Core)
Position: X: 1091.89 Y: -466.985 Z: -105.084 O: 3.1415927
```
Many area triggers had the names changed to properly describe what they are related, the biggest change would be `maraudon` and `dire maul`. Using most recent examples (for wotlk areatriggers in the db) 
The place you get teleported (from an instance …

fix(DB/areatrigger_teleport) - Multiple updated areatriggers.

---

data/sql/updates/pending_db_world/rev_1749848424024494127.sql
src/server/game/Events/GameEventMgr.cpp
src/server/game/Globals/ObjectMgr.cpp

game_event sets event_entry as an unsigned tiny int with a range from 0 to 255
Some game_event_* tables use tinyint, which limits the range from -128 to 127
game_event_model_equip was using tinyint
- https://github.com/azerothcore/azerothcore-wotlk/blob/a8cc3b7ba7817c545f006f51bd2ddb9c254955e5/src/server/game/Events/GameEventMgr.cpp#L618
Also fixes clang tidy warning:
> 'signed char' to 'int16' (aka 'short') conversion; consider casting to 'unsigned char' first.clang-tidycert-str34-c
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/signed-char-misuse.html
- Closes 
fixes sql error `Out of range value for …

fix(DB): set game_event_* tables to use smallint

---

src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp

- Closes unreported
Sometimes Kil'jaeden performs no actions after the initial Shadow Spikes in P5
Brought Kil'jaeden to 25% 4 times and the script still ran.
.go c id 25315
Slowly bring him to 25%, making a break at 85% and 55% for those health breakpoint scripts to complete …

fix(Script/SWP): unify events that interact with Anveena in P5 Kil'Jaeden

---

data/sql/updates/pending_db_world/rev_1751514394329775600.sql

I tried `SMART_ACTION_SET_CORPSE_DELAY` with the event death didn't work, so I'm setting it dispawn in 20 seconds so the 2 min timer can start, currntly corpse decay for boss rank might not be correct evaluted with dynmic spawns.
Result: https://www.youtube.com/watch?v=AOdQGXnELx8&feature=youtu.be
- Closes https://github.com/chromiecraft/chromiecraft/issues/8121
- `.gm on`
- `.go c i 31099`
- `.die`
- Wait 20 seconds, dispawns
- Wait 2 minutes, spawns. …

fix(DB/SAI) - Corrects Corpse.Decay for Patchwerk from the end of the Death Knight zone

---

src/server/game/Entities/Item/ItemTemplate.h
src/server/game/Spells/SpellEffects.cpp

Some creatures cast a spell with `SPELL_EFFECT_CREATE_ITEM`, which can mistakenly add an item with a signature "Created by" to the player. For example, a list below shows smartAI actions that will result in a Signature when it shouldn't. 
<details><summary>table of ~100 SmartAI/Items that should no longer give a "Created by" signature</summary>
| entryorguid | id | spell_id | item_entry | item_name                            | 
|-------------|----|----------|------------|--------------------------------------| 
| -98174      | 0  | 61457    | 44738      | Kirin Tor Familiar                   | 
| 5049        | …

fix(Core/Spells): No longer add a signature to items created by NPCs

---

src/common/Metric/Metric.cpp
src/common/Metric/Metric.h
src/server/apps/worldserver/worldserver.conf.dist

- Config setting Metric.ConnectionInfo has been renamed to Metric.InfluxDB.Connection to emphesise that we use InfluxDB
- AC Now supports sending data to InfluxDB v2
- Config setting Metric.ConnectionInfo has been renamed to Metric.InfluxDB.Connection to emphesise that we use InfluxDB
By implementing it this way we keep "legacy" support for InfluxDB v1 while also allowing to send data to InfluxDB v2
> [!IMPORTANT]
>  While InfluxDB v2 works, the grafana dashboard is not updated so it will not work with InfluxDB v2
> [!NOTE]
> The following screenshot is taken from the InfluxDB dashboard as proof that the connection works and sends data correctly. (NOT GRAFANA) 
* Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20448
- The Grafana json files here …

BREAKINGCHANGE(Metrics): Support InfluxDB v2

---

src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Spells/spell_warrior.cpp

Previously, killing a creature with Victory Rush procs Victory Rush, then removes the aura.
This change allows a player to kill a creature with Victory Rush and keep Victory Rush.
previous bugs reported for this spell:
- https://github.com/azerothcore/azerothcore-wotlk/issues/5156
- https://github.com/azerothcore/azerothcore-wotlk/issues/6657
- https://github.com/azerothcore/azerothcore-wotlk/issues/7628
- Closes https://github.com/chromiecraft/chromiecraft/issues/8146
Warrior character with Victory Rush learned
target a creature and grant immunity
``` …
```

fix(Scripts/Spells): killing with Victory Rush grants Victory Rush

---

data/sql/create/create_mysql.sql

Upon creation of the user and databases the `acore` user gets ALL PERMISSIONS for all the databases, instead of only the `acore` related ones, after the user is created it still grants all permissions to each respective database being created.
Current AC:
`Root User`
`Acore User`
Current PR:
`Root User`
`Acore User`
- Closes N/A
1.
2.
3. …

fix(DB/SQL): Do not give all permissions to user "acore" upon creation via the sql file

---

src/server/game/Entities/Player/PlayerQuest.cpp

Currently, doing either the daily random heroic dungeon or daily random normal dungeon locks you out of the other's reward. 
Random daily heroic dungeon reward (2 emblem of frost) and random daily normal dungeon reward (2 emblem triumph) are currently shared rewards. Meaning you cannot do both in one day. This PR alters the dungeon quest check to ensure both can be completed in the same day.
This is how it works on TrinityCore, and using resources such as: https://www.bluetracker.gg/wow/topic/us-en/20677351931-can-you-do-the-random-daily-with-a-non-pug/ seems to imply that both rewards can be obtained once per …

fix(CORE/lfg): Correct random LFG reward bug

---

apps/startup-scripts/src/simple-restarter

Unlike starting through the binaries, if you start through acore.sh and then try to shutdown worldserver with `server shutdown 1` or SIGINT, you don't stop after shutdown. Instead you remain in the starter script loop, and end up with a restart. This change ensures that you get out of the loop if you have requested a shutdown.
- Closes 
Before trying this fix, if you only run AC through the binaries and have never seen this issue, run the server through acore.sh at the AC directory with these commands:
```
./acore.sh run-authserver
./acore.sh …
```

fix(bash): Exit simple-restarter script if shutdown is requested

---

data/sql/updates/pending_db_world/rev_1754910707047949800.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22653
1. .go c id 29120
2. Start [Anub'arak](https://wowgaming.altervista.org/aowow/?npc=29120) encounter
3. Deal damage to [Anub'arak](https://wowgaming.altervista.org/aowow/?npc=29120) until it submerge at 75%
4. Do not kill [Anub'ar Venomancer](https://wowgaming.altervista.org/aowow/?npc=29217) and wait for [Anub'arak](https://wowgaming.altervista.org/aowow/?npc=29120) to emerge
5.  Deal damage to [Anub'arak](https://wowgaming.altervista.org/aowow/?npc=29120) until it submerge again at …

fix(DB/spell_custom_attr): Allow Poison Bolt to stack

---

src/server/game/World/WorldState.cpp
src/server/game/World/WorldState.h

This PR:
1. `.worldstate scourgeinvasion state 1`
2. Verify that bosses have spawned in instances.
3. Restart server.
4. Verify that bosses remain spawned in instances. …

fix(Core/WorldState): Start boss activation event when starting Scourge Invasion.

---

data/sql/updates/pending_db_world/tenris-bind.sql
src/server/scripts/EasternKingdoms/Karazhan/boss_tenris_mirkblood.cpp

fix(Scripts/Karazhan): Bind players to instance upon killing Tenris Mirkblood.

---

src/server/scripts/World/scourge_invasion.cpp

- Possibly closes https://github.com/chromiecraft/chromiecraft/issues/8288 …

fix(Scripts/World): Swap Shard communication spell to direct cast instead of AoE.

---

src/server/scripts/Spells/spell_quest.cpp

Updates spell_q12805_lifeblood_dummy to properly grant kill credit to all nearby group members when the spell is cast, instead of only the caster. Ensures group members within reward distance receive credit for the quest objective.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21546
1.
2.
3. …

fix(Scripts/Spells): Fix group credit for Salvaging Life's Strength quest spell

---

apps/bash_shared/menu_system.sh
apps/compiler/compiler.sh
apps/compiler/test/test_compiler.bats
apps/installer/includes/modules-manager/module-main.sh
apps/installer/includes/modules-manager/modules.sh
apps/installer/main.sh
apps/installer/test/test_module_commands.bats

This pull request introduces a unified, reusable Bash menu system for AzerothCore scripts and refactors major management scripts (`main.sh`, `compiler.sh`, and module manager) to use this new menu system. The changes significantly improve code maintainability, user experience, and consistency across interactive and direct command modes. Key improvements are grouped below.
**1. Introduction of Unified Menu System**
* Added new `bash_shared/menu_system.sh` library providing a generic, feature-rich menu system for Bash scripts, supporting both interactive and direct command modes, numeric and text selection, short aliases, and argument forwarding.
**2. Refactoring of Core Scripts to Use Menu System**
* Refactored `apps/installer/main.sh` to use the new menu system, replacing legacy `select` …

feat(MenuSystem): Implement unified menu system for AzerothCore management

---

src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22697
I could not find any old videos of the original wotlk client where this quest was turned in. I do believe, however, that this change aligns with how the original game logic was. 
The change removes the previous logic that checked whether the menu had already been opened or not. Now, on gossip hello, it always shows the main gossip page. For logic relating to getting a red essence or exchanging essences, that is handled in the OnGossipSelect method. The original logic seemed overly …

fix(Core): Fix oculus npc belgaristrasz gossip menu

---

data/sql/updates/pending_db_world/vurtok-axebreaker.sql

- Closes https://github.com/chromiecraft/chromiecraft/issues/8300
This PR: …

fix(DB/Creature): Remove incorrect other gender display from Vurtok Axebreaker.

---

deps/boost/CMakeLists.txt

This pull request updates the way Boost dependencies are specified in the `deps/boost/CMakeLists.txt` file to improve compatibility with newer Boost versions. The most important change is the adjustment to the `find_package` command to avoid requiring the `system` component, which is header-only in Boost 1.69 and above.
Dependency management update:
* Modified the `find_package` command to exclude the `system` component and use the `COMPONENTS` keyword, ensuring only necessary Boost libraries are required for builds with Boost 1.74 or newer.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22785 …

fix(CMake/Boost): package finding logic + suppress deprecation warnings + support Boost 1.89

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

This pull request refactors how the "force destination" behavior is controlled for movement actions in SmartScripts. It introduces a new `disableForceDestination` parameter to both the `moveToPos` and `moveToPosTarget` structs, and updates relevant logic to utilize this flag, allowing more granular control over movement commands.
**SmartScript movement logic improvements:**
* Added a `disableForceDestination` field to the `moveToPos` struct in `SmartAction`, enabling scripts to specify whether the force destination behavior should be disabled for position-based movement actions.
* Introduced a new `moveToPosTarget` struct in `SmartAction` with its own `disableForceDestination` field and updated related logic to use this struct for target-based movement actions.
* Updated all calls to …

feat(Core/SAI): enhance movement actions with force destination option

---

apps/installer/includes/os_configs/windows.sh

Refactor INSTALL_ARGS to use an array for better handling and update the OpenSSL version to 3.5.3.
This pull request updates the Windows installation script to improve argument handling and update a package version. The most important changes are grouped below:
Argument handling improvements:
* Refactored `INSTALL_ARGS` from a string to an array in `windows.sh`, allowing for safer and more flexible argument passing to `choco install` commands. All invocations now use `"${INSTALL_ARGS[@]}"` instead of `$INSTALL_ARGS`.
Dependency updates:
* Updated the `openssl` package version from `3.5.2` to `3.5.3` in the installation commands.

Improve INSTALL_ARGS handling and update OpenSSL version

---

data/sql/updates/pending_db_world/rev_1759325091278152494.sql

Fix the flight speed of Skeletal Assault Gryphon, and it will now eject the player.
Details:
The smartAI event OnCharmed cannot be used in this case, because the order in which the waypoint is loaded matters.
- OnCharmed -> Start WP -> On player boarding will reset the movement to `IDLE_MOTION_TYPE` which explain the slow movement and will no longer cause OnWaypoint events to be emitted.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21678
1.
2.
3.
You …

fix(DB/SmartAI): Icecrown quest Seeds of Chaos flight speed and eject
