azerothcore/azerothcore-wotlk

data/sql/updates/pending_db_world/rev_1680412607015816900.sql
- Add missing npc text (before any quests have been rewarded)
- Require 12212 to have been rewarded in order to see gossip, vendor option and 12216 to sell Flank..
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15771
https://wowpedia.fandom.com/wiki/Jesse_Masters
- tested
.go c id 29244
Talk with the npc, should have no vendor option and gossip:
"Our storehouses have been depleted. I have nothing to sell until we can get more supplies."
.q a 12212
.q c 12212
.q reward 12212
Should add the vendor option and change gossip to:
"Because you've managed to replenish some of our supplies I can get back to cooking. Now, what can I do for you?"
Completing 12216 should add Sizzling Grizzly Flank to the vendor. …
=> fix(DB/Conditions): Jesse Masters selling items without quest completion

data/sql/updates/pending_db_world/rev_1680462089982964400.sql
- Use SAI to set StandState
- Closes https://github.com/chromiecraft/chromiecraft/issues/2505
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9588
- tested
.go c id 8397
Pull …
=> fix(DB/SAI): Sentinel Keldara Sunblade attacking while feign death

data/sql/updates/pending_db_world/rev_1680566443470632000.sql
-  Just rebuilds it across the board, removes some extras
-  
- Closes 
Retail
- 
- 
1.
2.
3. …
=> fix(DB/Reputation): Onkill rep for Steamvault and Shadow Labyrinth

data/sql/updates/pending_db_world/rev_1679773328267054300.sql, src/server/scripts/Outland/CoilfangReservoir/SlavePens/instance_the_slave_pens.cpp, src/server/scripts/Outland/CoilfangReservoir/SlavePens/the_slave_pens.cpp, src/server/scripts/Outland/CoilfangReservoir/SlavePens/the_slave_pens.h, src/server/scripts/Outland/outland_script_loader.cpp
Fixes #8559
- Closes #8559
- Tested ingame. 
`.go cr id 17942`
=> fix(Scripts/SlavePens): Added waypoint movement to Quagmirran.

data/sql/updates/pending_db_world/rev_1680542257068778400.sql, src/server/scripts/World/npc_taxi.cpp
TrinityCore/TrinityCore/issues/23905
- Correct the currently broken SAI and add visuals.
- Correct TaxiPath
- Add 4 spellfocus objects in each "spike" of the building (from Trinity)
https://www.youtube.com/watch?v=CiLN0NO4iaE&
- tested
.go c id 20903
.q a 10438
Speak with the Drake to start
Confirm the item can be used from further than before
Kill the conduit and look for visuals and yell on death. …
=> fix(DB/SAI): Port On Nethery Wing visuals from Trinity.

data/sql/updates/pending_db_world/razormawdamageupdate.sql
from 7.5 to 2.5. probably still a bit high. subject to change
-  damagemodifier from 7.5 to 2.5 (might be 2 or 1.5) but that would make it really easy
- Progress https://github.com/chromiecraft/chromiecraft/issues/5300
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/7819
https://youtu.be/9010SfVJPN0 but this shows damage to a pet. so ideally you should test this as a hunter with a pet at the same level. a cat pet, that is
- tested myself as a paladin with appropriate gear at level 19. I take around 60ish damage each melee hit now, which is doable if it's a 2 man quest
1. `.quest add 9689`
2. .tele bloodmyst
3. move to quest location
4. summon boss
5. see how much damage you take on melee, preferably as a hunter with a cat pet
- [ the boss flies over the ground. it …
=> fix(DB/Creature): fix damage modifier of Razormaw

data/sql/updates/pending_db_world/rev_1679769505624357100.sql
- Closes #15541
- Closes https://github.com/chromiecraft/chromiecraft/issues/4825
`.go c 138353`
Go in any water and test if fishes come chasing you …
=> Underbog frenzy aggro

data/sql/updates/pending_db_world/rev_1680686430825385473.sql
-  Removes old/unused SAI from Yor 
- No errors
1.
2.
3.
=> chore(DB/SAI): Remove unused SAI from Yor

data/sql/updates/pending_db_world/rev_1680443009841196300.sql
-  
-  
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/15780
see https://www.wowhead.com/wotlk/npc=14308/ferra#drops;mode:normal (additional sources might be needed)
- no sql syntax errors
- 
1. run SQL queries in whatever way you want
2. go to DM:W by using .tele commands
3. fly to the top level
4. kill Illyanna Ravencloak and her pet bear Ferra
5. check Ferra's loot a couple of times and see if the items from the loot table are added (1% chance so will take some time)
- add additional loot. it's not complete, likely. but we need some better sources  …
=> fix(DB/Loot): Ferra add in DM:W not dropping correct loot

data/sql/updates/pending_db_world/fix-spire-frostwyrm-remnant-alliance
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> Remove the Spire Frostwyrm remnant in alliance side

src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15845
- 
- 
1.
2.
3. …
=> fix(Scripts/IcecrownCitadel): Fix Putricide crash

src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15856#issuecomment-1500001938
- 
- 
1.
2.
3. …
=> fix(Scripts/IcecrownCitadel): Fix Svalna crash

data/sql/updates/db_world/2023_04_02_02.sql
Typo'd file doesn't affect anything
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15758
- 
- 
1.
2.
3. …
=> chore(DB): Correct typo in 2023_04_02_02.sql

src/server/scripts/Outland/Auchindoun/SethekkHalls/boss_talon_king_ikiss.cpp
-  Change order of spells so that Blink actually works
-  
- Closes 
- 
2 Chars
.go c id 18473
Place the chars apart from each other
Tickle Ikiss down to 80% HP …
=> fix(Scripts/Sethekk) Fix Talon King Ikiss Blink

.github/workflows/windows_build.yml
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(CI): Windows build

data/sql/updates/pending_db_world/rev_1680984695073809300.sql, src/server/game/Instances/InstanceScript.cpp, src/server/game/Instances/InstanceScript.h, src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_warlord_kalithresh.cpp, src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp, src/server/scripts/Outland/CoilfangReservoir/SteamVault/steam_vault.h
-  fix distiller chase, add missing emote, add missing intro line
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15839
- 
- 
1.
2.
3. …
=> fix(Scripts/Steamvault): Rework Kalithresh

src/common/Utilities/EventProcessor.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Events): fix infinite loop

data/sql/updates/db_world/2023_04_09_00.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(SQL): Remove select query

data/sql/updates/pending_db_world/rev_1680910484895618500.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Reputation): Correct onkill reputation for Shattered Halls

data/sql/updates/pending_db_world/rev_1680885248680215700.sql
-  And refactor SAI comments
-  Hellfire Imps won't all have Summon Visual
-  Shadowmoon Warlocks won't all use Fel Power
- Closes 
- 
1.
2.
3. …
=> fix(DB/Conditions): Add missing SmartAI conditions to Blood Furnace

data/sql/updates/pending_db_world/rev_1680893261686151600.sql
- Drums of Restoration should only be acquired via reputation.  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14565
- Closes https://github.com/chromiecraft/chromiecraft/issues/4617
https://wowpedia.fandom.com/wiki/Pattern:_Drums_of_Restoration
[Patch 2.3.0](https://wowpedia.fandom.com/wiki/Patch_2.3.0) (2007-11-13): Drums of Speed and Drums of Restoration are no longer world drop recipes, and can now be obtained from the Mag'har and Kurenai faction vendors with revered standing.
- untested
1.
2.
3.
**REMEMBER**: when testing …
=> fix(DB/Loot): Remove `Pattern: Drums of Restoration` from reference loot.

data/sql/updates/pending_db_world/rev_1680812289641554100.sql
Co-Authored-By: Carlos Morales <carlos.morales@insmet.cu>
-  Adds SAI and conditions
-  
- Closes 
- 
1.
2.
3. …
=> fix(DB/Quest): Improve Quest Betrayed (3506) and port from event_script to SAI

data/sql/updates/pending_db_world/rev_1680966459127893700.sql
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14998
- Closes https://github.com/chromiecraft/chromiecraft/issues/5019
Mangos
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Correct respawn timers for 2 TBC quest mobs

data/sql/updates/pending_db_world/rev_1679646147806247600.sql, src/server/scripts/Spells/spell_generic.cpp
- Fix SAI and attempt to script spell [35385](https://www.wowhead.com/wotlk/spell=35385/threshalisk-charge)
- Closes https://github.com/chromiecraft/chromiecraft/issues/5251
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13925
Sniff from @Gultask
```
20607 (Craghide Basilisk)
12:23:28.906
Cast 28728
SMSG_ATTACK_STOP
Flags: 2048, 524288, 536870912
12:23:34.986
SMSG_ATTACK_START
Cast 35385 // Triggers 35382
Emote %s stops playing dead and charges forward
20283 Marshrock Stomper
12:14:32.982
Feign Death
SMSG_ATTACK_STOP
12:14:38.940
(Cast) SpellID: 35385 (35385)
(Spell 35385) Threshalisk Charge - It appears to be self-cast:
(Cast) [0] HitTarget: Full: 0x202F244240141FC000007500059DBDE7 Creature/0 R3017/S117 Map: 530 Entry: 20607 Low: 94223847
```
Wowhead comments/abilities …
=> fix(DB/SAI): Outland Basilisks.

data/sql/updates/pending_db_world/rev_1679480684395742200.sql, src/server/game/Entities/Player/Player.cpp, src/server/scripts/Pet/pet_dk.cpp, src/server/scripts/Spells/spell_dk.cpp
You still can't get resurrected if you have the aura.
This is a temp fix for the ability, until the entire spellscript is ported from trinity or rewritten.
- Correct creature_template_spells
- Add Thrash
- Fix ghoul explosion spam
- Move Risen Ally(30230) to creature script (meant as temp solution. as trinity handles all via spellscript)
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/2605
Trinity
- tested
```
open wow on double window
invite on party
1 player .die
2 player .cast 61999
``` …
=> fix(Spells/Scripts): Raise Ally improvements.

data/sql/updates/pending_db_world/rev_1680530349711913600.sql, src/server/scripts/Outland/zone_netherstorm.cpp
- Remove hardcode and move 20907 (Professor Dabiri) to SAI
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4151
- tested
.go c id 20985
.q a 10439
Check npc_text and gossip before escort starts
Text should be "Fleshling, I am Captain Saeed of the Protectorate..." and gossip " I am that fleshling..."
Start the escort
Check text and gossip again, before Dimensius
Text should be "This is it, $N. We charge on your orders!..." and gossip " I am ready. Let's make history!"
.go c id 20907
.q a 10438
Speak with/without the quest item in inventory and with/without the quest in log.
Gossip should only show when 1) You have the quest 10438 and 2) You don't have the item from the quest …
=> fix(Scripts/Core): Remove hardcode from zone_netherstorm.

data/sql/updates/pending_db_world/rev_1681232229972193910.sql, src/server/scripts/Spells/spell_generic.cpp
Adapted from TC Commits [3ddc6e70df0401a0677bef536e6b0e46e3dbf9e9](https://github.com/TrinityCore/TrinityCore/commit/3ddc6e70df0401a0677bef536e6b0e46e3dbf9e9) and [cc3293c0023b36434747190103a1f0ffee0f8488](https://github.com/TrinityCore/TrinityCore/commit/cc3293c0023b36434747190103a1f0ffee0f8488)
-  Fix blood pool effect being applied, and set position at the top of the water
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15914
Cherry picked TC commits 3ddc6e70df0401a0677bef536e6b0e46e3dbf9e9 and cc3293c0023b36434747190103a1f0ffee0f8488
- Added daily quest "Blood is Thicker" (`.q add 13833`)
- Go to borean tundra, killed animal
- Ran into water and tested the blood pool is created and positioned properly
1. .q add 13833
2. Go to borean tundra
3. Kill an animal (for …
=> fix(Script/Spell): Fix animal blood pool effect and position

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(Scripts/ShadowLabyrinth): Modernize Ambassador Hellmaw

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp
-  timer adaptations based on https://github.com/azerothcore/azerothcore-wotlk/issues/15868
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/15868
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15866
parses shown here:
- https://classic.warcraftlogs.com/reports/HfCRMQVx3hjNqrdF#fight=3&view=timeline&hostility=1&type=casts
- https://classic.warcraftlogs.com/reports/MzrNb7aXKwBp19gZ#fight=4&hostility=1&type=casts&view=timeline
- https://classic.warcraftlogs.com/reports/a2pcFzY6CP8HZQfR#fight=last&type=casts&view=timeline&hostility=1
- https://classic.warcraftlogs.com/reports/BHKP97GrJAcFgdMm#fight=last&hostility=1&type=casts&view=timeline
- testing of individual adds done by me
- more testing needed
1. pull files from my PR
2. recompile
3. go to Gruul's …
=> fix(Scripts/GruulsLair): timing/scripting fixes for High King Maulgar fight

data/sql/updates/db_world/2023_04_15_00.sql, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.h
-  Implement SMART_ACTION_SET_GUID
-  Param 1 =  (1) invoker guid, (2) self guid
- Param 2 = index
- Closes 
- 
- 
1.
2.
3. …
=> feat(Core/SAI): Implement SMART_ACTION_SET_GUID

src/server/database/Updater/DBUpdater.cpp, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.cpp, src/server/game/Chat/ChatCommands/ChatCommand.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/PetHandler.cpp, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/scripts/Commands/cs_character.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
-  clean up on excessive notes
-  no further changes
- Closes 
- no need to test just note clean up
1.
2.
3. …
=> chore (core): Clean up

data/sql/updates/pending_db_world/rev_1681662634958347500.sql, src/common/Utilities/TaskScheduler.cpp, src/common/Utilities/TaskScheduler.h, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h, src/server/scripts/Spells/spell_generic.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/ShadowLabs): Update Murmur script

data/sql/updates/pending_db_world/rev_1681770837660007300.sql, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/ShadowLabirynth): Fix OOC Murmur Supperssion Barrage

data/sql/updates/pending_db_world/rev_1681478008053171600.sql
- Despawn object after being activated.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4986
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15021
https://youtu.be/3CEYVEnEVgQ?t=31
- tested
.go gameobject id 184906
.q a10584
Right click the gameobject
See if it despawns …
=> fix(DB/SAI): Power Converter not despawning.

data/sql/updates/pending_db_world/rev_1681325343035334200.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5402
- 
- 
1.
2.
3. …
=> fix(DB/SAI): Correct Bog Overlord Trample being cast twice

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_blackheart_the_inciter.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
- Corrects timers with sniffs from Gultask.
- Missing Vorpil timer which is handled in this PR already: https://github.com/azerothcore/azerothcore-wotlk/pull/15962
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/15971
https://github.com/azerothcore/azerothcore-wotlk/issues/15971
- 
- 
1.
2.
3. …
=> fix(Scripts/ShadowLabyrinth): Boss spell timers correct values

data/sql/updates/pending_db_world/rev_1681324752444395800.sql
Damage is handled in that other PR
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5401
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Correct damage school of Steamvault Surgers

data/sql/updates/pending_db_world/rev_1681856955718272600.sql
-  And prevent Summoner exploit
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5378
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Add Interrupt Immunity to Murmur

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
**This is the last one from the list (issue) linked so ok for issue closure when merging this PR**
- Closes #15971 …
=> fix(DB/ShadowLabyrinth): Murmur - Sonic Shock's timer

data/sql/updates/pending_db_world/rev_1681039053601489100.sql
-  Enables SAI on Zem Leeward
-  Adds SAI to Zem Leeward so that when OOC he uses his broadcasts on a 10m03sec cooldown as examined
- Closes 
- I sped up the timer and tested the broadcasts to see if they were correctly set.  They were.
1.
2.
3. …
=> fix(DB/SAI): Enables and Adds SAI for Zem Leeward (348)

data/sql/updates/pending_db_world/rev_1681853904720484500.sql
-  
-  
- Closes
- 
- 
1.
2.
3.
=> fix(DB/Loot): Add missing Tailoring Patterns in TBC Normals

data/sql/updates/pending_db_world/rev_1681717535425377600.sql
- Revert https://github.com/azerothcore/azerothcore-wotlk/pull/13496 caused by invalid bug report(s)
- Closes https://github.com/chromiecraft/chromiecraft/issues/5072
Sources in the issue
- tested
Make a mage
Spec 2/2 into Fiery Payback (5% per talent), get hit by melee/ranged attacks, see if it can DR itself/ has no CD. …
=> fix(DB/spell_proc_event): Restore Fiery Payback to have no ICD.

data/sql/updates/pending_db_world/rev_1681470069214190500.sql
-  Remove cast 6136 on aggro
-  Improve Comments on Bloodmaul Geomancer SAI
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15946
- Closes https://github.com/chromiecraft/chromiecraft/issues/4958
- 
- 
.go c 71169
**For …
=> fix(DB/SAI) Bloodmaul Geomancer does not cast Chilled

data/sql/updates/pending_db_world/rev_1681665616875077300.sql
=> fix(DB/creature_addon): Update Patchwerk visibilityDistance

data/sql/updates/pending_db_world/rev_1681592609217864100.sql
- Add immunity flags, previously none.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5068
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15953
Mangos wotlk
-
-
.go c id 21181
See if immune to fear, root, stun, freeze, banish etc. …
=> fix(DB/Creature): Correct Cyrukh the Firelord immunity flags.

data/sql/updates/pending_db_world/rev_1681851219791307300.sql
- Remove vendor flag and vendor items.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5388
https://www.wowhead.com/classic/npc=2910/prospector-ryedol
https://wowpedia.fandom.com/wiki/Prospector_Ryedol
wotlk recycled
- tested
be alliance
.go c id 2910
He should not be a vendor. …
=> fix(DB/creature_template): Remove vendor flag and items from Prospector Ryedol.

data/sql/updates/pending_db_world/rev_1681832671178035000.sql
Can even remove the npc_vendor rows, not that it changes anything.
-  Remove Gossip & Vendor npc flags. (While keeping the npc_vendor rows, they exit in wowhead, check source)
- Closes https://github.com/chromiecraft/chromiecraft/issues/5319
https://wowpedia.fandom.com/wiki/Patch_3.1.0#First_Aid
> You no longer need to learn First Aid from books. The trainers have finally done their reading and are able to teach you the same thing.
https://www.wowhead.com/wotlk/npc=18990/burko#sells
https://www.wowhead.com/wotlk/npc=18991/aresella#sells
- tested
as alliance
.go c id 18990
as horde
.go c id 18991 …
=> fix(DB/creature_template): Remove npc flags from outland First Aid Trainers.

data/sql/updates/pending_db_world/rev_1681594798691444614.sql
- Closes (https://github.com/chromiecraft/chromiecraft/issues/5392)
https://www.wowhead.com/tbc/npc=16473/spectral-performer
- Tested
1. .npc add 16473
2. kill mob
3. …
=> fix(DB/SAI) Curtains Call is now only casted on death.

data/sql/updates/pending_db_world/rev_1681793005385047200.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5440
- Tested
=> fix(DB/ShadowLabyrinth): Fel Overseer - Frightening Shout

data/sql/updates/pending_db_world/2023_04_14_01.sql
Length: Should be translated "全程 / 长度".
-  
-  
- Closes 
It should be like this 
- 
- 
1.
2.
3. …
=> fix(DB/acore_string): Update the value of id 586

data/sql/updates/pending_db_world/rev_1680633363215025800.sql
https://github.com/TrinityCore/TrinityCore/commit/2bf94153bd7f3c75dc899ef56e1ce072cdbb1b55
- Port and correct Trinity SAI
- Closes https://github.com/chromiecraft/chromiecraft/issues/4357
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13624
https://youtu.be/ua6GZjYL5E8?t=33
- tested
.go c id 18482
.q a 9978
Compare to [Source](https://youtu.be/ua6GZjYL5E8?t=33)
Should be able to start combat again when he is friendly and stationary. (And the player meets the conditions) …
=> fix(DB/SAI): Port Quest: 'By Any Means Necessary' from Trinity

src/server/game/Entities/Player/PlayerUpdates.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix: Channel Crash

data/sql/updates/pending_db_world/rev_1681810720948358500.sql
- Port immunities from mangos
- Closes https://github.com/chromiecraft/chromiecraft/issues/5167
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15354
Mangos
- not tested
.go c id 22199,20600,20216,22910,22911
See immunities …
=> fix(DB/creature_template): Port Immunities for Ogrila quest npcs from Mangos.

data/sql/updates/pending_db_world/rev_1681369813867048100.sql
Source https://github.com/TrinityCore/TrinityCore/issues/3234
- Set 21861 (Vision of the Raven God) type to not specified.
- Correct spawn Raven God spawn location for first prophecy. (Was spawning in air and falling down)
- Use storetarget instead of closest player.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4995
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15006
https://www.youtube.com/watch?v=d3UGjMSl5eI&t=128s
- tested
.q a 10607
.cast 37466
.go gameobject id 184950
See if Raven God spawns on the ground and not in the air (and then falls down)
.go gameobject id 184967 / 184968 / 184969
Confirm that the invoker gets whisper and credit. …
=> fix(DB/SAI): Correct creature/objects for quest Whispers of the Raven God.

data/sql/updates/pending_db_world/rev_1681920717306872200.sql
-  Fix Spitelash Serpent Guard equipment
-  Currently has Cata equipment
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16014
Sniffed values (thanks Bench!)
- SQL runs successfully
1. .go cr id 6194
2. Confirm shield is gone …
=> fix(Creature): Spitelash Serpent Guard equipment

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/instance_shadow_labyrinth.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h
-  Convert to new script structure
- Allow [Empowering Shadows] to stack up
=> fix(scripts/ShadowLabyrinth): Update Grandmaster Vorpil's script

src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp
=> fix(scripts/naxxramas): Improve Gothik's minions

data/sql/updates/pending_db_world/rev_1677324467019760400.sql, src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
First time touching creature script (other than few minor changes). If there is something bad or that can be improved, please let me know.
Other than the listed sources, there is nothing else that I can find about it.
- Add a rough estimation of what the event should look like.
- Move creature_text from Thule Ravencla to Ravenclaw Apparition
- Trigger SAI Areatrigger 173 if no Ravenclaw Apparition within 30 yards.
(The event happens once every 5 minutes, upon Apparition despawn)
- Add cheer Rot Hide Gladerunner & Rot Hide Mystic, otherwise it would've been a hardcode (idk which one is better, db or hardcode, probably db even if it's not exact)
- none
https://www.wowhead.com/wotlk/npc=2056/ravenclaw-apparition
https://wowwiki-archive.fandom.com/wiki/Ravenclaw_Apparition
creature_text and …
=> fix(Scripts/Creature): Add Ravenclaw Apparition event.

data/sql/updates/pending_db_world/rev_1682123448347196000.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5464
- 
- 
1.
2.
3. …
=> fix(DB/Loot): Correct MinCount for Cabal Acolyte Fel Armaments

data/sql/updates/pending_db_world/rev_1682120419110815800.sql
-  Re-add loot to Summoners and Spellbinders
-  Re-add Combat SAI to scripted summoners in case players manage to CC/engage them
-  Tweak Spellbinders near Murmur to re-cast Blackfathom Channeling
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16051
- Closes https://github.com/chromiecraft/chromiecraft/issues/5462
- Closes https://github.com/chromiecraft/chromiecraft/issues/5466
- Closes https://github.com/chromiecraft/chromiecraft/issues/5467
- 
- 
1.
2.
3. …
=> fix(DB/ShadowLabyrinth): Adjust values for Murmur's Arena

data/sql/updates/pending_db_world/rev_1681942737921129600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4881
- Closes #16035 …
=> fix(DB/Karazhan): The Curator - Aggro range

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5474
- 
- 
1.
2.
3. …
=> fix(Scripts/ShadowLabs): Fix Murmur Touch dealing damage twice

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> refactor(Scripts/ShadowLabirynth): Rework Grandmaster Vorpil

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_ambassador_hellmaw.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/instance_shadow_labyrinth.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/shadow_labyrinth.h
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/ShadowLabirynth): Clean up script and fix doors

data/sql/updates/pending_db_world/rev_1682223226213485600.sql, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
-  Fix wrong Death Coil spell being used
-  Remove custom add spawns, replace with sniffed spawns
-  Remove custom flag usage
-  Makes boss available again after https://github.com/azerothcore/azerothcore-wotlk/commit/3dc7a89ad2640c2125ec2db5a34ab9af8b706cd6
- Closes 
- 
1.
2.
3. …
=> fix(Scripts/ShatteredHalls): Update Grand Warlock Netherkurse

data/sql/updates/pending_db_world/rev_1682245181189379600.sql
- Add flee to Assasin and Muckdweller, also move stealth for assasin to _addon  
- Link Servant's bandage to bandage debuff
servant - bandage + no flee https://youtu.be/jj6BBHasHXM?t=143
Assasin and Muckdweller - flee https://youtu.be/Hnd2fYXYanc?t=143
- tested
.go c id 18116/18115, see if they flee when less than 15%
.go c id 19733, see if they cast bandage on nearby friendlies when below 25% hp and if the debuff is applied correctly. …
=> fix(DB/SAI): Correct Daggerfen npcs

data/sql/updates/pending_db_world/rev_1680621050146554400.sql
-  Ports many walk/run values from Vmangos
-  Vmangos values all line up with Neifion's sniffed values, so I think they are reliable
VMangos
- SQL runs successfully
1. Go to any of the affected creatures, check walk and run speed
If we would prefer to wait for Neifion to sniff everything that is also an option, but hopefully this will save Neifion some work ^_^ …
=> fix(DB/creature): Port more VMangos Walk/Run Values

src/common/Collision/Management/MMapMgr.cpp, src/server/database/Updater/UpdateFetcher.cpp, src/server/game/AuctionHouse/AuctionHouseMgr.cpp, src/server/game/AuctionHouse/AuctionHouseMgr.h, src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp, src/server/game/Chat/Channels/ChannelMgr.cpp, src/server/game/Combat/ThreatMgr.h, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerSettings.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Guilds/Guild.cpp, src/server/game/Guilds/Guild.h, src/server/game/Maps/Map.cpp, src/server/game/World/World.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp, src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp, src/server/scripts/EasternKingdoms/ZulGurub/boss_venoxis.cpp, src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp, src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp, src/server/scripts/Northrend/DraktharonKeep/boss_novos.cpp
Suggestions from VS2022 code analysis
- Closes 
- 
- 
1.
2.
3.
=> chore(core): cleanup code p3

data/sql/updates/pending_db_world/rev_1682400962878780400.sql
She does not stop when spoken to, but this is generic afaik.
- Remove vendor flag and vendor items.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15769
in the issue
- not
.go c id 23734
see that she is no longer a vendor. …
=> fix(DB/creature_template): Remove vendor flag from Anchorite Yazmina.

data/sql/updates/pending_db_world/rev_1682122564998006700.sql
-  Add flag_extra
-  Fix unrelated SAI >.>
- Closes https://github.com/chromiecraft/chromiecraft/issues/5461
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Fixed chain pulling in Blackheart's Arena

data/sql/updates/pending_db_world/rev_1682514542784724300.sql
-  Fix Tortured Skeletons having wrong flags
-  Fixed most gameobjects having spawnMask 1, and thus missing from Heroic
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16071
- 
1.
2.
3. …
=> fix(DB/ShadowLabyrinth): Fixes for Heroic Shadow Labyrinth

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/World/IWorld.cpp, src/server/game/World/IWorld.h, src/server/game/World/World.cpp, src/server/game/World/World.h
This is the address the issue of select combat animation not playing with the player's attacks\spells due to killing blows ending the player's spell animation instantly before playing out fully or at all.
Process damage dealt by players in 400ms batches so that spell effects will show correctly when a spell is used to kill the target.
Player animation goes thru 9/10 of the time with some weird edge case of if you kill the npc before they get set in combat while turning wont play it, pretty much what is already happening already, so no regression with that. 
No Sleep threads or Loop Timers implemented. Will need a population to test to ensure no crashing or freezing as I am only doing this solo wise on my local and was hit with this idea while high on sugar booger while mid script with a …
=> fix (core\player): Missing combat animation

data/sql/updates/pending_db_world/rev_1675980483756273400.sql
-  Originally from TC, can however not find the original author
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Spawn and Script Pool of Souls

data/sql/updates/pending_db_world/rev_1682710323496877200.sql
-  Mostly corrects timers taking from ACID, TC and Sniffs
-  Fixed Bleeding Hollow Darkcaster using wrong Rain of Fire spell
-  Greatly increase Kidney Shot timer
- Closes 
- 
- 
1.
2.
3. …
=> fix(DB/SAI): Tweak SAI for Hellfire Ramparts

data/sql/updates/pending_db_world/rev_1682810005438594300.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Spell): Essence of Wintergrasp 

data/sql/updates/pending_db_world/rev_1682810922102457000.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Warden): New checks

src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp, src/server/scripts/Outland/HellfireCitadel/BloodFurnace/instance_blood_furnace.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(Scripts/BloodFurnace): Clean up unused code in Broggok script

data/sql/updates/pending_db_world/rev_1683034504648319100.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5538
TC
- 
- 
1.
2.
3. …
=> fix(DB/Event): Correct Orphan Matron Mercy item restoration gossip

data/sql/updates/pending_db_world/rev_1682964437089894300.sql
-  And remove questgiver flag
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5387
TC and Mangos
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Add Namdo Bizzfizzle

data/sql/updates/pending_db_world/rev_1683251018722971200.sql
- Moves Warder guid SAI to new system
- Fixes Warder pathing and formations
- Adds more Target Triggers and assigns correct movement
- Assigns one trigger's id to the correct one
- Closes https://github.com/chromiecraft/chromiecraft/issues/5348
Retail
- 
- 
1.
2.
3. …
=> fix(DB/MagtheridonLair): Revamp Magtheridon's Lair spawns

data/sql/updates/pending_db_world/rev_1682710323496877200.sql
-  I didn't touch Slaves or Slavehandler RP but it is NOT blizzlike
-  Neither is the Slave escape but Retail doesn't look reliable
- Closes 
TC, ACID, Retail
- 
- 
1.
2.
3. …
=> fix(DB/SAI): Rework The Slave Pens Trash SAI

data/sql/updates/pending_db_world/rev_1683258798551630600.sql
-  Adds pathing, formation and tweaks SAI a lil bit
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5194
MangosDB
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Add pathing to Zandras

data/sql/updates/pending_db_world/rev_1683170469129035500.sql
Same mechanic is used in Skettis
- Remove hack
- Make them not attack while invisible
- Closes 
Build 48069
- ye
- 
1. `.q a 10633` OR `.add 30721` OR `.aura 37495`
2. `.go c id 21815` for Clerics
3. `.go c id 21784` for Ghostriders, there are 2 groups that run clockwise and counter-clockwise along the main circle around Shadowmoon, but they spawn near the road around Black Temple
4. See if they attack while you have the buff, and do not attack otherwise (when invisible) …
=> fix(DB/Creature): Correct Cleric and Ghostrider of Karabor factions

src/server/game/Entities/Unit/Unit.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16180
- 
- 
1.
2.
3. …
=> fix(Vehicle): Crash

src/server/game/Globals/ObjectMgr.cpp
Wrong format occurred (invalid format string)
-  
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(Core/ObjectMgr.cpp): Wrong format occurred (invalid format string)

data/sql/updates/pending_db_world/rev_1668017149389906100.sql
-  adds CTM
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13758
- Closes https://github.com/chromiecraft/chromiecraft/issues/3865
- Tested a bit but I couldn't reproduce it in the first place 🤷 
- 
1. .learn 688
2. `.go c id 9938` Go straight to the gates to last boss room. Then kite the boss to the gates at the start
3. Repeat until golem starts attacking imp …
=> fix(DB/Creature): Root Ironhand Guardian

src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_omor_the_unscarred.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_watchkeeper_gargolmar.cpp
-  use taskscheduler instead of events
-  
- Closes 
- seems to work fine
- needs some proper testing from others to ensure old behaviour is not broken
1. run through Hellfire Ramps, preferable with 2 test chars
2.
3. …
=> fix(Scripts/HellfireRamparts): modernise boss scripts for Hellfire Ramparts

data/sql/updates/pending_db_world/ravenous_windroc.sql
-  change comment on Windroc to be more descriptive
-  add ability
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16192
see issue
- 
- 
1.
2.
3. …
=> fix(DB/Nagrand): add missing ability to Ravenous Windroc

data/sql/updates/pending_db_world/bashir_new_gold_rates.sql
-  change mingold to 448
-  change maxgold to 2520
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15850
- research drive link: https://docs.google.com/spreadsheets/d/11Wz9RS0uYH0EgtwnwHcztyzy_zZz-A0F2KYaDYSwx9U/edit?usp=sharing
- 
- 
1. `.tele bashirlanding`
2. kill mobs
3. test whether loot is closer to tbc classic/wotlk classic values now …
=> fix(DB/Loot): fix gold drops of ethereal mobs in Bash'ir Landing

src/server/game/Entities/Player/Player.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15952
Script is from PaperDollFrame
PaperDollFrame shows Health Regen / second
Health Regen ticks are every 2 seconds
target self
.damage 1000
note down the value restored and the time between ticks
compare to value displayed by hovering over the spirit stat …
=> fix (Core/Player) Double health regen from spirit

data/sql/updates/pending_db_world/rev_1683530792489127900.sql
- Closes #16189
[patch 3.0.2](https://wowpedia.fandom.com/wiki/Flameshocker#Patch_changes)
[mangos](https://github.com/cmangos/mangos-tbc/search?q=EVENT_MINION_FLAMESHOCKERS_TOUCH)
- Tested …
=> fix(DB/creature_template): Adjust Flameshocker's values

data/sql/updates/pending_db_world/rev_1682576689740907500.sql
- Add RP upon quest completion.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5509
https://wowpedia.fandom.com/wiki/Strange_Brew_(quest)
https://youtu.be/jw6eXc81G2o?t=231 - rp is delayed
- tested
.go c id 21151
.q a 10511
.q c 10511
Turn in the quest, after 5s he will say the line. …
=> fix(DB/SAI): Add RP for Quest - `Strange Brew` completion.

data/sql/updates/pending_db_world/fix-orphic-bracers-loot.sql
-  Remove `Orphic Bracers` from the `reference_loot_template` which is used by 746 `creature_loot_template`.
-  Created the 4 specific `creature_loot_template` rows for the `Orphic Bracers`.
- Closes nothing, there were no reports.
They all shows the same 4 mobs.
Classic Vanilla WowHead: https://www.wowhead.com/classic/item=18337/orphic-bracers
Classic TBC WowHead: https://www.wowhead.com/tbc/item=18337/orphic-bracers
Classic Wrath WowHead: https://www.wowhead.com/wotlk/item=18337/orphic-bracers
WoWWiki: https://wowwiki-archive.fandom.com/wiki/Orphic_Bracers
Wowpedia: https://wowpedia.fandom.com/wiki/Orphic_Bracers
- 
1. Grind! …
=> fix(DB/Loot): Orphic Bracers

data/sql/updates/pending_db_world/rev_1677938661497953700.sql
- Make the RP blizzlike
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13132
- Closes https://github.com/chromiecraft/chromiecraft/issues/4067
https://youtu.be/LzmXDQ1DlyE?t=53
https://youtu.be/gZyx81kIXG4?t=220
- tested
make a rogue
.level 19
.q a 2381
.go xyz -1456 -3959 0 1
.learn 1804
.maxskil
.additem 7970
Click the box, confirm that the summoned Polly is level 50
Use the the item
Compare the provided source to AC. …
=> fix(DB/Creature): Plundering the Plunderers - Polly improvements.

data/sql/updates/pending_db_world/rev_1684044915713162200.sql, src/server/scripts/Outland/HellfireCitadel/BloodFurnace/blood_furnace.h, src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_broggok.cpp, src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_kelidan_the_breaker.cpp, src/server/scripts/Outland/HellfireCitadel/BloodFurnace/boss_the_maker.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_omor_the_unscarred.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_watchkeeper_gargolmar.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/hellfire_ramparts.h, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warbringer_omrogg.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warchief_kargath_bladefist.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
- Need to know how to move these:
[events.SetPhase(0); to scheduler](https://github.com/azerothcore/azerothcore-wotlk/pull/16264/files#diff-2bcf8056ee31e42c8931be1683035afb753c1601c2ebcc3517dea687d5b1a421R119)
[events.SetPhase(1); to scheduler](https://github.com/azerothcore/azerothcore-wotlk/pull/16264/files#diff-2bcf8056ee31e42c8931be1683035afb753c1601c2ebcc3517dea687d5b1a421R131)
[!events.IsInPhase(1) to scheduler](https://github.com/azerothcore/azerothcore-wotlk/pull/16264/files#diff-2bcf8056ee31e42c8931be1683035afb753c1601c2ebcc3517dea687d5b1a421R173) …
=> fix(scripts/HellfireCitadel): Mass struct/model update

src/server/game/Entities/Player/PlayerStorage.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/16201
-  
-  
- Closes 
- 
1. Enable Instance.IgnoreRaid config
2. Go into a raid
3. Log out
4. Log in …
=> fix(Core/Player): Instance.IgnoreRaid kicking people out

data/sql/updates/pending_db_world/rev_1684593078469435100.sql
-  Some visual auras, some unit_flags, mostly equipment
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Misc fixes for TBC Heroic dungeons

data/sql/updates/pending_db_world/rev_1684618396046160600.sql
- Add the "pre-spawn" Blood Guard Porung adds
- Add movement to the Warchief Kargath Bladefist adds
https://github.com/azerothcore/azerothcore-wotlk/assets/100873791/163fb813-ff8f-4437-917f-95b1e8f63c9c
(yes I fixed the wonky movement of that one)
- Closes 
- 
- 
1.
2.
3. …
=> fix(DB/ShatteredHalls): Implement scripted adds for Porung and Kargath

data/sql/updates/pending_db_world/rev_1684108506441826000.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
-  Fix the intro roleplay, nethekurse always walks, fix void zones 
-  
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/16070
- 
1.
2.
3. …
=> chore(Scripts/ShatteredHalls): Rework Nethekurse

data/sql/updates/pending_db_world/rev_1684616338556943400.sql, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warbringer_omrogg.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
-  Rewrite the whole script.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16079
- Tested in-game. More needed though :)
1. Go to Shattered Halls and fight O'mrogg. 
2. Check https://github.com/Gultask/Research-Wotlk/issues/7#issuecomment-1520811733
=> fix(Core/Scripts): Rewrite Warbringer O'mrogg

data/sql/updates/pending_db_world/rev_1684773536924402300.sql, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warchief_kargath_bladefist.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/shattered_halls.h
-  Rewrite the whole script... 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16092
https://github.com/Gultask/Research-Wotlk/issues/7#issuecomment-1524592214
1. Go to Kargath, engage.
=> fix(Core/Scripts): Rewrite Warchief Kargath Bladefist

data/sql/base/db_characters/characters.sql, data/sql/updates/pending_db_characters/rev_1684700137059902900.sql
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/16314
* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/fb388298a0bf76402a6f1de35bdfcb33223d51bb)
-  
-  
- Closes 
1.
2.
3. …
=> fix(DB/Character): Allow names to be accent senstive

data/sql/updates/pending_db_world/rev_1684697962199868700.sql
https://www.wowhead.com/wotlk/spell=33096/threaten#used-by-npc
https://youtu.be/FBPQlr_VgJo?t=918 …
=> fix(DB/creature_template_spell): Add "Threaten" spell to "Wild Fel Stalker"

src/server/game/Entities/Player/PlayerStorage.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Player): Logic

data/sql/updates/pending_db_world/rev_1684493123181040400.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Loot): Overtuned loot drops in Hellfire Citadel dungeons

data/sql/updates/db_world/2023_05_21_01.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(SQL): fix delete query

data/sql/updates/pending_db_world/rev_1685245089801017800.sql
For some reason DATA SET for these 2 particular Legionnaires was playing SET_COUNTER event twice in a row, so doubling the amount needed for the counter is a workaround for it
- Closes 
- 
1.
2.
3. …
=> fix(DB/ShatteredHalls): Fix Legionnaires in Sparring Hall calling 2 adds at a time

src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/ShatteredHalls): Fix Nethekurse delay after peon dies

data/sql/updates/pending_db_world/fix-loot-shh.sql
-  change to 0.5% from 5%
-  
- Closes 
Mangos
- no tests
- 
1.
2.
3.
=> fix(DB/ShatteredHalls): Lower chance on pattern drops for Shattered Hand Legionnaire

src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_warchief_kargath_bladefist.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Script): Kargath should prevent adds spawn on death

data/sql/updates/pending_db_world/rev_1685290938570269300.sql, src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
-  Adds NON_ATTACKABLE flag on spawn, remove on Intro RP
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(Scripts/Nethekurse): Prevent boss from being pulled early

src/server/scripts/Outland/boss_doomlord_kazzak.cpp, src/server/scripts/Outland/boss_doomwalker.cpp
=> refactor(scripts/Outland): World Boss model update

src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_captain_skarloc.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_epoch_hunter.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_lieutenant_drake.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.h, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_aeonus.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_chrono_lord_deja.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/boss_temporus.cpp
=> refactor(scripts/CavernsOfTime): Mass struct/model update

src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16392
- 
- 
1.
2.
3. …
=> fix(Scripts/ShatteredHalls): Fire Executioner's call on heroic only

src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/boss_nethekurse.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5681
- 
- 
1.
2.
3. …
=> fix(Scripts/ShatteredHalls): Nethekurse shouldn't roleplay in combat

data/sql/updates/pending_db_world/rev_1684953661179621591.sql
-  adds creature formations for trash in the last boss room of ZF
Affected GUIDs:
Sul'lithuz Abomination (Blue)
- 81527*
- 81565
Sandfury Guardian (Red)
- 37998*
- 37999
- 38000
- 38001
Bosses are Yellow and do not pull with either group.
- adds pull separately when they should all be linked together
- Sul'lithuz Abomination: https://youtu.be/I9dOA-PktnM?t=1743
- Sandfury Guardian: https://youtu.be/I9dOA-PktnM?t=1769
- tested in-game, adds pull in correct groups without aggro'ing the boss
1. `.go xyz 1767.853394 1067.639038 45.800163 209 3.907347`
2. Pull one Sul'lithuz Abomination and observe the other one aggro
3. Pull one side of the Sandfury Guardians and obverse the other side aggro
None …
=> fix(DB/SAI): Zul'Farrak - Adds creature_formations for trash in the last boss room

src/server/scripts/World/npcs_special.cpp
- removes tick-based health reduction to patients and replaces with an emulation of the originally-intended effect
- fills all patient beds immediately to match Blizzlike behavior
- continue summoning patients long enough to complete the quest objective
- don't kill the last patient saved
- make patients invulnerable to non-quest-item healing
- Closes #16161
- Closes chromiecraft/chromiecraft#5507
- personal questing
- completed Alliance version successfully multiple times
- completed Horde version
1. Have First Aid skill of at least 225
2. Go to Doctor Gustaf VanHowzen (Alliance, 12939) or Doctor Gregory Victor (Horde, 12920)
3. Start quest, observe patients in beds
4. Use quest item to heal patients
5. Note completed quest
- True BlizzLike would have each of the patients being replaced …
=> fix(Scripts/Quest): Make quest "Triage" (6622/6624) completable

data/sql/updates/pending_db_world/future-is-now-old-man.sql
- put him in the location he should be in  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16404
- Closes https://github.com/chromiecraft/chromiecraft/issues/5542
Sniffs from bench
- tested ingame -> location seems correct
- 
1. go to Shatt
2. go to the lake
3. look at the location he should be, linked in the issue. he is there now!
none …
=> fix(DB/TerokkarForest): put Old Man Barlo in the right position

data/sql/updates/pending_db_world/rev_1685124320508720600.sql
-  condition: apply specific target for control 
- 
- 
1.
2.
3.
=> fix(DB/Quest): improve Teleport This!

data/sql/updates/pending_db_world/273.sql
-  Missing Text for Tavernkeep Smitts
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16205
- Closes https://github.com/chromiecraft/chromiecraft/issues/5436
https://wowpedia.fandom.com/wiki/Tavernkeep_Smitts?so=search
https://github.com/TrinityCore/TrinityCore/commit/63f050ea966b096c90cf56ddb6a6a75710428f14
.go cr 4193
1. Local …
=> add(DB/NPC) Missing Text for Tavernkeep Smitts

data/sql/updates/pending_db_world/346.sql
-  NPC Barkeep Daniels - Texts missing
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16208
- Closes https://github.com/chromiecraft/chromiecraft/issues/5441
https://wowpedia.fandom.com/wiki/Barkeep_Daniels
https://github.com/TrinityCore/TrinityCore/commit/76502ccba10c1b1907faf5304431342832722057
- Local
- 
1. go cre id 346
2.
3. …
=> add(DB/NPC) NPC Barkeep Daniels - Texts missing

data/sql/updates/pending_db_world/gostly-philantropist-to-jail.sql
-  change loot dropped to 0
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16286
see wowpedia patch notes. In wotlk, so also on AC, they should not drop any gold. This was probably done to prevent farms
- 
- 
1.
2.
3. …
=> fix(DB/Karazhan): Ghostly Philanthropists drop no gold in wotlk

data/sql/updates/pending_db_world/remove_restless_skel_rep.sql
-  remove onkill rep
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16270
- Closes https://github.com/chromiecraft/chromiecraft/issues/5607
- 
- 
1.
2.
3. …
=> fix(DB/Karazhan): remove Sha'tar rep gain from Restless Skeletons

data/sql/updates/pending_db_world/idontlikemakingthisthroughthewebsite.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5706
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Charming Totem Movement (Heroic)

data/sql/updates/pending_db_world/update-jinzallah-spawn-posis.sql
-  move him to the hut
-  
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/16393
- Progress https://github.com/chromiecraft/chromiecraft/issues/1222
found from parsing a sniff supplied to me:
`Position: X: -7195.0405 Y: -2979.6877 Z: 9.052029
Orientation: 5.340707302093505859`
- 
- 
1.
2.
3. …
=> fix(DB/Tanaris): correct position of Jin'Zallah the Sandbringer

data/sql/updates/db_world/2023_05_28_03.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB): Fix typo in 2023_05_28_03.sql

data/sql/updates/pending_db_world/rev_1685675135891070502.sql
-  adds additional SAI actions to despawn the various add types in the room upon death
- adds continue to attack players after Arcahedas dies
https://youtu.be/MSlqelUouNQ?t=142 - shows the adds despawning after boss death
1. `.go creature 33537`
2. Kill Archaedas
3. Observe adds despawning
- this is an improvement but doesn't yet match Blizzlike. Looks like the spell that is supposed to take out all the adds isn't working. I don't have the skills to fix that yet, but I can at least get us closer and save players a run back if they defeat the boss and then get killed by adds. …
=> fix(DB/Creature): Archaedas despawns his adds after dying

data/sql/updates/pending_db_world/rev_1686082520826526400.sql
-  Add missing silence and turn flag.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5721
=> fix(DB/BlackMorass): added missing immunities to Rift Lord/Keeper

data/sql/updates/pending_db_world/update-shh-immunities.sql
- change a variety of immunities on trash mobs
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16477
- Closes https://github.com/chromiecraft/chromiecraft/issues/5704
See issue. More sources/tests on retail/wotlk classic are welcome
- not tested
- 
Query DB:
```sql
SELECT * FROM `creature_template` WHERE `entry` IN (16507, 16700, 17465, 17670, 17671); -- normal
SELECT * FROM `creature_template` WHERE `entry` IN (20593, 20589, 20583, 20588, 20584, 20582, 20590, 20587, 20586); -- heroic
```
Or test in-game -> please report back …
=> fix(DB/ShatteredHalls): add CC immunities to a variety of trash mobs

apps/ci/ci-pending.sh
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(CI): Restore broadcast_text check

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/ShadowLabirynth): Fix Murmur not using abilities

data/sql/updates/pending_db_world/rev_1686855645703861100.sql
=> fix(DB/ShatteredHalls): Make triggers invisible to players

data/sql/updates/pending_db_world/rev_1686857040635595500.sql
=> fix(DB/ShadowLabyrinth): Make trigger invisible to players

data/sql/updates/pending_db_world/rev_1686855204524860800.sql
-  N mode is ok / H mode isn't - adding dungeon boss level immunity
=> fix(DB/ShatteredHalls): Add CC immunity to (H) Blood Guard Porung

data/sql/updates/pending_db_world/rev_1686948961677753100.sql
-  
-  
- Closes 
That's the midsummer icon
- 
- 
.go gameobject 28242
=> fix (DB) Add game_event_object entry for Midsummer Banners in Shattrath

data/sql/updates/pending_db_world/fix-hc-loot-bosses-ohf.sql
-  remove the normal pieces that were dropping from the loot tables
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16552
**CC**:
- Closes https://github.com/chromiecraft/chromiecraft/issues/5772
- Closes https://github.com/chromiecraft/chromiecraft/issues/5774
- Closes https://github.com/chromiecraft/chromiecraft/issues/5775
Logic + wowhead
- not tested in-game
- 
1. Run OHF and use gm commands to go up to the bosses and kill them a couple of times with `.respawn` afterwards ensuring they really don't drop the normal pieces anymore
2.
3. …
=> fix(DB/EscapeFromDurnholde): remove normal loot drops from OHF bosses (Drake, Skarloc, Epoch Hunter)

data/sql/updates/pending_db_world/rev_1686619097901055400.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5736
- 
- 
1.
2.
3. …
=> fix(DB/Gameobject): Add heroic version of Cache of the Legion

data/sql/updates/pending_db_world/rev_1686779435224151475.sql
SAI from Sharpshooter Guard
-  Add Scatter Shot to Shattered Hand Sharpshooter
- Closes https://github.com/chromiecraft/chromiecraft/issues/5679
https://www.wowhead.com/wotlk/npc=16704/shattered-hand-sharpshooter#abilities;mode:normal
https://wowpedia.fandom.com/wiki/Shattered_Hand_Sharpshooter
-  Tested
1. .npc add 16704 …
=> fix(DB/SAI)Add Scatter Shot to Shattered Hand Sharpshooter

data/sql/updates/pending_db_world/rev_1685926790862483900.sql
-  **Fix Spell: disabling LOS from the Spell 26522** [Lucky Lunar Rocket (Spell Item)](https://wowgaming.altervista.org/aowow/?spell=26522) **Item:** [Lucky Rocket Cluster](https://wowgaming.altervista.org/aowow/?item=21744)
_I disabled the Spell LOS as suggested by:_ @Gultask 
- Closes: https://github.com/chromiecraft/chromiecraft/issues/2886
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16475
- **Video Test:** [Lucky Rocket Cluster](https://youtu.be/sXR4cKifJb0)
1.
2.
3. …
=> Fix(DB/GameObjects): Cluster Launcher

data/sql/updates/pending_db_world/rev_1686942698941660200.sql
-  Add base dungeon-boss level cc immunity
=> fix(DB/ManaTombs): Add CC immunity to Yor

data/sql/updates/pending_db_world/rev_1687026584471372200.sql
- Closes #16262
- Closes https://github.com/chromiecraft/chromiecraft/issues/5593
https://www.wowhead.com/wotlk/quest=182/the-troll-cave
https://youtu.be/TL2EfrN0VQI
1. Delete cache (with client closed)
2. Apply query
3. Start server & client
4.  **.q a 182** …
=> fix(DB/quest_template): Change quest requirement for "The Troll Cave"

data/sql/updates/pending_db_world/rev_1687040404660689100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5795
=> fix(DB/creature_template): Make 'Grandmaster Vorpil' not interruptible

data/sql/updates/pending_db_world/rev_1686617579364661600.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Creature): Lower TBC Heroic bosses to level 72

src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.h
Rework time rift spawning logic slightly to:
- Fix time rifts spawning after Medivh's death
- Fix unreported issues (see below)
Also:
- Automatically cleanup and re-enable event 5 minutes after failure (Shield down and Medivh dead) instead of only relying on player behaviour to reset it
- Cleanup unused variables
- Fix typos
- Closes #16400 and https://github.com/chromiecraft/chromiecraft/issues/5750
Also fixes several unreported issues:
- A softlock indefinitely preventing time rifts from spawning and blocking players from clearing the event (can further explain if necessary)
- Prevent the instance from being half-reset when all players leave and reenter while event still in progress
- Visual fixes to Medivh's casting animation when the event has been failed and is retried
Regarding the …
=> fix(Scripts/TheBlackMorass): rework time rift event logic

src/server/game/Entities/Player/PlayerStorage.cpp, src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp
- Added hearthstone mechanic after approximately 2 and a half minutes where the party from Bly "hearths" home
-  also found an apparent bug where if you had already talked to Bly once, a boolean would be fire upon getting that gossip menu, which was also used in its condition. So this bugged the event if you closed the window. I fixed this too
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11773
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16316
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16317
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16318
- Closes https://github.com/chromiecraft/chromiecraft/issues/5546
See issue above
- tested by myself. should work
- 
1. go to ZF
2. start the pyramid event
3.
When a PR …
=> fix(Scripts/ZulFarrak): add Hearthstone mechanic to Blys party when event not started in time

data/sql/updates/pending_db_world/rev_1687097711262524400.sql
- This affects item [Short Bastard Sword](https://www.wowhead.com/wotlk/item=3192/short-bastard-sword) and [Training Sword](https://www.wowhead.com/wotlk/item=8178/training-sword)
- Verify this by running 
- ```sql
SELECT * FROM item_template WHERE randomproperty = 5173;
SELECT * FROM item_template WHERE randomsuffix = 5173;
```
-  This removes the following enchants from item_enchantment_template 5173
db_itemrandomproperties_12340
---
| id | NAME | name_lang_enus | 
| ---: | --- | --- | 
| 29 | of Toughness | of Toughness | 
| 33 | of Quality | of Quality | 
| 91 | of Beast Slaying | of Beast Slaying | 
| 197 |  | of Toughness | 
| 231 |  | of the Falcon | 
| 927 | of the Gorilla | of the Gorilla | 
| 1399 | of Fire Resistance | of Fire Resistance | 
| 1913 | of Holy Wrath | of Holy …
=> fix(DB/Item): Remove wrong RandomProperties enchantments

src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/Karazhan): Malchezaar should not cast Enfeeble on phase 3

data/sql/updates/pending_db_world/netherwebvictim.sql
-  set proper flags
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14314
- Closes https://github.com/chromiecraft/chromiecraft/issues/4632
- tested
-  …
=> fix(DB/Creature): Netherweb Victim should not move or attack

src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp
-  Minor clean-up.
-  Add missing scheduler update x.x
-  Only Vazruden the Herald behaves like a boss controller, it's the only one that should change the boss state.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5792
1. Go to Hellfire Ramparts and engage Vazruden the Herald.
2. Check that the dragon is now casting abilities and not standing still in the middle.
=> fix(Core/HellfireRamparts): Fix Nazan not casting abilities

data/sql/updates/pending_db_world/FixMaiZothFrostArmor.sql
-  Mai'Zoth now casts Frost Armor
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16582
- Closes https://github.com/chromiecraft/chromiecraft/issues/5556
Wrath Classic
https://www.wowhead.com/wotlk/spell=12544/frost-armor
https://www.wowhead.com/wotlk/npc=818/maizoth#abilities
https://youtu.be/_Ppcj-ZdT58?t=282
Tested
- .go c id 818 he must have frost armor on
- kill and respawn, he must buff himself as soon as he spawns
- purge/dispel and he must rebuff (if enough mana)
=> fix(DB/SAI): Mai'Zoth casts Frost Armor

data/sql/updates/pending_db_world/rev_1687383780751220300.sql
-  Correct level gain effect.
-  Change of faction according to sniff.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3775
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12391
- In-game
- Windows 10
1. .go c 75965
2. .quest add 9303
3. Make the quest and test the changes.
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/b2cf2047-eb99-4c13-864e-a66e3bccb30f …
=> Fix (Quest/SmartScript) Inoculation - ID: 9303

data/sql/updates/pending_db_world/rev_1687568644157138400.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Creature): Avoid Chain-pulling in Auchenai Crypts

src/server/game/Entities/Player/Player.cpp, src/server/game/Handlers/LootHandler.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptMgr.h
- Hook CanSendErrorAlreadyLooted
- Hook OnAfterCreatureLoot
- Hook OnAfterCreatureLootMoney
- Closes 
- In-game
- Windows 10
1. The truth is that it is difficult to test the pull request without the module as such, but the module does not work if we do not have the 3 hooks in the emulator.
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/fdf35a3a-bc6a-447f-91bd-2f52732b6f4e
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/24dd6685-8e9f-4980-83f6-518018412cc6 …
=> chore(Core/ScriptMgr): Hooks used in mod-aoe-loot

data/sql/updates/pending_db_world/powerheal.sql
-  I forgor 💀 
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Trainer): Add missing Powerheal 4000 Lens to Engineering trainers

data/sql/updates/pending_db_world/rev_1687609506371262000.sql, src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
-  Clean up code style, make code cleaner, remove AI cast
-  
- Closes 
- 
- 
1.
2.
3. …
=> refactor(Scripts/SlavePens): Clean up Ahune script

data/sql/updates/pending_db_world/rev_1687646564965572500.sql, src/server/scripts/Events/midsummer.cpp
-  I have no idea why this was added or its purpose. No other public cores have this NPC scripted.
- Closes 
- 
- 
1. So far I tried a few quests and they don't seem to be broken as far as I can see
2.
3. …
=> fix(Scripts/Midsummer): Stop Bonfires from spawning more gameobjects

src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/SlavePens): Add Chilling Aura to Ahune adds

src/server/game/AI/SmartScripts/SmartScript.cpp
- 
- Closes 
- Tested ingame with creatures that used target type SELF and NONE to stop follow
- 
Investigate any of the following:
`.go c 138920`
`.go c id 4781`
`.go c id 8668`
`.go c id 17953`
`.go c id 20400` …
=> chore(Core/SAI): Allow ACTION_FOLLOW to stop follow movement if target type is SELF or NONE

src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5840
- Closes https://github.com/chromiecraft/chromiecraft/issues/5839
- 
- 
1.
2.
3. …
=> fix(Scripts/SlavePens): Despawn Frozen Core after Ahune emerges

src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_ionar.cpp
-  Remove nature immunity from Ionar
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16469
https://www.wowhead.com/npc=28546/ionar/normal-encounter-journal#comments;mode:normal
> Psych
10-08-2009, 06:57 PM
As it was the double daily for me yesterday, I figured I'd give heroic HoL a try on my 5 druid group (one resto, one bear, 3 moonkin). No issues anywhere up until Ionar (with the exception of the Slag guys which are immune to nature damage, forcing me to either swipe them to death or use starfire...ugh, waste of mana!).
https://www.dual-boxing.com/archive/index.php/t-25247.html
However wowwiki states the opposite
- 
- 
1.
2.
3. …
=> fix(Scripts/Ionar): Remove nature damage immunity

src/server/apps/worldserver/Main.cpp
-  Introduced https://github.com/azerothcore/azerothcore-wotlk/commit/4fbec972a8fe55d73744205322298791ded0c204#diff-2aa4ecb2166f80cc14bc819c865b6d49a00a1ee9caae50dcc5fe98ae2158c0beR133
=> fix(Core): Cherrypick?

src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_mekgineer_steamrigger.cpp
=> chore(scripts/Steamvault): Remove unused spells from Mekgineer Steamrigger

src/server/game/Spells/SpellEffects.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16372
- 
.learn 53736/31801
Whack something
.learn 20332
Whack more and see it deals 15% increased damage …
=> fix (Core/Spells) Apply Seals of Pure talent to Seal of Vengeance/Corruption again

src/server/scripts/Outland/CoilfangReservoir/underbog/boss_swamplord_muselek.cpp
-  Change CanShoot logic to allow the boss to Chase the target if its victim is too far.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5822
1. Go to The Underbog and engage with Musel'ek.
2. Move away from the boss on pull, it should not get stuck if you move far away from him anymore.
3. It should engage in melee combat if you're too close.
=> fix(Core/TheUnderbog): Fix Swamplord Musel'ek combat movement

src/server/game/Spells/Auras/SpellAuras.cpp
-  Add Beast Lord 4P bonus
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16512
- Closes https://github.com/chromiecraft/chromiecraft/issues/5448
https://www.wowhead.com/tbc/item-set=650/beast-lord-armor
- Works
1. .learn 34026
2. .aura 37483 / or while wearing 4 pieces of Beast Lord Armor
3. use Kill Command …
=> fix(Core/Spells) Add Beast Lord 4P bonus

src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
=> chore(Core/SmartAI): Add min/max timer error check for NEAR_PLAYERS

src/server/game/Achievements/AchievementMgr.cpp, src/server/game/Achievements/AchievementMgr.h
-  Add a Function on Achievement Manager to get read-only access to the map which contains all completed achievements. This allows for easier access to the Information of a players completed achievements. 
- Does it build without errors? yes!
- Did you test in-game?  yes, with a custom module where I listened to the OnAchiCompleted Hook an then accessed the map over:  auto completedAchievements = player->GetAchievementMgr()->GetCompletedAchievements();
- On which OS did you test?  Ubuntu and Debian
- Describe any other tests performed --> none.
No functionality change out of the box, just a "Getter"-Fucntion to allow modules easier access to Information about a Players achieved Achievements - thus there is nothing no test out of the box. 
An example on how this could be used:     
```c++ …
```
=> feat(CORE):Add getter for completed achievement map in AchievementManager

src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/SAI) Update SmartScriptMgr.cpp

src/server/scripts/Outland/boss_doomlord_kazzak.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/Outlands): Fix Kazzak not reseting his timers

src/server/scripts/Outland/boss_doomwalker.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/Outlands): Fix Doomwalker not reseting abilities

data/sql/updates/pending_db_world/rev_1681398806458012400.sql, src/server/scripts/Spells/spell_generic.cpp
- Attempt to "script" the spell.  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4994
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15005
https://www.youtube.com/watch?v=d3UGjMSl5eI&t=132s
- tested
.aura 37589
See if it starts at 20 stacks and drops by 1 each second. …
=> fix(Core/Spells): Shriveling Gaze

data/sql/updates/pending_db_world/remove-garbage-sql-ai-handling-and-add-simple-sai.sql
-  remove old SAI (see linked issue) that did not work
-  add simple SAI akin to behaviour of Riverpaw Mystic in Westfall.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16703
- Closes https://github.com/chromiecraft/chromiecraft/issues/5817
None needed.
- 
1. Go to Ghostlands
2. Engage Blackpaw Shamans
use `.list creature 16337` and then `.go creature <creatureguid>` to go to them …
=> fix(DB/Ghostlands): allow Blackpaw Shamans to move after the attacker and melee them when they are out of mana

data/sql/updates/pending_db_world/fix-quest-9175-typo.sql
-  Added blank space between sentences - quest_offer_reward
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16691
https://www.wowhead.com/wotlk/quest=9175/the-ladys-necklace
- Tested myself, works
1. horde char
2. .additem 22597
3. start quest
4. .go xyz 7552.79998 -6760.879883 91.337097
- [No, but since this is my first PR, please check if everything is ok, i'm slightly nervous] …
=> fix(DB/quest): 9175 - Fixing typo

data/sql/updates/pending_db_world/rev_1687015554834488300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5684
https://github.com/TrinityCore/TrinityCore/commit/20a4c95ffb5a9b018010e7879e2ac17dd8a464a3
Co-authored-by: Wyreth <Wyreth@users.noreply.github.com> …
=> fix(DB/creature_model_info): Turn 'Guard Untula' as female

data/sql/updates/pending_db_world/rev_1687028319280087800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5662
Progress at https://github.com/azerothcore/azerothcore-wotlk/issues/16549
https://www.wowhead.com/wotlk/npc=4126/crag-stalker#abilities
https://github.com/TrinityCore/TrinityCore/commit/4e8b0fcaa584f764089a3cec1bd7165c3d0c0659
Co-authored by: CraftedRO <CraftedRO@users.noreply.github.com> …
=> fix(DB/Creature): Add correct stealth to Crag Stalker

data/sql/updates/pending_db_world/rev_1685912891682130400.sql
-  Reference: [TC@C92909](https://github.com/TrinityCore/TrinityCore/issues/16607)
-  co-author: @Gargarensis
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14974
- Closes https://github.com/chromiecraft/chromiecraft/issues/5005
TrinityCore …
=> fix(DB/Quest): It's a Fel Reaver, But with Heart

src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp
-  cancelall on scheduler
-  should fix the problems described in the issue
- Closes https://github.com/chromiecraft/chromiecraft/issues/5872
None needed
- not tested
- **PLEASE TEST**
1. go to Ramps
2. engage nazan
3.
None afaik
**For …
=> fix(Scripts/HellfireRamparts): Nazan and Vazruden properly reset

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(Scripts/MagtheridonsLair): Adjust Magtheridon's timers

data/sql/updates/pending_db_world/rev_1688928918454010300.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/Creature): Link Hellfire Channelers in Magtheridon's Lair

data/sql/updates/pending_db_world/rev_1688929936108072000.sql
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(DB/SAI): Adjust Spell Timers for Magtheridon's Lair adds

src/server/scripts/Outland/GruulsLair/boss_gruul.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5049
Retail sniffs
- 
- 
1.
2.
3. …
=> chore(Scripts/GruulsLair): Adjust timers for Reverberation and Hurtful Strike

data/sql/updates/pending_db_world/rev_1688915874765152000.sql
- Groups items according to research made by Tereneckla
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/16612
- Closes https://github.com/chromiecraft/chromiecraft/issues/5754
- Closes https://github.com/chromiecraft/chromiecraft/issues/5755
- Closes https://github.com/chromiecraft/chromiecraft/issues/5757
- Closes https://github.com/chromiecraft/chromiecraft/issues/5758
- Closes https://github.com/chromiecraft/chromiecraft/issues/5763
- Closes https://github.com/chromiecraft/chromiecraft/issues/5767
- 
1.
2.
3. …
=> fix(DB/Loot): Correct Loot for several TBC Heroics

data/sql/updates/pending_db_world/rev_1689097520967716500.sql
- Closes #16735
- Closes https://github.com/chromiecraft/chromiecraft/issues/5903 …
=> fix(DB/creature_loot_template): Remove loot from Hellfire Channeler

src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp
-  fix target type as its not an aoe spell
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5347
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15867
- 
- 
1.
2.
3. …
=> fix(Scripts/GruulLair): Fix Maulgar not casting intimidating shout

src/server/game/Entities/Player/PlayerGossip.cpp
-  Fix menu not localized properly when OptionBroadcastTextID=0
-  Fix menu not localized properly when broadcast_text_locale was missing locale text
-  Using gossip_menu_option texts by default
- Closes #15119 
- Closes #7209
- Tested in-game with zhCN client and enUS client
- Change before: 
- Change after:
1. Login to the game except for enUS client, I'm using zhCN.
2. Find a guardian, such as a Silvermoon City Guardian
3. Talk to them
4. Menu should be correctly localized …
=> fix(Core/Gossip): Fix gossip menu for locale clients

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Magtheridon): Fix Manticron Cube mechanic

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Magtheridon): Fix emote spam

data/sql/updates/pending_db_world/rev_1689122352995380700.sql
- Mosh'Ogg Witch Doctor SAI flag correction
- Mosh'Ogg Witch Doctor is able to cast under CC
- Tested locally
- 
1.
2.
3. …
=> fix(db/scripts): Mosh'Ogg Witch Doctor SAI fix

data/sql/updates/pending_db_world/orkaos.sql
-  adds smartscript
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16369
- closes https://github.com/chromiecraft/chromiecraft/issues/5660
cmangos
- none,should work
1. engage Or'kaos …
=> fix(DB/SmartScript): Or'kaos the Insane smartscript

src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp
-  
-  
- Updates https://github.com/chromiecraft/chromiecraft/issues/5937
- 
- 
1.
2.
3. …
=> fix(Scripts/ShadowLabyrinth): Fix Vorpil voidwalkers getting stuck

src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp
=> refactor(scripts/Karazhan): Update The Curator

src/server/scripts/EasternKingdoms/Karazhan/boss_terestian_illhoof.cpp
-  Update complete script into the new model/struct
- Wrong Yells
=> fix(scripts/Karazhan): Rewrite Terestian Illhoof

src/server/scripts/Commands/cs_server.cpp
-  Just minor improvements to the command
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(Scripts/Misc): Improve server debug

src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp
=> fix(scripts/Karazhan): The Curator - KilledUnit

data/sql/updates/pending_db_world/rev_1689367513231192832.sql
-  Add Immunities Knockback and Horror to Gruul trash
- Closes https://github.com/chromiecraft/chromiecraft/issues/5931
-  works
1. .npc add 19389
2. Death Coil …
=> fix(DB/creature_template) Add Immunities Knockback and Horror to Gruul trash

data/sql/updates/pending_db_world/outcastcache.sql
-  Added groups, and adjusted the droprate accordingly (just a side effect of adding groups)
-  Added VI scrolls
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15537
- Closes https://github.com/chromiecraft/chromiecraft/issues/4829
_wowhead, nobody is gonna sniff this sorry_
youtube videos
- Tested …
=> fix(DB/ItemLoot): Outcast's Cache Loot adjustment

data/sql/updates/pending_db_world/rev_1689538830419766600.sql, src/server/game/Entities/Player/Player.cpp, src/server/game/Spells/SpellMgr.h
-  Based on Trinity's flag, adapted to AC (if needed just add Co-authored-by: Ariel Silva<ariel-@users.noreply.github.com> )
- Needed for #16233 
=> fix(Core/Spells): Implement ENCHANT_PROC_ATTR_WHITE_HIT

src/server/scripts/EasternKingdoms/Karazhan/boss_moroes.cpp
=> refactor(scripts/Karazhan): Update Moroes

src/server/scripts/EasternKingdoms/Karazhan/boss_maiden_of_virtue.cpp
=> refactor(scripts/Karazhan): Update Maiden of Virtue

data/sql/updates/pending_db_world/fix-horizon-crew.sql
Credits to [heyitsbench](https://github.com/heyitsbench) for sniff of the aura and class
- add bubble aura effect to Roland Geardabbler
-  set standing state to Roland Geardabbler and his crew
- change Roland Geardabbler class from 2 to 8 getting him 1 hp off from the value Bench has found (lol)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16773
Bench's sniffs and images from classic (for standing state)
Tested
1. `.list creature 8394`
2. `.go creature <aboveguid>`
3. observe and compare to before this PR
none
**REMEMBER**: …
=> fix(DB/Azshara): fix Horizon Crew in sunken ship on Azshara

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
-  Use TaskScheduler instead of old update with diffs
-  Fix some bugs
- make water elementals unable to move for the time being
- Progress https://github.com/chromiecraft/chromiecraft/issues/4892
- Closes https://github.com/chromiecraft/chromiecraft/issues/5600 (but in a hacky way, but this is a general problem with caster AI on AC so this is perhaps the best solution here)
- 
- 
1. Go to Kara
2. Fight Aran
3.
Note: his mana doesn't really get depleted that quickly. Intentional? How does this work on retail?
Add the following to more easily test the drinking mechanic (to the regular scheduler):
```cpp
).Schedule(15s, [this](TaskContext)
{
me->Yell("Oof ouch owie, my mana!", LANG_UNIVERSAL);
me->SetPower(POWER_MANA, 3000);
});
```
The issues the first TODO creates are the following:
- …
=> chore(Scripts/Karazhan): rework Shade of Aran using TaskScheduler and fixes

src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp
=> refactor(scripts/Karazhan): Update Attumen and Midnight

src/server/scripts/EasternKingdoms/Karazhan/boss_moroes.cpp
-  change from eventmap to TaskScheduler
- hack-fix to prevent getting taken out of vanish too early
- Closes https://github.com/chromiecraft/chromiecraft/issues/4864
None needed
- Tested. works
- 
go to Moroes …
=> chore(Scripts/Karazhan): change Moroes to use TaskScheduler instead of events

src/server/scripts/EasternKingdoms/Karazhan/boss_servant_quarters.cpp
=> refactor(scripts/Karazhan): Update Servant Quarters

data/sql/updates/pending_db_world/bangle.sql
-   lowers ICD from 60s to 50s
- Closes no open issue
- tested
=> fix(DB/Spell): Bangle of Endless Blessing ICD adjustment

data/sql/updates/pending_db_world/badgeoftheswarmguard.sql
-  update PPM
-  update flags to only work on melee or ranged attack
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12754
- Closes https://github.com/chromiecraft/chromiecraft/issues/3901
- tested …
=> fix(DB/Spell): Badge of the Swarmguard PPM fix

data/sql/updates/pending_db_world/hellfire-channeler-does-action-on-mag.sql, src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
-  add smart script DoAction on Hellfire Channelers to increment death counter on Magtheridon and release him when all channelers are dead
- since we schedule all things in 2 different locations now, I moved all the scheduled stuff to a different method
- MOST IMPORTANTLY: now using the unused say_free line LOL (see video yell after the emote after breaking free for proof)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16792
- Closes https://github.com/chromiecraft/chromiecraft/issues/5944
See sources in issue
- Tested
1. Go to Magtheridon
2. Kill all channelers
3. wait 3s
4. see that magtheridon breaks free before the timer …
=> fix(Scripts/Magtheridon): allow for Magtheridon to also break free immediately when all Hellfire Channelers are killed

data/sql/updates/pending_db_world/rev_1689812064738638900.sql, src/server/scripts/Spells/spell_quest.cpp
-  added MoveFleeing
https://www.youtube.com/watch?v=mHJyMgZ-T8I&t=499s
- 
- 
1.  .quest add 6124 (ally)
2.  .quest add 6129 (horde) …
=> fix(Scripts/Quest): improved Curing the Sick

data/sql/updates/pending_db_world/garn_mathers_path.sql
-  add path to Garn Mathers
-  don't change loot, as it is unconfirmed that it is wrong
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9721 
- Closes https://github.com/chromiecraft/chromiecraft/issues/2582
Sniffed waypoints from [Bench](https://github.com/heyitsbench)
- tested
Go to Dustwallow Marsh and check that he now has a path …
=> fix(DB/DustwallowMarsh): add pathing to Garn Mathers

src/server/scripts/EasternKingdoms/Karazhan/boss_moroes.cpp, src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
=> refactor(scripts/Karazhan): Update Netherspite

data/sql/updates/pending_db_world/rev_1690342063161377379.sql
https://github.com/SunstriderEmu/BugTracker/commit/8c4235be673999ce424c911472d74d50cf7edf33
-  Add 20% buff to Spotlight
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16274
- Closes https://github.com/chromiecraft/chromiecraft/issues/5393
- Closes https://github.com/chromiecraft/chromiecraft/issues/5618
- Works
1. enter karazhan
2. .go xyz -10917.5 -1745.3 90.4 532
- (currently) Spectral Performer cast this randomly between 1 - 8 seconds and repeat this every 20-35 seconds
so sometimes it can be casted on pull making this ability redundant. A solution could be to increase from 1 to 3 seconds(?)
- Pretty sure enemies SHOULD get 50% buff …
=> fix(DB/spell_linked_spell) Add 20% buff to Spotlight

data/sql/updates/pending_db_world/remove-defias-cutpurse-sai.sql
Related:
- https://github.com/azerothcore/azerothcore-wotlk/pull/16471
- https://github.com/azerothcore/azerothcore-wotlk/issues/16433
-  remove broken SAI from defias cutpurse
-  
- Closes 
See discussion on PR. tl;dr: backstab ability existed in original wotlk (very likely) got removed with class as a nerf to the starting zones to make them more noob friendly
- not tested but db checked
- 
1. check defias cutpurse
2. should have no differences to before because the backstab was not working
3.
none …
=> fix(DB/ElwynnForest): remove SAI from Defias Cutpurse

data/sql/updates/pending_db_world/rev_1690557135377279000.sql
-  Revert https://github.com/azerothcore/azerothcore-wotlk/pull/16829
Thanks to Bench for confirming on WotLK Classic that the fix was incorrect! …
=> Revert fix(Creature): High Executor Darthalia movement

apps/ci/mac/ci-compile.sh, apps/installer/includes/os_configs/osx.sh
-  Attempt to fix macos build
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(CI): Update macos openssl to 3

.github/workflows/build_dbimport.yml, .github/workflows/check_pending_sql.yml, .github/workflows/codestyle.yml, .github/workflows/core_build.yml, .github/workflows/core_matrix_build.yml, .github/workflows/core_modules_build.yml, .github/workflows/cpp-check.yml, .github/workflows/docker_build.yml, .github/workflows/import_pending.yml, .github/workflows/macos_build.yml, .github/workflows/tools_build.yml, .github/workflows/windows_build.yml
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> chore(CI): Update checkout and cache to v3

data/sql/updates/pending_db_world/rev_1690598216460509800.sql
-  Port values from Mangos
-  
- Closes 
🥭s
- ye
- 
1.
2.
3.
=> fix(DB/Creature): Change CombatReach and Bounding Radius for Doom Lord Kazzak

data/sql/updates/pending_db_world/captainskarloc.sql
-  removes interrupt immunity flag
-  removes turn evil immunity flag
- Closes https://github.com/chromiecraft/chromiecraft/issues/5980
wotlk cmangos …
=> fix(DB/Creature): Captain Skarloc should be interruptable

data/sql/updates/pending_db_world/technicians.sql
- adds pickpocketloot  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5984
Cmangos wotlk
tested …
=> fix(DB/Creature): Shadowmoon Technician Heroic should be pickpocketable

src/server/game/Spells/Auras/SpellAuras.cpp
-  Adds Explosive Shot exception
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16480
- Closes https://github.com/chromiecraft/chromiecraft/issues/5787
- Works
1. .aura 56453
2.  2-1-2 or anything …
=> fix(Core/Spells) Add Explosive Shot exception

data/sql/updates/pending_db_world/rev_1690769530684832000.sql, src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp, src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/magtheridons_lair.h
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5922
- 
- 
1.
2.
3. …
=> fix(Scripts/MagtheridonLair): Script Manticron Cube conditions

src/server/scripts/Commands/cs_misc.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/Commands): Allow using flusharenapoints from console

src/server/game/Battlegrounds/BattlegroundMgr.cpp
-  It would previously repeat every 10 minutes
-  
- Closes 
- Needs more testing
- 
1. Use RunAsDate to check if its still flushing correctly
2.
3. …
=> fix(Core/Battleground): Fix auto arena flush interval

data/sql/updates/pending_db_world/add_mech_imm_and_sai_to_ghostly_steward.sql
-  change mech immune masks to make Ghostly Stewards immune to most CC and taunts
-  change SAI so frenzy events fire correctly at 50% instead of between 0% and 30%
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16212
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16211
CC:
- Closes https://github.com/chromiecraft/chromiecraft/issues/5578
- Closes https://github.com/chromiecraft/chromiecraft/issues/5577
- Tests needed, especially to check threat drop
- 
1. `.npc add 16414`
2.
3. …
=> fix(DB:Karazhan): fix mechanical immunities of Ghostly Steward as well as fixing/improving Frenzy

data/sql/updates/pending_db_world/karaloot.sql
-  loot adjustmenets
-  upped drop rate for mount to 1%, from 0.5%, upped attumen schematic drop rate
- adjusted some ¨codestyle" mistakes in reference table
- adjusted BoJ drop rate to be wotlk correct.
- Closes no reported issue I know
Cmangos Wotlk, wowhead. …
=> fix(DB/loot): Karazhan Boss Loot

data/sql/updates/pending_db_world/verog-the-dervish.sql
-  despawns after 5 minutes now
-  adds waypoint movement after spawning
- spawns in the correct position
**closes the following abandoned PR**:
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/12911
**issues closed:**
- Closes https://github.com/chromiecraft/chromiecraft/issues/114
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11236
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5941
Sniffs supplied by the one and only [Bench](https://github.com/heyitsbench). Orientation couldn't be sniffed, but is very likely 0 (going from Bench's supplied video). Yes it looks strange, but that's how it works
- tested
- 
1. go to the barrens and kill pack runners, marauders of bloodchargers. no other mobs spawn him. the odds are 3% per kill
When a PR is …
=> fix(DB/TheBarrens): fix Verog the Dervish spawn position and add movement down to ramp with sniffs

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
-  Smoother movement of hunter pets when following players
- Closes #16763 
- [Prove Video](https://youtu.be/y7PXED3LNlo)
1. Create a blood elf hunter
2. .level 79
3. Selected a Springpaw Cub then using .pet create
4. Pets learn Boar's Speed talent
5. Walking around. …
=> fix(Core/Movement) Smoother movement of hunter pets when following players

data/sql/updates/pending_db_world/rev_1690829165550626300.sql
-  Add missing gossip to Gremnik Rizzlesprang
-  Credit Vmangos (https://github.com/vmangos/core/commit/69d245466028e967552820ef61465d8c5b39ff3c)
Vmangos
1. .go cr id 16123
2. Gossip
**For …
=> fix(Gossip): Gremnik Rizzlesprang gossip

data/sql/updates/pending_db_world/unquenchedthirst.sql
-  reduces ppm from 4.2 to 1
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14604
@heyitsbench for hitting a dummy for ages on Wotlk Classic and spending 100g on the dagger
- tested
-  …
=> fix(DB/Item): Blade of Unquenched Thirst PPM fix

data/sql/updates/pending_db_world/rev_1691257289493032818.sql
Adds missing (36332) Rake ability to (17350) Royal Blue Flutterer
-  Adds missing (36332) Rake ability to (17350) Royal Blue Flutterer
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16896
https://www.wowhead.com/tbc/npc=17350/royal-blue-flutterer#abilities
Video of Royal Blue Flutterer using Rake ability: https://www.youtube.com/watch?v=r0pZaRBga3k&t=22
- Linux Mint 21.1
- I fought Royal Blue Flutterers and they used their Rake ability in combat like they should.
1. .go xyz -1453.013672 -11623.257812 20.930595 530 4.382232
2. fight royal blue flutterers
3. realize they are now using rake ability  …
=> fix(DB/SAI) Adds missing (36332) Rake ability to (17350) Royal Blue Flutterer

src/server/game/Spells/SpellInfoCorrections.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14549
- Closes https://github.com/chromiecraft/chromiecraft/issues/4446
- Closes https://github.com/chromiecraft/chromiecraft/issues/5888
-  Works
1. .aura 37529
2. Smack something (use all abilities) …
=> fix(Core/Spells): Warrior T5 2p 

data/sql/updates/pending_db_world/Roleplay.sql, data/sql/updates/pending_db_world/amberhouse.sql, src/server/scripts/Northrend/zone_grizzly_hills.cpp, src/server/scripts/World/go_scripts.cpp
Roleplay & Script Fix For Doing Your Duty Quest
Credits to Kitzunu for the Script & Bench for the Sniff!
None that I know of.
Fixes the Roleplay after the Quest has been completed.
Fixes the Amberhouse Script during the Quest.
Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16347
Youtube.
Sniff.
Wotlk Classic.
WoW Retail.
It's tested on Azerothcore with a video here.
[Video](https://www.youtube.com/watch?v=piTHWbaIgm0&ab_channel=Roddan)
1. .q add 12227
2. Run to the Amberhouse and use it.
3. Watch the Roleplay after the quest has been turned in.
Spell Dust Field (48329) currently not working when inside the Amberhouse.
=> fix(Script/Quest): Doing Your Duty

.github/SECURITY.md
-  https://github.com/azerothcore/azerothcore-wotlk/issues/16902
-  
- Closes 
- 
- 
1.
2.
3. …
=> chore(Docs): Specify MySQL 8.1 support

data/sql/updates/pending_db_world/infernalwarbringer.sql
-  add mask
- Closes https://github.com/chromiecraft/chromiecraft/issues/6019
@heyitsbench  …
=> fix(DB/Creature): Infernal Warbringer immune to horror

data/sql/updates/pending_db_world/hellfirefort.sql
-  removes max reputation requirement
- set prequest requirement
- Closes no issue
@heyitsbench and his chars …
=> fix(DB/Quest): Hellfire Fortifications adjustments

src/server/game/Battlegrounds/ArenaTeam.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Core/Arena): Fix LegacyArenaPoints logic

pull_request_template.md
This is an attempt to simplify the pull request template and make it easier to fill/save up time.
Please discuss and lets see if we can improve it so we can be more consistent about it.
Thanks!
=> docs: Simplify the pull request template

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
=> fix(Scripts/UBRS): typo in Blackrock Spire instance

data/sql/updates/pending_db_world/rev_1691767736730972500.sql, src/server/game/Miscellaneous/Language.h, src/server/scripts/Commands/cs_event.cpp
Actually output that an event has been started or stopped
- Closes 
1.
2.
3. …
=> fix(Scripts/Command): Improve output of event commands

src/server/scripts/EasternKingdoms/Karazhan/boss_maiden_of_virtue.cpp
=> chore(Scripts/Karazhan): Clean up Maiden of Virtue script

apps/docker/Dockerfile
- Add lines to `apps/docker/Dockerfile` so that the docker build can properly get version information from git
- The `ac-dev-server` doesn't properly pull the git versioning information during the build step
- This is due to the `var` directory being in a separate mount as well as ownership for the `/azerothcore` directory
- This is easily resolved with an extra env var and `RUN` step in `apps/docker/Dockerfile`
- Issue reported in discord in the #docker-support 
- The easiest way is to check the `var/build/obj/revision.h` file after executing `./acore.sh compiler configure`
1. Checkout master (`git checkout master`)
2. View the revision.h file that gets created by master:
```console
docker compose -f docker-compose.yml run --build ac-dev-server \
bash -c "./acore.sh compiler clean; …
```
=> fix(Docker): Git version resolution in docker build

data/sql/updates/pending_db_world/WrathscaleSorceressFix.sql
Creature casts Frostbolt.
Wrathscale Sorceress casts Frostbolt randomly on target.
[Video](https://www.youtube.com/watch?v=aNoKPrcZIwc&ab_channel=Roddan)
Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16899
Retail & Youtube & Sniff.
Teleport to Bloodmyst Isle and attack it.
1. Teleport to Bloodmyst Isle or Spawn the NPC.
None so far.
=> fix(DB/Creature) Wrathscale Sorceress casts Frostbolt

data/sql/updates/pending_db_world/rev_1691887692026103900.sql
Imagine using event_scripts 😹 
- Closes 
None of the above, this is a refactor
1. .q a 10877
2. .go ga id 185220
3. use :) …
=> refactor(DB/SAI): Port 'The Dread Relic' from event_scripts to SmartAI

data/sql/updates/pending_db_world/rev_1691944209332122100.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_servant_quarters.cpp, src/server/scripts/EasternKingdoms/Karazhan/karazhan.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16919
- Closes https://github.com/chromiecraft/chromiecraft/issues/5604
1.
2.
3. …
=> fix(Scripts/Karazhan): Fix Servant Quarters rares not spawning

data/sql/updates/pending_db_world/rev_1691962350657672100.sql
Jandice Barov appears to be currently using incorrect spell IDs. In particular, Curse of Blood seems much too strong. This changes them to those used in Vmangos.
- Closes https://github.com/ZhengPeiRu21/mod-individual-progression/issues/167
1.
2.
3. …
=> fix(Creature): Jandice Barov correct spell IDs

data/sql/updates/pending_db_world/warder.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6039
Cmangos Wotlk
1.
2.
3. …
=> fix(DB/Creature): Hellfire Warder Immunities

src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
None
untested
1. go ohf
2. do it two times, kill drake in one and don't kill him in another
3. check if thrall can be freed on both occasions
none …
=> fix(Scripts/OHF): make it so that even if you kill Drake you can still progress with Thrall (as it should be)

data/sql/updates/pending_db_world/Horrified_Drakkari.sql
-  Change the flags_extra (creature does not aggro (ignore faction/reputation hostility)
- No issue open
- https://www.wowhead.com/wotlk/npc=26583/horrified-drakkari-shaman
- https://www.wowhead.com/wotlk/npc=26582/horrified-drakkari-warrior
- 
- 
1. `.go creature id 26582` 
2. `.reload creature_template 26582`
3. `.reload creature_template 26583`
4. ![Screenshot 2023-08-08 041525](https://github.com/azerothcore/azerothcore-wotlk/assets/89680380/b817bdb4-6ab2-41e0-9a3a-af6f3e0497cc) …
=> fix(DB/Creature) Horrified Drakkari Shaman/Warrior

src/common/Configuration/Config.cpp, src/test/common/Configuration/Config.cpp
=> fix(build): macOS

src/cmake/macros/FindMySQL.cmake
-  clean it up a bit
- Closes 
1.
2.
3.
=> refactor(Deps/MySQL): Tidy up FindMySQL for windows

src/server/game/Entities/Transport/Transport.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15889
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16511
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17026
1.
2.
3. …
=> fix(Transport): Fixes crash with loading player on deleted transport

.github/README.md
-  Just make it less annoying to read I suppose and remove unnecessary stuff
-  demo https://github.com/azerothcore/azerothcore-wotlk/blob/d55dca57058de48c9136d61906b2b934276a6b93/.github/README.md
- Closes 
- 
- 
1.
2.
3. …
=> refactor(docs): Clean up readme a bit

src/server/game/Entities/Pet/Pet.cpp, src/server/game/Entities/Pet/Pet.h, src/server/game/Handlers/PetHandler.cpp
This situation occurs when, during a fight, a pet receives a command to apply a positive spell to an ally and then resume attacking its previous target. But that target already deleted (player logout, creature despawned etc.).
More details here - https://github.com/azerothcore/azerothcore-wotlk/issues/14662#issuecomment-1682010789
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14662
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16043
1.
2.
3. …
=> fix(Core/Pets): Fix crash when pet tries to attack deleted object

data/sql/updates/pending_db_world/rev_1692233536025387200.sql, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_lieutenant_drake.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17023
- Closes https://github.com/chromiecraft/chromiecraft/issues/6048
1.
2.
3. …
=> fix(Scripts/OHF): Don't update the escort steps when Drake dies

data/sql/updates/pending_db_world/rev_1692638445679940800.sql, src/server/scripts/Spells/spell_quest.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17045
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/16799
1. `.quest add 10651` and `.quest add 10692`
2. Deal damage until you get him to metamorphosis
3. Wait for the npc Varedis to have the metamorphosis aura.
4. Use the book, to remove the aura.
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/1c490b1b-0e43-4fd5-bbdc-fcf863d32807 …
=> fix(Script/Spells): Book of Fel Names

src/server/scripts/Outland/TempestKeep/arcatraz/boss_harbinger_skyriss.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6030
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16989
**Wipe after mellichar dies**
1.
2.
3. …
=> fix(Scripts/Arcatraz): Fix not being able to try Skyriss a second time after wipes

src/server/game/Entities/Vehicle/Vehicle.cpp
As I understand it, a try-catch block cannot intercept the ABORT function. Therefore, let's use a simple if statement instead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15998
1.
2.
3. …
=> fix(Crash): Fix crash in Vehicle::AddPassenger

data/sql/updates/pending_db_world/rev_1692106991947262800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4409
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13717
.go c id 18391
See if she has shadowform
See if she does mind sear
Bring her to 65% hp, should talk and transform. should still do mind sear …
=> fix(DB/SAI): Correct Giselda the Crone's SAI.

data/sql/updates/pending_db_world/deep.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17048
- Closes https://github.com/chromiecraft/chromiecraft/issues/6052
1.
2.
3. …
=> fix(DB/Item): Deep Thunder ppm adjustment

data/sql/updates/pending_db_world/add-path-ids-ulduar-trash.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15402
1. go to the listed creature guids
2.
3. …
=> fix(DB/Creature): add `path_id` to some Ulduar mobs that were missing it

src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp
Fixes the oversight I made on my previous PR using DoActions. Also very slightly lowered Dorothee timer as it was needed. They will get corrected soon anyway tho
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17067
1.
2.
3.
none specifically for Oz …
=> fix(Scripts/Karazhan): allow sequence of releases to continue even if Dorothee dies early

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp, src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp, src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/instance_the_black_morass.cpp, src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp, src/server/scripts/Northrend/AzjolNerub/AzjolNerub/instance_azjol_nerub.cpp, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp, src/server/scripts/Outland/Auchindoun/SethekkHalls/instance_sethekk_halls.cpp, src/server/scripts/Outland/CoilfangReservoir/SlavePens/instance_the_slave_pens.cpp, src/server/scripts/Outland/CoilfangReservoir/underbog/instance_the_underbog.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/instance_arcatraz.cpp
Within this function, if we do not provide the final element with a 0 entry, we will exceed the boundaries of the arrays.
https://github.com/azerothcore/azerothcore-wotlk/blob/092c2b9957c5cfddb01b0c6aedc0090e04e62e01/src/server/game/Instances/InstanceScript.cpp#L187-L195
- Closes 
1.
2.
3. …
=> fix(Core/Scripts): Fix scripts where LoadObjectData can leave arrays boundaries.

data/sql/updates/pending_db_world/rev_1692891069724453500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6065
1.
2.
3. …
=> fix(DB/creature_template): Add Taunt immunity to Magtheridon

src/common/Configuration/Config.cpp, src/server/game/Handlers/LFGHandler.cpp, src/server/game/Spells/SpellMgr.cpp
=> chore(Core/Misc): Correct some fmt outputs

src/server/scripts/EasternKingdoms/Karazhan/boss_moroes.cpp
Code based on code for Kargath Bladefist reset
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16033
- Closes https://github.com/chromiecraft/chromiecraft/issues/4862
1.
2.
3.
this is not sniffed and based on estimates, but works in the meantime. an idea would be to sniff the exact positions where they should reset (if that is even possible) …
=> fix(Scripts/Karazhan): allow Moroes and adds to reset when an add is pulled out of the room

src/common/Cryptography/OpenSSLCrypto.cpp, src/server/scripts/Commands/cs_account.cpp, src/server/scripts/Commands/cs_cast.cpp, src/server/scripts/Commands/cs_debug.cpp, src/server/scripts/Commands/cs_list.cpp, src/server/scripts/Commands/cs_message.cpp, src/server/scripts/Commands/cs_pet.cpp, src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp, src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp, src/server/scripts/Kalimdor/zone_feralas.cpp, src/server/scripts/Kalimdor/zone_tanaris.cpp, src/server/scripts/Kalimdor/zone_winterspring.cpp, src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp, src/server/scripts/Outland/zone_hellfire_peninsula.cpp, src/server/scripts/Outland/zone_shadowmoon_valley.cpp
- Removes unused `#import ` improving the compilation speed
- No tests have been performed
If it correctly builds, no additional tests are required. …
=> refactor(Scripts): remove unused imports

src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp, src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
Sourced by Bench who has been extensively testing Karazhan on wotlk
1.
2.
3.
none that I know of …
=> fix(Scripts/Karazhan): make it so door closes when Big Bad Wolf is engaged in Little Red Riding Hood in the Opera

src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17149
untested …
=> fix(Scripts/Karazhan): change to right gossip menu for Barnes

src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp, src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
=> fix(Scripts/Karazhan): Fix Nightbane health phase percentages

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
- Disables all kinds of attacks during quake
- Also makes it so no taunt lines are played when Magtheridon is engaged
- Makes it so that p1 with the channelers can no longer be skipped by adding a for loop that puts the channelers in combat with any attacker
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17126
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17125
- Closes unreported issue (taunt lines)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6090
- Closes https://github.com/chromiecraft/chromiecraft/issues/6091
This …
=> fix(Scripts/MagtheridonsLair): make it so no attack is being done during Quake and fix p1 cheese tactic

src/server/game/Maps/Map.cpp
This fix addresses the issue of undefined behaviour that arises when interacting with deleted player objects. 
The deletion occurs within a call chain initiated by `Map::RemovePlayerFromMap`.
- Closes 
1.
2.
3. …
=> fix(Core/InstanceMap): Stop using deleted player in RemovePlayerFromMap

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
SendClearThreatListOpcode(); should help follow blizzlike tbc behaviour player-side.
- Magtheridon keeps building ThreatTable during phase1, at phase2 release smashes healers or highest threatTarget (he's immune to taunt, so odd behavior, this does not happen in any tbc video)
https://youtu.be/LVDR-yzOezc?feature=shared&t=110
-> Only a hunter appears in ThreatTable addon due to Misdirection …
=> fix(scripts/Magtheridon): Remove ThreatList before release

data/sql/updates/pending_db_world/winter-jormungar-auras.sql, src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.h
- adds RegisterUlduarCreatureAI factory to make registering creature AI easier in the future
- updates Snow Mound to ScriptedAI model
- change some uint32 values (because they don't make sense to readers) into values from enums so they are easier to read
- jormungars now spawn consecutively every 2s
- add permanent auras to the npcs with `creature_template_addon`, instead of manually adding them (will the removal still work?)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15401
timers look to be very close to 2s between each spawn, sniffs would confirm …
=> fix(Scripts/Ulduar): update Winter Jormungar and Snow Mound creature script

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
Closes unreported issue
1.
2.
3. …
=> fix(Scripts/Magtheridon): add correct way to reset threat list

src/server/game/Entities/Player/Player.cpp, src/server/game/Loot/LootMgr.cpp, src/server/game/Scripting/ScriptDefines/GlobalScript.cpp, src/server/game/Scripting/ScriptMgr.h
=> feat(Core/Scripting): Implement OnAllowedToLootContainerCheck() hook

src/server/game/AuctionHouse/AuctionHouseMgr.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/17150
- Closes 
1.
2.
3. …
=> fix(Core/AuctionHouse): fix crash in BuildListAuctionItems

.github/workflows/import_pending.yml
Fixes deno executing a typescript file. The reason this broke is because deno requires some extra syntax to execute a file, that was previously removed:
https://github.com/azerothcore/azerothcore-wotlk/blob/23c5e990b6b6fe9dbc8fff1f2df5f3da9bc557e1/apps/bash_shared/deno.sh#L16-L23
The whole point of this code is to 1) check if the OS is Windows or Unix-like and 2) to run a typescript file with deno. CI is on unix-like systems so we don't need to think about windows, and we don't need to abstract away the command line args of deno
- Closes 
```console
$ …
```
=> fix(CI): pending sql changelog script's invocation

.github/workflows/import_pending.yml
-  [x] fix my devoops
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/6133844093/job/16646049408#step:4:19
`git fetch --unshallow ...` is made redundant by checking out the full history in the previous step (which is a better interface for GHA). This change removes the `git fetch --unshallow` and instead uses `git pull --rebase` which will pull in the latest changes from the current branch and then rebase the on top of that. 
If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to …
=> fix(CI): rebase instead of unshallow fetch

.github/workflows/import_pending.yml
Tested here https://github.com/Kitzunu/azerothcore-wotlk/actions/runs/6136857001/job/16652107417
=> fix(CI): pending files

apps/docker/docker-cmd.sh
-  [x] Acore dashboard
in the conversion from typescript to bash, an argument was missed in the `build:prod` command
- Closes 
1.
2.
3. …
=> fix(apps/Docker): Missing arg for build:prod

.github/workflows/cpp-check.yml
=> fix(CI): only run cpp check on AC

.github/workflows/windows_build.yml, apps/compiler/includes/functions.sh, apps/installer/includes/os_configs/osx.sh, apps/installer/includes/os_configs/windows.sh
=> chore(CI): Update deps for Windows and Mac builds

.github/README.md
=> chore(docs): remove reference to BountySource

data/sql/updates/pending_db_world/rev_1694636334573006200.sql
Co-Authored-By: neifion-00000000 [91289495+neifion-00000000@users.noreply.github.com](mailto:91289495+neifion-00000000@users.noreply.github.com)
The purpose of this column would be to provide additional context for each creature or gob row.
For example, if modifications are made to fix blizzlike bugs such as floating gobs, we add a comment with the original sniffed values. Other comments could be for the purpose of the creature/gob or what makes it trigger, etc.
It's simply better to maintain this information somewhere. Since GH isn't forever, it's best to address it in the DB itself
If your pull request …
=> feat(DB): Add another column for comments

data/sql/updates/pending_db_world/condense-tables.sql, src/server/game/Globals/ObjectMgr.cpp
This PR corrects a case of laziness with 5534455c3248ea88103abe1acb15d0a42ff9ae48 and unifies two tables that have no need being split.
This PR:
1. Make characters.
2. Play around with various class/level combinations.
3. Play around with gear combinations.
4. Observe health/mana values. …
=> refactor(DB): Unify two player stat tables.

data/sql/updates/pending_db_world/rev_1694389067923549800.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17176
- Closes https://github.com/chromiecraft/chromiecraft/issues/6101
1.
2.
3. …
=> fix(DB/Creature): Correct Orc Warlock controlled spell

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): decrease Aran cast cooldown on normal spells

src/server/scripts/Spells/spell_paladin.cpp
- Maybe (probably not) https://github.com/azerothcore/azerothcore-wotlk/issues/16954
- https://github.com/chromiecraft/chromiecraft/issues/5852
1.
2.
3. …
=> Refactor (Scripts/Spells) Check for existence of AD debuff instead of adding a custom cooldown to heal

src/server/game/Spells/Spell.cpp, src/server/scripts/Spells/spell_dk.cpp
=> chore(Scripts/DK): Move CheckCast to spell_dk_raise_ally script

data/sql/updates/pending_db_world/rev_1694778808871595100.sql
=> fix(DB/Creature): Netherspite is immune to taunts

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_hydross_the_unstable.cpp
Water tomb and vile sludge timers homogenised. I did this because the sniffs turn him into the pure form quite quickly. So I am assuming the initial timer is the same for both, and then taking some kind of average for the water tomb and also using that for vile sludge. We may need testing where we keep him in the first form for a bit just to look at the timers
N.A.
N.A. …
=> refactor(Scripts/SSC): Hydross the Unstable boss script updated

data/sql/updates/pending_db_world/rev_1694739263824086500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6144
1.
2.
3. …
=> fix(DB/Creature): The Big Bad Wolf should be Taunt immune

data/sql/updates/pending_db_world/rev_1694740225097878900.sql
There's probably more scripting but the movement is done
- Closes https://github.com/chromiecraft/chromiecraft/issues/6137
1.
2.
3. …
=> fix(DB/Creature): Ravenous Flayer Matriarch

src/server/game/Instances/InstanceScript.cpp, src/server/game/Instances/InstanceScript.h, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/instance_ruins_of_ahnqiraj.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp
=> feat(Core/Instance): Add TaskScheduler to the InstanceScript class

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
It is ugly... but so far the only way I got it to work. And I moved the whole thing from UpdateAI which was even uglier
none needed
1. go to Aran
2. wait for him to drink
3. observe he no longer casts whilst having his nice drink
none I know of right now …
=> fix(Scripts/Karazhan): Shade of Aran now no longer casts spells whilst he should be drinking

data/sql/updates/pending_db_world/rev_1687359733617622800.sql, src/server/scripts/Outland/zone_netherstorm.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15802
- Closes https://github.com/chromiecraft/chromiecraft/issues/5327
- 
- 
1.
2.
3. …
=> fix(Scrpits/Quest): Improve Recharging the Batteries

data/sql/updates/pending_db_world/rev_1694976478402282600.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17132
- Closes https://github.com/chromiecraft/chromiecraft/issues/4929
1.
2.
3. …
=> fix(Scripts/Karazhan): Fix Enfeeble hitting more than 5 targets

data/sql/updates/pending_db_world/62896.sql
-  "Know Thine Enemy" - Missing RP event
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16206
- Closes https://github.com/chromiecraft/chromiecraft/issues/5413
https://wowpedia.fandom.com/wiki/Know_Thine_Enemy
https://github.com/TrinityCore/TrinityCore/issues/18574
- Local
- 
.go cr 62896
.quest add 9567
.quest comp 9567 …
=> add(DB/Quest) "Know Thine Enemy" - Missing RP event

data/sql/updates/pending_db_world/rev_1694983857958013500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17271
1.
2.
3. …
=> fix(DB/SAI): Worldserver Error in Dalaran

data/sql/updates/pending_db_world/rev_1695004374973517300.sql, src/server/apps/worldserver/worldserver.conf.dist, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Fix Aran's chase distance and Blink conditions

.github/workflows/import_pending.yml
=> chore(CI): revert previous changes to import_pending.yml

data/sql/updates/pending_db_world/make-infernals-invisible.sql
adds flag that turns them into proper trigger creatures
- Closes 
none needed
untested
go to Nightbane or Aran in `.gm off` mode and check if infernals are still visible …
=> fix(DB/Karazhan): make infernal helper targets in Kara invisible to players

src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6163
1.
2.
3. …
=> fix(Scripts/Karazhan): Regen Curator mana on reset

data/sql/updates/pending_db_world/rev_1695111326975856300.sql, src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp
=> fix(Scripts/Karazhan): Fix fear immunity for Strawman

data/sql/updates/pending_db_world/rev_1695168508123583100.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Move Aran's elemental AI to SAI

src/server/scripts/EasternKingdoms/Karazhan/boss_terestian_illhoof.cpp
=> fix(Scripts/Karazhan): Delay chain spawning so it spawns on proper place

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptMgr.h, src/server/game/Spells/SpellInfo.cpp, src/server/game/Spells/SpellInfo.h
-  Add a bool Hook in CanFlyInZone check to give modules the possibility to influence this function to deny flight based on modules decision.
-  
- Builds without errors, tested ingame without any modules -> has no impact as intended(aka no regression for servers without module), tested with Proof-of-Concept module: [poc-can-fly-hook-override](https://github.com/Tralenor/poc-can-fly-hook-override), has intended impact, disallowing flying in Hellfire Peninsula. 
you can use the Module:  [poc-can-fly-hook-override](https://github.com/Tralenor/poc-can-fly-hook-override) to test this hook, this module simply blocks flight over the Hellfire Peninsula.
Test scenario 0 (check for regression, without having the module):
0. checkout revision and compile
1. go ingame, try to fly with your prefered …
=> Core: Addition of a Hook in CanFlyInZone check

data/sql/updates/pending_db_world/questfix6392.sql
This fixes the incorrect completion text for 6392.
-  Changed completion text for 6392
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16470
Before
After
WoW Classic
https://youtu.be/njpmde2sDfM?t=48
https://www.wowhead.com/wotlk/quest=6392/return-to-brock
I've also checked the previous 3 q in the series to confirm, that this should be the only incorrect text (related to Cataclysm overwrites).
1. Alliance
2. .q a 6392
3. .go xyz -5366.930176 -3014.870117 319.665344 …
=> fix(DB/quest): 6392 - Return to Brock - incorrect completion text

data/sql/updates/pending_db_world/questfix.sql
Added script to the graves.
Fixed with WoWDatabaseEditor
Add so it plays the scenes etc.
Fixed the Roleplay at the Graves.
https://www.youtube.com/watch?v=GZKXSFzAhhs&ab_channel=Roddan
Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/16885
Source from Sniff & Youtube: https://www.youtube.com/watch?v=FOctMDsnJDM&ab_channel=WorldOfWarcraftGuidesAndGameplay
I tested it ingame several times and it works.
1. .q add 13643
2. Click the graves.
It plays a death sound when clicking on the graves when the NPC spawns, on videos they don't.
=> fx(DB/Quest): The Stories Dead Men Tell Quest Fix

data/sql/updates/pending_db_world/rev_1692493990178861500.sql
- Closes 
https://clipchamp.com/watch/Lbc5hZ478zX summon
https://clipchamp.com/watch/EI7sFJ80NAr Despawn
1. Create Warlock
2. .go xyz 1711.58 57.16 -62.3 0
3. .quest add 1471
4. Move to "Magic Array" to use items “ Runes of Summoning”（id 6284）
5. Observe whether the status of the summoned creature is the same as Blizzard (after summoning, it is friendly and has the effect of …
=> Added smatAI to creatures for Warlock Pet Summoning Quests

data/sql/updates/pending_db_world/rev_1685745892775868100.sql
-  Set Stats, Armor, Class Restriction of season 1 and 2 wrist, waist, feet to wowhead.com/wotlk values
(I filtered by epics between iLvL 113 and 136 with resilience on them)
- 
- Closes https://github.com/chromiecraft/chromiecraft/issues/5710
Values are from the wowhead API
- Ran SQL
- added items specifically mentioned by reporter 32982 and 32976
add any of these items
28644,28383,32791,32794,28991,28987,28986,32795,32998,28404,28410,28993,32789,32806,28446,32786,28643,28445,32997,28978,32982,28984,31596,32792,28444,28385,28994,32819,32994,29002,32813,29005,32801,28998,32974,32793,28424,28988,28447,28974,28641,32978,28645,28981,28443,32975,28448,32788,32986,28983,32983,28402,32985,32811,32990,29004,32812,32808,28975,28646,28605,32992,28995,32979,32977,28985,32817,28640,32799,29003,28982, …
=> fix (DB/Item) Import stats of S1 and S2 Waist/Wrist/Feet from wowhead/wotlk

src/server/database/Database/Implementation/CharacterDatabase.cpp, src/server/game/Achievements/AchievementMgr.cpp, src/server/game/Achievements/AchievementMgr.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerStorage.cpp
- Closes #6901 
This PR fixes the following statistics:
- "Average gold earned per day"
- "Average quests completed per day"
- "Average daily quests completed per day"
These average values now get calculated like:
`average = total / (character_age * IN_DAYS)`
1. login to character 
2. observe correct average statistics value
(character age preferrably at least 2 days to get …
=> fix(Core): Implement ACHIEVEMENT_FLAG_AVERAGE

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6167
1.
2.
3. …
=> fix (Script/Karazhan) Voidzones should only happen in Portal Phase

src/server/scripts/Events/midsummer.cpp
- spell 45644 used to be linked to spell_midsummer_juggling_torch
- spell 45644 was later linked to new implementation spell_midsummer_torch_catch in e1e4c6cddc44971054c61df1a884ac7c795c8b73
- old implementation of spell 45644 was never removed from spell_midsummer_juggling_torch
- Closes 
throw & catch of torch still works after refactoring:
.quest add 11923
.quest complete …
=> refactor(Scripts/Midsummer): Remove old unused code for spell 45644

src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6166
1.
2.
3. …
=> fix (Scripts/Karazhan) Sync Enfeeble and Shadow Nova

data/sql/updates/pending_db_world/rev_1695559726583951400.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Events/brewfest.cpp
I created the script that leads to the Wolpertinger Net effect
- Closes 
1. event Brewfest
2. add quest Catch the Wild Wolpertinger!
3. look for Wild Wolpertinger …
=> fix(Scripts/Quest): improve Catch the Wild Wolpertinger!

src/server/scripts/Events/midsummer.cpp
- Progress #12392
.event start 1
.quest add 11923
go to midsummer location:
https://wowclassicdb.com/wotlk/npc/26113
throw & catch torch
observe shadow below torch
.cast 45280
(adds different non-quest torch to inventory)
throw torch
observe shadow below torch …
=> fix(Scripts/Midsummer): Add missing torch shadows

src/server/scripts/Commands/cs_list.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17350
1.
2.
3. …
=> fix(Scripts/Commands): Fix list creature string output

src/server/scripts/Outland/GruulsLair/instance_gruuls_lair.cpp
=> refactor(Scripts/GruulsLair): Clean up instance script

src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_selin_fireheart.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.h
=> refactor(Scripts/MagistersTerrace): Clean up instance script

data/sql/updates/pending_db_world/rev_1695611850243926000.sql, src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17168
- Closes 
1.
2.
3. …
=> fix(Scripts/Karazhan): Make Chess door non interactable

data/sql/updates/pending_db_world/rev_1695579044772631700.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6165
1.
2.
3. …
=> fix(DB/Text): Add missing Netherspite text emotes

data/sql/updates/pending_db_world/rev_1695589175269497100.sql, src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_quagmirran.cpp
=> fix(Scripts/SlavePens): Correct target selector for Quagmirran Acid Spray

data/sql/updates/pending_db_world/rev_1695581559864061500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17318
- Closes https://github.com/chromiecraft/chromiecraft/issues/6175
1.
2.
3. …
=> fix(DB/Conditions): Fix Berthold teleport gossip conditions

src/server/scripts/Spells/spell_druid.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5452
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16038
1.
2.
3. …
=> fix(Scripts/Spells): Druid Dash require Cat Form

data/sql/updates/pending_db_world/rev_1695598231920750800.sql, src/server/game/Entities/Pet/Pet.cpp, src/server/game/Entities/Pet/PetDefines.h, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Spells/spell_warlock.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17145
- Closes https://github.com/chromiecraft/chromiecraft/issues/5995
1.
2.
3. …
=> fix(Scripts/Spells): Fix Glyph of Voidwalker applying to every pet

src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15539
1.
2.
3. …
=> fix(Scripts/Ulduar): Respawn Algalon on wipes

data/sql/updates/pending_db_world/rev_1695612785136315613.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8476
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8359
- Closes https://github.com/chromiecraft/chromiecraft/issues/2007
- Closes https://github.com/chromiecraft/chromiecraft/issues/2006
Despite the issue notes, none of the quests appear to be team-specific. On my Classic human warrior, I can …
=> (DB/Fix): Argent Dawn shoulder enchant quest fixes

src/server/game/Instances/InstanceSaveMgr.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/17330
- Closes 
1.
2.
3. …
=> fix(Player/Achievement): fix crash

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6178
1. Go to Netherspite
2.  Watch threat
3. …
=> fix (Script/Karazhan) Netherspite resets threat after portal phase

src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Fix Aran combat movement behavior

data/sql/updates/pending_db_world/malchezaar-interrupt-immune.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17356
no source, but allowing you to interrupt this would destroy the whole enfeeble mechanic. source would be much appreciated, but it is hard to check.
untested rn
- [ x] This pull request can be tested by following the reproduction steps provided in the linked issue
none …
=> fix(DB/Karazhan): make Malchezaar interrupt immune

data/sql/updates/pending_db_world/rev_1695647577303392800.sql, src/server/scripts/Events/midsummer.cpp
progress #12145
- Progress #12145
.event start 1
.tele orgrimmar
.go xyz 1937 -4326 22
click on ribbon pole
observe beam connecting to the top …
=> fix(Scripts/Midsummer): Make beam target Ribbon Pole top

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
repeat maxtimer needs work. average is skewed because the max is very high. I took the average timer as maxtimer now
N.A.
N.A. …
=> refactor(Scripts/SSC): Lady Vashj boss script updated

data/sql/updates/db_world/2023_09_26_02.sql
=> chore: fix sql

data/sql/updates/pending_db_world/fathomguards.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h
N.A.
N.A.
N.A.
Current issues: …
=> refactor(Scripts/SSC): Fathomlord Karathress boss script updated

data/sql/updates/pending_db_world/SL_gem_loot_fix.sql
Heroic Shadow Labyrinth bosses dropped incorrect gem. They had a chance to drop Glinting Fire Opal, but this line of SQL corrects them to drop Etched Fire Opal instead, as they should.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17156
- Closes https://github.com/chromiecraft/chromiecraft/issues/6092
1.
2.
3. …
=> fix(DB/reference_loot_template): Corrected Shadow Labyrinth gem drops

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_morogrim_tidewalker.cpp
Mistake from my refactor. Change uint8 to uint32 as spellID has uint32 type.
No source required
1.
2.
3.
the water globules seem to be working correctly as they are. …
=> fix(Scripts/SSC): Morogrim Tidewalker now summons the water globules again

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
using a scheduler to postpone setting the boolean to false, and putting a scheduler between the potion spell, which has a cast time and pyroblast, this ensures it is cast.
no source
1. pull aran
2. wait for him to drink
3. `.damage 500` whilst targetting him
unsure how the interrupt mechanic should work. dots? no dots? we have to figure it out. …
=> fix(Scripts/Karazhan): allow Aran to cast pyroblast also when interrupted

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Update Aran script to use boss states

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
=> fix(Scripts/Karazhan): Clear Netherspite portal targets on transition

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5906
Sniff used for blast nova timer, video evidence for quake timer using the TBC classic world first video (as I couldn't find it in sniffs)
[This](https://youtu.be/PVL-m0CvfI0?si=ooxbB1uoytDh6t5I&t=144) video clearly shows that blast nova and quake are fully independent. So this is the most likely solution
When a …
=> fix(Scripts/Magtheridon): make the timers of Quake and Blast Nova independent from each other

src/server/scripts/Events/midsummer.cpp
=> refactor(Scripts/Midsummer): Add/Update Validate() for spell checks

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
=> fix(Scripts/Karazhan): Restore Netherspite DestroyPortals() function

data/sql/updates/pending_db_world/rev_1696108618524876800.sql, src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h, src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
- Fix drinking being interrupted by dots
- Fix first super timer
- Fix missing Arcane Explosion emote
- Fix supers being locked by spell interrupt
- Correct drinking to 10% mana down from 20%
- Closes https://github.com/chromiecraft/chromiecraft/issues/6190
1.
2.
3. …
=> fix(Scripts/Karazhan): Several Aran fixes

src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6198
1.
2.
3. …
=> fix(Scripts/Karazhan): Fix Curator arcane immunity

data/sql/updates/pending_db_world/rev_1696123533155312100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6199
1.
2.
3. …
=> fix(DB/Creature): Fiendish Portals should not move

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
Leotheras adds now respawn on resetting
N.A.
N.A. …
=> refactor(Scripts/SSC): Leotheras the Blind boss script updated

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp
=> refactor(Scripts/SSC): The Lurker Below boss script updated

src/server/game/Entities/Player/Player.h
=> feat(Core/Player): Move SaveSkills() to the public scope

data/sql/updates/pending_db_world/rev_1696361742234966300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17218
- Closes https://github.com/chromiecraft/chromiecraft/issues/6124
.aura 29166 …
=> fix(DB/Threat): Innervate having threat modifier.

.github/workflows/windows_build.yml
=> fix(CI): windows

pull_request_template.md
Makes it much easier to spot PRs with complex changes.
=> docs(template): Comment out changes proposed info.

data/sql/updates/pending_db_world/rev_1696575537212629500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9341
.additem 21986
.go ga 99906
use it
.cooldown
Use it again, notice you can't …
=> fix(DB/Conditions): Don't allow multiple Banner of Provocation

data/sql/updates/pending_db_world/rev_1696582271290131600.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Spells/spell_generic.cpp
Added a condition to prevent spawning infinitive amount of spirits.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9152
.additem 22048
.npc add 16042 (.npc delete after)
Try to use the item on other mobs that are alive/dead, notice it does not work.
Use the item on Valthalak while he is alive, shouldn't work.
Use it when he is dead, it should work.
Try to use …
=> fix(Core/Spells): Script Lord Valthalak's Amulet

src/server/game/World/World.cpp
=> fix(Core): GridCleanUpDelay Log

apps/docker/docker-cmd.sh
this change removes the `docker image prune -fa` that occurs a few times in the acore dashboard. this deletes _all_ docker containers on the machine that aren't running.
The scripts shouldn't be making these kind of changes to user's machine
None that I know of.
1.
2.
3. …
=> refactor(apps): remove docker image prune in dashboard

src/cmake/compiler/clang/settings.cmake, src/cmake/compiler/gcc/settings.cmake, src/cmake/macros/ConfigInstall.cmake, src/common/Cryptography/TOTP.h, src/common/Encoding/Base32.cpp, src/common/Encoding/Base32.h, src/common/Encoding/Base64.cpp, src/common/Encoding/Base64.h, src/common/Encoding/BaseEncoding.h, src/server/apps/worldserver/Main.cpp, src/server/game/Battlegrounds/Arena.h, src/server/game/Battlegrounds/ArenaScore.h, src/server/shared/Secrets/SecretMgr.h
=> chore(Core/Misc): warhead -> acore

data/sql/updates/pending_db_world/rev_1696722553687617600.sql, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/scripts/Commands/cs_misc.cpp
=> feat(Core/Player): Implement commentator tag

data/sql/updates/pending_db_world/rev_1696662162909705600.sql
Drop looks fine (with comparison to wowhead's cached drops)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8643
- Closes https://github.com/chromiecraft/chromiecraft/issues/1859
```sql
SET @item = 14495; -- 14495,14480,14473,14477
SELECT * FROM creature_loot_template WHERE item= @item;
SELECT * FROM reference_loot_template WHERE item = @item;
``` …
=> fix(DB/reference_loot_template): Ghostweave Patterns

data/sql/updates/pending_db_world/rev_1696750954220791100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8462 (CC Issue no longer exists)
Mangos 3.3.5 db for 60/120 timer & for emote 1
.go c 23896
observe  …
=> fix(DB/Creature): "Dirty" Michael Crowe continuous animation loop

data/sql/updates/pending_db_world/rev_1696600422866666000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8881
- Closes https://github.com/chromiecraft/chromiecraft/issues/2236
Trinity 3.3.5 for positions, Mangos 3.3.5 for Curse and polymorph timers.
Be alliance
.q a 72
.go c 26834
Turn in the quest, then accept the follow up, mob should spawn
See if she talks and cast spells.
.q add 67
.go q e 67
Turn in the quest, …
=> fix(DB/SAI):  The Legend of Stalvan spawns

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/CreatureData.h
=> refactor(Core/Creature): Calculate BaseArmor as float

data/sql/updates/pending_db_world/rev_1696747623986200300.sql
TrinityCore/TrinityCore/issues/20525
She has one more RP event - https://github.com/azerothcore/azerothcore-wotlk/issues/8537
.go c id 10926
.q add 5149
.q c 5149
turn in …
=> fix(DB/SAI): Port Pamela Redpath from Trinity.

data/sql/updates/pending_db_world/rev_1696416650721787400.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14641
- Closes https://github.com/chromiecraft/chromiecraft/issues/4733
.go c id 20477
See if he fears (10% chance per swing) …
=> fix(DB/SAI): Terrorclaw correct cleave timer and add fear.

data/sql/updates/pending_db_world/rev_1696512029084537100.sql, src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/Spells/spell_shaman.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10506
.aura 54283 - crit buff
.aura 54675 - crit buff
.aura 64928 - T8 4P
.cheat power
.cheat cast
.learn 49238 - LB
Spec deep ele
Equip some items with hit.
Confirm that crits with LB (non Lightning Overload) proc the debuff and stack, like ignite. …
=> fix(Core/Spells): Script Shaman T8 Elemental 4P Bonus

src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
Hopefully doesn't get stuck anymore after this
- Closes unreported issue of Nightbane not engaging (hopefully)
none
1.
2.
3.
no clue, I couldn't replicate on my local
fix this damn script …
=> fix(Scripts/Karazhan): Nightbane clean-up script

data/sql/updates/pending_db_world/rev_1696918490346114000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7599
- Closes https://github.com/chromiecraft/chromiecraft/issues/1545
.additem 24084
Try to use it on anything alive/dead, it shouldn't work
.go c id 17701
Try using it while he is alive, shouldn't work
Use it when he is dead, should work only then. …
=> fix(DB/Conditions): 'Place Draenei Banner' conditions

data/sql/updates/pending_db_world/rev_1696864048593539500.sql
TrinityCore/TrinityCore/issues/18559
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8346
- Closes https://github.com/chromiecraft/chromiecraft/issues/2016
Be alliance
.q a 4441
.q c 4441
.go q ender 4441
Turn it in
accept Purified …
=> fix(DB/SAI): Port Eridan Bluewind RP from Trinity

data/sql/updates/pending_db_world/rev_1696883818543898900.sql
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/7961
https://www.youtube.com/watch?v=6m2MA-M6Pi4
.go gobject 32551
Loot, should get 2 sometimes …
=> fix(DB/Loot): Shellfish Trap giving only 1 shellfish

data/sql/updates/pending_db_world/rev_1696922353340609300.sql, src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
https://github.com/TrinityCore/TrinityCore/commit/5856f520bbd8dded42f7742277839587b0645dde
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7309
.go c id 24239 …
=> fix(DB/Creature): Hex Lord Malacrass missing weapon

data/sql/updates/pending_db_world/rev_1696925471216269600.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7028
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/9587
- Progress https://github.com/chromiecraft/chromiecraft/issues/2502
.go xyz 2256 -7222 14 1
.additem 10444
Should greet when summoned (needs to be delayed by 1s, but this is for when the RP part gets done)
Try using the item more than once (while NPC is spawned)
Should despawn after 5m (unknown actual despawn time, but it's for sure not 150m) …
=> fix(DB/Conditions): Pilot Xiggs Fuselighter spawning multiple times

data/sql/updates/pending_db_world/rev_1696507200849767300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10662
- Closes https://github.com/chromiecraft/chromiecraft/issues/3039
.event start 8
.go xyz -228 2172 82 33 …
=> fix(DB/Gameobject): Remove wagon duplicate.

data/sql/updates/pending_db_world/rev_1696691443957086100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8608
- Closes https://github.com/chromiecraft/chromiecraft/issues/1736
- [] This pull request requires further testing and may have edge cases to be tested.
.go ga 9256,9257,9258
Only one should be spawned at a time
**REMEMBER**: when testing a …
=> fix(DB/Gameobject): Pool triple Truesilver Vein in Desolace

src/server/game/Spells/Spell.cpp
TrinityCore/TrinityCore/pull/17488
- Closes 
https://www.youtube.com/watch?t=22&v=FlGxBOs2YTw&feature=youtu.be
https://wowpedia.fandom.com/wiki/Swim?oldid=2300441 "In Outland and Northrend, characters can fly over water with [flying mounts](https://wowpedia.fandom.com/wiki/Flying_mount). Unlike ground mounts, flying mounts cannot be mounted while in water."
[Patch 3.1.0](https://wowpedia.fandom.com/wiki/Patch_3.1.0) (2009-04-14): All Ground Mounts may now swim without dismounting the rider. Flying Mounts still may NOT, and will dismount the rider upon entering water. …
=> fix(Core/Spells): Allow casting ground mounts in water

data/sql/updates/pending_db_world/rev_1696867624332424400.sql
Removed flag is repeatable flag (also prevents quest_rewarded from working for some reason)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8341
- Closes https://github.com/chromiecraft/chromiecraft/issues/2009
- Closes https://github.com/chromiecraft/chromiecraft/issues/2398
https://youtu.be/5KoqnxAyMko?t=150
The "simply greets" source linked in https://github.com/chromiecraft/chromiecraft/issues/2398 is from a private server xd
.go c id 10816
Kill it, shouldn't drop the key
.go ga id 175926
Notice the gossip before completing the …
=> fix(DB/Conditions): Mrs. Dalson's Diary gossip & Outhouse Key

data/sql/updates/pending_db_world/rev_1696489227773553900.sql, src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp
TrinityCore/TrinityCore/issues/22262
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10713
- Closes https://github.com/chromiecraft/chromiecraft/issues/3068
- Closes https://github.com/chromiecraft/chromiecraft/issues/5367
.go quest starter 11183
.q add 11183
Use the torch at the end of the bridge
https://github.com/TrinityCore/TrinityCore/pull/23072
When a PR …
=> fix(DB/Quest): Port Cleansing Witch Hill from Trinity.

data/sql/updates/pending_db_world/rev_1696400055341029700.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16494
.go c id 26805 / 26803
Pull mobs that are not Clerics
Confirm that Clerics don't leave their iceblock to cast shield. …
=> fix(DB/SAI): Nexus Clerics casting while frozen.

data/sql/updates/pending_db_world/rev_1696502092749827700.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10714
- Closes https://github.com/chromiecraft/chromiecraft/issues/3075
.go quest starter 11174
.q add 11174
Go next to Power Core and see that it doesn't turn off. …
=> fix(DB/Creature): Power Core Fragment should stay on.

data/sql/updates/pending_db_world/rev_1696862712689014300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8350
```sql
SELECT * FROM smart_scripts WHERE action_param1 = 50433
``` …
=> fix(DB/Creature): Various Crocolisk NPCs Using pet ability

data/sql/updates/pending_db_world/rev_1696375442482086300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16606
.additem 54572
.additem 54588
Confirm that they both have 45s of ICD and that the normal version does not proc multiple times. …
=> fix(DB/Spell): Correct Charred Twilight Scale ICD.

data/sql/updates/pending_db_world/rev_1696874480394168100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8264
https://www.wowhead.com/tbc/quest=1654/the-test-of-righteousness
Make a paladin
.go q starter 1655 - Bailor's Ore Shipment/
.go q starter 1442 - Seeking the Kor Gem
None of the quests should show up.
.q a 1653
.q c 1653
.q reward 1653
Now you should be able to see them …
=> fix(DB/Quests): The Test of Righteousness required quests.

src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6179
1.
2.
3. …
=> fix(Scripts/Karazhan): Side Enterance Door check

data/sql/updates/pending_db_world/rev_1696402821792959500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16311
- Closes https://github.com/chromiecraft/chromiecraft/issues/5629
https://github.com/TrinityCore/TrinityCore/issues/20734
.go c id 2792
.quest add 702
Turn in the quest.
Observe RP. …
=> fix(DB/SAI): Port Guile of the Raptor RP from Trinity.

data/sql/updates/pending_db_world/rev_1697220792861371500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17036
- Closes https://github.com/chromiecraft/chromiecraft/issues/6060
.go c id 16263
as a troll and as any other race …
=> fix(DB/Conditions): Make Paelarin racist.

data/sql/updates/pending_db_world/hydross-taunt.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17508
- Closes https://github.com/chromiecraft/chromiecraft/issues/6230
N.A. …
=> fix(DB/SSC): Make Hydross the Unstable immune to taunt

data/sql/updates/pending_db_world/rev_1697469523592686600.sql, src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5351
.go xyz 1872 -1328 60 0
.q add 5096
.additem 12814
Try planting the banner without burning the tent
Burn the tent and plant the banner after
Check if you can plant banner after burning down the tent and waiting for it to respawn (1m), it shouldn't let you plant it. (intended) …
=> fix(Core/Spells): Script Scourge Banner

data/sql/updates/pending_db_world/rev_1697449664501189600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5134
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17193
proc flags taken from spell 47881
go to any creature/target dummy
.aura 35399
Cast spells, should reflect magic spells and should lose 1 charge each reflect.
**REMEMBER**: …
=> fix(DB/spell_proc_event): Bloodwarder Protector Spell Reflection

data/sql/updates/pending_db_world/rev_1697441406032177300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4843
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15825
.go c id 4119
Should only ever move if it cannot cast …
=> fix(DB/SAI): Port Elder Cloud Serpent from Mangos

data/sql/updates/pending_db_world/rev_1697195727896791400.sql
10 -> 18
There is a possibility that it was 14.5~ on 3.3.5
- Closes https://github.com/chromiecraft/chromiecraft/issues/6139
Can confirm by logs (different logs) and https://wowsims.github.io/wotlk/ that ppm is 18~ for recycled version at least.
Find any random log with enhancer, select buff apply-end timestamp then use filter expression "ability.name = "Shamanistic Rage", go to resources(mana)->events
For more info, in the issue.
1.
2.
3. …
=> fix(DB/spell_proc_event): Shamanistic Rage ppm

data/sql/updates/pending_db_world/rev_1697227385860752900.sql
- react to ribbonPole dancers
- react to Master Fire Eater spewing fire
- Closes #12157
- Closes chromiecraft/chromiecraft#3648
.go c 202744
pole dance
get some occasional applause / cheering from Midsummer celebrants …
=> fix(DB/SAI): Make Midsummer Celebrants applaud/cheer

data/sql/updates/pending_db_world/rev_1697191216463702200.sql
I couldn't reproduce locally, but this should solve it + it's better than SAI.
- Closes https://github.com/chromiecraft/chromiecraft/issues/2111
.go c 3423
.go c 12170 …
=> fix(DB/Creature): Minor Manifestation of Earth stealth

data/sql/updates/pending_db_world/fathomlord_adds_spawn_to_db.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
adds now correctly cast their spell on Fathomlord Karathress when they die
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17512
- Closes https://github.com/chromiecraft/chromiecraft/issues/6234
1.
2.
3. …
=> fix(Scripts/SSC): fix issues with Fathomlord and add interactions

data/sql/updates/pending_db_world/rev_1697523119963738400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5563
.go c id 18220 …
=> fix(DB/SAI): Ravenous Windroc not stacking eagle claw

data/sql/updates/pending_db_world/rev_1697186168138525800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6160
https://www.wowhead.com/wotlk/npc=15687/moroes
.go c id 19874 …
=> fix(DB/Creature): Baron Rafe Dreuger level

.github/workflows/docker_build.yml
With #17419, functionality that installed `mod-eluna` during the container build was removed. This has caused a regression with acore-docker, which has a hard dependency on mod-eluna
This pr restores that functionality; if the container it going to be pushed to dockerhub, the container is built with eluna.
- Closes 
1.
2.
3. …
=> fix(CI): Ensure eluna is installed for acore-docker

data/sql/updates/pending_db_world/rev_1697438519978900900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4849
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15827
https://www.wowhead.com/wotlk/item=34469/strange-engine-part#comments
be alliance
.additem 34469 5
.go q ender 11531
You should be able to turn it multiple times and receive 9,79gold per turn in. …
=> fix(DB/Loot): Strange Engine Part should be fishable

src/server/scripts/Spells/spell_hunter.cpp
-  [] Core (units, players, creatures, game systems).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15895
- Closes https://github.com/chromiecraft/chromiecraft/issues/5363
Make a hunter
.npc add temp 33286
.pet create
.setskill 413 400
.additem 31328
Equip some more items with different stats
Calculate pet bonuses - 
Player armor  * 0.35 + 490
Player stamina *  0.45 + 52
Player rangedAP * 0.22 + 70 
When a PR is …
=> fix(Core/Spells): Script Leggings of Beast Mastery.

src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/Auras/SpellAuraEffects.h, src/server/scripts/Spells/spell_warlock.cpp
attempt 2 at https://github.com/azerothcore/azerothcore-wotlk/pull/17484
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4287
Make a warlock, spec into the talent point by point while calculating (pet stam + pet int *0.04 per talent point) …
=> fix(Core/Spells): Demonic Knowledge missing 1% per rank

.github/workflows/docker_build.yml
Github actions prefers single quotes
- Closes 
1.
2.
3. …
=> fix(ci): docker build double quotes typo

data/sql/updates/pending_db_world/rev_1697533767698549200.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17138
- Closes https://github.com/chromiecraft/chromiecraft/issues/5816
Quests should show when unfriendly or lower.
Scryers
.go c id 18596
.modify rep 934
Aldor
.go c id 18597
.modify rep 932 …
=> fix(DB/Conditions): Scryer/Aldor repeatable quests

data/sql/updates/pending_db_world/rev_1696414669144836700.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14722
.modify reputation 932 -50000
.go c id 18537
Make sure you are At War with Aldors
He should be attackable …
=> fix(DB/Creature): Adyen the Lightwarden being immune to PC.

data/sql/updates/pending_db_world/greyheart-tidecaller-frostbrand.sql
cast on respawn, gives each of them a 10% on melee hit to trigger a frostbrand attack
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16594
no source needed. the spell seems permanent and always present
1.
2.
3.
none …
=> fix(DB/SSC): add Frostbrand Weapon proc to Greyheart Tidecaller

src/server/scripts/Commands/cs_reset.cpp
=> refactor(Scripts/Commands): convert cs_reset to new system

src/server/game/Conditions/ConditionMgr.cpp, src/server/game/Conditions/ConditionMgr.h
Add GoState condition. Will help for cases like #17523
.go xyz 1872 -1328 60 0
.q add 5096
Try using the item, then change ConditionValue3 to 1 (ready) or 2 (not ready) (Set to more than 2 for console error)
.reload cond 
try again
```sql
DELETE FROM `conditions` WHERE (`SourceTypeOrReferenceId` = 17) AND (`SourceGroup` = 0) AND (`SourceEntry` = 16989);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, …
```
=> feat(Core/Conditions): Add GoState condition for near gameobject.

.github/actions/docker-tag-and-build/action.yml, apps/docker/Dockerfile
Bugfix: add the `target` to docker builds in github actions. Harder to notice because you only would if you were using acore-docker (which use the containers built by the CI)
- Closes 
Look at the docker build run in CI, there should be a `--target` option specified and the appropriate component being passed as an argument to that option …
=> fix(CI): Ensure targeted stage for docker is specified in CI

src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4581
Confirmed on recycled PTR by @heyitsbench 
.go q starter 6523
buff it, should keep the buff for it's duration + any debuffs …
=> fix(Scripts/EscortAI): Do not remove auras on evade

src/server/game/Battlegrounds/Arena.cpp, src/server/game/Battlegrounds/Battleground.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11984
NONE
1. Make an arena team and queue for battle.
2. Win/lose with killing blows, damage done and healing done.
3. Check log_arena_memberstats table to see if it filled properly.
=> Fix(Core/Arena): Fix logging scores in db

src/server/scripts/Commands/cs_ticket.cpp
=> refactor(Scripts/Commands): convert cs_ticket to new system

src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5916
1.
2.
3. …
=> fix(Scripts/Mechanar): Remove polarity shift stacks on polarity change

data/sql/updates/pending_db_world/rev_1697923671065331000.sql
=> fix(DB/Creature): Shade of Aran should not path

data/sql/updates/pending_db_world/rev_1697929174535985900.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Script Aran's Flame Wreath ability

data/sql/updates/pending_db_world/rev_1697930734514279300.sql
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/af89ef8cca1a3705fb3386921e3b87300a3dbaa0)
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/4484
- Closes 
1.
2.
3. …
=> fix(DB/Quests): Darkshore emotes

src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp, src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
=> fix(Scripts/Karazhan): Opera left door should stay open in case of wipe

src/server/game/AI/CoreAI/UnitAI.h, src/server/game/Entities/Unit/Unit.cpp
=> feat(Core/Unit): Implement OnPowerUpdate() unit script hook

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Update Aran with the new OnPowerUpdate() hook

data/sql/updates/pending_db_world/rev_1698073663894629500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6266
https://youtu.be/UoPhMD-e6Pg?t=91
.go ga id 183518 …
=> fix(DB/Gameobject): Shadow Labyrinth Enterance Lever

data/sql/updates/pending_db_world/rev_1698041126559012500.sql
Attempted to also correct empty text while transformed, but without any success, could this be a core issue?
(transformed/morphed creatures not correctly inheriting their npc_text?)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6273
- (Progress) Empty text when transformed
https://youtu.be/t6WVZNnEPks?t=2118
.go c id 16459  …
=> fix(DB/SAI): Wanton Hostess not removing all auras

data/sql/updates/pending_db_world/rev_1698165360651526600.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17165
1.
2.
3. …
=> fix(DB/CreatureText): Medivh cheat emote should be a boss emote

src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp, src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp
=> fix(Scripts/ObsidianSanctum): Fix Tenebron respawning

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Scripts/Karazhan): Fix Flame Wreath affecting pets

data/sql/updates/pending_db_world/rev_1698258147355013600.sql
Set triggered flag
Before
After
.go c id 19007 / 19006 …
=> fix(DB/SAI): Dark Portal mages missing animation

data/sql/updates/pending_db_world/rev_1698324075800200000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14626
- Closes https://github.com/chromiecraft/chromiecraft/issues/4694
https://www.wowhead.com/wotlk/npc=16906/unyielding-knight#comments
https://youtu.be/zSHVlT36lWU?t=35 Call for help is roughly 25y~
.go c id 16906 
Should call for help at 30%
Should heal a nearby friendly that is under 50% …
=> fix(DB/SAI): Unyielding Knight - not healing & not calling for help

src/server/scripts/Spells/spell_paladin.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6267
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/17564
.additem set 627
Equip 2 set
Cast any judgement, look at combat log …
=> fix(Core/Spells): T5 Holy Paladin 2 set

data/sql/updates/pending_db_world/rev_1697992204711152400.sql
Ranged Ability -> Physical Ability
- Closes https://github.com/chromiecraft/chromiecraft/issues/6269
make a paladin
.cheat power
.aura 37195
Use the following macro
```
/stopattack
/target CHARNAME
.cooldown
/targetlasttarget
/cast Judgement of Wisdom
``` …
=> fix(DB/Procs): Paladin Retribution Set T5 - 4P

src/server/game/Globals/ObjectMgr.cpp, src/server/game/Globals/ObjectMgr.h, src/server/game/Scripting/ScriptDefines/DatabaseScript.cpp, src/server/game/Scripting/ScriptMgr.h, src/server/scripts/Commands/cs_reload.cpp
Adds the `OnAfterDatabaseLoadCreatureTemplates` hook to `DatabaseScript`. This hook fires just after the creature template database (`ObjectMgr::_creatureTemplateStore`) has been loaded into `ObjectMgr::_creatureTemplateStoreFast`. This allows module authors to edit individual creature templates after they're loaded from the database but before they are applied to the creature. A variety of SQL-less in-memory DB edits can be accomplished with this, including changes that are not otherwise possible in code.
Additionally, I have fixed a hidden bug where doing a `.reload creature_template xxx` would not update …
=> (Core/Hooks) Add `OnAfterDatabaseLoadCreatureTemplates` hook

data/sql/updates/pending_db_world/rev_1698398730438489700.sql
https://www.wowhead.com/npc=16901/blistering-rot#comments
.go c id 16901 …
=> fix(DB/Custom): Blistering Rot should stack from different sources

data/sql/updates/pending_db_world/rev_1698247491999764000.sql
https://youtu.be/YoS0CpmQg5Y?t=62
1.
2.
3. …
=> fix(DB/Custom): Venom Sting should stack from different sources

data/sql/updates/pending_db_world/rev_1698326815078104700.sql
I may or may not have been slapped hard by that on CC.
Additionally, we are safe to assume that other Fire Nova Totems (1-9) use the corresponding spell rank.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16097
- Closes https://github.com/chromiecraft/chromiecraft/issues/5510
Thanks Pepsiman @heyitsbench 
target any hostile mob
.cast back 32062 t
check damage …
=> fix(DB/Creature): Fire Nova Totem VII - using wrong Fire Nova spell

data/sql/updates/pending_db_world/rev_1698597123341587200.sql, src/server/scripts/Spells/spell_generic.cpp
https://youtu.be/iRICQyDBrgs?t=81 5th stack -> remove and apply root
.go c id 19519
pull few
At 5th stack aura should be removed and new one (root) should be applied …
=> fix(Core/Spells): Script Choking Vines 

src/server/game/Spells/SpellInfoCorrections.cpp
eff0 was just smite (damage), eff1 is correct (dot)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6270
.learn 48156
Check damage
.aura 37571
Check damage, should be 5% more …
=> fix(Core/Spells): T4 Shadow Priest 4 Set

data/sql/updates/pending_db_world/17196.sql
fix(DB/Gossip): Fixes 17196
- Closes [17196 ](https://github.com/azerothcore/azerothcore-wotlk/issues/17196) …
=> fix(DB/gossip): fixes (azerothcore#17196) 

data/sql/updates/pending_db_world/rev_1699081574664733400.sql
- Closes 
they both sell food/water (+ checked in mangos wotlk db)
1.
2.
3. …
=> fix(DB/Creature): Add vendor food flags to Boots & Gant

src/server/game/Entities/Player/Player.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptMgr.h
Add a `OnAfterSpecSlotChanged` hook that fires just after the player changes their spec slot using the dual spec feature. This is to be used for an upcoming public module I am working on. …
=> Feat (Core) Add `OnAfterSpecSlotChanged` hook

data/sql/updates/pending_db_world/rev_1699283615092861500.sql
- Closes 
Only subname (Food & Drink)
1.
2.
3. …
=> fix(DB/Creature): Add vendor food flags to Targrom

data/sql/updates/pending_db_world/rev_1699385295763888300.sql
It targeted a totem and sent my healer back to durotar.
set Target Player only
Spell has target player only flag.
1.
2.
3. …
=> fix(DB/SAI): Gargantuan Abyssal's Meteor should target only players

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
NaN
NaN
1. go to the eye
2. go to the room of the astromancer
3. check whether the behaviour is the same as before the PR …
=> refactor(Scripts/TheEye): High Astromancer Solarian script refactored using taskscheduler

data/sql/updates/pending_db_world/rev_1698997416639705600.sql, src/server/game/Spells/SpellInfoCorrections.cpp
Chains of Naberius was (uncapped) 40 yards AoE MC.
Added missing shadow fissure spell.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5981
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16881
https://youtu.be/hUMNJMuTZ8I?t=114
Mangos wotlk db for fissure timer
.go c id 20483
Should cast shadow fissures (player only)
Should not MC you if you're alone (can MC if you have a pet, threatlist > 1) …
=> fix(DB/SAI): Naberius

data/sql/updates/pending_db_world/rev_1698991655707226900.sql
https://youtu.be/uzMbKMAwvc4?t=231
1.
2.
3. …
=> fix(DB/Custom): Sundering Swipe should stack from different sources

data/sql/updates/pending_db_world/rev_1699424064948487600.sql
https://youtu.be/hQr0b6rfVI0?t=992
1.
2.
3. …
=> fix(DB/Custom): Virulent Poison should stack from different sources

data/sql/updates/pending_db_world/rev_1699465982525072500.sql
subname (food and drink)
1.
2.
3. …
=> fix(DB/Creature): Add vendor food flags to Feranin

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/shared/SharedDefines.h
- Closes 
- Prerequisite for #17632 
1.
2.
3. …
=> fix(Core/Unit): Implement GetDisplayRace()

data/sql/updates/pending_db_world/rev_1698776108922297000.sql
Also missing a GO spawn (corpse/bones), but need a sniff for that.
Item is wasted if the NPC is dead.
No source, but it should either A) Spawn the npc (if dead) or B) Not let you use the item (if dead), currently if the npc is dead and use the item, you simply waste it without anything happening.
.additem 30618
.go c id 18707
Kill it, go next to the pillar and try to use the item, it shouldn't let you, respawn him and retry.  …
=> fix(DB/Conditions): Require Torgos to be alive to use Trachela's Carcass

data/sql/updates/pending_db_world/rev_1699518417423954400.sql
https://youtu.be/TDEwRyC9RpA?t=413
1.
2.
3. …
=> fix(DB/Custom): Acidic Bite should stack from different sources

data/sql/updates/pending_db_world/rev_1699599829931372600.sql
https://youtu.be/18Bih02nsWo?t=203
1.
2.
3. …
=> fix(DB/Custom): Tunneler Acid should stack from different sources

data/sql/updates/pending_db_world/rev_1699565925227660500.sql
https://youtu.be/gNa6FKOL0NM?t=247
1.
2.
3. …
=> fix(DB/Custom): Sunder Armor should stack from different sources

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp
Updates AQ20/Kurinnaxx to modern standards.
All abilities appear to fire normally. Ossirian yells on boss death. Andorov spawns on boss death.
None. …
=> (Scripts/AI) AQ20: Modernize Kurinnaxx

data/sql/updates/pending_db_world/extra-auras-caribdis-cyclone.sql
Uses all sniffed auras I could find for the cyclone. Which includes a serverside aura.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17511
- Closes https://github.com/chromiecraft/chromiecraft/issues/6233
None I know of …
=> fix(DB/SSC): make sure Fathomguard Caribdis Cyclone is visible

src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
1. engage void reaver
2. check that timers have changed
None I know of for Void Reaver …
=> fix(Scripts/TheEye): Void Reaver sniffed timers

data/sql/updates/pending_db_world/spell_script_tidalvess.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
Turns out we also needed a spellscript for that, as there was already one for the caribdis part.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17526
None I know of …
=> fix(Scripts/SSC): make Fathomlord use his Spitfire Totem ability

data/sql/updates/pending_db_world/rev_1699030149135827600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5613
- Closes https://github.com/chromiecraft/chromiecraft/issues/5614
.q a 10269
.go q ender 10269
go to the quest spot, use the item to see where it is, cancel the aura and go there, it should NOT complete, use the item again and go again, should complete.
repeat for part 2 - 10275 …
=> fix(DB/SAI): Require 'Triangulation Point' buff to complete quests

data/sql/updates/pending_db_world/only-trigger-on-alive.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
=> fix(Scripts/SSC): make sure adds properly respawn and DoAction only fires on Tidalvess alive

apps/installer/includes/os_configs/osx.sh
=> fix(ci): macos

data/sql/updates/pending_db_world/dustbelchernpcfix-2.0.sql
- Errors generated in the worldserver console were: 
`WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c0016b7 Type: Creature Entry: 2716  Low: 5815) doesn't have waypoint path id: 0`
- #16499
There is still a small omission:
1. `Dustbelcher Wyrmhunter` id1=2716
2. id1=2907, it's `Dustbelcher Mystic`
3. `Dustbelcher Wyrmhunter` with two guid 6973 and 6975
- Addresses an issue found in #16499
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17618
1.the database import and run …
=> fix(DB/Creature): Dustbelcher NPC MovementType 2.0

data/sql/updates/pending_db_world/ssc-mark-of-the-illidari-drops.sql
cherry pick from CManGOS wotlk
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/17651
From CMaNGOS wotlk database
untested but NA
1. go to SSC
2. kill any of the trash with the entries you see above here enough
3. obtain marks of the Illidari that were not available before
4. ???
5. profit (free flasks)
none …
=> fix(DB/SSC): add Mark of the Illidari to trash loot tables

data/sql/updates/pending_db_world/rev_1698419449037051800.sql, src/server/scripts/Spells/spell_item.cpp
No free permanent black rat morph.
Go to the location for quest 9472
Try using the item on self/other players, it shouldn't work …
=> fix(DB/Spells): Carinda's Scroll of Retribution usable on players

data/sql/updates/pending_db_world/rev_1698183186698472700.sql
Normal/Crit hits, block and full block
- Closes https://github.com/chromiecraft/chromiecraft/issues/5147
https://www.wowhead.com/tbc/item=31858/
https://www.youtube.com/watch?v=21voOJ9UuFo Thanks @heyitsbench 
class with a shield
.learn 10021 (100% block)
.additem 31858 …
=> fix(DB/Procs): Darkmoon Card: Vengeance should proc on blocks

data/sql/updates/pending_db_world/rev_1690997579137104900.sql
-  Reference: https://github.com/TrinityCore/TrinityCore/issues/24726
-  co-author: @offl
- Closes https://github.com/chromiecraft/chromiecraft/issues/4626
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14315
- Closes https://github.com/chromiecraft/chromiecraft/issues/4390
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13708
- 
- 
1.
2.
3. …
=> fix(DB/Quest): improve Veil Lithic: Preemptive Strike

data/sql/updates/pending_db_world/rev_1695587871089572200.sql
condition added in specific area
- Closes 
1. quest add 10679
2. Please note that the item must be used in shadowmoon valley …
=> fix(DB/Quest): improve Quenching the Blade

data/sql/updates/pending_db_world/rev_1699840779122160400.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
=> fix(Scripts/Karazhan): Implement Nightbane summon emote and despawn on evade

src/server/game/AI/CreatureAI.h, src/server/game/AI/ScriptedAI/ScriptedCreature.h
QoL change to keep individual AI scripts from having to declare their own TaskScheduler.
Moves the ScheduledTask and EventMap private objects up to the `CreatureAI` class. EventMap was currently declared in `BossAI` even though it already existed in `CreatureAI`, so I removed it.
If any script refers to `BossAI::events` it should automatically pick up the one from `CreatureAI`. All event functionality in `BossAI` should also use the one in `CreatureAI` transparently. I don't see any logic in `BossAI` or `CreatureAI` regarding events that is specific to just that class.
No changes to `UpdateAI()` or any other …
=> (Core/Feat) Add built-in `TaskScheduler` to `CreatureAI`

src/server/game/Instances/InstanceScript.cpp, src/server/game/Instances/InstanceScript.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp, src/server/scripts/Northrend/AzjolNerub/AzjolNerub/instance_azjol_nerub.cpp, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/instance_ruby_sanctum.cpp, src/server/scripts/Northrend/DraktharonKeep/instance_drak_tharon_keep.cpp, src/server/scripts/Northrend/Gundrak/instance_gundrak.cpp, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp, src/server/scripts/Northrend/Nexus/Nexus/instance_nexus.cpp, src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp, src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/instance_magtheridons_lair.cpp, src/server/scripts/Outland/TempestKeep/Mechanar/instance_mechanar.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/instance_arcatraz.cpp
Untwists the mind-twist that is `AddThing(add=false)`, at least for `InstanceScript`.
Adds `RemoveObject`, `RemoveDoor` and `RemoveMinion` helper functions to `InstanceScript`. Set the original `Add` versions to default to add, but they can be used as before if someone really wants to. Updated all calls to these functions to match.
Anubarak (doors)
- `.go xyz 550.863708 297.707977 228.705093 601 4.755584`
- engage boss
- observe doors around the platform go up after ~15 seconds
- kill boss
- observe doors around the platform go down
General Drakkisath …
=> (Core) InstanceScript: create `Remove` functions

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/Spell.cpp, src/server/game/Spells/SpellEffects.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17633
1.
2.
3. …
=> fix(Core/Spells): Banish should only be dispelled by Mass Dispel

data/sql/updates/pending_db_world/rev_1699845959191252800.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp, src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp, src/server/scripts/EasternKingdoms/Karazhan/karazhan.h
=> fix(Scripts/Karazhan): Implement Aran's Atiesh interaction

src/server/game/Instances/InstanceScript.cpp
Fixes a miss on the conversion from `Add(false)` to `Remove()` functions in InstanceScript.
- Closes 
1.
2.
3. …
=> fix(core/InstanceScript) Fix new Remove function conversion miss

data/sql/updates/pending_db_world/rev_1699998320216999100.sql, src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6154
1.
2.
3. …
=> fix(Scripts/Karazhan): Fix Temptation target

data/sql/updates/pending_db_world/rev_1699987913440503300.sql
20 ->
Only lurker is unchanged
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17513
- Closes https://github.com/chromiecraft/chromiecraft/issues/6236
1.
2.
3. …
=> fix(DB/Creature): Port SSC boss detection range from Mangos

src/server/game/Instances/InstanceScript.cpp
=> refactor(Core/Instance): Modernize a few player iterations

data/sql/updates/pending_db_world/rev_1700080856070649700.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
=> fix(Scripts/SSC): Respawn Leotheras and fix last phase transition

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/ruins_of_ahnqiraj.cpp
=> refactor(Scripts/RuinsOfAhnQiraj): Clean up script files

src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_epoch_hunter.cpp, src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/boss_lieutenant_drake.cpp
=> refactor(Scripts/OHF): Clean up script files

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
=> fix(Scripts/SCC): Clear Leotheras' Whirlwind aura on demon phase

src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_selin_fireheart.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp
=> refactor(Scripts/MagistersTerrace): Update scripts to new register model

data/sql/updates/pending_db_world/hilarys_necklace.sql
https://github.com/TrinityCore/TrinityCore/issues/20376
- Adds missing completion event for quest Hilary's Necklace
1. .tele lakeshire
2. .quest add 3741
3. .quest complete 3741
4. Turn in quest …
=> fix(DB\SAI): Port completion event for quest Hilary's Necklace from Trinity

data/sql/updates/pending_db_world/rev_1700101479282219800.sql, src/server/scripts/EasternKingdoms/zone_stormwind_city.cpp
=> refactor(Scripts/Stormwind): Move Bartleby script to SAI

src/server/scripts/Kalimdor/boss_azuregos.cpp, src/server/scripts/Outland/boss_doomlord_kazzak.cpp, src/server/scripts/Outland/boss_doomwalker.cpp, src/server/scripts/World/boss_emerald_dragons.cpp
=> refactor(Scripts/World): Clean up script files

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_hydross_the_unstable.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_morogrim_tidewalker.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
=> refactor(Scripts/SCC): Update spell scripts to the new register model

src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_gyrokill.cpp, src/server/scripts/Outland/TempestKeep/Mechanar/boss_gatewatcher_ironhand.cpp, src/server/scripts/Outland/TempestKeep/Mechanar/boss_mechano_lord_capacitus.cpp, src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp, src/server/scripts/Outland/TempestKeep/Mechanar/boss_pathaleon_the_calculator.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/boss_harbinger_skyriss.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/boss_wrath_scryer_soccothrates.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/boss_zereketh_the_unbound.cpp, src/server/scripts/Outland/TempestKeep/botanica/boss_high_botanist_freywinn.cpp, src/server/scripts/Outland/TempestKeep/botanica/boss_thorngrin_the_tender.cpp
=> refactor(Scripts/TempestKeep): Clean up script files

data/sql/updates/pending_db_world/rev_1700133549563685500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6312
1.
2.
3. …
=> fix(DB/Creature): Add Fear proc aura to Fear Fiend

src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
=> fix(Scripts/Karazhan): Fix chess and optional boss not saving players

src/server/scripts/EasternKingdoms/ZulGurub/boss_marli.cpp
Modernize ZG20/Mar'li encounter. I did not attempt to increase accuracy in this PR, only to convert to the latest AI conventions. All functionality should remain the same. …
=> refactor(Scripts/AI) ZG20: Mar'li (Spider Boss) modernization

data/sql/updates/pending_db_world/rev_1699978192145266700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6240
mangos wotlk db
1.
2.
3. …
=> fix(DB/Creature): Port Underbog Colossus immunities from Mangos

data/sql/updates/pending_db_world/rev_1700153080985098500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14744
- Closes https://github.com/chromiecraft/chromiecraft/issues/4852
.go ga GUID …
=> fix(DB/Gameobject): Port Bloodsail Charts spawns from Mangos

data/sql/updates/pending_db_world/rev_1699868248910672500.sql
sunder armor type, casted by multiple mobs in a close proximity, etc.
1.
2.
3. …
=> fix(DB/Spell): Sunder Armor should stack from different sources

data/sql/updates/pending_db_world/rev_1699988688060367046.sql, src/server/scripts/EasternKingdoms/ZulGurub/boss_venoxis.cpp
Modernize ZG20/Venoxis encounter. I did not attempt to increase accuracy in this PR, only to convert to the latest AI conventions. All functionality should remain the same.
No changes to AI logic.
1. `.go xyz -12007.214844 -1691.049683 32.284668 309 3.726766`
2. Clear trash
3. Engage boss
4. Observe same mechanics as before this PR …
=> refactor(Scripts/AI) ZG20: Venoxis (Snake Boss) modernization

data/sql/updates/pending_db_world/rev_1700225021308335400.sql
=> fix(DB/Gameobject): Sniffed Values for 187564 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700224590195626900.sql
=> fix(DB/Gameobject): Sniffed Values for 188352 'Flame of Shattrath'

data/sql/updates/pending_db_world/rev_1700223778914584100.sql
=> fix(DB/Gameobject): Sniffed Values for 187559 'Horde Bonfire'

data/sql/updates/pending_db_world/rev_1700255223611644400.sql
=> fix(DB/Gameobject): Sniffed Values for 187934 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700248467461377500.sql
=> fix(DB/Gameobject): Sniffed Values for 187914 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700249654490511700.sql
=> fix(DB/Gameobject): Sniffed Values for 187916 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700254890063286500.sql
=> fix(DB/Gameobject): Sniffed Values for 187932 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700255606064082200.sql
=> fix(DB/Gameobject): Sniffed Values for 187937 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700249979389044300.sql
=> fix(DB/Gameobject): Sniffed Values for 187917 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700255484344500100.sql
=> fix(DB/Gameobject): Sniffed Values for 187936 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700250718822076700.sql
=> fix(DB/Gameobject): Sniffed Values for 187919 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700251060700790600.sql
=> fix(DB/Gameobject): Sniffed Values for 187920 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700251324503437500.sql
=> fix(DB/Gameobject): Sniffed Values for 187921 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700255012639881700.sql
=> fix(DB/Gameobject): Sniffed Values for 187933 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700254727998929800.sql
=> fix(DB/Gameobject): Sniffed Values for 187931 'Alliance Bonfire'

data/sql/updates/pending_db_world/rev_1700298804472938000.sql, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/instance_shadow_labyrinth.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5936
.cast back 33493 
get hit 5 times …
=> fix(Core/Spells): Script Mark of Malice

data/sql/updates/pending_db_world/rev_1700253077457885100.sql
=> fix(DB/Gameobject): Sniffed Values for 187923 'Alliance Bonfire'

src/common/Threading/ProcessPriority.cpp
- Delete double include `Log.h`
=> chore(Cleanup/Includes): delete double include

src/server/game/OutdoorPvP/OutdoorPvP.cpp, src/server/game/OutdoorPvP/OutdoorPvP.h, src/server/game/OutdoorPvP/OutdoorPvPMgr.cpp, src/server/game/OutdoorPvP/OutdoorPvPMgr.h, src/server/scripts/OutdoorPvP/OutdoorPvPEP.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPGH.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPHP.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPSI.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPTF.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp
- Make ptr's via `std::unique_ptr` instead of `new`
- Change name private fields to actual code style
1.
2.
3. …
=> chore(Game/OutdoorPvP): cleanup ptr's, rename private fields

src/server/scripts/Outland/Auchindoun/ManaTombs/boss_pandemonius.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5857
[wowhead comment](https://www.wowhead.com/wotlk/npc=18341/pandemonius) / retail (in the issue)
.go c id 18341
Pull, room should aggro …
=> fix(Scripts/ManaTombs): Pandemonius should aggro the enitre room

data/sql/updates/pending_db_world/rev_1700337467933170800.sql, src/server/scripts/Spells/spell_item.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6042
.q add 7583
.tele blasted
go to tainted scar, use the item on a commander …
=> fix(DB/SAI): Doomguard Commander - Crystal Prison

src/server/scripts/Events/midsummer.cpp
- Closes 
.cast 46337
transform to crab
remove aura
transform to normal …
=> refactor(Scripts/Midsummer): AuraEffectRemoveFn -> AuraEffectApplyFn

data/sql/updates/pending_db_world/rev_1700395742200811100.sql
PROC_FLAG_DONE_MAINHAND_ATTACK
PROC_FLAG_DONE_OFFHAND_ATTACK
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17127
- Closes https://github.com/chromiecraft/chromiecraft/issues/6075
in the issue
.learn 51527 - rank 3 static shock
.setskill 118 450 - dual wield
.cast 25504 - windfury proc
.cast 60103 lava lash
.cast 32176 stormstrike
.cast 49279 LB
.cast 49269 CL (no cd)
.cast 60043 Lava Burst …
=> fix(DB/Spells): Static Shock proccing on non-melee attacks and abilities

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6333
checked on recycled, by @heyitsbench 
.go c id 16473 …
=> fix(Core/Spells): Spotlight having a duration

data/sql/updates/pending_db_world/rev_1700401952686093600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6138
tooltip/in the issue
.aura 54283 - crit buff
.aura 54675 - crit buff
.aura 15363 - inspiration r3
.cast 48113 - pom …
=> fix(DB/Spells): Prayer of Mending should proc Inspiration

data/sql/updates/pending_db_world/rev_1700477079190660500.sql
=> fix(DB/Creature): Lady Vashj should despawn on evade

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Maps/Map.cpp, src/server/game/Maps/Map.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16670
1.
2.
3. …
=> fix(Core/Creature): Move DespawnOnEvade() respawn handling to map level

data/sql/updates/pending_db_world/vashjirhonorguard-frighteningshout.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17790
- Closes https://github.com/chromiecraft/chromiecraft/issues/6335
1. go to SSC
2. find the honor guards
3. get feared …
=> fix(DB/SSC): allow Vashj'ir Honor Guard to use Frightening Shout

data/sql/updates/pending_db_world/rev_1700504837723904000.sql
=> fix(DB/GameObject): Fix being able to target Vashj's bridge

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
=> fix(Scripts/TheEye): adjust Solarian timers based on sniffs

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp, src/server/game/AI/ScriptedAI/ScriptedCreature.h, src/server/scripts/Outland/TempestKeep/botanica/boss_commander_sarannis.cpp
Simple way to schedule timed events, including support for unique events (non repeatable)
- Closes 
1.
2.
3. …
=> feat(Core/AI): Implement ScheduleTimedEvent() helper

src/server/scripts/Outland/TempestKeep/botanica/boss_laj.cpp
=> refactor(Scripts/Botanica): Update Laj's script after latest changes

src/server/game/World/World.cpp
=> chore(Core/World): Fix typo in the previous commit

src/server/game/Chat/Channels/Channel.cpp, src/server/game/Chat/Channels/Channel.h
1. Simplify some chat channel condition checks with the use of the proposed method
1. The entire chat code needs to be refactored. Some condition checks don't make sense and I have not tested all cases but some checks seem contradictory. I kept everything as-is, as to not introduce any new bug.
=> chore(chat): add Channel::ShouldAnnouncePlayer() method

src/server/game/Chat/Channels/Channel.cpp, src/server/game/Chat/Channels/Channel.h
=> chore(Core/Player): codestyle

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
Improve creature chase movement so it doesn't appear "laggy" and so creatures does not always stop immediately at max melee range.
See current behaviour here:
https://youtu.be/3f27EWJBPr4
New behaviour:
https://youtu.be/4dKaqg_jPjs
(Note: Videos still uploading/processing so quality might still be bad).
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/17543
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/13630
The logic to predict chase destination is derived from [ChaseMovementGenerator.cpp](https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/blob/master/src/server/game/Movement/MovementGenerators/ChaseMovementGenerator.cpp) so credits to @Ovahlord of [The Cataclysm Preservation Project](https://github.com/The-Cataclysm-Preservation-Project …
=> Improve chase movement

.github/README.md
=> fix(Docs): readme update with new CI

src/server/game/Spells/SpellInfoCorrections.cpp
closes https://github.com/azerothcore/azerothcore-wotlk/issues/16248
- Closes 
1.
2.
3. …
=> fix(Core/Spells): Haunted should not be right-clickable

src/server/game/Entities/Player/Player.cpp, src/server/game/Groups/Group.h, src/server/game/Handlers/GroupHandler.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/132538db1dfb3c495294eeb5acfead59dea02b5c)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/250e8d998bca7f239e2393b6d002441f70d4daf0)
* part https://github.com/azerothcore/azerothcore-wotlk/issues/11070
Group should be created when the first invite is sent, not when the invite is accepted. This makes it so you can leave a not yet visible group with `/run LeaveParty()` (CMSG_GROUP_DISBAND)
- Closes 
Can be tested by inviting people and running the the command …
=> fix(Core/Groups): Create the group at first invite

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp, src/server/game/AI/ScriptedAI/ScriptedCreature.h, src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp
=> refactor(Scripts/BlackTemple): Modernize Najentus boss script

src/common/Utilities/EventProcessor.h, src/common/Utilities/Types.h, src/common/Utilities/advstd.h, src/server/database/Database/MySQLConnection.cpp, src/server/game/Chat/ChatCommands/ChatCommand.h, src/server/game/Chat/ChatCommands/ChatCommandTags.h
* Clean advstd to use std c++20 features
* Use ABORT instead of std::abort
- Closes 
1.
2.
3. …
=> chore(Core/Misc): Clean up workarounds

src/server/scripts/Kalimdor/zone_darkshore.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/2840
The bug happens due to the quest Plagued Lands given by NPC entry 3701. After completion a spell will be cast on the bear, which sets StandState to DEAD (7), since the State is never changed back, the bear persists in a dead state.
**REMEMBER**: …
=> fix(Scripts/Darkshore): Rabid Thistle Bear spawning with StandState Dead

src/server/game/Accounts/AccountMgr.cpp, src/server/game/Accounts/AccountMgr.h, src/server/game/Chat/Channels/Channel.cpp, src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/SocialMgr.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/Socialhandler.cpp, src/server/game/Server/WorldSession.cpp, src/server/game/Server/WorldSession.h
- The changes in this pull request will affect modules that depend on the moved function. The modules will need to be modified to take the API changes into account. …
=> chore(Core): move AccountMgr::IsGMAccount() to class WorldSession

.github/CODE_OF_CONDUCT.md, .github/README.md
https://www.contributor-covenant.org/version/2/1/code_of_conduct/
=> chore(docs): Update Code of Conduct to version 2.1

.github/SECURITY.md
=> chore(docs): update security.md

src/server/scripts/Commands/cs_ticket.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/17877
- Closes 
1.
2.
3. …
=> fix(Scripts/Command): ticket comment should allow input

src/server/scripts/Commands/cs_gobject.cpp
* close https://github.com/azerothcore/azerothcore-wotlk/issues/8129
- Closes 
1.
2.
3. …
=> fix(Scripts/Commands): Display GUID on gob info

src/server/scripts/EasternKingdoms/MagistersTerrace/boss_vexallus.cpp
=> refactor(Scripts/MagisterTerrace): Update Vexallus script

src/server/scripts/Commands/cs_learn.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7529
1.
2.
3. …
=> fix(Script/Commands): Make sure learn all lang also give you the skill

.github/workflows/issue-labeler.yml
=> chore(CI): bump issue labeler version

data/sql/updates/pending_db_world/rev_1701389243654647400.sql, src/server/scripts/Commands/cs_misc.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/5549
- Closes 
1.
2.
3. …
=> fix(Scripts/Command): Allow player name/guid in additem

src/server/game/Instances/InstanceScript.cpp, src/server/game/Scripting/ScriptDefines/GlobalScript.cpp, src/server/game/Scripting/ScriptDefines/GlobalScript.h, src/server/game/Scripting/ScriptMgr.h
=> feat(Core/Scripting): Implement AfterInstanceGameObjectCreate() global hook

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
=> refactor(Scripts/SerpetnshrineCavern): Clear up unused variables

data/sql/updates/pending_db_world/deathclaw-wander.sql
he seems to wander on wotlk classic rn
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16892
1.
2.
3. …
=> fix(DB/BloodmystIsle): add wander movement to Deathclaw

data/sql/updates/pending_db_world/rev_1701692168915380100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6378
.cast 65728/65729 …
=> fix(DB/Spells): Hellfire Peninsula portal XYZ.

data/sql/updates/pending_db_world/rev_1701758049251094300.sql
https://github.com/azerothcore/azerothcore-wotlk/pull/17462/files#diff-909fc7d2e9e320b0fd9f17cc23923b6967063e82263b1c1bca86e21104aeb612R22-R32
Got Overridden by 
https://github.com/azerothcore/azerothcore-wotlk/pull/17459/files#diff-6da7366bead1c9a10b820aeaa6637f11c7f8ca4b02389698018bee6b0a135816R32
- Closes https://github.com/chromiecraft/chromiecraft/issues/6379
1.
2.
3. …
=> fix(DB/Pools): Correct Inconspicuous Landmark

data/sql/updates/pending_db_world/SerpentShrine.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h
=> fix(scripts/SerpentShrine): #17918 Errors generated

data/sql/updates/pending_db_world/shadow-of-leotheras-health-set.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
**additionally**: make sure the demon split has the same HP as Leotheras himself during the 15% p3 transition
- Closes https://github.com/chromiecraft/chromiecraft/issues/6380
1.
2.
3. …
=> fix(Scripts/SSC): Leotheras demon form fixes

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
Fixes some codestyle related things from https://github.com/azerothcore/azerothcore-wotlk/pull/17939
N.A.
1.
2.
3.
N.A. …
=> fix(Scripts/SSC): codestyle fix in SSC after recent PR

src/server/scripts/Events/midsummer.cpp
=> refactor(Scripts/Midsummer): use scheduler provided by CreatureAI

src/server/scripts/Commands/cs_go.cpp
- Closes 
1. .go xyz 0 0 0 5 (You can replace 5 with any invalid map)
2.
3. …
=> fix(Scripts/Commands): Crash on go xyz with invalid mapid

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/MovementHandler.cpp, src/server/game/Handlers/TaxiHandler.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.h, src/server/game/Scripting/ScriptMgr.h, src/server/game/Spells/SpellEffects.cpp, src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
- Remove unused AnticheatSetSkipOnePacketForASH() function from what seems to be remnants of an anti-cheat system that is no longer present in code
1.
2.
3. …
=> chore: remove unused AnticheatSetSkipOnePacketForASH() function

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
Drinking Routine of Aran was not alway working properly and sometimes it would trigger on resetting  the boss.
- Closes 
1. Pull Aran
2. Bring his mana down to 15% 
3. After the next normal spell he should start the drinking routine
1. Pull Aran
2. Make him drink
3. Bring his mana down to 10%
4. Make him evade
5. Check if drinking routine starts on reset …
=> fix(Scripts/Karazhan): fixing the Aran drink routine and reset behavior

data/sql/updates/pending_db_world/rev_1702246889888310000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6439
1.
2.
3. …
=> fix(DB/SSC): Added knockback immunity Fathom-Lord adds

data/sql/updates/pending_db_world/rev_1702245200712395800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6437
- Closes https://github.com/chromiecraft/chromiecraft/issues/6436
- Closes https://github.com/chromiecraft/chromiecraft/issues/6435
- Closes https://github.com/chromiecraft/chromiecraft/issues/6417
1.
2.
3. …
=> fix(DB/SSC): Added mechanic_immune_mask to a couple creatures

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6440
1.
2.
3. …
=> fix(Core/Spells): Add ignore LOS to Tidal Wave

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6441
- Closes https://github.com/chromiecraft/chromiecraft/issues/6427
- Closes https://github.com/chromiecraft/chromiecraft/issues/6428
1.
2.
3. …
=> fix(Core/SSC): Added boss boundaries

data/sql/updates/pending_db_world/rev_1702268269121700300.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp, src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6442
1.
2.
3. …
=> fix(Core/SSC): Fix Lady Vashj summons

data/sql/updates/pending_db_world/delete_unused_spellscript_name.sql
Spell script name got deleted in https://github.com/azerothcore/azerothcore-wotlk/pull/17982 and is now unused
n.a.
n.a.
1.
2.
3.
n.a.
None related …
=> fix(DB/SpellScript): remove spell_script_names entry that is no longer used

data/sql/updates/pending_db_world/rev_1700894450549367900.sql
After completing the quest, Creature 253 holds the material in his hand to craft the Invisibility Potion。
After completing the quest, NPCs 251 drink the Invisibility Potion in their hands。
- Closes 
1. .Create an affiliate role
2. .level 6++
3. .quest add 112
4. .quest complete 112
5. .go xyz -9460.299805 31.938900 57.049400 0
6. Complete the task
7. NPCs should have test tubes in both hands when making invisibility potions
8. Quest accepted "The Escape"
9. .go xyz -10014.00000 37.605 35.169 0
10. Complete the task
11. NPCs drink potions in their hands …
=> fix(DB/Creature) Add items to Creature hands

src/server/scripts/Outland/boss_doomwalker.cpp
=> refactor(Scripts/Outland): Update Doomwalker to new register model

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp
Rotation speed lines up with retail sniffs
- Closes https://github.com/chromiecraft/chromiecraft/issues/6448
untested
1.
2.
3. …
=> fix(Scripts/SSC): make The Lurker Below spout rotate faster again

data/sql/updates/pending_db_world/rev_1702318402325328200.sql, src/server/game/AI/CoreAI/UnitAI.h, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.h, src/server/game/Spells/Auras/SpellAuraEffects.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6414
- Closes https://github.com/chromiecraft/chromiecraft/issues/6415
1.
2.
3. …
=> fix(Core/SAI/SSC): Allow Farthest target to set a min distance

data/sql/updates/pending_db_world/rev_1702340603344359300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6453
1.
2.
3. …
=> fix(DB/Loot): Lady Vashj non-set items

data/sql/updates/pending_db_world/rev_1702347891613495300.sql
Values are taken from CMangos (TBC)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6420
1.
2.
3. …
=> fix(DB/SSC): update bosses movement speed

data/sql/updates/pending_db_world/rev_1702346080894902800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6456
1.
2.
3. …
=> fix(DB/SSC): Fix Toxic Sporebats Z Position

data/sql/updates/pending_db_world/rev_1702339323045769600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6455
1.
2.
3. …
=> fix(DB/SSC): Coilfang Strider should not be immune to snare/root

data/sql/updates/pending_db_world/rev_1702342807328245400.sql
- Closes non-reported bug
1.
2.
3. …
=> fix(DB/Item): Tainted Core loot rules

data/sql/updates/pending_db_world/rev_1702306388357732400.sql, src/server/scripts/Commands/cs_debug.cpp
- Closes 
.wpgps - should work now
.wpgps sai - should format for waypoints (SAI) table. …
=> fix(Scripts/Commands): fix wpgps and add sai option for formating

data/sql/updates/pending_db_world/rev_1702220889643717100.sql
Add a merge Sigil event for NPCs
- Closes 
1. .quest add 640
2. .go c 11291
3. Complete the quest and wait for the NPC to recast with the spell …
=> Fix(DB/SAI) Events are added after completing a mission

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp
=> fix(Scripts/SerpentshrineCaverns): fix  double submerge phases

data/sql/updates/pending_db_world/rev_1702120071739163800.sql
- Finishs some TODOs of #17549 
1.
2.
3. …
=> fix(Event/Midsummer): miscellaneous cleanups of spawns

data/sql/updates/pending_db_world/rev_1702391940911282400.sql
Just changed the SAI for the spell to be casted properly.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6418
1.
2.
3. …
=> fix(DB/SAI): Vashj'ir Honor Guard should cast Freightening Shout

data/sql/updates/pending_db_world/rev_1702390051865119400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6381
1.
2.
3. …
=> fix(DB/SSC): Fathom-Guard Caribdis should be able to be interrupted

data/sql/updates/pending_db_world/rev_1702400889402948200.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6423
1.
2.
3. …
=> fix(Core/SSC): Rancid Mushroom mechanic

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6446
1.
2.
3. …
=> fix(Scripts/SSC): play emerge animation on the Lurker Below and make sure whirl doesn't happen during spout

src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h
Plays for all players within given radius.
- Closes 
```c++
me->PlayRadiusSound(8571, 65);
me->PlayRadiusMusic(2523, 65);
``` …
=> feat(Core/Object): Play radius sound/music.

src/server/apps/authserver/Server/AuthSession.cpp, src/server/database/Updater/DBUpdater.cpp, src/server/scripts/Commands/cs_send.cpp, src/server/scripts/Commands/cs_server.cpp, src/server/scripts/Commands/cs_spectator.cpp, src/server/scripts/Commands/cs_tele.cpp, src/server/scripts/Commands/cs_ticket.cpp, src/server/scripts/Commands/cs_titles.cpp, src/server/scripts/Commands/cs_wp.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp, src/server/scripts/Spells/spell_item.cpp, src/server/scripts/Spells/spell_paladin.cpp
=> chore(Scripts): remove useless includes

src/server/game/Globals/ObjectMgr.cpp, src/server/game/Grids/Notifiers/GridNotifiers.cpp, src/server/game/Maps/MapInstanced.cpp, src/server/game/Movement/MovementGenerators/EscortMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/HomeMovementGenerator.cpp, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Tools/CharacterDatabaseCleaner.cpp
=> chore(Core): remove useless includes

.gitignore, src/server/scripts/World/go_scripts.cpp
- Closes #18031 , related to #15510 
- "Does this affect the Healthstones created via your Soulwells? Yes, of course" (https://www.wowhead.com/wotlk/spell=18693/improved-healthstone#comments)
1. Cast "Ritual of Souls" (Rank 1) with no talents: This should give a Master Healthstone with 2080 life
2. Put 1/2 talent point in "Improved healthstone". New Healthstones from your Soulwell should now give 2288 life
3. Put 2/2 talent point in "Improved healthstone". New Healthstones from your Soulwell should now give **2496** life
4. Cast "Ritual of Souls" (Rank 2) with no talents: This should give a Fel Healthstone with 4280 life
5. Put 1/2 talent point in "Improved healthstone". New Healthstones from your Soulwell should now give 4708 …
=> #18031 fix ritual of souls

data/sql/updates/pending_db_world/rev_1703092164960613400.sql
https://github.com/azerothcore/azerothcore-wotlk/pull/17741#issuecomment-1864810781
https://youtu.be/tkJI1iQLQJQ?t=44 
Duration of [Power Burn](https://www.wowhead.com/wotlk/spell=40305/power-burn) and that it shouldn't proc 20 times if you use divine storm, as an example.
.aura 40303 …
=> fix(DB/Procs): Spell Bomb not having cooldown

src/server/scripts/Northrend/AzjolNerub/ahnkahet/instance_ahnkahet.cpp, src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/instance_obsidian_sanctum.cpp, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp, src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp, src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp, src/server/scripts/Northrend/Gundrak/instance_gundrak.cpp, src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp, src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel_teleport.cpp, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp, src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp, src/server/scripts/Northrend/Nexus/Nexus/boss_anomalus.cpp, src/server/scripts/Northrend/Nexus/Oculus/instance_oculus.cpp, src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp, src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/utgarde_pinnacle.cpp, src/server/scripts/Northrend/zone_borean_tundra.cpp, src/server/scripts/Northrend/zone_dragonblight.cpp, src/server/scripts/Northrend/zone_storm_peaks.cpp
=> chore(Scripts/Northrend): remove useless includes

data/sql/updates/pending_db_world/rev_1703920580435795500.sql
- Closes 
https://www.wowhead.com/wotlk/spell=50196/rotting-touch#comments
+ Multiple mobs in small area that apply it.
1.
2.
3. …
=> fix(DB/Custom): Rotting Touch should stack from different sources

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/SpellEffects.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3112
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2801
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1571
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/832
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/298
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11641
- Closes https://github.com/chromiecraft/chromiecraft/issues/4136
- Closes https://github.com/chromiecraft/chromiecraft/issues/1136
- Closes https://github.com/chromiecraft/chromiecraft/issues/4319 …
=> fix(Core/Unit): Remove delay for Conflagrate aura state

data/sql/updates/pending_db_world/zarakh.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16935
1.
2.
3.
None afaik …
=> fix(DB/BloodmystIsle): add sniffed abilities to Zarakh

src/server/game/Handlers/AuctionHouseHandler.cpp
When you have a new stackable item with the state ITEM_NEW and when somebody trying to sell part of items from the stack, this item will be not saved to inventory. This happens because item’s SaveToDB sets its state to ITEM_UNCHANGED, that makes SaveInventoryAndGoldToDB ignore this item and as result - item saved in DB but not in characters inventory.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17631
1.
2.
3. …
=> Fix(Core): Fix item disappearing on selling item on auction

data/sql/updates/pending_db_world/sunhawk-spy.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16895
1.
2.
3.
None afaik, hamstring is listed as known ability in the db, but I couldn't see this being cast on classic wotlk …
=> fix(DB/BloodmystIsle): add sniffed abilities to Sunhawk Spy

data/sql/updates/pending_db_world/morogrim-reach.sql
Credits to [Bench](https://github.com/heyitsbench) for the sniff. Version: 50791 wotlk classic
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18076
- Closes https://github.com/chromiecraft/chromiecraft/issues/6508
none afaik …
=> fix(DB/SSC): change Morogrim's combat reach and model bounds based on sniffs

data/sql/updates/pending_db_world/rev_1703449890835634600.sql, src/server/scripts/World/areatrigger_scripts.cpp
=> refactor(Scripts/Areatrigger): Move Scholazar Waygate script to SAI

data/sql/updates/pending_db_world/2023_12_14_00.sql, src/server/game/AI/SmartScripts/SmartAI.cpp, src/server/game/AI/SmartScripts/SmartAI.h, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScript.h, src/server/game/AI/SmartScripts/SmartScriptMgr.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.h, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
@heyitsbench This one is for you 😛
First of all, this PR aims to address some underlying issues with combat movement for ranged creatures that became a lot more noticable after implementing [improvements to chase movements](https://github.com/azerothcore/azerothcore-wotlk/pull/17557).
But as always I went a bit out of scope and decided to fix other issues with combat movement and spellcaster behaviour, that I found along the way 😛
Heres some before and after videos to show some of the things that this PR fix:
Before: https://youtu.be/vwS1tz2gk3Y
After: https://youtu.be/1PQGNUMc6A0
- Fix ranged creatures not chasing to melee range when unable to cast spells
- Fix ranged creatures sometimes not moving
- Fix ranged creatures not chasing in melee range
- Removed …
=> Fix combat movement

data/sql/updates/pending_db_world/rev_1704198878008192900.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11822
1.
2.
3. …
=> fix(DB/Conditions): Quest Sniffing Out the Perpetrator

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerQuest.cpp, src/server/game/Handlers/LFGHandler.cpp
* Cherry-pick Player::IsMaxLevel from TrinityCore
* Correctly hide XP reward for max-level players in LFG
* Closes #18101
- Closes 
1.
2.
3. …
=> fix(Core/LFG): Hide XP from max players

data/sql/updates/pending_db_world/rework-xintor.sql
Works very nicely with https://github.com/azerothcore/azerothcore-wotlk/pull/18026 now. Removed the different phases and whatnot.
This mob was featured in an old issue report which probably inspired the previous attempt to fix it. See: https://github.com/azerothcore/azerothcore-wotlk/issues/4091
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/4091
N.A.
1.
2.
3. …
=> fix(DB/HellfirePeninsula): remove botched caster movement scripting from Arch Mage Xintor

data/sql/updates/pending_db_world/rev_1704419804837515700.sql
=> fix(DB/Creature): Fix Shadow of Leotheras banish immunity

data/sql/updates/pending_db_world/rev_1703933164908912300.sql
- Closes #18078
.quest add 11865
.go ga 67649
.go ga 67650
.go ga 67651
.go ga 67652
.go ga 67654
.go ga 67656
.go ga 67658
.go ga 67660
.go ga 67662
.go ga 67664
.go ga 67666
.go ga 67668
.go ga 67670
.go ga 67672
.go ga 67674
place quest item (fur)
observe
get kill credit for the quest (this didn't work for me before and after this PR - maybe someone can please test & verify this)
1.
2.
3. …
=> fix(DB/Gameobject): Update 'Caribou Trap' spawns with sniffed values

data/sql/updates/pending_db_world/update_lurker_loottable.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18116
- Progress https://github.com/chromiecraft/chromiecraft/issues/6483
https://youtu.be/4M3Y2w8-pdw?si=I5hmBHPnzMj9K3kz&t=243
untested
1.
2.
3. …
=> fix(DB/SSC): change Ranger-General's Chestguard on Lurker to The Seal of Danzalar

data/sql/updates/db_world/2023_11_12_07.sql
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/18119
- Closes 
1.
2.
3. …
=> fix(DB): Correct bad delete query

data/sql/updates/db_world/2023_11_12_07.sql
=> fix(DB): Bad query

data/sql/updates/pending_db_world/rev_1704634658411960800.sql, src/server/game/Spells/SpellEffects.cpp, src/server/scripts/Spells/spell_rogue.cpp
* closes https://github.com/chromiecraft/chromiecraft/issues/6528
* Script ServerSide Vanish Purge
* Vanish Purge should not be able to unroot Tainted Core
- Closes 
1.
2.
3. …
=> fix(Script/Spell): Vanish Purge behavior

src/server/game/Entities/Player/Player.cpp
=> fix(Core/Player): Sometimes Player whisper is sent as boss whisper

data/sql/updates/pending_db_world/rev_1704643532152504000.sql, src/server/game/Miscellaneous/Language.h, src/server/scripts/Commands/cs_gobject.cpp
=> feat(Scripts/Commands): Implement gameobject respawn command

data/sql/updates/pending_db_world/rev_1704668562192640700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6527
1.
2.
3. …
=> fix(DB/Creature): Vashj's Enchanted Elementals knockback immunity

.github/actions/docker-tag-and-build/action.yml, .github/workflows/docker_build.yml
This PR merges the docker build CI from 3 jobs into a single job defined in the workflow. 
The current procudure is:
1. Various setup tasks
1. Free up disk space
2. download mod-eluna if running on primary branch
3. auth to dockerhub if running on primary branch
4. parse `acore.json` for a version tag
5. setup docker builder
2. Build containers. If running on primary branch, push to dockerhub
1. Worldserver
2. authserver
3. db-import
4. client-data downloader
5. tools
6. dev-server 
3. send a [repository dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatc …
=> refactor(CI): Squash docker ci into one workflow

data/sql/updates/pending_db_world/rev_1700913491921182500.sql, src/server/scripts/Outland/zone_netherstorm.cpp
_**no source needed only condition**_ 
- Closes 
1. quest add 10274
2. go to the designated mission location
3. …
=> fix(Scripts/Quest): improve Securing the Celestial Ridge

data/sql/updates/pending_db_world/rev_1704657014016572900.sql
- Closes #18059
- Closes chromiecraft/chromiecraft#6259
1.
2.
3. …
=> fix(DB/npc_text): Fix Orgrimmar Grunt directions for barber shop

.github/workflows/docker_build.yml
The `if` blocks failed to function properly for some conditional steps (such as if the step to log into dockerhub should happen). It's a minor thing so I'd rather it just work.
1.
2.
3. …
=> fix(CI): revert `if` in job conditionals on docker build
