src/server/game/Entities/Creature/Creature.cpp
- this is necessary to correctly spawn creatures within small confines
- 0.42f is as good as 1.0f to detect and correct reasonable z errors in DB spawn data
- Closes #16839
1.
2.
3. …
=> fix(Core/Creature): Reduce z offset for automated spawn correction

data/sql/updates/pending_db_world/rev_1705005159549564700.sql
=> fix(DB/Creature): Sniffed Values for 28344 'Blazzle'

src/server/scripts/Spells/spell_rogue.cpp
=> fix(Scripts/Rogue): Fix Vanish not granting stealth

src/server/game/Combat/ThreatMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18161
- Closes https://github.com/chromiecraft/chromiecraft/issues/4411
- Closes https://github.com/chromiecraft/chromiecraft/issues/6471
1.
2.
3. …
=> fix(Core/ThreatMgr): Remove temp threat on resetting threat list

data/sql/updates/pending_db_world/rev_1705092713015591500.sql
=> fix(DB/Gameobject): Midsummer gameobject spawn cleanups

data/sql/updates/pending_db_world/rev_1705189109284336800.sql
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/18041
- Closes 
1.
2.
3. …
=> fix(DB/Creature): Warlock trainers in Orgrimmar should talk orcish

data/sql/updates/pending_db_world/rev_1704744571249555200.sql
- Closes #16289
- Closes chromiecraft/chromiecraft/issues/5225
1.
2.
3. …
=> fix(DB/Gameobject): Sniffed Values for 180665 'Draconic for Dummies'

src/server/game/Entities/Player/Player.cpp
=> fix(Core/Player): Fix Player not starting at full health

data/sql/updates/pending_db_world/rev_1704713347931310000.sql, src/server/scripts/Events/midsummer.cpp
- Closes 
.event start 1
- visit Bonfire of opposing faction
- complete quest to desecrate the fire
- (observe flames disappearing and white steam)
- re-open gossip menu
- select gossip option to desecrate the fire again (without quest)
- observe white steam again
-- Alliance Bonfires
.go ga 76301
.go ga 76302
.go ga 76303
.go ga 76304
.go ga 76306
.go ga 76307
.go ga 76308
.go ga 76311
.go ga 76312
.go ga 76313
.go ga 76314
.go ga 76316
.go ga 76319
.go ga 76321
.go ga 76323
.go ga 76326
.go ga 76329
.go ga 76330
.go ga 76335
.go ga 76339
.go ga 76340 …
=> fix(DB/SAI): Move GameObjectScript go_midsummer_bonfire to SAI

data/sql/updates/pending_db_world/rev_1704518041243129300.sql, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
Make the text display for the local client
- Closes 
1.  Create a warrior, paladin or death knight 
2. quest add 24547
3. .gm on
4. .go xyz -35.684574 2208.219482 27.902550 631
5. await …
=> Fix(script/instance_icecrown_citadel) Lich King Whispers uses localized languages

src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
https://github.com/chromiecraft/chromiecraft/issues/6337
To note, multiple behaviors addressed in the issue are invalid or beyond scope. This PR only fixes those that are valid and within scope.
https://www.youtube.com/watch?v=qtBuI6SGtNc&t=264s&ab_channel=Gorillo
https://youtu.be/vSO2Ik_e69I?t=1276
1. Summon Nightbane
2. Observe the cleave
3. Observe both the liftoff and the landing threat resets
- Spawn/Respawn mechanics should pause for 1-2 seconds before initializing combat …
=> fix(scripts/Karazhan): Add cleave and threat resets to Nightbane

src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
The respawn of Sindragosa is broken due to the overwriting of the IsSindragosaIntroDone variable in the instance data. This issue arises during instance loading when the `ReadSaveDataMore` function is called. Before reading the `IsSindragosaIntroDone` variable, we invoke `SetData(DATA_BUFF_AVAILABLE, IsBuffAvailable)`, which may trigger the saving of the instance. However, since we are in the process of loading the instance, it leads to saving the instance with the default value of `IsSindragosaIntroDone`, which is false. As a result, Sindragosa might not respawn due to this broken mechanism.
- Closes …
=> fix(Scripts/IcecrownCitadel): Fix Sindragosa respawn

data/sql/updates/pending_db_world/tainted-ele-vashj.sql
As they target random targets, I wasn't really able to test this perfectly on my own. Behaviour does seem improved.
1.
2.
3. …
=> fix(DB/SSC): Make sure Tainted Elementals on Vashj have better movement

data/sql/updates/pending_db_world/lurker-adds.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6555
1.
2.
3. …
=> fix(DB/SSC): Make sure Lurker archers don't move after spawning

data/sql/updates/pending_db_world/aran-water-elementals.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6556
1.
2.
3. …
=> fix(DB/Karazhan): make sure conjured elementals on Aran don't move after spawning

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6530
NA …
=> fix(Scripts/SSC): make sure Vashj doesn't move during P2

src/server/game/Entities/Unit/Unit.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6246
.add 28785
.add 18970 2
Equip items, cast spells …
=> fix (Core/Unit) Apply Capacitor cooldown on trigger proc instead of on stack add

data/sql/base/db_world/item_dbc.sql, data/sql/base/db_world/lfgdungeons_dbc.sql, data/sql/updates/db_world/2024_01_20_06.sql, data/sql/updates/pending_db_world/rev_1705789020183035200.sql
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/18202
- Closes 
1.
2.
3. …
=> fix(DB): Collation error

src/server/apps/worldserver/worldserver.conf.dist
=> fix(Conf): typo

src/server/game/Instances/InstanceSaveMgr.cpp
=> fix(CORE/INSTANCE): typo

src/server/game/Spells/Spell.cpp, src/server/game/Spells/Spell.h
=> feat(Core/Spell): Add helper for TriggeredCastFlag

data/sql/updates/pending_db_world/tk-immunities-fix.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6593
not tested
1.
2.
3.
na …
=> fix(DB/TheEye): fix some trash immunities in The Tempest Keep

docker-compose.yml
It's an enhancement for Docker setup. Updated mysql image to the latest 8.3 version. After updating tested it locally with an existing data and worked perfectly.
none
To tested this change you will need to:
1. Create a brand new local azerothcore server setup using docker
2. Make sure that game is playable by creating a character and grabbing some items in-game
3. Update mysql database version up to 8.3
4. Deploy the updated image by running `docker compose up -d`
5. Test that game is playable, your character and items are in place
none …
=> chore(Docker): update mysql image to 8.3 version

data/sql/updates/pending_db_world/rev_1706601489665034800.sql
- Closes chromiecraft/chromiecraft#6608
1.
2.
3. …
=> fix(DB/Creature): Add Repair npcflag to 28344 Blazzle

data/sql/updates/pending_db_world/rev_1706904611004281600.sql
=> fix(DB/Creature): Sniffed Values for 26123 'Midsummer Supplier'

data/sql/updates/pending_db_world/rev_1706907081004004500.sql
=> fix(DB/Creature): Sniffed Values for 25980 'Heretic Bodyguard'

data/sql/updates/pending_db_world/rev_1706906586017433300.sql
=> fix(DB/Creature): Sniffed Values for 26124 'Midsummer Merchant'

data/sql/updates/pending_db_world/rev_1706907359764262400.sql
=> fix(DB/Creature): Sniffed Values for 25951 'Heretic Emissary'

data/sql/updates/pending_db_world/rev_1706907543488878700.sql
=> fix(DB/Creature): Sniffed Values for 25949 'Ice Caller Briatha'

data/sql/updates/pending_db_world/rev_1706908042852801100.sql
=> fix(DB/Creature): Sniffed Values for 26221 'Earthen Ring Elder'

src/server/game/Spells/Spell.cpp
=> Check if triggered spell has cast time

data/sql/updates/pending_db_world/rev_1705674468268232500.sql, src/server/scripts/Northrend/zone_dalaran.cpp
- Closes 
.go c 105492
observe toy plane flying a circle below the ceiling, a cable connecting it to the hook at the ceiling …
=> fix(Scripts/Dalaran): Update Toy Shop Toy Plane behaviour based on sniffs

data/sql/updates/pending_db_world/remove-sai-kael-adds.sql, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
boss-like adds should be in the cpp file, not in SAI.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6596
- Closes https://github.com/chromiecraft/chromiecraft/issues/6598
- Preparation for refactoring
N.A.
N.A.
N.A. …
=> fix(Scripts/TheEye): add Kael adds to the cpp script

data/sql/updates/pending_db_world/arcane_burst.sql
Behaviour lines up with sniffs + video
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18269
- Closes https://github.com/chromiecraft/chromiecraft/issues/5188
Video shows one spawn afaik. However the tooltip indicates 2 and the value for us is at least set at 2. …
=> fix(DB/ShadowmoonValley): add Arcane Explosion to Arcane Bursts and make them despawn

data/sql/updates/pending_db_world/rev_1707136369363220800.sql
- follow-up to #18263 and #18262
- Closes 
1.
2.
3. …
=> fix(DB/Creature): reassign equipment_id to creatures 25949, 26221

data/sql/updates/pending_db_world/rev_1707136158481006000.sql
=> fix(DB/Creature): Sniffed Values for 25924 'Twilight Speaker Viktor'

data/sql/updates/pending_db_world/rev_1707162962330463400.sql
=> fix(DB/Creature): 'Shaman Bonfire Bunny' spawns with sniffed values

data/sql/updates/pending_db_world/tainted_ele.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
Apparently under some circumstances Vashj can still move. I couldn't replicate but predict she can get stuck when she wants to cast something so I changed the location of the scheduler cancel as well as make sure she stops casting when she has to move.
Tainted elemental wasn't working perfectly. As the range is unlimited on their poison bolt anyway we can just get a random player target, root the elemental and fire from that location. So caster movement is not relevant anyway. The behaviour was easier for me to put in script, and technically boss adds should be scripted in the boss script file anyway.
- Closes …
=> fix(Scripts/SSC): some Vashj fixes

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp, src/server/scripts/Outland/TempestKeep/Eye/instance_the_eye.cpp, src/server/scripts/Outland/TempestKeep/Eye/the_eye.h
- Closes 
Just refactoring for now. Although some fixes from sniffs I might already change. …
=> fix(Scripts/TheEye): Re-factor Kael'thas

data/sql/updates/pending_db_world/root_totem.sql, src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp, src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp, src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
- Closes unreported issue of totem moving around and not casting …
=> refactor(Scripts/ZulAman): refactor Halazzi

data/sql/updates/pending_db_world/Rev_1629488923927348.sql, src/server/scripts/Kalimdor/zone_azshara.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4185
1.- Create a druid with level 70+
2.- .go zonexy 14.2 47.9 16
3.- .quest add 10994
4.- Use the SouthFury Moonstone (the white sphere)
5.- Follow the Npc (female goblin) by the river and wait until you can speak to her
6.- The gossip option menu should show "Hand over the Southfury moonstone and I'll let you go." and give you an item for the quest. …
=> fix(Core/Creature): hardcoded gossip in zone_azshara

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
lmk what your thoughts are on this approach. vaguely inspired by the combat movement PR for caster chase behaviour
- Closes https://github.com/chromiecraft/chromiecraft/issues/6597
not really based on specific behaviour, just what makes sense in this case. boss shouldn't really move to melee people.
N.A. …
=> fix(Scripts/TheEye): Solarian movement

deps/boost/CMakeLists.txt
- This pull request is responsible for correcting a compatibility issue with the new cmake policies. It does not require any changes.
```
CMake Warning (dev) at deps/boost/CMakeLists.txt:35 (find_package):
Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
CMake variable BOOST_ROOT is set to:
D:\local\boost_1_81_0
For compatibility, find_package is ignoring the variable, but code in a
.cmake module might still use it.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
- Closes 
When a PR is ready to be tested, it will …
=> feat. (deps/boost) Update cmake file compatible with new policies

src/server/apps/worldserver/worldserver.conf.dist
- Closes chromiecraft/chromiecraft#6605
1.
2.
3. …
=> fix(Conf): disable LeaveGroupOnLogout by default

src/cmake/macros/FindOpenSSL.cmake
Author:    github.com/Shauren <shauren.trinity@gmail.com>
-  [X] CMake macros
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18281
- This is a copy of the latest FindOpenSSL.cmake file from TrinityCore commit ID [94aed68](https://github.com/TrinityCore/TrinityCore/commit/94aed6896873179b284b8b1911590ed9587466d6). Original author of that commit is tagged.  
Tested with OpenSSL version 1.1.1w, 3.1.2, 3.1.5, and 3.2.1.  All compile and build on Windows without error. Confirmed SSL version in-game.
1. Verify my testing by building with …
=> Fix(Core/Crypt): Updated cmake macro for OpenSSL

src/server/database/Database/MySQLConnection.cpp
- Currently, the library is no longer supported on macOS, so the tests were failing. That way, we can continue to preserve both methods, and for now support all operating systems, since now the tests also work on macOS.
- Closes 
- Apparently the library in macOS is outdated. Which causes the tests, when doing a merge, to fail in said operating system.
- I don't know if there are other bugs, I hope the tests can be corrected, and in that way, know if there are more of them. …
=> feat(fix/build) mysql_stmt_bind_param deprecated in MYSQL 8.3

data/sql/updates/pending_db_world/phoenix-hawk-targets.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6654
N.A. …
=> fix(DB/TheEye): change the way Phoenix Hawk targets players with its abilities

data/sql/updates/pending_db_world/charm_immune_tk_trash.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18301
- Closes https://github.com/chromiecraft/chromiecraft/issues/6646
untested
N.A. …
=> fix(DB/TheEye): Astromancer and Star Scryer MC immunity

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
If she is reset during the vanish phase, she was never set back to aggressive react state.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18300
- Closes https://github.com/chromiecraft/chromiecraft/issues/6647
N.A.
N.A. …
=> fix(Scripts/TheEye): make sure Solarian always get reset to REACT STATE aggressive on reset

src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
Most likely crash happens because after this change https://github.com/azerothcore/azerothcore-wotlk/pull/12347 we didn't update `ContinueTaxiFlight` code. But to add the missing logic, I need to know how to reproduce this issue, so I added additional logging (besides crash fix).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18012
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16356
1.
2.
3. …
=> fix(Core/Taxi): Fixes crash when player logins and continues flight

apps/docker/Dockerfile
There's supposed to be a dollar sign there in order to reference a variable
- Closes 
1.
2.
3. …
=> Fix(Docker): Add missing dollar sign

data/sql/updates/pending_db_world/rev_1707833862449013500.sql
- Closes #18285 
1. Obtain following items **49856, 49857, 49858, 49859, 49861, 49860** (itemId's)
2. Use them simultaneously
3. Effects should not stack anymore …
=> fix(DB/Spell): Valentine event buffs grouping

data/sql/updates/pending_db_world/rev_1708176682270821900.sql
=> fix(DB/Gameobject): Sniffed Values for 19878 'Parts Crate'

data/sql/updates/pending_db_world/rev_1708086685540587800.sql
- Progress chromiecraft/chromiecraft#6638
1.
2.
3. …
=> fix(DB/Creature): Sniffed Values for 38023 'Crown Sprinkler'

data/sql/updates/pending_db_world/rev_1708086341083028600.sql
- Progress chromiecraft/chromiecraft#6638
1.
2.
3. …
=> fix(DB/Creature): Sniffed Values for 38016 'Crown Agent'

data/sql/updates/pending_db_world/rev_1708085955100234300.sql
- Progress chromiecraft/chromiecraft#6638
1.
2.
3. …
=> fix(DB/Creature): Sniffed Values for 38006 'Crown Hoodlum'

data/sql/updates/pending_db_world/rev_1708084988308010400.sql
- Progress chromiecraft/chromiecraft#6638
1.
2.
3. …
=> fix(DB/Creature): Sniffed Values for 37984 'Crown Duster'

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6680
logic
untested
N.A. …
=> fix(Scripts/SSC): do reset threat list for p3 in the right place

src/server/game/Guilds/Guild.cpp
- Closes chromiecraft/chromiecraft#6669
Before this PR it was possible to swap limited duration items into the guild bank.
e.g. add item 'Bountiful Feast'
.additem 46887
try to directly move 'Bountiful Feast' into guild bank from inventory
-> should not be possible
pull any item from the guildbank onto the 'Bountiful Feast' in the inventory
-> items get swapped
-> 'Bountiful Feast' gets preserved infinitely within the guild bank
after PR:
pull any item from the guildbank onto the 'Bountiful Feast' in the inventory
-> swapping is beeing prevented
When a …
=> fix(Core/Guild): Prevent swapping limited duration items into guild bank

data/sql/updates/pending_db_world/correct-cage.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h
Original script summoned Olum but he was pre-spawned on instance load (fixed by: https://github.com/azerothcore/azerothcore-wotlk/pull/17918)
The cage was left in the wrong place so I had to replace with the correct ID and the correct position. Also changed the position Olum moves to based on sniffs.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6474
N.A. …
=> fix(Scripts/SSC): remove double spawn of Seer Olum and implement correctly

data/sql/updates/pending_db_world/rev_1708440064627694000.sql
=> fix(DB/SAI): unlink non-existing entry from SAI 17671

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6664
1.
2.
3. …
=> fix(Scripts/TheEye): Thaladred should only chase players

data/sql/updates/pending_db_world/rev_1708422110137281100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6692
1.
2.
3. …
=> fix(DB/Creature): Crystalcore Sentinel interrupt immunity

data/sql/updates/pending_db_world/rev_1707992890120663700.sql
You shouldn't be able to toggle pvp on for other players in such a trivial way.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6513
1.
2.
3. …
=> fix(DB/Custom): Wand of Holiday Cheer PVP tagging.

data/sql/updates/pending_db_world/skullpile-spawn-time.sql, src/server/scripts/Outland/zone_terokkar_forest.cpp
didn't check. but there are likely conditions on the spells for the player to have 10 scrolls to summon them. if they don't have it the spell fails due to the conditions and we don't want to unsummon in that case
- Closes https://github.com/chromiecraft/chromiecraft/issues/6550
- Closes https://github.com/chromiecraft/chromiecraft/issues/6547 …
=> fix(Scripts/TerokkarForest): fix behaviour of skull piles in Skettis

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6663
1.
2.
3. …
=> fix(Scripts/TheEye): Fix Capernian chase distance

src/server/game/Spells/Spell.cpp
Fix the spell : https://www.wowhead.com/wotlk/spell=57678/emerald-acorn-effect
Used in quest : https://www.wowhead.com/wotlk/quest=13075/the-boon-of-remulos
- https://github.com/azerothcore/azerothcore-wotlk/issues/18353
1. .quest add 13075
2. .quest complete 13075
3. .go creature id 30562
4. Return the quest to the NPC
NOTHING …
=> fix(Crash/Quest/Spell) : The Boon of Remulos

data/sql/updates/pending_db_world/crystalcore_mechanic_repair.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6700
common sense, tooltip …
=> fix(DB/TheEye): allow Crystalcore Mechanics to only repair mechanicals

data/sql/updates/pending_db_world/netherstrand_armor_stack.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6702
untested
N.A. …
=> fix(DB/TheEye): allow Armor Disruption from Netherstrand Longbow to stack

data/sql/updates/pending_db_world/weapon_action.sql, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
Could not figure out how to accurately filter the targets for Resurrection
- Closes https://github.com/chromiecraft/chromiecraft/issues/6698
- Closes https://github.com/chromiecraft/chromiecraft/issues/6713
- Closes https://github.com/chromiecraft/chromiecraft/issues/6712
N.A. …
=> fix(Scripts/TheEye): Kael'thas - allow phases to progress as well when all creatures die as well as other fixes

src/server/game/AI/SmartScripts/SmartScript.cpp
It seemed unimplemented to me and was hence causing issues
- Closes https://github.com/chromiecraft/chromiecraft/issues/6697
N.A.
needs testing
N.A. …
=> fix(Core/SmartAI): implement param maxCount for SMART_TARGET_PLAYER_RANGE

src/server/apps/worldserver/worldserver.conf.dist
=> fix(Conf): remove ThreatRadius (unused)

src/server/shared/DataStores/DBCDatabaseLoader.cpp, src/server/shared/DataStores/DBCEnums.h, src/server/shared/Network/AsyncAcceptor.h, src/server/shared/Network/Socket.h, src/server/shared/Network/SocketMgr.h, src/server/shared/Packets/ByteBuffer.cpp, src/server/shared/Packets/ByteBuffer.h, src/server/shared/Realms/Realm.cpp, src/server/shared/Realms/RealmList.cpp, src/server/shared/Realms/RealmList.h
=> chore(Core/Shared): little cleanup

src/server/game/Time/UpdateTime.cpp, src/server/game/Time/UpdateTime.h, src/server/scripts/Commands/cs_server.cpp
I'd like to make a slight improvement to our diff measurement. 
Currently, we display the following diff measurements: 
`Update time diff: 10ms, average: 15ms.`
However, when it comes to measuring performance, just knowing the average doesn't always tell the whole story. Sometimes we've got these spikes or delays that can affect how the system performs overall.
So, I'm thinking we should spice it up a bit and start showing not just the average, but also some other stats like percentiles.
So my suggestion to output the next things:
This way, we gain a better sense of how performance truly varies and ensure we don't overlook any important details.
- …
=> feat(Core/UpdateTime): Improve diff time measurement.

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6711
1.
2.
3. …
=> fix(Scripts/TheEye): Fix Capernian not casting if at max range

src/server/scripts/Spells/spell_generic.cpp
Fixes crash in the Rogue T10 4P Bonus that is caused by capturing a target reference that may have been deleted at the moment of code execution.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18399
1.
2.
3. …
=> fix(Core/Spell): Fix crash in Rogue T10 4P Bonus

CMakeLists.txt
- Fix make errors in commit - d72a71a4b2ec33f2891c712642adbc63bb201e61
=> fix(Cmake): using policy 0153 if exist

data/sql/updates/pending_db_world/rev_1709225636578523600.sql
=> fix(DB/Gameobject): Sniffed Values for 'Barber Chair' spawns

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6665 …
=> fix(Scripts/TheEye): make legendary TK dagger have  100% proc chance

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6658
- Closes https://github.com/chromiecraft/chromiecraft/issues/6660
N.A. …
=> fix(Scripts/TheEye): make sure Telonicus doesn't erroneously cast Conflagration and cast Remote Toy instead

data/sql/updates/pending_db_world/rev_1708463355574751000.sql
-  [x] Database (SAI, creatures, etc) : TRANSLATION
- English text is appearing in french client in first human quest given by deputy iIllem in Northshire : 
The text come from a quite good translation. It is always better to have this for players experience instead of English/French mix.
I have tried to log into Wotlk live server on classic Wotlk but the Deputy Willem does not display this gossip greetings anymore (he only gives the quest and then never allow you to talk with him). Testd with a lvl 1 charater and a lvl 60 character
1. Test the first quest given by deputy willem on a French …
=> fix(DB/Translation/FR) : Deputy Willem greetings gossip text

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6750
not tested. but simple enough to not really have to test. …
=> fix(Scripts/TheEye): amend Al'ar divebomb timer in p2

data/sql/updates/pending_db_world/rev_1709065962197103700.sql
- Closes #18439
- Closes chromiecraft/chromiecraft#6588
1.
2.
3. …
=> fix(DB/Gameobject): Add some missing 'Anvil, Forge, Alchemy Lab' spawns

data/sql/updates/pending_db_world/rev_1709299008995982200.sql
This is a follow-up to PR #17936 attempting to fix the issues that were still stopping the PR from getting merged.
The original author couldn't continue the work on the PR, so here we are.
This PR is now only changing data based on sniffs.
- Closes 
.go cre 26661
.q add 6002
see that the text field while the mission is in progress is no longer blank. Quest progression text on NPC was missing
open map
The IDs of the mission areas and points of interest have also been corrected and are now showing correctly.
.go ga 13477
use quest item near stone
Lunaclaw …
=> Fix(DB/SAI) update quest 6002 poi and text

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6795
N.A. …
=> fix(Scripts/TheEye): make sure Solarian does not cast arcane missiles on target with Wrath of the Astromancer active

data/sql/updates/pending_db_world/rev_1709718488788677100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6793
1.
2.
3. …
=> fix(DB/Creature): Kael Phoenix should not be immune to slows

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
This was a fun one!
- Closes https://github.com/chromiecraft/chromiecraft/issues/6735 …
=> fix(Scripts/TheEye): Al'ar phoenix spawn positions in p2

data/sql/updates/pending_db_world/deathwail.sql
-  [X] Database (SAI).
- Closes an unreported issue.
1. `.go c id 22061`
2. Kill the soulstealers.
3. Engage Deathwail.
4. Observe his scripting along the way.
There is a reported issue with this guy that he doesn't descend. I could not reproduce this issue myself, but I could see that his guard spawns sometimes only spawned the last pack in the series he's supposed to spawn. This PR does not resolve that issue, but instead makes him killable before descending (as he should be) so that the quest he is the objective of can be completed. …
=> fix(DB/SAI): Remove Shadowlord Deathwail's immunity.

src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp
- Progresses [17294](https://github.com/azerothcore/azerothcore-wotlk/issues/17294)
Retail (DF 10.1.0 49890)
1. .tele karazhan
2. do chess event with cross faction players
3. check that only faction that started the event can be controlled
- Raid leader faction should always be event faction …
=> fix(Scripts/Karazhan): Chess Event Cross Faction

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6719 …
=> fix(Scripts/TheEye): ensure Ember of Al'ar always spawn in the right spot

src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp
=> fix(Scripts/Karazhan): Correct chess piece gossip faction check.

data/sql/updates/pending_db_world/rev_1707943090372200600.sql
- discovered while researching chromiecraft/chromiecraft#6669
item duration should be realtime, see e.g.:
https://www.wowhead.com/wotlk/item=44844/turkey-caller
Otherwise the item might still exist on inactive characters months after Pilgrim's Bounty ended as the duration only "ticks" when the player is online.
1.
2.
3. …
=> fix(DB/Item): 44844 'Turkey Caller' - add flag CU_DURATION_REAL_TIME

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp, src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp, src/server/scripts/Outland/TempestKeep/Eye/instance_the_eye.cpp, src/server/scripts/Outland/TempestKeep/Eye/the_eye.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18487
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18497
- Closes https://github.com/chromiecraft/chromiecraft/issues/6600
- Closes https://github.com/chromiecraft/chromiecraft/issues/6522
- Closes https://github.com/chromiecraft/chromiecraft/issues/6758 …
=> fix(Scripts/TheEye): boss boundaries and Kael door

src/server/game/OutdoorPvP/OutdoorPvP.cpp
- the function HandleCustomSpell() should only return true if it actually handled a spell
- Closes #18034
- Closes chromiecraft/chromiecraft#6457.
1.
2.
3. …
=> fix(Core/PVP): Fix OutDoorPVP CustomSpell handling

.github/workflows/tools_build.yml
=> fix(CI): fix tools_build

.github/README.md
- Closes 
At least for me the link did not work as the file name didn't match.
1.
2.
3. …
=> fix(Docs): readme: fix broken link to CODE_OF_CONDUCT.md

.github/README.md
using same links as azerothcore.org now
- Closes 
1.
2.
3. …
=> fix(Docs): readme: fix broken license links

apps/installer/includes/os_configs/osx.sh
=> fix(CI/MacOS): Fix MacOS dependency installation

data/sql/updates/pending_db_world/rev_1710146818912293800.sql, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6780
1.
2.
3. …
=> fix(Scripts/TempestKeep): Kael pyroblast target only main target

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18526
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18525
- Closes https://github.com/chromiecraft/chromiecraft/issues/6830
- Closes https://github.com/chromiecraft/chromiecraft/issues/6825
1.
2.
3.
**REMEMBER**: when testing a …
=> fix(Scripts/TheEye): make sure Al'ar doesn't cast anything during rebirt + phoenix spawning

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18534
- Closes https://github.com/chromiecraft/chromiecraft/issues/6835 …
=> fix(Scripts/TheEye): allow Solarian to cast on pets/totems

data/sql/updates/pending_db_world/tempest_falconer.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18524
- Closes https://github.com/chromiecraft/chromiecraft/issues/6824 …
=> fix(DB/TheEye): make falconer move towards you

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
=> fix(Scripts/TheEye): remove auras from Solarian on invisiblity and sniffed spell

data/sql/updates/pending_db_world/rev_1710238997622002200.sql
=> fix(DB/Gameobject): fix phaseMask of two 'Bench' spawns

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
still can't replicate ffs
- Closes 
but not confirmed, as cannot replicate bug …
=> fix(Scripts/TheEye): maybe fix Al'ar transition

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes 
tested, but can't replicate a raid scenario. the prior issue was likely due to multiple sources dealing fatal damage at the same time, making the multiple instances of timed events start and thus scheduling multiple times
1.
2.
3. …
=> fix(Scripts/TheEye): make sure Al'ar doesn't schedule abilities multiple times

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
these shouldn't be made without coffee
- Closes 
1.
2.
3. …
=> fix(Scripts/TheEye): another Al'ar hotfix

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6697#event-12109728276
1.
2.
3. …
=> fix(Core/Spells): Domination affect max 5 targets

src/server/game/Globals/ObjectMgr.cpp
- Closes 
1. We have to ignore the ids of the items in the dbc that are not blizzlike, because if not, the tests in the modules fail, since the validation is executed, it does not find the item in the original dbc, and generates the error, causing do not continue the test.
```
Run source ./apps/ci/ci-error-check.sh
Checking Startup Errors
The Errors.log file contains startup errors:
Item (Entry: [7](https://github.com/azerothcore/mod-item-level-up/actions/runs/8221525862/job/22481986264#step:11:8)0[10](https://github.com/azerothcore/mod-item-level-up/actions/runs/8221525862/job/22481986264#step:11:11)01) does not exist in item.dbc! (not correct id?).
Please solve …
```
=> chore. Avoid failures in the tests of custom items

src/server/scripts/Commands/cs_misc.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18557
1.
2.
3. …
=> fix(Scripts/Commands): Fix crash when using additem from console

data/sql/updates/pending_db_world/fix_dagger_proc.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6665
- Closes https://github.com/chromiecraft/chromiecraft/issues/6857 …
=> fix(Scripts/TheEye): increase dagger proc chance and make sure mind control only targets players

data/sql/updates/pending_db_world/weapons_flags.sql, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6877
- Closes https://github.com/chromiecraft/chromiecraft/issues/6862
- Closes https://github.com/chromiecraft/chromiecraft/issues/6872
- Closes https://github.com/chromiecraft/chromiecraft/issues/6792
testing as we speak
**REMEMBER**: when testing …
=> fix(Scripts/TheEye): fix Kael progress bug and some other issues

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
=> fix(Scripts/TheEye): fix MC overlap

src/server/apps/worldserver/worldserver.conf.dist
- Error while configuring Appender GM in Logger commands.gm. Appender does not exist
- Closes 
1. Having commented on this line, I don't know if the logs are generated or not, because it depends on the options below, but in the worldserver at the top, a message appears with an error. Let it continue, but this message should not appear. …
=> chore. Correctly disable gm command dbg messages by default

flake.lock, flake.nix
This adds a nix flake to the project. This makes it easier for users of the nix package manager to build the project.
I compiled successfully on x86_64-linux with:
```
mkdir build && cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j $NIX_BUILD_CORES
```
1. Have the nix package manager installed with flakes enabled.
2. Run `nix develop` in the project root containing flake.nix and wait for the devshell to appear.
3. From within the devshell, proceed with a CMake build (such as the example under "Tests Performed") …
=> feat(build): initial development nix flake

src/server/game/Spells/SpellInfo.cpp
When on you use spell https://www.wowhead.com/spell=35329/vibrant-blood you cannot use stealth or invisibility.
This pr FIX that
- Closes 
1.
2.
3. …
=> Fix spell 35329 (Vibrant Blood)

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6637
1.
2.
3. …
=> fix(Scripts/TheEye): Fix Ember of Alar ember blast percent damage

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6840
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18549
1.
2.
3. …
=> fix(Scripts/TheEye): Make Solarian visible on phase transition

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
during p3 schedules are firing twice due to them not being cancelled after dying, but not respawning. they only get cancelled on reset, which is not called in between
- Closes 
1.
2.
3. …
=> fix(Scripts/TheEye): make sure schedules are cancelled when advisors die in p1

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6887
1.
2.
3. …
=> fix(Scripts/TheEye): Alar dont take 2% damage during dive bomb

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18596
1.
2.
3. …
=> fix(Scripts/HyjalSummit): Don't reset trash counter on scheduled waves

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18597
1.
2.
3. …
=> fix(Scripts/HyjalSummit): Frost Wyrms casting wrong spell

data/sql/updates/pending_db_world/rev_1704609963729945200.sql
Like Warlock's other pets, when first summoned and swapped, spells should be cast on themselves at 7741 and are friendly faction 35 
- Closes 
1. Create a tribal role
2. .quest add 1803
3. .quest complete 1803
4. .quest add 1805
5. .quest complete 1805
6. .go c 14366
7. Complete the quest -- Accept the quest
8. Summon using quest items
9. Summoned The faction that the Demon Hound has just summoned should be friendly …
=> fix(db/sai) Modified summoned felhunter smart AI

data/sql/updates/pending_db_world/Mechanostrider_Race.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6390
[Wowpedia patch 3.0.8 page](https://wowpedia.fandom.com/wiki/Patch_3.0.8), [Wowpedia version history for the mount adding new races March 16th, 2009](https://wowpedia.fandom.com/wiki/Fluorescent_Green_Mechanostrider?oldid=1808234)
1. .additem (playername) 13325
2. inspect item for alliance races …
=> fix(DB/Item): Change races for Fluorescent Green Mechanostrider

data/sql/updates/pending_db_world/blackrock-mobs-npc-flag-updates.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8466
1. .tele brd
2. .go c id 9499
3. Engage in combat with Plugger Spazzring, Dark Iron Brewer, Guzzling Patron, Grim Patron, and/or Hammered Patron, and confirm that you cannot engage in gossip text with them while fighting.
You …
=> fix(DB\Creatures): updating npcflags on Blackrock Bar mobs

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
with the minimum 18.0f range and maximum 20.0f range there was a small dead zone for arcane orbs. also LOS seems to sometimes be an issue
- Closes https://github.com/chromiecraft/chromiecraft/issues/6889 …
=> fix(Scripts/TheEye): make Void Reaver abilities ignore LOS

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_fathomlord_karathress.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6829 …
=> fix(Scripts/SSC): make adds reset when one leaves the room

src/server/game/Accounts/AccountMgr.cpp, src/server/game/Scripting/ScriptDefines/AccountScript.cpp, src/server/game/Scripting/ScriptDefines/AccountScript.h, src/server/game/Scripting/ScriptMgr.h
- I feel like this hook is necessary for custom modules, a lot of them use their own tables to store character/account associated data (e.g. mod-transmog). When accounts are deleted, data from these custom tables will become reduntant. This hook will provide an easy way to catch account deletion and do the necessary cleanup. 
1.
2.
3. …
=> feat(core): account delete hook

src/server/game/Handlers/TradeHandler.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.h, src/server/game/Scripting/ScriptMgr.h
- Create a new hook in PlayerScript : CanSetTradeItem
It allows you to filter the item you want to be allowed to be traded.
It goes further than the CanInitTrade existing hook.
_N/A_
You can use this module to test the hook : https://github.com/Elmsroth/mod-trade-items-filter
1. You can use this PlayerScript to check the hook behaviour : https://gist.github.com/Elmsroth/d8bc358791ab6cf7db501b5cad9126ad  (test script not added to PR since it is not required, it would pollute the repo).
_N/A_ …
=> chore(PlayerScript/Hook) : Add CanSetTradeItem Hook in PlayerScript

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h
- Closes 
1. complete the rest of Hyjal
2. engage Archimonde
3. …
=> fix(Scripts/Hyjal): Archimonde refactored

src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp, src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Updates/UpdateData.cpp, src/server/game/Entities/Object/Updates/UpdateData.h, src/server/game/Entities/Player/PlayerUpdates.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Grids/Notifiers/GridNotifiers.cpp, src/server/game/Groups/Group.cpp, src/server/game/Maps/Map.cpp, src/server/game/Server/WorldSocket.cpp, src/server/game/Server/WorldSocket.h, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp, src/server/scripts/Spells/spell_priest.cpp
At the moment, packet compression occurs in the maps thread, which could slow down map updates and increase the diff. With the proposed changes, compression will occur in the network thread, which will offload some work from the maps thread.
- Closes 
1.
2.
3. …
=> feat(Core/Compression): Move packets compression from map to network thread

.github/actions/linux-build/action.yml
- CI
- nopch builds building with pch
1. Run CI
- link https://github.com/azerothcore/azerothcore-wotlk/actions/runs/8466876183/job/23196590259#step:3:1522
- Linked behavior is different than this PR since PCH isn't supposed to be happening in the first place on nopch builds …
=> Fix(CI): Don't use PCH on nopch builds

.github/workflows/core_modules_build.yml
-  [x] CI
- Fixes regression in #17281 relating to the modules build.
- with that commit, modules weren't cloned
- this resolves that
I just look at the thing
1. run CI …
=> fix(ci): ensure module build clones modules

data/sql/updates/pending_db_world/rev_1711804492859268400.sql
- sniff sql parses were showing both initial states and apparently the wrong one was chosen when updating all Brazier spawns with sniffed values
- Follow-Up to #18609
- Closes chromiecraft/chromiecraft#6924
1.
2.
3. …
=> fix(DB/Gameobject): update initial state of some Brazier spawns

.github/workflows/core-build-pch.yml
right now all pch/nopch jobs are named "-nopch" which might be confusing
- Closes 
1.
2.
3. …
=> fix(CI): correct name suffix of PCH jobs

data/sql/updates/pending_db_world/thaladred-movement.sql, src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6657 …
=> fix(DB/TheEye): make Thaladred walk

data/sql/updates/pending_db_world/alar-loot.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6866 …
=> fix(DB/TheEye): remove faulty talon of al'ar reference from reference loot template

data/sql/updates/pending_db_world/skeletonmages.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h
- Closes https://github.com/chromiecraft/chromiecraft/issues/6928
- Closes https://github.com/chromiecraft/chromiecraft/issues/6929
- Closes https://github.com/chromiecraft/chromiecraft/issues/6930 …
=> fix(Scripts/Hyjal): Shadowy Necromancers now use Unholy Frenzy + Skeleton mage abilities

src/server/game/DataStores/DBCStores.cpp, src/server/game/DataStores/DBCStores.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Spells/SpellMgr.cpp, src/server/scripts/Commands/cs_learn.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18564
1.
2.
3. …
=> feat(Core/Optimization): Create index for sSkillLineAbilityStore to speedup search by skillLine.

src/server/scripts/Outland/TempestKeep/Eye/boss_void_reaver.cpp
calling for not spellcastresult existing does not work, as instead we need to check for not SPELL_CAST_OK (255 mask)
- Closes https://github.com/chromiecraft/chromiecraft/issues/6949 …
=> fix(Scripts/TheEye): fix targetting logic in Void Reaver

data/sql/updates/pending_db_world/alar-loooot.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6866 …
=> fix(DB/TheEye): remove unused reference and add Talon of the Phoenix back

data/sql/updates/pending_db_world/rev_1712070277049871600.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18547
- Closes https://github.com/chromiecraft/chromiecraft/issues/6844
1.
2.
3. …
=> fix(DB/Creature): Void Reaver Movement Speed and Model Info

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18550
- Closes https://github.com/chromiecraft/chromiecraft/issues/6839
1.
2.
3. …
=> fix(Scripts/TheEye): Lord Sanguinar's Bellowing Roar timer

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18649
1.
2.
3. …
=> fix(Scripts/TheEye): Fix crash in Kaelthas.

data/sql/updates/pending_db_world/rev_1711048056647652400.sql, src/server/scripts/Outland/BlackTemple/black_temple.h, src/server/scripts/Outland/BlackTemple/boss_illidan.cpp, src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp, src/server/scripts/Outland/BlackTemple/illidari_council.cpp, src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9095
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18591
1. Fight Shade of Akama
2. Go to Illidari Council and defeat them, see if Akama's event plays
3. Deafeat Illidari Council but, instead of starting the event, crash the server and return, see if the door to Illidan is open …
=> fix(Scripts/BlackTemple): Rewrite Shade of Akama

data/sql/updates/pending_db_world/rev_1712085690434398700.sql
- this is due to a 'collision' of the Black Temple rework PR and my general 'Door' update PR which was merged later
- due to 'collision' of
#18566 
and
#18569
1.
2.
3. …
=> fix(DB/Gameobject): remove duplicate 'Door' spawns in Black Temple

data/sql/updates/pending_db_world/rev_1712171769662178600.sql, src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
Sorry @icaca and others, it was my mistake
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18664
1.
2.
3. …
=> fix(Scripts/BlackTemple): Illidan not accessing Akama's guid

src/server/game/Battlegrounds/Zones/BattlegroundEY.cpp
- before the max points could exceed 1600 on winning which e.g. resulted in the achievement 'The Perfect Storm' not beeing triggered correctly
- Closes #11998
- Closes chromiecraft/chromiecraft#6962
1.
2.
3. …
=> fix(Core/Battleground): correctly limit Eye of the Storm max points to 1600

src/server/game/Entities/Corpse/Corpse.cpp, src/server/game/Entities/Corpse/Corpse.h, src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/GameObject/GameObject.h, src/server/game/Entities/Item/Container/Bag.cpp, src/server/game/Entities/Item/Container/Bag.h, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Scripting/ScriptDefines/UnitScript.cpp, src/server/game/Scripting/ScriptDefines/UnitScript.h, src/server/game/Scripting/ScriptMgr.h
The current approach to generate object updates is not optimized. Let's review the following scenario: suppose 400 players are gathered in the same location. With the current approach, for each player, we would need to generate 400 object updates (N^2), resulting in a total of 160 000 object update packets.
However, with the suggested approach, we would prebuild one object update per player (400 in total) and then make small patches to these prebuilt objects. I believe this change should significantly improve performance for overpopulated servers.
- Closes 
This PR has …
=> feat(Core/Optimization): Optimize build of units update object by leveraging cache

src/server/game/Entities/Player/Player.cpp
=> fix(Core/Player): Fix memory leak.

.github/actions/linux-build/action.yml
-  [x] CI
- Fixes PCH builds
- before #17281, pch builds weren't cached. That PR erroneously added caching to the pch builds, which is breaking those builds. 
1. run ci …
=> fix(CI): Don't cache pch builds

src/server/scripts/Commands/cs_go.cpp
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/18662
**More tests done without crashs**
> .go xyz 0 90000
> .go xyz -90000 0 
> .go xyz -99999 99999
> .go xyz 10 10 10 -1 (invalid mapid)
> etc.
1.
2.
3. …
=> Fix "go xyz" command crash

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp
Vem should enrage when it is the last bug alive
- Closes #18618 
1.
2.
3. …
=> fix(Scripts/TempleOfAhnQiraj): Fix Vem enrage

src/server/scripts/Outland/TempestKeep/Eye/instance_the_eye.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6948 …
=> fix(Scripts/TheEye): increase Void Reaver boundary so he does not reset when tanked against the wall

data/sql/updates/pending_db_world/archi_loot_fix.sql
old data:
```sql
DELETE FROM `creature_loot_template` WHERE `Entry` = 17968;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES 
(17968, 22903, 0, 0.2, 0, 1, 0, 1, 1, 'Archimonde - Recipe: Insane Strength Potion'),
(17968, 23884, 0, 0.2, 0, 1, 0, 1, 1, 'Archimonde - Schematic: Mana Potion Injector'),
(17968, 29434, 0, 100, 0, 1, 0, 2, 2, 'Archimonde - Badge of Justice'),
(17968, 32285, 0, 1.875, 0, 1, 1, 1, 1, 'Archimonde - Design: Flashing Crimson Spinel'),
(17968, 32289, 0, 1.875, 0, 1, 1, 1, 1, 'Archimonde - Design: Stormy Empyrean Sapphire'),
(17968, 32295, 0, 1.875, 0, 1, 1, 1, 1, 'Archimonde - Design: Mystic Lionseye'),
(17968, 32296, 0, 1.875, 0, 1, 1, 1, 1, 'Archimonde - …
```
=> fix(DB/Hyjal): weird loot format for Archimonde

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6974 …
=> fix(Scripts/Hyjal): make sure Jaina takes no damage from Death and Decay

src/server/scripts/Northrend/AzjolNerub/ahnkahet/ahnkahet.h, src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_elder_nadox.cpp, src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_jedoga_shadowseeker.cpp, src/server/scripts/Northrend/AzjolNerub/ahnkahet/instance_ahnkahet.cpp
=> [Instance:Ahnkahet] Fixed problem gathering GUIDS from bosses.

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
=> fix(Scripts/TheEye): make Al'ar not get stuck during dive bomb when no enemies in melee range

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
reasons etc: https://github.com/azerothcore/azerothcore-wotlk/commit/9b6e07ec2d49776f9f6c55c3535a1de3b1a13d19#commitcomment-140510094
- Closes 
1.
2.
3. …
=> fix(Scripts/TheEye): Kaelthas: Roar timer

src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18694
1.
2.
3. …
=> fix(Scripts/Karazhan): Fix crash in chess event.

src/server/game/Scripting/ScriptDefines/AccountScript.cpp, src/server/game/Scripting/ScriptDefines/AccountScript.h
=> feat(Core/Scripts): Optimize AccountScript need#18672

src/server/game/Scripting/ScriptDefines/MovementHandlerScript.cpp, src/server/game/Scripting/ScriptDefines/MovementHandlerScript.h
=> feat(Core/Scripts): Optimize MovementHandlerScript need#18672 

src/server/game/Scripting/ScriptDefines/ArenaScript.cpp, src/server/game/Scripting/ScriptDefines/ArenaScript.h
=> feat(Core/Scripts): Optimize ArenaScript need#18672

src/server/game/Scripting/ScriptDefines/ArenaTeamScript.cpp, src/server/game/Scripting/ScriptDefines/ArenaTeamScript.h
=> feat(Core/Scripts): Optimize ArenaTeamScript need#18672

src/server/game/Scripting/ScriptDefines/AccountScript.h, src/server/game/Scripting/ScriptDefines/ArenaScript.h, src/server/game/Scripting/ScriptDefines/ArenaTeamScript.h, src/server/game/Scripting/ScriptDefines/AuctionHouseScript.h, src/server/game/Scripting/ScriptDefines/MovementHandlerScript.h, src/server/game/Scripting/ScriptMgr.cpp, src/server/game/Scripting/ScriptMgr.h
=> fix(Core/Scripts): Fix build and crash when calling uninitialized scripts

src/server/game/Scripting/ScriptDefines/AccountScript.cpp, src/server/game/Scripting/ScriptDefines/ArenaScript.cpp, src/server/game/Scripting/ScriptDefines/ArenaTeamScript.cpp, src/server/game/Scripting/ScriptDefines/AuctionHouseScript.cpp, src/server/game/Scripting/ScriptDefines/MovementHandlerScript.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.h
=> refactor(Core/Scripts): Optimize Script

src/server/game/Scripting/ScriptDefines/DatabaseScript.cpp, src/server/game/Scripting/ScriptDefines/DatabaseScript.h
=> feat(Core/Scripts): Optimize DatabaseScript

src/server/game/Scripting/ScriptDefines/FormulaScript.cpp, src/server/game/Scripting/ScriptDefines/FormulaScript.h
=> feat(Core/Scripts): Optimize FormulaScript

src/server/game/DungeonFinding/LFGScripts.cpp, src/server/game/Scripting/ScriptDefines/GroupScript.cpp, src/server/game/Scripting/ScriptDefines/GroupScript.h
=> feat(Core/Scripts): Optimize GroupScript

src/server/game/Scripting/ScriptDefines/GameEventScript.cpp, src/server/game/Scripting/ScriptDefines/GameEventScript.h
=> feat(Core/Scripts): Optimize GameEventScript

src/server/game/Scripting/ScriptDefines/AllSpellScript.cpp, src/server/game/Scripting/ScriptDefines/AllSpellScript.h
=> feat(Core/Scripts): Optimize AllSpellScript

src/server/game/Scripting/ScriptDefines/AllCommandScript.cpp, src/server/game/Scripting/ScriptDefines/AllCommandScript.h
=> feat(Core/Scripts): Optimize AllCommandScript

src/server/game/Scripting/ScriptDefines/AchievementScript.cpp, src/server/game/Scripting/ScriptDefines/AchievementScript.h
=> feat(Core/Scripts): Optimize AchievementScript

src/server/game/Scripting/ScriptDefines/AllBattlegroundScript.cpp, src/server/game/Scripting/ScriptDefines/AllSpellScript.cpp, src/server/game/Scripting/ScriptDefines/GlobalScript.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptDefines/UnitScript.cpp, src/server/game/Scripting/ScriptMgrMacros.h
=> fix(Core/PlayerScript): Fix adding XP on quest completion and other overlooks.

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6971 …
=> fix(Scripts/Hyjal): Archimonde finger of death condition

src/server/game/Scripting/ScriptMgrMacros.h
=> fix(Core/Scripts): Fix one more typo after scripts refactoring

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6977
1.
2.
3. …
=> fix(Core/Spells): Fix Anetheron sleep only targetting himself

data/sql/updates/pending_db_world/rev_1713017015376822300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6978 
1.
2.
3. …
=> fix(DB/Creature): Towering Infernals should be immune to taunt

docker-compose.yml
-  [x] Docker setup.
- Issue #17656
- Error response from daemon: unable to find user $USER: no matching entries in passwd file -> this error occurs if you create additinal .env file with `DOCKER_USER`, `DOCKER_USER_ID` and `DOCKER_GROUP_ID` variables different from acore:1000:1000
1. groupadd -g 1100 testmeplz
2. useradd testmeplz -u 1100 -g 1100 -m -s /bin/bash
3. follow instructions from [link](https://www.azerothcore.org/wiki/install-with-docker) with newly created user (testmeplz)
4. (OPTIONAL) create .env file with contents:
``` …
```
=> fix(Docker): Fix docker compose build failed when using USER with UID:GID != 1000

src/server/game/Handlers/CharacterHandler.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18741
When trying to delete a character, which has a pending mail, the deletion is cancelled.
1. Create 2 characters
2. Send a collect item to another character
3. Attempt to delete the character that should have the item.
4. The character cannot be deleted, because he has a pending mail.
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/8a8a01c8-5243-466e-9818-7c65d3113d77 …
=> fix. Prevent character deletion if you have an email

src/server/game/Spells/SpellMgr.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6644
1.
2.
3. …
=> fix(Core/Spells): Dive Bomb should not share damage

src/server/game/AI/CoreAI/UnitAI.cpp, src/server/game/AI/CoreAI/UnitAI.h, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6986
1.
2.
3. …
=> fix(Scripts/Hyjal): Azgalor Doom should not be cast on the MT

data/sql/updates/pending_db_world/rev_1713022406349814900.sql
=> fix(DB/Creature): Al'lar should despawn on evade

data/sql/updates/pending_db_world/rev_1713097857608850100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6931
1.
2.
3. …
=> fix(DB/Spells): Add Pet Spells to Shadowy Necromancer

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6983
1.
2.
3. …
=> fix(Scripts/Hyjal): fix Mark of Kaz'rogal timer

data/sql/updates/pending_db_world/rev_1713534008677560300.sql
=> chore(DB/Creature): worldserver error

data/sql/updates/pending_db_world/rev_1713549415418061715.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18747
Issue claims a heal of 7% of max hp.
1. .tele hyjalsummit
2. start encounter by talking to jaina
3. wave 1 has ghouls. Health <= 7% triggers cannibalize
4. observe it heals 7% of max hp …
=> fix(Scripts/Hyjal): Cannibalize should heal more than 1

data/sql/updates/pending_db_world/rev_1713615045654319800.sql
- Closes 
.tele valleyofwisdom
.event start 1
observe nearby Midsummer celebrants to talking emote regularly …
=> fix(DB/SAI): make 'Midsummer Celebrants' talk regularly

data/sql/updates/pending_db_world/rev_1713699453958519800.sql
- Progress #6963
- this is the dusty tome referenced in #9957
https://www.wowhead.com/wotlk/object=179548
came across this in a sniff - there was no spawn yet in AC, so let's add it
.go ga 20
loot the book
enjoy …
=> fix(DB/Gameobject): Sniffed Values for 179548 'A Dusty Tome' spawns

data/sql/updates/pending_db_world/rev_1713610036097360400.sql
- these are now spawned in #18764 where I observed to not get any damage while sitting on top of these fires.
1.
2.
3. …
=> fix(DB/Gameobject): add missing script to some fire places

src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6876
-  https://github.com/chromiecraft/chromiecraft/issues/6870
- https://github.com/chromiecraft/chromiecraft/issues/6958
see sources in issues
1.
2.
3. …
=> fix(Scripts/TheEye): Update Astromancer timings and add phase

src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp
To match e.g. https://youtu.be/YlCfJB7RN6U?t=951 w.r.t. to initial timing and interval between subsequent timings
16 seconds delta from https://github.com/azerothcore/azerothcore-wotlk/blob/28a64111fd81b17d900f0af7c3be2d0daddb6895/src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp#L205
7 seconds delta from https://github.com/azerothcore/azerothcore-wotlk/blob/28a64111fd81b17d900f0af7c3be2d0daddb6895/src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp#L278 and https://github.com/azerothcore/azerothcore-wotlk/blob/28a64111fd81b17d900f0af7c3be2d0daddb6895/src/server/scripts/Outland/TempestKeep/Eye/boss_alar.cpp#L328
-  [ ] Database (SAI, …
=> fix(Scripts/TheEye): Update Alar Dive Bomb timings

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18237
1.
2.
3. …
=> fix(Core/Pet): Fix pets chasing when pet and target spins uncontrollable

data/sql/updates/pending_db_world/rev_1713785804437634300.sql
=> fix(DB/Gameobject): Sniffed Values for 'Doodad_DwarfSign_Alchemist01' spawns

src/server/game/Entities/GameObject/GameObject.cpp
- m_goData must be assigned before Create() is beeing called
- otherwise GetScriptId() can't load the correct scriptiD in Create()
- all in all this is now more in line with how it's beeing done in Creature.cpp
- Closes 
1.
2.
3. …
=> fix(Core/GameObject): load guid based scripts correctly

data/sql/updates/pending_db_world/rev_1713790630268201700.sql
=> fix(DB/Gameobject): Sniffed Values for 'AuctionNode' spawns

src/server/scripts/EasternKingdoms/Karazhan/boss_chess_event.cpp
=> refactor(Scripts/Karazhan): 'uint' It can never be less than 0

src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
=> fix(Scripts/PlayerScript): PlayerScript Error

data/sql/updates/pending_db_world/rev_1713803843196763300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18773
1. e.g. go to learning dual spec. …
=> fix(DB/Gossip_Menu_Option_Locale): fix german umlauts

data/sql/updates/pending_db_world/rev_1713104748708628400.sql, src/server/game/Battlegrounds/Zones/BattlegroundBE.cpp, src/server/game/Battlegrounds/Zones/BattlegroundDS.cpp, src/server/game/Battlegrounds/Zones/BattlegroundNA.cpp, src/server/game/Battlegrounds/Zones/BattlegroundRL.cpp
- Closes #17119
1. Log ingame with 2 accounts
2. .debug arena and then join skirmish
3. Use /timer to see when will Shadow Sight(s) spawn …
=> fix(Scripts/Arenas): Updating timer for Shadow Sight spawns

pull_request_template.md
The existing link has expired.
- Closes 
1.
2.
3. …
=> fix(Docs/PR-Template): update discord invite link

src/server/game/Loot/LootMgr.cpp
=> fix(Core/Loot): Correct typo when loading reference loot templates

src/server/game/World/World.cpp
- the default value had been changed in worldserver.conf.dist, but not in the core
- Closes https://github.com/chromiecraft/chromiecraft/issues/6605
- Follow-Up to #18245
1.
2.
3. …
=> fix(Conf): align LeaveGroupOnLogout default in core with worldserver.conf.dist

data/sql/updates/pending_db_world/rev_1714664171505149429.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18403
1.
2.
3. …
=> fix(DB/spell_target_position): Mara Portal tp location

src/server/game/Entities/Unit/Unit.cpp
SPELLMOD_RESIST_MISS_CHANCE is currently increasing miss chance. 
https://github.com/azerothcore/azerothcore-wotlk/blob/ab7405f94e8959d91ef1500a14b97218976bd8db/src/server/game/Entities/Unit/Unit.cpp#L19284
For example, in this issue t3 set bonus increases `hitChance` to `105.0f` then this line increases `missChance` by `5.0f` 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18848
1.
2.
3. …
=> fix(Core/Unit):  SPELLMOD_RESIST_MISS_CHANCE should decrease miss chance

data/sql/updates/pending_db_world/fix_issue18729.sql
-  [x] Database (creatures).
- Closes [18729](https://github.com/azerothcore/azerothcore-wotlk/issues/18729)
[Wrath retail](https://www.youtube.com/watch?v=7aVWto_rhGQ&t=47s)
[Issue comment](https://github.com/azerothcore/azerothcore-wotlk/issues/18729#issuecomment-2053769509) says that shredder can do melee attack on Classic, but I can't found any video for that behavior, so that question is still unclear …
=> fix(DB/Creature):  Correct spells order for Broken-down Shredder (issue 18729)

data/sql/updates/db_world/2024_05_11_00.sql
=> fix(DB/updates): fix downquery to match up

src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
similar structure to Thekal https://github.com/azerothcore/azerothcore-wotlk/blob/dd3f4a5f8e018bfd9d1aa5451bd884508a0e2d15/src/server/scripts/EasternKingdoms/ZulGurub/boss_thekal.cpp#L175
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18120
1. `.go ga id 194092` tp to blackened urn
2. damage Nightbane <75% to trigger flight phase
3. try kill boss during takeoff/landing + flight phase …
=> fix(Karazhan/Nightbane): no longer killable during flight

data/sql/updates/pending_db_world/archimondo.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7038
1.
2.
3. …
=> fix(DB/Hyjal): Archimonde aggro range

data/sql/updates/pending_db_world/rev_1715344535575710504.sql, src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
When Nightbane is airborne, Rain of Bones targets the highest threat target. This should be a random player or pet
Skeletons are spawned on the player with highest threat. Rain of Bones no longer follows targets as of 2.1. They should spawn around a static position
Rain of Bone casts shows as a buff. Picture shows `.cast back 37098` ![smoking_aura_smoking_effect](https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/953b4c9f-84c8-47b3-96c3-78d9d159a3f3)
- Closes 
mentions target randomness  https://wowpedia.fandom.com/wiki/Nightbane_(tactics)
```
Casts Rain of …
```
=> fix(Karazhan/Nightbane): Rain of Bones cast on one random player/pet, summon Skeletons at that location

data/sql/updates/pending_db_world/rev_1715349752817459800.sql
Removed East Plaguelands - Church of the Holy Light with flowers and small mounds. Because they are generated during the creature "Rimblat Earthshatter" dialogue event
- Closes 
1. .go c 54186
2. wait
3. …
=> fix(DB/gameobject):Remove the Church of the Holy Light with flowers and small mounds

src/server/scripts/Outland/zone_shadowmoon_valley.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6940 …
=> fix(Scripts/ShadowmoonValley): minor fixes to Enslaved Netherwing Drakes

.github/workflows/core-build-nopch.yml, .github/workflows/core-build-pch.yml
ubuntu-22.04 has no gcc-13 anymore
https://github.com/actions/runner-images/commit/cfcc1c6a1b0eff62779c36d5449a8874b3114122
https://github.com/actions/runner-images/blob/532cfd5c07ad1213e5d1b607430c2d69a5fc2683/images/ubuntu/Ubuntu2204-Readme.md
- Closes 
1.
2.
3. …
=> fix(CI): revert ubuntu-22.04 to gcc12

.github/workflows/core-build-nopch.yml, .github/workflows/core-build-pch.yml
there's a new CI - let's use it
https://github.com/actions/runner-images/blob/532cfd5c07ad1213e5d1b607430c2d69a5fc2683/images/ubuntu/Ubuntu2204-Readme.md
- Closes 
1.
2.
3. …
=> feat(CI): add CI for ubuntu-24.04

data/sql/updates/pending_db_world/wg_fix.sql
=> localize Arcanist Braedin txt line about WG

docker-compose.yml
-  [x] Docker
- removes `version` from `docker-compose.yml`
- docker prints deprecation warning when running compose commands
```console
mike@talos $ docker compose up -d --build
WARN[0000] /home/mike/builds/azerothcore-wotlk/docker-compose.yml: `version` is obsolete
```
https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-optional
1. No changes to procedures. Simply check out and `docker compose up -d --build` as normal
You can help …
=> chore(Docker): update docker compose file schema

.github/actions/linux-build/action.yml, .github/workflows/macos_build.yml, .github/workflows/tools_build.yml, .github/workflows/windows_build.yml
our workflows are currently filled with the warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Therefore we should upgrade to actions/cache@v4 with Node.js 20 now: https://github.com/marketplace/actions/cache?version=v4.0.2
And also hendrikmuhs/ccache-action: https://github.com/hendrikmuhs/ccache-action/releases/tag/v1.2.13
- Closes 
1.
2.
3. …
=> fix(CI): bump dependencies for usage of Node.js 20

src/server/scripts/Commands/cs_lookup.cpp
1. Switch your client to any language other than enGB/enUS, deDE, and zhCN.
2. Use the .lookup item command to search for items in the selected language.
3. Notice that nothing works, but this PR fixes the issue. …
=> fix(Scripts/Commands): Fix .lookup item command for most locales after 49e3d5d

data/sql/updates/pending_db_world/rev_1716154650178411700.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp
=> fix(Scripts/Hyjal): Limit Anetheron sleep to 3 targets

data/sql/updates/pending_db_world/doomfire_movement.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
Also changed some things to doomfire targetting. However this will still go wrong as the doomfire dummies are scripted as hostile npcs that just apply the debug on attack swing. Even if we remove the follow logic, they still chase players like normal hostile mobs would. So this needs some more work.
Update: they now chase a random target every 5s. Seems like a good intermediate solution to me until we figure out 100% for sure it's just random movement
- Closes https://github.com/chromiecraft/chromiecraft/issues/7030 …
=> fix(Scripts/Hyjal): Air Burst should not be cast on MT

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp
mark counter does not get reset on wipes
- Closes 
1.
2.
3. …
=> fix(Scripts/Hyjal): initialize/reset local private variables in Reset function

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
=> chore(Scripts/Hyjal): Don't initialize headers twice

data/sql/updates/pending_db_world/oopsmybad.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7065
1.
2.
3. …
=> fix(DB/Loot): Fix mistake in generic overworld profession drops

src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15400
```
Kill XT to open door
.go c id 33293
Go Kologarn door
.go ga id 194553
```
1. Kill Kologarn
2. Observe he comes a bridge
3. …
=> fix(Scripts/Ulduar) Kologarn becomes a bridge

data/sql/updates/pending_db_world/rev_1716571588345702920.sql, src/server/game/Maps/AreaBoundary.cpp, src/server/game/Maps/AreaBoundary.h, src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
1. Add spawn and AI "Kologarn Pit Kill Bunny"
2. Define generic intersect boundary to define a kill box
Z coordinate defined by lowest point:
- Closes 
one example
https://www.youtube.com/watch?v=S2VuUmr5ALw
warrior meme falling compilation
https://streamable.com/g0uy1w
```
Kill XT to open door
.go c id 33293
```
```
Go Kologarn
.go ga id 194553
```
fall down the pit
walk around area without GM mode to see if boundary is OK …
=> fix(Scripts/Ulduar) falling down Kologarn's pit should kill

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_kazrogal.cpp
=> chore(Scripts/Hyjal): Update Mark of Kazrogal script

data/sql/updates/pending_db_world/rev_1716648895478656500.sql
#18734 and #18850 Using GUIDs as smartscriptIDs will cause the mob combat AI to be lost and require DONT_OVERRIDE_SAI_ENTRY enabled flag, make the GUID and ENTRY scripts work at the same time
- Closes 
1.
2.
3. …
=> Fix creatures combat AI missing

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7061
1.
2.
3. …
=> fix(Scripts/Hyjal): Anetheron should not cast sleep on MT

data/sql/updates/pending_db_world/rev_1716833230281927300.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7075
1.
2.
3. …
=> fix(Scripts/Hyjal): Azgalor mark of doom spawn demons on target death

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6986
1.
2.
3. …
=> fix(Scripts/Hyjal): Azgalor doom shouldnt target tank MKII

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
=> fix(Scripts/Hyjal): Fix Doom spawning Doomguards twice on expire

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp
=> fix(Scripts/Hyjal): Anetheron dont cast sleep on tank

data/sql/updates/pending_db_world/doomfire_scripting.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
Essentially I upped the spirit speed so that the doomfire spawner (the one that drops the fires) never really catches up to the spirit, which would lead to a lot of stacked fires.
Additionally:
- Doomfire now spawns around Archimonde, instead of near a player (prevents it happening in the air)
- Doomfire now again spawns even when playing solo
- Closes https://github.com/chromiecraft/chromiecraft/issues/7032
1.
2.
3. …
=> fix(Scripts/Hyjal): tweak movement of Doomfire

AUTHORS, conf/dist/config.cmake, deps/recastnavigation/Detour/CMakeLists.txt, deps/recastnavigation/Recast/CMakeLists.txt, doc/changelog/master.md, src/common/Utilities/CircularBuffer.h, src/common/Utilities/DataMap.h
=> fix(LICENSE): update license file

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
=> fix(Scripts/Hyjal): remove summoned mobs on boss evade and reset waves

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
=> fix(Scripts/Hyjal): increase ranges on doomfire to make movement less inclined to stick close to the boss

.github/actions/linux-build/action.yml
caused by https://github.com/actions/runner-images/issues/9937
also CI should never attempt a restart as this will always disconnect the CI worker as it seems
- Closes 
1.
2.
3. …
=> fix(CI): fix ubuntu-24.04 build

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
=> fix(Scripts/Hyjal): fix some build warnings for unused parameters

.github/workflows/pr_labeler.yml
this workflow currently has the warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/labeler@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
- Closes 
1.
2.
3. …
=> fix(CI): bump pr-labeler dependencies for usage of Node.js 20

data/sql/updates/pending_db_world/netherwing-misc.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7083
- Closes https://github.com/chromiecraft/chromiecraft/issues/7084
- Closes an unreported issue.
- [Nethercite Deposit yields](https://www.wowhead.com/wotlk/object=185877#mining)
- [Sludge-covered Object yields](https://www.wowhead.com/wotlk/item=32724#contains)
- [Netherwing Crystal drops](https://www.wowhead.com/item=32427#dropped-by)
- [Fel Gland change note](https://wowpedia.fandom.com/wiki/Fel_Gland)
- [Netherwing Egg sources](https://www.wowhead.com/item=32506)
This PR: …
=> fix(DB): Couple Netherwing related fixes.

.github/labeler.yml, .github/workflows/pr_labeler.yml
=> fix(CI): I think this fixes the labeler :D

data/sql/updates/pending_db_world/hand_of_adal.sql
- Closes https://github.com/chromiecraft/chromiecraft/discussions/7091
1.
2.
3. …
=> fix(DB/achievement_reward): award title on Hand of A'dal FoS

data/sql/updates/pending_db_world/creature_scripts.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
Hi! So I figured out the issue. Issue was the despawning in Hyjal is done differently than on normal boss fights. It's done manually by GUID collection, and the infernals and doomguards were not properly collected yet. This PR rectifies that.
- Closes 
1. Go inside Hyjal
2. .instance setbossstate 1 2
3. go through the waves until you reach anetheron
4. wait for him to summon an infernal
5. die
6. wait for him to kill jaina
7. watch him despawn along with the infernal(s) …
=> fix(Scripts/Hyjal): correctly despawn summoned creatures on Jaina/Thrall death

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7031
1.
2.
3. …
=> fix(Scripts/Hyjal): archimonde enrage after 10 minutes

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7095
1.
2.
3. …
=> fix(Scripts/Hyjal): Anetheron cast Carrion Swarm on non player targets

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
=> chore(Scripts/Hyjal): Clean up unsafe calls and code style

.github/workflows/core-build-nopch.yml, .github/workflows/core-build-pch.yml, .github/workflows/import_pending.yml, .github/workflows/pr_labeler.yml, .github/workflows/tools_build.yml
We can't handle a million CI checks
=> chore(CI): Nuke checks

.github/labeler.yml
=> fix(CI): add missing ticks to labeler.yml file paths

src/server/shared/Network/NetworkThread.h
=> fix(Core/Networking): Fix crash in Proxy Protocol when removing closed sockets.

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
=> fix(Scripts/Hyjal): Fix Azgalor Doom targetting tanks since its an AoE spell

src/server/game/Entities/Player/Player.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/19014
- Closes 
1.
2.
3. …
=> fix(Core/Player): Delete by group

.github/labeler.yml
=> fix(CI/labeler): fix some paths for proper labeling

src/server/scripts/Northrend/Ulduar/HallsOfStone/brann_bronzebeard.cpp
Fixes Brann dialogue after completing the Tribunal encounter which was inaccurate to the live game
1. Enter the Halls of Stone
2. Complete all encounters up to the Tribunal of Stone escort encounter
3. Complete the encounter, then speak to Brann and observe the dialogue …
=> fix(Scripts/Halls of Stone): corrected Brann dialogue to match live game

data/sql/updates/pending_db_world/rev_1717701052651037100.sql
Incorrect subject line for the letter sent after achieving Glory of the Ulduar Raider
1. Complete the Glory of the Ulduar Raider achievement
2. Check the character's mail and read the subject line of the letter sent with the mount …
=> fix(DB/achievement_reward): Glory of the Ulduar Raider mail subject line

data/sql/updates/pending_db_world/rev_1717749728079323600.sql
* Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18903
- Closes 
1.
2.
3. …
=> fix(DB/Item): Egg Basket

data/sql/updates/pending_db_world/spell_scripts.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
No fear/air burst overlap, air burst no longer has an effect on the tank, uses the right enrage effect
- Closes https://github.com/chromiecraft/chromiecraft/issues/7030 …
=> fix(Scripts/Hyjal): some Archimonde fixes

data/sql/updates/pending_db_world/hyjal-models.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7072
- Closes https://github.com/chromiecraft/chromiecraft/issues/7080
- Closes https://github.com/chromiecraft/chromiecraft/issues/7081
This PR: …
=> fix(DB/Creature): Correct model info for Hyjal bosses.

data/sql/updates/pending_db_world/rev_1717886186186050826.sql, src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp, src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp, src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp, src/server/scripts/Northrend/Naxxramas/boss_grobbulus.cpp, src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp, src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp, src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp, src/server/scripts/Northrend/Naxxramas/naxxramas.h
only refactor
- Closes 
compiled, ran worldserver
1.
2.
3. …
=> Refactor(Scripts/Naxxramas): Spell Scripts use registry macros

data/sql/updates/pending_db_world/rev_1717964255204489800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7101
1.
2.
3. …
=> fix(DB/SAI): Subdue the Subduer should credit group

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
aoe should still not affect tanks
- Closes 
1.
2.
3. …
=> fix(Scripts/Hyjal): Air Burst back to random target

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.h, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7106
- Closes https://github.com/chromiecraft/chromiecraft/issues/7105
1.
2.
3. …
=> chore(Scripts/Hyjal): Clean up redundancy

data/sql/updates/pending_db_world/rev_1717965047865056400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6925
1.
2.
3. …
=> fix(DB/SAI): Watoosun Polluted Essence shouldnt cast Acid Splash

data/sql/updates/pending_db_world/rev_1717979069932709000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6535
1.
2.
3. …
=> fix(DB/Creature): Vashj elementals disorient immunity

src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6589
1.
2.
3. …
=> fix(Scripts/SSC): Fix Serpentshrine Parasites not being summoned

data/sql/updates/pending_db_world/rev_1717972134201713800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6764
1.
2.
3. …
=> fix(DB/Creature): Crystalcore Sentinals & Devastators knockback immunity

src/server/scripts/World/npcs_special.cpp
=> fix(Scripts/NPC): Fix arcanite dragonling attacking non flagged players

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
Can't replicate on local, but we're seeing crashes on live testing
- Closes 
1.
2.
3. …
=> fix(Scripts/Hyjal): remove very scary call by reference and posis without initialization

.github/labeler.yml
=> fix(CI/labeler): update Core, Documentation, Cmake labelling

data/sql/updates/pending_db_world/rev_1718086018134799100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7078
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18973
1.
2.
3. …
=> fix(DB/Creature): Kadrak's wrong axe model

.github/workflows/core-build-nopch.yml, .github/workflows/core-build-pch.yml
- we wan to support the 2 latest ubuntu LTS versions
- Closes 
1.
2.
3. …
=> fix(CI): reintroduce ubuntu-22.04 checks

.github/SECURITY.md
=> fix(docs): sync SECURITY.md with current CI config

data/sql/updates/pending_db_world/rev_1718275290940257000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7100
90s respawn timer on cata recycled, mangos has it between 60 and 120.
1.
2.
3. …
=> fix(DB/Creature): Reth'hedron spawn timer

data/sql/updates/pending_db_world/rev_1718466700851370000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7118
- Closes https://github.com/chromiecraft/chromiecraft/issues/7112
1.
2.
3. …
=> fix(DB/Formations): Aqueous Lord formation behaviour

data/sql/updates/pending_db_world/rev_1718465866090605600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7113
1.
2.
3. …
=> fix(DB/Spell): Sludge Nova stack from different casters

data/sql/updates/pending_db_world/rev_1718459860752594600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7111
1.
2.
3. …
=> fix(DB/Creature): Aquaneous Lord taunt immunity

data/sql/updates/pending_db_world/stunherald.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7063
This PR: …
=> fix(DB/Item): Stormherald PPM adjustment.

.github/workflows/core-build-nopch.yml, .github/workflows/core-build-pch.yml
=> feat(CI): enable fail-fast for pch/nopch

src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7114
1.
2.
3. …
=> fix(Scripts/BlackTemple): Fix Free Friend spell

src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7116
1.
2.
3. …
=> fix(Scripts/BlackTemple): Fix Najentus not enraging after 8 min

data/sql/updates/pending_db_world/rev_1718481266706776400.sql
* closes #18429
- Closes 
1.
2.
3. …
=> fix(DB/Achievement): Pilgrim reward mail

src/server/scripts/Outland/BlackTemple/boss_warlord_najentus.cpp
=> fix(Scripts/BlackTemple): Fix najentus enrage not reseting

data/sql/updates/pending_db_world/bt-bosses.sql
- Closes unreported issues.
This PR: …
=> fix(DB/Creature): Correct model info for Black Temple bosses.

data/sql/updates/pending_db_world/reckoning-downrank.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6997
This PR: …
=> fix(DB/Procs): Add proc info for lower ranks of Reckoning talent.

data/sql/updates/pending_db_world/rev_1718712283431197500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4768
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14582
mangos-wotlk
1.
2.
3. …
=> fix(DB/Creature): Port Force-Commander Gorax patrol from mangos-wotlk

data/sql/updates/pending_db_world/rev_1718710211512527300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7003
wowhead drops/comments & other similar mobs
1.
2.
3. …
=> fix(DB/Loot): Mote of Shadow incorrect low value for 2 npcs

src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp
=> fix(Scripts/ICC): Fix Valithria reseting

data/sql/updates/pending_db_world/seals.sql, src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/Spells/spell_paladin.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6566
Neither of these issues will be tackled by this PR. I'm sick of spell script already. …
=> fix(Scripts/Spells): Implement damage scaling based off DoT stack count for Seal of Vengeance and Corruption.

data/sql/updates/pending_db_world/rev_1718749668931737500.sql
- Makes despawn slightly faster
- Fixes BroadcastTextId for the line
- Changed a comment and removed a bad link that had no effect
- Closes https://github.com/chromiecraft/chromiecraft/issues/7103
- Closes https://github.com/chromiecraft/chromiecraft/issues/7090
1.
2.
3. …
=> fix(DB/Creature): Fix minor issues with Dragonmaw Peons

data/sql/updates/pending_db_world/molten-fury.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7108.
This PR: …
=> fix(DB/Loot): Correct oversight with Hyjal trash loot.

data/sql/updates/pending_db_world/hyjal-gem-veins.sql
=> fix(DB/Loot): Adjust Ancient Gem Vein loot table.

src/server/game/Spells/Spell.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7138
1. Cast spells.
2. Observe GCD delay behavior. …
=> fix(Core/Spells): Partially revert spell cancel behavior change.

data/sql/updates/pending_db_world/rev_1718872164901436000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7133
1.
2.
3. …
=> fix(DB/Creature): Illidari Fearbringer immunities

data/sql/updates/pending_db_world/rev_1718871720074355000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7126
1.
2.
3. …
=> fix(DB/Creature): Bonechewer Taskmaster taunt immunity

data/sql/updates/pending_db_world/rev_1718844992509230300.sql
*Otherwise, Archimonde will pull the Night Elf base into combat during the death RP
- Closes 
1.
2.
3. …
=> fix(DB/Conditions): Spell Protection of Elune only targets players

data/sql/updates/pending_db_world/rev_1717788081682357961.sql, src/server/scripts/Kalimdor/zone_orgrimmar.cpp
Adjust timings of Herald of Thrall and Thrall's WCB to classic
Limit Herald shout to Area instead of Zone
From my classic experience , WCB applies only to Orgrimmar and Crossroads. WCB does not apply to Razor Hill or Camp Taraujo. I found no classic or official data that says otherwise. PR/issue linked below show private server footage before Classic 2019 release.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1690
- https://github.com/azerothcore/azerothcore-wotlk/pull/10330
Classic crossroads Herald https://www.youtube.com/watch?v=Rhvi4KpUnqo
Classic …
=> fix(Scripts/Kalimdor): adjust Thrall's and Herald WCB timings, limit to Orgrimmar and Crossroads

data/sql/updates/pending_db_world/doomfire-speed.sql
=> fix(DB/Creature): Correct Doomfire/Spirit speed.

src/server/scripts/Events/midsummer.cpp
- Hopefully closes https://github.com/azerothcore/azerothcore-wotlk/issues/19107
This PR: …
=> fix(Scripts/Midsummer): Resolve Ribbon Pole crash.

src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
- Closes 
1. .qu ad 11691
2. start ahune
3. …
=> fix(Core/Ahune): Chest and Quest

data/sql/updates/pending_db_world/doomfire-speed-again.sql
Somehow forgot to include this one. …
=> fix(DB/Creature): Finish correcting Doomfire Spirit speed. 

src/server/scripts/Events/midsummer.cpp
=> fix(Scripts/Midsummer): use GUID storage rather than Player object

data/sql/updates/pending_db_world/rev_1718997265683510500.sql
these should be invisible to the normal player
- Closes 
1.
2.
3. …
=> fix(DB/Creature): add TRIGGER flag to 'Ribbon Pole Fire Spiral Bunny'

data/sql/updates/pending_db_world/rev_1718948799326042600.sql
In patch [2.3.0](https://wowpedia.fandom.com/wiki/Patch_2.3.0) the following change occurred.
"All primary profession trainers outside of capitals (Alchemy, Blacksmithing, Enchanting, Engineering, Leatherworking, Tailoring) have been changed to train up to Artisan level (skill level 300) in their respective professions."
Which kind of makes the gossip text irrelevant, but hey, it's there.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16292
- Closes https://github.com/chromiecraft/chromiecraft/issues/3025
.go c id 16729
.setskill 197 …
=> fix(DB/Gossip): Refik missing text for lowlevel tailoring

data/sql/updates/pending_db_world/rev_1719024661180085554.sql, src/server/scripts/Kalimdor/zone_orgrimmar.cpp
followup on info from https://github.com/azerothcore/azerothcore-wotlk/pull/19025#issuecomment-2183505000
- https://github.com/azerothcore/azerothcore-wotlk/pull/19025
- Closes 
head on southern spike https://www.youtube.com/watch?v=vwqiIIx_VLQ
Go to Thrall
```
.quest remove  4974
.quest add 4974
.quest complete  4974
```
Turn in quest …
=> fix(Scripts/Kalimdor) Thrall Warchief's Blessing, add level and reputation requirement, spike activation

data/sql/updates/pending_db_world/rev_1719015578865296300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7135
1.
2.
3. …
=> fix(DB/Creature): Fix Dragonmaw Wind Rider interrupt immunity

data/sql/updates/pending_db_world/rev_1719050119960028055.sql
fixup
- https://github.com/azerothcore/azerothcore-wotlk/pull/19121
fix invalid faction 528 to 76 Orgrimmar
fix effect_2 (4) to all effects (7)
- Closes 
1.
2.
3. …
=> fix(DB/Kalimdor): Thrall's WCB fixup

data/sql/updates/pending_db_world/rev_1719201621798878998.sql, src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
see https://github.com/azerothcore/azerothcore-wotlk/commit/cd9dff503258445958922be5643829aa21a8461e#commitcomment-143445861
d1dd35d1d497a8fe1017940a4b1ceeeb9e940e4e
- Closes 
1.
2.
3. …
=> refactor(Scripts/Northrend): fixup spell_hadronox_summon_periodic_crypt_fiend_aura

data/sql/updates/pending_db_world/rev_1719204209610400400.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14639
- Closes https://github.com/chromiecraft/chromiecraft/issues/4726
.go q starter 6544
Complete as a party …
=> fix(DB/SAI): Torek's Assault not completing for party members

data/sql/updates/pending_db_world/ahune-frozen-core-level.sql
Somehow missed this in the rewrite.
-  [X] Database (Creature).
This PR: …
=> fix(Creature): Adjust Ahune Frozen Core level.

.github/actions/linux-build/action.yml
let's fail on startup errors again
- Closes 
1.
2.
3. …
=> fix(CI): fix Error.log check

data/sql/updates/pending_db_world/rev_1719292494710324800.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14691
- Closes https://github.com/chromiecraft/chromiecraft/issues/4750
Checked by @heyitsbench!
.go c 70061
Kill the Zaxxis without completing/taking any quests
Loot Insignia(s) …
=> fix(DB/Conditions): Zaxxis Insignia should drop without any conditions.

data/sql/updates/pending_db_world/lager-loot.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16116
- Closes https://github.com/chromiecraft/chromiecraft/issues/5518
This PR: …
=> fix(DB/Loot): Correct chances related to Captain Rumsey's Lager recipe.

data/sql/updates/pending_db_world/rev_1719307113805462600.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14960
https://youtu.be/CTraItJtIlQ?t=13 They throw them instantly at (roughly~) 10y+ range.
https://www.youtube.com/watch?v=-txC_xYhQvM They do NOT throw them at melee range or close to it (10y~)
.go c id 20409
See that they no longer miss the shadowy aura
See if they throw their hammer(s) at you when you are further than 10 yards away. …
=> fix(DB/SAI): Kirin'Var Apprentice not throwing hammer and missing aura

data/sql/updates/pending_db_world/rev_1719293888962296500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17074
- Closes https://github.com/chromiecraft/chromiecraft/issues/4953
https://youtu.be/IJIDJuJlZS4?t=158
.go xyz 2121 61 52 560
start pulling the front mobs of each lodge …
=> fix(DB/Formations): Link Durnholde Lodges

data/sql/updates/pending_db_world/ethereum-loot.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15592
- Closes https://github.com/chromiecraft/chromiecraft/issues/5267
- Closes https://github.com/chromiecraft/chromiecraft/issues/5909
This PR: …
=> fix(DB/Loot): Add guaranteed drops to Ethereum Prisoner loot tables.

data/sql/updates/pending_db_world/rev_1719258494164779500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15126
- Closes https://github.com/chromiecraft/chromiecraft/issues/4955
Enrage spell -https://wowpedia.fandom.com/wiki/Lashh%27an_Kaliri
From video sources, they only emote roughly 50% of the time.
.go c id 19943
Pull and kill the Talonite, pet should enrage …
=> fix(DB/SAI): Lashh'an Talonite pets

data/sql/updates/pending_db_world/rev_1719301072788927300.sql
The root is there because they don't stop moving even if they go into passive reaction upon entering combat. (from random wander or wp pathing)
- Closes https://github.com/chromiecraft/chromiecraft/issues/4950
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15945
https://www.youtube.com/watch?v=s7hvoujn_d0&t=29s
.go c id 20512
Pull, see short animation
See if Soulbind reflects damage
https://youtu.be/s7hvoujn_d0?t=29 …
=> fix(DB/SAI): Tormented Soul & Soulbind spell

data/sql/updates/db_world/2024_06_25_09.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19174
1.
2.
3. …
=> fix(DB/SAI): A large number of SAI are lost

src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h
implement pause and resume for WaypointGenerator
so below functions work on NPCs that are pathing:
https://github.com/azerothcore/azerothcore-wotlk/blob/bb0a04e9941622796081c7dd15e3e164f953a4f4/src/server/game/Entities/Unit/Unit.cpp#L16940
https://github.com/azerothcore/azerothcore-wotlk/blob/bb0a04e9941622796081c7dd15e3e164f953a4f4/src/server/game/Entities/Unit/Unit.cpp#L16951
- Closes 
found as part of TC335 https://github.com/TrinityCore/TrinityCore/commit/7fff83d67526efff63867d41b9e036a19a9287b3#diff-bbcbf66611053741bbdcf0259310c1dadc6c082c797c18d35f9bbd3e204789d3 …
=> fix(Core/Movement): implement Pause and Resume to WaypointMovementGenerator

data/sql/updates/pending_db_world/rev_1719389660449504177.sql, src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
=> refactor(Scripts/Karazhan): Spell Scripts registry macros

data/sql/updates/pending_db_world/rev_1719389480144846526.sql, src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_salramm.cpp, src/server/scripts/Kalimdor/ZulFarrak/instance_zulfarrak.cpp, src/server/scripts/Kalimdor/zone_durotar.cpp, src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp, src/server/scripts/Kalimdor/zone_feralas.cpp
=> refactor(Scripts/Kalimdor): Spell Scripts registry macros

data/sql/updates/pending_db_world/ahune-ice-spear.sql, src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
=> fix(Scripts/SlavePens): Remove permanent knockback aura on ice spear bunny.

data/sql/updates/pending_db_world/rev_1719427468873631200.sql
- Closes azerothcore/azerothcore-wotlk#8823
- Closes chromiecraft/chromiecraft#2216
.go c 2
walk into transpolyporter
nothing happens
.additem 9173
walk into transpolyporter
visit Gnomegeran instantly
should work both ways while in posession of item 9173
without this item both transpolyporters should do nothing at all
I did not test the quest chain that provides this item. …
=> fix(DB): fix Booty Bay / Gnomegeran Transpolyporter

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
=> fix(Core/AI): Don't set boss state to none if already complete

data/sql/updates/pending_db_world/rev_1719322993021854900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4996
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15007
mangos-wotlk DB
1.
2.
3. …
=> fix(DB/Creature): Port Treebole WP from mangos-wotlk

data/sql/updates/pending_db_world/rev_1719452424249472600.sql
=> fix(DB/Creature): Blight Geist using wrong target_type

src/server/scripts/Outland/CoilfangReservoir/SlavePens/boss_ahune.cpp
-  [X] Scripts (boss script).
- Closes unreported issue. Ahune sometimes did not have his shield cast on himself. …
=> fix(Scripts/SlavePens): Adjust Ahune spell casts.

src/server/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
-  [X] Scripts (boss scripts).
- [Wrath Classic Death Knight solo](https://youtu.be/Nm1wYwjgHm8&t=47)
This PR: …
=> fix(Scripts/Karazhan): Allow portal color effects to overlap on players.

data/sql/updates/pending_db_world/rev_1719344429715330100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/4954
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15127
https://www.wowhead.com/wotlk/npc=19944/lashhan-wing-guard
Source for GO position is mangos-wotlk DB
.go c id 19944
Bring it to 20% hp
Should run to nearest (out of 2) runes and summon bird …
=> fix(DB/SAI): Lashh'an Wing Guard

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Events/midsummer.cpp
-  [x ] Core (units, players, creatures, game systems).
the visual channeled spells are interrupted by gossip, however the aura associated with spinning and adding the xp buff is not
https://github.com/azerothcore/azerothcore-wotlk/blob/fd87ce1bf39b4b44c77734bcc7f6c1f22000d7b3/src/server/game/Handlers/NPCHandler.cpp#L293
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/5bd03eef-fc27-458e-bbb0-dbf170d1c7d5
changes:
add AURA_INTERRUPT_FLAG_TALK to spin aura
- Closes 
1.
2.
3. …
=> fix(Core/Spells): Midsummer spinning visual interrupt on gossip

data/sql/updates/pending_db_world/ice-stone-despawns.sql
-  [X] Database (SAI, creatures).
- Progresses https://github.com/chromiecraft/chromiecraft/issues/7149 …
=> fix(Scripts/Midsummer): Add despawn to Ice Stones and drop respawn time.

data/sql/updates/pending_db_world/missing-ahune-ice-bunny.sql
=> fix(DB/Midsummer): Add missing slippery floor bunny.

data/sql/updates/pending_db_world/ahune-model-info.sql
=> fix(DB/Creature): Correct model info for Ahune related mobs.

data/sql/updates/pending_db_world/ahune-pocket-full-of-loot.sql
This PR:
1. Engage Ahune in The Slave Pens.
2. Get knocked back.
3. Open your pocket full of snow.
4. Observe your pocket full of snow contains snow. …
=> fix(Loot/Midsummer): Add loot to Pocket Full of Snow.

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/World/npcs_special.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17186
- Closes https://github.com/chromiecraft/chromiecraft/issues/5120
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/18847
1. .`tele area52` with 2 opposite faction player
2. Fight inside Area 52
3. The guards will start hitting you if you put up a fight.
https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/a38a081a-b080-432a-add6-4312123e19d6 …
=> fix(Spells/SpellInfoCorrections) Remove friendly mask on goblins

data/sql/updates/pending_db_world/rev_1719387072847374776.sql, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp
=> refactor(Scripts/SunwellPlateau): Spell Scripts registry macros

src/server/scripts/World/boss_emerald_dragons.cpp
=> refactor(Scripts/World): Spell Scripts registry macros

data/sql/updates/pending_db_world/rev_1719569808533378600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5099
TDB
.go c id 22017 …
=> fix(DB/SAI): Eclipsion Spellbinder from TDB

data/sql/updates/pending_db_world/rev_1719236663593006100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14577
- Closes https://github.com/chromiecraft/chromiecraft/issues/4782
https://www.youtube.com/watch?v=rh-KNhAObTc
They constantly cast outside of melee range, and in melee range they roughly cast 5-10s (judging from video(s))
Shadow Rush timer is from **mangos-wotlk DB**
.go c id 17088 …
=> fix(DB/SAI): Shadowy Summoner

src/server/scripts/Spells/spell_rogue.cpp
difficult refactor of rogue killing spree spell- and aurascript pair, due to 
- https://github.com/azerothcore/azerothcore-wotlk/blob/77be5bb19d82a12dc27928c52c4204f37b8bf327/src/server/scripts/Spells/spell_rogue.cpp#L323
- Closes 
1.
2.
3. …
=> refactor(Scripts/Spells): Spell Scripts registry macros, rogue killing spree

data/sql/updates/pending_db_world/rev_1719659662833833500.sql
- Follow-Up to #18073
- thanks @noisiver for letting me know of this issue
1.
2.
3. …
=> fix(DB/Creature): remove duplicate 25962 'Fire Eater' spawns

src/server/scripts/Spells/spell_item.cpp
=> fix(build): mac

data/sql/updates/pending_db_world/rev_1719517115175571300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5017
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14999
Video and TDB
* GO spawn
-- cherry-pick https://github.com/TrinityCore/TrinityCore/commit/e0ccfefb462e045cfaa07353421c4d4e5b02bc49
-- Co-Authored-By: offl <11556157+offl@users.noreply.github.com>
.q add 10256
.add 28786
.go c 69740
Use the item …
=> fix(DB/SAI): Port 'Finding the Keymaster' RP from TDB

data/sql/updates/db_world/2024_06_29_11.sql
=> fix(DB): correct query

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
=> fix(Scripts/Hyjal): Workaround bosses getting stuck in progress

src/server/apps/worldserver/worldserver.conf.dist, src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp, src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.h, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
=> fix(Script/GunshipBattle): Wipe if no player is on the deck

data/sql/updates/pending_db_world/rev_1719791096484121500.sql, src/server/game/Miscellaneous/Language.h, src/server/scripts/Commands/cs_lookup.cpp, src/server/scripts/Commands/cs_npc.cpp
* close https://github.com/azerothcore/azerothcore-wotlk/issues/19216
- Closes 
1.
2.
3. …
=> fix(Script/Commands): output lookup quest and npc near

data/sql/updates/pending_db_world/rev_1719843096503724800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5220
Timers are rough estimation by the other 2 mobs that have the same spell set. https://www.wowhead.com/wotlk/spell=36398
Tongue lash seems to not be 100% (over 15+ videos where it was never casted, but exists in sniffs ¯\_(ツ)_/¯)
Additionally in every video he spawns and instantly casts the beam.
Sniffs by @heyitsbench 
.q add 10669
.go zonexy 16 40 3521 …
=> fix(DB/SAI): Xeleth

src/server/scripts/EasternKingdoms/zone_blasted_lands.cpp, src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp, src/server/scripts/EasternKingdoms/zone_undercity.cpp
- Closes 
built and ran worldserver
1.
2.
3. …
=> refactor(Scripts/EasternKingdoms)SpellScripts

data/sql/updates/pending_db_world/hyjal-boss-speeds.sql
=> fix(DB/Creature): Correct movement speed of Hyjal bosses.

src/server/game/Battlegrounds/ArenaTeam.cpp, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Globals/ObjectMgr.h, src/server/game/Guilds/Guild.cpp, src/server/game/Handlers/PetHandler.cpp, src/server/game/Handlers/PetitionsHandler.cpp, src/server/game/World/World.cpp, src/server/scripts/Commands/cs_character.cpp, src/server/scripts/Commands/cs_guild.cpp, src/server/scripts/Commands/cs_reload.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/18556
- Closes 
1.
2.
3. …
=> refactor(Core/ObjectMgr): Handle Profanity & Reserved Names in load

src/server/game/Maps/Map.cpp, src/server/game/Scripting/ScriptDefines/AllMapScript.cpp, src/server/game/Scripting/ScriptDefines/AllMapScript.h, src/server/game/Scripting/ScriptMgr.h
- to me this hook should obviously provide an option to overwrite the InstanceScript pointer
- this is e.g. beeing used by mod-eluna (but currently broken)
- Closes 
1.
2.
3. …
=> fix(Core/Scripting): fix OnBeforeCreateInstanceScript hook

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
-  [X] Scripts (boss scripts).
- Closes https://github.com/chromiecraft/chromiecraft/issues/6886
This PR: …
=> fix(Scripts/TheEye): Kael'thas adjustments.

src/server/game/Entities/Player/PlayerQuest.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/4468
1.
2.
3. …
=> fix(Core/Quest): typo in RewardQuest makes LFG quests not reward if dead

data/sql/updates/pending_db_world/kara-chest-pos.sql
-  [X] Database (Objects).
- Closes https://github.com/chromiecraft/chromiecraft/issues/6342
This PR: …
=> fix(DB/Gameobject): Move Karazhan chess chest.

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6797
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18827
https://youtu.be/YlCfJB7RN6U?t=2422
1.
2.
3. …
=> fix(Scripts/TK): Kael'thas mind control should reset threat

src/server/game/Entities/Pet/Pet.cpp
This prevents sending a fake-cast to trigger client cooldown if the pet is created by a spell with no cooldown
see source in linked issue
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19135
1.
2.
3. …
=> fix(Core/Pet): prevent LoadPetFromDB to trigger a fake summon spell cast in most cases

src/server/scripts/Northrend/zone_dalaran.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/16841
There is absolutely no information on the internet about minigob except wowhead comments. So with the power of wowhead comments this is what I got
- Closes 
1. .event start 33
2.
3. …
=> refactor(Script/Dalaran): Minigob Manabonk

src/common/Logging/enuminfo_LogCommon.cpp, src/server/game/Entities/Item/enuminfo_Item.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/enuminfo_Unit.cpp, src/server/game/Quests/enuminfo_QuestDef.cpp, src/server/game/Warden/enuminfo_WardenCheckMgr.cpp, src/server/shared/SharedDefines.h, src/server/shared/enuminfo_SharedDefines.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/19248
- Closes 
1.
2.
3. …
=> fix(Core/Spell): Implement SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT

data/sql/updates/pending_db_world/rev_1720109494288604410.sql
found while testing
- https://github.com/azerothcore/azerothcore-wotlk/issues/6005
Idol Room Spawner  is briefly visible, surely it should not be?
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/04bb07ac-a50c-4dbd-a48c-9d683d046bcd
- Closes 
1. .go c id 8516
2. accept quest
3.
**REMEMBER**: …
=> fix(DB/RazorfenDowns): set Idol Room Spawner no longer visible

src/server/game/Spells/Auras/SpellAuraEffects.cpp
Unsafe operation blah blah
- Closes 
1.
2.
3. …
=> chore(Core/Spells): Fix compile warning

src/server/game/Handlers/CombatHandler.cpp
-  [X] Core (handlers).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11719
- Closes https://github.com/chromiecraft/chromiecraft/issues/3495
- Likely closes https://github.com/chromiecraft/chromiecraft/issues/7070
- Might close https://github.com/chromiecraft/chromiecraft/issues/7001
So this fix is weird. From what I understand, it's trying to avoid a null pointer being floated along the way, but the issue is that when it gets to the removed function and stops the attack, it breaks the client and the client can no longer auto attack anything ever again. The behavior can easily be seen (iirc) by doing something like casting the aether ray wrangling rope but removing the target before the cast finishes, or by using the macro …
=> fix(Core/Handlers): Adjust start swing handler.

src/server/scripts/Spells/spell_item.cpp
=> fix(Core/Misc): unused param

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h
Should fix an issue when the client sees dead NPCs when they are not (0 health means that npc dead on client side).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19205
1.
2.
3. …
=> fix(Core/Unit): Invalidate update object cache when changing health in the same world update tick.

data/sql/updates/pending_db_world/rev_1720211249204769700.sql
Btw, these creatures share AI in a sense. Look up Voidhunter Yar for an example
- Closes https://github.com/chromiecraft/chromiecraft/issues/7169
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18865
1.
2.
3. …
=> fix(DB/Creature): Rewrite Voidshrieker AI

src/server/game/Conditions/ConditionMgr.cpp, src/server/game/Time/UpdateTime.cpp, src/server/scripts/Commands/cs_reload.cpp, src/server/scripts/Commands/cs_server.cpp
QOL. Just to not get markdown bullets when copying this info into issues.
- Closes 
1.
2.
3. …
=> chore(Scripts/Commands): QOL server debug

data/sql/updates/pending_db_world/rev_1720224478854376400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7026
1.
2.
3. …
=> chore(DB/Loot): Remove Metzen's Letters and Notes from creature loot tables

data/sql/updates/pending_db_world/rev_1720223739574037500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7058
🥭s
1.
2.
3. …
=> fix(DB/Creature): Add AI to Affray Challenger

data/sql/updates/pending_db_world/rev_1720214274816211200.sql
Was QuestTaken (makes no sense), changed to QuestRewarded
- Closes https://github.com/chromiecraft/chromiecraft/issues/7170
- Closes https://github.com/chromiecraft/chromiecraft/issues/7102
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4316
1.
2.
3. …
=> fix(DB/Condition): Fix condition type for restoring Scale of the Sands exalted ring

src/server/scripts/Outland/BlackTemple/boss_teron_gorefiend.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7179
1.
2.
3. …
=> fix(Scripts/BlackTemple): Move Teron Gorefiend to scheduler and add Berserk

data/sql/updates/pending_db_world/rev_1720225685784761500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6987
1.
2.
3. …
=> fix(DB/Creature): Skyguard Prisoner shoul spawn with ReactState Passive

data/sql/updates/pending_db_world/rev_1720226619555284700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6991
🥭s
1.
2.
3. …
=> fix(DB/Quests): Marks of Kil'Jaeden and Firewing Signets quests should be available at Neutral 0

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
* closes https://github.com/chromiecraft/chromiecraft/issues/6900
- Closes 
1.
2.
3. …
=> fix(Scripts/ShadeOfAran): Make immune to Mind-numbing and Cure of Tongue

data/sql/updates/pending_db_world/rev_1720233129521675900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6885
1.
2.
3. …
=> fix(DB/Creature): Verog the Dervish ReactState

data/sql/updates/pending_db_world/rev_1720232245698455400.sql
I don't know what caused it to cancel the Timed Event, but if it might be because it was aggroed prematurely then pushing it to a Actionlist should fix it
- Closes https://github.com/chromiecraft/chromiecraft/issues/6893
1.
2.
3. …
=> fix(DB/Creature): Prevent Hellfire Peninsula's Pit Commander from cancelling Timed Event

src/server/game/AI/CoreAI/UnitAI.h, src/server/game/AI/ScriptedAI/ScriptedCreature.h, src/server/game/AI/SmartScripts/SmartAI.cpp, src/server/game/AI/SmartScripts/SmartAI.h, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScript.h, src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/cfc77fd84355d28737f3f85f2ba318be5caacdea)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/beb333738db0d493bf95994eb5557e174e5dd3a6)
* Move IsSmart function from headerfile
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19195
1.
2.
3. …
=> feat(Core/SAI): SetData now has invoker

data/sql/updates/pending_db_world/rev_1720259679409109500.sql
Merge after https://github.com/azerothcore/azerothcore-wotlk/pull/19296
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15028
- Closes https://github.com/chromiecraft/chromiecraft/issues/5018
https://www.youtube.com/watch?v=-wZ54_uFCnE&t=15s
.quest add 10924
.go c 67776
Use the quest item
kill Warp Chasers …
=> fix(DB/SAI): Zeppit's RP for collecting blood

src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/GameObject/GameObject.h, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Grids/Notifiers/GridNotifiers.cpp, src/server/game/Grids/Notifiers/GridNotifiers.h, src/server/game/Time/UpdateTime.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/297541e9c9bf90d410922db397d2f94dff9592cc)
* Get rid of unused param
* Get rid of unused function
* Merge SendMessageToSetInRange_OwnTeam into SendMessageToSetInRange
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14058
1.
2.
3. …
=> fix(Core/Player): Vertical Message distance

data/sql/updates/pending_db_world/promenade-kick-immune.sql
Issue reports kick immunity on T5 spell, but this is the creature's only spell with a cast time/channel
- Closes https://github.com/chromiecraft/chromiecraft/issues/7142
1.
2.
3. …
=> fix(DB/TheBlackTemple): make Promenade Sentinel kick immune

data/sql/updates/pending_db_world/detect.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7156
1.
2.
3. …
=> fix(DB/TheBlackTemple): Ashtongue Feral Spirit detection range

data/sql/updates/pending_db_world/rev_1720238285754402600.sql
* closes https://github.com/chromiecraft/chromiecraft/issues/6241
- Closes 
1.
2.
3. …
=> fix(DB/Quest): Spirits of the Feralfen

data/sql/updates/pending_db_world/rev_1720229222612824600.sql
Not needed since they're useless but now it'll remove the gossip if the player already has it.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6981
1.
2.
3. …
=> fix(DB/Gossip): Allow Estelle Gendry to give players Thieves' Tools

data/sql/updates/pending_db_world/rev_1720231700188069900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6896
~~vibes~~
err.. mangos has a typo I think. One of the static On Equip spells has a ppm of 5, which doesn't make sense? so maybe I thought it should've gone to the On Hit spell instead
1.
2.
3. …
=> fix(DB/Item): Increase ppm of Netherstrand Longbow

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_rage_winterchill.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6976
- Closes https://github.com/chromiecraft/chromiecraft/issues/6975
1.
2.
3. …
=> fix(Scripts/HyjalSummit): Rage Winterchill Spells

data/sql/updates/pending_db_world/rev_1720367551396070400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6105
https://youtu.be/WPpz07e6Cic?t=53
https://www.wowhead.com/tbc/npc=18473/talon-king-ikiss#comments
Multiple comments about not being interruptable (after 2.0.7)
1.
2.
3. …
=> fix(DB/Creature): Talon King Ikiss should be immune to interrupts

data/sql/updates/pending_db_world/rev_1720230463035941600.sql
Mechanical creatures were given Bleed immunity across the board, leading to, for example, unused creatures having bleed immunity when it'd be impossible to determine that. Mangos also seems to agree that bleed is something mechanicals do not have anymore.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6901
- Closes https://github.com/chromiecraft/chromiecraft/issues/7042
& 🥭s
1.
2.
3. …
=> fix(DB/Creature): Remove Bleed immunities from mechanical & undead creatures

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17258
- Closes https://github.com/chromiecraft/chromiecraft/issues/6122
https://www.wowhead.com/wotlk/npc=18832/krosh-firehand
.learn 48947
target an enemy npc
.cast back 33051 t
cast with and without the aura, damage should be the same. …
=> fix(Core/Spells): Greater Fireball should ignore resistances

data/sql/updates/pending_db_world/kara-gryphons.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6343 …
=> fix(DB/Karazhan): Respawn Skeletal Gryphons.

src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
=> fix(Build): -Wsign-compare

data/sql/updates/pending_db_world/rev_1720413117680804600.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6569
1.
2.
3. …
=> fix(DB/Quest): Add ability to request missing quest item Manna-Enriched Horse Feed

data/sql/updates/pending_db_world/rev_1720372819954042700.sql
As part of the script, the creature casts a 'Powered Down' stun spell on self. If pulled during this, it won't move.
- Closes https://github.com/chromiecraft/chromiecraft/issues/6849
1.
2.
3. …
=> fix(DB/Creature): Don't continue Crystalcore Sentinel RP script when combat starts

data/sql/updates/pending_db_world/rev_1720412580617188000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19325
1.
2.
3. …
=> fix(DB/Creature): Mo'grosh Shaman

data/sql/updates/pending_db_world/rev_1720367999640087800.sql
=> fix(DB/Creature): Attempt to avoid Timed Event overlap in Underbog Colossus

data/sql/updates/pending_db_world/rev_1720372030178282300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6868
1.
2.
3. …
=> fix(DB/Creature): Add Blink to Netherstrand Longbow

data/sql/updates/pending_db_world/rev_1720402396845233700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6741
1.
2.
3. …
=> fix(DB/Creature): Damage Requirement for Infernal Attacker

data/sql/updates/pending_db_world/rev_1720451450348532100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6327
1.
2.
3. …
=> fix(DB/Quest): 'A Special Thank You' should require friendly rep

data/sql/updates/pending_db_world/rev_1720368758501918700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6821
1.
2.
3. …
=> fix(DB/Creature): Shadowlord Deathwail's respawn time

data/sql/updates/pending_db_world/rev_1720411446927878900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7192
1.
2.
3. …
=> fix(DB/Quest): Add SpecialFlags to Scale of Sands ring swap quests

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
-  [X] Scripts (Boss scripts).
- Closes https://github.com/chromiecraft/chromiecraft/issues/7193
Some sources swap these two classes both the way proposed in this PR and in current master AC, video shows a paladin dying and applying the yellow charge to Archimonde, corroborating the former. …
=> fix(Scripts/HyjalSummit): Correct Soul Charge color assignments.

data/sql/updates/pending_db_world/rev_1720371062445685800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7191
1.
2.
3. …
=> fix(DB/Loot): Normalize Epic Gear Zone Drops in The Eye

data/sql/updates/pending_db_world/rev_1720452811650880300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6321
https://www.youtube.com/watch?v=BUNtnuTE7wI
.aura 40055,40165,40166,40167 …
=> fix(DB/Custom): Introspection aura(s) should be a debuff

src/server/game/Entities/Totem/Totem.cpp, src/server/game/Entities/Totem/Totem.h
- Closes https://github.com/chromiecraft/chromiecraft/issues/6561
https://www.youtube.com/watch?v=ZTyRjhG2mfc&t=283s
https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/785433bf-cbc8-45b0-a17b-f18c39ec121c
1.
2.
3. …
=> fix(Core/Totem): Totems shouldn't be immune to intervene.

data/sql/updates/pending_db_world/rev_1720460884217798700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6355
in the issue
1.
2.
3. …
=> fix(DB/Creature): Sturdy Plate shouldn't be selectable.

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
=> refactor(Scripts/BlackTemple): Update Mother Sharahz script

data/sql/updates/pending_db_world/rev_1720400328193554900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6776
1.
2.
3. …
=> fix(DB/Creature): Add pet spells to Tempest-Smith

src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Spells/SpellEffects.cpp, src/server/game/Spells/SpellInfoCorrections.cpp
=> fix(Core/GameObject): Use correct spell at meeting stone

data/sql/updates/pending_db_world/hyjal-trash-adjustments.sql
-  [X] Database (creatures).
This PR: …
=> fix(DB/Creature): Adjust some values of Hyjal trash creatures.

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_azgalor.cpp
-  [X] Scripts (boss scripts).
- Progresses https://github.com/chromiecraft/chromiecraft/issues/7200 …
=> fix(Scripts/HyjalSummit): Adjust Azgalor's Rain of Fire timings.

data/sql/updates/pending_db_world/hyjal-swing-timers.sql
-  [X] Database (creatures).
This PR: …
=> fix(DB/Creature): Update Hyjal boss swing timers.

data/sql/updates/pending_db_world/rev_1720719550227839300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6544
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18421
Timers for SAI cherry-picked from:
-- cmangos/tbc-db/pull/336
-- Co-Authored-By: AnonXS <19734826+AnonXS@users.noreply.github.com>
.go c id 21787
.aura 37678 on self …
=> fix(DB/Creature): Time-Lost Skettis High Priest & Talonpriests

data/sql/updates/pending_db_world/rev_1720456456817446800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6395
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18051
.go c id 4792
.q add 11183
use the torch at the end of the bridge
only 1 spawn …
=> fix(DB/Conditions): Spawn only 1 'Zelfrax'

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7013
in the issue
1.
2.
3. …
=> fix(Scripts/TK): KT Mindcontrol should respect Line of Sight

data/sql/updates/pending_db_world/rev_1720886969204406200.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/BlackTemple/black_temple.h, src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
41159 is in the basepoints of 39649 
- Closes https://github.com/chromiecraft/chromiecraft/issues/7136
More sources in the issue
https://classic.warcraftlogs.com/reports/KAqCaLM9kdZT1PfB#fight=23&pins=0%24Separate%24%23244F4B%24summons%24-1%240.0.0.Any%2422855.0.0.NPC%24true%240.0.0.Any%24true%240&hostility=1&type=summary&view=events&start=2751122&end=2754123
1.
2.
3. …
=> fix(Core/Spells): BT - Summon Shadowfiens should spawn 11, instead of 1

data/sql/updates/pending_db_world/rev_1720906730828914400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6545
- Closes https://github.com/chromiecraft/chromiecraft/issues/6546
🥭s with adjustments
1.
2.
3. …
=> fix(DB/Creature): Rewrite Skettis mini bosses

data/sql/updates/pending_db_world/rev_1720928725467169800.sql, src/server/scripts/Outland/zone_netherstorm.cpp
Simplify it, remove unnecessary code
- Closes https://github.com/chromiecraft/chromiecraft/issues/7197
1.
2.
3. …
=> fix(Scripts/Netherstorm): Rewrite Phase Hunter AI

src/server/game/Entities/Unit/Unit.cpp
-  [X] Core (unit).
- Kinda https://github.com/azerothcore/azerothcore-wotlk/issues/11719
- Kinda https://github.com/chromiecraft/chromiecraft/issues/3495
This PR: …
=> fix(Core/Unit): Adjust melee attack stop logic.

data/sql/updates/pending_db_world/bad-ai.sql
-  [X] Database (SAI, creatures).
This PR: …
=> fix(Creature): Remove bad SmartAI entries.

src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6790
https://github.com/DeadlyBossMods/DBM-Classic/releases/tag/1.15.18
https://github.com/DeadlyBossMods/DBM-Vanilla/blob/master/DBM-Raids-Vanilla/VanillaZG/Jindo.lua#L25
1.
2.
3. …
=> fix(Scripts/ZG): Jin'do using wrong hex spell

data/sql/updates/pending_db_world/mirkblood-loot.sql
-  [X] Database (creatures, loot).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16231
This PR: …
=> fix(DB/Loot): Add loot for Tenris Mirkblood event boss.

src/server/game/Scripting/ScriptDefines/GameObjectScript.h, src/server/scripts/Northrend/AzjolNerub/ahnkahet/ahnkahet.h
=> chore(Core/GameObjectAI): Cleanup register macro

src/server/scripts/World/server_mail.cpp
Make it a bit more readable and remove some redundant code
- Closes 
1.
2.
3. …
=> chore(Scripts/ServerMail): Cleanup the code

data/sql/updates/pending_db_world/rev_1719942973235275500.sql, src/server/scripts/Spells/spell_generic.cpp
For SAI just added demo shout & talk on aggro, ran generate comments from keira, need sniff for timers as those look very scuffed to me.
Spell 36209 is also probably being used in a sniff, but won't do anything as everything is handled in 36208.
- Closes https://github.com/chromiecraft/chromiecraft/issues/5249
https://www.wowhead.com/wotlk/npc=20730
.go c id 20730
.cast 30146 t 
attack with felguard …
=> fix(Core/Spells): Script Glumdor's Steal Weapon

data/sql/updates/pending_db_world/rev_1718995543775863200.sql
Fixed the text of Glyphic Scroll https://www.wowhead.com/classic/item=9574/glyphic-scroll  from the undead mage quest of the same name. 
It was showing the text of Glyphic Memorandum https://www.wowhead.com/classic/item=9573/glyphic-memorandum from the gnome mage quest of the same name.
- Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/18420
1.
2.
3. …
=> fix(DB/PageText): Glyphic Scroll text

data/sql/updates/pending_db_world/rev_1721187314824254400.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19361
- Closes https://github.com/chromiecraft/chromiecraft/issues/6856
yeah I went there to check
1.
2.
3. …
=> fix(DB/Creature): Hellfire Training Dummies shouldn't be attackable

data/sql/updates/pending_db_world/rev_1721186384223205700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7211
- Closes https://github.com/chromiecraft/chromiecraft/issues/7207
- Closes https://github.com/chromiecraft/chromiecraft/issues/7212
- Closes https://github.com/chromiecraft/chromiecraft/issues/7213
- Closes https://github.com/chromiecraft/chromiecraft/issues/7208
1.
2.
3. …
=> fix(DB/Creature): Small Black Temple adjustments

src/server/game/Entities/Pet/Pet.cpp, src/server/game/Entities/Pet/Pet.h, src/server/scripts/Spells/spell_generic.cpp
Pets were incorrectly revived without restoring its mana
- Closes #15894
- Closes https://github.com/chromiecraft/chromiecraft/issues/4272
- Closes https://github.com/chromiecraft/chromiecraft/issues/5309
Sources in the linked issues
1. Create warlock
1. Enter any battleground (Warsong) and wait for it to start 
1. Summon any pet, e.g. Succubus
1. Spend some of the pet's mana, e.g. cast Lesser Invisibility 3-4 times
1. Die before the pet regenerates all its mana back
1. Get resurrected by the Spirit Healer
1. The pet should be revived too and its mana …
=> fix(Scripts/Spells): Revive pets with full mana in bgs

src/server/game/Entities/Unit/Unit.cpp
when casting  shattering throw or non-instant slam will now cancel heroic strike and cleave 
- Closes https://github.com/chromiecraft/chromiecraft/issues/7131
issue video
https://github.com/azerothcore/azerothcore-wotlk/assets/46423958/41792ccf-2ff8-4535-8252-49b3ef87f1bf
1.
2.
3.
**REMEMBER**: when testing a …
=> fix(Core/Unit): add melee spell breaking for spells with cast time

data/sql/updates/pending_db_world/rev_1715075443315896336.sql, data/sql/updates/pending_db_world/rev_1715084722919779733.sql, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp
* 5% hp say text
* rewrite p3 to spawn trap objects which spawn skeletons. skeletons no longer spawn wielding weapons
* refactor to get rid of _scheduler
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16245
1.
2.
3. …
=> fix(Scripts/BlackwingLair): Nefarian say low health and rewrite p3

data/sql/base/database-squash.md
Document how to do a squash within the repo
=> docs(DB): Database Squash

src/server/scripts/World/chat_log.cpp
Make the code more readable
- Closes 
1.
2.
3. …
=> chore(Scripts/ChatLog): Cleanup the code

src/server/scripts/World/chat_log.cpp
=> fix(Scripts/ChatLog): Whoopsies

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/CombatHandler.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19429
This PR: …
=> fix(Core): Correct packet structure for combat stop messages.

src/server/game/Spells/SpellInfoCorrections.cpp
"Ground mounts may swim without dismounting the rider" 
This is true for all ground mounts accessible to the player, but some mounts that are typically not accessible to players still have flag  `AURA_INTERRUPT_FLAG_NOT_ABOVEWATER` set which makes them dismount when touching water. 
Propose to remove this flag for some.
process:
1. parse spells DBC with node-dbc-reader https://github.com/wowgaming/node-dbc-reader that have this flag set.
`run start -- --search="{*} & 128" --columns=AuraInterruptFlags Spell > spells_AuraInterruptFlags_128.txt`
2. Filter out 
a. must have SPELL_AURA_MOUNTED 78
b. must not have …
=> fix(Spells/SpellInfoCorrections): remove AURA_INTERRUPT_FLAG_NOT_ABOVEWATER from some mounts

src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7164
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19312
1.
2.
3. …
=> fix(Scripts/BlackTemple): Ashtongue Defenders unable to attack Akama

data/sql/updates/pending_db_world/rev_1721315048505216800.sql, src/server/scripts/Outland/BlackTemple/boss_teron_gorefiend.cpp, src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
Vengeful Spirit was being assigned as a Teron's summon, causing it to despawn on the latter's death. Vengeful Spirit should stay after his death because this is spawned by the player, not the boss.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7210
- Closes https://github.com/chromiecraft/chromiecraft/issues/7209
1.
2.
3. …
=> fix(Scripts/BlackTemple): Vengeful Spirit, Shadow of Death Remove

src/server/scripts/Commands/cs_reload.cpp
=> fix(Scripts/Reload): Only send reload output to GMs

data/sql/updates/pending_db_world/rev_1721179877054180200.sql
* Closes https://github.com/chromiecraft/chromiecraft/issues/7046
- Closes 
1.
2.
3. …
=> fix(DB/Item): Bouquet of Orange Marigolds

data/sql/updates/pending_db_world/rev_1721400804205047100.sql
* Show gossip option only if the player does not have the ring and has Choose your path rewarded
- Closes 
1.
2.
3. …
=> fix(DB/Creature): Ormus the Penitent

src/common/Configuration/Config.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4781
Tested using
`LoginDatabaseInfo = "127.0.0.1;3306;aa;#!StrOngPass#@rd;acore_auth"`
1.
2.
3. …
=> fix(Core/Config): Allow `#` outside of comments

.github/actions/linux-build/action.yml, .github/workflows/tools_build.yml
=> fix(CI): tools

data/sql/updates/pending_db_world/rev_1721705202781499700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7220
1.
2.
3. …
=> fix(DB/Creature): Illidan taunt immunity

data/sql/updates/pending_db_world/rev_1721586059640959700.sql, src/server/game/Miscellaneous/Language.h, src/server/scripts/Commands/cs_misc.cpp
Yet another custom change...
- Closes 
.aura 44833
.aura stack 44833 10
.list auras
.aura stack 44833 -5
.list auras …
=> feat(Scripts/Commands): .aura stack - Modify aura stacks

src/server/game/Spells/Auras/SpellAuraEffects.cpp
Spell Aura 230 is only used by Blood Pact and Commanding Shout.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7011
.damage yourself to various hp percentages
1. .cast self 47440
or
1. .cast self 688
2. use imps blood pact …
=> fix (Core/Spells) Commanding Shout and Blood Pact remember percentage of health

data/sql/updates/pending_db_world/rev_1721937325469970800.sql, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18826
- Closes https://github.com/chromiecraft/chromiecraft/issues/6633
https://youtu.be/GF_FtgDNvF8?t=418
1. .go c id 21212
2. do fight until p3
3. take Vashj on a walk …
=> fix (script/SSC) Enchanted Elementals follow Vashj

data/sql/updates/pending_db_world/rev_1722077567551108843.sql, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_baltharus_the_warborn.cpp, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_saviana_ragefire.cpp, src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/instance_ruby_sanctum.cpp
only refactor
- Closes 
1.
2.
3. …
=> refactor(Scripts/RubySanctum): Spell Scripts registry macros

deps/boost/CMakeLists.txt
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/ad96f1fd78f26a304e56c37495017d14aa34c9c0)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/66abca15933fcc6bfdd6dba71ee725da4e906af3)
- Closes 
========== Build: 3 succeeded, 0 failed, 16 up-to-date, 1 skipped ==========
Using Boost version:           1.85.0
1.
2.
3. …
=> chore(Deps/Boost): Cleanup pre-c++11 checks and silence CMake warning

src/server/game/Handlers/ChatHandler.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/19471
- Closes 
1.
2.
3. …
=> fix(Core/Chat): Exempt addon messages from CONFIG_CHAT_MUTE_FIRST_LOGIN

data/sql/updates/pending_db_world/rev_1720539450987942100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6602
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18408
https://www.wowhead.com/wotlk/item=20769/disgusting-oozeling#comments:id=10708
Checked on recycled by @heyitsbench 
(old timers, pre check on recycled)
https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/ae2a5c1e-dc22-416d-89df-35344fab9d69
.add 20769 
.add 11325 5 …
=> fix(DB/SAI): Disgusting Oozeling's Dark Iron Ale interaction

src/server/game/Handlers/AuctionHouseHandler.cpp, src/server/game/Handlers/ChatHandler.cpp, src/server/game/Handlers/MailHandler.cpp, src/server/game/Handlers/TicketHandler.cpp, src/server/game/Handlers/TradeHandler.cpp, src/server/game/Server/WorldSession.cpp, src/server/game/Server/WorldSession.h
* Make SendNotification use `fmt`
* Make SendNotification parse acore_string entries
- Fixes issues like players that are muted showing `You must wait {} before speaking again`
- Issue initially caused by https://github.com/azerothcore/azerothcore-wotlk/commit/3fbded8f6bdaae1ec6897dae34afdab36b124899
1.
2.
3. …
=> refactor(Core/WorldSession): Make SendNotification use `fmt` and parse acore_string

src/server/game/Achievements/AchievementMgr.cpp
-  [X] Core (Game systems).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19500 …
=> fix(Core/AchievementMgr): Check for null achievement before being derefenced.

src/server/game/Movement/MotionMaster.cpp, src/server/game/Movement/MotionMaster.h, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h, src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
1. .go c id 21212
2. bring Vashj to 2nd phase
3. observe movement speed of Enchanted Elementals …
=> fix (Core/Movement) Allow MoveFollow to not inherit walkstate of the target to fix Enchanted Elemental speed

apps/docker/Dockerfile
- Dockerfile
Docker Compose version 2.28.1 complains about `FromAsCasing` like this:
```
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 42)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 168)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 191)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 216)
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 238)
```
This is just fixing it :)
1. `docker compose build`
2. See no warnings …
=> fix docker warning about "FromAsCasing"

data/sql/updates/pending_db_world/rev_1722290115671857500.sql, src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7235
- Closes https://github.com/chromiecraft/chromiecraft/issues/7236
1.
2.
3. …
=> fix(Scripts/BlackTemple): Mother Shahraz Taunt Immunity and Enrage cancelling

data/sql/updates/pending_db_world/rev_1722303292918945800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7155
1.
2.
3. …
=> fix(DB/Spells): Acidic Wounds

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7159
1.
2.
3. …
=> fix(Scripts/BlackTemple): Mother Shahraz Periodic Beams

data/sql/updates/pending_db_world/rev_1722307588789038000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7222
1.
2.
3. …
=> fix(DB/Creature): Remove Essence of Desire interrupt immunity

src/server/game/Chat/Chat.cpp, src/server/game/Chat/Chat.h
* WorldText should be sent to all sessions
- Closes 
1.
2.
3. …
=> fix(Core/World): Crash on SendWorldText(Optional)

src/server/scripts/Outland/BlackTemple/boss_bloodboil.cpp
=> chore(Scripts/BlackTemple): Move Gurtogg Bloodboil to TaskScheduler

src/server/game/Handlers/GroupHandler.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6211
This PR:
1. Have one character step inside an instance.
2. Have another character set their dungeon difficulty to a different difficulty from that of the first character.
3. Have the second character invite the first. …
=> fix(Core/GroupHandler): Remove bad party invite check.

src/common/Threading/MPSCQueue.h, src/tools/vmap4_extractor/dbcfile.cpp
=> fix(Core/Common): add missing import

data/sql/updates/pending_db_world/air-burst-script.sql, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_archimonde.cpp
-  [X] Scripts (bosses, spell scripts).
1. Engage Archimonde in Hyjal Summit, both with one character and multiple.
2. Make sure Air Burst does not target the main threat target.
3. Make sure Air Burst does not get cast when engaged solo. …
=> fix(Scripts/HyjalSummit): Adjust Air Burst cast targetting.

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7242
1.
2.
3. …
=> fix(Scripts/BlackTemple): Mother Shahraz should not use frenzy

data/sql/updates/pending_db_world/archi-taunt.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7258
This PR: …
=> fix(DB/Creature): Add taunt immunity to Archimonde.

data/sql/updates/pending_db_world/rev_1722817302187444800.sql, src/server/scripts/Commands/cs_modify.cpp
Something I was toying around with.
There's also the Mount() method but I prefer using displayids instead
- Closes 
1. mount up
2. .morph mount 92
3. …
=> feat(Scripts/Commands): Morph Mount

data/sql/updates/pending_db_world/ethereum-redux.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19553
This PR: …
=> fix(DB/Loot): Update uncommon drops for Ethereum prisoner creatures.

src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/boss_anetheron.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7061
1.
2.
3. …
=> fix(Scripts/Hyjal): Anetheron dont sleep main tank

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7241
1.
2.
3. …
=> fix(Scripts/BlackTemple): Mother Shahraz Periodic part 2

data/sql/updates/pending_db_world/black-temple-values.sql
=> fix(DB/Creature): Adjust various values of Black Temple creatures.

src/server/scripts/Outland/zone_shadowmoon_valley.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19568
1.
2.
3. …
=> fix(Scripts/ShadowmoonValley): Dragonmaw Races Reset

src/server/shared/Network/Socket.h
Nodiscard flag is used to indicate that the return value of a function should be used. But here, we don't reuse the result of AsyncProcessQueue() (and it's not necessary).
- Closes two compilator warnings : 
\azerothcore-wotlk\src\server\shared\Network\Socket.h(147,26): warning C4834: discarding return value of function with [[nodiscard]] attribute
\azerothcore-wotlk\src\server\shared\Network\Socket.h(344,34): warning C4834: discarding return value of function with [[nodiscard]] attribute
1. Just build and look output …
=> fix(Shared/Socket): incorrect nodiscard flag

src/server/game/Spells/SpellInfo.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18042
- Closes https://github.com/chromiecraft/chromiecraft/issues/6391
- Closes https://github.com/chromiecraft/chromiecraft/issues/7263 …
=> fix(Core/SpellInfo): Disallow damage scaling trigger spells to get scaled twice.

src/server/game/Spells/SpellEffects.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19514
- Closes https://github.com/chromiecraft/chromiecraft/issues/6583
1. Observe summoned guardians follow target.
2. Confirm that they are correct. …
=> fix(Core/Spells): Adjust ownership and follow logic for guardian summons.

src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Spells/Spell.cpp, src/server/game/Spells/SpellDefines.h
Fixes the missing animation when clicking a ritual portal.
- Ritual of Summoning - 698
- Ritual of Souls (Rank 1) - 29893
- Ritual of Souls (Rank 2) - 58887
- Ritual of Doom - 18540
- Ritual of Refreshment (Rank 1) - 43987
- Ritual of Refreshment (Rank 2) - 58659
- #16101 
- #17012 
- https://github.com/chromiecraft/chromiecraft/issues/5346
- https://github.com/chromiecraft/chromiecraft/issues/5511
- (not cherry pick) https://github.com/cmangos/mangos-wotlk/commit/6eaef417163174ffa2f6e4943ded4b11784fa62d
1.
2.
3.
When a PR is ready to be tested, it will …
=> fix(Core): Ritual animations

src/server/game/Spells/Spell.cpp
https://github.com/cmangos/mangos-wotlk/commit/762f78b313cff195aadc0aab4b4ab9eaf2957892
- Closes #5603 
- https://github.com/cmangos/mangos-wotlk/commit/762f78b313cff195aadc0aab4b4ab9eaf2957892 
1.
2.
3. …
=> fix(Core/Spell) Ritual spells cooldown on cancel

data/sql/updates/pending_db_world/rev_1723569725185190500.sql, src/server/game/Entities/Creature/GossipDef.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Globals/ObjectMgr.h, src/server/game/World/World.cpp, src/server/scripts/Commands/cs_reload.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/14845
More than two years after I implemented this I feel like it's time to fix the locale table KEK
- Closes 
1. .go c id 341
2. .q add 345
3. Open gossip and see that it shows …
=> fix(Core/Creature): quest_greeting_locale

apps/Fmt/FormatReplace.py, src/server/game/Battlegrounds/BattlegroundQueue.cpp, src/server/game/Spells/Auras/SpellAuras.cpp, src/server/game/Spells/Spell.cpp, src/server/game/Spells/SpellScript.cpp, src/server/game/Tickets/TicketMgr.cpp, src/server/scripts/Commands/PlayerCommand.cpp, src/server/scripts/Commands/cs_account.cpp, src/server/scripts/Commands/cs_bag.cpp, src/server/scripts/Commands/cs_ban.cpp, src/server/scripts/Commands/cs_character.cpp, src/server/scripts/Commands/cs_debug.cpp, src/server/scripts/Commands/cs_inventory.cpp, src/server/scripts/Commands/cs_lookup.cpp, src/server/scripts/Commands/cs_message.cpp, src/server/scripts/Commands/cs_misc.cpp, src/server/scripts/Commands/cs_mmaps.cpp, src/server/scripts/Commands/cs_modify.cpp, src/server/scripts/Commands/cs_npc.cpp, src/server/scripts/Commands/cs_quest.cpp, src/server/scripts/Commands/cs_tele.cpp
Reverts azerothcore/azerothcore-wotlk#19619
=> Revert "chore(Script/Misc): cleanup"

src/server/game/AI/CoreAI/PetAI.cpp, src/server/game/Entities/Pet/Pet.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Unit/CharmInfo.cpp, src/server/game/Entities/Unit/CharmInfo.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/Spell.cpp
- Closes https://gist.github.com/Nyeriah/73aef2d205cc529795bc2ff319e30e5d
Test done : 
* Pet combat (Hunter/Warlock) by using various spells with cooldown
* Creature charm control with spell priest (605)
* Player charm control in duel
* Charm situation in BWL with the first boss
1. Test various situation with charm system and try to get spells to use
2. Look if you get a crash …
=> fix(Core/Entities): crash fix cause by a pointer change in #19622

src/server/game/Entities/Player/PlayerUpdates.cpp
- Closes 
1. Just compile and look if you see a warning …
=> fix(Core/PlayerUpdates): incorrect backslash in a debug_log

data/sql/updates/pending_db_world/rev_1723822265566661700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7281
1.
2.
3. …
=> fix(DB/Creature): High Nethermancer Zerevor taunt & interrupt immunity

data/sql/updates/pending_db_world/rev_1723769203579692900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7247
1.
2.
3. …
=> fix(DB/Creature): Gathios the Shatterer taunt immunity

data/sql/updates/pending_db_world/rev_1723780227197753900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7256
1.
2.
3. …
=> fix(DB/Creature): Remove Veras Darkshadow stun immunity

apps/docker/Dockerfile
Almost entirely format changes to the Dockerfile to resolve warnings when building
- Closes 
1.
2.
3. …
=> apps(docker): Fix Warnings in Dockerfile

src/server/game/Spells/Spell.cpp
=> fix(Core/Spell): check for player before dereferencing

src/server/scripts/Outland/BlackTemple/illidari_council.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7249
1.
2.
3. …
=> fix(Scripts/BlackTemple): Gathios Judgment spell should consume seals

src/server/game/Entities/Creature/GossipDef.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/19659
- Closes 
1.
2.
3. …
=> fix(Core/Creature): Nullcheck for questgreeting greeting

src/common/Utilities/StartProcess.cpp
Since version 1.81, boost process is being rewritten in a v2 version. Old elements have been moved to boost/process/v1/. This PR uses header file "boost/process.hpp", which correctly redirects header files depending of the version, and removes the build warning about these changes (at least in the newer version: 1.86).
this doesn't mean you can't be careful with future versions, as they'll end up deleting "boost/process/v1".
- Closes 
1. Just compile and look if it's succeeded …
=> fix(Dep/Boost): corrects a warning about path changes in boost process

src/server/game/Maps/MapMgr.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6915
1.
2.
3. …
=> fix(Core/Map): Exempt raids from the hourly limit

data/sql/updates/pending_db_world/rev_1723619543080521000.sql
* Add drain mana spell (cast only if the mana creture is below 75 %) 
* Correct timers from live server estimations
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19609 and https://github.com/chromiecraft/chromiecraft/issues/6310#issue-1988941516
1. .go creature 77787
2. Check that 'Tail swap" and 'Drain Mana' are cast (for mana main you should use Mana burn spells ( ), otherwise it will never cast) …
=> fix(DB/SAI): Aether Ray spells and timers

src/server/game/AI/CoreAI/PassiveAI.cpp, src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/Entities/Unit/Unit.h, src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/hyjal.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp
=> refactor(Core/Misc): Use NpcFlag helpers

data/sql/updates/pending_db_world/rev_1723613411731670300.sql
* add Terrifying Roar spell
* fix timers for Flame breath from live server estimations 
* fix the incorrect 'Devour' cast condition (currently cast when the creature as less than 20% Health instead of Target check)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19610 and https://github.com/chromiecraft/chromiecraft/issues/6316#issue-1989385964
1. .go creature 100869 or 100870 (if not spawn use .npc add 18692)
2. check that the creature cast 'Flame breath' and 'Terrifying Roar' …
=> fix(DB/SAI): Hemathion spells and timers

data/sql/updates/pending_db_world/rev_1723778762924716800.sql, src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
* Fix it not being cast if no valid targets are available
* Apply Patch 2.2 nerfs
- Closes https://github.com/chromiecraft/chromiecraft/issues/7239
- Closes https://github.com/chromiecraft/chromiecraft/issues/7245
1.
2.
3. …
=> fix(Scripts/BlackTemple): Fatal Attraction

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19616
- Closes https://github.com/chromiecraft/chromiecraft/issues/7255#issue-2446586452
1.
2.
3. …
=> fix(Core/Spells): Power of the Guardian should persist through death

src/server/game/Scripting/ScriptMgr.cpp
- Help for https://github.com/azerothcore/azerothcore-wotlk/issues/19635
* Test after 2min played with .server shutdown 5
* Test in an instance to force a loading script before to do: .server shutdown 5
1. Shutdown down the server in various situations with : .server shutdown 5 …
=> chore(Debug/Scripting): improve debug errors during the unloading scripts

data/sql/updates/pending_db_world/rev_1722804930814975200.sql
- Closes #19572
1. Accept the quest
2. use the flute on the rats
3. turn in the quest if you catched 5 …
=> fix(DB/Quest): deeprun rat roundup

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Spells/SpellInfo.cpp, src/server/game/Spells/SpellInfo.h
Happens if the aura has effects with MECHANIC_SNARE but the spell itself doesn't have that mechanic.
Fixes the gnome racial not removing some auras e.g kazrogal cripple
- Closes https://github.com/chromiecraft/chromiecraft/issues/6994
1.
2.
3. …
=> fix(Core/Spells): Fix movement impairment auras not being removed

src/server/game/Spells/Spell.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7300
1.
2.
3. …
=> fix (Core/Spells) partially revert #19529

apps/installer/includes/os_configs/debian.sh
- showing some love for the good old `acore.sh` installer
- Progress #19451
1.
2.
3. …
=> fix(apps/installer): update for Debian 12 using mysql

src/server/scripts/Outland/BlackTemple/illidari_council.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19667
- Closes https://github.com/chromiecraft/chromiecraft/issues/7280
- Closes https://github.com/chromiecraft/chromiecraft/issues/7261
- Closes https://github.com/chromiecraft/chromiecraft/issues/7250
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19685 …
=> fix(Scripts/BlackTemple) Gathios the Shatterer shouldnt use the same spell twice in a row

data/sql/updates/pending_db_world/gossip_8934.sql
fix(DB/Gossip): adds missing gossip for Recover the Cargo! author [ZenoX92 ](https://github.com/TrinityCore/TrinityCore/issues/22242)from TrinityCore
- Progress #8934 …
=> fix(DB/RP): Add missing RP for Recover the Cargo!

src/server/game/AI/ScriptedAI/ScriptedCreature.h, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
=> refactor(Scripts/TempleOfAhnQiraj): Clean up Cthun script

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp
=> refactor(Scripts/RuinsOfAhnQiraj): Clean up Ayamiss script

data/sql/updates/pending_db_world/rev_1724552482874297000.sql
Increasing NPC conversations when idle are triggered every 6 minutes. I waited in the game for about 20 minutes and the text content of the dialogue seemed to be sequential and not randomly triggered. 
- Closes 
1. go c 4080
2. wait
3. …
=> fix(DB/Creature): Added dialogue for the mob "Pilot Bellowfiz" (1378) when idle

apps/installer/includes/os_configs/ubuntu.sh
=> fix(apps/installer): update for Ubuntu 22.04/24.04 with mysql 8.4 LTS

data/sql/updates/pending_db_world/illidan-class.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7313
This PR: …
=> fix(DB/Creature): Adjust Illidan Stormrage's class.

src/server/game/Spells/SpellMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17235
- Closes https://github.com/chromiecraft/chromiecraft/issues/4815 …
=> fix(Core/SpellMgr): Remove binary attribute from Drain Soul.

data/sql/updates/pending_db_world/illidari-empyreal-balance.sql, src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
1. Engage Illidari Council in Black Temple.
2. Damage one member.
3. Ensure health is properly balanced. …
=> fix(Scripts/BlackTemple): Improve Illidari Council Empyreal Balance.

data/sql/updates/pending_db_world/rev_1724764338252798941.sql, src/server/scripts/Spells/spell_generic.cpp
handle General's Heart trinket the same as these other 2 with `spell_gen_absorb0_hitlimit1`
Argussian Compass https://wowgaming.altervista.org/aowow/?spell=39228
Essence of Gossamer https://wowgaming.altervista.org/aowow/?spell=60218
The General's Heart https://wowgaming.altervista.org/aowow/?spell=64765
encapsulate limit variable
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3544
1.
2.
3. …
=> fix(Scripts/Spells): General's Heart trinket

data/sql/updates/pending_db_world/rev_1724722289062405500.sql, src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7306
1.
2.
3. …
=> fix(Scripts/Spells): L1 Arcane Charge should hit 3 targets

src/server/scripts/Commands/cs_misc.cpp
Allows dealing a percentage of the target's max health as damage.
Helps debugging health checks.
- Closes 
1.
2.
3. …
=> feat(Scripts/Commands): Implement "pct" optional to the damage command

data/sql/updates/pending_db_world/rev_1724552033443919200.sql
Added combat AI for mobs. Entering a fight, receiving the first attack, having less than a certain amount of health, and killing the player can speak
- Closes 
1. .go c 112637
2. Attack it
3. Mobs should speak when entering combat, receiving their first attack, getting below %80 and %60 health, dying, and killing the player. And spells are used in battle. and the occasional comatose player …
=> fix(DB/Creature): Added SmartAi to the creature "Warlord Zim'bo" (26544).

src/server/game/Entities/Creature/Creature.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/5277 …
=> fix(Core/Creature): Fix grace period for can attack check.

src/server/game/Spells/SpellMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/19760#discussion_r1733342359
This PR: …
=> refactor(Core/SpellMgr): Remove nested ifs for binary evaluation.

data/sql/updates/pending_db_world/2024_08_25_01.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/5655
1.
2.
3. …
=> fix(DB/Creature): Quest Therylune's Escape - party completion issue

data/sql/updates/pending_db_world/2024_08_23_00.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10840 …
=> fix(DB/Creature):Quest Precarious Predicament does not complete

src/server/game/AI/CoreAI/UnitAI.cpp, src/server/game/AI/CoreAI/UnitAI.h, src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Movement/MotionMaster.cpp
* focus mainly for dev script usage, I've improve the documentation of many common functions
* Also revamp some comments and few variable names here and there
- Closes 
- Any review, comments or help to improve this PR is welcome …
=> docs(Core): improve several functions documentation

data/sql/updates/db_world/2024_08_28_03.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19771
1.
2.
3. …
=> chore(SQL): Collision in 2024_08_28_03.sql

data/sql/updates/pending_db_world/promenade-running.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7308
This PR: …
=> fix(DB/Waypoints): Set Promenade Sentinels to walk their paths.

data/sql/updates/pending_db_world/rev_1724894325123537700.sql
- Closes 
1. Download the branch with the changes
2. Test translations with different clients …
=> fix(GossipMenu) Dalaran guide guards

data/sql/updates/pending_db_world/promenade-speed.sql
=> fix(DB/Creature): Correct Promenade Sentinel speed.

src/server/apps/worldserver/worldserver.conf.dist
=> fix(Conf): drop unused options from worldserver.conf.dist

src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7315
The changes: …
=> fix(Scripts/BlackTemple): Call evade for Council creature when members evade.

src/server/game/Entities/Unit/CharmInfo.cpp, src/server/game/Entities/Unit/CharmInfo.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16047 …
=> fix(Core/CharmInfo): Respect charm spell indices when adding to action bar.

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp, src/server/game/AI/ScriptedAI/ScriptedCreature.h
initialize in the constructor class but never used anywhere else
- Closes 
1.
2.
3. …
=> fix(Core/AI): remove an unused variable in ScriptedAI

data/sql/updates/pending_db_world/2024_08_31_01.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19765
Add new row for Banish spell and set the InitialMin, InitialMax, RepeatMin, and RepeatMax parameters for the Greyheart Spellbinder casting behavior.
InitialMin: Set to 10 seconds.
InitialMax: Set to 30 seconds.
RepeatMin: Set to 10 seconds.
RepeatMax: Set to 30 seconds.
Chance: Set to 23% per interval.
Analyzed logs from 28 randomly selected fights (from this link: https://classic.warcraftlogs.com/zone/reports?zone=1010&boss=625&difficulty=0&class=Any&spec=Any&keystone=0&kills=0&durat …
=> fix(DB/Creature) SSC - Greyheart Spellbinder miss Banish ability

data/sql/updates/pending_db_world/2024_08_31_02.sql, src/server/game/Globals/ObjectMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19721
1.
2.
3. …
=> fix(DB/Item): Feathermoon Headdress has the wrong stats

.github/workflows/codestyle.yml, src/CMakeLists.txt
- fix warning in CI workflow
- Closes 
1.
2.
3. …
=> fix(CI/codestyle): bump dependencies for Node.js 20

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7158
1.
2.
3. …
=> fix(Scripts/BlackTemple): Fix Mother Shahraz teleport

src/server/game/Achievements/AchievementMgr.cpp, src/server/game/Achievements/AchievementMgr.h, src/server/game/Entities/Item/ItemTemplate.h, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp, src/server/scripts/Spells/spell_generic.cpp, src/server/shared/SharedDefines.h, src/server/shared/enuminfo_SharedDefines.cpp
=> refactor(Core): Correct typo.

apps/codestyle/codestyle.py, src/server/game/Entities/Creature/CreatureData.h, src/server/game/Entities/Item/Item.cpp, src/server/game/Entities/Item/Item.h, src/server/game/Entities/Item/ItemTemplate.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Groups/Group.cpp, src/server/game/Handlers/AuctionHouseHandler.cpp, src/server/game/Handlers/ItemHandler.cpp, src/server/game/Handlers/LootHandler.cpp, src/server/game/Handlers/MailHandler.cpp, src/server/game/Handlers/SpellHandler.cpp, src/server/game/Handlers/TradeHandler.cpp, src/server/game/Loot/LootItemStorage.cpp, src/server/game/Loot/LootMgr.cpp, src/server/game/Spells/Spell.cpp, src/server/game/Spells/SpellEffects.cpp
* ItemTemplate
* Added: 
* HasFlag(ItemFlags flag) 
* HasFlag2(ItemFlags2 flag) 
* HasFlagCu(ItemFlagsCustom flag)
* Removed
* enum ItemFlagsExtra - Use already existing enum ItemFlag2
* Item
* Added: 
* IsRefundable() 
* IsBOPTradable() 
* IsWrapped()
- Probably progresses https://github.com/azerothcore/azerothcore-wotlk/issues/19030 or might even close it. Not tested
1.
2.
3. …
=> refactor(Core/Item): Add helpers

src/server/game/Guilds/Guild.cpp
=> fix(Core/Guild): Require repair rights in order to make use of guild repairs.

data/sql/updates/pending_db_world/rev_1725143233684093900.sql
>ServerToClient: SMSG_UPDATE_OBJECT (0x27C5) LENGTH: 824 ConnIdx: 1 TIME: 08/31/2024 19:06:25.564 NUMBER: 2500
[0] UpdateType: CreateObject2
[0] Object Guid: FULL: Creature/0  Map: 564 Entry: 23429 Low: 
[0] Flags: 33554432
[0] Flags2: 2048
[0] Flags3: 524289
- Closes https://github.com/chromiecraft/chromiecraft/issues/7307
1.
2.
3. …
=> fix(DB/Creature): Fix unit flags for Arcane Charge trigger npc

src/server/game/Entities/GameObject/GameObject.cpp
Once a player is offline they can no longer be found in the map's `HashMapHolder` and causes the original check to fail
https://github.com/azerothcore/azerothcore-wotlk/blob/40eb616e1f576de3fd3ca215fc1250ee06953ce8/src/server/game/Globals/ObjectAccessor.cpp#L250
Instead, lookup the ownerGUID of the portal in the user's group. If present then succeed
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16291
1.
2.
3. …
=> fix(Core/GameObject): Allow use of Mage portal if caster is offline and still in group

src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19715
warrior lvl70+
1. `.add 31858`
2. swap stances
3. observe no damage …
=> fix(Core/Spell): warrior stances proccing darkmoon card vengeance damage

data/sql/updates/pending_db_world/shadowy-construct-speed.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19815
- Closes https://github.com/chromiecraft/chromiecraft/issues/7322
- Credit entirely goes to CMaNGOS. I know the change was made in its SVN days, but I could not find the change whatsoever in the existing SVN repository, I apologize for not being able to track it down.
This PR: …
=> fix(DB/Creature): Adjust Shadowy Construct run speed.

data/sql/updates/pending_db_world/molten-flame-stack.sql
=> fix(DB/Spell): Don't allow Molten Flame damage to stack from multiple spawns.

src/server/game/Entities/GameObject/GameObject.cpp
oops, I broke portals in https://github.com/azerothcore/azerothcore-wotlk/pull/19797
- Closes 
1.
2.
3. …
=> fix(Core/GameObject): fixup allow use of Mage portal if caster is offline and still in group

data/sql/updates/pending_db_world/2024_09_01_00.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19843
- Closes https://github.com/chromiecraft/chromiecraft/issues/6491 …
=> fix(DB/Creature): Steamvault - Coilfang Oracle casts Frostshock twice

src/server/game/Entities/Item/ItemEnchantmentMgr.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/ItemHandler.cpp, src/server/game/Handlers/NPCHandler.cpp, src/server/game/Spells/Spell.cpp, src/server/game/Time/UpdateTime.cpp, src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp, src/server/scripts/Northrend/zone_wintergrasp.cpp, src/server/scripts/Spells/spell_generic.cpp
=> chore(Core/Misc): update floor and ceil to std

src/server/apps/worldserver/Main.cpp, src/server/apps/worldserver/worldserver.conf.dist, src/server/database/Database/DatabaseLoader.h, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Time/UpdateTime.cpp, src/server/game/World/World.cpp
- default values in core and config should always be the same
- some default values have been different in config and core since the very first commit of AC
- cleanup some redundancy
- Closes 
- the visibility distances were updated with #9180 in the core but never made it into the config file, so these might need some testing / feedback
1.
2.
3. …
=> fix(Conf): sync default values with core defaults

apps/codestyle/codestyle.py, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/SocialMgr.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Movement/Spline/Spline.cpp, src/server/game/Warden/Warden.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/blackrock_depths.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_solakar_flamewreath.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp, src/server/scripts/Kalimdor/DireMaul/instance_dire_maul.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp, src/server/scripts/Northrend/Naxxramas/boss_gluth.cpp, src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp, src/server/scripts/Northrend/Naxxramas/boss_heigan.cpp, src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp, src/server/scripts/Spells/spell_hunter.cpp, src/server/shared/Packets/ByteBuffer.h
* New codestyle for Class/ObjectType const* and auto const& syntax
- Closes 
1.
2.
3. …
=> chore(Apps/Codestyle): add new codestyle checks for pointers and range loops

src/server/game/Battlegrounds/Arena.cpp, src/server/game/Scripting/ScriptDefines/ArenaScript.cpp, src/server/game/Scripting/ScriptDefines/ArenaScript.h, src/server/game/Scripting/ScriptMgr.h
mod-arena-replay updated code here: https://github.com/azerothcore/mod-arena-replay/pull/1
thanks @Romain-P, main author of the module
mantainers @laasker, @thomasjteachey
- remove patch from [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay/pull/1) adding `OnBeforeArenaCheckWinConditions` hook 
1. Do an arena 2v2 without the mod-arena-replay
2. [install mod-arena-replay](https://github.com/azerothcore/mod-arena-replay/pull/1) and do an arena 2v2 
3. check the replay to see if it works
You can …
=> feat(Scripting): add OnBeforeArenaCheckWinConditions hook for mod-arena-replay compatibility

src/common/Collision/Management/MMapMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19865
1.
2.
3. …
=> Fix(Core/Misc): Acore::StringFormat to fmt format

apps/docker/Dockerfile, src/tools/CMakeLists.txt, src/tools/dbimport/Main.cpp, src/tools/dbimport/dbimport.conf.dist
-  [X] Apps(Docker)
Related issues:
* https://github.com/azerothcore/azerothcore-wotlk/issues/18965
* https://github.com/azerothcore/azerothcore-wotlk/pull/16155
Support dicussion: 
https://discord.com/channels/217589275766685707/1280317898140680307
- Closes #18965
1. Install using docker instructions
2. Add a module that has sql in it mod-guildhouse as an example
3. Enabled confgiruation options in dbimport.conf.    Updates.AllowedModules to either "all" or the name of the module you are testing with. 
4. Validate in dbimport container start logging …
=> Fix(docker) Modules SQL do not get updated or populated for docker set ups

src/server/game/Entities/Unit/Unit.cpp
- Progresses https://github.com/chromiecraft/chromiecraft/issues/7342
The changes:
This PR: …
=> fix(Entities/Unit): Add leash extension with damage dealt.

src/server/scripts/Commands/cs_misc.cpp
=> fix(Scripts/Commands): .gps formatting transport offset

src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp
=> fix(Core/AI): Creature SetInCombatState Leashing.

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
=> fix(Scripts/BlackTemple): blade_of_azzinoth...and Possible crash

.gitignore, src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
Initialize a parameter that is used without initialization to avoid uncertainty in the script's execution logic, fixing the boss sometimes can not work.
- Closes 
https://github.com/azerothcore/azerothcore-wotlk/pull/19010
1.
2.
3. …
=> fix(Scripts/ZulAman): Nalorakk sometimes not move when player close

src/server/game/Entities/Unit/Unit.cpp
- This PR specifically targets an issue causing certain spells (namely mage's Blizzard) not to extend a creature's leash.
1. Engage mobs.
2. Observe their leashing behavior.
3. Make sure it matches official servers. …
=> fix(Core/AI): Add back leash update.

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
- Progresses leashing issues.
- https://github.com/vmangos/core/commit/c8510cbbd4dccbdac9900cc507910ef3ae0e6c43 authored by [ratkosrb](https://github.com/ratkosrb).
This PR:
1. Engage mobs.
2. Observe their leash behavior. …
=> fix(Core/AI): Initialize movement leash timer to five seconds.

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
=> fix(Core/AI): creature leashing behavior.

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
- Progresses leashing issue.
1. Engage mobs.
2. A lot of mobs.
3. Ensure they don't prematurely leash too much. …
=> fix(Core/AI): Reduce movement leash extension interval.

src/server/game/Entities/Creature/TemporarySummon.cpp, src/server/game/Spells/SpellEffects.cpp
Check SummonProperties Category(Control) too to decide the type of controls a Guardian should have.
Don't enslave Warlock's Infernal.
- Closes #19783
1.
2.
3. …
=> fix(Core/Pet): Control Infernal without enslave

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_drakkisath.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19805
- see linked issue
- collect further confirmation on the intended cooldown/interval
=> fix(Scripts/UBRS): increase Drakkisath's conflagrate interval from 10s..13s to 18s..25s, avoiding near infinite CC chains

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Spells/Spell.cpp
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/13330 …
=> fix(Core/Spells): Resolve a case of triggered spells prolonging combat.

src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
* Timer start: 15s
* UpdateAI timers: between 16s and 20s
- Closes https://github.com/chromiecraft/chromiecraft/issues/7261
1.
2.
3. …
=> fix(Scripts/BlackTemple): Ajust Judgment timers and pass all the script to std::chrono

src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
*one left over from the dev of my last PR, which was not used in the end (and is useless)
- Closes 
1.
2.
3. …
=> refactor(Scripts/TempestKeep): remove an dev residual from Kael'Thas revamp

src/server/game/Scripting/ScriptMgr.cpp
* This pr was wrongly use
* null check isn't necessary: https://en.cppreference.com/w/cpp/memory/new/operator_delete
* in spite of jackpoz's derision in the ‘lobby’ channel of TC, this coment remains to be learned.
- Closes 
1.
2.
3. …
=> Revert "chore(Debug/Scripting): improve debug errors during the unloading scripts (#19643)"

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes partially https://github.com/azerothcore/azerothcore-wotlk/issues/19954
1.Pull boss
2. Get to phase 2 …
=> fix(Scripts/BlackTemple): fix blaze and flame bast casting for Flame of Azzinoth

src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19935 and https://github.com/chromiecraft/chromiecraft/issues/7352#issue-2513942144
1.
2.
3. …
=> fix(Scripts/BlackTemple): Shadow demon - Allow to move while casting Paralyze

src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
* wrong conversion from https://github.com/azerothcore/azerothcore-wotlk/commit/5ae1473e3064beb4adf666e33a38b6072639069a
- Closes 
1.
2.
3. …
=> fix(Scripts/BT): correct illidari council enrage timer

src/server/game/Handlers/CharacterHandler.cpp, src/server/scripts/Commands/cs_character.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19966
1.
2.
3. …
=> fix(Scripts/Commands): Fix level up achievements not being granted

data/sql/updates/pending_db_world/command-syntax.sql, src/server/scripts/Commands/cs_debug.cpp, src/server/scripts/Commands/cs_misc.cpp
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/18536
- Closes https://github.com/chromiecraft/chromiecraft/issues/6799
- Closes https://github.com/chromiecraft/chromiecraft/issues/6800
- Closes https://github.com/chromiecraft/chromiecraft/issues/6801
- Closes https://github.com/chromiecraft/chromiecraft/issues/6802
- Closes https://github.com/chromiecraft/chromiecraft/issues/6803
- Closes https://github.com/chromiecraft/chromiecraft/issues/6808 …
=> fix(DB/Command): Add help values for various commands.

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
* fix the distance logic (negative usage imply "at least")
* remove also a old duplicate check in a spell script
- Closes totally https://github.com/azerothcore/azerothcore-wotlk/issues/19954 and https://github.com/chromiecraft/chromiecraft/issues/7351#issue-2513928203
1. Pull boss
2. Get to phase 2 …
=> fix(Scripts/BlackTemple): Flames of Azzinoth - Fix the charge logic

apps/installer/includes/os_configs/debian.sh
- Debian default is mariadb
- therefore install library from mysql source repo
- Progress #19999 
1.
2.
3. …
=> fix(apps/installer): fix Debian 12 build with mysql

.github/SECURITY.md, .github/workflows/macos_build.yml, apps/ci/mac/ci-compile.sh, apps/installer/includes/os_configs/osx.sh
=> fix(CI/macOS): Fix macOS CI dependency installation by updating macOS version.

data/sql/updates/pending_db_world/rev_1725899053676428516.sql, src/server/scripts/Spells/spell_generic.cpp
Without a lance equipped the mounting icon is hidden for "Stabled Campaign Warhorse"
After unequipping, the lance the mounting icon is still visible. Clicking does nothing. No error is shown
This is inconsistent with other argent tournament mounts. This is the only tournament mount that handles the lance requirement with conditions.
This removes those conditions and let mounting be handled similar to the other tournament mounts
- Closes 
https://github.com/user-attachments/assets/e55824e5-0305-481a-ad0e-b78f4de0b22e
```
required quest
.quest add 13862 …
```
=> fix(DB/ArgentTournament): Stabled Campaign Warhorse missing error message

data/sql/updates/pending_db_world/2024_09_08_00.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19904
- Closes chromiecraft/chromiecraft#5784
I also changed drop rate of Netherweave Cloth (it was too high, it was 60%). Here are the changes:
Unyielding Footman
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1
Unyielding Sorcerer
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1
Unyielding Knight
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1
When …
=> fix(DB/Creature): [Loot] Unyielding mobs low drop of Runecloth

data/sql/updates/pending_db_world/txt_line_fix.sql, src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.h
(Instance:Pit of Saron) cleanup some duplicated txt lines and make use broadcast_text for localization support
(Instance:AzjolNerub) added ruRU creature_text localization for Anub'arak intro (because BroadcastTextId unknown)
- Closes 
1.
2.
3.
- [there is a lot of to do if it is acceptable to use Autoincremented GroupID for text lines for better script readability] …
=> (Pit of Saron, AzjolNerub) assign BroadcastTextId to creature_text

data/sql/updates/pending_db_world/rev_1723083294200919589.sql
Update the goblin and gnome engineering questlines to omit the deprecated/legacy "Pledge of Secrecy" quests.
- Closes #19575 
Specific sources listed in linked issue
Follow the steps provided in the linked issue, with one exception: Pledge of Secrecy should be entirely skipped now, going straight from the breadcrumb to Show Your Work. …
=> fix(DB/Quest) - Omit deprecated Pledge of Secrecy from Goblin and Gnome Engineering Questlines.

src/server/database/Database/MySQLConnection.cpp, src/server/database/Database/MySQLConnection.h
=> refactor(Core/Database): improve abort messages for mysql errors

data/sql/updates/pending_db_world/rev_1724384703130549345.sql
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/19651
- Closes chromiecraft/chromiecraft#7282
- https://www.wowhead.com/npc=20141/hound-of-culuthas#drops;0-20+17+1
- https://www.wowhead.com/npc=20394/eye-of-culuthas#drops;0-20+17+1
1. `.go creature id 20141`
2. `.damage 99999`
3.  Observe updated drop
None …
=> fix(DB/Creature Loot) - Update Eye and Hound Culuthas loot tables

src/server/game/Loot/LootMgr.cpp
=> fix(Core/Loot): Fix crash for round robin loot mode when solving quest item for offline loot owner.

src/server/game/Spells/Spell.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20018
- Closes https://github.com/chromiecraft/chromiecraft/issues/7008
1.
2.
3. …
=> fix(Core/Spells): Prevent aura application if the target is immune

data/sql/updates/pending_db_world/rev_1727190899998700700.sql
=> fix(DB/Creature): Fix Illidan walking to waypoints instead of flying

src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20040
1.
2.
3. …
=> fix(Scripts/Spells): Remove immunity application from Preparation buff

data/sql/updates/pending_db_world/2024_09_23_00.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19863
- Closes https://github.com/chromiecraft/chromiecraft/issues/6244 …
=> fix(DB/Creature): SSC - Leotheras the blind - Adds are not chained

data/sql/updates/pending_db_world/phantom-leotheras-flags.sql
=> fix(DB/Creature): Add proper unit flags to Phantom Leotheras.

data/sql/updates/pending_db_world/rev_1727182333854036800.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/19878
1. Set the WoW client to esES and speak with a guard of a city (Ex: Silvermoon), some texts have a missing spanish translation and are in english
2. Execute the script added to the PR and restart the server
3. Talk to the guard again and all texts are now in Spanish or the language of the game client you use. …
=> chore(DB/CreatureText) Translate text in city guards

data/sql/updates/pending_db_world/rev_1727516139226526128.sql
remove stun immunity so coilfang strider can be stunned
see https://github.com/azerothcore/azerothcore-wotlk/issues/20000#issuecomment-2363564195
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20000
see https://github.com/azerothcore/azerothcore-wotlk/issues/20000#issuecomment-2363564195
fear immune
`.cast 22663`
.npc add temp 22056
hoj 
.cast 853
add net
.setskill 197 300
.add 24268
1. use net
2. 
3. …
=> fix(DB/Creature): remove stun immunity from Coilfang Strider

data/sql/updates/pending_db_world/super-healing-extra.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19780
- Closes https://github.com/chromiecraft/chromiecraft/issues/5883
This PR:
**For …
=> fix(DB/Spells): Add extra craft chance for Super Healing Potion.

apps/codestyle/codestyle.py, src/server/scripts/Spells/spell_priest.cpp
- Follow https://github.com/azerothcore/azerothcore-wotlk/pull/19970/files
1.
2.
3. …
=> chore(Apps/Codestyle): add a new check for if statements

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
=> fix(CI/Codestyle): Fix codestyle CI error introduced with the new rule for ifs.

src/server/game/AI/CoreAI/GuardAI.cpp
[Crashlog](https://github.com/user-attachments/files/17180704/message-2.txt)
- Closes 
1.
2.
3. …
=> fix(Core/GuardAI): Fix crash that happens in GuardAI when killer is null.

data/sql/updates/pending_db_world/illidan-elemental-model.sql
=> fix(DB/Creature): Adjust Flame of Azzinoth model data.

data/sql/updates/pending_db_world/rev_1727647338172762248.sql
previous: icon is only visible when near to the ship
change: icon is visible from further away
- Closes 
related but no visibility change https://github.com/TrinityCore/TrinityCore/commit/4979cdee2e95009e9d43667504e4dfae11d07914
visibility is set to infinite was mentioned in  https://github.com/TrinityCore/TrinityCore/issues/6186#issuecomment-622102689
and is present in tc335 DB but no idea who made the original change to set visibility to infinite
1. .tele icecrown
2. open map
3. move closer and farther away …
=> fix(DB/Creature): Icecrown Orgrim's Hammer and The Skybreaker map icons

data/sql/updates/pending_db_world/factions_shade.sql, src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20067
- Closes https://github.com/chromiecraft/chromiecraft/issues/7385#issue-2554017193 …
=> fix(Scripts/TheBlackTemple): resetting behaviour in p1 for Shade of Akama

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20102 …
=> fix(Scripts/TheBlackTemple): remove gossip option on Akama when Illidan is dead

data/sql/updates/pending_db_world/boahn.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20051
- Closes https://github.com/chromiecraft/chromiecraft/issues/7380 …
=> fix(DB/WailingCaverns): make Boahn cast snake form

data/sql/updates/pending_db_world/bt-path-runners.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7353
This PR: …
=> fix(DB/Creature): Adjust move type of various Black Temple creatures.

src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7395
This PR: …
=> fix(Scripts/BlackTemple): Reset Illidan threat with phase four.

src/server/scripts/Northrend/zone_dragonblight.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/18751
1.
2.
3. …
=> fix(Scripts/Dragonblight): Fix Torturer Leclaft spamming abilities

src/server/scripts/Outland/BlackTemple/boss_mother_shahraz.cpp
This fix adds 5 new teleport points if the boss is near the platform.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20135#issue-2567813712
1. Tank the boss around the platform
2. Tank the boss around the waterfall
3. …
=> fix(Script/Mother Shahraz) Add new teleport points.

src/server/game/Entities/Unit/Unit.cpp
Co-authored by: stfxpi (stfx)
Original CMaNGOS commit: https://github.com/cmangos/mangos-tbc/commit/c750533b5ec7f688d7f026b18edd19acccd68f2f
- Closes https://github.com/chromiecraft/chromiecraft/issues/7401
- Authored by stfxpi (Also known as stfx), pushed to CMaNGOS with [this commit](https://github.com/cmangos/mangos-tbc/commit/c750533b5ec7f688d7f026b18edd19acccd68f2f). …
=> fix(Core/Unit): Add mana drain effect to Black Bow of the Betrayer.

src/server/game/AI/ScriptedAI/ScriptedCreature.cpp, src/server/game/AI/ScriptedAI/ScriptedCreature.h
Dont iterate through list every time
- Closes 
1.
2.
3. …
=> fix(Core/Scripts): Further improve the ScheduleHealthCheck() function

src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Death Knight Initiate (id: 28406) was not turning to face the player after they engaged a duel instead the npc followed the player wherever they went. 
- Closes #20108
1. Start the quest (ID: 12733)
2. Select an Npc to challenge.
3. Move in various directions 
i. Originally the npc would follow the player
ii. Now it should reset as if losing focus then immediately turn to face the player and stay in that position wherever the player moves …
=> fix(Script): Fix npc following player after starting duel

data/sql/updates/pending_db_world/whirling-blade-model.sql
=> fix(DB/Creature): Adjust model probability for Whirling Blade trigger creatures.

data/sql/updates/pending_db_world/rev_1728233546701933600.sql
- Closes https://github.com/AdonisWOW/bugtracker/issues/11
1. TP to the npc: `.go c 247567`
247567 - (entry: 14368) [Lorekeeper Lydros X:164.335 Y:522.497 Z:-48.3836 MapId:429]
2. Take quest 7482: `.quest add 7482`
3. Interact with the skeleton that is nearby
Having the wrong target, at least in Spanish (I don't know about other languages, the NPC can't recognize the player's gender and the dialogue is displayed incorrectly) …
=> fix(SQL/smart_scripts) target in script 1436800

src/server/game/Spells/SpellInfoCorrections.cpp
=> fix(Core/SpellInfoCorrections): Add Arcane Missiles spell info correction.

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Spells/Spell.cpp, src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
https://gist.github.com/Nefertumm/bac49134fa22cf6ca38a3d38669a64d5
Cherrypick: https://github.com/TrinityCore/TrinityCore/commit/5e284d4b3826cd345193298688c1d2bc5b3c8f72 https://github.com/TrinityCore/TrinityCore/commit/514c847881a9fff504e90f1186a1209c0b8a3674
1. Unsure.- But something about akama resetting a spellevent that it shouldn't.
2.
3. …
=> fix(Core/Spells): Fix crash

src/server/scripts/Outland/BlackTemple/boss_supremus.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20167
- Closes https://github.com/chromiecraft/chromiecraft/issues/7409 …
=> fix(Scripts/BlackTemple): Adjust cast behavior for Supremus's charge.
