azerothcore/azerothcore-wotlk

- data/sql/updates/pending_db_world/gorefiend-model-data.sql
> fix(DB/Creature): Adjust Teron Gorefiend's model data.

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
> fix(Scripts/BlackTemple): Ensure root state is cleared on wipes

- data/sql/updates/pending_db_world/rev_1728239921994699100.sql
Dark Rider of Acherus (id: 28768) was missing some on death scripting that controled the deathcharger (id: 28782). Use smart ai to make the deathcharger rooted in place, emote a message, remove not selectable unitflag to allow player to mount and apply 100% health to ensure deathcharger isn't at 50% health.
Added the emote text to creature_text table for deathcharger.
Added NON_ATTACKABLE and NOT_SELECTABLE unitflags to deathcharger.
Added SmartAI script to deathcharger, so that when a passenger enters the horse unroots.
- Closes #20107 
Wotlk classic video of the quest: …
> Fix(DB/SAI) Into The realm of Shadows issues

- data/sql/updates/pending_db_world/shandy-fix.sql
Makes Shandy say his for a Suitable Disguise in the correct order
Order of dialogues was mixed up, causing issues such as the quest seeming like it had failed (ie. Sandy said the failure dialogue) despite the fact that there's no scripted failure event in the underlying cpp script, or asking for shirts instead of saying the second half of the scripted intro RP
- Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/744
https://www.youtube.com/watch?v=DHmeKq9t5Z0
1. .quest add 24556 (horde) or .quest add 20438 (ally)
2. .go creature 1790
3. …
> fix(DB/Creature): update Shandy's creature_text

- src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
> fix(Scripts/BlackTemple): Grant proper encounter credit for Illidari Council.

- src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7421
1.
2.
3. …
> fix(Scripts/BlackTemple): Fix Gathios not recasting Consecration

- data/sql/updates/pending_db_world/rev_1728859739562034100.sql
The damage they take comes from the trigger
- Closes 
1.
2.
3. …
> fix(DB/Creature): Illidari Council skip player damage req

- data/sql/updates/pending_db_world/rev_1728850639076317100.sql
Jenny's Whistle requires player to be near crashed flying machines, of which there are 6 total. This fix adds the other 3.
Closes AzerothCore issue #20196
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20196 …
> fix(DB): Missing additional crashed flying machines gameobjects

- data/sql/updates/pending_db_world/Kitrik_wp.sql
> fix(DB): Fix importer part 2

- apps/ci/ci-pending-sql.sh
The index for today will still be broken, but I'm pretty sure that's not a big deal.
- Closes 
1.
2.
3. …
> fix(CI/Import SQL): reference previous pending update in header

- data/sql/updates/pending_db_world/rev_1729021118457928000.sql
- Progress #18520
`.tele kamagua` …
> fix(DB/Creature): Sniffed Values for 'Oomailiq' spawns

- src/server/game/Entities/Unit/Unit.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20203
1.
2.
3. …
> fix(Core/Items): Don't remove all owned auras on removing enchantments.

- deps/g3dlite/source/CollisionDetection.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfoCorrections.cpp
- src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_murmur.cpp
- src/server/scripts/Spells/spell_druid.cpp
- src/server/shared/SharedDefines.h
- src/server/shared/enuminfo_SharedDefines.cpp
> chore(Core): Correct typo of `Suppress`.

- src/server/game/Entities/Unit/CharmInfo.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20149 …
> fix(Core/CharmInfo): Adjust how spells are given to charmed creatures.

- data/sql/updates/pending_db_world/rev_1729280864308751500.sql
- Closes #19817
- Closes chromiecraft/chromiecraft#7040
```
.q a 9910
.go ga 22716
.go ga 22717
.go ga 22719
.go c id 18300
.mod rep 941 1000
hand in quest
``` …
> fix(DB/Quest): fix Standards and Practices Quest spawns

- .github/README.md
- fix core-modules-build status and link
- use common structure for all images and links
- add pch-build
- add tools-build
- Closes 
1.
2.
3. …
> Update README.md - update build status logos and links

- data/sql/updates/pending_db_world/rev_1729454932992384900.sql
- Hallow's End decorations
- Closes 
1.
2.
3. …
> fix(DB/Gameobject): Sniffed Values for 'Skull 01' spawns

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
The changes:
This PR:
1. Engage Illidan.
2. Begin phase two (elemental phase).
3. Observe Illidan and his Eye Beam locations.
4. Repeat. …
> fix(Scripts/BlackTemple): Randomize Eye Beam target position.

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
1. Engage Illidan.
2. Begin phase two (elemental phase).
3. Observe Illidan and his Eye Beam locations.
4. Repeat. …
> fix(Scripts/BlackTemple): Properly randomize Illidan initial Eye Beam and order.

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
Fixes him being stuck in place if you wipe during demon phase
- Closes 
1.
2.
3. …
> fix(Scripts/BlackTemple): Reset Illidan combat movement

- data/sql/updates/pending_db_world/rev_1729732350483337300.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20261
1.
2.
3. …
> fix(DB/SmartScript): Fix Illidan Shadow Demons not killing their targets

- data/sql/updates/pending_db_world/rev_1729660470785757300.sql
- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20215
1.
2.
3. …
> fix(Scripts/BlackTemple): Apply Shadow Prison spell immunities

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19990#issue-2531350643
1.
2.
3. …
> fix(Scripts/BlackTemple): Prevent Illidan transformation during cutscene

- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes unreported issue (wrong spell for normal hatching)
some stuff based on video evidence. this PR however is NOT yet based on sniffs and actual careful checking of videos. It's meant to mostly just refactor the script to use more modern scripts to make it easier to fix in the future
1. `.go creature 89322`
2. Go fight him, see if the hatchers seem to work correctly as well as if the bombs work correctly
3. Try to find some edge cases …
> refactor(Scripts/ZulAman): refactor Jan'alai

- data/sql/updates/pending_db_world/#19606-dalaran-wizards-robe.sql
> fix(DB/creature_loot_template): Removing Dalaran Wizard's Robe from Witchwing harpies

- data/sql/updates/pending_db_world/rev_1729898849364366600.sql
On live servers, the iron rune laborers in the quarry are mining, not standing still. This change adds the mining emote.
Closes AzerothCore issue #20296
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20296 …
> fix(DB/Emote): Add STATE_WORK_MINING emote to certain iron rune laborers

- data/sql/updates/pending_db_world/rev_1729972036319397600.sql
- Closes chromiecraft/chromiecraft#7443
1.
2.
3. …
> fix(DB/Gameobject): final cleanup of Hallow's End decorations

- data/sql/updates/pending_db_world/sergeants-heavy-back-faction-change.sql
> fix(DB): Adjust faction change swap for Sergeant's Heavy back.

- data/sql/updates/pending_db_world/#20186-kaluak-fishing-derby.sql
> fix(DB/game_event): Fix Kalu'ak Fishing Derby starting times

- data/sql/updates/pending_db_world/Feral_Dragonhawk_Hatchling_skinnable.sql
Feral Dragonhawk Hatchling are skinnable now.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20328
- Closes https://github.com/chromiecraft/chromiecraft/issues/7450
1.
2.
3. …
> Fix(DB/Creature) Feral Dragonhawk Hatchling are skinnable.

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
Timing purely based on video evidence
https://youtu.be/k8_JbDiALkY?t=753
1. Fight Illidan until phase 4
2.
3. …
> fix (Script/Black Temple) Spawn Shadow Demons 30s into phase 4

- docker-compose.yml
Updated env variable name in docker-compose for data volume. `DOCKER_VOL_DATA` consistently should point to data volume binding in whole compose file.
- Closes 
1.
2.
3. …
> Fix env name for data volume

- data/sql/updates/pending_db_world/sunblade-vindicator-strike.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7463 …
> fix(DB/SAI): Replace bad spell ID for Sunblade Vindicator's Mortal Strike.

- data/sql/updates/pending_db_world/sunblade-scout-auras.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7472
This PR: …
> fix(DB/Creature): Add auras to Sunblade Scout.

- data/sql/updates/pending_db_world/rev_1730331051873196200.sql
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/20336
1.
2.
3. …
> fix(DB/Creature): Shadow Demon knockback immunity

- src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
- src/server/game/Movement/MovementGenerators/RandomMovementGenerator.h
Thank to Ovahlord for the catch.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20240
- [] This pull request requires further testing and may have edge cases to be tested.
1.
2.
3. …
> fix(Core/Movement): fix a small memory leak in RandomMovementGenerator

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20392
- Closes https://github.com/chromiecraft/chromiecraft/issues/7424
1.
2.
3. …
> fix(Scripts/BlackTemple): Parasitic Shadowfiends only target players

- src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7475
1.
2.
3. …
> fix(Core/Spells): Fix Gurtogg Bloodboil applying Acid Wound to himself

- data/sql/updates/pending_db_world/rev_1730474098944363200.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/1430
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7368
1.
2.
3. …
> fix(DB/Creature): Remove stunned flag from Syndicate Thiefs

- data/sql/updates/pending_db_world/rev_1730483438978049424.sql
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_lord_jaraxxus.cpp
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp
> refactor(scripts/CrusadersColiseum): spell scripts use registry macros 

- data/sql/updates/pending_db_world/rev_1730480939942370941.sql
- src/server/scripts/EasternKingdoms/Gnomeregan/instance_gnomeregan.cpp
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
- src/server/scripts/EasternKingdoms/Scholomance/instance_scholomance.cpp
- src/server/scripts/EasternKingdoms/ShadowfangKeep/instance_shadowfang_keep.cpp
- src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp
- src/server/scripts/EasternKingdoms/Uldaman/instance_uldaman.cpp
- src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
> refactor(Scripts/EasternKingdoms): spell scripts use registry macros

- data/sql/updates/pending_db_world/game-event-npc-vendor-key.sql
> feat(DB): Expand `game_event_npc_vendor` key to include event entry.

- src/server/scripts/Outland/zone_shadowmoon_valley.cpp
[crashlog](https://github.com/user-attachments/files/17549227/message-2.txt)
- Closes 
1.
2.
3. …
> fix(Scripts/Outland): Fix crash in dragonmaw_race_npc by refreshing players pointer in lambda function.

- src/server/scripts/Outland/zone_netherstorm.cpp
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/19591
https://github.com/azerothcore/azerothcore-wotlk/issues/19591#issuecomment-2284379813
diff to complete escort faster
```
diff --git a/src/server/scripts/Outland/zone_netherstorm.cpp b/src/server/scripts/Outland/zone_netherstorm.cpp
index 9b9a8d90bc..c990f78bf8 100644
--- a/src/server/scripts/Outland/zone_netherstorm.cpp
+++ b/src/server/scripts/Outland/zone_netherstorm.cpp
@@ -732,3 +732,3 @@ public:
break;
-                case 36: //return and quest_complete
+ …
```
> fix(Scripts/Netherstorm): make "Mark V is Alive!" group completable 

- data/sql/updates/pending_db_world/gift-loot-jack-o-lantern.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7447
This PR: …
> fix(DB/Loot): Add Weighted Jack-o'-Lanterns to Crudely Wrapped Gift.

- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp
fixup 
- https://github.com/azerothcore/azerothcore-wotlk/pull/20400
- Closes 
1.
2.
3. …
> fixup(Scripts/CrusaderColiseum)spellscripts

- src/server/game/Spells/SpellScript.cpp
Validate errors do not show up in `Errors.log` causing CI to pass with errors. https://github.com/azerothcore/azerothcore-wotlk/actions/runs/11633921119/job/32400061351
rename `scripts.spells` to `spells.scripts`
https://github.com/azerothcore/azerothcore-wotlk/blob/acf267f84fc99e6024e0b29efb6586d469752d11/src/server/apps/worldserver/worldserver.conf.dist#L689
blame b00ac48cfa9cf54546ae9ba1a3a545563ae37f32
- Closes 
1.
2.
3. …
> fix(Spells/SpellScript): fix CI, rename the log for Validate

- src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
fix reviews of Ovahlord #20258 . Thanks.
- Closes 
1.
2.
3. …
> fix(Core/Movement): remove unecessary reset()

- data/sql/updates/pending_db_world/rev_1730665013024686700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6888
https://www.wowhead.com/wotlk/item=28789/eye-of-magtheridon#comments:id=5375765
1.
2.
3. …
> fix(DB/Procs): Eye of Magtheridon not procing on miss

- data/sql/updates/pending_db_world/rev_1730643881779967700.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19716
- Closes https://github.com/chromiecraft/chromiecraft/issues/6332
1.
2.
3. …
> fix(DB/Custom): Spotlight aura stacking

- data/sql/updates/pending_db_world/rev_1730519194220305125.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20364#issue-2621453201
https://github.com/azerothcore/azerothcore-wotlk/issues/20364#issue-2621453201
1.
2.
3. …
> Fix(SQL): Pack near the first scout is not linked properly

- src/server/game/Spells/Auras/SpellAuras.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20298 …
> fix(Core/Spells): Adjust logic for removing/applying auras related to areas.

- data/sql/updates/pending_db_world/rev_1730575812039136017.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20344
1. https://github.com/azerothcore/azerothcore-wotlk/issues/20344
2.
3. …
> Fix(SQL): Unleashed Hellion's Rain of Fire

- data/sql/updates/pending_db_world/rev_1730519930456661020.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20397
https://github.com/azerothcore/azerothcore-wotlk/issues/20397
1.
2.
3. …
> Fix(SQL): deactivated sunblade protectors is not linked properly

- data/sql/updates/pending_db_world/rev_1730488634123195500.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
- src/server/scripts/Spells/spell_item.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/3010
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10711
1.
2.
3. …
> fix(Core/Spells): Luffa removing bleeds over level 60

- data/sql/updates/pending_db_world/last_hexlord_add.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
- Closes unreported issues
just refactor work, no real sources
1. `.go creature 89357`
2. overall testing (groups preferred) …
> refactor(Scripts/ZulAman): refactor set data to instance boss states and refactor Hex Lord Malacrass

- apps/ci/ci-pending-sql.sh
-  [x] CI
The fix-pending-sql CI script was inadvertently using octal numbers, since numbers < 10 are zero-padded, and this isn't escaped when parsed. This change makes it so the leading zero is removed.
- [error during github actions ](https://github.com/azerothcore/azerothcore-wotlk/actions/runs/11671868818/job/32499228883#step:4:18)
- Tested running locally
1.
2.
3. …
> fix(CI/SQL import): don't use octal

- src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14402
- Closes https://github.com/chromiecraft/chromiecraft/issues/4257
- Closes https://github.com/chromiecraft/chromiecraft/issues/6694
every other mount in the game
https://github.com/user-attachments/assets/863061bf-2141-49a4-8d8e-e15055f06207
1.
2.
3. …
> fix(Core/Spells): 'Black Qiraji Battle Tank' being removed on map change/teleport

- data/sql/updates/pending_db_world/rev_1730805281119063500.sql
Before you were required to do either one of 9957,9960,9961 in order to unlock 9968
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14296
- Closes https://github.com/chromiecraft/chromiecraft/issues/4616
https://wowpedia.fandom.com/wiki/Strange_Energy + in the issue
1.
2.
3. …
> fix(DB/Quests): 'Strange Energy' having prerequisites

- data/sql/updates/pending_db_world/rev_1730834742791547700.sql
- src/server/scripts/Spells/spell_generic.cpp
I noticed that Frostfire Regalia was using the same method and wasn't working either.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14403
- Closes https://github.com/chromiecraft/chromiecraft/issues/4320
1.
2.
3. …
> fix(Scripts/Item): Obsidian Armor & Frostfire Regalia Set

- data/sql/updates/pending_db_world/rev_1730893685558312500.sql
- src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/3796
1.
2.
3. …
> fix(Scripts/ZG): Poisonous Blood not being removed after Blood Siphon

- src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_rajaxx.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/3921
in the issue
1.
2.
3. …
> fix(Scripts/AQ20): Set General Rajaxx's Thundercrash to min 100 dmg

- src/server/game/Entities/Unit/Unit.cpp
[crashlog](https://github.com/user-attachments/files/17649044/message-3.txt)
- Closes 
1.
2.
3. …
> fix(Core/Unit): Fix crash during Judgement of Light/Wisdom proc

- data/sql/updates/pending_db_world/rev_1730883055614829500.sql
The classic update into empty rows...
https://github.com/azerothcore/azerothcore-wotlk/pull/15251/files#diff-39c595d688d0efbbb625590eda474f729666a520df71b1d2bf623421ebafdb8cR2 😔
- Closes 
1.
2.
3. …
> fix(DB/Creature): Darting Hatchling missing periodic aura

- data/sql/updates/pending_db_world/rev_1730923393720388300.sql
> fix(DB/Creature): Sniffed Values for 'Winter Veil Gifts' spawns

- data/sql/updates/pending_db_world/rev_1730911503089002300.sql
https://www.wowhead.com/wotlk/spell=71567/item-icecrown-dungeon-healer-trinket
1.
2.
3. …
> fix(DB/Procs): Ephemeral Snowflake having wrong icd

- data/sql/updates/pending_db_world/rev_1730989779516531800.sql
> fix(DB/Creature): Fix Zul'jin spawn position

- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20445
NOT TESTED
1. https://github.com/azerothcore/azerothcore-wotlk/issues/20445
2.
3. …
> Fix(Core/Scripts): Kael'thas' Arcane Spheres & Phoenix should despawn

- data/sql/updates/pending_db_world/rev_1730802205082380900.sql
Also correct respawn, xyz is from waypoint_data
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14331
- Closes https://github.com/chromiecraft/chromiecraft/issues/4619
1.
2.
3. …
> fix(DB/SAI): Arzeth the Merciless not moving on respawn

- data/sql/updates/pending_db_world/rev_1730874923490368506.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19903
1.https://github.com/azerothcore/azerothcore-wotlk/issues/19903
2.
3. …
> fix(DB/Creature): Magma Elemental interrupt

- data/sql/updates/pending_db_world/rev_1731165151168533600.sql
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
> fix(Scripts/ZulAman): Move Harrison Jones spawn to DB

- data/sql/updates/pending_db_world/rev_1731192427658198900.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
> refactor(Scripts/ZulAman): Move Jan'alai Fire Bomb to SAI

- src/server/game/AI/SmartScripts/SmartScript.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20326
- Closes https://github.com/chromiecraft/chromiecraft/issues/7445
1.
2.
3. …
> fix(Core/SAI): Don't try to reposition Rooted inhabit type creatures

- data/sql/updates/pending_db_world/rev_1731176128691196300.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20369
- Closes https://github.com/chromiecraft/chromiecraft/issues/7455#issue-2618071507
Updated storm visual (player gets lifted in the air)
Eagles dont fall to the ground
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Akilzon not spawning eagles and update script

- src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
> fix(Scripts/ZulAman): Fix crash in Nalorakk script

- src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/6963
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18833
1.
2.
3. …
> fix(Scripts/SSC): Fix Leotheras running in melee range in demon phase

- data/sql/updates/pending_db_world/rev_1731221614295821000.sql
- src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7489
1.
2.
3. …
> fix(Scripts/Spells): Limit Cyclone (39594) to 4 targets

- data/sql/updates/pending_db_world/rev_1731208074789403000.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
> refactor(Scripts/ZulAman): Move Spirit of the Lynx to SAI

- data/sql/updates/pending_db_world/rev_1731220503708811500.sql
- src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp
> fix(Scripts/SSC): Improve Tainted Elemental combat behaviour

- data/sql/updates/pending_db_world/rev_1731187917937110400.sql
- src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.h
> refactor(Scripts/MagisterTerrace): Move Kalecgos script to SAI

- data/sql/updates/pending_db_world/rev_1730825421243583400.sql
4724 was already correct (outside of the reference)
- Closes https://github.com/chromiecraft/chromiecraft/issues/4528
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14508
wowhead
1.
2.
3. …
> fix(DB/Loot): Humbert's set

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
> refactor(Scripts/SunwellPlateau): Modernize Eredar Twins script

- data/sql/updates/pending_db_world/harrison-jones-hack.sql
> fix(DB/Creature): Adjust Harrison Jones's movement type.

- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20530
1.
2.
3. …
> fix(Scripts/ZulAman): Set Akilzon encounter in progress when engaged

- src/server/game/Spells/SpellEffects.cpp
cherry-pick https://github.com/TrinityCore/TrinityCore/commit/0197a2f990aa7c7eaf8637a2a5da7f43def9c4bd
TC issue for info on Jump Speed Calculations https://github.com/TrinityCore/TrinityCore/issues/22547
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20460
https://github.com/TrinityCore/TrinityCore/commit/0197a2f990aa7c7eaf8637a2a5da7f43def9c4bd
death grip
```
.cast 49576
```
Leaping Hatchling Jump
```
.cast 67427
```
1.
2.
3. …
> fix(Core/Spells): Jump Speed Calculations

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
> refactor(Scripts/SunwellPlateau): Update Brutallus script

- data/sql/updates/pending_db_world/rev_1731513769607437914.sql
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
Currently, after the gong becomes clickable it opens after 1:45 (105s). Clicking does nothing
Changes:
- remove auto opening after 105s
- continue opening event after gong ritual is completed 
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/20494
This wrath classic source https://www.youtube.com/watch?v=6k1bWWJrkEs shows the gate being opened after ~8s of 1 person interacting with the gong
1.
2.
3. …
> fix(Scripts/ZulAman): speed up gong event

- src/server/scripts/Outland/TempestKeep/Eye/boss_astromancer.cpp
> fix(Scripts/TheEye): Fix Wrath of the Astromancer's original caster

- data/sql/updates/pending_db_world/rev_1731545993422354000.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
> fix(Scripts/ZulAman): Remove Eletrical Storm hacks

- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
> fix(Scripts/ZulAman): Permbind players when using the gong

- data/sql/updates/pending_db_world/rev_1731534309713710300.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
> refactor(Scripts/SunwellPlateau): Modernize Muru script

- src/server/game/Instances/InstanceScript.cpp
> fix(Core/Instance): Save persistent data to DB on updates

- src/server/game/Spells/SpellEffects.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20527
- Closes https://github.com/chromiecraft/chromiecraft/issues/7497
1.
2.
3. …
> fix(Core/Spells): Fix Lay on Hands healing bypassing Cyclone

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Scripting/ScriptDefines/PlayerScript.cpp
- src/server/game/Scripting/ScriptDefines/PlayerScript.h
- src/server/game/Scripting/ScriptMgr.h
- Add a hook that is called when base weapon damage is set
1.
2.
3. …
> feat(core): Add hook for applying weapon damage

- data/sql/updates/pending_db_world/rev_1731595481697504000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20342
1.
2.
3. …
> fix(DB/SAI): Correct Dawnblade Summoner timers and combat movement

- data/sql/updates/pending_db_world/rev_1731611937411826300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7471
1.
2.
3. …
> fix(DB/SAI): Remove SAI to set unselectable flag from Sunblade Protectors

- src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
Resurrection (36450) doubles max health, but advisors do not regen while waiting, so they activate with 50% hp. 
This ensures they spawn with max health
- https://github.com/azerothcore/azerothcore-wotlk/pull/20188
- Closes 
1.
2.
3. …
> fixup(Scripts/TheEye): spawn Kaelthas' advisors with full hp

- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
Ensures gate is open after restarts
- Closes 
1.
2.
3. …
> fix(Scripts/ZulAman): Save Massive Gate state to DB

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7461
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20414
1.
2.
3. …
> fix(Scripts/ZulAman): Update Malacrass adds spawn positions

- src/server/game/Instances/InstanceScript.cpp
- src/server/game/Instances/InstanceScript.h
- src/server/scripts/Outland/BlackTemple/instance_black_temple.cpp
This allows setting creature A as summoner if the creature is spawned by some other summoner.
Creature data must already be loaded in the creatureData list
- Closes 
1.
2.
3. …
> feat(Core/Instances): Implement SummonData

- src/server/apps/worldserver/worldserver.conf.dist
> fix(conf/worldserver): add Logger.sql.updates option

- data/sql/updates/pending_db_world/rev_1731487213354414876.sql
- src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20347
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20354
1. https://github.com/azerothcore/azerothcore-wotlk/issues/20347
2. https://www.wowhead.com/wotlk/npc=24979/dawnblade-marksman#abilities;mode:n25
3. …
> Fix(SQL/SAI): dawnblade marksman distance

- data/sql/updates/pending_db_world/rev_1731719085948895000.sql
> fix(DB/Creature): M'uru should not reposition in combat

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
> refactor(Scripts/SunwellPlateau): Modernize Kil'jaeden script

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp
> refactor(Scripts/SunwellPlateau): Update Kalecgos script

- data/sql/updates/pending_db_world/rev_1731726839690566900.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
> refactor(Scripts/ZulAman): Move Amani Hatchling to SAI

- src/server/scripts/Northrend/Naxxramas/boss_anubrekhan.cpp
- src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp
- src/server/scripts/Northrend/Naxxramas/naxxramas.h
> refactor(Scripts/Naxxramas): Modernize Anubrekhan script

- src/server/scripts/EasternKingdoms/ZulGurub/boss_gahzranka.cpp
> refactor(Scripts/ZulGurub): Modernize Gahzranka script

- data/sql/updates/pending_db_world/rev_1731858489096200800.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7514
1.
2.
3. …
> fix(DB/Creature): Zul'jin and Akil'zon should be taunt immune

- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
> refactor(Scripts/MagisterTerrace): Update Priestess Delrissa

- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
> fix(Scripts/ZulAman): Fix Janalai berserk

- data/sql/updates/pending_db_world/rev_1731793823275142100.sql
- Closes 
This fixes two issues:
- Protectors even disabled should still aggro if someone gets close enough
- Protectors activate themselves (lose perm stun aura) if you attack them
1.
2.
3. …
> fix(DB/SAI): Fix Sunblade Protector behaviour

- src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp
re-add event 
- https://github.com/azerothcore/azerothcore-wotlk/blob/a7578e1cce4ec49375fd9298676a1d6263473666/src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp#L797
fixup of
- https://github.com/azerothcore/azerothcore-wotlk/pull/20188
- Closes 
1.
2.
3. …
> fix(Scripts/TheEye): Advisors add Sanguinar's Bellowing Roar

- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20631
1.
2.
3. …
> fix(Scripts/ZulAman): Restore hatcher side switch

- data/sql/updates/pending_db_world/rev_1731998925094021764.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20623
1.https://github.com/azerothcore/azerothcore-wotlk/issues/20623
2.
3. …
> fix(DB/Conditions): Ur'dan require quest to buy stardust

- data/sql/updates/pending_db_world/remove_amani_bear_mount.sql
Remove Amani Bear Mount from Zul'Aman.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7517#issue-2666762828
1.
2.
3. …
> fix(DB/Creature): Remove Amani Bear Mounts from Zul'Aman.

- data/sql/updates/pending_db_world/rev_1732080184310717121.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20640
1. https://github.com/azerothcore/azerothcore-wotlk/issues/20640
2.
3. …
> fix(DB/Conditions): Mana Remnants can be used only near Crystal Wards

- data/sql/updates/pending_db_world/rev_1732070236293413533.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
- src/server/scripts/Spells/spell_generic.cpp
Remove the SetHealth and SetMaxHealth hacks. Use sniffed spells instead.
There's a few spells with spell_effect transform (like ID - 43142 Transfigure), but I can't find them in the sniff. So, I don't think they are used. Instead, `Creature->UpdateEntry` to the dummy NPC, is used to set the model and stats. 
Added a generic sethealth script to the triggered spells
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20634
extra sources for reference:
https://www.wowhead.com/tbc/guide/halazzi-zulaman-za-strategy-burning-crusade-classic …
> fix(Scripts/ZulAman): Halazzi Phases

- data/sql/updates/pending_db_world/rev_1732125382543129600.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20658
- Closes https://github.com/chromiecraft/chromiecraft/issues/7530
1.
2.
3. …
> fix(DB/Creature): Jan'alai taunt immunity

- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7534
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Janalai Enrage/Berserk behaviour

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20637
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Malacrass not casting correct class abilities

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20638
1.
2.
3. …
> fix(Scripts/ZulAman): Remove Zul'jin Electrical Storm on phase change

- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20635
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Halazzi lynx not moving on spawn

- data/sql/updates/db_world/2024_11_20_07.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
> fix(Scripts/ZulAman): Hexlord: missing update to last commit

- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20443
~~Didn't test this with multiple players. However can confirm the orbs at least still follow.~~ tested. works fine. code to select random player is not really pretty, but I don't think there is a better ready-made function to get a random alive and engaged player
1.
2.
3. …
> refactor(Scripts/MagistersTerrace): Felblood Kael'thas

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20657
1.
2.
3. …
> fix(Scripts/ZulAman): Correct gate ids

- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20659
- Closes https://github.com/chromiecraft/chromiecraft/issues/7532
1.
2.
3. …
> fix(Scripts/ZulAman): Jan'alai eggs should not respawn during encounter

- data/sql/updates/pending_db_world/rev_1732230663384806400.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7513
1.
2.
3. …
> fix(DB/Loot): Malacrass should drop 2-3 pieces of loot

- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20235
1.
2.
3. …
> fix(Core/Creature): Don't call reset if still in combat

- data/sql/updates/pending_db_world/rev_1732339897805274964.sql
Add implicit target conditions for the 'Summon Amani'shi Hatcher' spells allowing `.cast 45340` to spawn hatcher downstairs at the world trigger
- Closes 
```
(Cast) SpellID: 43962 (43962)
(Cast) (Target) (DstLocation) Location: X: -78.635124 Y: 1153.1543 Z: 5.494038
(Cast) (Target) Orientation: 5.66127777099609375
(Cast) SpellID: 45340 (45340)
(Cast) (Target) (DstLocation) Location: X: -76.78908 Y: 1144.4946 Z: 5.5153522
(Cast) (Target) Orientation: 5.66127777099609375
```
```
Effect 0: Id 28 (SPELL_EFFECT_SUMMON)
BasePoints = 1
Targets (46, 86) …
```
> fix(DB/Conditions): add Jan'alai's Summon Hatchers implicit target entry

- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
`EnterPhase(PHASE_LYNX);` which schedules lynx events is called on aggro and onreset, causing events to be scheduled twice on initial aggro
removes 1
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20697
- Closes https://github.com/chromiecraft/chromiecraft/issues/7542
1.
2.
3.
**REMEMBER**: …
> fix(Scripts/Zulaman): Halazzi double scheduling of lynx abilties in the first phase 1

- data/sql/updates/pending_db_world/rev_1732316403019721900.sql
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/20314
1.
2.
3. …
> fix(DB/Conditions): Fix Jan'lai not hatching all eggs

- src/server/game/AI/CreatureAI.cpp
- src/server/game/AI/CreatureAI.h
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7531
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20679
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Amani Hatcher behaviour

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
> fix(Scripts/ZulAman): Despawn Zuljin spirits shortly after death

- data/sql/updates/pending_db_world/rev_1732428469975738467.sql
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
* refactored with task scheduler, removed unused events 
* adjusted waypoints and actions based on sniffs
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15860
1. `.go c id 24358`
2.
3. …
> fix(Scripts/ZulAman): Harrison Jones gong event RP with taskscheduler

- src/common/Utilities/TaskScheduler.cpp
- src/common/Utilities/TaskScheduler.h
This allows getting the next time any tasks within the group will occur
- Closes 
1.
2.
3. …
> feat(Core/Scripting): Implement TaskScheduler GetNextGroupOccurrence()

- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
should only occur on lynx -> troll form transition (3 times total)
removes cast troll -> lynx form
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20715
1. `.go c id 23577`
2. trigger transitions
3. should only cast transfigure when going from lynx to troll …
> fix(Scripts/ZulAman): remove cast transfigure when going into lynx

- data/sql/updates/pending_db_world/rev_1732474303790541000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7550
1.
2.
3. …
> fix(DB/Spell): Correct gender requirement for ZA charm spells

- data/sql/updates/db_world/2024_11_24_05.sql
> chore(DB/Spells): Add missing Charm of the Bloodletter gender

- src/server/scripts/Northrend/Nexus/Nexus/boss_anomalus.cpp
- src/server/scripts/Northrend/Nexus/Nexus/boss_commander_stoutbeard_kolurg.cpp
- src/server/scripts/Northrend/Nexus/Nexus/boss_keristrasza.cpp
- src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp
- src/server/scripts/Northrend/Nexus/Nexus/boss_ormorok.cpp
- src/server/scripts/Northrend/Nexus/Nexus/instance_nexus.cpp
- src/server/scripts/Northrend/Nexus/Nexus/nexus.h
> refactor(Scripts/Nexus): Update creature scripts to new register method

- data/sql/updates/pending_db_world/rev_1732503730550901400.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19587
- Closes https://github.com/chromiecraft/chromiecraft/issues/5554
1.
2.
3. …
> fix(DB/SAI): Fix Grimtotem Raider using net under crowd control effects

- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20739
- Closes https://github.com/chromiecraft/chromiecraft/issues/7551
detailed analysis of video evidence in linked issue 
`.go c id 23577`
1.
2.
3. …
> fix(Scripts/ZulAman): Halazzi Lynx Ability Timers

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20752
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Soul Siphon visual effect

- src/server/scripts/Northrend/Nexus/Nexus/boss_commander_stoutbeard_kolurg.cpp
> refactor(Scripts/TheNexus): Update Command Kolurg script

- data/sql/updates/pending_db_world/rev_1732987456910406300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7572
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20775
1.
2.
3. …
> fix(DB/Creature): Fix Zul'jin formations

- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/scripts/Commands/cs_tele.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/20268
- Closes 
1.
2.
3. …
> fix(Script/Commands): tele add should only check exact match

- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_ingvar_the_plunderer.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_keleseth.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_skarvald_dalronn.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/utgarde_keep.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/utgarde_keep.h
> refactor(Scripts/UtgardeKeep): Upgrade scripts to new register method

- data/sql/updates/pending_db_world/scarlet_infantrymen.sql
This PR correct some Scarlet Infantrymen spawn-points, add waypoints and add invisibility feature for four of them.
- Update https://github.com/azerothcore/azerothcore-wotlk/issues/20744
1.
2.
3. …
> fix(DB/Creature) Scarlet Infantrymen.

- src/server/scripts/Commands/cs_server.cpp
> fix(Scripts/Commands) fix formatting in server debug

- data/sql/updates/pending_db_world/rev_1732461302175126777.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
Add Eagle gauntlet
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20407
- Closes https://github.com/chromiecraft/chromiecraft/issues/7453#issue-2618062108
tempests' timers for spawn eagles and warriors, wind walker and protector spawns: https://github.com/cmangos/mangos-wotlk/commit/4b890a4096153686f97c0faa3f6196b27205cc8a
2nd character with GM mode to see eagle triggers
1. `.go xyz 193.161 1455.56 17.66 568 0.35`
2.  trigger gauntlet by moving close to scout or an invisible trigger
3. …
> fix(Scripts/ZulAman): eagle gauntlet

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20773
- Closes https://github.com/chromiecraft/chromiecraft/issues/7570
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Zuljin targetting players during eagle phase

- src/server/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
> chore(Scripts/Karazhan): Remove unused variables

- src/common/Collision/Models/ModelInstance.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6093
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2437
- Closes https://github.com/chromiecraft/chromiecraft/issues/719
- Closes https://github.com/chromiecraft/chromiecraft/issues/2836
cherry-picked from:
https://github.com/TrinityCore/TrinityCore/commit/53b4501ce9b072cfffe7de7f348094f443e36950
1. `.go xyz -1460.34 2695.40 77.4971 1`
2. no Breath bar
3. …
> fix(Core/Vmaps): Do not ignore model rotation when calculating liquid level

- src/server/game/Entities/Pet/Pet.cpp
- src/server/game/Entities/Player/Player.cpp
Make the pets use the database classes instead of overwriting through code.
Mage: Water Elemental, Imp
Paladin: Succubus, Felhunter, Voidwalker, Felguard
Rogue: Ghoul
Warrior: Hunter pets (unchanged, some tameable beasts are not warriors before taming)
Use the current Database values
Pally Power works with those values
The spells to summon them are in brackets
1. Summon all Warlock(688,697, 712,691,30146), Deathknight(46584) and Mage(31687) pets on a fresh character
2. Target the pet
3.  `/dump UnitClass("target")`
4.  Resummon …
> fix(Core/Pet) Remove unnecessary Pet Class reassignments

- apps/startup-scripts/gdb.conf
- apps/startup-scripts/starter
`set logging on` is deprecated, so replace it with `set logging enabled on`
- Closes 
deprecated warning when running the worldserver with gdb
for example as described in https://www.azerothcore.org/wiki/how-to-restart-and-debug with `AC_RESTARTER_WITHGDB`
```
AC_RESTARTER_WITHGDB=true ./acore.sh 11
```
output:
```
Running worldserver ...
Running with GDB enabled
Warning: 'set logging on', an alias for the command 'set logging enabled', is deprecated.
Use 'set logging enabled on'.
```
1.
2.
3. …
> refactor(Apps/Startup): replace 'set logging on` command with 'set logging enabled on'

- data/sql/updates/pending_db_world/rev_1732828124635270700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7564
> .go creature id 10540 // Voljin
>. go creature id 4485 // Belgrom …
> fix(DB/Quest) - Added the missing NPC Starters for Regthar Deathgate

- data/sql/updates/pending_db_world/rev_1733152346182084675.sql
Please stop unchecked wowhead imports.
Critters are not skinnable
Loot often gets mixed up when creatures transform/change template
https://warcraft.wiki.gg/wiki/Patch_3.2.0_(undocumented_changes)#Skinning
https://www.wowhead.com/wotlk/npc=883/deer#comments:id=805628
- Partially revert https://github.com/azerothcore/azerothcore-wotlk/pull/20643 https://github.com/azerothcore/azerothcore-wotlk/pull/20644 https://github.com/azerothcore/azerothcore-wotlk/pull/20645 https://github.com/azerothcore/azerothcore-wotlk/pull/20646
1.
2.
3.
When a PR is ready to …
> fix (DB/Loot) Critters are not skinnable

- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
> feat(Core/Unit): Implement GetCompanionPet() helper

- data/sql/updates/pending_db_world/rev_1733154050654802692.sql
[18094](https://wowgaming.altervista.org/aowow/?npc=18094) is an actual human and was made skinnable
[23177](https://wowgaming.altervista.org/aowow/?npc=23177) transforms into [18171](https://wowgaming.altervista.org/aowow/?npc=18171), this is the one where wowhead got the skinning loot from
same with the other two
- Partially revert https://github.com/azerothcore/azerothcore-wotlk/pull/20643 https://github.com/azerothcore/azerothcore-wotlk/pull/20644 https://github.com/azerothcore/azerothcore-wotlk/pull/20645 https://github.com/azerothcore/azerothcore-wotlk/pull/20646 …
> fix (DB/Loot) Old Hillsbrad Foothills guards should not skinnable

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7582
1.
2.
3. …
> fix(Scripts/ZulAman): Overpower spell cooldown

- data/sql/updates/pending_db_world/rev_1730814217046191100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14284
- Closes https://github.com/chromiecraft/chromiecraft/issues/4577
.q add 10895
.go c id 22401
use the item at the bottom of the tower (do this for the other 3)
(you need to be within visibility range of the squad (2 spawn points) locations in order for the event to start) …
> fix(DB/Conditions): 'Zeth'Gor Must Burn!' setting the sky on fire

- .gitignore
Ignores .vs (Visual Studio) and /out/* (Default build directory when unspecified (Visual Studio).)
-  [x] Git
Visual Studio creates a hidden .vs directory that is currently not ignored.
Additionally, the default build directory when unspecified in CMAKE is `/out/*` (in Visual Studio, may be the same for other build systems.) which is also picked up by Git.
This makes switching between feature branches burdensome as you either need to discard all temporary IDE files (and copied over dynamic libraries and configurations) or you need to temporarily ignore these in each feature branch.
Without these changes (after …
> request(git): Update .gitignore

- data/sql/updates/pending_db_world/rev_1733253947081144253.sql
Swiftmane can attack back instead of continuing to run
- remove the unused waypoint data
- changes SAI to load wp on reset, set it to repeat, change react state to 1 so he can attack back  
Swiftmane has a SmartAI OOC timer with repeat 0 that loads a waypoint path with passive react state, so he cant attack back.
Swiftmane also has a waypoint set in the DB that is unused
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20816
1. `.go c id 5831`
2. attack swiftmane
3. see if he loads wp correctly on reset, respawn …
> fix(DB/SAI): Swiftmane Waypoint ReactState

- src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
handle speed like before, b42ca49329138c2a15747d594884e0af95764cc6
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20585
1. `.go ga id 194092`
2. 
3. …
> fix(Scripts/Karazhan): Nightbane Speed

- data/sql/updates/pending_db_world/rev_1733366049086007200.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7584
1.
2.
3. …
> fix(Scripts/ZulAman): Akil'zon storm damage should multiply per tick

- data/sql/updates/pending_db_world/rev_1733563031329419100.sql
- Lunar Festival
- Closes 
1.
2.
3. …
> fix(DB/Gameobject): Sniffed Values for 'Boss Fight Altar' spawns

- data/sql/updates/pending_db_world/rev_1733557953974539700.sql
- Lunar festival
- Closes 
1.
2.
3. …
> fix(DB/Gameobject): Sniffed Values for 'DwarvenTableSmall' spawns

- data/sql/updates/pending_db_world/rev_1733520787103950300.sql
- Lunar festival
- Closes 
1.
2.
3. …
> fix(DB/Gameobject): Sniffed Values for 'Starsong Scroll' spawns

- data/sql/updates/pending_db_world/rev_1733520465657996700.sql
- Lunar festival
- Closes 
1.
2.
3. …
> fix(DB/Gameobject): Sniffed Values for 'Lucky Red Envelope' spawns

- data/sql/updates/pending_db_world/Silt_Crawlers.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7510
1.
2.
3. …
> Fix(DB/Spawn) Silt Crawlers under the landscape (another two).

- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
- Likely closes https://github.com/azerothcore/azerothcore-wotlk/issues/20777
- Likely closes https://github.com/azerothcore/azerothcore-wotlk/issues/20859
This PR: …
> fix(Core/AI): Increase movement leash extension interval.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20848
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Fix Entropius despawning

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20844
- Closes https://github.com/chromiecraft/chromiecraft/issues/7581
1.
2.
3. …
> fix(Scripts/ZulAman): Zuljin abilities shouldnt overlap

- data/sql/updates/pending_db_world/Amani_Eagle_Talon.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7607
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20887
1.
2.
3. …
> fix(DB/Creature)Amani Eagle doesn't use Talon ability.

- data/sql/updates/pending_db_world/rev_1732889463640565780.sql
Split tokens and other items into two reference_loot_templates for better readability
Make it possible for both glaives to drop at once and slightly increase drop chance in accordance to [wowhead](https://www.wowhead.com/wotlk/npc=22917/illidan-stormrage#drops)
Source for possibility of both dropping at the same time:
https://www.mmo-champion.com/threads/1092709-Is-it-possible-for-BOTH-warglaives-of-azzinoth-to-drop-at-once
https://www.reddit.com/r/classicwow/comments/smqd54/has_there_been_any_confirmed_double_glaive_drops/
1.
2.
3. …
> fix(DB/Loot): improve Illidan loot

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/20751
- Updates https://github.com/chromiecraft/chromiecraft/issues/7558
1.
2.
3. …
> fix(Scripts/ZulAman): Dont update Hexlord timers while casting

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20890
- Closes https://github.com/chromiecraft/chromiecraft/issues/7609
1.
2.
3. …
> fix(Scripts/ZulAman): Malacrass adds shouldnt change on wipes

- src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
- Closes #20677 
1. go to ICC
2. Fight with Deathwhisper (2nd boss)
3. remove shield and wait to summon vengeful spirit …
> fix(Scripts/IcecrownCitadel): Vengeful Shade unroot timer fix

- data/sql/updates/pending_db_world/rev_1733968037822883300.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20855
- Closes https://github.com/chromiecraft/chromiecraft/issues/7587
1.
2.
3. …
> fix(DB/Creature): Fix ZA bosses not despawning on evade

- data/sql/updates/pending_db_world/rev_1733966897261929100.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20879
- Closes https://github.com/chromiecraft/chromiecraft/issues/7591
1.
2.
3. …
> feat(Core/SAI): Implement SMART_ACTION_DISMOUNT (206)

- src/server/game/Entities/Player/Player.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17163
I didn't test it
https://github.com/azerothcore/azerothcore-wotlk/issues/17163 …
> Fix(Core/Player): Energy regen rate bonuses

- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/18787
1.
2.
3. …
> feat(Core/WorldObjects): implement Heartbeat timers

- data/sql/updates/pending_db_world/rev_1734169883724571000.sql
- Amani-shi Tempest - Thunderclap -> On victim with timers based on creatures with the same spell
- Amani'shi Warrior - Charge -> On Random hostile with timers based on creatures the same spell
- Amani'shi Protector - Mortal Strike -> On victim with timers based on creatures the same spell
- Amani'shi Protector - Cleave -> On victim with timers based on creatures the same spell
- Amani'shi Protector - Piercing Howl -> On self with timers based on creatures the same spell
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20882
- Closes https://github.com/chromiecraft/chromiecraft/issues/7600
- …
> fix(DB/SAI): several missing abilities in Zul'Aman

- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/20889
- Updates https://github.com/chromiecraft/chromiecraft/issues/7608
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Electric Storm shouldnt hit safe players

- src/server/scripts/Commands/cs_gm.cpp
- Closes #9787, but instead of adding a new command; the command will now accept either on/off or just toggles to whatever state is logically next.
E.g.
1.  gm fly on -> activates flying
2. gm fly -> flight is deactivated
1. Use a gm account
3. gm fly on -> flight is active
4. Fly in the air
5. .gm fly -> flight is inactive …
> feat(Core/Commad)Update gm fly to behave like a toggle

- src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20680
- Closes https://github.com/chromiecraft/chromiecraft/issues/7527#issue-2673696630
1.
2.
3. …
> fix(Script/ZulAman): Nalorakk abilities.

- src/common/GitRevision.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
I suppressed the cppcheck unknownMacro error because a specific macro is defined in a CMake file that cppcheck cannot read properly.
- Failing pipeline due to codestyle violations and cppcheck unknownMacro error.
I ran a codestyle check using the Python script and executed cppcheck locally.
A successful pipeline should be enough to merge this PR. …
> ci: fix codestyle and cppcheck reports

- src/cmake/macros/FindMySQL.cmake
cherry-pick from https://github.com/TrinityCore/TrinityCore/commit/ab046bdc327374878b3bede39f2d519d0aef3493
Note: Compare the TC PR, I've add a check for the minimal version o MySQL and I've remove MariaDB.
Note: I've add a function to check the minimal version of MySQL
- Closes 
1.
2.
3. …
> refactor(Deps/MySQL): replace hardcoded MySQL paths

- docker-compose.yml
This PR sets Mysql to the 8.4 LTS version
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20924
1. `docker compose build --no-cache`
2. `docker compose up`
3. It'll come up. …
> docker-compose: ac-database: bump to mysql LTS

- pull_request_template.md
The problem with the desire to switch back to GLP2+ as initiated here: https://github.com/azerothcore/azerothcore-wotlk/discussions/19868 , is that as well as hunting down the contributors of the last five years, you also have to worry about the new contributors who will be arriving until the process is complete. 
I suggest to add automatically an agreement in PR to avoid these issues. …
> chore(Licence): Add an agreement to relicense for futur PRs

- data/sql/updates/pending_db_world/rev_1734571285903931000.sql
Adds missing creature loot entries for Heavy stones and update min and max count for existing entries. 
I did not change drop chances for entries that had pretty specific ones like 2.66 or similar. I assume that these values are from sniffs, otherwise they would be oddly specific.  
- Closes #20967
1. 
2.
3. …
> fix(DB/Loot)Add missing heavy stone loot entries

- pull_request_template.md
Reverts azerothcore/azerothcore-wotlk#20910
Reverting this as further discussion is needed.
> Revert "chore(Licence): Add an agreement to relicense for futur PRs"

- apps/codestyle/codestyle.py
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Player/PlayerSettings.cpp
- src/server/game/Handlers/MiscHandler.cpp
- src/server/game/Instances/InstanceSaveMgr.h
> feat(CI/Codestyle); Check for double semicolons

- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/UnitDefines.h
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfo.cpp
- Closes 
Add naming for all ShapeshiftFlags
https://github.com/cmangos/mangos-wotlk/commit/fba2ab320d3dfb823ef2af83f8d01bd78f55e369
1.
2.
3. …
> refactor(Core/Unit): Add naming for all ShapeshiftFlags

- .github/workflows/codestyle.yml
- .github/workflows/core-build-nopch.yml
- .github/workflows/core_modules_build.yml
- .github/workflows/pr_labeler.yml
- .github/workflows/sql-codestyle.yml
> fix(CI): do not run on draft PRs

- src/server/game/Entities/Creature/TemporarySummon.cpp
- src/server/game/Entities/Creature/TemporarySummon.h
- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Maps/Map.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18882
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15911
1. Enter ICC and go to the Boss Lich King
2. I reached Phase 3 of the Lich King
3. Vile Spirits do not descend to attack Pets and Totems. …
> Core/TempSummons: avoid use MoveInLineOfSight before InitSummon

- src/server/scripts/Commands/cs_npc.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/18988
- Closes 
1.
2.
3. …
> fix(Script/Command): Allow guid for npc move and delete

- src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
Make Blood-Queen Lana'thel bite tanks by removing useless checks.
- None in the issues tab
As stated in various sources below:
https://www.reddit.com/r/wow/comments/2kgsbd/how_to_solo_blood_queen_lanathel_in_icc/
https://www.mmo-champion.com/threads/1123873-Solo-Blood-Queen-Lana-thel
https://www.wowhead.com/npc=37955/blood-queen-lanathel#comments;mode:n10
Blood-Queen Lana'thel should bite tanks. …
> fix(Scripts/IcecrownCitadel): Make Blood-Queen Lana'thel bite tanks as well

- src/server/game/AuctionHouse/AuctionHouseSearcher.cpp
Items with random property names or suffixes still require server side extracted locale dbcs as intended.
- Closes #21018
1.
2.
3. …
> fix(Core/Auctionhouse): Fix auctionhouse searches with locales other than enUS

- src/server/scripts/Kalimdor/CavernsOfTime/BattleForMountHyjal/instance_hyjal.cpp
- Closes #21003 
- Closes https://github.com/chromiecraft/chromiecraft/issues/6923
1.
2.
3. …
> fix(Scripts/Hyjal) First wave should not grant reputation

- src/server/shared/Network/NetworkThread.h
- Closes #21032 
- Follow-Up #20940
thanks @Takenbacon @walkline 
1.
2.
3. …
> fix(Core/Network): fix high idle cpu load in NetworkThread

- src/common/Logging/Appender.cpp
You test a seemingly useless third-party app, but doing so you find an error. Nice
- Closes 
1.
2.
3. …
> fix(Core/Log): fmt output for appender

- data/sql/updates/pending_db_world/rev_1734977925243177000.sql
> fix(DB/Creature)Ashtongue Stormcaller missing interrupt immunity

- data/sql/updates/pending_db_world/rev_1734978274366357000.sql
> fix(DB/Creature) Illidari Nightlord's Fear can be interrupted

- src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
> chore(Scripts/SSC): Move Vashj summons to the new format

- data/sql/updates/pending_db_world/rev_1735214037279163200.sql
- src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp
- src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/serpent_shrine.h
> fix(Scripts/SSC): Fix console panel gate not opening

- src/server/game/Spells/SpellMgr.cpp
Allows periodic effects to have initial threat and start combat immediately instead of waiting until the first tick.
https://github.com/TrinityCore/TrinityCore/commit/c8dc9fdc418d9703893e21603b7593b015f08fea
- Closes #16028
1.
2.
3. …
> fix(Core/Spells): Initial threat for periodic effects

- data/sql/updates/pending_db_world/update_gossip_menu.sql
Fixes gossip id for NPC 15297 Arcanist Helion. This should fix also the "missing" localization for all locales.
Fix was suggested by Kitzunu.
- Closes an unreported issue.
1.
2.
3. …
> fix(DB/Locale): deDE fix gossip id for Arcanist Helion

- data/sql/updates/pending_db_world/za-hostage-bandaid.sql
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20847 …
> fix(Scripts/Zul'Aman): Band-Aid fix for hostage loot.

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
title
- Closes 
[PATCH] [SD] Add Altar Torch Visuals for ZulAman
https://github.com/cmangos/mangos-wotlk/commit/9b48b2740f5c72874fe3c8e53b401729df05e086
1. Kill a boss
2. See if the altar torch shows
3. …
> fix(Scripts/ZulAman): add Altar Torch visuals

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20856
- Closes https://github.com/chromiecraft/chromiecraft/issues/7588
1. Engage {Akilzon, Halazzi, Nalorakk, Janalai, Zuljin}
2. Try to reset the boss by running away …
> fix(Scripts/ZulAman): add Boss Boundaries

- data/sql/updates/pending_db_world/rev_1735053928227867164.sql
Previously, when Drakuru was charmed, its current health remained the same as it was before charming, and only its max health was increased.
- Closes 
1. .q a 12686
2. .go c id 28802
3. use `Scepter of Empowerment` …
> fix(DB/SAI): restore Drakuru’s (id: 28802) health to 100% upon charming

- src/server/game/Entities/Player/PlayerStorage.cpp
> fix(Core/Player): fix output for disabled maps

- src/server/scripts/EasternKingdoms/ZulAman/boss_nalorakk.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20858
- Closes https://github.com/chromiecraft/chromiecraft/issues/7589
reset
```
.tele zulaman
.instance unbind all
```
tp
```
.go xyz 76.7682 1422 0.77 568 3.18
.cheat god on
``` …
> fix(Scripts/ZulAman): reset Nalorakk's intro on wipe

- data/sql/updates/pending_db_world/rev_1735913324331119200.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20661
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/20667
1.
2.
3. …
> fix(Scripts/ZulAman): Fix Jan'lai teleport spells

- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21085
- Closes https://github.com/chromiecraft/chromiecraft/issues/7664#issue-2766908573 …
> fix(Scripts/ZulAman): make Zul'Jin p3 cyclones go to random targets

- data/sql/updates/pending_db_world/fix_quest_offer_8346.sql
fixes wrong german quest offer reward for quest 8346
- Closes 
1.
2.
3. …
> fix(DB/Locale): deDE fixes for quest offer reward entry 8346

- data/sql/updates/pending_db_world/rev_1735703152636383200.sql
- Closes 
1. .go c 125392
2. wait
3. …
> fix(DB/SAI): Add dialogue between creature argah 27440 and creature sagai 27441

- data/sql/updates/pending_db_world/rev_1736079931234163195.sql
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20416
- Closes https://github.com/chromiecraft/chromiecraft/issues/7456#issue-2618355102
[PATCH] Implement Amani'shi Scout AI
https://github.com/cmangos/mangos-wotlk/commit/09fa379c88453daaa59e461427dae0229ca6c151#diff-e3d7ab743f3eb4e7b0414fea9f8733bb469a22c95dbf952bd475395e42d283cfR1531
`.go xyz -221.09 1409.1 0 568 4.98`
1.
2. 
3. …
> fix(Scripts/ZulAman): add Scout run to drums

- data/sql/updates/pending_db_world/rev_1736093307962776687.sql
These creatures have an entry `HEALTH_PCT` where Min% equals Max%. If the mob takes a high enough hit to skip this health threshold, it also skips the action. 
- https://github.com/azerothcore/azerothcore-wotlk/blob/fd4019c0741c810e3af5feba095e364c70098dfe/src/server/game/AI/SmartScripts/SmartScript.cpp#L4049
This adjusts the entries for some creatures where `event_type = 2 && event_param1 = event_param2`. 
- Closes 
1.
2.
3. …
> fix(DB/SmartAI): `HEALTH_PCT` where Min equals Max

- data/sql/updates/pending_db_world/rev_1736106102651280100.sql
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21088
1.
2.
3. …
> fix(Scripts/ZulAman): Fix initial pack not chasing distant players

- src/server/scripts/EasternKingdoms/ZulAman/boss_halazzi.cpp
> refactor(Scripts/ZulAman): clean up Helazzi code

- src/common/Utilities/TaskScheduler.cpp
- src/common/Utilities/TaskScheduler.h
- src/server/scripts/EasternKingdoms/ZulAman/boss_akilzon.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20751
- Closes https://github.com/chromiecraft/chromiecraft/issues/7558 …
> fix(Scripts/ZulAman): make sure Malacrass timer is delayed only when it should be triggered during channel of Spirit Bolts

- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Motd/MotdMgr.cpp
- src/server/scripts/Commands/cs_npc.cpp
- src/server/scripts/Commands/cs_send.cpp
> fix(Core/Misc): Correct some fmt logs

- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
Adds a X coord check to invalidate the world trigger near Jana'lai as a valid hut
```
X: -80 south of Jana'lai stairs
X: -112 hut
```
- Closes 
1.
2.
3. …
> fix(Scripts/ZulAman): Scout's hut search should ignore the world trigger near Jan'alai

- data/sql/updates/pending_db_world/rev_1736536297178305597.sql
- src/server/scripts/EasternKingdoms/ZulAman/boss_zuljin.cpp
- Closes 
```
.go c id 23863
```
1. Enter Eagle phase
2. Cast Chain Lightning on adds
3. Expect only 1 Zap cast …
> fix(Scripts/ZulAman): Zul'jin Add Cooldown to EnergyStorm proc

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
> fix(Scripts/ZulAman): Fix Hexlord gate not opening after crashes

- data/sql/updates/pending_db_world/rev_1736546523943069600.sql
- src/server/scripts/Commands/cs_instance.cpp
Display all states instead of searching 1 by 1
- Closes 
1.
2.
3. …
> feat(Scripts/Commands): Update GetBossState to display all states

- data/sql/updates/pending_db_world/rev_1736551855453244500.sql
- src/server/game/Miscellaneous/Language.h
- src/server/scripts/Commands/cs_misc.cpp
> feat(Scripts/Commands): Implement opendoor command

- data/sql/updates/pending_db_world/rev_1736537763501202700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7675
1.
2.
3. …
> fix(DB/Creature): Akil'zon interrupt immunity

- data/sql/updates/pending_db_world/rev_1736550580324276200.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20194
1.
2.
3. …
> fix(DB/SAI): Fix Marauding Bursters repositioning in combat

- modules/CMakeLists.txt
- src/server/game/CMakeLists.txt
- Closes 
- [ x ] Tested in-game by the author.
1. Clone this PR
2. Clone source from [mod-eluna](https://github.com/azerothcore/mod-eluna/pull/209)
3. …
> (Modules/CMakeList): Update CMakeLists for modules to allow Eluna to switch Lua version

- data/sql/updates/pending_db_world/rev_1736627805988028300.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7655
- `.go c i 10639` // doesn't have a weapon now …
> fix(DB/Creature) - Removes weapons from Rorgish Jowl

- data/sql/updates/pending_db_world/rev_1736616775226885710.sql
- Actually closes https://github.com/chromiecraft/chromiecraft/issues/7513
https://github.com/chromiecraft/chromiecraft/issues/7513#issuecomment-2490780940
1.
2.
3. …
> fix(DB/Loot): Malacrass should drop 2 pieces of loot and sometimes Tiny Vodoo Mask

- src/server/game/Maps/Map.cpp
> fix(Core/Map): Fix crash OnPlayerLeave()

- data/sql/updates/pending_db_world/rev_1736654302862534200.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7676
- Closes #21146 
https://www.youtube.com/watch?v=rNdIKVm2d0U
1.
2.
3. …
> fix(DB/Creature) Sunfury Bloodwarder do not intercept anymore

- data/sql/updates/pending_db_world/rev_1736798670655210700.sql
Thanks @heyitsbench for the wotlk sniff.
This fixes the wrong texts and wrong formats:
Text will be like this (corrcet)
```
Arellas Fireleaf
High Wizard of the Scarlet Crusade 
Citizen of Quel'Thalas  
Locked in eternal combat with the Necromancer Diesalven
```
instead of some (incorrcet)
```
Arellas Fireleaf
High Wizard of the Scarlet Crusade 
Citizen of Quel'Thalas  
Locked in eternal combat with the Necromancer Diesalven
```
- Closes https://github.com/chromiecraft/chromiecraft/issues/2723
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10007
This PR …
> fix(DB/page_text) - Added Sniffed Texts to the plaques in Hall of Champions (Scarlet Monastery Armoury)

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.h
> fix(Scripts/ZulAman): Store chest count in DB

- data/sql/updates/pending_db_world/rev_1736530112429984785.sql
- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
Add fast respawns to Protectors and Wind Walkers if Akilzon's gauntlet has not been started.
Add Eagle Trash Triggers to avoid skipping the event at 70. You can skip the event at 80 by avoiding the Scout.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20880
> [Wotlk Classic](https://youtu.be/HcOv22AZ5Vg?t=139) at 2:19 , level 80 paladin hugging the wall and going past [Amani'shi Lookout](https://wowgaming.altervista.org/aowow/?npc=24175) and start attacking mobs without triggering the event .
1. `.go c id 24175`
2. Try to skip the …
> fix(Scripts/ZulAman): Akilzon Gauntlet hyperspawn, handling Eagle Trash Triggers

- data/sql/updates/pending_db_world/karabor-fix.sql
> fix(DB/Spell): Correct map ID for Medallion of Karabor.

- data/sql/updates/pending_db_world/rev_1736985935365008000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21179
1.
2.
3. …
> fix(DB/SAI): Amani Lynx shouldn't use dash

- data/sql/updates/pending_db_world/rev_1736987711191058900.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21178
1.
2.
3. …
> fix(DB/SAI): Tamed Amani Crocolisk abilities

- data/sql/updates/pending_db_world/karabor-sniffed.sql
This PR:
1. Equip Blessed Medallion of Karabor.
2. Use the item.
3. Observe your teleported position. …
> fix(DB/Spell): Add sniffed data for Medallion of Karabor.

- .github/ISSUE_TEMPLATE/feature_request.yml
> refactor(Github/Misc): Deprecate Suggestion label and use Github Type

- data/sql/updates/pending_db_world/rev_1737076652910686700.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/6416
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19965
1.
2.
3. …
> fix(DB/Creature): Remove rooted inhabit type from Coilfang Beast Tamer

- src/server/game/Maps/Map.cpp
- src/server/scripts/Commands/cs_ban.cpp
- src/server/scripts/Commands/cs_debug.cpp
- src/server/scripts/Commands/cs_mmaps.cpp
- src/server/scripts/Commands/cs_wp.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21190
1.
2.
3. …
> fix(Core/Misc): Resolve output formatting issues with fmt library

- data/sql/updates/pending_db_world/rev_1737057271097545900.sql
- src/server/scripts/Commands/cs_wp.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21158
1.
2.
3. …
> fix(Script/WP): correct output of wp show command

- src/server/game/Entities/Unit/Unit.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20994
1.
2.
3. …
> fix(Core/Unit): Fix fast creatures chasing indefinitely

- src/server/game/Entities/Player/PlayerStorage.cpp
If you had spells in your action bar that you shouldn't (as you don't have learnt (permantly) they get removed with a vague error message):
changed to:
values referenced from `acore_characters.character_action` (this value before reloging)
As before will shows if multiple errors but more information :)
- Closes N/A
- Make a warlock // Any class works for this, my tests were with a warlock.
- `.learn all my class`
- Place `Chaos Bolt` (from `Destruction`) in any of action bars // Any spell that you gain from `.learn all my class` that shouldn't stay …
> feat(Core) - Additional "ActionButton" log information.

- src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp
> fix(Scripts/Naxxramas): fixed invalid horseman state on instance init

- src/server/game/Globals/ObjectMgr.cpp
> fix(Core/ObjectMgr): Potential crash in GetModuleString()

- src/server/game/Entities/GameObject/GameObject.cpp
- this can happen if player is e.g. not eligible for any loot due to conditions
- ensure fallback to default loot gets triggered correctly in this case
- Closes #21141
- Closes chromiecraft/chromiecraft#7651
1.
2.
3. …
> fix(Core/Gameobject): prevent getting empty fishing loot

- src/server/game/ArenaSpectator/ArenaSpectator.cpp
- src/server/game/Chat/Channels/Channel.cpp
- src/server/game/Chat/Channels/Channel.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Player/PlayerUpdates.cpp
- src/server/game/Handlers/ChannelHandler.cpp
- src/server/game/Handlers/LFGHandler.cpp
- src/server/scripts/Commands/cs_misc.cpp
* progress https://github.com/azerothcore/azerothcore-wotlk/issues/2756
This prevents the LFG channel from being added to the client when logged in, which causes some issues. At LFG join, JoinChannel() is called but does not add the channel for the client. However, if you do "/join LookingForGroup" while in queue, you will join the channel, and after that, it will add/remove you from the channel correctly with the LFG tool.
* progress https://github.com/azerothcore/azerothcore-wotlk/issues/2756
1. config `Channel.RestrictedLfg = 1`
2. Join LFG
3. /join …
> refactor(Core/Player): Improve Channel.RestrictedLfg handling

- src/server/game/Instances/InstanceScript.cpp
- src/server/game/Instances/InstanceScript.h
- src/server/game/Maps/Map.cpp
> fix(Core/Instances): Ensure team is acquired before spawning creatures

- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
Fix phoenix not disappearing after wipe
- Closes #21231
1. .go c id 24664
2. Wait for phoenix 
3. .die and observe …
> fix(Scripts/MagistersTerrace) Pheonix will now reset after death

- data/sql/updates/pending_db_world/rev_1737600555496919400.sql
> fix(DB/Creature): Felblood Kael'thas should despawn on evade

- data/sql/updates/pending_db_world/rev_1737602003829088500.sql
- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
> fix(Scripts/MagisterTerrace): Implement missing Kaelthas text line

- data/sql/updates/pending_db_world/rev_1737598069427538700.sql
its a proc aura
blizzard later added an icon to it in later game versions
- Closes 
1.
2.
3. …
> fix(DB/Creature): Correct Sunblade Sentinel fel lightning

- data/sql/updates/pending_db_world/rev_1737641541738329200.sql
- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
[0]  Entry: 24666
[0] MovementFlags: 1536 (DisableGravity, Root)
- Closes 
1.
2.
3. …
> fix(DB/Creature): Fix Flamestrike inhabit types

- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.h
They were using... Tempest Keep ids.
- Closes 
1.
2.
3. …
> fix(Scripts/MagisterTerrace): Fix Phoenixes and eggs not despawning

- data/sql/updates/pending_db_world/rev_1737730013774604750.sql
Remove Normal loot from all HC Bosses
Group items of Kael'thas
- Closes #21259
Counting drops in multiple videos
https://youtu.be/vRjgCtDOzo8
https://youtu.be/eps9m8S4cLc
https://youtu.be/nKSSYAkpW_s
https://youtu.be/o1FaN1_JIug
https://youtu.be/4ZHh5UhkGIE
https://youtu.be/My5ZrCZ8mok
https://youtu.be/L-eWJ_TdMSE
https://youtu.be/g5oA9_0s8CY
https://youtu.be/kVF_Di5CRKo
https://youtu.be/xkJysd5YOHI
https://youtu.be/C7nMa-cM4pI
https://youtu.be/13EsTeJmiPQ
https://youtu.be/kfZoZ5EVNCo
https://youtu.be/AN27RLSZXu4
https://youtu.be/eFILcvIVrEo
https://youtu.be/9MierCOmCmA …
> fix(DB/Loot) Clean up loot of bosses in MGT HC

- apps/codestyle/codestyle-sql.py
These cases fail when I feel they shouldn't. This should improve checks: INSERT safety and Missing semicolon check.
```
--
DELETE FROM `table` WHERE `column` = 1;
-- comment
INSERT INTO `table` (`column`) VALUES(1);
DELETE FROM `table` WHERE `column` = 1;
INSERT INTO `table` (`column`) VALUES
-- comment
(1);
DELETE FROM `table` WHERE `column` = 1;
INSERT INTO `table` (`column`) VALUES
(1); -- comment
```
- Closes 
1.
2.
3. …
> fix(Apps/Codestyle): ignore comments for some checks

- data/sql/updates/pending_db_world/rev_1737721489253815600.sql
> fix(DB/SAI): Correct Phoenix/Egg rebirth and combat behaviour

- src/server/game/Handlers/AuctionHouseHandler.cpp
- Closes 
Progress on issue in this comment https://github.com/azerothcore/azerothcore-wotlk/issues/21140#issuecomment-2600822545 
1.
2.
3. …
> fix(Core/Auction):  Fix  usable item search in auction

- .github/SECURITY.md
Preview of the changes below.
If you guys like the way is formated / organised on the preview below, assist me in correcting the content / information of it.
--- preview ---
<details>
<summary>Click me to preview</summary>
We support the following versions of dependencies.
| Icon                 |      Meaning      |
| :------------------- | :---------------: |
| :white_check_mark:   |   **Supported**   |
| :red_circle:         | **NOT** Supported |
| :large_blue_diamond: |  **Recommended**  |
| AzerothCore Branch           |       Status       |     Recommended      |
| ---------------------------- | :----------------: | :------------------: |
| **master**                   | :white_check_mark: | :large_blue_diamond: |
| Any non-official fork        |    :red_circle:    | …
> SECURITY.md File Update 

- src/server/game/Entities/Unit/Unit.h
> feat(Core/Unit): Implement SetEmoteState() and ClearEmoteState() helpers

- data/sql/updates/pending_db_world/rev_1737933911029419400.sql
- src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.h
- Kael only starts roleplay once all mobs in front of him die
- Kael doesnt auto engage combat after roleplay
- Added talk animation from sniffs
- Closes 
1.
2.
3. …
> fix(Scripts/MagisterTerrace): Rescript Kael's intro

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
Before, when spawning, Madrigosa would drop to the ground and just walk, never reaching her target. Now she flies properly like she’s supposed to.
- Closes 
1. .tele sunwell
2. go to brutallus …
> fix(Scripts/SunwellPlateau): Fix Madrigosa flight movement

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
Before, Felmyst wouldn’t start the fight because the UpdateVictim check didn’t let the scheduler start counting time, so GROUP_START_INTRO never began.
- Closes [#21137](https://github.com/azerothcore/azerothcore-wotlk/issues/21137)
1. .tele sunwell
2. go to Felmyst …
> fix(Scripts/SunwellPlateau): Fix Felmyst start fight

- data/sql/updates/pending_db_world/rev_1738383337286562100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21225
1.
2.
3. …
> fix(DB/SAI): Fix Brightscale Wyrm Energy Infusion

- apps/codestyle/codestyle-sql.py
- data/sql/updates/db_world/2025_01_31_01.sql
- data/sql/updates/pending_db_world/rev_1738424678783288000.sql
> fix(DB/Misc): Bad delete in update file

- data/sql/updates/pending_db_world/rev_1738513021010110800.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp
- src/server/scripts/EasternKingdoms/SunwellPlateau/sunwell_plateau.h
> fix(Scripts/SunwellPlateau): Remove Sunwell Radiance from mobs

- src/server/scripts/EasternKingdoms/ZulAman/instance_zulaman.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7712
1.
2.
3. …
> fix(Script/ZulAman): Don't start the timer before Harrison Johnes event

- apps/codestyle/codestyle-sql.py
- data/sql/updates/pending_db_world/rev_1737290143156167600.sql
> feat(CI/Codestyle): backtick check for sql

- apps/installer/includes/os_configs/windows.sh
> fix(CI/windows): fix windows build

- data/sql/updates/pending_db_world/rev_1738706570230156800.sql
- src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21298
1.
2.
3. …
> fix(Scripts/Spells): Fix Isle of Queldanas Orb of Translocation

- data/sql/updates/pending_db_world/rev_1738799729653359300.sql
> fix(DB/Creature): Kalecgos should despawn on evade

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
> fix(Scripts/SunwellPlateau): Felmyst should be invincible while flying

- data/sql/updates/pending_db_world/rev_1738805488347916800.sql
> fix(DB/Text): Fix Brutallus text language

- src/server/game/Battlefield/Battlefield.cpp
Wintergrasp spawns an invisible creature with TEAM_NEUTRAL, which isn't defined in the array.
- https://github.com/azerothcore/azerothcore-wotlk/blob/b717893309dc5d48b1b4562aa1700c151745267f/src/server/game/Battlefield/Battlefield.h#L58
asan log https://gist.github.com/sogladev/6f502c3443a8b523b867db4f811776f6
- Closes 
1.
2.
3. …
> fix(Core/Battlefield): Wintergrasp out of bounds error when setting neutral faction of stalker

- src/server/scripts/Northrend/zone_dalaran.cpp
fixes horde player teleport when dalaran sewer pipe is entered 
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/4467 …
> fix(Scripts/Northrend): Exclude Dalaran Sewer Exit Pipe from GUARD teleport checks

- apps/codestyle/codestyle-sql.py
> fix(CI/Codestyle): Ignore comments for backtick check

- data/sql/updates/pending_db_world/rev_1738882510999997527.sql
- Closes 
This patrol is missing its mount 
shows up in a video, but I would need a sniff to confirm https://youtu.be/sOouX5t7tuE?si=9zjFzxXQVmfFkrlx&t=85
`.go c 94387`
1.
2.
3. …
> fix(DB/CreatureAddon): add hawkstriker mount to Sun's Reach patrol

- apps/codestyle/codestyle-sql.py
> fix(CI): typo

- data/sql/updates/pending_db_world/rev_1738910632654611022.sql
Hi, my first contribution to this wonderful project. I hope the workflow is correct and don't hesitate to correct me if I'm wrong. You can also find me on discord with my username.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21331
- Closes https://github.com/chromiecraft/chromiecraft/issues/7737#issue-2825135374
1.
2.
3. …
> fix(DB/Creature) Enable mining for Iron Rune Sentinel

- data/sql/updates/pending_db_world/Thornvine_Creeper.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21332
- Closes https://github.com/chromiecraft/chromiecraft/issues/7732#issue-2825129360
1.
2.
3. …
> fix(DB/Creature) Thornvine Creeper is skinnable with herbalism.

- data/sql/updates/pending_db_world/rev_1738947261551581149.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20964
- Closes https://github.com/chromiecraft/chromiecraft/issues/7612
1.
2.
3. …
> fix(DB/Quest): Remove Failed Incursion requirement from Lost in Action

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/PlayerUpdates.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Handlers/ItemHandler.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Miscellaneous/Formulas.cpp
> feat(Core/Creature): Implement HasFlagsExtra() helper to creature

- data/sql/updates/pending_db_world/kael-heroic-spheres.sql
> fix(DB/Creature): Correct run speed of Kael'thas's Arcane Spheres on heroic.

- src/server/game/World/WorldState.cpp
fix 
> .worldstate sunsreach counter 0 2 also changing the counter on the gate
due to faulty printout
- Closes 
1.
2.
3. …
> fix(Core/Worldstate): sunsreach print correct counter

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7765
1.
2.
3. …
> fix(Scripts/SunwellPleateau): Remove invincibility from human kalecgos

- data/sql/updates/pending_db_world/rev_1739154549891882300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21373
- Closes https://github.com/chromiecraft/chromiecraft/issues/7774
1.
2.
3. …
> fix(DB/SAI): Fix Doomfire Shard Avenging Wrath spell

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
> fix(Scripts/SunwellPlateau): Clear basic events on death

- apps/codestyle/codestyle-cpp.py
- src/server/scripts/Commands/cs_worldstate.cpp
> fix(CI/Codestyle): correct double semicolon check

- src/server/game/Loot/LootItemStorage.cpp
Steps to reproduce:
1. Obtain an item like this bag - https://www.wowhead.com/wotlk/item=46007.
2. Loot everything from the bag except the gold.
3. Log out.
4. Log in again.
5. The bag now contains new items to loot.
- Closes 
1.
2.
3. …
> fix(Core/Items): Fix duplication exploit where a player could loot infinitely from bags containing gold.

- src/server/game/AI/CoreAI/UnitAI.h
- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/scripts/EasternKingdoms/ZulAman/boss_janalai.cpp
- src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
- src/server/scripts/Northrend/IcecrownCitadel/boss_blood_prince_council.cpp
- src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
This mirrors the DamageTaken() hook
- Closes 
1.
2.
3. …
> feat(Core/Unit): Add SpellSchoolMask info to the DamageDealt() hook

- src/server/game/Conditions/DisableMgr.cpp
- src/server/game/Conditions/DisableMgr.h
Small change, removes a silly double map storage type when a single unordered_map and an array is plenty sufficient.
1.
2.
3. …
> fix(Core/Disables): Optimize DisableMgr container

- data/sql/updates/pending_db_world/rev_1739377505525423100.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7757
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21408
1.
2.
3. …
> fix(DB/Creature): Sacrolash and Alythess should be taunt immune

- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
> fix(Core/Scripts): Fix buffer-overflow errors in scripts.

- src/server/game/Guilds/Guild.cpp
> fix(Core/Guild): Fix use of guild members' data after deletion.

- src/server/game/Server/WorldSession.cpp
Fixes heap-use-after-free error:
```
==230820==ERROR: AddressSanitizer: heap-use-after-free on address 0x62800186fb60 at pc 0x5555580e8341 bp 0x7fffffffcab0 sp 0x7fffffffcaa8
WRITE of size 8 at 0x62800186fb60 thread T0
#0 0x5555580e8340 in Player::SetGroupInvite(Group*) /opt/wotlk_prod/src/server/game/Entities/Player/Player.h:2463:55
#1 0x5555580e8340 in Group::RemoveAllInvites() /opt/wotlk_prod/src/server/game/Groups/Group.cpp:363:21
#2 0x5555580e8340 in Group::Disband(bool) /opt/wotlk_prod/src/server/game/Groups/Group.cpp:819:5
#3 0x5555580e3399 in Group::RemoveMember(ObjectGuid, RemoveMethod const&, ObjectGuid, char const*) /opt/wotlk_prod/src/server/game/Groups/Group.cpp
#4 0x555557a8dbe4 in Player::RemoveFromGroup(Group*, ObjectGuid, RemoveMethod, ObjectGuid, char const*) …
```
> fix(Core/Group): Fix use of a deleted pointer in the group invites list.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21371
- Closes https://github.com/chromiecraft/chromiecraft/issues/7762
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Fix Brutallus burn timer

- data/sql/updates/pending_db_world/rev_1739149791709679700.sql
- src/server/scripts/Northrend/Naxxramas/boss_faerlina.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/7768
1.
2.
3. …
> fix(Scripts/Naxxramas): Update Faerlina script

- data/sql/updates/pending_db_world/rev_1739410685005818200.sql
- src/server/scripts/EasternKingdoms/MagistersTerrace/instance_magisters_terrace.cpp
- src/server/scripts/EasternKingdoms/MagistersTerrace/magisters_terrace.h
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp
> fix(Scripts/SunwellPlateau): Fix Felmyst death event

- src/server/apps/worldserver/worldserver.conf.dist
> chore(Config): Improve DynamicRates description

- src/server/game/Combat/ThreatMgr.cpp
- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp
- src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
- src/server/scripts/Outland/TempestKeep/Mechanar/boss_nethermancer_sepethrea.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21404
- Closes https://github.com/chromiecraft/chromiecraft/issues/7753
1.
2.
3. …
> fix(Core/Creature): Creatures should skip confused targets

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Maps/Map.h
> fix(Core/Map): Dynamic respawns: preserve original respawn timer and skip rares

- src/server/scripts/Outland/BlackTemple/boss_illidan.cpp
> urand returns a random number in the range min..max (inclusive)
before: 0, 1, 2, 3, 4
after: 0, 1, 2, 3
asan @walkline  https://gist.github.com/walkline/a325b0268b8b4a74ccaddc7eb6e2c181
fixes out of bounds + refactor recursion
- Closes 
1.
2.
3. …
> fix(Scripts/BlackTemple): Illidan buffer overflow

- src/server/scripts/Outland/zone_shadowmoon_valley.cpp
previous: the final wave 4 (counter 3) attempts to set timer for the next wave
asan @walkline L67 https://gist.github.com/walkline/a325b0268b8b4a74ccaddc7eb6e2c181
fixes global-buffer-overflow
- Closes 
1.
2.
3. …
> fix(Scripts/ShadowmoonValley): Illidan buffer overflow

- src/server/game/Handlers/SpellHandler.cpp
move was used originally to avoid copying, but the pointer to recvpacket is still used afterwards in `WorldSession::Update`  (`packet`) which can lead to undefined behavior. So, let's copy instead
- https://github.com/azerothcore/azerothcore-wotlk/blob/3854d00dee336ea9331b1f6a627fd117b017c16b/src/server/game/Server/WorldSession.cpp#L325
- Closes 
This  likely doesn't fix related crashes but I'll mention it for linking
- https://github.com/azerothcore/azerothcore-wotlk/issues/21427
1.
2.
3. …
> fix(Core/Player): SpellQueue avoid possible undefined behavior by copying instead of move

- src/server/scripts/Spells/spell_shaman.cpp
Lightning shield from 8/8 T2 shaman set proc (id: 23552) was doing damage to the shaman instead of the attacker
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21358
1.
2.
3. …
> fix(Scripts/Spells): Corrected shaman 8/8 T2 set bonus damage proc

- apps/installer/includes/os_configs/windows.sh
> fix(CI/Windows): Bump openssl version

- src/server/game/Entities/Creature/Creature.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21455
1.
2.
3. …
> Fix(Core): random heroic dungeon

- apps/codestyle/codestyle-sql.py
corrected wrong text in the sql codestyle check, was printing "No DELETE keyword found AFTER the INSERT" when it should "No DELETE keyword found BEFORE the INSERT"
- Closes 
1.
2.
3. …
> fix(Apps/Codestyle) corrected wrong text in the sql codestyle check

- src/server/scripts/Northrend/Naxxramas/boss_maexxna.cpp
maexxnas door was open when faerlina alive
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21170
1.
2.
3. …
> fix(Scripts/Naxxramas)

- data/sql/updates/pending_db_auth/rev_1739664850515709200.sql
- data/sql/updates/pending_db_characters/rev_1739664807403132000.sql
- data/sql/updates/pending_db_world/rev_1739663978360122100.sql
- src/server/apps/worldserver/worldserver.conf.dist
- src/server/database/Updater/UpdateFetcher.cpp
- src/server/database/Updater/UpdateFetcher.h
will import pending files
if you run default config files the orphaned entry will be deleted once the pending file is deleted
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21195
1.
2.
3. …
> feat(Core/DBUpdater): include pending path

- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfo.cpp
* Fixed item level requirements for enchanting spells
* cherry-pick (https://github.com/TrinityCore/TrinityCore/commit/243314806ff10d9cd4a7595cb48a7bb5878058d6)
- Closes 
1.
2.
3. …
> fix(Core/Spells): Implement SPELL_ATTR2_ALLOW_LOW_LEVEL_BUFF

- data/sql/updates/pending_db_world/fix-quest-11880.sql
- Closes chromiecraft/chromiecraft#7796
1. create alliance character
2. .character level 70
3. .go quest starter 11880
4. verify you can grab quest
5. repeat for horde character …
> fix(DB/Quest): Allow both factions to get quest "The Multiphase Survey" [id: 11880]

- src/server/game/Grids/Cells/CellImpl.h
- src/server/game/Grids/GridDefines.h
- src/server/game/Grids/GridTerrainLoader.cpp
- src/server/game/Grids/GridTerrainLoader.h
- src/server/game/Maps/MapMgr.cpp
- src/server/scripts/Commands/cs_misc.cpp
- src/server/scripts/Commands/cs_mmaps.cpp
Standardizes gridcoord calculation, fixes super rare edge case of returning wrong terrain data values due to calculation differences causing a precision issue. I have only done some brief testing so far and would highly suggest some additional testing.
Example reproduction with both types of calculation, same position returning different GridCoord: https://onlinegdb.com/LAwbPzWvu
- Closes #21472
1.
2.
3. …
> fix(Core/Grids): Standardize grid coordinates

- src/server/game/Server/WorldSession.cpp
> fix(Core/Server): Add bytebuffer exception handling to addoninfo read

- apps/ci/ci-install-modules.sh
> chore(CI): Add mod-arena-3v3-solo-queue.git

- data/sql/updates/pending_db_world/fix-npc24238.sql
Fixed Bjorn Halgurdsson behavior.
All changes ~sniffed~ gathered from very old WotLK video: [Youtube](https://www.youtube.com/watch?v=fIVgxv8TmW8)
and from Legion video: [Youtube](https://www.youtube.com/watch?v=0QfWvcoWwN8)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21447
- Closes https://github.com/chromiecraft/chromiecraft/issues/7750
1. .quest add 12481
2. .go c id 24238
3. Insult him using the script in your bags
4. Run away and watch him
You can …
> fix (DB/SAI) [Howling Fjord] Bjorn Halgurdsson behavior

- apps/ci/ci-install-modules.sh
> chore(CI): Add mod-costumes

- src/server/game/Maps/Map.cpp
- src/server/game/Maps/MapInstanced.cpp
- src/server/game/Maps/MapInstanced.h
- src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/instance_forge_of_souls.cpp
Caused by grids now being loaded before instance script `_teamIdInInstance` value was set. Please test and verify.
- Closes #21529
1.
2.
3. …
> fix(Core/Maps): Fix instance factions

- data/sql/updates/pending_db_world/rev_1740172521802548800.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21568
1.
2.
3. …
> fix(DB/SAI): Fix Kael Flamestrikes chasing players

- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
This fixes hard CC from triggering the summoning event.
Previously, expiration of hard cc remove point movement, which triggers the MovementInform to start the summon event. Now, we move to the Drum trigger NPC directly and periodically check range to see if we're near the Drum to start the summoning.
- Closes 
```
.go xyz -210.86 1409 0 568 5
```
hard cc like Repentance
```
.cast 20066
```
1. Aggro a scout
2. CC it
3. See if it still runs to a Drum and summon reinforcements …
> fix(Scripts/ZulAman): scout drum and hard CC interaction

- data/sql/updates/pending_db_world/rev_1739972100933255718.sql
- Closes 
https://www.wowhead.com/wotlk/npc=24723/selin-fireheart
https://www.wowhead.com/wotlk/npc=24744/vexallus
https://www.wowhead.com/wotlk/npc=24560/priestess-delrissa
https://www.wowhead.com/wotlk/npc=24664/kaelthas-sunstrider
1.
2.
3. …
> fix(DB/Creature): let Magister's Terrace Normal bosses give reputation until exalted and reduce Kael'thas reputation gain

- src/server/scripts/Spells/spell_hunter.cpp
Misdirection should not trigger from mend pet.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20824
- Closes https://github.com/chromiecraft/chromiecraft/issues/5137
In issues …
> fix(Core/Spells): Fixed misdirection triggering from mend pet

- data/sql/updates/pending_db_world/rev_1740180429215360500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21572
1.
2.
3. …
> fix(DB/Creature): Fix Steel Gate Flying Machine inhabit type

- src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21566
- Closes https://github.com/chromiecraft/chromiecraft/issues/7831
1.
2.
3. …
> fix(Core/Spells): Ingvar Smash and Dark Smash should not ignore LOS

- src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp
> fix(Scripts/OutdoorPvP): Fix Halaa guards not spawning

- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Handlers/QueryHandler.cpp
This pull request includes several changes aimed at improving logging messages and fixing data type inconsistencies. The most important changes include updating log messages for clarity and correcting the data type of the `NextPage` field in the `PageText` structure.
Logging improvements:
* [`src/server/game/Globals/ObjectMgr.cpp`](diffhunk://#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242R5851-R5855): Added a warning log message for an empty `page_text_locale` table in the `LoadPageTextLocales` method.
* [`src/server/game/Globals/ObjectMgr.cpp`](diffhunk://#diff-59e59afabb9e07b951f9cd43dc7ef08e8c894b2aa889ae394fc4ace2eef09242L5879-R5883): Corrected the log message to reference the correct table `instance_template` instead of `page_text` in the …
> fix(Core/Misc): Fix NextPage Data Type in PageText Structure and Improve Logging Messages

- src/server/game/Spells/SpellInfoCorrections.cpp
Previously, the stun radius was considerably larger than the damage radius.
- Closes #20613
1.
2.
3. …
> fix(Core/Spells): Fix "Repelling Wave" stun radius

- apps/codestyle/codestyle-sql.py
found here https://github.com/azerothcore/azerothcore-wotlk/actions/runs/13483297958/job/37671226530?pr=21590
- Closes 
1.
2.
3. …
> fix(CI/Codestyle): skip SQL keyword 'NOT'

- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- src/server/game/AI/ScriptedAI/ScriptedCreature.h
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
> feat(Core/Scripting): Implement ScheduleEnrageTimer() helper

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
> fix(Scripts/SunwellPlateau): Fix twins respawn

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
Previously, "Flame Sear" applied "Flame Touched" stacks with every damage tick (every 500ms), but now it applies them once when the spell is cast and 5 times over the next 6 seconds.
- Closes #21578
I don't consider this issue accurate. From what I've seen, the damage should indeed be dealt every 500ms, but there is an issue with the "Flame Touched" stacks.
1.
2.
3. …
> fix(Scripts/SunwellPlateau) Fix flame touched stacking

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
> fix(scripts/SWP): remove whitespaces to fix codestyle check

- src/server/scripts/Spells/spell_rogue.cpp
Previously, the talent "Prey on the Weak" would trigger on dead targets, which could, for example, cause a character to stand up or interrupt actions like eating.
- Closes 
1. Create rogue
2. Get "Prey on the Weak" talent
3. Kill enemy
4. Sit down or start eating while targeting the victim's corpse …
> fix(Core/Spell) Removed Prey on the Weak triggering on dead targets

- data/sql/updates/pending_db_world/Volatile_Fiend.sql
This PR will also fix behaviour issues that I noted during my checks on WoW Retail.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7772
1.
2.
3. …
> fix(DB/Creature) Volatile Fiends now reach the end of the ramp.

- data/sql/updates/pending_db_world/SwP_Scout_Formations.sql
The related issues can only be considered completely solved when this [PR](https://github.com/azerothcore/azerothcore-wotlk/pull/21613) is also merged.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21612
- Closes https://github.com/chromiecraft/chromiecraft/issues/7771
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20995
- Closes https://github.com/chromiecraft/chromiecraft/issues/7470
1.
2.
3. …
> fix(DB/Creature) Add formations to Scout's packs.

- data/sql/updates/pending_db_world/Scout_text.sql
> fix(DB/Text) Add correct text on Sunblade Scouts.

- src/server/scripts/Northrend/zone_wintergrasp.cpp
WG related NPC, like [Arcanist Braedin](https://www.wowhead.com/wotlk/npc=32169/arcanist-braedin#abilities), should use a Frost Armor spell on themselves. And that spell should last 30 minutes.
Right now they cast another frost armor spell, which lasts only a couple of second. 
This PR changes that spell.
.go creature id 32169 //alliance
.go creature id 32170 //horde
click on NPC. Observe "Frost Armor" holding for 30 minutes. …
> fix (Core/Wintergrasp) Change spell used by WG NPCs

- src/server/game/Battlefield/Battlefield.cpp
- src/server/game/Battlefield/Battlefield.h
- src/server/game/Battlefield/Zones/BattlefieldWG.cpp
- src/server/game/Battlefield/Zones/BattlefieldWG.h
- src/server/game/Entities/Player/Player.cpp
1. Show who controls WG on the map
2. Properly activates "ice" icon in battlegrounds tab
1.Show who controls WG on the map:
Open map and observe new Icon:
2. Properly activates "ice" icon in battlegrounds tab:
Open "battlegrounds" menu, 15 minutes before WG start. The "ice" icon will became active: …
> fix (Core/Wintergrasp) Fix map and battle icon

- apps/codestyle/codestyle-sql.py
* ref https://github.com/azerothcore/azerothcore-wotlk/pull/21630
- Closes 
1.
2.
3. …
> fix(CI/Codestyle): Escape all MySQL keywords and skip /* comments

- apps/codestyle/codestyle-sql.py
> fix(CI/Codestyle): Minor typo in insert_delete_safety_check

- data/sql/updates/pending_db_world/rev_1740880295787400500.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21383
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21402
- Closes 
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Fix Felmyst air phase

- .github/actions/linux-build/action.yml
> fix(CI/linux-build): use correct OS name for cache key

- data/sql/updates/pending_db_world/rev_1740956472100490700.sql
Because she tries to build a path on top of the firewall gameobject.
- Closes 
1.
2.
3. …
> fix(DB/Creature): Disable Felmyst pathfinding

- src/server/game/Maps/Map.cpp
- Closes 
1. ```.kill me```
2. Unleash the soul
3. Resurrect at the Physician's site, then go to the place of death to see if bones have been created …
> fix(Core/Bones): Unable to create bones

- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
> fix(Core/PvP): Sometimes mobs and objects fail to spawn in OutdoorPvP

- data/sql/updates/pending_db_world/rev_1740514128965406500.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
- src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
1. On first enter to Ulduar instance boss Kologarn could be in IN_PROGRESS state, which will cause player to freeze.
2. Focused Eyebeam spell casted first ray from first eye on target and second ray from second eye to random place. Rays not always follow people.
3. If raid suicided by jumping in pit near Kologarn, on reset his body would be rotated to wrong position.
Issues were resolved by next changes:
1. IN_PROGRESS state was set due to cast of "SPELL_ARM_DEAD" spell, which caused damage to Boss. Now this spell only casted when fight is in progress.
2. Correct effects targets were set for the spell. Also …
> fix(Scripts/Ulduar) Fix Kologarn script

- src/server/game/Entities/Unit/Unit.cpp
Mistakenly removed here https://github.com/azerothcore/azerothcore-wotlk/pull/21625
Word of wow-classic dev
https://github.com/Aeded/BCC_Buglist/issues/88#issuecomment-859874628
https://wowhats.wordpress.com/2009/10/27/elemental-chain-lightning/
1.
2.
3. …
> fix (Core/Spells) readd 33% chance for lightning overload to fail on chain lightning

- src/server/scripts/Commands/cs_ticket.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21664
1.
2.
3. …
> fix(Core/Tickets): Fix crash in `ticket complete` command.

- data/sql/updates/pending_db_world/Shield_Orb.sql
> fix(DB/Creature) Adds Disable Gravity to Shield Orb.

- src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp
> fix(Core/PvP): OutdoorPvPZM - fetch creature spawnId correctly

- data/sql/updates/pending_db_world/rev_1741564748117866104.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
add missing visual fel fire and explosion when Brutallus is frozen
https://github.com/user-attachments/assets/52824127-d2bf-4cfe-8507-a219e6fcb860
- Closes 
custom command to trigger the RP by https://github.com/sogladev/mod-dbg-tools
```
.dbg swp mad
```
reset
```
.tele sunwell
.instance unbind all
```
tp
```
.gm fly on
.go xyz 1420.88 623.3206 70 580 0.11
```
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Add Brutallus Flame Ring explosion

- src/server/game/Groups/Group.cpp
Co-authored by: EricksOliveira <ericksoliveira258@gmail.com>
- fix taken from PR #21001 
- Progresses #16653
- Progresses #20933
1.
2.
3. …
> fix(Core/Group): fix group loot for quest items

- data/sql/updates/pending_db_world/Twins_Entropius_loots.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21359
1.
2.
3. …
> fix(DB/Loot) Add missing loots on Eredar Twins and Entropius.

- src/server/game/Calendar/CalendarMgr.cpp
- src/server/game/Calendar/CalendarMgr.h
Crashlog:
```
Thread 1 "worldserver" received signal SIGSEGV, Segmentation fault.
0x0000555558cebd8a in CalendarMgr::RemovePlayerGuildEventsAndSignups (this=0x55555acdbfe0 <CalendarMgr::instance()::instance>, guid=..., guildId=225) at /opt/wotlk_prod/src/server/game/Calendar/CalendarMgr.cpp:297
297            if ((*itr)->GetCreatorGUID() == guid && ((*itr)->IsGuildEvent() || (*itr)->IsGuildAnnouncement()))
#0  0x0000555558cebd8a in CalendarMgr::RemovePlayerGuildEventsAndSignups (this=0x55555acdbfe0 <CalendarMgr::instance()::instance>, guid=..., guildId=225) at /opt/wotlk_prod/src/server/game/Calendar/CalendarMgr.cpp:297
#1  0x000055555813cc62 in Guild::HandleLeaveMember (this=<optimized out>, session=<optimized out>) at /opt/wotlk_prod/src/server/game/Guilds/Guild.cpp:1534
#2 …
```
> fix(Core/Calendar): Fix crash on deletion while iterating through calendar events.

- data/sql/updates/pending_db_world/rev_1741970015446422305.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21702
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21686
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Felmyst Demonic Vapor

- src/server/game/AI/ScriptedAI/ScriptedFollowerAI.cpp
- src/server/game/AI/ScriptedAI/ScriptedFollowerAI.h
- src/server/game/Movement/MotionMaster.cpp
- src/server/game/Movement/MotionMaster.h
- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
- e.g. required for quest 11881 Load'er Up
- Follow-Up to #19498
- e.g. required for #20241
1.
2.
3. …
> fix(Core/Movement): Allow MoveFollow to not inherit speed of the target

- data/sql/updates/pending_db_world/rev_1742065742639088616.sql
Quest "A Job Undone" incorrectly lists "The Respect of Another" as the prerequisite quest
Closes #21708
- Closes #21708
https://www.wowhead.com/wotlk/quest=9898/the-respect-of-another#comments:id=2989221
This doesn't lead to "a job undone" because I completed that before killing blacksting.
same for me.
https://www.wowhead.com/wotlk/quest=9773/no-more-mushrooms#comments:id=144913
Once you've completed this quest, https://www.wowhead.com/wotlk/quest=9899 becomes available.
1.
2.
3. …
> fix(DB/Quest): Fixes the prerequisite quest for "A Job Undone"

- data/sql/updates/pending_db_world/rev_1741995038650745837.sql
npc 27966 doesn't show any drop chance in wowhead. All chances and min/max based on data from current Wotlk Wowhead https://www.wowhead.com/wotlk
27960
27961
27962
27963
27964
27965
~~27966~~
27969
27970
27971
27972
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21704
1. .go c id [id above] 
2. kill and see if loot
3. …
> fix(DB/Halls of Stone) Trash inside dungeon now drops [Relic of Ulduar]

- data/sql/updates/pending_db_world/rev_1742151359540917588.sql
The quest "Pushed too Far" did not have a prerequisite quest.
- Closes #21553
I've confirmed that it is now required to complete "Baby Stealers" before you can accept the daily "Pushed Too Far". Also confirmed that "Loyal Companions" (12865) is still required to be completed before "Baby Stealers" as intended.
1.
2.
3. …
> fix(DB/Quest): Fixes missing prerequisite quest for "Pushed Too Far"

- src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
> fix(Scripts/Outland): add missing `return` if no target is found

- data/sql/updates/pending_db_world/rev_1742307871360448426.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp
Add jump behavior to PLR spell (45034)
Add visual dummy spell to indicate power of curse
Prevent stacking of curses if already afflicted
Add dispel visual when the encounter completes
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21674
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Sathrovarr's Curse of Boundless Agony

- data/sql/updates/pending_db_world/CF_pack.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7956
1.
2.
3. …
> fix(DB/Creature) Add formation for the the last pack before Kalecgos.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp
> fix(Script/Boss) Decrease Kalecgos human form spawn timer.

- src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp
- Closes 
1. create character, level up to 80 (.level 79)
2. .tele Nexus
3. set dungeon difficulty to Heroic
4. enter Nexus dungeon
5. .go xyz 488 108 -16 576
6. Clear room, begin boss fight
7. deal damage to boss until first split, kill copies, continue dealing damage until second split.
8. once cast begin - deal lot of damage to almost kill boss. Apply some DOT effect.
9. copies will appear, kill them.
10. boss will return with 1 hp, instead of being killed while copies exist. …
> fix(scripts/Nexus): Magus Telestra death

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21409
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Implement twins boundary wipe mechanic

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21739
1.
2.
3. …
> fix(Scripts/SunwellPlateau): M'Uru ability DARKNESS now spawns dispellable skulls

- data/sql/updates/pending_db_world/Volatile_Fiend_Packs.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21601
1.
2.
3. …
> fix(Creature/Formations) Volatile Fiend Packs now are in formation.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21748
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Fix twin emotes in phase 2

- data/sql/updates/pending_db_world/Twins_Taunt_Immune.sql
> fix(DB/Creature) Eredar Twins should be immune to taunt.

- data/sql/updates/pending_db_world/Scarlet_Cannon_Condition.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20144
1.
2.
3. …
> fix(DB/Condition) Scarlet Cannons now require Massacre at Light’s Point to be used.

- data/sql/updates/pending_db_world/rev_1742750116866370300.sql
Following the same mindset of sidragosa (1, 2, 3) per each difficulty_entry
Brann Bronzebeard (1) matches what the wowhead says (HP wise) for the Heroic Version.
Matching factions with the Heroic version
Help finding the correct brann by @amed80 
- Closes N/A
- Make sure youre in normal version
- `.go c i 28070` 
- Check that brann has 32k HP
- Teleport out and make sure youre in heroic version
- `go c i 28070`
- Check that brann has 40K HP …
> (db/Creautre) - Adds Heroic version of Brann Bronzebeard to Halls of Stone

- data/sql/updates/pending_db_world/Scarlet_Peasants.sql
- Related To https://github.com/azerothcore/azerothcore-wotlk/issues/20744
1.
2.
3. …
> fix(DB/Creature) Remove Random in Radius and edit orientation for some Scarlet Peasants.

- data/sql/updates/pending_db_world/Geist_and_DKs.sql
This PR will fix some wrong Geist and Death Knight Initiate spawns on Death's Breach (phase 1).
It will add also waypoints for some Geists.
These wrong spawns were probably caused by a wrong interpretation of a feature that is currently missing on AC (adding this feature will be my next work).
In addition it will fix a double mount issue for Baron Rivendare (Death's Breach, phase 64).
- Closes No reports
1.
2.
3.
You can help by testing PRs and writing your feedback here …
> fix(DB/Creatures) Fix various issues on DK starting area (phase 1 and 64).

- data/sql/updates/pending_db_world/Muru_distract.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21811
1.
2.
3. …
> fix(DB/Creature) Remove Immune to Distract Flag on M'uru.

- data/sql/updates/pending_db_world/rev_1743350402194716900.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7962
1.
2.
3. …
> fix(db/CreatureLoot) - Removal of "Rod of Lianthe" and "Nightmare Vine" from "Eclipsion Hawkstrider"'s Loot

- data/sql/updates/pending_db_world/Wrong_Loot.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21800
1.
2.
3. …
> Fix(DB/Loot) Remove Sunglow Vest from Eredar Twins loot.

- data/sql/updates/pending_db_world/rev_1743426015077494796.sql
live research may be needed to confirm
`SELECT DISTINCT creature_template.name, creature_template.entry , creature_template.mechanic_immune_mask, (creature_template.mechanic_immune_mask & 1 != 1) as 'can enslave' from creature, creature_template WHERE creature_template.`rank` != 3 and creature_template.`type` = 3 and creature.id1 = creature_template.entry and creature.`map` = 580;`
previous:
|name                |entry |mechanic_immune_mask|can enslave|
|--------------------|------|--------------------|-----------|
|Doomfire Destroyer  |25,592|131,073             |0          |
|Oblivion Mage …
> fix(DB/Creature): set Charm immune (`mechanic_immune_mask`) for SWP Trash demons 

- data/sql/updates/pending_db_world/Muru_mobs_immun.sql
> fix(DB/Creature) Add various immunities to Void Sentinel, Berserkers and Fury Mages.

- data/sql/updates/pending_db_world/Dark_Fiend_explode_range.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7985
1.
2.
3. …
> fix(DB/Creature) Reduce Dark Fiend range to explode.

- data/sql/updates/pending_db_world/Shadow_Image.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21808
1.
2.
3. …
> fix(DB/Creature) Shadow Image now only use one ability at a time. 

- data/sql/updates/pending_db_world/Citizen_of_New_Avalon.sql
This PR solves some smartai problems by updating existing timed action lists and adding new ones (one of the creature's entries had no action list).
- Closes 
1.
2.
3. …
> fix(DB/Creature) Citizen of New Avalon now have a more blizzlike behaviour.

- data/sql/updates/pending_db_world/rev_1743363476685228915.sql
- src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21163
SmartAI timings + strategy to model 43360 after 41295 from cmangos
fix(DB/SpellDBC): Update server-side 43360 - model after 41295 Fixate
[PATCH] Add missing spells all over TBC
https://github.com/cmangos/mangos-tbc/commit/7406614734e3bd038b5a5587da0859848a35b5cb
fix(Scripts/ZulAman): Add Beast Tamer spells mind control and fixate
https://github.com/cmangos/tbc-db/commit/38b75f68f9b883cca22a4d157149a4ebefcfaecd
1. `.go c id 24059`
2.
3. …
> fix(Scripts/ZulAman): Add Beast Tamer missing abilities

- src/server/scripts/Commands/cs_misc.cpp
> fix(Scripts/Commands): Fix crash in unstuck command

- src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
- Closes #21801
1. Attempt UNK state, think it's rare? Likely when using solo mod …
> fix(Script/ZulAmen) Hexlord now has fallback behavior as warrior

- data/sql/updates/pending_db_world/rev_1743708098406617107.sql
removes Sunder Armor
- Closes 
1.
2.
3. …
> fix(DB/SpellCooldownOverrides): remove overrides of player spells

- data/sql/updates/pending_db_world/rev_1743726578196339200.sql
- src/server/game/Entities/Object/Object.h
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21668
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Fix Darkness spawning midair

- data/sql/updates/pending_db_world/rev_1743880021262281174.sql
fixup `data/sql/updates/pending_db_world/rev_1737318437190767069.sql L491 L492`
- https://github.com/azerothcore/azerothcore-wotlk/pull/21219
- Closes 
>  [Exarch Nasuun](https://wowgaming.altervista.org/aowow/?npc=24932#starts) was giving the wrong progress when you talk to him during p3 :
> - when you ask him about Harbor progress it will show you Anvil
> - when you ask him about Anvil progress it will show you Harbor
1.
2.
3. …
> fix(DB/GossipMenuOption): Swap Exarch Nasuun Anvil and Harbor progress

- data/sql/updates/pending_db_world/rev_1743790045084096999.sql
Removes Sunwell Radiance aura 
Continues:
- https://github.com/azerothcore/azerothcore-wotlk/pull/21312
- Closes 
1.
2.
3. …
> fix(DB/CreatureAddon): Remove `auras` Sunwell Radiance

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21805
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Felmyst should choose the closest side

- data/sql/updates/pending_db_world/Ganarg_Analyzer.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15766
- Closes https://github.com/chromiecraft/chromiecraft/issues/5295
1.
2.
3. …
> fix(DB/Loot) Add gold drop, Netherweave Cloth and a drop chance for Gan'arg Analyzer.

- data/sql/updates/pending_db_world/Hand_of_Deceiver_IM.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21887
1.
2.
3. …
> fix(DB/Creature) Hand of the Deceiver is no longer immune to silence and stun.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21891
1. go c id 25741
2. damage to transition
3. observe  …
> fix(Scripts/SunwellPlateau): Correct Singularity behavior in Entropius encounter

- data/sql/updates/pending_db_world/rev_1744392732263733650.sql
Set Custom Spell Attr so that `IsPositiveEffect()` returns `true` for Effect 2 of spell 46102 Spell Fury
https://github.com/azerothcore/azerothcore-wotlk/blob/3f08610f84cfd7a20d38bc34f11816449684bc89/src/server/game/Spells/Auras/SpellAuras.cpp#L138
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21862
`.npc add temp 25799`
`.cast 46102`
1.
2.
3. …
> fix(DB/SpellCustomAttr): make Spell Fury spellstealable

- data/sql/updates/pending_db_world/rev_1744393940295043689.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21882
`.npc add temp 25772`
`.cast self 46071`
enslave Void Spawn
1.
2.
3. …
> fix(DB/Creature): Add Shadow Bolt Volley to Void Spawn's spells

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21717
1. .go c id 24882
2. kill brutallus 
3. observe …
> fix(Scripts/SunwellPlateau): Set Brutallus corpse despawn timer to 3 minutes

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
Removed a Trailing whitespace
- Closes 
1.
2.
3. …
> Fix(Script) Remove a Trailing whitespace from brutallus script.

- data/sql/updates/pending_db_world/rev_1744421404317179000.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/instance_sunwell_plateau.cpp
~~This might close the issue if the stun is correct (currently 2 sec stun), other options for the stuns might be~~
~~https://wowgaming.altervista.org/aowow/?spell=34510 -> 4 sec stun~~
~~https://wowgaming.altervista.org/aowow/?spell=56 -> 3 sec stun~~
- Progess https://github.com/azerothcore/azerothcore-wotlk/issues/20362
1. .tele sunwell
2. arch mages near beginning
3. Attack and observe
~~- [x] Stun doesn't currently work, though not even sure what spell ID it should use for the stun~~ …
> fix(Scripts/SunwellPlateau): Add Blink with Nove Arch Mage

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21807
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21768
1. go c id 25166
2. kill Lady Sacrolash
3. observe pyrogenics timers …
> fix(Scripts/SunwellPlateau): Correct timing for Eredar Twins

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21908
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Entropius' darkness spawn height

- data/sql/updates/pending_db_world/Verified_Build.sql
- Related https://github.com/azerothcore/azerothcore-wotlk/pull/21825
- Related https://github.com/azerothcore/azerothcore-wotlk/pull/21912
1.
2.
3. …
> fix(DB/Creature) Add Verified Build.

- data/sql/updates/pending_db_world/entropius-model-data.sql
> fix(DB/Creature): Add model data for Entropius display.

- data/sql/updates/pending_db_world/rev_1744566662130496377.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21916
1. .go c id 25741
2. damage to Entropius phase
3. .cast 29060
4. observe immune …
> fix(Scripts/SunwellPlateau): Add taunt immunity to Entropius

- data/sql/updates/pending_db_world/netherwing-bunnies.sql
> fix(DB/Creature): Remove unnecessary Netherwing targetting dummy creatures.

- data/sql/updates/pending_db_world/rev_1743779900893505053.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21855
1. .go c id 19273
2. .q a 10129
3. .q c 10129 and see if return to thrallmar available …
> fix(DB/Quest) Return to Thrallmar has proper prerequisite quest Mission: Gateways Murketh and Shaadraz

- data/sql/updates/pending_db_world/rev_1744559106171295151.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
More horizontal throw, less vertical throw more like tornado
- Progess https://github.com/azerothcore/azerothcore-wotlk/issues/21913
1. .go c id 25741
2. go to phase 2
3. get hit by singularity and observe
4. Check for issues with recursion (targets dying/wipe proper resets) …
> fix(Script/Sunwell): Adjust Singularity behaviors

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21941
1. .go to twin entrance and check
2.
3. …
> fix(Script/Sunwell): M'uru height check

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21905
1. .go c id 25741 (muru)
2. go to kj
3. dmg past 55% and observe that no more than 3 Armageddon 
4. Observe no new Armageddon when casting Darkness of thousand …
> fix(Scripts/SunwellPlateau): Limit Kil'jaeden's Armageddon ability

- src/server/scripts/Spells/spell_mage.cpp
ASAN log:
```
==2031024==ERROR: AddressSanitizer: heap-use-after-free on address 0x61901166f338 at pc 0x555557327156 bp 0x7fffc0870580 sp 0x7fffc0870578
READ of size 8 at 0x61901166f338 thread T16
#0 0x555557327155 in Spell::GetDelayMoment() const /root/azerothcore2025-04-15/src/server/game/Spells/Spell.h:568:44
#1 0x555557327155 in spell_mage_fingers_of_frost_proc_aura::HandleOnEffectProc(AuraEffect const*, ProcEventInfo&) /root/azerothcore2025-04-15/src/server/scripts/Spells/spell_mage.cpp:990:97
#2 0x555558c25eb2 in Aura::CallScriptEffectProcHandlers(AuraEffect const*, AuraApplication const*, ProcEventInfo&) /root/azerothcore2025-04-15/src/server/game/Spells/Auras/SpellAuras.cpp:2723:25
#3 0x555557dec556 in Unit::ProcDamageAndSpellFor(bool, Unit*, unsigned int, unsigned int, …
```
> fix(Core/Scripts): Fix heap-use-after-free in Fingers of Frost proc handler

- data/sql/updates/pending_db_world/rev_1744850939591523000.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21945#issuecomment-2811283596
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Void Sentinels spawn at floor level

- data/sql/updates/pending_db_world/SwP_formations.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8009
1.
2.
3. …
> fix (DB/Creature) Some SwP packs are now in formation.

- src/server/game/Autobroadcast/AutobroadcastMgr.cpp
> fix(Core/AutobroadcastMgr): correctly check for existing textId in SendWorldAnnouncement

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
> fix(Scripts/SunwellPlateau): Correct Felmyst landing pos variable names

- data/sql/updates/pending_db_world/rev_1745009912305741300.sql
- src/server/scripts/Events/events_script_loader.cpp
- src/server/scripts/Events/noblegarden.cpp
- src/server/scripts/World/go_scripts.cpp
- Closes 
.event start 9
.gob add temp 113768
right click to loot
receive an egg as loot
get transformed into a bunny at 5% with each loot
further looting should not remove bunny transformation
-> should be removed on spell hit / damage taken
while transformed into a bunny, the player will also lay eggs, this should also stop when the transform aura gets removed manually (right clicking on the icon). …
> fix(Scripts/Noblegarden): fix bunny transformation on egg looting

- src/server/game/Spells/SpellInfoCorrections.cpp
fixes potential crash due to Earthliving proc -> Heal proc -> Earthliving proc -> Heal proc -> ...
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21956
I found no mention that this triggered heal effect should count as a direct heal that can trigger effects such as: Earthliving Weapon, Ancestral Healing,... These effects commonly only proc from actual healing abilities
https://www.wowhead.com/item=32500/crystal-spire-of-karabor#comments
requires 2 chars
70 shaman with resto talent Blessing of the Eternals
.add 32500
a target to heal …
> fix(Core/SpellInfoCorrections): Suppress Crystal Spire of Karabor procs

- data/sql/updates/pending_db_world/sunwell-trash-recipes.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/7979.
- Wowhead pages don't imply a significant difference between BoE/BoP recipe drop rate from what I've seen, collating the reference tables is simpler and brings normalized drop chance for all items. Also kicked up the drop rate to match a little closer to what is implied from Wowhead's data.
This PR: …
> fix(DB/Loot): Consolidate Sunwell trash recipe drops into one reference table and update chance.

- data/sql/updates/pending_db_world/arena-rewards.sql
> fix(DB): Add and correct arena season rewards.

- src/server/game/AI/CoreAI/PetAI.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21921 …
> fix(Core/AI): Ignore PvP flagged players for aggressive pets if owner is not PvP flagged.

- src/server/game/Maps/MapMgr.cpp
not alive and does not have the corpse inside or in inner instance
- Closes 
[PATCH] Core/Maps: Do not allow entering an instance if the player is
not alive and does not have the corpse inside or in inner instance
(#30229)
https://github.com/TrinityCore/TrinityCore/commit/15598723810f76a56b1ea5f3198b482dc0c19d65
reproduced with GM commands
https://github.com/TrinityCore/TrinityCore/issues/26243#issuecomment-798925726
1.
2.
3. …
> fix(Core/Maps): Do not allow entering an instance if the player is

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp
> fix (Script/SWP) use enrage function for brutallus enrage

- data/sql/updates/pending_db_world/rev_1745536804631681300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21978
1.
2.
3. …
> fix(DB/SAI): Despawn Mu'ru Void Spawns on evade

- data/sql/updates/pending_db_world/rev_1745497441690295560.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21903
1. go kj
2. get blue dragon
3. test haste buff on buddy …
> fix(Scripts/SunwellPlateau): Make Blue Dragon Breath Haste apply 25% haste effect

- src/server/apps/authserver/Main.cpp
- Closes 
N/A
1. Launch authserver
2. Wait for database ping to happens
3. Validate log file output
/ …
> authserver: align mysql ping log level and name to worldserver

- data/sql/updates/pending_db_world/Dead_Bodies.sql
This fix will resolve the problem (I probably re-caused the problem with this [FIX](https://github.com/azerothcore/azerothcore-wotlk/pull/21842)).
In addition, dead bodies inside Scarlet Tavern will no longer be selectable (a feature verified on cata classic live).
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/2612 (point 8)
1.
2.
3. …
> fix (DB/Creature) Citizen of New Avalon inside Scarlet Tavern now remain dead.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21781
Tested with the number set to 2 and 4 characters
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Make Twin special abilities target one of the highest 6 in threat of the other twin

- data/sql/updates/pending_db_world/rev_1745876726796753902.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
Remove tank from targets of Flame Sear
I assume the previous cases of it selecting only 4 targets was when it selected the tank, the occurence of targets was fairly low in the 2 linked videos in the issue
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22011
Encounter the Eredar Twins with 2+ characters
**REMEMBER**: when testing a …
> fix(Scripts/SunwellPlateau): exclude tank from flame sear

- data/sql/updates/pending_db_world/rev_1745940911894528370.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19907
1.
2.
3. …
> fix(DB/Spells) add Battle Squawk to Melee Haste aura stack group

- data/sql/updates/pending_db_world/rev_1745941039161439470.sql
Also merge those 2 groups to make it possible
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21868
1.
2.
3. …
> fix(DB/Spells) add K'iru's Song of Victory to Intellect and Stamina aura stack groups

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Unit/Unit.h
- src/server/shared/DataStores/DBCStructure.h
- Closes https://github.com/chromiecraft/chromiecraft/issues/8011
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19246
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/7689 …
> fix(Core/Creature): Implement respond to call for help faction flag.

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp
- Closes 
1. .go c id 25741
2. wait for dark fiends and observe 
3. Go to second phase (entropius)
4. wait for dark fiends and observe …
> fix(Scripts/SunwellPlateau): Dark Fiends should use threat table and not deal melee damage

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
Just repeat of https://github.com/azerothcore/azerothcore-wotlk/pull/21895 because of merge issue
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21669
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Ensure proper reset for Kil'jaeden encounter

- data/sql/updates/pending_db_world/rev_1746124496649257276.sql
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20764
.aura 27648
.aura 58179
Attackspeed does not change with 2nd aura …
> fix(DB/Spells) Thunderfury does not stack with Infected Wounds/Thunderclap/Icy Touch anymore

- data/sql/updates/pending_db_world/rev_1746309097356194167.sql
place Alchemy Lab on the Alchemy Table
fixup of 
- https://github.com/azerothcore/azerothcore-wotlk/pull/21219
> `(@guidalch, 187115, 530, 4080, 4087, 1, 1, 12845.603516, -7011.98584, 18.592701, 5.543178, 0, 0, 0, 0, 0, 0, 0, '', 0);`
- Closes 
`.go ga id 187115`
1.
2.
3. …
> fix(DB/GameObject): place Alchemy Lab on the Alchemy Table

- data/sql/updates/pending_db_world/rev_1746334701815945000.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22007
1.
2.
3. …
> fix(DB/Formations): Naxxramas - Embalming Slime

- src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22008
1.
2.
3. …
> fix(Scripts/CoS): First trio transforming on low HP

- data/sql/updates/pending_db_world/rev_1746351205964053400.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21482
1.
2.
3. …
> fix(DB/Conditions): Gather Lumber not despawning Coldwind Tree GOs

- data/sql/updates/pending_db_world/Horses_Behaviour.sql
When player dismounts, the horse should play "mountspecial" animation , despawn after 5 seconds and respawn after 60 seconds.
When a horse dies, it should respawn after 60 seconds.
- Closes No reports
1.
2.
3. …
> fix(DB/Creature) Havenshire Horses now have a blizz-like behaviour when dismounted or die.

- data/sql/updates/pending_db_world/rev_1746546682435566500.sql
Already has no exp flag so it cannot be abused.
- Closes https://github.com/chromiecraft/chromiecraft/issues/7940
1.
2.
3. …
> fix(DB/Creature): Remove Wrath Enforcer damage requirement

- src/server/game/Battlefield/Zones/BattlefieldWG.cpp
- src/server/game/Battlefield/Zones/BattlefieldWG.h
- src/server/game/Battlegrounds/BattlegroundMgr.cpp
- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Events/GameEventMgr.cpp
- src/server/game/World/IWorld.h
- src/server/game/World/World.cpp
- src/server/game/World/World.h
- src/server/game/World/WorldState.cpp
- src/server/game/World/WorldState.h
- src/server/scripts/OutdoorPvP/OutdoorPvPTF.cpp
- src/server/scripts/World/npcs_special.cpp
> refactor(Core/World): Move various worldstate related functions to worldstate class.

- data/sql/updates/pending_db_world/rev_1746722946182306100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21507
1.
2.
3. …
> fix(DB/Creature): Ahn'kahar Watcher will no longer spawn in normal mode.

- data/sql/updates/pending_db_world/rev_1746808964702490700.sql
From `4` to `0` creatures that should drop this item, only should be drop from g.o `Pitted Iron Chest` 
Deletes `Lorgalis Manuscript` from `Aku'mai Fisher` (4824), `Blackfathom Myrmidon` (4807), `Blackfathom Sea Witch` (4805) and `Snapping Crustacean` (4822)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22089
1.
2.
3. …
> fix(DB/Loot) - Lorgalis Manuscript no longer drops from creatures.

- src/server/scripts/Kalimdor/zone_desolace.cpp
@Kitzunu 
- Closes https://github.com/chromiecraft/chromiecraft/issues/7727
1.
2.
3. …
> fix(Scripts/Desolace): Kodo Roundup

- data/sql/updates/pending_db_world/rev_1746846052760295300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21525
https://www.wowhead.com/wotlk/quest=12821/cell-block-tango#comments:id=695989
1.
2.
3. …
> fix(DB/Conditions): 'Opening the Backdoor' pre-quests

- data/sql/updates/pending_db_world/Kil'Jaeden_taunt_imm.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22109
1.
2.
3. …
> fix (DB/Creature) Add Taunt Immunity to Kil'Jaeden.

- data/sql/updates/pending_db_world/CrusadersAI.sql
- Progress https://github.com/azerothcore/azerothcore-wotlk/issues/20106
Regarding this point:
>  When Eye of Acherus is invisible, mobs hook it without attacking it.
1.
2.
3. …
> fix(DB/Creature) Scarlet Crusaders don't hook invisible Eye of Acherus anymore (phase 2).

- data/sql/updates/pending_db_world/kj-model-inf.sql
> fix(DB/Creature): Correct Kil'jaeden's model info.

- apps/extractor/extractor.sh
- apps/extractor/extractor_es.sh
-  [x] Apps 
Functionality and strings are based on existing `.bat` apps
- EN  https://github.com/azerothcore/azerothcore-wotlk/blob/master/apps/extractor/extractor.bat
- ES https://github.com/azerothcore/azerothcore-wotlk/blob/master/apps/extractor/extractor_es.bat 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22103
Test the branching instructions for options 1,2,3,4,5
to save time:
To test 2 (vmaps): copy Cameras, DBC, maps from a pre-extracted folder
To test 3 (mmaps): copy the pre-extracted vmaps
1. 
2.
3.
When a PR is ready to …
> feat(apps/extractor): add extractor for non windows

- src/server/game/Spells/SpellInfoCorrections.cpp
similar to 
- https://github.com/azerothcore/azerothcore-wotlk/pull/21787
> Pet avoidance spells do not apply avoidance to some boss' spells. This is due to them being cast from players to their allies and counting as creature spells. There's only a limited amount of spells with this flag: e.g., Mutated Plague from Professor Putricide (ICC). These spells have SPELL_ATTR7_TREAT_AS_NPC_AOE so pet avoidance spells can apply to these spells
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22132
1.
2.
3. …
> fix(Scripts/Spells): Kil'Jaeden Fire Bloom AoE pet damage

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
> fix(Scripts/SunwellPlateau): Fix Killjaeden text spam

- src/server/scripts/Outland/zone_blades_edge_mountains.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17182
.q add 10911
be in a group …
> fix(Scripts/Zone): Quest 'Fire At Will!' should give group credit

- data/sql/updates/pending_db_world/rev_1747490492456641600.sql
This removes the link 1 from the creature Ziggurat Defender, they only have 1 cast and no more actions. https://wowgaming.altervista.org/aowow/?npc=26202
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22128?notification_referrer_id=NT_kwDOAQKW4bQxNjQyNTIyODA3OToxNjk0NjkxMw#issuecomment-2888406720
Tested by @icemansparks https://github.com/azerothcore/azerothcore-wotlk/issues/22128#issuecomment-2885847228
and
@PkllonG https://github.com/azerothcore/azerothcore-wotlk/issues/22128#issuecomment-2888406720
1.
2.
3. …
> fix(DB/SAI) - Removes Link in Smart AI for creature Ziggurat Defender

- AUTHORS
- Outcome of https://github.com/azerothcore/azerothcore-wotlk/pull/22031
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22030
Co-authored-by: jackpoz <giacomopoz@gmail.com>
> docs(AUTHORS): add Cross-project Collaboration section

- data/sql/updates/pending_db_world/thoridal-chance.sql
> fix(DB/Loot): Adjust Thori'dal drop chance.

- data/sql/updates/pending_db_world/rev_1747667082397759252.sql
> fix(DB/Spells) Shadow Bolt Volley of Hand of Deceivers on the Kil'jaeden fight stack

- src/server/apps/worldserver/worldserver.conf.dist
Very minor change—might not be worth submitting, but it could help prevent confusion for others trying to find the database table. Took me a while to figure it out, since i was CTRL+F'ing it 😂
> Worldserver conf table reference correction

- data/sql/updates/db_world/2025_05_18_00.sql
- data/sql/updates/pending_db_world/rev_1747602093331873790.sql
- Closes: [Wailing Caverns Deviate Moccasin; A Bug or Unlisted Modification?](https://github.com/chromiecraft/chromiecraft/issues/8026)
- Closes: [Blackfathom Depths: Aku'Mai Servants Damage Bug](https://github.com/chromiecraft/chromiecraft/issues/8039)
[Please see this video for the Deviate Moccasin](https://www.youtube.com/watch?v=WR6cJkIOwL0&t=5366s)
and [this video for the Aku'Mai Servants](https://www.youtube.com/watch?v=WR6cJkIOwL0&t=5366s).
1. .char level 22 
2. .npc add temp 4978
3. .npc add temp 5762
- [These mobs both had a damagemodifier of …
> Update 2 mobs with broken damage

- data/sql/updates/pending_db_world/rev_1747547690190698400.sql
Captured Totem - NON_ATTACKABLE
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14597
in the issue
.go c id 4344
.q add 11169
Make sure you're close to level 40 and **NOT** in GM mode
place totem nearby, it shouldn't aggro …
> fix(DB/Creature): Captured Totem shouldn't be attackable

- data/sql/updates/pending_db_world/rev_1748062500283594000.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8057
.cast 45848
look at melee damage …
> fix(DB/Spells): Shield of the Blue output damage reduction

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp
`WorldObject* target = targets.front();` can be called on an empty list 
- https://github.com/azerothcore/azerothcore-wotlk/blob/77ac0ce7183b98c8be1e6311ed8b677c9aea5f61/src/server/game/Spells/Spell.cpp#L1234
The crash suggests `_HEAD = NULL`, that the list is empty when called
direct link: https://gist.github.com/Regrad/9566f5b069f80d47e916338ea1922d35#file-gistfile1-txt-L378
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22199
1.
2.
3. …
> fix(Scripts/SunwellPlateau): crash in Sinister Reflection Clone spellscript

- data/sql/updates/pending_db_world/rev_1748237026512147100.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
Also changed Deep Freeze to be casted to random non top target (was victim before)
Correct 58529 & 61592 from TARGET_UNIT_CASTER to TARGET_UNIT_TARGET_ENEMY
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22172
https://youtu.be/5cO9Hxv93Y4?t=391
Source: apply aura effect within those 2 spells.
1.
2.
3. …
> fix(DB/SAI): Portal Keepers using wrong Arcane Missiles

- src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_elder_nadox.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22154
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22153
.go c id 29309 …
> fix(Instance/OldKingdom): Elder Nadox enrage & health check

- src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_amanitar.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22183
1.
2.
3. …
> fix(Scripts/AhnKahet): Amanitar shouldn't be immune to nature damage

- src/server/game/Entities/Creature/Creature.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22238
The changes: …
> fix(Core/Creature): Use home position for leash distance check for creatures with no movement.

- data/sql/updates/pending_db_world/rev_1748093860285297800.sql
- src/server/scripts/Northrend/Nexus/Oculus/boss_varos.cpp
And fix arcane beam
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14738
- Closes https://github.com/chromiecraft/chromiecraft/issues/7912
https://www.youtube.com/watch?v=KR-1C_q-0vs
1.
2.
3. …
> fix(Instance/Oculus): Varos Cloudstrider does not summon Azure Ring Captain

- data/sql/updates/pending_db_world/rev_1748640298121075698.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_eredar_twins.cpp
This should be the only trap that requires this hack to activate the startDelay here:
- https://github.com/azerothcore/azerothcore-wotlk/blob/77ac0ce7183b98c8be1e6311ed8b677c9aea5f61/src/server/game/Entities/GameObject/GameObject.cpp#L503
- reference https://github.com/azerothcore/azerothcore-wotlk/pull/22102
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/22016
1.
2.
3. …
> fix(Scripts/SunwellPlateau): Eredar Twins blaze trap delay

- data/sql/updates/pending_db_world/DK_Remove_auras.sql
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
I also removed wrong auras on some of them.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22265
1.
2.
3. …
> fix (Scripts/ScarletEnclave): Death Knight Initiates now despawn when defeated.

- src/server/game/Guilds/Guild.h
> chore(Core/Guild): Adjust variable declaration name to match usage.

- src/server/game/Spells/SpellInfo.cpp
> refactor(Core/Spells): Remove effectively unused switch case.

- data/sql/updates/pending_db_world/rev_1749254753115209766.sql
https://github.com/azerothcore/azerothcore-wotlk/blob/90a101cedb66e59ddad4b51b14b1b1f8d526162f/src/server/scripts/Commands/cs_misc.cpp#L1842
before `.wchange`
after
- Closes 
1.
2.
3. …
> fix(DB/Command): update `wchange` help

- src/server/game/Chat/Channels/Channel.cpp
> refactor(Core/Channel): Cast moderation level to account types and avoid boolean evaluation.

- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Spells/Spell.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22219
1.
2.
3. …
> fix(Core/Spell): Halve healing threat generated by paladins

- data/sql/updates/pending_db_world/rev_1749519143875704500.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22275
1.
2.
3. …
> fix(DB/SAI): Savage Cave Beast should enrage every 30-35s

- data/sql/updates/pending_db_world/rev_1749524506982671600.sql
> fix(DB/SAI): Fix Bonegrinder not casting Frightening Shout

- data/sql/updates/pending_db_world/might-of-mograine.sql
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
- src/server/scripts/Spells/spell_generic.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20053 …
> fix(Scripts/ScarletEnclave): Improve Might of Mograine aura behavior.

- data/sql/updates/pending_db_world/area-52-mailbox.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8090
This PR: …
> fix(DB/Gameobject): Correct Area 52 Mailbox faction.

- src/server/game/AI/SmartScripts/SmartScript.cpp
From:
`SmartScript::ProcessAction: Entry 18945 SourceType 0, Event 3, Link Event 4 not found or invalid, skipped.`
To:
and to: (alterated the ID to throw an error)
- Closes N/A
`.go c 18945`
check your worldserver
To show the alterated error
```sql
-- Before change ID it's 4
UPDATE `smart_scripts` SET `id` = 15  WHERE `entryorguid` = 18945 AND `source_type` = 0 AND `id` = 4;
``` …
> fix(core/SMART_EVENT_LINK) - Seperation and clarification of "not found or invalid, skipped"

- data/sql/updates/pending_db_world/rev_1749586097955432885.sql
Immunities honestly were chosen by feel. No guide mentions you can interrupt the channel by CC so I added all of the reasonable ones
```
0	+1	CHARM
1	+2	DISORIENTED
2	+4	DISARM
3	+8	DISTRACT
4	+16	FEAR
5	+32	GRIP - Death Grip and similar effects
6	+64	ROOT
8	+256	SILENCE
9	+512	SLEEP
10	+1024	SNARE
11	+2048	STUN
12	+4096	FREEZE
13	+8192	KNOCKOUT - Incapacitate effects such as Repentance (Paladin)
16	+65536	POLYMORPH
17	+131072	BANISH
23	+8388608	HORROR - e.g. Death Coil (Warlock)
25	+33554432	INTERRUPT
26	+67108864	DAZE
29	+536870912	SAPPED
```
- Closes …
> fix(DB/Creature) add CC immunities to the Fel Crystals in the Selin Fireheart encounter

- data/sql/updates/pending_db_world/rev_1749529028851693000.sql
- src/server/scripts/Northrend/zone_zuldrak.cpp
- src/server/scripts/Spells/spell_quest.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21490
1.
2.
3. …
> fix(Scripts/ZulDrak): Fix Ghymer not being healed by storm clouds

- src/common/Utilities/Random.cpp
- src/common/Utilities/Random.h
The below is not possible as `DespawnOrUnsummon` requires `Seconds`, not `Milliseconds`
```
minionFinder->DespawnOrUnsummon(0s, randtime(150s, 200s));
```
A cast can be used instead, but this is ugly
```
minionFinder->DespawnOrUnsummon(0s, std::chrono::duration_cast<Seconds>(randtime(150s, 200s)));
```
Writing this as a template for other Duration types is possible if required in the future
- Closes 
1.
2.
3. …
> feat(Core/Utilities): add `Seconds` overload for `randtime`

- data/sql/updates/pending_db_world/Stolen_Horse_Cond.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22339
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22312
1.
2.
3. …
> fix(DB/Condition) Deliver Stolen Horse only works near Salanar.

- src/server/game/AI/SmartScripts/SmartScript.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/22344
- * closes https://github.com/azerothcore/azerothcore-wotlk/issues/22344
1.
2.
3. …
> fix(Core/SAI): Exclude GMs for player target/event

- src/server/game/AI/CoreAI/UnitAI.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfo.cpp
- src/server/shared/SharedDefines.h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22323
1.
2.
3. …
> fix(Core/Spell) implement SPELL_ATTR5_NOT_ON_PLAYER and SPELL_ATTR5_NOT_ON_PLAYER_CONTROLLED_NPC

- src/server/game/AI/CoreAI/UnitAI.cpp
Interestingly capturing by reference works when passing the lambda as a parameter
https://github.com/Tereneckla/azerothcore-wotlk/blob/f85d65cb3def94997418cd6214fb1adca403488c/src/server/game/AI/CoreAI/UnitAI.cpp#L195
- Closes #22352 
.cast 55342
Attack something from range …
> fix(Core/AI) crashfix(#22352)

- data/sql/updates/pending_db_world/command.sql
- src/server/database/Database/Implementation/LoginDatabase.cpp
- src/server/game/Accounts/AccountMgr.cpp
- src/server/game/Accounts/AccountMgr.h
- src/server/scripts/Commands/cs_account.cpp
- Closes #22140
1.use soap or in console:`.account create test test` and `.account create test2 test2 1@1.com` …
> gm command: account create support email

- data/sql/updates/pending_db_world/Spawn_in_Air.sql
This should resolve the leak problem into Scarlet Enclave map.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22373
1.
2.
3. …
> fix(DB/Creature) Remove respawn time from the smartAI of some npc's in the scarlet enclave.

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Spells/Spell.cpp
Mutilate was only critting with main-hand while Cold Blood
Closes AzerothCore issue #20027
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20027
1. Create a Rogue
2. Learn and use Mutilate with Cold Blood
3. See the double crit
4. Smile :) …
> fix(Core/Player): Mutilate + Cold Blood crit fix

- data/sql/updates/pending_db_world/rev_1751148569961282780.sql
- src/server/scripts/Spells/spell_generic.cpp
`ID - 29313 CooldownAll` resets the CDs of nearby players
equivalent of calling `.cooldown`
- https://github.com/azerothcore/azerothcore-wotlk/blob/f4e049f227be7c6c610534bd3daf4dc9b1d889bc/src/server/scripts/Commands/cs_misc.cpp#L1231
- Closes 
1. 1 or more players
2. use cooldowns
3. `.cast 29313` to reset CDs …
> fix(Scripts/Spells): add script to GM spell CooldownAll

- src/server/scripts/Pet/pet_dk.cpp
> refactor(Scripts/Pet): Death Knight use creature register macros

- data/sql/updates/pending_db_world/Gryp_Ghou_Corrections.sql
It corrects two small bugs that I had not seen in my last PR:
1. Scourge Gryphons no longer return to their spawn point.
2. Scarlet Ghouls now have a wider radius to enter combat.
- Related To https://github.com/azerothcore/azerothcore-wotlk/pull/22348
1.
3.
4. …
> fix (DB/Creature) A couple of simple SmartAI corrections for Scarlet Ghouls and Scourge Gryphons.

- data/sql/updates/pending_db_world/Tirion_Mount.sql
One problem less.
- Closes 
1.
2.
3. …
> fix (DB/Creature) Tirion doesn't get back on his horse anymore during The Light of Dawn event.

- src/server/game/Entities/Unit/Unit.cpp
- Closes 
1. Make a UnitScript that hooks into DealDamage, and have it print a system message or something
2. Deal damage in whatever way you want, it will never print the message
3. Apply my changes and then deal damage and observe the script has ran
- [Please note -- **neither** OnDamage or DealDamage will effect the amount of damage printed to the logs. This is a different code bug related to the fact that the packet of damage logs is sent before any damage value modifications from OnDamage or DealDamage have ran …
> fix(Core/Unit): Add previously unreferenced DealDamage script hook in Unit

- data/sql/updates/pending_db_world/rev_1750935252027011500.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8109
1.
2.
3. …
> fix(DB/Quests) - Corrected the Reputation requirements for the Scryers and Aldor 

- data/sql/updates/pending_db_world/rev_1751551734064867759.sql
Replace smartAI action "Draenei Anchorite - In Combat - Cast Holy Fire" which uses 'Arcanite Reaper' 16994 spellId to use Holy Fire instead
- Closes 
1.
2.
3. …
> fix(DB/SmartAI): Use Holy Fire spell for Draenei Anchorite

- data/sql/updates/pending_db_world/eye_of_acherus_aura.sql
> fix (DB/Creature) The Eye of Acherus now removes the aura from the player on death.

- data/sql/updates/pending_db_world/Unattackable.sql
Sometimes Scarlet NPCs can respawn with the not_attackable flag active.
This is caused by recent changes to the c++ script “How To Win Friends And Influence Enemies”.
My PR simply causes them to respawn without that flag.
Also, I added IC spells for Scarlet Lord Jesseriah McCree in anticipation of its future implementation.
- Closes 
1.
2.
3. …
> fix (DB/Creature) Ensure that Scarlet Npcs respawn without the NON_ATTACKABLE flag.

- src/server/game/DungeonFinding/LFGMgr.cpp
The part checks the lockstatus of a specific player for the dungeon. Their faction is irrelevant
- Closes https://github.com/chromiecraft/chromiecraft/issues/8132
- Closes https://github.com/chromiecraft/chromiecraft/issues/8133
1.
2.
3. …
> fix(Core/LFG): revert #22360

- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter5.cpp
- Issue: When the event "The Light of Dawn" battle resets, Darion respawn in his original position without Corrupted Ashbringer equipped.
1.
2.
3. …
> fix (Script/Scarlet Enclave) Darion now have Corrupter Ashbringer on respawn.

- src/server/game/Handlers/ChatHandler.cpp
> fix(Core/Opcodes): Crash fix

- apps/codestyle/codestyle-sql.py
- data/sql/updates/pending_db_world/rev_1752232806138408300.sql
Refering to this: https://github.com/azerothcore/azerothcore-wotlk/pull/21219#discussion_r2200296233
~This has not been tested, don't know how to do so.~
Test 1: https://github.com/azerothcore/azerothcore-wotlk/actions/runs/16218780025/job/45794146770?pr=22457
Test 2: https://github.com/azerothcore/azerothcore-wotlk/actions/runs/16218828295/job/45794292643?pr=22457
-  [x] Codestyle for SQL
- Closes N/A
1.
2.
3. …
> Addition(Codestyle/SQL) - Now check if the Database engine type is InnoDB

- src/server/scripts/World/scourge_invasion.cpp
fixes failing builds https://github.com/azerothcore/azerothcore-wotlk/actions/runs/16241056952/job/45857530538
> D:\a\azerothcore-wotlk\azerothcore-wotlk\src\server\scripts\World\scourge_invasion.cpp(590,75): error C2065: 'M_PIf': undeclared identifier [D:\a\azerothcore-wotlk\azerothcore-wotlk\var\build\obj\src\server\scripts\scripts.vcxproj]
(compiling source file '../../../../../../src/server/scripts/World/scourge_invasion.cpp')
- Closes 
1.
2.
3.
You can help by testing …
> fix(Scripts/World): fix windows/mac build

- src/server/game/World/WorldConfig.cpp
Fix values changed by https://github.com/azerothcore/azerothcore-wotlk/pull/21647
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22407
- Closes https://github.com/chromiecraft/chromiecraft/issues/8147
1.
2.
3. …
> fix(Core/Config): align worldconfig default values to .conf.dist

- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22473
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/22474
1.
2.
3. …
> fix(Script/ScarletEnclave) Acherus Soul Prisons now reset properly.

- src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp
Exarch Maladaar debuffs players when casting Stolen Soul, and summons a Stolen Soul mob. When the mob dies, the debuff is supposed to be removed from the player.
To achieve this, keep track of the number of Stolen Souls targeting each player. If that number falls to 0, remove the debuff.
Closes AzerothCore issue #22419
- Closes #22419  …
> fix(Scripts/AuchenaiCrypts): Remove debuff on summon death

- src/server/game/Entities/Creature/Creature.cpp
Always updates temporary summoned creatures, fixes possible overspawns where timed temp summons are not being despawned if no one is around to update them.
1.
2.
3. …
> fix(Core/Creatures): Always update temp summons

- src/server/apps/authserver/Server/AuthSession.cpp
- src/server/database/Database/Implementation/LoginDatabase.cpp
I don't know how to cite the author.
https://github.com/TrinityCore/TrinityCore/commit/bb4424c77cc5ca658584c7ba7274c767bd722847
- Closes 
1.
2.
3. …
> Core/Authserver: Remove blocking query in HandleLogonProof

- src/common/Metric/Metric.cpp
We need to check tokens.size after version check 
- Closes 
1.
2.
3. …
> Fix InFluxDB v1 work  after #22358

- data/sql/updates/pending_db_world/rev_1746905184805511100.sql
- Closes 
many mobs in one place that do the same ability = flag
1.
2.
3. …
> fix(DB/Custom): Stackable debuffs for wotlk T8 and up raids

- data/sql/updates/pending_db_world/rev_1746376436698611100.sql
many mobs in one place that do the same ability = flag
1.
2.
3. …
> fix(DB/Custom): Stackable debuffs for wotlk dungeons/T7 raids

- data/sql/updates/pending_db_world/rev_1753110129905756110.sql
Adds conditionals to gossip and vendors to the mail quests that start from drops during the Scourge Invasion.
This is missing a delay before the vendors unlock and conditional gossip like https://github.com/azerothcore/azerothcore-wotlk/issues/15566#issuecomment-1483318406 is missing
credit to @Grimfeather for providing a base to fix this https://github.com/azerothcore/azerothcore-wotlk/pull/22286#issuecomment-3083339284
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/15566
1.
2.
3. …
> fix(DB/Event): Scourge Invasion vendor conditions

- data/sql/updates/pending_db_world/Eyes_Above.sql
Silver Feather can now be used only on Imperial Eagles.
Imperial Eagles now act as they should.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21450
1.
2.
3. …
> fix (DB/Creature) Eyes Above quest issues are now solved.

- data/sql/updates/pending_db_world/Voldrassil_seeds.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21451
1.
2.
3. …
> fix (DB/Gameobject) Vordrassil Seeds now have a corrected spawn point.

- data/sql/updates/pending_db_world/Rhino.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21726
1.
2.
3. …
> fix (DB/Creature) Set right faction for Ice Steppe Rhinos.

- data/sql/updates/pending_db_world/Geirrvif.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21760
1.
2.
3. …
> fix (DB/Creature) Edit Geirrvif's position.

- data/sql/updates/pending_db_world/rev_1753322293728038600.sql
This pull request includes a single database update to adjust the position and orientation of a specific creature in the `creature` table.
* [`data/sql/updates/pending_db_world/rev_1753322293728038600.sql`](diffhunk://#diff-0b7851a9c31b38ef61862bdae7a6ec519858f402c9fd1019173dfbdc8a5050d5R1-R2): Updated the `position_x`, `position_y`, `position_z`, `orientation`, and `VerifiedBuild` fields for the creature with `id1` = 30258.Adjusts the position and orientation values for creature with id1=30258 in the database to reflect new coordinates and orientation. Also updates the VerifiedBuild field.
- Closes …
> fix(DB/Creature): Update Amanitar spawn position

- src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22485
1.
2.
3. …
> fix(Scripts/Northrend): Ulduar Mimiron plasma ball always target victim

- data/sql/updates/pending_db_world/Stratholme.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15625
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15624
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15622
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15619
1.
2.
3. …
> fix(DB/SAI): Implement various missing Culling of Stratholme behaviours (part 2).

- src/server/apps/worldserver/worldserver.conf.dist
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Object/ObjectDefines.h#L31C9-L31C32
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/World/World.cpp#L995
-  [x] Documentation
/
/
/
/ …
> Maximum visibility is 250

- data/sql/updates/pending_db_world/rev_1753106572373457633.sql
Epic gear from the event is now obtainable, and rare loot from vanilla event was removed
- unchanged, this works: Argent Quartermaster sells the Shoulders and Gloves for 15x Necrotic Rune Necrotic Runes each
Fix the Necrotic Rune drop amounts of Shadow of Doom and rare spawns
Loot chances are ??? The drop rate was increased, judging from wowhead.., so vanilla % aren't accurate.
What is known is that the chest drop chance is lower than the legs, and an epic drop is not guaranteed.
part about where to obtain epic gear …
> fix(DB/Event): Scourge Invasion Shadow of Doom and rare loot

- src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2123
1.
2.
3. …
> fix(Scripts/CullingOfStratholme): Prevent Arthas from despawning

- src/server/scripts/Spells/spell_dk.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/8170
1.
2.
3. …
> fix(Scripts/Spells): Death and Decay not breaking Hungering Cold

- src/server/game/Maps/MapUpdater.cpp
- src/server/game/Maps/MapUpdater.h
- src/server/game/World/World.cpp
Multithreads startup map preloading, greatly reducing startup time when the `PreloadAllNonInstancedMapGrids` config is in use. 
1.
2.
3. …
> feat(Core/Maps): Multithread startup map preloading

- src/server/game/AuctionHouse/AuctionHouseMgr.cpp
- src/server/game/Events/GameEventMgr.cpp
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Maps/MapMgr.cpp
- src/server/game/Misc/GameGraveyard.cpp
- src/server/game/Spells/SpellMgr.cpp
- src/server/game/Tickets/TicketMgr.cpp
- src/server/game/World/World.cpp
> refactor(Core): Clean

- src/server/game/Entities/Object/ObjectDefines.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfo.cpp
based on research in vmangos https://github.com/vmangos/core/issues/227
TLDR: Melee leeway applies to abilities/auto attacks/AoE spells and requires both targets to be moving, and if applicable, a minimum amount of speed
- abilities if speed
- AoE radius if speed
- AA always
current on ac:
- ❌ abilities leeway is always active
- ❌ AoE radius increase implemented <- fixed by cherry-pick https://github.com/TrinityCore/TrinityCore/commit/321f3cc4a7a59874c73ab82d57c2f1c76a820396 without a movement speed check
- ❌ AA not implemented <- this PR fixes this
- Closes …
> fix(Core/Unit): Add melee leeway for auto attacks

- data/sql/updates/pending_db_world/rev_1747581578778876200.sql
- src/server/scripts/Spells/spell_druid.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19313
2 characters, 1 druid
.learn 774 on druid
.add set 637
Use rejuvenation on character 2, try to log out server reset or any way to abuse/crash server. …
> fix(Spells/Druid): Moonglade Raiment 2-piece set bonus 

- data/sql/updates/pending_db_world/rev_1746620573935826954.sql
- src/server/game/Spells/SpellInfoCorrections.cpp
Improved Shadow Bolt no longer stacks with other Spell Crit Debuffs
Curse of Weakness and Spore Cloud no longer stack with other low Armor% debuffs
Vindication and Demoralizing Screech no longer stack with other AP debuffs
Stampede no longer stacks with other Bleed debuffs
Poison Spit and Lava Breath no longer stack with other Casting Speed debuffs
Master Poisoner no longer stacks with other Crit% debuffs
Savage Combat and Blood Frenzy no longer stack
https://www.icy-veins.com/wotlk-classic/raid-buffs-and-debuffs
common knowledge that the buffs/debuffs don't stack
This …
> fix(DB/Spells) add various spells to spell_groups

- src/server/database/Updater/DBUpdater.cpp
- this e.g. allows us to catch all sql errors in all modules within our module ci
- dryrun should not be used in production anyway as far as i can tell, so this should not be an issue for production environments
- Closes 
1.
2.
3. …
> fix(Core/DBUpdater): disable exception throwing for dryrun

- apps/installer/includes/os_configs/windows.sh
> fix(CI/windows): bump openssl to 3.5.2

- data/sql/updates/pending_db_world/rev_1754480069930060159.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8229
1.
2.
3. …
> fix(DB/Creature): remove skinning from Clutchmother Zavas

- data/sql/updates/pending_db_world/Icemist_village.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8215
1.
2.
3. …
> fix(DB/Creature) Add dialogue to the deaths of Anok'ra, Sinrok, and Tivax.

- src/server/scripts/Spells/spell_generic.cpp
The scaling aura was incorrectly applying immunity to stat increases. 
When comparing to other scaling auras, the immunity should only apply to resilience rating.
```
67561 - Serverside - Pet Scaling - Master Spell 06 - Spell Hit, Expertise, Spell Penetration
61013 - Warlock Pet Scaling 05
61017 - Hunter Pet Scaling 04
```
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22535
1. 
2.
3. …
> fix(Scripts/Spells): DK Ghoul pet is no longer immune to Horn of Winter and other stat mod auras

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/Item/Item.cpp
- src/server/game/Entities/Item/Item.h
- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Entities/Object/ObjectVisibilityContainer.cpp
- src/server/game/Entities/Object/ObjectVisibilityContainer.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Player/PlayerUpdates.cpp
- src/server/game/Entities/Transport/Transport.cpp
- src/server/game/Entities/Transport/Transport.h
- src/server/game/Grids/Notifiers/GridNotifiers.cpp
- src/server/game/Grids/Notifiers/GridNotifiers.h
- src/server/game/Grids/Notifiers/GridNotifiersImpl.h
- src/server/game/Handlers/CharacterHandler.cpp
- src/server/game/Maps/Map.cpp
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp
- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_ingvar_the_plunderer.cpp
- src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/instance_utgarde_keep.cpp
- src/server/scripts/Northrend/VioletHold/boss_cyanigosa.cpp
- src/server/scripts/Outland/BlackTemple/boss_illidari_council.cpp
- src/server/scripts/World/go_scripts.cpp
Part 1 of visibility overhaul by changing visibility from grid searchers to our own container implementation. This lays down the initial ground work for many more possible future commits to further expand upon and improve visibility (among other things). This alone should provide a fairly substantial performance boost when there is a large amount of players, however there is still plenty more performance opportunities that will be addressed in later PR's.
I've completed all the local tests/checks that I can think of, so should be ready for review/testing now.
This PR has …
> feat(Core/Visibility): Visibility improvements part 1

- data/sql/updates/pending_db_world/Wastes_Scavenger.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8223
1.
2.
3. …
> fix(DB/Creature) Init creature_template_addon in Wastes Scavenger.

- data/sql/updates/pending_db_world/rev_1754674822967930380.sql
Delete Nerubian Chitin, Borean Leather, and Arctic Fur from loot table from various creatures in WotLK
- No open issue appears to depict this bug
1.
2.
3. …
> fix(DB/creature_loot): Remove wotlk skinning items from creature loot tables

- src/server/game/Entities/GameObject/GameObject.h
- src/server/game/Entities/Object/ObjectVisibilityContainer.cpp
- src/server/game/Entities/Player/PlayerUpdates.cpp
- src/server/game/Entities/Transport/Transport.cpp
- src/server/game/Entities/Transport/Transport.h
- src/server/game/Grids/GridObjectLoader.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Maps/Map.h
- src/server/game/Maps/TransportMgr.cpp
Properly handles static transport visibility, removes a couple hacks and removes static transports from grid storage.
1.
2.
3. …
> fix(Core/Transports): Improve static transport visibility

- src/server/game/Handlers/CharacterHandler.cpp
- Closes [22672](https://github.com/azerothcore/azerothcore-wotlk/issues/22672)
1.
2.
3. …
> fix(Core/Visibility): Fix initial visibility on player reused sessions

- data/sql/updates/pending_db_world/rev_1754911204417603800.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22652
1.
2.
3. …
> fix(DB/spell_custom_attr): Allow Sunder Armor to stack

- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AuctionHouse/AuctionHouseMgr.cpp
- src/server/game/Chat/HyperlinkTags.cpp
- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Entities/Creature/CreatureGroups.h
- src/server/game/Entities/Player/Player.h
> refactor(Core): Improve readability

- data/sql/updates/pending_db_world/rev_1755975503363547000.sql
Co-authored by: Ryan Turner <AugustoMendes4426@gmail.com>
- Closes #22227
1.
2.
3. …
> fix(DB/SAI): fix event_type of Pit Commander SAI entry

- data/sql/updates/pending_db_world/rev_1755916063283631200.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21531
1.
2.
3. …
> fix(DB/Conditions): Everfrost Chip should require atleast friendly Sons of Hodir standing

- data/sql/updates/pending_db_world/rev_1756036806680249000.sql
- follow-up to #22585
1.
2.
3. …
> fix(DB/SAI): set dark portal event creatures active

- data/sql/updates/pending_db_world/rev_1756036806680249000.sql
> fix(DB/SAI): fix dark portal creatures calling for help on aggro

- data/sql/updates/pending_db_world/skeletalhorrors.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8105
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22354
Pull  Skeletal Horror's
Dont get feared
Get another player
Get feared
be alone with pet / totem -> no fear …
> fix (db/smart_scripts): Skeletal Horrors only cast when 2 or more players

- data/sql/updates/pending_db_world/mirkblood-spawntime.sql
- src/server/scripts/EasternKingdoms/Karazhan/boss_tenris_mirkblood.cpp
This PR:
1. Engage the boss.
2. Make sure he works good.
3. Profit. …
> fix(Scripts/Karazhan): Minor adjustments to Tenris Mirkblood.

- data/sql/updates/pending_db_world/rev_1756553610733937000.sql
> fix(DB/Gameobject): Sniffed Values for 'Mag'har Rug' spawns

- data/sql/updates/pending_db_world/rev_1756924523176702951.sql
Add 'Scourge Strike' to low-level SI creatures
- Closes https://github.com/chromiecraft/chromiecraft/issues/8297
VMangos' DB Dump(2025-08-30) 
https://github.com/vmangos/core/releases/tag/db_latest
```
Ghoul Berserker - Cast Spell Scourge Strike
Skeletal Shocktrooper - Cast Spell Scourge Strike
Spectral Soldier - Cast Spell Scourge Strike
Lumbering Horror - Cast Spell Scourge Strike
Bone Witch - Cast Spell Scourge Strike
Spirit of the Damned - Cast Spell Scourge Strike
Skeletal Trooper - Cast Spell Scourge Strike <-- missing
Spectral Spirit - Cast Spell Scourge Strike …
```
> fix(DB/SmartAI): low-level scourge invasion mobs are killed by guards

- src/server/game/AI/SmartScripts/SmartScript.cpp
Happens if
1) Owner of summon is a player
2) Owner of owner flag is used (it falls into the gameobject else since owner is not a creature)
- Closes 
1.
2.
3. …
> fix(Core/SAI): Fix crash in SMART_TARGET_OWNER_OR_SUMMONER

- data/sql/updates/pending_db_world/rev_1756947824261630300.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21573
1.
2.
3. …
> fix(DB/SAI): Despawn Frozen Phylactery on use

- data/sql/updates/pending_db_world/rev_1757011554068939700.sql
> fix(DB/Gameobject): Sniffed Values for 'Gravestone' spawns

- data/sql/updates/pending_db_world/rev_1757021490795481832.sql
manually give kill credit instead of using spell `43174` 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13842
https://www.youtube.com/watch?v=24PIRUbsDvQ
1.
2.
3. …
> fix(DB/SmartAI): Quest Draconis Gastritis can't be completed

- data/sql/updates/pending_db_world/kara-chess-warlock.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22769
This PR: …
> fix(DB/Creature): Correct spells for Orc Warlock chess piece.

- src/server/game/Spells/SpellInfoCorrections.cpp
The spell rolls for hit with a 96% chance to hit. The minion death spell shares the same attributes and effects, so I included it as well.
- Closes https://github.com/chromiecraft/chromiecraft/issues/8286
1.
2.
3. …
> fix(Scripts/Spells): Shadow of Doom death sometimes deals no damage

- data/sql/updates/pending_db_world/rev_1757111466618260938.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8289
1.
2.
3. …
> fix(DB/Event): missing Ironforge Argent Quartermaster

- data/sql/updates/pending_db_world/rev_1757106899882085716.sql
credit to @TheSCREWEDSoftware 
ported SAI events for Lord Blackwood from [cmangos/wotlk-dd](https://github.com/cmangos/wotlk-db)
- Closes https://github.com/chromiecraft/chromiecraft/issues/8306
- Closes https://github.com/chromiecraft/chromiecraft/issues/8308
1.
2.
3. …
> fix(DB/SAI): Scourge Invasion mini bosses various issues

- data/sql/updates/pending_db_world/rev_1754697821248272400.sql
- src/server/scripts/Northrend/AzjolNerub/AzjolNerub/azjol_nerub.h
- src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
- src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_krikthir_the_gatewatcher.cpp
- src/server/scripts/Northrend/AzjolNerub/AzjolNerub/instance_azjol_nerub.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22597
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22684
1.
2.
3. …
> fix(Scripts/AzjolNerub): Modernize Krikthir the Gatewatcher script

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Player/PlayerStorage.cpp
follow-up on 
- https://github.com/azerothcore/azerothcore-wotlk/pull/22736
- Closes https://github.com/chromiecraft/chromiecraft/issues/8287
1.
2.
3. …
> fix(Core/Player): Haunted Memento aura is present when item is in bank

- data/sql/updates/pending_db_world/immunities.sql
- Closes https://github.com/chromiecraft/chromiecraft/issues/8313
- Closes https://github.com/chromiecraft/chromiecraft/issues/8312
- Closes https://github.com/chromiecraft/chromiecraft/issues/8311
- Closes https://github.com/chromiecraft/chromiecraft/issues/8310
1.
2.
3. …
> fix(DB/Creature) Add immunities to various NPCs.

- src/server/game/Grids/Notifiers/GridNotifiers.cpp
Got ahead of myself and applied an optimization that cannot/shouldn't exist for the visibility system in its current form. Restores (much) slower CanSeeOrDetect check when processing out of range objects. We retain the new check as a slight optimization, the double distance check is still a worthy trade-off compared to all the crap in CanSeeOrDetect running for every object in visibility range. More work will be done on this area later down the road anyways.
1.
2.
3.
You …
> fix(Core/Visibility): Fix visibility issue at sight limit

- src/server/game/Maps/Map.cpp
> fix(Core/Visibility): Add some safety to visibility grid container

- src/server/game/Entities/GameObject/GameObjectData.h
Fixes wintergrasp walls/buildings not being visible throughout the entire zone
- Closes 
1.
2.
3. …
> fix(Core/Visibility): Mark destructible objects infinite visibility

- data/sql/updates/pending_db_world/rev_1757369338961290855.sql
- src/server/scripts/Northrend/zone_borean_tundra.cpp
Relocates the trigger summon spell's Z position to no longer be on the caster mid-air, but on the ground instead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21316
1.
2.
3. …
> fix(Scripts/Northrend): Scourge Plague Spreader summons ghouls mid-air

- data/sql/updates/pending_db_world/rev_1757462707122831818.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/21551
- Closes https://github.com/chromiecraft/chromiecraft/issues/7874
1.Have an alliance character at 80.
2. .go creature id 29732
3. Observe you are able to get the quest right away. …
> fix(DB/StormPeaks) Add quest prerequisite for Unwelcome Guests

- data/sql/updates/pending_db_world/rev_1757794989983160217.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22906
1.
2.
3. …
> fix(DB/Creature) Remove skinning loot from Soriid the Devourer

- data/sql/updates/pending_db_world/rev_1757775301662884000.sql
Only allows one of them to be picked, not both.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22903
1.
2.
3. …
> fix(DB/Quest) - Only allow either News for Rakoria or News from Zangarmarsh be picked up and completed

- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- src/server/game/AI/ScriptedAI/ScriptedCreature.h
> feat(Core/AI): Allow preventing health check events while casting

- src/server/game/Entities/Player/PlayerSettings.cpp
- src/server/game/Entities/Player/PlayerSettings.h
> chore(PlayerSettings): Save data and lowGuid

- src/server/game/AI/CreatureAI.cpp
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
Makes scripting talk sequences much easier
- Closes 
1.
2.
3. …
> feat(Core/SAI): Implement delay option to SMART_ACTION_TALK

- src/server/game/AI/CreatureAI.cpp
Initialize targetGuid only if target is not null.
- Closes 
1.
2.
3. …
> fix(Core/Creature): ensure target is valid when acquiring GUID

- data/sql/updates/pending_db_world/rev_1757938084848429700.sql
- src/server/scripts/Northrend/zone_borean_tundra.cpp
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/22842
1.
2.
3. …
> fix(Scripts/BoreanTundra): Script Soul Deflection spell

- src/server/game/AI/CreatureAI.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/Spell.h
cherry-picked from: https://github.com/TrinityCore/TrinityCore/commit/d1594c7295f1ca3f21a63a13895abf371d8bd3e0
- Closes 
1.
2.
3. …
> feat(Core/Spells): Implement OnSpellCastFinished hook

- data/sql/updates/pending_db_world/rev_1758204763903362829.sql
https://wowgaming.altervista.org/aowow/?quest=12003
- Closes 
https://github.com/TrinityCore/TrinityCore/commit/0a10573fef4243f782e5ea9dd09dd83caa98dbb1
```
.go xyz 4706 -4452 195 571 4
.q a 12003
```
1.
2.
3. …
> refactor(DB/SmartAI): quest  'Uncovering the Tunnels' 

- data/sql/updates/pending_db_world/rev_1758206177120204426.sql
https://wowgaming.altervista.org/aowow/?quest=11166
- Closes 
https://github.com/TrinityCore/TrinityCore/commit/6dce8c8d9bf2622f21ff3cb5894e11386818bb82
```
.tele zulaman
.q a 11166
```
1.
2.
3. …
> refactor(DB/SmartAI): quest 'X Marks... Your Doom!'

- data/sql/updates/pending_db_world/rev_1758363588780639900.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22657
1.
2.
3. …
> fix(DB/Misc): Fix Neutralizing the Cauldrons animations

- src/server/game/Spells/Spell.cpp
> fix(Core/Spells): crashfix

- data/sql/updates/pending_db_world/rev_1758378870340447581.sql
- Closes 
https://github.com/TrinityCore/TrinityCore/commit/81a32f89f6a3c07352d228b4651aba7aa6e344cb
1.
2.
3. …
> fix(DB/SmartAI): add AI to some Northrend creatures

- data/sql/updates/pending_db_world/rev_1758378011419760275.sql
follow up on TODO of PR below. Replaces move to position action with a waypoint
- https://github.com/azerothcore/azerothcore-wotlk/pull/22963
- Closes 
dirty test
```
.go c id 31731
to skip waiting for spawn
.npc add temp 31702
```
1. `.go c id 31731` 
2. wait for a dragon to spawn
3. …
> fix(DB/SmartAI): Frostbrood Spawn can now fly away

- data/sql/updates/pending_db_world/rev_1758151023989286000.sql
- src/server/scripts/Spells/spell_quest.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22071
1.
2.
3. …
> fix(Scripts/Spells): Fix Relief of the Fallen quest issues

- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/Spell.h
- src/server/game/Spells/SpellInfo.cpp
- src/server/game/Spells/SpellInfo.h
- src/server/game/Spells/SpellMgr.cpp
- src/server/game/Spells/SpellMgr.h
This reverts commit 6d2ad6047c8dcc1c7032c2aceb9582ce3e372229.
Some issues regarding `.reload` commands were introduced with:
- https://github.com/azerothcore/azerothcore-wotlk/pull/23006
A fix is in the works to refactor ConditionMgr, but for now, this is a simple revert to address immediate issues.
ASAN logs: https://gist.github.com/sogladev/5a74b328ad463ab2622f98d01815ec49
- Closes 
1.
2.
3. …
> Revert "fix(Core/Conditions): `ConditionList` use after free (#23006)"

- data/sql/updates/pending_db_world/rev_1758920110063277481.sql
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/21725 
1.
2.
3. …
> fix(DB/Quest): add prerequisite to Sniffing out the Perpetrator quest

- data/sql/updates/pending_db_world/rev_1758919967448732024.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/22639
1.
2.
3. …
> fix(DB/Quest): add prerequisite to Catching up with Brann quest

- data/sql/updates/pending_db_world/rev_1758965186881591714.sql
- src/server/game/Entities/Object/Position.cpp
- src/server/game/Entities/Object/Position.h
- src/server/game/Handlers/SpellHandler.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/Spell.h
- src/server/game/Spells/SpellMgr.cpp
> Currently, for quest [Shoot 'em Up](https://wowgaming.altervista.org/aowow/?quest=13069), you have to shoot some [proto-drakes](https://wowgaming.altervista.org/aowow/?npc=30330) off the sky. However, when shooting them, half the time the shots are not registered.
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/22492
https://github.com/TrinityCore/TrinityCore/commit/c6060dd0c511ddad3cb1f0423aa9ccf2de7aedec
> Be on quest Shoot 'em Up (id: 13069)
> Go on a harpoon
> Shoot some proto drakes and observe
1.
2.
3.
When a PR is ready to …
> fix(Core/Spells): updates trajectory target selection

- data/sql/updates/pending_db_world/rev_1759191371018343890.sql
- src/server/scripts/Northrend/Gundrak/boss_drakkari_colossus.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23054
1. .go c id 29307
2. pull boss with drakkari golems alive
3. observe …
> fix(Script/Gundrak) Drakkari Colossus will now call help from Drakkari Golems

- data/sql/updates/pending_db_world/rev_1759192557957949899.sql
Clearly a beastly beast like his buddy c id 8883
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5365
1. .go c id 8881
2.
3. …
> fix(DB) Riding Ram Upgraded to a beast from a critter

- data/sql/updates/pending_db_world/rev_1759180852833254842.sql
- src/server/scripts/Northrend/Gundrak/boss_drakkari_colossus.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23049
1. .go c id 29307
2. observer mortal strike 50% for normal 75% for heroic
3. …
> fix(Script/Gundrak) Drakkari Colossus will now use Mortal Strikes

- src/server/scripts/Commands/cs_go.cpp
- This fixes potential SQL injection when executing command .go creature name to a creature whose name contains quotes
- This allows executing .go creature name to creature such as "Sea Wolf" MacKinley in Booty Bay.
- N/A 
1. Open in-game chat
2. Look up creatures with quotes 
3. Use `.go creature name` command. For example: `go creature name "Sea Wolf" MacKinley"` …
> fix(Scripts/Commands): escape string before query on go creature command

- src/server/apps/worldserver/worldserver.conf.dist
- src/server/database/Updater/DBUpdater.cpp
Introduces the Updates.ExceptionShutdownDelay config option to delay application shutdown when a fatal exception occurs during update application. This allows administrators to observe errors before the server exits.
- Closes 
1.
2.
3. …
> feat(Core/Updater): Add configurable shutdown delay on update exceptions

- apps/installer/includes/os_configs/windows.sh
This also fixes issues with the GitHub Actions workflow -> windows-build.
- Closes 
1.
2.
3. …
> fix(CI/Windows): installer script - update OpenSSL version to 3.5.4

- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- src/server/scripts/Northrend/Gundrak/boss_moorabi.cpp
Creatures with offhand weapons like as Moorabi (GD) and Nalorakk (ZA) were incorrectly performing offhand attacks even with m_canDualWield disabled.
This introduces an enum that defaults to 'AUTO' to check creatures for a valid OH weapon.
Disabling/Enabling can be done through scripts.
Dual-wield logic for Player remains unchanged. It is set explicitly.
related: 
- https://github.com/azerothcore/azerothcore-wotlk/pull/20015
-  https://github.com/azerothcore/azerothcore-wotlk/pull/20707
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23047
This PR has …
> fix(Core/Unit): add Dual Wield 'auto' to improve scripting

- data/sql/updates/pending_db_world/rev_1759525004799036400.sql
> fix(DB/Gameobject): Sniffed Values for 'Big Rancid Meat' spawns

- data/sql/updates/pending_db_world/rev_1759524261297901900.sql
> fix(DB/Gameobject): Sniffed Values for 'Stolen Pack' spawns

- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/22074 
1.
2.
3. …
> fix(Core/Unit): Fix thorns/retribution aura only dealing damage on white hits

- data/sql/updates/pending_db_world/rev_1759598138082148000.sql
> fix(DB/Gameobject): Sniffed Values for 'Doodad_Nox_portal_top01' spawns

- data/sql/updates/pending_db_world/Disarm.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23135
1.
2.
3. …
> fix(DB/Creature) Remove immunity to Disarm from Gal'darah.

- src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/culling_of_stratholme.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23108
1.
2.
3. …
> fix(Scripts/CoS): Fix chest despawning when player leaves map

- data/sql/updates/pending_db_world/rev_1759604146375864300.sql
- src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp
- Closes https://github.com/chromiecraft/chromiecraft/issues/8100
1.
2.
3. …
> fix(Scripts/IsleOfQueldanas): Fix Greengill Slave script

- src/server/game/Spells/SpellInfoCorrections.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/23051
1.
2.
3. …
> fix(Core/Spells): Drakkari Medicine Man Earth Shield max targets
