azerothcore/azerothcore-wotlk

pull_request_template.md

Just improving the pull_request_template slightly (it's still a bit wordy but it will be good for now)
- Removed useless lines
- Changed titles style

chore: Clean up pull_request_template.md

---

src/server/game/Battlegrounds/Zones/BattlegroundAB.h

Fix a small compile error introduced with commit c6b5805
none
tested build on Ubuntu 16.04 / clang 7
Just need a successful Travis run, can be merged thereafter.
none

fix(Core/Battlegrounds): Fix compile error

---

src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp

Fix dk quest 12701 issue https://github.com/azerothcore/azerothcore-wotlk/issues/2557#issue-547091473
-  Add two WayPoints in AI Script of the minner for fix the bug.
-  More info about the bug in the issue.
- Closes #2557
- Testing the quest after the change many times and everything is ok.
- Testing for the two chips.
1. Create a Death Knight
2. Add quest - Command: .q a 12701
3. Command: .go xyz 2396.51 -5895.32 110.473
4. Enter in mining cart.
5. Wait for it to arrive on the ship (The error was only when it leaves you on the ship on the right but you can repeat the process until he leaves you at both ships).
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the …

fix(Core/CreatureScript): Fix dk quest 12701 #2557

---

src/server/game/Entities/Corpse/Corpse.h
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/DynamicObject/DynamicObject.h
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Pet/Pet.h
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Maps/Map.cpp
src/server/game/Maps/Map.h
src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
src/server/game/Server/WorldSession.cpp
src/server/scripts/Northrend/zone_sholazar_basin.cpp

-  Follow up of anticheat PR
-  A shit ton of overrides
-  Added phasemask for GetWaterOrGroundLevel
-  Changed some anticheat macros
-  Added CanSwim() and isSwimming methods
- Compiled and played around on Windows.
Just compile on Linux and play around a little bit.

fix(CORE): Missing override on various functions

---

data/sql/updates/pending_db_world/rev_1578865588449656124.sql

- Fix several Imperial Eagles using random movement although they should sit on the ground.
- Fix two Imperial Eagles sitting in the air.
none
- Check the two eagles, they should now fly and not sit anymore:
```
.go cr 96069
.go cr 96100
```
- Check a few of the following eagles (not necessary to check them all):
```
95613,95632,95633,95644,95657,95715,95731,95734,95735,95737,95747,
95750,95770,95782,95783,95784,95786,95807,95810,95820,95821,95848,
95849,95855,95860,95861,95922,95924,95927,95930,95946,95947,95948,
95983,95985,95986,95991,96020,96072,96080,96125,96127,96129,96130,
96136,96141
```
none
You can help by testing PRs and writing your feedback here in the PR's page on …

fix(DB/creature): Imperial Eagle

---

src/server/game/Entities/Player/Player.cpp

-  Quest items are removed from inventory upon quest completion again
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2620

Quest items are removed from inventory upon quest completion again

---

src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp
src/server/scripts/Northrend/Nexus/EyeOfEternity/eye_of_eternity.h
src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp

-  Remove hardcoded text.
-  NULL -> nullptr
-  Added missing overrides for virtual functions.
-  Added phases.
- Compiled and tested in game with esES client.
- Go to Malygos and let him speak. If your client is usUS, you shouldn't notice any difference, but if your client is in another language, you should see its texts translated.

Fix (Core/DB): Remove hardcoded text from Malygos

---

data/sql/updates/pending_db_world/rev_1579215466676030435.sql

- The Grizzly Bears will now attack the player and not just stand in the distance and watch when aggroed.
- They will now also stay near their spawn point instead of slowly drifting away.
none
- `.go 4391.41 -3683.5 254.738 571`
- Watch the Grizzly Bears, they should not wander too much away from their initial spawn point; if aggroed they should get into melee combat.
none

fix(DB/SAI): Grizzly Bear

---

data/sql/updates/pending_db_auth/rev_1579213352894781043.sql

- Differentiate 5 different type of test accounts for quick testing. People should rename/remove/change password from them though
- Add new column `comment` to "account_access"
Read some stuff from here for the default value https://dba.stackexchange.com/questions/28086/empty-longtext-or-null and other links, so I decided to make the comment empty instead of null 
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/1417 (old PR of mine)
- None yet, if someone can test, it'd be cool or just remind me
-
Just run the SQL and see if any error (for the UPDATE statements) …

feat(DB): Test accounts using various GM levels

---

data/sql/updates/pending_db_world/rev_1579389922264853693.sql

Fix a few issues concerning the quest "Anatoly Will Talk":
- Sasha: Fix the talk texts while she talks to Anatoly and let her shoot Anatoly after he transforms into a Worgen.
- Tatjana: Stop attack / combat movement after being hit by the Tranquilizer Dart (otherwise it could happen that she follows you around while being unconscious).
- Tatjana''s Horse: Use stored target to complete the quest. This ensures that the player stealing the horse is also granted the quest even if he dismounts the horse.
none
- preparation:
```
.q rem 12330
.q a 12330
.go 4071 -4126.95 211.555 571
```
- Listen to Sasha and Anatoly. Sasha should also talk now.
- Proceed with the quest and dismount shortly before the horse reaches it's destination. The quest should now also count as …

fix(DB/SAI): Quest "Anatoly Will Talk"

---

data/sql/updates/pending_db_world/rev_1579458178491145006.sql

Use "Shadow Shock" in combat instead of the useless "Strike" for Duskwing and also add "Sonic Burst".
none
- `.go cr id 11897`
- fight against Duskwing
none

fix(DB/SAI): Duskwing

---

src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Commands/cs_guild.cpp

-  fix some exploits with guild create command, send wrong packet to stuned creature  and  crashfix on summon spawn/despawn
- build

fix(Core/Misc): fix some exploits

---

src/server/game/Combat/ThreatManager.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Auras/SpellAuraEffects.h
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Auras/SpellAuras.h

Header include optimization for files: SpellAura.h SpellAuraEffects.h
Header include optimization for files: SpellAura.h SpellAuraEffects.h
Remove include "SpellInfo.h"
Only compile
Only compile
Only compile

Header include optimization SpellAura.h SpellAuraEffects.h

---

src/server/game/Spells/SpellEffects.cpp

Simplified the Developer Experience reading such a messy code and removed some duplicated useless conditions
No tested performed >.<
- Just make sure that the Summoning of the pet works

refactor(Core/Spells): Improved logic and DX Spell::EffectSummonPet

---

src/server/game/Guilds/Guild.cpp
src/tools/map_extractor/loadlib.cpp
src/tools/map_extractor/mpq_libmpq.cpp
src/tools/vmap4_extractor/mpq_libmpq.cpp

-  remove useless code
extract maps/vmaps/leave guild/ delete whole guild

Core/Misc: Remove redundant null pointer checks before delete

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp
src/server/game/AuctionHouse/AuctionHouseMgr.h
src/server/game/Mails/Mail.cpp
src/server/game/Mails/Mail.h
src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgr.h

I tried to introduce a few generic hooks which can help getting rid of the [patch file](https://github.com/azerothcore/mod-ah-bot/blob/6198ee2f30747b7dd66a517f8dd1537ed31272e1/ahbot.patch) of the [AuctionHouseBot module](https://github.com/azerothcore/mod-ah-bot):
**AuctionHouseScript**
- OnBeforeAuctionHouseMgrSendAuctionWonMail
- OnBeforeAuctionHouseMgrSendAuctionSalePendingMail
- OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail
- OnBeforeAuctionHouseMgrSendAuctionExpiredMail
- OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail
- OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail
- OnBeforeAuctionHouseMgrUpdate
**MailScript** (new ScriptObject!)
- OnBeforeMailDraftSendMailTo
none
- tested using a modified version of mod-ah-bot
see …

feat(Core/Hook): A few new hooks

---

data/sql/updates/pending_db_world/rev_1581974554600178400.sql

Argent Guard Thaelrid (ID 4787) had wrong faction such as title & name
in locales.
With this PR i adapted the NPC **from patch 4.0.3a to 3.3.5a.** Now the NPC is able to end quest 6561 and start quest 1200 as expected. 
-  Changed faction to 35 (Friendly with A/H) 
-  Changed Name from "Scout Thaelrid" to "Argent Guard Thaelrid" & added Title "The Argent Dawn" for deDE, esES, esMX & frFR locales
**References taken from https://wowwiki.fandom.com/wiki/Scout_Thaelrid**
**Adapted to the `creature_template from` AC.** 
- Closes 
- Imported SQL file with HeidiSQL on Win 10 pro x64
- Checked NPC and tested with A/H Char
- Checked quests
- Import SQL file 
- .go -528.080139 316.999176 -50.471893 48
- Check if the NPC is friendly with A/H char …

fix(DB): Argent Guard Thaelrid

---

README.md

Fix TC link and fix spacing

---

apps/git_tools/setup_git_commit_template.sh

Now returns an output.
Before that, it didn't return anything and could confuse people
Check the modified file, it's just one line :P

fix(apps): Script for default git commit template returns output

---

src/server/game/Handlers/CalendarHandler.cpp

-  Add a check for non-utf8 characters in order to avoid insert them to db and causes a lot of troubles. If you send multiple packet of this, you can hang up the database and cause lag in the server.
- Compiled under windows and tested by myself, using wpe sonic and filters.
-  Open WPE Pro (make it undetectable for warden, not gonna explain how just for safety) or some other packet sniffer.
-  Capture a packet when creating a calendar event with certain string, let's say "AAAAAA"
-  Apply a filter to change string "AAAAAA" ( 41 41 41 41 41 41 HEX) to FE 32 2E 34 36 45 in HEX (if you don't know how to do it search on google, pretty easy to use)
-  Create/Update another/the event with the same string ("AAAAAA") and look the string on console. …

Fix(Core/Packet): Calendar events exploits

---

src/common/Collision/BoundingIntervalHierarchy.h

-  https://stackoverflow.com/a/4328396

Core/Misc: Remove dependency on undefined behaviour

---

data/sql/updates/pending_db_world/rev_1582638956577578400.sql

The creatures with guid 84366, 84368 are wrong and will be removed with this PR.
These 2 creatures are the once who have a guid in `creature` table: 
All the other Storm Crows have no guid in DB (example): 
**Behaviour without the PR:** 
---------------------------
**Behaviour with the PR:** 
---------------------------
-  Remove the guid 84366 & 84368 as not needed in creature table
- Closes 
- Imported SQL with HeidiSQL on Win 10 pro x64
- Tested succesfully ingame
- .go -177.734650 5522.484375 42.142647 530
- .go -221.055984 5597.661133 62.601299 530
- Check that there is only one crow like the screenshots above
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow …

fix(DB): Remove duplicates Cenarion Stormcrow

---

src/server/game/Handlers/AuctionHouseHandler.cpp

I removed a comment in the previous PR :sweat_smile:

chore(Core): restore little comment

---

data/sql/updates/pending_db_world/rev_1582455931661032800.sql

Creature guid 64845 had wrong coordinates in position_z so it spawned above the map and couldn't be attacked. 
-  Upodated `position_z` in creature table so that creature can be attacked now and doesn't spawn above the map
- Closes 
- Imported SQL with HeidiSQL on Win 10 Pro x64
- .go c 64845 and check that the creature can be attacked
**Check spawn:** 
- Target the given creature and kill her .die
- Respawn creature .respawn
- Everything should look normal

fix(DB/creature_template): Marsh Lurker spawn position

---

src/server/game/Server/WorldSession.cpp

-  Commit name :P Remove from default case some repetitive movement packets in order to not get kicked by the minimum limit (100, which is too low for those packets)
- Compiled and tested. It's safe to merge.

fix(Core/Packets): Remove from default case some repetitive movement packets

---

data/sql/updates/pending_db_world/rev_1582472809971331600.sql

The 2 repeatable quests of faction 970 had a wrong rate x3 instad of
x1.
With this PR I set the factor from 3 to 1 in the `reputation_reward_rate` table so that the quests gain 750 rep as expected instead of 2250. 
**Source of research:**
https://wowwiki.fandom.com/wiki/Sporeggar
Depend all repeatable quests, for example those i tested: 
- ID 9744 More Tendrils!:
https://wowwiki.fandom.com/wiki/Quest:More_Tendrils!
- ID 9807 More Fertile Spores:
-  Update multiplier of `reputation_reward_rate` to 1
for faction 970  
- Closes 
- Imported SQL with HeidiSQL on Win 10 Pro x64
Prepare: 
- .modify rep 970 1
- .q rem 9743 
- .q rem 9806
More Tendrils!:
- .go c 63617
- .q a 9743 & .q c 9743 
- Now you can finish and repeat the q 9744 and it should gain 750 rep
More …

fix(DB/reputation): Sporeggar repeatable quest reputation rate

---

src/common/Database/DatabaseWorkerPool.cpp
src/server/game/Calendar/CalendarMgr.cpp
src/server/game/Calendar/CalendarMgr.h
src/server/game/Handlers/CalendarHandler.cpp
src/server/game/Server/WorldSession.cpp
src/server/game/Server/WorldSession.h
src/server/game/World/World.cpp
src/server/game/World/World.h
src/server/worldserver/worldserver.conf.dist

Co-authored-by: jackpoz <giacomopoz@gmail.com>
-  Read https://github.com/TrinityCore/TrinityCore/commit/fb05972
-  Added another check for string sizes to match up the db, those can be modified using wps or any other packet sniffer.
- Closes #2786 
- Compiled and tested with normal packets, everything normal. I sent some malformed packets and everything is fine.
Try to break the server sending malformed calendar packets and flooding it.

fix(Calendar/Packets): Add some additional validation when creating events

---

data/sql/updates/pending_db_world/rev_1583866008487985900.sql

Issue: No open
Currently was missing from the game.
It is a pretty cool npc :D

fix:(DB/Creature): Little Adeline

---

data/sql/updates/pending_db_world/rev_1582663580844407800.sql

Use creature_formations instead of pathing for each npc. This avoids that they get out of sync after a while or get stuck.
I didn't change the formation, just rebuild the positions in formation as it was before - see screenshots below! 
**Before:** 
--------
**After:**
--------
-  update paths for creature 46394 & 46416 so only the path of 46414 is used
-  create formation for guid 46414 
- Closes #2700 
- Imported SQL with HeidiSQL on Win 10 Pro x64
- .go c 46414
- Follow the formation a while and check that they are synced
- If you talk to any npc the whole formation should stop
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the …

fix(DB/creature_formations): Moon Priestess Amara pathing

---

data/sql/updates/pending_db_world/rev_1582823894137331500.sql

Use creature_formations instead of pathing for each npc. This avoids that they get out of sync after a while or get stuck.
Without the PR:
----------
With the PR:
----------
-  Delete own waypoints for creatures 6886, 6883, 6880, 6877
-  Create creature formation for creature 6885
- Closes 
- Imported SQL with HeidiSQL on Win 10 Pro x64
- .go c 6885 and wait ~ 2 minutes till the caravan starts
- Follow the NPC's and check that everything looks good
- Trty to interact with one NPC - A few seconds later the whole formation should stop and continue after ~ 2 minutes …

fix(DB/creature_formations): Thal'trak Proudtusk pathing

---

apps/db_assembler/includes/functions.sh

- Add bash 4.x+ recursion (this bash is available for years so it should be NP, also it makes use of the recursion Yehonal wrote in the bash script, no need to use `find` command for that)
- Closes 
- Before that commit, the recursion with "**" stopped after the first directory
- works fine :)
Seriously no need to test, I just made it to fix the issue right now, but just in case:
- Go in `data/sql/custom/db_world`
- Make a directory and its subdir like `test/test2` and put sql files inside
- Try to merge them with the db_assembler.sh (use the option 4 for custom SQL files) …

fix(app/db_assembler): Allow recursion with bash

---

src/server/game/Handlers/ChatHandler.cpp

Fix spell : [Silenced](https://wotlk.evowow.com/?spell=1852)
`.aura 1852` and try to chat as normal/other players and with GMs.

fix(Core): "Silenced - You can only chat with GMs" spell.

---

data/sql/updates/pending_db_world/rev_1583011949867573100.sql

-  added Despawn time in 5 minutes.
-  added Say Line.
- Closes [#2682](https://github.com/azerothcore/azerothcore-wotlk/issues/2682)
-  windows 7 64bits.
-  works perfectly in the game.

fix(DBSAI) Quest Fel Spirits

---

data/sql/updates/pending_db_world/rev_1583079134916792500.sql

Fixed a few grammar and spelling errors from various quest texts.
-  Update the incorrect texts
- Closes 
- Imported on win 10 pro x64 with HeidiSQL without errors
- Checked quests successfully ingame

fix(DB/lang): Fix Quest Minor Text Errors

---

src/server/game/Achievements/AchievementMgr.cpp

-  Added the locale based build of the MailTemplate in the AchievementMgr.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2810
- Built successfully
- Tested ingame, received german mails after completing achievements while using a german client
1. Download or use an other languaged client (not english)
2. Complete an achievement where u receive a mail, like reaching LvL 80
3. Read the mail you'll receive
- None

fix: achievement_reward_locale bug

---

data/sql/updates/pending_db_world/rev_1583347738773107900.sql

Update quest texts from patch stand 4.0.3a to 3.3.5a for deDE client.
**Research included in script!**
- Update 'Tiger Mastery' (185 - 188)
- Update 'Panther Mastery' (190 - 193)
- Update 'Raptor Mastery' (194-197)
- Update 'Big Game Hunter' (208)
- Closes 
- Imported sql
- Tested succesfully ingame
- Texts checked
To test changes ingame you need deDE client. Since I read almost every string and compared the correctness using the quest_template, it is sufficient to just test the SQL.
- Import SQL file and check that no error occurs

fix(DB/lang): The Green Hills of Stranglethorn German Quest Texts

---

src/common/Common.h
src/server/game/Handlers/MailHandler.cpp

-  prevent possible money dupe in mailhandler
-  Fix max packet size client crash in mailbox listing (thx Warlockbugs and cmangos)
- build only
- test open send mails in game and etc
- try to owerflow client mail buffer

fix(Core/Mail): Mailhandler cleanup

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h

* SMART_ACTION_CUSTOM_CAST
* SMART_ACTION_CONE_SUMMON (Legion, BFA, Mop like Custom Cone-Spells Yay!)
* SMART_ACTION_PLAYER_TALK (Custom DBM "Bomb Bla on me in 3...")
* SMART_ACTION_VORTEX_SUMMON (Vortex = Spiral)
* SMART_ACTION_CU_ENCOUNTER_START (Removes cds on boss start, retail like!)
* **MODIFIED:** SMART_ACTION_SET_ORIENTATION (Allow a random orientation)
```
SMART_ACTION_CUSTOM_CAST                        = 218,    // spellId, castflag, bp0, bp1, bp2
SMART_ACTION_CONE_SUMMON                        = 219,    // entry, duration (0 = perm), dist between rings, dist between earch summon in a row, length of cone, width of cone (angle)
SMART_ACTION_PLAYER_TALK                        = 220,    // creature_text.id, yell? (0/1)
SMART_ACTION_VORTEX_SUMMON                      = 221,    // …
```

feat(Core/AI): CU_SAI - Custom Action Options + Polar Coords System Offset Relocating

---

src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h

* SMART_EVENT_NEAR_PLAYERS (min, radius, first timer, check timer)
* SMART_EVENT_NEAR_PLAYERS_NEGATION (min, radius, first timer, check timer)
-  These events will trigger when the amount (min) of players are in range (radius) check periodically - NEGATION is the exact effect turned around (triggers when there are less than (min) players)

feat(Core/AI): CU_SAI - Custom Event Options

---

data/sql/updates/pending_db_world/rev_1584389666044943800.sql

@BarbzYHOOL Reported that the NPC currently is not doing any melee attacks. This PR extends the timers a bit of when the NPC can cast spells so it will be able to melee attack too
test before and after the PR
1. .tele ragefire
2. .npc add tem 11319
3. .npc add tem 11318
4. fight ⚔️

fix(DB/Creature): Ragefire Shaman

---

.github/workflows/import_pending_sql.yml

SQL import failed to push due to github branch protection.
Seems this will allow the actual supplied token to be used which has push access.
The solution was found from https://github.community/t5/GitHub-Actions/Push-to-restricted-master-branch/m-p/54948
-  
-  
- Closes 
-
-

Fix sql import

---

data/sql/updates/pending_db_world/rev_1586845118268975400.sql
src/server/game/Events/GameEventMgr.cpp

https://github.com/TrinityCore/TrinityCore/commit/299d6ebbffd11a8fa92327c5a9296602a1596202
https://github.com/TrinityCore/TrinityCore/commit/87c79c9485cbb9536912e1566174c717946c1537
https://github.com/TrinityCore/TrinityCore/commit/4913edf81bfbd505e3218161b45705962876552d
https://github.com/TrinityCore/TrinityCore/commit/f41dfa0089a7ba8719f28816ae75ba91313df5c4
-  Implement holiday_duration in holiday_dates (holiday_duration is the number of hours of how long the holiday may last (visible in the calendar))
-  Update Start and End dates of events
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2550
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/542
- Builds
- Checked in-game calendar and start dates. All bueno
1. Check calendar that all event frames are …

fix(Core/DB/Events): Game Event Start Date & Events on Calendar

---

data/sql/updates/pending_db_world/rev_1587491025762555300.sql

-  Change spawn HP (curhealth) to it's max (126000)
Proof https://youtu.be/KqGiOV8Dofg?t=76 You can see that he gets 4 successful shots on the dragon to make him die.
Basic maths:
126000 * 0.26 = 32760 (damage per shot by harpoon)
32760 * 4 = 131040 (Dragon = DEAD! :) ) 
-  Change condition from using spell 56578 since the harpoon use spell 56570
- Add smart_scripts to set passive on reset to fix the issue of constant combat bug here: https://github.com/azerothcore/azerothcore-wotlk/issues/2071
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2071
- Ran SQL
- Tested in-game (Works :) )
1. .go c id 30337
2. .q add 13069
3. Jump in a harpoon gun and shoot some proto-drakes 🗡️  …

fix(DB/Quest): Shoot 'Em Down

---

data/sql/updates/pending_db_world/rev_1586465404537052600.sql

As seen in this video https://youtu.be/RdqPb2Fslg0?t=86 Stinky is supposed to have a green aura on him.
-  Add missing aura to Stinky
- Closes None :)
- in-game
- SQL
1. .go c 201240

fix(DB/Creature): Stinky aura

---

data/sql/updates/pending_db_world/rev_1584891620193026600.sql

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2613
Tests:
Ran SQL
How to test:
1. .go c id 28913
2. Accept quest "Brothers In Death"

fix(DB/Quest): Brothers in Death event

---

data/sql/updates/pending_db_world/rev_1585441940559204300.sql

Currently, some are not kneeling which they should be doing.
How to test:
1. .go c 128030

fix(DB/Creature): Naxxramas Cultist

---

data/sql/updates/pending_db_world/rev_1585171102577227900.sql
data/sql/updates/pending_db_world/rev_1585171529989474800.sql

Change the keys description ''Heroisch'' which which incorrectly had two single quotes instead of just one.
to
-  Update item description for deDE Client
- Closes 
- Imported SQL script on Win 10 pro x64 with Heidi SQL v11
- Tested succesfully ingame 
To test changes ingame you need deDE client. It is sufficient to just test the SQL.
- Import SQL file and check that no error occurs
- Can be merged after approval

fix(DB/lang): TBC Heroic Dungeon Keys German Description

---

data/sql/updates/pending_db_world/rev_1586466641269881700.sql

-- https://wowwiki.fandom.com/wiki/Quest:Poisoned_Water
-- https://wowwiki.fandom.com/wiki/Quest:The_Molten_Core
-- https://wowwiki.fandom.com/wiki/Quest:Eye_of_the_Emberseer
-- https://wowwiki.fandom.com/wiki/Quest:Agent_of_Hydraxis
-- https://wowwiki.fandom.com/wiki/Quest:Hands_of_the_Enemy
-- https://wowwiki.fandom.com/wiki/Quest:A_Hero%27s_Reward
were all deprecated in 3.0.8
-  Make the quests above deprecated
- Closes 
- Run SQL
-
1. Try to obtain a quest

fix(DB/Quest): More deprecated quests

---

data/sql/updates/pending_db_world/rev_1586480454432011500.sql
src/server/scripts/Commands/cs_cheat.cpp
src/server/scripts/Commands/cs_misc.cpp

-  move from cs_misc to cs_cheat
- fix removing flag
- fix usability when targeting a player
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1524
- Builds
1. .cheat explore 1

fix(Core/Command): cheat explore

---

src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp

-  Fix so Magus Telestra is able to use all her lines in the fight
- Closes #2182
- Builds
- Before PR
- Works in-game
1. .go c id 26731
2. Start the fight and do some dps

fix(Core/Script): Grand Magus Telestra talk

---

data/sql/updates/pending_db_world/rev_1586601593003530500.sql

-  Alliance 15 [74] Thinning the Ranks & Alliance 15 [74] Secrets of the Flamebinders needs to be completed to get access to Alliance 15 [74] The Thane of Voldrune
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1374
- Ran SQL
- Tested in-game All works :)
Check the linked issue

fix(DB/Quest): Secrets of the Flamebinders quest chain

---

data/sql/updates/pending_db_world/rev_1586784089061059200.sql

-  Add a new invisible spellfocus for forge
- Spawn the new spellfocus to the 3 "big" forges in dalaran
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2885
- Added SQL
1. .go ob 5271
2. cast smelt

fix(DB/Gameobject): Dalaran Forges

---

data/sql/updates/pending_db_world/rev_1587062218041221300.sql
src/server/game/Miscellaneous/Language.h
src/server/scripts/Commands/cs_misc.cpp

-  Add check if player has 0 items to be destroyed
-  Add check if player has less than items trying to be destroyed
This will prevent players being able to scam Admins and GameMasters since the staff always will know if the player has the item when destroying or if they have less items than what should be destroyed
- Builds
1. .add 3030 50
2. .add 3030 -51
3. .add 3030 -50
4. .add 3030 -1

fix(Core/Command): additem checks

---

data/sql/updates/pending_db_world/rev_1587078801729376000.sql

-  Chain this puppy 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2902
- Ran SQL
- Tested by myself and a friend on my old server
- Do the quest chain
- Read the SQL file
- Use google
Well, this is a huge fix and an even bigger quest chain.
The best way to test this is to do the quest chain and google it, that is how I and my former friend tested it to make sure it is correct :)

fix(DB/Quest): Skybreaker Questchain

---

src/server/game/Groups/GroupMgr.cpp

-  I missed one keyword Lol
- Closes 
-
-

fix(Core/Query): MySQL 8.0 Keyword

---

data/sql/updates/pending_db_world/rev_1588099547971545300.sql
src/server/scripts/Commands/cs_lookup.cpp
src/server/scripts/Commands/cs_reload.cpp
src/server/scripts/Commands/cs_tele.cpp

-  rename tele to teleport, this has no effect on the command.
- Closes nada 
- builds
- works in-game
1. use the command

refactor(Core/Command): tele to teleport

---

src/common/Database/QueryResult.h

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3083
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3080
- Not tested
Install AC using MariaDB

fix(Core): solve issue with MariaDB

---

src/cmake/macros/FindMySQL.cmake

-  Allow MySQL 8.0
- Builded with MySQL 8.0
Build with MySQL 8.0 (on Windows)

fix(CMake/FindMySQL): MySQL 8.0 in Windows

---

.github/workflows/core_build.yml

Common keys block the efficient usage of cache in forks. When one build succeeds, other builds of the workflow or a later commit will match that cache with the common key. The stored cache may be for completely different compiler altogether, so cache is never hit during build.
Without the common key, caches for wrong compilers are not matched and caches are searched from the main repository, which contains recent caches for all of the compilers.
Details:
See https://github.com/azerothcore/azerothcore-wotlk/pull/3099 for an example of this scenario.
In this example the first commit triggers (non docker) builds and all of them finish within 5 minutes: https://github.com/azerothcore/azerothcore-wotlk/runs/725498934
A second commit is created after 15 minutes and some of its builds use over …

feat(CI): refine cache usage in gh-actions

---

data/sql/updates/pending_db_world/rev_1588332453846633800.sql

-  Fix SAI
-  Remove useless dummy npc
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2968
- Works
Read the issue

fix(DB/Quest): A Dire Situation

---

src/server/game/Grids/NGrid.h

-  Fix error `fatal error: cannot assign to non-static data member within const member function 'SetGridId'
-  This will allow clang 10 compilation
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3066
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2927
- Build
- Try to compile AC using clang 10 and run it, do a quick check in game

fix(Core/Clang): make it work with clang 10

---

.github/workflows/core_build.yml
.github/workflows/import_pending_sql.yml

Tiny PR, no description required.
If the build passes, this is good to be merged.

feat(CI): upgrade to Ubuntu 20.04

---

src/server/game/Handlers/MailHandler.cpp

-  Add a security check for Moderator
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1883
- Builds
1. do .mail before and after PR

fix(Core/MailHandler): Security check

---

src/server/game/Server/WorldSocket.cpp

When compiling there's a warning stating that not all paths return a value:
"_warning C4715: 'WorldSocket::ProcessIncoming': not all control paths return a value_"
-  Return 0 when receiving this opcode: CMSG_KEEP_ALIVE
- Closes #2494 
- Compiled and no issues detected while playing
Compile and launch worldserver.
Do a test run around the world checking for crashes

fix(Core): Worldsocket warning

---

data/sql/updates/pending_db_world/rev_1594986175990195100.sql

* Fixes https://github.com/azerothcore/azerothcore-wotlk/issues/3028
-  Remove faulty SAI
Gameobjects should not be allowed to be in combat with zone
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3028
This was tested and confirmed in https://github.com/azerothcore/azerothcore-wotlk/issues/3028#issuecomment-654536304

fix(DB/Sai): Crash

---

src/server/game/AI/SmartScripts/SmartScript.cpp

* Proper  fix for https://github.com/azerothcore/azerothcore-wotlk/issues/3028
-  Disallow Gob to use Combat with Zone
- Builds
1. Make a SAI for a Gob with SMART_ACTION_SET_IN_COMBAT_WITH_ZONE

fix(Core/SmartScripts): Disallow Gob to use Combat with Zone

---

data/sql/updates/pending_db_world/rev_1592783105272652900.sql

-  move the gob
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1644
before:
after:
1. .go ob 5228

fix(DB/Gameobject): Move GUID 5228

---

CMakeLists.txt

test: attempt to fix coverage report

---

apps/ci/ci-install.sh
src/server/game/ArenaSpectator/ArenaSpectator.h
src/server/game/Handlers/CalendarHandler.cpp
src/server/scripts/Commands/cs_spectator.cpp
src/tools/mmaps_generator/TerrainBuilder.cpp

-  Fix some clang warnings that potentially caused some bugs
- Enable the warning check in the ci to prevent new warnings for clang-10
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3108
- Builds
Building+running should be enough

fix(CI/Core/ArenaSpectator): clang warnings + prevent new warnings

---

src/common/Cryptography/BigNumber.cpp
src/common/Cryptography/BigNumber.h
src/common/Cryptography/HMACSHA1.cpp
src/common/Cryptography/HMACSHA1.h
src/common/Cryptography/OpenSSLCrypto.cpp
src/common/Cryptography/OpenSSLCrypto.h
src/server/game/Server/WorldSocket.cpp

-  remove ace_auto_ptr switch to uniq, bit cleanup
-  @FrancescoBorzi as you asked
play on server understand that all is ok also try some modules

refactor(Core): remove ace_autoptr, cleanup

---

.github/workflows/import_pending_sql.yml

- Make this message follow our commit conventions:

chore(CI): change bot's commit message format

---

apps/ci/mac/ci-compile.sh

- Prevent macOS to take too much space (we are limited to 5GB **in total**), while still making sure that this works.
I've re-run this PR multiple times and it still works ok.

fix(CI/macOS): reduce cache size

---

src/server/game/Movement/Spline/Spline.cpp
src/server/game/Movement/Spline/Spline.h

Based on: https://github.com/TrinityCore/TrinityCore/commit/408d68717cc1b920cae7da6dffd18ed992a6fdd6
Co-authored-by: Shauren <shauren.trinity@gmail.com>
-  Fix `-Wcast-function-type warning` GCC warning
- None
- Run the core, enter the game and make sure NPC movements are still fine

fix(Core/Spline): -Wcast-function-type warning

---

apps/ci/mac/ci-compile.sh

Trying out different cache levels

feat(CI/macOS): improve caching level

---

.github/labeler.yml

fix(Actions): Labeler

---

.github/workflows/labeler.yml

According to some research this could work for prs from forks

fix(action): labeler

---

apps/ci/mac/ci-install.sh

-  add workaround so configure os step doesn't fail for macos-10.15
- Closes none
- tested workflow in branch:

fix(ci): add workaround for configure os (macos-10.15)

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h

- Clear the array correctly
- Updated total mail variable handling to avoid false positives on system mail
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3603
- Create new character level it from 1-80 using .level 79 check if server 
- Created new character with instant 80
- Send mail from console
- Check if any action crashed the server
- Create new character level it from 1-80 using .level 79 check if server 
- Created new character with instant 80
- Send mail from console
- Check if any action crashed the server

fix(Core): Fixed crash happening when clearing old mail

---

data/sql/updates/pending_db_world/rev_1601240498542654700.sql

This PR will fix the following NPC=
ID: 18693
Name: Speaker Mar'grom
Reference for combat and dialogues are taken from: https://www.wowhead.com/npc=18693/speaker-margrom#comments
-  Add 4 different quotes when in combat
-  Add 6 (unused) dialogues when passive/moving
-  Improve SAI combat handling
- Closes #3507 
- Applied SQL
**Before applying SQL changes**
- .go c 151923 / 151924 / 151925 / 151926 / 151927 until finding him.
- .gm off
- Stand around him without any combat: You will notice there is no dialogue while he is around
- Enter in combat with him: You will also notice he does not say something when in combat
**After applying SQL changes**
- Test 1: Stand around him (around 20-30 yards should be enough), you will see different speeches being said for his comrades …

fix(DB/SAI): Speaker Mar'grom

---

data/sql/updates/pending_db_world/rev_1601314686326215700.sql

Western Plaguelands are now fully updated, since some creatures in zone was missing SmartAI.
Working on every zone at the moment, and will post updates once i'm done with each.
To test it:
Apply SQL
Restart your server
You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.
.npc add ID
or
.tele to zone and run / test around.

fix(DB/Zone):improved Western Plaguelands

---

data/sql/updates/pending_db_world/rev_1601361978416709800.sql

This change will add the item to the NPC Cult Researcher.
Reference: https://db.rising-gods.de/?item=44563#dropped-by
-  Add the item Pattern: Fur Lining - Arcane Resist to the NPC Cult Researcher as a possible loot
- Never reported
- Applied SQL change
**Before applying the SQL changes:**
- .go c id 32297
- Kill A LOT of Cult Researchers
- The recipe will never be a drop from them
**After applying the SQL changes:**
- .go c id 32297
[note: You will need to learn Leatherworking at high level in order to see this item]
- .learn 51302
- .setskill 165 450
- Kill a lot of Cult Researchers (remember it has a prop of 1%)
You can help by testing PRs and writing your feedback here in the PR's page …

fix(DB/creature_loot_template): Pattern: Fur Lining - Arcane Resist

---

data/sql/updates/pending_db_world/rev_1601315140580867400.sql

Improvements to few missing and skipped NPCs from before.
Also, updated few spawns.
To test it:
Apply SQL
Restart your server
You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.
.npc add ID

fix(DB/Zones):improved missing & skipped some NPCs

---

src/server/game/Spells/Auras/SpellAuras.cpp

-  Fix arguments in `sLog->outError()` call function
- None, but it doesn't compile if we compile with EXTRA-LOGS
- Compile
This is the called function, there is no `DebugLogFilters` param
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/common/Logging/Log.cpp#L469

fix(Core/Logs): Fix arguments in function call

---

src/tools/mmaps_generator/MapBuilder.cpp

This commit was already merged years ago :
https://github.com/azerothcore/azerothcore-wotlk/pull/2321/files
But got deleted by this one : 
https://github.com/azerothcore/azerothcore-wotlk/commit/4dd9b92759ad7e2a7e8e4ffce83cb4d90b8afa0c#diff-8dea62292b25ae49e11de5d68cbbd2578f45714f7b2532ba320eeb8768698540L98

feat(MMAPS/mapbuilder): Restore commit - mmaps_generator now working with MapID >= 1000

---

docker/authserver/etc/authserver.conf.dockerdist
docker/worldserver/etc/worldserver.conf.dockerdist

-  Change both authserver and worldserver conf.dockerdist files to not have comments in line with "LogsDir"
- Note that it is the same folder as the one in "Before PR", but now with logs
- None
- Tested in Windows 10 with Docker for Windows
- Clone azerothcore repo
- Follow "install with docker" instructions in AzerothCore wiki
- Confirm containers are running
- Check for logs in "docker\worldserver\logs" and "docker\authserver\logs" (should have no logs)
- Update both worldserver.conf.dockerdist and authserver.conf.dockerdist with fix
- followed "install with docker" instructions in wiki again from the start
- Check for logs in the above two folders (should have logs)
- Same steps as "TESTS PERFORMED"
You …

fix(CI/docker): AzerothCore in Docker now generates log files

---

src/common/Collision/BoundingIntervalHierarchyWrapper.h
src/common/Collision/DynamicTree.cpp
src/common/Collision/Management/IVMapManager.h
src/common/Collision/Management/MMapManager.cpp
src/common/Collision/Maps/MapTree.cpp
src/common/Collision/Maps/TileAssembler.cpp
src/common/Collision/RegularGrid.h
src/common/Configuration/Config.h
src/common/Cryptography/OpenSSLCrypto.cpp
src/common/DataStores/DBCFileLoader.cpp
src/common/Database/DatabaseWorkerPool.cpp
src/common/Database/MySQLConnection.cpp
src/common/Database/MySQLConnection.h
src/common/Database/QueryHolder.cpp
src/common/Debugging/WheatyExceptionReport.cpp
src/common/Dynamic/LinkedList.h
src/common/Dynamic/LinkedReference/RefManager.h
src/common/Dynamic/LinkedReference/Reference.h
src/common/Dynamic/ObjectRegistry.h
src/common/Dynamic/TypeContainer.h
src/common/Dynamic/TypeContainerFunctions.h
src/common/Dynamic/TypeContainerFunctionsPtr.h
src/common/Dynamic/TypeContainerVisitor.h
src/common/Logging/Log.cpp
src/common/Threading/LockedQueue.h
src/common/Utilities/EventProcessor.cpp
src/common/Utilities/Util.cpp
src/common/Utilities/Util.h

- Restyle `common` lib with astyle
- `-A1 -xV -S -N -Y -p -xg -k1 -W1 -O -xM -H -xf -xh -xy`
- http://astyle.sourceforge.net/

refactor(Core/Common): restyle with astyle

---

src/common/Common.h
src/server/game/Server/WorldSocketMgr.h
src/server/shared/Network/RealmSocket.h

-  Remove ACE types
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3451
- Builds
- If all builds pass, no tests needed

refactor(Core): remove ACE types

---

apps/installer/includes/os_configs/ubuntu.sh
deps/CMakeLists.txt
deps/PackageList.txt
deps/boost/CMakeLists.txt
src/common/CMakeLists.txt

- Add support boost
- Part #3739
- Compile
- Need?
**NOTE**: this is NOT targeting the `master` branch

feat(Deps/Boost): add support boost

---

deps/boost/CMakeLists.txt

feat(Deps/Boost): add required filesystem and set min ver for *nix 1.65

---

src/common/Utilities/StartProcess.cpp
src/common/Utilities/StartProcess.h

feat(Core/Util): implement start async process

---

src/server/game/Entities/Player/Player.cpp

Reverts azerothcore/azerothcore-wotlk#3715

Revert "fix(Core/Player): Improve rested removal"

---

data/sql/updates/pending_db_world/rev_1606305620937620900.sql

This change will update the guid position for human and night-elf initial NPCs
Reference - Human: https://www.youtube.com/watch?v=nvPSKTsvObk
Reference - Night elf: https://www.youtube.com/watch?v=0YhY4g-JEj4
- Update guide position for Deputy Willem and Ilthalaine
- Update guide position for Ilthalaine
- Adjust orientation
- Closes #3724 
- Applied SQL query
- Tested in-game (win x64)
.go c id 823 -> check pos
.go c id 2079 -> check pos
Apply SQL query and repeat as above
- N/A

fix(DB/creature): Starting zones

---

.github/workflows/check_pending_sql.yml

-  update the semicolon check to ignore whitespace
- Closes 

fix(ci): update semicolon check

---

src/server/scripts/Northrend/VaultOfArchavon/boss_archavon.cpp

-  Some code style improvements
-  Removed magic numbers
-  Attempt to fix one of the reported issues
**DEV:** Use `?w=1` with the commit link so that the GitHub shows you specific changes that I've done.
- Maybe closes #2260
NOTE: I do not know if it'll fix it still but perhaps some of the people who confirmed this as an issue can check it out.
So I'll link @Nemepy , @boom8866 and @pklloveyou 
- Compile
- Tested the boss (Archavon the Stone Watcher)
- Go to VOA raid
- Fight Archavon the Stone Watcher
- None at the moment.

fix(Scripts/VOA): Some code-style improvements and perhaps some bandwidth consumption issue

---

data/sql/updates/pending_db_world/rev_1605203808017925200.sql
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp

-  Change the first line of Tirion Fordring's text in ICC to correlate to the sound being heard (it had the first two lines of dialogue in one line)
-  Delay EVENT_BOLVAR_INTRO_1 so it doesn't overlap with EVENT_LK_INTRO_4
-  EVENT_TIRION_INTRO_6 now happens sooner, so there isn't an awkward pause after EVENT_LK_INTRO_1, and a healthy pause before EVENT_LK_INTRO_2.
- Tirion Fordring had two lines of text into one.
- Bolvar Fordragon's sound overlapped with The Lich King's sound
- Awkward pauses between voice lines
Current AC, Tirion says this in one big line of text:
Highlord Tirion Fordring yells: This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people! …

fix(Scripts/ICC): Intro Event Timers and Text

---

src/test/server/game/Miscellaneous/FormulasTest.cpp

Add full unit test coverage for the functions:
- GetGrayLevel
- GetColorCode
- GetZeroDifference

test(Formulas.h): GetGrayLevel, GetColorCode, GetZeroDifference

---

CMakeLists.txt

feat(CMake): show version when running cmake

---

deps/acelite/CMakeLists.txt

-  Explicitly link ACE lib against iphlpapi
- This fixed a linker error I experienced that was caused by no library defining the symbol for [if_nametoindex()](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-if_nametoindex).
- With this change the core now builds without a linker error

Added missing Windows dependency for acelite

---

src/server/game/AI/CoreAI/PetAI.cpp

-  Remove useless code introduced in https://github.com/azerothcore/azerothcore-wotlk/commit/3561d52b109a566d4300e8b87ec4e4fc99a4d2ad
-  This code is not doing what it actually claims to do, because:
```c++
owner->IsInCombat();
```
simply returns a boolean (that is ignored here) without doing any side effect
- None
- Nothing needs to be tested, this code did nothing

refactor(Core/PetAI): remove useless code

---

src/common/Collision/BoundingIntervalHierarchy.h
src/common/Utilities/Util.h
src/server/game/AuctionHouse/AuctionHouseMgr.h
src/server/game/Combat/ThreatManager.h
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/GameObject/GameObject.h
src/server/game/Entities/Player/Player.h
src/server/game/Globals/ObjectMgr.h
src/server/shared/DataStores/DBCStructure.h
src/tools/map_extractor/System.cpp
src/tools/map_extractor/mpq_libmpq.cpp
src/tools/mmaps_generator/MapBuilder.cpp
src/tools/mmaps_generator/TerrainBuilder.cpp
src/tools/vmap4_extractor/gameobject_extract.cpp
src/tools/vmap4_extractor/mpq_libmpq.cpp
src/tools/vmap4_extractor/vmapexport.cpp

- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-loop-convert`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html
This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:
- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go
You can help by testing PRs and writing your feedback here in the PR's page on …

refactor(Core): apply clang-tidy modernize-loop-convert

---

src/server/game/Entities/Player/Player.cpp

- Fixed a typo made in Rest & Inn Improvements
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3879
-  Portals are now working again.
Repeat the steps in issue https://github.com/azerothcore/azerothcore-wotlk/issues/3879

fix(Core): a typo introduced in the Rest & Inn Improvements

---

.github/workflows/core_build.yml

-  add macos-11.0 to core build  
- Closes none

feat(CI): add macos-11.0 to core-build

---

data/sql/updates/pending_db_world/rev_1608331608234968600.sql

This change will change the position of the initial NPCs for undeads, draeneis, gnomes/dwarf, orcs amd blood elfs.
I have already fix two, for Humans and Night elfs in the Pull Request #3763 
Source:
- Gnome & Dwarf:
https://www.youtube.com/watch?v=TvDP-BUOBvU&ab_channel=JamesPierce - 0:27
- Draenei:
https://www.youtube.com/watch?v=edbZut-mGRY&ab_channel=AwbeeX57 - 1:15  [Warmane - High Quality]
https://www.youtube.com/watch?v=k8lEKHHoPlk&ab_channel=StephenRussell - 1:14  [Retail - Low Quality]
- Blood elf:
https://www.youtube.com/watch?v=L4t_zn6ioEQ&ab_channel=jhonny1ooo - 1:15
- Orc:
https://www.youtube.com/watch?v=zPrnGIl4Mu0&ab_channel=EvilDemonMasterGaming - 2:30
- Undead:
https://www.youtube.com/watch?v=R9TWpPYK40o&ab_channel=superphil90 - 1:00
-  Adjust initial NPCs position as it …

fix(DB/creature): Improve starting NPCs

---

src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/boss_infinite.cpp

Instance: Culling of Straholme
Boss: Infinite corruptor
The spell "Corrupting Blight" should be removed from all players when the boss dies.
Source:
https://www.youtube.com/watch?v=dFg7rtEyQS0&ab_channel=MichaelHsiao
**4:05:** Some players can be seen with the debuff applied (tab at left side/group interface).
**4:22:** Once the boss dies the debuff is removed from all players.
- Remove "Corrupting Blight" at Infinite Corruptor's dead
- Add missing brackets
- Currently when the boss is defeated players have to wait 2 mins until everyone is clean before engaging Mal'Ganis (final boss)
- Built core
- Tested in live/prod server (for reference, link in my profile)
- Run "CullingOfStratholme" in Heroic difficulty until you get to "Infinite Corruptor" before the time for it is over.
- Engage …

fix(scripts/CullingOfStratholme): Remove "Corrupting Blight" at Infinite Corruptor's death

---

.github/workflows/check_pending_sql.yml

-  update the procedure/function check to filter out text between single quotes. (So if procedure or function get's used in creature_text it won't trigger a false positive on the check)
- Closes 

fix(CI): update procedure/function check

---

src/server/game/Entities/Object/Object.cpp

Co-Authored-By: Meltie2013 <Meltie2013@users.noreply.github.com>
Imported from https://github.com/Meltie2013/azerothcore-wotlk/commit/550fede1671613a844545f8810b986a31892fe5d
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4048
- https://github.com/azerothcore/azerothcore-wotlk/issues/4048#issuecomment-751297797
- check issue

fix(Core/Object): Fix small error in Position::IsWithinBox

---

data/sql/updates/pending_db_world/rev_1609001966856175000.sql

-  Fix [Soaked Pages] GO respawn time
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4060

fix(DB/gameobject): Quest 'Soaked Pages' GO respawn time

---

data/sql/updates/pending_db_world/rev_1609174873784850500.sql

-  Add script to Galaen.
- Remove Galaen spawn.
- Make Galaen non-attackable.
- Add correct aura to Galaen's Corpse so it looks dead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4078
- Windows
- .go c 84398
- .q a 9578
- .q c 9578
- Take Galaen's Fate from the corpse.
Before, nothing happend, Galaen was already spawned and could be attacked and killed by the blood elves.
After, Galaen spawns correctly and does his thing.

fix(DB/Quest): Galaen's Fate

---

data/sql/updates/pending_db_world/rev_1609803806703890000.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4092
- `.go c id 17986`
- aggro an Enraged Ravager
- bring it to the Demolitionist
- verify that he does not cast lightning shields

fix(DB/SmartAI): Demolitionist Legoso weird behavior

---

data/sql/updates/db_world/2021_01_07_00.sql

We really need a check for this @locus313 ... Can't allow things like this to pass

fix(DB/Update): Fix missing delete

---

apps/installer/includes/os_configs/osx.sh

-  add workaround for brew failing to add the symlink bin/2to3
- Closes none

fix(CI/MacOS) workaround for configure os failing

---

data/sql/updates/pending_db_world/rev_1609978307795332000.sql

-  Add graveyard for zone 3479 (better and closer than it was :D ) 
- Closes [4218](https://github.com/azerothcore/azerothcore-wotlk/issues/4218)
- Graveyard if u die in zone 3479
-
1. .go -2756 -12401 -10 530
2. select yourself then .die
3. release spirit

fix(DB/Graveyard): add ghostZone for zone 3479

---

src/server/game/Battlegrounds/Zones/BattlegroundSA.h
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Scripting/ScriptMgr.h
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter2.cpp
src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp
src/server/scripts/Northrend/zone_dalaran.cpp
src/tools/vmap4_extractor/wmo.cpp

https://www.codefactor.io/repository/github/azerothcore/azerothcore-wotlk/issues?category=Style&groupId=838
Last ones that were missed in the previous PR =)

chore(core): Remove malformed whitespace

---

.github/README.md

- Remove Codacy as the repo it points to does not exist
- Add Codefactor instead as that is what we use atm
- Remove Coverty scan as it has not run for 8 months and doesn't run since we removed Travis

chore(README): Add codefactor

---

src/server/game/AI/CreatureAI.cpp
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Object/Object.cpp
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Maps/Map.cpp
src/server/game/Maps/Map.h
src/server/game/Miscellaneous/SharedDefines.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
src/server/game/Spells/Spell.cpp

- fix issue with creatures spawning under map (for example Violett Hold portal guards)
- fix issue with hunter trap placement in some areas like dalaran, probably some other objects and in general refactor summon code used by spell
- fix issue with mob moving back too far or too close to the player making it hard to control boss in raids like ICC
- Closes  #4247 #4203
- Compiled
- Tested locally in different instanced and with different NPCs

Fix new bugs created by new Pathfinding System + Refactor some Code

---

data/sql/updates/pending_db_world/rev_1610598175630537700.sql
src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp
src/server/scripts/World/npcs_special.cpp

-  Properly setpvp for these creatures.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4261
- https://i.imgur.com/4a46MYJ_d.webp?maxwidth=760&fidelity=grand
-

fix(Core/Creature): Set PvP flag for some creatures

---

data/sql/updates/db_world/2021_01_14_01.sql

https://github.com/azerothcore/azerothcore-wotlk/pull/4270

chore(2021_01_14_01.sql): int not string

---

data/sql/updates/pending_db_world/rev_1607523114128420000.sql

**This PR will add some important teleports which were missing and makes Gamemaster's life easier.**
From Classic - TBC you are able to teleport instantly to every Dungeons entrance - Example: 
- .tele 726 (RagefireChasm)
- .tele 106 (BlackTemple)
For WotLK you have to walk far... - Example:
- .tele 1393 (TheNexus) It's the only teleport for The Nexus, Oculus and The Eye
same here 
- .tele 1419 (TheFrozenHalls) only one teleport for The Forge of Souls, Pit of Saron and Halls of Reflection.
- None
- Applied SQL Script
- Tested every teleport ingame
**1. Apply SQL script**
**2. To test you need to have an GM Account (account set gmlevel "accname" 3 1)**
**3. Test all the following teleports with .tele ID / tele Name and enjoy:**
- 455 (AzjolNerub) (Updated location)
- 1435 (TheStockade)
- …

feat(DB/game_tele): Improve GM Teleports

---

src/server/game/AI/CreatureAI.cpp
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Movement/Spline/MoveSplineInit.cpp

…in circle if creature is vicitim of the player - dont move too far away in circle movement (for example if creature is caster)
- dont move creature in circle if need to move backwards 
- dont move in circle if creature is vicitim of the player 
- dont move too far away in circle movement (for example if creature is caster)

Improvements to Creature CircleMovement (Pathfinding)

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Spells/Spell.cpp

-  Implement GetFreeInventorySpace() from TrinityCore
- change p_caster to player so this PR is the base for the two other
- Builds
- https://github.com/azerothcore/azerothcore-wotlk/pull/4298
- https://github.com/azerothcore/azerothcore-wotlk/pull/4296

feat(Core/Player): GetFreeInventorySpace()

---

src/server/game/Spells/SpellMgr.cpp

-  Add the spell [Death Plague ](https://db.rising-gods.de/?spell=55645) for 10mode and 25mode in Spell Manager
- Add comments to other unidentified spells in Spell Manager
- Built core
Go Naxxramas -> Gothik The Harvester
Initiate encounter, wait for unrelenting trainee to spawn and get some stacks from multiple of them
- N/A

fix(Core/SpellMgr): Death Plague stacks

---

apps/ci/ci-install.sh

-  temporarily restore ci-install.sh (so ci build's work for modules, until we can put in place a new solution) 
- Closes 

fix(CI): temp restore ci-install.sh

---

src/server/game/DataStores/DBCStores.cpp

This will not fix the build, but will fix one of the 2 issues causing it to fail.

fix(gcc): type warning

---

.github/workflows/core_build.yml

-  noticed the cache for the mac builds has not been posting:
this change makes it so the cache posts correctly
- Closes 

fix(CI/macOS): solve ccache issue

---

data/sql/updates/pending_db_world/rev_1611685103659442481.sql

-  ported from https://github.com/TrinityCore/TrinityCore/commit/82f6d482732e621882fa536ee04368034f78e00a
- I changed the guid to be more coherent with ours, moreover the guid proposed from the TC PR were already used in our db
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4348
- Closes https://github.com/chromiecraft/chromiecraft/issues/19
Tested in-game, I used the item in Ironforge and in Moonglade near humans, trolls, and gnomes.
Of course, if you are alliance and try to teleport to a horde capital it will not work.
- create a dwarf or gnome
- `.go xyz -4662.059316 -956.693726 500.893890 0`
- `.additem 21711`
-  use the item
- it will teleport you to Moonglade
- now you can use the item inside the moonlight area near the NPCs of your faction to teleport you to a …

feat(DB/SAI): lunar festival invitation teleport

---

data/sql/updates/pending_db_world/rev_1612094222775369000.sql

* https://github.com/TrinityCore/TrinityCore/commit/468d47f53e9269ee74f44313fbc0d69e2b190b87
-  Remove duplicate gossip
-  Add correct conditions for the gossip
-  Update SAI
1. go c id 15895
2. see no gossip to add another Lunar Invitation
2. . q add 8867
3. .q comp 8867
4. Hand in quest, get Lunar Invitation
5. See no gossip to add another Lunar Invitation
6. Delete item
7. See now there is a gossip to add another Lunar Inviation

fix(DB/Creature): Lunar Festival Harbinger gossip

---

.dockerignore

Apparently including cmake cache to the build context will take a long time for consecutive builds and causes docker build to spend a long time at `Sending build context to docker daemon (x %)` step.
-  add cmake cache to dockerignore so it is not copied to context when starting a docker build as it is not used in the image and causes a huge slowdown (the cache is used through a volume for the actual build, not for the `docker build` command)
- none
- without changes use docker to build the core.
- build the core again and see the slowdown caused by the old cmake cache
- add this PR
- build the core again and see that its now faster to start even if the old cmake cache is there
- This was reported by someone else, so I have not tested this. just making the PR. …

fix(Docker): add cache to dockerignore to speed up local build

---

data/sql/updates/pending_db_world/rev_1612101065652299500.sql

* https://github.com/TrinityCore/TrinityCore/commit/9f7824cbf00f22456054345c55b1b63831d85ada
-  Proof https://classic.wowhead.com/item=3718/foreboding-plans
Not really needed, but here you go :)
1. Delete your client cache
2. .add 3718
3. read it

fix(DB/Item): Foreboding Plans text

---

data/sql/updates/pending_db_world/rev_1612796984747044500.sql

-  Adds syntax/description to GM command ```.achievement checkall```

fix (DB/Commands): Add Syntax to Command .achievement checkall

---

data/sql/updates/pending_db_world/rev_1613069340138846000.sql
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h

- This PR targets `pathfinding-fix3`, not master.

chore: add improvements

---

data/sql/updates/pending_db_world/rev_1613069340138846000.sql
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp

Co-authored-by: Francesco Borzì <borzifrancesco@gmail.com>
- fix UpdateEnvironmentIfNeeded was changing flying creature status all the time. closes: #4447
- fix hovering state was causing bugs at #4466
- add animation state priortiy: fly > hover > ground

Fix new Creature Movement Bugs

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Handlers/LootHandler.cpp
src/server/game/Loot/LootMgr.cpp
src/server/game/Loot/LootMgr.h

Correct the problem that the bag when obtaining the item, by one of the group members, currently does not disappear, and remains so, until the body disappears. In this way, it is prevented the immediate stripping of the creature being in a group for example.
- Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/4399
https://github.com/chromiecraft/chromiecraft/issues/20
- Windows
Create a group, and perform a quest with an item that must be obtained by killing a creature. If the item does not have the flag that everyone can obtain it, only 1 should be able to obtain it. …

Gathering Quest While in Party bug

---

data/sql/updates/pending_db_world/rev_1612679130179828100.sql

-  Chinese translations
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4464
- None
1. Use zhCN client
2. .additem ID

fix(DB/Item): Chinese locale

---

data/sql/updates/pending_db_world/rev_1613390656721660682.sql

-  Remove Tormek Stoneriver, he was removed in patch 3.3.0.
-  Deprecate his 3 identically named quests
- Closes #4531
- Applied SQL
- His quests are gone
- He is gone (well, I tested it in steps)
- Make sure event "Love is in the air" is active.
- `.go c id 16009`
- Check if creature exists and if there are quests to be had

fix(DB/creature/quests): Remove Tormek Stoneriver and his quests

---

src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_garr.cpp

Change the timer of Garr abilities to be blizzlike
-  See https://github.com/azerothcore/azerothcore-wotlk/issues/4561
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4561
- .tele moltencore
- fight garr, check how often he casts his abilities

Fix Garr abilities timers

---

data/sql/updates/pending_db_world/rev_1613517719180332000.sql

-  Fixed position for NPC Rocklance and guars (Kolkar Marauder & Kolkar Bloodcharger)
- Closes [4582](https://github.com/azerothcore/azerothcore-wotlk/issues/4582)
1) Apply SQL
2) .go xyz -1228.5 -3167.5 92.8 1
3) You should see npc 

fix(DB/Creature): Position NPC Rocklance

---

data/sql/updates/pending_db_world/rev_1613582099030998500.sql

-  Change of NPC coordinates: [Amani Berserker](http://wotlk.cavernoftime.com/npc=15643) Guid-DB: `55632`
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4483 
- Closes https://github.com/chromiecraft/chromiecraft/issues/39
https://user-images.githubusercontent.com/1884642/108254980-87d46500-7153-11eb-89d6-111ceee261ca.mp4

fix(DB/Creature): Amani Berserker XYZO

---

data/sql/updates/pending_db_world/rev_1613843733957350900.sql

-  **Fix Menu Gossip**
- Closes https://github.com/chromiecraft/chromiecraft/issues/48
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4463
- **Video Test:** [NPC - Gubber Blump](https://youtu.be/QuJr18__K4A)

fix(DB/Creature): Gubber-Blump-missing-gossip

---

.git_commit_template.txt

- add "CO-AUTHORS" segment to  `.git_commit_template.txt`
- The idea is not my own, I just worded it (poorly) and made a PR for it as I like the idea
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4535
- None

chore(git): Add a co-author suggestion to the commit template

---

data/sql/updates/pending_db_world/rev_1613848536903926000.sql

- Fix the animation on the Sparklematic 5200
- Fix Techbots missing texts, spell conditions and dupe bug management
- Remove non-summoned dupe bugs from the creature table
- Fix the Irradiation Aura on irradiated creatures
- Fix duplicted text on creature ID 6223 and 6224 (Leper Gnomes)
- Fix irradiation splash damage SAIs and texts for nearby creature   
Techbot (id: 6231) is missing some texts, spell conditions, and dupe bug managment
Sparklematic 5200 (id: various) Missing animation on quest completion
Irradiated Mobs missing irradiation auras
Leprous Mobs have texts duplicated in DB
Various Mobs missing irradiation splash texts and spellhit SAI
Reference:
https://github.com/TrinityCore/TrinityCore/issues/18825
https://github.com/TrinityCore/TrinityCore/issues/18737 …

fix(DB): Fix Some Gnomeregan Issues - Missing Animations, Spells and Texts

---

data/sql/updates/pending_db_world/rev_1614071599270991320.sql

-  Pool all copper veins (there are only 3 of them, so the direct value of this PR is limited... but it makes sense if more spawn points are added later)
- This is a nicer way to control mining nodes
- Relevant for AzerothCore issue #4518 (but it does not close it)
- Teleport around
```
.go xyz -2411.3 -11965 13.399 530 -- 120324 Bloodmyst Isle, Copper Vein, spawn 1
.go xyz -2614.69 -12192.1 28.0703 530 -- 120325 Bloodmyst Isle, Copper Vein, spawn 2
.go xyz -2623.13 -11772.2 9.2479 530 -- 120363 Bloodmyst Isle, Copper Vein, spawn 
```

fix(DB/object): Pool copper veins on Bloodmyst Isle

---

data/sql/updates/pending_db_world/rev_1614187724074625300.sql

-  Add waypoints, missing spell and adjust scale to Viscous Fallout. 
-  Fix Combat Reach for Viscous Fallout due to scale change.
- Add missing spell/abilities to Corrosive Lurker, Irradiated Slime, and Irradiated Horror mobs.
- Viscous Fallout mini-boss missing pathing, spells, and scale is too small
- Irradiated Slime missing spell
- Irradiated Horror missing spell and aura
- Corrosive Lurker missing spell
- Merged SQL Successfully
- Checked Viscous Fallout size, combat reach, waypoints, and spells
- Checked spells for other mobs
- Go into the Gnomeregan Instance
- Check Viscous Fallout size - It should be noticeably larger than the Horrors , 
- Check if it is moving along a waypoint instead of being in a corner. 
- Check its combat reach and that it will continue to melee hit your …

fix(DB): Gnomeregan - Viscous Fallout and Minions Update

---

data/sql/updates/pending_db_world/rev_1614416165680486700.sql

- I spent the last two days freaking out behind this NPC, despite all the changes made to the SAI, and various attempts to modify the Template of the Creature I could not understand what was preventing the creature from attacking the mobs and therefore assisting the Player in the quest.
Then making an attempt to change faction, I realized that with another type of faction, the NPC attacked the other mobs.
But the problem was that I couldn't use another faction, because it wouldn't be the right one for NPCs.
- So I went to check the FactionTemplate.dbc file, I compared it to the faction I had used to do the test, and copying some parameters, I was able to Fix the Faction that was (evidently) buggy and finally, I converted that data in an SQL query.
- I had to edit most of the creature's …

fix(DB/Creature/SAI): Quest Mist Disappearing cat

---

data/sql/updates/pending_db_world/rev_1614656086454361900.sql

Co-Authored by @55Honey 
-  Update "Z position" for gobjects in-game with GUID 1399 and 631
- Closes #4675 
- Tested SQL query = /* Affected rows: 2  Found rows: 2  Warnings: 0  Duration for 4 queries: 0.000 sec. */
- Tested in-game as shown below:
1- Execute SQL query
2- .go gobject 1399
3- .go gobject 631
- N/A

fix(DB/gameobject): Underground Herbs in Mulgore

---

data/sql/updates/pending_db_world/rev_1615014079681051900.sql

-  Use [Lesser Heal](https://wotlkdb.com/?spell=2053) instead of [Chain Heal](https://wotlkdb.com/?spell=48894)
Proof / Evidence:
Source: https://wotlkdb.com/?npc=1895
- Closes #4728 
- Tested query
- Tested in-ingame
.go c id 1895
Get some mobs and damage them a little so the SAI makes him heal his comrades with "Lesser Heal"
- N/A

fix(DB/smart_scripts): Pyrewood Elder - Healing SAI

---

data/sql/updates/pending_db_world/rev_1614722186740264425.sql

- added the missing text in a book
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4683
- `.additem 5860`
- read the last page (11) of the book

fix(DB/Page): update legacy aspects

---

data/sql/updates/pending_db_world/rev_1614914535237106700.sql

-  Added Aura to GameObject [Bubbling Fissure](https://wowgaming.altervista.org/aowow/?object=3737)
- Closes https://github.com/chromiecraft/chromiecraft/issues/119
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4716
- **Video Test:** [Bubbling Fissure](https://youtu.be/kcOd_XKB0ek)

fix(DB/GameObject): Bubbling Fissure

---

src/server/game/Spells/SpellEffects.cpp

-  improve the fishing time, porting from https://github.com/TrinityCore/TrinityCore/pull/23448/files
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4732
- Closes https://github.com/chromiecraft/chromiecraft/issues/140
- didn't test
- https://github.com/TrinityCore/TrinityCore/pull/23448

fix(Code/Fishing): improve timing of fishing

---

data/sql/updates/pending_db_world/rev_1614921496929991300.sql
src/server/scripts/Kalimdor/zone_dustwallow_marsh.cpp
src/server/scripts/ScriptLoader.cpp

-  This fixes the The Missing Diplomat quest chain to include Quest: 1250 and
add the end event.  
- Also converts Private Hendel, Archmage Tervosh, Mikhail,
and Tapoke Jahn to smart scripts from C++ scripts.
- Note: Core code zone_wetlands.cpp is no longer being used.  Commented out all calls in ScriptLoader.cpp
- Quests: 1249,1265,1324 (The Missing Diplomat) are missing important parts
of the quests including the end of the quest chain event.
- Fix some minor Guard orientations and add missing waypoints to Dustwallow Marsh
guard towers.
Closes #4725
Closes chromiecraft/chromiecraft#132
- Ran through The Missing Diplomat quest chain starting at Quest: 1248
- Was able to see the end event and turn in quests near Private Hendel
Built without errors.
- .go creature Mikhail
- .quest add 1248 …

fix(Core/DB):Fix Missing Diplomat Quests Part 11,14,16 and Minor Guard Tower Fixes

---

data/sql/updates/pending_db_world/rev_1615190253062057000.sql

-  I had to Fix the creature's SAI; in that, he had as Target himself.
-  I had to fix the [Supercharge](https://wowgaming.altervista.org/aowow/?spell=10732) spell too, because it didn't work, even if the SAI was correct, in any case the spell didn't work and therefore it didn't Buff the mechanical NPCs.
- Closes https://github.com/chromiecraft/chromiecraft/issues/134
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4731
- **Video Test:** [Leprous Machinesmith](https://youtu.be/6Rs1VISkCsw) …

fix(DB/Spell+CreatureSAI): Leprous Machinesmith

---

data/sql/updates/pending_db_world/rev_1615200382358521000.sql

-  Correction SAI Actions list
- Closes https://github.com/chromiecraft/chromiecraft/issues/141
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4735
- **Video Test:** [Quest - Denalan's Earth](https://youtu.be/i0enGRiq8lo)

fix(DB/CreatureSAI): Quest Denalans Earth

---

data/sql/updates/pending_db_world/rev_1615210246361880600.sql

-  Added SAI to NPC: [Gnarlpine Mystic](https://wotlk.evowow.com/?npc=7235)
- Closes https://github.com/chromiecraft/chromiecraft/issues/148
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4740
- **Video Test:** [Gnarlpine Mystic](https://youtu.be/lwjEMJDsCOw)

fix(DB/CreatureSAI): Gnarlpine Mystic

---

data/sql/updates/pending_db_world/rev_1615212672744788600.sql

-  Moving GameObject Coordinates [Giant Clam](https://wowgaming.altervista.org/aowow/?object=19017)
- Closes https://github.com/chromiecraft/chromiecraft/issues/129
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4730
- **Screenshot:** 

fix(DB/GameObjectSpawn): Floating Giant Clam in Ghostlands

---

data/sql/updates/pending_db_world/rev_1612424906607643097.sql
data/sql/updates/pending_db_world/rev_1615289798727272419.sql

-  You need to be a skinner for the quest Gathering Leather
-  https://classic.wowhead.com/quest=768/gathering-leather
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4766
- Closes chromiecraft/chromiecraft#173
- Applied SQL
- Tried to pick up the quest as a skinner and not
- `.go c id 3050`
- `.learn 8613` (skinning)
- Talk to Veren Tallstrider

fix(DB/quest): Gathering Leather requires skinning

---

data/sql/updates/pending_db_world/rev_1615449389814904181.sql

-  Add spirit healer to Eastern graveyard in Arathi Highlands
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4785
- Closes https://github.com/chromiecraft/chromiecraft/issues/176
- Applied SQL
- Died and ressed (works for both alliance and horde)
- `.tele witherbark`
- `.die`

fix(DB/Creature): Add spirit healer to Eastern graveyard in Arathi Highlands

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgr.h

Hook: OnSendInitialPacketBeforeAddToMap
- Adds a hook for modules to use
- This hook will allow me to make my TimeIsTime module available

feat(Core/Hook): OnSendInitialPacketBeforeAddToMap

---

data/sql/updates/pending_db_world/rev_1615495161722587900.sql

-  SAI Spell changed to over 80+ NPCs
- Closes https://github.com/chromiecraft/chromiecraft/issues/115
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4673
- **Video Test:** [Various mobs in Tirisfal](https://youtu.be/mW6IqYpu02k)

fix(DB/CreatureSAI): Various mobs in Tirisfal

---

data/sql/updates/pending_db_world/rev_1615534981848336924.sql

-  Remove requirement for finishing quest 39 (Deliver Thomas' Report)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4800
- Closes https://github.com/chromiecraft/chromiecraft/issues/161
- Here they say the current version is correct: https://wotlkdb.com/?quest=39 (see lower right corner)
- Here they say the current version is wrong: https://classic.wowhead.com/quest=46/bounty-on-murlocs
- I assume wowhead is the better source and as such the change is valid
- Applied SQL
- Checked quest giver
- `.go c id 261`
- Talk to Thomas

fix(DB/quest): Bounty on Murlocs has no prerequisite

---

data/sql/updates/pending_db_world/rev_1615548043862503366.sql

- Missing SmartAI for Feegly the Exiled (taken from TC)
- Move his spawn position slightly
- Make him move
- Closes https://github.com/chromiecraft/chromiecraft/issues/193
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4814
- It should look more like this https://www.youtube.com/watch?v=4IMqLWg3eW4&t=165s now
- Applied SQL
- Turned in quest
- `.quest add 857`
- `.go c id 3421`
- `.additem 5038`
- Watch Feegly

fix(DB/quest): The Tear of the Moons

---

data/sql/updates/pending_db_world/rev_1615554526122337545.sql

- Make her move using the basic random AI (she currently just stands there)
- Some movement here: https://www.youtube.com/watch?v=f-fose1oE-w&t=4116s
- I found several Youtube videos with her moving, but unable to see if it's a path or just bumbling around in the area... So she will just bumble around now
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4774
- Applied SQL
- Watched her walk around
- `.go c id 2184`

fix(DB/Creature): Make Lady Moongazer move around

---

data/sql/updates/pending_db_world/rev_1615643547619605800.sql

-  Change NPCs [Mosshide Gnoll](https://classic.wowhead.com/npc=1007/mosshide-gnoll), [Mosshide Mongrel](https://classic.wowhead.com/npc=1008/mosshide-mongrel) coordinates
- Closes https://github.com/chromiecraft/chromiecraft/issues/164
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4802
- Screenshot

fix(DB/Creature-Spawn): Gnolls Underground in Wetlands

---

data/sql/updates/pending_db_world/rev_1615645470313391100.sql

-  Change GameObjects  [Copper Veins](https://classic.wowhead.com/object=1731/copper-vein)  coordinates
- Closes https://github.com/chromiecraft/chromiecraft/issues/165
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4803
- Screenshot

fix(DB/GameObject-Spawn): Copper Veins above Jangolode Mine

---

data/sql/updates/pending_db_world/rev_1615647120285678400.sql

-  Created SAI for GameObject [Bubbly Fissure](https://wowgaming.altervista.org/aowow/?object=177524)
- Closes https://github.com/chromiecraft/chromiecraft/issues/166
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4804
- Screenshot

fix(DB/GameObject-SAI): Bubbling Fissures in Moonglade

---

data/sql/updates/pending_db_world/rev_1615649181432525500.sql

-  Added GameObjects in Table **game_event_gameobject**
- Closes https://github.com/chromiecraft/chromiecraft/issues/167
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4805
- Screenshot

fix(DB/GameObject-SpawnEvent): Brewfest banners in Darnassus

---

data/sql/updates/pending_db_world/rev_1615996084725804000.sql

-  Update Z pos for Dreadmaw Crocolisk
- Closes #4888 
- Closes https://github.com/chromiecraft/chromiecraft/issues/224
**- Before:**
**- After:**
.go c 13565
- N/A

fix(DB/creature): Dreadmaw Crocolisk's position

---

data/sql/updates/pending_db_world/rev_1615866400966239600.sql

-  Accommodation of a fix I had made.
Probably, I got confused and filled the whole `factiontemplate_dbc` table,
**(but without the faction's modification that I had made before).**
So this fix is used to fix the previous fix.
- Closes https://github.com/chromiecraft/chromiecraft/issues/210
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4865
- Closes https://github.com/chromiecraft/chromiecraft/issues/159
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4783
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/4786
- **Video Test:** [Ruul Snowhoof](https://youtu.be/9S8eg9G6SkA) …

fix(DB/Fix Faction): Quest: Freedom to Ruul

---

src/server/game/Loot/LootMgr.cpp

-  Add a gold check into HasItemForAll, which stops it reporting false in Player::IsAllowedToLoot
- Closes #4839
- Kill the drakes a lot and loot
-

fix(Core/Loot): Gold should always be lootable, even if it's the only loot

---

data/sql/updates/pending_db_world/rev_1615883540984618200.sql

-  SAI adjustment, and Spell added in the template
- Closes https://github.com/chromiecraft/chromiecraft/issues/169
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4807
- **Video Test:** [One Shot  One Kill](https://youtu.be/ZCep83j4sG4)

fix(DB/CreatureSAI): Quest: One Shot One Kill

---

data/sql/updates/pending_db_world/rev_1615990232375736422.sql

- Pool treasures in Teldrassil
- 10 spawn locations, 4 in the pool
- Lower respawn to 5 minutes
- This should make it more enjoyable to visit the starting zone for nelves if there are multiple players at once.
- Applied SQL
- Visited all locations, twice
- `.go object 49528,49529,49621,49622,49623,49624,49625,49626,49627,49628` (only select 1 guid at a time)

fix(DB/pool_template): Treasures in Teldrassil

---

data/sql/updates/pending_db_world/rev_1616012094656299200.sql

Fix Quest: [Call of Water 5/6](https://wowgaming.altervista.org/aowow/?quest=9508)
-  NPCs spawns coordinates changed [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and 2 [Water Spirit](https://wowgaming.altervista.org/aowow/?npc=6748)
-  Added SAI to Creature [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and [Water Spirit](https://wowgaming.altervista.org/aowow/?npc=6748)
- Added SAI to GameObject [Barrel of Filth](https://wowgaming.altervista.org/aowow/?object=181699)
- GameObject spawn coordinates changed [Barrel of Filth](https://wowgaming.altervista.org/aowow/?object=181699)
- Added Text for SAI to Creature [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and [Water …

fix(DB/CreatureSAI/GameObjectSAI): Quest Call of Water 5/6

---

data/sql/updates/pending_db_world/rev_1615704736281325400.sql

- Stranglethorn Fever missing Text, Waypoints, and scripts
- Perry Gatner Event Missing.
- Kylene the Barmaid should roam the tavern
- Fix Stranglethorn Fever Quest missing text and Gorilla waypoints
- Add Perry Gatner Event in Shattrath City.  (Will start every four hours)
- Perry Gatner and Albert Quarksprocket waypoints adjusted
- Shattrath Saul, Perry Gatner, and Albert Quarksprocket smart scripts improved
- Kylene Barmaid has stopped dancing and now roams the Tavern and will randomly react to the Perry Gatner event
- Tinkerbell now wanders
- Tested Stranglethorn Fever Witch Doctor Event and completed it.
- Started (also waited for the auto start time) Perry Gatner event and watched it run to its completion.
- Stranglethorn Fever
- .go creature witch_doctor_unbagwa
- .quest add 348
- …

fix(DB):Stranglethorn Fever Fixes - Perry Gatner Event

---

src/server/game/Maps/Map.cpp
src/server/game/Maps/Map.h
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp

FleeingMovementGenerator: Improved fleeing movement generator by calculating a new path to collision point.
Fixed #4769.
- Fixed collision calculations.
-  Improved fleeing movement generator, by calculating a new path to collision point.
-  Fixed copypasta.
- Closes #4769 
- Tested on battlegrounds (more info in addressed issue)
-

fix(Core/Movement): Fixed collision calculation returning wrong position.

---

src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgr.h
src/server/game/Server/WorldSocket.cpp

-  Add new hook:
```cpp
void OnLastIpUpdate(uint32 accountId, std::string IP);
```
- Tested locally using https://github.com/azerothcore/mod-ip-tracker
- Checkout this PR
- Install this module https://github.com/azerothcore/mod-ip-tracker
- Try to login and check the `acore_auth`.`account_ip` table

feat(Core/Hooks): OnLastIpUpdate(accountId, ip)

---

src/common/Utilities/TaskScheduler.cpp
src/common/Utilities/TaskScheduler.h

-  See https://gist.github.com/Naios/6d143538abdc3d32fd2b for usage examples.
- Part #4112
- Part #4898
- Support new module https://github.com/WarheadCore/mod-server-auto-shutdown
- #4112
- #4112
- https://github.com/WarheadCore/mod-server-auto-shutdown

feat(Core/Utilities): Introduce a task scheduler which schedules task

---

.github/ISSUE_TEMPLATE/bug_report.md
pull_request_template.md

-  Adjust the "source" field
-  Change description to go in accordance with the PR purpose
- The "source" field is not being displayed correctly on new PRs
- The description was no the correct one

fix(IssueTemplate/PullRequestTemplate): Adjustment and fix typos

---

data/sql/updates/pending_db_world/rev_1616747334374476238.sql

- He should only summon adds once not twice
- He will now summon once from 0-50% health and not at both 50% and 25% health
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4946
- Video showing the fight in Classic: https://youtu.be/j01MfraN6b0?t=3232
- Applied SQL
- Had a meetup with VanCleef, it seems to work fine
- `.go c id 639`
- Fight VanCleef, notice when he summons.

fix(DB/SAI): Edwin VanCleef encounter

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Spells/SpellInfo.cpp

-  Bug originated due to changes in CheckLocation()
-  Remove duplicate code
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5013#issuecomment-808317120
- Builds
1. Test so flying works as expected in all maps (Classic, TBC, WotLK)
2. Fly over dalaran, see that you get the debuff no fly zone

fix(Core/Spell): Restricted Flight Area

---

data/sql/updates/pending_db_characters/rev_1616857517874136100.sql
src/server/game/Warden/WardenWin.cpp

Removed any action from false positive warden check.
Fixed #5017
-  Added to `warden_action` overriden entry.
-  
- Closes #5017
- 
-  …

fix(Core/Warden): Fixed random kicks caused by warden.

---

src/server/game/Entities/Creature/Creature.cpp

Fixed #5030
-  Fixed unitialized variable.
-  
- Closes #5030
- 
- 

fix(Core/Creatures): Fixed unitialized varibale implemented in 728d018.

---

apps/installer/includes/os_configs/debian.sh

-  add curl and unzip for debian 10 (required for the client-data download)
- Closes 
-  …

fix(BASH/INSTALLER): add missing deps for debian 10

---

data/sql/updates/pending_db_world/rev_1616536931445376664.sql

-  Fix herb spawn or wrong placement at Stonetalon Mountains and Redridge Mountains
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4971 https://github.com/azerothcore/azerothcore-wotlk/issues/4972
- SQL applied
- Go to locations reported in issues, check fixed spawn points.

Fix herb spawn and position at two maps

---

data/sql/updates/pending_db_world/rev_1616686614747472700.sql

- Fixed Faction NPC [Demolitionist Legoso](https://wowgaming.altervista.org/aowow/?npc=17982)
- Fixed Stats NPC [Demolitionist Legoso](https://wowgaming.altervista.org/aowow/?npc=17982)
- Fixed Respawn NPC [Demolitionist Legoso](https://wowgaming.altervista.org/aowow/?npc=17982)
- Fixed SAI NPC [Demolitionist Legoso](https://wowgaming.altervista.org/aowow/?npc=17982)
- Fixed Waypoints NPC [Demolitionist Legoso](https://wowgaming.altervista.org/aowow/?npc=17982)
- Added New ID NPC EventTriggerSAI Named Q-9759 Trigger Barrel Bomb
- Added SAI New ID NPC Q-9759 Trigger Barrel Bomb
- Added SAI GameObject [Barrel](https://wowgaming.altervista.org/aowow/?object=180779)
- Fixed SAI NPC [Sironas](https://wowgaming.altervista.org/aowow/?npc=17678)
- Fixed Stats NPC …

fix(DB/Quest): Ending Their World

---

data/sql/updates/pending_db_world/rev_1616755366269256667.sql

-  All races can do this (Horde side)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5000
- Closes https://github.com/chromiecraft/chromiecraft/issues/293
-  https://wotlk.evowow.com/?quest=367 - it counts for Loremaster
- TC allows it for all as well
- Applied SQL
- Picked up the quest as a tauren
- `.go c id 1518`
- Pick up the quest, you need to be something else than undead and level 6+.

fix(DB/quest_template): A New Plague is not just for undeads

---

data/sql/updates/pending_db_world/rev_1616756103204132721.sql

-  It should only be for Draenei
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4999
- Closes https://github.com/chromiecraft/chromiecraft/issues/292
-  https://wotlkdb.com/?quest=9429
- This is also the case in TC
- Applied SQL
- Not tested in game
- `.go c id 17103`
- be at least level 18, be a Draenei
- Pick up the quest

fix(DB/quest_template): Travel to Darkshire

---

data/sql/updates/pending_db_world/rev_1616620260846086881.sql

-  Fix wrong position and placement or multiple spawn of herbs
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4984
- SQL applied
- Go to locations reported in issues, check fixed spawn points. (.go object GUID and .gobject near) …

fix(DB) Wrong position or multiple placements of herbs

---

data/sql/updates/pending_db_world/rev_1617153703041946200.sql

- Fixed Stats NPC: [Helcular's Remains](https://wowgaming.altervista.org/aowow/?npc=2433)
- Fixed Faction NPC: [Helcular's Remains](https://wowgaming.altervista.org/aowow/?npc=2433) and NPCs Involved with Quest
- Faction: [Horde Generic 66](https://wowgaming.altervista.org/aowow/?faction=66) **(ID 83)**
- Faction: [HIllsbrad, Southshore Mayor 79](https://wowgaming.altervista.org/aowow/?faction=79) **(ID 96)**
- Fixed SAI NPC: [Helcular's Remains](https://wowgaming.altervista.org/aowow/?npc=2433)
- Added Waypoints NPC: [Helcular's Remains](https://wowgaming.altervista.org/aowow/?npc=2433)
- Fixed Text NPC: [Helcular's Remains](https://wowgaming.altervista.org/aowow/?npc=2433)
- Fixed Stats NPC: [Puppet of Helcular](https://wowgaming.altervista.org/aowow/?npc=2946)
- Fixed SAI NPC: [Puppet …

fix(DB/Creatures/GameObjectSAI): Quest Helcular's Revenge

---

data/sql/updates/pending_db_world/rev_1617176680426521000.sql

- Fixed Stats NPC: [Apprentice Mirveda](https://wowgaming.altervista.org/aowow/?npc=15402)
- Fixed SAI NPC: [Apprentice Mirveda](https://wowgaming.altervista.org/aowow/?npc=15402)
- Fixed Stats NPC: [Gharsul the Remorseless](https://wowgaming.altervista.org/aowow/?npc=15958)
- Fixed SAI NPC: [Gharsul the Remorseless](https://wowgaming.altervista.org/aowow/?npc=15958)
- Fixed Stats NPC: [Angershade](https://wowgaming.altervista.org/aowow/?npc=15656)
- Fixed SAI NPC: [Angershade](https://wowgaming.altervista.org/aowow/?npc=15656)
- Closes https://github.com/chromiecraft/chromiecraft/issues/213
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4868
- **Video Test:** [Unexpected Results](https://youtu.be/yh8Xm0hK9fw)
When …

fix(DB/CreaturesSAI): Quest Unexpected Results

---

data/sql/updates/pending_db_world/rev_1617197895526268300.sql

-  Fix Talen's missing emotes and smart scripts
-  Fix Ruuzel's missing waypoint data and creature formation
- Talen is missing smart scripts for scene after first turn in
- Ruuzel is missing waypoint data and creature formation
- Did the same tests as in the "How to test" section. 
- .quest add 1007 
- .add 5424
- .go c Talen
- Turn in quest to Talen and he should say text, perform emotes, and place statuette on the ground
- Accept the second part of the quest (Ruuzel) 1009 - Not really needed
- .go c Ruuzel
- Ruuzel should be moving now along a circular waypoint (instead of standing still) and should have two bodyguards following her through those waypoints …

fix(DB): The Ancient Statuette questline missing smart scripts and waypoints

---

data/sql/updates/pending_db_world/rev_1617265345631987700.sql

- Fixed Waypoints NPC: [Nancy Vishas](https://wowgaming.altervista.org/aowow/?npc=3984)
- Fixed SAI NPC: [Nancy Vishas](https://wowgaming.altervista.org/aowow/?npc=3984)
- Fixed SAI NPC: [Grandpa Vishas](https://wowgaming.altervista.org/aowow/?npc=3985)
- Closes https://github.com/chromiecraft/chromiecraft/issues/222
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4942
- **Video Test:** [Nancy Vishas](https://youtu.be/5WGoMcWPBao) …

fix(DB/SAI): NPC Nancy Vishas

---

data/sql/updates/pending_db_world/rev_1617306326870988315.sql

-  Fix spawn points of mineral veins
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5099
- SQL applied
- .go object 5236, 4755, 5746, 5199, 5637 …

fix(DB) Spawn placement of mineral veins - Redridge Mountains

---

src/common/Logging/Log.cpp

-  I changed GMLogFile -> GmLogFile in Log.cpp as the worldserver.conf.dist is.
- the GM Log conf does not work
- log in with a GM and run a command …

fix(Core/Log): GMLogFile -> GmLogFile

---

src/server/game/Entities/Player/Player.cpp

Walking on Water when alive after leaving BG whilst dead
-  On player revive, set the walking on water state to false.
- Closes #4768
- Compiled and Tested on Windows 10
.tele Durotar
Go West to a water source before going into the BG
.debug bg
Start BG
.debug bg
(Wait for the start time)
target yourself and .die
Release spirit and cancel the ressurection timer.
After 5 mins you can go back to Azeroth and test if you walk over water or not.
None …

fix(Core): Ghost property fix

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h

Ported from tc
-  Make use of SPELL_ATTR4_DONT_REMOVE_IN_ARENA
-  Move for loop into functions
<details>
<summary>These spells are affected by the flag</summary>
dbc_spell
---
```sql
SELECT `id`, `name_lang_1`, `attributesEx5`
FROM `dbc_spell` 
WHERE `attributesEx5` & @flag = @flag
```
| id | name_lang_1 | attributesEx5 | 
| ---: | --- | ---: | 
| 498 | Divine Protection | 4 | 
| 642 | Divine Shield | 4 | 
| 1022 | Hand of Protection | 4 | 
| 1490 | Curse of the Elements | 4 | 
| 5599 | Hand of Protection | 4 | 
| 7367 | Infected Bite | 4 | 
| 8733 | Blessing of Blackfathom | 4 | 
| 10278 | Hand of Protection | 4 | 
| 11721 | Curse of the Elements | 4 | 
| 11722 | Curse of the Elements | 4 | 
| 16128 | Infected Bite | 4 | 
| 21848 | Snowman | 4 | 
| 23444 | Transporter Malfunction | 4 | …

fix(Core/Spell): Make use of SPELL_ATTR4_DONT_REMOVE_IN_ARENA

---

data/sql/updates/pending_db_world/rev_1617743115631291700.sql

-  Adjust SAI for Elder Timberling
- Closes https://github.com/chromiecraft/chromiecraft/issues/324
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5169
https://wowgaming.altervista.org/aowow/?npc=2030#abilities
- Tested in-game (no spam)
.go c id 2030 …

fix(DB/smart_scripts): Adjust SAI for Elder Timberling

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Handlers/LootHandler.cpp
src/server/game/Loot/LootMgr.cpp
src/server/game/Loot/LootMgr.h

-  Added additional check if items is under group threshold.
-  
- Closes #4939.
- Tested ingame by 2 chars in Utgarde Pinnacle.
- 
1. Make a party
2. Teleport both players to any dungeon, e.g. Utgarde Pinnacle
3. Set master loot and item threshold to epic
4. Kill random mobs and try to loot gray/white items by non-master looter. …

fix(Core/Loot): Items below group threshold should not be blocked by master looter.

---

apps/extractor/extractor.bat

- Add a program to run all extraction tools from.
- https://github.com/TrinityCore/TrinityCore/blob/3.3.5/contrib/extractor.bat
- Tested with base files
1. Copy all extractor .exe's into the folder with wow.exe
2. Copy extractor.bat into the same folder
3. run extractor.bat …

feat(Apps): Automatic extractor for windows

---

src/server/game/Entities/Object/Object.cpp

Bad copypasta intoduced by c8f43d85849
Fixed #4620.
-  FIxed bad copypasta introduced with massive movement changes.
-  
- Closes #4620
- Might close many problems from #5022.
- Tested ingame in Teldrassil.
-  …

fix(Core/Objects): Fixed calculating LoS.

---

src/server/game/Spells/Auras/SpellAuras.cpp

cp from tc
-  Check for SPELL_ATTR3_IGNORE_PROC_SUBCLASS_MASK
<details>
<summary>Spells with the attribute</summary>
dbc_spell
---
```sql
SELECT `id`, `name_lang_1`, `attributesEx3`
FROM `dbc_spell` 
WHERE `attributesEx3` & @flag = @flag
```
| id | name_lang_1 | attributesEx3 | 
| ---: | --- | ---: | 
| 2565 | Shield Block | 2 | 
| 6984 | Frost Shot | 2 | 
| 12551 | Frost Shot | 2 | 
| 12834 | Deep Wounds | 2 | 
| 12849 | Deep Wounds | 2 | 
| 12867 | Deep Wounds | 67108866 | 
| 16511 | Hemorrhage | 1026 | 
| 17347 | Hemorrhage | 1026 | 
| 17348 | Hemorrhage | 1026 | 
| 17364 | Stormstrike | 67108866 | 
| 18802 | Frost Shot | 2 | 
| 20127 | Redoubt | 2 | 
| 20130 | Redoubt | 2 | 
| 20135 | Redoubt | 2 | 
| 20925 | Holy Shield | 2 | 
| 20927 | Holy Shield | 2 | 
| 20928 | Holy Shield | 2 | …

fix(Core/Spell): make use of SPELL_ATTR3_IGNORE_PROC_SUBCLASS_MASK

---

data/sql/updates/pending_db_world/rev_1617739461755573400.sql

- Fixed All PvP Bandages, now they get Debuff.
- Closes https://github.com/chromiecraft/chromiecraft/issues/269
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4970
- **Video Test:** [PvP Bandages](https://youtu.be/JOtWVW9YndM) …

fix(DB/Spells): All PvP Bandages

---

data/sql/updates/pending_db_world/rev_1617772431626528000.sql

- Fixed SAI NPC: [Razormane Wolf](https://wowgaming.altervista.org/aowow/?npc=3939)
- Closes https://github.com/chromiecraft/chromiecraft/issues/277
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4952
- **Video Test:** [Razormane Wolf](https://youtu.be/mEaCcBQUlQ8) …

fix(DB/smart_scripts): Razormane Wolf

---

data/sql/updates/pending_db_world/rev_1617774706114876200.sql

- Fixed Spawn NPC: [Nerubis Guard](https://wowgaming.altervista.org/aowow/?npc=16313) **GUID 81792**
- Closes https://github.com/chromiecraft/chromiecraft/issues/283
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4978
- **Screenshot:**  …

fix(DB/creature): Adjust spawn for Nerubis Guard

---

data/sql/updates/pending_db_world/rev_1617779221786870600.sql

- Fixed SAI Ruul-Snowhoof
- Closes https://github.com/chromiecraft/chromiecraft/issues/358
- Partially https://github.com/azerothcore/azerothcore-wotlk/issues/5173
- **Video Test:** [Ruul Snowhoof](https://youtu.be/40Ez3370f_w) …

fix(DB/Creature): Ruul Snowhoof

---

data/sql/updates/pending_db_world/rev_1617661090934443600.sql

- Fixed InhabitType NPCs:
- [Highland Razormaw](https://wowgaming.altervista.org/aowow/?npc=1018)
- [Elder Razormaw](https://wowgaming.altervista.org/aowow/?npc=1019)
- [Razormaw Matriarch](https://wowgaming.altervista.org/aowow/?npc=1140)
- Fixed Spawn NPC: [Highland Razormaw](https://wowgaming.altervista.org/aowow/?npc=1018) **GUID: 9981**
- Closes https://github.com/chromiecraft/chromiecraft/issues/215
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4881
- **Video Test:** [Raptor Ridge Cave](https://youtu.be/6kwFoBQ7Wjo) …

fix(DB/creature): Raptor Ridge Cave

---

data/sql/updates/pending_db_world/rev_1617732568440189700.sql

-  Fixed SAI NPC: [Imp Minion](https://wowgaming.altervista.org/aowow/?npc=12922)
-  Fixed SAI NPC: [Voidwalker Minion](https://wowgaming.altervista.org/aowow/?npc=8996)
- Closes https://github.com/chromiecraft/chromiecraft/issues/266
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4969
- Related PR https://github.com/azerothcore/azerothcore-wotlk/pull/4626 **(Little Correction of this PR)**
- **Video Test:** [Npc Minions not Engaging](https://youtu.be/wXh_WH4I4PA) …

fix(DB/smart_scripts): Minions not engaging

---

data/sql/updates/pending_db_world/rev_1617865372308647700.sql

- Fixed Reference Skinning loot NPC: [Mottled Boar](https://wowgaming.altervista.org/aowow/?npc=3098#skinning)
- Closes https://github.com/chromiecraft/chromiecraft/issues/316
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5189
- **Video Test:** [Skinning boars](https://youtu.be/72Bt37PcFEY) …

fix(DB/CreatureSkinning): Skinning boars

---

data/sql/updates/pending_db_world/rev_1617867794413109600.sql

-  Fixed SAI NPC: [Southsea Cannoneer](https://wowgaming.altervista.org/aowow/?npc=3382) and [Palemane Poacher](https://wowgaming.altervista.org/aowow/?npc=2951)
- Closes https://github.com/chromiecraft/chromiecraft/issues/320
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5191
- **Video Test:** [Ranged mobs shooting](https://youtu.be/g1LZCnOb3nk) …

fix(DB/CreatureSAI): Ranged mobs shooting

---

data/sql/updates/pending_db_world/rev_1617902440529783360.sql

-  Remove bogus entry in `reference_loot_template` for Flesh Piercer
-  Add proper entries in `creature_loot_template` for Flesh Piercer
- Closes #5194
[Wowhead Classic](https://classic.wowhead.com/item=3336/flesh-piercer)
[Wowhead TBC](https://tbc.wowhead.com/item=3336/flesh-piercer)
- I added these values to my database
- Set `Rate.Drop.Item.Uncommon = 10`
- Went to Hillsbrad Foothills
- Killed ~10-15 of these and the item dropped.
- Follow the above steps, and go to this location:
- Kill Daggerspine Shorestalkers and Daggerspine Screamers. …

Flesh piercer drop rate

---

data/sql/updates/pending_db_world/rev_1617913282545327642.sql

-  fixed tight groups of mining veins
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5196
- SQL applied
- .go object GUID from issue …

fix(DB/GameObject) Mining veins spawn

---

data/sql/updates/pending_db_world/rev_1617919651657315506.sql

-  Fixed spawn place of Timberstrider Fledgling
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5200
Mob is undermap this should not happen.
- SQL applied
- .go creature 62767
-  he is now in a proper place …

fix(DB/Creature)Timberstrider Fledgling undermap

---

data/sql/updates/pending_db_world/rev_1617936479961800600.sql

Adjust xyz pos for gobject:
- 12381
- 5361
- 5756
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4973
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5107
- Gobject(12381) was inside a wall
- Gobject(5361) was inside a rock
- Gobject(5756) was inside another node
N/A
- SQL applied
.go gobject GUID from issue …

fix(DB/gameobject): Change position of copper/other veins

---

data/sql/updates/pending_db_world/rev_1617986524556683595.sql

-  Fix `spawntimesecs` for a chest (`guid` = 100067) in Arathi Highlands.
I considered adding a chest to a pool of chests, but this is a standalone chest. No other chests around. Therefore, I simply increase the respawntime to what is most common for the other chests in the world. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5209
- Verify the issue is reproducible in the latest `master`
- Rebuilt using docker on Linux host
- Tested locally to verify no chest in two minutes.
- Verify the issue is reproducible in the latest `master`
- Apply the SQL update file. 
- Reload the world `.reload all`
- Loot the chest (`.go object 100067`)
- Wait two minutes
- Notice the chest has not spawned
- _Optionally_ wait for two hours and verify the chest is there.  …

fix(DB/GameObject-Spawn): Solid Chest respawn time for gameobject 100067

---

data/sql/updates/pending_db_world/rev_1618037276986031900.sql

- Fixed Skinning loot
- Closes https://github.com/chromiecraft/chromiecraft/issues/368
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5218 …

fix(DB/Creature): Skinning loot

---

data/sql/updates/pending_db_world/rev_1617475678754474649.sql

-  move the spawn over the earth
- .go cr 25623

fix(DB/Spawn): move spawn because it was under the earth

---

data/sql/updates/pending_db_world/rev_1617560891918432300.sql

- Fixed Quest POI, Quest: [The Principal Source](https://wowgaming.altervista.org/aowow/?quest=6127)
- Closes https://github.com/chromiecraft/chromiecraft/issues/245
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4963
- **Video Test:** [The Principal Source](https://youtu.be/XTxmyivyXK4) …

fix(DB/quest_poi_points): The Principal Source

---

data/sql/updates/pending_db_world/rev_1617612991251140137.sql

-  move spawn over the ground because it is under the earth
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5140
- Closes https://github.com/chromiecraft/chromiecraft/issues/340
.go cr 20534 …

fix(DB/Spawn): move spawn over the ground

---

data/sql/updates/pending_db_world/rev_1617614528274234003.sql

-  make this quest only for horde
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5142
- Closes https://github.com/chromiecraft/chromiecraft/issues/343
- Log in with an alliance char
- .go cr id 3216
- .mod faction 7
- the NPC will give you the quest, so import the fix and run .reload quest_template
- the NPC will no give you the quest anymore …

fix(DB/Quest): required race (faction) of quest

---

src/server/game/Spells/SpellMgr.cpp

-  Some fucker (me) don't know how to use indentations :D

chore(Core/SpellMgr): Indentation

---

src/server/game/Entities/Unit/Unit.cpp

-  be able to consider the feature to "decrease swim speed", actually our core doesn't
- Closes https://github.com/chromiecraft/chromiecraft/issues/246
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4964
swim and use `.aura 19727`, it will slow you …

fix(Core/Unit): decrease swim speed

---

data/sql/updates/pending_db_world/rev_1617620649041950300.sql

-  Fixed GameObject SAI: [Bubbling Fissure](https://wowgaming.altervista.org/aowow/?object=3740)
- Closes https://github.com/chromiecraft/chromiecraft/issues/246
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4964
- **Screenshot:**  …

fix(DB/smart_scripts): Bubbling Fissure

---

data/sql/updates/pending_db_world/rev_1618275651812886000.sql

-  Set `RewardMoney` to `900` for these quests
- Prevent players from farming a lot of gold using new level 1 characters
See comments in https://www.wowhead.com/quest=13503/a-tisket-a-tasket-a-noblegarden-basket#comments
> This page says your reward is 7g 40s, but I looked at the quest text in-game and it says only 9s
> That's the reward at level 80. At level 80 quest EXP is converted to money. Below 80 you'll receive 9s and a level scaled EXP reward. …

fix(DB/Quest): Noblegarden RewardMoney

---

data/sql/updates/pending_db_world/rev_1618370524737999000.sql

-  Change **SMART_ACTION_FLEE_FOR_ASSIST** for **SMART_ACTION_CALL_FOR_HELP**
- Closes https://github.com/chromiecraft/chromiecraft/issues/418
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5276
https://github.com/azerothcore/azerothcore-wotlk/issues/5276#issuecomment-819202765
.go c id 3637
Attack until 0-15% HP then check how it calls for help in 40yrds …

fix(DB/smart_scripts): Deviate Guardian - Call for help

---

data/sql/updates/pending_db_world/rev_1618371459590523500.sql

-  Port https://github.com/TrinityCore/TrinityCore/commit/6d5705a1041b8df9bfe0ab18a425976a601bf3e2
- Wrong loot
https://www.wowhead.com/npc=7883/andre-firebeard#drops
- Tested
.go c id 7883
- N/A …

fix(DB/creature_loot_template): Remove 'Wastewander Water Pouch' from Andre Firebeard

---

data/sql/updates/pending_db_world/rev_1618698984447935300.sql

-  Adjust InhabitType (ground/water - ground/air)
-  Adjust timers for Deviate Stinglash on its SAI
- Closes #5327 
- Also fixes the behaviour of other mobs around:
InhabitYpe = Movement logic
SAI = https://wowgaming.altervista.org/aowow/?npc=3631#abilities
- Testd in-game
.go c 3631
Go into the water and fight all mobs around this area
- N/A …

fix(DB/creature_template): Adjust InhabitType and SAI - Deviate creatures

---

data/sql/updates/pending_db_world/rev_1618166495075484153.sql

ported the fix from TC
-  add the right equipe template
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5249
- Closes https://github.com/chromiecraft/chromiecraft/issues/405
https://youtu.be/x8044fxfTug?t=206
https://github.com/TrinityCore/TrinityCore/issues/12796
- .go cr 9122 …

fix(DB/Creature): thrown animations

---

data/sql/updates/pending_db_world/rev_1618170334855143471.sql

-  add spirit healer spawn
- Closes https://github.com/chromiecraft/chromiecraft/issues/403
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5253
- go to eastern plaguelands
- suicide
- you will see now the spirit healer next to you …

fix(DB/Creature): add missing spirit healer

---

data/sql/updates/pending_db_world/rev_1618180915871216782.sql

- Humbert's Helm was dropped by around 475 mobs while it should only drop for one 
- Delete the drop from every other mob and align the dropchange with Vanillawowdb/Wotlkwowdb
- Part https://github.com/azerothcore/azerothcore-wotlk/issues/4987
- Part https://github.com/chromiecraft/chromiecraft/issues/286
- https://vanillawowdb.com/?item=4724
- https://classic.wowhead.com/item=4724/humberts-helm
- https://wotlkdb.com/?item=4724
- Applied SQL and checked the DB
- Not really any need to kill maybe hundreds of mobs to confirm.
- Apply the SQL
- Check the DB
- / …

fix(DB): Drop for Humbert's Helm

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Groups/Group.cpp
src/server/game/Loot/LootMgr.h

Reverts azerothcore/azerothcore-wotlk#5371

Revert "fix(Core): fix chests not despawning when opened in group"

---

data/sql/updates/pending_db_world/rev_1619115153766529700.sql

-  Add gossip for Jangdor Swiftstrider
- Closes #5400
https://youtu.be/R3aeE_TYqnI?t=8
- Tested in-game:
Ignore the class, I'm using an esES client, translations are ok, but the original text (enUS) was the one missing
.go c id 7854
- There are multiple texts/gossips missing, run the following query:
```sql
SELECT * FROM npc_text WHERE text0_0='MISSING TEXT';
``` …

fix(DB/npc_text): Add gosip for Jangdor Swiftstrider

---

.github/README.md
.github/workflows/core_build.yml
.github/workflows/macos_build.yml

- move macos build to separate workflow
- add macos build status badge to the readme
- update actions/cache to v2
- update ccache path
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5411 …

chore(CI): move macos build to separate workflow

---

.github/README.md
.github/workflows/core_build.yml
.github/workflows/windows_build.yml

-  move windows build to separate workflow
-  add windows build status badge to the readme
- Closes  …

chore(CI): move windows build to separate workflow

---

conf/dist/env.ac

env variables should not use the quotes
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5429
- 
-  …

fix(docker): env variable settings

---

data/sql/updates/pending_db_world/rev_1618656094946285190.sql

- ported some spawns from cmangos
- generated guid by https://github.com/FrancescoBorzi/TC-Unused-Guid-Search-web
-  add 3 spawns
- related to https://github.com/azerothcore/azerothcore-wotlk/issues/4934
- don't need tests …

feat(DB/creature): Add vulture spawns

---

src/server/game/Movement/MovementGenerators/ConfusedMovementGenerator.cpp

Fixed #5442.
Fixed https://github.com/chromiecraft/chromiecraft/issues/271
-  Improved confused movement generator by building path generator to specific destination.
- Closes #5442
- Not tested ingame.
More info #5442. …

fix(Core/Movement) : Improved confused movement generator.

---

data/sql/updates/pending_db_world/rev_1619538084717796794.sql

- Add all Chest spawns in Stranglethorn Vale into a Pool.
- Make 5 of them spawn at a time.
- Set the respawntime to 15 minutes
- Part: https://github.com/chromiecraft/chromiecraft/issues/458
- https://github.com/azerothcore/azerothcore-wotlk/pull/4947 Took this PR as a template
- Applied the update
- .go ob to all the guids and checked that only 5 of them are spawned at one time.
- Apply SQL
- .go ob to all the guids …

fix(DB): Chest Pooling in Stranglethorn Vale

---

src/server/game/Entities/Player/Player.cpp

- Title
- Closes #5507
- In game
- 

fix(Core/Player): correct add guid for packet SMSG_CLIENT_CONTROL_UPDATE

---

src/server/game/Battlefield/Battlefield.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Maps/Map.cpp
src/server/game/Movement/MotionMaster.cpp
src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/RandomMovementGenerator.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h

Fixed #5535
Fixed #5544
- Closes #5535 and #5544

fix(Core/Misc): Memleaks fixes. Part I.

---

.github/workflows/codestyle.yml
.github/workflows/core_build.yml
.github/workflows/docker_build.yml
.github/workflows/issue-labeler.yml
.github/workflows/macos_build.yml
.github/workflows/windows_build.yml

-  change on: push to only run on master branch

fix(CI): change on: push to only run on master branch

---

data/sql/updates/pending_db_world/rev_1619976848278136900.sql

-  Adjust XYZ for Copper Vein nodes
- Closes #5584
- Closes #5571
- Closes https://github.com/chromiecraft/chromiecraft/issues/492
Gobject logic
.go gob [GUID]
- N/A …

fix(DB/gameobject): Adjust gob position for some Copper Vein nodes

---

.github/ISSUE_TEMPLATE/bug_report.md
pull_request_template.md

Appearently `[//]: # ( )` only works on .md but not the PR or Issue's themselves

chore(template): Fix comment

---

.github/workflows/windows_build.yml

-  trigger windows build on comment

feat(CI): trigger windows build on comment

---

.github/workflows/windows_build.yml

-  This reverts commit 48a0c72604aef01b2b93cbef4ab7f58fc07b19a9.

Revert "feat(CI): trigger windows build on comment (#5643)"

---

data/sql/updates/pending_db_world/rev_1619695262798189500.sql

cp https://github.com/TrinityCore/TrinityCore/commit/cd853118b6cc215676cd7a4661c0b91575e5650a
-  title
- none
Not needed, the table works as it works ^^ …

fix(DB/Creature): Verify & update Ashen Verdict reputation values

---

data/sql/updates/pending_db_world/rev_1619822861176792300.sql

Once upon a time, about 2 years ago it was taken from TC, so cred to whoever made the original commit ^^
- Add SAI to it
.go c id 8419 …

fix(DB/Creature): Twilight Idolater

---

data/sql/updates/pending_db_world/rev_1619823825635053300.sql

Once upon a time, about 2 years ago it was taken from TC, so cred to whoever made the original commit ^^
-  When killing Son of Hakkar you should receive Poisonous Blood
- Tested in-game 
.go c id 11357
Kill it …

fix(DB/Creature): Son of Hakkar

---

data/sql/updates/pending_db_world/rev_1619824464997653100.sql

Once upon a time, about 2 years ago it was taken from TC, so cred to whoever made the original commit ^^
-  Update them to be blizzlike
- Not tested in-game, not necessary
- Rechecked them all to make sure they are right.
go to a guard
**For …

fix(Creature/Gossip): Adjust some guard direction text

---

data/sql/updates/pending_db_world/rev_1619958638373648000.sql

To be sure the Fix works,
I entered the entire SAI fix of this creature,
so I didn't just enter the summons coordinates.
**(I am doing this because since in my local at the same version of AC the fix works, but on CC it doesn't, I prefer to put the complete fix to be sure that everything works as it should.)**
- Re-Work SAI NPC:  [Apprentice Mirveda](https://wowgaming.altervista.org/aowow/?npc=15402)
- Related to: Fix https://github.com/azerothcore/azerothcore-wotlk/pull/5072
- Related to: Issue https://github.com/chromiecraft/chromiecraft/issues/213
- Related to: Issue https://github.com/azerothcore/azerothcore-wotlk/issues/4868
- Closes https://github.com/chromiecraft/chromiecraft/issues/504
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5595
- Tested in game and …

fix(DB/Creature): Apprentice Mirveda

---

data/sql/updates/pending_db_world/rev_1619974489991847400.sql

- Fix Pool Spawns NPC: [Or'Kalar](https://wowgaming.altervista.org/aowow/?npc=2773)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5598 …

fix(DB/pool_creature): NPC: Or'Kalar

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp

Co-Authored-By: UltraNix <80540499+UltraNix@users.noreply.github.com>
-  fix BuildAuctionMailBody guid
- Closes #5718
- Closes https://github.com/chromiecraft/chromiecraft/issues/558
Original Author: @UltraNix 
- https://github.com/azerothcore/azerothcore-wotlk/issues/5718#issuecomment-835491939
- https://github.com/azerothcore/azerothcore-wotlk/issues/5718#issuecomment-835550915
1. pull changes, rebuild & restart 
2. post some auctions with one character (seller)
3. buy some auctions posted from first character(buyer)
4. check the mail to make sure the character names show and the gold values show from the auction. …

fix(Core/Misc): BuildAuctionMailBody guid

---

src/common/Configuration/Config.cpp

- Added info about bad lines in config file
- #5725
- Just add whitespace in uncomment line
```diff
-
+ 
``` …

feat(Core/Config): added info about bad lines in config file

---

data/sql/updates/pending_db_world/rev_1620439642282070000.sql

-  Delete loot from Witherbark Bloodling
- Closes #5662
- Closes https://github.com/chromiecraft/chromiecraft/issues/538
https://classic.wowhead.com/npc=7768/witherbark-bloodling#comments
- Tested in-game: No loot …

fix(DB/crature_loot_template): Remove loot from Witherbark Bloodlings

---

data/sql/updates/pending_db_world/rev_1620477325004735900.sql

- Adjust SAI for Mirefin Coastrunner
- Closes #5722
- Closes https://github.com/chromiecraft/chromiecraft/issues/553
https://github.com/TrinityCore/TrinityCore/blob/f759809d9d4364bc1d988e4390d3d5a33d5469e9/sql/old/6.x/world/02_2015_11_08/2015_07_25_04_world.sql#L391
- Tested …

fix(DB/smart_scripts): Mirefin Coastrunner

---

data/sql/updates/pending_db_world/rev_1620586666463013100.sql

- **Fixed Warlock's Pets movement in the water**
**[EDIT]:**
**Video Test:** [Pathfinding](https://youtu.be/xU27sYtMdp0)
So the Fix I made doesn't fix anything. 
However, in any case the fix I made is correct because pets should be able to swim in the water anyway.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5748
1.
2.
3. …

fix(DB/creature_template): NPCs: 416, 417, 1860, 1863

---

data/sql/updates/pending_db_world/rev_1620613702128937000.sql

-  Delete SAI line for Scorn spawning
- Closes #5750 
- Closes https://github.com/chromiecraft/chromiecraft/issues/587
https://www.wowhead.com/npc=14693/scorn#comments
- Tested
No more spawning. …

fix(DB/smart_scripts): Remove spawn event for Scorn

---

src/server/scripts/Spells/spell_hunter.cpp

fix(Scripts/SpellHunter): crashfix

---

data/sql/updates/pending_db_world/rev_1620888636790704800.sql

-  He will now be banished
-  He will have the proper visuals
- Closes #1159
Port from TrinityCore https://github.com/TrinityCore/TrinityCore/issues/23857
I believe @dr-j is the original author of this SmartAI, thanks!
Tested on local Windows 10 server.
1. .quest add 10688 and .quest add 10637
2. .go xyz -3878.602783 364.436432 129.075577 530
N/A …

Fix (DB/Quest) A Necessary Distraction from TrinityCore

---

data/sql/create/drop_mysql_8.sql

Co-Authored-By: Giacomo Pozzoni <giacomopoz@gmail.com>
cherry-pick https://github.com/TrinityCore/TrinityCore/commit/7e5c1cf453972e142613ab828b75c8635edf697d …

fix(MySQL8): Add Drop script

---

data/sql/updates/pending_db_world/rev_1621015424165306900.sql

-  Remove the command
- https://github.com/azerothcore/azerothcore-wotlk/issues/5827
- Windows 10
1. Execute SQL
2. Check that the error message is no longer displayed. …

fix(DB/command): delete command togglequerylog

---

src/server/scripts/Commands/cs_gobject.cpp

-  Adding a line to update the generated GUID in cs_gobject.cpp
-  
- https://github.com/azerothcore/azerothcore-wotlk/issues/5597
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Commands/cs_gobject.cpp
- Build, Tested, and build on Ubuntu 20.04
- 
1. just spawn the gameobject and he will appear
2.
3. …

fix(CORE): GUID of GameObject

---

src/server/authserver/Main.cpp
src/server/worldserver/Main.cpp

-  Show Boost Ver in startup
- works 
run

feat(Core/Main): Show Boost Ver

---

data/sql/updates/pending_db_world/rev_1620427214886749400.sql

Adjust xyz pos for gobject:
- 5027
- 5471
- 5240
- 4661
- 4759
- 5325
- 5454
- 6494
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5354
https://github.com/chromiecraft/chromiecraft/issues/440
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5329
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5274
https://github.com/chromiecraft/chromiecraft/issues/416
N/A
- SQL applied
- .go gobject GUID from changes proposed …

fix(DB/gameobject): Adjust Position For Some Copper Veins

---

data/sql/updates/pending_db_world/rev_1621271952210432100.sql

-  Adjust quest Your Fortune Awaits You... (qID 7944) POI to the correct location
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5126
https://www.wowhead.com/quest=7944/your-fortune-awaits-you
https://classic.wowhead.com/quest=7944/your-fortune-awaits-you
- Tested in-game. Windows 10 - enGB client.
- 
1. `.additem 19443`
2. Use the item and accept the quest …

fix(DB): Adjust Quest 7944 POI

---

src/server/game/Server/WorldSession.cpp

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6044

fix(Core/WorldSession): prevent crash in SendPacket

---

data/sql/updates/pending_db_world/rev_1621682307665630800.sql

-  Prevent NPC Inquisitor Salrand from assisting nearby mobs in combat
-  Adjust SAI and InhabitType so that she doesn't keep flying/hovering after she's engaged in combat
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2875
https://youtu.be/7mI9sJumHEM?t=151
https://user-images.githubusercontent.com/82320853/119226940-e2db7680-bb0b-11eb-8899-bff95c8f1a95.mp4
1. `.q a 11671`
2. `.go c id 25584` …

fix(DB): Adjust NPC Inquisitor Salrand's behaviour

---

data/sql/updates/pending_db_world/rev_1621746341007519100.sql

-  Improve Spiteful Apparation script
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/848
- Tested in-game, better than before  …

fix(DB/Creature): Spiteful Apparition

---

src/server/scripts/EasternKingdoms/ScarletMonastery/instance_scarlet_monastery.cpp

-  Do not cast Whitemane's spells as triggered, so they will consume mana and have a cast time.
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/5226
- Build & Implementation
1. Fight Mograine and Whitemane.
- No
**For …

fix(Core/Creature): Make Whitemane's spell casts regular.

---

data/sql/updates/pending_db_world/rev_1621846003001480200.sql

-  Remove duplicate gossip options for NPC Chromie (Entry 26527)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6023
None
1. `.go c id 26527`
2. Speak to her and go through the gossip options …

fix(DB/gossip_menu_option): Remove Chromie duplicate gossip options

---

data/sql/updates/pending_db_world/rev_1621933074448445073.sql

-  Added a SAI query for `Lord Baurles K. Wishock`.
- On quest completion of `A Noble Brew` it will now play a small event.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5222
- Closes https://github.com/chromiecraft/chromiecraft/issues/379
https://youtu.be/di1GyozfIU8?t=151
- Tested without the changes: no event is playing on `A Noble Brew` turn in.
- Tested in game on linux/docker setup from windows client.
- Tested with the changes: an event is now playing like in the source video.
1. `.quest add 335`
2. `.additem 2779`
3. `.additem 2784`
4. `.go xyz -8980.497070 1025.567139 101.404068 0` and turn in the quest.
5. Accept the next quest or use `.quest add 336`
6. `.go xyz -8559.486328 371.781189 108.385941 0`
7. Observe if an event is playing on quest turn in and if …

fix(DB/smart_scripts): Play small event on noble brew part 2 completion

---

src/server/game/Spells/SpellInfo.cpp

-  Adds missing anti-stealth aura to Faerie Fire variant with spell ID 20656.
- UPDATE: Now also added 25602 and 32129.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6094
- Closes https://github.com/chromiecraft/chromiecraft/issues/720
Tested: was correctly unable to stealth until Faerie Fire wore off.
1. Be rogue/feral druid and .go c 51271 - you'll end up in a group of 3, so don't forget god mode.
2. The Tree Warder will cast FF at start of combat.
3. Kill all 3 and try to stealth. You should be unable to until FF wears off.
- There's 5 variants of Faerie Fire, 3 of which are now fixed. The remaining two, IDs 25602 and 32129, are probably worth checking:
- https://wotlkdb.com/?spell=25602 - update: checked, NOT working. Test with Darnassian Druid (ID 16331)
- …

fix(Core/Spell): Apply AURA_STATE_FAERIE_FIRE to Faerie Fire

---

src/common/Define.h
src/server/game/Chat/ChatLink.cpp
src/server/game/DungeonFinding/LFGScripts.cpp
src/server/game/Handlers/ChatHandler.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp

chore(Core/Common): delete macro UNUSED

---

data/sql/updates/pending_db_world/rev_1621946683156041900.sql

- Fix SAI NPC: [Sickly Deer](https://wowgaming.altervista.org/aowow/?npc=12298)
- Closes https://github.com/chromiecraft/chromiecraft/issues/312
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5055
- **Video Test:** 
https://user-images.githubusercontent.com/1884642/119499781-f6cae680-bd5e-11eb-9441-40def2e910c2.mp4
1.
2.
3. …

fix(DB/SAI): Quest: Curing the Sick

---

data/sql/updates/pending_db_world/rev_1621964735730077300.sql

- Fix GameObject Respawn Time [Fathom Stone](https://wowgaming.altervista.org/aowow/?object=177964)
- Closes https://github.com/chromiecraft/chromiecraft/issues/430
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5323
- **Video Test:** 
https://user-images.githubusercontent.com/1884642/119543853-065f2500-bd89-11eb-8e3a-2acd9f359309.mp4
1.
2.
3. …

fix(DB/gameobject): GObject Respawn: Fathom Stone

---

data/sql/updates/pending_db_world/rev_1622076993710927000.sql
src/server/scripts/World/go_scripts.cpp

-  Move the script to the database
- Closes 
- I tested it on Windows 10
1. go o 48777
2. Then click on the object.
3. The npc should appear and start attacking you. …

refactor(SmartAI): Moving the script to the DB

---

data/sql/updates/pending_db_world/rev_1622046406344372400.sql

- Fix NPC: [Disciple of Naralex](https://wotlk.evowow.com/?npc=3678)
- Closes https://github.com/chromiecraft/chromiecraft/issues/281
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4953
- **Video Test:** [Disciple of Naralax](https://youtu.be/3wcq2qeFucE)
1.
2.
3. …

fix(DB/Creature/SAI): Disciple of Naralex

---

data/sql/updates/pending_db_world/rev_1622046680993341100.sql

-  Lunaclaw will now spawn outside the cave in Darkshore and run towards the player 
-  The Moonkin Stone will glow purple for 60 seconds whenever Lunaclaw is summoned
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4829
[#1. Video from 2008](https://youtu.be/Et7zuYWvS-s?t=172)
[#2. WoW Classic Behaviour](https://youtu.be/lVHaegvdrKc?t=113)
https://user-images.githubusercontent.com/82320853/119700676-cdd84d80-be53-11eb-8769-32edb98bbf02.mp4
1. `.go go 48565`
2. `.additem [Cenarion Moondust]`
3. Use the item near the moonkin stone …

fix(DB/SAI): Improve Lunaclaw/Moonkin Stone behaviour

---

data/sql/updates/pending_db_world/rev_1622104586099236800.sql

-  Swap scripts called on gossip option selected for NPC Krasus ( ID 27990 ) during the quest 'What The Dragons Know' to correctly align with player faction.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5583
https://www.wowhead.com/quest=24555/what-the-dragons-know
https://www.wowhead.com/quest=14444/what-the-dragons-know
1. `.go c id 27990`
2. Horde : `.q a 24555` //// Alliance `.q a 14444`
3. Speak to Krasus and watch the dialogue …

fix(DB/SAI): Swap scripts called on gossip for NPC Krasus

---

data/sql/updates/pending_db_world/rev_1622192313812244100.sql

-  Set NPC Gatekeeper Rageroar (ID 6651) to Timbermaw Hold faction, so that nearby mobs don't attack him
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6075
https://classic.wowhead.com/npc=6651/gatekeeper-rageroar#comments
https://user-images.githubusercontent.com/82320853/119960244-0f2c4280-bfa5-11eb-85b1-045e42bbd767.mp4
1. `.go c id 6651`
2. Engage the mobs then walk away so that they reset
3. Nearby mobs shouldn't attack Gatekeeper Rageroar …

fix(DB/creature_template): Set Gatekeeper Rageroar to faction Timbermaw Hold

---

src/server/game/Entities/Object/Object.h
src/server/game/Globals/ObjectMgr.h
src/server/game/Maps/MapManager.h

- Added few helpers for chat commands

chore(Core/MIsc): added few helpers for chat commands

---

data/sql/updates/pending_db_world/rev_1622447836581960000.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6147
credits to @mpfans

fix(DB): chinese translations

---

data/sql/updates/pending_db_world/rev_1622465489637988400.sql

-  Advisor Sorrelon will now have a different gossip text if the player is not a Blood Elf 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6152
- Closes https://github.com/chromiecraft/chromiecraft/issues/745
https://wowpedia.fandom.com/wiki/Advisor_Sorrelon
1. Be a Blood Elf  -> `.go c id 16288`
2. Be another Horde race -> `.go c id 16288` …

fix(DB): Adjust Advisor Sorrelon gossip conditions

---

data/sql/updates/pending_db_world/rev_1622547209752619743.sql

Slimy Bags (20766), Oozing Bags (20767) and Scum Covered Bags (20768)
did not contain money, their loot was not grouped, and some loot was
missing. All of these are fixed.
Had to rely on wowhead comments and unboxing videos for this one. I noticed during the unboxing videos that bags may only contain up to 1 of each type of item (so no Health Potion and Mana Potion in the same bag, for example). Recipes were missing from the loot tables so I added the ones listed on wowhead. 
There wasn't much into about Slimy Bags in particular. They're essentially a lower tier version of the other 2 bags so I thought they should contain some cash too. 
Initially I wanted to scrap the existing drop tables, import the ones from wowhead and arrange the items into groups as necessary, but during testing I …

fix(DB/loot): Slimy, Oozing, Scum Covered Bag loot

---

data/sql/updates/pending_db_world/rev_1622599423158947800.sql

-  Change dinosaur bones to only drop when you have the required quest.
- Closes #6170
- Closes chromiecraft/chromiecraft#755
- https://wowgaming.altervista.org/aowow/?item=11114
- Ran the sql script and inspected the resulting database changes.
- Killed relevant npcs in Un'goro crater with and without the quest in order to check if they were dropping properly.
1.  Run ```SELECT * FROM `acore_world`.`creature_loot_template` WHERE ITEM = 11114;``` and checked to ensure QuestRequired is set to 1 for all rows.
2. Go to Un'goro crater and kill anything that drops dinosaur bones: https://wowgaming.altervista.org/aowow/?item=11114#dropped-by They should not drop without the quest.
3. Get quest https://wowgaming.altervista.org/aowow/?quest=3882 and repeat step 2 to ensure dinosaur bones now …

 fix(DB/loot): Dinosaur bones in Un'Goro crater are dropping without the associated quest

---

data/sql/updates/pending_db_world/rev_1622618904028016440.sql

Aku'mai (id: 27433) is supposed to stroll around in the BFD boss area, but he was standing still. I've given him a path to circle around in the boss room and wait in 2 locations for 10s each.
- Put Aku'mai on a fixed path 
- Closes #5925
- Closes chromiecraft/chromiecraft#665
No source for the precise path
https://www.youtube.com/watch?v=UyyUM1rZras
https://www.youtube.com/watch?v=IzrXL_dDQiw
1. `.go c 27433` 
2. Observe his path …

fix(DB/waypoint_data): Aku'mai pathing

---

.github/workflows/core_build.yml
.github/workflows/docker_build.yml
.github/workflows/macos_build.yml
.github/workflows/windows_build.yml

-  enabled the new workflow concurrency feature https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/ …

feat(CI): limit workflow concurrency

---

data/sql/updates/pending_db_world/rev_1623093110337112400.sql

-  Moved the spawn point to local coords (54.3, 83.6) according to https://classic.wowhead.com/npc=4334/firemane-flamecaller#map
-  Added wander distance to match the other creatures in the area of the same type
- Closes #5766
- Closes chromiecraft/chromiecraft#594
- https://classic.wowhead.com/npc=4334/firemane-flamecaller#map
- See below
1. Run ```SELECT * FROM `acore_world`.`creature` WHERE `guid` IN (30504);``` The result should have:
```
position_x = -4960.708496, position_y = -3828.589600, position_z = 43.382378
wander_distance = 5, MovementType = 1
```
2. Use ```go creature 30504``` to teleport to the changed npc. It should no longer be in the wall, and it should be wandering.
You can help by testing …

fix(DB/Creature): Firemane Flamecaller Spawning Inside Wall

---

.editorconfig
.github/workflows/import_pending.yml
.vscode/settings.json
acore.json
apps/ci/ci-pending-changelogs.ts
apps/ci/ci-pending-sql.sh
apps/docker/docker-cmd.ts
bin/acore-import-changelogs
doc/changelog/README.md
doc/changelog/master.md
doc/changelog/pendings/changes_1623667140221711000.md
doc/changelog/pendings/create.sh
doc/changelog/previous-versions/v2.x.md
doc/changelog/previous-versions/v3.x.md

-  new changelog system, instructions are available in this WIKI PR to merge at the same time: https://github.com/azerothcore/wiki/pull/543
This system provides rules and automatizes (via a Deno script) the creation of a changelog file to help developers to adapt their code and know what is new with every (pre)release

feat(doc): changelog system

---

src/server/game/AI/CoreAI/GuardAI.cpp
src/server/game/AI/CoreAI/PetAI.cpp
src/server/game/AI/CoreAI/ReactorAI.cpp
src/server/game/AI/CreatureAI.cpp
src/server/game/Accounts/AccountMgr.cpp
src/server/game/Addons/AddonMgr.cpp
src/server/game/Battlefield/Zones/BattlefieldWG.cpp
src/server/game/Battlegrounds/ArenaTeam.cpp
src/server/game/Battlegrounds/Battleground.cpp
src/server/game/Battlegrounds/Zones/BattlegroundRL.cpp
src/server/game/Battlegrounds/Zones/BattlegroundRV.cpp
src/server/game/Battlegrounds/Zones/BattlegroundSA.cpp
src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
src/server/game/Combat/HostileRefManager.cpp
src/server/game/Combat/ThreatManager.cpp
src/server/game/Conditions/ConditionMgr.cpp
src/server/game/DataStores/DBCStores.cpp
src/server/game/Entities/Object/Object.cpp
src/server/game/Events/GameEventMgr.h
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Server/WorldSession.h
src/server/game/Spells/SpellMgr.cpp
src/server/game/Weather/Weather.h

- Just a minor code cleanup
- Cleaned `src/server/game` directories alphabetically until `DataStores` by fixing warnings such as unused imports, shadowed variables, etc...

refactor(Core): code cleanup (part 1)

---

.github/workflows/codestyle.yml
.github/workflows/core_build.yml
.github/workflows/core_modules_build.yml
.github/workflows/docker_build.yml
.github/workflows/macos_build.yml
.github/workflows/windows_build.yml

-  general workflow updates
- try to improve concurrency grouping

fix(CI): workflow updates

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Spells/SpellMgr.h

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6452
- Allow better investigations of the underlying problem using logs

fix(Core): check spell info and prevent crash

---

data/sql/updates/pending_db_world/rev_1624283180593292800.sql

-  SmartAI for this NPC
- Closes #6476
- Closes https://github.com/chromiecraft/chromiecraft/issues/939
1. .go c id 17342
2. Casts Rain of Fire in combat …

fix(SmartAI): Axxarien Hellcaller SmartAI

---

data/sql/updates/pending_db_world/rev_1624165153573726801.sql

-  Deletes Green Linen Shirt (ID 2579) from Skeletal Warrior (ID 48) drop table.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6440
- Closes https://github.com/chromiecraft/chromiecraft/issues/906
https://tbc.wowhead.com/npc=48/skeletal-warrior#drops;q=green
https://wotlkdb.com/?npc=48#drops
https://wowpedia.fandom.com/wiki/Green_Linen_Shirt?oldid=2377464
- Checked for any other NPCs dropping the item, none found.
1. Use this query to search for any other instances of the item in NPC drop tables. None should be found.
```SELECT ct.name, clt.chance
FROM `creature_template` ct
LEFT JOIN `creature_loot_template` clt ON ct.lootid = clt.entry
JOIN `item_template` it ON clt.item = it.entry
WHERE it.entry = 2579
``` …

fix(DB/loot): Remove Green Linen Shirt from Skeletal Warrior

---

src/server/database/Database/Implementation/CharacterDatabase.cpp

Tested in game, to be merged ASAP

fix(Core/CharacterDatabase): bad query in prepared statement

---

data/sql/updates/pending_db_world/rev_1624664527197257200.sql

- Last of 3 PRs, closes my work on gem translations.
-  Fix for esES and esMX locales where some Gems names and descriptions were not matching their English versions.
- Wrong names and descriptions. 
- No test needed. …

(DB)Pending locales for Gems esES/esMX

---

data/sql/updates/pending_db_world/rev_1624682095822347519.sql

- Changes Gnarl Leafbrother's speed_walk from 2.9 to 1.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6553
- Closes https://github.com/chromiecraft/chromiecraft/issues/985
https://www.youtube.com/watch?v=iRxiA9YeXG0
- Checked in game, NPC is now moving at more reasonable speed.
1. .go c 51842
N/A. …

fix(DB/Creature): Corrects Gnarl Leafbrother's movement speed

---

data/sql/updates/pending_db_world/rev_1624687532594694252.sql

-  Removes QuestRequired flag from Warden Belamoore's junk drop Belamoore's Research Journal (ID 3711)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6543
- Closes https://github.com/chromiecraft/chromiecraft/issues/984
https://www.wowhead.com/item=3711/belamoores-research-journal#comments
Also note the DB showed the item as class 15 (Miscellaneous, i.e. junk) rather than as class 12 (quest item). Also ran SQL against the quest_template table (```SELECT * from `quest_template' qt where qt.RequiredItemId1 = 3711```) and got back no results, so no quests are using the item.
- Tested in game, ganked Warden repeated;y, she dropped the Journal every time.
1. .go c 17341
2. Murder Warden, check loot for Journal.
N/A. …

fix(DB/Loot): Fix Belamoore's Rearch Journal drop requirement

---

doc/changelog/pendings/changes_1624799411242887600.md
doc/changelog/pendings/changes_1624799731107698500.md

feat(Changelog): SkillLineAbility changes

---

data/sql/updates/pending_db_world/rev_1625063367376312208.sql

-  Azzere the Skyblade 5834, MovementType to 1, wander_distance to 20. Matched wander_distance with nearby Thunderhawk Cloudscraper.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6525
- Closes https://github.com/chromiecraft/chromiecraft/issues/967
- https://youtu.be/rwtfE9XaPQM?t=2
- https://youtu.be/o0svob_rd54
- Ran SQL, no warnings/errors.
- Checked in game to see him moving about.
1. Visit provided GUID and observe.
2. Or just use Keira.
N/A. …

fix(DB/Creature): Fix motionless Azzere the Skyblade

---

data/sql/updates/pending_db_world/rev_1625140998826519742.sql

-  Sets Silithid Harvester (ID 3253) to MovementType 1, wander_distance 15.
Wander distance is higher than most local mobs, but TBC WH map and the linked YT video shows this NPC should range fairly widely.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6531
- Closes https://github.com/chromiecraft/chromiecraft/issues/971
https://www.youtube.com/watch?v=5eeKWBQATyI
- Checked in game to see it moving correctly.
1. Check in-game or with Keira.
N/A. …

fix(DB/Creature): Fix motionless Silithid Harvester

---

data/sql/updates/pending_db_world/rev_1625248824338191500.sql

-  Make Kroshius not selectable while he's in his "rubble" form
-  Adjust Kroshius' spawn point and make its dead form despawn when quest item [Fel Fire] is used.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6146
- Closes https://github.com/chromiecraft/chromiecraft/issues/741
https://it.classic.wowhead.com/quest=7603/kroshius-infernal-core
https://user-images.githubusercontent.com/82320853/124313323-01a04480-db71-11eb-9b31-7bd633599266.mp4
1. `.go c 39715`
2. `.q a 7603`
3. Use the provided item and complete the quest …

fix(DB): Improve quest Kroshius' Infernal Core

---

data/sql/updates/pending_db_world/rev_1625314084249000751.sql

- Verifonix ID 14492, speed_walk from 1.64 to 1, MovementType to 1, wander_distance to 3 across 6 spawns
- Diamond Head ID 5345, speed_walk from 2.16 to 1, MovementType to 1, wander_distance to 15
- Lady Szallah ID 5343, MovementType to 1, wander_distance to 15
- Qirot ID 5350, MovementType to 1, wander_distance to 3
- Witherheart the Stalker ID 8218, MovementType to 1, wander_distance to 3
I've tried to match wander_distance to local mobs of the same kind:
- Verifonix to Venture Co. Surveyor
- Diamond Head to Coast Crawl Deepseer
- Lady Szallah to Hatecrest Sorceress
- Qirot to Zukk'ash Stinger
- Witherheart the Stalker to Witherbark Sadist
- Partially addresses https://github.com/azerothcore/azerothcore-wotlk/issues/6549
- Verifonix - https://youtu.be/dHgiCHGSjZs?t=29
- Diamond Head - …

fix(DB/Creatures) Fix more static rare spawns, 40-49 bracket

---

data/sql/updates/pending_db_world/rev_1625383484945729168.sql

-  Nudges 6 ore nodes in EPL up by about 2.5 units each so they are no longer hidden underground.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6686
- Closes https://github.com/chromiecraft/chromiecraft/issues/1056
Mining nodes should not be spawned underground.
- Checked in game, nodes are now visible and accessible.
1. .go o 9539 - it's right next to the other 5, so all 6 can be checked at once, assuming they have spawned.
N/A. …

fix(DB/gameobject): Reposition underground ore nodes in EPL

---

data/sql/updates/pending_db_world/rev_1625384990443326741.sql

- Removes Frenzy (spell ID 8269) and replaces in with the correct Enrage (ID 8599) in the lvl 10 Amani Berserker's script.
Frenzy does something like quadruple damage (50 dmg + 2 per level = ~60 per hit) on top of 60% melee haste, whereas Enrage is a much more reasonable +19% dmg and 30% melee haste. Note that Enrage is what this mob is listed as using in TBC Wowhead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6688
- Closes https://github.com/chromiecraft/chromiecraft/issues/1057
https://tbc.wowhead.com/npc=15643/amani-berserker#abilities
- Ran SQL, no errors/warning.
- Went out and tried it in-game, the Berserker is more more sensible now.
1. .go c 55623 and damage the troll down to < 30% health and check the right buff appears.
2. Or just look in Keira.
N/A.
When a …

fix(DB/Creature): Add correct buff to Amani Berserkers

---

data/sql/updates/pending_db_world/rev_1625304053277095200.sql

-  Add roleplay missing for the quest 'The Divination' upon accepting the quest.  
- Closes #6706
- Closes https://github.com/chromiecraft/chromiecraft/issues/1075
- Sadly there's not much information about the quest but I could find a fix done by the TC guys https://github.com/TrinityCore/TrinityCore/commit/293fd67faceffdd7b86dc6843cda5a899af6cac2
- Test in local AzerothCore environment, performs the RP perfectly.
1. `.go c id 8022`
2. Turn in the previous quest in order to be able to get The Divination (`.q a 2991` & `.q c 2991`)
3.  RP is performed …

fix(DB/smart_scripts): Add roleplay for the quest The Divination

---

data/sql/updates/pending_db_world/rev_1625401809536592600.sql

-  Update missing deDE locale title for NPC 16279 Tannaria
- None
- https://wowwiki-archive.fandom.com/wiki/Tannaria
- https://de.tbc.wowhead.com/npc=16279/tannaria
- Ran SQL
1. Run SQL
2. Check that there are no errors
3. No further tests needed because you need an deDE client and i checked it by myself …

fix(sql/creature_template_locale): Tannaria deDE Title

---

data/sql/updates/pending_db_world/rev_1625434614739025100.sql

Add roleplay missing for the quest 'Set Them Ablaze!' upon returning the quest
-  Closes #6729
-  Closes https://github.com/chromiecraft/chromiecraft/issues/1089
https://youtu.be/XgRMniOXs04?t=124
https://classic.wowhead.com/quest=3463
https://classic.wowhead.com/npc=8509/squire-maltrake
https://classic.wowhead.com/npc=8480/kalaran-the-deceiver#screenshots
- Test in local AzerothCore environment, performs the RP perfectly.
1. `.go c id 8509`
2. `.q a 3463`
3. `.q c 3463`
4. Return the quest and check that the RP is performed …

fix(DB/smart_scripts): Add roleplay for the quest Set Them Ablaze!

---

data/sql/updates/pending_db_world/rev_1625489162833644602.sql

Restores gossip to Maggran Earthbinder (ID 11860). Did some digging in the npc_text table and his text was already in there, so verified the text matched that listed for him in Wowpedia and linked everything back up in gossip_menu and creature_template.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6739
- Closes https://github.com/chromiecraft/chromiecraft/issues/1094
Text matches that found here: https://wowpedia.fandom.com/wiki/Maggran_Earthbinder
- Tested in game:
1. .go c 29245
N/A. …

fix(DB/Creature): Add gossip to Maggran Earthbinder

---

data/sql/updates/pending_db_world/rev_1625579303979883175.sql

- Moves Glasshide Gazer spawn 21996 about 7 units up so it's sitting on the sand, not underground. 
- Also added MovementType = 1 and wander_distance = 25 like all the other ones nearby.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6766
- Closes https://github.com/chromiecraft/chromiecraft/issues/1108
- Ran SQL, no errors/warnings, correct number of rows changed. (1)
- Checked in game, NPC was visible and not pretending to be a sandworm.
1. .go c 21996. If it immediately bites you, the PR worked. Such gratitude.
N/A. …

fix(DB/Creature): Correct Glasshide Gazer position and movement

---

data/sql/updates/pending_db_world/rev_1625583552450565968.sql

- Adjusts Ironfur Bear spawn 50650 and Longtooth Runner spawn 50875 so they do not spawn inside large trees.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6545
- Closes https://github.com/chromiecraft/chromiecraft/issues/982
- Checked in open world, both mobs were spawning correctly outside the tree objects rather than inside them:
1. .go c 50650
2. .go c 50875
3. Check to see if either command puts you inside a tree (and with these really big trees, you need to run around a bit to see as the textures don't show from the inside.)
N/A. …

fix(DB/Creature) Stop two NPCs spawning inside trees

---

data/sql/updates/pending_db_world/rev_1625603525661258200.sql

- Correct some timers.
- Faction shouldn't change as the NPC shouldn't be helping the player (https://youtu.be/OrlFu1c0Zis?t=112).
- When Mokk dies Witch Doctor Unbagwa should stop casting.
- Mokk sets data based on GUID and not on distance.
- Closes #6774
- Closes https://github.com/chromiecraft/chromiecraft/issues/1065
- Tested on my local AC, he always started the event even if Mokk was far away.
1. `.go c id 1449`
2.  `.q a 348`
3. `.additem 2799`
4. Start the quest, finish it, remove the quest, do it again. …

fix(DB/smart_scripts): Rewrite Stranglethorn Fever quest

---

.github/workflows/docker_build.yml

-  fix job if that has multiple conditions 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6803 …

fix(CI): docker workflow update

---

data/sql/updates/pending_db_world/rev_1625927133942554056.sql

- Nudges a Wrathscale Siren (ID 17195, GUID 60996) spawn location up so she doesn't spawn under the floor.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6831
- Closes https://github.com/chromiecraft/chromiecraft/issues/1129
- Ran SQL, no errors/warning, 1 entity changed as expected.
- Checked in game, she's spawning properly now:
1. .go c 60996
2. Observe.
N/A. …

fix(DB/Creature): Correct Wrathscale Siren spawn location

---

src/server/database/Database/DatabaseWorkerPool.cpp

- Point to wiki... Hopefully less tickets from people that do weird stuff o.o …

chore(Core/Database): Add info about errors

---

deps/g3dlite/source/debugAssert.cpp

fix(Deps/G3DLite): char to LPTSTR

---

data/sql/updates/pending_db_world/rev_1626390963148739000.sql

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6952
- Fix by @mpfans

fix(DB/Locale): better chinese translations by @mpfans

---

data/sql/updates/pending_db_world/rev_1626532264671526700.sql

Champion Cyssa had  Farseer Umbrua`s gossip. That happened because the gossip menu id had 2 gossip lines.
One the draenei and other the correct one.
I deleted the correct one and added to a new gossip id.
After that i updated the character to use the right one.
-  Deleted the line from the gossip menu id
-  Added the right line to a new gossip line
-  Updated the character to she uses the right line now
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6971
- Closes https://github.com/chromiecraft/chromiecraft/issues/1212
Picture of the fix:
Just to be sure i didnt broke the Farseer gossip i checked, and its all right.
-  I went with a paladin wigher that lvl 20, so she can give us the quest.
-  Observe the gossip is correct
1. .go c 32066
2. Speak with her with more that …

fix(DB/Gossip): Fix Champion Cyssa Dawnrose gossip in Undercity

---

data/sql/updates/pending_db_world/rev_1626478998978263400.sql

-  Move the Large Termite Mound (ID = 177464 - GUID = 45874) to the ground
- Closes #6954
Before:
After:
- .go o 45874
- Observe
1. .go o 45874
2. Observe …

fix(DB/GO): move termite mound to the ground

---

data/sql/updates/pending_db_world/rev_1626479953231614600.sql

-  Moves the herbs (GUID 3564 and 85462) to the nearest spot outside
- Closes #6312 
- Closes #6314
Before - 3564:
After - 3564:
Before - 85462:
After - 85462:
- .go o 3564, 85462
- Observe
1. .go o 3564, 85462
2. Observe …

fix(DB/GO): move herbs outside of buildings

---

data/sql/updates/pending_db_world/rev_1626790590532118200.sql

Changed the spawn and animprogress so the book can spawn in his default location
Closes issue#7037
-  Changed x y z coordinates so it match the spawn point
-  Changed animprogress  from 100 to 0 because its not a box
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7037
https://classic.wowhead.com/object=175763/old-hatreds-the-colonization-of-kalimdor
https://wow.zamimg.com/uploads/screenshots/small/937977.jpg
- Go to Tanaris ( i used .go c id 9460)
- Look for the book. Its near the south door, look for the image in source
1. Go to Tanaris
2. Look for the book
3. Open it and check if it can be read
TEST
Opening it …

fix(DB/gameObject): Fixed Book "Old Hatreds - The Colonization of Kalimdor" spawn

---

data/sql/updates/pending_db_world/rev_1626645229282661200.sql

The box of supplies dont have silver in the loot table
Closes AzerothCore issue#7018
-  I added from 1 to 4 silvers as the source indicates
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7018
- Closes https://github.com/chromiecraft/chromiecraft/issues/1230
https://tbc.wowhead.com/item=6827/box-of-supplies#comments:id=2675693
https://wowpedia.fandom.com/wiki/Box_of_Supplies
-  .additem 6827
-  See if there is silver on it
Proof
1. .additem 6827
2. Open it
3. Notice boxes will contain coin
- [On https://tbc.wowhead.com/item=6827/box-of-supplies#contains;0-19+16+1 it seems to have more items on it than we have, dont know how accurate is that web page, jut to have in mind] …

fix(DB/item): Box of supplies not containing coin reward

---

data/sql/updates/pending_db_world/rev_1626953516206751500.sql
src/server/game/Spells/SpellMgr.cpp
src/server/scripts/Spells/spell_item.cpp

Fixed #5648
-  Corrected the item script.
- Closes #5648
- Closes https://github.com/chromiecraft/chromiecraft/issues/528
-  …

Scripts/Item: Fixed Gnomish Death Ray.

---

src/server/game/Loot/LootItemStorage.cpp

-  
-  
- Closes 
Missing a write to 'conditionlotid'
- 
- 
1.
2.
3.

#6337 Missing supplement

---

data/sql/updates/pending_db_world/rev_1626683624183921600.sql

Now Miran will walk instead of running to the quest location.
Closes AzerothCore issue#6985
-  Changed the Run param on SmartAI so he will walk instead of running
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6985
TEST
https://user-images.githubusercontent.com/87535580/126131165-3bfecbe4-a243-4620-8df4-832cafc60f09.mp4
- .quest add 454 (Needed before the one fixed)
- .go c id 1379
- Complete the quest 454 speaking with miran.
- Accept the quest Protecting the Shipment
- See him walk to the marker instead of running
1.  .quest add 454 (Needed before the one fixed)
2.  .go c id 1379
3.  Complete the quest 454 speaking with miran.
4.  Accept the quest Protecting the Shipment
5.  See him walk to the marker instead of running …

fix(DB/NPC-Quest):Fixed the quest Protecting the Shipment

---

data/sql/updates/pending_db_world/rev_1626687838564902600.sql

Added the armor multiplier from 1 to 1.5 as source indicates
Closes AzerothCore issue#6907
-  Added the armor multiplier from 1 to 1.5 as source indicates
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6907
https://user-images.githubusercontent.com/40864460/125347395-265b9f80-e35b-11eb-8a69-30fcc924db3d.png
- Used the .npc info on those creatures to check the armor before and after the changes
Before
After
1. .go c id 3532 and .go c id 3528
2. .npc info 3532 and  .npc info 3528 and check if the armor is as the source indicates …

fix(DB/Creature): Increased armor of Pyrewood leatherworker and armorer and their worgen transformation

---

data/sql/updates/pending_db_world/rev_1626802354783547000.sql

-  I changed the z position so the nodes that were spawning underground are now on ground level
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7042
- Closes https://github.com/chromiecraft/chromiecraft/issues/1249
They have to be mineable
- When using any of the commands below you get teleported to ground level, instead of falling.
.go object 73680
.go object 73681
.go object 73682
.go object 73683
.go object 73684
I waited so i could say some of them spawned but no luck.
1 - .go object 73680
.go object 73681
.go object 73682
.go object 73683
.go object 73684
(anyone of them is fine)
2. See if the node is above ground …

fix(DB/GameObject): Fixed some nodes so they spawn on ground level

---

data/sql/updates/pending_db_world/rev_1626875485474871100.sql

-  They had no movement on any spawn, so i added to some of them
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6813
- Closes https://github.com/chromiecraft/chromiecraft/issues/989#issuecomment-870786353
- .go c id 3197 and .go c id 3198
- Check if some of them move now
Test
https://user-images.githubusercontent.com/87535580/126500662-63fce107-7cb7-4d3a-8fbe-32c6c913a899.mp4
1. .go c id 3197 and .go c id 3198
2. Check if some of them move now
- As you maybe see on the test video some of the Voidwalker minions are spawning outside i think, and when loaded they start going to their masters. …

fix(DB/Creature): Added movement to some spawns of Burning Blade Fanatic and Burning Blade Apprentice

---

data/sql/updates/pending_db_world/rev_1626884022511079500.sql

He had speed of 1.54 instead of 1 as the rest of orcs
-  Slowed down the movement speed of Dragonmaw Battlemaster from  1.54 to 1
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6552
- Closes https://github.com/chromiecraft/chromiecraft/issues/980
https://youtu.be/miU442qvovg
- .go c id 1037  
- Check his speed
Video
https://streamable.com/tl2282
1.  .go c id 1037  
2. Check his speed …

fix(DB/Creature): Slowed down the movement speed of Dragonmaw Battlemaster

---

.github/SECURITY.md
src/cmake/macros/FindMySQL.cmake

feat(Cmake/MySQL): add support MariaDB 10.6

---

data/sql/updates/pending_db_world/rev_1627113920593737013.sql

This PR copies the SmartAI script written by @ZenoX92 for Trinity across to AC. It fixes the final event for "The Test of Righteousness" 3/3 (https://tbc.wowhead.com/quest=1806/the-test-of-righteousness). I am not the author, just the committer.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7083
- Closes https://github.com/chromiecraft/chromiecraft/issues/1261
Source for correct behaviour: https://youtu.be/G4tXyQ23d-o?t=976
https://wowpedia.fandom.com/wiki/The_Test_of_Righteousness_(3)
Source for fix:
https://github.com/TrinityCore/TrinityCore/issues/21938
- Tested in game, event now runs properly:
https://user-images.githubusercontent.com/81782124/126863770-d5328edf-8d21-4b20-91fb-5ce08fddaa47.mp4
1. Be a paladin of the correct level …

fix(DB/Script): Adds NPC event for The Test of Righteousness 3/3

---

data/sql/updates/pending_db_world/rev_1627307634943513800.sql

-  Added patrolling to Dart
-  Changed his spawn speed from 5 minutes to 5 hours 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6820
- Closes https://github.com/chromiecraft/chromiecraft/issues/981
https://classic.wowhead.com/npc=7016/lady-vespira
https://www.youtube.com/watch?v=Qob9-gInCqA
https://user-images.githubusercontent.com/80769357/126553797-8046bf94-2196-4956-8851-abc85e4b5b9e.jpg
https://user-images.githubusercontent.com/80769357/126553800-968af382-3500-4ac7-8109-ac98d53cc60c.jpg
- .go c id 14232
- Check the route, all good
Small video proof
https://user-images.githubusercontent.com/87535580/127001156-0f3a6d5e-9dbb-4fe0-aaa9-3e6d4a60bb4b.mp4
1.  .go c id 14232
2. Check the route …

fix(DB/Creature): Added patrolling to Dart(14232)

---

data/sql/updates/pending_db_world/rev_1627383748783756100.sql

-  Changed the spawn point of  Scarlet High Clerist to the top of the tower as the source say
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7138
- Closes https://github.com/chromiecraft/chromiecraft/issues/1292
https://tbc.wowhead.com/npc=1839/scarlet-high-clerist#comments
https://www.wowhead.com/npc=1839/scarlet-high-clerist#comments (only look at 3.3.5 or earlier comments)
World of Warcraft Atlas
- .go c 49764
- Check the new spawn
Before
https://user-images.githubusercontent.com/80769357/127042840-41c624f8-8d4a-46fb-bbc9-7a4769f58d54.jpg
After
1. .go c 49764
2. Check the new spawn …

fix(DB/Creature): Fixed spawn point of Scarlet High Clerist

---

data/sql/updates/pending_db_world/rev_1627384150089455900.sql

-  Added a patrolling route to Foulmane
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7137
- Closes https://github.com/chromiecraft/chromiecraft/issues/1293
https://tbc.wowhead.com/npc=1847/foulmane#comments
https://www.wowhead.com/npc=1847/foulmane#comments
World of Warcraft Atlas
- .go c 45454
- Check the new route
Small video proof
https://user-images.githubusercontent.com/87535580/127145821-30b208d3-891d-4c8b-9db6-72d4bb9d4531.mp4
1. .go c 45454
2. Check the new route …

fix(DB/Creature): Added patrolling to Foulmane

---

data/sql/updates/pending_db_world/rev_1627578885877631300.sql

-  Changed the display id so it match the rest of the moonwells
-  Reverted the 4 deleted nodes
-  Changed the spawn so it cant be seen
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7156
- Closes https://github.com/chromiecraft/chromiecraft/issues/1304
https://wowpedia.fandom.com/wiki/Moonwell
- .go c 90465 - ports you to a nelf next to the SW moonwell.
- Add all the skills with .learn all crafts
- Add felcloth with .add 14256 20
- Use the mooncloth recipe, all good
Picture
1. .go c 90465 - ports you to a nelf next to the SW moonwell.
2. Add all the skills with .learn all crafts
3. Add felcloth with .add 14256 20
4. Use the mooncloth recipe …

fix(DB): Fixed Stormwind moonwell

---

src/server/worldserver/ACSoap/ACSoap.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/2a12e96d1739a12c5ecfe375eabf5343557cb592)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/de4ccc7f2785f61ea1f6eb514d948b73a8ddfb98)
Co-Authored-By: Giacomo Pozzoni <giacomopoz@gmail.com>
-  As the code is the same I assume these ASan warnings would be the same here.
- None
I don't know, I do not use SOAP.
Maybe check that it starts, works and closes correctly …

fix(Core/SOAP): mem leak and new/free mismatch

---

data/sql/updates/pending_db_world/rev_1627568726175425000.sql

-  Fix his spawn time from 2.45 hours to 24h as wow atlas
-  Added his 2 new spawns added on https://github.com/azerothcore/azerothcore-wotlk/pull/7039 in his pool table so he can only spawn 1 Olm at the same time
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7167
- Closes https://github.com/chromiecraft/chromiecraft/issues/1306
- .go c 51897, 301303 and 301304 and check he spawned only once
Video proof
https://streamable.com/dhzqa7
1. go c 51897, 301303 and 301304 and check he spawned only once …

fix(DB/Creature): Fixed Olm the wise spawning multiple times concurrently

---

data/sql/updates/pending_db_world/rev_1627741035221642000.sql

-  Added some patrolling to Azurous
-  Changed his movement from 1.74 to 1
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6827
- Closes https://github.com/chromiecraft/chromiecraft/issues/993#issuecomment-868957893
- .go c 51890
- Check his new route
https://user-images.githubusercontent.com/87535580/127742826-6fea1fd0-6984-48d3-9d60-8366d508071e.mp4
1. .go c 51890
2. Check his new route
- Might be good idea to open another issue to add more spawns to him, because he has been seen on wowhead on the ice thistle hills. Or we can add them if the AzerothCore teams wants on this PR …

fix(DB/Creature): Added patrolling to Azurous(10202)

---

data/sql/updates/pending_db_world/rev_1627571680257852000.sql

- Increased the spawn timer from 2h to 24h
- Added 2 new spawns
- Added movement to the spawns
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7154
- Closes https://github.com/chromiecraft/chromiecraft/issues/1305
https://tbc.wowhead.com/npc=14339/death-howl#comments
- .go c 40656 or .go c 152290 or .go c 152291
- Check if he moves in the spawn
- Check if ony one of them is active at the same time
Video
https://user-images.githubusercontent.com/87535580/127520437-d8f2988c-1504-4edc-8df2-a55cfdecf024.mp4
1. .go c 40656 or .go c 152290 or .go c 152291
2.  Check if he moves in the spawn
3. Check if ony one of them is active at the same time …

fix(DB/Creature): Fixed spawns of Death Howl

---

data/sql/updates/pending_db_world/rev_1627733875042202000.sql

-  Added movement to his spawn
-  Added new spawn near the inn in sorrow hill
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7143
- Closes https://github.com/chromiecraft/chromiecraft/issues/1297
https://www.wowhead.com/npc=1848/lord-maldazzar#comments
https://classic.wowhead.com/npc=1848/lord-maldazzar#comments
- .go c 52725 or .go c 152292
- Checked movement and new spawn
Video
https://user-images.githubusercontent.com/87535580/127739691-d6c6c662-1ebc-4de4-a5d3-df6818accce1.mp4
1.  .go c 52725 or .go c 152292
2. Checked movement and new spawn …

fix(DB/Creature): Added spawn and movement to Lord Maldazzar

---

data/sql/updates/pending_db_world/rev_1627743560834389300.sql
src/server/scripts/Pet/pet_generic.cpp
src/server/scripts/Spells/spell_item.cpp

Fixed #6609
-  Added missing summon script.
- Closes #6609
- Closes https://github.com/chromiecraft/chromiecraft/issues/1143
1. `.set 202 300` (engineering skill)
2. `.additem 10587`
3. Equip and use it …

fix(Scripts/Items): Fixed Goblin Bomb Dispenser.

---

data/sql/updates/pending_db_world/rev_1627898569049526800.sql

-  Reduced the movement speed from 2.65 to 1
-  Added movement roam to her spawn point
- Changed her spawn time to 38h as source said between 32 and 48h
- Closes https://github.com/chromiecraft/chromiecraft/issues/1204
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6953
https://classic.wowhead.com/npc=14344/mongress#comments
https://www.youtube.com/watch?v=2_zZ8gzgWQw
https://youtu.be/iSqn4QEOhHo?t=6
- . go c id 14344
- See her movement
Video
https://user-images.githubusercontent.com/87535580/127844994-2f1b0608-7042-4479-b71c-1ff0589ada1c.mp4
1. . go c id 14344
2. See her movement …

fix(DB/Creature): Fixed rare mob mongress(14344) spawn movement

---

data/sql/updates/pending_db_world/rev_1627916502657250695.sql

-  Moves Wildthorn Stalker (ID 3819) spawn 34832 out from inside the tree it is currently spawning inside. Finding a good spot was a bit tricky because the area is swarming with Orc guards who attack all wildlife, but found a spot quite close to the tree where it can wander without being ganked.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7204
- Closes https://github.com/chromiecraft/chromiecraft/issues/1330
That NPCs should not spawn inside world objects is not controversial.
- Ran SQL, no errors/warnings, 1 row affected as expected.
- Checked in game, NPC is now visible in open world:
1. .go c 34832 and verify that you are not inside the tree stump.
N/A. …

fix(DB/Creature): Fix spawn point of Wildthorn Stalker

---

data/sql/updates/pending_db_world/rev_1628080294513744600.sql

-  Reduced his movement speed from 2,17 to 1
- Added patrolling around the map as the source indicates
- Closes https://github.com/chromiecraft/chromiecraft/issues/959
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6504
https://classic.wowhead.com/npc=2754/anathemus#comments
https://classic.wowhead.com/npc=2754/anathemus
- .go c id 2754
- Check the route
Video
https://streamable.com/su3jv6
1.  .go c id 2754
2. Check the route …

fix(DB/creature): Added patrolling to Anathemus

---

data/sql/updates/pending_db_world/rev_1628302161194713320.sql

Remove wandering behaviour from the four spawns of Fedfennel (ID 472) in Elwynn Forest. This is a bit unusual - normally we're adding wandering, not removing it - but he's supposed to be standing still at a campsite.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7248
- Closes https://github.com/chromiecraft/chromiecraft/issues/1342
https://wowwiki-archive.fandom.com/wiki/Fedfennel?oldid=2007376
https://www.youtube.com/watch?v=NFMlmSEIov4 (classic WoW)
https://www.youtube.com/watch?v=r9fzTapm0WE (later expansion, still no movement)
- Ran SQL, no errors/warnings, correct number of rows affected.
- Checked in game, he is now correctly motionless.
1. Check in Kiera or port to the GUIDs (8112, 134000, 134001, 134002)
N/A. …

fix(DB/Creature): Remove Fedfennel wandering

---

data/sql/updates/pending_db_world/rev_1628410058620922947.sql

- Rotate NPC Dorin Songblade to the correct facing.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7249
- Closes https://github.com/chromiecraft/chromiecraft/issues/1344
As you can see from the next picture from WoWHead The torch is right on his back while on my screen he was looking at it.
- Ran SQL, no errors/warnings, 1 row affected.
- Checked ingame:
1. .go c 6717 and view his orientation.
N/A. …

fix(DB/Creature): Reorient Dorin Songblade

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp

-  Fixed `BuildListAuctionItems` function
- Closes #7208
- Closes chromiecraft/chromiecraft#1323
https://wowwiki-archive.fandom.com/wiki/API_QueryAuctionItems#Pre-Patch_7.0.3
1. Open auction house window by interacting with any auctioneer
- NPC ID 8723 for alliance
- NPC ID 8724 for horde
2. Type this command in chat to query for all items posted
`/run QueryAuctionItems("", nil, nil, 0, 0, 0, 0, 0, 0, true)`
Keep in mind that the server limits how many of these queries can be done in a certain amount of time (default is 1 query for 
every 15 minutes).
You can check if you are able to query all items again with
`/run local _,canQAll=CanSendAuctionQuery(); print(canQAll)`
If it returns 1, you are allowed to do it, if it returns "nil" you must wait.
3. It should …

fix(Core/Auction): Server Returning Wrong Items With Auction House Function QueryAuctionItems()

---

data/sql/updates/pending_db_world/rev_1628449221739059900.sql

-  Add missing spells for creature Wrath Hammer Construct in BRD https://tbc.wowhead.com/npc=8907/wrath-hammer-construct#abilities;mode:normal
- Closes 
https://tbc.wowhead.com/npc=8907/wrath-hammer-construct#abilities;mode:normal
And sniffs 
And used vmangos spell timers 
- 
1.  `.npc add 8907`
2. test if he uses his new spells
3. …

Add missing spells for Wrath Hammer Construct

---

data/sql/updates/pending_db_world/rev_1628691033880289424.sql

Deletes skinning loot from the following level 1 critters/pets/objects:
| entry | name                          |
|-------|-------------------------------|
|  1419 | Fizzles                       |
|  2230 | Umpi                          |
|  4781 | Snufflenose Gopher            |
|  6728 | Narnie                        |
|  7507 | Brown Snake                   |
|  7508 | Black Kingsnake               |
|  7509 | Crimson Snake                 |
|  7557 | Prarie Dog                    |
|  8662 | Idol Oven Fire Target         |
| 10116 | Slave                         |
| 10577 | Crypt Scarab                  |
| 10657 | Corrupted Cat                 |
| 12202 | Human Skull                   |
| 14453 | Orb of Domination             |
| 14646 | Stratholme Trigger            |
| 14869 | …

fix(DB/creature_template): Make various critters/pets unskinnable

---

src/server/database/Database/DatabaseWorkerPool.cpp

- Correct support `MariaDB 10.6`
- Closes #7086
- 

fix(Core/DBPlayer): correct support MariaDB 10.6

---

data/sql/updates/pending_db_world/rev_1628606203210970248.sql

- Adds movement and wander distance settings to a total of 22 Dunemaul Ogres in Tanaris. Wander distances are derived from working members of each type of ogre and averaged out across each set of spawns.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6948
- Closes https://github.com/chromiecraft/chromiecraft/issues/1198
Found a video of the area: https://www.youtube.com/watch?v=i8aAhjikGuA which shows the ogres all moving around slightly. There are other YT videos of this area, but they're shot on private servers as well, so useless to us.
- Ran SQL, no errors/warning, correct number of rows affected.
- Checked in-game, they all look more natural now.
1. Port to any of the provided GUIDs, i.e. 23126, 23127, 23131, and verify movement
N/A.
When a PR is ready to be tested, …

fix(DB/Creature): Add movement to various Dunemaul Ogres

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp

-  I commented out a condition in ```CheckRequiredBosses```, which in fact we do not need. Now Drakes works fine
- Closes #7246
https://www.youtube.com/watch?v=FgMAbpD1Faw random video
1. ```.gm on``` to tele in the instance
2. ```.go creature 85783```
3. turn gm off ```.gm off```
4. try attacking the drakes and see how they react …

fix(Scripts/BWL): drakes in Blackwing Lair can't attack

---

data/sql/updates/pending_db_world/rev_1628955615714597262.sql

- Moves Silvermane Stalker GUID 93058 so it's not stuck inside a tree.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7342
- Closes https://github.com/chromiecraft/chromiecraft/issues/1410
- Ran SQL, no errors/warnings, 1 row affected as expected.
- Checked in-game:
1. .go c 93058  and confirm it's not inside a tree.
N/A. …

fix(DB/creature): Shift Silvermane Stalker spawn slightly

---

data/sql/updates/pending_db_world/rev_1628999064175305912.sql

- Moves Primitive Owlbeast GUID 92955 to a spawn above ground, and gives it random movement and wander distance.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7347
- Closes https://github.com/chromiecraft/chromiecraft/issues/1411
N/A.
- Ran SQL, no errors/warnings, 1 row changed as expected.
- Checked in-game, NPC was visible and moving:
1. .go c 92955, check that you're not falling through the world, and that the NPC is randomly wandering.
N/A. …

fix(DB/creature): Fix Primitive Owlbeast spawn location, movement

---

data/sql/updates/pending_db_world/rev_1629122909167793000.sql

-  Fix Mr. Smite aggro additional mobs by moving the near creatures further away. The distance is about 1-2 yards adjustment
- Closes https://github.com/chromiecraft/chromiecraft/issues/1444
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7381
- Aggroed Mr. Smite by attacking the rogues at the start of the bridge and also reset the boss with those mobs killed and aggroed by attacking him first, he didn't aggro in both cases.
1. .tele deadmines
2. .go xyz 3.472 -755.362 9.175
3. Aggro smite by aggroing one hidden rogue near the bridge …

fix(DB/Creature): Mr. Smite Aggro

---

data/sql/updates/pending_db_world/rev_1629364085695486470.sql

-  Added patrolling to Murgurgula (17475)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7332
- Closes https://github.com/chromiecraft/chromiecraft/issues/1394
https://tbc.wowhead.com/npc=17475/murgurgula
- .go c id 17475
- Test his movement
Test
https://user-images.githubusercontent.com/87535580/130042068-42bddc94-4ef5-438a-9856-83c6469701e6.mp4
1.  .go c id 17475
2. Test his movement …

fix(DB/Creature): Add patrol to Murgurgula (17475)

---

data/sql/updates/pending_db_world/rev_1629391445774422568.sql

The Ammo Crate doesn't despawn at all in Classic WoW, but in AC we need to wait til the old crate is despawned, before spawning a new one.
-  Decreases the respawn time of the Ammo Crate (entry: 176785, guid: 10663) from 900 s to 15 s.
- Closes AC https://github.com/azerothcore/azerothcore-wotlk/issues/7400
- Closes CC https://github.com/chromiecraft/chromiecraft/issues/1447
- Ran SQL, no errors
- checked db and in-game: Ammo Crate respawns after 15 s
1. `.go gobject 10663`
2. `.quest add 5541`
3. Pick up the Ammo and wait 15 s for the crate to respawn …

fix(DB/GO): Decreases the respawn time of Ammo Crate

---

src/server/game/Maps/Map.cpp

Fixes #7580
- Closes #7580
1. `.quest add 13836`
2. Go fishing in Dalaran sewer
3. Unable to catch the task item, and caught a fish that does not belong to the sewer (ID 41808 and id 41814) …

fix(Core/Maps): Fixed getting wrong area/zone on spawn.

---

data/sql/updates/pending_db_world/rev_1629918244800506403.sql

-  Added the commit https://github.com/TrinityCoreLegacy/TrinityCore/commit/f251d91a8ec8df97280f15578b37710cb87c199b from TrinityCore
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7554
- Closes https://github.com/chromiecraft/chromiecraft/issues/1522
- .quest add 251 (Need for this quest to pop up)
- .go c id 268
- Accept quest
- Wait 2 or 3 seconds while he does the script
Video test
https://streamable.com/b53r5m
1. .quest add 251 (Need for this quest to pop up)
2.  .go c id 268
3. Accept quest
4.  Wait 2 or 3 seconds while he does the script …

fix(DB/Quest): Add script to Wait for Sirra to Finish

---

data/sql/updates/pending_db_world/rev_1629919057423789312.sql

-  Changed the allowed races from horde to blood elf only
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7547
- Closes https://github.com/chromiecraft/chromiecraft/issues/1520
https://tbc.wowhead.com/blood-elf#quests all of the quests mentioned above are listed as Blood Elf only quests there
https://wotlk.evowow.com/?race=10#quests:0+3+1+2 has them listed as Blood Elf quests also
- .go c id 15296 as orc for example (15278,15281, 15296, 15295)
- See the quest is available to you
- Apply fix and see the quest is now hidden
1.  .go c id 15296 as orc for example
2. See the quest is available to you
3. Apply fix and see the quest is now hidden
Before
After …

fix(DB/Quest): Starting Blood Elf quests are now only belf

---

data/sql/updates/pending_db_world/rev_1629983088640886216.sql

Added movement to Risen Creeper,  Dreadbone Skeleton and Deathcage Scryer on ghostlands
-  Added movement to Risen Creeper,  Dreadbone Skeleton and Deathcage Scryer on ghostlands
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7478
- Closes https://github.com/chromiecraft/chromiecraft/issues/1484
https://youtu.be/E_k7PGkHyL4?t=1201
- .go c 82122
- Check no movement
- Apply sql
- See movement
Test
Before
https://user-images.githubusercontent.com/87535580/130968227-e6aea280-e56a-4087-ac4b-e5814668bc8e.mp4
After
https://user-images.githubusercontent.com/87535580/130968248-6ea89758-3fec-4010-b1f6-ffc4f33826f0.mp4
1. .go c 82122
2. Check no movement
3. Apply sql
4. See movement …

fix(DB/Creature): GhostLands Added movement to multiple mobs

---

data/sql/updates/pending_db_world/rev_1629982964484888577.sql

- Adds Den Mother (ID 6788) and 3 of her nearby Thistle Cubs (ID 6789) to a formation such that any one of the 4 being aggroed will aggro the other 3 NPCs. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7562
- Closes https://github.com/chromiecraft/chromiecraft/issues/1532
https://youtu.be/8-E_QE1le4Q?t=50 - clip shot on retail showing shooting a cub rouses the Den Mother + other cub.
"Adds from the den mother. Hard to tame if you are lv 10 :P" - https://tbc.wowhead.com/npc=6789/thistle-cub#comments
- Ran SQL, no errors/warnings, correct number of lines changed.
- Tested in game. Taunting one cub now pulls all 4:
- 
https://user-images.githubusercontent.com/81782124/130968289-88107a2c-9f85-471f-b243-591f667cb8f3.mp4
1. .go c 37567 (takes you to a cub closest to the cave …

fix(DB/creature_formation): Link Den Mother and cubs

---

data/sql/updates/pending_db_world/rev_1630007612293972500.sql

Fixes #5570.
- Closes #5570
- Closes https://github.com/chromiecraft/chromiecraft/issues/487
1. `.go c Xan'tish`
2. Follow him around for a few minutes. …

fix(DB/Creatures): Fixed  Xan'tish Snakes pathing.

---

data/sql/updates/pending_db_world/rev_1630100495388127462.sql

aye so in this bih we got this mf Jargba that when it MC us the core set the player's faction the same as the one who charmed us so Jargba in this case. the relationship between Jardba and its adds factions be```REP_NEUTRAL```.
problem is that when we are MC we select our victim with ```Unit::SelectNearbyTarget``` that tolerates ```REP_NEUTRAL``` so if the add is nearer to us than another party member we finna attack the neutral mob instead of party members.
imo by looking at this
https://wotlkdb.com/?faction=109
https://wowpedia.fandom.com/wiki/Death_Speaker_Jargba_(Classic)
Jardgba should be changed faction to the same faction that other quillboars elite in razorfen are so faction 152 instead of the generic "Monster" 14 that is now => https://wotlkdb.com/?faction=14
this way when his …

fix(DB/Creature): fix Death Speaker Jargba's MC

---

data/sql/updates/pending_db_world/rev_1630147471003792720.sql

-  Change quest log objective text from **Return to Bashana Runetotem at The Golden Plains in Mulgore** into **Return to Bashana Runetotem at Elder Rise in Thunder Bluff**.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6972
- Closes https://github.com/chromiecraft/chromiecraft/issues/1211
database in-game + quest log.
- Apply SQL via HeidiSQL, no error
- Tested on local server / Win 10 64 Bit
BEFORE
AFTER
1. .go c 24796
2. .quest add 6561 
3. .quest complete 6561 
4. look at objective pane …

 fix(DB/quest_template): Correct objective for the Blackfathom Villainy

---

data/sql/updates/pending_db_world/rev_1630227596211930942.sql

-  Added new spawn and roaming
-  Changed the spawn time from 20h to 6h
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7352
- Closes https://github.com/chromiecraft/chromiecraft/issues/1416
https://classic.wowhead.com/npc=8219/zularek-hatefowler
https://tbc.wowhead.com/npc=8219/zularek-hatefowler#comments
https://www.youtube.com/watch?v=UN5-JSYqMGs
- .go c 86257 or 138255
- Check roaming around the spawn
Test
https://user-images.githubusercontent.com/87535580/131244904-cc52956d-84e1-4c52-891d-e63b15c2b186.mp4
1. .go c 86257 or 138255
2.  Check roaming around the spawn …

fix(DB/Creature): Fixed Zul'arek Hatefowler

---

data/sql/updates/pending_db_world/rev_1630228897555898489.sql

-  Added patrol movement to Lord Xiz
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7353
- Closes https://github.com/chromiecraft/chromiecraft/issues/1418
[Video from TBC Classic](https://www.youtube.com/watch?v=QU1Oq5TLbm0&t=246s)
https://youtu.be/8JJGepcLLAQ?t=65
- .go c id 17701
- Check route
Video
https://user-images.githubusercontent.com/87535580/131245528-c16bda09-76a0-43e3-ad4e-bc86f7effcea.mp4
1. .go c id 17701
2. Check route …

fix(DB/Creature): Fixed Lord Xiz

---

data/sql/updates/pending_db_world/rev_1630252354413939245.sql

-  Used some code from https://github.com/TrinityCore/TrinityCore/issues/17267
-  Using the base commit i fixed the barrels not spawning after picking quest and the orientation of the dude after doing the route
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6984
https://www.youtube.com/watch?v=uN-Va90gL70
- .go c 1373 and pick the quest
- .add 2686 10 for the beer needed to distract the guy
- Start the distraction and see when the guarded barrel turns into unguarded
- Without turning the quest check the route and text of the guy
- After that check the unguarded barrel transforms into the guarded one
- After doing the route you could distract him again, this time do the quest and check that after doing all of that the distraction quest dissapears.
Video …

fix(DB/Quest): Fixed quest Bitter Rivals

---

data/sql/updates/pending_db_world/rev_1630312205613208089.sql

-  adds missing movement for Spindlewebs
- Closes https://github.com/chromiecraft/chromiecraft/issues/1510
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7511
- Run SQL, 11 Affected Rows, 0 errors
- Check using SQL
```
+-------+--------------+-----------------+
| guid  | MovementType | wander_distance |
+-------+--------------+-----------------+
| 82160 |            1 |               5 |
| 82163 |            1 |               5 |
| 82166 |            1 |               5 |
| 82167 |            1 |               5 |
| 82170 |            1 |               5 |
| 82173 |            1 |               5 |
| 82212 |            1 |               5 |
| 82213 |            1 |               5 |
| 82215 |            1 |               5 |
| 82238 |            1 |               5 |
| …
```

fix (DB/Creature): Add movements for Spindleweb

---

data/sql/updates/pending_db_world/rev_1630180229119275600.sql

Fixes #6501
- Closes #6501
- Closes https://github.com/chromiecraft/chromiecraft/issues/951
- Not tested
1. `event start 1`
2. Start quest Unusual Activity (quest ID is 11886) on two characters and accounts.
3. Go to Zoram Strand in Ashenvale.
4. Use the Totemic Beacon on the first character (1st account).
5. Use the Totemic Beacon on the second character (2nd account). …

fix(DB/Creature): Corrected model of Earthen Ring Guide.

---

data/sql/updates/pending_db_world/rev_1630345537511243600.sql

Fixes #6560
- Closes #6560
- Closes https://github.com/chromiecraft/chromiecraft/issues/947
1. Teleport to GUID 245691 and see the tent is spawned …

fix(DB/GameEvents): Added missing pavilion at Tarren Mill.

---

data/sql/updates/pending_db_world/rev_1630318500363217970.sql

-  Make Webwood spiders and Githyiss the Vile neutral by adding civilian status and faction creature, that is neutral to players
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7627
- Closes https://github.com/chromiecraft/chromiecraft/issues/1581
https://www.wowhead.com/quest=917/webwood-egg#comments
- .gm off (if not they are always yellow)
- .go c id 1986 and check the bar now yellow
- .go c id 1994and check the bar now yellow
Test
1. .gm off ( if not they are always yellow)
2. .go c id 1986 and check the bar now yellow
3. .go c id 1994and check the bar now yellow …

fix(DB/Creature): Make Webwood spiders and Githyiss the Vile neutral

---

data/sql/updates/pending_db_world/rev_1630344741636829281.sql

The gossip options for Celebras the Redeemed were very different from https://wowpedia.fandom.com/wiki/Celebras and some of them were broke.
I changed the whole menu so we have now 3 options, as the source says, and every one of those options are now linked properly to the answer.
-  Changed the menu options for celebras the redeemed
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7612
- Closes https://github.com/chromiecraft/chromiecraft/issues/1567
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6902
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6749
https://wowpedia.fandom.com/wiki/Celebras
- .go c id 12225 (cursed part)
- Kill it
- Celebras the Redeemed will now spawn
- Talk to him and check that all the options work
1. .go c id …

fix(DB/Creature): Fixed Celebras the Redeemed gossip

---

data/sql/updates/pending_db_world/rev_1630172168898330770.sql

-  Decrease spawn time for **Bloodsail Charts** & **Bloodsail Orders** from 900sec to 180sec
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7602
- Closes https://github.com/chromiecraft/chromiecraft/issues/1549
-  Ran SQL, 3 affected rows, 0 error
- Check in-game, I only records for last 30 seconds since limitation size for uploading video on github
https://user-images.githubusercontent.com/44707108/131226872-49532841-d801-4238-8370-a81acd1131ad.mp4
1. .go c 382
2. check crates behind the tent
3. stopwatch …

fix(DB/QuestItems): Change items respawn time The Bloodsail Buccaneers

---

data/sql/updates/pending_db_world/rev_1630408706945809100.sql

-  Adjust Cavindra position
- Closes #7656 
- Closes https://github.com/chromiecraft/chromiecraft/issues/1592
https://youtu.be/AsjFD5ymQpA?t=68
- Checked ingame
- 
1. `.go c id 13697` …

fix(DB/creature): Fix Cavindra position inside the pool

---

data/sql/updates/pending_db_world/rev_1630405831769074100.sql

-  Set correct faction according to sniffs.
- Closes #7654 
- Closes https://github.com/chromiecraft/chromiecraft/issues/1591
- Checked ingame with horde character.
1. `.go c id 2386` as horde
2. Guards attack you …

fix(DB/creature_template): Fixed Southshore Guards faction

---

src/server/game/DungeonFinding/LFGMgr.cpp

Possible crashfix.

---

data/sql/updates/pending_db_world/rev_1630244571729817781.sql

-  Changes the Brood of Nozdormu reputation gain from killing Anubisath Defender, Anubisath Sentinel, Obsidian Eradicator, Qiraji Lasher, Vekniss Hive Crawler, Vekniss Soldier, Vekniss Stinger, Vekniss Warrior, Vekniss Wasp from 500  to 100 and stop giving rep up to neutral.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7621
- Closes https://github.com/chromiecraft/chromiecraft/issues/1577
https://classic.wowhead.com/faction=910/brood-of-nozdormu#npcs
- Ran SQL, 10 Affected rows, 0 error
Check via in-game
1. Kill mob in Friendly Reputation
2. Kill mob in Neutral Reputation 
3. Kill mob in Unfriendly Reputation
4. Kill mob in Hostile Reputation
5. Kill mob in Hated Reputation
Tested on local server / Win 10 64 Bit
1. .go c 88015 / Anubisath Defender
2. .modify rep 910 …

fix(DB/Reputation):Brood of Nozdormu reputation

---

rev_1630418153212582713.sql

-  Add roaming for Stonewind Trackers (GUID 82666, 82668)
- Closes https://github.com/chromiecraft/chromiecraft/issues/1493
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7487
- 
- Ran SQL, 2 Affected rows, 0 errors
- Check via in-game
https://user-images.githubusercontent.com/44707108/131516557-b0f1bf2f-0daf-44c7-86f5-30dc64377e60.mp4
1. go .c 82666 / 82668
2. observe …

 fix (DB/Creature): Add roaming Stonewind Trackers

---

data/sql/updates/pending_db_world/rev_1630263728286533056.sql

-  Added Return to Krog for The Black Shield questline
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6077
- Closes https://github.com/chromiecraft/chromiecraft/issues/714
https://wotlkdb.com/?npc=4943
https://tbc.wowhead.com/quest=11204/return-to-krog
- Ran SQL, Affected rows 1, 0 errors.
- Check Via in-game
https://user-images.githubusercontent.com/44707108/131263429-408c294e-03f7-4664-89dc-6edccfc61943.mp4
1.  .quest add 1323
2.   .go c krog
3. Handin quest and accept new one
4. .go c mosarn
5. mosarn give you a new quest …

 fix(DB/Quest): Fix missing quest Return to Krog

---

data/sql/updates/pending_db_world/rev_1630690395841002600.sql
rev_1630418153212582713.sql

-  Delete misplaced update from root dir
-  Create new update with correct path …

fix(DB/updates): Fix merge of PR 7707

---

data/sql/updates/pending_db_world/rev_1630437845134253537.sql

-  Changes to correct reputation for Hydraxian Waterlords
- Closes https://github.com/chromiecraft/chromiecraft/issues/1573
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7618
https://wowwiki-archive.fandom.com/wiki/Hydraxian_Waterlords#Historical_reputation
https://tbc.wowhead.com/faction=749/hydraxian-waterlords#comments
- Ran SQL, 24 Affected rows, 0 errors
- check from query SQL
BEFORE
```
BEFORE
+--------------+--------------------+
| MaxStanding1 | RewOnKillRepValue1 |
+--------------+--------------------+
|            4 |                 25 |
|            5 |                 75 |
|            5 |                250 |
|            7 |               1000 |
|            5 |                100 |
|            5 |                200 |
|            5 |                 50 …
```

fix(DB/Reputation):Hydraxian Waterlords Reputation

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/shared/DataStores/DBCEnums.h
src/server/shared/DataStores/DBCStructure.h

-  Redefine after leaks.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7689
- Open issues for the //@todo's …

refactor(DBC/Misc): Redefine & Define FactionTemplateFlags

---

data/sql/updates/pending_db_world/rev_1630670252547733100.sql

Fixes #6624
- Closes #6624
- Closes https://github.com/chromiecraft/chromiecraft/issues/934
- Not tested
1. `.event start 1`
2. Do some quests from that list #6624 …

fix(DB/Quests): Corrected gold reward for some Midsummer quests.

---

data/sql/updates/pending_db_world/rev_1630684891779932519.sql

-  Add missing exclamation mark on quest item - Elegant Letter https://classic.wowhead.com/item=17126/elegant-letter
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7698
- Closes https://github.com/chromiecraft/chromiecraft/issues/1616
- Ran SQL, 1 Affected rows, 0 erros
https://user-images.githubusercontent.com/44707108/132039114-d622976a-3e83-482a-830a-0713aca822fc.mp4
1. create rogue character and .levelup 23
2. head to rogue trainer and take a letter
3. check on inventory …

 fix(DB/Quests): Exclamation mark - Elegant Letter

---

data/sql/updates/pending_db_world/rev_1630703356735581407.sql

-  Correct objective tracker for quest  "The Perenolde Tiara"
- Add correct translate for other languages - https://cn.classic.wowhead.com/quest=543/%E5%8C%B9%E7%91%9E%E8%AF%BA%E5%BE%B7%E7%8E%8B%E5%86%A0
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6636
- Closes https://github.com/chromiecraft/chromiecraft/issues/1031
https://github.com/chromiecraft/chromiecraft/issues/1031
https://youtu.be/h8MbVLzzsJM?t=478
- Ran SQL, 3 Affected rows, 0 Erros
https://user-images.githubusercontent.com/44707108/132066309-228cfe56-c097-45f2-890a-511982b16c7f.mp4
1. .quest add 543
2. .additem 3684
3. check quest log and objective tracker  …

fix(DB/quest_template): The Perenolde Tiara Objective

---

data/sql/updates/pending_db_world/rev_1630731145138028688.sql

- Changes Rift Spawn (ID 6492) smart scripting so it checks for low health and goes into a stun state once per second, instead of once per 30 seconds. This should make it much more responsive to incoming damage. My only concern about this was presumably it was set to 30 seconds for a reason, and once-per-second checks for 11 spawned creatures is more expensive in terms of server load.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7715
- Closes https://github.com/chromiecraft/chromiecraft/issues/1594
https://youtu.be/91kfcn79zXU?t=40
https://youtu.be/3u6bbzflEDU?t=42
https://wotlk-twinhead.twinstar.cz/?quest=1920
http://wowhead.com/?quest=1920
- Ran SQL, no errors/warnings, 1 row changed as expected.
- Tested in-game. Pulled a bunch of Rift spawns and damaged them all to …

fix(DB/smart_script): Increase Rift Spawn health check frequency

---

src/server/game/Handlers/ItemHandler.cpp

Fixes #7598
- Closes #7598
- Closes https://github.com/chromiecraft/chromiecraft/issues/1565
- Tested ingame with different items.
More info here: #7598. Just add one of these item and try to place them on AH. Before the test, clear your cache folder. …

fix(Core/Items): Properly display item spell charges.

---

src/server/game/Conditions/ConditionMgr.cpp

Ignore the commit with code-style, check only what I changed, it's really a small change.
https://github.com/azerothcore/azerothcore-wotlk/pull/7730/commits/facaf3ddab2f31f815aaf19374ddd820e6b89cba
-  replace ASSERT with logs
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7577
- I didn't test it, but it should not break anything
I suggest to import this on your private server and check if this crash happens again. …

chore(Core/Condition): replace assertion with logs preventing server crash

---

data/sql/updates/pending_db_world/rev_1630832577462717951.sql

-  Change to correct reputation for Cenarion Circle
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7634
- Closes https://github.com/chromiecraft/chromiecraft/issues/1579
https://wowpedia.fandom.com/wiki/Cenarion_Circle_reputation_guide#Reputation
https://www.wowhead.com/faction=609/cenarion-circle
- Ran SQL, 29 Affected rows, 0 Erros
Add 10 rep for Cenarion Circle
Add 30 rep for Cenarion Circle
Add 100 rep for Cenarion Circle
Decreased 300 rep for Cenarion Circle
Decreased 600 rep for Cenarion Circle
Decreased 10 rep for Cenarion Circle
1. Kill creature …

fix(DB/Reputation):Cenarion Circle

---

data/sql/create/drop_mysql.sql

-  Fixes issue with incorrect table names on mysql drop queries.
-  None
1. I mean, just look at it. …

fix(DB/MySQL): Drop script table name

---

src/server/game/Entities/Unit/Unit.cpp

Reverts azerothcore/azerothcore-wotlk#6379
Unfortunately that PR was causing critical issues and we can't afford to have it until a proper solution is available

Revert "Fix NPC enters into EvadeMode, he loses all his Auras."

---

src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h

-  Defined from TC Master branch. 
- better names tbh

chore(Core/Spells): Redefine & Define some castFlags

---

data/sql/updates/pending_db_world/rev_1631296599663223200.sql

Fixes #7643
- Closes #7643
- Closes https://github.com/chromiecraft/chromiecraft/issues/1584
1. Enter a fresh BRD instance
2. Walk to the Vault / Coffer room …

fix(DB/Creatures): remove invalid script for Warder Stilgiss

---

src/server/game/Spells/Auras/SpellAuraEffects.cpp

-  Remove duplicate code.
- As you can see it's already defined on line 3382
- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Auras/SpellAuraEffects.cpp#L3388
- Closes None
- No need
1. No need
2. 
**For …

Core/Misc: Remove duplicate line

---

data/sql/updates/pending_db_world/rev_1631306487914473600.sql
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp

- Closes #7804
- Testd ingame in ToC.
1. `.tele TrialOfTheCrusader`
2. Go to the inc
3. Kill Icehowl or Anub'arak
4. Loot the boss
5. Close the loot
6. You can loot it again …

fix(Scripts/ToC): Removed completely invalid code about removing loot.  Fixes #7804

---

.github/workflows/windows_build.yml

-  update mysql path for windows build
- Closes 

fix(CI): update mysql path for windows build

---

src/server/game/AI/CreatureAI.cpp

* cherry-pick commit <https://github.com/TrinityCore/TrinityCore/commit/462e11c96f6cb3a59fea4dc164886a421db11e52>
Co-Authored-By: Kelno <3866946+kelno@users.noreply.github.com>
-  Remove combo points from creature if it evades
- youtube.com/watch?v=CZbSCtrm8dQ (Video from classic TBC)
- none
1. Be rogue
2. Cast sinister strike on creature
3. Make it evade …

fix(Core/Creature): Remove combo points on evade

---

data/sql/updates/pending_db_world/rev_1631572727925631500.sql

* cherry-pick commit <https://github.com/TrinityCore/TrinityCore/commit/6a46817f5d0a9ec760cc16b0871b74c40033f69a>
- no more dupe
- none
1. SELECT * FROM game_tele WHERE NAME LIKE '%CrusadersOutpost%' …

fix(DB/game_tele): Duplicate teleport name

---

apps/installer/includes/os_configs/osx.sh

-  pinto openssl@1.1 to avoid openssl@3 getting installed
- Closes 

fix(CI/MacOS): pinto openssl@1.1

---

data/sql/updates/pending_db_world/rev_1633781441009417000.sql
data/sql/updates/pending_db_world/rev_1633781700837048300.sql

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8325
- Closes https://github.com/chromiecraft/chromiecraft/issues/2000
- Finish the quests listed onto issue and see the current amount of reputation rewarded, should be higher.
- 
1. Finish the quests listed onto issue and see the amount has doubled.
2.
3. …

fix(DB\Quest):Argent Dawn reward recalculated

---

data/sql/updates/pending_db_world/rev_1634598950367001300.sql

-  Some translations into English of the starting quests of the Draenei zone.
- Closes 
- Windows 10
1. Create a Draenei character
2. Use a game client in Spanish (esES or esMX)
3. Continue to perform missions to the center village.
**For …

fix(DB/locale): Some more translations of the draenei

---

src/server/game/Server/WorldSocketMgr.cpp
src/server/game/Server/WorldSocketMgr.h

-  Move function OnSocketAccept in class
- Part #6865
- Local with MSVC 2022 17.0.0 prev 5.0
`Although I don't think it needs to be tested`
1. Just check world socket (enter in world and etc) …

feat(Core/Socket): make world OnSocketAccept like auth

---

src/server/game/Entities/Player/PlayerUpdates.cpp

- Just a minor code change to fix what would be a compiler warning in C++20
- No need to test anything

fix(Core/PlayerUpdates): one more C++20 compile warning

---

data/sql/updates/pending_db_world/rev_1635873886464817740.sql
src/server/scripts/EasternKingdoms/zone_western_plaguelands.cpp

-  Move Return to the Bulwark and Return to Chillwind Camp quest chains to SAI.
-  Add conditions for existing gossip in DB and remove hard coded text from C++.
None that I can find.
TC
- Builds
- Quest work correctly
1. Add quest 5230 Horde or 5217 Alliance and do quest chain.

fix(Script/SAI/Conditions) Move npcs_dithers_and_arbington script to SAI

---

data/sql/updates/pending_db_world/rev_1635884292065100734.sql

-  Add missing equipment
- Closes #8822
TC
Last one was from sniff.
Checked them
Go to Desolace and view them in Angerforge.

fix(DB/Equipment) Burning Blade npcs

---

src/server/game/World/World.cpp

-  Set the Realm Availability feature as disabled by default.
-  
- Closes 
- 
1.
2.
3. …

feat(Core/World): Don't prevent players from logging characters by default

---

src/server/game/Spells/Spell.cpp
src/server/game/Spells/Spell.h

Fixes #8764
- Closes #8764
More info [here](#8764)

Core/Spells: Triggered spells should not cause players to stand up.

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp

-  Open Rend's and Drakkisath's door when the encounters are done
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9026
- 
1. KIll the bosses, check that their gates open (check the issue for more information)
2.
3. …

fix(Scripts/UBRS): Handle Rend and Drakkisath doors

---

src/server/scripts/Spells/spell_druid.cpp

- Builds
2. test that one druid spell e.g barkskin works as before …

refactor(Scripts/Spells): convert spell_druid into new system

---

src/server/scripts/Spells/spell_hunter.cpp

- Builds
2. test that one hunter spell e.g chimera shot works as before …

refactor(Scripts/Spells): convert spell_hunter into new system

---

src/server/scripts/Pet/pet_generic.cpp
src/server/scripts/Pet/pet_hunter.cpp
src/server/scripts/Pet/pet_mage.cpp
src/server/scripts/Pet/pet_priest.cpp
src/server/scripts/Pet/pet_shaman.cpp

- builds
- worldserver without errors (all scripts are loaded)
1. See that a pet works like before. e.g Earth Elemental …

refactor(Scripts/Creature): convert pets into new system

---

src/server/scripts/Spells/spell_rogue.cpp

- Builds
2. test that one rogue spell e.g blade flurry works as before …

refactor(Scripts/Spells): convert spell_rogue into new system

---

data/sql/updates/pending_db_world/rev_1636371600934152600.sql
src/server/scripts/Spells/spell_mage.cpp

- Builds
2. test that one mage spell e.g deep freeze works as before …

refactor(Scripts/Spells): convert spell_mage into new system

---

src/server/scripts/Spells/spell_paladin.cpp

- Builds
2. test that one paladin spell e.g lay on hands works as before …

refactor(Scripts/Spells): convert spell_paladin into new system

---

src/server/scripts/Spells/spell_paladin.cpp
src/server/scripts/Spells/spell_priest.cpp

- Builds
2. test that one priest spell e.g mind sear works as before …

refactor(Scripts/Spells): convert spell_priest into new system

---

src/server/scripts/Spells/spell_quest.cpp

- Builds
2. test that one quest spell  …

refactor(Scripts/Spells): convert spell_quest into new system

---

src/server/scripts/Spells/spell_shaman.cpp

- Builds
2. test that one shaman spell e.g thunderstorm works as before …

refactor(Scripts/Spells): convert spell_shaman into new system

---

src/server/scripts/Spells/spell_warlock.cpp

- Builds
2. test that one warlock spell e.g banish works as before …

refactor(Scripts/Spells): convert spell_warlock into new system

---

src/server/scripts/Spells/spell_warrior.cpp

- Builds
2. test that one warrior spell e.g deep wounds works as before …

refactor(Scripts/Spells): convert spell_warrior into new system

---

.github/workflows/pr_labeler.yml
src/server/game/Spells/Spell.cpp

- Fix a minor C++ warning in order to test the PR labeller once again

fix(CI): revert sleep + fix shadowing variable issue

---

apps/startup-scripts/gdb.conf
apps/startup-scripts/starter

feat(Apps): Improve crashlogs on Linux.

---

data/sql/updates/pending_db_world/rev_1636812374856286400.sql

-  Add Mend Dragon ability yo Blackhand Dragon Handlers
-  
- Closes 
https://classic.wowhead.com/guides/upper-blackrock-spire-classic-dungeon-strategy-season-of-mastery-som#the-beast
- 
1. Start rend encounter
2. Notice the dragon handlers now heal nearby dragons
3. …

fix(DB/SAI): Blackhand Dragon Handler should cast Mend Dragon

---

data/sql/updates/pending_db_world/rev_1636810061548705300.sql

-  Add curse of thorns ability to the mob
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9174
https://classic.wowhead.com/guides/upper-blackrock-spire-classic-dungeon-strategy-season-of-mastery-som#the-beast
- 
1.go c 9817
2.check that it now casts curse of thorns
3. …

fix(DB/SAI): Blackhand Dreadwaver should cast Curse of Thorns

---

src/server/scripts/Spells/spell_warrior.cpp

fix(Script/Spells): Validate Warrior spells

---

src/server/scripts/Commands/cs_lookup.cpp

-  Fix build for https://github.com/azerothcore/azerothcore-wotlk/commit/ed55aa63af6d7d466bb8e95d154f057608cbdad2

fix(Core/Scripts): corrrect cs_lookup

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_gyth.cpp

-  Update Gyth's encounter state so it's no longer stuck IN_PROGRESS
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/2322
- 
1. Do the arena encounter
2. Try to ress someone
3. …

fix(Scripts/UBRS): Set Gyth's encounter state on death

---

data/sql/updates/pending_db_world/rev_1636656798364802400.sql
src/server/scripts/Commands/cs_misc.cpp

Closes #8845
-  Usage: `inventory count $name or $guid`
- Closes #8845 …

feat(Scripts/Commands): Implemented new command: `inventory count`.

---

data/sql/updates/pending_db_world/rev_1636906059131132400.sql

-  Script quartermaster zigris waypoints
-  
- Closes 
Sniffed waypoints
https://user-images.githubusercontent.com/47818697/141688937-fd809b00-0921-4c0b-bb05-0d089303c28c.mp4
https://user-images.githubusercontent.com/47818697/141688897-455969c0-d845-4c99-a3ac-78b91a3102be.mp4
1. go c id 9746
2. watch his waypoints
3. …

fix(DB/Waypoints): Script Quartermaster Zigris waypoints

---

src/server/game/Loot/LootMgr.cpp

Remove Duplicated Note
-  Remove duplicate Note.
- Closes Nothing
Saw a dupe note in the core.
Compiles, loads with no issues.
This is just code reduction. Nothing to test for. …

chore(Core): remove duplicate comment

---

src/server/scripts/Spells/spell_rogue.cpp

fix(Script/Spells): Validate all rogue spells

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp

-  Fix character cache usage after sorting & global cache prs
-  
- Closes 
- 
- 
1.
2.
3. …

chore(Core/AH): update auction house files after cache update & sorting PR

---

data/sql/updates/pending_db_world/rev_1637407013873952635.sql

- Changes [Emberstrife](https://tbc.wowhead.com/npc=10321/emberstrife)'s respawn timer from 20 minutes to 5. This NPC is part of the Horde's Onyxia key quest chain, so the delay in respawn was inconvenient as well as incorrect.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9241
- Closes chromiecraft/chromiecraft#2351
> I just had to wait 5 min for the respawn. - https://classic.wowhead.com/npc=10321/emberstrife#comments:id=2910244:reply=1237585
> What is respawn time?
XenaSkull on 2006/05/30 (Patch 1.10.2)Subject: "RE: Respawn??"
His respawn is 5 mins exactly. My group messed up and killed him accidently when we were doing the UBRS key quest. We timed him since no one could say for sure on here how long the resapwn time was. So there it is... 5 Minutes. - …

fix(DB/creature): Correct Emberstrife's respawn time

---

src/common/Utilities/EventProcessor.h

Port from TrinityCore.
Nothing to be tested here.

fix(Core/Misc): Added lambda support to EventProcessor.

---

src/server/game/Entities/Creature/Creature.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Creature): crash on SmartAI creature aggro

---

src/server/game/Entities/Creature/Creature.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Creature): Prevent useless grid searches

---

data/sql/updates/pending_db_world/rev_1637108982872651500.sql

-  Added previous quest.
- Closes #9185
- Closes https://github.com/chromiecraft/chromiecraft/issues/2320
- Ran the sql and tested in-game.
1. .go c 6862
2. .setskill 202 300 …

Fix(DB/Quest): Added pre-quest for Flash Bomb Recipe quest

---

src/server/scripts/Kalimdor/OnyxiasLair/boss_onyxia.cpp
src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp

-  Fix broken code style
- Not required
- 

chore(Scripts/OnyxiasLair): Fix broken code style

---

src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp

-  Restore old code deleted in 2eb4228
- Closes #9330
- Compiled and tested in-game
1. go to MC
2. pull golemagg
3. notice adds not engaging

Fix(Core/MC): adds should aggro with Golemagg

---

data/sql/updates/pending_db_world/rev_1637948987614040500.sql
src/server/scripts/Kalimdor/OnyxiasLair/boss_onyxia.cpp
src/server/scripts/Kalimdor/OnyxiasLair/instance_onyxias_lair.cpp
src/server/scripts/Kalimdor/OnyxiasLair/onyxias_lair.h

-  Moved her to BossAI
-  Updated instance to use BossStates
- Removed useless creature scripts
- Closes 
- 
1.Engage Onyxia
2. Check that her abilities & phase transitions still work properly
3. Check that achievements still work properly …

refactor(Scripts/Onyxia): Update Onyxia's script

---

src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgrMacros.h

- Cleanup few scripts in `ScriptMgr`
- Need test `Creature` scripting with/without `mod-eluna`
- For example: https://www.wowhead.com/the-forge-of-souls
- In game https://www.wowhead.com/the-forge-of-souls

fix(Core/ScriptMgr): Cleanup few scripts

---

data/sql/updates/pending_db_world/rev_1638657340.sql

-  Add SAI for missing abilities: Mental Domination & Mind Shatter
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9332
- Closes https://github.com/chromiecraft/chromiecraft/issues/2391
https://wowpedia.fandom.com/wiki/Doctor_Weavil?oldid=2394019 (September 2010 source)
https://tbc.wowhead.com/npc=15552/doctor-weavil#abilities
-  Tested ingame with 2 characters
> /* Affected rows: 14  Found rows: 0  Warnings: 0  Duration for 3 queries: 0,000 sec. */
1. Apply changes
2. Reload table `.reload smart`
3. Optional 1: Spawn NPC  `.npc add 15552` & Test
4. Optional 2: Restart server & ` .go crea 18614`
**Note**: Mental Domination will not be cast if you are the only entry in the npc's threatlist, hence try with dual-logging if you want to verify this spell being cast
The timer …

fix(DB/SAI): Dr Weavil Abilities

---

data/sql/updates/pending_db_world/rev_1638924855980524100.sql

-  Update Greatmother Hawkwind faction to Thunder Bluff
- Closes #9547
.go c 26610

fix(DB/Creature): Greatmother Hawkwind faction

---

src/common/Dynamic/TypeContainerVisitor.h
src/server/game/Conditions/ConditionMgr.cpp
src/server/game/Conditions/ConditionMgr.h
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerQuest.cpp
src/server/game/Entities/Player/PlayerStorage.cpp
src/server/game/Entities/Player/PlayerUpdates.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h
src/server/game/Groups/Group.cpp
src/server/game/Spells/Auras/SpellAuras.cpp
src/server/game/Spells/Auras/SpellAuras.h
src/server/scripts/Pet/pet_dk.cpp

This reverts commit 85d2c39a48104a7148f3b1142cd8593feaed2c67.
-  Fixes auras not working
-  
- Closes 
- 
- 
1.
2.
3. …

Revert "fix(Core/Spells): Forward core changes (#8841)"

---

src/server/game/Entities/Player/Player.cpp

-  Correct the language and type of the whisper chat hook
- The other chat hooks behave the same way as the corrected one
- Seems that the old code was a copy paste mistake from emote code
- Closes https://github.com/azerothcore/mod-eluna-lua-engine/issues/74
- Builds
- Works
1. You could try make a playerscript that uses whisper hook and then you could check the parameter values that are being passed to the hook. The values should be CHAT_MSG_EMOTE for type and LANG_UNIVERSAL for language which is wrong.
2. Alternatively set up Eluna and AIO and try out the test window script, wich should show up as you log in or as you use .test command https://github.com/Rochet2/AIO/tree/master/Examples/TestWindow The script fails because eluna expects the language to be addon and its hardcoded to be …

fix(Core/ScriptMgr): Correct whisper hook parameters

---

src/server/game/Handlers/CharacterHandler.cpp

-  Remove the prematurely removal of the first login flag
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9663
- 
- 
1.
2.
3. …

fix(Core/Character): Fix OnFirstLogin script hook

---

src/server/game/Scripting/ScriptDefines/CreatureScript.cpp
src/server/game/Scripting/ScriptDefines/GameObjectScript.cpp

-  Revert https://github.com/azerothcore/azerothcore-wotlk/commit/19a3caa5ebd87c4cb689fc8bf2e3fddb26527a14
-  Fix felwood plants, again
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9716
- 
1. Complete fel salve quest/fel wood plants
2. Notice they spawn new plant
1. Talk to random gossip scripted creatures (e.g majordomo executus)
2. Notice they still offer their gossips …

fix(Core/Scripts): Fix QuestRewarded hook

---

apps/ci/mac/ci-compile.sh

- pin macOS ci to use openssl@1.1
- Closes 

fix(CI/MacOS): set openssl to use openssl1.1

---

src/server/game/Handlers/TaxiHandler.cpp

Fixes #9510
- Closes #9510
- Closes https://github.com/chromiecraft/chromiecraft/issues/2472
- Not tested.
.cast 67527
take a flight somewhere …

fix(Core/Movement): Despawn mini pets on flight take.

---

src/server/database/Updater/UpdateFetcher.cpp

chore(Core/Misc): use fallthrough attribute instead of comment

---

src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObject.h

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/b0db728c49f0b70d2c4f18270c389e4445161b7f)
*Add Infinite gameobject check
Co-Authored-By: Kittnz <5845231+kittnz@users.noreply.github.com> …

fix(Core/Object): Add infinite gob check

---

src/server/scripts/Northrend/zone_crystalsong_forest.cpp

refactor(Scripts/Zone): move crystalsong_forest to new system

---

data/sql/updates/pending_db_world/rev_1639488515603583485.sql

According to wowhead and wowpedia the three blackmithing recipes (11614,
11615, 12827) are only lootable from an object so they should be removed
from any creature loot as they can't drop the item.
- https://www.wowhead.com/item=11614/plans-dark-iron-mail
- https://www.wowhead.com/item=11615/plans-dark-iron-shoulders
- https://www.wowhead.com/item=12827/plans-serenity
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9681
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9684
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9685
- Issue description
- Wowhead 
- Wowpedia (e.g. [here](https://wowpedia.fandom.com/wiki/Plans:_Serenity))
- SQL script executes without errors
- Item entries are removed from `creature_loot_template`
1. Execute the SQL …

fix(DB/Loot): Remove incorrect blacksmithing recipe drops

---

data/sql/updates/pending_db_world/rev_1639521847268743300.sql

Creatures affected:
- Ragnaros
- Baron Geddon
- Garr
- Closes #9704 
- Not tested.
1. .go c id 11502 12057 12056
2. .lookup spell Rake
3. .cast #SpellID
4. Confirm non bleed immunity
None …

fix(DB): Remove immunity to bleed effects on Boss

---

data/sql/updates/pending_db_world/rev_1639796637915870500.sql

-  Cherry-picked a bunch of commits of TC.
- Closes #9727
- Closes https://github.com/chromiecraft/chromiecraft/issues/2590
- Tested partially, needed more info.
1. .go c id 16033 and try to recover items with the proper quests.

Fix(DB/Gossip): Added Bodley gossips

---

.github/workflows/docker_build.yml

-  free up additional space for docker builds
- Closes 

fix(CI/Docker): free up additional space

---

src/server/game/Globals/ObjectMgr.cpp

Fixes this issue:
-  Remove empty spell ids from CreatureAddon.auras Vectors
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9763
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9781
- https://github.com/TrinityCore/TrinityCore/commit/f20265feafbf28f722338649740bd11a9e48f2e7
- 
- Builds
- Runs
1. Log into the world
2. Observer no more evil red letters hurting feelings. …

Fix (Core/Creature): Remove empty spell ids from CreatureAddon.auras Vector

---

src/server/game/Globals/ObjectMgr.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Load): Comment continue

---

data/sql/updates/pending_db_world/rev_1640126973356333200.sql

-  Add `MECHANIC_ROOT `flag to Baron Geddon
N/A
-   ❌ Not tested ingame
-   👍  SQL query works 
1. go to Baron Geddon 
2. cast a root spell, such as frost nova
3. see it not being applied and Geddon remains a red sport car
N/A
**For …

fix(DB): Baron Geddon rootable

---

src/server/scripts/Commands/cs_misc.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9842
- 
- 
1.
2.
3. …

fix(Scripts/Commands): fix additem

---

data/sql/updates/db_characters/2021_12_26_00.sql
data/sql/updates/pending_db_characters/rev_1640532476858588300.sql

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(DB/SQL): fix SQL imports

---

data/sql/updates/pending_db_world/rev_1640623438538274991.sql

-  Remove creature_addon causing startup error.

fix(DB) Startup error

---

data/sql/updates/db_world/2021_12_28_01.sql

fix(SQL): Fix broken SQL

---

src/server/game/Scripting/ScriptDefines/GlobalScript.cpp

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9945
- 
1. Create an orc hunter
2.
3. …

fix(Core/Scripting): fix a loop in the affected mod spell hook

---

src/server/game/Entities/Object/ObjectPosSelector.h

attempt to fix the build broken in https://github.com/azerothcore/azerothcore-wotlk/pull/9790

fix(Core/Object): macOS build

---

src/server/game/Entities/Unit/Unit.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Scripting): Solve issue with client crashes on login

---

src/common/Collision/DynamicTree.cpp
src/common/Utilities/Util.cpp
src/server/authserver/Main.cpp
src/server/database/Database/DatabaseWorkerPool.cpp
src/server/database/Database/MySQLConnection.cpp
src/server/game/DungeonFinding/LFGPlayerData.cpp
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Pet/Pet.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Handlers/AuctionHouseHandler.cpp
src/server/game/Handlers/QuestHandler.cpp
src/server/game/Modules/ModuleMgr.cpp
src/server/scripts/Commands/cs_bag.cpp
src/server/scripts/Commands/cs_group.cpp
src/server/scripts/Commands/cs_pet.cpp
src/server/scripts/Commands/cs_send.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_golemagg.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp
src/server/scripts/Northrend/AzjolNerub/AzjolNerub/boss_hadronox.cpp
src/server/scripts/OutdoorPvP/OutdoorPvPZM.cpp
src/server/worldserver/ACSoap/ACSoap.cpp
src/server/worldserver/CommandLine/CliRunnable.cpp

Only 14 days since the last cleanup: https://github.com/azerothcore/azerothcore-wotlk/pull/9767
It's amazing how many new unused imports we have in such a short time.

refactor(Core): remove unused imports

---

data/sql/updates/pending_db_world/rev_1641213986609051100.sql
src/server/game/Spells/SpellMgr.cpp

-  make Grethok use correct arcane missiles spell
-  make Grehtok immune to fear, grip, slow, freeze, interrupts etc
Also made some comments to let the world know the CastingTimeIndex value in ms, maybe unneccesary but done while researching/testing said issue about cast time for mc spell, see issue for more
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9030
https://github.com/azerothcore/azerothcore-wotlk/issues/9030
-  build is fine
- SQL reappliable
1. Go to Grethok with 2 characters, both with `cheat god on`
2 See arcane missiles being channeled
3. Try to interupt him and other CC …

fix(DB): BWL Grethok arcane missiles & immunity flags

---

data/sql/updates/pending_db_world/rev_1640704117328778600.sql
src/server/game/AI/SmartScripts/SmartScript.cpp

- Improved SmartAI for **Lord Kragaru**
- Improved SmartAI for **Sperpent Statue**
- Implemented SmartAI for **Naga Beam** missing gameobject
- Closes not reported issue for quest **Book of the Ancients**
https://youtu.be/eSqgI0skorg?t=289
1. .go gameobject id 177673
2. .additem 15766
3. Use Gameobject to spawn Lord Kragaru
There should be a Beam above the statue and lord Kragaru spawning from the statue.
- Can't despawn the statue because It's not implemented in the core to despawn gameobjects via SmartAI. Changing it would mean breaking other stuff that needs to be corrected with Dynamic Spawn.
Gameobject.cpp::L886 (DespawnOrUnsummon hook)
``` c++
// Respawn is handled by the gameobject itself.
// If we delete it from world, it simply never respawns...
// Uncomment this …
```

fix(DB): Improved Lord Kragaru and gameobjects

---

AUTHORS

chore(AUTHORS): Now it is 2022

---

data/sql/updates/pending_db_world/rev_1641421162754592797.sql
src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp

GAME_EVENT_CHILDEREN_OF_GOLDSHIRE to GAME_EVENT_CHILDREN_OF_GOLDSHIRE
-  GAME_EVENT_CHILDEREN_OF_GOLDSHIRE to GAME_EVENT_CHILDREN_OF_GOLDSHIRE
- Closes Nothing
Spell Check
- Builds
- Performs
1.Spellcheck …

Fix (Core\Script) Grammar Correction

---

data/sql/updates/pending_db_world/rev_1641335115392148600.sql

- Added quest requirements to his quests
- Disabled deprecated quests from vanilla wow
- Closes #8275
- Closes https://github.com/chromiecraft/chromiecraft/issues/1979
The first comment from this database and following videos prove that the first 3 quests should be available, then the 2 elites quest and finally the quest chain that leads to the Undercity.
https://tbc.wowhead.com/quest=6144/the-call-to-command#comments:id=3158426
https://www.youtube.com/watch?v=0pmoJ2pj4pE&t=17s&ab_channel=BloodyFoxGaming
https://www.youtube.com/watch?v=6scsnMguapE&ab_channel=StormblazeGaming
1. .go c id 11878
2. 3 Quests are available from the get-go
3. After completing the 3 quests, 2 more become available
4. After the 2 previous quests are done, another quest chain becomes available. …

fix(DB): Nathanos quest requirements

---

data/sql/updates/pending_db_world/rev_1640706977785890600.sql

- Since these guys have 5 possible gossip options, setting this to 25
each option will equal to 100 percentage.
- There are plenty more gossips like this one only have % of 1 to show
that need to me manually fixed since we don't know how many npc_text
they may have. A query to count the text_x_x and update the according
% should be good to go, however this way is safer.
- Closes #5408
- Not tested
1. .go c id 4429
2. Check for several gossip menus and check different texts.
None. …

fix(DB): Goblin pit crew's gossip probability

---

data/sql/updates/pending_db_world/rev_1641426458023302944.sql
src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp

Scripted Eastvale Peasants to look 99% like official.
Added a missing path, fixed some movement. 
- Closes #5654
Sniff
- Checked Script and path in game
1. .go c 81257

fix(DB/Script): Eastvale Logging Camp, Elywnn Forest

---

src/tools/mmaps_generator/TerrainBuilder.cpp

https://github.com/TrinityCore/TrinityCore/pull/27503
I am the author, so any cross posting licensing issues dont apply.

MMAP: Build ADT floor just like WMO floor below liquid

---

data/sql/updates/pending_db_world/rev_1641503993585656232.sql

-  Fix some bad paths and and some missing
- Closes 
Sniff
1. .go c 4230
2. .go c 5941
3. .go c 4203
4. .go c 4204

fix(DB/Pathing): Darkshire

---

src/server/scripts/EasternKingdoms/zone_ghostlands.cpp

-  Convert script to newer format
- Closes 
Me
- Compiles
1. ,add quest 9212

fix(Core/Scripting): Convert Ranger Lilatha to RegisterCreatureAI

---

src/server/game/Entities/Creature/Creature.cpp

-  Changed chance check to use proper core function.
- Closes 
Core
- Tested in game. Works fine.
1. kill fiends and horrors at Raven Hill with new update.

fix(Core/Dual Spawning) Change rand to roll_chance_f

---

src/server/game/Entities/Creature/Creature.cpp

-  Fixes Cretures evading so we dont have to do 10k worth of water swim adjustments in the ctm
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10113
- Closes most likely alot
- builds
- perform
1. Aggro a creature and run into the water
2. They should no longer evade when you touch water …

fix (Core/CTM) Water Evade Fix

---

data/sql/updates/pending_db_world/rev_1641686782891083700.sql
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Globals/ObjectMgr.h

fix(DB/broadcast_text): align some column names

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_broodlord_lashlayer.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Build): Fallthrough

---

src/server/game/Guilds/Guild.cpp

Fixes #9997
- Closes #9997
- Closes https://github.com/chromiecraft/chromiecraft/issues/2681
- Not tested.
create horde character
.guild create "Test"
.additem 11973
.go ga 20621
.mod mon 10000000
purchase guild bank tab
place item in guild bank …

fix(Core/Packets): Display item suffixes in guild bank packet.

---

src/server/game/Entities/Unit/Unit.h
src/server/scripts/Spells/spell_priest.cpp

Fixes #9980
- Closes #9980
- Closes https://github.com/chromiecraft/chromiecraft/issues/2683
.go creature 80690
.character level <name> 40
Cast Mind Control on target
Cancel Mind Control
Kill target …

fix(Core/Spells): Drop combat on Mind Control cancel.

---

src/server/game/Conditions/ConditionMgr.h
src/server/game/Entities/Object/Object.cpp

-  Implement CONDITION_SOURCE_CREATURE_VISIBILITY, to hide creatures if conditions are not met.
-  
- Closes 
- 
Apply:
```sql
-- Spawn Lady Katrana Prestor
-- Positions are hand-made. There's a huge throne where she used to be spawned in classic...
DELETE FROM `creature` WHERE `guid` = 500800 AND `id1` = 1749;
INSERT INTO `creature` (`guid`, `id1`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES
(500800, 1749, 0, 0, 0, 1, 1, 1, -8435, 335.559, 122.163, 2.56468, 300, 0, 3497, 2568, 0, 0, 0, 0, '', 0);
DELETE FROM `conditions` WHERE …
```

feat(Core/Conditions): Implement CONDITION_SOURCE_CREATURE_VISIBILITY

---

data/sql/updates/pending_db_world/rev_1642438429439298217.sql

-- DB/Misc: Add OldScarletMonastery game_tele and mark mapID 44 as valid
-- Same treatment for OldScarletMonastery as in here for EmeraldDream [#16131](https://github.com/TrinityCore/TrinityCore/issues/16131) which is present in our db as well
- Closes 
Cherry picked by TC Issue https://github.com/TrinityCore/TrinityCore/issues/27626 by @anzz1
- Builds
- Performs
1. .tele OldScarletMonastery
2. welcome to a empty old version of Scarlet Monastery …

Add (DB/Misc): Add OldScarletMonastery

---

data/sql/updates/pending_db_world/rev_1642446176908579800.sql

-  Add repeatable flag to the quests
- Closes #10173
- Closes https://github.com/chromiecraft/chromiecraft/issues/2784
See the issue.

Fix(DB/Quests): The Shadow Guard and The Ice Guard should be repeatable

---

data/sql/updates/pending_db_world/rev_1642322992276769800.sql

Fixes #10086
- Closes #10086
`.event start 7`
`.go gameobject 230` …

DB/Gameobjects: Corrected ground position for Cluster Launchers.

---

src/server/worldserver/worldserver.conf.dist

- Add default logger for all modules

chore(Core/Logging): add default logger for modules

---

data/sql/updates/pending_db_world/rev_1642697456650571700.sql

-  Change DamageModifier to 1, instead of 5
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10266
- Closes https://github.com/chromiecraft/chromiecraft/issues/2820
MangosDB
1. go c id 13022
2. Check the damage. It should be <100 and occasionally (crits or few hits) above that number.

Fix(DB/Creature): Adjustment to Whip Lasher damage

---

apps/ci/ci-pending-sql.sh

-  Make CodeFactor happy
-  
- Closes 
- 
- 
1.
2.
3.

fix(CI/Misc): Make CodeFactor happy

---

src/server/game/Handlers/SpellHandler.cpp

This reverts commit faa4035de7f217730a86eb3657c5c4008a84f18e.
-  Revert this commit until we find another solution :) 
-  CC https://github.com/azerothcore/azerothcore-wotlk/pull/8232 @IntelligentQuantum 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10444
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10443
- Not tested
1. Go to any of the bosses above and test the mechanic, it should work now.

Revert "fix(Core/Spells): Fix spellclick (#8232)"

---

src/common/Utilities/Util.h
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Unit/Unit.h
src/server/game/Movement/Spline/MoveSplineFlag.h

-  Seeing as we use C++17 we don't need to check for >= C++11 :D
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Misc): Remove check for c++11

---

src/server/game/Spells/SpellInfo.h

-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10597
- 
- 
1.
2.
3. …

fix(Core/Spells): Revert an oopsie

---

.github/SECURITY.md

-  Apparently we support it
-  
- Closes 
- 
- 
1.
2.
3.

fix(SECURITY): macOS 11 support

---

src/server/scripts/Events/love_in_air.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Scripts/Events): fix typo

---

src/server/game/Conditions/ConditionMgr.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Commands/cs_npc.cpp
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp

-  in Creature scripts "me" is the pointer to the scripted creature and thus it can be confusing if we define "me" in other places where it isn't needed. …

refactor(Core/Misc): Rename some variables that can be confusing

---

data/sql/updates/pending_db_world/rev_1644514358466639200.sql

-  Move Wildthorn Stalker spawn point above ground
-  Also had to adjust x coordinate slightly as otherwise was inside a tree
- Closes https://github.com/chromiecraft/chromiecraft/issues/3012
- Before (creature is underground)
- After
1. .go creature 34804
2. Creature is above ground …

fix(DB/creature): Wildthorn Stalker under ground

---

data/sql/updates/pending_db_world/rev_1644517852933459100.sql

-  Fix Kwee Q. Peddlefeet to give Lovely Charm Collector's Kits
- Co-authored-by: dr-j
- See TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/67b6f382878ea5d6c41bfe140e8210fbcf14dcc2
- Closes https://github.com/chromiecraft/chromiecraft/issues/3000
https://github.com/TrinityCore/TrinityCore/commit/67b6f382878ea5d6c41bfe140e8210fbcf14dcc2
- Talked to NPC, selected gossip, received kit. Does not require quest. Do not give more items when selecting again due to item is unique.
1. SELECT * FROM creature where id1 in (SELECT entry FROM creature_template where name like '%Kwee Q%');
2. Go to any version of Kwee Q. Peddlefeet
3. Select gossip option
4. Receive kit …

fix(DB): Script Kwee Q. Peddlefeet

---

data/sql/updates/pending_db_world/rev_1644601221468992700.sql

-  Add missing quest markers for several quests in Blood Elf zones
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10567
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10558
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10557
In original issues
1. Add quests mentioned in SQL
2. Go to creatures mentioned in SQL
3. See markers now properly appear …

fix(DB/creature_questitem): Some Missing Quest Markers

---

src/server/scripts/Events/love_in_air.cpp

Fixes #10652
- Closes #10652
- Closes https://github.com/chromiecraft/chromiecraft/issues/3031
- Not tested.
Mount up.
Accept the quest "Pilfering Perfume" (https://wowgaming.altervista.org/aowow/?quest=24656) …

Core/Spells: Crown Parcel Service Uniform should dismount players.

---

data/sql/updates/pending_db_world/rev_1644959483034654993.sql
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp

-  SAI Error Reporting Touch up. Fixes current master build tests.
- fixes sai error reports in the DBerrors.log
- https://github.com/azerothcore/azerothcore-wotlk/pull/10124/ did not break anything, but reporting is touched up
- sql to fix errors in sai table from new reporting\error checks.
- Closes 
- builds
- performs
1. Compile
2. run sql
3. observe no more errors being logged in dberrors.log file …

fix (core\db): SAI Error Reporting

---

src/server/worldserver/worldserver.conf.dist

https://github.com/azerothcore/mod-npc-all-mounts is failing due to its gossip not being made a exception.
-  Since this is a AZ Catelogue NPC module. We add the exception into the conf as default for it to show passing.
- Closes 
- Builds
- Performs
1. Compile Module
2. Observe no errors on world server
3. Testing should pass now. …

Fix (Conf): Add Gossip exemption for AZ Catelogue

---

data/sql/updates/pending_db_world/rev_1645220638173840730.sql

-  Fixing up area to look like official. Still have some scripting to do after packet parser is updated.
- Closes 
sniff
- tested in game. Working
1. .go c 68474

fix(DB/Spawning/Pathing/SAI) Telaar, Nagrand

---

data/sql/updates/pending_db_world/rev_1645226316218841996.sql

-  Many many paths for hellfire. More to come.
- Closes 
sniff
1. .go c 68255
2. do the same for the rest

fix(DB/Pathing) Hellfire Peninsula

---

src/server/game/Events/GameEventMgr.cpp
src/server/game/Scripting/ScriptDefines/GameEventScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Implement a hook called once events are checked (start/stop checks)
-  Needed for https://github.com/Nyeriah/mod-cta-switch …

feat(Scripting/Hooks): Implement OnGameEventCheck() hook

---

data/sql/updates/pending_db_world/rev_1645536335125857423.sql

-  Fix error in a  previous commit.
- Closes 
Official

fix(DB/Creature) Fix an error in PR #10736

---

data/sql/updates/pending_db_world/rev_1644964674105463600.sql

-  Add many missing emotes to Azuremyst Isle quests
-  From TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/d5466ae56332d96e5c7b4d7582841144ae6b170a
- Co-authored-by: [ZenoX92](https://github.com/TrinityCore/TrinityCore/commits?author=ZenoX92)
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/d5466ae56332d96e5c7b4d7582841144ae6b170a
- Spot checked some quests, everything seems good
- Verified that these values were not already in DB
1. Make Draenei character
2. Accept some of these starting quests
3. See more NPC emotes …

fix(DB): Azuremyst Isle Quest Emotes

---

data/sql/updates/pending_db_world/rev_1645638398139044400.sql

-  Add missing pathing to Delmanis the Hated
-  From TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/329fd578ba751f3bee253751bcec16d3decb154f
- Co-authored-by: @[Alastro-Kraken](https://github.com/TrinityCore/TrinityCore/commits?author=Alastro-Kraken)
- Closes issue like https://github.com/TrinityCore/TrinityCore/issues/27656
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/329fd578ba751f3bee253751bcec16d3decb154f
- Followed NPC, moving around correctly
1. .go creature 37068
2. Watch pathing …

fix(DB): Add missing pathing to Delmanis the Hated

---

data/sql/updates/pending_db_world/rev_1645313448111474600.sql

-  Quest Emotes for Horde Feralas Quests
-  Values from TrinityCore
- Only missing values were added
- Co-authored-by: [ZenoX92](https://github.com/TrinityCore/TrinityCore/commits?author=ZenoX92)
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/09559d51de34c2c2e7caa61e05526081a8b88dc6
- Accepted and Completed a few quests, everything seems correct
1. .tele feralas
2. Try some quests, observe emotes …

fix(DB): Horde Feralas Quest Emotes

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Creature/Creature.h
src/server/scripts/Kalimdor/boss_azuregos.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Creature): clean up an unnecessary function

---

data/sql/updates/pending_db_world/rev_1645633842238335100.sql

-  Add missing text for Odesyus' Landing NPCs
-  From TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/676cd425eeffa07f8b2113d1d75e55c2c7e35527
- Co-authored-by: [Alastro-Kraken](https://github.com/Alastro-Kraken)
- Closes issue like https://github.com/TrinityCore/TrinityCore/issues/27659
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/676cd425eeffa07f8b2113d1d75e55c2c7e35527
- Gossip correctly changes with quest status:
1. .go creature 61965
2. Check gossip
3. .quest add 9537
4. .quest complete 9537
5. .quest reward 9537
6. Check that gossip is changed …

fix(DB): Odesyus' Landing Gossip Conditions

---

data/sql/updates/pending_db_world/rev_1646155636640613000.sql

-  I was reviewing most of the missions in the area, noticing that many of their texts were in English, even though I was using a Spanish game client.
-  In the file, you can find most of the horde, alliance and neutral missions of the map. It is not a sniff, but for the moment, it provides a solution to the missions that are untranslated. Later, they can be improved if necessary.
- Closes 
- Each of the missions was tested separately within the game. What I did, was to create a level 80 character, with enough equipment to be able to do them, and I set out to do them. Some of them I completed with the `quest complete` command, but the vast majority of them I did as a player.
1. You should have done the missions currently in the emulator.
2. Then, apply the SQL and notice that many of your …

(DB/Translation) Howling Fjord missions translated into Spanish

---

data/sql/updates/pending_db_world/rev_1646325069714130000.sql

-  Add party that begins quest as target to receive quest credit (target was previously missing)
-  Quest can now be completed
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10864
- Completed quest, now successfully marks as complete when both brothers are killed
- Killing only one brother does not complete quest, as intended
1. .go quest starter 9967
2. Accept quest
3. Defeat enemies
4. Receive credit
I think this should be best way of assign credit only to correct party. There is possibility that if two parties are start this quest at the same time, that credit will not go to first party, but I don't know how Blizz-like way to handle this. I think Blizz may prevent other parties from accept same quest while it is running to avoid this issue, but that I think is a …

fix(DB/Scripts): Fix Ring of Blood Quest Credit

---

data/sql/updates/pending_db_world/rev_1646670856940613800.sql

-  Add the texts of the tables `quest_request_items_locale` and `quest_offer_reward_locale`. As well as some `ObjectiveText` from the `quest_template_locale` table that are untranslated.
- Closes 
- The tests were made inside the game, executing one by one the SQL queries, which I have them in separate files, but I put them together, all in one file, to make it easier to apply and test.
- At the time of executing the queries, both separately and as a whole, none of them presented conflicts.
1. If you take missions from that area, in the alliance faction, you will notice, with the client in Spanish, that many of the texts mentioned are untranslated.
2. You apply the SQL, delete the game client cache folder, and enter to test the quests (of the alliance only for the moment). The others are …

(DB/Translations) Alliance quests in Grizzly Hills

---

data/sql/updates/pending_db_world/rev_1646669713670945917.sql

- Fix issue of Grimclaw  "Skyhopping"/"flying" on his pathing RolePlay (RP)
- added missing way points.
- adjusted smart scripts and action scripts with new waypoint adjustments
- Closes https://github.com/chromiecraft/chromiecraft/issues/2882
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10925
Sniff
- builds
- performs
1. .mod speed 5
2. .go c 37101
3. stalk npc and observe no sky hopping\flying.  …

fix (DB): Grimclaw NPC Mini RP event

---

src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp

Fixes #10877
- Closes #10877
- Not tested.
1.talk Lore Keeper of Norgannon(id 33686) and Brann Bronzebeard(id 33579)
2.Fight Flame Leviathan …

fix(Scripts/Ulduar): Fixed launching Leviathan's hard mode.

---

data/sql/updates/pending_db_world/rev_1646883386946549000.sql

-  Set the movement type to 0 as there is no waypoint attached to the creature. (if it should have one, modify it again when adding the waypoints).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10938
1. Run the sql
2. Go to Blackwing Lair
3. See if worldserver showed any error.

fix(DB/BWL): Blackwing Taskmaster path error

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp

Co-authored-by: 天鹿 <pklloveyou@users.noreply.github.com>
-  Added different reset scenarios.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10951
1. Go to BWL
2. Talk to Victor Nefarius
3. Engage and wipe while Nefarian is still flying, and also wipe after killing Nefarian but with adds alive.

fix(Core/BWL): Nefarian reset behaviour

---

src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp

-  Make Shade of Eranikus unattackable until Jammal'an the Prophet is killed
https://wowpedia.fandom.com/wiki/Shade_of_Eranikus#mw-content-text:~:text=In%20order%20to%20fight%20Eranikus%2C%20you%20must%20first%20defeat%20Jammal'an%20the%20Prophet.
https://classic.wowhead.com/npc=5709/shade-of-eranikus#comments:id=2801069:~:text=The%20reason%20why%20he%20is%20immune,is%20how%20you%20wake%20the%20dragon.&text=To%20get%20this%20fight%20you%20need,are%20keeping%20jammal's%20green%20wall%20up.
- Teleported to boss, now unattackable as intended, killed Jammal'al, then boss is attackable and instance can be complete
1. .go creature 39842
2. See is unselectable
3. Go kill Jammal'al
4. Shade of Eranikus can now be killed
Hopefully this is not upset too many player that …

fix(Scripts/Sunken Temple): Fix Shade of Eranikus

---

data/sql/updates/pending_db_world/rev_1646152616244410200.sql

-  Add gossip logic to restore missing totem if destroyed
-  Original issue was for Alliance version, Horde version was also missing so is also added
- Closes https://github.com/chromiecraft/chromiecraft/issues/3141
1. .quest add 14111 or 14100
2. .quest complete (same quest)
3. .go quest ender (same quest)
4. Complete quest
5. Destroy totem
6. See new gossip option
The only spell that creates this item in the spell_dbc is the original version that requires reagents, so I believe adding item directly like this is correct logic.
I am not sure that this is the correct broadcast text for the gossip option, but I chose the one that looked correct. Please change if you can find another correct text! …

fix(DB): Gossip Option to Restore Missing Totem

---

src/server/game/DataStores/M2Stores.cpp

fix (core) typo fix

---

data/sql/updates/pending_db_world/rev_1647185908361212000.sql
src/server/scripts/Spells/spell_generic.cpp

Fixes #10994
- Closes #10994
- Not tested.
Enter Alterac Vallay as an Alliance
Go the main bunker and see you buff list …

fix(Scripts/Spells): Icewing Marshal should affect not affect players.

---

data/sql/updates/pending_db_world/rev_1647107378248226200.sql

Fixed #10944
- Closes #10944
1.quest add 12969
2.go c id 30154
3.talk it …

fix(DB/SAI): Fixed setting faction to Agnetta Tyrsdottar.

---

data/sql/updates/pending_db_world/rev_1647134885721287500.sql

-  Fix conditions for the quest to be available
-  Quest available before u complete any of pre-quests(2997,2999,3000) and not available after u complete any of them.
- Closes [Tome Of Divinity - Dwarf Paladin #3196](https://github.com/chromiecraft/chromiecraft/issues/3196)
- Completed pre-quest(2997 or 2999 or 3000) and got next quest  [The Tomb of Divinity](https://classic.wowhead.com/quest=1645/the-tome-of-divinity)
- 
1. Accept quest [Tome of Divinity](https://classic.wowhead.com/quest=2999/tome-of-divinity) (Level 12 Dwarf Paladin req.)
2. Complete quest at [Tiza Battleforge](https://classic.wowhead.com/npc=6179/tiza-battleforge)
3. She should have quest available to you. [The Tome of Divinity](https://classic.wowhead.com/quest=1645/the-tome-of-divinity) …

fix(DB/conditions): Fix Quest: The Tome of Divinity

---

data/sql/updates/pending_db_world/rev_1647387221217292000.sql

-  Update missing gossip flag for npc
- Closes [Quest: The Stone Watcher - bugged! #2899](https://github.com/chromiecraft/chromiecraft/issues/2899)
https://www.youtube.com/watch?v=bONxXSBNSAo
https://www.youtube.com/watch?v=3XVRWi2SJkA
- Added quest [Seeing What Happens](https://classic.wowhead.com/quest=2946/seeing-what-happens) (.q add 2946). 
- Submitted quest and NPC spawns and gives u another quest [The Stone Watcher](https://classic.wowhead.com/quest=2954/the-stone-watcher)
-  Accepted quest and clicked trough gossips and finished quest after that.
1. Add quest (.q add 2946)
2. Submit and wait for NPC to spawn. Accept next quest [The Stone Watcher](https://classic.wowhead.com/quest=2954/the-stone-watcher) from NPC.
3. Click trough NPCs gossips and complete quest.
Peoples who already …

fix(DB/SAI) Fix Quest: The Stone Watcher

---

data/sql/updates/pending_db_world/rev_1647384955185295290.sql

Taken from TrinityCore/commit/9f7cd3aa13636b9fe774a04063842611cab8b556
(Part 189) …

fix(DB/Locale): Add missing esES & esMX quest texts 

---

data/sql/updates/pending_db_world/rev_1647385217273847981.sql

Taken from TrinityCore/commit/b645cb7fde0caf3f80d4d4cfb3b88d804907f2cd
(Part 190) …

fix(DB/Locale): Add missing esES & esMX quest texts

---

data/sql/updates/pending_db_world/rev_1647391921098550500.sql

-  Set correct target for quest credit
- Closes [[Class quest][Rogue] 20 - The touch of Zanzil (Alliance) - Quest doesn't complete #2978](https://github.com/chromiecraft/chromiecraft/issues/2978)
https://www.youtube.com/watch?v=ZlT8nE_HwQo
- Accepted quest. Laid down. Gnome finished his walking and gave quest credit. Complete quest.
1. Be a Dwarf Rogue Level 20. Follow the quest chain start from [Mathias and the Defias](https://classic.wowhead.com/quest=2360/mathias-and-the-defias) (.q add 2360)
2. Get to quest [The Touch of Zanzil](https://classic.wowhead.com/quest=2608/the-touch-of-zanzil)
3. Start quest. Lay down wait until gnome finished walking and gives u quest credit.
4. Complete quest.
- According to video there is some delays while he walking around and there is some phrases …

fix(DB/smart_scripts) Fix Quest: The Touch of Zanzil

---

src/server/game/Instances/InstanceSaveMgr.cpp
src/server/game/Instances/InstanceSaveMgr.h
src/server/game/Maps/Map.cpp

Fixes #10965
- Closes #10965
- Not tested.
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/10965) …

fix(Core): Crashfix.

---

data/sql/updates/pending_db_world/rev_1643931984499831200.sql

-  Fix Blood Elf Mage Trainers to not use Blood Elf Hunter gossip
- Taken from TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/163e4c9eaba8c88f60979b84ee2be57be8bd6580
- Same issue as https://github.com/TrinityCore/TrinityCore/issues/27679
https://github.com/TrinityCore/TrinityCore/issues/27679
- Before:
- After:
1. .go creature 54985 with Mage
2. No longer act like a hunter …

fix(DB): Blood Elf Mage Trainers Incorrect Dialog

---

data/sql/updates/pending_db_world/rev_1647208425086920700.sql

-  Fix Crown Hoodlum(38006) and Crown Duster(37984) level.
- Closes[ [Love is in the Air / Dustwallow Marsh] Crown Hoodlum are level 1. #3070](https://github.com/chromiecraft/chromiecraft/issues/3070)
- Started event [Love is in the Air], added both quests [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24648) and [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24647), gone to creatures and they are both right level and not level 1.
1. Add quests ( .q add 24647, .q add 24647)
2. Start event (.event start 8)
3. Go to creatures Duster(.go creature 244621) and Hoodlum(.go creature 244616)
4. Duster should be Level 25-26, Hoodlum 33-34 …

fix(DB/creature_template): Fix Creatures Level

---

data/sql/updates/pending_db_world/rev_1647791446104793800.sql

Fixes #10998
- Closes #10998
- Closes chromiecraft/chromiecraft/issues/3193
`.go creature id 10184`
Aggro Onyxia and see her movement. …

fix(DB/Creatures): Control Onyxia's movement flags via script.

---

data/sql/updates/pending_db_world/rev_1648306734434273023.sql

-  Reduced drop rate of several BoE items to be more reasonable (several items had 2 or 3 times the expected drop rate)
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/10766
- Closes https://github.com/chromiecraft/chromiecraft/issues/2946
vmangos
- 
-  not tested
1. Go to BWL in the room after Broodlord Lashlayer
2. Kill all trash there and notice BoE drop rates are less
Or check Keira ;) …

fix (DB/Creature): BWL trash boe drop adjustment

---

data/sql/updates/pending_db_world/rev_1648309713111396700.sql

Corrected spawn positions
Death Talon Hatcher should patrolling the room.
Fixes #10941
- Closes #10941
- Not tested.
.go xyz -7579.5917 -980.4238 442 469
Look the situation in the supression room …

fix(DB/Spawns): Some improvements to Death Talon Hatcher spawns:

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp

Fixes #9423
Fixes #11138
- Closes #9423
- Closes #11138
- Closes https://github.com/chromiecraft/chromiecraft/issues/2433
- Closes https://github.com/chromiecraft/chromiecraft/issues/3221
About Hand of Justice:
Be on 59 lvl
`.aura 15600`
Make a stopattack macro for an ability (/cast crusader strike /stopattack) so you don't auto attack. You'll see the trinket not proccing.
About Sword Spec:
.`aura 12815`
Use some yellow ability (e.g. Mortal Strike or Slam).
In both situations, you'll get extra attack from yellow attack. …

fix(Core/Combat): Improved extra attacks handling. Author: @trickerer

---

modules/CMakeLists.txt

- Fixes the build when using the merged Eluna module named as `mod-eluna`
- Fixes https://github.com/azerothcore/Eluna/pull/29#issuecomment-1079785377
- Built locally (Windows 10 64bits) …

fix(modules/CMakeLists): new Eluna module name

---

data/sql/updates/pending_db_world/rev_1648398529574716400.sql

-  Players that completed the drakefire amulet quest chain should be able to ask their respective npcs for a retrieval in case they deleted the items
-  Alliance quest side was removed but the horde is still available as wrath of the lich king
- Closes https://github.com/azerothcore/mod-progression-system/issues/196
- 
1. .go creature 10929
2. quest reward & complete 6602
3. destroy your amulet
4. talk to npc, get a new one …

fix(DB/SAI): Haleh & Rokaro Drakefire Amulet retrieval gossips

---

src/server/game/Spells/Spell.cpp

-  These are not errors, just debug outputs.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11193 …

fix(Core/Misc): Update some log errors to debug

---

data/sql/updates/pending_db_world/rev_1648266327758563400.sql
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp

- Although I am writing the pull request, the ideas and authorship belong to Mr. @Nefertumm. I only made the tests.
-  Currently, in the last phase of the lich king boss, when it reaches 10%, after the terenas king revives you, the npc constantly regenerates his health, which makes him never finish the fight.
- https://github.com/azerothcore/azerothcore-wotlk/issues/10821
- The tests were performed on a Windows 10 operating system. Although I was alone in the raid, it would be interesting if someone can test it, with other people. (but I don't think it will change too much)
1. Go to the citadel: `.tele IcecrownCitadelRaid`
2. Eliminate the previous bosses beforehand
3. Perform the fight and you will be able to finish it normally. …

fix(Scripts/Icecrown): ICC Lich king does not evade 10% of health

---

data/sql/updates/pending_db_world/rev_1647830174089422864.sql
src/server/worldserver/worldserver.conf.dist

-  fix interraction with Light and Dark Essences
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10807
-  Now it works
1. Start challenge, kill bosses until Val'cyr's phase
2. Speak with Barrett Ramsey and start next challenge
3. Once Essences will appear - click on them …

fix (DB/creature_template): fix interraction with Light and Dark Essences

---

data/sql/updates/pending_db_world/rev_1648290893075572700.sql
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp

Fixes #11140
- Closes #11140
- Not tested.
1.Enter P2 phase
2.click 'Descend Into Madness' …

fix(Scripts/Ulduar): Yogg-Saron portals should be interactable.

---

data/sql/updates/pending_db_world/rev_1648075927512739900.sql

-  Fix multiple barrel spawns 
- Closes #10829 
- Close [#2981](https://github.com/chromiecraft/chromiecraft/issues/2981)
https://youtu.be/EElKpo1mu6U?t=302
- .go gameobject 1037
- .quest add 310
- .additem 2686
- Hand in item to Jarven Thunderbrew in the room 
- Guarded Barrel De-spawns, Unguarded Barrel Spawns(vice versa when NPC returns)
1. `.go gameobject 1037`
2. `.quest add 310`
3. ` .additem 2686`
4.  Hand in item to Jarven Thunderbrew in the room 
5. Observe barrel (Guarded Barrel De-spawns, Unguarded Barrel Spawns(vice versa when NPC returns)) …

fix(DB/SAI): Multiple barrel spawns

---

data/sql/updates/pending_db_world/rev_1647992044021568600.sql

-  Fix dialogue when player doesn't have Herbalism skill.
- Closes #10663 
- Closes [#3026](https://github.com/chromiecraft/chromiecraft/issues/3026)
https://www.youtube.com/watch?v=D71ahIQegnM&t=40s
https://youtu.be/wdJ0m6e7jZo?t=22
-  Checked welcome message when u have don't have Herbalism and when u obtain it.
1. `.go creature 79825`
2. Talk to Tannysa when u don't have Herbalism: `I hope that your interruption is for a good cause, I was in the middle of some important work.`
3. Talk to Tannysa when u  have Herbalism: `Another Herbalist, hmm. I doubt your skill is as great as my own so perhaps I can train you in a few proper techniques.` …

fix(DB/conditions): Missing conditions for trainer gossip

---

src/server/game/Spells/Spell.cpp

Fixes #11186
- Closes #11186
Cast a spell that requires runes
Check whether the rune energy bar changes …

fix(Core/Spells): Fixed displaying runes cooldowns.

---

data/sql/updates/pending_db_world/rev_1648456139839620175.sql

feat(DB): assign BroadcastText to creature_text (Night Elf Commoner)

---

data/sql/updates/pending_db_world/rev_1648570617646721492.sql

Taken from TrinityCore/commit/d75ae769b5d44664053804cbbb3132710976b665

feat(DB/Locale): Add some missing ruRU quest texts

---

data/sql/updates/pending_db_world/rev_1648455947142163675.sql

Taken from TrinityCore/commit/404e74ebe1ba08b2011b4755b955b781a64dfba7

feat(DB/Locale): Add missing esES & esMX quest texts

---

src/server/game/AI/CreatureAI.cpp
src/server/game/Entities/Creature/Creature.cpp

Fixes #8167
- Closes #8167
- Not tested.
1.go c 137630
2.Start combat
3.Use teleport command or hearthstone(and Divine Shield) to get out Ulduar
4.Now you can enter Ulduar …

fix(Core/Creatures): Properly reset encounter if boss despawns on evade.

---

data/sql/updates/pending_db_world/rev_1648209216423577919.sql

ICC - Lich King for Valithria Dreamwalker
- Tested. Text shown according to client localization 
1. Pass ICC to boss Valitria Dreamwalker and start fight.
2. Leech King's shout must be shown localized …

fix (DB/creature_text): add missed BroadcastTextID

---

src/server/game/Handlers/TaxiHandler.cpp

-  Additional Teleport helper placements.
- Closes 
- Builds
- Performs
1. These are additional Helpers for Module Support …

Add (core) Additional Teleport Helpers

---

src/server/game/Battlegrounds/Battleground.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Entities/Player/PlayerMisc.cpp
src/server/game/Entities/Player/PlayerStorage.cpp
src/server/game/Entities/Player/PlayerUpdates.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Groups/Group.cpp
src/server/game/Handlers/CharacterHandler.cpp
src/server/game/Handlers/GroupHandler.cpp
src/server/game/Handlers/MiscHandler.cpp
src/server/game/Handlers/MovementHandler.cpp
src/server/game/Handlers/SpellHandler.cpp
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/game/Spells/Spell.cpp
src/server/game/Spells/SpellEffects.cpp
src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp
src/server/scripts/World/npcs_special.cpp

-  Helpers =)
```cpp
PlayerFlags GetPlayerFlags() const { return PlayerFlags(GetUInt32Value(PLAYER_FLAGS)); }
bool HasPlayerFlag(PlayerFlags flags) const { return HasFlag(PLAYER_FLAGS, flags) != 0; }
void SetPlayerFlag(PlayerFlags flags) { SetFlag(PLAYER_FLAGS, flags); }
void RemovePlayerFlag(PlayerFlags flags) { RemoveFlag(PLAYER_FLAGS, flags); }
void ReplaceAllPlayerFlags(PlayerFlags flags) { SetUInt32Value(PLAYER_FLAGS, flags); }
```
- Closes 
- 
- 
1.
2.
3. …

feat(Core/Players): PlayerFlag helpers

---

data/sql/updates/pending_db_world/rev_1648972434572977796.sql

Fixed ruRU title of npc Lhara (Darkmoon Faire Exotic Goods)

fix(DB/creature_template_locale): npc 14846 Title ruRU

---

data/sql/updates/pending_db_world/rev_1649122676928024300.sql

-  Added flags_extra.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11285
- Not tested.
1. Go to Chromaggus with 2 chars.
2. Aggro
3. Try to taunt the boss with the other char.
4. Should be immune.

fix(DB/BWL): Chromaggus should be taunt immune

---

data/sql/updates/pending_db_world/rev_1648996451912542300.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_broodlord_lashlayer.cpp

Fixes #11249
- Closes #11249
- Not tested.
Go to suppression with a rogue
Go in stealth
You should not be hit by a suppression device. …

Scripts/Spells: Suppression Aura should not hit stealthed units.

---

data/sql/updates/pending_db_world/rev_1644428839091658700.sql
src/server/scripts/Spells/spell_item.cpp

-  Script was existing but missing malfunction explosion chance and was not assigned correctly
- Some NPC values were incorrect; these are now fixed
- All values are from TrinityCore: https://github.com/TrinityCore/TrinityCore/pull/27749
TrinityCore: https://github.com/TrinityCore/TrinityCore/pull/27749
Summon appears:
Attacks nearest target, explodes then dies:
Malfunction Explosion working:
1. .additem 10587
2. Test if it is working …

fix(Scripts/Items): Fix Goblin Bomb Dispenser

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp

-  Make the class selection uniform.
-  Extend the class call filter to all the spell effects, this was causing some weird behaviours.
- Closes 
- Not tested. Only built.
1. Go to Nefarian with different classes (example: 2 hunters and 1 mage) and make sure the chances of getting a class call is the same for every class present (on the example before, hunters should have a chance of 50% instead of 66%)
2. Check that the effects are not applied to another class. …

fix(Core/BWL): Nefarian class call spells

---

src/server/scripts/Pet/pet_dk.cpp

-  Fix gargoyle's dmg
- Closes #11387 
- Tested and work
1.
2.
3.

Fix (Dk pet/Spell): Gargoyle's damage

---

apps/ci/ci-install-modules.sh

fix(CI): Fuck eluna

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/BlackwingLair): Improve Nefarian's add animations

---

data/sql/updates/pending_db_world/rev_1649944595674185734.sql
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h
src/server/game/Combat/ThreatMgr.cpp
src/server/game/Combat/ThreatMgr.h
src/server/game/Entities/Unit/Unit.cpp
src/server/scripts/Commands/cs_debug.cpp
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp

-  Corrects Hostil to Hostile
- Closes 
Auto-Correct\Spell Check\Webster Dictionary Online
- Builds
- Performs
1. spelling correction. no need to really test but does effect the .debug hostil gm cmd that is now .debug hostile
**For …

Fix (Core\DB) Hostil to Hostile spelling fix

---

data/sql/updates/pending_db_world/rev_1649704204212585721.sql

-  Add esES, esMX, ruRU, koKR, zhCN, frFR translations
- Closes #11369
- Closes https://github.com/chromiecraft/chromiecraft/issues/3332
https://es.classic.wowhead.com/item=13873/llave-de-la-sala-de-visi%C3%B3n
- Tested 🐼 
Use esES/esMX WoW Client
.add 13873 …

fix(DB/item_template_locale): 'Viewing Room Key' translations

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/BlackwingLair): Prevent Nefarian's adds corpse from decaying

---

data/sql/updates/pending_db_world/rev_1644537932629642900.sql

-  Fix Renn McGill Gossip to provide the player with Repaired Diving Gear
- Closes https://github.com/chromiecraft/chromiecraft/issues/3015
https://www.youtube.com/watch?v=bOG-sDuYhd0
- Talked with NPC, selected gossip option, received Helmet
1. .go creature 18595
2. Select gossip option
3. Receive helmet …

fix(DB): Renn McGill Gossip Option

---

src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp

Fixes #11314
- Closes #11314
- Not tested.
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/11314) …

fix(Scripts/Ulduar): Fixed console errors of uninstalling vehicles.

---

src/server/game/AI/SmartScripts/SmartScript.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

FIX Server crash

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Spell.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

Feat: (core) Additional Helper

---

src/server/game/Spells/Spell.cpp

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/6785
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/Spell): Move SelectTrajTarget log to Debug

---

src/server/game/Entities/Unit/Unit.cpp

Anticheat helper
-  
-  
- Closes 
- 
- 
1.
2.
3.

feat (core): another helper implemented

---

src/common/Collision/Management/MMapFactory.cpp
src/common/Utilities/Util.cpp
src/server/game/AI/CreatureAISelector.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h
src/server/game/Entities/Item/Item.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/PlayerStorage.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/Handlers/MovementHandler.cpp
src/server/game/Handlers/TradeHandler.cpp
src/server/game/Maps/Map.cpp
src/server/game/Maps/MapMgr.cpp
src/server/game/Maps/TransportMgr.cpp
src/server/game/Misc/GameGraveyard.cpp
src/server/game/Movement/MotionMaster.cpp
src/server/game/Server/WorldSession.cpp
src/server/game/Spells/Auras/SpellAuraEffects.cpp
src/server/scripts/Commands/cs_debug.cpp
src/server/scripts/EasternKingdoms/Scholomance/boss_darkmaster_gandling.cpp
src/server/scripts/Outland/zone_netherstorm.cpp
src/server/worldserver/Main.cpp
src/tools/mmaps_generator/TerrainBuilder.cpp

-  cleanup
-  
- Closes 
- 
- 
1.
2.nothing to test
3.

chore(Core/Misc): nullptr cleanup

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Spells/Spell.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix (core): Null check the helpers

---

src/server/game/Spells/SpellEffects.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

add (core): additional helper for jump destination

---

data/sql/updates/pending_db_world/rev_1650022301338957500.sql

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/7273
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7273
- 
- 
1.
2.
3. …

fix(DB/Quest): Corruption of Earth and Seed faction exclusive

---

src/server/game/AI/CreatureAI.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/CreatureAI): improve log

---

data/sql/updates/pending_db_world/rev_1650152443729183400.sql

-  Correct Gossips for different reputation rank.
- Closes #11304 
-  Closes [#3303](https://github.com/chromiecraft/chromiecraft/issues/3303)
https://wowpedia.fandom.com/wiki/Master_Smith_Burninate
- Checked trough different reputation rank now shows correct gossips.
.mod rep 59 3000 - Set Friendly
.mod rep 59 9000 - Set Honored
.mod rep 59 21000 - Set Revered
.mod rep 59 43000 - Set Exalted
for easy testing
1.`.go c id 14624` 
2. If quest [What The Flux? ](https://classic.wowhead.com/quest=7722) rewarded u get gossip (`Burninate's the name, smithin's my game... and, erm... I sell a little food and water on the side. Care for some meat?`) and quests if not complete it's standart greeting and  [What The Flux? ](https://classic.wowhead.com/quest=7722) quest.
3. Complete  [What The Flux? …

fix (DB/conditions): Correct gossip display for Master Smith

---

data/sql/updates/pending_db_world/rev_1648560789862497357.sql

feat(DB/Locale): Entry 190671 deDE

---

data/sql/updates/pending_db_world/rev_1650603437547310423.sql

-  To fix Behsten so you can talk to him to freeze/unfreeze XP on Alliance Side.   Slahtz for Horde was working so this modifies Behsten's entry 35365 in Creature_template to replace gossip_menu_id from 0 to 10638 and npcflag from 0 to 1 like Slahtz.
- Didn't see this issue posted.
Nothing to add here.  easy one liner for MySQL.
- Tested on Windows with a Visual c++ build of Azerothcore and script was imported in MySql.
1. Before applying this fix, try to talk to Behsten in a room behind the King in Stormwind Keep.  You'll notice that you cannot interact with him at all.  So no XP freeze for Alliance.
2. If you import manually the sql file to test, make sure you have your worldserver shutdown first.  Dont try to apply the .sql file with the server online because Behsten will not work …

fix(DB/Creature_template): Fix Behsten XP freeze for Alliance

---

data/sql/updates/pending_db_world/rev_1650635071075389545.sql

https://github.com/azerothcore/azerothcore-wotlk/issues/11473
-  fix Z axis
- Closes #11473 
- Tested IG
1. .go xyz 2319.13 1614.74 38.17 …

fix(DB/Creature) Scarlet Warrior position

---

data/sql/updates/pending_db_world/rev_1648483014206486262.sql

TrinityCore#22294
fix of the translations, currently has those of Cataclysm,

feat(DB/Locale): Zul'jin

---

data/sql/updates/pending_db_world/rev_1648565976022955594.sql

feat(DB/Locale): Entry 12698,12701,12722

---

data/sql/updates/pending_db_world/rev_1648484936302537243.sql

TrinityCore/commit/cbdb0606eb4988b62ca006e43c21a57de4a3777a

feat(DB/Locales): Risen Ghoul (DK)

---

data/sql/updates/pending_db_world/rev_1650033460420476500.sql
src/server/game/Spells/SpellInfoCorrections.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Core/Spells): Custom attributes belong in the DB

---

src/server/database/Database/DatabaseWorkerPool.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

chore(Core/Misc): Improve wiki link in database error

---

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp

-  Remove requirement
-  
- Closes 
Retail, gate is open, Chromaggus can be pulled normally, they're optional
- 
1.
2.
3. …

fix(Scripts/BlackwingLair): Three drake bosses should be optional

---

src/server/game/Maps/Map.cpp

-  Correct water adjustment with liquad data and GetFullTerrainStatusForPosition 
- Closes 
- Builds 
- Performs
1.
2.
3. …

fix (core): Water Calculation Corrections

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp

Fixes #11368
- Closes #11368
- Not tested.
Nothing to be tested - it's hard to replicate. …

fix(Core): Restored code about shared visions removed in d504a62.

---

apps/installer/includes/functions.sh

this PR follows https://github.com/azerothcore/azerothcore-wotlk/pull/10974
-  update ac data version of the dashboard

chore: update ac data version

---

src/server/scripts/Spells/spell_generic.cpp

-  
-  
- Closes 
- 
- 
1.
2.
3.

fix(Scripts/Spells): Validate some spells in spell_generic

---

src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp
src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp

Fixes #11439
- Closes #11439
go icc any mode
go fight with sindragosa
wait for fly phase …

fix(Scripts/IcecrownCitadel): Increases radius of Sindragosa's boundary.

---

src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp

Fixes #9254
- Closes #9254
- Closes https://github.com/chromiecraft/chromiecraft/issues/2355
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9254), [here](https://github.com/chromiecraft/chromiecraft/issues/2562) and [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9290) …

fix(Core/Movement): Improved pet's follow movement.

---

data/sql/updates/pending_db_world/rev_1651251117611496925.sql

-  Set Prince Thunderaan's summon duration to 1 hour (so his corpse despawns after 1 hour)
-  
- Closes players unable to proceed with Thunderfury quest due to thunderaan disappearing / corpse disappearing.
- Closes: https://github.com/chromiecraft/chromiecraft/issues/3431
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/11573
Videos showing THunderaan being tagged all the way to Orgrimmar.  https://www.youtube.com/watch?v=brk1tpXWmnY
Players should not be locked of looting him due to low timer
- Tested
- 
1. .quest add 7786
2. .quest complete 7786
3. Hand in quest and see if Thunderaan disappears after 60 seconds after kill …

Fix(DB/SmartScript): Prince Thunderaan corpse should despawn after 1 hour.

---

src/server/game/Entities/Creature/TemporarySummon.cpp

Core: Crashfix.

---

src/server/game/Maps/Map.cpp

-  We do not need to excessively have ground level be -2 below the player when underwater. ground level is ground level. no need for a lower adjustment. Most likely left over from from when the shallow water calculations was wrong entirely that lead to false hits with water walking detection due to core side calculations.
-  There is No Noticible Game Play Changes. This deals with strictly numbers and measurement calculations with the anticheat module which relies on core handling.
- Closes 
- Builds without errors
- Tested with the anticheat dev crew which resulting in much sensible and accurate detection with water walking and ignore z-axis hack detection
- Windows 11
1. compile with anticheat module
2. perform a z-ignore hack or water hack in slightly deeper then shallow water
3. …

fix (core): water level and ground level correction

---

data/sql/updates/pending_db_world/rev_1651542266671948700.sql
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp

-  Fixes gate closing right away
-  
- Closes 
- 
1. Pull lever, pull chromaggus - gate doesn't close
2. kill chromaggus, gate to nefarian opens
3. pull nefarian, gate to nefarian closes …

fix(Scripts/BlackwingLair): Prevent Chromaggus cage from locking up

---

data/sql/updates/pending_db_world/rev_1651694260487289884.sql

-  Update creature template with proper gossip id.
- Add missing gossip text.
- Add missing conditions.
- Closes #11484
TC
1. .go c 40428
2. talk to npc
3. do quest 5202
4. talk to npc
5. do quest 5203
6. talk to npc
7. observe 3 different gossip text

Fix (DB/Gossip/Conditions) Captured Arko'narin

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Scripting/ScriptDefines/AllCreatureScript.cpp
src/server/game/Scripting/ScriptDefines/AllGameObjectScript.cpp
src/server/game/Scripting/ScriptMgr.h

-  Add OnCreatureSaveToDB Hook and OnGameObjectSaveToDB Hook
- Does it build without errors? Yes
- Did you test in-game? yes (with Objscale: https://github.com/Tralenor/mod-objscale)
- On which OS did you test? Windows
- Describe any other tests performed: compiled with -DUSE_COREPCH=0 & -DUSE_SCRIPTPCH=0
1. use the new Hooks in any Module
2.
3. …

Add Hooks On creature/game object save to db

---

src/server/game/AI/CoreAI/UnitAI.cpp
src/server/game/AI/CoreAI/UnitAI.h

- SpellCastResult
- Closes 
- none
- 
1. Just check that any creature that is scripted and casts spells, casts spells …

refactor(Core/Spells): make DoCast functions use SpellCastResult

---

src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp

Will do more of https://github.com/azerothcore/azerothcore-wotlk/projects/15 in separate PRs, good practice
-  
-  
- Closes #4158
- Tested in-game, with sound (just to be sure)
- 
1. .go c 137581 
2. Pull (with sound enabled)
3.
**For …

fix(Core/Creature): Move hardcoded text/gossips to DB - boss_general_vezax 

---

data/sql/updates/pending_db_world/rev_1651752894543472300.sql

-  Removed the item Cache of Zanzil's Altered Mixture (8073) from Grand Foreman Puzik Gallywix (7288)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11361
Multiple comment on [Wowhead](https://classic.wowhead.com/quest=2478/mission-possible-but-not-probable#comments) that say that you have to loot the lockbox to obtain [Cache of Zanzil's Altered Mixture].
The quest also give the info pretty clear: 
Assassinate Grand Foreman Gallywix and take his head, then pick the lock on Gallywix's lockbox and steal the [Cache of Zanzil's Altered Mixture](https://classic.wowhead.com/item=8073/cache-of-zanzils-altered-mixture). Take the Cache and [Gallywix's Head](https://classic.wowhead.com/item=8074/gallywixs-head) back to [Shenthul](https://classic.wowhead.com/npc=3401/shenthul) in …

fix(DB/Loot): Removed Cache of Zanzil from Grand Foreman Puzik Gallywix

---

data/sql/updates/pending_db_world/rev_1651862669936324646.sql

-  Add random hiccup text and drink emote. 
-  Add missing script for quest 1452 "Rhapsody's Kalimdor Kocktail" reward.
- Closes #11454
Sniff
- Inserts
1. .go c 92848
2. .quest add 1452
3. .quest complete 1452
4. turn in quest

Fix(DB/SAI/Quest) Rhapsody's Kalimdor Kocktail quest script

---

data/sql/updates/pending_db_world/rev_1651915141793572500.sql
src/server/game/Spells/SpellInfoCorrections.cpp

Fixes #11637
- Closes #11637
.quest a 13010
.go xyz 7345.899902 -2812.949951 798.488281 571
summon a mount
talk to King Jokkum(creature id 30105) …

fix(DB/Quest): Krolmir, Hammer of Storms.

---

src/server/game/Handlers/ItemHandler.cpp

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/d0b8fb87f29c6fe5a100c4f1f85cad2b349d9619)
Co-Authored-By: okfok <44704482+okfok@users.noreply.github.com>
-  Make it impossible to sell items if it will cause exceeding gold limit
-  
- Closes 
- 
- 
1.
2.
3. …

fix(Core/ItemHandler): fix selling items over gold limit

---

data/sql/updates/pending_db_world/rev_1652024996795453900.sql

* closes https://github.com/azerothcore/azerothcore-wotlk/issues/11500
-  
-  
- Closes 
- 
- 
1.
2.
3. …

fix(DB/Spells): 54476 triggerspell

---

src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp

Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 Going trough the entirety of Ulduar
creature_text for Razorscale and it's npcs/objects is already populated in the DB
Additional note:
Shouldn't all add types be converted converted into smart scripts? (just a question, not for this pr)
- Added the following missing emotes:
- *EMOTE_BERSERK
- *EMOTE_PERMA_GROUND
- Cleaned unused variables and re-structured most of the code to match C++ standard
- Expedition Commander's does not show gossip icon if encounter is in progress.
- All random spell ids are now properly assigned.
- Removed RepeatEvent from berserk
- Disabled the "intro" (was just SAY_AGGRO, which is wrong) from Expedition Commander, read TODO 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4154 …

fix(Core/Creature): Move hardcoded text/gossips to DB and minor fixes - boss_razorscale 

---

.vscode/settings.json
src/server/game/Entities/Unit/Unit.cpp

- Make spells with that attribute unable to be parried (attacks from the rear cannot be parried by anything)
- Closes [#11459](https://github.com/azerothcore/azerothcore-wotlk/issues/11459)
[TC](https://github.com/TrinityCore/TrinityCore/pull/2762/files)
[Wiki](https://wowwiki-archive.fandom.com/wiki/Parry)
[Deterrence](https://wowpedia.fandom.com/wiki/Deterrence) (reworked 4.x.x)
1. Make a hunter and a rogue/druid
2. Deterrence on the hunter and try to ambush/shred from behind (spell IDs in the issue)
**Attacks with this attribute can still be dodged by mobs (as expected)** …

fix(Core/Spells): Allow spells with SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET attribute to go through deterrence.
