azerothcore/azerothcore-wotlk

- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
Fix che corregge il bug del boss Urom a Oculus, esso a ogni cambio piattaforma dovrebbe spawnare prima i mob e poi teletrasportarsi per ritornare off combat, invece ora come ora il boss si teletrasporta e spawna gli add sulla nuova piattaforma. Questo fa si che i mob arrivino dopo 30 sec sulla prima piattaforma fluttuando nell'aria.
Questo fix corregge il bug.
Google translator:
Fix that fixes the bug of Urom boss in Oculus , change it to any platform should spawn before the mobs and then teleport back off for combat , however right now the boss teleports and spawns the add on the new platform . This makes that the mob arrive after 30 sec on ​​the first floating platform in the air .
This fix corrects the bug .
> [Core/Boss] Oculus/Orum, fix spawn mob position

- src/server/game/Handlers/TaxiHandler.cpp
- src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
1) When a player hit battlemage npc with a first spell of dot class, he enter in evade mode and not cast spell Below Zero.
2) When a player complete tour in bird morph, at movementSpline end, quest status change to complete and remove auraspell morph is done (quest AsTheCrowFlies).
> [Core/Script] Gunship battle, fix evade for battlemage & [Core/script] Quest, fix complete quest and remove morph on movementSpline complete

- src/game/Handlers/MiscHandler.cpp
-    Make use of CONFIG_INSTANT_LOGOUT instead of comparing player's security level against SEC_PLAYER
**Target branch(es):** 1.x
**Issues addressed:** Closes #65 
Tested in-game , works as intended.
No issue.
> Core/Misc: Fix instant logout config

- data/sql/updates/2016_08_14_01.sql
Changes proposed: Fix Hellscream's Warsong & Strength of Wrynn buffs
- Currently, ICC uses 10% buff, but we have a version 3.3.5a and it is 30%.
Target branch(es): 1.x
Tests performed: (Does it build, tested in-game, etc)
Tested in-game , works as intended.
Known issues and TODO list: No issue.
> Core/Spells: Fix Hellscream's Warsong & Strength of Wrynn buffs.

- data/sql/updates/world/2016_08_13_01.sql
- src/game/Miscellaneous/Language.h
- src/scripts/Commands/cs_ticket.cpp
-  Do not allow the completion of the ticket if the handler is not the asignee
-  Let the player know when his/her ticket has been closed or completed.
-  Add missing .ticket complete global GM message.
**Target branch(es):** 1.x
**Issues addressed:** Closes #54 
The tests have been tested in-game.
Nothing so far
Do not allow the completion of a ticket with or without response if the handler isn't the asignee
Let players know when their ticket has been closed or they received a response.
> Core/Commands: Add missing message for .ticket complete

- src/scripts/Spells/spell_dk.cpp
Changes proposed: Fix Corpse Explosion picking ghoul as a target without selection
Target branch(es): 1.x
Tests performed: (Does it build, tested in-game, etc)
Tested in-game , works as intended.
Known issues and TODO list: No issue.
> Core/Spells: Fix Corpse Explosion picking ghoul as a target without selection.

- src/authserver/Main.cpp
Fixed some warnings about outError() and outString() params on src/authserver/Main.cpp
Core rev: 314ad9091b8688ae6b30ebdf4ddbc81d1099b3e4
> Core/Build: fixed 4 warnings

- src/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp
This code adds a Blizzlike check to avoid starting the encounter without being mounted.
http://prntscr.com/cei921.
**Tests performed:** Works with both Alliance and Horde faction.
> Trial of the Champions : Checking if the player is mounted.

- modules/worldengine/nucleus/src/cmake/macros/FindMySQL.cmake
-  Add support for MySQL Server 5.7
master
None
CMake now detect MySQL 5.7 and it builds fine
I'm curious as to why you don't support MySQL 5.7, is there any particular reason?
> Core/CMake: Add support for MySQL Server 5.7

- modules/worldengine/nucleus/src/cmake/compiler/msvc/settings.cmake
-  This fixes the compilation of tools under windows
**Issues addressed:** Closes #212 
**Tests performed:** Compile just fine with VS15
> Core/Tools: Fix compilation of tools under windows

- data/sql/updates/pending_db_world/rev_1483918476110152000.sql
- src/scripts/EasternKingdoms/Karazhan/boss_netherspite.cpp
- src/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp
- src/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp
- src/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp
- src/scripts/EasternKingdoms/Karazhan/boss_terestian_illhoof.cpp
- src/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp
- src/scripts/EasternKingdoms/Karazhan/instance_karazhan.cpp
- src/scripts/EasternKingdoms/Karazhan/karazhan.h
Changes proposed:
**Opera Event**
**Nightbane**
**Shade of Aran**
**Moroes**
**Illhoof**
**Prince Malcazhaar**
Target branch(es): master
Issues addressed: Closes #173 #172 #174 #39
Tests performed: (Does it build, tested in-game, etc)
Tested in game all working correctly.
NOTE You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)
> Karazhan rework

- data/sql/updates/pending_db_world/rev_1486213838562161500.sql
- data/sql/updates/pending_db_world/rev_1486214058938766300.sql
_**Civilian Recruit(s)** will now appear as their correct model._
_Brittle Revenant will now drop the quest item **[Essence of Ice]** with the correct drop rates._
_Added item(s) **[Crystallized Earth]** and **[Relic of Ulduar]** to loot table._
> Minor SQL fixes

- modules/acore/extractors/mmaps_generator/MapBuilder.cpp
-  Fix MMAP:loadMap: X.mmtile was built with generator v5, expected v3
**Issues addressed:** Any issue that has problem with mmaps
**Tests performed:** Not tested
> Core/Extractors : Fix MMAP version

- data/sql/updates/pending_db_world/rev_1487514602617381300.sql
**TESTED**
------------
Fixes item cooldown from 1 min 30 seconds to 30 seconds, to remedy the
uncompletable quest [Basic Chemistry]. Please remove your items cache in
your World of Warcraft directory to reset the item cooldown.
Closes: #332 
@talamortis - here we go :+1:
> [QUEST][WOTLK] Basic Chemistry

- data/sql/updates/pending_db_world/rev_1487539576728818800.sql
Rotting Agam'ar should not be in the air, should be in Razorfen Kraul.
> [NPC][VANILLA] Rotting Agam'ar

- src/game/Battlegrounds/BattlegroundMgr.cpp
-  Restore chek for disables table for battelgraunds
**Target branch(es):** 1.x/2.x etc. master
**Issues addressed:** Closes #306 
no test can't test now
- [ need test] 
> Restore chek in disables table for bg and random bg

- modules/acore/extractors/mmaps_generator/CMakeLists.txt
Compiling extraction tools on Fedora I got following error:
```
/bin/ld: CMakeFiles/mmaps_generator.dir/PathGenerator.cpp.o: undefined reference to symbol 'pthread_condattr_setpshared@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/build.make:210: recipe for target 'modules/acore/extractors/mmaps_generator/mmaps_generator' failed
make[2]: *** [modules/acore/extractors/mmaps_generator/mmaps_generator] Error 1
CMakeFiles/Makefile2:1132: recipe for target 'modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_generator.dir/all' failed
make[1]: *** [modules/acore/extractors/mmaps_generator/CMakeFiles/mmaps_gen …
```
> Fix building mmaps_geenrator on linux

- src/game/Maps/Map.cpp
this should stop creatures falling through the map (ie. if a cave is under the mountin)
-  Creatures should no longer fall under the map.
-  
-  
master
**Issues addressed:** Closes #338 
tested and workimg
> Map.cpp Update

- src/game/Spells/SpellInfo.cpp
-  Spell ID: 9991 now prevents stealth.
-  Simple fast fix. 
-  Thanks to Rushor for pointing it out.
Master
Not an AzerothCore specific issue, is a Trinitycore issue. https://github.com/TrinityCore/TrinityCore/issues/13053
No known issues I found from this commit.
> Touch of Zanzil now prevents stealth.

- src/game/Movement/Spline/MovementTypedefs.h
- Remove code that conflicts with the keyword static_assert http://en.cppreference.com/w/cpp/language/static_assert
- Should fix VS2017 compilation, not sure on the effects on other compilers
- If build fails on other compilers or similar, then we can probably try to just remove all usages of static_assert since its only used in one place: https://github.com/azerothcore/azerothcore-wotlk/blob/736b92d9a70a30db1bff67cd2df2c596b4ce99c9/src/game/Movement/Spline/Spline.h#L41-L48
- Compiled successfully on VS 2017
```
git clone -b Rochet2-patch-1 https://github.com/azerothcore/azerothcore-wotlk.git VS2017
```
then …
> Fix VS2017 build

- data/sql/updates/pending_db_world/rev_1495461970084153283.sql
Borrowed from TC issue#13905
The Warbear Matriarch vehicle for The Warm-Up (12996) and Into the Pit (12997) is not doing any auto-attacks, neither does an auto-attack button appear on the action bar.
This update fixes the first issue, and adjust the auto attack damage to be the same as the maul ability, as that's what it seems to be from this video: https://youtu.be/CJ28xVAeh6M?t=41s
**Tests performed:** Tested it in-game
Fix the action bar to include auto-attack, currently you have to right click the target to start auto-attacking.
> auto-attack for warbear matriarch

- data/sql/updates/pending_db_world/rev_1495729610203623150.sql
**Bael'Gar's Fiery Essence**: updated so that it now needs Bael'Gar's corpse to work.
**Crimson Crystal Shard**: Should be guaranteed over 5 kills, setting it to 100%
**Kurenai, Mag'Har**: Rep from quests for these was increased in some patch.
**Sporeggar**: rep from quests was to low.
**Diaphanous wing droprate**: made uniform over all insects.
**Greater and Young Sporebat**: now drop eyes, was added in some patch.
**Vengeful Draenei**: There were 3 of these, added more based on TC.
**Escaping the Tomb**: was missing its goal
**Slain Sha'tar Vindicator**: Redone to be more and faster respawn.
**Slain Auchenai Warrior**: Redone to be more and faster respawn.
**Howling wind**: uniform droprate.
**Tests performed:** tested on my own build
> minor quest fixes 3

- data/sql/updates/pending_db_world/rev_1495464409315344160.sql
**The Troll Cave**: needs 14 kills, not 10.
http://wow.gamepedia.com/Quest:The_Troll_Cave
**The Grizzled Den**
The wendigos at this den, especially at the entrance, are very dense. It looks as if they're double spawned a lot. It's very hard on lvl 6-8 players, as you're forced to grab 2 at a time.
The id list is gathered from this query.
```
SELECT guid FROM sunwell_world.creature
WHERE id in (1134,1135) AND guid NOT IN
( SELECT A.guid
FROM sunwell_world.creature AS A
JOIN trinity_world.creature AS B
ON A.guid = B.guid
WHERE A.id in (1134,1135) AND B.id IN (1134,1135)
);
```
Turns out TC is a subset of AC, with this fix both are the same. This result is much more tolerable.
**The Perfect Stout**: Rejold's New Brew has The Perfect Stout as prequest, not the otherway around. …
> minor quest fixes 2

- data/sql/updates/pending_db_world/rev_1503630648814585000.sql
Fixed Shattered Hand Blood Guard Event
expecially:
How it worked before:
https://www.youtube.com/watch?v=hXWud6JoJwo
How it works now:
https://www.youtube.com/watch?v=mhquiJv1I_M
**Issues addressed:** Closes https://github.com/azerothcore/azerothcore-wotlk/issues/529
**Tests performed:** tested on local, it works as in video
In Retail server, the areatriggers seems to start in ~150 yards ...instead in our case it's about ~70 yards, but it's not an huge issue. 
I think we need to create a table where fix this kind of special areatrigger instead of read directly from dbc (or use an npc trigger instead)
> [Script/SAI] Fixed Shattered Hand Blood Guard Event

- src/game/Battlefield/Battlefield.cpp
-  Fix warning for compiler GCC under UNIX.
**Issues addressed:** None
https://media.discordapp.net/attachments/348114153849749516/356393487735980032/image.png?width=1200&height=66
**Tests performed:** Tested, working
> Fix warning under GCC Unix

- src/game/Spells/Spell.cpp
-   Spell casting destination channeled spells no longer requires ENABLE_LOGS and ENABLE_EXTRA_LOGS to be enabled for the animations and correct destination target to work correctly.
**Target branch(es):** Master
**Issues addressed:** Closes #601 
**Tests performed:** Builds & tested in game with Penance, Blizzard and Mind Sear
**Known issues and TODO list:** None
> Fixed spell casting destination to require ENABLE_LOGS and ENABLE_EXTRA_LOGS to be enabled

- src/game/Globals/ObjectMgr.h
**Changes proposed:** Added getter for ObjMgr::_itemTemplateStoreFast
**Target branch(es):** Master
**Tests performed:** Builds, Tested
**Why:** This is needed if you want to add a new ItemTemplate outside of ObjMgr
> Added getter for ObjMgr::_itemTemplateStoreFast

- modules/worldengine/nucleus/src/cmake/compiler/msvc/settings.cmake
* Setting all compiler flags in the cache led to circular bloating of
msvc cxx parameters (was visible in console) which caused MSVC to
rebuild the whole solution even on a small CMake change.
It's not neccessary anyway to set the cxx parameters to the cache
to take effect.
* Cleaning the CMake cache is recommended!
Basically when you run cmake then you always need to rebuild the whole solution.
This fix will fix it so that only changed files need to be rebuilt.
This is a cherry pick from TC.
all
Does build and rebuild after using cmake (configure generate) does not compile anything again if nothing has changed.
**NOTE** You no longer need to squash your commits, …
> Core/Build: Never overwrite the msvc cxx flags in the cache

- modules/worldengine/nucleus/src/Database/Implementation/CharacterDatabase.cpp
- src/game/World/World.cpp
- Removed an unneeded GROUP BY to prevent empty return sets
- Added accountId as a fallback value (SELECT statement would return NULL because there is no entry for your account after you deleted all your characters)
**Target branch(es):** 
master
**Issues addressed:** 
Closes #629
It builds and i tested it in-game without any problems.
> Realmlist returns 0 instead of 1 characters after you deleted all characters

- src/server/game/Handlers/ChatHandler.cpp
The receiver player name is missing from the read and it was defined to be the "msg".
Fixing the received whisper addonmessage packet reading from the client.
**Tests performed:** Tested in game.
> Addon message read fix

- data/sql/updates/pending_db_world/rev_1522263653566045620.sql
There are 3 triggers that are from the areatrigger.dbc which are useless since the linked maps don't exist.
It's probably a mistake from blizz.
-  Fixes:
Loading Area Trigger definitions
Area trigger (ID:60) map (ID: 24) does not exist in `Map.dbc`.
Area trigger (ID:81) map (ID: 28) does not exist in `Map.dbc`.
Area trigger (ID:83) map (ID: 28) does not exist in `Map.dbc`.
**Issues addressed:** Part of https://github.com/azerothcore/azerothcore-wotlk/issues/679
**Tests performed:** yes, removed
> DB - Areatrigger - Removes warnings when booting the server

- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/instance_trial_of_the_champion.cpp
- src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.h
I am pushing this on request of Grimgravy who is almost never online but told me he fixed this and isn't sure how to use GIT. He said he fixed it last year so here we go. I added the changes manually, not applying a patch.
-  Make the North Portcullis in Trial of the Champion work as intended
- The fix in action (the code is slightly newer than what you see in the video https://www.youtube.com/watch?v=2s8JZH9ELUw&feature=youtu.be )
**Target branch(es):** 2.x / master
None from me, but @grimgravy says it works fine.
- Test compilation on windows and linux
- Test if it works fine ingame
> Fixes the North Portcullis in TOCh

- data/sql/updates/pending_db_world/rev_1525370516654001760.sql
The "Forlorn Spirit" (NPC 2044) is part of the "Legend of Stalvan" quest chain:
https://wowgaming.altervista.org/aowow/?quest=66
It spawns at different places when finding traces of Stalvan. The following fixes have been applied:
- Target closest player (<30 yards) in order to fill the name and race variables with correct values
- Change from neutral to hostile after 5 seconds and attack the closest player (<30 yards)
**Tests performed:** tested build incl. DB update, tested in-game
> Fix Forlorn Spirit (part of the "Legend of Stalvan" quest chain)

- data/sql/updates/pending_db_world/rev_1525439768213092888.sql
There are two overlapping mailboxes in Undercity, south Trade Quarter. Delete one of them.
**Tests performed:** tested build incl. DB update, tested in-game
> Fix overlapping mailbox in undercity (Trade Quarter, south)

- data/sql/updates/pending_db_world/rev_1525369633022692869.sql
Change spell from 33924 to 12542. They are both equal, but the former caused the NPC to always cast the spell on itself.
**Issues addressed:** Closes  #838 
**Tests performed:** tested build incl. DB update, tested in-game
> Change Fear spell of Bleeding Hollow Tormentor

- data/sql/updates/pending_db_world/rev_1525369154910150908.sql
Change the action when he reaches the lantern: Use oneshot "laughing" instead of emote state
**Issues addressed:** Closes #837 
**Tests performed:** tested build incl. DB update, tested in-game
> Change waypoint data of Deathguard Terrence in Brill

- src/server/game/DungeonFinding/LFGMgr.cpp
- src/server/game/Handlers/LFGHandler.cpp
Once LFG is finished, it is forbidden to queue again.
Now I've removed this restriction.
**Target branch(es):**  master
**Issues addressed:** Closes #856
**Tests performed:** i test in game.Normal work.
I don't know why pussywizard wanted to disable it.
There may be other problems.
So need to test it.
> fix:Dungeon Queue - Not working(#856)

- src/server/game/Spells/Spell.cpp
Cast items with target "TARGET_DEST_NEARBY_ENTRY" (e.g. item 7247) do not work because the if-clause only checks valid target units or game objects.
Fixed via additional check for target object type "TARGET_OBJECT_TYPE_DEST" and a valid target destination.
**Issues addressed:** Closes #846 #70 
**Tests performed:** tested build, tested in-game
> Bugfix: cast items with target type "nearby destination" do not work

- src/server/scripts/Events/hallows_end.cpp
- src/server/scripts/Spells/spell_quest.cpp
Without these, the server would not compile when disabling precompiled headers (PCH)
-  Add missing headers to core scripts
-  
-  
It compiles fine when you disable PCH with Cmake (-DUSE_COREPCH=0)
I should have pushed to master because there is not much to test atm lol
> Scripts - Fixed missing headers

- src/common/Configuration/Config.cpp
- src/common/Logging/Log.cpp
* Update code in Log.cpp (To avoid errors when opening authserver.exe)
* If the required settings are not found when the configuration file is opened, a notification is displayed and the value that was set by default
**Target branch(es):** master.
**Issues addressed:** No issue
**Tests performed:** Tested build, tested in-game (Windows 10 / VS 2017)
* Comment out the option not related to category Log (.conf and .conf.dist)
**Example** MaxPingTime
- Notifications are working, if everything is in order with the options category Log
> Show default options, missing in config files

- data/sql/updates/pending_db_world/rev_1527626760682403687.sql
Based on this commit: https://github.com/TrinityCore/TrinityCore/commit/0156e05953a77c04098044d1fd4f754337778a69
Used most of the commit mentioned above with the following changes:
- more comments
- remove "on aggro" texts and scripts (have nothing to do with the DK quest chain)
- use script ID 15 instead of 0 and changed the delete statements (the original would have deleted all existing scripts of the affected NPCs)
- added the "talk" script 2 more times to the random reaction in order to increase chances that the NPCs will talk (the original had too much throwing in it).
**Tests performed:** tested in-game
Horde:
- .quest remove 13189
- .quest add 13189
- run through Orgrimmar, …
> DK quest chain: Implement reaction for Orgrimmar and Alliance guards while finishing the last quest

- data/sql/updates/pending_db_world/rev_1526938640533602197.sql
He now shoots from a distance and says the correct text lines on aggro.
smart_scripts:
- Set min and max distance for shoot and corrected the comment for ID 0
- Added ID 4 to say the correct text lines on aggro
creature_text:
- Delete wrong text line "Light bless you, my child.", which is not contained in the quotes (see https://wowgaming.altervista.org/aowow/?npc=28611)
**Tests performed:** tested in-game:
1. .npc add 28611 (NPC does not attack from a distance, just stands there)
2. apply SQL script
3. .reload smart_scripts
4. .reload creature_text
5. .npc add 28611 (NPC says correct text lines on aggro and shoots from a distance)
**NOTE** You no longer need to squash …
> Fix NPC 28611 (Scarlet Captain) in the DK area

- src/server/scripts/EasternKingdoms/Karazhan/boss_prince_malchezaar.cpp
Added a cooldown to amplify damage in phase 3, else it's cast every frame. Used random between 20 and 30 seconds as that's what's set at the start of phase 3.
-  Add a cooldown to Prince Malchezaar's Amplify Damage (currently there is none)
-  
1.x/2.x etc.
Closes #
Did you test in-game? Yes
What did you test? Fought and defeated the Prince normally
Did you do all these tests on Linux, Mac or Windows? Windows
Go to the prince in Karazhan and fight him, in phase 3 he currently spams Amplify Damage every frame after the first cast. I've added in a cooldown of 20-30 seconds (same as the inital cooldown is set to when he enters phase 3).
Which commands to use? Which NPC to …
> Prince Malchezaar: Add cooldown to Amplify Damage in phase 3

- data/sql/updates/pending_db_world/rev_1517167424973293300.sql
- src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp
- src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp
When you are at Lord Marrowgar entrance and he starts his intro, Lady
starts her intro too. With this fix, that is fixed.
-  Use DoAction + AreaTriggerScript instead MoveInLOS for intro.
**Issues addressed:** -
**Tests performed:** Build and tested in game.
**Known issues and TODO list:** -
> Fix Lady Deathwhisper intro

- src/server/scripts/Northrend/VaultOfArchavon/boss_archavon.cpp
Changes:
- Archavon's Stone Breath now knocks back tanks at 40y as intended.
> Fixed Archavon's Stone Breath knockback on tank.

- data/sql/updates/pending_db_world/rev_1530048726574700306.sql
Fix faction of Midsummer Celebrant (NPC ID 16781):
old: 84 (Alliance Generic)
new: 35 (Friendly)
master
Closes #949 
tested in-game
- .go creature 94615 (NPC is hostile)
- apply SQL script
- .go creature 94615 (NPC is not hostile anymore)
none
> fix faction of Midsummer Celebrant (NPC ID 16781)

- data/sql/updates/pending_db_world/rev_1530226452517673074.sql
-  delete duplicate Midsummer Celebrants in Tanaris
-  Fire Breathing for all Fire/Flame Eaters (currently only for Fire Eaters)
master
tested in-game
- Go to Tanaris/Gadgetzan and check the duplicate NPCs in both Midsummer Festival camps, e.g.:
`.go creature 94715`
or
`.go creature 94726`
- Check the Master Fire Eaters, Master Flame Eaters and Flame Eaters: They are not breathing fire, e.g.:
`.go creature 90510` (Master Fire Eater)
`.go creature 83243` (Master Flame Eater)
`.go creature 94475` (Flame Eater)
- After applying the SQL script the duplicate NPCs in Tanaris have vanished and all Fire/Flame Eaters are breathing fire.
> delete duplicate Midsummer Celebrants in Tanaris; Fire Breathing for all Fire/Flame Eaters

- src/server/scripts/Spells/spell_rogue.cpp
Tested in-game and it's working.
> Blade flurry shouldn't target totems.

- data/sql/updates/pending_db_world/rev_1530312696838521331.sql
-  Change Midsummer Celebrants in Tirisfal Glades from Alliance to Horde models
-  Add a Festival Scorchling in Tirisfal Glades for quest "Incense for the Festival Scorchlings" (11966)
master
tested in-game
- `.go creature 202761`
- all Midsummer Celebrants have Alliance models
- apply SQL script
- all Midsummer Celebrants have now Horde models
- Festival Scorchling has been added (creature ID 86895 which was deleted in commit https://github.com/azerothcore/azerothcore-wotlk/commit/904ec49d4228f1b995239565dd0694886158022c and already has an entry in table "game_event_creature")
> Fix Midsummer Celebrants in Tirisfal Glades and add Festival Scorchling

- data/sql/updates/pending_db_world/rev_1530734106945512205.sql
Change smart script of the Southsea Freebooter to let him shoot from a distance.
master
tested in-game
- `.go -8075.74 -5080.64 16.4176 1`
- aggro one of the Southsea Freebooters; they will just stand there, doing nothing
- apply the SQL script
- the Southsea Freebooters will now shoot from a distance
> Fix NPC 7856 (Southsea Freebooter)

- data/sql/updates/pending_db_world/rev_1531706256840900300.sql
Fix by:
https://github.com/offl
DB/Script: Fix Captain Dranarus sound range
-  Change datalong2 for guid:15 to 2 in waypoint_scripts
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/621
Tested before fix
Tested after fix
All tests were done on Windows 10 Pro Edition 64bit
Do .tele Shattrath (Walk around for a bit)
You will hear an annoying elf talking crap on you
Apply provided SQL
Tele again, but this time he will only talk crap on you if you are close to him.
(Note: Npc is Captain Dranarus and he is right in front of where you get teleported.)
Master
> DB/Script: Fix Captain Dranarus sound range

- apps/compiler/compiler.sh
- apps/compiler/includes/functions.sh
- apps/db_assembler/db_assembler.sh
Currently Travis won't complain if there are compiler errors. This is the case since the bash scripts have been rewritten (see commit 85388901cf6a69659569ad751767fd7108b25a3c) and the script
`apps/compiler/compiler.sh`
is called via bash from within script
`apps/installer/main.sh`
- include `set -e` to the "compiler.sh"-script in order to exit the script on errors
- the same to the "db_assembler.sh"-script to also allow exit on errors (it is also called via bash from the main installer script)
- ignore exit code of 'make clean' as it won't find a Makefile if called as first action (which is the case for "compiler all"); see script
`apps/compiler/includes/functions.sh`
Sadly, cannot test Travis
Force a compiler error and check Travis
Master
> exit compiler script if any statement returns non-zero exit code

- CMakeLists.txt
fix: config.cmake not work.
`conf/config.cmake.dist` copy and rename to `conf/config.cmake`
`conf/config.cmake` is used to add custom cmake option.(look in https://github.com/azerothcore/azerothcore-wotlk/blob/4d7c06c304e54b52455cd748e4994227b9348482/CMakeLists.txt#L45)
in fact, It should work.
But actually, it doesn't work.
The problem is that "EXISTS" cannot use relative paths.
fix: config.cmake not work.
-  
Closes 
none
Don't need to test.
Don't need to test.
none
Master
> fix: config.cmake not work.

- data/sql/updates/pending_db_world/rev_1534115647861309430.sql
- src/server/scripts/Commands/cs_npc.cpp
Since commit 295f461fdde19256aee6f94f2ed8d83ce6fe26a4 the following error message appears if a command like `.help` is executed:
```
ERROR: Table `command` have non-existing subcommand 'factionid' in command 'npc set factionid', skip.
```
Also there's no help message for the new 'npc set faction' command and it's subcommands. Changes proposed:
-  convert the subcommands to lower case (it is confusing to read upper case subcommands in the help when everything else is lower case):
temp
original
permanent
-  add help text to the 'command' table
tested build and in-game (Ubuntu 16.04)
Execute help:
`.help npc set faction`
`.help npc set faction temp`
`.help npc set faction original`
`.help npc set faction permanent`
Master
> fix error message and help text for new 'npc set faction' command

- src/common/Configuration/Config.cpp
- src/common/Configuration/Config.h
- src/common/Logging/Log.cpp
This is basically PR #908 by @Winfidonarleyan with an alternative fix to the deadlock problem of the auth server. Instead of pulling the initialization of the log files out of the Log constructor (which led to #991) the extended logging functionality is deactivated for the logging options. This should not be a problem as this was mainly implemented to track unused options in modules.
Here's the list of option names which won't be tracked if unused:
LogDB.Char
LogDB.RA
LogDB.GM
LogDB.Chat
LogsDir
LogFile
LogFileLevel
LogTimestamp
LogColors
LogLevel
GmLogPerAccount
GMLogFile
GmLogTimestamp
DBLogLevel
DBErrorLogFile
SQLDriverLogFile
SQLDriverQueryLogging
SQLDeveloperLogFile
CharLogFile
CharLogTimestamp
CharLogDump
CharLogDump.Separate
CharLogDump.SeparateDir
RaLogFile
ChatLogFile …
> log unused config options

- data/sql/updates/pending_db_world/rev_1537654210905936070.sql
set correct broadcast IDs for creature texts during the Pit of Saron intro for Horde and Alliance
none
tested in-game
- enter Pit of Saron with a Horde character
- wrong intro text Tyrannus: "Worthless gnat! Death is all that awaits you!"
- wrong intro text Sylvanas: "Take cover behind me! Quickly!"
- enter Pit of Saron with a Alliance character
- wrong intro text Jaina: "What a cruel end. Come, heroes. We must see if the gnome\'s story is true. If we can separate Arthas from Frostmourne, we might have a chance at stopping him."
- apply SQL script
- correct intro text Tyrannus: "Intruders have entered the master's domain. Signal the alarms!"
- correct intro text Sylvanas: "Soldiers of the Horde, attack!"
- correct intro text Jaina: "Heroes of the Alliance, attack!"
none
Master
> bugfix Pit of Saron intro

- src/server/worldserver/worldserver.conf.dist
-  Warning note to avoid stupid crashes.
https://github.com/azerothcore/azerothcore-wotlk/issues/1042
Crashes also happen when using the anticheat module with a low MaxCoreStuckTime
Note: maybe there is an issue with .reload all which makes the server considered "stuck". That's why I make this PR, if someone thinks there is a more serious issue, please comment below :)
> CORE/conf: Note about MaxCoreStuckTime danger

- data/sql/updates/pending_db_world/rev_1528129508252853447.sql
-  set correct gossip menu ID for Squibby Overspeck (NPC 12137):
old: 1969 (belongs to Frezza)
new: 3842
-  set correct gossip menu ID for Nez'raz (NPC 3149):
old: 1971 (belongs to Zapetta)
new: 2441
- removed gossip menu options 1969 and 1971 ("Where is the zeppelin now?"), as this functionality is not implemented and the option only existed for Frezza and Zapetta
master
tested in-game
just speak to the affected zeppelin masters
> Fix zeppelin master gossip text; remove gossip option "Where is the zeppelin now?"

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Handlers/CharacterHandler.cpp
-  The player should start with most of the main city factions at Exalted status to allow the purchase of items, mounts, etc. when this setting is enabled
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/580
0 test performed by me, 1 test performed by Inifield
- Set ` PlayerStart.AllReputation = 1` in your worldserver.conf
- Create a new character and look at the reputation tab
Master
> Core/Conf: Remove StartAllReputation from player.cpp

- src/server/scripts/Events/hallows_end.cpp
Add voice samples for the following texts:
- "The sky is dark. The fire burns. You strive in vain as Fate's wheel turns."
- "The town still burns. A cleansing fire! Time is short, I'll soon retire!"
none
Tested build on Ubuntu 16.04; tested in-game
Start daily quest "Let the Fires Come!", do not put out the fires.
none
Master
> Fix voice samples for Headless Horseman during quest "Let the Fires Come!"

- data/sql/updates/pending_db_world/rev_1542756898843297200.sql
Wrong Offer Reward Text
The current reward text says: "Thanks for the done work!" 
It should says 
> Another one of Eitrigg's recruits, hm? A sorry state of affairs we find ourselves in if this is the best the Horde can produce. No matter. By the time we think you're ready to leave the Valley, you'll be a proud warrior of the Horde. 
1.  Simply create Horde character
2.  .quest add 787 ( The New Horde )
3.  .go creature 3443 ( Gornek )
4.  Finish Quest ( To see the current OfferRewardText ) 
5. > It will say : Thanks for the done work <--- **Which is Wrong** 
Builded without errors.  --> Tested in game, work as like Blizzlike.
[Quest Take](http://prntscr.com/lkwmxb)
[Quest Finished](http://prntscr.com/lkwlnw)
1.  Now create another Horde character
2.  .quest add 787 ( The New Horde )
3. …
>  DB/QUEST: fix OfferRewardText for The New Horde

- data/sql/updates/pending_db_world/rev_1542839405121938872.sql
Some of the tortured skeletons in Shadow Labyrinth are moving around while lying on the ground. They are also not standing up when attacking. The following TC commit fixes part of this (skeletons standing up):
https://github.com/TrinityCore/TrinityCore/issues/14367
I added another statement to prevent the movement of the lying skeletons.
none
tested build and in-game
- check the skeletons:
.go creature 67091
.go creature 67096
.go creature 67133
- attack the skeletons
none
Master
> DB/SAI: fix tortured skeletons in Shadow Labyrinth

- src/server/scripts/EasternKingdoms/zone_silverpine_forest.cpp
PROPOSED CHANGES:
The string can now be translated in the database
ISSUES ADDRESSED:
The creature currently says the script dialogs instead of searching the database, which does not allow to translate it in case of having dialogs in local_creature_text
Windows; tested in-game
.go creature 18352
KNOWN PROBLEMS AND LIST OF THINGS TO DO:
Destination branch(s):
Master
> Talk method for translations

- src/server/game/Achievements/AchievementMgr.cpp
1. Added a warning ingame and in console when you're a GM testing achievements (else it was confusing).
2. Added another GM mode check in ResetAchievement from TrinityCore.
3. Added an extra type check in UpdateAchievementCriteria, ported from TrinityCore.
None yet.
- Compile
- Enter the game in GM mode on
- Type `.achiev add 504` and see if it warns you ingame and in console.
- I'm not sure how to test change 3) though :P
Master
> Core/Achiev: Warning if GM mode enabled

- data/sql/updates/pending_db_world/rev_1544365875726165400.sql
Fix for the Quest and Vehicles
**##### CHANGES PROPOSED:**
DB changes
Closes 
#1008 
**P.S -->** For quest [11690](ttps://www.wowhead.com/quest=11690/bring-em-back-alive) included in issue, i have tested it, and i don't have any issue with it.
**##### TESTS PERFORMED:**
Already tested in game, everything is correct , and working.
Vehicles are fixed, doesn't dismount anymore, Quest can be done without problems.
**##### HOW TO TEST THE CHANGES:**
1. .quest add 12326
2. [Teleport your self and try to complete quest by using vehicle.](https://www.wowhead.com/quest=12326/steamtank-surprise)
**##### Target branch(es):**
Master
Thanks @boom8866
> DB/Quest Steamtank Surprise

- src/server/game/Conditions/DisableMgr.cpp
- src/server/game/Conditions/DisableMgr.h
- src/server/game/DungeonFinding/LFGMgr.cpp
-  Enables the sourcetype of 8 in the disables table
Unable to disable LFD/LFG maps like you can in trinitycore
Closes 
Allows the disabling of LFG/LFD Maps
Works ingame, unable to select instance under LFG/LFD
The below will now disable Pit of Sauron in LFG/LFD it will show as locked
`INSERT INTO `disables` VALUES (8, 658, 3, '', '', 'PoS 5 Man Disabled LFD');`
Master
> Enable SourceType of 8 for Disables table to disable LFG/LFD maps

- src/server/scripts/Outland/GruulsLair/boss_gruul.cpp
Currently if the Gruul fight goes on for long enough he will cast a new cave in every frame. Added a minimum of 2.5 seconds (taken from Trinity).
-  Add a cooldown to Gruul's cave in ability, else he spams it at the end of the fight.
-  
1.x/2.x etc. 
Closes #
Did you test in-game? Yes
What did you test? Fought Gruul, encounter worked correctly
Did you do all these tests on Linux, Mac or Windows? Windows
Try to kill Gruul before and after the changes. You'll need to kill him slowly to see a difference.
Current has Cave in starting at 29 seconds and removing 1.5 per cast. So it takes 21 casts for the Cave in Timer to become negative (around 300 seconds / 5 minutes) so he …
> Gruul: Add a minimum cooldown for Cave In

- src/cmake/macros/FindOpenSSL.cmake
should fix windows openssl build troubles and must close #1047
change names of libs in 1.1 version of OSSL
Closes #1047
No test, don't have windows, but should work fine
Master
> Core/Build: should fix windows openssl build troubles and must close #1047

- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Currently the second talk text of the Unworthy Initiate has the player as source. This leads to a wrong text when the race variable "$r" is included ("Sate your hunger on cold steel, $r!").
Fix:
Both text lines should have the Unworthy Initiate as source (see also https://youtu.be/U6ZWyvp9b3Q?t=199). Replaced the function call "sCreatureTextMgr->SendChat" with "Talk".
**Tests performed:** Tested build, tested in-game
> Bugfix quest "The Endless Hunger": Wrong source for second talk text.

- src/server/game/Achievements/AchievementMgr.cpp
-  It now only warns the player that he can't complete achievements.
I had added too many GM warnings (stupidly) in that PR https://github.com/azerothcore/azerothcore-wotlk/pull/1028
No more useless warnings.
- Enter the game in GM mode on
- Type `.achiev add 504` and see if it warns you ingame and in console.
- Do other stuff related to achievements and see if any bug?
Master
> Core/Achiev: Fix unwanted GM warnings

- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Prevent random movement of Death Knights; clean up internal player GUID list
- Follow the player at the beginning of the duel (prevent random movement)
- Clear the internal player GUID list if this NPC is not duelled for 10 minutes; this list is used to track the players which already duelled this NPC (you could theoretically flee from each duel and then have no Death Knights left to solve the quest; also the GUIDs did sum up over time)
**Issues addressed:** none
Tested build and in-game
As GM:
1. .quest remove 12733
2. .quest add 12733
3. .go creature 129520
4. Duel
> Fix quest 12733 (Death's Challenge)

- src/server/game/Guilds/Guild.cpp
-  Fix gcc compile warnings
Closes #1148
- Builds on Ubuntu 18.04
Play with Guilds and make sure nothing is broken.
In particular, methods `Guild::HandleSetBankTabInfo` and `Guild::HandleAddNewRank` have been refactored so the tester should perform those actions in game and make sure they still work as expected.
No issues
Master
> Core/Guilds: fix gcc compile warnings

- src/server/game/World/World.cpp
Updates: https://github.com/azerothcore/azerothcore-wotlk/issues/679
Having 0 players in the Database is the default state of a fresh installation of AzerothCore, therefore it should **not** be considered as a DB error.
> Core/World: do not consider error when no players in the DB

- data/sql/updates/pending_db_world/rev_1546271889931245071.sql
The vanity pet "Sen'jin Fetish" has an invisible model assigned for modelid2. Through this PR this model is removed.
none
Tested in-game
- ```.additem 45606```
- Use the item and summon the vanity pet; there's a 50% chance that you won't see a model
- Apply the SQL script
- ```.reload creature_template 33810```
- Resummon the pet
none
Master
> DB: Fix Sen'jin Fetish model

- data/sql/updates/pending_db_world/rev_1546694249586814731.sql
- src/server/scripts/Pet/pet_generic.cpp
Fix the hover height for some of the flying vanity pets (they fly nearly on the ground). Also fix the animation while following the player for the moths, the "Gryphon Hatchling" and the "Wind Rider Cub".
none
Tested build, tested in-game
Summon the following vanity pets, especially the moths, the "Gryphon Hatchling" and the "Wind Rider Cub":
Azure Whelpling
Blue Dragonhawk Hatchling
Blue Moth
Cockatiel
Crimson Whelpling
Dark Whelpling
Emerald Whelpling
Firefly
Frosty
Golden Dragonhawk Hatchling
Great Horned Owl
Green Wing Macaw
Gryphon Hatchling
Hawk Owl
Hyacinth Macaw
Mana Wyrmling
Miniwing
Nether Ray Fry
Netherwhelp
Onyxian Whelpling
Phoenix Hatchling
Red Dragonhawk Hatchling
Red Moth
Senegal
Silver Dragonhawk Hatchling
Sprite Darter Hatchling
Tickbird Hatchling
Tiny Sporebat
Tirisfal …
> DB/Core: Fix hover height and some flying animations of vanity pets

- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
This is more of a base for discussion, although it works on my solo test-server.
It bugged me since starting with AC that the pets and vanity pets start to stutter while running beneath the character. The cause of this is a fixed speed calculation for the pet speed while not in combat, see line 13097 in Unit.cpp:
```
if (speed < pOwner->GetSpeedRate(mtype)+0.1f)
speed = pOwner->GetSpeedRate(mtype)+0.1f; // pets derive speed from owner when not in combat
```
This leads to the pet constantly trying to outrun the player but has to wait if too far ahead. This wait is causing the animation to stutter.
As a possible fix I adjusted the "TargetedMovementGenerator" in order to update the speed of pets every tick and changed the speed calculation in Unit.cpp (only for pets and vanity pets). This …
> Core/Movement: Prevent pet animation stuttering during movement

- data/sql/updates/pending_db_world/rev_1547251001073984601.sql
I falsely thought in PR #1208 that model ID 29189 was a better one because ID 28880 was invisible. In fact ID 29189 is the model for the pet overview and ID 28880 is the right model, but needed the correct auras applied:
- always:
Enchanted Tiki Warrior: Enchanted Tiki Warrior Glow Visual (52619)
- randomly:
Enchanted Tiki Warrior: Enchanted Tiki Warrior Visual 01 (52614)
Enchanted Tiki Warrior: Enchanted Tiki Warrior Visual 02 (52617)
Enchanted Tiki Warrior: Enchanted Tiki Warrior Visual 03 (52618)
This PR fixes this by assigning an appropriate SAI for the Sen'Jin Fetish (33810).
Closes #1211 
Tested in-game
- ```.learn 63712```
- Summon Sen'Jin Fetish
none
Master
> DB/SAI: Finally fix Sen'Jin Fetish

- apps/db_assembler/includes/functions.sh
-  Added option `--default-character-set=utf8`
-  Fix incorrect apply not English text
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1250
- `import-all: Assemble & Import all` in Windows
**Need full clean DB!**
1. Apply PR
2. Use `db_assembler`
3. Choose `5 - import-all: Assemble & Import all`
4. Check DB table e.g. `locales_broadcast_text`
5. First data should be as follows
> Bash: Fix incorrect apply sql files at import

- docker/database/Dockerfile
Fixed permission in docker-database, added command chmod 755 before run the file db_assembler.sh in the Dockerfile for the database.
> Fixed permission in docker-database

- src/server/game/Entities/Creature/GossipDef.h
- src/server/game/Entities/Player/Player.cpp
- Correctly hide and show info gossip based on dual spec requirements.
- Show correct gossip after learning dual spec.
- Port PR from TC https://github.com/TrinityCore/TrinityCore/pull/17921
- **Need apply after PR** https://github.com/azerothcore/azerothcore-wotlk/pull/1160
Master
> Core/Gossip: Improve gossips related to Dual Talent Specialization

- src/common/Database/MySQLConnection.cpp
Authserver and Worldserver don't die immediately if they don't find MySQL, but they wait until they can connect to it (trying every 10 seconds).
After 180 attempts (30 minutes) it exits.
This is how modern, resilient apps are done. This helps virtualization environments & similar setups.
-  Closes #1285
Closes 
- Compiles on Linux
- Successfully waits until mysql service is up and then connects to it
- Logging in game works
- Stop mysql service (on linux: `sudo service mysql stop`)
- Run authserver and worldserver
- After a while, start mysql service again (on linux: `sudo service mysql start`)
On windows it should be the same, just a different way to start/stop mysql I guess.
Master
> Core/MySQL: wait for the DB to be ready

- .travis.yml
-  Add a branch constraint to the travis config to only execute pending sql imports when the activation comes from _master_ branch
Currently, we have a problem with working branches from collaborators in the main repo, explained by the following:
1. Collab creates a working branch, i.e. **john-hotfix-ulduar**
2. Collab pushes some scripts to **pending_db_world**
3. Travis imports that pending sql script
4. Collab creates a pull request
5. Time passes while the PR is tested. Meanwhile, other PRs got approved
6. PR is approved and merged into master branch.
In step 6, the **pr column name** will be older than the **current column name** in master branch, breaking the update chain.
> CI: Import pending sql from Travis only master branch

- src/server/game/Spells/SpellMgr.cpp
Not increases the damage done by your Death and Decay ability by 20%
- Increase the damage of Death and Decay by equipping the two tank parts to lose ago.
Closes 
-Use the two tank parts of the T10 DeathKnight
-Being in front of a boss or mobs
-cast Death and decay and see the damage it does
Master
> Core/Spells: Fix DeathKnight T10 Tank 2P Bonus

- data/sql/updates/pending_db_world/rev_1547906915621116396.sql
- Remove minor differences to sync with TC
Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/1178
Compile, runs
The only affected fields that are actually used by the core are:
```
- `quest_template_addon`.`NextQuestID`
- `spell_bonus_data`.`entry`
- `waypoint_data`.`wpguid`
```
the test should just make sure that the data stored in those fields is not altered after this PR.
Master
> refactor(DB-world): minor changes

- data/sql/updates/pending_db_world/rev_1547990516486417003.sql
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
Moved some AC-only SmartAI actions. This will avoid conflicts with TC 3.3.5.
We will use enums **> 200** for all the actions that are in AC but not in TC.
- Move `SMART_ACTION_MOVE_TO_POS_TARGET` to `201`  (previous value `130`)
- Move `SMART_ACTION_SET_GO_STATE` to `202`  (previous value `131`)
- Move `SMART_ACTION_EXIT_VEHICLE` to `203`  (previous value `132`)
- Move `SMART_ACTION_SET_UNIT_MOVEMENT_FLAGS` to `204`  (previous value `133`)
- Move `SMART_ACTION_SET_COMBAT_DISTANCE` to `205`  (previous value `134`)
- Move `SMART_ACTION_SET_CASTER_COMBAT_DIST` to `206`  (previous value `135`)
- Move `SMART_ACTION_SET_HOVER` to `207`  (previous value `141`)
- Move `SMART_ACTION_ADD_IMMUNITY` to `208`  (previous value `142`)
- Move `SMART_ACTION_REMOVE_IMMUNITY` to `209`  (previous value …
> refactor(SmartAI): move AC-only SMART_ACTIONs to avoid conflicts with TC

- data/sql/updates/pending_db_world/rev_1548170266680613800.sql
- Fix crash in https://github.com/azerothcore/azerothcore-wotlk/issues/1336
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1336
1. Make a new Draenei (any class)
2. Teleport to azure watch .tele azurewatch
3. Talk to NPCs
- In AC [GridNotifiersImpl.h](https://github.com/azerothcore/azerothcore-wotlk/blob/6c233c4d8c49cd8f014f2df497d7c8a646b2bf74/src/server/game/Grids/Notifiers/GridNotifiersImpl.h#L524)
```cpp
template<class Builder>
void Trinity::LocalizedPacketDo<Builder>::operator()(Player* p)
{
LocaleConstant loc_idx = p->GetSession()->GetSessionDbLocaleIndex();
uint32 cache_idx = loc_idx+1;
WorldPacket* data;
// create if not cached yet
if (i_data_cache.size() < cache_idx + 1 || !i_data_cache[cache_idx])
{
if (i_data_cache.size() < cache_idx + 1) …
```
> DB: Fix crash in waypoint_scripts

- data/sql/updates/pending_db_world/rev_1548013361501724652.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
-  Rename ` SMART_ACTION_ADD_QUEST` to `SMART_ACTION_OFFER_QUEST`
-  This action can now open a dialog to offer the quest instead of adding it straight to the quest log
- With `action_param2` = `1` it will be like the old behaviour, with `0` it's the new behaviour
- All existing scripts will keep the same behaviour, except for creature `11216`
Feature by **@Treeston** imported from TC
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/1326
Builds
- Test that the current scripts that use this action are not broken and use the same behaviour (with the exception of creature `11216` that will have the new behaviour). So check some existing scripts that add quests.
- Test the script of creature `11216` and make sure it asks for quest with a quest dialog
Master
> feat(SmartAI): improve add quest action

- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
Implement action type 115 "SMART_ACTION_RANDOM_SOUND". This will allow smart scripts like the one contained in PR #1348 to play random sound samples.
None
Tested build and in-game (Ubuntu 16.04)
This can be tested via quest 5441 (see #1348)
- ```.quest add 5441```
- ```.go creature 3345```
- use Foreman's Blackjack on the peon
- he will now randomly say "okey dokey" or "I can do that"
None
Master
> feat(SmartAI): Implement action type 115 "SMART_ACTION_RANDOM_SOUND"

- data/sql/updates/pending_db_world/rev_1548282125491483924.sql
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- Move `SMART_TARGET_FARTHEST` to `28`  (previous value `40`) to avoid conflicts with TC
- Display error when an invalid `target_type` is used, which is lower than `0` or bigger the the max taget we have (currently the max is `29`)
> "SmartAIMgr: EntryOrGuid %d using event(%u) has an invalid target type (%u), skipped."
- Display error when an unsupported `target_type` is used (currently `27` or `29`)
> "SmartAIMgr: EntryOrGuid %d using event(%u) has a target type that is not yet supported on AzerothCore (%u), skipped."
Updates https://github.com/azerothcore/azerothcore-wotlk/issues/1326 
Builds, runs.
- Try to put an invalid `target_type` in table `smart_scripts` and see if the error is properly displayed ( lower than ` 0` and bigger than `29` )
- Try to put an unsupported `target_type` …
> feat(SmartAI): display error on unsupported targets + align TC enums

- data/sql/updates/pending_db_world/rev_1548367133880932410.sql
- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Quests/QuestDef.cpp
- src/server/game/Quests/QuestDef.h
Imported & adapted 2 fixes from TC, original authors:
- Killyana
- ariel-
-  Fix some quest chains (`12222` and `12223`)
-  Align `NextQuestID` to TC (made unsigned)
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1328
Build, runs.
- Check that the quest chains involving `12222` and `12223` still works
- Test other quest chains and make sure everything still works
Master
> fix(quest): fix some quest chains + align NextQuestID with TC

- docker/database/generate-databases.sh
Docker: Naming errors for some sql files
Fixes naming errors in `generate-databases.sh`  
When running `docker-compose up`, the `ac-database` exited, since it didn't find the following sql files:
- /sql/auth_update.sql
- /sql/characters_update.sql
- /sql/world_update.sql
By running `docker-compose run ac-database /bin/bash` i checked the files with `ls /sql` and could find the files, but they were named in plurally. So when I changed in the `generate-databases.sh` the names, the databases could be generated, and at last the authserver and worldserver could connect to the database.
Tests only done on Mac. But I guess, since the fix was made in docker, it should have the same effects on all platforms
1. `git clone https://github.com/Raschaad/azerothcore-wotlk.git`
2. Copy the data (client …
> Docker: Naming errors for some sql files

- data/sql/updates/pending_db_world/rev_1548704473723698729.sql
- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Conditions/ConditionMgr.h
This improves the way we handle table `conditions`. You can find its TC reference here: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130002/conditions#conditions-
------
- When `SourceTypeOrReferenceId` that are not supported on 3.3.5a are used, show the following error:
> "ConditionSourceType XX in `condition` table is not supported on 3.3.5a, ignoring."
Current source types that are not supported in 3.3.5a: `25`, `26`, `27`.
------
- `CONDITION_QUEST_SATISFY_EXCLUSIVE` has been moved from `50` to `101`
- `CONDITION_HAS_AURA_TYPE` has been moved from `51` to `102`
- When `ConditionTypeOrReference` that are not supported on 3.3.5a are used, show the following error:
> SourceEntry YY in `condition` table has a ConditionType that is not supported on 3.3.5a (XX), ignoring.
Current …
> feat(conditions): prevent adding bad contitions + align enums with TC

- conf/config.sh.dist
-  Now use the logical order of DBs.
- **Also disabled extractors compilation by default.** (CTOOLS if I'm not making a mistake here)
It was ordered like this:
- characters
- auth
- world
which is not the logical/usual order ^^
Also disabled tools compilation by default as it's something you only do rarely (or never).
> style: Reorder DBs in config.sh.dist

- data/sql/updates/pending_db_world/rev_1548850930086940600.sql
- src/server/scripts/Spells/spell_item.cpp
-  Fixed Val'anyr Hammer of Ancient Kings
-  
Closes #296 
Tested ingame on a paladin, before applying fix was applying blessing of kings on self to check proc.
after applying fix doing the same.
1. Before applying the PR, Create a paladin or priest log in on that character
2. Spam cast buff effects on yourself (such as blessing of kings or power word fortitude)
3. See shield was applied.
4. Apply the fix
5. Log back in and do the same.
Master
> [Core/ Spell] Val'anyr Hammer of Ancient Kings Fix

- data/sql/updates/pending_db_world/rev_1548717283055325995.sql
The Mage only quests "Investigate the Blue Recluse" (1920) and "Investigate the Alchemist Shop" (1960) are already working, but triggered by the PR #1360 created by @poszer I took the chance to look a little deeper into those quests. As pointed out by @poszer and seen in this old [video](https://www.youtube.com/watch?v=M9XbZWgzHpM), the Rift Spawns are indeed attacking the player once the "Cantation of Manifestation" is used.
This PR contains the following changes:
- The Rift Spawns will immediately attack after using "Cantation of Manifestation" and now correctly say "Rift Spawn is angered and attacks!"
- The Rift Spawns will now correctly say "Rift Spawn escapes into the void!" if it takes too long to catch them after being stunned.
- The LoS restriction of "Cantation of Manifestation" …
> Fix(DB/SAI): Small fix for the Rift Spawns (Mage only quests 1920 / 1960)

- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/GameObject/GameObject.h
- src/server/game/Entities/Transport/Transport.cpp
-  Fixes elevator issue
-  Prevent other issues related to the gameobject's faction and flags
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1396
- Builds, run
- Tested elevators in game, now they work again
- Checked a couple of other gameobjects (e.g. mailbox) to make sure they still work
- Test some elevators
- Check some other random objects to make sure they still work fine
Master
> fix(gobject): elevator bug + prevent bugs related to faction and flags

- data/sql/updates/pending_db_world/rev_1549150908212681677.sql
-  Removed a couple of `spell_scripts` that are causing DB startup errors
Closes 
- Build, runs
Those two `spell_scripts` where introduced in this commit: https://github.com/azerothcore/azerothcore-wotlk/commit/7a0a5613d0f94dcc2df62383df7bfadf1721e9ca
which was about "Fixing Encounter Boss Faerlina".
In particular, those 2 lines were marked as "Widow's Embrace".
The test should basically:
- make sure that Boss Faerlina still works as before 
Master
> fix: spell_scripts DB startup errors

- data/sql/updates/pending_db_world/rev_1548778743987887239.sql
Fix Backbiter following Warp-Huntress Kula in Dalaran. Instead of summoning Backbiter via spell "Summon Backbiter" by Kula it is inserted as regular creature following Kula in close formation. Also fixed some missing texts for the following creature IDs in order to get rid of the errors in the server log:
27047: Invisible Stalker (Floating Only)
32711: Warp-Huntress Kula
29506: Orland Schaeffer
I used the inserts proposed by Knindzagxg in #980.
Closes #980
Closes #1379
tested in-game on Ubuntu 16.04 using AC commit 9af2a461f65316ce4c21c9668dd62515b8e4f370
- ```.go creature id 32711```
- follow Kula around
- check server log for error messages concerning the texts for the creature IDs mentioned above
None
Master
> Fix(DB): Backbiter movement and some missing texts in Dalaran

- src/server/game/Loot/LootMgr.cpp
- Fixed bug that made the core complaining about "unused mail_loot_template" while they were actually used (thanks @wetbrownsauce for verifying those)
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1155
- Builds, run -> no more errors
- There should no longer be any `mail_loot_template` errors at startup (check `DBErrors.log`)
- Test a couple of `mail_loot_template` and make sure they still works
Master
> fix: core reporting wrong mail_loot_template startup DB errors

- data/sql/updates/pending_db_world/rev_1549149082825412953.sql
This change was already tested by @wetbrownsauce in another PR (which was closed because containing other unwanted changes), the result was:
> As for the achievement_criteria changes, most of the affected achievements are actually statistics for number of 5 player, 10 player, and 25 player instances entered. These don't appear to work before or after the PR, so the changes in their db table make no difference aside from removing start up warnings/errors.
-  Fix DB startup errors about unsupported achievement criteria types
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1156
- Run and those DB errors are gone
- Just make sure we're not breaking anything that is currently working, apparently this was already tested by @wetbrownsauce 
Master
> fix: remove data for unsupported criteria type

- src/server/game/Achievements/AchievementMgr.cpp
- src/server/game/Entities/Player/Player.cpp
**CHANGES PROPOSED:**
- Check achievements on player creation.
Fixes client not allowing to open achievements list if start level is superior or equal to 10.
Closes #1422
> Core/Player: fix achievements activation

- data/sql/updates/pending_db_world/rev_1547897046380364588.sql
This is more an idea that I would like to share and discuss.
---------------
The idea is the following:
- We are currently using the third column's name of the `version_db_world` table to uniquely identify the `world` DB version (and same for `auth` and `characters` DBs). This system has proven to work well and it's **not** changing.
- We can use the (currently unused) `db_version` and `cache_id` to keep track of every time that we squash our DB updates (i.e. merge all updates into the base table files).
- The idea is to flag with "`(dev)`" when there are pending sql updates. This means that next time we want to do the sql update squash, we will: 
1. remove  "`(dev)`"
2. squash and fix the `db_version` to just `ACDB 335.2`
3. add a new sql update that flags the "beginning" of the …
> chore(DB): set main DB version

- src/server/game/Spells/SpellMgr.cpp
- src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp
-  Apply Resistances in Players VS damage spell Halion, Living Inferno
-  
Closes 
- Start combat and wait for "Halion" and "Living Inferno" to appear, then see "Meteor Strike", "Combustion periodic" hit the "raid" or player.
-While "Living Inferno" causes damage with "Blazing Aura" to a player who takes it, and you will see that it does not resist
Master
> Core/Instance: Ruby Sanctum. Resistances ignored

- data/sql/updates/pending_db_world/rev_1549809565412286900.sql
Fixes for Opened Quest issues
- Ironband's excavation and gathering idols quest fix. The quest 297 can't be used without finishing quest 436.
- Find bingles and bingles missing supplies quest fix. The quest 2038 can't be used without finishing quest 2039.
- Data rescue quest fix. Added Missing options for the  Matrix Punchograph 3005-D to finish quest.
- Fixed the SmartAI scripts for Cursed and Tainted Ooze - The corpse will disappear now on Spell Hit.
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1434 
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1428
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1425
The Sql is imported without any errors. Tested in game, the Quest and listed quest issues are fixed, and can be done without any …
> DB/Quest: Fixes for opened Quest issues

- apps/db_exporter/db_export.sh
- bin/acore-db-export
This tool is for developers-only and it's not supposed to be used by users. Test is not required for this PR.
- Fixed bad path
- Prompt the user before actually executing, since this scripts overrides the DB base files.
> fix(Bash/Exporter): correct path + add prompt to prevent user to use it by mistake

- .travis.yml
Since we have the build matrix now, running with 2 different versions of clang, each build job tries to trigger the import sql file and the second one will fail since the first already did it.
This way we trigger such activities only in one build job.
**How to test**: Unfortunately there is no way to test this until it gets on master.
> fix(CI): Travis triggers the AC bot only once

- apps/ci/ci-before_install.sh
- apps/ci/ci-install.sh
- apps/ci/ci-script.sh
- currently the CI scripts don't break on errors, so Travis does not recognize problems in these scripts; fixed by adding `set -e`
- increase build timeout to 2700 seconds (45 minutes)
none
has to be tested by Travis run
see above
none
Master
> fix(CI): break on errors in CI scripts

- src/server/game/Globals/ObjectMgr.cpp
- src/server/game/Globals/ObjectMgr.h
-  Added new method `ObgectMgr::ChangeFishingBaseSkillLevel(uint32 entry, int32 skill)` to change the fishing base skill level for a particular zone.
> Core/Skills: Add FishingBaseSkillLevel dynamic change method

- apps/ci/ci-install.sh
Dynamically calculate the thread count for the build process by reading `/proc/cpuinfo` in order to be more independent from the environment.
none
has to be tested via Travis run
see above
none
Master
> feat(CI): dynamically calculate thread count for build process

- .gitignore
- bin/acore-docker-build
- bin/acore-docker-remove-build-cache
- docker-compose.yml
- docker/README.md
- docker/authserver/Dockerfile
- docker/authserver/README.md
- docker/build/Dockerfile
- docker/build/README.md
- docker/worldserver/Dockerfile
- docker/worldserver/README.md
This PR allows docker build to cache the results for faster rebulding. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1502
To test this PR you need to have the requirements [Docker setup](http://www.azerothcore.org/wiki/Install-with-Docker#setup) (install docker, download data files, etc...). If you already used AC with Docker at least once, then you're good to go. Otherwise just checkout this PR and follow the Docker guide from the beginning.
1) Start from a clean environment (no existing AC images and containers). You can manually delete them or just use `docker system prune -a` (**WARNING**: this will delete ALL Docker images and containers from your machine).
2) Launch the build with `./bin/acore-docker-build`
3) Try to run the build again, it should be much faster …
> feat(docker): add cache for faster rebuild

- data/sql/updates/pending_db_world/rev_1549320792563626100.sql
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/scripts/Commands/CMakeLists.txt
- src/server/scripts/Commands/cs_cheat.cpp
- src/server/scripts/Commands/cs_misc.cpp
- src/server/scripts/ScriptLoader.cpp
-  Add the cheat command, it's very useful for testing purposes. 
#533
Compiled and test all of them, they work.
Just enter to the game and use the `cheat` commands:
```
('cheat',           2, 'Syntax: .cheat $subcommand\r\nType .cheat to see the list of possible subcommands or .help cheat $subcommand to see info on subcommands'),
('cheat god',       2, 'Syntax: .cheat god [on/off]\r\nTurn the user invulnerable.'),
('cheat casttime',  2, 'Syntax: .cheat casttime [on/off]\r\nRemove spells\' casting time.'),
('cheat cooldown',  2, 'Syntax: .cheat cooldown [on/off]\r\nDisable spells\' cooldowns.'),
('cheat power',     2, 'Syntax: .cheat power [on/off]\r\nRemove spells\' cost (mana, energy, rage...).'),
('cheat waterwalk', 2, 'Syntax: .cheat waterwalk on/off\r\nAllow to walk on water (self or …
```
> Core/Commands: Added cheat command

- .travis.yml
- apps/db_pendings/import.sh
Add commit hashes to the automatic SQL import.
Closes #1449 
Tested on Ubuntu 16.04
(sadly, I don't know how to test the Travis run itself)
- clone azerothcore-wotlk
- reset to commit 38830f29c18159327707ff9d40cc97306b588c6a (this commit contains 3 pending SQL files)
```git reset --hard 38830f29c18159327707ff9d40cc97306b588c6a```
- manually apply the PR changes to ```apps/db_pendings/import.sh```
- execute ```source bin/acore-db-pendings```
- execute ```echo "$COMMIT_HASH"```; result (please also take note of the leading blank!):
```  275dbec76d023da6824e44c725813f10802287f8 6a53a73c1b235b111194e44b0dff5e6e6fda8927 38830f29c18159327707ff9d40cc97306b588c6a```
The Travis configuration is changed to also call ```source acore-db-pendings```, so the variable should be set for the commit …
> feat(CI): add commit hashes to the automatic SQL import

- data/sql/updates/pending_db_world/rev_1550874957572075786.sql
Fix wrong creature texts during the Pit of Saron intro for Horde and Alliance. This was already fixed some time ago via PR #1033 but somehow it seems to got reverted through commit b34bc28e5b02514fca3519beac420c58faa89cad.
none
tested in-game
- enter Pit of Saron with a Horde character
- wrong intro text Tyrannus: "Worthless gnat! Death is all that awaits you!"
- wrong intro text Sylvanas: "Take cover behind me! Quickly!"
- enter Pit of Saron with a Alliance character
- wrong intro text Jaina: "What a cruel end. Come, heroes. We must see if the gnome\'s story is true. If we can separate Arthas from Frostmourne, we might have a chance at stopping him."
- apply SQL script
- correct intro text Tyrannus: "Intruders have entered the master's domain. Signal the alarms!"
- correct intro text …
> fix(DB): Pit of Saron intro creature texts

- src/server/scripts/Commands/cs_reload.cpp
**Fixing velocity < 0.01f error after reloading a creature**
-  Changing the field called by cInfo->speed_run from 29 to 19. (in cs_reload.cpp)
No issues found about that. To reproduce, simply reload an existing creature with .reload creature_template, respawn the creature and try to make it move with .come, the error should appear on the console.
Tested with a clean compil on windows 64, working now as intended, after a reload the creature can move without any errors.
- Edit something on a creature_template
- Reload creature_template
- Add the reloaded creature
- Try to make it .come
- No more error on the console and the creature WILL move
master
> Fixing velocity < 0.01f error after reload

- data/sql/updates/pending_db_world/rev_1552517697995597395.sql
PR #922, just like PR #1033, got reverted by commit b34bc28e5b02514fca3519beac420c58faa89cad. It originally did fix issue #920 concerning the bugged Malmortis conversation texts. These bugs are corrected via this PR once again.
#920 
Tested in-game
Use the coffin which is around these coordinates:
`.go xyz 6251.59 -1969.51 484.782 571`
none
Master
> fix(DB): Malmortis creature text

- data/sql/updates/pending_db_world/rev_1550579754213080400.sql
- src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp
<!Scripts/Instances/Oculus: improvements>
A new feature was applied to the oculus dragons that were missing, the [drake-flag-visual](https://www.wowhead.com/spell=53797/drake-flag-visual) application after calling it
I fixed drakes flight error at the request of @comix1988 and @alexkulya using the trinitycore code
Link: https://www.youtube.com/watch?v=d6J2lH0fe28&t=327s&list=FL5HpOkw1d6zY_LtGCLSxeFg&index=11
after leaving any drake the parachute is not activated
-  added spell_oculus_evasive_charges
-  added spell_oculus_evasive_charges
-  added spell_oculus_soar
-  added spell_oculus_rider_aura
- added spell_oculus_drake_flag
Tested by windows 7 operating system
> Scripts/Instances/Oculus: improvements

- .travis.yml
- apps/ci/ci-compile.sh
- apps/ci/ci-import-db.sh
- apps/ci/ci-install.sh
- apps/ci/ci-worldserver-dry-run.sh
Improve Travis build time by using two stages: One to prepare the ccache by compiling without scripts and the second to run the actual build. This way none of the jobs should hit the 50 minute limit of Travis for a single job execution.
Closes #1518 
hast to be tested in this PR
see above
none
Master
> feat(CI): improve Travis build time

- data/sql/updates/pending_db_world/rev_1552778052775198017.sql
Fix another PR which got partly reverted through b34bc28e5b02514fca3519beac420c58faa89cad: #907 
Remove gossip menu options 1969 and 1971 ("Where is the zeppelin now?"), as this functionality is not implemented and the option only existed for Frezza and Zapetta.
none
tested in-game
- ```.go creature id 9564``` (Frezza) and ```.go creature id 9566``` (Zapetta)
- speak with the zeppelin masters
none
Master
> fix(DB): zeppelin master - remove gossip option "Where is the zeppelin now?"

- data/sql/updates/pending_db_world/rev_1552778845262248351.sql
- set the following creatures active after spawning in order to resume their waypoints even if no player is near (this was originally the danger about them):
Fel Reaver in Hellfire Peninsula (GUID 67001 & 203341)
Durn the Hungerer in Nagrand (GUID 65801)
Storm Giant in Howling Fjord (GUID 118177 & 118191)
- fix the aura 44385 (Storm Giant Warning Aura) for one of the Storm Giants (GUID 118177) which did cause the following error message in the logs:
```SCRIPT_COMMAND_CAST_SPELL ('waypoint_scripts' script id: 1161) no source unit found for spell 44385```
- remove the waypoint scripts for one of the Storm Giants (GUID 118177) which did cause him at a specific part of his path to just stand there spinning around
- update the spawning position for one of the Storm Giants (GUID 118191) in …
> fix(DB): a few improvements to the giant wandering outdoor creatures

- data/sql/updates/pending_db_world/rev_1553536152748153223.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- add all necessary portals for the Horde and Alliance quest chain
- add Horde version of the phased Orgrimmar
- add event for "Herald of War", based on the already existing Alliance version with a few tweaks
- add a few tweaks to the event for "Fate, Up Against Your Will" (Alliance)
- add Runthak speaking to the Orc commoners (based on https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8)
- randomize the Forsaken refugees (some sleeping, some sitting around)
- add a 5th parameter to SAI events "SMART_EVENT_OOC_LOS" and "SMART_EVENT_IC_LOS" in order to allow a reaction to players only; this is based on these TC commits:
https://github.com/TrinityCore/TrinityCore/commit/5ad38c31b0ed633555f281318684e57ea5d6dd73 …
> fix(DB/Core): quest chain leading to "Battle for the Undercity"

- data/sql/updates/pending_db_world/rev_1553556583989604427.sql
Change "InhabitType" to 7 for Fezzix Geartwist to prevent him from "jumping" through the air while testing his flying machine when finishing quest "Patching Up" (11894).
none
tested in-game
- ```.go creature id 25849```
- ```.quest remove 11894```
- ```.quest add 11894```
- ```.additem 35289 5```
- finish quest
none
Master
> fix(DB): Fezzix "jumping" through the air

- data/sql/updates/pending_db_world/rev_1553669941222108220.sql
Despawn Jenny when quest "Load'er Up!" (11881) is complete. Otherwise she would just continue to follow you around even when the quest is finished.
none
tested in-game
- ```.go creature id 25849```
- ```.quest remove 11881```
- ```.quest add 11881```
- finish quest
none
Master
> fix(DB/SAI): despawn Jenny when quest "Load'er Up!" is complete

- CMakeLists.txt
-  Add new hook AFTER_LOAD_CMAKE_MODULES
-  This hook is needed primarily for Eluna module
- I think that this PR does not need testing, this PR is necessary for the normal operation of the Eluna module
- See https://github.com/azerothcore/mod-eluna-lua-engine/pull/12
> Cmake: Add new hook AFTER_LOAD_CMAKE_MODULES

- data/sql/updates/pending_db_world/rev_1553973207096786300.sql
- data/sql/updates/pending_db_world/rev_1553974864385673300.sql
Fix for Rough Stone from Copper Veins.
For some reason, there was only 10 or 20% drop chance -> Should be 80% except Ghostlands where's 88%.
To check it go to:
gameobject_template and take DATA IDs for loot
gameobject_loot_template and see drop chance
Also fix for Dragonmaw Bonewarder.
He's missing guardian and casting almost 2 same spells.
To test it .go cre 9626
Apply SQL fix, .reload smart_scripts
.npc add 1057
> [DB & SAI] Rough Stone & Dragonmaw Bonewarder

- src/server/game/Entities/Object/Object.cpp
Fix the following compiler warning by reordering the parameters:
```
src/server/game/Entities/Object/Object.cpp:967:65: fatal error: field 'LastUsedScriptID' will be initialized after field 'elunaEvents' [-Wreorder]
WorldObject::WorldObject(bool isWorldObject) : WorldLocation(), LastUsedScriptID(0),
```
This is necessary as preparation for including Eluna into the Travis run (see https://github.com/azerothcore/mod-eluna-lua-engine/pull/11 and #1663)
none
tested build on Ubuntu 16.04 incl. Eluna with warnings enabled, clang 7
other than the build no testing is necessary
none
Master
> fix(Core/Eluna): fix compiler warning concerning Eluna

- .travis.yml
- apps/ci/ci-error-check.sh
- apps/ci/ci-import-db.sh
- apps/ci/ci-install-modules.sh
- apps/ci/ci-worldserver-dry-run.sh
- data/travis/worldserver.conf
- Extend Travis compilation check by including some of the most popular modules.
- Change the absolute paths of the CI scripts to use environment variable "TRAVIS_BUILD_DIR". This way it is also possible to run Travis on forks.
none
see Travis runs
see Travis runs
All modules included here have to make sure that they don't throw any Travis errors. In order to check this they have to activate Travis and include (or update) this file in their repository:
https://github.com/azerothcore/skeleton-module/blob/master/.travis.yml
I already did this for beastmaster, transmog and VAS autobalance.
TODO list:
I will remove the comments in "apps/ci/ci-install-modules.sh" after each of the modules passes the Travis check.
Master
> feat(CI): Travis check modules

- apps/ci/ci-error-check.sh
- apps/ci/ci-worldserver-dry-run.sh
- data/travis/worldserver.conf
Revert the part of PR #1663 where the environment variable "TRAVIS_BUILD_DIR" is used for the dry-run. This breaks the Travis check for modules as the variable has another value there. Sorry, I did not think about this when creating #1663.
none
see Travis check
see Travis check
none
Master
> fix(CI): fix paths for dry-run check

- data/sql/updates/pending_db_world/rev_1554847609374764694.sql
Fix the event concerning Shadowlord Deathwail and the Heart of Fury (see quest "The Ata'mal Terrace", ID 10707).
- This is based on the waypoints of PR #1411 which seem to were taken from here:
https://github.com/AshamaneProject/AshamaneCore/blob/master/sql/updates/world/master/2018_04_29_04_world_2016_12_29_07_world_335.sql#L5391-L5413
I had to delete a few waypoints to create a smooth circling movement.
- It is also based on a script @poszer provided which seems to have been taken from here:
https://github.com/TrinityCore/TrinityCore/issues/21570
I had to modify some of the SAI in order to get this event running.
- I also included the scripts concerning some of the NPCs in the area:
Shadowmoon Darkweaver: Now casts "Shadow Bolt", "Immolate", "Shadowfury"
Shadowmoon Chosen: Now uses …
> fix(DB/SAI): Shadowlord Deathwail

- data/sql/updates/pending_db_world/rev_1555017745656363300.sql
- Level 1 wolves no longer drop ilvl 12-13 green items and other high value items. Aside from being incorrect, this is easily exploitable.
- Wolf pelt and bandana quest item drops are guaranteed.
- Kobold Miners now rarely drop their unique item. This is currently missing entirely from TDB.
- Bags from some NPCs have a slightly higher drop rate.
- General trash drops much less frequently.
Riverpaw Leather Vest (821) is a unique drop from Riverpaw Mongrel.
Hard Crawler Carapace (2087) is a unique drop from Sand Crawler.
Embossed Leather Vest (2300)
Didn't test yet
Master
> DB - Elwyn Forest loot

- conf/config.cmake.dist
- src/cmake/macros/FindMySQL.cmake
- src/cmake/showoptions.cmake
- src/common/Database/MySQLConnection.cpp
* Delete CMake option MARIADB
* Delete definitions (-DMARIADB)
* Added support MariaDB 10.1 / 10.2 / 10.3 / 10.4 for windows
* Replaced condition for error `CR_INVALID_CONN_HANDLE`
- Apply PR
- Rebuild core
- - **If you use WIN** replace `libmysql.dll` to `libmariadb.dll`
- Launch `worldserver` or `authserver`
> Cmake/MYSQL: Correct support MariaDB for windows

- data/sql/updates/pending_db_world/rev_1555073136028342544.sql
When finishing the Horde side of the event a distant voice yells "YOU HAVE FAILED ME, VARIMATHRAS!", but without sound sample. This is fixed with this PR.
none
tested in-game
- preparation:
```
.quest remove 13266
.quest remove 13267
.quest add 13266
.go 1955.33 242.527 41.5081 0
```
- play through the event until the end, when Varimathras is defeated the appropriate sound sample for the voice should be played
none
Master
> fix(DB/SAI): fix creature text for "Battle for the Undercity"

- data/sql/updates/pending_db_world/rev_1555051312474328059.sql
- stop combat for the Horde / Alliance defenders right before starting wapoint movement in order to prevent error messages in the server log like
```ERROR: SmartAI::StartPath: Creature entry 18948 wanted to start waypoint movement while in combat, ignoring.```
- use one of the hidden creatures "Infernal Relay (Hellfire)" to spawn an initial wave of daemons, so the battle can begin at once when the player enters the area
- reduce the spawn time of the defenders to avoid the area to be easily overrun by daemons (it can still happen, but not that often anymore)
- increase the random time interval when the defenders leave their portal, so they won't run all at once when spawning for the first time
Closes #600 
Closes #1376 
tested in-game (once started the battle will continue even if no …
> fix(DB/SAI): battle beneath the dark portal

- data/sql/updates/pending_db_world/rev_1554920580112420800.sql
Neferian Head gob in SW updated spawn time
spawntime from nef head gob in sw updated to 2 hours.
despawns after 21 seconds on current
Closes 
#1702
no errors/warnings produced in db.
.use an Alliance character and then .additem 19003
start the quest from the item
follow the quest through
head should remain for 2 hours.
Master
> Neferian head gob spawntime updated to 2 hours

- data/sql/updates/pending_db_world/rev_1555246241741494428.sql
- src/server/game/Globals/ObjectMgr.h
- src/server/game/Scripting/MapScripts.cpp
The following errors are caused by a non existing waypoint script command:
```
ERROR: Unknown script command Unknown command: 35 ('waypoint_scripts' script id: 8025100).
ERROR: Unknown script command Unknown command: 35 ('waypoint_scripts' script id: 8014900).
```
Implement "SCRIPT_COMMAND_MOVEMENT" (35) based on this TC commit:
https://github.com/TrinityCore/TrinityCore/commit/85357c75c4a202e2b7b72e14fe0d4083f74c87bb
Thanks @Meltie2013
none
tested in-game
- ```.go creature 80149```
- stay in the area for a while
- the errors mentioned above should not occur after this PR is applied
none
Master
> fix(Core): implement "SCRIPT_COMMAND_MOVEMENT" (35) to fix Defias Thug waypoint errors

- src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp
-  Removed the whelpings that were spawned as soon as the portal opens.
Closes #1081 
Compiled & tested
join a raid group with at least 2 people
.go c 126415
have 1 character go inside the portal and check for no spawned dragons while the other tanks Tenebron
Master
> [Raid] Obsidian Sancturn - Tenebron

- src/server/scripts/Spells/spell_item.cpp
Shadowmourne soul fragment spell effect 
-  Remove if the player unequip item while the effect/buff is active
-  
The issue is next, atm i'll say about Shadowmourne Axe. When you equip it, and fight someone and your spell effect/buff from weapon is activated  (In this case Soul Fragment) if you swap it with new weapon, the spell effect stay on player, doesn't get removed, which is wrong. Spell effect/buff should disappear in a moment when the player change item.
Closes 
Yes, on Win. Builded without errors, tested in game, everything looks okay now. 
The effect is removed when the item is unequiped/removed
1. Create War / Pala or DK 
2. Equip Shadowmourne
3. Attack player or dummy until the spell effect/buff get activated ( Soul Fragment ) 
4. Get some stacks ( 10 is max ) 
5. Leave combat …
> fix(CORE/Spells): Shadowmourne spell effect

- src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp
C'Thun Dark Glare spell should be casted about 4 seconds after C'Thun turns red, but is currently casting after just 1 second.
https://youtu.be/vZcR-OcrJGg?t=70
> C'Thun Dark Glare spell timer

- data/sql/updates/pending_db_world/rev_1555795494372087220.sql
Based on the existing scripts fix the mini-event playing during the quest "All Hail Roanauk!" (12140) according to this video:
https://www.youtube.com/watch?v=8IVKrt9fdY8
- set orientation of Overlord Agmar to face Roanauk Icemist
- set orientation of the Taunka Soldiers to face Roanauk and let them kneel before him
- add cheer emote to the Taunka Soldiers
- let the Taunka Soldiers return to their home position after the event ends
- prevent Overlord Agmar to get stuck waiting for the player to talk to Roanauk; Overlord Agmar will now return to his home position after 3 minutes 
none
tested in-game
- preparation:
```
.quest remove 12069
.quest remove 12140
.go creature id 26379
```
- add and complete quest "Return of the High Chief" (12069):
```
.quest add 12069
.quest complete 12069
``` …
> fix(DB/SAI): fix mini-event for quest "All Hail Roanauk!"

- src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp
- src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
- Doors not closing or opening during and after encounter
- Petrifying gaze should have a start window so the raid doesn't wipe on pull
-  Doors now close during encounter and open when over/reset
-  Petrifying gaze now has a starting window so the raid doesn't wipe when pulling
Closes #1781 
.tele ulduar
. kill XT and Flame Leviathan
. go to kologarn chamber
.engage
Master
> fix(Core/Raid): Ulduar - Kologarn

- data/sql/updates/pending_db_world/rev_1555998926077008658.sql
- cleanup phasing after the quest "Return To Angrathar" is rewarded
- add correct phasing for areas "Fordragon Hold" and "Kor'kron Vanguard"
- let the Fleeing Horde / Alliance Soldiers run around and cower in fear (the old SAI did not work correctly, the soldiers were only walking around)
none
tested in-game
**Alliance**
- ```.quest remove 12499```
- check the areas "The Court of Skulls" and "Angrathar the Wrathgate", there should be undead everywhere
- check the areas "Fordragon Hold" and "Kor'kron Vanguard" which should show the correct NPCs (especially "Highlord Bolvar Fordragon" and "Saurfang the Younger")
- ```.quest add 12499```
- ```.go creature id 27872```
- turn in the quest
- check the areas "The Court of Skulls" and "Angrathar the Wrathgate", everything should burn now, …
> fix(DB/SAI): phasing after reward for "Return To Angrathar"

- data/sql/updates/pending_db_world/rev_1555926066020418100.sql
NPC Ethereum guardian shouldn't be immune
-  Remove UNIT_FLAG_IMMUNE_TO_PC from NPC 'Ethereum guardian'.
-  
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1741
Yes, the quest can be completed now without problem.
Look in the https://github.com/azerothcore/azerothcore-wotlk/issues/1741
Master
> fix(DB/Creature): NPC Ethereum guardian

- data/sql/updates/pending_db_world/rev_1556147118750847662.sql
Use spell "Throw" (38556) instead of "Shoot" (6660) for Darkspear Spear Thrower, allowing them to launch ranged attacks.
none
tested in-game
- ```.go 4826.99 1269.52 190.221 571```
- watch them fight the undead
none
Master
> fix(DB/SAI): Darkspear Spear Thrower

- data/sql/updates/pending_db_world/rev_1556522385066705884.sql
Fix various aspects of the Skorn area:
- Winterskorn Woodsman: Use emote 'STATE_WORK_CHOPWOOD' (234) instead of 'STATE_WORK_MINING' (233)
- Various Winterskorn Vrykul: Adjust position, orientation, emotes etc.
- Disable random movement for Winterskorn Rune-Caster (23668) and Winterskorn Oracle (23669) to prevent them from falling down the towers
- Winterskorn Raider (riding on Proto-Drake): Increase flight speed by setting "move_type" to 1 (run) and allow mounted combat
- Winterskorn Shield-Maiden / Warrior / Raider / Berserker: Spar with other Vrykul and restrict talking to the sparring partners
- Quest "Burn Skorn, Burn!": Add fire effect after using the torch
- Winterhoof Brave: Set react state to defensive; cast spell "Loan Spyglass" when selecting the gossip option "Please loan me …
> fix(DB/SAI): Skorn

- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/GameObject/GameObject.h
- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
Based on this TC commit: https://github.com/TrinityCore/TrinityCore/commit/d1c3ee957962897a8b323e8ca40302fc5ff8c932
I only took over code parts concerning the visibility distance of large game objects as the visibility calculation of AC seems to be quite different from TC.
- large game objects will be handled like active objects:
visibility distance is set to MAX_VISIBILITY_DISTANCE (250.0f)
- the logic concerning Wintergrasp visibility calculation is not touched
- I tried to keep the code changes to a minimum
It looks much better to see large game objects from far away in my opinion, e.g. the demon portals in Hellfire Peninsula:
before:
after:
none
tested build (Ubuntu 16.04, Clang 7) and in-game
- GAMEOBJECT_TYPE_BUTTON (1):
```.go object 27370``` (Night Elf Moon Crystal)
- …
> fix(Core): increase visibility distance of large game objects

- data/sql/updates/pending_db_world/rev_1556709959826673022.sql
This concerns the quest "Some Make Lemonade, Some Make Liquor" (12634):
As it is now you can use the same "Sturdy Vine" many times in succession. After applying this PR the vines will correctly despawn (they respawn after ca. 5 minutes).
none
tested in-game
- preparation:
```
.quest remove 12634
.quest add 12634
.go 5611.36 5207.23 -133.34 571
```
- proceed with the quest by clicking on the vines in the area
none
Master
> fix(DB): Sturdy Vine Despawn (quest "Some Make Lemonade, Some Make Liquor")

- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_tomb_of_seven.cpp
- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp
- Swapped timers to EventMap
- 1st attacker is Anger'rel
- 2nd attacker is Seeth'rel
- 3rd Attacker is Dope'rel
- 4th Attacker is Gloom'rel
- 5th attacker is Vile'rel
- 6th attacker is Hate'rel
- 7th attacker is Doom'rel
Closes #1772 
No testes performed.
Events start Boss Doomrel ID 9039
Either one of the two choices:
1. Look on the database for the GUID on creature with entry 9039 and then do
.go c \<guid\>
2. Do the entire dungeon
Master
> fix(Core/Dungeon) BRD - The seven minibosses re-order

- data/sql/updates/pending_db_world/rev_1556953235734868559.sql
Despawn game object "Raised Mud" after using it (see quest "An Embarassing Incident", ID 12699).
none
tested in-game
- preparation:
```
.quest remove 12699
.quest add 12699
.go 5482.7  4757.96 -197.446 571
```
- dive into the lake and use the "Raised Mud" game objects there. They should despawn now and respawn after approximately 5 minutes.
none
Master
> fix(DB): Raised Mud Despawn (quest "An Embarassing Incident")

- data/sql/updates/pending_db_characters/rev_1557608218190967100.sql
-  Add a creation date column to the characters table to know when the character was created
Possible difficulties when you want to perform an action on characters created after X date.
- Added the column
- The current characters get assigned the timestamp on which the change is applied
- New characters get assigned the timestamp when they are created
- Add the column to your table
- Check the current characters
- Create a new character
None
Master
> feat(Core/DB): Add creation_date column to characters table

- data/sql/updates/pending_db_world/rev_1557180801797784400.sql
Healthy Dragon Scale should drop just after Quest ID: 5529 is completed
-  Added conditions. Item will be drop, just if the quest 5529 is completed.
-  Loot updated to 6 drop chance.
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1805
Yes, tested in game. The item is dropped just when the player have finished quest ID 5529
Read here : https://github.com/azerothcore/azerothcore-wotlk/issues/1805
Master
> fix(DB/Quest): Healthy Dragon Scale

- data/sql/updates/pending_db_world/rev_1557489332825322207.sql
The Defendo-tank 66D talks on aggro, but uses "SMART_TARGET_ACTION_INVOKER" instead of "SMART_TARGET_SELF". This is corrected through this PR.
none
tested in-game
- ```.go creature id 25758```
- attack the creature
none
Master
> fix(DB): Defendo-tank 66D - fix target of "say" action

- data/sql/updates/pending_db_world/rev_1557741075472498600.sql
Adding missing gameobject
-  Adding missing gameobject_template in DB. Entry 184981 (Poodad Trap)
-  Required for Quest https://wotlk.evowow.com/?quest=10629
The problem is that we missing creature in gameobject_template related to this quest. So, since this quest work like, yor pet have to summon gameobject after you kill creature there, and you loot them, until you loot quest item. On the first try you are able to loot it (Your pet will create it), if the quest item isn't droped, and you are trying to kill second mob, than your Pet spawn gameobject, but you are unable to loot it. Actually you are unable to click on it.
Related to this report: https://github.com/azerothcore/azerothcore-wotlk/issues/1824
```sql
2019-05-08 13:20:11 Gameobject (GUID: 2140565 Entry: 184981) not created: …
```
> fix(DB/Gameobject): Missing in DB (Giving conflicts on quest)

- data/sql/updates/pending_db_world/rev_1557742774901700400.sql
-  Set correct npc flags to 16
-  The creature is Weaponsmith Trainer (Should just teach)  [Kelgruk Bloodaxe](https://www.wowdb.com/npcs/7231-kelgruk-bloodaxe)
Related to this report : https://github.com/azerothcore/azerothcore-wotlk/issues/1824
Closes 
Yes, there is no more DB errors while interacting with this NPC.
First, test without this commit
1. Creature Horde character
2. .go creature 6613
3. Click on him (Open menu)
4. Check your DB log. 
5. Apply now commit and test again.
Master
> fix(DB/Creature); Kelgruk Bloodaxe

- data/sql/updates/pending_db_world/rev_1556980489509436556.sql
- src/server/scripts/Northrend/zone_sholazar_basin.cpp
Just a small adjustment to the core script handling the reaction of the NPCs during the quest "The Taste Test" (12645) in order to provide a better visual feedback for the player. Here's an old video showing the quest:
https://www.youtube.com/watch?v=uq_nvYpUyNA
Changes:
- use "MonsterSay" instead of "Say" for the player text and switch to broadcast text ID
- show drinking animation for the NPCs
- add knockdown effect for Hadrius (not visible in the video, but I remember this well from retail WotLK)
- increase the time interval between the NPC texts
none
tested build (Ubuntu 16.04, clang 7) and in-game
- preparation
```
.quest remove 12645
.quest add 12645
.go 5567.68 5748.04 -75.4131 571
```
- just proceed with the quest
none
Master
> fix(DB/Core): Emotes / reaction during quest "The Taste Test"

- data/sql/updates/pending_db_world/rev_1557766899660556000.sql
Fix DB errors with this creature
-  Related to this quest - https://wotlk.evowow.com/npc=27807?quest=12459
-  Scripted AI for Weakened Overseer Deathgaze
Related to this report : https://github.com/azerothcore/azerothcore-wotlk/issues/1824
```sql
2019-05-10 08:39:59 SmartScript: Action target Creature(entry: 27807) is not using SmartAI, action skipped to prevent crash.
```
Closes 
Yes, the script is fine now. No more DB errors. Many thanks to @Knindzagxg 
1. Take this [Quest](https://wotlk.evowow.com/npc=27807?quest=12459)
2. Tele to Quest location.
3. Kill first required NPC, than second NPC
4. And on third NPC (Check will you get DB errors while fighting him) - Best to test, without commit than with this commit.
Master
> fix(DB/SAI): Overseer Deathgaze SAI

- data/sql/updates/pending_db_world/rev_1557939799614685700.sql
Quest: "A Spirit Ally?" id 9847
Questitem: "Feralfen Totem" id 24498
Error: The mission item has no cd and infinite snakes can be invoked.
Simple solved:
Thanks to @solidmaxtor for the fix
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1822
I tested it myself and it worked.
Give yourself the quest quest: "A Spirit Ally?" id 9847
go to the place of the quest
try to use the quest item more than once
I hope it's all correct now.
Master
> fix(DB/Quest): A Spirit Ally QuestId 9847

- data/sql/updates/pending_db_world/rev_1557952462090372016.sql
Set Fizzcrank Bomber active when it starts moving along it's waypoint path. This should prevent dozens of bombers piling up in the air when no player is near.
Closes #1835 
tested in-game
- ```.tele fizzcrank```
- watch the bombers taking off
none
Master
> fix(DB/SAI): Fizzcrank Bomber

- src/server/game/Spells/SpellMgr.cpp
Changed the radius spell effect of following spells:
- http://wotlk.cavernoftime.com//spell=51422
- http://wotlk.cavernoftime.com//spell=57610
- http://wotlk.cavernoftime.com//spell=50999
- http://wotlk.cavernoftime.com//spell=50990
Closes #1327 
Didn't test.
1. Go to Wintergrasp and use cannon, machines
2. Cast spells mentioned and see damage radius index.
Master
> fix(Core/Spells): Fix wintergrasp spells yards

- src/server/game/Handlers/SpellHandler.cpp
This commit is related to this issue : "Chaman Reincarnation does not consume ankh #1843"
It fixed it for me.
-  Make the self_ressurection spells not triggered so it can consume reagents etc like Chaman Reincarnation spell
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1843
Tested on Win10 x64, on master branch.
1. Died, used reincarnation. `Ankh is consumed`
2. Applied Reincarnation Glyph (itemID : 43385), died, used reincarnation. `Ankh isn't consumed`
I've also compared the `WorldSession::HandleSelfResOpcode` code with TrinityCore one, and on TC the spell isn't triggered.
`_player->CastSpell(_player, spellInfo, false, nullptr);`
Make sure that the Reincarnation Glyph isn't applied (itemID : 43385).
_Before this commit :_
Go ingame with a shaman, die and use …
> fix(Core/Spells): Shaman Reincarnation

- data/sql/updates/pending_db_world/rev_1558943884011471260.sql
- despawn game object "The Gearmaster's Manual" after usage
- Despawn "Gearmaster Mechazod" after 300 seconds instead of 3000 seconds as it was before
Closes #1850 
Horde:
```
.quest remove 11909
.quest add 11909
.go 4000.06 4853.55 25.9698 571
```
- use the manual (it should despawn and respawn after ca. 5 minutes)
Alliance:
```
.quest remove 11798
.quest add 11798
.go 4000.06 4853.55 25.9698 571
```
- use the manual (it should despawn and respawn after ca. 5 minutes)
none
Master
> fix(DB/Quest): "Defeat the Gearmaster" / "The Gearmaster"

- src/server/scripts/Spells/spell_generic.cpp
Fix for mount Big Blizzard Bear
- Correctly apply 60% & 100% speed for mounts based on riding skill
-  
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1896
Yes, builded without errors. Tested in game, now everything is fine.
Read this issue : https://github.com/azerothcore/azerothcore-wotlk/issues/1896
Master
> fix(Core/Spell): Big Blizzard Bear

- data/sql/updates/pending_db_world/rev_1559215442284268490.sql
- src/server/scripts/Northrend/zone_sholazar_basin.cpp
Apply the following fixes to "Thorim's Charm of Earth" (ID 41050, provided for quest "Mending Fences"):
- allow Fjorn to be targeted by the spell "Hurl Boulder"
- summon exactly 5 dwarves at the target of "Hurl Boulder"
- the dwarves will attack Stormforged Iron Giants and Fjorn
- remove the cpp spell script and all references for "Hurl Boulder" as they are not needed anymore
Closes #1897 
- preparation:
```
.quest remove 12915
.quest add 12915
.go 7209.15 -3363.71 845.991 571
```
- pick up granite boulders
- use the item "Thorim's Charm of Earth" against Stormforged Iron Giants and Fjorn, it should now work on both NPCs
none
Master
> fix(DB/Core): Fix some issues concerning "Thorim's Charm of Earth" (Mending Fences)

- data/sql/updates/pending_db_world/rev_1559394390864887200.sql
Fixes the visibility of the Creature HC Id 20308 because this is a trigger
Boss Shirrak the Dead Watcher HC Id 20318
Zul'Aman - Jan'alai (Dragonhawk boss): Firebomb (Zul'Aman) 23920
Mount Hyjal - Archimonde: Doomfire  18095
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/897
I tested it myself and it worked.
Fix is not on the server https://youtu.be/4mlLfyIoaN8
Fix on Server https://youtu.be/uFkdy-0-8ms
Attack the Boss and wait for him to cast the spell.
Focus fire on you sets a flame appears below you
Switch the instance to HC beforehand.
.go c 83388
Master
> fix(DB/Creature): Invisibility Creature Trigger HC Boss Shirrak the Dead Watcher HC

- data/sql/updates/pending_db_world/rev_1559684382046240375.sql
Allow to dismiss the Frenzyheart companions by using their respective items:
- Goregek's Shackles
- Dajik's Worn Chalk
- Zepik's Hunting Horn
none
- preparation:
```
.additem 38619
.additem 38621
.additem 38512
.tele SholazarBasin
```
- use each of the items to call or dismiss the companion.
none
Master
> fix(DB): Dismiss Frenzyheart companion

- data/sql/updates/pending_db_world/rev_1559456042362460279.sql
- src/server/game/AI/ScriptedAI/ScriptedCreature.cpp
- src/server/game/AI/ScriptedAI/ScriptedCreature.h
- src/server/scripts/EasternKingdoms/zone_undercity.cpp
- Play "Lament of the Highborne" as music for all players in the area if "Sylvanas's Music Box" (item ID 52253) is used
- Play "Lament of the Highborne" as music for all players in the Undercity zone if the quest "Journey to Undercity" (ID 9180) is finished
- Small adjustment for the Thrall event ("Hero of the Mag'har"), which also uses "SMART_ACTION_MUSIC": Set "onlySelf" to 1 as the music should be played directly for all players in the zone. Does not need to be tested, as there is no difference, just should make it clear in the SAI script that the music is played directly.
none
"Sylvanas's Music Box":
- Either use the item
```.additem 52253```
or cast one of the summon spells directly:
```.cast 73332```
```.cast 73333```
- the …
> fix(DB/Core): Play "Lament of the Highborne" as music instead of sound

- src/server/game/Entities/Player/Player.cpp
Check quest conditions after items are equipped.
Closes #1932 
- build was successful on Ubuntu 16.04 / clang 7
test the quest mentioned in #1932, when you equip the lance while in the area "Court of Bones" you can now mount the horses, if you unequip it you cannot.
none
Master
> fix(Core): check quest conditions on item equip

- data/sql/updates/pending_db_world/rev_1559857922897245970.sql
- "Serfex the Reaver", a sand worm who is an objective of "The Underground Menace" (quest ID 12531), is now spawned in 4 random locations (see https://github.com/TrinityCore/TrinityCore/commit/e90660bab33ead6aa8b3aabfcbbdcd6a552cadd7)
- Serfex now casts poison if the player is too far away
- He now spawns submerged
none
- ```.go 4757.74 4397.78 -48.7984 571```
- look for Serfex somewhere near the river
none
Master
> fix(DB/SAI): Serfex the Reaver

- data/sql/updates/pending_db_world/rev_1559915961271940130.sql
Thalgran is the objective of quest "Returned Sevenfold" (ID 12611). As it is now his spell "Rain of Fire" will always interrupt his spell "Deathbolt", which makes it impossible to use the provided quest item "Freya's Ward" to reflect his Deathbolts. This PR fixes this.
none
- preparation:
```
.quest remove 12611
.quest add 12611
.go creature id 28443
```
- kill Thalgran by reflecting his Deathbolts
none
Master
> fix(DB/SAI): Thalgran

- src/server/game/Battlegrounds/BattlegroundMgr.cpp
I'm really not sure about this `ASSERT` put there.
First of all, in TC there is no such assertion. It was added by pussywizard in SunwellCore.
Second, both in TC and AC there are cases where `QueueSlot`  can be exactly `PLAYER_MAX_BATTLEGROUND_QUEUES`, causing crash.
For example, in `Player.h`: 
- line 975: `struct BGData`  defaults `bgTeamId` to `PLAYER_MAX_BATTLEGROUND_QUEUES`
- liune 2232: `uint32 GetBattlegroundQueueIndex(BattlegroundQueueTypeId bgQueueTypeId) const` can return `PLAYER_MAX_BATTLEGROUND_QUEUES` or any lower value.
- Closes #1756
- Make sure that BGs and their queue system still works fine
- Start, play and finish BGs
> fix(Core/BG): prevent potential crash in BG

- data/sql/updates/pending_db_world/rev_1560493947655900000.sql
- src/server/scripts/Spells/spell_warlock.cpp
Use correct spell ID for Shadow Ward (Warlock spell)
-  Set correct ID of warlock spell Shadow Ward.  It was set to -7235(Shadow Protection) which is wrong
https://wotlk.evowow.com/?spell=7235
-  Correct is to use -6229 (Shadow Ward)
https://wotlk.evowow.com/?spell=6229
- Also updated DB `world` -> `spell_script_names` to match these changes
Closes 
Yes, everything fine.
Master
> fix(Core/Spells): Correct ID of Warlock spellscript

- data/sql/updates/pending_db_world/rev_1560039329024344786.sql
This concerns catching the chickens for quest "Flown the Coop!":
- the chickens are now constantly under the effect "Scared Chicken" and will try to run away from the player
- the Frenzyheart companions cannot accidently kill the chickens anymore and have their range for "Chicken Net" increased
- despawn the chickens automatically after 3-4 minutes in order to reset chickens which get stuck or are in evade state
- prevent the chickens from attacking the player after they are catched with the net
none
- preparation:
```
.quest remove 12532
.quest add 12532
.go 5276.54 4527.16 -81.6682 571
```
- finish the quest
none
Master
> fix(DB/SAI): Chicken Escapee

- src/server/game/Spells/Spell.cpp
Spells with target "TARGET_DEST_CHANNEL_TARGET" should take over the target from the channeled spell.
Closes #1082 
- ```.tele VaultOfArchavon```
- fight against Archavon
- his spell "Rock Shards" should now follow and cause damage to a random player
none
Master
> fix(Core/Spell): Target "TARGET_DEST_CHANNEL_TARGET"

- data/sql/updates/pending_db_world/rev_1560028006349950800.sql
The creatures Sporebat+Greater Sporebat+Young Sporebat+Sporewing should occupy the player with the spell Energizing Spores at death
Creatur ID 18128,18129,18280,20387
https://db.rising-gods.de/?spell=35336#used-by-npc
https://de.wowhead.com/spell=35336/energiereiche-sporen
Closes nothing
I tested it myself and it worked.
.go c 64455
.go c 64559
.go c 72265
.go c 65571
Kill the creature and see if you got the buff.
Master
> fix(DB/Creature): FixCreature Sporebat+Greater Sporebat+Young Sporebat+Sporewing

- data/sql/updates/pending_db_world/rev_1560292934254034937.sql
This concerns the quest "The Fate of Bloodbane": The Death Knight Adepts just spawn here continuously without fighting the Ebon Blade Reapers. This is fixed through this PR:
- the Death Knight Adepts attack their owners at once after they are summoned by the Ebon Blade Reapers
- the Ebon Blade Reapers only summon a new adept on reset (after a fight and on respawn); this should prevent summoning too many adepts
Closes #1941 
- preparation:
```
.quest remove 13164
.quest add 13164
.go 5839.84 2082.33 503.951 571
```
- watch the fight; the adepts should now spawn, fight and die one after another for each Ebon Blade Reaper
none
Master
> fix(DB/SAI): Death Knight Adept mass spawn

- src/server/scripts/World/npc_professions.cpp
Fix for master blacksmithing trainer not teaching master swordsmith closes https://github.com/azerothcore/azerothcore-wotlk/issues/1965
To test , pull pr and follow testing instructions on issues post 
Tested and working on Debian 9 AzerothCore rev.  #b96a31e8+
> fix(Core/npc_professions): Swordsmith specialization

- data/sql/updates/pending_db_world/rev_1560980987673005006.sql
- src/server/scripts/EasternKingdoms/zone_undercity.cpp
- Cast the buffs from Thrall and Wrynn on themselves instead of the player. This prevents interrupting spellcasting of the player during battle.
- Override "EnterEvadeMode" for Thrall and Wrynn AI in order to prevent removing their auras on evade.
- Remove the spell script "spell_undercity_buffs" as it is not needed anymore (the players only get the aura when near Thrall or Wrynn)
none
**Horde version**
- preparation:
```
.quest remove 13266
.quest remove 13267
.quest add 13266
.go 1955.33 242.527 41.5081 0
```
- proceed with the quest
**Alliance version**
- preparation:
```
.quest remove 13371
.quest remove 13377
.quest add 13371
.go 1774.72 770.518 55.3043 0
```
- proceed with the quest
none
Master
> fix(DB/Core): "Battle for the Undercity" buffs

- data/sql/updates/pending_db_world/rev_1561127338947558444.sql
- src/server/scripts/Spells/spell_generic.cpp
As it is now the Haunted Memento just spawns a ghost who stands there, does nothing, and also never despawns. Through this PR the Spell "Haunted" (53768) is changed so it will spawn a ghost who will follow the player around slowly for a few seconds and then despawns. It will respawn every few minutes as long as the player has the aura "Haunted".
none
Just add the item:
```.additem 40110```
none
Master
> fix(Core/Spell): Haunted Memento

- data/sql/updates/pending_db_world/rev_1561242305351726648.sql
- let the Zergling fight against Grunty (50% win chance)
- add Zergling aura (will trigger attack emote every 20 seconds)
none
- First player: ```.additem 13582 (Zergling Leash)```
- Second player: ```.additem 46802 (Heavy Murloc Egg)```
- learn and summon both pets
none
Master
> fix(DB/SAI): Zergling vs Grunty

- src/server/game/AI/SmartScripts/SmartScript.cpp
Improve the logging of SmartAI action "SMART_ACTION_TALK" in order to help identify missing or wrongly triggered creature talk text. This should generally help fixing issues like #1015 or #1062.
none
- preparation:
```
.quest remove 12680
.quest add 12680
.go creature id 28653
```
- steal a horse and just run through the peasants / citizens
- in the server log similar error entries like the following should appear:
```
ERROR: SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28608 SourceType 0 EventType 4 TargetType 2 using non-existent Text id 0 for talker 28606, ignored.
ERROR: SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 28557 SourceType 0 EventType 61 TargetType 7 using non-existent Text id 0 …
```
> feat(Core/SAI): improve SAI logging for missing creature text

- data/sql/updates/pending_db_world/rev_1561274158622782000.sql
Adding missing Arena Vendors , linking creatures with Game Event ID's:
* ID: 55 - Arena Season 3
* ID: 56 - Arena Season 4
- Adding two missing creatures Drolig (ID:27722) and Drelik Blastpipe (ID: 27721) in Shattrah, They re located in the Scryer's Tier and Aldor Rise. Using free Guid's from DB (Guids: 75475, 79018).
- Linking Arena vendors from the season 3 & 4 to game event.
We are missing two creatures Drolig (ID:27722 - Scryer's Tier) and Drelik Blastpipe (ID: 27721 - Aldor Rise) spawns in Shattrah. Also, others Vendors are always visible to players which is wrong. They should be linked with the Game_Event - Seasons. If the season(event) is active, the creatures should be visible too. If the season(event) is inactive they shouldn't be visible to players.
Closes 
Yes, query imported …
> fix(DB/Creature/Event): Arena Vendors & Creatures

- data/sql/updates/pending_db_world/rev_1561378495704012800.sql
Living lasher, Mature lasher movement
- New SAI script
- Fixed issue with movements for these creatures (Living lasher, Mature lasher).
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2005
Yes. Query imported without errors. Tested in game, the creatures are standing now, and correctly move to the player in combat.
1. .go c 88233, .go c 131438
2. Enter in combat with them (Check without this commit first)
Master
> fix(DB/Creatures): Living & Mature lasher

- data/sql/updates/pending_db_world/rev_1561467004981777657.sql
- Mini Diablo: Add aura "Diablo" which causes the pet to cast a flame spell every 12 minutes
- Panda Cub: Add aura "Sleepy Pet" to allow it to occasionally fall asleep; sometimes uses "Roar" after awakening
- Sleepy Willy: Disable fly / hover as this was also not the case originally; let the pet fall asleep occasionally
none
Mini Diablo:
- ```.additem 13584```
- learn and summon the pet
- he should now cast flames every 12 minutes
Panda Cub:
- ```.additem 13583```
- learn and summon the pet
- the pet should fall asleep occasionally and sometimes use a roar emote after awakening
Sleepy Willy:
- ```.additem 32617```
- learn and summon the pet
- he should no longer be able to fly and should hover nearer to the ground; he also should now fall asleep from time to …
> fix(DB/SAI): Mini Diablo, Panda Cub, Sleepy Willy

- data/sql/updates/pending_db_world/rev_1561387934007172065.sql
- src/server/scripts/Spells/spell_item.cpp
- Argent War Horn: Summon correct version of "Argent Knight" for Horde / Alliance
- Argent Dawn Banner: Set "Argent Dawn Banner (Visual)" not selectable
- Argent Tome: Summon the Argent Tome and cast "Argent Wisdom" as it opens
none
Argent War Horn:
- ```.additem 40492```
- equip and use with Horde / Alliance player; it should summon a blood elf paladin for Horde and a human paladin for Alliance
Argent Dawn Banner:
- ```.additem 40601```
- equip and use the item; the banner should now be not selectable
Argent Tome:
- ```.additem 40593```
- equip and use the item; the tome should now appear and cast it's spell as it opens
none
Master
> fix(DB/Spell): Argent Dawn trinkets

- data/sql/updates/pending_db_world/rev_1561541013574518977.sql
As it is now you can complete the quest "When All Else Fails" (Horde: 13060, Alliance: 12862) but there are just 2 gossip options "I am ready to head further into Storm Peaks." which don't do anything. This is fixed through this PR which is based on the TC commit https://github.com/TrinityCore/TrinityCore/commit/7c7029c25c9f07ae6ec14c44cdea75c2cb935499 (I just omitted the delete/insert statements for table "gossip_menu_option", because the AC database already contains the data).
none
tested successfully in-game with both a Horde and Alliance character
Horde:
- preparation:
```
.quest remove 13060
.quest remove 12824
.quest add 12824
.quest complete 12824
.quest reward 12824
.go creature id 29428
```
- accept quest "When All Else Fails" from Ricket
- choose "I am ready to head further into …
> fix(DB/SAI): quest "When All Else Fails"

- data/sql/updates/pending_db_world/rev_1561816769087112416.sql
- src/server/game/Pools/PoolMgr.cpp
- src/server/game/Pools/PoolMgr.h
This is basically the implementation of this TC commit: https://github.com/TrinityCore/TrinityCore/commit/022575329ff6766485ccddb2053820326a6664bf :
- use "std::unordered_map" instead of "std::vector" in order to reduce memory usage (not much, perhaps 5-10%)
- identify missing pool entries in pool_template via error messages in the server log
Concerning the pool entries I applied the following fixes as they would now cause errors:
- Remove pool entry 5217 from pool_gameobject (only 1 game object "Saronite", not needed here)
- Remove pool entry 1047 from pool_creature (only 1 creature "Hematos", not needed here)
- Add a few missing Saronite nodes to pool_template
none
- without applying the SQL script: check the startup …
> feat(Core/Pool): improve pool manager

- data/sql/updates/pending_db_world/rev_1561842370323631350.sql
Remove on aggro text "Light bless you, my child." for "Scarlet Medic" and "Scarlet Infantryman".
none
either
- ```.go creature id 28608```
- ```.go creature id 28609```
or
- ```.npc add temp 28608```
- ```.npc add temp 28609```
None of the creatures should say the text "Light bless you, my child." on aggro anymore.
none
Master
> fix(DB/creature_text): "Scarlet Medic" / "Scarlet Infantryman"

- data/sql/updates/pending_db_world/rev_1561905129740963200.sql
**CHANGES PROPOSED:**
This fix should prevent the player from opening or closing the gates with a right click.
Since the gates open when the gatekeepers die. 
**ISSUES ADDRESSED:**
none
**TESTS PERFORMED:**
Before and after https://youtu.be/pG7YPZw7Szk
**HOW TO TEST THE CHANGES:**
.go c 83173 gates
.go c 83239 gatekeepers 
.go c 83240 gatekeepers 
**KNOWN ISSUES AND TODO LIST:**
none
Master
> Fix (DB/gameobject): Faction+flags ID 184632

- data/sql/updates/pending_db_world/rev_1561967531437429600.sql
High Overlord Saurfang
-  Adding UNIT_FLAG_IMMUNE_TO_NPC (disables combat/assistance with NonPlayerCharacters (NPC)) to creature High Overlord Saurfang in icc.
-  
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1990
Yes, the creature is fine now. No more DB errors, no more combat with mobs around.
1. .go c 200984
2. Pull mobs there, and move to Saurfang
3. Before when we do that, he enter in combat, and giving us DB errors about wrong text.
4. Now, he's unable to enter in combat, and we don't have anymore this issue.
Master
> fix(DB/Creature): High Overlord Saurfang

- data/sql/updates/pending_db_world/rev_1561997614685609600.sql
Razorscale Harpoon Fire State
- Adding flags_extra 128	CREATURE_FLAG_EXTRA_TRIGGER creature is trigger-NPC (invisible to players only). 
-  It already have flags_extra set to 2 | CREATURE_FLAG_EXTRA_CIVILIAN | 0x00000002 | creature does not aggro (ignore faction/reputation hostility)
- At the end it's set to flags_extra=130.
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2035
Yes, it should be invisible to players. It's trigger
Master
> fix(DB/Creature): Razorscale Harpoon Fire State

- src/server/game/Server/WorldSession.cpp
The status of the accounts in the database is always "online" after disconnection.
Yes, everything fine.
Log out of your account, the online column will change to 0 after one minute :)
Master
> fix(Core): Online status of accounts

- data/sql/updates/pending_db_world/rev_1562110333242304237.sql
- Culling of Stratholme: Apply random movement instead of waypoint movement in order to prevent log errors for these creatures: Bile Golem, Crypt Fiend, Devouring Ghoul, Patchwork Construct
- Utgarde Keep: Apply correct waypoint path for Prince Keleseth
- Fix Rocknar SAI link error
- Fix Impaled Valgarde Scout SAI link error (quest "Rescuing the Rescuers")
- Utgarde Pinnacle: Fix Ymirjar Flesh Hunter SAI link error in Normal difficulty; fix using "Aimed Shot" in Heroic difficulty
Fixes part of #1062 
**Culling of Stratholme:**
- ```.go creature 1970989``` (Bile Golem)
- just look around for the other creatures, they should now move randomly: Crypt Fiend, Devouring Ghoul, Patchwork Construct
- there should be no errors like these anymore:
``` …
```
> fix(DB/SAI): fix movement / SAI errors

- data/sql/updates/pending_db_world/rev_1562149079104513383.sql
- make the Ebon Blade Prisoners non-attackable
- reset Jotunheim Cage after 5 minutes instead of 10 in order to sync with the Ebon Blade Prisoner respawn
- Jotunheim Warrior, Njorndar Spear-Sister and Mjordin Water Magus have to use "SMART_TARGET_SELF" instead of "SMART_TARGET_ACTION_INVOKER" for their talk action
fixes part of #1062 
- preparation:
```
.go 7706.52 3439.86 656.132 571
.additem 42422
```
- the Mjordin Water Magus should no longer attack the Ebon Blade Prisoner
- after opening the cage and freeing the Ebon Blade Prisoner the cage and the prisoner should respawn at the same time (ca. 5 minutes)
- there should be no errors like this anymore:
```
CreatureTextMgr: Could not find Text for Creature(Ebon Blade Prisoner) Entry 30186 in 'creature_text' …
```
> fix(DB/SAI): fix a few issues for Jotunheim

- src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp
Fix text error when Grauf ist taken down with the harpoons.
This PR together with #2022, #2041 and #2047 should finally conclude #1062
- ```.go creature id 26693```
- fight against Skadi
- after killing Grauf Skadi should now yell "You motherless knaves! Your corpses will make fine morsels for my new drake!"
- there should be no errors like this anymore:
```
CreatureTextMgr: Could not find TextGroup 4 for Creature(Grauf) GuidLow 2029953 Entry 26893. Ignoring.
```
none
Master
> fix(Core/CreatureScript): fix Skadi / Grauf text error

- data/sql/updates/pending_db_world/rev_1562237566436595766.sql
- Increase cooldown for "War Horn of Jotunheim" from 30 to 500 seconds to match the despawn timer from "Overthane Balargarde", which is also 500 seconds.
- Set "Overthane Balargarde" active after he is summoned to ensure that he will despawn after 500 seconds even if no player is around anymore.
Closes #2030 
- preparation:
```
.quest remove 13142
.quest add 13142
.go 7073.64 4311.24 870.989 571
```
- use the War Horn; after using it it should not be possible to use it again for 500 seconds
- Overthane Balargarde should disappear after 500 seconds, no matter if a player is near or not
none
Master
> fix(DB/SAI): Overthane Balargarde

- src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
Fixes cast speed of Hodir ice shards in 10 man
CHANGES PROPOSED:
Adjust cast cooldown of ice shards based on 10 or 25 man (really a toggle based on if it is greater than 15 man)
Imports mapManager.h to identify the maximum players
ISSUES ADDRESSED:
Closes azerothcore#1938
Compiled on windows 7 64 bit, tested fighting hodir, saw the icicle spawn rate was approximately once every 4 seconds like on the linked video from official
Go fight hodir in ulduar, watch the spawn speed of the ice shards
KNOWN ISSUES AND TODO LIST:
[ ]
[ ]
Master
> fix (Core/Boss Scripts) Update boss_hodir.cpp - Fix ice shards cast speed in 10 man

- data/sql/updates/pending_db_world/rev_1562252728718185214.sql
- src/server/game/Spells/SpellMgr.cpp
Instead of a blue/white checkered cube the Dragonflayer Strategist now hurls a throwing knife if casting "Hurl Dagger".
Fixes part of #2101
- ```.go 325.466 247.177 30.7478 574```
- the Dragonflayer Strategist should know correctly hurl a throwing knife at the player when casting "Hurl Dagger"
none
Master
> fix(DB/Core): Dragonflayer Strategist spell "Hurl Dagger"

- src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
Description : https://github.com/azerothcore/azerothcore-wotlk/issues/2065  (Warsong flags can be picked up while mounted...)
-  DisMount Player while Pickedup Flag
-  
Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/2065
Tested in Game
win 10 vs 2017
Master
> fix(Core/Battleground): Warsong flags can be picked up while mounted

- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
- Should fix issue with not spawned
Boss Urom teleporting issue
-  Updated
-  
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1957
Yes, builded without errors. Tested in game 15 Runs, for me it works fine. In all 15 runs , the Boss is correctly teleported, spawned.
1. Do 5H dungeon several times
Master
> fix(Core/Boss): Boss Urom

- data/sql/updates/pending_db_world/rev_1562421937870171000.sql
This its fix to: #2045 Thanks to solidmaxtor for the fix
CHANGES PROPOSED:
Fix Deletes false prey from Emalon Storm Watcher
ISSUES ADDRESSED:
Closes #2045
I tested it, and the loot's gone.
How reproduce
Tele Vault to Archavon
kill emalon
well loot its random for many items check id in DB its more fast =)
Master
> fix(DB/reference_loot_template): Loot error

- data/sql/updates/pending_db_world/rev_1562666306247342200.sql
**CHANGES PROPOSED:**
The fix should cause the event to start after the quest The Emitter ID 9312 has ended. 
The old smart_script is deleted because it does not belong to the NPC.
It belongs to the NPC with the ID 16514 which also has the script.
Before Fix https://youtu.be/US-QM6TTKiE
After Fix https://youtu.be/tZ1vvufOaac
**ISSUES ADDRESSED:**
none
**TESTS PERFORMED:**
**HOW TO TEST THE CHANGES:**
.go c 7978
.quest add 9312
Pass the quest and look at the holographic emitter.
The script should now start
KNOWN ISSUES AND TODO LIST:
none
Master
> fix(DB/SAI): Technician Zhanaa's script on quest turn-in

- data/sql/updates/pending_db_world/rev_1562779174835710547.sql
- src/server/scripts/Outland/zone_netherstorm.cpp
- src/server/scripts/Outland/zone_shattrath_city.cpp
Co-authored-by: Pondaveia Pondaveia@users.noreply.github.com
Implement the event which takes place during the "Deathblow to the Legion" quest. This is based on PR #1834 but had to be heavily modified as the original scripts contained many bugs and inconsistencies.
Closes #470
Alliance quest "Deathblow to the Legion":
- preparation:
```
.quest remove 10409
.quest add 10409
.go 4773.160645 3450.580322 105.150002 530
```
- follow the quest by using "Socrethar's Teleportation Stone" and then talk to Adyen
Please also test the Horde version "Turning Point":
- preparation:
```
.quest remove 10507
.quest add 10507
.go 4928.93 3823.68 211.483 530
```
- kill Socrethar (you can use "Voren'thal's Presence" to weaken him)
none …
> fix(DB/CreatureScript): Deathblow to the Legion

- data/sql/updates/pending_db_world/rev_1560396171418694700.sql
- src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp
Co-authored-by: Andrei-UPB Andrei-UPB@users.noreply.github.com
Co-authored-by: GMKyle GMKyle@users.noreply.github.com
Nexus Raid Platform no longer collapses on the first Saronite Bomb use
CHANGES PROPOSED:
Modify Nexus Raid Platform's health from 100 to 6.000.000, thus making it way harder to break
ISSUES ADDRESSED:
Closes #1948
Tested, the platform now breaks upon taking 6.000.000 damage ( an unreachable ammount by normal standards) rather than on 100 damage.
A saronite bomb does 150 siege damage, 25 players using Saronite Bombs on cooldown and considering 11 saronite bombs can be used before Malygos enters berserk mode (10 min), the maximum damage that will be dealt to the platform will be 41.250, if we add in Global Thermal Sapper Charges -250 siege damage per use, it …
> fix(DB/gameobject): Band-aid fix for Malygos platform

- src/server/game/Handlers/ChannelHandler.cpp
Fix client game crash with invite player to invalid name for Channel.
```CMSG_JOIN_CHANNEL [Player: Testguys GUID Full: 0x00000000000042f0 Type: Player Low: 17136, Account: 6287] Channel: 1, unk1: 1, unk2: 0, channel: ÐžÐ±Ñ‰Ð¸Ð¹: ÐŸÐ¾Ð»ÑƒÐ¾ÑÑ‚Ñ€Ð¾Ð² ÐÐ´ÑÐºÐ¾Ð³Ð¾ ÐŸÐ»Ð°Ð¼ÐµÐ½Ð¸, password: 
CMSG_JOIN_CHANNEL [Player: Testguys GUID Full: 0x00000000000042f0 Type: Player Low: 17136, Account: 6287] Channel: 2, unk1: 1, unk2: 0, channel: Ð¢Ð¾Ñ€Ð³Ð¾Ð²Ð»Ñ: ÐŸÐ¾Ð»ÑƒÐ¾ÑÑ‚Ñ€Ð¾Ð² ÐÐ´ÑÐºÐ¾Ð³Ð¾ ÐŸÐ»Ð°Ð¼ÐµÐ½Ð¸, password: 
CMSG_JOIN_CHANNEL [Player: Testguys GUID Full: 0x00000000000042f0 Type: Player Low: 17136, Account: 6287] Channel: 22, unk1: 1, unk2: 0, channel: ÐžÐ±Ð¾Ñ€Ð¾Ð½Ð°: ÐŸÐ¾Ð»ÑƒÐ¾ÑÑ‚Ñ€Ð¾Ð² ÐÐ´ÑÐºÐ¾Ð³Ð¾ ÐŸÐ»Ð°Ð¼ÐµÐ½Ð¸, password: 
CMSG_JOIN_CHANNEL [Player: Testguys GUID Full: …
```
> Fix client game crash with invite player to invalid name for Channel.

- src/server/scripts/Outland/zone_blades_edge_mountains.cpp
NPC Kaliri totem despawn on [Quest](https://wotlk.evowow.com/?quest=10556) complete
- Correctly despawn NPC Kaliri totem when the quest is completed.
-  
Closes Nothing. Issue is next, when you do this quest, and complete it, the Quest NPC remain to player which is incorrect. NPC should be despawned on quest complete.
Yes, builded without errors on Win. Tested in game. the Creature is correctly despawned now.
1. .quest add 10556
2. .go xyz 1613.3148 6935.7812 159.1015
3. Use there [Quest Item](https://wotlk.evowow.com/?item=30530), in that circle.
4. Now escort that NPC to the Quest location -> (Check without/with this commit).
Master
> fix(Core/Quest): Scratches

- data/sql/updates/pending_db_world/rev_1563920358511875161.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- Remove unused parameter "team" (action_param2) from action type "SMART_ACTION_UPDATE_TEMPLATE"
- invert parameter "doNotChangeLevel" (now: updateLevel) and move it from action_param3 to action_param2 (which is now equal to TC's version of the action type)
none
- ```.go -346.584 1402.88 30.2519 0```
- switch the event "Pyrewood Village" on and off:
```.event start 25```
```.event stop 25```
- the transforming Pyrewood Villagers should always stay on the same level
- ```.go -3542.92 2642.02 88.6888 1```
- cast "Transmogrify!" on the Mountain Giants:
```.cast 23359```
- they should sometimes change their level after becoming non-elite
none
Master …
> fix(Core/SAI): fix parameters for action type "SMART_ACTION_UPDATE_TEMPLATE"

- README.md
This gives more visibility to our chat, since some users struggled to find it.
> chore(README.md): add Discord badge

- apps/ci/ci-install-modules.sh
- src/server/game/Battlegrounds/BattlegroundQueue.cpp
- src/server/game/Battlegrounds/BattlegroundQueue.h
- src/server/game/Handlers/BattleGroundHandler.cpp
- src/server/game/Handlers/ChatHandler.cpp
- src/server/game/Handlers/MiscHandler.cpp
- src/server/game/Handlers/QueryHandler.cpp
- src/server/game/Scripting/ScriptMgr.cpp
- src/server/game/Scripting/ScriptMgr.h
- Finally, PR, which adds support for the module [mod-cfbg](https://github.com/Winfidonarleyan/mod-cfbg)
(A little humor, in connection with the recent events 👍 )
-  Added support `mod-cfbg` module
1. Apply this PR
2. Added module [mod-cfbg](https://github.com/Winfidonarleyan/mod-cfbg)
3. Enable system
> feat(Core/CFBG): Added support module mod-cfbg

- src/server/game/Server/WorldSession.cpp
- Fix issue with instance reset exploit
Co-Authored-By: Lee <talamortis@users.noreply.github.com>
-   Instead of doing this how tc did it (complicated) it's done in simple way.
-  
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2073
Yes, everything is fine.
Master
> fix(Core/Instance): Fix instance resetting exploit

- src/server/scripts/Commands/cs_modify.cpp
With display_id > 65535, the morph command just doesn't work
-  change uint16 to uint32
Create display_id > 65535 in your creaturedisplayinfo.dbc and apply .morph it before and after the proposed changes.
Master
> Support .morph uint32 ids

- data/sql/updates/pending_db_world/rev_1564352943601377944.sql
Add random movement to "Icemaw Bear" and "Ravenous Jormungar" in the Hibernal Cavern. This will cause both creatures to fight each other.
none
successfully tested in-game
- ```.go 7146.51 -2137.52 761.844 571```
- test both phases there:
```.modify phase 1```: "Icemaw Bear" and "Ravenous Jormungar" should fight each other and move around randomly
```.modify phase 4```: "Ravenous Jormungar" should move around randomly
none
Master
> fix(DB/creature): Random movement for "Icemaw Bear" and "Ravenous Jormungar"

- src/server/game/Spells/SpellInfo.cpp
Fixing Magmadar's Enrage spell
-  Putting the Magmadar's Enrage spell as a Buff to make it dispelable.
Closes #2129 
Dispelled Magmadar's Enrage successfully with Tranquilizing shot.
Windows 10.
Master
> (Core/SpellInfo.cpp) Magmadar's Enrage dispel fix

- src/server/game/Battlegrounds/BattlegroundQueue.cpp
Fix compile error C3848 - expression having type 'type' would lose some const-volatile qualifiers in order to call 'function'
Some compilers will throw this errors, some won't (e.g. VS 2013 doesn't, VS 2019 does.)
> fix(Core): Fix build - C3848 compile error

- data/sql/updates/pending_db_world/rev_1564613018254939406.sql
- Fix errors like the following which are caused by dismounting the initial Proto-Drake you get during the quest "The Drakkensryd".
```ERROR: Vehicle GuidLow: 5011278, Entry: 29679 attempts to uninstall, but already has STATUS_UNINSTALLING! Check Uninstall/PassengerBoarded script hooks for errors.```
- Summon the initial Proto-Drake at the same position as the Proto-Drake near Gretta the Arbiter.
- Add a few more waypoints to the path of the initial Proto-Drake in order to fly around the Temple of Storms. This gives the player more time to actually use the Hyldnir Harpoon.
- If using the Hyldnir Harpoon on the Column Ornaments the player will slowly hover to the ground automatically (as it was before the player will get mounted on the Column Ornament and just gets stuck in the air if he …
> fix(DB/SAI): The Drakkensryd

- src/server/game/AI/ScriptedAI/ScriptedEscortAI.cpp
- src/server/game/AI/ScriptedAI/ScriptedFollowerAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Miscellaneous/SharedDefines.h
- src/server/game/Spells/Spell.cpp
Closes #1984
add a missing condition in Spell:SelectImplicitTrajTargets when creature has flag CREATURE_TYPE_FLAG_CAN_COLLIDE_WITH_MISSILES
> Creature type flags

- .travis.yml
Reason: no one is using it at the moment so we don't have to bother with merge conflicts.
When needed, we can restore it again.
> chore(CI): disable staging branch

- src/server/game/Spells/Spell.cpp
- Partially reverts https://github.com/azerothcore/azerothcore-wotlk/commit/7954a2a07ed1af2eb050f9252d3d2c3d7dab7e1f
(such Spell changes were commited by mistake)
> fix: revert unwanted Spell changes

- data/sql/updates/pending_db_world/rev_1564814353928512372.sql
- Fix the Stoneskin Gargoyles in Naxxramas leaving their Stoneskin form (actually their submerged stand state) when attacking.
- Add a few waypoints to the path of the gargoyle patrolling the stairs in order to prevent bunny-hopping.
none
- ```.go 2846.13 -3489.35 297.853 533```
- follow the gargoyle patrolling the stairs
- attack the moving and standing gargoyles
none
Master
> fix(DB/SAI): Stoneskin Gargoyle (Naxxramas)

- conf/config.sh.dist
-  Replace '127.0.0.1' with 'localhost' in the db-assembler script to make MySQL happy
- Tested on a clean Ubuntu environment (with no initial DBs)
> fix(db-assembler): error 'cant find any matching row in the user table'

- src/server/authserver/Main.cpp
Changes:
- improved the error shown when the authserver port is invalid (showing the name of the parameter and the actual invalid value)
- showing the bind ip address and the port that the authserver is listening to
There is no need to test since these are cosmetic changes that just add some logs, there is no way they break anything (and I have tested them locally).
> chore(authserver): improve startup console logs

- data/sql/updates/pending_db_world/rev_1564842659519525022.sql
Fix the quest "Keeping Pace", as it was missing the small event taking place when you ask Zamek about the distraction. This fix was taken from here:
https://github.com/TrinityCore/TrinityCore/commit/1560224d73085801fbde85056bb1117905d1308c
I just removed the statements about the creature texts, as AC already had those.
none
- preparation:
```
.quest remove 1190
.quest add 1190
.tele mirageraceway
```
- talk to Zamek about the distraction and then just follow the quest
none
Master
> fix(DB/SAI): Quest "Keeping Pace" (Zamek's Distraction)

- src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_scourgelord_tyrannus.cpp
more description #2106
boss not attackable before starting
-  
-  
Closes #2106
Master
> fix(Core/Dungeon): Scourgelord Tyrannus died mid-air. Body got stuck mid-air and can't be looted

- data/sql/updates/pending_db_world/rev_1566600036032917597.sql
- src/server/game/Entities/Vehicle/Vehicle.cpp
- src/server/game/Handlers/ItemHandler.cpp
- Increase the reputation reward for the "Sons of Hodir" quests by 30%, as it was mentioned in the 3.3.0 patch notes:
https://wow.gamepedia.com/Patch_3.3.0#Reputation
- King Jokkum is now only visible in phase 4 in Dun Niffelem
- Quest "Battling the Elements":
- Reduce respawn time from 300 to 10 seconds for the Seething Revenants
- Change faction to "Sons of Hodir" for the Frost Giant Stormheralds (they are trying to cool the anvil) and remove one of them who stands too far away from the anvil
- Quest "In Memoriam": Apply correct phase mask to the Horn Fragments (otherwise the quest cannot be completed)
- Ensure that the quest "A Monument to the Fallen" has to be finished before "Blowing Hodir's Horn" becomes available
- Hide "Hodir's Helm", "Hodir's Spear" and "Hodir's Horn" until their …
> fix(DB/Core): "Sons of Hodir" quests / areas

- data/sql/updates/pending_db_world/rev_1566945787997948952.sql
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/scripts/Spells/spell_hunter.cpp
- Ensure that the creature is only charmed after channeling the spell for the full time (as it was before it was charmed even when interrupting the spell).
- Force despawn after the creature is dismissed (either manually or when the spell runs out or when the creature is out of range). This ensures that it is correctly reset by respawning it at it's home position after 5 minutes.
- The creature should not despawn after the quest is turned in. Instead the player gets a qualified error message when trying to tame a new creature while still having the old one.
Closes #1073
- Dwarf quests
```
.q a 6085
.go c id 1196
.q a 6064
.go c id 1126
.q a 6084
.go c id 1201
```
- Tauren quests
```
.q a 6061
.go c id 2956
.q a 6087 …
```
> fix(Core/Spell): "Taming the Beast" hunter quests

- data/sql/updates/pending_db_world/rev_1566257693610996077.sql
- src/server/game/Spells/SpellMgr.cpp
- Remove wrong SAI for "Infesting Jormungar"
- Fix spell "Jormungar Bite" to target enemies (otherwise the jormungars just damage themselves)
- Add a few more Cavedweller Worgs to fight against the jormungars and bolster their numbers in the worg lair (they are necessary for the quest "Emergency Measures")
- Add a few more Cave Mushrooms for quest "Cave Medicine"
- Add "Permanent Feign Death" to 3 of the jormungars in the worg lair and add a "feeding" emote to the worgs adjacent to them
none
- ```.go 7573.15 -1482.65 978.402 571```
- just check out the cave
none
Master
You can help by testing PRs and writing your feedback here in the PR's …
> fix(DB/Creature): Gimorak's Den

- data/sql/updates/pending_db_world/rev_1567460303929588791.sql
- After accepting the quest "The Summoning" Bath'rah should run to the summoning place, only walking the last part of the path.
- After finishing the movement he should change his orientation, play the "bow" emote and then start the summoning.
- After the summoning he should run back to his home position and use the same orientation he had before.
none
- preparation using a warrior character:
```
.q rem 1712
.q rem 1713
.q a 1712
.q c 1712
.go c id 6176
```
- proceed with the quest
none
Master
> fix(DB/SAI): Bath'rah the Windwatcher

- data/sql/updates/pending_db_world/rev_1567608091409034200.sql
- Fix some issues concerning the vehicle "Xink's Shredder" provided for the Quest "Lumber Hack":
- Ensure that the vehicle spell "Twisting Blade" cannot target itself or the player.
- Add emotes when summoning and dismissing the shredder.
- Disable random movement for "Zivlix's Destruction Machine" at Nozzlerust Post.
none
- preparation:
```
.q rem 12050
.q a 12050
.go c id 26660
```
- proceed with the quest, check the emotes of the shredder and try to use "Twisting Blade" without a target
- also check "Zivlix's Destruction Machine" at Nozzlerust Post
none …
> fix(DB/Quest): Lumber Hack

- CMakeLists.txt
- deps/CMakeLists.txt
- deps/acelite/ace/CMakeLists.txt
- deps/bzip2/CMakeLists.txt
- deps/fmt/CMakeLists.txt
- deps/g3dlite/CMakeLists.txt
- deps/gsoap/CMakeLists.txt
- deps/jemalloc/CMakeLists.txt
- deps/libmpq/CMakeLists.txt
- deps/recastnavigation/Detour/CMakeLists.txt
- deps/recastnavigation/Recast/CMakeLists.txt
- deps/zlib/CMakeLists.txt
- src/cmake/compiler/clang/settings.cmake
- src/cmake/compiler/gcc/settings.cmake
- src/cmake/compiler/icc/settings.cmake
- src/cmake/compiler/mingw/settings.cmake
- src/cmake/compiler/msvc/settings.cmake
- src/cmake/macros/ConfigureBaseTargets.cmake
- src/cmake/platform/unix/settings.cmake
- src/common/CMakeLists.txt
Co-authored-by: Naios <Naios@users.noreply.github.com>
Based TC commit https://github.com/TrinityCore/TrinityCore/commit/e60c1f84a7e13577a82046b02b214f9466d20a7c
- Remove the usage of global flags and definitions
set through the CMAKE_CXX_FLAGS variable.
- Use cmake target compile features for setting the
CXX standard automatically.
- Closes
- Build this
> feat(Cmake/Build): Use interface targets for inheriting flags and definitions

- src/server/scripts/Outland/zone_shadowmoon_valley.cpp
After feeding a drake during the quest "Kindness" it should fly away and continue it's waypoint movement instead of just hovering in the air.
#2267
Tested successfully in-game
- preparation:
```
.q rem 10804
.q a 10804
.ad 31372 8
.go -4095.99 809.262 2.43068 530
```
- just proceed with the quest; after being fed the drakes should now continue their waypoint movement; please note that after feeding a drake it gets the aura "Has Eaten Recently" preventing it to be fed for 1 minute
none
> fix(Core/CreatureScript): Quest "Kindness"

- src/cmake/showoptions.cmake
- src/server/worldserver/CMakeLists.txt
Use [cmake-generator-expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html) for escaping quotation marks. This should fix the latest compile errors and render the PRs #2303 and #2305 obsolete.
Closes #2306
tested build on Ubuntu 16.04 / clang 7 with PCH (pre-compiled headers) turned on via the following cmake options:
```-DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1```
Compile using the following cmake options:
```-DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1```
> fix(CMake): Use cmake-generator-expressions for escaping quotes

- data/sql/updates/pending_db_world/rev_1568496805410616069.sql
Reduce the respawn time of "Tallonkai's Dresser" used for the quest "The Emerald Dreamcatcher" in order to allow other party members to loot the item.
Closes #2256
- preparation:
```
.q rem 2438
.q a 2438
.go 9814.81 353.474 1308.46 1
```
- proceed with the quest; the game object should not vanish anymore
none
> fix(DB/gameobject): Tallonkai's Dresser

- data/sql/updates/pending_db_world/rev_1568383989969278689.sql
- Set Marid active after the player selects the gossip option concerning quest "Troublesome Distractions" and despawn him 5 minutes after he reached the destination of his path (this ensures that the NPC is reset if the player decides to just run away or log out).
- Cleaned up the SAI a bit and updated the comments.
- Prevent the following error in the server log, which was caused by a bug in the old SAI script:
```
ERROR: SmartScript::ProcessAction: Entry 20071 SourceType 0, Event 0, Link Event 1 not found or invalid, skipped.
```
none
- preparation:
```
.q rem 10273
.q a 10273
.go 4285.85 2231.63 124.217 530
```
- proceed with the quest and just run away; Marid should reset after ca. 5 minutes
none …
> fix(DB/SAI): Wind Trader Marid

- src/cmake/ac_macros.cmake
Currently there are 2 conflicting modules:
mod-transmog
mod-weapon-visual
Both use "OnLogin" to apply their visual modifications, but the modifications of "mod-transmog" have to be executed before "mod-weapon-visual". This PR introduces additional optional arguments for the cmake macro "AC_ADD_SCRIPT_LOADER" which can contain script names which should be handled with lower priority. This way it is possible to ensure that the scripts of one module are always executed before the other specified module scripts.
This will in no way affect existing behaviour, only if the additional arguments are specified.
none
tested successfully on Ubuntu 16.04 with cmake version 3.15.4
I tested it using these modules, but it can be tested with any combination of modules:
- mod-autobalance
- …
> feat(cmake/macro): Allow scripts to lower prioritize other scripts

- data/sql/updates/pending_db_world/rev_1568988467237730140.sql
- src/server/scripts/Spells/spell_item.cpp
- Remove a wrong emote played while using the "Oracle Talisman of Ablution" (every time you kill an enemy which grants the spell effect the emote about the "Titanium Seal of Dalaran" was played).
- Use broadcast text for the emotes of the "Titanium Seal of Dalaran" (text was hard-coded before).
- Use broadcast text for the emotes of "Fish Feast", "Great Feast", "Small Feast" and "Gigantic Feast".
none
- ```.au 59787``` (or alternatively use "Oracle Talisman of Ablution", ID 44074):
- there should no longer occur an emote about the "Titanium Seal of Dalaran" if you kill enemies.
- ```.ad 44430```:
- use the item: It should now display the emotes in the correct language with the correct gender.
- Use each of the feasts: …
> fix(Core/spell_item): Fix a few items with spell effects

- bin/acore-docker-build-no-scripts
- docker/build/Dockerfile
This PR allows to build AC in Docker having scripts disabled.
This can be useful for a faster build for a non-production server, that can be used in travis or for any other reason.
> feat(docker): allow building without scripts

- data/sql/updates/pending_db_world/rev_1568644079531382202.sql
Remove one of the two duplicate gossip options "The Horde Quarter" when asking NPCs about class trainers.
none
- ```.tele dalaran```
- just speak with the NPCs, asking for directions to the class trainers; there should now be no duplicate entry anymore concerning the Horde quarter
none
> fix(DB/gossip_menu_option): Gossip Dalaran NPCs

- data/sql/updates/pending_db_world/rev_1568644505350490588.sql
This is related to PR #1719. The initial wave of demons did not attack if the player just triggered the spawn, but then moves out of reach. This is fixed by setting the initial Wrath Masters active.
none
- ```.go -248.322 934.786 84.3793 530```
- just fly as GM over the intial wave of demons and continue to the Path of Glory until out of reach; wait a bit and return: The battle should have been started even without a player around.
none
> fix(DB/SAI): Battle beneath the Dark Portal, part 2

- data/sql/updates/pending_db_world/rev_1569531971839824730.sql
The Fel Reaver should use War Stomp in combat.
none
- `.go creature id 18733`
- fight against the Fel Reaver; he should now use War Stomp every 12-25 seconds
none
> fix(DB/SAI): Fel Reaver

- src/tools/mmaps_generator/MapBuilder.cpp
Get the mmaps_generator working with MapID >= 1000.
mmaps_generator doesn't work with maps that have MapID >= 1000, theses changes will fix it.
-  See pull request
The issue was that the mmaps_generator doesn't generate the mmaps properly when MapID is above 999. (length of MapID > 3)
Noticed that I've 3 custom maps : 996, 1514 and 1600.
Everything is fine with 996 (generating 996.mmap and 996YYXX.mmtile)
For map 1514 and 1600, it generate : 151.mmap, 151YYXX.mmtile and 160.mmap and 160YYXX.mmtile
The "problem" is that the tool is overriding files, so imagine if you've a custom map with ID 5710, it'll create 571.mmap and 571YYXX.mmtile instead of 5710.mmap and 5710YYXX.mmtile. In consequence, it'll override Northrend (MapID 571) mmaps.
Build without errors.
Mmaps working fine in-game : …
> feat(MMAPS/mapbuilder): mmaps_generator now working with MapID >= 1000

- data/sql/updates/pending_db_world/rev_1570401436494865858.sql
Added Emerald Dream game_tele and the instance Emerald Dream ID:169
Apply the sql code in this PR.
Use the following commands:
```
.tele EmeraldDream
.tele EmeraldStatue
.tele VerdantFields
.tele EmeraldForest
```
See the different zones ;-)
To see the Emerald Dream zone with textures use [this patch](https://mega.nz/#!59gywQBZ!mH3-7pTW_MSDIi-Eayc-aXVnBC__NtHDEJwYgtVbqiE).
Source: https://github.com/TrinityCore/TrinityCore/issues/16131
> feat(DB/game_tele): Added Emerald Dream game_tele

- data/sql/updates/pending_db_world/rev_1570473473602619780.sql
-  Add condition to check for Fel Reaver corpse
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2335
- .qu add 10764(Alliance)/10758(Horde)
- use quest item
- .go c fel_reaver
- use quest item
- select Fel Reaver
- .die
- use quest item
- .qu add 10764(Alliance)/10758(Horde)
- use quest item
- .go c fel_reaver
- use quest item
- select Fel Reaver
- .die
- use quest item
> fix(DB/Quest): Fix quest Hotter than Hell requirement of Fel Reaver corpse

- data/sql/updates/pending_db_world/rev_1570916858306186295.sql
- src/server/game/Miscellaneous/Language.h
- src/server/scripts/Commands/cs_debug.cpp
The GM command `.debug send opcode` can be used to send opcodes to the client by storing a file "opcode.txt" in the working directory of the server. If this file is missing and a GM executes the command the server will (at least on Linux) allocate more and more memory until the OS kills the process. The cause of this is an incorrect check if the file is open for reading:
https://github.com/azerothcore/azerothcore-wotlk/blob/0651e771231ca2a3ccf23cb141cb51ddf5152667/src/server/scripts/Commands/cs_debug.cpp#L252-L254
If the file is missing, "bad" returns false, so use "is_open" instead.
none
- execute `.debug send opcode` without the file "opcode.txt": This should now result in an error message "Incorrect syntax".
- save …
> fix(Core/Commands): debug send opcode

- data/sql/updates/pending_db_world/rev_1570979437296560126.sql
-  Added item Cape of the Black Baron (13340) to the creature loot of  Baron Rivendale (10440)
The loot chance is 8.7%, source: [wotlk.evowow](https://wotlk.evowow.com/item=13340?npc=10440) and [AoWoW live demo](https://db.rising-gods.de/Item=13340?npc=10440) from sarjuk
I made this fix using the [Keira3 editor ](https://github.com/azerothcore/Keira3/),
- Closes  #2349
- The creature Baron Rivendale (10440) now drop the item Cape of the Black Baron (13340)
```
log in game
.go creature id 10440
kill the NPC multiple times
```
> Fix Baron Rivendale loot, close #2349

- data/sql/updates/pending_db_world/rev_1571179939629745569.sql
Remove a duplicate gossip option while on quest "The Exorcism of Colonel Jules".
none
- preparation:
```
.q rem 10935
.q a 10935
.go -710.799 2745.24 101.591 530
```
- talk to Anchorite Barada, he should now only have 1 gossip option
none
> fix(DB/gossip_menu_option): Quest "The Exorcism of Colonel Jules"

- data/sql/updates/pending_db_world/rev_1571215774635756412.sql
Remove waypoint scripts causing Chilltusk to cast "First Aid" which is obviously wrong and causes errors in the server log:
```
ERROR: SCRIPT_COMMAND_CAST_SPELL ('waypoint_scripts' script id: 1046) no target unit found for spell 746
ERROR: SCRIPT_COMMAND_CAST_SPELL ('waypoint_scripts' script id: 1047) no target unit found for spell 746
```
none
- ```.go c id 27005```
- just follow Chilltusk around, the errors mentioned above should not show in the server log
none
> fix(DB/waypoint_scripts): Chilltusk

- src/server/authserver/Server/AuthSocket.cpp
There is a public tool, AuthFlooder that DDOS the authserver with multiple requests, this little fix can easily stop it.
-  Added a MAX request REALMLIST quantity in a row to 10, this will STOP the AuthFlooder
- This is a critical issue, a member can lock the client log in if open multiple AuthFlooder and target a victim server
- I used AuthFlooder with and without the fix, the fix stop it
Before the PR, I opened 3 AuthFlooder and in any I got this output in console:
The client wait in the "Authenticating" phase:
After the PR, here the AuthFlooder output text:
In the AuthServer console you will get `Got 10 REALM_LIST in a row from '127.0.0.1', possible ongoing DoS`.
I tried also to log in with my client 10 times, it works perfectly, the problem is make it "in a row", so multiple times in …
> feat(Core/AuthServer) Added check for AuthFlooder, now the server stop it!

- data/sql/updates/pending_db_world/rev_1571608072211416530.sql
- Enable the K3 teleporter after "Opening the Backdoor" is rewarded
- Fix a few phasing issues in the Garm area
- Remove some creatures in the Garm cave (this was actually taken from https://github.com/TrinityCore/TrinityCore/commit/4187c9f1846fa90f45fd05d1741117862bbe7bea)
- provide waypoint movement for some of the creatures in the Garm cave
- Add Goblin Sappers which run into the Garm cave and explode when near enemies
- Adjust Gino's waypoint movement
- Adjust Tormar Frostgut's waypoint movement
none
- preparation:
```
.q rem 12821
.q rem 12822
.q rem 12823
.go 6147.6 -1070.63 402.624 571
```
- ensure that the teleporter is not usable
- quest "Know No Fear":
```
.q a 12821
.q c 12821
.q rew 12821
.q a 12822
```
- ensure that the teleporter is now usable
- …
> fix(DB/SAI): Garm area

- src/server/game/Entities/Unit/Unit.cpp
Glyph of Shadow Word: Death: Targets below 35% health take an additional 10% damage from your Shadow Word: Death spell.
https://wotlk-twinhead.twinstar.cz/?spell=55682
-  Objectives below 35% of life receive an additional 10% damage using the spell of the Word of Shadows: death.
The Report does not exist, the first thing you should do is the following:
- Get the glyph: Glyph of Shadow Word: Death
- Go to a Boss or Raid and cast the spell when the target is or is below 35%
- You are not respecting what the glyph indicates
- 
- Get the glyph: Glyph of Shadow Word: Death
- Go to a Boss or Raid and cast the spell when the target is or is below 35%
- You are not respecting what the glyph indicates
Master
> [Spell/Core] Glyph of Shadow Word: Death

- src/common/Utilities/Util.cpp
Me and @Stoabrogga figure out that `Utf8toWStr()` is responsible for server crashes when a malformed opcode and special characters are sent to the server.
-  improved Utf8toWStr() like TC-335a do
- #2077
- #2043
- #2170
- #2198
- #2345
- other issues about exploiting crashes which functions turn on `Utf8toWStr()`
related to this PR https://github.com/azerothcore/azerothcore-wotlk/pull/2374
- I used AccLeito addon to send malformed CSMG_ADD_FRIEND opcode and special character to the server, with this PR the server does not crash.
- use AccLeito Addon and try to get down the server with the Crash button
> fix(Core/Crash): Improved Utf8toWStr() function to prevent crashes

- data/sql/updates/pending_db_world/rev_1571737953110374673.sql
- src/server/scripts/EasternKingdoms/Scholomance/instance_scholomance.cpp
- src/server/scripts/EasternKingdoms/Scholomance/scholomance.h
- While on the quest "The Lich, Ras Frostwhisper" the item "Soulbound Keepsake" will now correctly transform Ras into a human after finishing the 20 seconds channel of the spell "Boon of Life".
- The loot item "Human Head of Ras Frostwhisper" will now only drop if Ras has been transformed into his human form.
- Ras attacks the caster of "Boon of Life" and gains additional threat.
- After being transformed into a human Ras is set to full health.
Closes #2364
- Preparation:
```
.q rem 5466
.q a 5466
.go cr id 10508
```
- Use "Soulbound Keepsake" on Ras to transform him into a human.
- Ensure that the item "Human Head of Ras Frostwhisper" can only be looted after he is in human form.
none
When a PR is ready to be tested, …
> fix(Core/Quest): The Lich, Ras Frostwhisper

- src/common/Database/DatabaseWorkerPool.cpp
- src/common/Database/DatabaseWorkerPool.h
- Move DatabaseWorkerPool into its own translation unit
- Part for dynamic linking
PR based TC commit https://github.com/TrinityCore/TrinityCore/commit/09fa0ab46a487ea85d475ac0b3495724c170fe1a
- Build and run in Windows at VS 16.3.8
- This no need test, only build in Travis
> feat(Core/DBLayer): move DatabaseWorkerPool into it's own translation unit

- src/server/game/Entities/Object/Object.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Grids/Notifiers/GridNotifiers.cpp
- src/server/game/Grids/Notifiers/GridNotifiers.h
- src/server/game/Grids/Notifiers/GridNotifiersImpl.h
This is a follow-up to PR #2304. Currently there exist two problems with large objects:
- They don't initially appear at their full range.
- As for creatures, they don't disappear if the player stands still and just watches them moving (see #2323)
I tried to fix this by adjusting the VisibleNotifier to either handle only non-large or only large objects. The visibility check is then split into two parts: Default distance for non-large, maximum distance for large objects. So far my tests where successful and it looks much better now as large creatures and game objects are now appearing at full distance.
Closes #2323
- Check one of the Fel Reavers (`.go creature fel_reaver`) and then just wait doing nothing while it moves …
> fix(Core/GridNotifiers): increased visibility for large creatures, part 2

- src/common/Common.h
- src/common/CompilerDefs.h
- src/common/Debugging/Errors.cpp
- src/common/Debugging/Errors.h
- src/common/Debugging/WheatyExceptionReport.cpp
- src/common/Debugging/WheatyExceptionReport.h
- src/common/Define.h
- src/common/GitRevision.cpp
- src/common/Logging/Log.cpp
- src/common/Utilities/Util.cpp
- src/server/game/World/World.cpp
- src/server/worldserver/CommandLine/CliRunnable.cpp
- Replace prefix all preprocessor defines from CompilerDefs with `AC_`. So that there would be no conflict in the future.
PR based TC commit https://github.com/TrinityCore/TrinityCore/commit/9ec2a82cac993648ed603711f84b6b743ca1e106
- Build and run in Windows at VS 16.3.8
- No need test this
> feat(Core/Misc): replace all prefix preprocessor defines from CompilerDefs with AC_

- src/server/game/Chat/ChatLink.cpp
Add a check to `uint32` variable assignment to prevent that a negative value is assigned to an `unsigned int`, it causes that the variable assume the max value of `uint32` and make crash the server.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2433
- I tested the command showed in https://github.com/azerothcore/azerothcore-wotlk/issues/2433 before and after the PR, after the PR the server does not crash.
I linked the `[Inscription]` spell in game, I didn't get any issues.
- Read issue https://github.com/azerothcore/azerothcore-wotlk/issues/2433 …
> fix(Core): uint32 assignment, prevent crash, closes #2433

- src/server/game/Grids/Notifiers/GridNotifiers.cpp
In PR #2378 I forgot to include a check for existence of the world object which can cause a server crash. I sadly did not see this in my tests because I'm only playing alone on my server, sorry.
- Closes #2441
Tested build on Ubuntu 16.04 / clang 7
Nothing to test, can be merged after a successful Travis run.
none
> fix(Core/GridNotifiers): Fix crash

- data/sql/updates/db_world/2019_11_09_00.sql
import error for 1970 date to old for updated maria
-  change date to 2000 
-  
- error in sql insert about 1970 sql is skipped and arena tournament has no start date 
-  game_event now has adequate start times and no error in sql import must be a Debian 10 buster mariadb latest issue 
-
> fix(DB/game_event): use another default minimum date to avoid import errors

- data/sql/updates/pending_db_world/rev_1572128545565068694.sql
Drop the quest item "Essence of Ice" only if the quest "Hot and Cold" has been taken.
none
- preparation:
```
.q rem 12981
.go 7485.24 -3287.78 876.769 571
.mo p 4
```
- kill the Brittle Revenants and ensure that the quest item does not drop anymore
- add the quest "Hot and Cold": `.q a 12981`
- kill again Brittle Revenants: The quest item "Essence of Ice" should now drop
none
> fix(DB/Quest): "Hot and Cold" quest item

- data/sql/updates/pending_db_world/rev_1572680805604667000.sql
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Globals/ObjectMgr.cpp
- Add the quest sparkle effect for game object type "GAMEOBJECT_TYPE_SPELL_FOCUS"
- Add event played during the quest "The Bones of Nozronn" based on this TC commit:
https://github.com/TrinityCore/TrinityCore/commit/afccb54a0ee03fd7dab3cf5381823cef27271c45
(adapted the SQL script to AC, changed the comments a bit and fixed the random movement)
none
- preparation:
```
.q rem 12544
.q a 12544
.go 5209.28 5792.54 -71.3554 571
```
- proceed with the quest
none
> fix(DB/GameObject): Quest event "The Bones of Nozronn"; quest sparkle for GO type "GAMEOBJECT_TYPE_SPELL_FOCUS"

- data/sql/updates/pending_db_world/rev_1572823869348028411.sql
Area "Valley of Echoes" near "Argent Vanguard":
- Do not spawn the Freed Crusader on the player, but on the Webbed Crusader instead
- Extend creature text for the Freed Crusader (taken from TC)
- Prevent the roaming crusaders from attacking the "bad" Webbed Crusaders
none
- `.go 6436.93 251.749 397.095 571`
- free the Webbed Crusaders
none
> fix(DB/SAI): Freed Crusader

- .travis.yml
- apps/ci/ci-install-modules.sh
The PRs #2454 and #2455 have been merged and the modules fixed accordingly, so the modules check executed by Travis should be enabled again. The module "mod-vas-autobalance" has been renamed to "mod-autobalance" so I also updated the appropriate script.
none
see Travis run
see Travis run
none
> fix(CI): Enable Travis modules check

- src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
-  Moved AddObject AV doors after their spawn.
- Added the spawn of the object in `StartingEventCloseDoors()` function
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2453
**Before PR:**
if I join AV for the first time and I can't see the gate, if I open another client with a second account and join AV (same faction) I can see the gate and I can see that the first player can pass through the gate because he can't see them.
**After PR:**
The problem don't persist, I can see the gate at the first join.
- start your worldserver
- delete Cache, open Wow.exe
- join AV, check if you can see the gate
**Before the PR:** you will not see the gate, but the gate is spawned, if you use another account you will see it.
**After the PR:** you will see the gate at the first join.
When a …
> fix(Core/BG) Moved AddObject AV doors after their spawn, closes #2453

- data/sql/updates/pending_db_world/rev_1574892827070035498.sql
The NPC "Krun Spinebreaker" (ID 17405) has to be enabled for SAI or else the following error occurs during the quest "The Seer's Relic":
`SmartScript: Action target Creature(entry: 17405) is not using SmartAI, action skipped to prevent crash.`
none
- preparation:
```
.q rem 9545
.q a 9545
.go 194.415 4143.8 73.7128 530
```
- proceed with the quest; the error mentioned above should not occur anymore
none
> fix(DB/SAI): Fix SAI error during quest "The Seer's Relic"

- data/sql/updates/pending_db_world/rev_1574980316492398478.sql
- Fix SAI talk action for "Citizen of New Avalon", leading to the following error:
`ERROR: SmartScript::ProcessAction: SMART_ACTION_TALK: EntryOrGuid 2894202 SourceType 9 EventType 60 TargetType 7 using non-existent Text id 2 for talker 28897, ignored.`
- Fix positions of some of the citizens as they were standing inside each other
- Delete redundant creature text
none
- create a new Death Knight
- `.go 1633.08 -5721.75 127.562 609`
- `.mo p 4`
- fly over the citizens and drop a ghoul on them: `.npc add temp 28897`
- ensure that the error mentioned above does not occur in the log anymore
- ensure that no citizens are standing inside each other
none …
> fix(DB/SAI): Citizen of New Avalon

- data/sql/updates/pending_db_world/rev_1575409612123583009.sql
- src/server/scripts/Commands/CMakeLists.txt
- src/server/scripts/Commands/PlayerCommand.cpp
- src/server/scripts/Commands/PlayerCommand.h
- src/server/scripts/Commands/cs_learn.cpp
- src/server/scripts/Commands/cs_player.cpp
- src/server/scripts/ScriptLoader.cpp
Don't know if it's actually needed, but I created two new GM commands to learn or unlearn spells for players without targeting the player directly:
```
.player learn #playername #spell
.player unlearn #playername #spell
```
I use them on my own server for some time now and just want to share the code. If not needed this PR can be closed.
none
Just use the commands with a GM account or via server console, e.g.:
```
.player learn Testplayer 23223
.player unlearn Testplayer 23223
```
This will learn / unlearn "Swift White Mechanostrider" for the player "Testplayer". Also try the existing commands (you need another player as target):
```
.learn 23223
.unlearn 23223
```
none …
> feat(Core/CommandScript): New GM command "player learn"

- src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp
UBRS Rend Blackhand was spawing too many mobs in first phase
Partially fixes issue #1876 now playable
- Partially Closes #1876 
- Go to event: .go 154.01 -394.17 124.23 229
- Verify that the mobs in phase 1 spawns at correct rate
- Tested on docker in win10
- .go 154.01 -394.17 124.23 229
- Verify spawnrate
> fix(CORE/Instance): Fixed group spawn UBRS Rend Blackhand

- data/sql/updates/pending_db_world/rev_1576103837497375056.sql
Prevent the Wastewalker Captives attacking players.
none
- `.go -144.782 -168.814 -10.6359 547`
- swim in the water and jump around a little under the slave cage hanging over the water (need to be around level 60); the Wastewalker Captives should no longer attack the player
none
> fix(DB/SAI): Wastewalker Captive

- data/sql/updates/pending_db_world/rev_1576535250226124911.sql
- src/server/game/Handlers/PetHandler.cpp
- src/server/scripts/Spells/spell_mage.cpp
- Fix permanent Water Elemental not showing it's localized name.
- Despawn the permanent Water Elemental if the Glyph of Eternal Water is removed.
Closes #2503
- Create a mage who can summon a Water Elemental
- Add the Glyph of Eternal Water
- Summon the Water Elemental: It should now show the localized name (perhaps also test using a second player with a different client language watching the Water Elemental, it should show the name in the language of the client)
- Remove the Glyph of Eternal Water: The permanent Water Elemental should vanish.
none
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. …
> fix(Core): Glyph of Eternal Water

- src/common/Containers.h
- src/common/Utilities/Util.cpp
- src/common/Utilities/Util.h
- src/server/game/Battlegrounds/Battleground.cpp
- src/server/game/Battlegrounds/Battleground.h
- src/server/game/Battlegrounds/BattlegroundMgr.cpp
- src/server/game/Battlegrounds/BattlegroundMgr.h
- src/server/game/Battlegrounds/BattlegroundQueue.cpp
- src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp
- src/server/game/Battlegrounds/Zones/BattlegroundEY.cpp
- src/server/game/Battlegrounds/Zones/BattlegroundWS.cpp
- src/server/game/DataStores/DBCStores.cpp
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Groups/Group.cpp
- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/game/Spells/SpellMgr.cpp
- src/server/scripts/World/achievement_scripts.cpp
Random Battleground system was hardcoded in core. Battlegrounds/Arenas that can proc from Random BG/Arena queue should be read from BattlemasterList.dbc.
Battlegrounds weights stored in `world.battleground_template` weren't used.
Due to this :
```C
switch (m_CurrentRandomBg)
{
case BATTLEGROUND_AV: m_SwitchTimer = 180*IN_MILLISECONDS; break; // max 40 per team
case BATTLEGROUND_WS: m_SwitchTimer = 30*IN_MILLISECONDS; break; // max 10 per team
case BATTLEGROUND_IC: m_SwitchTimer = 180*IN_MILLISECONDS; break; // max 40 per team
case BATTLEGROUND_EY: m_SwitchTimer = 40*IN_MILLISECONDS; break; // max 15 per team
case BATTLEGROUND_AB: m_SwitchTimer = 40*IN_MILLISECONDS; break; // max 15 per team
case BATTLEGROUND_SA: m_SwitchTimer = 40*IN_MILLISECONDS; break; // max 15 per team
default: …
```
> fix(Core/Battlegrounds) Rewrite RandomBG and enabling bg/arenas weights

- data/sql/updates/pending_db_world/rev_1576886642925348957.sql
Fix the Snufflenose Gopher pulling mobs.
Closes #2415
- preparation:
```
.q rem 1221
.q a 1221
.ad 5880
.ad 5897
.ad 6684
.tele razorfenkraul
```
- proceed with the quest "Blueleaf Tubers". The Snufflenose Gopher should no longer cause aggro.
none
> fix(DB/SAI): Snufflenose Gopher

- src/server/game/Entities/Pet/Pet.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Scripting/ScriptMgr.cpp
- src/server/game/Scripting/ScriptMgr.h
Add a new PlayerScript hook "OnPetInitStatsForLevel" which is called after the player's pet has been loaded and initialized. This can be used to get access to the player's pet object and alter it's values, e.g. "SetObjectScale".
none
tested build on Ubuntu 16.04 / clang 7
Can be tested using this simple PlayerScript which sets all pets half their normal size:
```cpp
class PetInit_PlayerScript : public PlayerScript
{
public:
PetInit_PlayerScript() : PlayerScript("PetInit_PlayerScript") { }
void OnPetInitStatsForLevel(Pet* pet) override
{
pet->SetObjectScale(0.5f * pet->GetFloatValue(OBJECT_FIELD_SCALE_X));
}
};
```
none
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. …
> feat(Core/Hook): New PlayerScript hook "OnPetInitStatsForLevel"

- src/server/authserver/Main.cpp
- src/server/game/World/World.cpp
- src/server/worldserver/Master.cpp
- src/server/worldserver/RemoteAccess/RARunnable.cpp
- Give a possible error explanation when authserver can't bind to port, and when a PidFile can't be created.
- Change outString to outError for the pidfile (so it displays in red in the console AND now it's the same code in both worldserver and authserver)
- Launch two authservers on the same port and see the error
- Or have a permission error when creating the pidfile (like try to create it in /root)
But there is nothing to test really :D just check the code
> fix(core): Improve output for 2 small errors

- src/server/game/Entities/Player/Player.cpp
I posted it on Discord : 
I found out that for optimization reasons, AC use `NeedToSaveGlyphs()` to know if glyphs should be re-saved into db or not. So, according to `SetGlyph` function, `NeedToSaveGlyphs()` is becoming `true` (called by `SetNeedToSaveGlyph(true)`) when the player add/change a glyph. (That's pretty normal)
But, my question is, why is `SetNeedToSaveGlyph(false)` never called ? Even after save ? It means that it'll continue to re-save player's glyphs into db even if they were already saved and unchanged.
-  Add `SetNeedToSaveGlyph(false)` after Glyphs got saved 
Commit : 70170f0bbd767c7d4656b9a3e33b7e21429f00ab
- `SetNeedToSaveGlyph(false)` was never used
- Checked if glyphs are still saved
- Checked if the `Player::_SaveGlyphs()` function was NOT called when the player …
> fix(Core/Player): Only save players glyphs when needed

- src/server/game/World/World.cpp
- Fixed typos
- Changed outError to outString when it's not an actual error but just a warning
- Display "load hardcoded default settings" only when .conf.dist AND .conf are missing  
- None
- Launch worldserver with a missing .conf file, or a missing .conf.dist, or both but there is no testing required IMO
> fix(Core): Improve logging msg when missing .conf file

- src/server/game/Groups/Group.cpp
- src/server/game/Handlers/BattleGroundHandler.cpp
-  Disallow starter dk to join battleground queue
According to 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L2321
Death-knights aren't allowed to get teleported out of their starting zone until they didn't got their "Death gate" spell (dk quest lines).
Currently, they can't get teleported but they still can queue bg, and when the queue pops, they can click on "enter". 
The issue is that they're not teleported and still considered "in bg" (according to the Battleground queue icon that pops near the minimap circle). They can click on the "Leave battleground" option, but nothing happens.
Commit : 70170f0bbd767c7d4656b9a3e33b7e21429f00ab
PS : Confirmed by [ Stevej [es] - @pangolp ] on Discord
- Tried to queue bg with dk (solo) -> …
> fix(Core/DK): Don't allow starter dk to queue bg

- data/sql/updates/pending_db_world/rev_1579041492812648634.sql
- Set the Devilsaurs in Un'Goro Crater active in order to be able to move on their own and pose an additional threat to the players.
- Delete the duplicate Tyrant Devilsaur
none
just follow the Devilsaurs:
`.go cr id 6498` (Devilsaur)
`.go cr id 6499` (Ironhide Devilsaur)
`.go cr id 6500` (Tyrant Devilsaur)
`.go cr id 6584` (King Mosh)
They should move on their own even when no player is near.
none
> fix(DB/SAI): Devilsaurs

- data/sql/updates/pending_db_world/rev_1579128650269731381.sql
- Ensure that the Innocuous Scarabs (the small white bugs running around the Argent Tournament) stay near their spawn position. As it was before they tended to slowly drift away as the random SAI movement always took the last position as base for the calculation of the next random position.
- Hide the model while the scarabs are burrowed (you could sometimes see parts of their model sticking out of the ground).
none
Just run around the Argent Tournament and watch the small white bugs (they cannot be targeted).
none
> fix(DB/SAI): Innocuous Scarab

- src/server/game/Maps/Map.cpp
OnPlayerLeaveMap was previously inside the if(remove) block which only is called when the player is logging out, this moves it outside that block but still has it trigger in the same order, thus allowing OnPlayerLeaveMap scripts to fire properly (needed for AutoBalanceFix)
-  
-  
- Closes 
-
-
> Make OnPlayerLeaveMap actually trigger

- src/server/game/Entities/Creature/TemporarySummon.cpp
- src/server/game/Entities/Pet/Pet.cpp
- src/server/game/Scripting/ScriptMgr.cpp
- src/server/game/Scripting/ScriptMgr.h
Provide new PlayerScript hooks which can be used to access and manipulate player's pets, guardians, non-combat pets etc. at different states of their initialization:
- OnBeforeTempSummonInitStats
- OnBeforeGuardianInitStatsForLevel
- OnAfterGuardianInitStatsForLevel (replaces OnPetInitStatsForLevel)
- OnBeforeLoadPetFromDB
Thanks for your feedback @Yehonal on #2600, I hope that I got it right this time.
none
- tested successfully in-game using modified versions of [mod-npc-beastmaster](https://github.com/azerothcore/mod-npc-beastmaster) and [mod-morphsummon](https://github.com/azerothcore/mod-morphsummon) and a small test-module.
Example for a PlayerScript:
```cpp
class Test_PlayerScript : public PlayerScript
{
public:
Test_PlayerScript() : …
```
> feat(Core/Hook): New PlayerScript hooks

- src/server/game/Entities/Creature/TemporarySummon.cpp
Fix a crash introduced with #2639 concerning the PlayerScript hook for TempSummon. I forgot to check if "owner" is null, sorry for that.
Closes #2649
tested build on Ubuntu 16.04 / clang 7
Don't know how to provoke the crash, but it should not happen anymore.
none
> fix(Core/TempSummon): Fix crash concerning PlayerScript hook

- src/server/game/Spells/Auras/SpellAuraEffects.cpp
-  Remove checking of return value for an Eluna hook.
-  The check was invalid, so this can fix spell procs.
-  The return value will be void in latest Eluna, so if this change is not applied everywhere for OnDummyEffect it will error later when using latest eluna.
- Possibly closes issues related to spell procs and totems.. hmm.
- 
-
"it breaks procs like Earthbind Totem."
So try see if that totem was broken before when using the module and try with the fix and see if the totem now works.
> fix(Core/Spells): spell procs issues with Eluna

- src/server/game/Entities/Unit/Unit.cpp
As it is now the Guardian Pets, like the Mage's (temporary) Water Elemental or the Shaman's Spirit Wolves cannot clear their combat state after combat has ended. This can be tested like follows:
- create a Mage who can summon the temporary Water Elemental
- use "`.npc info`" on the Water Elemental: Unit Flag "UNIT_FLAG_IN_COMBAT" (0x00080000, 524288) is not set
- attack an enemy NPC
- after the combat the Unit Flag "UNIT_FLAG_IN_COMBAT" ist still there and won't be cleared.
After applying this PR the flag will be correctly cleared when combat ends.
none
See the description above.
none …
> fix(Core/Unit): Fix Guardian Pets clearing combat state

- src/server/game/AI/CreatureAI.cpp
Skip creatures in evade mode if DoZoneInCombat is called. This prevents error messages similar to this:
```
ERROR: DoZoneInCombat called for creature that has empty threat list (creature entry = 18831)
```
part of #2536
- `.tele GruulsLair`
- pull High King Maulgar to the entrance of the dungeon
- leave the dungeon and enter it again
- run past the mobs (they're in evade mode), wait until the first one returned to it's home position and attack him while the other mobs are still returning
- the error message mentioned above should not occur anymore
none
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. …
> fix(Core/CreatureAI): Skip creatures in evade mode for DoZoneInCombat

- src/server/game/Entities/Creature/CreatureGroups.cpp
Prevent the speed rate of the formation movement of members from getting too low which otherwise leads to errors similar to these:
```
ERROR: MoveSplineInitArgs::Validate: expression 'velocity > 0.01f' failed for GUID: 57968 Entry: 16843
ERROR: MoveSplineInitArgs::Validate: expression 'velocity > 0.01f' failed for GUID: 101655 Entry: 32572
ERROR: MoveSplineInitArgs::Validate: expression 'velocity > 0.01f' failed for GUID: 4479 Entry: 727
ERROR: MoveSplineInitArgs::Validate: expression 'velocity > 0.01f' failed for GUID: 4480 Entry: 727
```
The error happens after the creatures finish combat and the member has to wait for the leader.
none
- follow these creatures:
```
.go cr 4479
.go cr 57968
.go cr 101655
```
- the …
> fix(Core/CreatureGroups): Fix "MoveSplineInitArgs::Validate" errors

- data/sql/updates/pending_db_world/rev_1579770074985495361.sql
Fix gossip options for the following NPCs in Un'Goro Crater:
- Spark Nilminer
- J.D. Collie
- Karna Remtravel
This is based on the following TC commits:
https://github.com/TrinityCore/TrinityCore/commit/d78b62f4372153b81b7539b54c0fcd8092858d47
https://github.com/TrinityCore/TrinityCore/commit/17ddc47577cfeb6218780b444ec0595eb47ac594
I adapted them to AC and only took over the necessary parts.
none
**Spark Nilminer**
- `.go cr id 9272`
- ask him about Dadanga: there should not be any more gossip options following this
**J.D. Collie**
- step 1:
```
.q rem 4285
.q rem 4287
.q rem 4288
.q rem 4321
.go cr id 9117
```
- talk to J.D. Collie: she should not show any gossip options
- step 2:
```
.q a 4285
.q a 4287
.q a 4288
.q c 4285
.q c 4287
.q c 4288
.q rew 4285
.q …
```
> fix(DB/gossip): Fix several gossip options for NPCs in Un'Goro Crater

- src/server/game/Handlers/AuctionHouseHandler.cpp
- src/server/game/Misc/AsyncAuctionListing.cpp
- src/server/game/Misc/AsyncAuctionListing.h
- src/server/game/Server/WorldSession.h
-  Refactor the function HandleAuctionListOwnerItems to prevent crash from malformed packet (opcode **CMSG_AUCTION_LIST_OWNER_ITEMS**).
- Closes #2683 
- probably related to #2666
- I tested it as the issue show
- after the refactor I also tested several times the function during the "normal" play, I put on the auction some items and in "Auctions" I can see all my own items in the auction.
[chardump](https://paste.ubuntu.com/p/QdHgD8FgDt/)
- To reproduce the sending of the malformed packet just follow the instructions in issue #2683.
- To verify the normal play in wow just open an auction house in-game, put something in the Auction and see in the "Auction" frame if you can see your own items in the Auction.
Thx @SolidMaxtor who reported to me this issue.
When a PR is ready to be tested, …
> refactor(HandleAuctionListOwnerItems): prevent crash

- src/server/game/Tools/PlayerDump.cpp
Columns were not longer aligned and sometimes it worked, sometimes it didn't want to save a character or load a character. Now it works fine.
Thanks @Rochet2 for identifying the column count issue
- Tested ingame and in the console, works perfectly fine for both subcommands
Before and after PR:
1. `.pdump write pdump_test.txt character_name` without PR it failed for me on SOME characters (saying the character had been deleted)
1. `.pdump load pdump_test.txt account_id`
- The code is prehistoric, in theory it should be reworked and also make use of "named queries" (with column names instead of column count) to avoid this issue again.
You can help by testing PRs and writing your feedback here in the PR's page …
> fix(CORE/commands): Realign columns for command ".pdump"

- src/server/game/Handlers/ChatHandler.cpp
According to #2407, We should use `normalizePlayerName` and UTF-8 check before using the player name when we take it from the client.
But, We already have `sScriptMgr->OnPlayerChat` for whsiper in [Player.cpp](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/Player.cpp#L20956)
That would be load the scripts if anything like the player name was valid and the player was online.
You can check `ChatHandler.cpp` file in TrinityCore, they don't have `OnPlayerChat` (for whisper) inside that file.
I think, If the server had any custom script for the whisper, like chat censure, Server can get Crash with WPS.
If you really want to keep that **[Not need that, That's duplicate!]**, You should validate the player name with `normalizePlayerName` function.
Use …
> fix(Core/Crash): remove unneeded hook OnPlayerChat

- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- src/server/game/Scripting/ScriptMgr.cpp
- src/server/game/Scripting/ScriptMgr.h
Introduce a new GlobalScript hook which is called before the WorldObject phasemask check. This can be used to get rid of the [Guildhouse module](https://github.com/azerothcore/mod-guildhouse) patch file, but also for other kind of stuff concerning the phases as you are able to access the WorldObject and can also update the phasemask against which the check is running later.
none
- tested successfully in-game using a small GlobalScript
I used this small GlobalScript to test the hook:
```cpp
class GuildHouseGlobal : public GlobalScript
{
public:
GuildHouseGlobal() : GlobalScript("GuildHouseGlobal") {}
void OnBeforeWorldObjectSetPhaseMask(WorldObject const* worldObject, uint32& /*oldPhaseMask*/, uint32& /*newPhaseMask*/, bool& useCombinedPhases, bool& …
```
> feat(Core/Hook): New GlobalScript hook

- src/server/game/Entities/Pet/Pet.cpp
- src/server/game/Handlers/PetHandler.cpp
Only show pet details (Shift+P) for the Hunter pets and Warlock demons, not for the Death Knight's permanent ghoul or the Mage's permanent water elemental.
Closes #2414
- pet details should show normally for Hunter pets and Warlock demons, just as it was before
- pet details should not show for the Death Knight's permanent ghoul or the Mage's permanent water elemental
none
> fix(Core/Pet): only show pet details for hunter pets and demons

- data/sql/updates/pending_db_world/rev_1583690478008671900.sql
- data/sql/updates/pending_db_world/rev_XXXXXXXXXXXX.sql
Ref https://github.com/azerothcore/azerothcore-wotlk/issues/2690
Fixed loot for gameobject = 161495
(I don't know the stuff with rev and shiz so feel free to edit it <3)
Tests: None
> fix(DB/Gameobject): Secret Safe loot

- README.md
- src/server/game/Entities/GameObject/GameObject.cpp
Fixes #2658 
Test performed:
Branch: Master
How to test:
1. Use any consumable goober without the change and with the change.
**I want to state that this is NOT my doing, it was taken from these commits originally made by Wyrserth on TrinityCore https://github.com/TrinityCore/TrinityCore/commit/50c5d30d13fe12af2a2028baf845fb6eab329a57 & https://github.com/TrinityCore/TrinityCore/commit/2b1e8d135bd3f3a3ddf7f29471cf6116da223175**
> Fix:(Core/Gameobjects) Fix so non-consumable goobers don't despawn on use

- src/server/game/Entities/Creature/GossipDef.cpp
Original commit https://github.com/TrinityCore/TrinityCore/commit/61ba1351e0da10219877ad9761ab161e3de51c74
Before:
After:
Tests:
Builds, Tested in-game
How to test:
1. .go c id 25163
2. .q add 11549
3. .q comp 11549
4. open gossip
> fix(Core/Gossip): Show title reward from quests in gossip

- data/sql/base/db_world/npc_text_locale.sql
-  fix `Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.` on default MySQL install
- Closes #2270
- Run db_assembler after fresh MySQL/MariaDB install without this error
- Run db_assembler after fresh MySQL/MariaDB
> DB/Misc: fix error on default MySQL install

- src/server/game/Handlers/CharacterHandler.cpp
Please see the commit message for extended details. 
-  push OnFirstLogin down, closer to the OnLogin callback 
- OnFirstLogin can now make persistent changes
- works on my personal server
- you would need to write your own PlayerScript that uses the OnFirstLogin hook and teach the player a spell within it. 
- ~~I will soon post a merge request to a module where I used it, which can be used for testing~~ https://github.com/azerothcore/mod-learn-spells/pull/9 
> fix(Core/Hook): OnFirstLogin can now make persistent changes.

- data/sql/updates/pending_db_world/rev_1584233284203119000.sql
@BarbzYHOOL found this bug, where the Corrupted Cat did not have a gossip.
This fixes the gossip thing 🗡 
How to reproduce:
1. `.qu add 4506`
1. `.go cr 40765`
1. Summon the tiger in the green well
> fix(DB/Gossip): Corrupted Cat gossip

- data/sql/updates/pending_db_world/rev_1584052298613344800.sql
Issue:
Currently the quest_offer_reward is like this
```
Listen well, $C. In accepting this weapon your fate is sealed.$B$BOvercome or succumb.$B$BI have placed your feet upon this path. You are therefore my personal responsibility. Should you falter, I am duty-bound to deliver you from this life.$B$BRemember my words, $C, and do not fail.
```
Which is wrong according to WoWHead where it should be 
```
Listen well, <class>. In accepting this weapon your fate is sealed.
Overcome or succumb.
I have placed your feet upon this path. You are therefore my personal responsibility. Should you failter, I am duty-bound to deliver you from this life.
Remember my words, <race>, and do not fail.
```
Tests:
Works
How to test:
1. .q add 24743
2. .go c 201042
> Fix:(DB/Quest) Shadow's Edge quest_offer_reward

- data/sql/updates/pending_db_world/rev_1584389363968563900.sql
Currently, in the quest_offer_reward it is missing some spaces and is wrongly written compared to https://classic.wowhead.com/quest=8474/old-whitebarks-pendant
How to test:
1. .q add 8474
2. .q comp 8474
3. .go c id 15398
4. Hand in the quest
> fix(DB/Quest): Old Whitebark's Pendant

- data/sql/updates/pending_db_world/rev_1518477962308987200.sql
Doing the first Event Dungeon Finder of the day currently won't award any Emblem of Frost and will aswell count as the first RDF of the day, thus making impossible to get the first two EoFs of the day (with RDFs).
Adding 2x Emblem of Frost inside the Heart-Shaped Box.
**Tests performed:** Tested in game.
> Heart-Shaped Box

- data/sql/updates/pending_db_world/rev_1584387270154812400.sql
https://wow.gamepedia.com/Tome_of_Tranquilizing_Shot
>The subject of this article was removed from World of Warcraft in patch 3.0.2.
Removed from creature_loot_template and added deprecated flag in item_template
This means:
Can't drop and can't be used
> fix(DB/Item): Tome of Tranquilizing Shot

- data/sql/updates/pending_db_world/rev_1584388048550524100.sql
Currently has no gold loot.
https://www.wowhead.com/item=20602/chest-of-spoils
https://classic.wowhead.com/item=20602/chest-of-spoils#comments
Checking Wowhead comments I estimate that it contains around 60 to 100 gold since there have been no comments of lower or above those values
> fix(DB/Item): Chest of Spoils

- data/sql/updates/pending_db_world/rev_1584790013870207000.sql
The quest rates for faction 941 The Mag`har and 978 Kurenai were doubled. They should give a normal reputation reward. 
Example quests below rewarded before the PR 1.000 rep while they should give in WOTLK 500 rep. 
**Normal quests like:**
https://wowwiki.fandom.com/wiki/Quest:Fierce_Enemies
https://wowwiki.fandom.com/wiki/Quest:Proving_Your_Strength
**Repeatable quests like:** 
https://wowwiki.fandom.com/wiki/Quest:More_Warbeads
https://wowwiki.fandom.com/wiki/Quest:More_Warbeads
-  Update `reputation_reward_rates` to 1 for faction 941
-  Update `reputation_reward_rates` to 1 for faction 978
- Also update the `spell_rate` for faction 978 to 1
- Closes 
- Imported SQL wihtout errors on Win 10 Pro x64 and HeidiSQL v11
- Prepare:
`.modify rep 941 3000`
`.modify …
> fix(DB/reputation): Kurenai and Mag'har Reputation Rates

- data/sql/updates/pending_db_world/rev_1584388487036984300.sql
According to https://wow.gamepedia.com/Category:Removed_in_patch_3.3.3 these quests got deprecated in patch 3.3.3:
For Great Honor
Concerted Efforts
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1133
How to test:
Try to pick them up at the quest givers (15350,15351);
> fix(DB/Quest) Some Deprecated quests

- apps/installer/includes/includes.sh
joiner tool has been moved has been moved under azerothcore organization.
I've fixed the url and the path
So it's now available here: 
https://www.azerothcore.org/joiner/   , repo: https://github.com/azerothcore/joiner
the previous url doesn't exist anymore
Just run the acore.sh dashboard, it should download the new joiner under
/apps/joiner
however, the CI should do it too so we can just wait for it
> fix(bash): joiner tool has been moved

- src/server/game/Entities/Pet/Pet.cpp
- src/server/game/Handlers/PetHandler.cpp
-  Shows an unique name & pet details for a permanent "Risen Ghoul" created with the spell "Raise Dead" and the unholy talent "Master of Ghouls" (which makes the pet permanent)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2942 while still preserving the changes concerning the bug with permanent water elementals in https://github.com/azerothcore/azerothcore-wotlk/pull/2637
- tested build on Windows 10
- tested successfully in-game (works on permanent ghouls, ignores temporary ones or those summoned by the spell "Army Of The Dead" and the pet details of permanent Water Elementals are still hidden)
- play death knight
- activate the talent "Master of Ghouls" in the unholy tree
- Learn & use the spell "Raise Dead"
If you want to check, if the pet details of the permanent …
> fix(Core/Pet): Risen Ghoul random name & pet detail

- data/sql/updates/pending_db_world/rev_1588335399793049400.sql
Changes:
Min, Max & Modifier Damage for whole Dungeon.
Added flags for each boss, so they will appear with skull instead regular level elite.
All checks have been done trough Classic Realms and Youtube videos.
How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add very very basic gear (15 ilvl for example) towards each Dungeon.
> [Dungeon] Ragefire Chasm

- docker/database/Dockerfile
Mysqladmin use the right credentials so the error about not using password in the healthcheck is gone.
-  HEALTHCHECK --interval=5s --timeout=15s --start-period=30s --retries=3 CMD mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping -h localhost
[Note] Access denied for user 'root'@'localhost' (using password: NO)
tested on local docker instance
Startup the db container
> mysqladmin use the right credentials

- data/sql/updates/pending_db_world/rev_1588335862820761100.sql
Changes:
Min, Max & Modifier Damage for whole Dungeon.
Added flags for each boss, so they will appear with skull instead regular level elite.
All checks have been done trough Classic Realms and Youtube videos.
How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add very very basic gear towards each Dungeon.
> fix(DB/Creature): Deadmines

- src/server/game/Groups/GroupMgr.cpp
DELETE GROUP < 1 Members
-  [Update Query viewed in TrinityCore](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Groups/GroupMgr.cpp#L136)
- Builds
- Starting Server With MySQL 8.0 & MySQL 5.6
- Just start ur server
> fix(Core/Query): Update GroupMgr query to support MySQL 8.0

- .github/workflows/core_build.yml
- apps/ci/ci-install.sh
- deps/g3dlite/include/G3D/Vector3.h
After this PR, our CI will do the following checks
- clang-6 that also checks warnings **(no changes)**
- clang-9 that also checks warnings **(updated clang-7 to clang-9)**
- clang-10 **without** warnings check **(new)**
We can enable clang-10 warnings check (and remove clang-9) once all warnings of clang-10 are solved (see https://github.com/azerothcore/azerothcore-wotlk/issues/3108).
> feat(CI): update clang-7 to clang-9, add clang-10 build

- src/server/game/Battlegrounds/Battleground.cpp
If you set `Battleground.InvitationType = 0` the expected behaviour would be:
> Normal, Invite as much players to battlegrounds as queued, don't bother with balance
as described in `worldserver.conf`. However, it looks like that before this PR this only affected the **initial** invitation (when the BG starts). After the BG started, it kept balancing the teams even if `Battleground.InvitationType` was set to `0`.
This caused problems when using modules like [mod-cfbg](https://github.com/azerothcore/mod-cfbg) that has its own balancing system. So when using such modules, it's preferrable to disable the core's balance using `Battleground.InvitationType = 0`.
This PR makes sure that ``Battleground.InvitationType = 0` actually disables the core's balancing system, **always**.
This PR does …
> fix(Core/BG): fix BG_QUEUE_INVITATION_TYPE_NO_BALANCE

- src/server/game/Globals/ObjectMgr.cpp
-  Add a condition for normalizePlayerName to not search for existing names with a blank space " " in the end of the string.
-  Prevents global storage to go nuts and overwrite player info with missing information, as detailed on issue #3151
- Closes  #3151
- Tested on Ubuntu 18.04 and Debian 10.
- Without this PR, create a character with guild and arena team. With other character, send a mail to the first character, but on the receiver's name, add the condition mentioned above (I don't want to explicitly say the process). The mail won't be sent, but try and see what happens on world console, and then relogin the first character. This will cause issue #3151.
- With this PR, this won't happen. The mail won't be sent, and that's it.
- I've checked for other characters besides the space " ", …
> fix(Core/ObjectMgr): Avoid Global Storage issue

- src/test/CMakeLists.txt
**Unit Test Linking Problem**
Here is my build machine information: 
OS: Ubuntu 18.04.4 LTS
Compiler: GCC 7.5.0
Make: v4.1
CMake: 3.17.2
Currently, the build fails on my machine when the unit tests are enabled. The order of the libraries matters, and I got linking errors when the unit tests are being built. (These dependencies will probably be stubbed out or mocked in the future, but the current situation creates a build problem.) 
This tiny change in the MR solves the issue.
@FrancescoBorzi
> test: fix unit test linking problem in ubuntu 18.04

- .gitignore
- CMakeLists.txt
- src/test/CMakeLists.txt
**Add code coverage report**
Code coverage report generation becomes possible with this MR. After a successful build with unit tests enabled, the report generation can be triggered via 'make coverage' command under the build directory. Finally, the report becomes available under <project dir>/coverage_report.
@FrancescoBorzi
> test: add code coverage report

- apps/ci/ci-run-unit-tests.sh
-   Make the test CI run using relative path instead of hard-coded to avoid build problems in case of the path changing in any way, this includes the fork being named other than azerothcore-wotlk.
> fix(CI): launch CI unit test with relative path

- data/sql/updates/pending_db_world/rev_1601269291015416700.sql
This will fix the Naxxarmas 25 loot on Thaddius, Four Horsemen, Gluth and Loatheb as their current loot values are wrong.
(In 25 mode)
End wing bosses should drop 2 items + 2 tokens
Non-end wing bosses should drop 4 items
Gluth is a rare case, its loot is like an end wing bosses without being one: 2 items + 2 tokens
References:
End wing bosses like Thaddius
(at 2:55)  https://www.youtube.com/watch?v=WMVGZNe-cbo
Non-end wing bosses like Gluth:
(at 3:35)  https://www.youtube.com/watch?v=6_jUTBGQJew
(at 4:00)  https://www.youtube.com/watch?v=Yi85pjYGg0c
Source: https://www.mmo-champion.com/threads/625542-Simple-Question-How-many-items-per-Heoric-Naxx-Boss
-  Rebuild the looting system on these 4 bosses in order to make them work properly as they were at retail
- Never reported at AzerothCore …
> fix(DB/Loot): Naxxramas 25

- data/sql/updates/pending_db_world/rev_1601277180341917800.sql
This change will make the Nerubian Burrower immune to any cc effect, only interrupt or stun effects are allowed.
Reference is taken from retail videos and TankSpot guide at YouTube:
TankSpot's Guide to Heroic Anub'arak (25 Hard)
https://www.youtube.com/watch?v=zDmdb9RYecY
In the TankSpot video, they explain that only interrupt or stun effects are used to cut the cast of the adds, other cc's are never mentioned.
https://www.youtube.com/watch?v=PlMtNG8D2x0
= = = = = = = = = = = = = = = = = = = =
Original immune mask: 549520145
Fixed immune mask: 550187859
**Change makes immune to the following spells:**
-- 2094 | Blind
-- 339 | Entangling Roots
-- 60192 | Freezing Arrow
-- 3355 | Freezing Trap Effect
-- 49203 | Hungering Cold
-- 20066 | Repentance
-- 33786 | Cyclone
-- 9484 | Shackle Undead …
> fix(DB/creature_template): Nerubian Burrower's immunity

- src/server/scripts/Commands/cs_misc.cpp
This change avoids setting the same phase as the one the GM has to a player when this is summoned by command
-  Remove SetPhaseMask at the end of the command execution
- Closes #3702 
- Tested in-game in several locations with GM only stuff like the entrance of Undercity, Archerus, Orgrimmar, etc
Get 2 accounts, 1 of them should be GM.
Create a fresh character with your normal account, in this example, we are gonna call it 'human'
with the gm account use: `.tele tirisfal`
move close to the entrance of undercity where you will see tanks and some leaders/npcs
with the gm account use:  `.summon human`
- The GM account can see all the war stuff
- The normal account will only see the normal phase
-> Test in other places.
- N/A
When a PR is ready to be tested, it will be marked as **[WAITING TO …
> fix(scripts/Commands): Avoid get gm phase when summoning

- src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp
This change deletes the immune effect applied by script.
The intention is to remove the immune event which is triggered by the overload event, the immunity is not needed at all, seems it was implemented to prevent players to interrupt the Overload spell:
This spell by default cannot be interrupted so the immunity by script is useless and is just generating the issue #3728 
I have tried to interrupt with spell classes such as
[Shield Bash](https://wotlkdb.com/?spell=72)
[Kick](https://wotlkdb.com/?spell=1766)
[Mind Freeze](https://wotlkdb.com/?spell=47528)
none of them interrupted the spell (as expected)
-  Delete EVENT_IMMUNE
-  Remove ApplySpellImmune
- Closes #3728 
- Tested in-game:  Took 2 (big and mid bosses) down and left Brundir (small) alive, when he casts Overload, I tried to …
> fix(scripts/Ulduar): Assembly of Iron - interrupt immune effect

- data/sql/updates/pending_db_world/rev_1605661689213920900.sql
- src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp
- DB: Add missing broadcast_text for Computer npc.
- Script: Change Computer npc position so players can't see the chat bubble.
<details>
<summary>Tested on 10 and 25-man</summary>
</details>
.go c 137630
Push the button
> fix(Scripts/DB): Mimiron Computer NPC text

- data/sql/updates/pending_db_world/rev_1605586971095091500.sql
-  Remove Cataclysm gossip from Anduin Wrynn (id: 1747)
-  Remove quest giver and gossip flags from Anduin Wrynn (id: 1747)
- Anduin currently has gossip from a Cataclysm quest: https://wow.gamepedia.com/My_Son,_the_Prince (added Patch 4.0.3a)
- In WotLK, Anduin should not have any gossip at all, in WotLK he was simply a static NPC standing next to his dad.  Gossip for Anduin Wrynn was added in 4.0.3a (cataclysm) and beyond - https://wow.gamepedia.com/Anduin_Wrynn#Quotes
- Does not have any quests attached to him in WotLK
- Should only have two on-click voice lines (third was removed in 3.0.2, this is all correct currently though)
- Apply SQL
- Before: https://i.imgur.com/6fOVi7m.jpg
- After: no more gossip
1. Create Alliance Character
2. .tele stormwindkeep
3. Hover mouse over Anduin
1. …
> fix(DB/gossip): remove cataclysm gossip/gossip flag from Anduin Wrynn

- src/tools/mmaps_generator/MapBuilder.cpp
- src/tools/mmaps_generator/PathCommon.h
- src/tools/vmap4_extractor/vmapexport.cpp
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-use-emplace`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html
This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:
- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go
You can help by testing PRs and writing your feedback here in the PR's page on …
> refactor(Core): apply clang-tidy modernize-use-emplace

- src/server/scripts/Northrend/Nexus/Oculus/boss_urom.cpp
-  Restore position at death
-  Add missing brackets
- If Urom dies when he is casting "Empowered arcane explosion" in the air, his body will fail through the rift and nobody will be able to loot it, same issue like Noth at Naxxramas in the past.
-  Built
-  Tested in game
Go to the Oculus, complete almost all the dungeon until you have to fight with Urom
Try to leave him at 1% HP and wait until he cast "Empowered arcane explosion" in the air
Kill him when he is casting
- The body will appear at his original position so you can loot it.
- N/A
> fix(scripts/Oculus): Reset Mage-Lord Urom's position at death

- .github/README.md
Changed the catalogue link from catalogue/ to the new integrated page: catalogue.hml
> fix(README): catalogue link

- src/server/scripts/EasternKingdoms/SunwellPlateau/boss_felmyst.cpp
Change the way Felmyst selects the target for the beam which summons skeletons at the encounter.
All available players get one beam ❌ 
Only one player gets one beam ✔️ 
Sources:
- https://www.youtube.com/watch?v=zKIepv2-Yjo    (since 1:45: Only one target runs from the beam)
- https://wowwiki.fandom.com/wiki/Felmyst    "She will target **a** random player for a couple of seconds"
-  Convert CastSpell to CastCustomSpell in order to prevent AOE targets and just pick one valid target
- Felmyst currently summons one beam per player available in the encounter instead of pick just one as the expected blizzlike behavior
- Tested in-game locally and with a production/live server in the past.
You will need to bring 2 accounts  and make a raid group
.go c felmyst
Kill Brutallus
Wait for >1 minute …
> fix(scripts/Felmyst): Adjust beam target

- data/sql/updates/pending_db_world/rev_1609009225243254400.sql
Imported from https://github.com/TrinityCore/TrinityCore/issues/20162
-  Adjust 'spawntimesecs' in 'gameobject' for:
Cozzle's Footlocker
Captain's Footlocker
Soaked Tome
Rathis Tomber's Supplies
Dented Chest
Worn Chest
Crate of Ingots
Mysteries of the Light
The Saga of Terokk
First Aid Supplies
Night Elf Plans: An'daroth
An'owyn
Scrying on the Sin'dorei
Sealed Box
Dawn Runner Cargo/Warped Crates
- Improve spawn time on multiple low/mid-level game objects
Close: https://github.com/azerothcore/azerothcore-wotlk/issues/4060
- **Tested in-game**
- **SQL query applied:** /* Affected rows: 17  Found rows: 0  Warnings: 0  Duration for 3 queries: 0.125 sec. */
Same as described in https://github.com/TrinityCore/TrinityCore/issues/20162
- N/A …
> fix(DB/gameobject): Adjust spawntimesecs for multiple GOs

- data/sql/updates/pending_db_world/rev_1609414989791132104.sql
Moved the position of the NPC, fixed created by [Keira3](https://azerothcore.org/Keira3).
-  Move the position of the NPC 1766, guid 17952
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4116
`.go c 17952`
now, it should not be inside a tree
> fix(DB/Creature): position of guid 17952

- src/server/game/Entities/Unit/Unit.cpp
complex float calculations can have weird behaviours. I've added a check to use a simpler formula in case of catastrophic failures
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/4225
- Engage multiple NPCs at the same time (lot of them) to benchmark the stability of the repositioning system
> fix(Core/Crash): safe calculation in GetMeleeAttackPoint

- .github/workflows/core_build.yml
-  disable macos-11.0 in the mac-build matrix. Currently the github hosted macos runners do not have enough capacity and the build runs for macos-11.0 are often just failing to start.
- Closes 
> fix(CI): disable macos-11.0 in mac-build matrix

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Handlers/QuestHandler.cpp
- src/server/scripts/Commands/cs_quest.cpp
Co-Authored-By: Yehonal yehonal.azeroth@gmail.com
-  do not store quest if quest_id is null in `Player::CompleteQuest`
-  a bunch of types replaced by author
- Closes none, just a minor code improvement
- could be related to https://github.com/azerothcore/azerothcore-wotlk/issues/4005 but not sure about it
- Not tested
- Set `Quests.EnableQuestTracker` to `1` in `worldserver.conf`
- Make sure the `acore_characters.quest_tracker` table is properly filled when completing quests
- Optionally, you can use this old web tool to have a better view: https://github.com/TrinityCore/TC-Quest-Tracker
None …
> fix(Core/QuestTracker): do not store quest if quest_id is null

- src/server/scripts/Commands/cs_misc.cpp
The .save command has a `true` flag which claims it should create a character. It should be changed to `false` because the character obviously already exists at the time the command is used.
See https://github.com/azerothcore/azerothcore-wotlk/blob/0a8a7ef1494b1dcc43bdf5134f7c4836acc66f4e/src/server/game/Entities/Player/Player.cpp#L26487 regarding the syntax of the arguments.
Insert statement erroring out because character already exists. No saves to db happening.
- Built on Win10 64 with MySQL 5.7.18
- Tested on default account test1 and test10. .save works
- .save
- Watch worldserver console not erroring
- Possibly watch the db prior to and after the .save and see if e.g. level gains were saved to the `characters` table. …
> fix (Core/Commands) remove character creation flag from .save command

- data/sql/updates/pending_db_world/rev_1612676592853947300.sql
- src/server/game/ArenaSpectator/ArenaSpectator.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellInfo.h
- src/server/game/Spells/SpellMgr.cpp
-  Fix accidental removal of SPELL_ATTR0_CU_AURA_CC from https://github.com/azerothcore/azerothcore-wotlk/commit/0b35a24053f4d118b119fe792f187f816acbadfb
-  This will NOT affect anything regarding STEALTH
- This will RESTORE proper CC checks where they once were :)
- This WILL fix Druids once again being able to shapeshift to remove movement impairing effects :D
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4471
- Builds
1. As Shaman place Earthbind Totem
2. As Druid go into cat form and Prowl
3. Start a duel
4. See that Earthbind Totem will NOT break your stealth
5. Change Shapeshift and see that you WILL remove the movement impairing debuff. …
> fix(Core/Spell): Restore SPELL_ATTR0_CU_AURA_CC

- src/server/game/Spells/Spell.cpp
-  @Kitzunu helped me out by suggesting I add back a line of code that was removed in #4472 to make sure Stealth works properly.
- Closes #4489
- Ensured that Sprint doesn't break stealth, ensure shadowmeld puts player in stealth, ensure that vanish puts player in stealth, ensure that druid cat form can prowl.
1. Build
2. On Night Elf Rogue, Stealth and use Sprint.  Use Vanish.  Use Shadowmeld.
3. On Druid, use Cat form and then Prowl.
> fix(Core/Spell): Restore Stealth remove check

- data/sql/updates/pending_db_world/rev_1612566366687490200.sql
Fix position of Strange Lockbox for quest https://classic.wowhead.com/quest=30/trial-of-the-sea-lion
Actual position was based on classic content, after TBC the position was moved from fatigue zone and added a Bubbly Fissure.
Closes AzerothCore issue #4352
More info: https://wowwiki-archive.fandom.com/wiki/Quest:Trial_of_the_Sea_Lion_(Horde) and https://www.wowhead.com/quest=30/trial-of-the-sea-lion
-  Move from fatigue zone the Strange Lockbox
-  Add Bubbly fissure near the lockbox.
- Closes #4352
- Applied the SQL
- Then `.go o 27813`
- Take the quest [Trial of the sea lion](https://www.wowhead.com/quest=30/trial-of-the-sea-lion)
- Then `.go o 27813`
- There should be the Strange Lockbox near a Bubbly Fissure (no fatigue zone).
- Loot the pendant inside.
When a PR is ready to be tested, …
> fix(DB/gameobject) Strange lockbox position and add Bubbly Fissure

- data/sql/updates/pending_db_world/rev_1613242843051334000.sql
-  Adjust Position and remove piece of Ham from Reese Langston
-  Previously spawned somewhat in the bar table and had a piece of ham in the left hand which isn't blizzlike.  Source: https://wow.gamepedia.com/Reese_Langston
- .go c 79751
Before SQL
After SQL
> fix(DB/creature): Adjust Position and remove piece of Ham from Reese Langston

- data/sql/updates/pending_db_world/rev_1613357478020500900.sql
-  Move Copper Vein GUID 4788 a few feet from its original position to avoid spawning inside of a map object
- Closes #4574 
After SQL:
- .go gob 4788
> fix(db/GameObject): Adjust XYZ of Copper Vein

- data/sql/updates/pending_db_world/rev_1613512073209092300.sql
-  Add gossip for Commander Althea Ebonlocke
-  Adjust orientation for Councilman Millstipe
- Remove unnecessary spaces in Ambassador Berrybuck's text.
- Applied SQL and tested in-game - it fixes what i wanted it to.
- .tele Darkshire
- talk to Althea Ebonlocke, go into the building and look at Councilman Millstipe
- Stay for a few minutes and read the random text that all the NPCs say.  Ambassador's text should be fixed.
> fix(db/Creature): Darkshire NPC updates

- data/sql/updates/pending_db_world/rev_1613853959150972140.sql
- Let the  Captured Scarlet Zealot die in the end of quest Fields of Grief
- Changes carried over from the TC database - I eventually found [this](https://github.com/TrinityCore/TrinityCore/pull/16960) and added a co-author
- Reference: https://youtu.be/zZIfXkIC4b8?t=60
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4540
- Applied SQL, tested.
- `.quest add 407`
- (Remove the quest if done: `.quest remove 407`)
- `.go c id 1931`
- Click the zealot, watch him turn into a ghoul, run around and then die (when patched)
> fix(DB/SAI): Captured Scarlet Zealot should die

- src/server/game/Entities/Player/Player.cpp
-  Reduce fall damage if player have aura Divine Protection (498) [Paladin]
- Closes [4610](https://github.com/azerothcore/azerothcore-wotlk/issues/4610)
**Don't use Divine Protection:**
**Use Divine Protection:**
1) use Divine Protection, look damage fall
**.go xyz 2700 6081 100 571**
2) Don't use Divine Protection, look damage fall
**.go xyz 2700 6081 100 571**
3) Compare
> fix(Core/Spell): Divine Protection reduces fall damage

- src/server/game/Battlegrounds/BattlegroundQueue.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Handlers/BattleGroundHandler.cpp
- src/server/game/Scripting/ScriptMgr.cpp
- src/server/game/Scripting/ScriptMgr.h
- src/server/game/Server/WorldSession.cpp
-  Implement `OnBattlegroundDesertion` hook to support hooks like https://github.com/azerothcore/mod-desertion-warnings
-
> feat(Core/Hooks): OnBattlegroundDesertion

- data/sql/updates/pending_db_world/rev_1614901038211344456.sql
- src/server/scripts/World/npcs_special.cpp
-  make the same text of the chicken for alliance and horde as it should be
- remove the old and useless text
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4712
- https://github.com/chromiecraft/chromiecraft/issues/127
- .go cr id 620
- /chicken
- do /chicken a lot of time (use a macro maybe). the chicken will say `Chicken looks up at you quizzically. Maybe you should inspect it"` alliance and horde side (now), be friendly and give you the quest "CLUCK"
> fix(DB/Text): chicken text for CLUCK special quest

- data/sql/updates/pending_db_world/rev_1614968849352707375.sql
-  add prevQuest 364 for 3098 Glyphic Scroll & 3097 Hallowed Scroll
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4726
- Closes https://github.com/chromiecraft/chromiecraft/issues/126
create a mage
.q add 364
complete and see if the quests 3098 and 3097 are available
> fix(DB/Quest): prevQuest

- data/sql/updates/pending_db_world/rev_1615504923515644278.sql
-  move position of the gameobject
- Closes https://github.com/chromiecraft/chromiecraft/issues/188
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4796
- now the gamoebject is positioned correctly as the wowhead picture shows https://classic.wowhead.com/quest=567/dangerous
.go object 17154
> fix(DB/Gameobject): spawn position

- data/sql/updates/pending_db_world/rev_1615506284007051682.sql
porting from https://github.com/TrinityCore/TrinityCore/issues/22195
-  link suicide spell to sapper explode spell
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4798
- Closes https://github.com/chromiecraft/chromiecraft/issues/184
- .go cr id 1052
- reduce him to 0-15% health, he will casts the sapper exclude and (after PR) die
> fix(DB/Spell): suicide saboteur on sapper explode

- data/sql/updates/pending_db_world/rev_1615597737321479109.sql
-  Fix non hitable mobs Pridewing Soarer in Stonetalon Mountains
- Closes #4801
- Aplied SQL
- Mobs can be mark and kill, they are skinnable and drop only quest item (https://classicdb.ch/?npc=6141#drop)
- Go to Stonetalon Mountains
1st mob 47.60 46.63
2nd mob 47.78 38.90
Can be killed, skinned and drop quest item for quest Pridewings of Stonetalon
> fix(DB/Creature) bugged Pridewing Soarer

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
After certain spellcasts that trigger taxi paths such as 32474 on spellauras.cpp, these pending auras are supposed to be removed 
since they are supposed to substitute the model from the taxiID.
-  Removing the auras triggered by spells at the end of taxi flypaths
Not reported but fixes part of https://github.com/azerothcore/azerothcore-wotlk/pull/4819
- Compiled and tested on windows 10
This test requires the PR mentioned above:
1. .go c 31749
2. Talking to Susurrus it doesn't display any gossip menu options
3. .add 23843
4. Now the gossip option displays as "I am ready to be flown down to the Exodar"
5. After clicking on the option you receive "Buffeting winds of susurrus" and start flying down to the Exodar
6. When arriving to the destination the **Buffeting Winds of Susurrus** should …
> fix(Core): Removing auras from spells that trigger taxi

- src/server/game/Battlefield/Zones/BattlefieldWG.h
- Enums when passed into uint32 functions produce warnings
- Mixed enums with const std::array for readability and type safety
In preparation for Wintergrasp fixes. I've added a temporary solution to one of the many underlying problems on the core, passing enum values (which are int) into functions that receive uint32 numbers due to the ease of use of defining names to numbers such as this:
``` c++
enum npc_spells
{
SPELL_FIREBALL = 1234,
SPELL_TELEPORT = 5678
}
```
- Mixed enums with const array for readability and type safety
- Doesn't close any specific issue
- Compiled on Windows 10
- Doesn't need any other test since no logic was changed, just types sent to functions
Compile the core without errors
You …
> fix(Core): Code warnings clean-up 

- data/sql/updates/pending_db_world/rev_1615843852881240992.sql
- Allow [Pattern: Raptor Hide Harness](https://wotlkdb.com/?item=13287) to be learned by Alliance character when transfered via trade, mail or AH   
- Closes #4854
- Closes https://github.com/chromiecraft/chromiecraft/issues/204
- cmake, make on Linux without errors
- db_assembler.sh without errors
- checked DB using mysql command prompt
- learned pattern on Alliance character 
- Get Alliance character to LW skill >= 165 
- Run .additem 13287
- Learn the pattern
> fix(DB/item_template): Remove Horde-only flag from Pattern: Raptor Hide Harness

- data/sql/updates/pending_db_world/rev_1615882800304292617.sql
-  Change map marker coordinates for quest [The Principal Source](https://wotlkdb.com/?quest=6122) from (7218, -386) to (6882, -653). 
- Closes #4867
- Closes https://github.com/chromiecraft/chromiecraft/issues/212
- cmake, make on Linux without errors
- db_assembler.sh without errors
- checked DB using mysql command prompt
-  checked in game
- Roll an Alliance Druid
- `.quest add 6122`
- `.tele Auberdine`
- `.go xyz 6882 -653`
- Draw the sample (success)
> fix(DB/quest_poi): Wrong map marker position - The Princial Source (A)

- src/server/game/AI/SmartScripts/SmartScript.cpp
-  SAI creatures change to melee combat if the current spell is prohibited
- Closes #4468 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4091
- Tested on Defias Rogue Wizard and NPCs inside Hellfire Ramparts
- .go xyz -9224 -1006 71
- Stand at a distance from a Defias Rogue Wizard
- Interrupt it with Counterspell (.cast 2139)
- NPC will now change to melee attacks until the Counterspell's effect ends
> fix(CORE/AI): Added a condition to force casters into melee combat

- data/sql/updates/pending_db_world/rev_1616977871251124200.sql
- src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp
-  Implement the [NPC](https://www.wowhead.com/npc=36064/marked-immortal-guardian) into the world at the [Yogg-Saron](https://www.wowhead.com/npc=33288/yogg-saron)'s encounter (Ulduar)
-  Create spell script for [Shadow beacon](https://www.wowhead.com/spell=64465/shadow-beacon)
- The NPC nor the mechanic for his existence are used in AC
Link: https://wowwiki-archive.fandom.com/wiki/Immortal_Guardian
- Built:
SQL = /* Affected rows: 4  Found rows: 0  Warnings: 0  Duration for 5 queries: 0.000 sec. */
Core = ========== Build: 1 succeeded, 0 failed, 15 up-to-date, 2 skipped ==========
- Tested in-game as shown below:
Check guardians at Yogg-Saron's encounter when they are buffed with "Shadow beacon"
- N/A
A [Marked immortal guardian](https://www.wowhead.com/npc=36064/marked-immortal-guardian) …
> fix(scripts/DB): Implement "Marked immortal guardian"

- src/server/game/Movement/MotionMaster.cpp
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Spells/Spell.cpp
This reverts commit b4242735749ca6ff4d7e370cc0d41105f5856f60.
-  revert https://github.com/azerothcore/azerothcore-wotlk/pull/3384
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5021 …
> feat(Core/Spell): revert "feat(Core/Spells): improve SpellCheckRange(), spell cast when dismounting, falling or levitating spells (#3384)"

- data/sql/updates/pending_db_world/rev_1617105845198069500.sql
- Fixed Stats NPC: [Matis the Cruel (Herald of Sironas)](https://wowgaming.altervista.org/aowow/?npc=17664)
- Fixed SAI NPC: [Matis the Cruel (Herald of Sironas)](https://wowgaming.altervista.org/aowow/?npc=17664)
- Fixed **creature_addon** and **creature_template_addon** NPC: [Matis the Cruel (Herald of Sironas)](https://wowgaming.altervista.org/aowow/?npc=17664)
- Fixed **Waypoints**  NPC: [Matis the Cruel (Herald of Sironas)](https://wowgaming.altervista.org/aowow/?npc=17664)
- Fixed Stats NPC: [Tracker of the Hand](https://wowgaming.altervista.org/aowow/?npc=17853)
- Fixed **creature_template_addon** NPC: [Tracker of the Hand](https://wowgaming.altervista.org/aowow/?npc=17853)
- Fixed SAI NPC: [Tracker of the Hand](https://wowgaming.altervista.org/aowow/?npc=17853)
- Closes …
> fix(DB/CreaturesSAI): Quest Matis the Cruel

- data/sql/updates/pending_db_world/rev_1617172919168716426.sql
-  Remove a double spawn and pool the rest,  so it's 1 Black Lotus per zone per hour (and not 20 every 3 minutes)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5037
- Closes https://github.com/chromiecraft/chromiecraft/issues/309
- https://classicguides.org/black-lotus-farming-guide/ (comments say 1 per zone per hour)
- Notice that Blizzard has later changed this for more - it will be trivial to adjust this later if needed, using the created pool
- Applied SQL
- Visited locations
Before the PR:
(You only see 19 marks on the map, since 1 is a double spawn. So that's 20 spawns in total).
After the PR test 1:
and test 2:
So it looks fine to me.
- `.go object <guid>`, check the list with numbers
- Only 1 should be available at a time, once picked, it should respawn in 1 …
> fix(DB/pool_template): Fix Black Lotus in Burning Steppes

- data/sql/updates/pending_db_world/rev_1617177621821036427.sql
-  He should walk much slower (from 1.4 to 0.8)
- The number 0.8 was selected as a "seems about right" number. Anything from 0.7-0.9 is probably fine.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5011
- Closes https://github.com/chromiecraft/chromiecraft/issues/297
- https://youtu.be/xeW3Nl9akYA?t=1721 - from Classic, but he's slow as molasses going uphill on a cold day
- Applied SQL
- Did the quest. He walks slowly... but when testing, I found out there's more wrong... The issue is here:  https://github.com/azerothcore/azerothcore-wotlk/issues/4953. This does not invalidate this PR, but there's more to fix afterwards...
In order to start the event which makes Disciple of Naralex start walking, you must kill the 4 Leaders of the Fang
They can be found here:
.go …
> fix(DB/creature_template): Disciple of Naralax walking speed

- data/sql/updates/pending_db_world/rev_1617254287410662400.sql
This spell is applied when players in Obsidian Sanctum enters to twilight portal.
By default this spell is applied by player himself, at initial point its counted as positive spell and any damage increase spells which player gets - it increases damage on that aura.
Also this aura shouldn;t be applied on npcs (only on players).
-  Marked aura effects as negative
-  Added condition to allow casting this aura only on players.
- Closes 
- Entered to twilight portal and used damage increase spells (tested mainly on warrior, with death wish)
- 
To test these change, well, its enough to enter to twilight portal in Obsidian Sanctum and try to use some damage increase buffs (berserk, enrage, death wish).
You can help …
> fix(DB/Spells): spell "57874 Twilight Shift" should be negative + target only players

- data/sql/updates/pending_db_world/rev_1615275106559909076.sql
- Set  ranged attack times to default for all creatures
- Suggested here: https://github.com/azerothcore/azerothcore-wotlk/pull/4637
- This was done by TC here: https://github.com/TrinityCore/TrinityCore/commit/b7b1c2df790f1eb9203f084045e90ee5f9e1ebb5
- ~~I'm not sure if we should do the same, so marking this for in need of feedback~~
- This is just to take the discussion, you are very welcome to disagree
- It could be relevant for https://github.com/azerothcore/azerothcore-wotlk/pull/4749
- None
> fix(DB/creature_template): Set RangeAttackTime to default value

- src/server/game/Entities/Object/Object.cpp
- src/server/game/Spells/Spell.cpp
Fixed #4510.
- Closes #4510.
- Tested ingame with fishing skill in Valley of Honor. …
> fix(Core/Movement): Corrected calculating ground level in shallow water.

- data/sql/updates/pending_db_world/rev_1617403339704819681.sql
-  make the quests "A new plague" available for all hordes
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5109
- Closes https://github.com/chromiecraft/chromiecraft/issues/326
WoWhead https://classic.wowhead.com/quest=369/a-new-plague (and wowgaming/AoWoW, so TC DB)
didn't test
try to take the quests with an horde that is not undead …
> fix(DB/Quest): make quest "a new plague" for Horde

- src/server/game/DungeonFinding/LFGMgr.cpp
- After finishing random dungeon, RDF cooldown is removed from players
- Closes #5001
- Closes chromiecraft/chromiecraft#294
- Log in with 5 players
- From group using RDF 
- Finished dungeon before cooldown (15min)
- Disband group
- Check if players are able to queue RDF again …
> fix(Core): Remove RDF cooldown after completion

- src/server/game/Spells/Auras/SpellAuras.cpp
cp from tc
-  Don't remove proc charges from spells with SPELL_ATTR6_DONT_CONSUME_PROC_CHARGES
<details>
<summary>Spells with the attribute</summary>
dbc_spell
---
```sql
SELECT `id`, `name_lang_1`, `attributesEx6`
FROM `dbc_spell` 
WHERE `attributesEx6` & @flag = @flag
```
| id | name_lang_1 | attributesEx6 | 
| ---: | --- | ---: | 
| 698 | Ritual of Summoning | 32 | 
| 1464 | Slam | 32 | 
| 8820 | Slam | 32 | 
| 11604 | Slam | 32 | 
| 11605 | Slam | 32 | 
| 25241 | Slam | 32 | 
| 25242 | Slam | 32 | 
| 46584 | Raise Dead | 32 | 
| 47474 | Slam | 32 | 
| 47475 | Slam | 32 | 
| 47632 | Death Coil | 32 | 
| 47633 | Death Coil | 32 | 
| 53352 | Explosive Shot | 32 | 
| 53353 | Chimera Shot - Serpent | 33 | 
| 53769 | Death Coil | 32 | 
| 60856 | TF-Xplosive Rocket Turret | 32 | 
| 61999 | …
> fix(Core/Spell): Make use of SPELL_ATTR6_DONT_CONSUME_PROC_CHARGES

- data/sql/updates/pending_db_world/rev_1617634980911314885.sql
the waypoint were there, the only missing thing was the movementType in the creature table
-  set movementType to 2 for Rageclaw in creature table
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5153
- Closes https://github.com/chromiecraft/chromiecraft/issues/345
.go cr id 7318 …
> fix(DB/Creature): set movementType to 2 for Rageclaw

- data/sql/updates/pending_db_world/rev_1617915554384852400.sql
-  Allow Demoralizing Roar to break stealth  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5181
It was changed in Cata to not break stealth.
- None 
1. Duel
2. be in stealth
3. cast demoralizing roar on the stealth
4. it should reveal them …
> fix(DB/Spell): Demoralizing Roar

- data/sql/updates/pending_db_world/rev_1617988329167837335.sql
-  Add two chests (guids `(16946,100068)`) in Northfold Manor into a gamepool, sharing respawn of 15 minutes, with 1 max limit
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5211
- Verify the issue is reproducible in the latest master
- Rebuilt using docker on Linux host
- Tested locally to verify no chest in `.go object 100067` in two minutes.
- Verify the issue is reproducible in the latest master
- Apply the SQL update file.
- Reload the world `.reload all`
- Verify that there is only one chest spawned across two locations (`.go object 100067`, `.go object 16946`)
- Loot the chest
- Wait 15 minutes (when I was testing it I updated the spawn time to something more feasible for testing)
- Verify that there is only one chest spawned across two locations (`.go object …
> fix(DB/GameObject-Spawn): Solid Chest respawn time for gameobject 100068,16946

- data/sql/updates/pending_db_world/rev_1617170212396609300.sql
-  Make both Mikhail and Slim Active for the duration of event
-  Use hashmap targeting to overcome targeting distance limitations
- Slim is walking just barely too far to target and send data back to Mikhail on a failed quest so Mikhail never returns to Quest Giver status without a GM respawning Mikhail
- Closes #4871
- I did the how to test changes section instructions.  
- 
- .add quest 1248
- Complete quest at Mikhail (.quest remove 1249, 1250 before if you already did quests)
- Accept Subdue Slim quest 1249
- Just stand there and wait for a quest fail
- Wait at least 10 seconds more then abandon failed quest.
- Mikhail should allow you to accept the Subdue Slim quest
- Also test by following Slim to his final waypoint when he despawns 
- wait 10 seconds and return to Mikhail and …
> fix(DB): The Missing Diplomat Part 11 Fix

- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
Fixed #4603.
-  Added code that enables pets to always follow its master.
- Closes #4603
- Tested ingame on Warsong Gulch with warlock's Imp …
> fix(Core/Movement): Make sure pet always follows its master.

- src/server/game/Battlegrounds/BattlegroundMgr.cpp
- Correct return BattlegroundQueueTypeId for arena queue
- Closes #5279
- In game
- Try enter arena queue …
> fix(Core/BGQueue): correct return BattlegroundQueueTypeId

- data/sql/updates/pending_db_world/rev_1618169871194421039.sql
-  move spawn out from the tree
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5241
- Closes https://github.com/chromiecraft/chromiecraft/issues/404 
.go cr 24506 …
> fix(DB/Creature): move creature spawn

- data/sql/updates/pending_db_world/rev_1618169172923159272.sql
-  removed duplicates nodes
-  moved one small thorium vein in the right position
- Closes https://github.com/chromiecraft/chromiecraft/issues/401
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5242
- Closes https://github.com/chromiecraft/chromiecraft/issues/393
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5233
- Closes https://github.com/chromiecraft/chromiecraft/issues/398
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5234
Now you will not see the duplicates listed in the issues …
> fix(DB/Spawns): duplicate nodes

- data/sql/updates/pending_db_world/rev_1618709045226609356.sql
- Update the loot table of Broken Tooth to be more consistent with Wowhead
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5336
- Spawn a bunch of Broken Tooth, kill them and verify the loot is as expected.
1. `.npc add 2850`
2. Target it and do `.damage 10000`
3. Loot it and verify that the loot table is as in https://classic.wowhead.com/npc=2850/broken-tooth#drops;0-3+17-21+1 …
> fix(DB/creature_loot_template): Fix Broken Tooth loot table

- data/sql/updates/pending_db_world/rev_1619469854375537568.sql
-  link to brewfest the 2 gameobjects in SilvermoonCity
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5422
- Closes https://github.com/chromiecraft/chromiecraft/issues/459
.go obj 59183
.event start 24
.event stop 24
you will see the gameobject appearing and disappearing, repeat the same with gameobject 59184 …
> fix(DB/game_event_gameobject): link to brewfest 2 gameobjects

- data/sql/updates/pending_db_world/rev_1619636650124390405.sql
- deleted the waypoint path of the Hezrul's companions and used the creature_formations
-  Close https://github.com/chromiecraft/chromiecraft/issues/472
-  Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4398
- tested in-game 
.go cr 13991
try to attack Hezrul from a far distance and see if the bodyguards attack you …
> fix(DB/creature_formations): hezrul bodyguards path and formations

- data/sql/updates/pending_db_world/rev_1619891302194258700.sql
- data/sql/updates/pending_db_world/rev_1619893844216235100.sql
-  Add graveyard for zone 1537 (ironforge)
- Closes [5579](https://github.com/azerothcore/azerothcore-wotlk/issues/5579)
- Issue wasn't just in lava, but all of Ironforge as well.
- Teleports player to correct graveyard in Ironforge.
- .tele ironforge
- select yourself and .die
- release spirit …
> fix(DB/Graveyard): add ghostZone for zone 1537

- data/sql/updates/pending_db_world/rev_1620033619588576561.sql
- Remove Silver Piffeny Band (7342) from chest (gameobject) loot
- Also remove Mood Ring (7338), Miniscule Diamond Ring (7339) and Cubic Zirconia Ring (7341)
- Closes #5607
- Closes https://github.com/chromiecraft/chromiecraft/issues/527
- https://wotlkdb.com/?item=7338#sold-by-npc
- https://wotlkdb.com/?item=7339#sold-by-npc
- https://wotlkdb.com/?item=7341#sold-by-npc
- https://wotlkdb.com/?item=7342#sold-by-npc
- https://wowpedia.fandom.com/wiki/Mood_Ring?oldid=2467657
- https://wowpedia.fandom.com/wiki/Miniscule_Diamond_Ring?oldid=2467448
- https://wowpedia.fandom.com/wiki/Cubic_Zirconia_Ring?oldid=2453741
- https://wowpedia.fandom.com/wiki/Silver_Piffeny_Band?oldid=2515822
- SQL statement executed
- Execute the SQL statements mentioned in  the bug report …
> fix(DB/gameobject_loot_template): Silver Piffeny Band should not be lootable from chests

- apps/docker/Dockerfile
- apps/docker/docker-cmd.ts
- apps/installer/includes/os_configs/ubuntu.sh
- bin/acore-restarter
- conf/dist/config.sh
Added more support to the gperftools (integrated in AzerothCore since 2016)
This is a powerful tool from google that allows you to get monitoring information to profile the CPU and the memory
Also useful to spot memory leaks
Screenshot with AzerothCore:
Video demo:
Soon available
GOOGLE PERF TOOLS
Repository: https://github.com/gperftools/gperftools#readme
Documentation: https://gperftools.github.io/gperftools/
Install (Ubuntu):
sudo apt-get install google-perftools libgoogle-perftools-dev
Note: dependencies above are already installed in docker
Usage:
1. To enable the gperftools you need to compile with the -DWITH_PERFTOOLS=ON compiler flag. You can use CUSTOMOPTIONS above to set it for the dashboard compiler
2. Configure the variable below accordingly to your needs
3. run the …
> feat(bash): Improved support for gperftools

- data/sql/updates/pending_db_world/rev_1620425644910599900.sql
- Delete path info for minions (only boss need to have one)
- Create formation group using Tho'grun as core leader
- Closes #5698
- Closes https://github.com/chromiecraft/chromiecraft/issues/564 
https://www.youtube.com/watch?v=efOrXMZriLU
- Tested …
> fix(DB/creature_formations): Adjust Boss Tho'grun's group

- data/sql/updates/pending_db_world/rev_1620435208642994700.sql
- Adjust Ravelosh's loot with the classic loot table
- https://classic.wowhead.com/npc=6910/revelosh
- Closes #5707
- Closes https://github.com/chromiecraft/chromiecraft/issues/559
> fix(DB/creature_loot_template): Revelosh items drop

- data/sql/updates/pending_db_world/rev_1620616751102617000.sql
The path 111980 is from an NPC in a camp in Swamp of Sorrows but is currently unknown who is the owner.
This path is no active in TC 3.3.5a branch and it was removed in Cataclysm
https://github.com/TrinityCore/TrinityCore/blob/f759809d9d4364bc1d988e4390d3d5a33d5469e9/sql/old/4.3.4/TDB5_to_TDB6_updates/world/130_reguiding.sql#L1
-  Remove path info from Blackwater Deckhand
- Closes #5757
- Tested …
> fix(DB/creature_addon): Remove path info from Blackwater Deckhand

- src/server/scripts/World/npc_innkeeper.cpp
-  Use the texts in the database which are already translated.
- https://github.com/azerothcore/azerothcore-wotlk/issues/5809
- After applying the script, the texts appeared in Spanish (since it is the game client I use) but it should be able to be translated in several languages.
- However, it can be tested without the event. It is preferable to activate it: `event start 12`
- If it is an alliance: `.go c 110585`
- If horde: `.go c 97714` …
> Fix(Core) Remove hard-coded texts from npc Innkeeper

- src/server/game/Entities/GameObject/GameObject.cpp
Fixed #5771.
-  Fixed a typo introduced with ObjectGuid class implementation.
-  
- Closes #5771
- Tested ingame with Undercity portal in Stormwind. …
> fix(Core/Gameobjects): Fixed loading addon table.

- src/server/game/Loot/LootMgr.cpp
- src/server/game/Loot/LootMgr.h
Patch ported from TC
Original Author:  @Wyrserth 
(copied from TC PR)
> Currently Loot::AddItem() will increase unlootedCount without checking LootItem::AllowedForPlayer's result first. This means that items that cannot be looted by any player can be added to the loot. Because nobody can loot them, they're never removed and the creature will show an empty loot window and can't be skinned as a result.
> However, in some cases the dropped item is not visible by some players (because they're not allowed to loot it) but should start a roll if any other player in party/raid can loot it. This case is also fixed in this PR. 
This appllies 100% to our issue with Fishing Trunks staying in the inventory when it contains an invisible **Weather-Beaten Journal**.
- Closes #5372
- Closes …
> fix(CORE/Loot): make Loot::AddItem() honor LootItem::AllowedForPlayer()

- data/sql/updates/pending_db_world/rev_1620835284341181100.sql
-  He should now yell when banner is placed
- Closes #5808
Original fix -> https://github.com/TrinityCore/TrinityCore/issues/18444
Thanks to @Rushor !
On windows 10 local server
1. .quest add 11162
2. .additem [stonemaul banner]
3. .go c 31463 takes you to a mob right outside the Onyxia Lair entrance
4. Plant the banner in front and see Smolderwing spawn
I don't know about the flying over that the bug report mentions seperately. That might need me to take a 2nd look at it. …
> fix(DB/Quest) Smolderwing from TrinityCore

- data/sql/updates/pending_db_world/rev_1620842884434937800.sql
-  Remove The Scarlet Key (ID 7146) from Scarlet Diviner, Scarlet Chaplain and Scarlet Monk loot tables (IDs 4291,4299,4540 respectively)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5806
- Closes https://github.com/chromiecraft/chromiecraft/issues/618
"You get the key from a chest after finishing the Library wing in SM." (https://classic.wowhead.com/item=7146/the-scarlet-key#comments:id=52)
- Tested in-game. Windows 10 - enGB client.
1. `.go c id 4299` …
> fix(DB/creature_loot_template): Remove the Scarlet Key from creature loot tables

- data/sql/updates/pending_db_world/rev_1621246170226501700.sql
- Prevent Blackhoof Cages (ID 186287)  from despawning
- Make the cages not selectable after they close, while there's no Theramore Prisoner alive inside (roughly 60 seconds)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5790
- Closes https://github.com/chromiecraft/chromiecraft/issues/602
The cage should not despawn, but reset and wait for another prisoner spawn (or spawn same time/before the prisoner)
https://www.wowhead.com/quest=11145/deprecated-prisoners-of-the-grimtotems
- Tested in-game. Windows 10 - enGB client.
1. `.go go 11719`
2. `.add [Grimtotem Key]`
3. Open one of the cages and observe …
> fix(DB): Adjust Blackhoof Cage behaviour

- data/sql/updates/pending_db_world/rev_1621414710329639831.sql
Only Gesharahan (id: 3398) should be able to drop Shiver Blade (id: 5182), with a ~72% drop chance.
Currently no gameobjects or creatures drop Shiver Blade directly. It's only included in a reference table:
```
SELECT * FROM `creature_loot_template` WHERE `Item` = 5182;
Empty set (0.080 sec)
SELECT * FROM `gameobject_loot_template` WHERE `Item` = 5182;
Empty set (0.018 sec)
```
```
SELECT * FROM `reference_loot_template` WHERE `Item` = 5182;
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+--------------+
| Entry | Item | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment      |
+-------+------+-----------+--------+---------------+----------+---------+----------+----------+--------------+
| 24060 | 5182 | …
```
> fix(DB/loot): Fix Shiver Blade drop

- data/sql/updates/pending_db_world/rev_1621426406097836315.sql
Some Scarlet Monastery mobs were dropping items they were not supposed
to. Reference table 24053 consists of these items. Refs to this table
from the affected creatures were removed.
```
SELECT * from `reference_loot_table` WHERE `entry` = 24053;
+-------+-------+-----------+--------+---------------+----------+---------+----------+----------+----------------------+
| Entry | Item  | Reference | Chance | QuestRequired | LootMode | GroupId | MinCount | MaxCount | Comment              |
+-------+-------+-----------+--------+---------------+----------+---------+----------+----------+----------------------+
| 24053 |  2277 |         0 |      0 |             0 |        1 |       1 |        1 |        1 | Necromancer Leggings |
| 24053 |  2565 |         0 |      0 |             0 |        1 | …
```
> fix(DB/loot): Adjust SM mobs' loot tables

- data/sql/updates/pending_db_world/rev_1621496626209255481.sql
Andorhal sign (id: 30079) was floating in midair next to a signpost, but
its orientation was correct. It has been attached to the signpost, below
the sign pointing to Strahnbrad.
- Place floating Andorhal sign below the Strahnbrad sign on the nearby signpost
- Closes #5945
- Closes https://github.com/chromiecraft/chromiecraft/issues/674
1. `go o 30079`
2. Make sure the signpost looks ok …
> fix(DB/gameobject): Fix Andorhal sign location

- src/server/scripts/Spells/spell_generic.cpp
- Fix crash in spell_pvp_trinket_wotf_shared_cd that was due to the script sending data2 packet empty.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6046
- Builds
- Tested in-game, script works as it should
You need to test this two ways.
1. Be horde
2. .learn 7722 (Undead racial)
3. .additem (https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=42292#used-by-item any horde item here)
4. Use either the spell or the trinket, the one you do not use should go on a 45s cooldown …
> fix(Core/Spell): packet build in spell_pvp_trinket_wotf_shared_cd

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Handlers/MovementHandler.cpp
- Resurrect players upon entering instance portals even if their corpse is not spawned in the world
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5896
- Closes https://github.com/chromiecraft/chromiecraft/issues/577
- Applied C++ fix and tested on Windows 10 clients and server
1. Log in with 5 characters
2. Queue the 5 characters in random dungeon finder
3. When everyone is in the instance, have one of the players die (don't release spirit)
4. Close the game for the character that died with alt+f4
5. Wait until the dead character appears offline
6. Votekick the dead character
7. Log back in on the dead character
8. As a ghost, run to the instance portal and enter it
9. Verify that you are spawned inside the instance alive …
> fix(Core): fix instance portal not resurrecting when corpse is not spawned

- src/common/Utilities/Util.h
* Add AsUnderlyingType function to cast enum value to its underlying type (avoids repeating std::underlying_type everywhere)
(cherry picked from commit https://github.com/TrinityCore/TrinityCore/commit/fdd9227b232db9aae9bc4b2c60ca4de2cdaa0b54)
Co-Authored-By: Shauren <shauren.trinity@gmail.com>
Needed for https://github.com/azerothcore/azerothcore-wotlk/pull/6109
* Add AsUnderlyingType function to cast enum value to its underlying type (avoids repeating std::underlying_type everywhere)
- nome
Not used yet …
> feat(Core/Util): AsUnderlyingType

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/Spell.h
Fixed #5263.
-  Changes the way potion cooldowns are handled via spell casts.
-  
- Closes #5263.
- Tested ingame with Troll's Blood Elixirs and Healing potions.
Follow #5263. …
> fix(Core/Spells):triggering potion cooldowns (from TC)

- apps/db_pendings/import.sh
- data/sql/updates/pending_db_auth/rev_1621715473238990700.sql
- data/sql/updates/pending_db_characters/rev_1621715444570678000.sql
- data/sql/updates/pending_db_world/rev_1621709841145351300.sql
-  This is good and can open for opportunities where we can output current DB version with commands ingame etc.
- Introduce date column
-  Don't update and check column name
- Start to check latest date column instead
- insert date when importing DB
1. run import.sh and db_assambler
WHEN MERGED!!!!
We need to MANUALLY DELETE THIS FOR THE DB FILES:
```sql
SELECT date INTO @COLEXISTS
FROM version_db_db
ORDER BY date DESC LIMIT 1;
IF @COLEXISTS <> '"$oldVer"' THEN LEAVE proc; END IF;
```
when the CI has run the script for ONLY THESE FILES IN THE PR. Otherwise importing with db_assambler will break.
It works as it should after that and we don't need to touch it again.
- Tested locally with import.sh and db_assambler.sh 
| # | C |
| :- | :- | 
| 1 | File that imported these changes (The ones …
> feat(DB/Version): Add date on update

- data/sql/updates/pending_db_world/rev_1621659447273280925.sql
The Staff of Horrors should only be dropped by Skeletal Horrors with a ~1.6% drop rate. At the moment it is contained in a reference table that is shared by several hundred NPCs instead, and is not directly dropped at all.
-  Remove Staff of Horrors from reference_loot_table 24062.
-  Add it to Skeletal Horrors drop table with 1.6% drop rate.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5987
https://classic.wowhead.com/item=880/staff-of-horrors
I have chosen to use the Wowhead drop rate over that of WOTLKDB because Wowhead's data is more likely to be accurate.
- Checked modified tables in Keira
1. Check Skeletal Horror (entry 202) loot table
2. Check Staff (880) doesn't drop anywhere else
3. Check Staff is not contained in any reference tables.
N/A. …
> fix(DB/loot): Fix Staff of Horrors drops

- deps/acelite/VERSION
VERSION was deprecated when acelite was bumped to newer version 7 months ago, and now we have VERSION.txt
deleting VERSION might fix Windows CI build... Hopefully... 
ace... ace... ace... 💩
> chore(deps/acelite): Remove VERSION

- src/server/game/Entities/Unit/Unit.cpp
-  Added `EMOTE_ONESHOT_NONE` to `m_uint32Values` when a unit enters combat.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5515
https://youtu.be/vVRB_1s38QA?t=116
- Tested without the changes: mobs continue the emote animation when fleeing.
- Tested in game on linux/docker setup from windows client.
- Tested with the changes: mobs don't play the emote animation when fleeing
1. Rebuild against the change in this branch.
2. Go to Azurelode Mine in Hillsbrad Foothills.
3. Clear nearby mobs.
4. Lower HP of the Hillsbrad Miner to the point where they flee.
5. Watch the fleeing animation.
6. The Hillsbrad Miner shouldn't be playing the mining animation. …
> fix(Core/Unit): Prevent Unit emote when entering combat

- src/server/game/Spells/SpellScript.cpp
- src/server/game/Spells/SpellScript.h
* Cherry-pick https://github.com/TrinityCore/TrinityCore/commit/f2f0aeb562dfc1a78b04d13a14e3c37a58367619
Co-Authored-By: Shauren <shauren.trinity@gmail.com>
- Allow spell script ValidateSpellInfo to work with any container type
- Does not break current Validation …
> feat(Core/Script): allow ValidateSpellInfo to work with any container type

- src/server/database/Database/DatabaseWorkerPool.cpp
- src/server/database/Database/MySQLConnection.cpp
- src/server/database/Database/MySQLConnection.h
- src/server/database/Database/Transaction.cpp
Fix transactions not being recommitted on dead-lock error (error code 1213) because of calling http://dev.mysql.com/doc/refman/5.0/en/mysql-errno.html after sending the ROLLBACK command. This way the returned error code was related to the ROLLBACK command, not the failed transaction.
- Updates #3679.
-  Not tested 
Follow #3679. …
> fix(Core/Shared/DB): transactions not being recommitted on dead-lock error

- src/server/scripts/Northrend/VaultOfArchavon/boss_toravon.cpp
Toravon The Ice Watchter in Archavon when dead the Orbs not despawn
-  Add the despawn of the Orbs on Toravon Icewatcher when he dies
- https://github.com/azerothcore/azerothcore-wotlk/issues/5494
1. .go c id 38433
2. Wait until boss spawns "Frozen Orb"
3. Kill the boss
4. Look how now the Orb disappeared correctly :D
> fix(Scripts/VoA): Toravon Orbs Bug

- data/sql/updates/pending_db_world/rev_1621968262932056500.sql
- Fix loot NPC: [Rotting Slime](https://wowgaming.altervista.org/aowow/?npc=3928)
- Closes https://github.com/chromiecraft/chromiecraft/issues/432
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5339
1.
2.
3. …
> fix(DB/creature_loot_template): NPC loot: Rotting Slime

- data/sql/updates/pending_db_world/rev_1622103568572292814.sql
Some loot tables mistakenly include reference table 24060, which (mostly) contains equipable items with an average itemlevel of 20.36:
```sql
SELECT AVG(itemlevel) FROM `item_template` it JOIN `reference_loot_template` rlt ON it.entry = rlt.item WHERE rlt.entry = 24060;
```
```
+----------------+
| AVG(itemlevel) |
+----------------+
|        20.3649 |
+----------------+
```
List of creatures where the deviation between this number and the given creature's avg level is higher than 10:
```sql
SET @AVG = (SELECT AVG(itemlevel) FROM `item_template` it JOIN `reference_loot_template` rlt ON it.entry = rlt.item WHERE rlt.entry = 24060);
SELECT ct.entry, ct.name, ROUND(ABS(@AVG - (ct.minlevel + ct.maxlevel) / 2), 2) AS delta
FROM 
`creature_loot_template` clt 
JOIN `creature_template` ct ON …
```
> fix(DB/loot): Clean up refs to ref table 24060

- data/sql/updates/pending_db_world/rev_1622106798992540218.sql
Here's a list of all Noblegarden-related items that I could find:
```sql
SELECT `entry`, `name` FROM `item_template` WHERE `entry` IN (6833, 6835, 7806, 7807, 7808, 7809, 19028);
```
```
+-------+--------------------+
| entry | name               |
+-------+--------------------+
|  6833 | White Tuxedo Shirt |
|  6835 | Black Tuxedo Pants |
|  7806 | Lollipop           |
|  7807 | Candy Bar          |
|  7808 | Chocolate Square   |
|  7809 | Easter Dress       |
| 19028 | Elegant Dress      |
+-------+--------------------+
```
These items are normally available from Brightly Colored Eggs. No creatures should drop these items, with the exception of Candy Bar and Lollipop which are dropped by a select few named NPCs.
None of these items are included in reference tables so no intervention …
> fix(DB/loot): Fix messed up Noblegarden loot

- data/sql/updates/pending_db_world/rev_1622117565567403115.sql
Removes three overlevelled items from NPCs. Checked  and all three items are well outside the standard level range, and should not be dropped by these NPCs.
I did consider modifying the Sawtooth drops to be reference table IDs instead of just deleting them, as the numbers are in the right range and it looked as if that's what they were originally supposed to be. However, checking those reference IDs, they contained various recipes that were as much as 10 levels higher than the Sawtooths, so were not level appropriate. So instead I am simply deleting them.
Partially addresses https://github.com/azerothcore/azerothcore-wotlk/issues/6000
- Remove Shriveled Heart (iLvl 45) from Farmer Ray (lvl 23)
- Remove Sunroc Mask (iLvl 96) from Sawtooth Crocolisk (lvl 39)
- Remove Sunroc Gloves (iLvl 96) …
> fix(DB/loot): Remove overlevelled items

- data/sql/updates/pending_db_world/rev_1622344663132928321.sql
-  Delete misplaced Earthroot node with GUID 1962 from Menethil Harbor.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6091
- Close https://github.com/chromiecraft/chromiecraft/issues/715
https://tbc.wowhead.com/object=1619/earthroot
- Ran SQL, 1 row affected as expected.
1. ```SELECT * FROM gameobject WHERE `id` = 1619 AND `guid` = 1962``` should return 0 rows. …
> fix(DB/spawn) Remove Earthroot node from Menethil Harbor

- data/sql/updates/pending_db_world/rev_1622559179437510182.sql
Kurdros and Granistad NPCs are now wandering randomly in a small radius like they're supposed to.
- Adjust Kurdros (16025) and Granistad (16027) movement type and wander radius.
- Closes #6156
- Closes chromiecraft/chromiecraft#749
Video footage from classic: (watch the beginning)
https://www.youtube.com/watch?v=sQuox81DZYA
1. `.go c 16025`
2. Make sure both griffins fly around randomly …
> fix(DB/creature): Kurdros and Granistad movement

- data/sql/updates/pending_db_world/rev_1622617341739892363.sql
Son of Arugal (id: 18424) was standing still. The only "source" I have found claims that he doesn't have a set path, so I made him wander around instead.
-  Give Son of Arugal (18424) random movement
- Closes #6084
https://vanillawowdb.com/?npc=2529 - only the one on the top has a path, 18424 is the bottom one
1. `go c 18424`
2. Watch him wander around …
> fix(DB/creature): Son of Arugal movement

- src/server/scripts/Spells/spell_paladin.cpp
Fixed #5517
-  Added check if proc target is alive.
- Closes #5517
- Closes https://github.com/chromiecraft/chromiecraft/issues/476
1. Get a Paladin to level 20 and pick the Seal of Command talent
2. Apply Seal of Command
3. Kill stuff …
> fix(Scripts/Spells): Seal of Command cannot be casted on dead targets.

- data/sql/updates/pending_db_world/rev_1622621882267236728.sql
Some Greymist murlocs were standing still instead of wandering around as they're supposed to.
I checked all Greymist murlocs (template id 2201 - 2208) and made them move around randomly, except if they were obviously meant to stand still (guarding something).
I also flipped murloc 37990 around because he wasn't facing the bonfire he's standing next to, unlike his homies.
Closes #6020
- Make some stationary murlocs wander around instead
- Adjust murloc 37990 orientation 
- Closes #6020
None
1. `.go c 37974`, make sure they're moving around
2. `.go c 37990`, make sure he's facing the bonfire …
> fix(DB/creature): Greymist murlocs movement

- data/sql/updates/pending_db_world/rev_1622632251168886593.sql
Drinking Bethor's Potion (spell id: 7669) triggered the Hex of Ravenclaw
Removal (spell id: 8320), which was supposed to remove the Hex of
Ravenclaw debuff from the caster (spell id: 7656), but it didn't.
- Adjust Hex of Ravenclaw Removal (spell id: 8320) to actually do what its name suggests
- Closes #5906
- Closes chromiecraft/chromiecraft#661
https://classic.wowhead.com/item=3251/bethors-potion#comments
https://user-images.githubusercontent.com/39011611/120484747-a9302880-c3b3-11eb-8206-cc8f79720f80.mp4
1. `.additem 3251`
2. `.go c 18277`
3. Wait until he casts Hex of Ravenclaw
4. Drink potion and make sure it cancels the Hex of Ravenclaw aura on you …
> fix(DB/spell): Fix Hex of Ravenclaw Removal spell

- data/sql/updates/pending_db_world/rev_1622640898688425404.sql
Melon Juice Barrel (id: 14890) was floating in the air.
Its z coordinate has been adjusted. 
-  Adjust z coordinate of gameobject id 14890
- Closes #6157
- Closes chromiecraft/chromiecraft#744
None
1. `.go o 14890`
2. Make sure the barrel is not midair …
> fix(DB/gameobject): Adjust Barrel location

- data/sql/updates/pending_db_world/rev_1622644136275319906.sql
Webbed Creature (id: 17680) is not supposed to drop any items. Currently they drop Coarse Stone with 2/3 probability.
-  Remove all drops from Webbed Creature
- Closes #6123
- Closes chromiecraft/chromiecraft#732
- Made sure the loot table was empty after applying the sql
1. run ```SELECT * FROM `creature_loot_template` WHERE `Entry` = 17680;```
2. Result should be the empty set …
> fix(DB/loot): Remove Webbed Creature drops

- data/sql/updates/pending_db_world/rev_1622733528401617288.sql
Some creatures were not patrolling or wandering around as they're supposed to. 
Initially I only looked at mobs whose names contain the word "Razormaw", but during this I encountered other mobs having the same issue, so I extended my query to cover them as well. One of them is a unique (Goreclaw the Ravenous), but there's nothing that suggests that he should be standing still.
- Give the affected creatures random movement with a radius of 5
- Closes #5823
- Closes https://github.com/chromiecraft/chromiecraft/issues/627
For the common creatures: none
For the unique creature: https://www.wowhead.com/npc=23873/goreclaw-the-ravenous#comments
1. Teleport to the mentioned creatures `.go c ...`
2. Make sure they're moving …
> fix(DB/creature): Fix some raptors not moving

- data/sql/updates/pending_db_world/rev_1622735574123785029.sql
During the Rite of Vision quest (id: 772), The Plains Vision creature
(entry: 2983) guides the player to a location. The creature moves too
fast and outruns the player, making it impossible to follow all the way.
- Adjust The Plains Vision movement from running to walking
- Closes #5982
- Closes https://github.com/chromiecraft/chromiecraft/issues/680
https://www.youtube.com/watch?v=BYy_-uytlrg
1. `.quest add 772`
2. `.go o 20436`
3. Use quest item and follow the ghost wolf …
> fix(DB/smart_scripts): The Plains Vision speed

- data/sql/updates/pending_db_world/rev_1622849161495010100.sql
-  Added missing wander distance to match other npcs of this type.
- Closes #6189 
- Closes chromiecraft/chromiecraft#759
- Ran ```SELECT * FROM `acore_world`.`creature` WHERE `id` = 5998;``` and ensure all wander_distance values are set to 5 and MovementType is set to 1
- Teleported to the 3 affected npcs to ensure they were now wandering.
1. Run ```SELECT * FROM `acore_world`.`creature` WHERE `id` = 5998;``` and ensure all wander_distance values are set to 5 and MovementType is set to 1
2. use ```go creature 3713``` ```go creature 3863``` ```go creature 3878```to check that each npc is now wandering.
3. …
> fix(DB/Creature): Some Nethergarde Foremans missing patrol pattern

- src/server/worldserver/worldserver.conf.dist
-  Add a missing "#" at the line 1460 of worldserver.conf.dist file
- Closes ???
- Fix this > Config::LoadFile: Failure to read line number 1460 in file 'configs/worldserver.conf.dist'. Skip this line
- No need to recompile.
1. Load the worldserver and see the output
- [None] …
> fix(Core/Config): missing "#" at line 1460 of worldserver.conf.dist

- data/sql/updates/pending_db_world/rev_1622966158177775526.sql
- Removes lvl 27 Cuirboulli Boots from lvl 21 Blackfathom Tide Priestess
- Removes lvl 27 Cuirboulli Boots from lvl 21 Blackfathom Oracle
- Removes lvl 65 Idol of Brutality from lvl 59 Hive'Zora Tunneler
- Removes lvl 65 Idol of Brutality from lvl 60 Twilight Stonecaller
- Removes lvl 17 Stonesplinter Rags from lvl 12 Stonesplinter Scout
- Removes lvl 17 Stonesplinter Rags from lvl 12 Stonesplinter Trogg
- Removes lvl 23 Scouting Spaulders from lvl 18 Foreman Thistlenettle
- Removes lvl 65 Idol of Brutality from lvl 60 Scourge Champion
- Removes lvl 65 Idol of Brutality from lvl 60 Hive'Zora Hive Sister
- Removes lvl 65 Idol of Brutality from lvl 60 Hive'Regal Ambusher
- Removes lvl 65 Idol of Brutality from lvl 60 Hive'Regal Spitfire
- Partially addresses …
> fix(DB/loot): Delete more overlevelled items from world NPCs

- data/sql/updates/pending_db_world/rev_1623254092348182246.sql
Remove despawn event (`id=0`) from `smart_scripts` for **Lorgus Jett**  (`entryorguid=12902`)
- Closes #6286
- Closes https://github.com/chromiecraft/chromiecraft/issues/823
- https://wowpedia.fandom.com/wiki/Lorgus_Jett?oldid=2297733
- https://wowgaming.altervista.org/aowow/?quest=6565
- SQL statement successfully executed
- `.tele Blackfathom Deeps`
- `.instance unbind all`
- enter instance
- `.go creature id 12902` 
- observe that **Lorgus Jett** has not be depawned
- repeat until convinced that the fix works
**REMEMBER**: …
> fix(DB/SAI): Remove despawn event from Lorgus Jett

- data/sql/updates/pending_db_world/rev_1623303655379442308.sql
- Increase and unify drop chance for **Diabolical Plans (23777, 23797)** to `8%`
- The drop chance varied between `1.2%` and `3%` (for no specific reason) and resulted in roughly a `65%` chance to not get this quest starter item while doing **Destroy the Legion**. With this change the overall chance of not getting the followup quest is reduced to roughly `20%` when only killing the required number of demons.
- Closes #6295
- Closes https://github.com/chromiecraft/chromiecraft/issues/829
- https://www.wowhead.com/item=23797/diabolical-plans#comments:id=1125955
The drop rates are actually higher than listed on WoWhead because the quest item will not drop for people who have already completed the quest or are currently on it.
- https://github.com/chromiecraft/chromiecraft/issues/829#issuecomm …
> fix(DB/creature_loot_template): Increase drop chance for Diabolical Plans

- data/sql/updates/pending_db_world/rev_1623193677054313100.sql
- Removed Conjured Mana Agate from the drop table because it is a conjured mage item and should not drop anywhere
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6249
- Closes https://github.com/chromiecraft/chromiecraft/issues/791
- After running the sql script the drop is no longer in the database
1. Execute the sql script
2. Make sure that the query SELECT entry FROM \`creature_loot_template\`  WHERE \`item\`=5514; does not return entry 462 (id of Vultros) …
> fix(DB/loot): Remove Mana Agate drop from Vultros

- .github/SECURITY.md
- .github/workflows/core_build.yml
- apps/ci/ci-conf.sh
- apps/ci/ci-install.sh
- src/cmake/compiler/clang/settings.cmake
- From now on, the minimum required clang version will be 10
- Also removed some builds to save runs
> feat(Core): deprecate clang-9 and older

- data/sql/updates/pending_db_world/rev_1623196877899764500.sql
- copper vein with the guid 5149 is now moved on top of the cliff so that players can reach it 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6270
- Closes https://github.com/chromiecraft/chromiecraft/issues/807
- SQL Script executed without errors
- Checked the changes ingame
New location
Old location
To see the new location:
`.go gobject 5149`
You can check the old location around this coords:
`.go xyz -9165 -2091 90` …
> fix(DB/gameobject): Unreachable Copper vein

- data/sql/updates/pending_db_world/rev_1616275490460233200.sql
Based on the bestiary book : 
-Updated Molten Core, BWL and AQ 40 bosses damages
-Updated all Molten Core trash damages
**They all had a placeholder value, 35 for bosses and 7.5 for trash. Boss damages will be a lot lower overall but trash damages will be a lot higher**
-Updated a bunch of vanilla creatures by ID (checked creatures that had a modifier higher than 1, from ID 1 to 4625)
-updated a bunch of important creatures(msotly dungeon bosses) that used the placeholder value 7.5 (1050 creature still use it)
-Querries runs properly
-checked some beasts in game with beast lore
- teleport to a creature modified by this PR with `.go c id xxx`
-let the creature hit you without armor to test the damages(nude character still has a bit of armor) or use beast lore and check the damages
-or just …
> fix(DB/creature_template): Mass update vanilla creatures damages

- src/server/game/Groups/Group.cpp
- Add support enter queue at diff group
- Part #5315
- Just enter queue with diff faction in one group …
> feat(Core/Group): Add support enter queue at diff group

- .github/FUNDING.yml
- .github/README.md
Due to serious issues with Bountysource (which we can't control) such as developers not receiving the money they claimed, Bountysource support not answering our emails,  etc... we will be considering the possibility of completely opting out from Bountysource. It looks like other communities are experiencing the same issue: https://github.com/bountysource/core/issues/1539
Meanwhile, we are placing our "donate" links to point to the PayPal of our legal non-profit organisation (Drassil). With the money collected, we will keep paying freelance developers for their open-source contributions using different means (such as GitHub Sponsor, PayPal, etc...).
If you want to donate to AzerothCore, from now on please use: https://www.paypal.com/donate/?hosted_button_id=L69ANPSR8BJDU
100% of the money …
> docs: replacing Bountysource with PayPal donation

- data/sql/updates/pending_db_world/rev_1624198243312398771.sql
- Add missing POI for quest objective of **Waters of Xavian (1944)**
- Add missing POIs for quest objective of **Laughing Sisters (1945)**
- Closes #6456
- Closes https://github.com/chromiecraft/chromiecraft/issues/924
Quest objectives should have proper POIs as shown in https://github.com/azerothcore/azerothcore-wotlk/issues/6456#issuecomment-864560108
- SQL statements executed 
- `.quest add 1944`
- Observe that the quest objective at the **Xavian Waterfall (Ashenvale)**  is now properly marked on the map 
- `.quest add 1945`
- Observe that the quest objective at **Raynewood Retreat (Ashenvale)**  is now properly marked on the map 
You can help by testing PRs and writing your feedback here …
> fix(DB/quest_poi): Waters of Xavian (1944) and Laughing Sisters (1945)

- data/sql/updates/pending_db_world/rev_1624283834038071800.sql
-  Added flags to creature
- Closes #6478
1. .go c id 17680
2. They are immune to taunt
3. They are immobile
4. They don't attack
5. They can't dodge attacks …
> fix(DB): Webbed Creature missing flags

- data/sql/updates/pending_db_world/rev_1624754774083089600.sql
- Correct when Deep Freeze Immunity State should proc
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6570
- Tested in-game, procs with Deep Freeze and not any other spells
- 
1. Try to use any spell as mage, see that Deep Freeze doesn't proc
2. Use Deep Freeze and see that Deep Freeze procs …
> fix(DB/Spell): Correct proc for Deep Freeze Immunity State (71761)

- data/sql/updates/pending_db_world/rev_1624286776168757800.sql
-  Missing condition on quest `Flawed Power Stone` that was able to be picked up if players finished quest `The Demon Seed`
- Closes not reported bug
https://youtu.be/1S-cTwn-EHo?t=581
You can see that the stones on the table next to the quest giver aren't able to be taken no longer
1. .q a 924
2. .go c id 3521
3. Quest `Flawed Power Stones` are able to be taken
4. .q c 924
5. Quest `Flawed Power Stones` are no longer able to be taken
Complete …
> fix(DB): The Demon seed conditions

- src/server/game/Entities/Player/Player.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/b1ac631f68d122558c25c4da7eedef75b4c2b7b6)
Co-Authored-By: r00ty-tc <173349+r00ty-tc@users.noreply.github.com>
- Learn skill runeforging when the spell is learned
- Do same for lockpicking to avoid issues (half of the lockpicking stuff was already imported, missing this stuff see https://github.com/TrinityCore/TrinityCore/commit/dcba0106d64bd598e70cc65be8e28f6ee279dcfd)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6611
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6604
1. Do the DK questline
2. When you finish the quest to get runeforging, see that you learn the Spell and the Skill "Runeforging"
1. Have a rogue at lvl 16
2. Learn lockpicking at trainer …
> fix(Core/Player): Learn runeforging & lockpicking

- data/sql/updates/pending_db_world/rev_1624657033501888850.sql
Flag all **Shredder Operating Manual - Page %** items for `HORDE_ONLY` so that they no longer drop for Alliance characters.
- Closes #6572
- Closes https://github.com/chromiecraft/chromiecraft/issues/1001
From https://wowpedia.fandom.com/wiki/Shredder_Operating_Manual_-_Page_1:
>Patch 1.8.0 (2005-10-10): Shredder Operating Manual pages will no longer drop for the Alliance.
- SQL statement executed
- Run the following SQL statement to verify that the fix was applied
```SQL
SELECT `entry`, `name`, `FlagsExtra` FROM `item_template` WHERE `name` LIKE 'Shredder Operating Manual - Page %' ORDER BY `entry`;
+-------+-------------------------------------+------------+
| entry | name                                | FlagsExtra | …
```
> fix(DB/item_template): Flag all "Shredder Operating Manual" pages for HORDE_ONLY

- data/sql/updates/pending_db_world/rev_1624668958042794600.sql
-  Creates the missing `gossip_menu_option_locale`, `creature_text_locale`, `quest_request_items_locale` and `quest_offer_reward_locale` to spanish.
- Closes 
- File and statements executed on my database several times to verify failures.
- Changes seen in-game with both alliance and horde.
- Inserting the sql in your acore_world database. …
> fix(DB) Untranslated texts for The Battle for Undercity

- data/sql/updates/pending_db_world/rev_1624669484085082860.sql
- Change `summonType` from `TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT` to ` TEMPSUMMON_CORPSE_TIMED_DESPAWN ` 
- Change `summonTime` (despawn timer) from 1 minute (out of combat) to 5 minutes (dead)
- Groups may now wipe at the **Fire Of Aku'Mai** event and come back to finish it
- Closes #5213
- Closes https://github.com/chromiecraft/chromiecraft/issues/220
Plenty. Check the addressed issues including comments.
- SQL statement successfully executed
On a GM account
- `.tele Blackfathom`
- enter
- `.go creature id 4832`
- Light all fires
- Observe that the summoned creatures do not despawn (after 1 minute). Stay as long as you like, leave the instance and come back, ... they are still there. 
- Kill all summoned creatures
- Observe that the door opens
- Observe that the …
> fix(DB/creature_summon_groups): Adjust creature despawn in BFD / Fire Of Aku'Mai

- data/sql/updates/pending_db_world/rev_1624891276964449853.sql
- Rare spawn Accursed Slitherblade (ID 14229, GUID 51846) - MovementType to 1, wander dist to 20
- Rare spawn Giggler - (ID 14228, GUID 51847) - MovementType to 1, wander dist to 5
- Also normalize Giggler's speed to 1. (was 2.12)
- Rare spawn Crusty - (ID 18241, GUID 27825) -  MovementType to 1, wander dist to 20
I've tried to match wander_distance to local mobs of the same kind. Accursed Slitherblade was matched to Slitherblade Nagas, Giggler was matched to Bonepaw Hyenas, and Crusty was matched to Enraged Reef Crawlers.
Also noted Giggler's speed was inconsistent with that shown in source, so adjusted to usual hyena speed.
- Partially addresses https://github.com/azerothcore/azerothcore-wotlk/issues/6548
Acc Slither - https://www.youtube.com/watch?v=MyFZNA4DuWk
Giggler - …
> fix(DB/Creature): Fix various motionless rare spawns - 30-30 bracket

- data/sql/updates/pending_db_world/rev_1624689676324157623.sql
-  Removes the Civilian flag from the flags_extra field of Nazzivus Summoners (ID 17524) so they will now attack players.
-  Also set one individual spawn (86538) to have a MovementType of 1 (random wandering) instead of 0 (standing still) to match all the others in the area.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6538
- Closes https://github.com/chromiecraft/chromiecraft/issues/962
Common sense.
- Checked in-game, NPCs are now properly aggressive and attack when you go near them.
1. .go c 86538, it should attack you instead of ignoring you. …
> fix(DB/Creature) Remove Civilian flag from Nazzivus Summoners

- data/sql/updates/pending_db_world/rev_1624714294954952856.sql
Attempts to disable 10 Arathi Basin quests that were deprecated in path 2.4. They are:
- Alliance: 8154, 8155, 8156, 8080, 8297 - [Arathi Basin Resources!](https://wowpedia.fandom.com/wiki/Arathi_Basin_Resources!_(level_20))
- Horde: 8160, 8161, 8162, 8123, 8299 - [Cut Arathor Supply Lines](https://wowpedia.fandom.com/wiki/Cut_Arathor_Supply_Lines_(level_20))
It does this by removing the quests from the `creature_queststarter` and `creature_questender` tables and inserting the quests into `disables`. If anything else needs to be done to disable these quests, let me know.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6503
- Closes https://github.com/chromiecraft/chromiecraft/issues/958
- https://wowpedia.fandom.com/wiki/Arathi_Basin_Resources!_(level_20)
- …
> fix(DB/Quest): Remove deprecated Arathi Basin quests

- data/sql/updates/pending_db_world/rev_1624718377760938108.sql
- When an Ally player dies in Thunder Bluff, they currently respawn in Ratchet, which is quite a long way away. This PR moves their respawn point to what I believe is the correct GY, which is the GY SE of Bloodhoof Village in Mulgore. This is where Allies who die in the rest of Mulgore go, so it's consistent. There is an argument to be made that they should respawn in Bloodhoof itself, however.
As a tauren player, was tempted to have Ally players who died in TB forced to run back from say, Outlands, but have nobly refrained.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6499
- Closes https://github.com/chromiecraft/chromiecraft/issues/954
Only source I could find was https://us.forums.blizzard.com/en/wow/t/beta-graveyard-hopping/221094/3, which is patch 1.6 and thus …
> fix(DB/Graveyard) Move Ally GY when dying in Thunder Bluff

- data/sql/updates/pending_db_world/rev_1624770439358526029.sql
-  Delete Crisp Spider Meat (ID 1081) from Deviate Lurkers and Deviate Creepers (both non-spiders.)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6602
- Closes https://github.com/chromiecraft/chromiecraft/issues/1014
https://wowpedia.fandom.com/wiki/Crisp_Spider_Meat
https://tbc.wowhead.com/npc=3641/deviate-lurker
https://tbc.wowhead.com/npc=3632/deviate-creeper
- Checked creature's drop tables in Keira.
- Ran original query looking for spider meat, two Deviates now both missing.
1. Check creature's drop tables in Keira. …
> fix(DB:Creature) Removes Spider Meat from Deviate Creepers/Lurkers

- data/sql/updates/pending_db_world/rev_1624779042193682155.sql
Deletes underlevelled (lvl 18-19) RLT 24078 from:
-  lvl 28 Nightbane Dark Runner (ID 205)
- lvl 28 Dark Strand Voidcaller (ID 2337)
- lvl 31 Athrikus Narassin (ID 3660)
- lvl 50 Jadefire Rogue (ID 7106)
- lvl 54 Scarshield Spellbinder (ID 9098)
RLT 20478 has an average item level of 18.5 - it's made up of lvl 18-19 gear. A query finding all mobs with RLT 24078 in their loot tables who are 5+ level higher than that gives this list:
```
+-------+------------------------+----------+
| entry | name                   | minlevel |
+-------+------------------------+----------+
|   205 | Nightbane Dark Runner  |       28 |
|  2337 | Dark Strand Voidcaller |       28 |
|  3660 | Athrikus Narassin      |       31 |
|  7106 | Jadefire Rogue         |       50 |
|  9098 | Scarshield Spellbinder | …
```
> fix(DB/Loot): Removes underlevelled RLT 24078 from various NPCs

- data/sql/updates/pending_db_world/rev_1624818270368841200.sql
-  Bellygrub now wandering
- Closes #6275
He should be wandering like in this video: https://www.youtube.com/watch?v=KKlibkOYRm0
1. ```go creature 10105```
2. Observe …
> fix(DB/Creature) Bellygrub not wandering

- data/sql/updates/pending_db_world/rev_1624933074542630900.sql
-  Increased despawn timer to allow players to loot Sironas
- Closes #5777
https://www.youtube.com/watch?v=xi9x8zkOOIA
- Tested on Windows 10
1. Do quest `Ending Their World` …
> fix(SAI): Sironas despawn time increased

- src/server/scripts/Spells/spell_warrior.cpp
-  Remove aura state for victory rush on hit confirmed
- Closes #6657
- Closes https://github.com/chromiecraft/chromiecraft/issues/1039
- Tested on windows 10: https://youtu.be/XB8FhYbQa3s
1. Kill an enemy with Victory Rush
2. Cast the next Victory Rush
3. Can't cast it again like on the linked issue
None …
> fix(Spell): Victory Rush spammable ability

- data/sql/updates/pending_db_world/rev_1625138742497401267.sql
-  Set Siege Golem (ID 2749) from a speed_walk of 2.27 to 1. Speed was matched to nearby Stone Golems which have speed 1.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6506
- Closes https://github.com/chromiecraft/chromiecraft/issues/960
https://youtu.be/A1535Tk94F8?t=238
- Checked in-game, was much more reasonable speed.
1. Check Keira, as checking in-game is a pain due to this NPC's many spawn points.
N/A. …
> fix(DB/Creature): Set correct Siege Golem speed

- data/sql/updates/pending_db_world/rev_1625291253501808914.sql
-  Limit maximum number of Darkclaw Lobsters caught in one fishing cast from 2 to 1.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6681
- Closes https://github.com/chromiecraft/chromiecraft/issues/1048
https://tbc.wowhead.com/azshara#fishing
TBC comments don't mention multiple drops at all. However, the vast majority of fish are caught one at a time.
- Tested in game,now behaving as expected.
1. Look at RLT 11105 in Keira
N/A. …
> fix(DB/Loot): Limit maximum Darkclaw Lobster catches

- src/server/worldserver/worldserver.conf.dist
Duplicate entry for Logger.mmaps=4,Server
-  Remove duplicate entry in worldserver.conf.dist
-  
- Closes 
- Launch the server with new worldserver.conf.dist and do not log the duplicate entry error.
- 
1. The server log the duplicate entry error inmediatly after launch.
2.
3. …
> fix(Core/Conf): worldserver.conf.dist duplicate entry for Logger.mmaps

- data/sql/updates/pending_db_world/rev_1625375927776772391.sql
- Delete Blackwater Cutlass from general RLT 24078.
- Add Blackwater Cutlass to Defias Pirate and Squallshaper drop tables with 6% drop rate and GroupId of 1. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6605
- Closes https://github.com/chromiecraft/chromiecraft/issues/1015
https://tbc.wowhead.com/item=1951/blackwater-cutlass
- Checked in-game, Deadmines Pirates/Squallshapers now occasionally drop the sword.
1. Check RLT 24078 - it should not contain the sword.
2. Check loot tables for Pirates and Squallshapers - they should have the sword with 6% drop rate and a GroupId of 1.
N/A. …
> fix(DB/Loot): Correct Blackwater Cutlass drops

- data/sql/updates/pending_db_world/rev_1625379465170274070.sql
-  Delete Stonemason's Cloak from general RLT 24078
-  Add Stonemason's Cloak to Defias Miner drop table with 3% drop rate and GroupId of 1.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6607
- Closes https://github.com/chromiecraft/chromiecraft/issues/1017
https://tbc.wowhead.com/item=1930/stonemason-cloak
- Checked loot tables from Defias miner, Cloak is now there.
1. Check RLT 24078 in Keira, item should not be in it.
2. Check Defias Pirate drop table, item should be included with a 3% chance and GroupId of 1.
N/A. …
> fix(DB/Loot): Correct Stonemason's Cloak drops

- data/sql/updates/pending_db_world/rev_1625406775061855034.sql
-  Adds 210 Alchemy as a requirement to the Horde quest "Badlands Reagent Run II" (ID 2203). This brings it into line with the Alliance version of the same quest.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6718
- Closes https://github.com/chromiecraft/chromiecraft/issues/1080
"This quest requires an Alchemy skill of 210 to pick it up. " - https://tbc.wowhead.com/quest=2203/badlands-reagent-run-ii#comments:id=2781389
"Requires a minimum 210 Alchemy to be able to be offered this quest." - https://classic.wowhead.com/quest=2501/badlands-reagent-run-ii#comments:id=3159614
- Tested in game:
Character with no Alchemy - not offered quest:
Character with 209 Alchemy - not offered quest:
Character with 210 Alchemy is offered quest (also levelled …
> fix(DB/Quest) Adds Alchemy requirement to "Badlands Reagent Run II" (H)

- data/sql/updates/pending_db_world/rev_1625410362418489198.sql
The Horde quest "Broken Alliances" 2/2 (ID 793) and the Alliance quest "Tremors of the Earth" 2/2 (ID 717) both require the player to click on three pillars in the Badlands. This PR changes the respawn timers of the Pillars of Diamond (ID 2842, GUID 10643), Opal (ID 2848, GUID 10644) and Amethyst (ID 2858, GUID 10830) to 0 seconds to match observed retail behaviour. They were previously 2 seconds/2 hours/2 hours respectively. 
This ensures that more than one person can complete this quest every two hours.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6719
- Closes https://github.com/chromiecraft/chromiecraft/issues/1081
https://youtu.be/tX7AS0eM2J4?t=4
https://youtu.be/o7feaCOmsWg?t=120
https://youtu.be/x6xQeumYLCU?t=633
- Ran the relevant …
> fix(DB/Quest): Remove respawn timers from "Broken Alliances" pillars

- data/sql/updates/pending_db_world/rev_1625485014381956791.sql
- Moves Dread Swoop GUID 27980's spawn point to above ground, and adds random movement.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6743
- Closes https://github.com/chromiecraft/chromiecraft/issues/1099
Mobs should not spawn underground.
- Checked in game, swoop is now enjoying a nice view and guarding its own copper node. (Also, what's a copper node doing in Desolace?)
1. .go c 27980
2. If you land on the small hill and a bird starts attacking you, it worked. If you fall into the endless void, it didn't.
N/A. …
> fix(DB/Creature): Correct Dread Swoop spawn point

- data/sql/updates/pending_db_world/rev_1625490612430815354.sql
Removes the Dark Iron Ale Mug (item ID 11325) from Whit Wantmal's (ID 275) loot table. As that was the only item he dropped, and Wowhead confirms that he isn't supposed to actually drop anything at all, deleted his loot template and set his lootID to 0.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6737
- Closes https://github.com/chromiecraft/chromiecraft/issues/1088
https://tbc.wowhead.com/npc=275/whit-wantmal
https://tbc.wowhead.com/item=11325/dark-iron-ale-mug
- Then checked in game, ganked Whit and he dropped nothing.
1. .go c 4196
2. Tell him how much you disliked "Leaves of Grass" in school and then gank him.
3. you should be unable to loot as he drops nothing.
N/A.
When a PR is ready to be tested, it will be marked as **[WAITING TO …
> fix(DB/Loot): Remove Dark Iron Ale Mug from Whit Wantmal

- data/sql/updates/pending_db_world/rev_1625511611223853500.sql
-  Correct `MovementType` flags as it makes the NPC display a wrong orientation.
- Closes #6744
- Closes https://github.com/chromiecraft/chromiecraft/issues/1100
- `.go c id 16916`
1. `.go c id 16916`
2. Orientation is ok 👍  …
> fix(DB/creaure_template): Wretched Captive orientation

- data/sql/updates/pending_db_world/rev_1625515191527869300.sql
-  Despawn Vylestem Vine in order to not be abused, also added 3 summoned creatures in total 
- Closes #6752
- Closes https://github.com/chromiecraft/chromiecraft/issues/1101
- https://www.youtube.com/watch?v=um3d4wdd4Ag&t=111s
- Object can only be used once, 3 creatures spawn.
1. `.q a 7041`
2. Fill in the Orange Pool outside the Maraudon instance
3. Try to use the filled object inside Orange Maraudon Instance, you will only be able to do it once, with 3 creatures spawned …
> fix(DB/smart_ai): Prevent Vylestem Vine to be used multiple times

- data/sql/updates/pending_db_world/rev_1625577114142882549.sql
- Deletes Illusion Dust, Sungrass, Stranglekelp, Briarthorn, and Un'Goro Soil from Torwa's Pouch (ID 11568). this pouch should only contain two quest items.
- Deletes Preserved Threshadon Meat (ID 11569) and Preserved Pheromone Mixture (ID 11570) from Hoard of the Black Dragonflight (ID 10569). WH shows this bag should not contain these items.
- Deletes Preserved Threshadon Meat (ID 11569) and Preserved Pheromone Mixture (ID 11570) from A Small Pack (ID 11107). WH shows this bag should not cvontain these items.
- Changes drop rate of Preserved Pheromone Mixture from Torwa's Pouch from 99.6% to 100%.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6763
- Closes https://github.com/chromiecraft/chromiecraft/issues/1107
https://tbc.wowhead.com/item=11568/torwas-pouch …
> fix(DB/Loot): Correct various bag item lists

- src/server/game/World/World.cpp
Fixes the following warning:
```
azerothcore-wotlk/src/server/game/World/World.cpp:1493:22: warning: loop variable 'map' is always a copy because the range of type 'DBCStorage<MapEntry>' does not return a reference [-Wrange-loop-analysis]
for (auto const& map : sMapStore)
^
azerothcore-wotlk/src/server/game/World/World.cpp:1493:10: note: use non-reference type 'const MapEntry *'
for (auto const& map : sMapStore)
^~~~~~~~~~~~~~~~~
```
According to [this answer](https://stackoverflow.com/a/50066414/3497671):
>  That means in every iteration you have an object that is being created and destroyed, which could be costly, and is not obvious as you are using a reference. The warning wants you to use a non reference type to make it obvious that you are not actually working with the element from …
> fix(Core/World): -Wrange-loop-analysis warning

- data/sql/updates/pending_db_world/rev_1625925059779148449.sql
Adds movement and wander distances to:
- Kregg Keelhaul - ID 8203- matched to SouthSea Freebooter. Also setting his speed_walk to 1 as it was too high (checked with @Efymer 's web app [here ](https://azerothcore-speedchecker.web.app) to verify correct speed was 1, not 1.68.)
- Licillin ID 2191 - matched to Vile Sprite - also setting speed_walk from 1.83 to 1.
- Carnivous the Breaker ID 2186  - matched to Blackwood Windtalker, speed was fine.
- Flagglemurk the Cruel ID 7015 - no nearby murlocs, matched to Tide Crawler, speed was fine.
- Lord Sinslayer ID 7017 - matched to Stormscale Waverider, speed was fine.
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/6815
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6826
- Kregg - …
> fix(DB/Creature): Fix various static NPCs in Darkshore/Tanaris

- data/sql/updates/pending_db_world/rev_1625841824336043500.sql
- src/server/scripts/Northrend/zone_icecrown.cpp
Quest: No Fly Zone  available through the website [here](https://www.wowhead.com/quest=12815/no-fly-zone)
-  Fix: Raidus 3yards
-  Fix: removed the Blood Presence aura. Correct function added smart_scripts Cast (11)
-  Fix: Gravity and Hover
-  Fix: Plague Strike ability of the npc Bone Gryphon
-  was performed windows 7 64bits. Not a single error was found and it is Functional
1. quest add 12815
2. tele icecrown
3. go to the zone indicated by the map and test …
> fix(DB/Quest): improved No Fly Zone

- data/sql/updates/pending_db_world/rev_1625916764471568068.sql
- Deletes lvl (min:10/avg:10.68/max:11) RLT 24074 from lvl 44 Blisterpaw Hyena (ID 5426), lvl 43 Fire Roc (ID 5429)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6863
- Closes https://github.com/chromiecraft/chromiecraft/issues/1145
https://tbc.wowhead.com/npc=5429/fire-roc#drops
https://tbc.wowhead.com/npc=5426/blisterpaw-hyena#drops
- Ran SQL, no errors/warnings, correct number of rows affected.
- Checked in Keira.
- Verified with [ac-whcomp](https://github.com/Azcobu/ac-whcomp) that these items were not listed in Wowheads drop tables for these NPCs.
1. Checked DB, ensure that RLT 24074 is no longer listed for IDs 5426 and 5429.
N/A. …
> fix(DB/Loot): Remove underlevel RLT 24074 from Rocs/Hyenas

- data/sql/updates/pending_db_world/rev_1626007477539439387.sql
- Deletes Arathi Basin Enriched Ration (ID 20062) and Arathi Basin Runecloth Bandage (ID 20066) from the loot tables of:
- Warpwood Stomper (ID 11465)
- Desert Rumbler (ID 11746)
- Vekniss Soldier (ID 15229)
- Deletes the entire loot table of Field Marshal Oslight (ID 14983). This sounds drastic, but Wowhead shows he shouldn't drop anything at all. (At the moment he drops 9 items, including 6 different types of Arathi PVP supplies.) This brings Oslight into line with other nearby PVP NPCs like Sir Maximus Adams and Samuel Hawke, who also have no drops. (Apparently incorrectly in Hawke's case according to WH, but that's another issue.)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6882
- Closes https://github.com/chromiecraft/chromiecraft/issues/1157
Links showing that …
> fix(DB/Loot): Remove Arathi PVP food/bandages from open world NPCs

- src/server/game/Entities/Object/Object.cpp
- src/server/game/Entities/Object/Object.h
- This PR fixes a problem that would result in a warning in C++20
- See [this thread on StackOverflow](https://stackoverflow.com/questions/60386792/c20-comparison-warning-about-ambiguous-reversed-operator) for more details
> fix(Core/Object): -Wambiguous-reversed-operator warning

- deps/boost/CMakeLists.txt
- This was broken the Docker build
- This was causing some issues to some users, as in several systems such as Debian and Ubuntu the default Boost version is not 1.74 yet and can be cumbersome to migrate
However, this is just a temporary revert. We'll need to require Boost 1.74+ in future. But I guess it's better to wait for now.
> fix(Core): revert Boost minimum version change

- .clang-format
-  Changes the AccessModifiersOffset to -4 
-  Changes the ColumnLimit to 500
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6995
- None yet.
1. Format a file with clang-format
2. (Optional) Test if it compiles
**For …
> fix(format): Acessmodifieroffset & line breaks

- data/sql/updates/pending_db_world/rev_1626317015822404300.sql
- Changed the drop rates for  'Deadwood Headdress Feather'
- Closes #6937
- Closes chromiecraft/chromiecraft#1179
- https://tbc.wowhead.com/item=21377/deadwood-headdress-feather
1. Directly kill NPCs from the list and check the item drop rate
2. Look in Keira3 or in DB …
> fix(DB/Loot): 'Deadwood Headdress Feather' Drop rates Inaccurate

- data/sql/updates/pending_db_world/rev_1626358725875698500.sql
-  Mobs now run to the player and attack
- Closes #6944
- Closes chromiecraft/chromiecraft#1187
- Trelane's Footlocker (2717) - 16611 - https://www.youtube.com/watch?v=oFdLPHn4w7E&t=731s
- Trelane's Lockbox (2718) - 16610 - https://youtu.be/oFdLPHn4w7E?t=951
- Trelane's Chest (2716) - 16617 - https://youtu.be/oFdLPHn4w7E?t=2166
1. .q add 696
2. .go o 16611 - loot and observe
3. .go o 16610 - loot and observe
4. .go o 16617 - loot and observe …
> fix(DB/SAI): "Attack on the Tower" Quest - Incorrect NPC Spawn Behaviour

- src/server/scripts/Northrend/Naxxramas/boss_thaddius.cpp
Fixed #6929.
-  Fixed removing polarity stacks on charge change
- Closes #6929
1.Fight `Thaddius`
2.Have `Positive Charge` and Run to the positive …
> Scripts/Naxxramas: Properly handled Thaddius' polarity stacks.

- data/sql/updates/pending_db_world/rev_1626545461944168600.sql
The quest reward gossip had text with a setted name and gender. Its changed to use the name and character now
Closes AzerothCore issue #6976
-  Changing in the database the text of the quest using $N to take the name and $gman:woman; to change between man and woman.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6976
- Closes https://github.com/chromiecraft/chromiecraft/issues/1219
Picture of the new text
With man named World
-  .go c id 7161
- .quest add 2381 to add the quest
- .quest complete 2381 to complete it
-  I talked with the goblin and saw the he used my name and gender on the text.
1. .go c  id 7161
2. .quest add 2381 to add the quest
3. .quest complete 2381 to complete it
4. Talk with the goblin and see if the text use the name and gender of the character. …
> fix(DB/Quest): "Plundering the Plunderers" has incorrect quest completion text

- src/server/game/Handlers/PetHandler.cpp
Fixed #5320.
-  Change the order of loaded spells from DB.
- Closes #5320
- Closes https://github.com/chromiecraft/chromiecraft/issues/419
- Tested ingame with Voidwalker 39/40 lvl.
1. Set level to 39
2. Summon Voidwalker
3. Dismiss Voidwalker
4.  `.level 1`
5.  Summon Voidwalker
6. See that there are new ranks on the bar. …
> Core/Pets: Fixed spells disappearing while pet being offline.

- data/sql/updates/pending_db_world/rev_1626780409112630500.sql
I added some new spawn points and added movements to all of them
Closes AzerothCore issue#7012
-  Added 2 new spawn points 
-  Added movement to the creature on all of them
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7012
- Closes https://github.com/chromiecraft/chromiecraft/issues/1224
https://tbc.wowhead.com/npc=14343/olm-the-wise
https://www.youtube.com/watch?v=evs3q3xk_fs
https://youtu.be/WEg1X9Cs6eg?t=9
https://youtu.be/dkk3VDeS-LU?t=2
- .go c id 14343
- Observe if it moves around the spawn point
Video test
https://streamable.com/7fwttv
1. .go c id 14343
2. Observe if it moves around the spawn point
- Tried to give it the faction of Cenarion circle as the source
-  " Alliance hunters might be puzzled by the fact Olm the Wise is clearly rated "Tameable" via Beast …
> fix(DB/Creature): Olm the Wise (rare) missing movement pattern

- data/sql/updates/pending_db_world/rev_1626810503477176700.sql
Fixed #5520.
-  Corrected and added new graveyard for alliance players in Shadowfang Keep instance.
- Closes #5520
- Closes https://github.com/chromiecraft/chromiecraft/issues/479
1.Travel to SFK (not through dungeon finder), enter the instance and logout (or die.) …
> DB/Graveyards: Corrected graveyard for alliance in Shadowfang Keep.

- src/server/game/Movement/MovementGenerators/PathGenerator.h
- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
Fixed #5220.
-  Clear out path generator if not initializing the new one in `TargetedMovementGenerator`. We need to do this, because later in `PathGenerator` calculations we still have old points if something went wrong.
- Closes #5220.
- Closes https://github.com/chromiecraft/chromiecraft/issues/369
- Tested ingame in Stromgarde Keep.
Description [here](https://github.com/azerothcore/azerothcore-wotlk/issues/5220) …
> Core/Movement: Fixed weird pathing by clearing old path.

- src/server/game/Entities/Unit/Unit.cpp
-  Melee spells against sitting targets should do crit.
- Closes #5986.
- Tested ingame in duel.
1. Duel another player.
2. Have them sit or lie down.
3. Go into Prowl/Stealth and attack them from behind. …
> Core/Spells: Melee spells against sitting targets are guarenteed as critical strikes.

- data/sql/updates/pending_db_world/rev_1627133872787794145.sql
Sets the respawn time for all four of the items required for the quest "Bingles' Missing Supplies" (https://tbc.wowhead.com/quest=2038/bingles-missing-supplies) to 8 seconds. Previously, 3 of them had 5 minute/300 second respawn times, which made quest completion in a party difficult. The fourth had a 2 second respawn, which I have changed for the sake of consistency. 
The 8 second respawn time was derived from a video (https://youtu.be/R6taQBjNIVo?t=204) where the looting and respawn of one of these items is recorded.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6982
- Closes https://github.com/chromiecraft/chromiecraft/issues/1215
https://youtu.be/R6taQBjNIVo?t=204
https://tbc.wowhead.com/quest=2038/bingles-missing-supplies
- Ran SQL, no errors/warning, correct …
> fix(DB/Gameobject): Normalise respawn times for Bingles' items

- src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
-  Added checks to remove frenzy aura within Reset()
-  Correctly set Ohgans boss state to NOT_STARTED when Mandokir's Reset() is called.
- Closes part of: https://github.com/azerothcore/azerothcore-wotlk/issues/834 
- Tested on Windows10 64-bit in-game following the steps outline below.
- Tested additional bug where if you had killed Ohgan then reset the fight, Ohgans data remained as DONE and mandokir
would immediately enrage on subsequent pulls.
1. Pull Mandokir and .damage or .die Ohgan, see Mandokir enrage.
2. Reset the fight by turning GM on or dying. Observe that enrage is removed on reset.
3. Additionally, observe that mandokir does not enrage if you have killed ohgan before him, and then re-pulled him.
- [This PR is complete, however it does not resolve all the issues outlined in …
> fix(Script/Mandorik): enrage on reset and on subsequent pulls.

- data/sql/updates/pending_db_world/rev_1627581490592719000.sql
-  Changed the coords of the node, so now it will spawn outside of the tree
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7142
- Closes https://github.com/chromiecraft/chromiecraft/issues/1298
- .go go 65024
- Check the new spawn
1. .go go 65024
2. Check the new spawn …
> fix(DB): Moved Briarthorn node outside of terrain

- data/sql/updates/pending_db_world/rev_1627655074869500200.sql
Fixed #6542
-  There is some time desynchro between aura duration and proc cooldown - that's why Taste for Blood sometimes does not proc from Rend. The problem might be something general. I modified cooldown to ensure that TfB will always proc. There is not threat about early proc - Rend ticks every 3 sec, so TfB will always proc every 2nd tick of Rend.
-  
- Closes #6542
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6542
1. get a warrior, level it it up to have at least 18 talent points
2. spend your points in arms tree and get 3/3 taste of blood
3. get glyph of rending
4. use rend on a target dummy. …
> fix(DB/Spell): Set proc cooldown of Taste of Blood to 5.5 sec.

- src/server/scripts/Spells/spell_rogue.cpp
-  Killing spree should not affect invisible units.
- Closes #2371 
1. Create a rogue.
2. Cast killing spree on another character.
3. Cast invisibility with the character you are attacking, check that Killing spree should not affect the invisible target. …
> fix(Core/Spells):  Killing spree should not affect invisible units.

- data/sql/updates/pending_db_world/rev_1627727878498349900.sql
Fixes quest text in issue #7029
Fixed quest text for quest in Azshara called Crew Under Fire
-  Adjust quest text from incorrect quest to correct quest
-  
'This is going to be a tough battle...' 
- Closes #7029
https://github.com/azerothcore/azerothcore-wotlk/issues/7029
Sources in issue report
https://classic.wowhead.com/quest=3382/a-crew-under-fire
https://vanillawowdb.com/?quest=3564
- 
- 
No tests, SQL fix only.
1. Go to Azshara
2. Start quest Crew Under Fire
3. Observe progress text mid quest by talking to questgiver …
> fix(DB/quest_request_items): quest completion text for Crew Under Fire & closes #7029

- data/sql/updates/pending_db_world/rev_1627735957987999500.sql
-  Changed the coords of 2 spawn points (guid 5608 and guid 5687)
- Closes https://github.com/chromiecraft/chromiecraft/issues/881
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6393
- .go c 5608 
- .go c 5687
- Check if the position is good
Test
1. .go c 5608 
2. .go c 5687
3. Check if the position is good …
> fix(DB/Creature): Fixed the spawns of two Heavy War Golem (5854)

- data/sql/updates/pending_db_world/rev_1627805665809266322.sql
Deletes 'Recipe: Savory Deviate Delight' (ID 6661) from RLT 24701
The Recipe is supposed to be a Barrens-exclusive drop, and thus it is a direct drop from the loot tables of 110 creatures from the Barrens. However, the problem comes from the fact that the Recipe is also contained in reference_loot_template (RLT) 24701. This RLT is only directly used by 1 creature (Murloc Warrior, ID 171) but is itself contained by 3 other RLTS, 24730, 24731, and 24732. These 3 RLTs are used by a total of 122 various random low level NPCs, all of which are from the Eastern Kingdoms. In other words, it is not a valid drop for any of them.
Checking via SQL confirms this. Creature field `map` is 0 for Eastern Kingdoms and 1 for Kalimdor. If we search for creatures who use these RLTs in Kalimdor, we get an …
> fix(DB/Loot): Delete 'Recipe: Savory Deviate Delight' from RLT 24701

- data/sql/updates/pending_db_world/rev_1627813955000857700.sql
Corrupted plants were not despawning after completing the quest, and their cleansed counterparts were not despawning after being picked.
A lot of things had to change for  them to work properly.
Because the corrupted and cleansed Sunflowers worked almost properly (the corrupted parts were not despawning on my tests)
i picked them for scripts examples.
The issues came because the corrupted parts had no action of despawning, so i added one. The same thing happened to the cleansed ones, but they also had some spawn point activated, and i had to delete them to mimic the songflower code.
After that i added some flags so the cleansed one where consumables, and added a logic for the corrupted to be despawned after completing the quest.
-  Added some logic to the corrupted and cleansed parts to …
> fix(DB): Fixed corrupted and cleansed plants on Felwood

- data/sql/updates/pending_db_world/rev_1627818799536182900.sql
-  Added movement type 1 and wander of 5 to Mok'rash (1493)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6226
- Closes https://github.com/chromiecraft/chromiecraft/issues/778
- .go c id 1493
- Check if he moves
1.  .go c id 1493
2. Check if he moves
https://user-images.githubusercontent.com/87535580/127769955-51e37c04-0397-4f66-8ae3-1a41c6ca9b50.mp4 …
> fix(DB/creature): Added movement to Mok'rash (1493)

- src/server/game/Spells/SpellEffects.cpp
Fixed #6721.
-  If player charges, they should attack only their current target.
- Closes #6721
- Closes https://github.com/chromiecraft/chromiecraft/issues/1078
1. create a warrior, learn charge/intercept
2. go to the dummies select one dummy as your main target and the other one as your focus target by simply typing /focus
3. use this macro while targeting your main target, it will charge the focus target and melee swing at it without changing targets
`/cast [@Focus] Charge`
or
`/cast [@Focus] Intercept` …
> fix(Core/Spells): Do not attack focus target while charging.

- data/sql/updates/pending_db_world/rev_1627894869122476600.sql
-  Added the flag so they dissapear now after attacking them for the quest Brood of Onyxia (1172)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6832
- Closes https://github.com/chromiecraft/chromiecraft/issues/1135
- .quest add 1172
- .go go 13656
- Attack the egg and see them explode and dissapear
Video proof
https://streamable.com/hrcehq
1. .quest add 1172
2.  .go go 13656
3.  Attack the egg and see them explode and dissapear …
> fix(DB/Quest): Fixed  Brood of Onyxia (1172) eggs

- data/sql/updates/pending_db_world/rev_1627896958983750100.sql
-  Reduced the spawn of the skull piles from 900 seconds to 1 so they wont dissapear
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7199
- Closes https://github.com/chromiecraft/chromiecraft/issues/1324
-Be Horde
-.quest add 585
-.go object 9986
-.gm off
-Pick up the skull.
-The pile only dissapears for a brief moment
-Repeat for objects 10135, and 10030
1. Be Horde
2. quest add 585
3. .go object 9986
4.  gm off
5. Pick up the skull.
6. The pile only dissapears for a brief moment
7. Repeat for objects 10135, and 10030
**Test redone with the generic pile of bones inside the quest piles**
https://user-images.githubusercontent.com/87535580/128197230-e79bd5a7-bd20-485e-97d9-cd7fb6f911eb.mp4
You …
> fix(DB/object): Fixed skull piles despawning on quest Speaking with Nezzliok

- data/sql/updates/pending_db_world/rev_1628001727322964286.sql
-  Changes the Gadgetzan reputation gain from killing Caliph Scorpidsting from 25 to 15, and stops rep gain from killing him at Honoured instead of Revered.
-  Changes the Gadgetzan reputation gain from killing Wastewander Assassin, Bandit, Rogue, Scofflaw, Shadow Mage, and Thief from 10 to 5.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7207
- Closes https://github.com/chromiecraft/chromiecraft/issues/1321
- Caliph: https://tbc.wowhead.com/npc=7847/caliph-scorpidsting
- Wastewanders: https://tbc.wowhead.com/npc=5618/wastewander-bandit
See the [original AC issue](https://github.com/azerothcore/azerothcore-wotlk/issues/7207) for more discussion on sources. Most of them contradict each other in at least one way, so I've gone with Wowhead as the most modern source. The …
> fix(DB/Reputation): Correct Caliph/Wastewander Gadgetzan reps

- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Auras/SpellAuras.cpp
-  Activate slow effect only if trap effect is broken
- Closes #7183
- Closes https://github.com/chromiecraft/chromiecraft/issues/1313
1 - Inscribe "Glyph of Freezing Trap"
2 - Apply Freezing Trap to a target
3 - Wait for the trap effect to end
4 - Check that the slow effect is applied. …
> fix(Core/Spells): Glyph of Freezing Trap Applying Slow Incorrectly

- data/sql/updates/pending_db_world/rev_1628018690377094600.sql
Fixed #6689
-  Updated `spell_proc_event` so Shadow Weaving can proc from DOTs.
- Closes #6689
- Closes https://github.com/chromiecraft/chromiecraft/issues/1049
1. Priest with 3/3 Shadow weaving in shadow talent tree
2. Spam Devouring plaque on mobs
3.Shadow weaving proc from DOTs …
> fix(DB/Spells): Shadow Weaving can proc from periodic spells.

- data/sql/updates/pending_db_world/rev_1628065925391917900.sql
According to multiple data sources, the Chillwind Ravager casts [Chill](https://wowgaming.altervista.org/aowow/?spell=28547). This is an error, as that amout of damage would oneshot a level 60, and I think someone realized this at some point because the spell on AC has been altered to do no damage. AC has the mob casting that spell. It has the same animation and thumbnail as the Blizzard spell, and players can easily just move out of it, but again it causes no damage.
We changed it to [Chilled](https://classic.wowhead.com/spell=15850/chilled) 
-  Changed the spell Chill (28547) to Chilled (15850)
-  Updated comment
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7224
- Closes https://github.com/chromiecraft/chromiecraft/issues/1338
- .go Creature 41331
- Attack it and …
> fix(DB/creature): Changed the spell Chill to Chilled for Chillwind Ravager

- data/sql/updates/pending_db_world/rev_1628079063977567436.sql
Deletes item Pure Un'goro Sample (ID 12236) from NPC Firegut Brute (ID 7035). 
This is because the item should not drop from any world NPCs, as it is generated as part of [this quest](https://tbc.wowhead.com/quest=4294/and-a-batch-of-ooze) instead.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7226
- Closes https://github.com/chromiecraft/chromiecraft/issues/1336
https://tbc.wowhead.com/item=12236/pure-ungoro-sample shows no drops from world NPCs - instead the item is generated as part of a quest.
- Checked all other drop tables/RLTs, no other NPCs dropping the item found.
1. View the Firegut Brute's drop table in Keira and verify item 12236 is not present.
N/A. …
> fix(DB/Loot): Delete Pure Un'goro Sample from Firegut Brute drops

- data/sql/updates/pending_db_world/rev_1628079878307473993.sql
- Deletes lvl 75 items "Plans: Red Belt of Battle" and "Pattern: Belt of Deep Shadow" from Galak Windchaser drop table. The Windchaser is a lvl 25 NPC and should not be dropping lvl 75 plans.
- UPDATE: also deletes two entries pertaining to this NPC and these two items from the conditions table.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7223
- Closes https://github.com/chromiecraft/chromiecraft/issues/1335
https://tbc.wowhead.com/item=30322/plans-red-belt-of-battle
https://tbc.wowhead.com/item=30302/pattern-belt-of-deep-shadow
https://tbc.wowhead.com/npc=4096/galak-windchaser#drops
1. View Galak Windchaser drop table in Keira and verify the two items are no longer present.
N/A. …
> fix(DB/Loot): Remove two lvl 75 plans from Galak Windchaser drops

- data/sql/updates/pending_db_world/rev_1628101702822210800.sql
-  Removed the script that made them use Trash
-  Because it was the only script i changed it to AggresorAI, that said: Creature attacks when entering aggro radius; uses only melee attacks.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6916
- Closes https://github.com/chromiecraft/chromiecraft/issues/1178
- .go c id 1142
- Test the damage, they should only auto atack
1.  .go c id 1142
2. Test the damage, they should only auto atack …
> fix(DB/Creature): Removed spell Trash from Mosh'Ogg Brute (1142)

- data/sql/updates/pending_db_world/rev_1628103343468216300.sql
This quest  it's been added to the end of Magistrix Landra Dawnstrider's other quest chain, that starts with [The Wayward Apprentice](https://tbc.wowhead.com/quest=9254/the-wayward-apprentice) ->[ Corrupted Soil ](https://tbc.wowhead.com/quest=8487/corrupted-soil)-> [Unexpected Results](https://tbc.wowhead.com/quest=8488/unexpected-results) -> [Research Notes](https://tbc.wowhead.com/quest=9255/research-notes). Research Notes is tagged in the DB as the pre-req for Saltheril's Haven whereas Wowhead shows it as a separate and unrelated quest.
- Deleted the quest Sartheril's Haven(9395) from the chain quest starting at The Wayward Apprentice [9254]
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6880
- Closes https://github.com/chromiecraft/chromiecraft/issues/1155
- .go c …
> fix(DB/quest): Removed the quest Sartheril's Haven(9395) from the quest chain

- src/server/game/Entities/Unit/Unit.cpp
Fixed #6935
-  Removed hack fix for sword specialization proc that blocked Hack and Slash proc off from special abilities.
-  
- Closes #6935
- Closes https://github.com/chromiecraft/chromiecraft/issues/1169
1. start auto attacking Targetdummy
2. keep document of procc rates …
> fix(Core/Spells): Removed hack fix for sword specialization proc.

- data/sql/updates/pending_db_world/rev_1628329351520849428.sql
- Adds 3 entries to `skinning_loot_template` to create a new group of drops for level 10-15 creates. This table is as follows:
| Item ID | Item Name | Drop % |
|------|------|-----|
| 2318 | Light Leather| 60% |
| 2934 | Ruined Leather Scraps | 35% |
| 783 | Light Hide | 5% |
This table is derived from studying the loot tables of 58 creatures in the relevant level range. Of course I checked the `skinning_loot_template` table for entries that would fit this distribution first before making a new table, but I couldn't find one that matched with sufficient precision, or one that didn't also contain other leather items that were incorrect. (like medium leather/hides, deviate scales, etc.) And it seems to me that 55 creature templates is a large enough group that making a table to fit their …
> fix(DB/Loot): Create new skinning entries, assigns to various 10-15 NPCs

- src/server/game/Spells/Spell.cpp
Fixed #7090
-  Display spell error if cast levitate on mounted target.
- Closes #7090
- Closes https://github.com/chromiecraft/chromiecraft/issues/1271
- Not tested
1. While playing a character of any class, summon a mount.
2. Using a Priest character, find the mounted character.
3. Cast levitate on the mounted character. …
> fix(Core/Spells): Levitate cannot be casted on mounted targets.

- src/server/game/Entities/Unit/Unit.cpp
-  Notifies AI of nearby creatures immediately if forced update object visibility is called.
-  Removed wrong code. Forced mean forced. Comment `generally this is not needed here, delayed notifier will handle this, call only for pets` is totally wrong, because delayed notifier is called only for non-forced update.
- Closes #7126
- Closes https://github.com/chromiecraft/chromiecraft/issues/1264
- Might closes other tickets about creatures not attacking on player's revive/teleport etc
1. Teleport to any Hillsbrad Miner NPC (GUID 15931) (coords: 27.0, 57.8)
2. Let him kill you
3. Go behind him as a spirit
4. Resurrect & wait …
> fix(Core/Visibility): Notifies AI of nearby creatures immediately if forced update object visibility is called.

- data/sql/updates/pending_db_world/rev_1628521621840404043.sql
- Deletes skinning table 100008 from lvl 1 Serpentbloom Snake (ID 3680). This NPC is too low level to be skinnable, and definitely shouldn't be dropping medium leather or red whelp scales, which it currently does. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7270
- Closes https://github.com/chromiecraft/chromiecraft/issues/1365
https://tbc.wowhead.com/npc=3680/serpentbloom-snake
- Ran SQL, no errors/warnings, 1 row changed as expected.
- Checked in-game, was unable to skin snake corpses:
- Be Horde
- .quest add 962
- .go o 13264 through to 13277
- pick herb, kill snake
- check for skinnability.
N/A. …
> fix(DB/Creature): Delete skinning table from lvl 1 Serpentbloom Snake

- src/server/game/Handlers/PetHandler.cpp
Fixed #7159
-  Player should not be able to summon pet is already is being teleported to other map.
- Closes #7159
- Closes #6830
- Closes https://github.com/chromiecraft/chromiecraft/issues/1302
- Closes https://github.com/chromiecraft/chromiecraft/issues/1132
- 
1. Check that pet is alive
2. Get to BG/RDF queue
3. Start flying to another town
4. Accept the queue
5. Teleport to bg and see pet besides you. …
> fix(Core/Pets): Do not summon pet if owner is being teleported.

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
Fixed #7165
-  Properly unlearn skill dependent spells
- Closes #7165
- Closes https://github.com/chromiecraft/chromiecraft/issues/1044
1. Set Mining to one of these skills: 75-150-225-300
2. Unlearn the Mining skill.
3. See that skills get removed.
4. Log out and back in
5. See there is no Toughness spell in your spellbook. …
> fix(Core/Professions): Properly unlearn skill dependent spells.

- src/server/game/Spells/Spell.cpp
Fixed #7239
-  Added an exception fro Master's Call - do not check if pet is rooted.
- Closes #7239
1. Create a mage and get near a hunter and his pet
2. Cast Frost Nova
3. Use Master's Call …
> fix(Core/Spells): Fixed Master's Call used on rooted pet.

- data/sql/updates/pending_db_world/rev_1628543691784458000.sql
- Added conditions for using the spell
- Closes #7267
- Closes chromiecraft/chromiecraft#1361
1. Take the quest [Raptor Captor](https://wowgaming.altervista.org/aowow/?quest=11146)
2. Attack any mob until it's low on health (~10%/20%)
3. Use the quest item [Sturdy Rope](https://wotlkdb.com/?item=33069) on any NPC
4. Use the quest item [Sturdy Rope](https://wotlkdb.com/?item=33069) on Bloodfen Raptor or Bloodfen Screecher …
> fix(DB/Quest): "Sturdy Rope" Quest Item Despawns Any Low Health NPC, Including Dungeon/Raid Bosses

- data/sql/updates/pending_db_world/rev_1628777209086733059.sql
Aku'mai Servants in BFD (ID 4978) were not casting Frostbolt Volley properly. Checking smart_scripts showed the target selection was 1 (self) not 2 (victim.) This PR corrects that. The confusion probably came from Frost Nova which they also cast, where the spell target is correctly set to 1.
Also note the Frostbolt Volley spell they use is https://wowgaming.altervista.org/aowow/?spell=15043. However, Wowpedia and Wowhead both say they use https://wowgaming.altervista.org/aowow/?spell=8398. However, I have left this alone for now, as the 8398 version does double the damage and I don't want to cause balance issues when someone presumably had good reason to set it this way.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7313
- Closes …
> fix(DB/smart_scripts): Fix Aku'mai Servant spell targeting
