azerothcore/azerothcore-wotlk

data/sql/updates/pending_db_world/rev_1629117996105184400.sql
- Change the quest POI to the correct location
- Closes https://github.com/chromiecraft/chromiecraft/issues/1441
1. Load the SQL query
2. .q add 2518 ( before & after ) …
=> fix(DB/Quest): Tears of the Moon

src/server/game/Maps/MapUpdater.cpp, src/server/game/Server/WorldSocket.cpp
-  Update WorldSocket.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7350
- Muted an offline player then logged on the offline player and he was properly muted.
1. Mute an offline player
2. Login with the offline player
3. Try speaking …
=> fix(Core/Chat): Fix muteTime for players that were muted when offline.

data/sql/updates/pending_db_world/rev_1629121385000760612.sql
Changes the wrong spawnrate of some Groomsblood creatures from 1 minute to 5 minutes.
- Closes #7345 
The issue's author, @jamadaha, provided all the usefull informations and the solution.
None?
- Use the teleport command to one of the provided GUID and kill the creature, wait for 2700 seconds.
None, the changes should be risk-free
=> fix(DB/Creature): Groomsblood's spawn rate

src/server/game/Spells/Auras/SpellAuras.cpp
-  Properly increase / decrease armor after using enrage
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6751
- closes https://github.com/chromiecraft/chromiecraft/issues/1102
- Logged in on a druid used bear form casted enrage.
1. Login on a druid
2. Use Bear form or Dire Bear form
3. Cast Enrage …
=> [Core/Spells]: Fix Druid's Enrage not reducing armor.

data/sql/updates/pending_db_world/rev_1629205101934861200.sql
-  Add the missing [Wildheart Belt](https://tbc.wowhead.com/item=16716/wildheart-belt) item to the loot table
-  Change rates to items based on [this](https://tbc.wowhead.com/npc=9736/quartermaster-zigris)
- Closes partially https://github.com/azerothcore/azerothcore-wotlk/issues/7366
https://tbc.wowhead.com/npc=9736/quartermaster-zigris
- Runned the SQL query and tried some runs on the boss but i ain't that lucky to get a 1.3% drop :(
1. Run the SQL query
2. Kill the boss …
=> fix(DB/Creature): Fix Quartermaster Zigris loot table

data/sql/updates/pending_db_world/rev_1629208615028131900.sql
-  Removes the singular spawn of the Naxxramas portal in Plaguewood.
I've left the `gameobject_template` as it can be used by custom content.
- Closes https://github.com/chromiecraft/chromiecraft/issues/1238
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7401
I don't have a source besides just straight up game knowledge. The portal was removed when Naxx moved. 
- No start up errors / warnings
1. `.go zonexy 35.8 21 139` …
=> fix(DB/Gameobjects): Remove Classic Naxxramas Portal

data/sql/updates/pending_db_world/rev_1629279891518261056.sql
-  Fixed respawn timer for Timmy the Cruel - Stratholme Boss in Scarlet Side. Respawn timer was 300 seconds.
This is a dungeon boss, 86400 seconds is a standard respawn timer for them.
- .go c 247227
- Killed the boss, boss no longer spawns after 5 minutes.
1. `.go c 247227`
2. Kill all Scarlet mobs around to spawn the boss
3. Kill the boss
4. Wait for 5 minutes …
=> fix(DB/creature): respawn timer for Timmy the Cruel

src/server/game/AI/CoreAI/PetAI.cpp, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp, src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
Fixed #7296
-  Properly synchronize pet's position with its owner.
- Closes #7296
- Closes https://github.com/chromiecraft/chromiecraft/issues/1376
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/7296) …
=> fix(Core/Movement): Rewritten follow movement generator for pets.

data/sql/updates/pending_db_world/rev_1629290838385347720.sql
Removes Chimaera Leather from `skinning_loot_template` (this item was removed from Skinning Loot in Patch 3.1.0). Furthermore, this PR increases the Skinning Loot chance for all remaining Skinning Loot (Thick Leather, Thick Hide (if present), Rugged Leather & Rugged Hide) to add up to 100 %, so that there is no chance of no Skinning Loot after removing Chimaera Leather.
The increase was calculated by multiplying with the following factor: 100/(100 - [%chance of Chimaera Leather]).
We don't have any blizzlike data for the exact chances without Chimaera Leather after Patch 3.1.0, so this is the best I can do.
-  Removes Chimaera Leather from `skinning_loot_template`
-  Increases the chance for Thick Leather, Thick Hide (if present), Rugged Leather & Rugged Hide appropriately (sum =100 % -> …
=> fix(DB/Skinning_loot): Remove Chimaera Leather

src/server/scripts/Spells/spell_dk.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/bea682f95c374d914f47925448fff6b8c9d3fcb4)
Co-Authored-By: Lucas Nascimento <keader.android@gmail.com>
* Spell is casted by a trigger, not a player, so script need get owner instead caster
- None
1. See that the CalculateAmount is properly calculated …
=> fix(Script/Spells): Anti-Magic Zone amount calc

data/sql/updates/pending_db_world/rev_1629293337424377430.sql
-  Removed `skinloot` entry from Spirestone Mystic which is a humanoid NPC (ogre)
- Removed `skinning_loot_template` for this NPC as well
- Humanoids can't be skinned.
- Applied PR and tested skinning on a dead NPC
1. Apply this PR
2. .npc add 9198 and kill him
3. Try to skin Spirestone Mystic …
=> fix(DB/Creature): Removed skinloot and skinning_loot_template for Spirestone Mystic

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h, src/server/game/Entities/GameObject/GameObject.cpp, src/server/game/Entities/GameObject/GameObject.h, src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Object/Object.h, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Groups/Group.cpp, src/server/game/Handlers/LootHandler.cpp, src/server/game/Loot/LootItemStorage.cpp, src/server/game/Loot/LootMgr.cpp, src/server/game/Loot/LootMgr.h, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/instance_trial_of_the_crusader.cpp, src/server/scripts/Northrend/IcecrownCitadel/instance_icecrown_citadel.cpp, src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/instance_utgarde_keep.cpp, src/server/scripts/Outland/GruulsLair/boss_high_king_maulgar.cpp
Players that did not participate in killing dungeon boss are not eligible to get loot.
Players that are too far away from the looted object are not eligible to get loot.
Players that released spirit and were outside the dungeon when the loot has been released are eligible to get loot.
Players that have pending bind are not eligible to get loot.
Properly get loot recipient for some chests in dungeons.
All aboved fixes should work in any loot mode (group loot, master loot, etc.)
Fixed #2104.
-  Added some conditions to loot.
- Closes #2104
- Not tested
`Players that did not participate in killing dungeon boss are not eligible to get loot.`
More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/2104) and [here](https://github.com/azerothcore/azerothcore-wotlk/issues/7444) …
=> fix(Core/Loot):

data/sql/updates/pending_db_world/rev_1629313785965120137.sql
Changed the movement to some murlocs.
The (Optional) Move guid 43610 a bit to the side, he is much too close to the tower.
New position could be: x = -11051.1 y = -4121.6 z = 0.85 i checked and he is just in that spot, so all good.
-  Added movement to some mutlocs, removed movement from 1 to prevent clipping
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7409
- Closes https://github.com/chromiecraft/chromiecraft/issues/1454
- .go c 42643. 43629, 42837, 43610, 43612, 43607,  43774 and check the movement
- .go c 43658 and check that he is NOT moving
1. .go c 42643. 43629, 42837, 43610, 43612, 43607,  43774 and check the movement
2. .go c 43658 and check that he is NOT moving …
=> fix(DB/Creature): Fixed some murlocs spawns

data/sql/updates/pending_db_world/rev_1629485842027723200.sql, src/server/game/Globals/ObjectMgr.cpp
-  Partially revert https://github.com/azerothcore/azerothcore-wotlk/pull/3122
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5919
- Tested using the method below
1. Create a fresh DK character.
2. Open your bags
3. Look if you have the item ```[TDB PH] - unsused Scourgestone```
4. If you don't see the item in your inventory then the PR did it's job …
=> [Core/Misc]: Restore playercreateinfo_item item deletion functionality.

data/sql/updates/pending_db_world/rev_1629360903817888286.sql
- Deletes item Thick Wolfhide (ID 8369) from the skinning loot tables of any NPCs that have it.
- Adjusts the other skinning drop rates for items dropped by affected NPCs to compensate. Otherwise the gap left by the deleted Wolfhide in a skinning loot template that no longer added up to 100% would sometimes result in skinning dropping no item at all. This adjustment was done such that each item currently in the skinning table was adjusted proportionally to its current drop rate.
Holding in draft atm because checking with the SQL below shows two NPCs still have the item even after trying to delete it - Tamed Cat 5438 and Deathmaw 10077. This was because these two had skinning IDs that did not match their creature IDs. Modifying those details clears this up.
- Closes …
=> fix(DB/Skinning_loot): Remove Thick Wolfhide, adjust other drops

src/server/game/Spells/Spell.cpp
Fixed #6128
- Closes #6128
- Closes https://github.com/chromiecraft/chromiecraft/issues/736
- Tested ingame with Voidwalker in Elwyn Forest
1. Toggle PvP on
2. Toggle PvP off
3. Wait until PvP flag duration is less than 5 minutes
4. Heal your pet
5. Observe that the duration has been reset to 5 minutes …
=> fix(Core/Players): Healing pet should not reset PvP timer.

data/sql/updates/pending_db_world/rev_1629808025047678029.sql
-  Added 4 new spawns to Slagtree's Lost Tools quest item
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6915
- Closes https://github.com/chromiecraft/chromiecraft/issues/1175
https://tbc.wowhead.com/item=19033/slagtrees-lost-tools#comments
Comments from wowhead for classic realms.
https://www.wowhead.com/object=179908/slagtrees-lost-tools#comments
Comment from 2009 for patch 3.2 where the location still differs from the single spawn on AzerothCore.
- .go go 46420 or 100510, 100511, 100512,100513 and queck the spawn
- Should only be 1 present
Test image of one of the new spawns
1. .go go 46420 or 100510, 100511, 100512,100513 and queck the spawn
2. Should only be 1 present
- Looks like the Point of interest is setted on the base the deepest below the map. I dont know if …
=> fix(DB/Gameobject): Add new spawns to Slagtree's Lost Tools

data/sql/updates/pending_db_world/rev_1629326440508086998.sql
-  removed shadowcat hide entries listed in https://github.com/azerothcore/azerothcore-wotlk/issues/7341
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7341
- None
1. Skin the mobs listed in https://github.com/azerothcore/azerothcore-wotlk/issues/7341 and see if shadowcat hide drops
No. …
=> fix(DB/loot): remove shadowcat hide from skinning loot

data/sql/updates/pending_db_world/rev_1629974973789158607.sql
-  Change `Req.MaxRepValue` to 6000 instead of 0
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7552
- closes https://github.com/chromiecraft/chromiecraft/issues/1503
- None
Look at https://github.com/azerothcore/azerothcore-wotlk/issues/7552 …
=> fix(DB/Quest): "Gaining Acceptance" Reputation limit

data/sql/updates/pending_db_world/rev_1629981420936961816.sql
Changed allowed races on Fire Hardened Mail. Follow up quest should be race-specific.
- Changed the allowed races from alliance only to race specific
- Grimand Elmore (1700) is now human only
- Klockmort Spannerspan (1704) is not dwarf/gnome only
- Mathiel (1703) is now night elf only
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7549
- Closes https://github.com/chromiecraft/chromiecraft/issues/1529
https://tbc.wowhead.com/quest=1701/fire-hardened-mail
- Be warrior lvl 20 (.levelup 19 on yourself)
- .quest add 1702 (required for this to pop up)
- .go c id  5413  Pick the quest fire-hardened-mail from furen-longbeard
- .quest complete 1701 ( fire-hardened-mail )
- Now we should have the 3 quest available, without race filter
- Apply the sql
- Check again. Now depending …
=> fix(DB/Quest): Changed allowed races on Fire Hardened Mail

data/sql/updates/pending_db_world/rev_1630006389394994500.sql
Fixes #5216
- Closes #5216
- Closes https://github.com/chromiecraft/chromiecraft/issues/351
1. Obtain Darkmoon Faire tickets turning in Blacksmithing items
2. Purchased the Minor Darkmoon Prize from Gelvas Grimegate
3. Opened prize in storage …
=> fix(DB/Loot): Corrected Darkmoon Faire Prizes loot.

data/sql/updates/pending_db_world/rev_1630055966364700300.sql
- Set Honored rep requirement in order to access to this quests.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7581
- Checked ingame before/after having the rep.
1. `.go c id 12944`
2. Check that you cannot access the quests.
3. `.modify reputation 59 9000`
4. Check that you can access the quests. …
=> fix(DB/quest_template_addon): Set honored requirement for "Favor Amongst the Brotherhood" quests

data/sql/updates/pending_db_world/rev_1630089240125826910.sql, data/sql/updates/pending_db_world/rev_1630089599912305764.sql
-  Decreases the respawn time of Garrick Padfoot to 90 s (from 180 s)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7586
- Closes https://github.com/chromiecraft/chromiecraft/issues/1551
WoW Classic: https://www.youtube.com/watch?v=5mEmk67r4MQ (spawn at around 00:31 and then again at around 02:03)
- Ran SQL, no errors
- checked db
1. `.go c 80247`
2. kill and wait 90 s
3. or check db (GUID 80247 | ID 103) …
=> fix(DB/Creature): Decreases the respawn time of Garrick Padfoot

data/sql/updates/pending_db_world/rev_1630128453579281559.sql
- Sets the respawn timer for 2 Dark Iron Deposits (GUIDs 64838 and 64842) from 180 secs/3 mins to 900 secs/15 mins to bring them in line with the minimum of all others. There are other nodes of this type with up to 45 min respawn, so this is arguably the smallest change that retains consistency.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7565
- Closes https://github.com/chromiecraft/chromiecraft/issues/1527
Consistency.
- Ran SQL/ no errors/warnings, 2 rows affected.
- Checked DB after query and verifed respawn in now 900 secs.
1. Check Keira for GUIDs 64838 and 64842 of object type 165658.
N/A. …
=> fix(DB/gameobject): Correct respawn time for 2 Dark Iron Deposits

data/sql/updates/pending_db_world/rev_1630158070330132264.sql
-  Change respawn from 20 hours to 32 hours
-  Add random movement for The Husk
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7558
- Closes https://github.com/chromiecraft/chromiecraft/issues/1540
https://tbc.wowhead.com/npc=1851/the-husk
https://youtu.be/wxcbnYbk_uY?t=121
- Run SQL via Heidisql, 4 affected rows, no error.
- Check via in-game
https://user-images.githubusercontent.com/44707108/131220449-f5717733-039a-4e81-8d50-08bf12ffd37e.mp4
- Tested on local server / Win 10 64Bit
1. .go c 53933
2. Observe movement
3. Check databases using keira3 …
=> fix(DB/Creature): Change respawn timer and added movement to The Husk

data/sql/updates/pending_db_world/rev_1630089240125826910.sql, data/sql/updates/pending_db_world/rev_1630139869353251128.sql
-  Slightly changes the position of a Small Thorium Vein (guid = 154), so that is not in the rock and can be mined
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7574
- Closes https://github.com/chromiecraft/chromiecraft/issues/1554
- Ran SQL, no errors
- checked in-game
- looks good and can be mined now
1. `.go gobject 154`
2. check that it is there
3. if not spawned, check with the coordinates of the object with `.gobject near` or check the db …
=> fix(DB/GO): Repositioning of a Small Thorium Vein

data/sql/updates/pending_db_world/rev_1630148697901793648.sql
- Changes the minimum amount of Rich Thorium (ID 10620) mined from Rich Thorium Veins and Ooze Covered Thorium Veins from 1 to 3. This results in 3-5 units mined.
- Changes the minimum amount of Dense Stone (ID 12365) mined from Rich Thorium Veins and Ooze Covered Thorium Veins from 1 to 4. This results in a 50% chance of 4-7 units mined.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7578
- Closes https://github.com/chromiecraft/chromiecraft/issues/1485
https://wowpedia.fandom.com/wiki/Thorium_Ore
https://wotlkdb.com/?object=175404
https://wotlk.evowow.com/?object=175404
- Ran SQL, no errors/warnings, 2 rows changed as expected.
- Tested in-game. All nodes mined conformed to new minimum drops.
1. .set 185 255/300
2. .additem 2901
3. .go object 39945
4. Mine and count …
=> fix(DB/gameobject_loot): Correct Rich Thorium Vein drops

data/sql/updates/pending_db_world/rev_1630085433143335851.sql
Drop rate of the Blood Red Key is different from the drop rate on TBC Wowhead.
Added missing lootid for Dur'an since Keira3 can't open creature loot template without lootid value
-  Changes drop rate for Blood Red Key
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7498
- Closes 
https://github.com/chromiecraft/chromiecraft/issues/1498
https://tbc.wowhead.com/item=13140/blood-red-key
- Apply SQL via HeidiSQL, no error
- Check via SQL Statement
BEFORE
```
mysql> SELECT ct.name, clt.chance
-> FROM `creature_template` ct
-> LEFT JOIN `creature_loot_template` clt ON ct.lootid = clt.entry
-> JOIN `item_template` it ON clt.item = it.entry
-> WHERE it.entry = 13140
-> ORDER BY clt.chance DESC LIMIT 5;
+----------------------+--------+
| name                 | chance | …
```
=>  fix(DB/Loot): Change blood red key drop rate

data/sql/updates/pending_db_world/rev_1630335615911208914.sql
While i was working on it i realized that some crystals were dropping from the sky.
The item falling its a Ash'ari Crystal (10415).
https://wotlk-twinhead.twinstar.cz/?npc=10415
I changed their habitat so its air only and they stay on it. Please if they should go to the ground at some point tell me so we can see the better fix.
Also i added for Masophet the Black a new spawn with 3 new Deatholme Necromancer ready to defend him from some heroes.
-  Changed habitat for  Ash'ari Crystal (10415) to only air
- Added new spawn to Masophet the Black
- Added 3 new spawns to Deatholme Necromancer inside the same ziggurat
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7614
- Closes https://github.com/chromiecraft/chromiecraft/issues/1571 …
=> fix(DB/Creature): Added new spawn to Masophet the Black and more

data/sql/updates/pending_db_world/rev_1630416137992915266.sql
- Moves Tin Vein ID 1732 GUID 63486 slightly so it is accessible to players. Previously it was stuck inside a cave wall.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7659
- Closes https://github.com/chromiecraft/chromiecraft/issues/1564
- Ran SQL, no errors/warnings, 1 row affected as expected.
- Checked in-game, node is now accessible:
1. .go o 63486 and observe.
Note that as this node is pooled, it may not spawn. I ended up temporarily deleting it from the `pool_gameobject` table just to eventually get it to appear (```DELETE FROM `pool_gameobject` WHERE `guid` = 63486;```) - not exactly elegant, but it did make the node spawn at last. The change to the node pool is of course not part of this PR.
N/A. …
=> fix(DB/Gameobject): Adjust Tin Vein position in Westfall

data/sql/updates/pending_db_world/rev_1630405222505942000.sql
Fixes #6633
- Closes #6633
- Closes https://github.com/chromiecraft/chromiecraft/issues/1030
1. go to dalaran sewers
2. train fishing
3. `.set 356 450`
4. .additem 19970, 19971, 7996, 50287, 6553 5, 38802
5. `.cast 59645` (Hungry Tuskarr) This should out level fishing for all of 3.3.5 (600 is max for MOP)
6. Turn off auto loot and fish.
7. You will always get loot. …
=> fix(DB/Loot): Bloated Slippery Eel should be lootable only with quest.

data/sql/updates/pending_db_world/rev_1630421521637477310.sql
-  Added roaming to Quel'Dorei Wraith and Ghost
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7486
- Closes https://github.com/chromiecraft/chromiecraft/issues/1492
https://youtu.be/RaNFK9upvM0?t=117
-  Ran SQL, 31 Affected rows, 0 errors
- SQL query
```
Quel'dorei Wraith
+-------+--------------+-----------------+
| guid  | MovementType | wander_distance |
+-------+--------------+-----------------+
| 82165 |            1 |               5 |
| 82175 |            1 |               5 |
| 82176 |            1 |               5 |
| 82179 |            1 |               5 |
| 82181 |            1 |               5 |
| 82182 |            1 |               5 |
| 82188 |            1 |               5 |
| 82191 |            1 |               5 |
| 82194 |            1 | …
```
=>  fix (DB/Creature): Add roaming Quel'dorei

data/sql/updates/pending_db_world/rev_1629752061588917431.sql
since we dont be havin no solid source i just checked more or less erry guid for the radius to wander. i left some to 0 cuz imo they be guards and issa right that they stay in the place and not stroll around
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6959
- Closes https://github.com/chromiecraft/chromiecraft/issues/1210
none really, only thang we know is that they gotta be wandering
- tested locally, all good.
1. just go in the guids provided in the commit file and check mobs wandering …
=> fix(DB/Creature): fix gordunni/forest walker movement

data/sql/updates/pending_db_world/rev_1630423020825292612.sql
Fixed the spawntimer of Gatekeeper Rageroar (GUID: 36519) to 37800 according to Blizzlike documentation. This translates to 10.5 hours.
-  Fixing spawntimer of Gatekeeper Rageroar by matching the Blizzlike configuration of 10.5-16 hours 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7500
- Closes https://github.com/chromiecraft/chromiecraft/issues/1500
- Tested in-game by verifying the spawntimer using `.npcinfo` on Gatekeeper Rageroar
1. .go creature 36519
2. .npcinfo when selected
3. check spawntimer of 37800 seconds
See screenshots for actual time.
**Alive**
**Dead** …
=> fix(DB/Creature): Spawntimer fix GUID 36519

data/sql/updates/rev_1630698323562531323.sql
sup. this mf -> Screecher Spirit which has entry of 8612 got himself a SmartAI to despawn rogue vale screecher (entry = 5308). i just added new row in its SmartAI script to depsawn vale screecher too (entry = 5307)
idk if for this action (FORCE_DESPAWN) there's a way to specify multiple targets. i didn't find it
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6879
- Closes https://github.com/chromiecraft/chromiecraft/issues/1154
- tested locally and seems all gucci for my ass
1. .q add 3520
2. .go c 51207 and kill the Screecher.
3. Use the quest item on its corpse
4. the mf should disappear when the spirit spawn
word. …
=> fix(DB/SmartAI): fix Screecher Spirit despawn target

data/sql/updates/pending_db_world/rev_1630816536518638817.sql
- Deletes the drop tables for Theldren's 7 Arena Team NPCs in BRD. They are:
| entry | name | 
| ---: | --- | 
| 16049 | Lefty | 
| 16050 | Rotfang | 
| 16051 | Snokh Blackspine | 
| 16052 | Malgen Longspear | 
| 16055 | Va'jashni | 
| 16058 | Volida | 
| 16095 | Gnashjaw | 
These NPCs were collectively dropping 4 items ([Ironweave Mantle](https://tbc.wowhead.com/item=22305/ironweave-mantle), [Shroud of Arcane Mastery](https://tbc.wowhead.com/item=22330/shroud-of-arcane-mastery), [Malgen's Long Bow](https://tbc.wowhead.com/item=22318/malgens-long-bow), [Lefty's Brass Knuckle](https://tbc.wowhead.com/item=22317/leftys-brass-knuckle)) which should only be dropped from the [Arena Spoils](https://tbc.wowhead.com/object=181074/arena-spoils) item. Checking their tables showed they dropped …
=> fix(DB/Loot): Remove NPC drop tables from BRD Arena Team

data/sql/updates/pending_db_world/rev_1630927565231100667.sql
-  Deletes Frost Oil (ID 3829) from the drop tables of 3 NPCs - Vilebranch Witch Doctor 2640, Tar Creeper 6527, and Deadwood Gardener 7154. The origins of this item are a bit unclear, whether it's alchemist-only or if one mob in Silithus also drops it (see the original ticket for a fuller discussion of the matter) but either way, these 3 NPCs should not drop it.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7744
- Closes https://github.com/chromiecraft/chromiecraft/issues/1637
https://classic.wowhead.com/quest=713/coolant-heads-prevail#comments
https://wowpedia.fandom.com/wiki/Frost_Oil?oldid=2030887 
Also https://tbc.wowhead.com/item=3829/frost-oil#dropped-by which shows data that is probably contaminated (imo) but does show these NPCs do not drop it.
- Ran SQl, no …
=> fix(DB/creature_loot): Remove Frost Oil drops from 3 NPCs

data/sql/updates/pending_db_world/rev_1629826555036082700.sql, data/sql/updates/pending_db_world/rev_1630094503763134300.sql, data/sql/updates/pending_db_world/rev_1630484852047598500.sql, src/server/game/Loot/LootMgr.cpp, src/server/game/Loot/LootMgr.h
Fixed #5781
- Closes #5781
- closes https://github.com/chromiecraft/chromiecraft/issues/600
- Might close other tickets about empty loot tables using references.
- Tested ingame with prospecting.
1. `.additem 10620 300`
2. `.learn 31252`
3. set your prospecting to a number key and start tapping …
=> fix(Core/Loot): Properly handle referenced group loot templates.

data/sql/updates/pending_db_world/rev_1631038913388302500.sql
-  Add missing item to loot table
- Closes #7761
- Closes https://github.com/chromiecraft/chromiecraft/issues/1645
[Wiki](https://vanilla-wow-archive.fandom.com/wiki/Azure_Whelpling)
```
Azure Whelpling drops from Blue Dragonspawn, Blue Scalebane, Draconic Magelord and Draconic Mageweaver in Azshara.
This drop possibility was added in Patch 2.3.
```
[TBC Wowhead](https://tbc.wowhead.com/item=34535/azure-whelpling)
```
By Nexuslord on 2008/04/12 (Patch 2.4.1) 
I believe Blue Dragonspawns have a increased drop chance believe it or not.
I have gotten 2 whelps from them. One for myself and one for my friend.
Took me 154 kills to get two whelps from them. But I was still killing the dragons that were all over the place.
```
```
By Rholm on 2007/11/15 (Patch 2.3.0)
I got mine from a Blue …
```
=> fix(DB/creature_loot_template): Add Azure Whelpling on Blue Dragonspawn

data/sql/updates/pending_db_world/rev_1630757583266839900.sql, src/server/game/Entities/Player/PlayerQuest.cpp, src/server/game/Handlers/QuestHandler.cpp, src/server/game/Quests/QuestDef.cpp
Fixes #6732
-  `QuestType=0` means that quest is autocompleted, but it is not added/show in quest log - client automatically shows requested items in UI. That means there should be "!" quest mark instead of "?"
- Closes #6732
- Closes https://github.com/chromiecraft/chromiecraft/issues/1085
- Tested ingame with Darkmoon quests.
1. Go to Darkmoon Faire grounds (Mulgore SW of Thunder Bluff right now)
2. Talk to NPCs Chronos and Morja (DBGUID 137671 and 137684)
3. Notice the quest marks and quest completion/requested items texts as it should …
=> fix(Core/Quests): Properly handle quests with QuestType=0.

src/server/game/Spells/SpellEffects.cpp, src/server/game/Spells/SpellMgr.cpp
-  Dispel spells that remove only one bleed effect should work properly now.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7749
- closes https://github.com/chromiecraft/chromiecraft/issues/1643
1. Apply two bleed effects on yourself
2. Use the Luffa Item
3. Observe if only one bleed has been removed. If so it works properly. …
=> [Core/Item]: Fix Luffa removing more than one bleed

src/server/scripts/Northrend/Ulduar/Ulduar/boss_hodir.cpp
-Prior to this change the Hodir encounter could not be started due to constant Reset(); spam -
-  Changed IsInRoom call to standard Y axis comparison.
-  Added EvadeMode when Hodir leaves the room.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5859
- Tested changes in-game.
1. Go to Hodir.
2. Attack.
- No other issues on this ticket. …
=> fix(Scripts/Ulduar): Hodir boss fight issue

data/sql/updates/pending_db_world/rev_1631201007246764700.sql, src/server/game/Entities/Unit/Unit.cpp
Fixes #5392
Fixes #6285
- Closes #5392
- Closes #6285
1. Enter Maraudon Pristine Waters
2. Fight Princess and watch her when casting Dust Field …
=> fix(DB/Spells): Define Dust Field as a positive spell.

data/sql/updates/pending_db_world/rev_1631329691460885909.sql
Changes the respawn timer for 3 quest items used in ["A Refugee's Quandary"](https://www.wowhead.com/quest=3361/a-refugees-quandary). These items are:
- [Felix's Chest](https://www.wowhead.com/item=16313/felixs-chest) (16313)
- [Felix's Bucket of Bolts](https://www.wowhead.com/item=16314/felixs-bucket-of-bolts)(16314)
- [Felix's Box](https://www.wowhead.com/item=10438/felixs-box) (10438)
The respawn for all of these is changed from 180 secs/3 mins to 10 seconds.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7817
- Closes https://github.com/chromiecraft/chromiecraft/issues/1689
https://youtu.be/3xH2zHN4J7c?t=86 - someone grabs item before the person recording, so we get to see the full respawn time. This was shot on Wow Classic.
https://youtu.be/3xH2zHN4J7c?t=135 - same …
=> fix(DB/gameobject): Fix respawn timers for "Refugee's Quandary" items

data/sql/updates/pending_db_world/rev_1631368907971857000.sql
-  Moves multiple stranglekelp to the shore
- Closes #5794
- Closes https://github.com/chromiecraft/chromiecraft/issues/608
New positions gathered from [wowhead](https://tbc.wowhead.com/item=3820/stranglekelp#map)
- Checked whether the new positions are to close, by .gobject near 20
- Also performed below test
1. Perform SQL query
* Should change one row per query
2. Check that each stranglekelp spawns in/near water …
=> fix(DB/Gameobject): moves stranglekelps to the shore

data/sql/updates/pending_db_world/rev_1631433270459665577.sql
- Removes the respawn timer from [quest](https://tbc.wowhead.com/quest=529/battle-of-hillsbrad) object [Shipment of Iron](https://tbc.wowhead.com/item=3564/shipment-of-iron) ID 1736. It was previously set to 5 minutes. This is to bring it in line with observed behaviour on Classic servers. 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7831
- Closes https://github.com/chromiecraft/chromiecraft/issues/1703
YouTube:
[Youtube Clip 1](https://youtu.be/kq_xTYj_XBw?t=128) 2:07
[Youtube Clip 2](https://youtu.be/MJ8g6jNHB3k?t=252) 4:12
Both of these appear to be shot on retail servers. I did find other clips showing the crate vanishing when clicked, but they were either self-identified as being on private servers (Wow-Mania in this case), or were made by people who seemed very …
=> fix(DB/Gameobject): Remove Shipment of Iron respawn timer

data/sql/updates/pending_db_world/rev_1631537204810734698.sql
- Adds missing Voidwalker summons to [Apothecary Falthis](https://tbc.wowhead.com/npc=3735/apothecary-falthis). Video and Wowhead both support him having this ability.
- Also shifted his spawn slightly to match observed spawn point in Wrath-era video listed in sources below. I was much more hesitant about this bit because of the concerns about using footage from a private server. (Were there private servers in 2010? In German?) But checking some of his other videos does show signs of other people (flying taxis in the distance, people helping in fights) so the risk doesn't seem that high. The new spawn point also averages the two points shown on TBC Wowhead, instead of being slightly off for one and way off for the other as it is currently.
- Closes …
=> fix(DB/smart_scripts): Add Voidwalker summons to Apothecary Falthis

data/sql/updates/pending_db_world/rev_1631634961417748000.sql
Reputation gains were too high (x5). No decrease after honored.
Some mobs (Warug bodyguard, Khan shaka, Khan Jehn) had wrong reputation.
Closes AzerothCore 7339 and 6526
ChromieCraft 1406
-  Reduce reputation gain for Gelkis and Magram 
-  Add variable reputations for the different mobs based on data from commits
-  Increase "MaxStanding" to make the loss of reputation possible beyond honored. Increase MaxStanding to make revered possible.
- Added SmartAI to Khan Shaka but not used, I think he should have some scripts based on wowhead, he should be the opposite of Jehn which has defensive abilities, wowhead says he has offensive abilities.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7339
- closes https://github.com/chromiecraft/chromiecraft/issues/1406
- closes …
=> Fix(DB): Gelkis/Magram reputations

src/server/game/Maps/Map.cpp
-  Remove `ABORT()` so the server doesn't crash
**NOTE**: yes, I know, this is NOT solving the underlying issue and the program should never reach that point anyway. HOWEVER, with this change at least the server doesn't crash. We have been testing this with hundreds of players online:
- with `ABORT()`: the server kept crashing from time to time
- without `ABORT()`: no issues reported, no crash
- ref https://github.com/azerothcore/azerothcore-wotlk/issues/7881
- Tested with hundreds of players
- We should fix the underlying issue, but I have no idea what it is …
=> fix(Core/Map): remove ABORT() to prevent crash

src/server/game/Globals/ObjectMgr.cpp
This solves issue https://github.com/azerothcore/azerothcore-wotlk/issues/8819
This is related to my previous PR https://github.com/azerothcore/azerothcore-wotlk/pull/8715 .
I had a wrong field id number being 19 when it should be 18 by error. I apologize.
Change incorrect field from 19 to 18.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8819
Segment fault issue should be resolved. I apologize for the typo. …
=> (Core/Fix) Segment fault error fix

src/server/scripts/Spells/spell_hunter.cpp
- Checks for `spellInfo` before accessing `spellInfo->xxx`
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8846
=> fix(Scripts/SpellHunter): prevent crash in spell_hun_readiness

src/server/scripts/Spells/spell_item.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8864#issuecomment-956069465
- 
- 
1.
2.
3. …
=> fix(Scripts/Spells): Blessing of Ancient Kings crash

src/server/game/Handlers/ItemHandler.cpp
Fixes #8604
- Closes #8604
- Closes https://github.com/chromiecraft/chromiecraft/issues/2134
1. Fill out all bag slots with bags - .additem [Runecloth Bag] 4 if your bag slots aren't full already.
2. .additem [small soul pouch]
3. .additem [runecloth bag]
4. .additem [gem pouch]
5. Try to equip the soul bag or runecloth bag by right clicking on them.
6. Right click on the gem pouch, hit Ok on the popup. …
=> fix(Core/Item): Fixed showing errors when cannot equip some item.

src/server/scripts/Spells/spell_generic.cpp
-  Check if the player is mounted before spawning the gobject.
- Closes #8873
- Closes https://github.com/chromiecraft/chromiecraft/issues/2227
- Build and tested, works
1. The silithyst aura can be added with `.aura 29519`
2. For Horde, `.go c 43204` will get you to a nearby NPC.
3. For Alliance, `.go c 43205`
=> Fix(Core/Spells): Exploit with silithyst aura

data/sql/updates/pending_db_world/rev_1636026426526412472.sql
There are 29 Sayge's Fortune cards dropping from 51 various NPCs, which should only drop from [Darkmoon Faire Fortune](https://tbc.wowhead.com/item=19422/darkmoon-faire-fortune). This removes the fortunes from the NPC drop tables. The items are still dropped from the DMF Fortune item as they should be.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8943
- Closes https://github.com/chromiecraft/chromiecraft/issues/2259
https://tbc.wowhead.com/item=19229/sayges-fortune-1#contained-in-item
https://tbc.wowhead.com/item=19422/darkmoon-faire-fortune#contains
https://wowpedia.fandom.com/wiki/Sayge's_Fortunes?oldid=2385001
- Ran SQL, no errors/warnings. Only 50 rows changed instead of 51, turns out that Lieutenant Lewis ID 13147 and Lieutenant Lewis (1) ID 22703 share the same …
=> fix(DB/creature_loot): Removes Sayge's Fortunes from all NPCs

src/server/game/DungeonFinding/LFGMgr.cpp
Fixes #8609
- Closes #8609
- Closes https://github.com/chromiecraft/chromiecraft/issues/1743
1. Make players join a group dungeon through Random Dungeon queue
2. Make one of the party members leave the dungeon.
3. Make the Group Guide queue the group to find the missing person.
4. Make the Group Guide stop the queue.
5. Make the Group Guide queue the group the again, only this time they should receive the "One or more dungeons was not valid" message. …
=> fix(Core/DungeonFinder): Enabled requeueing inside random dungeon.

src/server/game/Entities/Player/PlayerUpdates.cpp
Fixes #7266
- Closes #7266
- Not tested.
https://github.com/azerothcore/azerothcore-wotlk/issues/7266#issuecomment-950305006 …
=> fix(Core/Players): Charge should not delay player's auto attacks.

src/server/game/Entities/Unit/Unit.cpp
Fixes #8723
- Closes #8723
- Closes https://github.com/chromiecraft/chromiecraft/issues/1905
.learn 1464
.setskill 172 300
.additem 11931
equip item
.go c 202727
use slam and watch to swing timer …
=> fix(Core/Spells): Slam should suspend attack timers.

data/sql/updates/pending_db_world/rev_1636045459174422908.sql
-  Sets spawn timers in accordance to the addressed issue.
- Closes #7588
- Closes https://github.com/chromiecraft/chromiecraft/issues/1558
See linked issue
- As below
1. Run query - Each row should change respectively 1, 1, 1, 41 and 1 rows 
2. Check that each mob have the correct spawn time
* ID 506 should have 9000 seconds
* ID 519 should have 10800 seconds
* ID 520 should have 9000 seconds
* ID 573 should have 18000 seconds
* ID 1424 should have 7200 seconds …
=> fix(DB/Creature): Corrects spawn times of various Westfall rare mobs

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_gyth.cpp
Fixes him not being summoned if Gyth's casting something when the transition hits.
-  Fixes him not being summoned if Gyth's casting something when the transition hits.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9062
- 
1.
2.
3. …
=> fix(Scripts/UBRS): Rend's summon spell should be a triggered cast

data/sql/updates/pending_db_world/rev_1636425298992535900.sql
-  Remove despawn SAI line (85% chance of despawn on initialize)
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9029
- 
1.
2.
3. …
=> fix(DB/SAI): Goraluk Anvilcrack should always spawn

src/server/game/Entities/Creature/Creature.cpp
-  Move OnCreatureCreate call to the end of the AddToWorld(), so that a user gets a creature that is initialized beforehand.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9088
TC has the same (discovered after trying) https://github.com/TrinityCore/TrinityCore/blob/04909bada85d4770a58a5b2b6f2180f5aacb1b81/src/server/game/Entities/Creature/Creature.cpp#L274
Since the code base has diverged, we still need to check that we're not affecting anything else
- Tested on The beast, he seemed to work. Using a win10 x64 build relwithdebinfo.
- 
1. First test is to verify it fixes the issue (steps taken from the issue report)
.additem 12709 - skining dagger
.setskill 173 400 - dagger skill if needed
.setskill 393 400 - skinning
.go c id 10430
.cast 10768
2. Try to find where it …
=> Fix(core/Creature) initialize AI before calling OnCreatureCreate

data/sql/updates/pending_db_world/rev_1636143937359438400.sql
Fixes #8735
- Closes #8735
- Closes https://github.com/chromiecraft/chromiecraft/issues/2191
- Not tested.
.character level 60
.go c 202727
.additem 42956 and use it
.learn all my spells
add Hemorrhage in Subtlety branch
.maxskill
**For …
=> fix(DB/Spells): Glyph of Backstab should proc off only from Backstab.

data/sql/updates/pending_db_world/rev_1636665257418709911.sql
TC & VMangos Cherry Pick
-  Add pre-cata equipment to 2 creatures from tc commit which is also also a vmagos cherrypick as well.
- Mentioned TC Issue: https://github.com/TrinityCore/TrinityCore/issues/27209 
[](https://github.com/TrinityCore/TrinityCore/commit/5a3c9c46f654c1cecf4aebb2c53e58e220c7aead)
- Builds and compiles with no issues.
- https://tbc.wowhead.com/npc=3203/fizzle-darkstorm - Missing staff is now added
https://www.wowhead.com/item=1907/monster-staff-basic
- https://tbc.wowhead.com/npc=4667/burning-blade-shadowmage - Wrong staff, is now corrected to
https://www.wowhead.com/item=2177/monster-staff-ornate-mage-staff
1.  perform a .npc add 3203 to observe they now have the correct staff
2.  perform a .npc add 4667 to observer they now have the correct staff …
=> DB/Creature: Add pre-cata equipment to 2 creatures

data/sql/updates/pending_db_world/rev_1637271386614261100.sql
Restore accidentally deleted creature spawns with new guids.
https://github.com/azerothcore/azerothcore-wotlk/pull/9200
-
- checked that both new guids are free
- run sql, checked imgame
1. go creature 201207 
2. go creature 201208 
-
**For …
=> DB/Creature - restore deleted spawns

data/sql/updates/pending_db_world/rev_1637539503631638300.sql
-  Remove groupAI flag wrongly assigned.
-  
- Closes #9269 
- Ran the sql, went to pitofsaron and there were no crash anymore.
- 
1.
2.
3. …
=> fix(DB/Crash): remove wrong groupAI flag causing stack overflow

data/sql/updates/pending_db_world/rev_1636799867064749300.sql, src/server/game/Entities/GameObject/GameObject.cpp
- add 2 exceptions for badge and shield so that they actually use the DB quaternions
- add data to said quaternions
- Move hoofprints a bit so they are less stuck in the ground
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7946
- Went there, objects are in a more reasonable position, though not perfect.
- 
1. Go to shady inn at dustwallow marsh .go gameobject 10175 and assess
2.
3. …
=> (hack/db) improve position of objects around Shady Inn (dustwallow marsh)

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/Spell.cpp
Fixes #8883
- Closes #8883
- Closes https://github.com/chromiecraft/chromiecraft/issues/1912
1. Start Auto-Attacking a target, for example training dummy.
2. Start channeling Volley.
3. Switch target to any other target that you are able to attack from where you are channeling. …
=> fix(Core/Spells): Autoshot should not interrupt Volley.

src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.h, src/server/scripts/Kalimdor/BlackfathomDeeps/instance_blackfathom_deeps.cpp
-  Add new state for when the overall event is completed to use for identifying the state of fight
-  When crash happends, and you re-enter, use this new state to determine whether if the door should be opened or not
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9434
_Scenarios tested:_
- Use all flames but not finishing event & crash (**Result**: Door closed, flames reusable)
- Use all flames and finish event  (**Result**: Door opens as intended)
- Use all flames and finish event & crash (**Result**: Door open, flames not reusable)
_Build_
> ========== Build: 3 succeeded, 0 failed, 15 up-to-date, 1 skipped ==========
1.  `.go ga 32930`
2. use flames
3. exit worldserver or command `.server restart 1`
N/A …
=> fix(Scripts/BFD): Fix problem with Aku'mai event being skippable after crash

src/server/game/DungeonFinding/LFGMgr.cpp, src/server/game/DungeonFinding/LFGMgr.h
-  Emit `LFG_TELEPORTERROR_COMBAT `(was `LFG_TELEPORTERROR_CHARMED`) if player is in combat when trying to leave LFG
-  Rename `LFG_TELEPORTERROR_CHARMED ` to  `LFG_TELEPORTERROR_COMBAT  `since the message is shown as below
> You can't do that while in combat
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/9438
"Players may teleport in and out of the dungeon at any time if they are not in combat." - https://wowpedia.fandom.com/wiki/Dungeon_Finder?oldid=2357590 - from August 2010
- Message is shown and you don't get removed from group/dungeon if in combat attempting to leave
- Build Pass
> ========== Build: 4 succeeded, 0 failed, 14 up-to-date, 1 skipped ==========
1. `.debug lfg`
2. Join solo or with someone to grief.
3. Get into combat, then use the LFG/RDF icon on the …
=> fix(Core/LFG): Prevent leaving LFG if in combat

src/server/game/Handlers/ChatHandler.cpp
- Change condition for hook `CanPlayerUseChat`
- Closes #9504
=> fix(Core/Chat): correct logic for using guild officer chat

src/server/game/Entities/Player/Player.cpp
-  Move to static_cast and matching it up with tc stops the error on console and first login characters from being frozen when skipping cinematics
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9321
Trinitycore Comparison dealing with GetViewpoint in the player.cpp
- Builds and runs
- I skip the cinematics with in 2 seconds on a new created player and had zero error on console and can move freely
Most easily replicable.
1. create blood elf, any class, any gender
2. skip the cinematic with in 2 to 6 seconds
3. observer no error on console and character can move freely. …
=> (Core\First Login) Freeze fix potential

data/sql/updates/pending_db_world/rev_1638644587511744300.sql
-  Apply Aura [29266](https://classic.wowhead.com/spell=29266/permanent-feign-death) to Citizen of New Avalon in Death Knight Base during DK starting experience.  Confirmed to be correct aura via sniffs (thanks @acidmanifesto)
-  Match dead Scarlet Crusaders in the same room.
[Before](https://i.imgur.com/ny08I6R.jpg)
[After](https://i.imgur.com/9lUnyhn.jpg)
.go c 129727
=> fix(DB/Creature): Apply 'Permanent Feign Death' to Citizen of New Avalon

src/server/database/Database/Implementation/CharacterDatabase.cpp, src/server/scripts/Commands/cs_item.cpp
-  Add a player guid check towards recory_items column to make sure you cannot restore a item to the wrong player
- Closes TODO part in https://github.com/azerothcore/acore-cms/pull/85
**Note**: This item duplication cannot be done by a player today, but without this PR it will be doable, as the above PR about item restoration for websites ain't implemented as of time.
- Builds
- Tested command before & after in worldserver
**Before**
**After**
Do the same as above, however you will now be met with "no items with the given entry to recover" msg
N/A …
=> fix(Core/Commands): Item duplication exploit

src/server/scripts/Commands/cs_item.cpp
-  Validate item recover is enabled in worldserver config upon `.item restore list` command
N/A
N/A
Not tested
1. run `.item restore list` with item recovery disabled in worldserver config
2. you should now see a msg telling you it's disabled …
=> fix(Core/Command) cfg check on item restore list

data/sql/updates/pending_db_world/rev_1639529374031815939.sql
-  Fix loot mindlessly copied from web.
- Closes #9603
Done this quest a few times. It should only contain one item, a fel cone.
- none
1. .add quest 489
2. loot fel cones
=> fix(DB/Loot) Fel cone loot incorrect

data/sql/updates/pending_db_world/rev_1639771397743365253.sql
- Fixed movement and position of Deatholme Darkmages
- Updated SAI to use Combat Movement Control flag 64 rather than the out dated prevent movement monstrosity.
- Removed one bad Mist Bat spawn.
Closes #5764
I could not replicate issue.
Sniff
- Inserted
- Tested SAI combat
- There were no issues with NPCs not using doorway to exit.
1. .go c 82742
=> fix(DB/Creature/SAI/Conditions) Twin Ziggurats Deatholme Darkmage

data/sql/updates/pending_db_world/rev_1640365530283717518.sql, src/server/scripts/World/go_scripts.cpp
- Update quest to deactivate the beams for 10 seconds on click like official.  
- I chose C++ over SAi for this scripting due to DespawnOrUnsummon forced respawn timer fails the first time in SAI and I wanted this to work correctly.
Sniff
1. .quest add 8889
2. .go xyz 9334.2 -7880.1899 74.9103
3. do quest
=> fix(Script) Quest "Deactivating the Spire"

data/sql/updates/pending_db_world/rev_1640718198383728700.sql
-  Generally remove Jingling Bell from creature loot. _(today, only  creature Lava Surger drops it)_
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9866
> Jingling Bell is one of the four possible pets inside gifts under the big tree in Ironforge and Orgrimmar during the Feast of Winter Veil seasonal event.
https://wowwiki-archive.fandom.com/wiki/Jingling_Bell#Source
- SQL applies
- SQL doesn't remove item from unwanted creature loot. _(should be none)_
- Verified Jingling bell to still drop from Gaily Wrapped Present
Following query should retrieve 0 results.
> SELECT *
FROM creature_loot_template
WHERE Item = 21308
And this query should show you a drop from `Gaily Wrapped Present`
N/A
You …
=> fix(DB): Remove Jingling Bell from creature loot

src/server/scripts/Kalimdor/zone_silithus.cpp
-  Change out of combat despawn from 6 seconds to 5 minutes
-  Apparently tempsummon timer alone can't handle the expected behavior
- Closes https://github.com/chromiecraft/chromiecraft/issues/2689
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9913
- 
1.
2.
3. …
=> fix(Scripts/Silithus): Solve issues with bosses despawning during loot

src/server/game/Entities/Creature/TemporarySummon.cpp, src/server/game/Entities/Object/Object.h, src/server/scripts/Kalimdor/zone_silithus.cpp
-  Implement new tempsummon event: `TEMPSUMMON_TIMED_DESPAWN_OOC_ALIVE`
-  Apply `TEMPSUMMON_TIMED_DESPAWN_OOC_ALIVE `to wind stone summons in Silithus to fix issues addressed
- Manually set corpse delay to 5minutes
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/9913
- Closes https://github.com/chromiecraft/chromiecraft/issues/2689
- Properly fixes https://github.com/azerothcore/azerothcore-wotlk/pull/9914
1. Tested ingame: See my video below
2. Build works
```
.go c 42971
.additem 20406
.additem 20407
.additem 20408
.additem 20422
.additem 20451
wear items
use [Greater Wind Stone] near
```
Do above steps twice, kill one, and second one to gm on
N/A  …
=> fix(Core/TemporarySummon) New event to despawn OOC

data/sql/updates/pending_db_world/rev_1640969804388366165.sql
Tree Frog has no loot. This is comical that we had it like this for so long.
-  Remove Loot Link to Tree Frog
-  Remove Tree frod loot table
- Closes 
Tree Frogs never had loot. No Pet ever had Loot.
- Kill Tree Frog
- Observer no more loot.
1. Kill Tree Frog
2. Observe No more loot.
3. I repeated myself didn't I? …
=> Fix (DB\Loot) Remove Tree Frog Loot

data/sql/updates/pending_db_world/rev_1640972252071688181.sql
Verified via UDB Loot per consolidated sniffs
-  Corrects The % of the Abyssal Crest with verified % drop
-  
- Corrects https://github.com/azerothcore/azerothcore-wotlk/pull/9857
UDB Consolidated Sniffs
- Builds
- Runs
1. Murder the 4 templars
2. Notice drop rates are not 100% as intended. …
=> Fix (DB\Loot) Abyssal Crest Loot % correction

src/server/game/Entities/Player/PlayerSettings.cpp
-  Remove trailing whitespaces
-  
- Closes 
- 
1. settings announcer off
2. save
3. notice no extra 0s get added to the db after saving …
=> fix(Core/Players): fix trailing whitespaces being added as settings

src/server/scripts/Kalimdor/zone_the_barrens.cpp
-  Someone forgot to restore the faction upon destroying lol...
- Closes #6856
- Closes https://github.com/chromiecraft/chromiecraft/issues/1137
1. .go c 14387 and accept quest.
2. Escort the NPC to the end of quest trail.
3. Pull any aggressive mob around or let it come into Wizzlecrank's Shredder's pull range.
4. Observe the mech face sliding toward the enemy.
=> Fix(Core/Creature): Disable shredder should not attack creatures nearby

data/sql/updates/pending_db_world/rev_1640651539577989000.sql
-  Add conditions for both alliance and horde quests sides.
- Closes #8326
- Closes https://github.com/chromiecraft/chromiecraft/issues/2001
1. .go c id 14368
2. Check if it has some daily quests. It should not have any (except for mages I think).
3. If you are horde: .q a 7481 / .q c 7481 / .q rew 7481 --- If you are alliance: .q a 7482 / .q c 7482 / .q rew 7482
4. Check if the dailies are available.
=> Fix(DB/Quests): Pre-quest requirement for Lorekeeper Lydros quests

data/sql/updates/pending_db_world/rev_1640656702788330300.sql, src/server/scripts/Spells/spell_item.cpp
-  Added spell script to calculate the damage.
- Closes #8262
- Closes https://github.com/chromiecraft/chromiecraft/issues/1969
https://www.youtube.com/watch?v=iH_HnGyFplI
https://tbc.wowhead.com/item=11920/wraith-scythe#comments
1. .add 11920
2. Equip some spell power gear
3. See the dmg
=> Fix(Core/Item): Wraith Scythe scales with spell power

data/sql/updates/pending_db_world/rev_1641238616670655918.sql
Catch and Release smart script fix for quest
-  Catch and Release Smart Script adjustment to prevent killing when tagged and now despawns
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8146
Sniff Team
- Build
- Performance
1. Do quest Catch and Release and you will see quest now works like it does with retail.
2. When you Tag the scout with the quest item, please try to attack the scout and wait 7 seconds as this should despawn in that time …
=> Fix (DB\SmartScript\Quest) Catch and Release

data/sql/updates/pending_db_world/rev_1641153687282510374.sql
Item was never a npc drop. Verified thru UDB.
-  Removes Ez-Thro Dynamite II from npc Loot tables
-  Item was never a Loot Drop from a NPC.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9974
- Closes https://github.com/chromiecraft/chromiecraft/issues/2713
UDB
- Builds
- Performs
1. Item is fabricated only. Never Dropped …
=> Fix (DB\Loot) Ez-Thro Dynamite II

data/sql/updates/pending_db_world/rev_1641307926630364064.sql
Deletes Frigid Ring from Creature Loot and adds to Reference Loot where it is proper. Item is a area creatures drop not a single creature loot drop.
-  Removes Frigid Ring from Creature Loot
-  Adds Frigid Ring to Reference Loot Table
- Closes https://github.com/chromiecraft/chromiecraft/issues/2370
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10003
- Builds
- Performs
1. Rare drop, Kill any creature with reference loot table 24016 …
=> Fix (DB\Loot) Frigid Ring Reference Loot Fix

data/sql/updates/pending_db_world/rev_1641313085677965557.sql
Removes the loot from 3 creatures who should not have the loot per udb audit.
-  Removes the Loot from 3 creatures who should not have the loot item.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10005
- Closes https://github.com/chromiecraft/chromiecraft/issues/2530
UDB Sniff Team
- Builds
- Performs
1. Item is removed from 3 creatures who should not have it …
=> Fix (DB\Loot) Copper Bolt Loot fix

data/sql/updates/pending_db_world/rev_1641302977270881641.sql
Remove Broken Silithid Chitin from npc. NPC Never dropped it. Compared to UDB for verification.
-  Removes Wrong Loot from NPC
- Closes https://github.com/chromiecraft/chromiecraft/issues/1824
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10001
UDB Sniff Team
- Builds
- Performs
1. NPC no longer drops wrong loot. …
=> Fix (DB\Loot) Zora Loot fix

src/server/game/AI/CreatureAI.h, src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
-  Add the ability to know when a non repeating path has completed without the need to know the number of points. 
-  This works in c++ script atm using void PathEndReached().
I have never been a fan of pausing pathing to do actions. This simple addition will give the ability to have multiple paths between actions and randomize the time before calling new path rather than a set a pause time in one path allowing more control over scripting.
The only important point in a path is when it ends. Pausing is wrong. We can now script properly.
Me
- Tested on a script I am working on for Eastvale logging camp.
1. You would need to script an npc with a non repeating path in c++ and do an action in void PathEndReached()
- Will need to get this added to SAI.
=> Feat(Core/Pathing) Path End Reached

src/server/game/AI/CreatureAI.h, src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
-  After using function on a script I am working on I realized it would be helpful to know the path Id you just reached the end of if you have multiple paths. 
- Closes 
Me
- Tested in game on an in progress script. Works perfectly.
1. At end of a path use a check for correct path number in void PathEndReached().
=> feat(Core/Pathing): Add path_id to PathEndReached

data/sql/updates/pending_db_world/rev_1641421027611299094.sql
-  Missing entire script for last part of chain so added this, waypoints and correct walk/run values from sniffer
-  
- Added missing script issue mentions cant start while mounting, but didnt mention Totem Yor part has no script, just a simple spell cast.
- Also corrected all npc walk/run speeds all values taken from sniffer and added waypoints for last part also from sniffer
- Closes #7338
Sniffer Team
- Build
- Performed
1. Do chain quest https://tbc.wowhead.com/quest=9538/learning-the-language
2. Totem of Yor part was missing the entire script, this adds the script and the waypoints from sniff
3. The only issue is when he casts Shadow of the Forest on the player you have to move or you wont see Stillpine Ancestor Yor, this is a visual state issue within the core
4. This is the spell …
=> Fix (DB\Quest\SmartScript): Quest 9540 Totem of Tiki

data/sql/updates/pending_db_world/rev_1641340369241454365.sql
-  fix position of Greater Timberstrider in Azuremyst Isle
- Closes #9996
- npc moved to proper position, sql applied
1. .go c 62817 …
=> fix(DB/Creature) Greater Timberstrider position

data/sql/updates/pending_db_world/rev_1641384460010602200.sql
- Changed reputation to monsters in Western Plaguelands according to the
wiki, which was updated until patch 2.2
- Closes #7130
- Closes https://github.com/chromiecraft/chromiecraft/issues/1232
https://wowpedia.fandom.com/wiki/Argent_Dawn?oldid=2384820
- Not tested
1. Check the NPCs 8558, 1788, 11873, 1804, 12262, 12263, 8543, 8545, 11075, 1852, 853
2. They should award the same reputation as displayed on that table
None …
=> fix(DB): Western Plaguelands monster reputation

src/server/game/Handlers/GuildHandler.cpp
Fix for TabWithdrawItemLimit
-  remove the problematic cast to uint8 to allow guild bank max stacks per day to be greater than 255.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10041
Should be obvious...
- Compiled on Debian 11 x86 and x64
- Tested to set max stacks per day and it worked as intended.
- Cheked the value in the DB table guild_bank_right and it was correct as expected.
Ingame:
1. press o
2. click guild
3. click options
4. select a rank
5. select a tab
6. enter value above 255 at stacks per day
7. click accept
8. click options again and see the changed value for stacks per day
- maybe encapsulate packet.TabFlags[tabId] in a uint32 ? …
=> fix(Core/Handlers): remove the uint8 cap from guild bank max stacks per day

data/sql/updates/pending_db_world/rev_1641660333161433796.sql
-  Replace manual paths with proper sniffed paths. Add one missing path and remove some random movements to match official.
- The Timbermaw Woodbenders and Timbermaw Mystics share spawn points, which cannot be handled properly yet, and AZ had all Woodbenders spawned so I changed two to look more like official. Hope to poll them in the future.
- Closes 
Sniff
- Checked in game
1. .go c 39353
2. .go c 39721
3. .go c 39354
4. .go c 39685
=> fix(DB/Pathing) Timbermaw Hold

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Globals/ObjectMgr.h
If a creature has genders it will consider gender changing on respawn.
Currently if a creature has genders on Azerothcore, it is locked to the creature_model_info of the display id and will not cycle between gender if it has the gender of (0 = male, 1= female) when it respawns (NOT BLIZZLIKE) but only the model id of pre-exsisting gender.
Durning Sniff Team's Observation it was observed that creature entries with genders will respawn to other genders at random on official Blizzard Realm.
-  If creature has genders it will consider gender changing on respawn.
-  GetCreatureModelInfo to const
- Slight Code Reduction
- Closes None Reported
Malcrom and sniff team observation.
- Builds
- Performs 
1. turn on gm mode so you can safely test with no issues regardless of toon
2. type in .go c …
=> fix (Core/Creature): Random Gender on respawn if Gender exsist for Entry

data/sql/updates/pending_db_world/rev_1641913700930614616.sql
-  Update several spawn points to use Dual Spawning
- Closes 
Official
- Tested in game.
1. .tele RavenHill kill fiends and horrors
2. .tele Timbermawhold
=> fix(DB/Creature): Dual Spawning Creature Update

src/server/game/Entities/Creature/Creature.cpp
-  Fix an error, I introduced with multi id spawning, when showing waypoints.
- Closes 
- Tested in game. no longer getting errors in console when showing waypoints in gm mode. 
- 
1. Select a pathing creature.
2. Type ".wp show on" while in gm mode.
=> fix(Core/Waypoint Show): Fixed error with waypoint show.

data/sql/updates/pending_db_world/rev_1642432018580300313.sql
-  Deletes drop from Felhunter
- Partially Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10214
https://tbc.wowhead.com/item=18519/pattern-shifting-cloak
-  sql applied, test drop
1. Spawn Felhunter (entry 417), kill it, pattern will not drop …
=> fix(DB/CreatureLoot) Felhunter (417)

data/sql/updates/pending_db_world/rev_1642347006476746100.sql
Fixes #9819
- Closes #9819
- Closes https://github.com/chromiecraft/chromiecraft/issues/2634
.go ga 50359 …
=> fix(DB/Gameobjects): Pools of Arlithrien moonwell should be invisible.

data/sql/updates/pending_db_world/rev_1643408513033818500.sql
-  Added a new gossip option to recover Amulet of Draconic Subversion.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10410
- Closes https://github.com/chromiecraft/chromiecraft/issues/2873
1. .go c id 11872
2. Talk to her, you shouldn't see a gossip option
3. .q a 6570 / .q c 6570 / .q rew 6570
4. Talk to her again, same as 2.
5. Destroy the Amulet
6. Talk to her, you should see the gossip option to recover your amulet.
7. Click, you now have the amulet again.
=> Fix(DB/Gossip): Myranda the Hag

src/server/game/Scripting/ScriptDefines/GlobalScript.cpp, src/server/game/Scripting/ScriptMgr.h, src/server/game/Spells/SpellMgr.cpp
-  Implement OnLoadSpellCustomAttr global hook, to load custom spell hacks in modules without using spell_dbc (because it's not practical in any way).
-   …
=> feat(Core/Scripting): Implement OnLoadSpellCustomAttr global hook

src/server/game/AI/SmartScripts/SmartScript.cpp
No need to repeat ObjectList* targets = GetTargets(e, unit); over 100 times in the same void you sinners.
-  Stop repeating yourself
- Closes 
- Builds
- Performs
1. Nothing to test
2. Nothing Broke
3. Yes i even ensure SMART_ACTION_SET_ORIENTATION still works. …
=> fix (core): Smart Script Clean up\Code Reduction

src/server/game/AI/SmartScripts/SmartScript.cpp
This reverts commit 0a218c975f3c03cd9f3073910539663fc2e9e2ea.
Memory Leak Issue is being identified by a few fellow devs in response to the clean up.
-  
-  
- Closes 
- 
- 
1.
2.
3. …
=> Revert "fix (core): Smart Script Clean up\Code Reduction (#10491)"

data/sql/updates/pending_db_world/rev_1643306978965271700.sql
-  Use the right broadcast_text for the option.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8739
- Closes https://github.com/chromiecraft/chromiecraft/issues/2195
Based on the previous gossip_menu_action broadcasts.
1. .go c id 16116
2. Go through the dialogs, the gossip with 'What?' shouldn't be empty as before.
=> Fix(DB/Gossip): Angela Dosantos

data/sql/updates/pending_db_world/rev_1643324466347472100.sql
-  Correct ppm for the weapon's proc.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10374
- Closes https://github.com/chromiecraft/chromiecraft/issues/2875
Based on VMangos.
1. .add 17076
2. Verify that the weapon now procs normally.
=> Fix(DB/Item): Bonereaver's Edge proc

src/server/worldserver/worldserver.conf.dist
This is soo we can get a proppery pass\fail status on npc catelog modules dealing with hard coded gossip
-  Add Azerothcore Cateloge NPC ID's to be exempt from gossip check failures due to them being hardcode.
- Closes 
- Builds
- Performs
1. Start up with any of the listed modules npcs
2. Observer no errors or failures …
=> fix (conf): Added additional Cateloge NPC IDS

data/sql/updates/pending_db_world/rev_1643487408879682900.sql
-  Change spawn id from 12468
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10424
Videos from issue
1. go c 84592
2. Adds near the Wyrmguard should be Overseers instead of Hatchers.
=> Fix(DB/Spawn): Death Talon Overseer

src/server/game/Spells/SpellInfo.h
-  Using default constructor without uninitialized value can cause a crash due to out of range value.
- Closes none, this happened to me.
Server crashed while loading SpellInfoCustomAttributes. I debugged it which resulted in this: 
Where SpellId has the following SpellFix
It is using an empty constructor for the assign, which without the uninitialized value, the variable can have trash and occasionally crashing the server due to out of range value when trying to use to retrieve information from its array.
- Tested.
Run worldserver.exe, it will explode sometimes.
=> Fix(Core/Crash): possible crash due uninitialized value

src/server/game/Chat/Chat.cpp
- Add a null check in `ChatHandler::IsAvailable`
- Prevents a crash when using `IsAvailable` from the console
- Compiled and tested on Windows 10 x64 …
=> fix(Chat): session null check for isavailable

data/sql/updates/pending_db_world/rev_1644590484974206900.sql
While working on https://github.com/azerothcore/Keira3/pull/1623 I noticed that in the table `spell_dbc` the EffectBonusMultiplier fields were named `Field227`, `Field228` and `Field229`. The name change would make the columns easier to identify and work with. (Also it makes using them in Keira easier). The new names would then be the same as in the DBC structure / the name commonly used.
- N/A
- [wowdev wiki](https://wowdev.wiki/DB/Spell)
- DBCStructure.h
https://github.com/azerothcore/azerothcore-wotlk/blob/2933a535ff0c037f00ec2c93e27ecef91ce5f849/src/server/shared/DataStores/DBCStructure.h#L1670-L1672
- Query applied without errors
- Server is still usable without errors in the console/log.
- Casting a spell from the `spell_dbc` table worked fine.
1. Apply the sql script
2. Look at the …
=> Refactor(DB/spell): Rename fields according to their DBC equivalent

data/sql/updates/pending_db_world/rev_1644600270428016400.sql
-  Require quest 8481 before 8485 or 8484.
- Closes #6855
Described in:
https://github.com/azerothcore/azerothcore-wotlk/issues/6855
1.     .modify reputation 576 42000
2.     Go to your rep window, select Timbermaw, and unclick "At War"
3.     .go c 39065
4.     See only one quest available
5.     Complete quest, now next is available …
=> fix(DB/quest_template_addon): The Brokering of Peace Quest Order

data/sql/updates/pending_db_world/rev_1644967518818105800.sql, src/server/game/Spells/SpellInfoCorrections.cpp
-  Change implicit target
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10661
1. .go c id 13020
2. Start the encounter
3. See the green beam from Nefarius (it's called Corruption) only affects Vaelastrasz, and not him or anyone else.
=> fix(Core/Spells): Nefarius Corruption should only affect Vaelastrasz

data/sql/updates/pending_db_characters/rev_1644943100668922283.sql, src/server/game/Battlegrounds/Battleground.cpp
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10675
- Tested in game (with the instructions below)
1. Make sure `Battleground.StoreStatistics.Enable = 1` is set
2. Do BGs and check that the table [pvpstats_battlegrounds](https://www.azerothcore.org/wiki/pvpstats_battlegrounds) is correctly set (check the value of `bracket_id`)
3. Try different BGs including Alterac Valley and Warsong Gulch …
=> fix(Core/Battleground/PvPstats): correct bracket_id for AV

src/server/game/Battlegrounds/ArenaScore.h, src/server/game/Battlegrounds/Zones/BattlegroundAB.h, src/server/game/Battlegrounds/Zones/BattlegroundAV.h, src/server/game/Battlegrounds/Zones/BattlegroundEY.h, src/server/game/Battlegrounds/Zones/BattlegroundIC.h, src/server/game/Battlegrounds/Zones/BattlegroundSA.h, src/server/game/Battlegrounds/Zones/BattlegroundWS.h
Code factor fix, this needs to be done so we can merge In support of https://github.com/azerothcore/mod-cfbg/pull/94 and be green on the custom module build test.
-  BG Final Override to Final
-  In support of https://github.com/azerothcore/mod-cfbg/pull/94
- Closes 
- builds
- runs
1. This is just a code factor and hopefully module support compile fix which is another pr …
=> fix (core): BG Final Override to Final

src/server/game/Battlegrounds/Zones/BattlegroundAB.h, src/server/game/Battlegrounds/Zones/BattlegroundEY.h, src/server/game/Battlegrounds/Zones/BattlegroundIC.h, src/server/game/Battlegrounds/Zones/BattlegroundSA.h, src/server/game/Battlegrounds/Zones/BattlegroundWS.h
PT2, codefactor was green and then decided to complain about the other final overrides in BG
-  changed bg final override to final pt 2
- Closes 
- builds
- performs
1 .PT2, codefactor was green and then decided to complain about the other final overrides in BG …
=> fix (core): Final Override to Final PT 2

src/server/game/Entities/Creature/Creature.cpp
-  This was preventing multi ids in certain zones
- Closes 
me
- tested in game. Working
1. ```UPDATE `creature` SET `id1`=18488, `id2`=18549 WHERE `guid` IN (68474,68475,68476,68477,68478);```
2. .go c 68474
=> fix(Core/Creature): Allow Multi id in areas with zone script

data/sql/updates/pending_db_world/rev_1645476483912365838.sql
Smolderthorn Berserker guid 43101 was not attacking due to it being assigned some weird funky smart script instead of just giving it normal pathing waypoints.
-  Moves its guid specific sai to just waypoint pathing
- Closes https://github.com/chromiecraft/chromiecraft/issues/2938
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10782
- builds
- performs
1. .go c 43101
2. observe the npc moving back and forth on its path
3. npc can now attack …
=> fix (db): Smolderthorn Berserker not attacking

data/sql/updates/pending_db_world/rev_1645029283139327800.sql
-  Do not allow Stonemaul Banner to drop from NPCs
-  Already can correctly be retrieved from game object
- Closes https://github.com/chromiecraft/chromiecraft/issues/3071
See original issue: https://github.com/chromiecraft/chromiecraft/issues/3071
- Item no longer drops
1. .go creature 30732
2. Item no longer drops …
=> fix(DB/creature_loot_template): Stonemaul Banner Drop

data/sql/updates/pending_db_world/rev_1645034279058988900.sql
-  Do not show Elder Bronzebeard gossip text after selecting the gossip option
- Closes https://github.com/chromiecraft/chromiecraft/issues/3066
See original issue: https://github.com/chromiecraft/chromiecraft/issues/3066
- Gossip now closes immediately and starts script when option is choose, with no incorrect gossip
1. .tele Theramore
2. .quest add 11133
3. Talk to guard, select dialog option …
=> fix(DB/gossip_menu_option): Fix Theramore Guards gossip

src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp
Please, let me know if this is the correct way to do a script PR, thanks!
-  Fix timing on gate breaking, combat engage and underground pathing.
- Closes #10808 
https://www.youtube.com/watch?v=00p_Ni58YGE (Also in the #10808 issue)
https://user-images.githubusercontent.com/46330494/155529534-7b83db6c-8b31-4f18-8d1e-48b738222fd0.mp4
1. .go c 137039 (Steelforged Defender, in front of FL gate)
2. .npc add 33060 (Salvaged Siege Engine)
3. Kill the 2 Ulduar Colossus (While inside the Siege Engine, can .die them) …
=> fix(Scripts/Ulduar): Flame Leviathan first time engage

data/sql/updates/pending_db_world/rev_1645312955890170800.sql
-  Add missing Horde and Neutral Quest Emotes for Desolace, Thousand Needles, and Stranglethorn
-  Values from TrinityCore PR
- Some values were already present. I only included what was missing.
- Co-authored-by: [ZenoX92](https://github.com/TrinityCore/TrinityCore/commits?author=ZenoX92)
TrinityCore: https://github.com/TrinityCore/TrinityCore/commit/345e067855b19985a387b59f851f6a6a3907aa1e
- Accepted and completed several quests in area, seems correct
1. .tele to mentioned areas
2. Test that quest emotes look correct - previously were missing
Values are accepted from Trinitycore so should be correct, but someone could check on live if not sure. They seem correct and were all default values before. …
=> fix(DB): Quest Emotes - Desolace, Thousand Needles, Stranglethorn

data/sql/updates/pending_db_world/rev_1645377551356909900.sql, src/server/game/Entities/Unit/Unit.cpp
Fixes #9475
- Closes #9475
cast nature's grasp .cast 53312 with one char
get a rogue with 2 fast daggers (1.8 and 1.4 speed)
on the rogue, cast hemmorhage (.cast 48660)
watch nature's grasp stacks and root duration on rogue …
=> fix(DB/Spells): Added internal proc cooldown to Nature's Grasp.

data/sql/base/db_auth/account.sql
-  Previously, about 10 accounts were created by default, so when they were removed, the auto incrementing option was left in the table structure.
- Closes 
- Generally, when I create a server, I have to remember to remove that option, because otherwise, the accounts start to be generated from id 11.
1. If you remove the option, the beads start from id 1. Otherwise, they start at id 11. …
=> (DB/auth) Delete auto incrementable in account

src/server/game/Entities/Player/Player.cpp
- Fix pet support after dismount for warlock
- Closes 
- Locally
1. be warlock
2. summon voidwalker or other pet
3. MOUNT UP
4. log out (hear the shard coming in inventory sound)
5. watch that you see your char having pet next to you on character screen
6. log in
7. Dismount: no pet
8. summon new pet
9. mount up
10. mount down : pet gone …
=> fix(Core/Player): fix pet support after dismount for warlock

data/sql/updates/pending_db_world/rev_1646081535601402400.sql
-  Add missing pathing to Ironforge Mountaineer GUID 225.
-  Values are from Vmangos
Vmangos
- Followed NPC, path seems correct. Previously was standing still.
1. .go creature 225
2. Observe pathing …
=> fix(DB/Pathing): Add missing pathing to Ironforge Mountaineer

data/sql/updates/pending_db_world/rev_1646088431493180100.sql
-  Add missing pathing to Hakkari Oracle outside Zul'Gurub
-  Waypoint values are from Vmangos
Vmangos
- Followed NPC, path is now looks correct
1. .go creature 733
2. Observe pathing …
=> fix(DB/Pathing): Add Missing Hakkari Oracle Pathing

data/sql/updates/pending_db_world/rev_1646088848185485200.sql
-  Adds missing pathing to Murkgill Hunter outside Kal'ai Ruins
-  Waypoint values are from Vmangos
Vmangos
- Followed NPC, confirmed path seems correct
1. .go creature 793
2. Observe pathing …
=> fix(DB/Pathing): Add Missing Murkgill Hunter pathing

data/sql/updates/pending_db_world/rev_1646089487915555800.sql
-  Adds missing pathing to several ogres in and around Mosh'Ogg Ogre Mound
-  Values are from VMangos
Vmangos
- Followed NPC, pathing is now correct and patrols path down to mound
1. .go creature 849
2. Observe correct pathing …
=> fix(DB/Pathing): Add Missing Mosh'Ogg Warmonger Pathing

src/server/game/Entities/Unit/Unit.cpp
Fixes #10802
- Closes #10802
- Closes https://github.com/chromiecraft/chromiecraft/issues/3110
1.get friendly target such as another player
2. max range another heal like flash of light(range 40yd)
3. attempt to cast holy shock at the same range …
=> fix(Core/Spells): Fixed getting max spell range for friendly targets.

data/sql/updates/pending_db_world/rev_1646433692860151400.sql
-  Set auto attack to false on smart script.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10773
1. .go c id 13996
2. Engage …
=> fix(DB/BWL): Blackwing Technicians should not auto attack

data/sql/updates/pending_db_world/rev_1646749877159440400.sql
-  Add the texts of the tables `quest_request_items_locale` and `quest_offer_reward_locale`. As well as some `ObjectiveText` from the `quest_template_locale` table that are untranslated.
- Closes
- The tests were made inside the game, executing one by one the SQL queries, which I have them in separate files, but I put them together, all in one file, to make it easier to apply and test.
- At the time of executing the queries, both separately and as a whole, none of them presented conflicts.
1. If you take missions from that area, you will notice, with the client in Spanish, many of the texts mentioned are untranslated.
2. You apply the SQL, delete the game client cache folder, and enter to test the quests. …
=> (DB/Translations) Neutral quests in Grizzly Hills

src/server/game/Globals/ObjectMgr.cpp
-  Previously, the server showed the number of lines for enUS instead of the amount of other localizations.
- Tested by starting server. Now it shows correct value of records in `broadcast_text_locale`
- 
1. Apply changes, compile and start the server. 
If something went wrong, you'll se old results:
In other case it must show correct result, something like this: …
=> fix (core/logger) Corrected count of Broadcast Text Locales shown by logger on server start

src/server/game/Events/GameEventMgr.cpp
Huge thanks to @[pklloveyou](https://github.com/pklloveyou) for the details describing the issue.
This effect any and all Smartscripts using Smart Event 68 (10 total at this time of rev) and 69 (21 total at this time of rev)
Dealing both with event 85 Stitches Event and event 87 Scarlet Oracle
-  This will correct game event 85 and maybe others
- Load order issue
- Updated correct notes in source
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/10920 as details were provided in conversation on that PR
- build
- performs
1. goto darkshire
2. .quest add 252 and turn in it
3. observe event 85 now triggers and wait for stitches to arrive from the east. …
=> fix (core): Load Order Adjustment GAME_EVENT_START hook

data/sql/updates/pending_db_world/rev_1646878467204463700.sql
-  Update positions (sniffs) and delete double spawns.
-  Added a missing smart_script to despawn one of the Vaelastrasz technicians event.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10949
1. Go to BWL
2. Kill Razorgore and start the Vaelastrasz event.
3. You should see there are only 6 technicians only and all of them should despawn if not killed.
=> fix(DB/BWL): Blackwing Technicians

src/server/game/Entities/Creature/Creature.cpp
-  Split the conditional so the creature's equipment loads correctly. This fixes some issues introduced on a previous PR with not being able to disarm some creatures.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10753
- Closes https://github.com/chromiecraft/chromiecraft/issues/3101
-  Tested in-game
1. .debug bg and go to AV
2. Try to disarm the bosses, you should be able to.
=> fix(Core/Creature): correctly load creature equipments

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp
-  Make the code more readable and fix some orthographic errors.
-  Vaelastrasz now should cast Tail Sweep.
- Closes none addressed
1. Go to Vaelastrasz and engage.
2. If you wipe or kill him, the aura of Essence of the Red should be removed from players.
3. While multiboxing, put some players behind him, you should be hit by Tail Sweep from time to time.
=> fix(Core/BWL): Vaelastrasz

data/sql/updates/pending_db_world/rev_1645520412284756500.sql
-  Add Apothecary Hummel to game_event_creature, I missed it on my last PR.
- Closes none
- Not tested
1. .tele sfk
2. Check if the apothecary is there, it should not.
3. .event start 8
4. Enter the instance again, it should be there.
=> fix(DB/Events): Apothecary Hummel should be linked to event

data/sql/updates/pending_db_world/rev_1646684893315098900.sql
-  Remove repeatable flag from The Battle for Arathi Basin.
- Thanks [Kosiak](https://github.com/Kosiak) for investigating the issue!
- Closes https://github.com/chromiecraft/chromiecraft/issues/3140
- Completed quest, can no longer be received
1. Accept one of the affected quests
2. Complete quest
3. No longer can repeat quest …
=> fix(DB/quest_template_addon): Fix The Battle for Arathi Basin

data/sql/updates/pending_db_world/rev_1646846735975559298.sql
Fixed ruRU translation of the objectives field for quest 5624 - Garments of the Light.
Taken from https://github.com/TrinityCore/TrinityCore/issues/27861 …
=> feat(db/locales): ruRU translation of the objectives field for quest 5624

src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp
-  Prevent Arlokk from being summoned twice if two players click the gong simultaneously
-  
- Closes 
- Not tested
- 
1. log two characters
2. click the gong on both of them at the same time (might be difficult to reproduce)
3.
**For …
=> fix(Scripts/ZulGurub): Prevent Arlokk from being summoned twice

src/server/game/AI/SmartScripts/SmartScript.cpp
Allow scripts to target the summoner of a TempSummon, this was removed in PR #9372 (TempSummons do not use the same path as GetCharmerOrOwnerGUID())
- Closes #10760
- Closes #10123
- Completed dungeon Pit of Saron
1. `.tele PitOfSaron`
2. Kill the first two bosses and wait for the RP section to finish
3. Start running up the hill to Tryrannus
4. 10 creatures will spawn, once killed the next set will correctly spawn as you reach the top and the dungeon can be completed
=> fix(Core/SAI): Allow scripts to target the summoner of a TempSummon

src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/Auras/SpellAuraEffects.h
Fixes #10876
- Closes #10876
- Not tested.
1.need 150 players in the Ulduar
2.there are about 4-5 25 person teams fighting Kologarn at the same time
3. look arm sweeps (spell ID 63983) damage …
=> fix(Core/Spells): Periodic ticks number should not exceed the max one.

apps/compiler/includes/functions.sh
-  add custom cmake configurations per Mac OS X fixing the dashboard setup
- Closes https://github.com/azerothcore/wiki/issues/653
- tested on mac
- run the dashboard on mac:
- ./acore.sh compiler all
- the build now should succeed and it should not give any issues about OpenSSL …
=> fix(Core/Dashboard): fix mac os configurations

data/sql/updates/pending_db_world/rev_1647993341915438725.sql
-  Set missing equipment.
- Closes #10850
Whyy0416
- Checked in game
.go creature 27607 --Burning Blade Augur
.go creature 27631 --Burning Blade Reaver
.go creature 27657 --Burning Blade Adept
.go creature 27697 --Burning Blade Felsworn
.go creature 27741 --Burning Blade Shadowmage maybe this is fine.
=> fix(DB/Creature): Update equipment for Burning Blade NPCs

src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
This fixes the client side crash for the dk starter area while flying as the EYE OF ACHERUS, apparrently if the player lacks the visual spell on his character the client would crash. This is something I just was NOT ABLE to identify in debugger, however, true story also by the way, @TheDdraig made a suggestion while being both exceedly stoned and highly intoxicate in a discord voice session that he came up with the insane nonsensible approach that actually solved the issue 100%.
Co-Authored-By: TheDdraig <62179779+TheDdraig@users.noreply.github.com>
-  Adds visual and removes visuals during the event launch case of the Eye of Acherus.
- Closes Unspecified
- Builds
- Performs
1. Do quest dk start quest https://www.wowhead.com/quest=12641/death-comes-from-on-high
2. observe no client side …
=> Fix (core) DK starter zone quest Client Crash

src/server/scripts/OutdoorPvP/OutdoorPvPTF.cpp, src/server/scripts/OutdoorPvP/OutdoorPvPTF.h
-  After all 5 towers have been captured and the 6 hour lockout has passed all towers will reset back to neutral
-  WorldState is used to reinitialize capture state incase of a core crash / shutdown (Saving once all 5 towers have been captured)
- Closes #10548
https://wowpedia.fandom.com/wiki/Spirit_Tower
- Captured all 5 towers, restarted server to observe state reinit from DB
- Waited 10 minutes and restarted to test save timer
- Manually changed timer value in WorldState DB to test case where the lockout expired while core was offline
1. `.tele TheBoneWastes`
2. Capture all 5 towers
3. Restart core (timer will start at 6:00 and all towers should still be controlled by your faction)
4. Wait 10 minutes and restart core (timer will start at 5:50 and all towers should still be controlled …
=> feat(Core/Script): Spirit towers reset to neutral 6 hours after capture and save WorldState

data/sql/updates/pending_db_world/rev_1647426130709105800.sql
-  ppmRate should be 1 instead of 3, according to the sources.
- Closes https://github.com/chromiecraft/chromiecraft/issues/2901
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10448
1. Equip 4 pieces of Shadowcraft or Darkmantle armor set.
2. Attack anything and wait for it to proc.
=> fix(DB/Spells): Rogue Armor Energize proc chance

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
-  Update the guid stored on instance for Nefarius when we start the encounter (we only need to this once tbh, but whatever).
- Closes none addressed.
1. Defeat Vaelastrasz and then go to Victor Nefarius.
2. Start the encounter and wipe with some spawns killed or kill enough adds until he spawns Nefarian.
3. The encounter should reset or you should engage Nefarian properly.
=> fix(Core/BWL): Victor Nefarius encounter not resetting properly

data/sql/updates/pending_db_world/rev_1648289846118024900.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_vaelastrasz.cpp
-  Correct gameobject data for multiple doors. (CMangos)
-  Corrected spawn timer for blackwing technicians.
-  Suppression Aura should not break stealth.
-  Corrected Fire Nova timer for Vaelastrasz fight.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3232
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11152
- Closes https://github.com/chromiecraft/chromiecraft/issues/3248
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11151
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11122
- Closes https://github.com/chromiecraft/chromiecraft/issues/3247
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11148
-  Tested in-game all of them.
=> fix(DB/Core/Misc): More adjustments to BWL

data/sql/updates/pending_db_world/rev_1648255016918528600.sql
-  Remove from Ragnaros loot, it doesn't belong there.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11129
- Closes https://github.com/chromiecraft/chromiecraft/issues/3235
- Ran the sql. No need to test really.
1. Go to Ragnaros and check the ring is not dropping anymore.
=> fix(DB/Loot): Remove wrongly added ring from Ragnaros loot

data/sql/updates/pending_db_world/rev_1648383353183302321.sql
-  Updated existing proc as this already existed in spell_proc_event however all values were set to 0 and only custom chance was showing at 2%, this way should be avoided as this table overwrites the proc values in dbc table, aka taking prio over them.
- Closes #9423
- Closes https://github.com/chromiecraft/chromiecraft/issues/2433
- Already reported and should proc on any melee hit, this should include any melee spell damage, but it only procs on auto attack as mentioned in the reported issue
- Performed
- Build
1. Do .additem 11815 and equip the trinket.
2. I suggest you update the chance to 100% purely for testing, atm its set to 2% `UPDATE `spell_proc_event` SET `CustomChance='100' WHERE `entry`='15600'; in order to check if Crusader Strike from Paladin procs it, or Windfury, Lava …
=> fix(DB/SpellProcEvent) Hand of Justice Fix

src/server/game/Entities/Player/PlayerGossip.cpp
-  Clarify what attribute it refers to, because "invalid gossip option" in the "gossip_menu_option" table can mean literaly anything
-   …
=> chore(Core/Player): clarify a gossip error about invalid OptionType

src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
Fixes #11139
- Closes #11139
- Not tested.
`.go c id 32845`
Kill Hodir
Loot both chests
`.tele gmisland`
Logout
Restart server
`.go c id 32845`
No chests anymore in the room. …
=> fix(Scripts/Ulduar): Do not spawn Hodir chests if already defeated.

src/server/game/Entities/Object/Object.cpp
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/e9992066a5ccd7f085a56de09ea027240e8da873)
Co-Authored-By: HelloKitty <5829095+HelloKitty@users.noreply.github.com>
-  Change unsafe casting in WorldObject::SetZoneScript
-  Not seen a case where it causes a crash, but better to prevent a maybe edge case than not :D
- Closes 
- None
1. When we create a Transport/Gob/CreatureFromProto we set SetZoneScript();
2. It's an edge case so there is no real test case as 99% of the times it would work with the old code.
**REMEMBER**: …
=> Core/Object: Fix WorldObject::SetZoneScript unsafe cast to InstanceMap

data/sql/updates/pending_db_world/rev_1648810356834040900.sql, src/server/scripts/Commands/cs_misc.cpp
-  Add a subcommand to respawn command to behave like it does without target right now. Since this command is kinda dangerous, this would prevent respawning the whole grid by mistake.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11209
1. Find a creature, kill it and try to respawn it without targeting it.
2. Try targeting and .respawn
3. Without targeting, .respawn all
4. Change the security of the command on DB and try again.
=>  feat(Core/Command): Split respawn command

data/sql/updates/pending_db_world/rev_1648906248199850600.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_razorgore.cpp
Fixes #11180
- Closes #11180
- Not tested.
Hide a player with a columns or an other gameobject
Kill razorgore during the P1/P2 …
=> fix(Core/Spells): Razorgore's Explosion ignores LoS.

data/sql/updates/pending_db_world/rev_1649325436095486698
-  Set not interruptable flag for razorgore
-  
- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/11312
- not tested
- 
1. go to razorgore fight and get to p2, check if you can interrupt fireball volley
2.
3. …
=> fix(DB/Creature): Razorgore should not be interruptable. 

data/sql/updates/pending_db_world/rev_1648521257247923500.sql
Fixes issue of Stitches running back to its waypoint start
- It appears there were a few changes to Azerothcore that modified elements to this event since it was created.
- It also appears that the Smart Script OOC no repeat seems to repeat anyway under specific circumstances.  Fixed this.
- Updated Watcher Cutford's waypoints to be more resilliant to his feet being under the floor as he runs.
- Updated the event spawned watchers (Corwin and Sarys) from respawning during the event after they have been killed. 
- Issue #6685 talked about Watcher Ladimore and Commander Althea Ebonlocke attacking Stitches.  This was dicussed in length on the original PR but was abandoned due to a few youtube sources (one in source section) and the idea that Blizzard had an issue with killing quest hub NPCs. …
=> fix(DB): Stitches Event Fix

data/sql/updates/pending_db_world/rev_1649126786433718200.sql
-  Corrected Warlock summon portal timers, it was kinda low.
-  Added smart scripts for the portals and Enraged Felguards.
-  Despawn the portals if the warlock evades.
-  Blackwing technicians respawn timer has been lowered again to 30s, but this time their respawn is linked to each warlock near the pack. This allows them to respawn and for the players, farm elementium.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11256
1. Go to blackwing lair and check the changes made.
=> fix(DB/BWL): Blackwing Warlocks

data/sql/updates/pending_db_world/rev_1643928221060796100.sql
-  Corrects Gossip text for NPC Gorbold Steelhand (NPC 6301). His current text is from Cataclysm expansion.
- Correct WotLK text was already in DB, so just need to be set correctly.
Original WotLK leveling video:
https://youtu.be/P8cXHJcb50o?t=2m19s
1. .go creature 37980
2. See gossip text is now correct …
=> fix(DB): Gorbold Steelhand incorrectly has Cataclysm Gossip Text

src/server/game/Handlers/BattleGroundHandler.cpp
-  
-  
- Closes 
- Locally
1. Press the queue button twice with the group
=> fix(Core/BattlegroundQueue): disable double queue in one bg

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
-  Set the timer to 15s as it should be.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11292
- Closes https://github.com/chromiecraft/chromiecraft/issues/3293
- Not tested.
1. Go to Razorgore and engage.
2. Check the spawn timer, it should be exactly 15s.
=> fix(Core/BWL): Razorgore spawns timer

data/sql/updates/pending_db_world/rev_1649181854899342300.sql, src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/utgarde_pinnacle.cpp, src/server/scripts/Northrend/northrend_script_loader.cpp
* chery-pick commit (https://github.com/TrinityCore/TrinityCore/commit/f6409efcf664a21d43243f8d2048025014c76afb)
Co-Authored-By: Lucas Nascimento <keader.android@gmail.com>
-  Cast damage spell each time that Beast's Mark proc, if attacker is a beast.
- Closes 
- none
- 
1. Go to utgarde pinnacle
2. let Ymirjar Savage cast Beast's Mark on a beast …
=> fix(Scripts/UtgardPinnacle): Implement Beast's Mark

data/sql/updates/pending_db_world/rev_1649660925472546752.sql
-  Updated interrupt mask
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3323
Nowhere is stated that you can interrupt it, no videos show that they interrupt it:
https://youtu.be/MyH-OWhjxW4?t=514
-  Tested
- 
1. Go to vael bwl
2. try to interrupt his breath
3. …
=> Fix(DB/Creature): Vaelastrasz should be immune to interrupts

data/sql/updates/pending_db_world/rev_1649663437340205577.sql
-  Change immunity mask to include disarm
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3324
https://www.youtube.com/watch?v=MyH-OWhjxW4&t=514s
Generally no boss can be disarmed in raids, no guide mentions this boss can be disarmed, this warrior above does not use disarm on boss and is a sweaty guild.
- Tested
- 
1. Go to broodlord lashlayer (BWL boss 2) and try to disarm him.
2.
3. …
=> Fix(DB/Creature): Broodlord Lashlayer should not be disarmable

src/server/game/Entities/Player/PlayerUpdates.cpp
Corrected synthax of HasUnitFlag usage
=> fix(Core/Synthax): corrected HasUnitFlag usage

data/sql/updates/pending_db_world/rev_1649370784577886400.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
-  Nefarian spawns from third phase should now spawn on their death's position.
-  Removed Shadowbolt Volley changes from a previous PR of mine, it seems its behavior was correct after all.
-  Rogue class call should not be removed by using Vanish.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11299
1. Go to BWL and engage Nefarian with a Rogue.
2. Check skeletons position and Nefarius volley.
3. Try to vanish rogue call.
=> fix(Core/BWL): Nefarian spawns

data/sql/updates/pending_db_world/rev_1649799370491572700.sql, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp
-  Add the script for the areatrigger used for death players.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11377
1. Die in BWL and release.
2. Go near the Orb of Command.
3. You should be tped to BWL again.
=> fix(Core/BWL): Orb of Command areatrigger

data/sql/updates/pending_db_world/rev_1649093998908343415.sql
-  Adjust z axis of harpy npc to be above ground and not under which leads it to death
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11282
- Closes https://github.com/chromiecraft/chromiecraft/issues/3292
- Builds
- Performs
1. .go c 51729
2. observe npc is no longer undermeshing …
=> fix (db) Harpy Z Axis fix

src/server/game/Maps/Map.cpp
-  Fixes correct caluations for Shallow water
- Shallow water calculation (in water and water walking value) is not correct and were matching each other. not right at all. this corrects the issue.
- Closes 
- builds
- performs
1.
2.
3.
**For …
=> fix (core): Shallow Water Calulation Correction

src/server/authserver/Server/AuthSession.cpp
- Closes #11388 
[Pick up from TC](https://github.com/TrinityCore/TrinityCore/commit/4ec52fb160c9bd5ab43a305756e4e4066c857994)
Co-Authored-By: Shauren <[shauren.trinity@gmail.com](mailto:shauren.trinity@gmail.com)>
- Need to test
1.
2.
3. …
=> Core/Authserver: Fix uninitialized variable, fixes changing realms aFter logging in to world

src/server/game/Entities/Creature/Creature.cpp
- Since the mysterous why things evade in shallow water root issue was finally determined because of our shallow water calculations was wrong that was corrected by pr https://github.com/azerothcore/azerothcore-wotlk/pull/11419 we can now remove this operator which was a hack fix from PR https://github.com/azerothcore/azerothcore-wotlk/pull/10147.
- Closes 
- Builds
- Performs
1. aggro any creature into shallow water ( water you can walk and run in but not float\swim)
2. creatures should enter the water with no issues now. …
=> fix (core) Remove not need CanSwim operator

data/sql/updates/pending_db_world/rev_1648562925756409969.sql
update 12718 locale frFR entry in quest_request_items_locale table
This translation currently has a NULL value.
It is found within the suggestion that I made a trip PR #10888, which was closed and was to remove all NULL results with translation errors
=> feat(DB/Locale): Update 12718 "frFR"

data/sql/updates/pending_db_world/rev_1649549626279664100.sql
-  Proper gossip text for Farmer Furlbrow & Gryan Stoutmantle
- Closes #11307 
- Closes [#3263](https://github.com/chromiecraft/chromiecraft/issues/3263)
https://wowpedia.fandom.com/wiki/Farmer_Furlbrow
https://wowpedia.fandom.com/wiki/Gryan_Stoutmantle
- Checked gossips is correct
1. `.go c id 237`,  `.go c id 234`
2. Right click NPC and confirm Welcome gossip is correct. …
=> fix(DB/gossip_menu): wrong TextId for NPC's

src/server/scripts/Kalimdor/boss_azuregos.cpp
Fixes Issue https://github.com/azerothcore/azerothcore-wotlk/issues/11343
Changes Proposed:
- Removes removal of mark of frost debuff on Death
- Applies Mark of Frost to last player alive
Issues Addressed:
Closes
- Issue 11343
SOURCE:
Tests Performed:
- Tested in Small raid
- Wiped team
- Debuff persists
- Debuff applied to last player alive
How to Test the Changes:
1. In a group go to Azuregos
2. .go creature 52349
3. Wipe on Azuregos
4. Mark of Frost on Last Player to die?
5. Mark of Frost persist through death?
6. Joy
Known Issues and TODO List:
[ ]
[ ]
How to Test AzerothCore PRs
When a PR is ready to be tested, it will be marked as [WAITING TO BE TESTED]. …
=> Azuregos' Mark of Frost debuff should persist through wipe and reset

src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_ebonroc.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_firemaw.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_flamegor.cpp
-  Changes initial shadowflame timer to 18 seconds for Flamegor, Ebonroc and Firemaw.
-  Changes in combat shadowflame timer to between 15 and 25 seconds for Flamegor, Ebonroc and Firemaw
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3364
- closes https://github.com/chromiecraft/chromiecraft/issues/3365
- closes https://github.com/chromiecraft/chromiecraft/issues/3366
See issues above for video evidence and warcraft logs, it never happened withitn 10-15 seconds and it can happen up to 24 seconds during combat. It also always happened 18 seconds into combat. 
-  Tested
- 
1. Go to ebonroc, flamegor or firemaw and check if the first shadowflame is at 18 seconds.
2. Check if follow up cast is between 15 and 25 seconds
3. …
=> Fix (Script/BWL): Fix initial shadowflame timers

data/sql/updates/pending_db_world/rev_1650555787208782000.sql, src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/6785
-  This spell doesn't have a trigger spell
-  * cherry-pick part of commit (https://github.com/TrinityCore/TrinityCore/commit/5b8e68ee6335ecbc9fea253eaceecb20c50aa41e)
- Closes 
- 
- 
1.
2.
3. …
=> fix(Scripts/ICC): Change trigger flag for Battle Ecperience spell

src/server/game/Entities/Creature/Creature.cpp
-  
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11474
- Closes https://github.com/chromiecraft/chromiecraft/issues/3388
- 
- 
1.
2.
3. …
=> fix (core): inhabit CanSwim revert

data/sql/updates/pending_db_world/rev_1650360263328185762.sql
Fix the double gate at the entrance of Zul'Gurub - issue(https://github.com/azerothcore/azerothcore-wotlk/issues/11350)
-  Move one of two gates at the entrance of Zul'Gurub
- Closes #11350
- Tested IG
1. .tele zulgurub …
=> fix(DB/Gameobject): Zul'Gurub - Fix Entrance Gate

deps/g3dlite/include/G3D/Vector3.h, src/cmake/compiler/clang/settings.cmake
* cherry-pick commit (WarheadCore/WarheadBand@0eeff42)
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/10164
Co-Authored-By: Kargatum <dowlandtop@yandex.com>
-  
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(Clang/CMake): fix compile with PCH 21.10

data/sql/updates/pending_db_world/rev_1650378083515345987.sql
-  Change drop rate from Shaft of Tsol to 100 
- Closes #11376 
- Closes https://github.com/chromiecraft/chromiecraft/issues/3336
Not tested
- Kill Revelosh in Uldaman (id: 6910)
- Item should always loot …
=> fix(DB/Creature] Fix drop rate of Shaft of Tsol

data/sql/updates/pending_db_world/rev_1649705878401365511.sql
-  Add esES translation
-  Add esMX translation
- Closes #11371
- Closes https://github.com/chromiecraft/chromiecraft/issues/3333
esES/esMX language pack
- Tested
- Apply changes, run server, Use esES/esMX WoW client, create Shaman
- Summon Totem of Wrath ll and Totem of Wrathlll, those will be displayed as they should …
=> fix(DB/creature_template_locale): Spanish totem translation

data/sql/updates/pending_db_world/rev_1650071065104177600.sql
-  Add esES/esMX translation for [Wand of Allistarj](https://classic.wowhead.com/item=13065/wand-of-allistarj)
- Closes #11411
- Closes https://github.com/chromiecraft/chromiecraft/issues/3357
https://es.classic.wowhead.com/item=13065/varita-de-allistarj …
=> fix(DB/item_template_locale): Add Spanish translation for 'Wand of Allistarj'

src/server/game/Entities/Pet/Pet.cpp
Fixes #11481
- Closes #11481
- Closes https://github.com/chromiecraft/chromiecraft/issues/3390
be a hunter
`.go creature id 15649`
tame the dragonhawk
Learn pet talent Cornered (rank 2)
relog
`.list auras` on your pet to see if `Cornered` aura is active …
=> fix(Core/Pets): Handle health-aurastates on pet loading.

src/server/game/Entities/Player/Player.cpp
- fix null crash when RemovePet() is trying to save in DB
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/11331
- none
Still unknown how to reproduce the crash …
=> fix(Core/Player): null crash in RemovePet()

data/sql/updates/pending_db_world/rev_1650744666752700000.sql, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Spells/SpellInfoCorrections.cpp
Brood Power bronze affects only one target.
Death Talon Wyrmguard gain the Brood Power aura only once per lifetime.
Fixes #11448
- Closes #11448
- Not tested.
go to bwl with a few chars
aggro death talon wyrmguard packs till you get bronze one
watch as your whole raid dances around …
=> fix(Scripts/Spells): Improvements to Brood Power: Bronze:

data/sql/updates/pending_db_world/rev_1649654147658907782.sql
source TC: https://github.com/TrinityCore/TrinityCore/issues/24162
Description:
We have an incorrect locale name/description of the items:
Formula: Enchant Cloak - Titanweave ID 37347
Formula: Enchant Cloak - Shadow Armor ID 37349
https://wowwiki.fandom.com/wiki/Enchant_Cloak_-_Titanweave
https://wowwiki.fandom.com/wiki/Enchant_Cloak_-_Shadow_Armor
=> fix(DB/Locale): Formula esMX-SP, FR ID 37347-37349

src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/Creature.h
-  Implement a function to change threat temporarily, autoreseting after a brief amount of time
-  
- Closes 
- 
1. Its for modules, no places uses it ingame, it doesn't crash the server 👍 
2.
3. …
=> feat(Core/Creature): Implement ModifyThreatPercentTemp() function

src/server/game/Spells/SpellInfoCorrections.cpp
Rapture should not generate threat.
Fixes #11396
- Closes #11396
- Closes https://github.com/chromiecraft/chromiecraft/issues/3346
- Not tested.
Cast a rank one Power Word: Shield (ID: 17) on another player character
Use the other character to initiate combat with a creature strong enough to break the shield
Upon the shield breaking and Rapture proccing, watch that the priest does not enter combat/generate threat
Or, if LoS is broken, observe that the other character does regenerate resources and the priest does not enter combat
**REMEMBER**: …
=> fix(Core/Spells): Rapture should ignore line of sight.

data/sql/updates/pending_db_world/rev_1650790172951548882.sql
-  Set loot condition on unfired plate gauntlets to blacksmithing 225
-  Removed quest requirement.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11472
- Closes https://github.com/chromiecraft/chromiecraft/issues/2343
- Tested
.go LBRS
loot the object Unfired Plate Gauntlets, and see it empty.
.setskill 164 225
.respawn all
loot it again and find the item inside …
=> Fix(DB): Unfired Plate Gauntlets should only require blacksmithing 225 to loot.

data/sql/updates/pending_db_world/rev_1650555535836713900.sql, src/server/game/Battlefield/Zones/BattlefieldWG.cpp, src/server/game/Battlefield/Zones/BattlefieldWG.h, src/server/game/Entities/Player/PlayerQuest.cpp, src/server/scripts/Northrend/zone_wintergrasp.cpp
-  Added player loot for quest items
-  Give player kill credit to all in range (same as vehicle kills)
- Added vendor check to WG CreatureScript
- Added WG control check in GetDialogStatus to resolve inconsistency between quest available icon and actually available quests
- TODO of #9198
https://wowwiki-archive.fandom.com/wiki/Wintergrasp_quests
- Completed all Wintergrasp quests to test drops / kill credit
- Win 10 x64 / Ubuntu 20.04 x64
Effected quests:
```
Victory in Wintergrasp - 13181
No Mercy for the Merciless - 13179, 13177
Defend the Siege - 13222
Stop the Siege - 13186
A Rare Herb - 13156, 13195
Bones and Arrows - 13196, 13154
Fueling the Demolishers - 236, 13197
Warding the Warriors - 13153, 13198
Southern Sabotage - 13538
Victory in Wintergrasp - 13183
Defend the Siege - 13223 …
```
=> fix(Core/Wintergrasp): Reimplement Wintergrasp quests and fix vendors

data/sql/updates/pending_db_world/rev_1650789793340379741.sql
-  sets bonereavers edge proc to 2 pm
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11482
- Closes https://github.com/chromiecraft/chromiecraft/issues/3282
See issues addressed
- Not tested
- 
1. .additem 17076
2. Verify that the weapon now procs 2 times per minute. …
=> Fix(DB/Item) Bonereaver's Edge proc should be 2 ppm.

src/server/game/Entities/Player/Player.cpp
Fixes #11332
- Closes #11332
- Closes https://github.com/chromiecraft/chromiecraft/issues/3114
- Not tested.
Queue a Battleground on PTR or on Live.
Try to have a debuff/damaging dot on you when BG ends
Exit Battleground and check if you have a dot or a debuff on yourself. …
=> fix(Core/Battlegrounds): Remove all DoTs when exiting battleground.

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp
-  Correct Sartura's enrage spell ids from sniffs
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(Scripts/TempleOfAhnQiraj): Correct Battleguard Sartura spell ids

data/sql/updates/pending_db_world/rev_1650793025980507979.sql
-  Changes faction flag to be the same as the other creatures around him.
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3403
- Not tested
- 
1. Go to Coldtooth mine in AV and see if Aggi has no longer the Alliance Pvp symbol on his name and can be properly killed.
2.
3. …
=> Fix(DB/Creature): Set correct faction flag for Aggi Rumplestomp.

data/sql/updates/pending_db_world/rev_1651687148755567176.sql
-  Fix bad and missing scripts for NPCs at Falconwing Square in Eversong Woods.
Sniffs
- Inserts without errors.
- Tested scripts in game.
1. .go c 58691
2. Observe Novice Ranger, Wretched Captive, Sergeant Kan'ren, Sleyin, and Kyrenna,
=> Fix(DB/SAI): Falconwing Square scripted NPCs

data/sql/updates/pending_db_world/rev_1651708009830546980.sql
-  Gender check in text eg. $glad:lass; has the semi colon replaced with a comma in AZ db thus not working properly.
-  Updated 6 incorrect text in quest_greeting by replacing comma with semi colon.
- Closes #3383 
- #11453
TC with help from @acidmanifesto 
- tested in game on two of the 6 repaired
1. .go c 1398
2. open gossip
=> Fix(DB/quest_greeting) gender check

src/server/scripts/Kalimdor/zone_silithus.cpp
-  fix the script "npc_anachronos_the_ancient" which will hung up the server.
-  fix some logic errors in script "npc_anachronos_the_ancient".
- Closes 
- build without errors 
- no server hung up/crash
- quest "A Pawn on the Eternal Board" can finished.
1. accept the quest "A Pawn on the Eternal Board". (quest id: 8519)
2. view the quest animation.
3. confirm there is no server hung up/crash and the quest can finished. …
=> fix(CORE/Script): Quest "A Pawn on the Eternal Board" can't finish and hung up the worldserver.exe

src/server/scripts/Commands/cs_misc.cpp
- Removed the else on the SEC_PLAYER check, this shouldn't be there and silently stops the removal of items on player accounts
- Removed an item from an account with SEC_PLAYER (0) security
- Removed an item from an account with SEC_ADMINISTRATOR (3) security
1. Create two accounts, one with GM permissions and one without.
2. Add an item to both characters eg. `.addit 17 1`
3. Remove the item from both characters eg. `.addit 17 -1`
4. The item should be successfully removed from both characters …
=> fix(Core/Commands): Fix removing item from player account

data/sql/updates/pending_db_world/rev_1651874393098969660.sql
- Rooted is set in creature_template_movement so the SAI to set rooted on spawn was useless.
- Since the rooted was being removed on player exit I changed SAI to root gun on player exit.
- Closes #11643
Me
- Inserts
- Tested in game. Gun remains rooted.
1. .go xyz 7354.860352 -80.268097 777.624817 571
2. .quest a 12953
3. mount a Valkyrion Harpoon Gun
4. use the ADWS of the keyboard to move it
=> Fix (DB/SAI) Valkyrion Harpoon Gun

data/sql/updates/db_world/2022_05_04_01.sql, src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp
-  Added Grauf's deep breath emote
-  Renamed SPELL_FLAME references to properly reflect correct spell name FREEZING_CLOUD
- https://github.com/azerothcore/azerothcore-wotlk/issues/6741
- https://github.com/azerothcore/azerothcore-wotlk/issues/4153
- Tesed in-game
- OS: Win10
1. Teleport to Skadi the Ruthless in Utgarde Pinnacle
2. Start the encounter
3. Move to the harpoons
4. Wait for his breath …
=> Fix issue skadi the ruthless emote

data/sql/updates/pending_db_world/rev_1651916297606648500.sql
Fixes #11634
- Closes #11634
- Not tested.
`.quest a 12915`
`.quest a 12922`
`.quest c 12922`
`.go xyz 7217.320312 -3636.736084 824.563965 571`
Return the quest
`.go xyz 7306.065918 -3160.722412 837.451050 571`
you still can see the target monster of the Mending Fences (quest id 12915) …
=> fix(DB/Spells): Fixed phasing after quest "A Spark of Hope".

data/sql/updates/pending_db_world/rev_1651742335531289900.sql
-  Set MC exit teleport location to in front of Lothos Riftwalker
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10028
- OS: Win10
1. Teleport inside Molten Core
2. Run through raid instance teleporter inside Molten Core to exit the instance
- None …
=> Set molten core exit teleport location to in front of Lothos Riftwalker

data/sql/updates/pending_db_world/rev_1651987971178548000.sql
Added gossip_menu entries linking to existing npc_text.
- Closes #8571
- Closes chromiecraft/chromiecraft/issues/2120
.npc add 16112
Talk and ask about Dreadnaught armor …
=> fix(DB/Gossip): Korfax missing text

src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp
Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 Going trough the entirety of Ulduar
creature_text for Freya is already populated in the DB 
-  Added the following missing emotes:
- *EMOTE_ALLIES_OF_NATURE
- *EMOTE_LIFEBINDERS_GIFT
- *EMOTE_GROUND_TREMOR
- *EMOTE_IRON_ROOTS
- Alive Elders no longer talk if starting Freya hardmode.
- Fixed Freya instantly despawning after being defeated.
- Completing hardmode now despawn any alive Elders, instead of killing them. (This also fixes elders talking as if they've killed someone, themselves in that case, when killed by the previous code, `UNIT::Kill`)
- Closes none
[YT](https://www.youtube.com/results?search_query=freya+wow)
- Tested in-game with sound
1. .go c 136554
2. Interact with the Elders (kill/leave alive).
3. Pull …
=> fix(Core/Creature): Move hardcoded text/gossips to DB and minor fixes - boss_freya

src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp
Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 but xt was not on the list. (Going trough entirety of ulduar)
All of the creature_text is already in DB
However, SAY_SUMMON is not linked with BroadcastTextId and I cannot find any video source of it actually being used. (Except TC boss script, but still, no actual proof)
-  
-  
- Closes none
- Tested in-game with sound
- 
1. .go c 136054
2. Pull (with sound enabled)
3. …
=> fix(Core/Creature): Move hardcoded text/gossips to DB - boss_xt002

src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp
Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 Going trough the entirety of Ulduar
All of the creature_text is already in DB
-  Added the missing (wasn't being used before) SAY_SUMMON, source TC & [YT](https://www.youtube.com/watch?v=PYlfUoY9I3Y)
- Closes #4156
- Tested in-game with sound
1. .go c 136371
2. Pull (with sound enabled) …
=> fix(Core/Creature): Move hardcoded text/gossips to DB - boss_ignis

data/sql/updates/pending_db_world/rev_1651872810987186100.sql, src/server/scripts/Northrend/Ulduar/Ulduar/boss_auriaya.cpp
Part of https://github.com/azerothcore/azerothcore-wotlk/projects/15 Going trough the entirety of Ulduar
Please read TODO
-  SQL had a duplicate and was missing EMOTE_DEATH
Previous SQL state:
- Closes none
Source for the scream sound ID is from TC/the script itself/YT
- Tested in-game with sound
1. .go c 137496
2. Pull (with sound enabled)
Do we leave it at 0 or do we script it (revert it back to TextEmote hardscript + play sound)? Should it be sniffed (if possible), or it's simply there, in the BroadcastTextId table, but I failed to find it? Thanks. …
=> fix(Core/Creature): Move hardcoded text/gossips to DB - boss_auriaya

src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp
- Replace DoAction despawn with a DespawnOrUnsummon, as suggested by [Nyeriah ](https://github.com/azerothcore/azerothcore-wotlk/pull/11665/files/0645d71663877358c63e260bc6025f103a78d79b#diff-e8088b0bc012a572df7e19441fb0eb78ac22aa61901caa45c1dfc2d1269daa8aR340)
- Closes none
Source that elders should despawn and are not being killed after the fight is over. (unchanged behaviour here, just the method used to despawn them)
Freya has the 3 elder buffs in both videos
[video 1](https://youtu.be/C-SX1MCm2rc?t=601) - The player is facing the same direction where one of the elders should be, but he has despawned as the fight has come to an end.
[video 2 during the fight](https://youtu.be/IdRUDiXcM7o?t=412) - from a similar angle, showing that the elder is there, stunned during the fight …
=> fix(Script/Freya): Change the way Elders are despawned

src/server/game/Entities/Player/PlayerUpdates.cpp
TC CHERRY PICK
This addresses a rarity issue that at times I have seen but never really thought much of.
This issue can cause GameObjects to render incorrectly on the client. 
Original PR that is closed on tc that readdress the issue with further conversation:
https://github.com/TrinityCore/TrinityCore/pull/27914
Original TC issues is here: 
https://github.com/TrinityCore/TrinityCore/issues/24846
https://github.com/TrinityCore/TrinityCore/issues/20401
TC Cherry Pick: https://github.com/TrinityCore/TrinityCore/commit/38dc5667ba13d5c1d094330b0f57ba0ee9b2dde5
Co-Authored-By: Shauren <shauren.trinity@gmail.com>
Co-Authored-By: Jurgis <326232+chemicstry@users.noreply.github.com>
-  Prevent Forced UpdateObjectVisibility Before in World
- Closes 
- Builds
- Performs
1.
2.
3. …
=> fix (core): Prevent Forced UpdateObjectVisibility Before in World

src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp
=> fix(Core): Crashfix.

data/sql/updates/pending_db_world/rev_1652793617224967000.sql
- Created missing gossip menus for npc and changed his flags to allow
gossips.
- Conditions for when player has either bindings or is on quest 7786
- Closes #11774 
1. Reproduce the steps on the linked issue.
None
**For …
=> fix(DB): Earthcaller gossips

data/sql/updates/pending_db_world/rev_1652601366513566300.sql
Fixes #10780
- Closes #10780
- Closes https://github.com/chromiecraft/chromiecraft/issues/2960
Get Elemental Focus Talent
Land a Critical Strike from spell
Use melee/ use no-mana spell / get hit with lightning/water shield
No stack of Clearcasting is consumed …
=> fix(DB/Spells): Fixed Shaman's Clearcasting proc.

data/sql/updates/pending_db_world/rev_1652731923594016000.sql
formation table was empty for every single GUID in the sql
-  Linked both sides each, as the right side was also not pulling a mob
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8008
https://youtu.be/2GxM9F192MA?t=214 cata
https://www.youtube.com/watch?v=NuFeZPXZuG0 classic
1. .go xyz 358 -133 -65 230 3.3
2. Pull left from distance, all should come
3. Pull right from distance, all should come …
=> fix(DB/Creature): BRD Detention Block - Link mobs in group pack

src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
-  Spawn the skeletons in the pit instead of next to player location
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11559
- Tested
- 
1. Go to Jin'ko
2. Get teleported
3. Skeletons spawn in pit. …
=> Fix(Script/ZulGurub): Skeletons should appear in pit

src/server/game/Entities/Unit/Unit.cpp
Fixes #10343
- Closes #10343
- Closes https://github.com/chromiecraft/chromiecraft/issues/2847
. go creature id 2344
mind control them
you'll notice the mind controlled creature stopped moving and you can control it
**For …
=> fix(Core/Units): Clear any movement on charm.

data/sql/updates/pending_db_world/rev_1653383651000084300.sql
Fix by @pklloveyou 
**Other LnL interactions are unaffected**
-  Set procPhase to 0 (previously was 4)
- https://github.com/azerothcore/azerothcore-wotlk/issues/10919
- https://github.com/azerothcore/azerothcore-wotlk/issues/11363
1. Make a hunter
2. Learn the following talents, Lock and Load(3/3) & Black Arrow
3. Cast Black Arrow 
4. Wait for LnL proc …
=> fix(DB/Spell): Set Lock and Load procPhase to 0, allowing Black Arrow to proc it.

data/sql/updates/pending_db_world/rev_1653350504760491620.sql, data/sql/updates/pending_db_world/update.sql
Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)
-  Change text range
-  Change text to blizzlike
- Closes #11751
https://wowpedia.fandom.com/wiki/Jin%27do_the_Hexxer#Quotes
- None
1. Go ZG
2. ENgage encounter
3. Let Broodlord kill you for him to level up and Jindo should say GRATS! which should be visible to youin chat …
=> fix(DB/creature_text): Jin'do the Hexxer's RP - GRATS!

data/sql/updates/pending_db_world/rev_1653824974575032300.sql, src/server/scripts/EasternKingdoms/ZulGurub/boss_gahzranka.cpp
Fixes #11563
- Closes #11563
`.additem 19975 5`
`.additem 19974`
`.go xyz -11695 -1770 13 309` Teleports to Pagle's Pointe
Engage Gahz'ranka
Observe the combat log once the Massive Geyser is summoned …
=> fix(Scripts/ZulGurub): Massive Geyser should not attack players.

src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
Fixed #11556
- Closes #11556
- Not tested.
Go to ZG - Jin'do with 2 chars
get hexed
notice second target is now the primary target …
=> fix(Scripts/ZulGurub): Jindo cannot attack targets affected by Hex.

data/sql/updates/pending_db_world/rev_1654407708502994800.sql, src/server/scripts/EasternKingdoms/ZulGurub/boss_grilek.cpp
Corrected timers of events.
Avatar should wipe all threat for the entire raid.
Boss is immuned to taunt.
Added missing spells.
Fixes #11611
- Closes #11611
- Not tested.
If the Summoning Event is implemented:
`.event stop 28`
`.event stop 29`
`.event stop 30`
`.event start 27`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Gri'lek
else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15082` …
=> fix(Scripts/ZulGurub): Improvements to Gri'lek encounter:

src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
Fixed #11763
- Closes #11763
- Not tested.
Fight with Jindo and wait until Healing Totem is dropped and see if it's healing the boss. …
=> fix(Scripts/ZulGurub): Fixed Jindo's Healing Ward Totem.

src/server/scripts/Kalimdor/zone_silithus.cpp
-  those functions already return a boolean value, it is not needed to use the ternary operator
=> refactor: remove useless ternary operator

data/sql/updates/pending_db_world/morrowgrainherbs.sql
-  Remove random herbs, add mutated morrowgrain herbs
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3543
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11882
- tested
.additem 11024
View loot in it
**For …
=> Fix(DB/Loot): Evergreen Herb Casing should not drop random herbs

data/sql/updates/pending_db_world/rev_1652973605826504900.sql, src/server/scripts/Northrend/zone_dragonblight.cpp
All of the creature text tables are correctly populated for both npcs (Future & Past)
- [SQL] Removed the unused SAI from Future You
- Added couple of the missing lines (Source)
- Added IsFlying check to the NPCS in attempt to stop them from attacking the unattackable drakes in the area) STILL HAPPENS ON TIME TO TIME IDK, probably needs some more checks
- Added Nozdormu appearing for a brief period at the end of the roleplay
- Completes moving zone_dragonblight entirely to DB (Unless I've missed something) 🤔 
https://wowpedia.fandom.com/wiki/Mystery_of_the_Infinite
https://wowpedia.fandom.com/wiki/Mystery_of_the_Infinite,_Redux
https://www.wowhead.com/quest=13343/mystery-of-the-infinite-redux#comments:id=456274:reply=59375 (3.x.x)
And any video of the quest for Nozdormu appearing …
=> fix(Script/Quest): Mystery of the Infinite minor adjustments & zone_dragonblight move to db from hardcode

src/cmake/googletest-download.cmake
related of https://github.com/azerothcore/azerothcore-wotlk/pull/11902
-  restore the googletest repo reference
- related of https://github.com/google/googletest/pull/3859
- https://github.com/google/googletest/issues/3858
=> chore: restore googletest main repo reference

src/server/game/Entities/Player/Player.cpp, src/server/scripts/Commands/cs_deserter.cpp
- Battleground deserter now only overrides a deserter debuff if it has a shorter time remaining
- The deserter add command now only overrides a deserter debuff if it has a shorter time remaining
- The deserter add command no longer errors if the player already has a deserter debuff
- Closes #11955
- Closes #11914
- Deserter added multiple times on offline players
- Added deserter with 5 min and 30min to a player in a battleground and left
1. Use the `.deserter add bg` command to add a deserter debuff to a player in a battleground
2. Leave the battleground with that player
3. Check the deserter debuff duration
4. Use the `.deserter add bg` on that player again with different values with the player being online and offline
5. Observe the outcome times …
=> fix(Core): Deserter overrides from BG and Command

data/sql/updates/pending_db_world/rev_1653810747543320600.sql
-  Update drop rate to 72 % (based with test  on retail. Look below)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11875
Drop rate confirm also with https://wotlkdb.com/?item=6634
- None
1.Create a Tauren Shaman
2. Start Call of Earth questline from [Seer Ravenfeather](https://classic.wowhead.com/npc=5888/seer-ravenfeather)
3. See you are having difficulties gathering 2 Salves after more than 5 Shamans killed. …
=> fix(DB/Creature_loot): Increase drop rate of Ritual Salve

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h
Fixes #12018
- Closes #12018
- Closes https://github.com/chromiecraft/chromiecraft/issues/3601
Cast [Mind Control] (ID: 605) on enemy player.
Toggle Walk (using numpad [ / ] by default).
Cancel [Mind Control].
Enemy player has walk toggled off. …
=> fix(Core/Units): Fixed restoring running movement flag after charm. Source: TrinityCore

data/sql/updates/pending_db_world/kroshius.sql
- Remove untargetable flag
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12042
- Closes https://github.com/chromiecraft/chromiecraft/issues/3611
- Tested
.character level 51
.quest add 7603
.go c 39715
.gm off
/tar Kroshius and try to click on it …
=> Fix(DB/Creature): Kroshius should be targetable.

data/sql/updates/pending_db_world/callofwater.sql
-  Increases the range that water elementals check for tel'athion, so they help in combat
-  Set proper flags on tel'athion smartai abilities, so he does not just instant cast them.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7139
- Closes https://github.com/chromiecraft/chromiecraft/issues/810
- Tested
1. be draenei, 20, shaman
2. .q add 9508
3. .tele bloodmyst isle and go to location of map
4. summon tel'athion.
5. Kill him/ evade, water elemetnals despawn
6. during combat, abilities have cast time. …
=> Fix(DB/smartscripts): Call of Water(5/6)(draenei) improvements

data/sql/updates/pending_db_world/shadowweaver.sql
-  Removed smartai script that told him to stay at range
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6155
- Closes https://github.com/chromiecraft/chromiecraft/issues/748
- 
- tested
1. .tele fenris
2. aggro a rot hide plague weaver and see that he will come towards you. …
=> Fix(DB/Smartscripts): Rot Hide Plague Weavers incorrectly stay at range

data/sql/updates/pending_db_world/axethrower.sql
-  fixed target
- tested
- 
1. .tele zg
2. engage axethrower, wait for him to cast axe flurry
3. profit …
=> fix(DB/smartscripts): Gurubashi Axe Thrower should cast Axe Flurry

data/sql/updates/pending_db_world/rev_1655244193594772800.sql
Quest drops properly drop individual stacks in loot window.
What's left of #12007 that isn't fixed by #12024 (Extra Notes section)
-  Makes the loot appear as it should (unstacked drops).  
- Closes 
TBC Classic / packet sniff
- Tested as explained below, works as expected.
1.  .quest add 1701
2.  .tele to wetlands and goto spider cave, get a few drops
3.  .tele charred (vale) and kill a few chimaeras  …
=> (DB/loot): Addressed drop style to be proper for Fire Hardened Mail

data/sql/updates/pending_db_world/nightmareillusion.sql
-  set immune to aoe flag
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12084
- confirmed in database
-  …
=> fix(DB/Creature): Nightmare Illusion should be aoe immune

src/server/game/Spells/Auras/SpellAuras.cpp
Fixed #12080
- Closes #12080
- Closes https://github.com/chromiecraft/chromiecraft/issues/3630
`.go xyz -9797.036133 722.195251 35.278992 0 5.542893`
cast Flamestrike (2120) right in front of your character
cast Consecration (26573)
cast Explosive Trap (13813) …
=> fix(Core/Spells): Fixed calculating LoS for dynamic objects.

src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
Overpower is casted on dodge.
Execute is casted when victim is below 20% health.
Cleave is casted when there is at least 5 targets in melee range.
Fixes #11747
- Closes #11747
- Not tested.
`.go xyz -12212 -1959 133 309`
Kill the Vilebranch Speaker and start the encounter. …
=> fix(Scripts/ZulGurub): Improvements to Madonkir's melee spells.

data/sql/updates/pending_db_world/rev_1655583442917433100.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
-  Chained spirits should revive the nearest player instead of random. Also added a check to not select the same spirit for 2 players.
-  Mandokir should charge the farthest target possible.
-  Removed double debuff for Frightening Shout.
-  Added a check to not cast spells during charge.
- Closes #11746
- Closes #11749
- Closes https://github.com/chromiecraft/chromiecraft/issues/3626
1. Engage Mandokir with more than 2 players.
2. Let Mandokir or Ohgan kill players
3. See the nearest spirits revive the killed players.
=> fix(Core/ZulGurub): Mandokir charge and chained spirits

src/server/apps/worldserver/worldserver.conf.dist, src/server/game/Groups/Group.cpp, src/server/game/Groups/Group.h, src/server/game/Handlers/GroupHandler.cpp
-  And it's configurable, pog. 
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12107
- 
1. Try to create a raid group with a member below level 10 …
=> fix(Player/Groups): Level restriction on allowing raid groups

src/server/game/Globals/ObjectMgr.cpp
in this change #9665 several NPCs were broken when changing `npcflag`=`npcflag`|1 (Trainers, Missions) and fixing them when starting the worldserver shows an error in the console example of this error PR #11980 
example:
Creature (Entry: 18991) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
Creature (Entry: 18990) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
* It may not be the correct solution but it is a way that does not show those errors anymore and makes it possible to repair several broken missions and trainers
Staff Edit Begin by @acidmanifesto 
TC Cherry Pick: https://github.com/TrinityCore/TrinityCore/pull/24375
Co-Authored-By: [Sorikoff](https://github.com/Sorikoff)
Co-Authored-By: [@jackpoz ](https://github.com/jackpoz) …
=> fix (core): Npc gossip error logging

src/server/game/Entities/Player/Player.cpp
Fixed #11937
- Closes #11937
log into a shaman
`.level 79`
`.learn all class`
use fire elemental totem then wait 2 min
use [Call of the Elements](https://wotlkdb.com/?spell=66842), [Call of the Spirits](https://wotlkdb.com/?spell=66843) or [Call of the Ancestors](https://wotlkdb.com/?spell=66844) with fire ele totem in it and see what happens
try the same with earth elemental totem …
=> fix(Core/Spells): Fixed cooldowns on shaman totems.

src/server/scripts/World/npcs_special.cpp
-  Fix Brazier of Dancing Flames to begin dancing when spawn
- Closes https://github.com/chromiecraft/chromiecraft/issues/3666
- Tested in-game, also tested that emotes as still work
1. .additem 34686
2. Use item, test that flames dance …
=> fix(Scripts): Brazier of Dancing Flames should dance when spawned

src/server/game/Handlers/CharacterHandler.cpp, src/server/game/Spells/SpellEffects.cpp
Fixes #11939
- Closes #11939
- Closes https://github.com/chromiecraft/chromiecraft/issues/2815
- Not tested.
log into a shaman
.level 79
.learn all class
.additem 50458
.additem 45776 (Glyph) and use it
use [Totem of Wrath](https://wotlkdb.com/?spell=57722)
now u have the buff check ur spellpower
remove the glyph with shift rightclick
check ur spellpower
click the buff away
check ur spellpower …
=> fix(Core/Spells): Removed any triggered auras on glyph removal.

data/sql/updates/pending_db_world/skullsplitter.sql
-  Removes unnecessary Skulsplitter Panther spawns
-  Removes the 3s SmartAI despawn timer from Skullsplitter Panthers
-  Make Skullsplitter Hunters summon their pets On Reset instead of On Aggro
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12197
- Closes https://github.com/chromiecraft/chromiecraft/issues/3681
- 
1.
2.
3. …
=> fix(DB/Creature): Make Skullsplitter Hunter and Panther more in line with other creatures with summoned pets

data/sql/updates/pending_db_world/rev_1656438496539854300.sql
-  Remove Cataclysm gossip menu from Cenarion Emissary Jademoon
-  Confirmed with Vmangos that NPC does not have other gossip
- Closes https://github.com/chromiecraft/chromiecraft/issues/3705
Cross-checked with Vmangos
Checked in game, correctly has no gossip
1. .go cr 52
2. Check there is no gossip …
=> fix(DB/creature_template): Cenarion Emissary Jademoon Cata Gossip

data/sql/updates/pending_db_world/rev_1656482750700107200.sql
-  Remove extra_flags from Mar'li
- Closes -
- SQL Ran, should work...
1. Go to Mar'li and try to taunt, you should be able to taunt her.
=> fix(DB/ZulGurub): Remove taunt immunity from Mar'li

data/sql/updates/pending_db_world/rev_1656632586022126700.sql
-  Change Greater Windstone Bosses to begin combat after 5 seconds instead of 10 seconds, because they are set to despawn after being out of combat for 5 seconds
- Resolves issues with despawning after summoning
-  If we prefer to have wait 10 seconds, a other option is to make the despawn out of combat timer longer instead. Vmangos appears to use a 5 second timer despawn as well, though, so I think the implementation of this PR is Blizz-like.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3675
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12171
- Summoned all bosses, now correctly start combat and do not despawn
1. Summon boss at greater windstone, ensure combat starts and boss does not despawn …
=> fix(DB/Scripts): Greater Windstone Bosses

data/sql/updates/pending_db_world/rev_1656487501551472500.sql, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/EasternKingdoms/ZulGurub/boss_hazzarah.cpp
-  Change wait timer for Nightmare Illusions
-  Nightmare Illusions are now despawned after being killed.
-  Change their damage and their spawn mode.
-  Chain burn will only be casted if Hazza'rah has more than 5% of mana.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12235
- Tested in-game everything except chain burn.
.event stop 27
.event stop 29
.event stop 30
.event start 28
.additem 19931
.go xyz -11905 -1911 66 309
use the brazier and engage Hazza'rah
else:
.go xyz -11905 -1911 66 309
.npc add temp 15083
check the issues.
=> fix(Core/ZulGurub): Hazza'rah improvements

src/server/game/Spells/SpellInfoCorrections.cpp
Fixes #12226
- Closes #12226
`.q a 11865`
`.go xyz 2944.481689 5325.224121 62.272579 571`
found Caribou Trap use Pile of Fake Furs …
=> fix(Core/Spells): Place Fake Fur should activate Caribou Trap.

data/sql/updates/pending_db_world/rev_1656749058349666900.sql, src/server/game/Entities/GameObject/GameObject.cpp
Will of Hakkar is casted on pile looter.
Fixes #12186
- Closes #12186
`.go gameobject id 180229`
Loot it and see result. …
=> fix(DB/ZulGurub): Hoodoo Piles should not melee atack their targets.

src/server/scripts/EasternKingdoms/ZulGurub/boss_grilek.cpp
Fixes #12249
- Closes #12249
- Not tested.
`.tele ZG`
`.npc add temp 15082`
=> fix(Scripts/ZulGurub): Added Sweeping Strikes to Gri'lek encounter.

data/sql/updates/pending_db_world/rev_1656469500232857400.sql, src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
-  A lot of code improvements.
-  Brain wash totem should use the correct spell now.
-  Corrected respawn timer and corpse despawn for sacrificed trolls, and also added to a formation.
-  Use the proper spell for teleporting players and summoning creatures (Shades)
-  Now shades should properly engage after summoned.
- #12324 
- #12330 
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12188
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12204
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12205
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12206
Run and walk speed and spell ids from CMangos.
1. .go c id 11380 with 2 or 3 characters to avoid combat reset.
2. Test the issues above.
=> fix(Core/ZulGurub): Jin'do the Hexxer rewrite

data/sql/updates/pending_db_world/rev_1649656477945100427.sql
Description:
The proper quote is not written on this NPC. She quotes, which seems to be post-Cataclysm:
From this dock, The Bravery travels back and forth between Stormwind and Rut'theran Village.
Expected behaviour:
According to [Wowpedia](https://wow.gamepedia.com/Nayura), the proper quote is:
From this dock, The Bravery travels back and forth between Stormwind and Auberdine.
TC: https://github.com/TrinityCore/TrinityCore/issues/24972
- .go creature id 28650
- Interact with her.
=> fix(DB/Locale): Creature: Nayura

src/server/scripts/World/boss_emerald_dragons.cpp
-  Force the remove flag on death
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12267
- Tested IG
1. .go c id 14890
2. .damage 200000 …
=> fix(Scripts/World): Prevent Taerar to be untargetable on death

data/sql/updates/pending_db_world/emerissrep.sql
-  remove thrallmar and alliance equivalent rep gain on emeriss kill
-  
Its nowhere listed that they should give rep, especially not tbc rep.
- tested
- 
1.
2.
3. …
=> fix(db/creature): Emeriss should not give reputation on kill

data/sql/updates/pending_db_world/rev_1657581203983147300.sql
Adds researched packs to possible spawns
-  A few general fixes (removed defunct patrols)
-  Implemented research as followed from notes: 
```
--Before first bridge 
Trolls in front in Huts Can be Priests or Axe Throwers, outside huts are Axe Throwers
All paired snakes can be either type, but there are some complexities on bigger packs.  Adder/Adder is slightly less common than the other combos, except when it's not.  Leaving it 50/50 is prolly fine on all 2 packs.
(3) Bridge Entrance Patrol seen Axe/Priest and Axe/Axe
```
Sniff data along with personal research.
- Runs and tested without error.
1.  .tele ZG and check out the area
- Pooling is required on the snake pack, I am holding off on that for now.  Part 2 of this are will come soon …
=> fix(DB/creature): ZG entrance creature improvement

data/sql/updates/pending_db_world/rev_1657055583659435900.sql
- Standardize = Morloch / Taskmaster Snivvle
- Fix the level of "Irondeep Shaman"
- Remove loot from Whitewhisker NPCs and Irondeep NPCs / leave pickpocket / cannot confirm for leaders (Morloch - Snivvle)
- Closes #12308
- Closes https://github.com/chromiecraft/chromiecraft/issues/3731
- Closes #12310
- Closes https://github.com/chromiecraft/chromiecraft/issues/3732
- Closes #12311
- Closes https://github.com/chromiecraft/chromiecraft/issues/3733 …
=> fix(DB/creature template): Adjust Whitewhisker/Irondeep NPCs in Alterac Valley

data/sql/updates/pending_db_world/rookerywhelpsxp.sql
-  set flag to give no xp
-  
unlimited spawned monsters should not give xp.
- Tested
- 
1.
2.
3. …
=> Fix(DB/Creature): Rookery Whelps should not give XP.

data/sql/updates/pending_db_world/rev_1657968102568754700.sql, src/server/scripts/EasternKingdoms/ZulGurub/boss_jindo.cpp
Jindo can be re-aggroed when he soft reset.
Jindo can cast Brain Wash Totem while soloing.
Fixes #12338
- Closes #12338
- Not tested.
`.go c 49655` solo, engage boss
wait for a Brain Wash Totem cast, see if it works.
after the Brain Wash wears off, try to attack the boss to restart combat (you should have a 4-5s window before he completely resets) …
=> fix(Scripts/ZulGurub): Jindo the Hexxer - improvements.

data/sql/updates/pending_db_world/rev_1658266226251855400.sql, src/server/scripts/Commands/cs_npc.cpp
(Core/Commands): Introduce .npc guid
.npc info is too robust and floods the screen
.npc guid will simply provide only the first part of .npc info's output
-  Creates a new command named .npc guid which outputs only the first portion of .npc info
- using .npc info to get simple information about creatures was too difficult to read in game, this begins to address that, though some may find it still outputs too much info
1. After compile, enter world on any char
2. use .npc guid on a creature
3. use .npc guid on yourself to make sure error outputs are correct
- despite its name, it outputs a decent amount more than guid, I figure it can either be renamed or shortened more later and that I should keep my PR scope small especially since this is my first c++ commit on github …
=> (Core/Commands): Introduce .npc guid

data/sql/updates/pending_db_world/skeletalhorror.sql
-  fixes target for terrify ability
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12388
- closes https://github.com/chromiecraft/chromiecraft/issues/3636
cmangos
- tested
1. .go c id 202
2. see that you get feared.
3. …
=> fix(SmartScript/Creature): Skeletal Horror should cast Terrify at top threat target

data/sql/updates/pending_db_world/rev_1658282918588821000.sql
-  Update a few creature positions
-  Add a few extra ids
-  Remove movement from croc mobs until proper movement can be added.
-  Adjust movement type on bat pack.
Sourced from PTR or similar.
Notes:
```
--After first bridge 
49097 needs moved forward
Bat pack rotates positions (4 pools)
Front Troll can be a Priest or Axe Thrower, Adders can be any combo
Headhunter in Hut can also be witchdoctor, in front is always one of each 2 pools of 3  always match the hut directly in front
Seen 4-5 Crocs (6 Pools)
Crocs movement is a scripted action that occurs about every 30 seconds, not normal random movement.
```
Not all of these will be done in this PR (un-pooled changes only), additionally 2 more mobs were moved that were not mentioned (just out of position, 49121, 49122).
- Entered ZG and …
=> fix(DB/creature): ZG Before Bats Area Improvements

src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
-  Fixes a bug preventing this action type from accepting its parameter
Parameter is included in the documentation:
https://www.azerothcore.org/wiki/smart_scripts
- None yet. Please help test!
1. Add parameter 1 to any AI script using action type 101.
2. See documentation for details of how it should work.
3. Confirm no error message `SmartAIMgr: entryorguid {} source_type {} id {} action_type {} has unused action_param{} with value {}, it must be 0, skipped.` appears in server log. …
=> fix(Core): SMART_ACTION_SET_HOME_POS should accept a parameter

src/server/scripts/Spells/spell_priest.cpp
Fixes #11878
- Closes #11878
- Closes https://github.com/chromiecraft/chromiecraft/issues/3547
- Not tested.
`.learn 34916`
cast Vampiric Touch
Cast any other spell, such as Smite, on that target while it is afflicted by Vampiric Touch.
No Replenishment buff …
=> fix(Scripts/Spells): Replenishment should trigger only from Mind Blast.

src/server/game/AI/SmartScripts/SmartScript.cpp
-  add nullchecks to unit before dereference.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12478
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12465
- Not tested, kinda obvious crash, not needed.
1. Engage some creature with that kind of SAI.
=> fix(Core): Crash on smart event: near players

data/sql/updates/pending_db_world/rev_1658567599833438900.sql, src/server/game/Entities/Pet/Pet.cpp, src/server/scripts/Spells/spell_warlock.cpp
Fixes #12432
- Closes #12432
- Closes https://github.com/chromiecraft/chromiecraft/issues/2816
- Not tested.
Use "Glyph of Felguard"
Summon Felguard
Clear/replace "Glyph of Felguard"
See pet's ap stat …
=> fix(Scripts/Spells): Glyph of Felguard.

src/server/game/Entities/Totem/Totem.cpp
-  Merge duplicate `if`
- Closes none.
- Totem still despawn upon its death.
- Totem still despawn upon player's death.
1. Does the totem still behave the same?
- None …
=> Chore(Cleanup): Merge redundant `if` in Totem::Update()

src/server/game/Maps/Map.cpp, src/server/game/Server/WorldSession.cpp
-  When a player logs out during a "not your instance" homebind timer, they are sent to beginning of the instance
-  Also an optimization to only check map players when logging out within an instance - previously would unnecessary fetch all players on non-instance maps when anyone in a group logged out.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12447
- Not tested yet! Please help test. Thanks!
1. Follow steps in original issue report
2. Ensure no longer can re-log in at boss location
- I do not know proper Blizz-like behavior when logging out with a homebind timer. It is possible correct behavior should be to go to homebind location or graveyard rather than instance entrance. If someone can confirm this behavior is different, we can change it, but I think we should …
=> fix(Core): Instance Reset Exploit Fix

src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp
-  Remove double InstanceScript::OnCreatureCreate
- Closes -
- Built. No further test needed.
=> chore(Scripts): remove double method calling for ZG script

data/sql/updates/pending_db_world/rev_1658582043233714100.sql, src/server/scripts/Spells/spell_generic.cpp
-  Apply Hive'Zara Catalyst on Itch removal
-  Implement Spit out after consume expires and the target survives & remove consume if the ooze dies
- Closes 
- 
- 
1.
2.
3. …
=> fix(Scripts/Spells): Script spell Itch (AQ20) and improve Consume (AQ20)

data/sql/updates/pending_db_world/aq20trashupdate.sql
-  Hive'Zara Wasp, Qiraji Swarmguard improvements to smartscript / added smartscripts
- Obsidian destroyer drops chunk at death, spawns with low mana, uses mana drain
- Closes https://github.com/chromiecraft/chromiecraft/issues/3760
Sniffs from @Gultask 
- not tested
- 
1. Check the creatures and see if they cast their spells properly …
=> fix(SmartScript/Creature): AQ20 Trash improvements

data/sql/updates/pending_db_world/rev_1658857216982492500.sql, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp
-  Ossirian should perform a hard reset.
-  Vortexes should despawn on evade.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12467
1. Go to Ossirian and engage.
2. .combatstop
3. He should despawn and respawn after a while.
=> fix(Core/RuinsOfAhnQiraj): Ossirian reset

data/sql/updates/pending_db_world/aqdestroyer.sql
-  Sets on evade smartscript to return mana to 0
sniff
- tested …
=> fix(SmartScript/Creature): Destroyer should have 0 mana on repull

data/sql/updates/pending_db_world/aq20wasp.sql
-  adds 2 more spell casts to inflict 3 people with the poison.
- tested …
=> fix(Smartscript/creature): Hive Wasp should target 3 people every cast

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_moam.cpp
-  Limit it to 6 targets
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/RuinsOfAhnQiraj): Limit Moan's mana drain to 6 targets

src/server/scripts/World/boss_emerald_dragons.cpp
-  Repeat the event every 500ms instead of every update.
-  Check for his actual target and don't use the other method <.<
- Closes 
- Built.
1. Go to any of the emerald dragons and engage with 2 chars
2. With the tank stay in melee range while you run away with the other, the one who isn't tanking should not be summoned ever.
3. Later try kiting with the tank, you should be ported as soon as you reach 50yds
=> fix(Scripts/EmeraldDragons): fix summon player spam

data/sql/updates/pending_db_world/emeralddragonsskinloot.sql
- uses own Skinning Loot ID
-  changes green scales to 5-8 60% chance
-  adds dreamscale 3-5 40% chance
cmangos
- Tested …
=> fix(DB/SkinningLootTemplate): emerald dragons should skin dreamscale

data/sql/updates/pending_db_world/rev_1658273838607986200.sql
-  Changes movement type and wander distance on two creatures in the ZG entrance way, finishing touches on the last 2 PRs  
1.  .go c 49739, 49740
2.  observe movement
- This specific entrance area might be completely done now in terms of movetype ids and pooling.  Hurray.  Next. …
=> fix(DB/creature): correct movement type on a couple snakes (ZG Entrance 3)

data/sql/updates/pending_db_world/rev_1659289474965390600.sql
-  From TrinityCore (I'm assuming this is sniffed), set spawn times Deliana, High Priest Rohan, Bubulo Acerbus and Bahat to 5 minutes.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12578
TrinityCore's DB
- Ran the sql.
1. Kill one of the npcs and wait 5min until they respawn
=> fix(DB/Creature): Deliana and other npcs spawn time

src/server/scripts/Spells/spell_priest.cpp
Fixes #12265
- Closes #12265
- Closes https://github.com/chromiecraft/chromiecraft/issues/3698
Place 2 characters in a party and enter combat
`.learn 27871` and cast Lightwell
Character A clicks on the Lightwell
Character B clicks on the Lightwell
Now Character A can use again the Lightwell (after the hot buff wears off) …
=> fix(Scripts/Spells): Properly handle spellclick flag for Lightwell.

data/sql/updates/pending_db_world/rev_1659015925728207500.sql
- Adjust unit_falg
- Closes #12571
- Closes https://github.com/chromiecraft/chromiecraft/issues/3861 
Applied SQL and tested: …
=> (DB/creature_template): Make Nefarian's Troops [trigger] invisible

src/server/scripts/Spells/spell_generic.cpp
Fixes #11631
- Closes #11631
- Not tested.
create a mage, level 60
`.additem set 526`
equip 4/9 items
cast Mage Armor ID: `22783`
use another character to cast any spell against the mage, like fireball 113 or frostbolt 116, use `.cheat casttime` to help
see that Adaptive Warding procs …
=> fix(Scripts/Spells): Fixed T3 4P Frostfire Regalia bonus not proccing.

data/sql/updates/pending_db_world/rev_1658607158126098600.sql
-  Creates the two ways this pack can spawn.
Classic/retail/sniff
- Rebooted server until both variations were seen in ZG. 
1.  Enter ZG
2.   .go c 49120
3.  Reboot server until you see both variations …
=> fix(DB/creature, pools): ZG Before Bats cont. Troll 3-pack

data/sql/updates/pending_db_world/rev_1659293964039098600.sql
-  Add missing emote to Hive'Zara Soldier.
- Correct Retaliation usage.
- Added missing cleave to Swarmguard Needler (thanks to @Gultask for the script)
- Added missing Uppercut and Thunderclap for Qiraji Warrior.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12590
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12587
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12589
Retail - sniffs from issues.
1. Go to each creature and check the issues for each one of them.
=> fix(DB/RuinsOfAhnQiraj): add missing SAI for some creatures

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/Spell.cpp
-  Removed caster dependency from ProcDamageAndSpell method, avoiding dereference crash.
-  Partially cherry-picked from https://github.com/TrinityCore/TrinityCore/commit/cb9e72e521d3cc415dd15bf6912c87f89e41b92a
- Closes no open issue.
https://gist.github.com/Nefertumm/0f5aace3a036808ce17425f740019482
- Built
1. Make sure everything works as before (mainly procs), there is no difference.
=> fix(Core/Spells): Crashfix

src/server/scripts/EasternKingdoms/ZulGurub/boss_mandokir.cpp
-  Add a null check for caster, an aura can have a null caster.
- Closes -
- Built, no test needed.
1. Possible crash: Go to mando, let him cast gaze on you, kill him while you still have the debuff, watch it crash.
2. Apply the PR and make sure there is no crash anymore.
=> fix(Core): Crash on Mandokir gaze

src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_lord_jaraxxus.cpp
-  Get all creatures and despawn all at once.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12613
- Only built.
1. Go to Jaraxxus and wipe on the add phase.
2. worldserver shouldn't freeze.
=> fix(Core): Freeze on Lord Jaraxxus

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp
-  Add a missing check to not repeat the same action multiple times on bug death.
-  Add another missing check on MovementInform to prevent bugs to heal to max health when they shouldn't.
-  Prevent despawning if a boss was killed too quickly.
-  Clear motion master to prevent stuck issues.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12566
1. Go to bug trio with 2 chars and engage.
2. Kill one with a dot applied, the final spell should be executed once.
3. Let Vem charge you, it shouldn't heal anymore.
=> fix(Core/TempleOfAhnQiraj): Bug Trio

src/server/game/Entities/Unit/Unit.cpp
Fixes #11613
- Closes #11613
- Closes https://github.com/chromiecraft/chromiecraft/issues/3437
Volley a mob with Auto Shot active ie /startattack. witness Auto Shot casting during the channel. …
=> fix(Core/Spells): Volley should suspend auto-shot.

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Unit/Unit.cpp
- Adds knock back helpers to the core for future core and module use.  
-  Simular to the Can Teleport Helpers but for knock back confirmation
- Closes 
- Builds
- Runs
1.
2.
3. …
=> update (core): Knock Back Helpers

src/server/scripts/EasternKingdoms/ZulGurub/boss_gahzranka.cpp
-  Check if the boss is spawned
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12662
- Closes https://github.com/chromiecraft/chromiecraft/issues/3894
- Not tested
- 
1. Try to use the lure quickly in succession
2.
3. …
=> fix(Scripts/Zul'Gurub): Prevent multiple spawns of Gazhranka

src/server/game/Entities/GameObject/GameObject.cpp
-  Happens once f.e a death knight leaves a death gate open and logs off/dissappears/gets deleted
-  No reason for the crash scare as it often doesnt mean anything ill (have yet to see a crash from this in the past 12 months)
- Closes 
- 
- 
1.
2.
3. …
=> chore(Core/GameObject): Clear an error that often doesn't mean anything

data/sql/updates/pending_db_world/rev_1659982493488417100.sql, src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_kurinnaxx.cpp
-  Thrash should be casted every 16s exactly.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3898
- Not tested.
1. Engage Kurinnaxx and wait for Thrash spell.
=> fix(Core/RuinsOfAhnQiraj): Kurinnaxx thrash

data/sql/updates/pending_db_world/q9740_fix_20220809, data/sql/updates/pending_db_world/q9740_fix_20220809.sql
Fix to quest 9740 The Sun Gate. Gate can't be desactivated and this fix it.
-  Fix the Sun Portal that can't be desactivated 
- Closes [issue 12518](https://github.com/azerothcore/azerothcore-wotlk/issues/12518)
- Tested
1. Adquire quest 9740 "The Sun Portal" in NPC Vindicator Aesom
2. Go to Sun portal location
3. Disable portal controllers
4. Disable Sun portal …
=> fix (Quest 9740): The Sun Gate

data/sql/updates/pending_db_world/rev_1660309887806825183.sql
Eldinarcus is stationary and does not wander around his spawn
https://github.com/azerothcore/azerothcore-wotlk/issues/7462
Add wander distance of 20 to Eldinarcus. 
I don't see any specific patrol points in the reference video (https://www.youtube.com/watch?v=iw6xT997OLg&t=841s) and 20 seems correct when testing
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7462
```
.go c 58019
```
Observe patrol …
=> fix(DB/EversongWoods): Add Eldinarcus Patrol

src/server/game/Handlers/AuctionHouseHandler.cpp
-  Execute the hook on buyout, currently is only executing if you win the auction by time passing.
- Closes https://github.com/azerothcore/mod-eluna/issues/56
- Tested in-game with cpp hook and eluna hook.
1. Try to use a OnAuctionSuccessful script on Eluna or cpp.
2. Buyout an auction.
=> fix(Core/Scripting): OnAuctionSuccessful on buyout

data/sql/updates/pending_db_world/rev_1660249698988810843.sql
Angershade repeatedly tries to attack quest giver without quest (8488)
Unexpected Results being started.
Closes #12016
-  Changes to Smartscript so the mob only tries to attack quest giver when the summoned NPC is spawned
It checks for the summoned quest NPC (gharsul the remorseless) to be in 20 yard range. Previously it checked if quest giver was in 53 yard range (which it was) and tried to attack it, which it couldn't as her flags were set to be not attackable. Resulting in angershades within 53 yard to repeatedly try to attack it and make the attack noise.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12016
- Closes https://github.com/chromiecraft/chromiecraft/issues/3599
https://www.youtube.com/watch?v=1XzhPZ_CFT0
Tested 
1. Go to the mob with `.go c 56105` and …
=> fix(DB/EversongWoods): Fix Angershade noise spam

src/server/game/Entities/Player/Player.cpp
-  Make `bool Player::CanResummonPet(uint32 spellid)` only use `getClass()` once
-  Mage needs both [Summon Water Elemental] spell and [Glyph of Eternal Water] to in order to be ressurected with the water elemental pet at the Spirit Healer.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12638
- Closes https://github.com/chromiecraft/chromiecraft/issues/3837
- Closes https://github.com/chromiecraft/chromiecraft/issues/3922
- Mage without talent and without glyph
- Mage with talent but no glyph
- Mage with both talent and glyph
- Mage without talent but with glyph
1. Try to replicate https://github.com/azerothcore/azerothcore-wotlk/issues/12638 …
=> fix(Core/Mage) Water Elemental wrongly ressurected at Spirit Healer

src/server/game/Battlegrounds/BattlegroundQueue.cpp, src/server/game/Handlers/BattleGroundHandler.cpp
- Fix crash at kick players from queue group
- Remove queue in all group if player any leave
- Part https://github.com/azerothcore/mod-cfbg/pull/111
=> feat(Core/BattlegroundQueue): remove queue in all group if player leave

src/server/game/Loot/LootMgr.cpp
-  Remove the unique item check that hides unique items from loot
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/3930
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12748
- 
- 
1. .additem 21133 and keep looting
2.
3. …
=> fix(Core/Loot): Unique items shouldn't be hidden indiscriminately

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp
-  Call the method to update the encounter state... x.x Dumb me.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3931
- Not tested.
1. Go to AQ 20 with a raid group and kill Buru.
2. Leave the instance and try to enter again.
=> fix(Core/RuinsOfAhnQiraj): re-enter the instance after Buru died

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_buru.cpp
-  Completely delete full speed event on egg phase.
-  Make sure we are removing stacks from gathering speed (edge case of boss being low life after an egg explosion and players hitting it enough to phase it without killing another egg)
-  Add threat on entering combat as well (showed on sniffs)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12791
- Closes https://github.com/chromiecraft/chromiecraft/issues/3950
- Not tested.
1. Go to Buru and make sure it's not casting full speed unless while phasing or evade.
2. It should restart all his stacks of gathering speed on phasing.
=> fix(Core/RuinsOfAhnQiraj): Buru full speed and gathering speed

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ossirian.cpp
On pull Ossirian movies too slow and is kiteable. He should speed up and
become no longer kitable.
Add event that repeats 10 times to speed up Ossirian from 1.0f to 2.0f in steps of 0.1f
- Closes https://github.com/chromiecraft/chromiecraft/issues/3912
1. Go to Ossirian
```
.go c 144601
```
2. Set Speed
```
.mod speed 1.3
.mod speed 1.08
```
3. Ranged pull and attempt to kite
In both cases he should catch up to the player
- Ossirian aggro range is too small. He does not body pull accurately …
=> fix(Scripts/AQ20): Ossirian movement speed

data/sql/updates/pending_db_world/rev_1658940484513440700.sql
-  Remove incorrect loot from several creatures that should not have
-  Note that this is slightly different from original TC PR - I did not remove pickpocket loot from 12352 because it appears it should have it is correct (https://www.wowhead.com/wotlk/npc=12352/scarlet-trooper)
- Co-authored by offl
From TrinityCore https://github.com/TrinityCore/TrinityCore/commit/74ed066aa34fbd30161136d5989e99bbe34ab72d
- SQL runs, no DB issues
1. Test that creatures listed no longer drop loot
- If someone wants to confirm that Scarlet Trooper cannot be pickpocketed on retail, we can remove that loot as well, but otherwise I think we can remain as is - we are currently consistent with WoWHead. …
=> fix(DB/creature_template): Remove Incorrect Loot

src/server/scripts/World/go_scripts.cpp
Dwarf hourly horn should only play a single time, each time the next hour begins.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11328
1. tele ironforge (or any other place where dwarf horn sound is used, like Kharanos)
2. `.event start 73`
3. sound is played once …
=> fix(Core/Event): Hourly bell: Dwarf horn sound should only play once

src/server/game/Spells/SpellInfoCorrections.cpp
-  It shouldn't disarm at all.
- Closes https://github.com/chromiecraft/chromiecraft/issues/3943
Sniffs on retail - logs - etc.
1. Go to Ayamiss and make sure it doesn't disarm itself anymore (or players).
=> fix(Core/RuinsOfAhnQiraj): Lash should not disarm

src/server/scripts/EasternKingdoms/zone_duskwood.cpp
-  Remove Mandokir spell wrongly used by the boss, use Swell of souls instead.
-  Refactor the whole code.
-  Corrected timers.
- Closes -
1. .quest add 8735
2. .debug areatrigger
3. .go xyz -10648.385742 -383.815857 109.027054
4. Follow the path.
5. You should see you activated an areatrigger and go to the moonwell.
6. Engage the boss.
=> refactor(Core/Duskwood): Twilight Corrupter

data/sql/updates/pending_db_world/aq20enchantloot.sql
-  sets correct loot for enchanting recipes in aq20
-  
- Partially adresses https://github.com/chromiecraft/chromiecraft/issues/3915
cmangos
- 
- 
1.
2.
3. …
=> fix(Loot/CreatureLoot): AQ20 enchanting recipes

data/sql/updates/pending_db_world/rev_1661366860302196200.sql
-  Imports Vmangos data for creature 14668.
-  Damage modifier was previously 1 and had no spells or AI scripts
Vmangos
- Tested with `.npc add temp 14668`
1. Engage Nefarian with a Warlock, go into phase 2
2. Wait for the Class Call
3. See if Corrupted Infernals deal proximity damage (30) and occasionally stuns its target. …
=> fix(DB/Creature): Improve Nefarian's Corrupted Infernal (14668)

src/server/game/Weather/Weather.cpp
There's a rare bug that occurs where it starts raining in zones that
shouldn't like Winterspring and Tanaris.
https://user-images.githubusercontent.com/74299960/184515714-7074c2e7-201d-4c7e-b4ff-bcddf75accb1.mp4
-  Change range to not include chance 0
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12711#issuecomment-1214226996
https://wowpedia.fandom.com/wiki/Weather_effects#Kalimdor_and_Eastern_Kingdoms
I changed the setting in `worldserver.conf.dist` and managed to get weather updates more frequently and was able to reproduce the issue.
```
#
ChangeWeatherInterval = 20
```
I used vscode to set a conditional breakpoint when the rnd hits 0. And as you can see chance1 is the chance to rain in the zone and it'll change the type to rain.
The randomness is also inaccurate. …
=> fix(Core/Weather): Wrong change type algorithm

data/sql/updates/pending_db_world/rev_1661475791842006200.sql
-  Remove QuestRequired from Scarab Bag
-  Increase MaxCount in Large Scarab Coffer to 3 according to Vmangos and own experience
- Closes https://github.com/chromiecraft/chromiecraft/issues/3996
- 
1. `.additem 21761 20` `.additem 21762 20`
2. `.gob add temp 180690` open, see if 1-3 Scarab Bags can be looted, alongside Idols
3. `.gob add temp 180691` open, see if 1 Scarab Bag can be looted, alongside Idols …
=> fix(DB/gameobject): Update Scarab Coffer (180690 & 180691) loot

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_ayamiss.cpp
-  Move the scheduler to when it lands
-  
- Closes 
- 
- 
1. pull ayamiss, check if it still cast spells, damage till it lands, check if it lands and if it casts p2 spells correctly
2.
3. …
=> fix(Scripts/RuinsOfAhnQiraj): Restructure Ayamiss task scheduling during landing

data/sql/updates/pending_db_world/rev_1660710379331178100.sql
-  Remove [Idol of Brutality](https://wowgaming.altervista.org/aowow/?item=23198) from all mobs in DB except from [Magistrate Barthilas](https://wowgaming.altervista.org/aowow/?npc=10435) in Stratholme
- Closes #12757
[WoW Classic - dropped by](https://classic.wowhead.com/item=23198/idol-of-brutality#dropped-by)
[WOTLK Classic - dropped by](https://www.wowhead.com/wotlk/item=23198/idol-of-brutality#dropped-by)
* Comments only refer to Magistrate Barthilas as well on every patch
- /* Affected rows: 52  Found rows: 0  Warnings: 0  Duration for 2 queries: 0.984 sec. */ …
=> fix(DB/creature_template): Remove incorrect drops for Idol of Brutality

data/sql/updates/pending_db_world/rev_1660709375823590700.sql
-  Delete all [Punctured Voodoo Dolls](https://wowgaming.altervista.org/aowow/?search=punctured+voodoo+doll) that can drop from trash mobs in Zul'Gurub
- Closes #12755
[Classic - only obtainable from Jinxed Voodoo Piles](https://classic.wowhead.com/item=19819/punctured-voodoo-doll#contained-in-object)
[Woltk Classic - only obtainable from Jinxed Voodoo Piles](https://www.wowhead.com/wotlk/item=19819/punctured-voodoo-doll#contained-in-object)
/* Affected rows: 142  Found rows: 0  Warnings: 0  Duration for 1 query: 0.937 sec. */ …
=> fix(DB/creature_loot_template): Remove all Punctured Voodoo Dolls from mobs

src/server/scripts/Kalimdor/RuinsOfAhnQiraj/boss_rajaxx.cpp
-  ResetAllThreat after cast Thundercrash
- Closes 
https://classic.wowhead.com/guides/general-rajaxx-ruins-of-ahnqiraj-strategy
- Tested
1. Engage Rajaxx
2. Wait Thundercrash
3. Look if you got a drop threat …
=> fix(Core/Scripts): Rajaxx should drop aggro after Thundercrash

src/server/game/Entities/Creature/GossipDef.cpp
-  Show correct amount of XP that will be received if the amount is modified by the hook
-  Previously, correct amount would be award but the amount in the quest details would be incorrect
N/A
- Tested in game, works now correctly
1. Change Quest XP using OnBeforeQuestComputeXP hook
2. Check that the modified value now appears in quest details …
=> fix(Core): Correct Quest XP Display when modified by OnQuestCompleteXP Hook

data/sql/updates/pending_db_world/rev_1661398559549192100.sql
- Imports damagemodifier, armormodifier, resistances values and detection_ranges from Vmangos.
- Closes unopened issues
- 
- 
1.
2.
3. …
=> fix(DB/creature_template): Import Vmangos values for AQ40.

data/sql/updates/pending_db_world/rev_1661701493702481600.sql
Fixes #11409
- Closes #11409
- Closes https://github.com/chromiecraft/chromiecraft/issues/3353
Go to Warsong Gulch with 2 characters of the opposite faction.
Pick up both flags
Wait 10 minutes to get Focused Assault
Wait 5 more minutes and see Focused Assault being dropped and Brutal Assault be applied. …
=> fix(DB/Spells): Fixed applying Brutal Assault.

data/sql/updates/pending_db_world/rev_1662155367567816700.sql
- Sets all Vekniss Guardian except GUIDs 87595 and 87596 to MovType 1 and wander_dist 3, as per Retail sniffs
- Closes unopened issue.
Retail
1.
2.
3. …
=> fix(DB/creature): Update Vekniss Guardian (15233) movement

data/sql/updates/pending_db_world/rev_1660252072288200163.sql
Tigers were using sprint. Expected tigers should not use sprint.
Closes #12679
-  Remove smartAI script action 22863 from the tigers that use it.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12679
```
.go c 55919
.go c 55988
```
1. Use above listed commands to go to mobs
2. Aggro and see if they cast sprint on aggro …
=> fix(DB/EversongWoods): Remove sprint action from tigers

data/sql/updates/pending_db_world/rev_1660681693491912819.sql
Some dungeons do not give desert when leaving. This aims to fix BRD - Prison and Scholomance 
LFG dungeons listed in `lfgdungeonsDBC` https://wow.tools/dbc/?dbc=lfgdungeons&build=3.3.5.12340#page=1
that are not in `lfg_dungeon_template` (https://gist.github.com/SoglaHash/c93663feec0a47a63f5adc057c0a1d5f) do not give deserter accurately.
for instance: Blackrock Depths - Upper City, Scholomance and Slave Pens
-  Added missing Blackrock Depths - Upper City and Scholomance to `lfg_dungeon_template`
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12676
Tested queueing LFG for Blackrock Depths - Upper City, LBRS and Scolomance. Leaving applies deserter correctly.
Also tested Slave Pens, this does not give deserter accurately but is included in TODO
1. Make a 5man party with …
=> fix(DB/LookingForGroup): Leaving dungeon does not give deserter

src/server/game/Entities/Player/Player.cpp
Changing maps while on transport shouldn't dismount
-  Add `!m_transport` check to avoid removing mount auras on player that is on a transport  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12837
- Tested on menethil boat and org zep
As described in #12837
1.  .tele Ratchet
2. .aura 23221
3. Board the boat.
4.  Observe the issue. …
=> fix(Core/Player): Dismount on Transport Teleport

data/sql/updates/pending_db_world/rev_1661991078330961901.sql
Dark Rune puts Demonic Rune on a 2min cooldown instead of 15min
-  `spellcategorycooldown_1`=900000 (15min) instead of 120000 (2min)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12898
As described in  https://github.com/azerothcore/azerothcore-wotlk/issues/12898
.additem 12662
.additem 20520
use Dark Rune
use Demonic Rune
Deleting `cache/` in wowfolder might be needed …
=> fix(DB/Item): Dark Rune puts Demonic Rune 2min CD

src/server/game/Entities/Unit/Unit.cpp
When mainhand has on next swing spell, offhand doesnt suffer penalty
-  Implement changes that are present in CMangos and VMangos core
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12767
This change is present in CMangos and VMangos. See links below
VMangos
Unit.cpp
`float Unit::MeleeMissChanceCalc(Unit const* pVictim, WeaponAttackType attType) const`
https://github.com/vmangos/core/blob/d7e2dee88304745540527d6a9f33dd0b9aeddc9c/src/game/Objects/Unit.cpp
CMangos
Unit.cpp
`float Unit::CalculateEffectiveMissChance(const Unit *victim, WeaponAttackType attType, const SpellEntry* ability) const`
https://github.com/cmangos/mangos-classic/blob/master/src/game/Entities/Unit.cpp
Difference between these two is `!m_currentSpells[CURRENT_MELEE_SPELL]`, CMangos more restrictive, …
=> fix(Core/Unit): DualWield Off-hand hit penalty

data/sql/updates/pending_db_world/rev_1662107131127819900.sql
-  Changed SpecialFlags in `quest_template_addon`
- Closes  #12756
- https://wowgaming.altervista.org/aowow/?quest=8314
- Tested on local AC server
1.  `.go creature 42752`
2. `.quest add 8309` `.quest add 8310`
3. `.quest complete 8309` `.quest complete 8310`
4. Finish both quests
5. Check [Unraveling the Mystery](https://wowgaming.altervista.org/aowow/?quest=8314) …
=> fix(DB/Quest) "Unraveling the Mystery" has wrong quest marker

data/sql/updates/pending_db_world/rev_1662131908035510198.sql
original author https://github.com/Warglaive of https://github.com/azerothcore/azerothcore-wotlk/pull/12544 
I noticed the riding trainer also has repair flag set by mistake (unless its a blizzlike bug).
I checked the other NPCs on map 530 and only these 2 have the wrong repair flag set
-  SQL & Python script used in https://gist.github.com/SoglaHash/39be7c76082674442ad8c954f999c9cb
-  Remove repair flag from riding trainer and leatherworking trainer
- Closes 
1. Leatherworking trainer 
` .go c 56986`
4. Riding trainer 
`.go c 56988` …
=> fix(DB/EversongWoods): Repair Flag wrongly set

data/sql/updates/pending_db_world/rev_1662487488595481700.sql
-  Modifies values for entries 15316, 15317, 15246, 15537 and 15538
-  Also adds resistance values
- Query ran multiple times
- 
1.
2.
3. …
=> fix(DB/creature_template): Import AQ40 values from Vmangos missing in previous PR

data/sql/updates/pending_db_world/rev_1661649172326868600.sql
Co-authored-by: Mathematical <zajibrik@gmail.com>
-  Add a quest condition to quest 374 so that it can only be taken by the player, if he has completed and submitted quest 427.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12873
- Closes https://github.com/chromiecraft/chromiecraft/issues/3855
- In-game
1. `.go c 29798`
2. Try to obtain the quest without having completed the previous quest.
3. And then, do the test, to see that the quest is only available, if the requirement is completed. …
=> (DB/Conditions) Add condition to quest 374

data/sql/updates/pending_db_world/Remove-AQ40-idols-from-AQ20.sql
-  Remove the AQ40 idols from AQ20.
- Closes none, I didn't bother opening an issue.
Wowhead only shows that the AQ40 idols only drops from Temple of Ahn'Qiraj.
- I ran the following query and it gave me nothing after I executed the deletion.
```SQL
SELECT *
FROM /*acore_world.*/creature_loot_template
WHERE Item IN (
20874, #Idol of the Sun
20875, #Idol of Night
20876, #Idol of Death
20877, #Idol of the Sage
20878, #Idol of Rebirth
20879, #Idol of Life
20881, #Idol of Strife
20882  #Idol of War
) AND Entry IN (
15318, #Hive'Zara Drone
15323, #Hive'Zara Sandstalker
15325, #Hive'Zara Wasp
15327, #Hive'Zara Stinger
15333, #Silicate Feeder
15336, #Hive'Zara Tail Lasher
15338, #Obsidian Destroyer
15343, #Qiraji Swarmguard
15355, #Anubisath Guardian
15386, #Major Yeggeth
15392  #Captain Tuubid …
```
=> fix(DB/loot): Remove AQ40 Idols from AQ20

data/sql/updates/pending_db_world/rev_1661392957497204000.sql
-  changes Damage Modifier and resistance values to all creatures in AQ20
-  Original was 7.5 for *all* trash and 35 for *all* bosses.
Vmangos
- 
- 
1.
2.
3. …
=> fix(DB/creature_template): Import AQ20 values from Vmangos.

data/sql/updates/pending_db_world/rev_1662632661986479800.sql
-  Adds items Grimoire of Shadow Bolt X, Grimoire of Immolate VIII and Grimoire of Corruption VII to reference entry 34024
- Closes https://github.com/chromiecraft/chromiecraft/issues/4042
Cmangos Classic
1. `.go c 144603`
2. kill the boss until one of the 3 items drop …
=> fix(DB/loot): Add missing Warlock grimoires to AQ20 loot

src/server/game/Spells/SpellInfoCorrections.cpp
Fixes #12628
- Closes #12628
- Closes https://github.com/chromiecraft/chromiecraft/issues/3877
`.learn 20271` or `.learn 53408` or `.learn 53407` (Judgements)
`.aura 20164` (Seal of Justice)
cast any of the judgements, note the damage
`.aura 23591` (set bonus aura)
cast any of the judgements again …
=> fix(Core/Spells): Fixed Paladin's T2 8P bonus.

data/sql/updates/pending_db_world/rev_1662807926407515000.sql
Fixes #12629
- Closes #12629
- Closes https://github.com/chromiecraft/chromiecraft/issues/3876
- Not tested.
`.aura 26119`
cast Lightning Bolt several times, see if Stormcaller's Wrath (26121) gets applied to you.
use `.cheat casttime` `.cheat power` `.cheat cooldown` if necessary …
=> fix(DB/Spells): Fixed Shaman's T2 3Pbonus.

data/sql/updates/pending_db_world/rev_1662808735373629900.sql, src/server/game/Entities/Unit/Unit.cpp
Fixes #12764
- Closes #12764
- Closes https://github.com/chromiecraft/chromiecraft/issues/3783
- Not tested.
Equip 2 of the same weapon or with different weapons with the same speed
`.aura 16280`
attack a target, see how many charges are consumed …
=> fix(DB/Spells): Added 500ms cooldown to Flurry proc.

src/server/game/Spells/Spell.cpp
Fixes #11815
- Closes #11815
Enter WSG
`.learn 1953`
`.go xyz 1326.544922 1548.792236 313.554077 489 2.925584`
Blink
`.go xyz 1322.790894 1388.942383 315.210632 489 4.309457`
Blink …
=> fix(Core/Spells): Improved Blink in WSG near NE huts.

src/server/game/Spells/SpellInfoCorrections.cpp
Gift of Arthas duration with Mixology should be increased to 1 hour
-  Change SPELLFAMILY_GENERIC to SPELLFAMILY_POTION
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12941
Alliance alch trainer 
.go c 79832
.setskill 171 450 450
.add 9296 recipe
learn mixology
.additem 9088
/use Gift of Arthas …
=> fix(Core/Spell): Mixology duration Gift of Arthas

src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.h
-  Add ability to set flag in param5 to prevent Range Event from activating on entering combat thus only after the repeat timer occurs.
The Range Event is a much better choice for the Frost Nova spell over In Combat timers due to the fact that the spell should not be cast unless the player is in range.
Currently the event will cast the spell in entering combat which is not desirable.
Malcrom
- Tested in game with and without flag
1. Recompile with changes
2. Test without flag
3. Insert ```UPDATE `smart_scripts` SET `event_type`=9, `event_chance`=75, `event_param1`=0, `event_param2`=8, `event_param3`=10000, `event_param4`=15000, `event_param5`=0, `action_param2`=1, `target_type`=1, `comment`="Boulderfist Magus - Within 0-8 Range - Cast 'Frost Nova'" WHERE `entryorguid`=2567 AND …
```
=> fix(Core/Smart Scripts): Add param5 flag for range event

data/sql/updates/pending_db_world/rev_1661958107725070400.sql
-  Rot Hide Mongrel loot table changed
- Closes #12808 
- https://www.wowhead.com/wotlk/quest=358
- https://www.wowhead.com/wotlk/npc=1675
- Tested on local AC windows server
1. Add quest  `.quest add 358`
2. Teleport to NPC `.go creature 44663`
3. Kill Rot Hide Mongrel's and check drop …
=> fix(DB/Loot): Rot Hide Mongrel has incomplete loot table

src/server/scripts/Kalimdor/zone_ungoro_crater.cpp
Aggro dialog targets player. It should target the summoned creature instead
-  Change target player to summoned
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12871
Add prequest
.quest add 4243
.go c 24268
.add 10561
start escort q …
=> fix(Scripts/Quest): Aggro Talk text targets player

data/sql/updates/pending_db_world/rev_1661953746218069448.sql, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
Vaelan stands in a corner in Lower Blackrock Spire and always offers the Seal of Ascension quest
Scarshield Infiltrator stands there and does nothing
Before pic with areatriggers
-  Remove static Vaelan
- Make Scarshield Infiltrator kneel and transform when player with unadorned seal of ascension triggers areatrigger
- Sends whisper like "not worthy of my knowledge" if seal not in bags and transform has not started
- Add missing NPC Texts to gossip
- Add script to Areatrigger 1946 to trigger transformation or whisper
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12687
Similar change found in VMangos https://github.com/vmangos/core/blob/a01720f547f0d042b7989085a1a3558cc6e92a64/sql/old_migrations/20171124181306_world.sql
Gossip and transformation …
=> fix(Scripts/BlackrockSpire): Scarshield Infiltrator

src/server/game/AI/SmartScripts/SmartScript.cpp
- Make AI finish cast before fleeing.
- Patch originally written for TrinityCore: https://github.com/TrinityCore/TrinityCore/pull/28228
- Currently, AI will cancel casting in order to flee. This is not how it worked in Wrath- they will finish casting, and then flee.
- Joana 42-43 STV grind, watch the warlock finish the cast before fleeing around the 8:30 mark https://youtu.be/NmuWN_3Qkec?t=509
- Continue watching the video and observe the behavior is consistent
- Also consider watching other parts of the speedrun where Joana fights humanoids that tend to run
- Built and deployed to personal AC instance running on Linux
- Tested with enemies at Gold Coast Quarry in Westfall
1. Either `.go c id 589` or `.tele GoldCoastQuarry`.
2. Get into combat with a Defias Pillager (which was id 589).
3. …
=> Fix AI flee logic: creatures should finish casting any current spells before fleeing

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/instance_temple_of_ahnqiraj.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.h
-  Move door handling to its proper system.
-  Code cleanup.
- Closes -
1. Enter AQ40 and check the door behind Skeram, it should be closed. Kill Skeram and it should open.
2. Go to Twin Emperors and engage, the entrance door should close, while the other one should be always closed. Kill them and both of them should open.
=> fix(Core/TempleOfAhnQiraj): Door handling

src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.cpp, src/server/game/AI/SmartScripts/SmartScriptMgr.h
-  Please forgive my previous fix as I tested it with chance at 75 percent and by chance everything worked. I found out after that it didn't work and started on a proper fix.
This fix will, really really this time, prevent initial firing of ranged event and will not fire until repeat time has expired.
Me - tested at 100 percent this time.
- tested in game at 100 percent this time.
1. With flag ```UPDATE `smart_scripts` SET `event_type`=9, `event_chance`=100, `event_param1`=0, `event_param2`=8, `event_param3`=10000, `event_param4`=15000, `event_param5`=1, `action_param2`=1, `target_type`=1, `comment`="Boulderfist Magus - Within 0-8 Range - Cast 'Frost Nova'" WHERE `entryorguid`=2567 AND `source_type`=0 AND `id`=3;```
2. Without flag ```UPDATE `smart_scripts` SET `event_type`=9, …
```
=> Feature(Smart Scripts/SMART_EVENT_RANGE): Proper fix to prevent Initial timer

src/server/game/Handlers/CharacterHandler.cpp, src/server/game/Scripting/ScriptDefines/AccountScript.cpp, src/server/game/Scripting/ScriptMgr.h
-  CharacterCreateInfo has protected access, so the previous parameters were not useful
-  Passes only the most useful parameters as arguments directly. Please submit an additional PR and add the other parameters if you are needing them in an AccountScript.
- Works locally
1. This PR was just merged and this adjusts it to be usable, so I do not think any testing is necessary …
=> fix(Core): CanAccountCreateCharacter hook parameters

src/server/game/Handlers/LootHandler.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptMgr.h
-  Adds a hook called before money is looted, allowing modification of money amount
-  Useful for Autobalance type modules that scale down instances, so that bosses do not give so much money
- Tested with sample code, works as described
1. Ensure looting money still works as intended
2. Use hook to modify money amount
- Please note that players will see the original money amount in the loot window, but the "You loot..." notification will show the correct amount, similar to when looting money in a group. This is intended behavior because any alternative would be very disruptive to implement. …
=> feat(Core): OnBeforeLootMoney hook

data/sql/updates/pending_db_world/rev_1661690424898681400.sql
The critters should not be attackable.
Lady and Cleo should spawn under Alliance control.
Spike and Underfoot should spawn under Horde control.
Fixes #11995
- Closes #11995
- Closes https://github.com/chromiecraft/chromiecraft/issues/671
Queue Arathi Basin as Alliance.
Cap Blackmsith as Alliance.
Wait for Cleo and Lady to spawn. (They only spawn when BS is controlled by Alliance)
Attack Cleo and Lady. …
=> fix(DB/Creatures): Arathi Basin Rare Critters:

data/sql/updates/pending_db_world/rev_1660200016038134112.sql, src/server/scripts/Northrend/Naxxramas/instance_naxxramas.cpp
This fixes overlapping portals inside and outside Naxxramas. Their
rotation is also corrected (from CCW to CW). The post-boss
Naxxramas portals now teleport to the blue hub portal and it activates only
when all wings are cleared. This requirement can be bypassed with the
orbs, which are now correctly
casting their respective sapphiron entry/exit spells in addition to having the
correct position.
-  Remove duplicate green portal objects outside Naxxramas in Dragonblight
-  Remove duplicate green portal object inside Naxxramas
- Change animation of portals outside Naxx from CCW to CW
- Fix post-boss and Sapphiron entry/exit teleport spells  to the correct positions
- Fix position of the Orbs of Naxxramas
- Add allwingscleared requirement to the naxx hub portal
- Fix position of the hub …
=> fix(CORE/Naxxramas): Portals and Teleports

data/sql/updates/pending_db_world/rev_1661717784573839588.sql, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/blackrock_spire.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_gyth.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_rend_blackhand.cpp, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp
Using seal of ascension during the arena event  does not start event
Seal of ascension does not give chromatic protection buffs
-  Add missing event 
- Add chromatic protection proc
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9069
https://youtu.be/E3i998lGwYM?t=34 
- Matched recordings of the event with the source video to get timing correct
See "Expected Blizzlike Behaviour" details in issue https://github.com/azerothcore/azerothcore-wotlk/issues/9069
2 clients may be useful, 1 that starts the event with the ring and 1 with GM mode on to observe.
Start arena event 
.go c 137967
start Gyth and Rend event
.cheat cooldown
.additem 12344
Observe Vael event matches https://youtu.be/E3i998lGwYM?t=34
Ring can only be used once per encounter.
Ring cannot be used outside Rend …
=> fix(Scripts/UpperBlackrockSpire): Missing Seal of Ascension event

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_ouro.cpp
-  Reduce player damage requirement for loot. We need to do it each time it spawns or the players won't get loot in multiple phase fights.
- Closes -
- Not tested.
1. Go to Ouro and make it submerge multiple times with different amount of hp.
2. It should give loot when you kill it.
=> fix(Core/TempleOfAhnQiraj): Reduce player damage req for Ouro

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_fankriss.cpp
-  Increase its aggro range by 80.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13138
- Closes https://github.com/chromiecraft/chromiecraft/issues/4090
- Not tested.
1. Go to Fankriss, you should enter combat with it immediately after entering its room.
=> fix(Core/TempleOfAhnQiraj): Fankriss pull range

data/sql/updates/pending_db_world/rev_1664206413363828800.sql
-  Updates detection ranges from those observed in retail
-  
Retail
- 
1. `.tele AQ20`
2. see if the the affected creatures are pulled from a larger distance …
=> fix(DB/creature_template): Update AQ20 detection ranges

data/sql/updates/pending_db_world/rev_1664125356048989800.sql
-  Imports Values from Vmangos
-  Forces at least 1 item drop and 1-2 scroll drops
- Closes https://github.com/chromiecraft/chromiecraft/issues/4084
- Closes https://github.com/chromiecraft/chromiecraft/issues/4023
Vmangos
-  Tested ingame
1. `.additem 23162 4`
2. `.additem 21509 100` or/and 21510, 21511, 21512, 21513
3. see that one item and at least one scroll always drops …
=> fix(DB/item_loot): Ahn'Qiraj War Effort Supplies loot

data/sql/updates/pending_db_world/rev_1663868044866882500.sql
-  Remove quest item Broken Tears from creature loot table
-  It should only be get from Tears of Theradras
See comments from https://www.wowhead.com/wotlk/item=6083/broken-tears#comments
- No longer drops
1. Ensure item no longer drops from NPCs …
=> fix(DB/creature_loot_template): Broken Tears should not drop from NPCs

src/server/game/Spells/Auras/SpellAuras.cpp, src/server/game/Spells/SpellInfoCorrections.cpp
-  Fixes Shadowform Dispel issue.
- Closes 
- Windows 11 \ Visual Studio 2022
- Build and Tested in game
1. Priest used shadowform.
2. Priest used dispersion.
3. used any mount while dispersion is active.
4. Priest removes Shadowform while dispersion is active.
5. Remove Mount while dispersion is active.
or
1. Priest used shadowform.
2. Priest used dispersion.
3. Priest removes Shadowform while dispersion is active. …
=> fix (Core/Spell): Shadowform Dispel

src/server/game/Spells/Spell.cpp
Purpose of a a surpressed Log_info\warning\debug line is to simply unsurpress it incase you need logging for debugging reasons. This corrects the FMT and the TC_LOG_ERROR to LOG_ERROR.
-  Fixes commit out TC_LOG_INFO to LOG_INFO
-  Remove excess // line
- Closes None Reported
- Build
- Runs
1. Removing the // does give appropiate logging in the .log and console based on log world console conf settings.
2. start server
3. perform blink and observer messages …
=> fix (core): LOG correction

src/server/game/Spells/SpellEffects.cpp
Guardians summoned by engineering and items have incorrect scaling. This will fix Guardians summoned by Engineering items some Guardians summoned by items to have appropriate level and stats.
As of now, `Guardian::InitStats` in `Creature/TemporarySummon.cpp +391` sets Stats based on the summoner level. This is not always correct as it allows lower-level guardians to scale to max-level content. For instance Timberling in #12446 when summoned by a lvl80 Player scales to lvl80 with lvl80 stats.
There is a fix in place for Engineering items to set the level to `skill/5`. Also for Dragon's Call the summoned guardian is set to lvl55. However this does not change the stats as they are scaled to Player level. So a lvl55 dragon summoned by a lvl80 is much stronger than a lvl55 summoned by a lvl55 …
=> fix(CORE/Spells): Fix Scaling of some Guardians

data/sql/updates/pending_db_world/rev_1664637924608497900.sql
-  Adds 1000 resistance to each school
Vmangos
- Query runs
- 
1. .go c id 15339
2.
3. …
=> fix(DB/creature_template): Fix Ossirian's resistances accidentally removed.

data/sql/updates/pending_db_world/rev_1664444955521407200.sql
WOTLK quest rate corrections continued
-  ITEM Lynx Collar (20797) should be 100% drop rate off NPCs Springpaw Cub (15366), Springpaw Lynx (15372) for QUEST Unfortunate Measures (8326)
-  ITEM Arcane Silver (20482) "0.6777893639207508" over 959 repetitions rounded to 2/3rds (70% is also in likely margin of error, but 66.67% is closer to seen and given as second opinion so it will be the standard I go by) drop rate off NPCs Mana Wyrm (15274), Feral Tender (15294), Arcane Wraith (15273), Tainted Arcane Wraith (15298) for QUEST A Fistful of Silvers (8336)
(For those of you who care about numbers and how this is derived, I use the margin of error/sampling error formula to determine how much effort I need to put into a given issue, and using that you can derive there is a 99.99% chance that it …
=> fix(DB/creature_loot_template): Sunstrider Isle Quest Rate Fixes

data/sql/updates/pending_db_world/rev_1664495426800201100.sql
-  Removes incorrect loot
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13152
https://github.com/azerothcore/azerothcore-wotlk/issues/13152
- SQL runs, item removed from DB
1. Ensure incorrect item no longer drops
2. Ensure item still drops from correct mob …
=> fix(DB/creature_loot_template): Branch of Cenarius should not drop from Prince Raze

src/common/Utilities/EventMap.cpp, src/common/Utilities/EventMap.h, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_huhuran.cpp
-  Added support to EventMap::Repeat for allowing 2 parameters of std::chrono.
-  Fixed timers according to sniffs
-  Cancel Frenzy event on enrage.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13092
- Not tested.
1. Go to huhuran and check the timers.
=> fix(Core/TempleOfAhnQiraj): Huhuran timers + EventMap::Repeat

data/sql/updates/pending_db_world/rev_1664728395247854700.sql
Fixes #13084
- Closes #13084
- Closes https://github.com/chromiecraft/chromiecraft/issues/4104
`.go c 144601`
activate crystal
attempt to heal player on opposite side of activated crystal …
=> fix(DB/Disables): Ossirian Crystals should not block LoS.

data/sql/updates/pending_db_world/rev_1665166481073025800.sql
-  Increases detection ranges for AQ40 creatures
Retail
1. See if the creatures now pull at ranges higher than 20y …
=> fix(DB/creature_template): Update AQ40 detection ranges

data/sql/updates/pending_db_world/rev_1665047704458371200.sql
-  Grimscale Murloc Head (21757) and Captain Kelisendra's Cargo (21771) set to 45% drop rate as experienced over 1144 iterations   
Packets/farmed
- I checked the entries in the db 
1.  on a horde character
2. .quest add 8886 
3. .quest add 8884 
4. kill and experience the new lower drop rate
Part 3/3 for now in this area, meaning, left undone:
- The murlocs will occasionally (rarely) do a group fear event, and also when on Mmmrrrggglll's quest on his death will do a very large one  (this one i can prolly do threw SAI somehow???)
- Two Gameobjects Tattered Chest at a time one on each side of the Shore/Strand, but there is a third long spawn that is rarely up (Gameobject Tattered Chest need researched more)
- General mob placement needs addressed but that's beyond the scope of what I …
=> fix(db/creature_loot_template): Item 21757 and 21771 rate corrections

data/sql/updates/pending_db_world/rev_1664929532434519400.sql
-  Shortens Mmmrrrggglll's spawn timer
-  Gives Grimscale NPCs proper (multiple) ids
Sniff/Research
- Checked locally
1. .tele Tranquilshore and look at the area, and see how they respawn as different types with melee bias.
- Spawn points in general might need checked, functionality wise it works
- At least one more PR is coming related to this area, maybe two if I can figure out the SAI needed …
=> fix(DB/creature): Grimscale Murloc improvements in Eversong Woods

src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/instance_molten_core.cpp
Fixes #12905
- Closes #12905
- Closes https://github.com/chromiecraft/chromiecraft/issues/4017
- Not tested.
`.go creature 3328`
jump through window
group with second character
set loot to Free for all
on one char kill all bosses and majordomo's minions
`.summon` [player2]
[player2] can loot Cache of the Firelord
[Player2] leave instance before countdown …
=> fix(Scripts/MoltenCore): Added loot recipient to Cache of the Firelord.

src/server/apps/authserver/Server/AuthSession.cpp, src/server/database/Database/QueryResult.h, src/server/shared/Realms/RealmList.cpp
- Add support range loop for `ResultSet` and `PreparedResultSet`
- https://github.com/WarheadCore/WarheadBand/commit/ea5f2b1538cc39d551a4fadc8ce9f8fa04c37b37
```cpp
auto result = WorldDatabase.Query("SELECT racemask, classmask, Spell FROM playercreateinfo_spell_custom");
for (auto const& fields : *result)
{
uint32 raceMask = fields[0].Get<uint32>();
uint32 classMask = fields[1].Get<uint32>();
uint32 spellId = fields[2].Get<uint32>();
// ...
}
````
=> feat(Core/DB): add support range loop for mysql result

data/sql/updates/pending_db_world/rev_1664322385002360300.sql
Despite the definitive title, its only two drops that were wrong :)
Replenishing the Healing Crystals (9280 Draenei Version) (DROP QUEST)
Vial of Moth Blood (item 22889): 100% rate
and
What Must Be Done... (9293) (DROP QUEST) 
Lasher Sample (item 16517): 100% rate
https://www.youtube.com/watch?v=M1_2pCRUr2M 
-  Tested locally
1. create a new draenei char, and add quests 9280 and 9293 to your log, they should now drop 100% of the time from the nearby related mobs. …
=> fix(DB/creature_loot):  Corrects all incorrect quest rates in Ammen Vale

data/sql/updates/db_characters/Homebind_Orientation.sql, src/server/database/Database/Implementation/CharacterDatabase.cpp, src/server/game/DungeonFinding/LFGScripts.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Entities/Player/PlayerUpdates.cpp, src/server/game/Handlers/CharacterHandler.cpp, src/server/game/Handlers/MiscHandler.cpp, src/server/game/Handlers/MovementHandler.cpp, src/server/game/Maps/Map.cpp, src/server/game/Spells/Spell.cpp, src/server/scripts/Commands/cs_misc.cpp, src/server/scripts/Commands/cs_tele.cpp, src/server/scripts/Northrend/VaultOfArchavon/instance_vault_of_archavon.cpp
-  Adds Orientation Collumn for Character_Hombind in the Character DB
-  Supports Orientation save and load for  hearthstone use and homebind use
- Exisiting Orientation is set to zero for homebinds without a orientation set so exsisting homebinds are not messed with.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13386
- Closes https://github.com/chromiecraft/chromiecraft/issues/4094
- builds
- self tested but don't take my word for it
1. do a .cheat cooldown so you wont rage with the cool down
2. homebind while facing some weird direction so you dont think its a fluke
3. go somewhere and face a different way then what you were when you binded your hearthstone.
4. use hearthstone
5. observe orientation was as it was when you set the homehind …
=> Add (core\db): Support for Homebind Orientation

data/sql/updates/pending_db_world/rev_1657762683954396900.sql, src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp
-  The hardcore code is removed from the gossip and replaced with the database code.
-  Some broadcast_text, from the intro, are updated.
- Closes
- Windows 10
- In-game
1. .tele IcecrownCitadelRaid
2. The first broadcast_text, belong to the dialogues at the entrance of the instance, after you kill the first adds of the ladder (in the alliance). In the horde, I had no problems.
3. The `gossip` and the `npc_text`, belong to the npc, which start the 4 boss event.
The script does not fix the problem currently found in the event. It only adds the functionality of being able to read the gossip from the database and add some missing broadcast_text.
--- …
=> fix(Scripts/ICC): gossip in boss Deathbringer Saurfang

data/sql/updates/pending_db_world/rev_1665712907402997300.sql
-  Add IGNORE_ASSISTANCE_CALL to Anubisath Sentinel
-  And remove that flag from creatures that are not supposed to have it.
- Closes 
Retail
- 
1. Go to Zul'Gurub, pull the trash pack in front of Jin'do without pulling Jin'do himself
2. `.go xyz -7455.238281 -893.764771 465.217041 469 5.961959` Attack the warlock, see if Wyrmtalons are pulled
3. Go to AQ40, at the second pack of Anubisath Sentinels, pull an Obsidian Eradicator while it is pathing nearby the Anubisath and see if they assist.
4. Pull the Anubisath Sentinel pack to see if they are still linked …
=> fix(DB/creature_template): Add IGNORE_ASSISTANCE_CALL to Anubisath Sentinel

src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
-  Removes triggered spell argument
- Closes 
- 
1. Teleport to Obsidian Nullifier with a class that has mana
2. `.cheat power`
3. Wait until it casts Nullify. See if it consumes its mana …
=> fix(Scripts/TempleOfAhnQiraj): Make Nullify consume mana

data/sql/updates/pending_db_world/rev_1664655909869728000.sql
-  Modifies DamMod for all Dragons of Nightmare, their adds and Azuregos
-  Lowers the bosses' damage across the board, and increases add damage
- 
1. Engage the bosses Ysondre, Lethon, Emeriss, Taerar, Azuregos
2.  Engage the creatures Demented Druid Spirit, Shade of Taerar …
=> fix(DB/creature_template): Import Vmangos values for Dragons of Nightmare and Azuregos

src/server/scripts/Commands/cs_reset.cpp
-  In file src\server\scripts\Commands\cs_reset.cpp in method HandleResetTalentsCommand:
- Change constant AT_LOGIN_NONE to AT_LOGIN_RESET_TALENTS
- Closes Issue 13325 https://github.com/azerothcore/azerothcore-wotlk/issues/13325#issue-1398587152
None.  Observed behavior.
- Does it build without errors? Yes
- Did you test in-game? Yes
- What did you test? After the fix, logging in the character causes talents to be reset and a notification "Your talents have been reset"
- On which OS did you test?  Windows 10
- Describe any other tests performed  I checked the database after issuing the command, and observed that the at_login flag of the player was changed to 20 which is the expected value.
1. At server console, type reset talents player, for an offline player (with learned talents.)
2. …
=> Fix(core/scripts): issue 13325 - reset talents command

src/server/game/Entities/Player/PlayerSettings.cpp
-  Fix PlayerSettingVectors returning garbage values when requesting an existing source with a non-existing index
- Tested in-game, works
1. Call GetPlayerSetting for any source with a low index on a new character to create the vector
2. Call GetPlayerSetting a second time with the same source and a higher index
3. Ensure returned value is 0 …
=> fix(Core): Fix PlayerSettingVectors

data/sql/updates/pending_db_world/rev_1665525266543513900.sql
-  Removes skinning loot from Giant Buzzard in Badlands (currently skins for Heavy Leather)
No history of skinning on WoWhead, and no other birds are skinnable.
- SQL runs, no longer skinnable
1. Ensure Giant Buzzard no longer skinnable …
=> fix(DB): Remove Skinning loot from Giant Buzzard

src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp
-  Fix text when capturing an alterac valley mine which was the wrong way
-  #13374 
- Before fix (Reproducing bug) : 
.debug bg
queue AV
capture irondeep mine
--> The text is in the incorrect way
- After fix (Testing fix) : 
.debug bg
queue AV
capture irondeep mine
--> The text is now in the correct way
1. .debug bg
2. queue AV
3. capture irondeep mine …
=> fix(core):  Text when capturing an alterac valley mine is the wrong way around 

src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4227
- Drain Mana is still cast for both creatures
- 
1.
2.
3. …
=> fix(Scripts/TempleOfAhnQiraj): Use correct Ids for Drain Mana

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_twinemperors.cpp
-  Sets threat to 2000 from 200000
-  Seems like the parser is multiplying threat by x100?
- Closes 
Vmangos and https://youtu.be/gopCIIGZA98?t=53
Thanks @Plasmashield for providing the sources
- Tested ingame. 2k threat
- 
1.
2.
3.
**For …
=> fix(Scripts/TempleOfAhnQiraj): Correct post-teleport threat values for Twin Emperors

data/sql/updates/pending_db_world/rev_1665863988336160100.sql, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_skeram.cpp
-  Remove instance bind flag_extra and force bind on death.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13417
- Closes https://github.com/chromiecraft/chromiecraft/issues/4214
- Not tested.
1. Go to skeram and kill copies, they shouldn't give raid cd unless you kill the original one.
=> fix(Scripts/TempleOfAhnQiraj): Skeram copies shouldn't save raid cd

docker-compose.yml, src/server/database/Updater/DBUpdater.cpp
-  Implement AC_DISABLE_INTERACTIVE that allow us to skip the question when the db doesn't exit
It can be useful for other purposes
- Closes 
- 
- 
1.
2.
3. …
=> feat(CORE): implemented AC_DISABLE_INTERACTIVE for DBUpdater

data/sql/updates/pending_db_world/frostmane_alliance_grave_fix.sql
- Corrects Graveyard for alliance in Frostmane Hold.
-  Adds new graveyard zone for Iceflow Lake due to resurrecting at Iceflow Lake sent you to another spot if Alliance
- Closes https://github.com/chromiecraft/chromiecraft/issues/4041
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13391
- builds
- tested
1. Be alliance character
2. .go xyz -5625.04 625.59 386.24 0 0
3. die in combat or .die your character
4. observe alliance character is now in proper grave yard
5. revive and observe you are still in proper grave yard. …
=> Fix (db): Graveyard Frostmane Hold Alliance

apps/docker/Dockerfile, env/docker/etc/authserver.conf.dockerdist, env/docker/etc/dbimport.conf.dockerdist, env/docker/etc/worldserver.conf.dockerdist, mysql_ac.conf, src/common/Utilities/StringFormat.cpp, src/common/Utilities/StringFormat.h, src/server/apps/authserver/authserver.conf.dist, src/server/apps/worldserver/worldserver.conf.dist, src/server/database/Updater/DBUpdater.cpp, src/tools/dbimport/dbimport.conf.dist
-  This new approach uses the defaults-extra-file strategy mysql argument to provide a password through a config file that is created by the server on the fly
- Implemented the TempDir config that can be used to store temporary files (including the generated mysql conf)
Related: https://github.com/azerothcore/azerothcore-wotlk/pull/13404
- Running on a linux and windows environment. No errors
1. Run the worldserver preferably on a new database 
2. check if you have any error
=> fix(CORE): another attempt to fix the dbimport command line warning

src/server/scripts/Kalimdor/TempleOfAhnQiraj/temple_of_ahnqiraj.cpp
-  Changes spell from 25699 to 25698
- Closes https://github.com/chromiecraft/chromiecraft/issues/4278
- 
1. `.go c id 15277`
2. `.damage 475000`
3. If it enrages, try another or reset
4. If Explode is cast, see if it casts Explode 25699 **after** the aura fades …
=> fix(Scripts/TempleOfAhnQiraj): Correct Anubisath Defender Explode spell ID

src/server/game/Entities/Unit/Unit.cpp
Fixes #13431
- Closes #13431
- Closes https://github.com/chromiecraft/chromiecraft/issues/4226
More info [here](#13431) …
=> fix(Core/Spells): Deep Wounds can proc off from non-physical spells.

src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp
-  Removes triggered argument
-  
- Closes 
- 
1. `.aura 10308` on boss, see if Whirlwind is applied anyways …
=> fix(Scripts/TempleOfAhnQiraj): Prevent Sartura from casting Whirlwind while stunned

src/server/scripts/World/npcs_special.cpp
`Creature->Yell()` expects the raw broadcast_text id and does not work with texts assigned in `creature_text`.
Using `creature->AI()->Talk()` instead of  `Creature->Yell()` works.
Fix world server error and announcements in game.
- followup fix for https://github.com/azerothcore/azerothcore-wotlk/commit/28d1913276d4eab4eaf724d0a953e5c0d6906c66
- tested 
1. go to booty bay
2. check announcements of Riggle Bassbait during STV
(manually start event using `.event start 62` and `.event start 90`) …
=> fix(Core/Event): STV Riggle Bassbait broadcast text ids

data/sql/updates/pending_db_world/rev_1666648043812780000.sql, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_sartura.cpp
-  Moves mechanic from .cpp to DB
-  Makes use of flag GROUP_AI_FLAG_DONT_RESPAWN_LEADER_ON_EVADE implemented by Nyeriah
- Closes 
- Tested ingame by killing 2 of 3 adds then resetting. Killing all adds and resetting, killing the boss and resetting, killing 2/3 adds, moving far away and resetting and waiting for the corpses to despawn and then resetting.
- 
1. .go c id 15516
2. Kill a couple of the adds, move boss away from them (>200y) and then .combatstop OR wait for the corpses to despawn and then .combatstop
3. See if adds reset …
=> fix(Scripts/TempleOfAhnQiraj): Make sure Sartura adds respawn on evade

data/sql/updates/pending_db_world/rev_1666457333873760600.sql
Fixes #13345
- Closes #13345
- Closes https://github.com/chromiecraft/chromiecraft/issues/3770
- Not tested.
`.aura 64349` (Fiery Payback) on target
`.mod hp 1000000000` `.damage 800000000` on target
`.additem 5551` or any other .lookup item fast test on self
Attack the target that is below <35% HP
See how often Fiery Payback procs. Remember that diminishing effects still apply. …
=> fix(DB/Spells): Fiery Payback should have 1min internal cooldown.

src/server/game/Quests/QuestDef.cpp
Fixes #3503
- Closes #3503
Set `Quests.IgnoreAutoAccept=1` in worldconfig
Clear `Cache` folder inside WoW directory
Create human char
Accept the quest from the nearby NPC …
=> fix(Core/Quest): Fixed implementation of `CONFIG_QUEST_IGNORE_AUTO_ACCEPT` and `CONFIG_QUEST_IGNORE_AUTO_COMPLETE` configs.

data/sql/updates/pending_db_world/rev_1666530994967113600.sql
Fixes #13510
- Closes #13510
- Closes https://github.com/chromiecraft/chromiecraft/issues/4284
- Not tested.
try `.go c id 15353`
`.tele ironforge`
`.go xyz -4921 -978 502` …
=> fix(DB/WorldEvents): Added missing spawn of Katrina Shimmerstar.

src/server/game/Entities/Pet/Pet.cpp
Fixes #13497
- Closes #13497
- Closes https://github.com/chromiecraft/chromiecraft/issues/4279
.go c id 521
tame the mob, attack another player mob, the tamed mob's auto-attacks deal pgysical damage …
=> fix(Core/Pets): Tamed hunter pets should deal physical damage.

data/sql/updates/pending_db_world/rev_1666513208047763600.sql
Fixes #12832
- Closes #12832
- Closes https://github.com/chromiecraft/chromiecraft/issues/3269
`.learn 11605` `.cheat cooldown` `.cheat power`
`.aura 46916`
Cast Slam and see the buff being consumed …
=> fix(DB/Spells): Bloodsurge vs Slam.

src/server/game/Entities/Unit/Unit.cpp, src/server/scripts/Spells/spell_rogue.cpp, src/server/scripts/Spells/spell_warrior.cpp
e390087.
Improved 252755415c87
Parially reverted 252755415c87.
More info [here](#13369) and [here](#13368) …
=> fix(Core/Units): Fixed uninitialized `m_cleanDamage` variable after e390087

data/sql/updates/pending_db_world/rev_1667430602678974600.sql
Additional fix for #13493.
Booty Bay Innkeeper Skindle is a rest area for both factions.
- See next section
1. .go xyz -14457.700195 495.347992 15.212900
2. Test with characters from both factions …
=> fix(DB/areatrigger_tavern) Fix neutral rest area in Booty Bay

data/sql/updates/pending_db_world/rev_1667492399768442000.sql
-  Decreases spawn timer to 120 seconds
-  with despawn time, this brings the respawn time to between 2:30 and 3:00 mins as expected
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13677
- Closes https://github.com/chromiecraft/chromiecraft/issues/4364
-
- killed Lisaile Fireweaver and looted
- killed Lisaile Fireweaver and not looted 
1.  .go cr 84701
2.  kill Lisaile Fireweaver
3. …
=> fix(DB/creature) Lisaile Fireweaver

data/sql/updates/pending_db_world/rev_1667681347229290600.sql
-  
-  
- Closes 
Retail and Wowhead trash guides
1.
2.
3.
=> fix(DB/SAI): Change Qiraji Mindslayer Mana Burn cast to ON_DEATH instead of UPDATE_IC

data/sql/updates/pending_db_world/rev_1667666190202265500.sql
-  fixes a bunch of quest interactables that shouldnt dissapear on looting
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13588
- Closes https://github.com/chromiecraft/chromiecraft/issues/4336
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13672
- Closes https://github.com/chromiecraft/chromiecraft/issues/4387
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13667
- Closes https://github.com/chromiecraft/chromiecraft/issues/4384
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13621
- Closes https://github.com/chromiecraft/chromiecraft/issues/4354
- used gm commandts to test on my local
- 
1. 
.quest add 9376
.go xyz -870 4397 72
2.
.quest add 10877
.tele terok
.go xyz -3750.310059 4711.770020 -17.320499
3.
.quest …
=> fix(DB/gameobject): instant spawn on 61-64 quest interactables

src/server/game/Spells/SpellInfoCorrections.cpp
Digestive Acid still is not applied depending on player's position
-  
- Does not close https://github.com/azerothcore/azerothcore-wotlk/issues/13733
- Tested ingame. Using the .gps given in the issue still does not apply Digestive Acid.
1. .go c id 15727
2. .damage 3000000 to enter Phase 2
3. .aura 65961 on self
4. most of the time you'll get Digestive Acid debuff …
=> fix(Spells/TempleOfAhnQiraj): Attempt to partly fix Digestive Acid not being applied

src/server/game/Entities/Player/PlayerStorage.cpp
-  The existing rest bonus formula did not account for the client doubling the sent value, so it would always send double rest
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13164
- Tested that rest is gained at half the existing rate
1. Check my math is correct (hehe.)
2. Confirm that 24 hours of rest at 1x rate in a Tavern gives 3 bars of rested XP, not 6 (offline time can be edited in the DB to avoid waiting) …
=> fix(Core): Correct Rest Bonus Formula

data/sql/updates/pending_db_world/removeanim.sql
-  Changes Hellfire Imp to Remove Summon Visual on "in combat" rather than "on Aggro"
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13515
- Closes https://github.com/chromiecraft/chromiecraft/issues/4274
- run through on local
https://user-images.githubusercontent.com/11332559/200404162-473aebb7-0333-46a5-83f3-49985f092d0d.mp4
1. .tele bloodfurnace
2. enter combat with the three imps in the first room …
=> fix(DB/Creature): Hellfire Imp SmartAI

data/sql/updates/pending_db_world/rev_1667668503070084000.sql
-  Makes all venom bottles in zone start the quest
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13296
- Closes https://github.com/chromiecraft/chromiecraft/issues/4157
https://youtu.be/VXOvGDWYTYA?t=9
https://www.wowhead.com/wotlk/quest=2933/venom-bottles#comments
- teleported to bottles
- started and handed in quest
1. teleport to gameobjects in the range 142703 to 142714 …
=> fix(DB/gameobject): Venom bottle queststarter

data/sql/updates/pending_db_world/removeloot.sql
-  Remove Syndicate emblems from Battered Junkbox and Worn Junkbox
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11360
- Checked Kiera loot table after running SQL query
- opened a few boxes and no obvious issues, but low sample size
1. .setskill 633 300 300
2. .additem 16882
3. .additem 16883 …
=> fix(DB/Loot): Syndicate emblems in junkboxes

data/sql/updates/pending_db_world/rev_1668355497035231700.sql
Fixes #13567
- Closes #13567
- Closes https://github.com/chromiecraft/chromiecraft/issues/4318
- Not tested.
`.learn 63737`
`.learn 32546`
use Binding Heal on friendly target
check stacks of Serendipity …
=> fix(DB/Spell): Serendipity should proc off on cast rather than on hit.

src/server/scripts/Commands/cs_mmaps.cpp
Fixes this error when using `.mmap path` with server running on debug mode (maybe that's just a specific combination of MSVC version and Windows).
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\optional(359) : Asserti
on failed: Cannot access value of empty optional
``` …
=> fix(Scripts/Commands): Fix assertion error on mmaps path command

src/server/game/Entities/Pet/Pet.cpp
Fixes #13539
- Closes #13539
- Closes https://github.com/chromiecraft/chromiecraft/issues/4269
- Not tested.
Use a warlock.
Summon Felhunter pet.
Use spell lock on an low level creature and kill the creature instantly.
Summon your mount.
Dismount
See the spell is still on cooldown. …
=> fix(Core/Pets): Save all spell cooldowns to db.

data/sql/updates/pending_db_world/angermanagementcourse.sql
-  Sets Rage modifier to zero so they cant gain any
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3026
https://www.youtube.com/watch?v=X00FCqp3s_I&t=67s
- teleported to npc on local
1. go c 103 (wont aggro so downlevel to not insta kill / taunt) …
=> fix(DB/Creature): Garrick Padfoot Rage generation

data/sql/updates/pending_db_world/rev_1667348648920858600.sql
-  Updates on kill rep for several Venture Co. mobs in stv
-  Sets Venture Co. Lumberjack to not give rep after honored
- Closes [Venture Co. mobs in stv give too much reputation #13586 ](https://github.com/azerothcore/azerothcore-wotlk/issues/13586)
- Closes [Venture Co. mobs in stv give too much reputation #4324 ](https://github.com/chromiecraft/chromiecraft/issues/4324)
- killed mobs on local
- 
1. .go c id ( 675, 1096, 1097, 1094, 4260, 674, 676, 677, 1095, 4723)
2. kill them
3. note xp gain (account for human bonus) …
=> fix(DB/onkill_reputation) Venture Co. mobs in stv

src/common/Cryptography/OpenSSLCrypto.h, src/common/Threading/PCQueue.h
I noticed that compiling with gcc 12.1 fails.
-  remove `<T>`from a constructor
-  rename header guard because in conflicts with openssl header guard
-  compile with gcc 12
1. compile with gcc 12
I saw that in the openssl 3.0 PRs the header is also renamed. I was not sure if I should keep it in the PR or not. I kept it for now, because without it can not compile on gcc 12.
=> Fix compiling with gcc 12

src/server/game/AI/SmartScripts/SmartScript.cpp
-  Add an alive check for the SAI's owner in case no targets were found.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13827
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13855
1. .go xyz -445.000153 4747.521 19.9338989
2. Kill both Dreghood brute and then kill the Illidari
3. No crash.
=> fix(Core): Crash on random movement SAI

src/server/scripts/Spells/spell_mage.cpp
-  Add a nullcheck, this shouldn't happen but somehow it does.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13835
- 
- 
1.
2.
3. …
=> fix(Core/Scripts): Master of elements odd crash

data/sql/updates/pending_db_world/rev_1668750734814640600.sql
-  Modify the serverside spell effects to actually summon things.
-  Added proper SAI events for each phase (75,50,25).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13592
- Closes https://github.com/chromiecraft/chromiecraft/issues/4330
1. .go creature 68637
2. .damage 4000 (aprox 25% health)
3. Stun the target, damage further 75%
4. If stunned properly, it shouldn't spawn Shardlings.
=> fix(DB/SAI): Raging Colossus

data/sql/updates/pending_db_world/rev_1669553293045073800.sql
-  Add Arcane Explosion spell 
-  Adjust Drain Mana timer after retail research
- Remove mana regeneration
- Set mana to 0 on spawn (creature template current mana is completely ignored)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13926#issuecomment-1328169941
- 
1. pull mob as mana user
2. see drain mana
3. arcane boom
4. gg …
=> fix(DB/SAI): Marshfang Ripper AI

data/sql/updates/pending_db_world/rev_1670066795022662000.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4449
- 
1. .go c id 37072
2.
3. …
=> fix(DB/creature_template_addon): Add Emote state work to Rogg (37072)

data/sql/updates/pending_db_world/rev_1670029407665884500.sql
-  Changes 13 creatures onkill_rep
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14015
- 
1.
2.
3. …
=> fix(DB/creature_onkill_reputation): Correct reputation gains in Blood Furnace Normal Mode

data/sql/updates/pending_db_world/rev_1670023913457530500.sql
-  Increase to 35 from 20
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13983
Very common value for large creatures, and visible in the video sources provided
- 
.tele underbog
.go xyz 280.749817 -169.079193 36.874214 …
=> fix(DB/creature_template): Increase detection_range of Underbog Lord

data/sql/updates/pending_db_world/rev_1670021706396094700.sql
-  Remove Mana regeneration
-  Cast 'Nether Shock' when at 25-100% mana
-  Remove mana on reset (curmana is useless)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13922
- 
1. .go c id 18131 with a mana user
2.
3. …
=> fix(DB/SAI): Marshfang Slicer (18131)

data/sql/updates/pending_db_world/rev_1669589041819811900.sql
-  Set 100% chance to Fenclaw Thrashers' loot.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13921
-  Executed the query, no issues. No further tests needed.
1. .quest add 9834
2. .go c 65442
3. Kill the npcs, you should always get 1 item.
=> fix(DB/Loot): Fenclaw Hide

data/sql/updates/pending_db_world/rev_1669590774563293200.sql
-  Add 11025 as prerequisite.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13949
1. . go c 91763
2. It shouldn't give any quests.
3. .quest add 11025
4. .quest complete 11025
5. .quest reward 11025
6. And now Torkus should give you the quest 11030 (Our Boy Wants To Be A Skyguard Ranger)
=> fix(DB/Quest): Our Boy Wants To Be A Skyguard Ranger prerequisite

src/server/game/Loot/LootMgr.cpp, src/server/game/Loot/LootMgr.h
Fixes quest items distribution as described in this [issue](https://github.com/TrinityCore/TrinityCore/issues/22829). Problem applies to AC aswell.
Currently, quest items are seen by everyone, even in round robin or group mode. The first player who click on corpse get the item. This is frustrating for ranged players, and comes problematic for pickup groups (hello ninja looters).
The new rules are:
- in every mode, "non free for all" quest items are round robin
- if the round robin player can't loot quest item (he has not the quest or he has completed it), it will find the first available player in the group (can be changed to something else if someone got Blizz rules for this)
- "free for all" quest items won't change, everybody is able to see and loot it.
On a side effect, it will fix …
=> fix(Core/Loot): Fix quest items looting system

data/sql/updates/pending_db_world/rev_1669303320334648300.sql
-  Fix missing esES Kreldig ungor
- Close AC issue #13914 
https://github.com/azerothcore/azerothcore-wotlk/issues/13914
- Executed without errors, not tested
- 
1. .go c id 5638
2. Speak to NPC
- [Seems quest_greeting_locale only have one row in rusian so all languages miss those locales] …
=> fix(DB/QuestGreeting): Krelding Ungor missing locale

data/sql/updates/pending_db_world/wormbenotgone.sql
-  removes the despawn instant on reset and changes to 60 seconds to prevent spam.
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13144
- tested
-  …
=> fix(DB/Smartscript): Worms should not despawn instantly

data/sql/updates/pending_db_world/rev_1671225346039183900.sql
-  Title
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4517
- 
1.
2.
3. …
=> fix(DB/creature_onkill_rep): Add AQ40 missing onkill reputation gains

src/server/game/Entities/Creature/GossipDef.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Scripting/ScriptDefines/PlayerScript.cpp, src/server/game/Scripting/ScriptMgr.h
-  Fixes several issue with quest reward display:
- Shows correct money value received if player is at max level
- Respect MaxPlayerLevel config setting and ShouldBeRewardedWithMoneyInsteadOfExp Hook when determining XP and Money to display
- Add OnSetMaxLevel hook to be able to programmatically set max level client data value, used together with ShouldBeRewardedWithmoneyInsteadOfExp to ensure proper client display of money and XP
- Also closes https://github.com/ZhengPeiRu21/mod-individual-progression/issues/27
- Tested in game at Quest Details menu, Reward Quest menu, and Quest Log menu at not max level, max level set through Config at 60 and at 80, and with ShouldBeRewardedWithMoneyInsteadOfExp hook value on and off.
1. Look at above mentioned menus at various …
=> fix(Core): Correct Quest Details Display at Max Level

data/sql/updates/pending_db_world/rev_1669870365832502100.sql
-  Increases the drop rate chance of 2 recipes, lowers the drop rate chance of 1 recipe to match wowhead's* values
*I used Wowhead values to save time, I also as always sniffed the loot manually and got every item to drop, usually multiple times, but it would take me at least 10hours to come up with better numbers and their numbers seemed "pretty close enough" for this and our numbers seemed wildly inaccurate
- Untested but I don't see why it wouldn't work as is, its just a loot change and the SQL is written by HeidiSQL
- 
1.
2.
3.
**REMEMBER**: …
=> fix(DB/loot): Improve Mazthoril recipe drop rates

data/sql/updates/pending_db_world/lykulstinger.sql
-  Set correct maxstanding1
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4585
- tested
-  …
=> fix(DB/CreatureOnKillReputation): Lykul Stinger rep should stop at friendly

data/sql/updates/pending_db_world/rev_1671645973738924500.sql
-  Sets Super Mana Pot Recipe to 30m based on wowhead comments and Frost Power Potion to 10m based on testing
Testing for Frost power pot (variable timer)
The only source on the timer I could really get for this was comments on wowhead from 2010, as super mana potion recipe was changed in classic but intuitively this should not be 12hrs, not ever, but definitely not in wotlk.  Even at 30m in heavy population this will get pretty absurdly camped, at 12hr you get people camping the vendors on small servers >_>
=> fix(db/npc_vendor): Improve two Alch Recipe Timers (Super Mana Pot Recipe, Frost Power Potion Recipe)

data/sql/updates/pending_db_world/rev_1671639583415891400.sql
-  Changes timers from 12hr to 5/10m  
- Closes 
First timers pulled from classic wotlk PTR (note:  this, like all timers are not actually supposed to be static)
1. Should run fine (just a timer change) but https://www.wowhead.com/wotlk/npc=20916/xerintha-ravenoak is the NPC in question, just buy the items and wait
- More of these vendors exist, this is just important as a barrier for cooking for Horde side on CC so it's annoying (recipe is also available via quest)
=> fix(db/npc_vendor): Improve Xerintha Ravenoak vendor timers

data/sql/updates/pending_db_world/rev_1671218467178621900.sql
-  Removes Golden Pearl from Jaggal Clam
-  Removed Jaggal Clam from creature loot tables
- Closes https://github.com/chromiecraft/chromiecraft/issues/4556
- Closes https://github.com/chromiecraft/chromiecraft/issues/4554
- 
1. .cast 58160
2. check loot tables of creatures (21044, 21126, 21842); …
=> fix(DB/Loot): Jaggal Clam

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/ChatHandler.cpp, src/server/game/Handlers/MovementHandler.cpp
Fixes #11618
- Closes #11618
- Closes https://github.com/chromiecraft/chromiecraft/issues/3458
Use /dance to start dancing.
Use /say to speak.
Observe as the dancing animation does automatically resume afterwards.
**For …
=> fix(Core/Misc): Consider `/dance` as an emote state.

data/sql/updates/pending_db_world/rev_1671391096303779900.sql
-  Wasn't in the pool, and was also a duplicate, so no need to fix its position.
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4593
- 
- 
1.
2.
3. …
=> fix(DB/gameobject): Delete bad Nightmare Vine node

src/server/game/AI/CoreAI/PetAI.cpp
Fixes #14217
- Closes #14217
- Closes https://github.com/chromiecraft/chromiecraft/issues/4544
require 1 hunter with pet, one warrior with taunt and a third target.
hunters pet attacks third target, warrior taunts pets
**For …
=> fix(Core/Pets): Taunt should work on pets.

data/sql/updates/pending_db_world/rev_1671668610731654600.sql
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/4461
- 
- 
1.
2.
3. …
=> fix(DB/loot): Correct Primal Nether drop chance from normal dungeons

src/server/scripts/Outland/zone_zangarmarsh.cpp
-  
-  
- Closes 
- Used two characters to receive the boon separately, Bite didn't despawn
- 
1.
2.
3. …
=> fix(Scripts/Zangarmarsh): Naturalist Bite shouldn't desummon after casting Mark of Bite

src/server/game/Handlers/MiscHandler.cpp
-  Don't overflow the account_data array with type = 8. It can be caused by sending a malformed packet.
- Closes 
-  Tested.
=> fix(Core/Handlers): Crash

src/server/game/Groups/Group.cpp, src/server/game/Groups/Group.h
- Add `Group::GetGroupType()`
N/A
N/A
Compiled and ran on Windows 11, tested with Eluna …
=> feat(Core/Group): add GetGroupType()

data/sql/updates/pending_db_world/bouldermagic.sql
-  add smartscript to boulderfist mage and warrior
Based on MANGOS WOTLK 
- Tested …
=> fix(DB/SmartScript): Boulderfirst Mage / Warrior smartscript

data/sql/updates/pending_db_world/update.sql
Tested in live server with ~130 players
No negative script/side-effects found.
* Trigger attacking players - Fix trigger aggro (updates flags) …
=> fix(DB/HallsOfStone): Triggers in Tribunal of Ages

data/sql/updates/pending_db_world/rev_1670381120624981200.sql
ALL unique drops in Deathknell have been looked at. Improvements made based on a mix of available data and research.
-  Improves loot as followed:
-- Deathknell Zone Drops (DONE)
-- Night Web Matriarch should drop Webbed Cloak most of the time (~80%  Wowhead estimate, seems fair based off testing)
-- Night Web Crawlers should drop Webbed Pants (sniff 5/~410, wowhead estimate 1% based on robust error adjusted wowhead data
-- Putrid Wooden Hammer 3/369 off Rattlecage Skeleton, but 2% is in line with robust error adjusted wowhead data, leaving unchanged from AC
-- Deadman Cleaver off Daniel Ulfman (~3/300 sniff, wowhead 10/567 1.5% seems fair)
-- Deadman Dagger off Stephan Bartec (~7/300 sniff, wowhead 9/518 2% seems fair, leaving unchanged from AC)
-- 1 Deadman Blade off Samuel Flipps …
=> fix(DB/loot): Deathknell unique drops rate improvements

data/sql/updates/pending_db_world/rev_1672337646756506500.sql
-  Sets detection_rang~~o~~e = 0
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14306
Retail
- 
1.
2.
3. …
=> fix(DB/creature): Hellfire Channelers shouldn't be pulled by distance

data/sql/updates/pending_db_world/rev_1672337356285395000.sql
Authored-By: neifion-00000000 <91289495+neifion-00000000@users.noreply.github.com>
-  Correct speed of Auchenai Monks
-  
- Closes 
- 
- 
1.
2.
3. …
=> fix(DB/creature): Auchenai Monk speed

data/sql/updates/pending_db_world/rev_1672568748762669000.sql
Fixes #13996
- Closes #13996
`.go cr 138500`
Wait until Claw is enraged …
=> fix(DB/SAI): Swamplord Musel'ek should yell when Claw is enraged.

data/sql/updates/pending_db_world/rev_1672683380617865400.sql
-  Improves a few TBC Recipe Rates
-  (Uses this wotlk sourced rate for a previously touched recipe as well, since wotlk classic rates can not be trusted sadly)
- Research, unfortunately classic can not be used as a source for this (else all the timers would be 5/10 mins, and we'd actually need to edit some recipes to be BoP and unlimited) but general research concludes that no recipes were in the multi-hour respawn rate by wotlk and at least one TBC recipe was reported at 30mins respawn during the wotlk era.
- There might still be more recipes like this that need reported …
=> fix(DB/npc_vendor): Improve a few TBC Vendor Recipe Rates

data/sql/updates/pending_db_world/rev_1657261273976252267.sql
-  Added the script on SAI to morph the creatures to the model id 25749.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12094
https://wowwiki-archive.fandom.com/wiki/Enchanted_Tiki_Warrior
Youtube videos
- .go c id 28882
- Check no infernals are around
1. .go c id 28882
2. Check no infernals are around
Tests …
=> fix(DB/Creature): Force the correct modelid on spawn of Enchanted Tiki Warriors

src/server/scripts/Spells/spell_druid.cpp
Fixes #13829
- Closes #13829
- Closes https://github.com/chromiecraft/chromiecraft/issues/4072
- Not tested.
Take Omen of Clarity talent
Take Revitalize talent
Cast Rejuvenation/Wild Growth
Watch Clearcasting not procing on a hot tick
**For …
=> fix(Scripts/Spells): Omen of Clarity should not proc from Revitalize.

src/common/Collision/Maps/MapDefines.h, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Movement/MovementGenerators/PathGenerator.cpp, src/tools/mmaps_generator/TerrainBuilder.cpp
This reverts commit 66e6d331166b18c996cda6b58bca3131b524d4bc.
- Fix a lot of water creatures by reverting aforementioned PR, recast doesn't handle very well underwater terrain, above water terrain and water itself as connected, resulting in creatures using weird path or not be able to compute a path at all
- Check [TrinityCore PR](https://github.com/TrinityCore/TrinityCore/pull/28392) for more information
- Water creatures should follow you in a more straightforward way.
- Water creatures should continue to attack you even if you have waterwalk and/or are jumping in water (which was partially fixed by #12112, thanks to @UltraNix )
- Closes #13551
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6784
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12411
- …
=> fix(MMAP/core/PathGenerator): Try to fix more water creatures

src/server/apps/worldserver/worldserver.conf.dist, src/server/game/World/World.cpp
Reverts azerothcore/azerothcore-wotlk#14039
Causing corpses to despawn instantly: https://github.com/azerothcore/azerothcore-wotlk/issues/14325
=> Revert "fix(Core/Config): Set default corpse decay for normal creatures to 5 …"

data/sql/updates/pending_db_world/eots-maxdist.sql
-  this fixes the StartMaxDist to the appropiate size of 10 instead of default which will never flag the player for being outside the start spot before the bg starts (exploit) and there fore will never tele them back into place after 9 seconds.
-  
- Closes unreported EOTS StartMaxDist is incorrect and allows exploiters to be outside of the start spot without penalty.
- Builds
- Self Tested
1. Enter etos bg
2. teleport out of the start bubble before it begins
3. observe player being auto tele back after the 9 second count down …
=> fix (db): EOTS BG StartMaxDist

data/sql/updates/pending_db_world/rev_1672806531310531500.sql, src/server/game/Entities/Creature/CreatureGroups.cpp, src/server/game/Entities/Creature/CreatureGroups.h, src/server/game/Entities/Unit/Unit.cpp
-  Reverts https://github.com/azerothcore/azerothcore-wotlk/pull/13509
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14492
- 
1. `.go c id 15277`, see if only one is aggroed
2. `.tele BRD` `.GO XYZ 1379 -723 -92` see if aggroing a creature won't pull the entire room
3. …
=> revert "fix(Core/Formations): Implemented new creature formation flag: GROUP_AI_FLAG_ACQUIRE_NEW_TARGET_ON_EVADE."

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Spells/SpellInfoCorrections.cpp, src/server/scripts/Spells/spell_druid.cpp, src/server/scripts/Spells/spell_mage.cpp, src/server/scripts/Spells/spell_shaman.cpp, src/server/scripts/Spells/spell_warrior.cpp
Fixes #13330
- Closes #13330
- Closes https://github.com/chromiecraft/chromiecraft/issues/3905
- Closes https://github.com/chromiecraft/chromiecraft/issues/4072
- Not tested.
Ignite:
Get 2 characters, 1 of them mage
On the mage learn ignite and living bomb
.add 18970 2
.add 45737
Equip those rings
Learn the Glyph
Duel
Cast Living Bomb
Look at the combat status
Revitalize:
For the combat:
Same talents
Needs 3 chars
Cast Rejuv on friendly char and then attack hostile char with that one
Wait for the Revitalize proc and see if combat is prelong …
=> fix(Core/Spells): Ignite and Revitalize should not prelong combat.

src/server/game/Spells/Spell.cpp
Fixes #11888
- Closes #11888
- Not tested.
Do a non damaging (e.g cast Corruption) spell on a mob
notice it does tag on cast …
=> fix(Core/Spells): Every spell casted by player should tap the creature.

data/sql/updates/pending_db_world/rev_1672995772284756600.sql
-  Worn Stone Tokens are 100%
-  Encrusted Tail Fins should be 100% and only off Saltscale Murlocs
- Closes 
Sniffed/classic …
=> fix(DB/creature_loot): fix two quest rates in EK

src/server/game/Loot/LootMgr.cpp
An attempt to fix the master looter bug where he can see all quest items even if he doesn't have quest.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4757 …
=> fix(Core/Loot): Fix too many quest items visible by master looter

src/server/game/Entities/Player/PlayerGossip.cpp, src/server/game/Globals/ObjectMgr.h
fix GetQuestGreetingLocale typeIndex just like GetQuestGreeting
-  fix GetQuestGreetingLocale typeIndex just like GetQuestGreeting
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10913
- 
- 
1. login with zhCN Clients.
2. .go xyz  -9215.981  -2221.368  67.53985 3.77
3. See if the NPC(ID 344)'s quest greeting is Chinese. …
=> fix(Core/Gossip): quest_greeting_locale doesn't work #10913

src/server/game/Entities/Player/Player.cpp, src/server/game/Handlers/GroupHandler.cpp
-  Validate min, max values from MSG_RANDOM_ROLL before DoRandomRoll.
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14544
- Tested with WPS
1. Send a MSG_RANDOM_ROLL packet through a tool with a min value that's greater than max value. …
=> fix(Core/Packets): Fix a crash in MSG_RANDOM_ROLL.

src/server/game/Entities/Unit/Unit.cpp
Fixes #14216
- Closes #14216
- Closes https://github.com/chromiecraft/chromiecraft/issues/4545
`.learn 7302` Ice Armor
`.learn 69787` Ice Barrier
Apply Ice Armor.
Attack mobs with and without Ice Barrier …
=> fix(Core/Spells): Fixed applying some proc ex flags to melee attacks.

data/sql/updates/pending_db_world/skinning.sql
-  Create a new skinning loot entry with 80% chance (Knothide Leather) and 20% chance (Knothide Leather Scraps)
-  Create a new skinning loot entry with 100% chance (Knothide Leather)
-  Updated different mobs (see Source) with the right skinning loot percentage
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14486
https://github.com/azerothcore/azerothcore-wotlk/issues/14486
- I checked the updated values in the DB
1. learn Skinning
2. `.additem 7005` (skinning knife)
3. `.go c 74891`
4. Skin the creature …
=> fix(DB/skinning_loot_template): Create new skinning entries for different mobs in TBC

src/server/database/Database/MySQLConnection.cpp, src/server/database/Database/MySQLConnection.h
- Moves `m_Mysql` and `_HandleMySQLErrno` to `protected` in `MySQLConnection`
- Makes `_HandleMySQLErrno` virtual
This allows much more flexibility for child classes.
- Compiled and tested on Windows 11 …
=> feat(Core/Database): move MySQL handle and HandleMySQLErrno to protected

data/sql/updates/pending_db_world/rev_1673180342307668400.sql
Fixes #13820
- Closes #13820
`.go creature 138175`
engage npc …
=> fix(DB/SAI): Shadowmoon Summoner should not interrupt its spells.

data/sql/updates/pending_db_world/rev_1673609818458819900.sql
-  Increase respawn timer from 30m to 3hr
Tested on Wotlk Classic, confirmed an approximate 3hr timer with frequent visitation and npctime's / GUID derived server timestamps, and confirmed not a 30m timer the most manual hard way.  Sniffed over several packets. …
=> fix(DB/creature): Correct Mok'rash respawn timer

src/common/Utilities/Util.cpp, src/server/game/Battlegrounds/Zones/BattlegroundAV.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Spells/SpellEffects.cpp, src/server/game/Spells/SpellScript.cpp, src/server/scripts/Events/brewfest.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_argent_challenge.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp, src/server/scripts/Northrend/VaultOfArchavon/boss_archavon.cpp, src/server/scripts/Spells/spell_generic.cpp
Fix workflow error message:
```
azerothcore-wotlk/src/common/Utilities/Util.cpp:558:9: fatal error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
sprintf(buffer, "%02X", bytes[i]);
```
Long story short, Buffer Overflow exploiting is possible.
The best option, of course, is not to suppress but to transition. 
Considerations to take when dealing with what this exploit can do:
- What kind of buffer and where it resides: physical, logical, virtual memory?
- What data will remain when the buffer is freed or left around to LRU out?
- What strategy will be followed to ensure old buffers do not leak data …
=> fix (core): macos12 depreciation workflow error / security CWE-120

apps/docker/Dockerfile
When we create the dev image we do not have the .dockerdist file under the etc folder. The ac-dev-server included in the azerothcore-wotlk repository bind the /env/docker/etc folder inside the container, but the acore-docker repository doesn't. That's why we are having the error in that project. 
This happened after the latest changes:
* https://github.com/azerothcore/azerothcore-wotlk/pull/14707
* https://github.com/azerothcore/azerothcore-wotlk/pull/14747
Closes https://github.com/azerothcore/acore-docker/issues/12
=> fix(docker): missing config file in dev image

src/server/game/Globals/ObjectMgr.cpp
Thanks for the heads up, @trickerer. ❤️
- Adjusts some capitalization of logs.
- Swap out instances of `level 1` with `initial level` where applicable.
- Closes [commented issue](https://github.com/azerothcore/azerothcore-wotlk/commit/4e2270c935a362d2aade55e2b814bede0dd72bf6#r98118336).
N/A
- Untested.
1. Trigger the logs affected. …
=> chore(Core/ObjectMgr): Adjust a few comments/logs to reflect recent changes with stat handling.

data/sql/updates/pending_db_world/rev_1673692538921177900.sql
Fixes #14282
- Closes #14282
- Closes https://github.com/chromiecraft/chromiecraft/issues/4033
`.cheat cooldown`
`.learn 17364`
`.learn 51522`
`.mod mana 10000`
Spam with Stormstrike (while wielding both melee weapons) and see only one proc of Improved Stormstrike per cast. …
=> fix(DB/Spells): Improved Stormstrike should proc only once per cast.

src/server/game/Entities/Unit/Unit.cpp, src/server/game/Spells/Auras/SpellAuras.cpp, src/server/game/Spells/Auras/SpellAuras.h, src/server/game/Spells/SpellScript.cpp, src/server/game/Spells/SpellScript.h, src/server/scripts/Spells/spell_mage.cpp
Fixes #14377
- Closes #14377
- Closes https://github.com/chromiecraft/chromiecraft/issues/4682
**Setup for guarantee critical hit.**
`.cheat cooldown`
Get 10 stacks of [Combustion](https://wotlkdb.com/?spell=11129) for 100% crit.
`.unaura all`
.learn 44449`
.learn 29076`
`.mod mana 10000`
Cast Fireball (remember the cost mana)
After the spell hits, check your mana pool (or check combat log) …
=> fix(Core/Spells): Fixed Master of Elements not refunding mana.

CMakeLists.txt
-  Remove unnecessary regex check and use simple string replace instead
- The original code can cause errors depending on the absolute path to your source directory. This fixes that.
https://stackoverflow.com/questions/75045135/cmake-regex-replace-fails-to-compile
- Tested and working
1. Put your source directory in a subdirectory named C++, then try to generate. …
=> Fix module related cmake error

src/server/scripts/OutdoorPvP/OutdoorPvPHP.cpp
Progress bar shows the objective to be neutral but it still is horde/alliance controlled.
https://github.com/azerothcore/azerothcore-wotlk/issues/14300
Valdifer
-  Progress bar sync when slider is on neutral zone
-  
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14300
- Tested (Capped horde and turn back to neutral, not tested alliance side to normal and alliance to horde)
- 
1. .go xyz -450 3470 40 530
2. Cap it with Horde/Alliance
3. Change to opposite faction and move it to neutral …
=> fix(Core/OPvP): Hellfire PvP Objective Flag and Progress bar not in sync

data/sql/updates/pending_db_world/tower-althalaxx-ruru.sql
- Adds ruRU ObjectiveText1 and ObjectiveText2 to [The Tower of Althalaxx](https://www.wowhead.com/wotlk/quest=1140).
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14112.
Wrath Classic live sniffs.
- Untested.
2. Start the game with ruRU localization.
3. `.quest add 1140`
4. Observe Russian objective texts. …
=> fix(DB/quest_template_locale): Add ruRU ObjectiveText1/2 to The Tower of Althalaxx.

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Groups/Group.cpp
Fixes #12694
- Closes #12694
Create two characters, having one of them be able to cast heal spells really helps
Create a group with these characters
Cast heals on yourself on one of them and wait for the mana to naturally regenerate (level 1 makes this easy)
Check the mana value seen by the other player, it should be full …
=> fix(Core/Players): Fixed sending power regen update to nearby players.

src/server/database/Database/MySQLConnection.cpp
**This PR is not just meant as a change to the MySQL Query function for Premared Statements but mostly as a base for an open discussion about the change.**
@Nyeriah and I talked about this a bit but a change to functions associated with the Database should not be made unless it is certain that it will not cause any issues.
-  Correctly count the affected Rows on `UPDATE`, `DELETE` and `INSERT` queries using Prepared Statements
In #11958 I am using a `SELECT` Query to determine the amount of deserter debuffs with certain constraints in the Database, just to have feedback for the number of affected rows by the following `DELETE` Query.
I have tried to use a `DELETE` query only with the plain SQL query function as well as with the Prepared Statement query function. Sadly neither give …
=> feat(DB): MySQL PreparedStatement Affected Row Count

src/server/scripts/Outland/HellfireCitadel/MagtheridonsLair/boss_magtheridon.cpp
Fixed emotes.
Fixes #14721
- Closes #14721
- Closes https://github.com/chromiecraft/chromiecraft/issues/4814
Engage https://wotlkdb.com/?npc=17257
Kill all 5 https://wotlkdb.com/?npc=18829
Survive for 120 seconds and wait until Magtheridons aggro and start casting Quake. …
=> fix(Scripts/MagtheridonsLair): Fixed Blast Nova timers.

src/server/game/AI/SmartScripts/SmartScript.cpp, src/server/game/Entities/Unit/Unit.h, src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_nefarian.cpp, src/server/scripts/EasternKingdoms/Karazhan/boss_midnight.cpp, src/server/scripts/EasternKingdoms/MagistersTerrace/boss_felblood_kaelthas.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp, src/server/scripts/EasternKingdoms/SunwellPlateau/boss_muru.cpp, src/server/scripts/Events/brewfest.cpp, src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp, src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp, src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp, src/server/scripts/Northrend/Gundrak/boss_drakkari_colossus.cpp, src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp, src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp, src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp, src/server/scripts/Northrend/UtgardeKeep/UtgardeKeep/boss_keleseth.cpp, src/server/scripts/Northrend/VioletHold/boss_zuramat.cpp, src/server/scripts/Northrend/zone_dragonblight.cpp, src/server/scripts/Northrend/zone_storm_peaks.cpp, src/server/scripts/Outland/Auchindoun/ShadowLabyrinth/boss_grandmaster_vorpil.cpp, src/server/scripts/Outland/BlackTemple/illidari_council.cpp, src/server/scripts/Outland/CoilfangReservoir/SteamVault/boss_warlord_kalithresh.cpp, src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp, src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp, src/server/scripts/Pet/pet_generic.cpp, src/server/scripts/World/npcs_special.cpp
- 
Add Unit::KillSelf() function as overload of Unit::Kill(this) . Use KillSelf() whenever the killer and the victim are the same to clearly state the Unit is going to kill itself.
-  
- Closes 
- 
- 
1.
2.
3. …
=> feat(Core/Unit): Add KillSelf overload

src/server/game/Entities/Creature/TemporarySummon.cpp
-  Fix a null reference when trying to summon creatures.
- Closes #14805
-  No tests performed, no access to build server right now. …
=> fix(Core/SmartAI) Fix null reference when summoning.

data/sql/updates/pending_db_world/rev_1675021295162850400.sql
-  Link the broadcast_text IDs, so that the dialogs are displayed in different languages, since the translations are in the database, but are not assigned.
- Closes 
- Windows 10
- Inside the game
1. Apply the SQL, and perform the dungeon Pit of Saron
2. Depending on the game client, and if the dialogs are added (at least in Spanish they are), they should be displayed in different languages. …
=> (DB/creature_text) Adding missing BroadcastTextId in Pit of Saron

data/sql/updates/pending_db_world/rev_1675142910827405300.sql
-  Removes Heartswood drop from excavators
- https://github.com/azerothcore/azerothcore-wotlk/issues/14676
- https://github.com/chromiecraft/chromiecraft/issues/4819
https://www.wowhead.com/wotlk/item=6912/heartswood
- 
-
2. .go zonexy 31 31 412
3. .quest add 1738
4. Kill an excavator …
=> fix(DB) Heartswood drop

src/server/game/World/World.cpp
-  Based on how GuildReset and BGReset times are calculated
-  Makes sure the Calendar reset doesn't spam
- Closes 
- 
- 
1.
2.
3. …
=> fix(Core/Calendar): Correct calculation of reset time

src/server/game/Server/WorldSocket.cpp
Fixes #14790
- Closes #14790
Set `SocketTimeOutTime` and `SocketTimeOutTimeActive` to `60000` in `worldserver.conf`
Login with your username and password, but do not login into the game (stay at character selection screen)
Wait 1 minute until got disconnected …
=> fix(Core/Socket): `CMSG_WARDEN_DATA` should not reset idle connections.

data/sql/updates/pending_db_world/rev_1675503083908745800.sql
Fixes #14729
- Closes #14729
- Closes https://github.com/chromiecraft/chromiecraft/issues/4798
`.go c id 17626` …
=> fix(DB/SAI): Laughing Skull Legionnaire casts Sweeping Strikes.

src/server/game/Instances/InstanceScript.cpp, src/server/game/Scripting/ScriptDefines/GlobalScript.cpp, src/server/game/Scripting/ScriptMgr.h
Provides a hook which fires whenever a BossState is set.
-  New Hook
-  
- Closes 
```cpp
LOG_INFO("sql", "OnBeforeSetBossState: bossId = {}, newState = {}, oldState = {}, MapId = {}, InstanceId = {}", id, newState, oldState, instance->GetId(), instance->GetInstanceId());
```
```
OnBeforeSetBossState: bossId = 1, newState = 1, oldState = 0, MapId = 565, InstanceId = 2
OnBeforeSetBossState: bossId = 1, newState = 3, oldState = 1, MapId = 565, InstanceId = 2
```
1.
2.
3. …
=> feat(core/hook): add OnBeforeSetBossState

data/sql/updates/pending_db_world/rev_1675903993952928700.sql
changes Qiff's limited supply frequency
-  Changes timers on Qiff, to best reflect what I was able to datamine, see TODO at bottom  
- There is a high value exploit currently possible, see TODO for more info
Classic WotLK
- The correct functionality for this vendor (and prolly others like this) is as followed:
Every approximately hour a spawn group will spawn only if the vendor is empty of the spawned group
This spawned group will contain up to 6 items at their randomly selected quantities (1 to max)
There is different rarity levels of each item, and some items are quite rare while other ones seem to spawn every time.
In this PR I simply adjust the timers based on their frequency to throttle an exploit (also makes it hard for a single person to camp reasonably as the timer should drift …
=> improve(DB/npc_vendor): Address vendor exploit

data/sql/updates/pending_db_world/durnholde-immunity.sql
- Removes the bleed immunity mask from [Lieutenant Drake](https://www.wowhead.com/wotlk/npc=17848), [Captain Skarloc](https://www.wowhead.com/wotlk/npc=17862), and [Epoch Hunter](https://www.wowhead.com/wotlk/npc=18096), including their heroic variants.
- Closes https://github.com/chromiecraft/chromiecraft/issues/4944.
Original issue, as well as Wrath Classic.
- Tested in-game, works as observed on Wrath Classic.
1. `.tele oldhillsbrad`
2. `.quest add 10277`
3. `.quest reward 10277`
4. Enter the dungeon.
5. Try to cast a bleeding spell (such as [Rend](https://www.wowhead.com/wotlk/spell=47465)) on the three bosses. …
=> fix(DB/creature_template): Remove bleed immunity from Escape from Durnholde bosses.

data/sql/updates/pending_db_world/rev_1675649780091440100.sql
-  Adds aura 8876 to its normal and Heroic versions
-  
- Closes 
Sniffed
- 
- 
1.
2.
3. …
=> fix(DB/Creature): Add missing Thrash aura to Aeonus in Black Morass

data/sql/updates/pending_db_world/rev_1675207681546911800.sql
-  Casts Summon Sundered Shard on death
-  Says text "Sundered Rumbler shatters into shards."
- https://github.com/azerothcore/azerothcore-wotlk/issues/14818
- https://github.com/chromiecraft/chromiecraft/issues/4908
https://youtu.be/HX8haCDIVT0?t=165
- 
2. .go c 67708
3. .damage 50000 …
=> fix(DB/SmartScript) Sundered Rumblers wrong use of Summon Sundered Shard

src/server/game/AI/SmartScripts/SmartAI.cpp
-  Makes it so that minions dont sit idle if summoned during combat, set them in combat with their owner's victim if any
-  
- Closes 
- 
1.
2.
3. …
=> fix(Core/SAI): Set minions in combat with their master's victim

data/sql/updates/pending_db_world/rev_1676204879733696800.sql
- Adds 2 yell lines to Tempest-Forge Peacekeeper in The Botanica. Only played by a single GUID and around every 8-9 mins
- Closes 
- 
1.
2.
3. …
=> fix(DB/SAI): Add OOC lines to Tempest-Forge Peacekeeper

src/server/game/Entities/Player/Player.cpp
-  Adds the Summon Skeleton effect of Book of the Dead to unequip exceptions list
-  Allows player to unequip Book of the Dead and have the summoned skeleton remain for its duration
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11691
- Closes https://github.com/chromiecraft/chromiecraft/issues/3480
- Also fixes Ancient Cornerstone Grimoire
Additional source material in the above issue links.
https://www.wowhead.com/item=13353/book-of-the-dead#comments:id=239392
- Used active ability of Book of the Dead, swapped to a different offhand equip, confirmed summoned skeleton remained active.
1. Create/Select character level 58+
2. .additem 17067
3. Equip Book of the Dead, wait until active ability is ready
4. Use active ability
5. Swap to any other offhand item or otherwise …
=> fix(CORE/Player): Book of the Dead unequip fix

src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp
typo refactor changed it to 18s
-  
-  
- Closes 
https://github.com/azerothcore/azerothcore-wotlk/commit/afb071bb0491aa90a7219f445289759720515cac#diff-c79ff565ff7f99dfdc21843c4b04dafbc4aedad52ddfadb47492c732bb197e75L484
- 
- 
1.
2.
3.
**For …
=> fix(Scripts/MoltenCore): revert ragnaros submerge event to 180s

src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp
-  
-  
- Closes 
- 
- 
1.
2.
3.
=> fix(Scripts/Ulduar): Don't load encounter states as IN_PROGRESS

src/server/scripts/Outland/GruulsLair/boss_gruul.cpp
-  
-  
- Closes https://github.com/chromiecraft/chromiecraft/issues/5050
- 
- 
1.
2.
3. …
=> fix(Scripts/GruulsLair): Only players should deal aoe shatter damage

src/server/game/Handlers/MiscHandler.cpp, src/server/game/Handlers/TradeHandler.cpp, src/server/game/Server/Protocol/Opcodes.cpp, src/server/game/Server/Protocol/Opcodes.h, src/server/game/Server/WorldSession.cpp, src/server/game/Server/WorldSession.h
* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/dc68c2b269fdd401e2f0f6e1e372292b74c66bb8)
* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/9fc5c4bc41b2738836ce99eb42ddbb88fb398884)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/f1e6601032ba4077e1d1c6070c4cb20812289f7a)
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/aee4f0350ea5610b663cb07fb097f2fad256809e)
Funny that someone have cherry-picked 90% of these commits already, but forgot about the important things x)
- Implement m_playerRecentlyLogout & STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT
- make use of requeuePackets
* For client packets that can be send in loggined state or just after logout but assocualted with recently logout character add new …
=> feat(Core/PacketIO): Implement STATUS_LOGGEDIN_OR_RECENTLY_LOGGOUT

data/sql/updates/pending_db_world/rev_1676678339159333800.sql
-  Remove vendor inventory and vendor flag from child Andormu
- Closes #15015
- Closes https://github.com/chromiecraft/chromiecraft/issues/4978
- SQL runs without error, data in DB looks correct
**For …
=> fix(DB): Andormu should not sell ammunition

data/sql/updates/pending_db_world/rev_1676741293045096600.sql
-  Fixes being able to spawn The Stone Watcher several times
-  Fixes wrong creature queststarter
- Makes quest re-obtainable if Stone Watcher despawns
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11700
- Closes https://github.com/chromiecraft/chromiecraft/issues/3483
- 
1.
2.
3. …
=> fix(DB/Quest): The Stone Watcher

data/sql/updates/pending_db_world/rev_1677181094686770100.sql
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14345
in the issue
- tested
.go c id 4287 
pull a bunch of them
Notice they all add to the stacks …
=> fix(DB/spell_custom_attr): Crusader Strike now stacks from multiple sources
